// ===== park02 ESSAY =====

const newEssayData = [
  {
    "text": "4. Park Rules\nEvery park has rules to keep visitors safe and comfortable every day. People should follow these rules to protect nature and respect others. Good behavior helps everyone enjoy a clean and peaceful environment together.\n\nVisitors should throw trash into bins and never damage flowers or trees. Dogs should stay on leashes, and loud music should be avoided. People must use playground equipment safely and watch young children carefully always.\n\nPark rules make visits more enjoyable for everyone. When people follow simple rules, parks stay beautiful and clean for many years. Respecting nature and other visitors creates a friendly place for families and friends.",
    "vi": "4. Quy Tắc Trong Công Viên\nMỗi công viên đều có các quy tắc để giữ cho khách tham quan an toàn và thoải mái mỗi ngày. Mọi người nên tuân theo các quy tắc này để bảo vệ thiên nhiên và tôn trọng người khác. Hành vi tốt giúp mọi người cùng tận hưởng một môi trường sạch sẽ và yên bình.\n\nKhách tham quan nên bỏ rác vào thùng và không bao giờ làm hỏng hoa hoặc cây. Chó nên được giữ bằng dây dắt và nên tránh mở nhạc lớn. Mọi người phải sử dụng thiết bị sân chơi an toàn và luôn trông chừng trẻ nhỏ cẩn thận.\n\nCác quy tắc trong công viên làm cho những lần ghé thăm thú vị hơn với mọi người. Khi mọi người tuân theo những quy tắc đơn giản, công viên sẽ đẹp và sạch trong nhiều năm. Việc tôn trọng thiên nhiên và những khách tham quan khác tạo nên một nơi thân thiện cho gia đình và bạn bè."
  },
  {
    "text": "5. A Children's Playground\nA children's playground is a fun place inside many public parks today. It has swings, slides, climbing frames, and other exciting play equipment. Children laugh, play, and make new friends during every visit happily.\n\nParents watch their children while they enjoy different games together. Some children climb, run, jump, or play hide-and-seek with friends. Everyone shares the playground kindly and waits for their turn on the swings patiently.\n\nA playground helps children become active and confident. They learn teamwork, improve their balance, and enjoy healthy outdoor exercise. Keeping playground equipment clean and safe allows children to have fun every single day.",
    "vi": "5. Sân Chơi Trẻ Em\nSân chơi trẻ em là một nơi vui nhộn bên trong nhiều công viên công cộng ngày nay. Nơi đó có xích đu, cầu trượt, khung leo trèo và các thiết bị vui chơi thú vị khác. Trẻ em cười đùa, vui chơi và kết bạn mới trong mỗi lần ghé thăm.\n\nCha mẹ trông con trong khi các em cùng nhau tận hưởng những trò chơi khác nhau. Một số trẻ leo trèo, chạy, nhảy hoặc chơi trốn tìm với bạn bè. Mọi người chia sẻ sân chơi một cách tử tế và kiên nhẫn chờ đến lượt mình trên xích đu.\n\nSân chơi giúp trẻ em trở nên năng động và tự tin. Các em học cách làm việc nhóm, cải thiện khả năng giữ thăng bằng và tận hưởng hoạt động ngoài trời lành mạnh. Giữ thiết bị sân chơi sạch sẽ và an toàn cho phép trẻ em vui chơi mỗi ngày."
  },
  {
    "text": "6. Walking in the Park\nWalking in the park is a healthy activity for people of all ages. The fresh air, green trees, and quiet paths make everyone feel relaxed. Many people enjoy morning or evening walks with family or friends together.\n\nWhile walking, people can watch birds, smell flowers, and hear gentle sounds. Some visitors stop to rest on benches or take beautiful photos. Others enjoy talking while walking slowly around the peaceful lake every afternoon.\n\nWalking in the park improves both health and happiness. It keeps the body active and helps reduce stress after busy days. Everyone should enjoy nature and help keep parks clean for future visitors always.",
    "vi": "6. Đi Bộ Trong Công Viên\nĐi bộ trong công viên là một hoạt động lành mạnh cho mọi người ở mọi lứa tuổi. Không khí trong lành, cây xanh và những lối đi yên tĩnh khiến mọi người cảm thấy thư thái. Nhiều người thích đi bộ buổi sáng hoặc buổi tối cùng gia đình hay bạn bè.\n\nTrong khi đi bộ, mọi người có thể ngắm chim, ngửi hoa và nghe những âm thanh nhẹ nhàng. Một số khách tham quan dừng lại nghỉ trên ghế băng hoặc chụp những bức ảnh đẹp. Những người khác thích trò chuyện trong khi đi chậm quanh hồ yên bình vào mỗi buổi chiều.\n\nĐi bộ trong công viên cải thiện cả sức khỏe lẫn niềm vui. Hoạt động này giữ cho cơ thể năng động và giúp giảm căng thẳng sau những ngày bận rộn. Mọi người nên tận hưởng thiên nhiên và giúp giữ công viên sạch sẽ cho những khách tham quan trong tương lai."
  }
];
