// ===== park01 VOCABULARY =====

const lessonVocabularyWords = [
  "beautiful",
  "park",
  "peaceful",
  "place",
  "where",
  "people",
  "relax",
  "and",
  "enjoy",
  "nature",
  "has",
  "green",
  "grass",
  "colorful",
  "flowers",
  "tall",
  "trees",
  "clean",
  "walking",
  "paths",
  "families",
  "children",
  "friends",
  "often",
  "visit",
  "school",
  "or",
  "work",
  "together",
  "can",
  "walk",
  "jog",
  "ride",
  "bicycles",
  "sit",
  "benches",
  "play",
  "swings",
  "slides",
  "while",
  "parents",
  "watch",
  "happily",
  "some",
  "visitors",
  "read",
  "books",
  "take",
  "photos",
  "feed",
  "ducks",
  "small",
  "lake",
  "every",
  "weekend",
  "makes",
  "city",
  "cleaner",
  "more",
  "enjoyable",
  "gives",
  "fresh",
  "air",
  "quiet",
  "spaces",
  "happy",
  "memories",
  "everyone",
  "should",
  "keep",
  "using",
  "trash",
  "bins",
  "protecting",
  "day",
  "activities",
  "many",
  "different",
  "parks",
  "safe",
  "places",
  "neighbors",
  "spend",
  "time",
  "exercise",
  "outside",
  "around",
  "run",
  "games",
  "fly",
  "kites",
  "climb",
  "playground",
  "equipment",
  "others",
  "have",
  "picnics",
  "listen",
  "music",
  "birds",
  "sunny",
  "afternoons",
  "help",
  "stay",
  "healthy",
  "spending",
  "reduces",
  "stress",
  "energy",
  "respect",
  "kindness",
  "care",
  "family",
  "picnic",
  "enjoys",
  "having",
  "weekends",
  "bring",
  "delicious",
  "food",
  "cold",
  "drinks",
  "fruits",
  "large",
  "blanket",
  "feels",
  "excited",
  "because",
  "eat",
  "sandwiches",
  "tell",
  "funny",
  "stories",
  "big",
  "tree",
  "brother",
  "flies",
  "kite",
  "lunch",
  "creates",
  "wonderful",
  "helps",
  "laugh",
  "talk",
  "busy",
  "schedules",
  "going",
  "home",
  "area",
  "carefully",
  "throw",
  "all",
  "properly"
];

const newVocabData = [
  {
    "id": 1,
    "word": "beautiful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bjutəfəl/",
    "meaning": "đẹp",
    "ex1": "A beautiful park is a peaceful place where people relax and enjoy nature.",
    "ex1_vi": "Một công viên đẹp là nơi yên bình để mọi người thư giãn và tận hưởng thiên nhiên."
  },
  {
    "id": 2,
    "word": "park",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrk/",
    "meaning": "công viên",
    "ex1": "A beautiful park is a peaceful place where people relax and enjoy nature.",
    "ex1_vi": "Một công viên đẹp là nơi yên bình để mọi người thư giãn và tận hưởng thiên nhiên."
  },
  {
    "id": 3,
    "word": "peaceful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈisfəl/",
    "meaning": "thanh bình",
    "ex1": "Usually, a beautiful park is a peaceful place where people relax and enjoy nature.",
    "ex1_vi": "Thông thường, một công viên đẹp là nơi yên bình để mọi người thư giãn và tận hưởng thiên nhiên."
  },
  {
    "id": 4,
    "word": "place",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪs/",
    "meaning": "nơi; địa điểm",
    "ex1": "Often, a beautiful park is a peaceful place where people relax and enjoy nature.",
    "ex1_vi": "Thường thì, một công viên đẹp là nơi yên bình để mọi người thư giãn và tận hưởng thiên nhiên."
  },
  {
    "id": 5,
    "word": "where",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈɛr/",
    "meaning": "nơi mà",
    "ex1": "On most days, a beautiful park is a peaceful place where people relax and enjoy nature.",
    "ex1_vi": "Trong hầu hết các ngày, một công viên đẹp là nơi yên bình để mọi người thư giãn và tận hưởng thiên nhiên."
  },
  {
    "id": 6,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈiːpəl/",
    "meaning": "mọi người",
    "ex1": "During a park visit, a beautiful park is a peaceful place where people relax and enjoy nature.",
    "ex1_vi": "Trong một lần đến công viên, một công viên đẹp là nơi yên bình để mọi người thư giãn và tận hưởng thiên nhiên."
  },
  {
    "id": 7,
    "word": "relax",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪlˈæks/",
    "meaning": "thư giãn",
    "ex1": "For many visitors, a beautiful park is a peaceful place where people relax and enjoy nature.",
    "ex1_vi": "Đối với nhiều khách tham quan, một công viên đẹp là nơi yên bình để mọi người thư giãn và tận hưởng thiên nhiên."
  },
  {
    "id": 8,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈand/",
    "meaning": "và",
    "ex1": "In daily park life, a beautiful park is a peaceful place where people relax and enjoy nature.",
    "ex1_vi": "Trong sinh hoạt hằng ngày ở công viên, một công viên đẹp là nơi yên bình để mọi người thư giãn và tận hưởng thiên nhiên."
  },
  {
    "id": 9,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɛndʒˈɔɪ/",
    "meaning": "yêu thích; tận hưởng",
    "ex1": "On a calm day, a beautiful park is a peaceful place where people relax and enjoy nature.",
    "ex1_vi": "Vào một ngày yên bình, một công viên đẹp là nơi yên bình để mọi người thư giãn và tận hưởng thiên nhiên."
  },
  {
    "id": 10,
    "word": "nature",
    "type": "noun",
    "cat": "n",
    "phonetic": "/neɪtʃɚ/",
    "meaning": "thiên nhiên",
    "ex1": "During outdoor time, a beautiful park is a peaceful place where people relax and enjoy nature.",
    "ex1_vi": "Trong thời gian ở ngoài trời, một công viên đẹp là nơi yên bình để mọi người thư giãn và tận hưởng thiên nhiên."
  },
  {
    "id": 11,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈaz/",
    "meaning": "có",
    "ex1": "It has green grass, colorful flowers, tall trees, and clean walking paths.",
    "ex1_vi": "Công viên có cỏ xanh, hoa nhiều màu sắc, cây cao và những lối đi bộ sạch sẽ."
  },
  {
    "id": 12,
    "word": "green",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈin/",
    "meaning": "xanh",
    "ex1": "It has green grass, colorful flowers, tall trees, and clean walking paths.",
    "ex1_vi": "Công viên có cỏ xanh, hoa nhiều màu sắc, cây cao và những lối đi bộ sạch sẽ."
  },
  {
    "id": 13,
    "word": "grass",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡrˈæs/",
    "meaning": "cỏ",
    "ex1": "Usually, it has green grass, colorful flowers, tall trees, and clean walking paths.",
    "ex1_vi": "Thông thường, công viên có cỏ xanh, hoa nhiều màu sắc, cây cao và những lối đi bộ sạch sẽ."
  },
  {
    "id": 14,
    "word": "colorful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kʌlɚfəl/",
    "meaning": "đầy màu sắc",
    "ex1": "Often, it has green grass, colorful flowers, tall trees, and clean walking paths.",
    "ex1_vi": "Thường thì, công viên có cỏ xanh, hoa nhiều màu sắc, cây cao và những lối đi bộ sạch sẽ."
  },
  {
    "id": 15,
    "word": "flowers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈaʊɝz/",
    "meaning": "hoa",
    "ex1": "On most days, it has green grass, colorful flowers, tall trees, and clean walking paths.",
    "ex1_vi": "Trong hầu hết các ngày, công viên có cỏ xanh, hoa nhiều màu sắc, cây cao và những lối đi bộ sạch sẽ."
  },
  {
    "id": 16,
    "word": "tall",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈɔl/",
    "meaning": "cao",
    "ex1": "During a park visit, it has green grass, colorful flowers, tall trees, and clean walking paths.",
    "ex1_vi": "Trong một lần đến công viên, công viên có cỏ xanh, hoa nhiều màu sắc, cây cao và những lối đi bộ sạch sẽ."
  },
  {
    "id": 17,
    "word": "trees",
    "type": "noun",
    "cat": "n",
    "phonetic": "/triz/",
    "meaning": "cây",
    "ex1": "For many visitors, it has green grass, colorful flowers, tall trees, and clean walking paths.",
    "ex1_vi": "Đối với nhiều khách tham quan, công viên có cỏ xanh, hoa nhiều màu sắc, cây cao và những lối đi bộ sạch sẽ."
  },
  {
    "id": 18,
    "word": "clean",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈiːn/",
    "meaning": "sạch",
    "ex1": "In daily park life, it has green grass, colorful flowers, tall trees, and clean walking paths.",
    "ex1_vi": "Trong sinh hoạt hằng ngày ở công viên, công viên có cỏ xanh, hoa nhiều màu sắc, cây cao và những lối đi bộ sạch sẽ."
  },
  {
    "id": 19,
    "word": "walking",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/wˈɔkɪŋ/",
    "meaning": "việc đi bộ",
    "ex1": "On a calm day, it has green grass, colorful flowers, tall trees, and clean walking paths.",
    "ex1_vi": "Vào một ngày yên bình, công viên có cỏ xanh, hoa nhiều màu sắc, cây cao và những lối đi bộ sạch sẽ."
  },
  {
    "id": 20,
    "word": "paths",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈæðz/",
    "meaning": "lối đi",
    "ex1": "During outdoor time, it has green grass, colorful flowers, tall trees, and clean walking paths.",
    "ex1_vi": "Trong thời gian ở ngoài trời, công viên có cỏ xanh, hoa nhiều màu sắc, cây cao và những lối đi bộ sạch sẽ."
  },
  {
    "id": 21,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fæməliz/",
    "meaning": "gia đình",
    "ex1": "Families, children, and friends often visit the park after school or work together.",
    "ex1_vi": "Các gia đình, trẻ em và bạn bè thường đến công viên sau giờ học hoặc giờ làm việc."
  },
  {
    "id": 22,
    "word": "children",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃɪldrən/",
    "meaning": "trẻ em",
    "ex1": "Families, children, and friends often visit the park after school or work together.",
    "ex1_vi": "Các gia đình, trẻ em và bạn bè thường đến công viên sau giờ học hoặc giờ làm việc."
  },
  {
    "id": 23,
    "word": "friends",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈɛndz/",
    "meaning": "bạn bè",
    "ex1": "Usually, families, children, and friends often visit the park after school or work together.",
    "ex1_vi": "Thông thường, các gia đình, trẻ em và bạn bè thường đến công viên sau giờ học hoặc giờ làm việc."
  },
  {
    "id": 24,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɔfən/",
    "meaning": "thường xuyên",
    "ex1": "Often, families, children, and friends often visit the park after school or work together.",
    "ex1_vi": "Thường thì, các gia đình, trẻ em và bạn bè thường đến công viên sau giờ học hoặc giờ làm việc."
  },
  {
    "id": 25,
    "word": "visit",
    "type": "verb",
    "cat": "v",
    "phonetic": "/vˈɪzɪt/",
    "meaning": "thăm",
    "ex1": "On most days, families, children, and friends often visit the park after school or work together.",
    "ex1_vi": "Trong hầu hết các ngày, các gia đình, trẻ em và bạn bè thường đến công viên sau giờ học hoặc giờ làm việc."
  },
  {
    "id": 26,
    "word": "school",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈul/",
    "meaning": "trường học",
    "ex1": "During a park visit, families, children, and friends often visit the park after school or work together.",
    "ex1_vi": "Trong một lần đến công viên, các gia đình, trẻ em và bạn bè thường đến công viên sau giờ học hoặc giờ làm việc."
  },
  {
    "id": 27,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔː/",
    "meaning": "hoặc",
    "ex1": "For many visitors, families, children, and friends often visit the park after school or work together.",
    "ex1_vi": "Đối với nhiều khách tham quan, các gia đình, trẻ em và bạn bè thường đến công viên sau giờ học hoặc giờ làm việc."
  },
  {
    "id": 28,
    "word": "work",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɜːk/",
    "meaning": "làm việc",
    "ex1": "In daily park life, families, children, and friends often visit the park after school or work together.",
    "ex1_vi": "Trong sinh hoạt hằng ngày ở công viên, các gia đình, trẻ em và bạn bè thường đến công viên sau giờ học hoặc giờ làm việc."
  },
  {
    "id": 29,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/təɡˈɛðə/",
    "meaning": "cùng nhau",
    "ex1": "On a calm day, families, children, and friends often visit the park after school or work together.",
    "ex1_vi": "Vào một ngày yên bình, các gia đình, trẻ em và bạn bè thường đến công viên sau giờ học hoặc giờ làm việc."
  },
  {
    "id": 30,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈan/",
    "meaning": "có thể",
    "ex1": "People can walk, jog, ride bicycles, or sit on benches.",
    "ex1_vi": "Mọi người có thể đi bộ, chạy bộ, đi xe đạp hoặc ngồi trên ghế băng."
  },
  {
    "id": 31,
    "word": "walk",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɔk/",
    "meaning": "đi bộ",
    "ex1": "People can walk, jog, ride bicycles, or sit on benches.",
    "ex1_vi": "Mọi người có thể đi bộ, chạy bộ, đi xe đạp hoặc ngồi trên ghế băng."
  },
  {
    "id": 32,
    "word": "jog",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dʒˈɑɡ/",
    "meaning": "chạy bộ chậm",
    "ex1": "Usually, people can walk, jog, ride bicycles, or sit on benches.",
    "ex1_vi": "Thông thường, mọi người có thể đi bộ, chạy bộ, đi xe đạp hoặc ngồi trên ghế băng."
  },
  {
    "id": 33,
    "word": "ride",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈaɪd/",
    "meaning": "đi; đi xe",
    "ex1": "Often, people can walk, jog, ride bicycles, or sit on benches.",
    "ex1_vi": "Thường thì, mọi người có thể đi bộ, chạy bộ, đi xe đạp hoặc ngồi trên ghế băng."
  },
  {
    "id": 34,
    "word": "bicycles",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈaɪsɪkʌlz/",
    "meaning": "xe đạp",
    "ex1": "On most days, people can walk, jog, ride bicycles, or sit on benches.",
    "ex1_vi": "Trong hầu hết các ngày, mọi người có thể đi bộ, chạy bộ, đi xe đạp hoặc ngồi trên ghế băng."
  },
  {
    "id": 35,
    "word": "sit",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɪt/",
    "meaning": "ngồi",
    "ex1": "During a park visit, people can walk, jog, ride bicycles, or sit on benches.",
    "ex1_vi": "Trong một lần đến công viên, mọi người có thể đi bộ, chạy bộ, đi xe đạp hoặc ngồi trên ghế băng."
  },
  {
    "id": 36,
    "word": "benches",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɛntʃɪz/",
    "meaning": "ghế băng",
    "ex1": "For many visitors, people can walk, jog, ride bicycles, or sit on benches.",
    "ex1_vi": "Đối với nhiều khách tham quan, mọi người có thể đi bộ, chạy bộ, đi xe đạp hoặc ngồi trên ghế băng."
  },
  {
    "id": 37,
    "word": "play",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪ/",
    "meaning": "chơi",
    "ex1": "Children play on swings and slides while parents watch happily.",
    "ex1_vi": "Trẻ em chơi xích đu và cầu trượt trong khi cha mẹ vui vẻ quan sát."
  },
  {
    "id": 38,
    "word": "swings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/swˈɪŋz/",
    "meaning": "xích đu",
    "ex1": "Children play on swings and slides while parents watch happily.",
    "ex1_vi": "Trẻ em chơi xích đu và cầu trượt trong khi cha mẹ vui vẻ quan sát."
  },
  {
    "id": 39,
    "word": "slides",
    "type": "noun",
    "cat": "n",
    "phonetic": "/slˈaɪdz/",
    "meaning": "cầu trượt",
    "ex1": "Usually, children play on swings and slides while parents watch happily.",
    "ex1_vi": "Thông thường, trẻ em chơi xích đu và cầu trượt trong khi cha mẹ vui vẻ quan sát."
  },
  {
    "id": 40,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "Often, children play on swings and slides while parents watch happily.",
    "ex1_vi": "Thường thì, trẻ em chơi xích đu và cầu trượt trong khi cha mẹ vui vẻ quan sát."
  },
  {
    "id": 41,
    "word": "parents",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɛrʌnts/",
    "meaning": "cha mẹ",
    "ex1": "On most days, children play on swings and slides while parents watch happily.",
    "ex1_vi": "Trong hầu hết các ngày, trẻ em chơi xích đu và cầu trượt trong khi cha mẹ vui vẻ quan sát."
  },
  {
    "id": 42,
    "word": "watch",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɑtʃ/",
    "meaning": "quan sát",
    "ex1": "During a park visit, children play on swings and slides while parents watch happily.",
    "ex1_vi": "Trong một lần đến công viên, trẻ em chơi xích đu và cầu trượt trong khi cha mẹ vui vẻ quan sát."
  },
  {
    "id": 43,
    "word": "happily",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/hˈapɪli/",
    "meaning": "vui vẻ",
    "ex1": "For many visitors, children play on swings and slides while parents watch happily.",
    "ex1_vi": "Đối với nhiều khách tham quan, trẻ em chơi xích đu và cầu trượt trong khi cha mẹ vui vẻ quan sát."
  },
  {
    "id": 44,
    "word": "some",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sʌm/",
    "meaning": "một số",
    "ex1": "Some visitors read books, take photos, or feed ducks near the small lake every weekend.",
    "ex1_vi": "Một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần."
  },
  {
    "id": 45,
    "word": "visitors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪzɪtɝz/",
    "meaning": "du khách",
    "ex1": "Some visitors read books, take photos, or feed ducks near the small lake every weekend.",
    "ex1_vi": "Một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần."
  },
  {
    "id": 46,
    "word": "read",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹˈɛd/",
    "meaning": "đọc",
    "ex1": "Usually, some visitors read books, take photos, or feed ducks near the small lake every weekend.",
    "ex1_vi": "Thông thường, một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần."
  },
  {
    "id": 47,
    "word": "books",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʊks/",
    "meaning": "sách",
    "ex1": "Often, some visitors read books, take photos, or feed ducks near the small lake every weekend.",
    "ex1_vi": "Thường thì, một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần."
  },
  {
    "id": 48,
    "word": "take",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪk/",
    "meaning": "đi; lấy",
    "ex1": "On most days, some visitors read books, take photos, or feed ducks near the small lake every weekend.",
    "ex1_vi": "Trong hầu hết các ngày, một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần."
  },
  {
    "id": 49,
    "word": "photos",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈoʊtˌoʊz/",
    "meaning": "ảnh",
    "ex1": "During a park visit, some visitors read books, take photos, or feed ducks near the small lake every weekend.",
    "ex1_vi": "Trong một lần đến công viên, một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần."
  },
  {
    "id": 50,
    "word": "feed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈiːd/",
    "meaning": "cho ăn",
    "ex1": "For many visitors, some visitors read books, take photos, or feed ducks near the small lake every weekend.",
    "ex1_vi": "Đối với nhiều khách tham quan, một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần."
  },
  {
    "id": 51,
    "word": "ducks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈʌks/",
    "meaning": "vịt",
    "ex1": "In daily park life, some visitors read books, take photos, or feed ducks near the small lake every weekend.",
    "ex1_vi": "Trong sinh hoạt hằng ngày ở công viên, một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần."
  },
  {
    "id": 52,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "On a calm day, some visitors read books, take photos, or feed ducks near the small lake every weekend.",
    "ex1_vi": "Vào một ngày yên bình, một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần."
  },
  {
    "id": 53,
    "word": "lake",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈeɪk/",
    "meaning": "hồ",
    "ex1": "During outdoor time, some visitors read books, take photos, or feed ducks near the small lake every weekend.",
    "ex1_vi": "Trong thời gian ở ngoài trời, một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần."
  },
  {
    "id": 54,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɹɪ/",
    "meaning": "mỗi",
    "ex1": "Usually, some visitors read books, take photos, or feed ducks near the small lake every weekend.",
    "ex1_vi": "Thông thường, một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần."
  },
  {
    "id": 55,
    "word": "weekend",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈiːkˌɛnd/",
    "meaning": "cuối tuần",
    "ex1": "Often, some visitors read books, take photos, or feed ducks near the small lake every weekend.",
    "ex1_vi": "Thường thì, một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần."
  },
  {
    "id": 56,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm cho",
    "ex1": "A beautiful park makes the city cleaner and more enjoyable.",
    "ex1_vi": "Một công viên đẹp làm cho thành phố sạch hơn và thú vị hơn."
  },
  {
    "id": 57,
    "word": "city",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪti/",
    "meaning": "thành phố",
    "ex1": "A beautiful park makes the city cleaner and more enjoyable.",
    "ex1_vi": "Một công viên đẹp làm cho thành phố sạch hơn và thú vị hơn."
  },
  {
    "id": 58,
    "word": "cleaner",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈklinər/",
    "meaning": "sạch hơn",
    "ex1": "Usually, a beautiful park makes the city cleaner and more enjoyable.",
    "ex1_vi": "Thông thường, một công viên đẹp làm cho thành phố sạch hơn và thú vị hơn."
  },
  {
    "id": 59,
    "word": "more",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/mɔr/",
    "meaning": "hơn",
    "ex1": "Often, a beautiful park makes the city cleaner and more enjoyable.",
    "ex1_vi": "Thường thì, một công viên đẹp làm cho thành phố sạch hơn và thú vị hơn."
  },
  {
    "id": 60,
    "word": "enjoyable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɛndʒˈɔɪəbəl/",
    "meaning": "thú vị",
    "ex1": "On most days, a beautiful park makes the city cleaner and more enjoyable.",
    "ex1_vi": "Trong hầu hết các ngày, một công viên đẹp làm cho thành phố sạch hơn và thú vị hơn."
  },
  {
    "id": 61,
    "word": "gives",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvz/",
    "meaning": "mang lại",
    "ex1": "It gives fresh air, quiet spaces, and happy memories for everyone.",
    "ex1_vi": "Công viên mang lại không khí trong lành, những không gian yên tĩnh và những kỷ niệm vui cho mọi người."
  },
  {
    "id": 62,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fɹˈɛʃ/",
    "meaning": "tươi; trong lành",
    "ex1": "It gives fresh air, quiet spaces, and happy memories for everyone.",
    "ex1_vi": "Công viên mang lại không khí trong lành, những không gian yên tĩnh và những kỷ niệm vui cho mọi người."
  },
  {
    "id": 63,
    "word": "air",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛr/",
    "meaning": "không khí",
    "ex1": "Usually, it gives fresh air, quiet spaces, and happy memories for everyone.",
    "ex1_vi": "Thông thường, công viên mang lại không khí trong lành, những không gian yên tĩnh và những kỷ niệm vui cho mọi người."
  },
  {
    "id": 64,
    "word": "quiet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kwˈaɪət/",
    "meaning": "yên tĩnh",
    "ex1": "Often, it gives fresh air, quiet spaces, and happy memories for everyone.",
    "ex1_vi": "Thường thì, công viên mang lại không khí trong lành, những không gian yên tĩnh và những kỷ niệm vui cho mọi người."
  },
  {
    "id": 65,
    "word": "spaces",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈeɪsɪz/",
    "meaning": "không gian",
    "ex1": "On most days, it gives fresh air, quiet spaces, and happy memories for everyone.",
    "ex1_vi": "Trong hầu hết các ngày, công viên mang lại không khí trong lành, những không gian yên tĩnh và những kỷ niệm vui cho mọi người."
  },
  {
    "id": 66,
    "word": "happy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈapi/",
    "meaning": "vui vẻ; hạnh phúc",
    "ex1": "During a park visit, it gives fresh air, quiet spaces, and happy memories for everyone.",
    "ex1_vi": "Trong một lần đến công viên, công viên mang lại không khí trong lành, những không gian yên tĩnh và những kỷ niệm vui cho mọi người."
  },
  {
    "id": 67,
    "word": "memories",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛmɝiz/",
    "meaning": "những kỷ niệm",
    "ex1": "For many visitors, it gives fresh air, quiet spaces, and happy memories for everyone.",
    "ex1_vi": "Đối với nhiều khách tham quan, công viên mang lại không khí trong lành, những không gian yên tĩnh và những kỷ niệm vui cho mọi người."
  },
  {
    "id": 68,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvɹɪwˌɒn/",
    "meaning": "mọi người",
    "ex1": "In daily park life, it gives fresh air, quiet spaces, and happy memories for everyone.",
    "ex1_vi": "Trong sinh hoạt hằng ngày ở công viên, công viên mang lại không khí trong lành, những không gian yên tĩnh và những kỷ niệm vui cho mọi người."
  },
  {
    "id": 69,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "People should keep the park clean by using trash bins and protecting nature every day.",
    "ex1_vi": "Mọi người nên giữ công viên sạch sẽ bằng cách sử dụng thùng rác và bảo vệ thiên nhiên mỗi ngày."
  },
  {
    "id": 70,
    "word": "keep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈiːp/",
    "meaning": "giữ; duy trì",
    "ex1": "People should keep the park clean by using trash bins and protecting nature every day.",
    "ex1_vi": "Mọi người nên giữ công viên sạch sẽ bằng cách sử dụng thùng rác và bảo vệ thiên nhiên mỗi ngày."
  },
  {
    "id": 71,
    "word": "using",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/jˈuːzɪŋ/",
    "meaning": "việc sử dụng",
    "ex1": "Usually, people should keep the park clean by using trash bins and protecting nature every day.",
    "ex1_vi": "Thông thường, mọi người nên giữ công viên sạch sẽ bằng cách sử dụng thùng rác và bảo vệ thiên nhiên mỗi ngày."
  },
  {
    "id": 72,
    "word": "trash",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈæʃ/",
    "meaning": "rác",
    "ex1": "Often, people should keep the park clean by using trash bins and protecting nature every day.",
    "ex1_vi": "Thường thì, mọi người nên giữ công viên sạch sẽ bằng cách sử dụng thùng rác và bảo vệ thiên nhiên mỗi ngày."
  },
  {
    "id": 73,
    "word": "bins",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɪnz/",
    "meaning": "thùng rác",
    "ex1": "On most days, people should keep the park clean by using trash bins and protecting nature every day.",
    "ex1_vi": "Trong hầu hết các ngày, mọi người nên giữ công viên sạch sẽ bằng cách sử dụng thùng rác và bảo vệ thiên nhiên mỗi ngày."
  },
  {
    "id": 74,
    "word": "protecting",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/prʌtˈɛktɪŋ/",
    "meaning": "việc bảo vệ",
    "ex1": "During a park visit, people should keep the park clean by using trash bins and protecting nature every day.",
    "ex1_vi": "Trong một lần đến công viên, mọi người nên giữ công viên sạch sẽ bằng cách sử dụng thùng rác và bảo vệ thiên nhiên mỗi ngày."
  },
  {
    "id": 75,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "For many visitors, people should keep the park clean by using trash bins and protecting nature every day.",
    "ex1_vi": "Đối với nhiều khách tham quan, mọi người nên giữ công viên sạch sẽ bằng cách sử dụng thùng rác và bảo vệ thiên nhiên mỗi ngày."
  },
  {
    "id": 76,
    "word": "activities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/æktˈɪvətiz/",
    "meaning": "hoạt động",
    "ex1": "Many people enjoy different activities in the park every day.",
    "ex1_vi": "Nhiều người tận hưởng các hoạt động khác nhau trong công viên mỗi ngày."
  },
  {
    "id": 77,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Many people enjoy different activities in the park every day.",
    "ex1_vi": "Nhiều người tận hưởng các hoạt động khác nhau trong công viên mỗi ngày."
  },
  {
    "id": 78,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɹənt/",
    "meaning": "khác nhau",
    "ex1": "Usually, many people enjoy different activities in the park every day.",
    "ex1_vi": "Thông thường, nhiều người tận hưởng các hoạt động khác nhau trong công viên mỗi ngày."
  },
  {
    "id": 79,
    "word": "parks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑːɹks/",
    "meaning": "công viên",
    "ex1": "Parks are safe places where families, friends, and neighbors spend time together.",
    "ex1_vi": "Công viên là nơi an toàn để gia đình, bạn bè và hàng xóm dành thời gian bên nhau."
  },
  {
    "id": 80,
    "word": "safe",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪf/",
    "meaning": "an toàn",
    "ex1": "Parks are safe places where families, friends, and neighbors spend time together.",
    "ex1_vi": "Công viên là nơi an toàn để gia đình, bạn bè và hàng xóm dành thời gian bên nhau."
  },
  {
    "id": 81,
    "word": "places",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪsɪz/",
    "meaning": "nơi",
    "ex1": "Usually, parks are safe places where families, friends, and neighbors spend time together.",
    "ex1_vi": "Thông thường, công viên là nơi an toàn để gia đình, bạn bè và hàng xóm dành thời gian bên nhau."
  },
  {
    "id": 82,
    "word": "neighbors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈeɪbɝz/",
    "meaning": "hàng xóm",
    "ex1": "Often, parks are safe places where families, friends, and neighbors spend time together.",
    "ex1_vi": "Thường thì, công viên là nơi an toàn để gia đình, bạn bè và hàng xóm dành thời gian bên nhau."
  },
  {
    "id": 83,
    "word": "spend",
    "type": "verb",
    "cat": "v",
    "phonetic": "/spˈɛnd/",
    "meaning": "dành (thời gian)",
    "ex1": "On most days, parks are safe places where families, friends, and neighbors spend time together.",
    "ex1_vi": "Trong hầu hết các ngày, công viên là nơi an toàn để gia đình, bạn bè và hàng xóm dành thời gian bên nhau."
  },
  {
    "id": 84,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "During a park visit, parks are safe places where families, friends, and neighbors spend time together.",
    "ex1_vi": "Trong một lần đến công viên, công viên là nơi an toàn để gia đình, bạn bè và hàng xóm dành thời gian bên nhau."
  },
  {
    "id": 85,
    "word": "exercise",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛksɚsˌaɪz/",
    "meaning": "tập thể dục",
    "ex1": "Visitors can exercise, relax, and enjoy the fresh air outside happily.",
    "ex1_vi": "Khách tham quan có thể tập thể dục, thư giãn và vui vẻ tận hưởng không khí trong lành ngoài trời."
  },
  {
    "id": 86,
    "word": "outside",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈaʊtsˈaɪd/",
    "meaning": "ở ngoài trời",
    "ex1": "Visitors can exercise, relax, and enjoy the fresh air outside happily.",
    "ex1_vi": "Khách tham quan có thể tập thể dục, thư giãn và vui vẻ tận hưởng không khí trong lành ngoài trời."
  },
  {
    "id": 87,
    "word": "around",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ɚɹˈaʊnd/",
    "meaning": "quanh",
    "ex1": "Some people walk around the park or run on the paths.",
    "ex1_vi": "Một số người đi bộ quanh công viên hoặc chạy trên các lối đi."
  },
  {
    "id": 88,
    "word": "run",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹˈʌn/",
    "meaning": "chạy",
    "ex1": "Some people walk around the park or run on the paths.",
    "ex1_vi": "Một số người đi bộ quanh công viên hoặc chạy trên các lối đi."
  },
  {
    "id": 89,
    "word": "games",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈeɪmz/",
    "meaning": "trò chơi",
    "ex1": "Children play games, fly kites, and climb on playground equipment.",
    "ex1_vi": "Trẻ em chơi trò chơi, thả diều và leo trèo trên thiết bị sân chơi."
  },
  {
    "id": 90,
    "word": "fly",
    "type": "verb",
    "cat": "v",
    "phonetic": "/flˈaɪ/",
    "meaning": "thả; bay",
    "ex1": "Children play games, fly kites, and climb on playground equipment.",
    "ex1_vi": "Trẻ em chơi trò chơi, thả diều và leo trèo trên thiết bị sân chơi."
  },
  {
    "id": 91,
    "word": "kites",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈaɪts/",
    "meaning": "những cái diều",
    "ex1": "Usually, children play games, fly kites, and climb on playground equipment.",
    "ex1_vi": "Thông thường, trẻ em chơi trò chơi, thả diều và leo trèo trên thiết bị sân chơi."
  },
  {
    "id": 92,
    "word": "climb",
    "type": "verb",
    "cat": "v",
    "phonetic": "/klˈaɪm/",
    "meaning": "leo",
    "ex1": "Often, children play games, fly kites, and climb on playground equipment.",
    "ex1_vi": "Thường thì, trẻ em chơi trò chơi, thả diều và leo trèo trên thiết bị sân chơi."
  },
  {
    "id": 93,
    "word": "playground",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪɡrˌaʊnd/",
    "meaning": "sân chơi",
    "ex1": "On most days, children play games, fly kites, and climb on playground equipment.",
    "ex1_vi": "Trong hầu hết các ngày, trẻ em chơi trò chơi, thả diều và leo trèo trên thiết bị sân chơi."
  },
  {
    "id": 94,
    "word": "equipment",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪkwˈɪpmənt/",
    "meaning": "thiết bị",
    "ex1": "During a park visit, children play games, fly kites, and climb on playground equipment.",
    "ex1_vi": "Trong một lần đến công viên, trẻ em chơi trò chơi, thả diều và leo trèo trên thiết bị sân chơi."
  },
  {
    "id": 95,
    "word": "others",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈʌðəz/",
    "meaning": "những người khác",
    "ex1": "Others have picnics, listen to music, or watch birds in the trees during sunny afternoons.",
    "ex1_vi": "Những người khác đi dã ngoại, nghe nhạc hoặc ngắm chim trên cây vào những buổi chiều nắng."
  },
  {
    "id": 96,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈav/",
    "meaning": "có",
    "ex1": "Others have picnics, listen to music, or watch birds in the trees during sunny afternoons.",
    "ex1_vi": "Những người khác đi dã ngoại, nghe nhạc hoặc ngắm chim trên cây vào những buổi chiều nắng."
  },
  {
    "id": 97,
    "word": "picnics",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɪknˌɪks/",
    "meaning": "các buổi dã ngoại",
    "ex1": "Usually, others have picnics, listen to music, or watch birds in the trees during sunny afternoons.",
    "ex1_vi": "Thông thường, những người khác đi dã ngoại, nghe nhạc hoặc ngắm chim trên cây vào những buổi chiều nắng."
  },
  {
    "id": 98,
    "word": "listen",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɪsən/",
    "meaning": "lắng nghe",
    "ex1": "Often, others have picnics, listen to music, or watch birds in the trees during sunny afternoons.",
    "ex1_vi": "Thường thì, những người khác đi dã ngoại, nghe nhạc hoặc ngắm chim trên cây vào những buổi chiều nắng."
  },
  {
    "id": 99,
    "word": "music",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mjˈuzɪk/",
    "meaning": "âm nhạc",
    "ex1": "On most days, others have picnics, listen to music, or watch birds in the trees during sunny afternoons.",
    "ex1_vi": "Trong hầu hết các ngày, những người khác đi dã ngoại, nghe nhạc hoặc ngắm chim trên cây vào những buổi chiều nắng."
  },
  {
    "id": 100,
    "word": "birds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɝdz/",
    "meaning": "chim",
    "ex1": "During a park visit, others have picnics, listen to music, or watch birds in the trees during sunny afternoons.",
    "ex1_vi": "Trong một lần đến công viên, những người khác đi dã ngoại, nghe nhạc hoặc ngắm chim trên cây vào những buổi chiều nắng."
  },
  {
    "id": 101,
    "word": "sunny",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈʌniː/",
    "meaning": "có nắng",
    "ex1": "For many visitors, others have picnics, listen to music, or watch birds in the trees during sunny afternoons.",
    "ex1_vi": "Đối với nhiều khách tham quan, những người khác đi dã ngoại, nghe nhạc hoặc ngắm chim trên cây vào những buổi chiều nắng."
  },
  {
    "id": 102,
    "word": "afternoons",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌæftɝnˈuːnz/",
    "meaning": "các buổi chiều",
    "ex1": "In daily park life, others have picnics, listen to music, or watch birds in the trees during sunny afternoons.",
    "ex1_vi": "Trong sinh hoạt hằng ngày ở công viên, những người khác đi dã ngoại, nghe nhạc hoặc ngắm chim trên cây vào những buổi chiều nắng."
  },
  {
    "id": 103,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "Park activities help people stay healthy and happy.",
    "ex1_vi": "Các hoạt động trong công viên giúp mọi người khỏe mạnh và vui vẻ."
  },
  {
    "id": 104,
    "word": "stay",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈeɪ/",
    "meaning": "duy trì; ở trạng thái",
    "ex1": "Park activities help people stay healthy and happy.",
    "ex1_vi": "Các hoạt động trong công viên giúp mọi người khỏe mạnh và vui vẻ."
  },
  {
    "id": 105,
    "word": "healthy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlθi/",
    "meaning": "khỏe mạnh",
    "ex1": "Usually, park activities help people stay healthy and happy.",
    "ex1_vi": "Thông thường, các hoạt động trong công viên giúp mọi người khỏe mạnh và vui vẻ."
  },
  {
    "id": 106,
    "word": "spending",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/spˈɛndɪŋ/",
    "meaning": "việc dành thời gian",
    "ex1": "Spending time outside reduces stress and gives everyone more energy.",
    "ex1_vi": "Dành thời gian ngoài trời giúp giảm căng thẳng và mang lại cho mọi người nhiều năng lượng hơn."
  },
  {
    "id": 107,
    "word": "reduces",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪdjˈuːsɪz/",
    "meaning": "giảm",
    "ex1": "Spending time outside reduces stress and gives everyone more energy.",
    "ex1_vi": "Dành thời gian ngoài trời giúp giảm căng thẳng và mang lại cho mọi người nhiều năng lượng hơn."
  },
  {
    "id": 108,
    "word": "stress",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stɹˈɛs/",
    "meaning": "căng thẳng",
    "ex1": "Usually, spending time outside reduces stress and gives everyone more energy.",
    "ex1_vi": "Thông thường, dành thời gian ngoài trời giúp giảm căng thẳng và mang lại cho mọi người nhiều năng lượng hơn."
  },
  {
    "id": 109,
    "word": "energy",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛnɚdʒi/",
    "meaning": "năng lượng",
    "ex1": "Often, spending time outside reduces stress and gives everyone more energy.",
    "ex1_vi": "Thường thì, dành thời gian ngoài trời giúp giảm căng thẳng và mang lại cho mọi người nhiều năng lượng hơn."
  },
  {
    "id": 110,
    "word": "respect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪspˈɛkt/",
    "meaning": "tôn trọng",
    "ex1": "People should respect others, keep the park clean, and enjoy every visit with kindness and care.",
    "ex1_vi": "Mọi người nên tôn trọng người khác, giữ công viên sạch sẽ và tận hưởng mỗi lần ghé thăm với sự tử tế và quan tâm."
  },
  {
    "id": 111,
    "word": "kindness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈaɪndnəs/",
    "meaning": "lòng tốt",
    "ex1": "People should respect others, keep the park clean, and enjoy every visit with kindness and care.",
    "ex1_vi": "Mọi người nên tôn trọng người khác, giữ công viên sạch sẽ và tận hưởng mỗi lần ghé thăm với sự tử tế và quan tâm."
  },
  {
    "id": 112,
    "word": "care",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɛr/",
    "meaning": "sự quan tâm",
    "ex1": "Usually, people should respect others, keep the park clean, and enjoy every visit with kindness and care.",
    "ex1_vi": "Thông thường, mọi người nên tôn trọng người khác, giữ công viên sạch sẽ và tận hưởng mỗi lần ghé thăm với sự tử tế và quan tâm."
  },
  {
    "id": 113,
    "word": "family",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/fˈæmɪli/",
    "meaning": "gia đình",
    "ex1": "My family enjoys having a picnic in the park on weekends.",
    "ex1_vi": "Gia đình tôi thích đi dã ngoại trong công viên vào cuối tuần."
  },
  {
    "id": 114,
    "word": "picnic",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɪknˌɪk/",
    "meaning": "buổi dã ngoại",
    "ex1": "My family enjoys having a picnic in the park on weekends.",
    "ex1_vi": "Gia đình tôi thích đi dã ngoại trong công viên vào cuối tuần."
  },
  {
    "id": 115,
    "word": "enjoys",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪz/",
    "meaning": "thích; tận hưởng",
    "ex1": "Usually, my family enjoys having a picnic in the park on weekends.",
    "ex1_vi": "Thông thường, gia đình tôi thích đi dã ngoại trong công viên vào cuối tuần."
  },
  {
    "id": 116,
    "word": "having",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/hˈævɪŋ/",
    "meaning": "việc có; việc tham gia",
    "ex1": "Often, my family enjoys having a picnic in the park on weekends.",
    "ex1_vi": "Thường thì, gia đình tôi thích đi dã ngoại trong công viên vào cuối tuần."
  },
  {
    "id": 117,
    "word": "weekends",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈiːkˌɛndz/",
    "meaning": "các cuối tuần",
    "ex1": "On most days, my family enjoys having a picnic in the park on weekends.",
    "ex1_vi": "Trong hầu hết các ngày, gia đình tôi thích đi dã ngoại trong công viên vào cuối tuần."
  },
  {
    "id": 118,
    "word": "bring",
    "type": "verb",
    "cat": "v",
    "phonetic": "/brˈɪŋ/",
    "meaning": "mang theo",
    "ex1": "We bring delicious food, cold drinks, fruits, and a large blanket.",
    "ex1_vi": "Chúng tôi mang theo thức ăn ngon, đồ uống lạnh, trái cây và một tấm chăn lớn."
  },
  {
    "id": 119,
    "word": "delicious",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dɪlˈɪʃʌs/",
    "meaning": "ngon",
    "ex1": "We bring delicious food, cold drinks, fruits, and a large blanket.",
    "ex1_vi": "Chúng tôi mang theo thức ăn ngon, đồ uống lạnh, trái cây và một tấm chăn lớn."
  },
  {
    "id": 120,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thức ăn",
    "ex1": "Usually, we bring delicious food, cold drinks, fruits, and a large blanket.",
    "ex1_vi": "Thông thường, chúng tôi mang theo thức ăn ngon, đồ uống lạnh, trái cây và một tấm chăn lớn."
  },
  {
    "id": 121,
    "word": "cold",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈoʊld/",
    "meaning": "lạnh",
    "ex1": "Often, we bring delicious food, cold drinks, fruits, and a large blanket.",
    "ex1_vi": "Thường thì, chúng tôi mang theo thức ăn ngon, đồ uống lạnh, trái cây và một tấm chăn lớn."
  },
  {
    "id": 122,
    "word": "drinks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɪŋks/",
    "meaning": "đồ uống",
    "ex1": "On most days, we bring delicious food, cold drinks, fruits, and a large blanket.",
    "ex1_vi": "Trong hầu hết các ngày, chúng tôi mang theo thức ăn ngon, đồ uống lạnh, trái cây và một tấm chăn lớn."
  },
  {
    "id": 123,
    "word": "fruits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈuːts/",
    "meaning": "trái cây",
    "ex1": "During a park visit, we bring delicious food, cold drinks, fruits, and a large blanket.",
    "ex1_vi": "Trong một lần đến công viên, chúng tôi mang theo thức ăn ngon, đồ uống lạnh, trái cây và một tấm chăn lớn."
  },
  {
    "id": 124,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑɹdʒ/",
    "meaning": "lớn",
    "ex1": "For many visitors, we bring delicious food, cold drinks, fruits, and a large blanket.",
    "ex1_vi": "Đối với nhiều khách tham quan, chúng tôi mang theo thức ăn ngon, đồ uống lạnh, trái cây và một tấm chăn lớn."
  },
  {
    "id": 125,
    "word": "blanket",
    "type": "noun",
    "cat": "n",
    "phonetic": "/blˈæŋkʌt/",
    "meaning": "tấm chăn",
    "ex1": "In daily park life, we bring delicious food, cold drinks, fruits, and a large blanket.",
    "ex1_vi": "Trong sinh hoạt hằng ngày ở công viên, chúng tôi mang theo thức ăn ngon, đồ uống lạnh, trái cây và một tấm chăn lớn."
  },
  {
    "id": 126,
    "word": "feels",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈiːlz/",
    "meaning": "cảm thấy",
    "ex1": "Everyone feels excited because we can spend happy time together outside.",
    "ex1_vi": "Mọi người đều cảm thấy hào hứng vì chúng tôi có thể vui vẻ dành thời gian bên nhau ngoài trời."
  },
  {
    "id": 127,
    "word": "excited",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪksˈaɪtʌd/",
    "meaning": "hào hứng",
    "ex1": "Everyone feels excited because we can spend happy time together outside.",
    "ex1_vi": "Mọi người đều cảm thấy hào hứng vì chúng tôi có thể vui vẻ dành thời gian bên nhau ngoài trời."
  },
  {
    "id": 128,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈʌz/",
    "meaning": "bởi vì",
    "ex1": "Usually, everyone feels excited because we can spend happy time together outside.",
    "ex1_vi": "Thông thường, mọi người đều cảm thấy hào hứng vì chúng tôi có thể vui vẻ dành thời gian bên nhau ngoài trời."
  },
  {
    "id": 129,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈiːt/",
    "meaning": "ăn",
    "ex1": "We eat sandwiches, play games, and tell funny stories under a big tree.",
    "ex1_vi": "Chúng tôi ăn bánh mì kẹp, chơi trò chơi và kể những câu chuyện vui dưới một cây lớn."
  },
  {
    "id": 130,
    "word": "sandwiches",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈændwɪtʃɪz/",
    "meaning": "bánh mì kẹp",
    "ex1": "We eat sandwiches, play games, and tell funny stories under a big tree.",
    "ex1_vi": "Chúng tôi ăn bánh mì kẹp, chơi trò chơi và kể những câu chuyện vui dưới một cây lớn."
  },
  {
    "id": 131,
    "word": "tell",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈɛl/",
    "meaning": "kể",
    "ex1": "Usually, we eat sandwiches, play games, and tell funny stories under a big tree.",
    "ex1_vi": "Thông thường, chúng tôi ăn bánh mì kẹp, chơi trò chơi và kể những câu chuyện vui dưới một cây lớn."
  },
  {
    "id": 132,
    "word": "funny",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈʌniː/",
    "meaning": "hài hước",
    "ex1": "Often, we eat sandwiches, play games, and tell funny stories under a big tree.",
    "ex1_vi": "Thường thì, chúng tôi ăn bánh mì kẹp, chơi trò chơi và kể những câu chuyện vui dưới một cây lớn."
  },
  {
    "id": 133,
    "word": "stories",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈɔriːz/",
    "meaning": "câu chuyện",
    "ex1": "On most days, we eat sandwiches, play games, and tell funny stories under a big tree.",
    "ex1_vi": "Trong hầu hết các ngày, chúng tôi ăn bánh mì kẹp, chơi trò chơi và kể những câu chuyện vui dưới một cây lớn."
  },
  {
    "id": 134,
    "word": "big",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɪɡ/",
    "meaning": "lớn",
    "ex1": "During a park visit, we eat sandwiches, play games, and tell funny stories under a big tree.",
    "ex1_vi": "Trong một lần đến công viên, chúng tôi ăn bánh mì kẹp, chơi trò chơi và kể những câu chuyện vui dưới một cây lớn."
  },
  {
    "id": 135,
    "word": "tree",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈiː/",
    "meaning": "cây",
    "ex1": "For many visitors, we eat sandwiches, play games, and tell funny stories under a big tree.",
    "ex1_vi": "Đối với nhiều khách tham quan, chúng tôi ăn bánh mì kẹp, chơi trò chơi và kể những câu chuyện vui dưới một cây lớn."
  },
  {
    "id": 136,
    "word": "brother",
    "type": "noun",
    "cat": "n",
    "phonetic": "/brˈʌðɝ/",
    "meaning": "anh/em trai",
    "ex1": "My brother flies a kite while my parents take photos.",
    "ex1_vi": "Em trai tôi thả diều trong khi bố mẹ tôi chụp ảnh."
  },
  {
    "id": 137,
    "word": "flies",
    "type": "verb",
    "cat": "v",
    "phonetic": "/flˈaɪz/",
    "meaning": "thả; bay",
    "ex1": "My brother flies a kite while my parents take photos.",
    "ex1_vi": "Em trai tôi thả diều trong khi bố mẹ tôi chụp ảnh."
  },
  {
    "id": 138,
    "word": "kite",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈaɪt/",
    "meaning": "cái diều",
    "ex1": "Usually, my brother flies a kite while my parents take photos.",
    "ex1_vi": "Thông thường, em trai tôi thả diều trong khi bố mẹ tôi chụp ảnh."
  },
  {
    "id": 139,
    "word": "lunch",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈʌntʃ/",
    "meaning": "bữa trưa",
    "ex1": "After lunch, we walk around the lake and enjoy the beautiful flowers together.",
    "ex1_vi": "Sau bữa trưa, chúng tôi đi bộ quanh hồ và cùng nhau ngắm những bông hoa đẹp."
  },
  {
    "id": 140,
    "word": "creates",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kɹiːˈeɪts/",
    "meaning": "tạo ra",
    "ex1": "A family picnic creates wonderful memories for everyone.",
    "ex1_vi": "Một buổi dã ngoại gia đình tạo nên những kỷ niệm tuyệt vời cho mọi người."
  },
  {
    "id": 141,
    "word": "wonderful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈʌndɝfʌl/",
    "meaning": "tuyệt vời",
    "ex1": "A family picnic creates wonderful memories for everyone.",
    "ex1_vi": "Một buổi dã ngoại gia đình tạo nên những kỷ niệm tuyệt vời cho mọi người."
  },
  {
    "id": 142,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "It helps us relax, laugh, and talk without busy schedules.",
    "ex1_vi": "Nó giúp chúng tôi thư giãn, cười nói và trò chuyện mà không bị lịch trình bận rộn chi phối."
  },
  {
    "id": 143,
    "word": "laugh",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈæf/",
    "meaning": "cười",
    "ex1": "It helps us relax, laugh, and talk without busy schedules.",
    "ex1_vi": "Nó giúp chúng tôi thư giãn, cười nói và trò chuyện mà không bị lịch trình bận rộn chi phối."
  },
  {
    "id": 144,
    "word": "talk",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈɔːk/",
    "meaning": "nói chuyện",
    "ex1": "Usually, it helps us relax, laugh, and talk without busy schedules.",
    "ex1_vi": "Thông thường, nó giúp chúng tôi thư giãn, cười nói và trò chuyện mà không bị lịch trình bận rộn chi phối."
  },
  {
    "id": 145,
    "word": "busy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɪzi/",
    "meaning": "nhộn nhịp",
    "ex1": "Often, it helps us relax, laugh, and talk without busy schedules.",
    "ex1_vi": "Thường thì, nó giúp chúng tôi thư giãn, cười nói và trò chuyện mà không bị lịch trình bận rộn chi phối."
  },
  {
    "id": 146,
    "word": "schedules",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɛdʒʊlz/",
    "meaning": "lịch trình",
    "ex1": "On most days, it helps us relax, laugh, and talk without busy schedules.",
    "ex1_vi": "Trong hầu hết các ngày, nó giúp chúng tôi thư giãn, cười nói và trò chuyện mà không bị lịch trình bận rộn chi phối."
  },
  {
    "id": 147,
    "word": "going",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈoʊɪŋ/",
    "meaning": "đi",
    "ex1": "Before going home, we clean the area carefully and throw all trash into the bins properly.",
    "ex1_vi": "Trước khi về nhà, chúng tôi dọn sạch khu vực cẩn thận và bỏ toàn bộ rác vào thùng đúng cách."
  },
  {
    "id": 148,
    "word": "home",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hoʊm/",
    "meaning": "nơi sinh sống; nhà",
    "ex1": "Before going home, we clean the area carefully and throw all trash into the bins properly.",
    "ex1_vi": "Trước khi về nhà, chúng tôi dọn sạch khu vực cẩn thận và bỏ toàn bộ rác vào thùng đúng cách."
  },
  {
    "id": 149,
    "word": "area",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛriːʌ/",
    "meaning": "khu vực",
    "ex1": "Usually, before going home, we clean the area carefully and throw all trash into the bins properly.",
    "ex1_vi": "Thông thường, trước khi về nhà, chúng tôi dọn sạch khu vực cẩn thận và bỏ toàn bộ rác vào thùng đúng cách."
  },
  {
    "id": 150,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈeəfəli/",
    "meaning": "cẩn thận",
    "ex1": "Often, before going home, we clean the area carefully and throw all trash into the bins properly.",
    "ex1_vi": "Thường thì, trước khi về nhà, chúng tôi dọn sạch khu vực cẩn thận và bỏ toàn bộ rác vào thùng đúng cách."
  },
  {
    "id": 151,
    "word": "throw",
    "type": "verb",
    "cat": "v",
    "phonetic": "/θrˈoʊ/",
    "meaning": "vứt; ném",
    "ex1": "On most days, before going home, we clean the area carefully and throw all trash into the bins properly.",
    "ex1_vi": "Trong hầu hết các ngày, trước khi về nhà, chúng tôi dọn sạch khu vực cẩn thận và bỏ toàn bộ rác vào thùng đúng cách."
  },
  {
    "id": 152,
    "word": "all",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɔl/",
    "meaning": "tất cả",
    "ex1": "During a park visit, before going home, we clean the area carefully and throw all trash into the bins properly.",
    "ex1_vi": "Trong một lần đến công viên, trước khi về nhà, chúng tôi dọn sạch khu vực cẩn thận và bỏ toàn bộ rác vào thùng đúng cách."
  },
  {
    "id": 153,
    "word": "properly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/prˈɑpɝliː/",
    "meaning": "đúng cách",
    "ex1": "For many visitors, before going home, we clean the area carefully and throw all trash into the bins properly.",
    "ex1_vi": "Đối với nhiều khách tham quan, trước khi về nhà, chúng tôi dọn sạch khu vực cẩn thận và bỏ toàn bộ rác vào thùng đúng cách."
  }
];

const newReadingVocabOrder = [
  "beautiful",
  "park",
  "peaceful",
  "place",
  "where",
  "people",
  "relax",
  "and",
  "enjoy",
  "nature",
  "has",
  "green",
  "grass",
  "colorful",
  "flowers",
  "tall",
  "trees",
  "clean",
  "walking",
  "paths",
  "families",
  "children",
  "friends",
  "often",
  "visit",
  "school",
  "or",
  "work",
  "together",
  "can",
  "walk",
  "jog",
  "ride",
  "bicycles",
  "sit",
  "benches",
  "play",
  "swings",
  "slides",
  "while",
  "parents",
  "watch",
  "happily",
  "some",
  "visitors",
  "read",
  "books",
  "take",
  "photos",
  "feed",
  "ducks",
  "small",
  "lake",
  "every",
  "weekend",
  "makes",
  "city",
  "cleaner",
  "more",
  "enjoyable",
  "gives",
  "fresh",
  "air",
  "quiet",
  "spaces",
  "happy",
  "memories",
  "everyone",
  "should",
  "keep",
  "using",
  "trash",
  "bins",
  "protecting",
  "day",
  "activities",
  "many",
  "different",
  "parks",
  "safe",
  "places",
  "neighbors",
  "spend",
  "time",
  "exercise",
  "outside",
  "around",
  "run",
  "games",
  "fly",
  "kites",
  "climb",
  "playground",
  "equipment",
  "others",
  "have",
  "picnics",
  "listen",
  "music",
  "birds",
  "sunny",
  "afternoons",
  "help",
  "stay",
  "healthy",
  "spending",
  "reduces",
  "stress",
  "energy",
  "respect",
  "kindness",
  "care",
  "family",
  "picnic",
  "enjoys",
  "having",
  "weekends",
  "bring",
  "delicious",
  "food",
  "cold",
  "drinks",
  "fruits",
  "large",
  "blanket",
  "feels",
  "excited",
  "because",
  "eat",
  "sandwiches",
  "tell",
  "funny",
  "stories",
  "big",
  "tree",
  "brother",
  "flies",
  "kite",
  "lunch",
  "creates",
  "wonderful",
  "helps",
  "laugh",
  "talk",
  "busy",
  "schedules",
  "going",
  "home",
  "area",
  "carefully",
  "throw",
  "all",
  "properly"
];
