// ===== park01 ESSAY =====

const newEssayData = [
  {
    "text": "1. A Beautiful Park\nA beautiful park is a peaceful place where people relax and enjoy nature. It has green grass, colorful flowers, tall trees, and clean walking paths. Families, children, and friends often visit the park after school or work together.\n\nPeople can walk, jog, ride bicycles, or sit on benches. Children play on swings and slides while parents watch happily. Some visitors read books, take photos, or feed ducks near the small lake every weekend.\n\nA beautiful park makes the city cleaner and more enjoyable. It gives fresh air, quiet spaces, and happy memories for everyone. People should keep the park clean by using trash bins and protecting nature every day.",
    "vi": "1. Một Công Viên Đẹp\nMột công viên đẹp là nơi yên bình để mọi người thư giãn và tận hưởng thiên nhiên. Công viên có cỏ xanh, hoa nhiều màu sắc, cây cao và những lối đi bộ sạch sẽ. Các gia đình, trẻ em và bạn bè thường đến công viên sau giờ học hoặc giờ làm việc.\n\nMọi người có thể đi bộ, chạy bộ, đi xe đạp hoặc ngồi trên ghế băng. Trẻ em chơi xích đu và cầu trượt trong khi cha mẹ vui vẻ quan sát. Một số khách tham quan đọc sách, chụp ảnh hoặc cho vịt ăn gần hồ nhỏ vào mỗi cuối tuần.\n\nMột công viên đẹp làm cho thành phố sạch hơn và thú vị hơn. Công viên mang lại không khí trong lành, những không gian yên tĩnh và những kỷ niệm vui cho mọi người. Mọi người nên giữ công viên sạch sẽ bằng cách sử dụng thùng rác và bảo vệ thiên nhiên mỗi ngày."
  },
  {
    "text": "2. Park Activities\nMany people enjoy different activities in the park every day. Parks are safe places where families, friends, and neighbors spend time together. Visitors can exercise, relax, and enjoy the fresh air outside happily.\n\nSome people walk around the park or run on the paths. Children play games, fly kites, and climb on playground equipment. Others have picnics, listen to music, or watch birds in the trees during sunny afternoons.\n\nPark activities help people stay healthy and happy. Spending time outside reduces stress and gives everyone more energy. People should respect others, keep the park clean, and enjoy every visit with kindness and care.",
    "vi": "2. Các Hoạt Động Trong Công Viên\nNhiều người tận hưởng các hoạt động khác nhau trong công viên mỗi ngày. Công viên là nơi an toàn để gia đình, bạn bè và hàng xóm dành thời gian bên nhau. Khách tham quan có thể tập thể dục, thư giãn và vui vẻ tận hưởng không khí trong lành ngoài trời.\n\nMột số người đi bộ quanh công viên hoặc chạy trên các lối đi. Trẻ em chơi trò chơi, thả diều và leo trèo trên thiết bị sân chơi. Những người khác đi dã ngoại, nghe nhạc hoặc ngắm chim trên cây vào những buổi chiều nắng.\n\nCác hoạt động trong công viên giúp mọi người khỏe mạnh và vui vẻ. Dành thời gian ngoài trời giúp giảm căng thẳng và mang lại cho mọi người nhiều năng lượng hơn. Mọi người nên tôn trọng người khác, giữ công viên sạch sẽ và tận hưởng mỗi lần ghé thăm với sự tử tế và quan tâm."
  },
  {
    "text": "3. A Family Picnic\nMy family enjoys having a picnic in the park on weekends. We bring delicious food, cold drinks, fruits, and a large blanket. Everyone feels excited because we can spend happy time together outside.\n\nWe eat sandwiches, play games, and tell funny stories under a big tree. My brother flies a kite while my parents take photos. After lunch, we walk around the lake and enjoy the beautiful flowers together.\n\nA family picnic creates wonderful memories for everyone. It helps us relax, laugh, and talk without busy schedules. Before going home, we clean the area carefully and throw all trash into the bins properly.",
    "vi": "3. Một Buổi Dã Ngoại Gia Đình\nGia đình tôi thích đi dã ngoại trong công viên vào cuối tuần. Chúng tôi mang theo thức ăn ngon, đồ uống lạnh, trái cây và một tấm chăn lớn. Mọi người đều cảm thấy hào hứng vì chúng tôi có thể vui vẻ dành thời gian bên nhau ngoài trời.\n\nChúng tôi ăn bánh mì kẹp, chơi trò chơi và kể những câu chuyện vui dưới một cây lớn. Em trai tôi thả diều trong khi bố mẹ tôi chụp ảnh. Sau bữa trưa, chúng tôi đi bộ quanh hồ và cùng nhau ngắm những bông hoa đẹp.\n\nMột buổi dã ngoại gia đình tạo nên những kỷ niệm tuyệt vời cho mọi người. Nó giúp chúng tôi thư giãn, cười nói và trò chuyện mà không bị lịch trình bận rộn chi phối. Trước khi về nhà, chúng tôi dọn sạch khu vực cẩn thận và bỏ toàn bộ rác vào thùng đúng cách."
  }
];
