// ===== office02 VOCABULARY =====

const lessonVocabularyWords = [
  "team",
  "meeting",
  "helps",
  "workers",
  "discuss",
  "projects",
  "and",
  "share",
  "useful",
  "ideas",
  "everyone",
  "gathers",
  "one",
  "room",
  "or",
  "joins",
  "online",
  "meetings",
  "help",
  "people",
  "understand",
  "goals",
  "solve",
  "problems",
  "work",
  "together",
  "better",
  "every",
  "single",
  "day",
  "successfully",
  "during",
  "person",
  "gives",
  "opinions",
  "listens",
  "carefully",
  "manager",
  "explains",
  "plans",
  "assigns",
  "tasks",
  "members",
  "ask",
  "questions",
  "suggest",
  "improvements",
  "agree",
  "best",
  "solutions",
  "future",
  "after",
  "knows",
  "do",
  "next",
  "complete",
  "support",
  "good",
  "improve",
  "communication",
  "build",
  "stronger",
  "teamwork",
  "company",
  "achieve",
  "results",
  "week",
  "office",
  "rules",
  "has",
  "important",
  "keep",
  "organized",
  "comfortable",
  "employees",
  "should",
  "before",
  "starting",
  "jobs",
  "following",
  "creates",
  "friendly",
  "environment",
  "can",
  "peacefully",
  "arrive",
  "time",
  "finish",
  "deadlines",
  "speak",
  "quietly",
  "wear",
  "suitable",
  "clothes",
  "respect",
  "coworkers",
  "keeping",
  "desks",
  "clean",
  "policies",
  "also",
  "shows",
  "responsibility",
  "professional",
  "behavior",
  "always",
  "safely",
  "happily",
  "feels",
  "respected",
  "when",
  "follow",
  "standards",
  "well",
  "workplace",
  "improves",
  "increases",
  "productivity",
  "success",
  "whole",
  "working",
  "because",
  "brings",
  "another",
  "faster",
  "positive",
  "daily",
  "someone",
  "needs",
  "offer",
  "advice",
  "communicate",
  "clearly",
  "different",
  "trust",
  "relationships",
  "make",
  "easier",
  "reduce",
  "stress",
  "busy",
  "days",
  "successful",
  "teams",
  "celebrate",
  "achievements",
  "learn",
  "mistakes",
  "skills",
  "group",
  "succeed",
  "strong",
  "builds",
  "confidence",
  "happier"
];

const newVocabData = [
  {
    "id": 1,
    "word": "team",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈiːm/",
    "meaning": "nhóm",
    "ex1": "A team meeting helps workers discuss projects and share useful ideas.",
    "ex1_vi": "Một cuộc họp nhóm giúp nhân viên thảo luận các dự án và chia sẻ những ý tưởng hữu ích."
  },
  {
    "id": 2,
    "word": "meeting",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈiːtɪŋ/",
    "meaning": "cuộc họp",
    "ex1": "A team meeting helps workers discuss projects and share useful ideas.",
    "ex1_vi": "Một cuộc họp nhóm giúp nhân viên thảo luận các dự án và chia sẻ những ý tưởng hữu ích."
  },
  {
    "id": 3,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "During a normal workday, a team meeting helps workers discuss projects and share useful ideas.",
    "ex1_vi": "Trong một ngày làm việc bình thường, một cuộc họp nhóm giúp nhân viên thảo luận các dự án và chia sẻ những ý tưởng hữu ích."
  },
  {
    "id": 4,
    "word": "workers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɜːkəz/",
    "meaning": "nhân viên",
    "ex1": "In daily routines, a team meeting helps workers discuss projects and share useful ideas.",
    "ex1_vi": "Trong các thói quen hằng ngày, một cuộc họp nhóm giúp nhân viên thảo luận các dự án và chia sẻ những ý tưởng hữu ích."
  },
  {
    "id": 5,
    "word": "discuss",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dɪskˈʌs/",
    "meaning": "thảo luận",
    "ex1": "During busy working hours, a team meeting helps workers discuss projects and share useful ideas.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, một cuộc họp nhóm giúp nhân viên thảo luận các dự án và chia sẻ những ý tưởng hữu ích."
  },
  {
    "id": 6,
    "word": "projects",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɹˈɒdʒɛkts/",
    "meaning": "dự án",
    "ex1": "As part of regular work, a team meeting helps workers discuss projects and share useful ideas.",
    "ex1_vi": "Là một phần của công việc thường ngày, một cuộc họp nhóm giúp nhân viên thảo luận các dự án và chia sẻ những ý tưởng hữu ích."
  },
  {
    "id": 7,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈand/",
    "meaning": "và",
    "ex1": "On a typical weekday, a team meeting helps workers discuss projects and share useful ideas.",
    "ex1_vi": "Vào một ngày làm việc điển hình, một cuộc họp nhóm giúp nhân viên thảo luận các dự án và chia sẻ những ý tưởng hữu ích."
  },
  {
    "id": 8,
    "word": "share",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈeə/",
    "meaning": "chia sẻ",
    "ex1": "During ordinary office activities, a team meeting helps workers discuss projects and share useful ideas.",
    "ex1_vi": "Trong các hoạt động văn phòng thông thường, một cuộc họp nhóm giúp nhân viên thảo luận các dự án và chia sẻ những ý tưởng hữu ích."
  },
  {
    "id": 9,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈuːsfəl/",
    "meaning": "hữu ích",
    "ex1": "In everyday workplace routines, a team meeting helps workers discuss projects and share useful ideas.",
    "ex1_vi": "Trong các thói quen hằng ngày tại nơi làm việc, một cuộc họp nhóm giúp nhân viên thảo luận các dự án và chia sẻ những ý tưởng hữu ích."
  },
  {
    "id": 10,
    "word": "ideas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/aɪdˈiəz/",
    "meaning": "ý tưởng",
    "ex1": "Throughout the working day, a team meeting helps workers discuss projects and share useful ideas.",
    "ex1_vi": "Suốt ngày làm việc, một cuộc họp nhóm giúp nhân viên thảo luận các dự án và chia sẻ những ý tưởng hữu ích."
  },
  {
    "id": 11,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvɹɪwˌɒn/",
    "meaning": "mọi người",
    "ex1": "Everyone gathers in one room or joins online.",
    "ex1_vi": "Mọi người tập trung trong một phòng hoặc tham gia trực tuyến."
  },
  {
    "id": 12,
    "word": "gathers",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈaðəz/",
    "meaning": "tập trung",
    "ex1": "Everyone gathers in one room or joins online.",
    "ex1_vi": "Mọi người tập trung trong một phòng hoặc tham gia trực tuyến."
  },
  {
    "id": 13,
    "word": "one",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/wˈɒn/",
    "meaning": "một người; một",
    "ex1": "During a normal workday, everyone gathers in one room or joins online.",
    "ex1_vi": "Trong một ngày làm việc bình thường, mọi người tập trung trong một phòng hoặc tham gia trực tuyến."
  },
  {
    "id": 14,
    "word": "room",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɹˈuːm/",
    "meaning": "phòng",
    "ex1": "In daily routines, everyone gathers in one room or joins online.",
    "ex1_vi": "Trong các thói quen hằng ngày, mọi người tập trung trong một phòng hoặc tham gia trực tuyến."
  },
  {
    "id": 15,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔː/",
    "meaning": "hoặc",
    "ex1": "During busy working hours, everyone gathers in one room or joins online.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, mọi người tập trung trong một phòng hoặc tham gia trực tuyến."
  },
  {
    "id": 16,
    "word": "joins",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dʒˈɔɪnz/",
    "meaning": "tham gia",
    "ex1": "As part of regular work, everyone gathers in one room or joins online.",
    "ex1_vi": "Là một phần của công việc thường ngày, mọi người tập trung trong một phòng hoặc tham gia trực tuyến."
  },
  {
    "id": 17,
    "word": "online",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɒnlaɪn/",
    "meaning": "trực tuyến",
    "ex1": "On a typical weekday, everyone gathers in one room or joins online.",
    "ex1_vi": "Vào một ngày làm việc điển hình, mọi người tập trung trong một phòng hoặc tham gia trực tuyến."
  },
  {
    "id": 18,
    "word": "meetings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈiːtɪŋz/",
    "meaning": "các cuộc họp",
    "ex1": "Meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 19,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "Meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 20,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈiːpəl/",
    "meaning": "mọi người",
    "ex1": "During a normal workday, meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Trong một ngày làm việc bình thường, các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 21,
    "word": "understand",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌʌndəstˈand/",
    "meaning": "hiểu",
    "ex1": "In daily routines, meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Trong các thói quen hằng ngày, các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 22,
    "word": "goals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈəʊlz/",
    "meaning": "các mục tiêu",
    "ex1": "During busy working hours, meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 23,
    "word": "solve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɒlv/",
    "meaning": "giải quyết",
    "ex1": "As part of regular work, meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Là một phần của công việc thường ngày, các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 24,
    "word": "problems",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɹˈɒbləmz/",
    "meaning": "vấn đề",
    "ex1": "On a typical weekday, meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Vào một ngày làm việc điển hình, các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 25,
    "word": "work",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɜːk/",
    "meaning": "làm việc",
    "ex1": "During ordinary office activities, meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Trong các hoạt động văn phòng thông thường, các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 26,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/təɡˈɛðə/",
    "meaning": "cùng nhau",
    "ex1": "In everyday workplace routines, meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Trong các thói quen hằng ngày tại nơi làm việc, các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 27,
    "word": "better",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/bˈɛtə/",
    "meaning": "tốt hơn",
    "ex1": "Throughout the working day, meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Suốt ngày làm việc, các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 28,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɹɪ/",
    "meaning": "mỗi",
    "ex1": "During a busy morning, meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Trong một buổi sáng bận rộn, các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 29,
    "word": "single",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪŋɡəl/",
    "meaning": "duy nhất",
    "ex1": "In regular daily tasks, meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Trong các nhiệm vụ hằng ngày, các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 30,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "During normal working hours, meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Trong giờ làm việc bình thường, các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 31,
    "word": "successfully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/səksˈɛsfəli/",
    "meaning": "một cách thành công",
    "ex1": "As part of the team's routine, meetings help people understand goals, solve problems, and work together better every single day successfully.",
    "ex1_vi": "Là một phần trong thói quen của cả nhóm, các cuộc họp giúp mọi người hiểu mục tiêu, giải quyết vấn đề và làm việc cùng nhau tốt hơn mỗi ngày."
  },
  {
    "id": 32,
    "word": "during",
    "type": "preposition",
    "cat": "prep",
    "phonetic": "/djˈʊəɹɪŋ/",
    "meaning": "trong suốt",
    "ex1": "During the meeting, each person gives opinions and listens carefully.",
    "ex1_vi": "Trong cuộc họp, mỗi người đưa ra ý kiến và lắng nghe cẩn thận."
  },
  {
    "id": 33,
    "word": "person",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɜːsən/",
    "meaning": "người",
    "ex1": "During the meeting, each person gives opinions and listens carefully.",
    "ex1_vi": "Trong cuộc họp, mỗi người đưa ra ý kiến và lắng nghe cẩn thận."
  },
  {
    "id": 34,
    "word": "gives",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvz/",
    "meaning": "đưa ra",
    "ex1": "During a normal workday, during the meeting, each person gives opinions and listens carefully.",
    "ex1_vi": "Trong một ngày làm việc bình thường, trong cuộc họp, mỗi người đưa ra ý kiến và lắng nghe cẩn thận."
  },
  {
    "id": 35,
    "word": "opinions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/əpˈɪniənz/",
    "meaning": "ý kiến",
    "ex1": "In daily routines, during the meeting, each person gives opinions and listens carefully.",
    "ex1_vi": "Trong các thói quen hằng ngày, trong cuộc họp, mỗi người đưa ra ý kiến và lắng nghe cẩn thận."
  },
  {
    "id": 36,
    "word": "listens",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɪsənz/",
    "meaning": "lắng nghe",
    "ex1": "During busy working hours, during the meeting, each person gives opinions and listens carefully.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, trong cuộc họp, mỗi người đưa ra ý kiến và lắng nghe cẩn thận."
  },
  {
    "id": 37,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈeəfəli/",
    "meaning": "cẩn thận",
    "ex1": "As part of regular work, during the meeting, each person gives opinions and listens carefully.",
    "ex1_vi": "Là một phần của công việc thường ngày, trong cuộc họp, mỗi người đưa ra ý kiến và lắng nghe cẩn thận."
  },
  {
    "id": 38,
    "word": "manager",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈanɪdʒə/",
    "meaning": "quản lý",
    "ex1": "The manager explains plans and assigns tasks.",
    "ex1_vi": "Người quản lý giải thích kế hoạch và phân công nhiệm vụ."
  },
  {
    "id": 39,
    "word": "explains",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɛksplˈeɪnz/",
    "meaning": "giải thích",
    "ex1": "The manager explains plans and assigns tasks.",
    "ex1_vi": "Người quản lý giải thích kế hoạch và phân công nhiệm vụ."
  },
  {
    "id": 40,
    "word": "plans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈanz/",
    "meaning": "kế hoạch",
    "ex1": "During a normal workday, the manager explains plans and assigns tasks.",
    "ex1_vi": "Trong một ngày làm việc bình thường, người quản lý giải thích kế hoạch và phân công nhiệm vụ."
  },
  {
    "id": 41,
    "word": "assigns",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɐsˈaɪnz/",
    "meaning": "phân công",
    "ex1": "In daily routines, the manager explains plans and assigns tasks.",
    "ex1_vi": "Trong các thói quen hằng ngày, người quản lý giải thích kế hoạch và phân công nhiệm vụ."
  },
  {
    "id": 42,
    "word": "tasks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈasks/",
    "meaning": "nhiệm vụ",
    "ex1": "During busy working hours, the manager explains plans and assigns tasks.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, người quản lý giải thích kế hoạch và phân công nhiệm vụ."
  },
  {
    "id": 43,
    "word": "members",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛmbəz/",
    "meaning": "thành viên",
    "ex1": "Team members ask questions, suggest improvements, and agree on the best solutions for future work together.",
    "ex1_vi": "Các thành viên trong nhóm đặt câu hỏi, đề xuất cải tiến và thống nhất những giải pháp tốt nhất cho công việc tương lai."
  },
  {
    "id": 44,
    "word": "ask",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈask/",
    "meaning": "hỏi",
    "ex1": "Team members ask questions, suggest improvements, and agree on the best solutions for future work together.",
    "ex1_vi": "Các thành viên trong nhóm đặt câu hỏi, đề xuất cải tiến và thống nhất những giải pháp tốt nhất cho công việc tương lai."
  },
  {
    "id": 45,
    "word": "questions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kwˈɛstʃənz/",
    "meaning": "câu hỏi",
    "ex1": "During a normal workday, team members ask questions, suggest improvements, and agree on the best solutions for future work together.",
    "ex1_vi": "Trong một ngày làm việc bình thường, các thành viên trong nhóm đặt câu hỏi, đề xuất cải tiến và thống nhất những giải pháp tốt nhất cho công việc tương lai."
  },
  {
    "id": 46,
    "word": "suggest",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sədʒˈɛst/",
    "meaning": "đề xuất",
    "ex1": "In daily routines, team members ask questions, suggest improvements, and agree on the best solutions for future work together.",
    "ex1_vi": "Trong các thói quen hằng ngày, các thành viên trong nhóm đặt câu hỏi, đề xuất cải tiến và thống nhất những giải pháp tốt nhất cho công việc tương lai."
  },
  {
    "id": 47,
    "word": "improvements",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪmpɹˈuːvmənts/",
    "meaning": "sự cải tiến",
    "ex1": "During busy working hours, team members ask questions, suggest improvements, and agree on the best solutions for future work together.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, các thành viên trong nhóm đặt câu hỏi, đề xuất cải tiến và thống nhất những giải pháp tốt nhất cho công việc tương lai."
  },
  {
    "id": 48,
    "word": "agree",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɐɡɹˈiː/",
    "meaning": "đồng ý",
    "ex1": "As part of regular work, team members ask questions, suggest improvements, and agree on the best solutions for future work together.",
    "ex1_vi": "Là một phần của công việc thường ngày, các thành viên trong nhóm đặt câu hỏi, đề xuất cải tiến và thống nhất những giải pháp tốt nhất cho công việc tương lai."
  },
  {
    "id": 49,
    "word": "best",
    "type": "superlative adjective",
    "cat": "adj",
    "phonetic": "/bˈɛst/",
    "meaning": "tốt nhất",
    "ex1": "On a typical weekday, team members ask questions, suggest improvements, and agree on the best solutions for future work together.",
    "ex1_vi": "Vào một ngày làm việc điển hình, các thành viên trong nhóm đặt câu hỏi, đề xuất cải tiến và thống nhất những giải pháp tốt nhất cho công việc tương lai."
  },
  {
    "id": 50,
    "word": "solutions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/səlˈuːʃənz/",
    "meaning": "các giải pháp",
    "ex1": "During ordinary office activities, team members ask questions, suggest improvements, and agree on the best solutions for future work together.",
    "ex1_vi": "Trong các hoạt động văn phòng thông thường, các thành viên trong nhóm đặt câu hỏi, đề xuất cải tiến và thống nhất những giải pháp tốt nhất cho công việc tương lai."
  },
  {
    "id": 51,
    "word": "future",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fjˈuːtʃə/",
    "meaning": "tương lai",
    "ex1": "In everyday workplace routines, team members ask questions, suggest improvements, and agree on the best solutions for future work together.",
    "ex1_vi": "Trong các thói quen hằng ngày tại nơi làm việc, các thành viên trong nhóm đặt câu hỏi, đề xuất cải tiến và thống nhất những giải pháp tốt nhất cho công việc tương lai."
  },
  {
    "id": 52,
    "word": "after",
    "type": "preposition",
    "cat": "prep",
    "phonetic": "/ˈaftə/",
    "meaning": "sau",
    "ex1": "After the meeting, everyone knows what to do next.",
    "ex1_vi": "Sau cuộc họp, mọi người biết mình cần làm gì tiếp theo."
  },
  {
    "id": 53,
    "word": "knows",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈəʊz/",
    "meaning": "biết",
    "ex1": "After the meeting, everyone knows what to do next.",
    "ex1_vi": "Sau cuộc họp, mọi người biết mình cần làm gì tiếp theo."
  },
  {
    "id": 54,
    "word": "do",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈuː/",
    "meaning": "làm",
    "ex1": "During a normal workday, after the meeting, everyone knows what to do next.",
    "ex1_vi": "Trong một ngày làm việc bình thường, sau cuộc họp, mọi người biết mình cần làm gì tiếp theo."
  },
  {
    "id": 55,
    "word": "next",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɛkst/",
    "meaning": "tiếp theo",
    "ex1": "In daily routines, after the meeting, everyone knows what to do next.",
    "ex1_vi": "Trong các thói quen hằng ngày, sau cuộc họp, mọi người biết mình cần làm gì tiếp theo."
  },
  {
    "id": 56,
    "word": "complete",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kəmplˈiːt/",
    "meaning": "hoàn thành",
    "ex1": "Workers complete their tasks and support each other.",
    "ex1_vi": "Nhân viên hoàn thành nhiệm vụ và hỗ trợ lẫn nhau."
  },
  {
    "id": 57,
    "word": "support",
    "type": "verb",
    "cat": "v",
    "phonetic": "/səpˈɔːt/",
    "meaning": "hỗ trợ",
    "ex1": "Workers complete their tasks and support each other.",
    "ex1_vi": "Nhân viên hoàn thành nhiệm vụ và hỗ trợ lẫn nhau."
  },
  {
    "id": 58,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "Good meetings improve communication, build stronger teamwork, and help the company achieve better results every single week.",
    "ex1_vi": "Những cuộc họp tốt cải thiện giao tiếp, xây dựng tinh thần làm việc nhóm mạnh hơn và giúp công ty đạt kết quả tốt hơn mỗi tuần."
  },
  {
    "id": 59,
    "word": "improve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɪmpɹˈuːv/",
    "meaning": "cải thiện",
    "ex1": "Good meetings improve communication, build stronger teamwork, and help the company achieve better results every single week.",
    "ex1_vi": "Những cuộc họp tốt cải thiện giao tiếp, xây dựng tinh thần làm việc nhóm mạnh hơn và giúp công ty đạt kết quả tốt hơn mỗi tuần."
  },
  {
    "id": 60,
    "word": "communication",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kəmjˌuːnɪkˈeɪʃən/",
    "meaning": "sự giao tiếp",
    "ex1": "During a normal workday, good meetings improve communication, build stronger teamwork, and help the company achieve better results every single week.",
    "ex1_vi": "Trong một ngày làm việc bình thường, những cuộc họp tốt cải thiện giao tiếp, xây dựng tinh thần làm việc nhóm mạnh hơn và giúp công ty đạt kết quả tốt hơn mỗi tuần."
  },
  {
    "id": 61,
    "word": "build",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɪld/",
    "meaning": "xây dựng",
    "ex1": "In daily routines, good meetings improve communication, build stronger teamwork, and help the company achieve better results every single week.",
    "ex1_vi": "Trong các thói quen hằng ngày, những cuộc họp tốt cải thiện giao tiếp, xây dựng tinh thần làm việc nhóm mạnh hơn và giúp công ty đạt kết quả tốt hơn mỗi tuần."
  },
  {
    "id": 62,
    "word": "stronger",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/stɹˈɒŋɡə/",
    "meaning": "khỏe hơn",
    "ex1": "During busy working hours, good meetings improve communication, build stronger teamwork, and help the company achieve better results every single week.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, những cuộc họp tốt cải thiện giao tiếp, xây dựng tinh thần làm việc nhóm mạnh hơn và giúp công ty đạt kết quả tốt hơn mỗi tuần."
  },
  {
    "id": 63,
    "word": "teamwork",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈiːmwɜːk/",
    "meaning": "tinh thần đồng đội",
    "ex1": "As part of regular work, good meetings improve communication, build stronger teamwork, and help the company achieve better results every single week.",
    "ex1_vi": "Là một phần của công việc thường ngày, những cuộc họp tốt cải thiện giao tiếp, xây dựng tinh thần làm việc nhóm mạnh hơn và giúp công ty đạt kết quả tốt hơn mỗi tuần."
  },
  {
    "id": 64,
    "word": "company",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌmpəni/",
    "meaning": "công ty",
    "ex1": "On a typical weekday, good meetings improve communication, build stronger teamwork, and help the company achieve better results every single week.",
    "ex1_vi": "Vào một ngày làm việc điển hình, những cuộc họp tốt cải thiện giao tiếp, xây dựng tinh thần làm việc nhóm mạnh hơn và giúp công ty đạt kết quả tốt hơn mỗi tuần."
  },
  {
    "id": 65,
    "word": "achieve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɐtʃˈiːv/",
    "meaning": "đạt được",
    "ex1": "During ordinary office activities, good meetings improve communication, build stronger teamwork, and help the company achieve better results every single week.",
    "ex1_vi": "Trong các hoạt động văn phòng thông thường, những cuộc họp tốt cải thiện giao tiếp, xây dựng tinh thần làm việc nhóm mạnh hơn và giúp công ty đạt kết quả tốt hơn mỗi tuần."
  },
  {
    "id": 66,
    "word": "results",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɹɪzˈʌlts/",
    "meaning": "kết quả",
    "ex1": "In everyday workplace routines, good meetings improve communication, build stronger teamwork, and help the company achieve better results every single week.",
    "ex1_vi": "Trong các thói quen hằng ngày tại nơi làm việc, những cuộc họp tốt cải thiện giao tiếp, xây dựng tinh thần làm việc nhóm mạnh hơn và giúp công ty đạt kết quả tốt hơn mỗi tuần."
  },
  {
    "id": 67,
    "word": "week",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈiːk/",
    "meaning": "tuần",
    "ex1": "Throughout the working day, good meetings improve communication, build stronger teamwork, and help the company achieve better results every single week.",
    "ex1_vi": "Suốt ngày làm việc, những cuộc họp tốt cải thiện giao tiếp, xây dựng tinh thần làm việc nhóm mạnh hơn và giúp công ty đạt kết quả tốt hơn mỗi tuần."
  },
  {
    "id": 68,
    "word": "office",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɒfɪs/",
    "meaning": "văn phòng",
    "ex1": "Every office has important rules to keep work organized and comfortable.",
    "ex1_vi": "Mỗi văn phòng đều có những quy tắc quan trọng để giữ công việc có tổ chức và thoải mái."
  },
  {
    "id": 69,
    "word": "rules",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɹˈuːlz/",
    "meaning": "quy tắc",
    "ex1": "Every office has important rules to keep work organized and comfortable.",
    "ex1_vi": "Mỗi văn phòng đều có những quy tắc quan trọng để giữ công việc có tổ chức và thoải mái."
  },
  {
    "id": 70,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈaz/",
    "meaning": "có",
    "ex1": "During a normal workday, every office has important rules to keep work organized and comfortable.",
    "ex1_vi": "Trong một ngày làm việc bình thường, mỗi văn phòng đều có những quy tắc quan trọng để giữ công việc có tổ chức và thoải mái."
  },
  {
    "id": 71,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪmpˈɔːtənt/",
    "meaning": "quan trọng",
    "ex1": "In daily routines, every office has important rules to keep work organized and comfortable.",
    "ex1_vi": "Trong các thói quen hằng ngày, mỗi văn phòng đều có những quy tắc quan trọng để giữ công việc có tổ chức và thoải mái."
  },
  {
    "id": 72,
    "word": "keep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈiːp/",
    "meaning": "giữ; duy trì",
    "ex1": "During busy working hours, every office has important rules to keep work organized and comfortable.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, mỗi văn phòng đều có những quy tắc quan trọng để giữ công việc có tổ chức và thoải mái."
  },
  {
    "id": 73,
    "word": "organized",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɔːɡɐnˌaɪzd/",
    "meaning": "có tổ chức; ngăn nắp",
    "ex1": "As part of regular work, every office has important rules to keep work organized and comfortable.",
    "ex1_vi": "Là một phần của công việc thường ngày, mỗi văn phòng đều có những quy tắc quan trọng để giữ công việc có tổ chức và thoải mái."
  },
  {
    "id": 74,
    "word": "comfortable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌmftəbəl/",
    "meaning": "thoải mái",
    "ex1": "On a typical weekday, every office has important rules to keep work organized and comfortable.",
    "ex1_vi": "Vào một ngày làm việc điển hình, mỗi văn phòng đều có những quy tắc quan trọng để giữ công việc có tổ chức và thoải mái."
  },
  {
    "id": 75,
    "word": "employees",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɛmplˈɔɪiːz/",
    "meaning": "nhân viên",
    "ex1": "Employees should understand these rules before starting their jobs.",
    "ex1_vi": "Nhân viên nên hiểu những quy tắc này trước khi bắt đầu công việc."
  },
  {
    "id": 76,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "Employees should understand these rules before starting their jobs.",
    "ex1_vi": "Nhân viên nên hiểu những quy tắc này trước khi bắt đầu công việc."
  },
  {
    "id": 77,
    "word": "before",
    "type": "preposition",
    "cat": "prep",
    "phonetic": "/bɪfˈɔː/",
    "meaning": "trước",
    "ex1": "During a normal workday, employees should understand these rules before starting their jobs.",
    "ex1_vi": "Trong một ngày làm việc bình thường, nhân viên nên hiểu những quy tắc này trước khi bắt đầu công việc."
  },
  {
    "id": 78,
    "word": "starting",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/stˈɑːtɪŋ/",
    "meaning": "việc bắt đầu",
    "ex1": "In daily routines, employees should understand these rules before starting their jobs.",
    "ex1_vi": "Trong các thói quen hằng ngày, nhân viên nên hiểu những quy tắc này trước khi bắt đầu công việc."
  },
  {
    "id": 79,
    "word": "jobs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɒbz/",
    "meaning": "công việc",
    "ex1": "During busy working hours, employees should understand these rules before starting their jobs.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, nhân viên nên hiểu những quy tắc này trước khi bắt đầu công việc."
  },
  {
    "id": 80,
    "word": "following",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/fˈɒləʊɪŋ/",
    "meaning": "việc tuân theo",
    "ex1": "Following office rules creates a friendly environment where everyone can work peacefully together every day.",
    "ex1_vi": "Tuân theo nội quy văn phòng tạo ra một môi trường thân thiện, nơi mọi người có thể làm việc yên bình cùng nhau mỗi ngày."
  },
  {
    "id": 81,
    "word": "creates",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kɹiːˈeɪts/",
    "meaning": "tạo ra",
    "ex1": "Following office rules creates a friendly environment where everyone can work peacefully together every day.",
    "ex1_vi": "Tuân theo nội quy văn phòng tạo ra một môi trường thân thiện, nơi mọi người có thể làm việc yên bình cùng nhau mỗi ngày."
  },
  {
    "id": 82,
    "word": "friendly",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fɹˈɛndli/",
    "meaning": "thân thiện",
    "ex1": "During a normal workday, following office rules creates a friendly environment where everyone can work peacefully together every day.",
    "ex1_vi": "Trong một ngày làm việc bình thường, tuân theo nội quy văn phòng tạo ra một môi trường thân thiện, nơi mọi người có thể làm việc yên bình cùng nhau mỗi ngày."
  },
  {
    "id": 83,
    "word": "environment",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɛnvˈaɪɹənmənt/",
    "meaning": "môi trường",
    "ex1": "In daily routines, following office rules creates a friendly environment where everyone can work peacefully together every day.",
    "ex1_vi": "Trong các thói quen hằng ngày, tuân theo nội quy văn phòng tạo ra một môi trường thân thiện, nơi mọi người có thể làm việc yên bình cùng nhau mỗi ngày."
  },
  {
    "id": 84,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈan/",
    "meaning": "có thể",
    "ex1": "During busy working hours, following office rules creates a friendly environment where everyone can work peacefully together every day.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, tuân theo nội quy văn phòng tạo ra một môi trường thân thiện, nơi mọi người có thể làm việc yên bình cùng nhau mỗi ngày."
  },
  {
    "id": 85,
    "word": "peacefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/pˈiːsfəli/",
    "meaning": "một cách yên bình",
    "ex1": "As part of regular work, following office rules creates a friendly environment where everyone can work peacefully together every day.",
    "ex1_vi": "Là một phần của công việc thường ngày, tuân theo nội quy văn phòng tạo ra một môi trường thân thiện, nơi mọi người có thể làm việc yên bình cùng nhau mỗi ngày."
  },
  {
    "id": 86,
    "word": "arrive",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɐɹˈaɪv/",
    "meaning": "đến",
    "ex1": "Workers should arrive on time and finish tasks before deadlines.",
    "ex1_vi": "Nhân viên nên đến đúng giờ và hoàn thành nhiệm vụ trước thời hạn."
  },
  {
    "id": 87,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "Workers should arrive on time and finish tasks before deadlines.",
    "ex1_vi": "Nhân viên nên đến đúng giờ và hoàn thành nhiệm vụ trước thời hạn."
  },
  {
    "id": 88,
    "word": "finish",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɪnɪʃ/",
    "meaning": "đích",
    "ex1": "During a normal workday, workers should arrive on time and finish tasks before deadlines.",
    "ex1_vi": "Trong một ngày làm việc bình thường, nhân viên nên đến đúng giờ và hoàn thành nhiệm vụ trước thời hạn."
  },
  {
    "id": 89,
    "word": "deadlines",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɛdlaɪnz/",
    "meaning": "thời hạn",
    "ex1": "In daily routines, workers should arrive on time and finish tasks before deadlines.",
    "ex1_vi": "Trong các thói quen hằng ngày, nhân viên nên đến đúng giờ và hoàn thành nhiệm vụ trước thời hạn."
  },
  {
    "id": 90,
    "word": "speak",
    "type": "verb",
    "cat": "v",
    "phonetic": "/spˈiːk/",
    "meaning": "nói",
    "ex1": "They should speak quietly, wear suitable clothes, and respect coworkers.",
    "ex1_vi": "Họ nên nói nhỏ, mặc quần áo phù hợp và tôn trọng đồng nghiệp."
  },
  {
    "id": 91,
    "word": "quietly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kwˈaɪətli/",
    "meaning": "một cách nhỏ nhẹ",
    "ex1": "They should speak quietly, wear suitable clothes, and respect coworkers.",
    "ex1_vi": "Họ nên nói nhỏ, mặc quần áo phù hợp và tôn trọng đồng nghiệp."
  },
  {
    "id": 92,
    "word": "wear",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈeə/",
    "meaning": "mặc",
    "ex1": "During a normal workday, they should speak quietly, wear suitable clothes, and respect coworkers.",
    "ex1_vi": "Trong một ngày làm việc bình thường, họ nên nói nhỏ, mặc quần áo phù hợp và tôn trọng đồng nghiệp."
  },
  {
    "id": 93,
    "word": "suitable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈuːtəbəl/",
    "meaning": "phù hợp",
    "ex1": "In daily routines, they should speak quietly, wear suitable clothes, and respect coworkers.",
    "ex1_vi": "Trong các thói quen hằng ngày, họ nên nói nhỏ, mặc quần áo phù hợp và tôn trọng đồng nghiệp."
  },
  {
    "id": 94,
    "word": "clothes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈəʊðz/",
    "meaning": "quần áo",
    "ex1": "During busy working hours, they should speak quietly, wear suitable clothes, and respect coworkers.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, họ nên nói nhỏ, mặc quần áo phù hợp và tôn trọng đồng nghiệp."
  },
  {
    "id": 95,
    "word": "respect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪspˈɛkt/",
    "meaning": "tôn trọng",
    "ex1": "As part of regular work, they should speak quietly, wear suitable clothes, and respect coworkers.",
    "ex1_vi": "Là một phần của công việc thường ngày, họ nên nói nhỏ, mặc quần áo phù hợp và tôn trọng đồng nghiệp."
  },
  {
    "id": 96,
    "word": "coworkers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈəʊwɜːkəz/",
    "meaning": "đồng nghiệp",
    "ex1": "On a typical weekday, they should speak quietly, wear suitable clothes, and respect coworkers.",
    "ex1_vi": "Vào một ngày làm việc điển hình, họ nên nói nhỏ, mặc quần áo phù hợp và tôn trọng đồng nghiệp."
  },
  {
    "id": 97,
    "word": "keeping",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/kˈiːpɪŋ/",
    "meaning": "việc giữ",
    "ex1": "Keeping desks clean and following company policies also shows responsibility and professional behavior always.",
    "ex1_vi": "Giữ bàn làm việc sạch sẽ và tuân theo chính sách của công ty cũng thể hiện trách nhiệm và tác phong chuyên nghiệp."
  },
  {
    "id": 98,
    "word": "desks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɛsks/",
    "meaning": "bàn làm việc",
    "ex1": "Keeping desks clean and following company policies also shows responsibility and professional behavior always.",
    "ex1_vi": "Giữ bàn làm việc sạch sẽ và tuân theo chính sách của công ty cũng thể hiện trách nhiệm và tác phong chuyên nghiệp."
  },
  {
    "id": 99,
    "word": "clean",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈiːn/",
    "meaning": "sạch",
    "ex1": "During a normal workday, keeping desks clean and following company policies also shows responsibility and professional behavior always.",
    "ex1_vi": "Trong một ngày làm việc bình thường, giữ bàn làm việc sạch sẽ và tuân theo chính sách của công ty cũng thể hiện trách nhiệm và tác phong chuyên nghiệp."
  },
  {
    "id": 100,
    "word": "policies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɒlɪsiz/",
    "meaning": "chính sách",
    "ex1": "In daily routines, keeping desks clean and following company policies also shows responsibility and professional behavior always.",
    "ex1_vi": "Trong các thói quen hằng ngày, giữ bàn làm việc sạch sẽ và tuân theo chính sách của công ty cũng thể hiện trách nhiệm và tác phong chuyên nghiệp."
  },
  {
    "id": 101,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɒlsəʊ/",
    "meaning": "cũng",
    "ex1": "During busy working hours, keeping desks clean and following company policies also shows responsibility and professional behavior always.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, giữ bàn làm việc sạch sẽ và tuân theo chính sách của công ty cũng thể hiện trách nhiệm và tác phong chuyên nghiệp."
  },
  {
    "id": 102,
    "word": "shows",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈəʊz/",
    "meaning": "thể hiện",
    "ex1": "As part of regular work, keeping desks clean and following company policies also shows responsibility and professional behavior always.",
    "ex1_vi": "Là một phần của công việc thường ngày, giữ bàn làm việc sạch sẽ và tuân theo chính sách của công ty cũng thể hiện trách nhiệm và tác phong chuyên nghiệp."
  },
  {
    "id": 103,
    "word": "responsibility",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɹɪspˌɒnsəbˈɪlɪti/",
    "meaning": "trách nhiệm",
    "ex1": "On a typical weekday, keeping desks clean and following company policies also shows responsibility and professional behavior always.",
    "ex1_vi": "Vào một ngày làm việc điển hình, giữ bàn làm việc sạch sẽ và tuân theo chính sách của công ty cũng thể hiện trách nhiệm và tác phong chuyên nghiệp."
  },
  {
    "id": 104,
    "word": "professional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pɹəfˈɛʃənəl/",
    "meaning": "chuyên nghiệp",
    "ex1": "During ordinary office activities, keeping desks clean and following company policies also shows responsibility and professional behavior always.",
    "ex1_vi": "Trong các hoạt động văn phòng thông thường, giữ bàn làm việc sạch sẽ và tuân theo chính sách của công ty cũng thể hiện trách nhiệm và tác phong chuyên nghiệp."
  },
  {
    "id": 105,
    "word": "behavior",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bɪhˈeɪvjə/",
    "meaning": "hành vi; tác phong",
    "ex1": "In everyday workplace routines, keeping desks clean and following company policies also shows responsibility and professional behavior always.",
    "ex1_vi": "Trong các thói quen hằng ngày tại nơi làm việc, giữ bàn làm việc sạch sẽ và tuân theo chính sách của công ty cũng thể hiện trách nhiệm và tác phong chuyên nghiệp."
  },
  {
    "id": 106,
    "word": "always",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔːlweɪz/",
    "meaning": "luôn luôn",
    "ex1": "Throughout the working day, keeping desks clean and following company policies also shows responsibility and professional behavior always.",
    "ex1_vi": "Suốt ngày làm việc, giữ bàn làm việc sạch sẽ và tuân theo chính sách của công ty cũng thể hiện trách nhiệm và tác phong chuyên nghiệp."
  },
  {
    "id": 107,
    "word": "safely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sˈeɪfli/",
    "meaning": "một cách an toàn",
    "ex1": "Good office rules help employees work safely and happily.",
    "ex1_vi": "Nội quy văn phòng tốt giúp nhân viên làm việc an toàn và vui vẻ."
  },
  {
    "id": 108,
    "word": "happily",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/hˈapɪli/",
    "meaning": "vui vẻ",
    "ex1": "Good office rules help employees work safely and happily.",
    "ex1_vi": "Nội quy văn phòng tốt giúp nhân viên làm việc an toàn và vui vẻ."
  },
  {
    "id": 109,
    "word": "feels",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈiːlz/",
    "meaning": "cảm thấy",
    "ex1": "Everyone feels respected and comfortable when people follow the same standards.",
    "ex1_vi": "Mọi người cảm thấy được tôn trọng và thoải mái khi cùng tuân theo những tiêu chuẩn giống nhau."
  },
  {
    "id": 110,
    "word": "respected",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɹɪspˈɛktɪd/",
    "meaning": "được tôn trọng",
    "ex1": "Everyone feels respected and comfortable when people follow the same standards.",
    "ex1_vi": "Mọi người cảm thấy được tôn trọng và thoải mái khi cùng tuân theo những tiêu chuẩn giống nhau."
  },
  {
    "id": 111,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "During a normal workday, everyone feels respected and comfortable when people follow the same standards.",
    "ex1_vi": "Trong một ngày làm việc bình thường, mọi người cảm thấy được tôn trọng và thoải mái khi cùng tuân theo những tiêu chuẩn giống nhau."
  },
  {
    "id": 112,
    "word": "follow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɒləʊ/",
    "meaning": "theo",
    "ex1": "In daily routines, everyone feels respected and comfortable when people follow the same standards.",
    "ex1_vi": "Trong các thói quen hằng ngày, mọi người cảm thấy được tôn trọng và thoải mái khi cùng tuân theo những tiêu chuẩn giống nhau."
  },
  {
    "id": 113,
    "word": "standards",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈandədz/",
    "meaning": "tiêu chuẩn",
    "ex1": "During busy working hours, everyone feels respected and comfortable when people follow the same standards.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, mọi người cảm thấy được tôn trọng và thoải mái khi cùng tuân theo những tiêu chuẩn giống nhau."
  },
  {
    "id": 114,
    "word": "well",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈɛl/",
    "meaning": "tốt",
    "ex1": "A well-organized workplace improves teamwork, increases productivity, and creates success for the whole company together.",
    "ex1_vi": "Một nơi làm việc được tổ chức tốt cải thiện tinh thần làm việc nhóm, tăng năng suất và tạo nên thành công cho toàn công ty."
  },
  {
    "id": 115,
    "word": "workplace",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɜːkpleɪs/",
    "meaning": "nơi làm việc",
    "ex1": "A well-organized workplace improves teamwork, increases productivity, and creates success for the whole company together.",
    "ex1_vi": "Một nơi làm việc được tổ chức tốt cải thiện tinh thần làm việc nhóm, tăng năng suất và tạo nên thành công cho toàn công ty."
  },
  {
    "id": 116,
    "word": "improves",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɪmpɹˈuːvz/",
    "meaning": "cải thiện",
    "ex1": "During a normal workday, a well-organized workplace improves teamwork, increases productivity, and creates success for the whole company together.",
    "ex1_vi": "Trong một ngày làm việc bình thường, một nơi làm việc được tổ chức tốt cải thiện tinh thần làm việc nhóm, tăng năng suất và tạo nên thành công cho toàn công ty."
  },
  {
    "id": 117,
    "word": "increases",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɪnkɹiːsɪz/",
    "meaning": "tăng",
    "ex1": "In daily routines, a well-organized workplace improves teamwork, increases productivity, and creates success for the whole company together.",
    "ex1_vi": "Trong các thói quen hằng ngày, một nơi làm việc được tổ chức tốt cải thiện tinh thần làm việc nhóm, tăng năng suất và tạo nên thành công cho toàn công ty."
  },
  {
    "id": 118,
    "word": "productivity",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɹˌɒdəktˈɪvɪti/",
    "meaning": "năng suất",
    "ex1": "During busy working hours, a well-organized workplace improves teamwork, increases productivity, and creates success for the whole company together.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, một nơi làm việc được tổ chức tốt cải thiện tinh thần làm việc nhóm, tăng năng suất và tạo nên thành công cho toàn công ty."
  },
  {
    "id": 119,
    "word": "success",
    "type": "noun",
    "cat": "n",
    "phonetic": "/səksˈɛs/",
    "meaning": "thành công",
    "ex1": "As part of regular work, a well-organized workplace improves teamwork, increases productivity, and creates success for the whole company together.",
    "ex1_vi": "Là một phần của công việc thường ngày, một nơi làm việc được tổ chức tốt cải thiện tinh thần làm việc nhóm, tăng năng suất và tạo nên thành công cho toàn công ty."
  },
  {
    "id": 120,
    "word": "whole",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/hˈəʊl/",
    "meaning": "toàn bộ",
    "ex1": "On a typical weekday, a well-organized workplace improves teamwork, increases productivity, and creates success for the whole company together.",
    "ex1_vi": "Vào một ngày làm việc điển hình, một nơi làm việc được tổ chức tốt cải thiện tinh thần làm việc nhóm, tăng năng suất và tạo nên thành công cho toàn công ty."
  },
  {
    "id": 121,
    "word": "working",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/wˈɜːkɪŋ/",
    "meaning": "làm việc",
    "ex1": "Working together is important in every office because teamwork brings better results.",
    "ex1_vi": "Làm việc cùng nhau rất quan trọng trong mọi văn phòng vì tinh thần đồng đội mang lại kết quả tốt hơn."
  },
  {
    "id": 122,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈʌz/",
    "meaning": "bởi vì",
    "ex1": "Working together is important in every office because teamwork brings better results.",
    "ex1_vi": "Làm việc cùng nhau rất quan trọng trong mọi văn phòng vì tinh thần đồng đội mang lại kết quả tốt hơn."
  },
  {
    "id": 123,
    "word": "brings",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɹˈɪŋz/",
    "meaning": "mang lại",
    "ex1": "During a normal workday, working together is important in every office because teamwork brings better results.",
    "ex1_vi": "Trong một ngày làm việc bình thường, làm việc cùng nhau rất quan trọng trong mọi văn phòng vì tinh thần đồng đội mang lại kết quả tốt hơn."
  },
  {
    "id": 124,
    "word": "another",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ɐnˈʌðə/",
    "meaning": "người khác; lẫn nhau",
    "ex1": "Employees share ideas, solve problems, and support one another.",
    "ex1_vi": "Nhân viên chia sẻ ý tưởng, giải quyết vấn đề và hỗ trợ lẫn nhau."
  },
  {
    "id": 125,
    "word": "faster",
    "type": "comparative adverb",
    "cat": "adv",
    "phonetic": "/fˈastə/",
    "meaning": "nhanh hơn",
    "ex1": "Good teamwork helps everyone finish tasks faster and creates a positive working environment daily.",
    "ex1_vi": "Tinh thần làm việc nhóm tốt giúp mọi người hoàn thành nhiệm vụ nhanh hơn và tạo ra một môi trường làm việc tích cực hằng ngày."
  },
  {
    "id": 126,
    "word": "positive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɒzɪtˌɪv/",
    "meaning": "tích cực",
    "ex1": "Good teamwork helps everyone finish tasks faster and creates a positive working environment daily.",
    "ex1_vi": "Tinh thần làm việc nhóm tốt giúp mọi người hoàn thành nhiệm vụ nhanh hơn và tạo ra một môi trường làm việc tích cực hằng ngày."
  },
  {
    "id": 127,
    "word": "daily",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈeɪli/",
    "meaning": "hằng ngày",
    "ex1": "During a normal workday, good teamwork helps everyone finish tasks faster and creates a positive working environment daily.",
    "ex1_vi": "Trong một ngày làm việc bình thường, tinh thần làm việc nhóm tốt giúp mọi người hoàn thành nhiệm vụ nhanh hơn và tạo ra một môi trường làm việc tích cực hằng ngày."
  },
  {
    "id": 128,
    "word": "someone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/sˈʌmwɒn/",
    "meaning": "ai đó",
    "ex1": "When someone needs help, coworkers offer support and useful advice.",
    "ex1_vi": "Khi ai đó cần giúp đỡ, đồng nghiệp cung cấp sự hỗ trợ và lời khuyên hữu ích."
  },
  {
    "id": 129,
    "word": "needs",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈiːdz/",
    "meaning": "cần",
    "ex1": "When someone needs help, coworkers offer support and useful advice.",
    "ex1_vi": "Khi ai đó cần giúp đỡ, đồng nghiệp cung cấp sự hỗ trợ và lời khuyên hữu ích."
  },
  {
    "id": 130,
    "word": "offer",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɒfə/",
    "meaning": "đưa ra; cung cấp",
    "ex1": "During a normal workday, when someone needs help, coworkers offer support and useful advice.",
    "ex1_vi": "Trong một ngày làm việc bình thường, khi ai đó cần giúp đỡ, đồng nghiệp cung cấp sự hỗ trợ và lời khuyên hữu ích."
  },
  {
    "id": 131,
    "word": "advice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɐdvˈaɪs/",
    "meaning": "lời khuyên",
    "ex1": "In daily routines, when someone needs help, coworkers offer support and useful advice.",
    "ex1_vi": "Trong các thói quen hằng ngày, khi ai đó cần giúp đỡ, đồng nghiệp cung cấp sự hỗ trợ và lời khuyên hữu ích."
  },
  {
    "id": 132,
    "word": "communicate",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kəmjˈuːnɪkˌeɪt/",
    "meaning": "giao tiếp",
    "ex1": "They communicate clearly, respect different opinions, and trust each other.",
    "ex1_vi": "Họ giao tiếp rõ ràng, tôn trọng các ý kiến khác nhau và tin tưởng lẫn nhau."
  },
  {
    "id": 133,
    "word": "clearly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/klˈiəli/",
    "meaning": "rõ ràng",
    "ex1": "They communicate clearly, respect different opinions, and trust each other.",
    "ex1_vi": "Họ giao tiếp rõ ràng, tôn trọng các ý kiến khác nhau và tin tưởng lẫn nhau."
  },
  {
    "id": 134,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɹənt/",
    "meaning": "khác nhau",
    "ex1": "During a normal workday, they communicate clearly, respect different opinions, and trust each other.",
    "ex1_vi": "Trong một ngày làm việc bình thường, họ giao tiếp rõ ràng, tôn trọng các ý kiến khác nhau và tin tưởng lẫn nhau."
  },
  {
    "id": 135,
    "word": "trust",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tɹˈʌst/",
    "meaning": "tin tưởng",
    "ex1": "In daily routines, they communicate clearly, respect different opinions, and trust each other.",
    "ex1_vi": "Trong các thói quen hằng ngày, họ giao tiếp rõ ràng, tôn trọng các ý kiến khác nhau và tin tưởng lẫn nhau."
  },
  {
    "id": 136,
    "word": "relationships",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɹɪlˈeɪʃənʃˌɪps/",
    "meaning": "các mối quan hệ",
    "ex1": "Friendly relationships make work easier and reduce stress during busy days in the office.",
    "ex1_vi": "Các mối quan hệ thân thiện làm công việc dễ dàng hơn và giảm căng thẳng trong những ngày bận rộn ở văn phòng."
  },
  {
    "id": 137,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm cho",
    "ex1": "Friendly relationships make work easier and reduce stress during busy days in the office.",
    "ex1_vi": "Các mối quan hệ thân thiện làm công việc dễ dàng hơn và giảm căng thẳng trong những ngày bận rộn ở văn phòng."
  },
  {
    "id": 138,
    "word": "easier",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/ˈiːziə/",
    "meaning": "dễ hơn",
    "ex1": "During a normal workday, friendly relationships make work easier and reduce stress during busy days in the office.",
    "ex1_vi": "Trong một ngày làm việc bình thường, các mối quan hệ thân thiện làm công việc dễ dàng hơn và giảm căng thẳng trong những ngày bận rộn ở văn phòng."
  },
  {
    "id": 139,
    "word": "reduce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪdjˈuːs/",
    "meaning": "giảm",
    "ex1": "In daily routines, friendly relationships make work easier and reduce stress during busy days in the office.",
    "ex1_vi": "Trong các thói quen hằng ngày, các mối quan hệ thân thiện làm công việc dễ dàng hơn và giảm căng thẳng trong những ngày bận rộn ở văn phòng."
  },
  {
    "id": 140,
    "word": "stress",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stɹˈɛs/",
    "meaning": "căng thẳng",
    "ex1": "During busy working hours, friendly relationships make work easier and reduce stress during busy days in the office.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, các mối quan hệ thân thiện làm công việc dễ dàng hơn và giảm căng thẳng trong những ngày bận rộn ở văn phòng."
  },
  {
    "id": 141,
    "word": "busy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɪzi/",
    "meaning": "nhộn nhịp",
    "ex1": "As part of regular work, friendly relationships make work easier and reduce stress during busy days in the office.",
    "ex1_vi": "Là một phần của công việc thường ngày, các mối quan hệ thân thiện làm công việc dễ dàng hơn và giảm căng thẳng trong những ngày bận rộn ở văn phòng."
  },
  {
    "id": 142,
    "word": "days",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪz/",
    "meaning": "ngày",
    "ex1": "On a typical weekday, friendly relationships make work easier and reduce stress during busy days in the office.",
    "ex1_vi": "Vào một ngày làm việc điển hình, các mối quan hệ thân thiện làm công việc dễ dàng hơn và giảm căng thẳng trong những ngày bận rộn ở văn phòng."
  },
  {
    "id": 143,
    "word": "successful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/səksˈɛsfəl/",
    "meaning": "thành công",
    "ex1": "Successful teams celebrate achievements and learn from mistakes together.",
    "ex1_vi": "Những nhóm thành công cùng nhau ăn mừng thành tích và học hỏi từ sai lầm."
  },
  {
    "id": 144,
    "word": "teams",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈiːmz/",
    "meaning": "các nhóm",
    "ex1": "Successful teams celebrate achievements and learn from mistakes together.",
    "ex1_vi": "Những nhóm thành công cùng nhau ăn mừng thành tích và học hỏi từ sai lầm."
  },
  {
    "id": 145,
    "word": "celebrate",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɛləbɹˌeɪt/",
    "meaning": "ăn mừng",
    "ex1": "During a normal workday, successful teams celebrate achievements and learn from mistakes together.",
    "ex1_vi": "Trong một ngày làm việc bình thường, những nhóm thành công cùng nhau ăn mừng thành tích và học hỏi từ sai lầm."
  },
  {
    "id": 146,
    "word": "achievements",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɐtʃˈiːvmənts/",
    "meaning": "thành tích",
    "ex1": "In daily routines, successful teams celebrate achievements and learn from mistakes together.",
    "ex1_vi": "Trong các thói quen hằng ngày, những nhóm thành công cùng nhau ăn mừng thành tích và học hỏi từ sai lầm."
  },
  {
    "id": 147,
    "word": "learn",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɜːn/",
    "meaning": "học",
    "ex1": "During busy working hours, successful teams celebrate achievements and learn from mistakes together.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, những nhóm thành công cùng nhau ăn mừng thành tích và học hỏi từ sai lầm."
  },
  {
    "id": 148,
    "word": "mistakes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mɪstˈeɪks/",
    "meaning": "sai lầm",
    "ex1": "As part of regular work, successful teams celebrate achievements and learn from mistakes together.",
    "ex1_vi": "Là một phần của công việc thường ngày, những nhóm thành công cùng nhau ăn mừng thành tích và học hỏi từ sai lầm."
  },
  {
    "id": 149,
    "word": "skills",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪlz/",
    "meaning": "kỹ năng",
    "ex1": "Everyone has different skills that help the group succeed.",
    "ex1_vi": "Mỗi người có những kỹ năng khác nhau giúp nhóm thành công."
  },
  {
    "id": 150,
    "word": "group",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡɹˈuːp/",
    "meaning": "nhóm",
    "ex1": "Everyone has different skills that help the group succeed.",
    "ex1_vi": "Mỗi người có những kỹ năng khác nhau giúp nhóm thành công."
  },
  {
    "id": 151,
    "word": "succeed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/səksˈiːd/",
    "meaning": "thành công",
    "ex1": "During a normal workday, everyone has different skills that help the group succeed.",
    "ex1_vi": "Trong một ngày làm việc bình thường, mỗi người có những kỹ năng khác nhau giúp nhóm thành công."
  },
  {
    "id": 152,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/stɹˈɒŋ/",
    "meaning": "mạnh mẽ",
    "ex1": "Strong teamwork improves productivity, builds confidence, and creates a happier workplace for all employees every day.",
    "ex1_vi": "Tinh thần làm việc nhóm mạnh mẽ cải thiện năng suất, xây dựng sự tự tin và tạo ra một nơi làm việc vui vẻ hơn cho tất cả nhân viên mỗi ngày."
  },
  {
    "id": 153,
    "word": "builds",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɪldz/",
    "meaning": "xây dựng",
    "ex1": "Strong teamwork improves productivity, builds confidence, and creates a happier workplace for all employees every day.",
    "ex1_vi": "Tinh thần làm việc nhóm mạnh mẽ cải thiện năng suất, xây dựng sự tự tin và tạo ra một nơi làm việc vui vẻ hơn cho tất cả nhân viên mỗi ngày."
  },
  {
    "id": 154,
    "word": "confidence",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɒnfɪdəns/",
    "meaning": "sự tự tin",
    "ex1": "During a normal workday, strong teamwork improves productivity, builds confidence, and creates a happier workplace for all employees every day.",
    "ex1_vi": "Trong một ngày làm việc bình thường, tinh thần làm việc nhóm mạnh mẽ cải thiện năng suất, xây dựng sự tự tin và tạo ra một nơi làm việc vui vẻ hơn cho tất cả nhân viên mỗi ngày."
  },
  {
    "id": 155,
    "word": "happier",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/hˈapɪə/",
    "meaning": "vui vẻ hơn",
    "ex1": "In daily routines, strong teamwork improves productivity, builds confidence, and creates a happier workplace for all employees every day.",
    "ex1_vi": "Trong các thói quen hằng ngày, tinh thần làm việc nhóm mạnh mẽ cải thiện năng suất, xây dựng sự tự tin và tạo ra một nơi làm việc vui vẻ hơn cho tất cả nhân viên mỗi ngày."
  }
];

const newReadingVocabOrder = [
  "team",
  "meeting",
  "helps",
  "workers",
  "discuss",
  "projects",
  "and",
  "share",
  "useful",
  "ideas",
  "everyone",
  "gathers",
  "one",
  "room",
  "or",
  "joins",
  "online",
  "meetings",
  "help",
  "people",
  "understand",
  "goals",
  "solve",
  "problems",
  "work",
  "together",
  "better",
  "every",
  "single",
  "day",
  "successfully",
  "during",
  "person",
  "gives",
  "opinions",
  "listens",
  "carefully",
  "manager",
  "explains",
  "plans",
  "assigns",
  "tasks",
  "members",
  "ask",
  "questions",
  "suggest",
  "improvements",
  "agree",
  "best",
  "solutions",
  "future",
  "after",
  "knows",
  "do",
  "next",
  "complete",
  "support",
  "good",
  "improve",
  "communication",
  "build",
  "stronger",
  "teamwork",
  "company",
  "achieve",
  "results",
  "week",
  "office",
  "rules",
  "has",
  "important",
  "keep",
  "organized",
  "comfortable",
  "employees",
  "should",
  "before",
  "starting",
  "jobs",
  "following",
  "creates",
  "friendly",
  "environment",
  "can",
  "peacefully",
  "arrive",
  "time",
  "finish",
  "deadlines",
  "speak",
  "quietly",
  "wear",
  "suitable",
  "clothes",
  "respect",
  "coworkers",
  "keeping",
  "desks",
  "clean",
  "policies",
  "also",
  "shows",
  "responsibility",
  "professional",
  "behavior",
  "always",
  "safely",
  "happily",
  "feels",
  "respected",
  "when",
  "follow",
  "standards",
  "well",
  "workplace",
  "improves",
  "increases",
  "productivity",
  "success",
  "whole",
  "working",
  "because",
  "brings",
  "another",
  "faster",
  "positive",
  "daily",
  "someone",
  "needs",
  "offer",
  "advice",
  "communicate",
  "clearly",
  "different",
  "trust",
  "relationships",
  "make",
  "easier",
  "reduce",
  "stress",
  "busy",
  "days",
  "successful",
  "teams",
  "celebrate",
  "achievements",
  "learn",
  "mistakes",
  "skills",
  "group",
  "succeed",
  "strong",
  "builds",
  "confidence",
  "happier"
];
