// ===== office01 VOCABULARY =====

const lessonVocabularyWords = [
  "busy",
  "office",
  "many",
  "people",
  "work",
  "modern",
  "every",
  "day",
  "has",
  "desks",
  "computers",
  "and",
  "bright",
  "lights",
  "workers",
  "arrive",
  "early",
  "greet",
  "start",
  "tasks",
  "everyone",
  "stays",
  "during",
  "whole",
  "morning",
  "together",
  "employees",
  "answer",
  "emails",
  "make",
  "phone",
  "calls",
  "write",
  "reports",
  "attend",
  "meetings",
  "talk",
  "customers",
  "while",
  "others",
  "prepare",
  "documents",
  "help",
  "when",
  "needed",
  "good",
  "teamwork",
  "makes",
  "daily",
  "easier",
  "faster",
  "afternoon",
  "finish",
  "important",
  "organize",
  "before",
  "leaving",
  "check",
  "tomorrow's",
  "schedule",
  "say",
  "goodbye",
  "needs",
  "responsible",
  "clear",
  "communication",
  "careful",
  "planning",
  "single",
  "jobs",
  "have",
  "different",
  "worker",
  "special",
  "duties",
  "helps",
  "company",
  "succeed",
  "share",
  "information",
  "support",
  "one",
  "another",
  "complete",
  "business",
  "well",
  "manager",
  "leads",
  "team",
  "decisions",
  "accountant",
  "checks",
  "money",
  "financial",
  "records",
  "secretary",
  "answers",
  "arranges",
  "salesperson",
  "talks",
  "sells",
  "products",
  "or",
  "useful",
  "services",
  "job",
  "because",
  "person",
  "responsibilities",
  "should",
  "friendly",
  "organized",
  "successfully",
  "create",
  "better",
  "workplace",
  "equipment",
  "machines",
  "tools",
  "use",
  "quickly",
  "correctly",
  "save",
  "time",
  "improve",
  "quality",
  "send",
  "store",
  "printers",
  "paper",
  "copies",
  "telephones",
  "speak",
  "photocopiers",
  "produce",
  "extra",
  "files",
  "carefully",
  "follow",
  "simple",
  "instructions",
  "keeping",
  "clean",
  "reporting",
  "problems",
  "prevent",
  "damage",
  "safer",
  "productive"
];

const newVocabData = [
  {
    "id": 1,
    "word": "busy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɪzi/",
    "meaning": "nhộn nhịp",
    "ex1": "Everyone stays busy during the whole morning together.",
    "ex1_vi": "Mọi người đều bận rộn suốt cả buổi sáng cùng nhau."
  },
  {
    "id": 2,
    "word": "office",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɒfɪs/",
    "meaning": "văn phòng",
    "ex1": "Many people work in a modern office every day.",
    "ex1_vi": "Nhiều người làm việc trong một văn phòng hiện đại mỗi ngày."
  },
  {
    "id": 3,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Many people work in a modern office every day.",
    "ex1_vi": "Nhiều người làm việc trong một văn phòng hiện đại mỗi ngày."
  },
  {
    "id": 4,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈiːpəl/",
    "meaning": "mọi người",
    "ex1": "During a normal workday, many people work in a modern office every day.",
    "ex1_vi": "Trong một ngày làm việc bình thường, nhiều người làm việc trong một văn phòng hiện đại mỗi ngày."
  },
  {
    "id": 5,
    "word": "work",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɜːk/",
    "meaning": "làm việc",
    "ex1": "In daily routines, many people work in a modern office every day.",
    "ex1_vi": "Trong các thói quen hằng ngày, nhiều người làm việc trong một văn phòng hiện đại mỗi ngày."
  },
  {
    "id": 6,
    "word": "modern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈɒdən/",
    "meaning": "hiện đại",
    "ex1": "During busy working hours, many people work in a modern office every day.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, nhiều người làm việc trong một văn phòng hiện đại mỗi ngày."
  },
  {
    "id": 7,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɹɪ/",
    "meaning": "mỗi",
    "ex1": "As part of regular work, many people work in a modern office every day.",
    "ex1_vi": "Là một phần của công việc thường ngày, nhiều người làm việc trong một văn phòng hiện đại mỗi ngày."
  },
  {
    "id": 8,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "On a typical weekday, many people work in a modern office every day.",
    "ex1_vi": "Vào một ngày làm việc điển hình, nhiều người làm việc trong một văn phòng hiện đại mỗi ngày."
  },
  {
    "id": 9,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈaz/",
    "meaning": "có",
    "ex1": "The office has many desks, computers, and bright lights.",
    "ex1_vi": "Văn phòng có nhiều bàn làm việc, máy tính và đèn sáng."
  },
  {
    "id": 10,
    "word": "desks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɛsks/",
    "meaning": "bàn làm việc",
    "ex1": "The office has many desks, computers, and bright lights.",
    "ex1_vi": "Văn phòng có nhiều bàn làm việc, máy tính và đèn sáng."
  },
  {
    "id": 11,
    "word": "computers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kəmpjˈuːtəz/",
    "meaning": "máy tính",
    "ex1": "During a normal workday, the office has many desks, computers, and bright lights.",
    "ex1_vi": "Trong một ngày làm việc bình thường, văn phòng có nhiều bàn làm việc, máy tính và đèn sáng."
  },
  {
    "id": 12,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈand/",
    "meaning": "và",
    "ex1": "In daily routines, the office has many desks, computers, and bright lights.",
    "ex1_vi": "Trong các thói quen hằng ngày, văn phòng có nhiều bàn làm việc, máy tính và đèn sáng."
  },
  {
    "id": 13,
    "word": "bright",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bɹˈaɪt/",
    "meaning": "sáng",
    "ex1": "During busy working hours, the office has many desks, computers, and bright lights.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, văn phòng có nhiều bàn làm việc, máy tính và đèn sáng."
  },
  {
    "id": 14,
    "word": "lights",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪts/",
    "meaning": "đèn",
    "ex1": "As part of regular work, the office has many desks, computers, and bright lights.",
    "ex1_vi": "Là một phần của công việc thường ngày, văn phòng có nhiều bàn làm việc, máy tính và đèn sáng."
  },
  {
    "id": 15,
    "word": "workers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɜːkəz/",
    "meaning": "nhân viên",
    "ex1": "Workers arrive early, greet each other, and start their tasks.",
    "ex1_vi": "Nhân viên đến sớm, chào nhau và bắt đầu công việc của mình."
  },
  {
    "id": 16,
    "word": "arrive",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɐɹˈaɪv/",
    "meaning": "đến",
    "ex1": "Workers arrive early, greet each other, and start their tasks.",
    "ex1_vi": "Nhân viên đến sớm, chào nhau và bắt đầu công việc của mình."
  },
  {
    "id": 17,
    "word": "early",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɜːlɪ/",
    "meaning": "sớm",
    "ex1": "During a normal workday, workers arrive early, greet each other, and start their tasks.",
    "ex1_vi": "Trong một ngày làm việc bình thường, nhân viên đến sớm, chào nhau và bắt đầu công việc của mình."
  },
  {
    "id": 18,
    "word": "greet",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡɹˈiːt/",
    "meaning": "chào hỏi",
    "ex1": "In daily routines, workers arrive early, greet each other, and start their tasks.",
    "ex1_vi": "Trong các thói quen hằng ngày, nhân viên đến sớm, chào nhau và bắt đầu công việc của mình."
  },
  {
    "id": 19,
    "word": "start",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈɑːt/",
    "meaning": "bắt đầu",
    "ex1": "During busy working hours, workers arrive early, greet each other, and start their tasks.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, nhân viên đến sớm, chào nhau và bắt đầu công việc của mình."
  },
  {
    "id": 20,
    "word": "tasks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈasks/",
    "meaning": "nhiệm vụ",
    "ex1": "As part of regular work, workers arrive early, greet each other, and start their tasks.",
    "ex1_vi": "Là một phần của công việc thường ngày, nhân viên đến sớm, chào nhau và bắt đầu công việc của mình."
  },
  {
    "id": 21,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvɹɪwˌɒn/",
    "meaning": "mọi người",
    "ex1": "Everyone stays busy during the whole morning together.",
    "ex1_vi": "Mọi người đều bận rộn suốt cả buổi sáng cùng nhau."
  },
  {
    "id": 22,
    "word": "stays",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈeɪz/",
    "meaning": "duy trì; vẫn ở trạng thái",
    "ex1": "During a normal workday, everyone stays busy during the whole morning together.",
    "ex1_vi": "Trong một ngày làm việc bình thường, mọi người đều bận rộn suốt cả buổi sáng cùng nhau."
  },
  {
    "id": 23,
    "word": "during",
    "type": "preposition",
    "cat": "prep",
    "phonetic": "/djˈʊəɹɪŋ/",
    "meaning": "trong suốt",
    "ex1": "In daily routines, everyone stays busy during the whole morning together.",
    "ex1_vi": "Trong các thói quen hằng ngày, mọi người đều bận rộn suốt cả buổi sáng cùng nhau."
  },
  {
    "id": 24,
    "word": "whole",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/hˈəʊl/",
    "meaning": "toàn bộ",
    "ex1": "During busy working hours, everyone stays busy during the whole morning together.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, mọi người đều bận rộn suốt cả buổi sáng cùng nhau."
  },
  {
    "id": 25,
    "word": "morning",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɔːnɪŋ/",
    "meaning": "buổi sáng",
    "ex1": "As part of regular work, everyone stays busy during the whole morning together.",
    "ex1_vi": "Là một phần của công việc thường ngày, mọi người đều bận rộn suốt cả buổi sáng cùng nhau."
  },
  {
    "id": 26,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/təɡˈɛðə/",
    "meaning": "cùng nhau",
    "ex1": "On a typical weekday, everyone stays busy during the whole morning together.",
    "ex1_vi": "Vào một ngày làm việc điển hình, mọi người đều bận rộn suốt cả buổi sáng cùng nhau."
  },
  {
    "id": 27,
    "word": "employees",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɛmplˈɔɪiːz/",
    "meaning": "nhân viên",
    "ex1": "Employees answer emails, make phone calls, write reports, and attend meetings.",
    "ex1_vi": "Nhân viên trả lời email, gọi điện thoại, viết báo cáo và tham dự các cuộc họp."
  },
  {
    "id": 28,
    "word": "answer",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈansə/",
    "meaning": "trả lời",
    "ex1": "Employees answer emails, make phone calls, write reports, and attend meetings.",
    "ex1_vi": "Nhân viên trả lời email, gọi điện thoại, viết báo cáo và tham dự các cuộc họp."
  },
  {
    "id": 29,
    "word": "emails",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈiːmeɪlz/",
    "meaning": "email",
    "ex1": "During a normal workday, employees answer emails, make phone calls, write reports, and attend meetings.",
    "ex1_vi": "Trong một ngày làm việc bình thường, nhân viên trả lời email, gọi điện thoại, viết báo cáo và tham dự các cuộc họp."
  },
  {
    "id": 30,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm cho",
    "ex1": "In daily routines, employees answer emails, make phone calls, write reports, and attend meetings.",
    "ex1_vi": "Trong các thói quen hằng ngày, nhân viên trả lời email, gọi điện thoại, viết báo cáo và tham dự các cuộc họp."
  },
  {
    "id": 31,
    "word": "phone",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈəʊn/",
    "meaning": "điện thoại",
    "ex1": "During busy working hours, employees answer emails, make phone calls, write reports, and attend meetings.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, nhân viên trả lời email, gọi điện thoại, viết báo cáo và tham dự các cuộc họp."
  },
  {
    "id": 32,
    "word": "calls",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɔːlz/",
    "meaning": "cuộc gọi",
    "ex1": "As part of regular work, employees answer emails, make phone calls, write reports, and attend meetings.",
    "ex1_vi": "Là một phần của công việc thường ngày, nhân viên trả lời email, gọi điện thoại, viết báo cáo và tham dự các cuộc họp."
  },
  {
    "id": 33,
    "word": "write",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹˈaɪt/",
    "meaning": "viết",
    "ex1": "On a typical weekday, employees answer emails, make phone calls, write reports, and attend meetings.",
    "ex1_vi": "Vào một ngày làm việc điển hình, nhân viên trả lời email, gọi điện thoại, viết báo cáo và tham dự các cuộc họp."
  },
  {
    "id": 34,
    "word": "reports",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɹɪpˈɔːts/",
    "meaning": "báo cáo",
    "ex1": "During ordinary office activities, employees answer emails, make phone calls, write reports, and attend meetings.",
    "ex1_vi": "Trong các hoạt động văn phòng thông thường, nhân viên trả lời email, gọi điện thoại, viết báo cáo và tham dự các cuộc họp."
  },
  {
    "id": 35,
    "word": "attend",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɐtˈɛnd/",
    "meaning": "tham dự",
    "ex1": "In everyday workplace routines, employees answer emails, make phone calls, write reports, and attend meetings.",
    "ex1_vi": "Trong các thói quen hằng ngày tại nơi làm việc, nhân viên trả lời email, gọi điện thoại, viết báo cáo và tham dự các cuộc họp."
  },
  {
    "id": 36,
    "word": "meetings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈiːtɪŋz/",
    "meaning": "các cuộc họp",
    "ex1": "Throughout the working day, employees answer emails, make phone calls, write reports, and attend meetings.",
    "ex1_vi": "Suốt ngày làm việc, nhân viên trả lời email, gọi điện thoại, viết báo cáo và tham dự các cuộc họp."
  },
  {
    "id": 37,
    "word": "talk",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈɔːk/",
    "meaning": "nói chuyện",
    "ex1": "Some talk with customers, while others prepare documents.",
    "ex1_vi": "Một số người nói chuyện với khách hàng, trong khi những người khác chuẩn bị tài liệu."
  },
  {
    "id": 38,
    "word": "customers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌstəməz/",
    "meaning": "khách hàng",
    "ex1": "Some talk with customers, while others prepare documents.",
    "ex1_vi": "Một số người nói chuyện với khách hàng, trong khi những người khác chuẩn bị tài liệu."
  },
  {
    "id": 39,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "During a normal workday, some talk with customers, while others prepare documents.",
    "ex1_vi": "Trong một ngày làm việc bình thường, một số người nói chuyện với khách hàng, trong khi những người khác chuẩn bị tài liệu."
  },
  {
    "id": 40,
    "word": "others",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈʌðəz/",
    "meaning": "những người khác",
    "ex1": "In daily routines, some talk with customers, while others prepare documents.",
    "ex1_vi": "Trong các thói quen hằng ngày, một số người nói chuyện với khách hàng, trong khi những người khác chuẩn bị tài liệu."
  },
  {
    "id": 41,
    "word": "prepare",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹɪpˈeə/",
    "meaning": "chuẩn bị",
    "ex1": "During busy working hours, some talk with customers, while others prepare documents.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, một số người nói chuyện với khách hàng, trong khi những người khác chuẩn bị tài liệu."
  },
  {
    "id": 42,
    "word": "documents",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɒkjuːmənts/",
    "meaning": "tài liệu",
    "ex1": "As part of regular work, some talk with customers, while others prepare documents.",
    "ex1_vi": "Là một phần của công việc thường ngày, một số người nói chuyện với khách hàng, trong khi những người khác chuẩn bị tài liệu."
  },
  {
    "id": 43,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "They help each other when needed.",
    "ex1_vi": "Họ giúp đỡ nhau khi cần."
  },
  {
    "id": 44,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "They help each other when needed.",
    "ex1_vi": "Họ giúp đỡ nhau khi cần."
  },
  {
    "id": 45,
    "word": "needed",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈiːdɪd/",
    "meaning": "cần thiết",
    "ex1": "During a normal workday, they help each other when needed.",
    "ex1_vi": "Trong một ngày làm việc bình thường, họ giúp đỡ nhau khi cần."
  },
  {
    "id": 46,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "Good teamwork makes daily work easier and faster for everyone.",
    "ex1_vi": "Tinh thần làm việc nhóm tốt giúp công việc hằng ngày trở nên dễ dàng và nhanh chóng hơn cho mọi người."
  },
  {
    "id": 47,
    "word": "teamwork",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈiːmwɜːk/",
    "meaning": "tinh thần đồng đội",
    "ex1": "Good teamwork makes daily work easier and faster for everyone.",
    "ex1_vi": "Tinh thần làm việc nhóm tốt giúp công việc hằng ngày trở nên dễ dàng và nhanh chóng hơn cho mọi người."
  },
  {
    "id": 48,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm cho",
    "ex1": "During a normal workday, good teamwork makes daily work easier and faster for everyone.",
    "ex1_vi": "Trong một ngày làm việc bình thường, tinh thần làm việc nhóm tốt giúp công việc hằng ngày trở nên dễ dàng và nhanh chóng hơn cho mọi người."
  },
  {
    "id": 49,
    "word": "daily",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈeɪli/",
    "meaning": "hằng ngày",
    "ex1": "In daily routines, good teamwork makes daily work easier and faster for everyone.",
    "ex1_vi": "Trong các thói quen hằng ngày, tinh thần làm việc nhóm tốt giúp công việc hằng ngày trở nên dễ dàng và nhanh chóng hơn cho mọi người."
  },
  {
    "id": 50,
    "word": "easier",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/ˈiːziə/",
    "meaning": "dễ hơn",
    "ex1": "During busy working hours, good teamwork makes daily work easier and faster for everyone.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, tinh thần làm việc nhóm tốt giúp công việc hằng ngày trở nên dễ dàng và nhanh chóng hơn cho mọi người."
  },
  {
    "id": 51,
    "word": "faster",
    "type": "comparative adverb",
    "cat": "adv",
    "phonetic": "/fˈastə/",
    "meaning": "nhanh hơn",
    "ex1": "As part of regular work, good teamwork makes daily work easier and faster for everyone.",
    "ex1_vi": "Là một phần của công việc thường ngày, tinh thần làm việc nhóm tốt giúp công việc hằng ngày trở nên dễ dàng và nhanh chóng hơn cho mọi người."
  },
  {
    "id": 52,
    "word": "afternoon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌaftənˈuːn/",
    "meaning": "buổi chiều",
    "ex1": "In the afternoon, workers finish important tasks and organize their desks.",
    "ex1_vi": "Vào buổi chiều, nhân viên hoàn thành các nhiệm vụ quan trọng và sắp xếp bàn làm việc."
  },
  {
    "id": 53,
    "word": "finish",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɪnɪʃ/",
    "meaning": "đích",
    "ex1": "In the afternoon, workers finish important tasks and organize their desks.",
    "ex1_vi": "Vào buổi chiều, nhân viên hoàn thành các nhiệm vụ quan trọng và sắp xếp bàn làm việc."
  },
  {
    "id": 54,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪmpˈɔːtənt/",
    "meaning": "quan trọng",
    "ex1": "During a normal workday, in the afternoon, workers finish important tasks and organize their desks.",
    "ex1_vi": "Trong một ngày làm việc bình thường, vào buổi chiều, nhân viên hoàn thành các nhiệm vụ quan trọng và sắp xếp bàn làm việc."
  },
  {
    "id": 55,
    "word": "organize",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɔːɡɐnˌaɪz/",
    "meaning": "tổ chức",
    "ex1": "In daily routines, in the afternoon, workers finish important tasks and organize their desks.",
    "ex1_vi": "Trong các thói quen hằng ngày, vào buổi chiều, nhân viên hoàn thành các nhiệm vụ quan trọng và sắp xếp bàn làm việc."
  },
  {
    "id": 56,
    "word": "before",
    "type": "preposition",
    "cat": "prep",
    "phonetic": "/bɪfˈɔː/",
    "meaning": "trước",
    "ex1": "Before leaving, they check tomorrow's schedule and say goodbye.",
    "ex1_vi": "Trước khi ra về, họ kiểm tra lịch trình ngày mai và chào tạm biệt."
  },
  {
    "id": 57,
    "word": "leaving",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/lˈiːvɪŋ/",
    "meaning": "việc rời đi",
    "ex1": "Before leaving, they check tomorrow's schedule and say goodbye.",
    "ex1_vi": "Trước khi ra về, họ kiểm tra lịch trình ngày mai và chào tạm biệt."
  },
  {
    "id": 58,
    "word": "check",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈɛk/",
    "meaning": "kiểm tra",
    "ex1": "During a normal workday, before leaving, they check tomorrow's schedule and say goodbye.",
    "ex1_vi": "Trong một ngày làm việc bình thường, trước khi ra về, họ kiểm tra lịch trình ngày mai và chào tạm biệt."
  },
  {
    "id": 59,
    "word": "tomorrow's",
    "type": "possessive adjective",
    "cat": "adj",
    "phonetic": "/təmˈɒɹəʊz/",
    "meaning": "của ngày mai",
    "ex1": "In daily routines, before leaving, they check tomorrow's schedule and say goodbye.",
    "ex1_vi": "Trong các thói quen hằng ngày, trước khi ra về, họ kiểm tra lịch trình ngày mai và chào tạm biệt."
  },
  {
    "id": 60,
    "word": "schedule",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɛdjuːl/",
    "meaning": "lịch trình",
    "ex1": "During busy working hours, before leaving, they check tomorrow's schedule and say goodbye.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, trước khi ra về, họ kiểm tra lịch trình ngày mai và chào tạm biệt."
  },
  {
    "id": 61,
    "word": "say",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪ/",
    "meaning": "nói",
    "ex1": "As part of regular work, before leaving, they check tomorrow's schedule and say goodbye.",
    "ex1_vi": "Là một phần của công việc thường ngày, trước khi ra về, họ kiểm tra lịch trình ngày mai và chào tạm biệt."
  },
  {
    "id": 62,
    "word": "goodbye",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡʊdbˈaɪ/",
    "meaning": "lời chào tạm biệt",
    "ex1": "On a typical weekday, before leaving, they check tomorrow's schedule and say goodbye.",
    "ex1_vi": "Vào một ngày làm việc điển hình, trước khi ra về, họ kiểm tra lịch trình ngày mai và chào tạm biệt."
  },
  {
    "id": 63,
    "word": "needs",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈiːdz/",
    "meaning": "cần",
    "ex1": "A busy office needs responsible people, clear communication, and careful planning every single day.",
    "ex1_vi": "Một văn phòng bận rộn cần những người có trách nhiệm, giao tiếp rõ ràng và lập kế hoạch cẩn thận mỗi ngày."
  },
  {
    "id": 64,
    "word": "responsible",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɹɪspˈɒnsəbəl/",
    "meaning": "có trách nhiệm",
    "ex1": "A busy office needs responsible people, clear communication, and careful planning every single day.",
    "ex1_vi": "Một văn phòng bận rộn cần những người có trách nhiệm, giao tiếp rõ ràng và lập kế hoạch cẩn thận mỗi ngày."
  },
  {
    "id": 65,
    "word": "clear",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈiə/",
    "meaning": "rõ ràng",
    "ex1": "During a normal workday, a busy office needs responsible people, clear communication, and careful planning every single day.",
    "ex1_vi": "Trong một ngày làm việc bình thường, một văn phòng bận rộn cần những người có trách nhiệm, giao tiếp rõ ràng và lập kế hoạch cẩn thận mỗi ngày."
  },
  {
    "id": 66,
    "word": "communication",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kəmjˌuːnɪkˈeɪʃən/",
    "meaning": "sự giao tiếp",
    "ex1": "In daily routines, a busy office needs responsible people, clear communication, and careful planning every single day.",
    "ex1_vi": "Trong các thói quen hằng ngày, một văn phòng bận rộn cần những người có trách nhiệm, giao tiếp rõ ràng và lập kế hoạch cẩn thận mỗi ngày."
  },
  {
    "id": 67,
    "word": "careful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈeəfəl/",
    "meaning": "cẩn thận",
    "ex1": "During busy working hours, a busy office needs responsible people, clear communication, and careful planning every single day.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, một văn phòng bận rộn cần những người có trách nhiệm, giao tiếp rõ ràng và lập kế hoạch cẩn thận mỗi ngày."
  },
  {
    "id": 68,
    "word": "planning",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈanɪŋ/",
    "meaning": "việc lập kế hoạch",
    "ex1": "As part of regular work, a busy office needs responsible people, clear communication, and careful planning every single day.",
    "ex1_vi": "Là một phần của công việc thường ngày, một văn phòng bận rộn cần những người có trách nhiệm, giao tiếp rõ ràng và lập kế hoạch cẩn thận mỗi ngày."
  },
  {
    "id": 69,
    "word": "single",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪŋɡəl/",
    "meaning": "duy nhất",
    "ex1": "On a typical weekday, a busy office needs responsible people, clear communication, and careful planning every single day.",
    "ex1_vi": "Vào một ngày làm việc điển hình, một văn phòng bận rộn cần những người có trách nhiệm, giao tiếp rõ ràng và lập kế hoạch cẩn thận mỗi ngày."
  },
  {
    "id": 70,
    "word": "jobs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɒbz/",
    "meaning": "công việc",
    "ex1": "Many people have different jobs in an office.",
    "ex1_vi": "Nhiều người có những công việc khác nhau trong một văn phòng."
  },
  {
    "id": 71,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈav/",
    "meaning": "có",
    "ex1": "Many people have different jobs in an office.",
    "ex1_vi": "Nhiều người có những công việc khác nhau trong một văn phòng."
  },
  {
    "id": 72,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɹənt/",
    "meaning": "khác nhau",
    "ex1": "During a normal workday, many people have different jobs in an office.",
    "ex1_vi": "Trong một ngày làm việc bình thường, nhiều người có những công việc khác nhau trong một văn phòng."
  },
  {
    "id": 73,
    "word": "worker",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɜːkə/",
    "meaning": "nhân viên",
    "ex1": "Each worker has special duties and helps the company succeed.",
    "ex1_vi": "Mỗi nhân viên có nhiệm vụ riêng và góp phần giúp công ty thành công."
  },
  {
    "id": 74,
    "word": "special",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/spˈɛʃəl/",
    "meaning": "đặc biệt",
    "ex1": "Each worker has special duties and helps the company succeed.",
    "ex1_vi": "Mỗi nhân viên có nhiệm vụ riêng và góp phần giúp công ty thành công."
  },
  {
    "id": 75,
    "word": "duties",
    "type": "noun",
    "cat": "n",
    "phonetic": "/djˈuːtiz/",
    "meaning": "nhiệm vụ",
    "ex1": "During a normal workday, each worker has special duties and helps the company succeed.",
    "ex1_vi": "Trong một ngày làm việc bình thường, mỗi nhân viên có nhiệm vụ riêng và góp phần giúp công ty thành công."
  },
  {
    "id": 76,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "In daily routines, each worker has special duties and helps the company succeed.",
    "ex1_vi": "Trong các thói quen hằng ngày, mỗi nhân viên có nhiệm vụ riêng và góp phần giúp công ty thành công."
  },
  {
    "id": 77,
    "word": "company",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌmpəni/",
    "meaning": "công ty",
    "ex1": "During busy working hours, each worker has special duties and helps the company succeed.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, mỗi nhân viên có nhiệm vụ riêng và góp phần giúp công ty thành công."
  },
  {
    "id": 78,
    "word": "succeed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/səksˈiːd/",
    "meaning": "thành công",
    "ex1": "As part of regular work, each worker has special duties and helps the company succeed.",
    "ex1_vi": "Là một phần của công việc thường ngày, mỗi nhân viên có nhiệm vụ riêng và góp phần giúp công ty thành công."
  },
  {
    "id": 79,
    "word": "share",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈeə/",
    "meaning": "chia sẻ",
    "ex1": "They work together every day, share information, and support one another to complete important business tasks well.",
    "ex1_vi": "Họ làm việc cùng nhau mỗi ngày, chia sẻ thông tin và hỗ trợ lẫn nhau để hoàn thành tốt những nhiệm vụ kinh doanh quan trọng."
  },
  {
    "id": 80,
    "word": "information",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnfəmˈeɪʃən/",
    "meaning": "thông tin",
    "ex1": "They work together every day, share information, and support one another to complete important business tasks well.",
    "ex1_vi": "Họ làm việc cùng nhau mỗi ngày, chia sẻ thông tin và hỗ trợ lẫn nhau để hoàn thành tốt những nhiệm vụ kinh doanh quan trọng."
  },
  {
    "id": 81,
    "word": "support",
    "type": "verb",
    "cat": "v",
    "phonetic": "/səpˈɔːt/",
    "meaning": "hỗ trợ",
    "ex1": "During a normal workday, they work together every day, share information, and support one another to complete important business tasks well.",
    "ex1_vi": "Trong một ngày làm việc bình thường, họ làm việc cùng nhau mỗi ngày, chia sẻ thông tin và hỗ trợ lẫn nhau để hoàn thành tốt những nhiệm vụ kinh doanh quan trọng."
  },
  {
    "id": 82,
    "word": "one",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/wˈɒn/",
    "meaning": "một người; một",
    "ex1": "In daily routines, they work together every day, share information, and support one another to complete important business tasks well.",
    "ex1_vi": "Trong các thói quen hằng ngày, họ làm việc cùng nhau mỗi ngày, chia sẻ thông tin và hỗ trợ lẫn nhau để hoàn thành tốt những nhiệm vụ kinh doanh quan trọng."
  },
  {
    "id": 83,
    "word": "another",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ɐnˈʌðə/",
    "meaning": "người khác; lẫn nhau",
    "ex1": "During busy working hours, they work together every day, share information, and support one another to complete important business tasks well.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, họ làm việc cùng nhau mỗi ngày, chia sẻ thông tin và hỗ trợ lẫn nhau để hoàn thành tốt những nhiệm vụ kinh doanh quan trọng."
  },
  {
    "id": 84,
    "word": "complete",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kəmplˈiːt/",
    "meaning": "hoàn thành",
    "ex1": "As part of regular work, they work together every day, share information, and support one another to complete important business tasks well.",
    "ex1_vi": "Là một phần của công việc thường ngày, họ làm việc cùng nhau mỗi ngày, chia sẻ thông tin và hỗ trợ lẫn nhau để hoàn thành tốt những nhiệm vụ kinh doanh quan trọng."
  },
  {
    "id": 85,
    "word": "business",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɪznəs/",
    "meaning": "kinh doanh",
    "ex1": "On a typical weekday, they work together every day, share information, and support one another to complete important business tasks well.",
    "ex1_vi": "Vào một ngày làm việc điển hình, họ làm việc cùng nhau mỗi ngày, chia sẻ thông tin và hỗ trợ lẫn nhau để hoàn thành tốt những nhiệm vụ kinh doanh quan trọng."
  },
  {
    "id": 86,
    "word": "well",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈɛl/",
    "meaning": "tốt",
    "ex1": "During ordinary office activities, they work together every day, share information, and support one another to complete important business tasks well.",
    "ex1_vi": "Trong các hoạt động văn phòng thông thường, họ làm việc cùng nhau mỗi ngày, chia sẻ thông tin và hỗ trợ lẫn nhau để hoàn thành tốt những nhiệm vụ kinh doanh quan trọng."
  },
  {
    "id": 87,
    "word": "manager",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈanɪdʒə/",
    "meaning": "quản lý",
    "ex1": "A manager leads the team and makes important decisions.",
    "ex1_vi": "Một quản lý dẫn dắt nhóm và đưa ra những quyết định quan trọng."
  },
  {
    "id": 88,
    "word": "leads",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈiːdz/",
    "meaning": "dẫn dắt",
    "ex1": "A manager leads the team and makes important decisions.",
    "ex1_vi": "Một quản lý dẫn dắt nhóm và đưa ra những quyết định quan trọng."
  },
  {
    "id": 89,
    "word": "team",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈiːm/",
    "meaning": "nhóm",
    "ex1": "During a normal workday, a manager leads the team and makes important decisions.",
    "ex1_vi": "Trong một ngày làm việc bình thường, một quản lý dẫn dắt nhóm và đưa ra những quyết định quan trọng."
  },
  {
    "id": 90,
    "word": "decisions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪsˈɪʒənz/",
    "meaning": "quyết định",
    "ex1": "In daily routines, a manager leads the team and makes important decisions.",
    "ex1_vi": "Trong các thói quen hằng ngày, một quản lý dẫn dắt nhóm và đưa ra những quyết định quan trọng."
  },
  {
    "id": 91,
    "word": "accountant",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɐkˈaʊntənt/",
    "meaning": "kế toán",
    "ex1": "An accountant checks money and financial records.",
    "ex1_vi": "Một kế toán kiểm tra tiền bạc và hồ sơ tài chính."
  },
  {
    "id": 92,
    "word": "checks",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈɛks/",
    "meaning": "kiểm tra",
    "ex1": "An accountant checks money and financial records.",
    "ex1_vi": "Một kế toán kiểm tra tiền bạc và hồ sơ tài chính."
  },
  {
    "id": 93,
    "word": "money",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌni/",
    "meaning": "tiền",
    "ex1": "During a normal workday, an accountant checks money and financial records.",
    "ex1_vi": "Trong một ngày làm việc bình thường, một kế toán kiểm tra tiền bạc và hồ sơ tài chính."
  },
  {
    "id": 94,
    "word": "financial",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/faɪnˈanʃəl/",
    "meaning": "tài chính",
    "ex1": "In daily routines, an accountant checks money and financial records.",
    "ex1_vi": "Trong các thói quen hằng ngày, một kế toán kiểm tra tiền bạc và hồ sơ tài chính."
  },
  {
    "id": 95,
    "word": "records",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɹˈɛkɔːdz/",
    "meaning": "hồ sơ",
    "ex1": "During busy working hours, an accountant checks money and financial records.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, một kế toán kiểm tra tiền bạc và hồ sơ tài chính."
  },
  {
    "id": 96,
    "word": "secretary",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛkɹətɹi/",
    "meaning": "thư ký",
    "ex1": "A secretary answers calls and arranges meetings.",
    "ex1_vi": "Một thư ký trả lời điện thoại và sắp xếp các cuộc họp."
  },
  {
    "id": 97,
    "word": "answers",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈansəz/",
    "meaning": "trả lời",
    "ex1": "A secretary answers calls and arranges meetings.",
    "ex1_vi": "Một thư ký trả lời điện thoại và sắp xếp các cuộc họp."
  },
  {
    "id": 98,
    "word": "arranges",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɐɹˈeɪndʒɪz/",
    "meaning": "sắp xếp",
    "ex1": "During a normal workday, a secretary answers calls and arranges meetings.",
    "ex1_vi": "Trong một ngày làm việc bình thường, một thư ký trả lời điện thoại và sắp xếp các cuộc họp."
  },
  {
    "id": 99,
    "word": "salesperson",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈeɪlspəsən/",
    "meaning": "nhân viên bán hàng",
    "ex1": "A salesperson talks with customers and sells products or useful services.",
    "ex1_vi": "Một nhân viên bán hàng nói chuyện với khách hàng và bán sản phẩm hoặc dịch vụ hữu ích."
  },
  {
    "id": 100,
    "word": "talks",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈɔːks/",
    "meaning": "nói chuyện",
    "ex1": "A salesperson talks with customers and sells products or useful services.",
    "ex1_vi": "Một nhân viên bán hàng nói chuyện với khách hàng và bán sản phẩm hoặc dịch vụ hữu ích."
  },
  {
    "id": 101,
    "word": "sells",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɛlz/",
    "meaning": "bán",
    "ex1": "During a normal workday, a salesperson talks with customers and sells products or useful services.",
    "ex1_vi": "Trong một ngày làm việc bình thường, một nhân viên bán hàng nói chuyện với khách hàng và bán sản phẩm hoặc dịch vụ hữu ích."
  },
  {
    "id": 102,
    "word": "products",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɹˈɒdʌkts/",
    "meaning": "sản phẩm",
    "ex1": "In daily routines, a salesperson talks with customers and sells products or useful services.",
    "ex1_vi": "Trong các thói quen hằng ngày, một nhân viên bán hàng nói chuyện với khách hàng và bán sản phẩm hoặc dịch vụ hữu ích."
  },
  {
    "id": 103,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔː/",
    "meaning": "hoặc",
    "ex1": "During busy working hours, a salesperson talks with customers and sells products or useful services.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, một nhân viên bán hàng nói chuyện với khách hàng và bán sản phẩm hoặc dịch vụ hữu ích."
  },
  {
    "id": 104,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈuːsfəl/",
    "meaning": "hữu ích",
    "ex1": "As part of regular work, a salesperson talks with customers and sells products or useful services.",
    "ex1_vi": "Là một phần của công việc thường ngày, một nhân viên bán hàng nói chuyện với khách hàng và bán sản phẩm hoặc dịch vụ hữu ích."
  },
  {
    "id": 105,
    "word": "services",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɜːvɪsɪz/",
    "meaning": "dịch vụ",
    "ex1": "On a typical weekday, a salesperson talks with customers and sells products or useful services.",
    "ex1_vi": "Vào một ngày làm việc điển hình, một nhân viên bán hàng nói chuyện với khách hàng và bán sản phẩm hoặc dịch vụ hữu ích."
  },
  {
    "id": 106,
    "word": "job",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɒb/",
    "meaning": "công việc",
    "ex1": "Every office job is important because each person has different responsibilities.",
    "ex1_vi": "Mỗi công việc văn phòng đều quan trọng vì mỗi người có những trách nhiệm khác nhau."
  },
  {
    "id": 107,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈʌz/",
    "meaning": "bởi vì",
    "ex1": "Every office job is important because each person has different responsibilities.",
    "ex1_vi": "Mỗi công việc văn phòng đều quan trọng vì mỗi người có những trách nhiệm khác nhau."
  },
  {
    "id": 108,
    "word": "person",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɜːsən/",
    "meaning": "người",
    "ex1": "During a normal workday, every office job is important because each person has different responsibilities.",
    "ex1_vi": "Trong một ngày làm việc bình thường, mỗi công việc văn phòng đều quan trọng vì mỗi người có những trách nhiệm khác nhau."
  },
  {
    "id": 109,
    "word": "responsibilities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɹɪspˌɒnsəbˈɪlɪtiz/",
    "meaning": "trách nhiệm",
    "ex1": "In daily routines, every office job is important because each person has different responsibilities.",
    "ex1_vi": "Trong các thói quen hằng ngày, mỗi công việc văn phòng đều quan trọng vì mỗi người có những trách nhiệm khác nhau."
  },
  {
    "id": 110,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "Workers should be careful, friendly, and organized.",
    "ex1_vi": "Nhân viên nên cẩn thận, thân thiện và có tổ chức."
  },
  {
    "id": 111,
    "word": "friendly",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fɹˈɛndli/",
    "meaning": "thân thiện",
    "ex1": "Workers should be careful, friendly, and organized.",
    "ex1_vi": "Nhân viên nên cẩn thận, thân thiện và có tổ chức."
  },
  {
    "id": 112,
    "word": "organized",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɔːɡɐnˌaɪzd/",
    "meaning": "có tổ chức; ngăn nắp",
    "ex1": "During a normal workday, workers should be careful, friendly, and organized.",
    "ex1_vi": "Trong một ngày làm việc bình thường, nhân viên nên cẩn thận, thân thiện và có tổ chức."
  },
  {
    "id": 113,
    "word": "successfully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/səksˈɛsfəli/",
    "meaning": "một cách thành công",
    "ex1": "Good communication and teamwork help everyone finish work successfully and create a better workplace for all.",
    "ex1_vi": "Giao tiếp tốt và tinh thần làm việc nhóm giúp mọi người hoàn thành công việc thành công và tạo ra một nơi làm việc tốt hơn cho tất cả."
  },
  {
    "id": 114,
    "word": "create",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kɹiːˈeɪt/",
    "meaning": "tạo ra",
    "ex1": "Good communication and teamwork help everyone finish work successfully and create a better workplace for all.",
    "ex1_vi": "Giao tiếp tốt và tinh thần làm việc nhóm giúp mọi người hoàn thành công việc thành công và tạo ra một nơi làm việc tốt hơn cho tất cả."
  },
  {
    "id": 115,
    "word": "better",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/bˈɛtə/",
    "meaning": "tốt hơn",
    "ex1": "During a normal workday, good communication and teamwork help everyone finish work successfully and create a better workplace for all.",
    "ex1_vi": "Trong một ngày làm việc bình thường, giao tiếp tốt và tinh thần làm việc nhóm giúp mọi người hoàn thành công việc thành công và tạo ra một nơi làm việc tốt hơn cho tất cả."
  },
  {
    "id": 116,
    "word": "workplace",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɜːkpleɪs/",
    "meaning": "nơi làm việc",
    "ex1": "In daily routines, good communication and teamwork help everyone finish work successfully and create a better workplace for all.",
    "ex1_vi": "Trong các thói quen hằng ngày, giao tiếp tốt và tinh thần làm việc nhóm giúp mọi người hoàn thành công việc thành công và tạo ra một nơi làm việc tốt hơn cho tất cả."
  },
  {
    "id": 117,
    "word": "equipment",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪkwˈɪpmənt/",
    "meaning": "thiết bị",
    "ex1": "Employees use different equipment to finish tasks quickly and correctly.",
    "ex1_vi": "Nhân viên sử dụng các thiết bị khác nhau để hoàn thành nhiệm vụ nhanh chóng và chính xác."
  },
  {
    "id": 118,
    "word": "machines",
    "type": "noun",
    "cat": "n",
    "phonetic": "/məʃˈiːnz/",
    "meaning": "máy móc",
    "ex1": "An office has many useful machines and tools for daily work.",
    "ex1_vi": "Một văn phòng có nhiều máy móc và công cụ hữu ích cho công việc hằng ngày."
  },
  {
    "id": 119,
    "word": "tools",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈuːlz/",
    "meaning": "công cụ",
    "ex1": "An office has many useful machines and tools for daily work.",
    "ex1_vi": "Một văn phòng có nhiều máy móc và công cụ hữu ích cho công việc hằng ngày."
  },
  {
    "id": 120,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuːs/",
    "meaning": "sử dụng",
    "ex1": "Employees use different equipment to finish tasks quickly and correctly.",
    "ex1_vi": "Nhân viên sử dụng các thiết bị khác nhau để hoàn thành nhiệm vụ nhanh chóng và chính xác."
  },
  {
    "id": 121,
    "word": "quickly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kwˈɪkli/",
    "meaning": "nhanh chóng",
    "ex1": "During a normal workday, employees use different equipment to finish tasks quickly and correctly.",
    "ex1_vi": "Trong một ngày làm việc bình thường, nhân viên sử dụng các thiết bị khác nhau để hoàn thành nhiệm vụ nhanh chóng và chính xác."
  },
  {
    "id": 122,
    "word": "correctly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kəɹˈɛktli/",
    "meaning": "đúng cách",
    "ex1": "In daily routines, employees use different equipment to finish tasks quickly and correctly.",
    "ex1_vi": "Trong các thói quen hằng ngày, nhân viên sử dụng các thiết bị khác nhau để hoàn thành nhiệm vụ nhanh chóng và chính xác."
  },
  {
    "id": 123,
    "word": "save",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪv/",
    "meaning": "tiết kiệm",
    "ex1": "Good office equipment helps workers save time and improve the quality of their daily jobs.",
    "ex1_vi": "Thiết bị văn phòng tốt giúp nhân viên tiết kiệm thời gian và nâng cao chất lượng công việc hằng ngày."
  },
  {
    "id": 124,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "Good office equipment helps workers save time and improve the quality of their daily jobs.",
    "ex1_vi": "Thiết bị văn phòng tốt giúp nhân viên tiết kiệm thời gian và nâng cao chất lượng công việc hằng ngày."
  },
  {
    "id": 125,
    "word": "improve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɪmpɹˈuːv/",
    "meaning": "cải thiện",
    "ex1": "During a normal workday, good office equipment helps workers save time and improve the quality of their daily jobs.",
    "ex1_vi": "Trong một ngày làm việc bình thường, thiết bị văn phòng tốt giúp nhân viên tiết kiệm thời gian và nâng cao chất lượng công việc hằng ngày."
  },
  {
    "id": 126,
    "word": "quality",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kwˈɒlɪti/",
    "meaning": "chất lượng",
    "ex1": "In daily routines, good office equipment helps workers save time and improve the quality of their daily jobs.",
    "ex1_vi": "Trong các thói quen hằng ngày, thiết bị văn phòng tốt giúp nhân viên tiết kiệm thời gian và nâng cao chất lượng công việc hằng ngày."
  },
  {
    "id": 127,
    "word": "send",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɛnd/",
    "meaning": "gửi",
    "ex1": "Computers help people write reports, send emails, and store information.",
    "ex1_vi": "Máy tính giúp mọi người viết báo cáo, gửi email và lưu trữ thông tin."
  },
  {
    "id": 128,
    "word": "store",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈɔː/",
    "meaning": "lưu trữ",
    "ex1": "Computers help people write reports, send emails, and store information.",
    "ex1_vi": "Máy tính giúp mọi người viết báo cáo, gửi email và lưu trữ thông tin."
  },
  {
    "id": 129,
    "word": "printers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɹˈɪntəz/",
    "meaning": "máy in",
    "ex1": "Printers make paper copies of documents.",
    "ex1_vi": "Máy in tạo các bản sao tài liệu trên giấy."
  },
  {
    "id": 130,
    "word": "paper",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈeɪpə/",
    "meaning": "giấy",
    "ex1": "Printers make paper copies of documents.",
    "ex1_vi": "Máy in tạo các bản sao tài liệu trên giấy."
  },
  {
    "id": 131,
    "word": "copies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɒpɪz/",
    "meaning": "bản sao",
    "ex1": "During a normal workday, printers make paper copies of documents.",
    "ex1_vi": "Trong một ngày làm việc bình thường, máy in tạo các bản sao tài liệu trên giấy."
  },
  {
    "id": 132,
    "word": "telephones",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛlɪfˌəʊnz/",
    "meaning": "điện thoại",
    "ex1": "Telephones help workers speak with customers.",
    "ex1_vi": "Điện thoại giúp nhân viên nói chuyện với khách hàng."
  },
  {
    "id": 133,
    "word": "speak",
    "type": "verb",
    "cat": "v",
    "phonetic": "/spˈiːk/",
    "meaning": "nói",
    "ex1": "Telephones help workers speak with customers.",
    "ex1_vi": "Điện thoại giúp nhân viên nói chuyện với khách hàng."
  },
  {
    "id": 134,
    "word": "photocopiers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈəʊtəkˌɒpiəz/",
    "meaning": "máy photocopy",
    "ex1": "Photocopiers produce extra copies for meetings and office files every day.",
    "ex1_vi": "Máy photocopy tạo thêm bản sao cho các cuộc họp và hồ sơ văn phòng mỗi ngày."
  },
  {
    "id": 135,
    "word": "produce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹədjˈuːs/",
    "meaning": "sản xuất",
    "ex1": "Photocopiers produce extra copies for meetings and office files every day.",
    "ex1_vi": "Máy photocopy tạo thêm bản sao cho các cuộc họp và hồ sơ văn phòng mỗi ngày."
  },
  {
    "id": 136,
    "word": "extra",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɛkstɹə/",
    "meaning": "thêm",
    "ex1": "During a normal workday, photocopiers produce extra copies for meetings and office files every day.",
    "ex1_vi": "Trong một ngày làm việc bình thường, máy photocopy tạo thêm bản sao cho các cuộc họp và hồ sơ văn phòng mỗi ngày."
  },
  {
    "id": 137,
    "word": "files",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈaɪlz/",
    "meaning": "tệp; hồ sơ",
    "ex1": "In daily routines, photocopiers produce extra copies for meetings and office files every day.",
    "ex1_vi": "Trong các thói quen hằng ngày, máy photocopy tạo thêm bản sao cho các cuộc họp và hồ sơ văn phòng mỗi ngày."
  },
  {
    "id": 138,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈeəfəli/",
    "meaning": "cẩn thận",
    "ex1": "Workers should use office equipment carefully and follow simple instructions.",
    "ex1_vi": "Nhân viên nên sử dụng thiết bị văn phòng cẩn thận và làm theo các hướng dẫn đơn giản."
  },
  {
    "id": 139,
    "word": "follow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɒləʊ/",
    "meaning": "theo",
    "ex1": "Workers should use office equipment carefully and follow simple instructions.",
    "ex1_vi": "Nhân viên nên sử dụng thiết bị văn phòng cẩn thận và làm theo các hướng dẫn đơn giản."
  },
  {
    "id": 140,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpəl/",
    "meaning": "đơn giản",
    "ex1": "During a normal workday, workers should use office equipment carefully and follow simple instructions.",
    "ex1_vi": "Trong một ngày làm việc bình thường, nhân viên nên sử dụng thiết bị văn phòng cẩn thận và làm theo các hướng dẫn đơn giản."
  },
  {
    "id": 141,
    "word": "instructions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪnstɹˈʌkʃənz/",
    "meaning": "hướng dẫn",
    "ex1": "In daily routines, workers should use office equipment carefully and follow simple instructions.",
    "ex1_vi": "Trong các thói quen hằng ngày, nhân viên nên sử dụng thiết bị văn phòng cẩn thận và làm theo các hướng dẫn đơn giản."
  },
  {
    "id": 142,
    "word": "keeping",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/kˈiːpɪŋ/",
    "meaning": "việc giữ",
    "ex1": "Keeping machines clean and reporting problems quickly helps prevent damage.",
    "ex1_vi": "Giữ máy móc sạch sẽ và báo cáo sự cố nhanh chóng giúp ngăn ngừa hư hỏng."
  },
  {
    "id": 143,
    "word": "clean",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈiːn/",
    "meaning": "sạch",
    "ex1": "Keeping machines clean and reporting problems quickly helps prevent damage.",
    "ex1_vi": "Giữ máy móc sạch sẽ và báo cáo sự cố nhanh chóng giúp ngăn ngừa hư hỏng."
  },
  {
    "id": 144,
    "word": "reporting",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/ɹɪpˈɔːtɪŋ/",
    "meaning": "việc báo cáo",
    "ex1": "During a normal workday, keeping machines clean and reporting problems quickly helps prevent damage.",
    "ex1_vi": "Trong một ngày làm việc bình thường, giữ máy móc sạch sẽ và báo cáo sự cố nhanh chóng giúp ngăn ngừa hư hỏng."
  },
  {
    "id": 145,
    "word": "problems",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɹˈɒbləmz/",
    "meaning": "vấn đề",
    "ex1": "In daily routines, keeping machines clean and reporting problems quickly helps prevent damage.",
    "ex1_vi": "Trong các thói quen hằng ngày, giữ máy móc sạch sẽ và báo cáo sự cố nhanh chóng giúp ngăn ngừa hư hỏng."
  },
  {
    "id": 146,
    "word": "prevent",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹɪvˈɛnt/",
    "meaning": "ngăn ngừa",
    "ex1": "During busy working hours, keeping machines clean and reporting problems quickly helps prevent damage.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, giữ máy móc sạch sẽ và báo cáo sự cố nhanh chóng giúp ngăn ngừa hư hỏng."
  },
  {
    "id": 147,
    "word": "damage",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈamɪdʒ/",
    "meaning": "hư hỏng",
    "ex1": "As part of regular work, keeping machines clean and reporting problems quickly helps prevent damage.",
    "ex1_vi": "Là một phần của công việc thường ngày, giữ máy móc sạch sẽ và báo cáo sự cố nhanh chóng giúp ngăn ngừa hư hỏng."
  },
  {
    "id": 148,
    "word": "safer",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪfə/",
    "meaning": "an toàn hơn",
    "ex1": "Good equipment and careful use make the office safer, faster, and more productive every day.",
    "ex1_vi": "Thiết bị tốt và cách sử dụng cẩn thận làm cho văn phòng an toàn hơn, nhanh hơn và hiệu quả hơn mỗi ngày."
  },
  {
    "id": 149,
    "word": "productive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pɹədˈʌktɪv/",
    "meaning": "năng suất; hiệu quả",
    "ex1": "Good equipment and careful use make the office safer, faster, and more productive every day.",
    "ex1_vi": "Thiết bị tốt và cách sử dụng cẩn thận làm cho văn phòng an toàn hơn, nhanh hơn và hiệu quả hơn mỗi ngày."
  }
];

const newReadingVocabOrder = [
  "busy",
  "office",
  "many",
  "people",
  "work",
  "modern",
  "every",
  "day",
  "has",
  "desks",
  "computers",
  "and",
  "bright",
  "lights",
  "workers",
  "arrive",
  "early",
  "greet",
  "start",
  "tasks",
  "everyone",
  "stays",
  "during",
  "whole",
  "morning",
  "together",
  "employees",
  "answer",
  "emails",
  "make",
  "phone",
  "calls",
  "write",
  "reports",
  "attend",
  "meetings",
  "talk",
  "customers",
  "while",
  "others",
  "prepare",
  "documents",
  "help",
  "when",
  "needed",
  "good",
  "teamwork",
  "makes",
  "daily",
  "easier",
  "faster",
  "afternoon",
  "finish",
  "important",
  "organize",
  "before",
  "leaving",
  "check",
  "tomorrow's",
  "schedule",
  "say",
  "goodbye",
  "needs",
  "responsible",
  "clear",
  "communication",
  "careful",
  "planning",
  "single",
  "jobs",
  "have",
  "different",
  "worker",
  "special",
  "duties",
  "helps",
  "company",
  "succeed",
  "share",
  "information",
  "support",
  "one",
  "another",
  "complete",
  "business",
  "well",
  "manager",
  "leads",
  "team",
  "decisions",
  "accountant",
  "checks",
  "money",
  "financial",
  "records",
  "secretary",
  "answers",
  "arranges",
  "salesperson",
  "talks",
  "sells",
  "products",
  "or",
  "useful",
  "services",
  "job",
  "because",
  "person",
  "responsibilities",
  "should",
  "friendly",
  "organized",
  "successfully",
  "create",
  "better",
  "workplace",
  "equipment",
  "machines",
  "tools",
  "use",
  "quickly",
  "correctly",
  "save",
  "time",
  "improve",
  "quality",
  "send",
  "store",
  "printers",
  "paper",
  "copies",
  "telephones",
  "speak",
  "photocopiers",
  "produce",
  "extra",
  "files",
  "carefully",
  "follow",
  "simple",
  "instructions",
  "keeping",
  "clean",
  "reporting",
  "problems",
  "prevent",
  "damage",
  "safer",
  "productive"
];
