// ===== office01 ESSAY =====

const newEssayData = [
  {
    "text": "1. A Busy Office\nMany people work in a modern office every day. The office has many desks, computers, and bright lights. Workers arrive early, greet each other, and start their tasks. Everyone stays busy during the whole morning together.\n\nEmployees answer emails, make phone calls, write reports, and attend meetings. Some talk with customers, while others prepare documents. They help each other when needed. Good teamwork makes daily work easier and faster for everyone.\n\nIn the afternoon, workers finish important tasks and organize their desks. Before leaving, they check tomorrow's schedule and say goodbye. A busy office needs responsible people, clear communication, and careful planning every single day.",
    "vi": "1. Một văn phòng bận rộn\nNhiều người làm việc trong một văn phòng hiện đại mỗi ngày. Văn phòng có nhiều bàn làm việc, máy tính và đèn sáng. Nhân viên đến sớm, chào nhau và bắt đầu công việc của mình. Mọi người đều bận rộn suốt cả buổi sáng cùng nhau.\n\n\n\nNhân viên trả lời email, gọi điện thoại, viết báo cáo và tham dự các cuộc họp. Một số người nói chuyện với khách hàng, trong khi những người khác chuẩn bị tài liệu. Họ giúp đỡ nhau khi cần. Tinh thần làm việc nhóm tốt giúp công việc hằng ngày trở nên dễ dàng và nhanh chóng hơn cho mọi người.\n\n\n\nVào buổi chiều, nhân viên hoàn thành các nhiệm vụ quan trọng và sắp xếp bàn làm việc. Trước khi ra về, họ kiểm tra lịch trình ngày mai và chào tạm biệt. Một văn phòng bận rộn cần những người có trách nhiệm, giao tiếp rõ ràng và lập kế hoạch cẩn thận mỗi ngày."
  },
  {
    "text": "2. Office Jobs\nMany people have different jobs in an office. Each worker has special duties and helps the company succeed. They work together every day, share information, and support one another to complete important business tasks well.\n\nA manager leads the team and makes important decisions. An accountant checks money and financial records. A secretary answers calls and arranges meetings. A salesperson talks with customers and sells products or useful services.\n\nEvery office job is important because each person has different responsibilities. Workers should be careful, friendly, and organized. Good communication and teamwork help everyone finish work successfully and create a better workplace for all.",
    "vi": "2. Các công việc văn phòng\nNhiều người có những công việc khác nhau trong một văn phòng. Mỗi nhân viên có nhiệm vụ riêng và góp phần giúp công ty thành công. Họ làm việc cùng nhau mỗi ngày, chia sẻ thông tin và hỗ trợ lẫn nhau để hoàn thành tốt những nhiệm vụ kinh doanh quan trọng.\n\n\n\nMột quản lý dẫn dắt nhóm và đưa ra những quyết định quan trọng. Một kế toán kiểm tra tiền bạc và hồ sơ tài chính. Một thư ký trả lời điện thoại và sắp xếp các cuộc họp. Một nhân viên bán hàng nói chuyện với khách hàng và bán sản phẩm hoặc dịch vụ hữu ích.\n\n\n\nMỗi công việc văn phòng đều quan trọng vì mỗi người có những trách nhiệm khác nhau. Nhân viên nên cẩn thận, thân thiện và có tổ chức. Giao tiếp tốt và tinh thần làm việc nhóm giúp mọi người hoàn thành công việc thành công và tạo ra một nơi làm việc tốt hơn cho tất cả."
  },
  {
    "text": "3. Office Equipment\nAn office has many useful machines and tools for daily work. Employees use different equipment to finish tasks quickly and correctly. Good office equipment helps workers save time and improve the quality of their daily jobs.\n\nComputers help people write reports, send emails, and store information. Printers make paper copies of documents. Telephones help workers speak with customers. Photocopiers produce extra copies for meetings and office files every day.\n\nWorkers should use office equipment carefully and follow simple instructions. Keeping machines clean and reporting problems quickly helps prevent damage. Good equipment and careful use make the office safer, faster, and more productive every day.",
    "vi": "3. Thiết bị văn phòng\nMột văn phòng có nhiều máy móc và công cụ hữu ích cho công việc hằng ngày. Nhân viên sử dụng các thiết bị khác nhau để hoàn thành nhiệm vụ nhanh chóng và chính xác. Thiết bị văn phòng tốt giúp nhân viên tiết kiệm thời gian và nâng cao chất lượng công việc hằng ngày.\n\n\n\nMáy tính giúp mọi người viết báo cáo, gửi email và lưu trữ thông tin. Máy in tạo các bản sao tài liệu trên giấy. Điện thoại giúp nhân viên nói chuyện với khách hàng. Máy photocopy tạo thêm bản sao cho các cuộc họp và hồ sơ văn phòng mỗi ngày.\n\n\n\nNhân viên nên sử dụng thiết bị văn phòng cẩn thận và làm theo các hướng dẫn đơn giản. Giữ máy móc sạch sẽ và báo cáo sự cố nhanh chóng giúp ngăn ngừa hư hỏng. Thiết bị tốt và cách sử dụng cẩn thận làm cho văn phòng an toàn hơn, nhanh hơn và hiệu quả hơn mỗi ngày."
  }
];
