const lessonVocabularyWords = [
  "seafood",
  "fried",
  "rice",
  "colorful",
  "and",
  "satisfying",
  "dish",
  "cooked",
  "shrimp",
  "squid",
  "eggs",
  "carrots",
  "peas",
  "onions",
  "simple",
  "seasonings",
  "cook",
  "mixes",
  "everything",
  "hot",
  "pan",
  "until",
  "becomes",
  "dry",
  "fragrant",
  "evenly",
  "heated",
  "often",
  "served",
  "cucumber",
  "tomato",
  "chili",
  "sauce",
  "or",
  "soy",
  "adds",
  "sweet",
  "taste",
  "while",
  "vegetables",
  "make",
  "meal",
  "fresh",
  "attractive",
  "suitable",
  "lunch",
  "dinner",
  "easy",
  "prepare",
  "leftover",
  "small",
  "amounts",
  "also",
  "convenient",
  "busy",
  "families",
  "good",
  "plate",
  "should",
  "have",
  "separate",
  "grains",
  "balanced",
  "flavors",
  "ingredients",
  "throughout",
  "noodles",
  "popular",
  "many",
  "asian",
  "countries",
  "bowl",
  "usually",
  "contains",
  "fish",
  "balls",
  "flavorful",
  "broth",
  "soup",
  "can",
  "clear",
  "spicy",
  "sour",
  "creamy",
  "depending",
  "local",
  "cooking",
  "style",
  "people",
  "add",
  "green",
  "herbs",
  "lime",
  "juice",
  "before",
  "eating",
  "soft",
  "gives",
  "flavor",
  "commonly",
  "eaten",
  "breakfast",
  "filling",
  "but",
  "not",
  "too",
  "heavy",
  "provide",
  "energy",
  "protein",
  "one",
  "especially",
  "enjoyable",
  "rainy",
  "days",
  "when",
  "want",
  "quick",
  "comforting",
  "grilled",
  "oysters",
  "rich",
  "opened",
  "carefully",
  "placed",
  "grill",
  "cheese",
  "butter",
  "garlic",
  "peanuts",
  "ready",
  "topping",
  "melts",
  "meat",
  "salty",
  "slightly",
  "smoky",
  "directly",
  "shells",
  "spoon",
  "common",
  "restaurants",
  "street",
  "stalls",
  "outdoor",
  "parties",
  "properly",
  "safety",
  "prepared",
  "well",
  "juicy",
  "full",
  "enjoy",
  "trying",
  "different",
  "toppings",
  "sharing",
  "several",
  "together",
  "friends",
  "golden",
  "then",
  "covered",
  "made",
  "tomatoes",
  "pineapple",
  "sugar",
  "vinegar",
  "bright",
  "appearance",
  "crispy",
  "outside",
  "inside",
  "tastes",
  "eat",
  "family",
  "meals",
  "because",
  "combines",
  "strong",
  "children",
  "adults",
  "keep",
  "tender"
];

const newVocabData = [
  {
    "id": 1,
    "word": "seafood",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsiːfuːd/",
    "meaning": "hải sản",
    "ex1": "Seafood noodles are filling but not too heavy.",
    "ex1_vi": "Mì hải sản làm no nhưng không quá nặng bụng."
  },
  {
    "id": 2,
    "word": "fried",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈaɪd/",
    "meaning": "chiên",
    "ex1": "Seafood fried rice is a colorful and satisfying dish.",
    "ex1_vi": "Cơm chiên hải sản là một món ăn nhiều màu sắc và no bụng."
  },
  {
    "id": 3,
    "word": "rice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪs/",
    "meaning": "cơm; gạo",
    "ex1": "Seafood fried rice is a colorful and satisfying dish.",
    "ex1_vi": "Cơm chiên hải sản là một món ăn nhiều màu sắc và no bụng."
  },
  {
    "id": 4,
    "word": "colorful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌlɝfʌl/",
    "meaning": "nhiều màu sắc",
    "ex1": "People discuss colorful during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về nhiều màu sắc trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 5,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "People eat seafood and vegetables together during family meals.",
    "ex1_vi": "Mọi người ăn hải sản và rau cùng nhau trong các bữa ăn gia đình."
  },
  {
    "id": 6,
    "word": "satisfying",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈætɪsfˌaɪɪŋ/",
    "meaning": "no bụng; thỏa mãn",
    "ex1": "People discuss satisfying during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về no bụng; thỏa mãn trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 7,
    "word": "dish",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪʃ/",
    "meaning": "món ăn",
    "ex1": "People discuss dish during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về món ăn trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 8,
    "word": "cooked",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʊkt/",
    "meaning": "được nấu",
    "ex1": "Oysters should be fresh and cooked properly for safety.",
    "ex1_vi": "Hàu nên tươi và được nấu đúng cách để bảo đảm an toàn."
  },
  {
    "id": 9,
    "word": "shrimp",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃrˈɪmp/",
    "meaning": "tôm",
    "ex1": "Families talk about shrimp during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về tôm trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 10,
    "word": "squid",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skwˈɪd/",
    "meaning": "mực",
    "ex1": "Fresh seafood can include squid in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có mực."
  },
  {
    "id": 11,
    "word": "eggs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛɡz/",
    "meaning": "trứng",
    "ex1": "People enjoy eggs during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức trứng trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 12,
    "word": "carrots",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈærʌts/",
    "meaning": "cà rốt",
    "ex1": "Families talk about carrots during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về cà rốt trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 13,
    "word": "peas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈiz/",
    "meaning": "đậu Hà Lan",
    "ex1": "Fresh seafood can include peas in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có đậu Hà Lan."
  },
  {
    "id": 14,
    "word": "onions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈʌnjʌnz/",
    "meaning": "hành",
    "ex1": "People often add green onions, herbs, lime juice, and chili before eating.",
    "ex1_vi": "Mọi người thường thêm hành lá, rau thơm, nước cốt chanh và ớt trước khi ăn."
  },
  {
    "id": 15,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "Fresh seafood can taste simple during a warm family meal.",
    "ex1_vi": "Hải sản tươi có thể có vị đơn giản trong một bữa ăn gia đình ấm áp."
  },
  {
    "id": 16,
    "word": "seasonings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈizʌnɪŋz/",
    "meaning": "gia vị",
    "ex1": "Fresh seafood can include seasonings in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có gia vị."
  },
  {
    "id": 17,
    "word": "cook",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʊk/",
    "meaning": "người nấu; nấu",
    "ex1": "Cooks cook seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu người nấu; nấu hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 18,
    "word": "mixes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɪksʌz/",
    "meaning": "trộn",
    "ex1": "Families talk about mixes during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về trộn trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 19,
    "word": "everything",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvriθˌɪŋ/",
    "meaning": "mọi thứ",
    "ex1": "The cook mixes everything in a hot pan carefully.",
    "ex1_vi": "Người nấu trộn mọi thứ trong chảo nóng một cách cẩn thận."
  },
  {
    "id": 20,
    "word": "hot",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑt/",
    "meaning": "nóng",
    "ex1": "A well-prepared seafood meal can feel hot and satisfying.",
    "ex1_vi": "Một bữa hải sản được chuẩn bị tốt có thể nóng và làm no."
  },
  {
    "id": 21,
    "word": "pan",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈæn/",
    "meaning": "chảo",
    "ex1": "Families talk about pan during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về chảo trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 22,
    "word": "until",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌntˈɪl/",
    "meaning": "cho đến khi",
    "ex1": "The seafood cooks until it becomes hot and ready.",
    "ex1_vi": "Hải sản được nấu cho đến khi nóng và sẵn sàng."
  },
  {
    "id": 23,
    "word": "becomes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌmz/",
    "meaning": "trở nên",
    "ex1": "Cooks becomes seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu trở nên hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 24,
    "word": "dry",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/drˈaɪ/",
    "meaning": "khô",
    "ex1": "Fresh seafood can taste dry during a warm family meal.",
    "ex1_vi": "Hải sản tươi có thể có vị khô trong một bữa ăn gia đình ấm áp."
  },
  {
    "id": 25,
    "word": "fragrant",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈeɪɡrʌnt/",
    "meaning": "thơm",
    "ex1": "This seafood dish looks fragrant when served at the table.",
    "ex1_vi": "Món hải sản này trông thơm khi được phục vụ tại bàn."
  },
  {
    "id": 26,
    "word": "evenly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈivʌnli/",
    "meaning": "đều",
    "ex1": "Cooks evenly serve seafood when it is hot and fresh.",
    "ex1_vi": "Người nấu đều phục vụ hải sản khi còn nóng và tươi."
  },
  {
    "id": 27,
    "word": "heated",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈitʌd/",
    "meaning": "được làm nóng",
    "ex1": "Families heated fresh seafood during relaxed weekend meals.",
    "ex1_vi": "Các gia đình được làm nóng hải sản tươi trong những bữa ăn cuối tuần thư giãn."
  },
  {
    "id": 28,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "People often add green onions, herbs, lime juice, and chili before eating.",
    "ex1_vi": "Mọi người thường thêm hành lá, rau thơm, nước cốt chanh và ớt trước khi ăn."
  },
  {
    "id": 29,
    "word": "served",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɝvd/",
    "meaning": "được phục vụ",
    "ex1": "Cooks served seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu được phục vụ hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 30,
    "word": "cucumber",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kjˈukʌmbɝ/",
    "meaning": "dưa leo",
    "ex1": "Families talk about cucumber during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về dưa leo trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 31,
    "word": "tomato",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʌmˈeɪtˌoʊ/",
    "meaning": "cà chua",
    "ex1": "Fresh seafood can include tomato in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có cà chua."
  },
  {
    "id": 32,
    "word": "chili",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪli/",
    "meaning": "ớt",
    "ex1": "People discuss chili during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về ớt trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 33,
    "word": "sauce",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔs/",
    "meaning": "nước sốt; nước chấm",
    "ex1": "The sauce tastes sweet, sour, and slightly salty.",
    "ex1_vi": "Nước sốt có vị ngọt, chua và hơi mặn."
  },
  {
    "id": 34,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "Families serve seafood with rice or fresh vegetables.",
    "ex1_vi": "Các gia đình dùng hải sản với cơm hoặc rau tươi."
  },
  {
    "id": 35,
    "word": "soy",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔɪ/",
    "meaning": "đậu nành",
    "ex1": "People enjoy soy during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức đậu nành trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 36,
    "word": "adds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈædz/",
    "meaning": "thêm",
    "ex1": "Families talk about adds during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về thêm trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 37,
    "word": "sweet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/swˈit/",
    "meaning": "ngọt",
    "ex1": "The sauce tastes sweet, sour, and slightly salty.",
    "ex1_vi": "Nước sốt có vị ngọt, chua và hơi mặn."
  },
  {
    "id": 38,
    "word": "taste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪst/",
    "meaning": "có vị",
    "ex1": "People enjoy taste during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức có vị trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 39,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "People talk while the seafood cooks at the table.",
    "ex1_vi": "Mọi người trò chuyện trong khi hải sản được nấu tại bàn."
  },
  {
    "id": 40,
    "word": "vegetables",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɛdʒtʌbʌlz/",
    "meaning": "rau",
    "ex1": "They provide energy, protein, and vegetables in one bowl.",
    "ex1_vi": "Chúng cung cấp năng lượng, protein và rau trong một tô."
  },
  {
    "id": 41,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm cho",
    "ex1": "Cooks make seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu làm cho hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 42,
    "word": "meal",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈil/",
    "meaning": "bữa ăn",
    "ex1": "Seafood noodles are a popular meal in many Asian countries.",
    "ex1_vi": "Mì hải sản là một bữa ăn phổ biến ở nhiều quốc gia châu Á."
  },
  {
    "id": 43,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi",
    "ex1": "Oysters should be fresh and cooked properly for safety.",
    "ex1_vi": "Hàu nên tươi và được nấu đúng cách để bảo đảm an toàn."
  },
  {
    "id": 44,
    "word": "attractive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌtrˈæktɪv/",
    "meaning": "hấp dẫn",
    "ex1": "The sauce gives the dish a bright and attractive appearance.",
    "ex1_vi": "Nước sốt làm món ăn có vẻ ngoài sáng và hấp dẫn."
  },
  {
    "id": 45,
    "word": "suitable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈutʌbʌl/",
    "meaning": "phù hợp",
    "ex1": "Fresh seafood can taste suitable during a warm family meal.",
    "ex1_vi": "Hải sản tươi có thể có vị phù hợp trong một bữa ăn gia đình ấm áp."
  },
  {
    "id": 46,
    "word": "lunch",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈʌntʃ/",
    "meaning": "bữa trưa",
    "ex1": "Fresh seafood can include lunch in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có bữa trưa."
  },
  {
    "id": 47,
    "word": "dinner",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪnɝ/",
    "meaning": "bữa tối",
    "ex1": "People enjoy dinner during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức bữa tối trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 48,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "Fresh seafood can taste easy during a warm family meal.",
    "ex1_vi": "Hải sản tươi có thể có vị dễ trong một bữa ăn gia đình ấm áp."
  },
  {
    "id": 49,
    "word": "prepare",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pripˈɛr/",
    "meaning": "chuẩn bị",
    "ex1": "People can prepare seafood carefully for a family dinner.",
    "ex1_vi": "Mọi người có thể chuẩn bị hải sản cẩn thận cho một bữa tối gia đình."
  },
  {
    "id": 50,
    "word": "leftover",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɛftˌoʊvɝ/",
    "meaning": "còn thừa",
    "ex1": "People enjoy leftover during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức còn thừa trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 51,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "Fresh seafood can taste small during a warm family meal.",
    "ex1_vi": "Hải sản tươi có thể có vị nhỏ trong một bữa ăn gia đình ấm áp."
  },
  {
    "id": 52,
    "word": "amounts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌmˈaʊnts/",
    "meaning": "lượng",
    "ex1": "Fresh seafood can include amounts in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có lượng."
  },
  {
    "id": 53,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "Cooks also serve seafood when it is hot and fresh.",
    "ex1_vi": "Người nấu cũng phục vụ hải sản khi còn nóng và tươi."
  },
  {
    "id": 54,
    "word": "convenient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kʌnvˈinjʌnt/",
    "meaning": "tiện lợi",
    "ex1": "Fresh seafood can taste convenient during a warm family meal.",
    "ex1_vi": "Hải sản tươi có thể có vị tiện lợi trong một bữa ăn gia đình ấm áp."
  },
  {
    "id": 55,
    "word": "busy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɪzi/",
    "meaning": "bận rộn",
    "ex1": "This seafood dish looks busy when served at the table.",
    "ex1_vi": "Món hải sản này trông bận rộn khi được phục vụ tại bàn."
  },
  {
    "id": 56,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌliz/",
    "meaning": "các gia đình",
    "ex1": "People enjoy families during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức các gia đình trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 57,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "Fresh seafood can taste good during a warm family meal.",
    "ex1_vi": "Hải sản tươi có thể có vị tốt trong một bữa ăn gia đình ấm áp."
  },
  {
    "id": 58,
    "word": "plate",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪt/",
    "meaning": "đĩa",
    "ex1": "Fresh seafood can include plate in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có đĩa."
  },
  {
    "id": 59,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "People discuss should during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về nên trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 60,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có",
    "ex1": "Families have fresh seafood during relaxed weekend meals.",
    "ex1_vi": "Các gia đình có hải sản tươi trong những bữa ăn cuối tuần thư giãn."
  },
  {
    "id": 61,
    "word": "separate",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɛpɝˌeɪt/",
    "meaning": "tách rời",
    "ex1": "This seafood dish looks separate when served at the table.",
    "ex1_vi": "Món hải sản này trông tách rời khi được phục vụ tại bàn."
  },
  {
    "id": 62,
    "word": "grains",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡrˈeɪnz/",
    "meaning": "hạt cơm",
    "ex1": "People enjoy grains during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức hạt cơm trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 63,
    "word": "balanced",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈælʌnst/",
    "meaning": "cân bằng",
    "ex1": "Fresh seafood can taste balanced during a warm family meal.",
    "ex1_vi": "Hải sản tươi có thể có vị cân bằng trong một bữa ăn gia đình ấm áp."
  },
  {
    "id": 64,
    "word": "flavors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝz/",
    "meaning": "hương vị",
    "ex1": "Fresh seafood can include flavors in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có hương vị."
  },
  {
    "id": 65,
    "word": "ingredients",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnɡrˈidiʌnts/",
    "meaning": "nguyên liệu",
    "ex1": "People enjoy ingredients during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức nguyên liệu trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 66,
    "word": "throughout",
    "type": "preposition/adverb",
    "cat": "adv",
    "phonetic": "/θruˈaʊt/",
    "meaning": "khắp; xuyên suốt",
    "ex1": "People use throughout naturally when talking about seafood dishes.",
    "ex1_vi": "Mọi người dùng “throughout” tự nhiên khi nói về các món hải sản."
  },
  {
    "id": 67,
    "word": "noodles",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈudʌlz/",
    "meaning": "mì",
    "ex1": "Seafood noodles are filling but not too heavy.",
    "ex1_vi": "Mì hải sản làm no nhưng không quá nặng bụng."
  },
  {
    "id": 68,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "Grilled oysters are a rich and popular seafood dish.",
    "ex1_vi": "Hàu nướng là một món hải sản đậm đà và phổ biến."
  },
  {
    "id": 69,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Seafood noodles are a popular meal in many Asian countries.",
    "ex1_vi": "Mì hải sản là một bữa ăn phổ biến ở nhiều quốc gia châu Á."
  },
  {
    "id": 70,
    "word": "asian",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈeɪʒʌn/",
    "meaning": "thuộc châu Á",
    "ex1": "People discuss asian during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về thuộc châu Á trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 71,
    "word": "countries",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌntriz/",
    "meaning": "quốc gia",
    "ex1": "People discuss countries during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về quốc gia trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 72,
    "word": "bowl",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈoʊl/",
    "meaning": "tô",
    "ex1": "They provide energy, protein, and vegetables in one bowl.",
    "ex1_vi": "Chúng cung cấp năng lượng, protein và rau trong một tô."
  },
  {
    "id": 73,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "Families usually enjoy seafood together during weekend gatherings.",
    "ex1_vi": "Các gia đình thường thưởng thức hải sản cùng nhau trong các buổi tụ họp cuối tuần."
  },
  {
    "id": 74,
    "word": "contains",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈeɪnz/",
    "meaning": "chứa",
    "ex1": "Cooks contains seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu chứa hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 75,
    "word": "fish",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɪʃ/",
    "meaning": "cá",
    "ex1": "The fish is crispy outside and soft inside.",
    "ex1_vi": "Cá giòn bên ngoài và mềm bên trong."
  },
  {
    "id": 76,
    "word": "balls",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɔlz/",
    "meaning": "viên",
    "ex1": "Fresh seafood can include balls in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có viên."
  },
  {
    "id": 77,
    "word": "flavorful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/flˈeɪvɝfʌl/",
    "meaning": "đậm vị",
    "ex1": "A well-prepared seafood meal can feel flavorful and satisfying.",
    "ex1_vi": "Một bữa hải sản được chuẩn bị tốt có thể đậm vị và làm no."
  },
  {
    "id": 78,
    "word": "broth",
    "type": "noun",
    "cat": "n",
    "phonetic": "/brˈɔθ/",
    "meaning": "nước dùng",
    "ex1": "Families talk about broth during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về nước dùng trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 79,
    "word": "soup",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈup/",
    "meaning": "nước lẩu; súp",
    "ex1": "Fresh seafood can include soup in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có nước lẩu; súp."
  },
  {
    "id": 80,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Families can prepare seafood together for weekend meals.",
    "ex1_vi": "Các gia đình có thể cùng chuẩn bị hải sản cho bữa ăn cuối tuần."
  },
  {
    "id": 81,
    "word": "clear",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈɪr/",
    "meaning": "trong",
    "ex1": "Fresh seafood can taste clear during a warm family meal.",
    "ex1_vi": "Hải sản tươi có thể có vị trong trong một bữa ăn gia đình ấm áp."
  },
  {
    "id": 82,
    "word": "spicy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/spˈaɪsi/",
    "meaning": "cay",
    "ex1": "This seafood dish looks spicy when served at the table.",
    "ex1_vi": "Món hải sản này trông cay khi được phục vụ tại bàn."
  },
  {
    "id": 83,
    "word": "sour",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈaʊɝ/",
    "meaning": "chua",
    "ex1": "People discuss sour during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về chua trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 84,
    "word": "creamy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈimi/",
    "meaning": "béo; kem mịn",
    "ex1": "The flavor is creamy, salty, sweet, and slightly smoky.",
    "ex1_vi": "Hương vị béo, mặn, ngọt và hơi ám khói."
  },
  {
    "id": 85,
    "word": "depending",
    "type": "verb/preposition",
    "cat": "v",
    "phonetic": "/dɪpˈɛndɪŋ/",
    "meaning": "tùy thuộc",
    "ex1": "Families use depending in simple sentences about seafood meals.",
    "ex1_vi": "Các gia đình dùng “depending” trong những câu đơn giản về bữa ăn hải sản."
  },
  {
    "id": 86,
    "word": "local",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈoʊkʌl/",
    "meaning": "địa phương",
    "ex1": "A well-prepared seafood meal can feel local and satisfying.",
    "ex1_vi": "Một bữa hải sản được chuẩn bị tốt có thể địa phương và làm no."
  },
  {
    "id": 87,
    "word": "cooking",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/kˈʊkɪŋ/",
    "meaning": "việc nấu",
    "ex1": "People often add cheese, butter, garlic, green onions, or peanuts before cooking.",
    "ex1_vi": "Mọi người thường thêm phô mai, bơ, tỏi, hành lá hoặc đậu phộng trước khi nướng."
  },
  {
    "id": 88,
    "word": "style",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈaɪl/",
    "meaning": "phong cách",
    "ex1": "Fresh seafood can include style in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có phong cách."
  },
  {
    "id": 89,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "People discuss people during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về mọi người trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 90,
    "word": "add",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈæd/",
    "meaning": "thêm",
    "ex1": "People discuss add during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về thêm trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 91,
    "word": "green",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈin/",
    "meaning": "xanh",
    "ex1": "People discuss green during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về xanh trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 92,
    "word": "herbs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɝbz/",
    "meaning": "rau thơm",
    "ex1": "People discuss herbs during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về rau thơm trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 93,
    "word": "lime",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪm/",
    "meaning": "chanh",
    "ex1": "People discuss lime during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về chanh trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 94,
    "word": "juice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈus/",
    "meaning": "nước cốt; nước ép",
    "ex1": "People discuss juice during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về nước cốt; nước ép trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 95,
    "word": "before",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/bɪfˈɔr/",
    "meaning": "trước",
    "ex1": "People discuss before during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về trước trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 96,
    "word": "eating",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈitɪŋ/",
    "meaning": "việc ăn",
    "ex1": "People discuss eating during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về việc ăn trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 97,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "The fish is crispy outside and soft inside.",
    "ex1_vi": "Cá giòn bên ngoài và mềm bên trong."
  },
  {
    "id": 98,
    "word": "gives",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvz/",
    "meaning": "mang lại",
    "ex1": "The sauce gives the dish a bright and attractive appearance.",
    "ex1_vi": "Nước sốt làm món ăn có vẻ ngoài sáng và hấp dẫn."
  },
  {
    "id": 99,
    "word": "flavor",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝ/",
    "meaning": "hương vị",
    "ex1": "The flavor is creamy, salty, sweet, and slightly smoky.",
    "ex1_vi": "Hương vị béo, mặn, ngọt và hơi ám khói."
  },
  {
    "id": 100,
    "word": "commonly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɑmʌnli/",
    "meaning": "thường",
    "ex1": "It is commonly eaten for breakfast, lunch, or dinner.",
    "ex1_vi": "Món này thường được ăn vào bữa sáng, trưa hoặc tối."
  },
  {
    "id": 101,
    "word": "eaten",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈitʌn/",
    "meaning": "được ăn",
    "ex1": "It is commonly eaten for breakfast, lunch, or dinner.",
    "ex1_vi": "Món này thường được ăn vào bữa sáng, trưa hoặc tối."
  },
  {
    "id": 102,
    "word": "breakfast",
    "type": "noun",
    "cat": "n",
    "phonetic": "/brˈɛkfʌst/",
    "meaning": "bữa sáng",
    "ex1": "People discuss breakfast during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về bữa sáng trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 103,
    "word": "filling",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɪlɪŋ/",
    "meaning": "no bụng",
    "ex1": "People discuss filling during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về no bụng trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 104,
    "word": "but",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bˈʌt/",
    "meaning": "nhưng",
    "ex1": "People discuss but during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về nhưng trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 105,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "People discuss not during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về không trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 106,
    "word": "too",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tˈu/",
    "meaning": "quá",
    "ex1": "People discuss too during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về quá trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 107,
    "word": "heavy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛvi/",
    "meaning": "nặng bụng",
    "ex1": "People discuss heavy during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về nặng bụng trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 108,
    "word": "provide",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌvˈaɪd/",
    "meaning": "cung cấp",
    "ex1": "People discuss provide during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về cung cấp trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 109,
    "word": "energy",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛnɝdʒi/",
    "meaning": "năng lượng",
    "ex1": "People discuss energy during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về năng lượng trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 110,
    "word": "protein",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈoʊtˌin/",
    "meaning": "protein",
    "ex1": "People discuss protein during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về protein trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 111,
    "word": "one",
    "type": "number",
    "cat": "adj",
    "phonetic": "/wˈʌn/",
    "meaning": "một",
    "ex1": "People discuss one during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về một trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 112,
    "word": "especially",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌspˈɛʃli/",
    "meaning": "đặc biệt",
    "ex1": "Families especially enjoy seafood together during weekend gatherings.",
    "ex1_vi": "Các gia đình đặc biệt thưởng thức hải sản cùng nhau trong các buổi tụ họp cuối tuần."
  },
  {
    "id": 113,
    "word": "enjoyable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɛndʒˈɔɪʌbʌl/",
    "meaning": "thú vị",
    "ex1": "A well-prepared seafood meal can feel enjoyable and satisfying.",
    "ex1_vi": "Một bữa hải sản được chuẩn bị tốt có thể thú vị và làm no."
  },
  {
    "id": 114,
    "word": "rainy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈeɪni/",
    "meaning": "có mưa",
    "ex1": "Fresh seafood can taste rainy during a warm family meal.",
    "ex1_vi": "Hải sản tươi có thể có vị có mưa trong một bữa ăn gia đình ấm áp."
  },
  {
    "id": 115,
    "word": "days",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪz/",
    "meaning": "ngày",
    "ex1": "Fresh seafood can include days in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có ngày."
  },
  {
    "id": 116,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "When prepared well, they are soft, juicy, and full of flavor.",
    "ex1_vi": "Khi được chuẩn bị tốt, chúng mềm, mọng nước và đầy hương vị."
  },
  {
    "id": 117,
    "word": "want",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɑnt/",
    "meaning": "muốn",
    "ex1": "Families want fresh seafood during relaxed weekend meals.",
    "ex1_vi": "Các gia đình muốn hải sản tươi trong những bữa ăn cuối tuần thư giãn."
  },
  {
    "id": 118,
    "word": "quick",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kwˈɪk/",
    "meaning": "nhanh",
    "ex1": "This seafood dish looks quick when served at the table.",
    "ex1_vi": "Món hải sản này trông nhanh khi được phục vụ tại bàn."
  },
  {
    "id": 119,
    "word": "comforting",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌmfɝtɪŋ/",
    "meaning": "ấm bụng; dễ chịu",
    "ex1": "Cooks comforting seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu ấm bụng; dễ chịu hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 120,
    "word": "grilled",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈɪld/",
    "meaning": "nướng",
    "ex1": "Grilled oysters are a rich and popular seafood dish.",
    "ex1_vi": "Hàu nướng là một món hải sản đậm đà và phổ biến."
  },
  {
    "id": 121,
    "word": "oysters",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔɪstɝz/",
    "meaning": "hàu",
    "ex1": "People discuss oysters during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về hàu trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 122,
    "word": "rich",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɪtʃ/",
    "meaning": "đậm đà",
    "ex1": "People discuss rich during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về đậm đà trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 123,
    "word": "opened",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈoʊpʌnd/",
    "meaning": "được mở",
    "ex1": "Fresh oysters are opened carefully and placed on a grill.",
    "ex1_vi": "Hàu tươi được mở cẩn thận và đặt lên vỉ nướng."
  },
  {
    "id": 124,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "Fresh oysters are opened carefully and placed on a grill.",
    "ex1_vi": "Hàu tươi được mở cẩn thận và đặt lên vỉ nướng."
  },
  {
    "id": 125,
    "word": "placed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪst/",
    "meaning": "được đặt",
    "ex1": "People discuss placed during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về được đặt trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 126,
    "word": "grill",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡrˈɪl/",
    "meaning": "vỉ nướng",
    "ex1": "People discuss grill during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về vỉ nướng trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 127,
    "word": "cheese",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈiz/",
    "meaning": "phô mai",
    "ex1": "People often add cheese, butter, garlic, green onions, or peanuts before cooking.",
    "ex1_vi": "Mọi người thường thêm phô mai, bơ, tỏi, hành lá hoặc đậu phộng trước khi nướng."
  },
  {
    "id": 128,
    "word": "butter",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʌtɝ/",
    "meaning": "bơ",
    "ex1": "People discuss butter during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về bơ trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 129,
    "word": "garlic",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɑrlɪk/",
    "meaning": "tỏi",
    "ex1": "People discuss garlic during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về tỏi trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 130,
    "word": "peanuts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈinʌts/",
    "meaning": "đậu phộng",
    "ex1": "People discuss peanuts during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về đậu phộng trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 131,
    "word": "ready",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛdi/",
    "meaning": "sẵn sàng",
    "ex1": "A well-prepared seafood meal can feel ready and satisfying.",
    "ex1_vi": "Một bữa hải sản được chuẩn bị tốt có thể sẵn sàng và làm no."
  },
  {
    "id": 132,
    "word": "topping",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɑpɪŋ/",
    "meaning": "phần phủ",
    "ex1": "Families talk about topping during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về phần phủ trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 133,
    "word": "melts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛlts/",
    "meaning": "tan chảy",
    "ex1": "Fresh seafood can include melts in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có tan chảy."
  },
  {
    "id": 134,
    "word": "meat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈit/",
    "meaning": "thịt",
    "ex1": "People enjoy meat during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức thịt trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 135,
    "word": "salty",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɔlti/",
    "meaning": "mặn",
    "ex1": "People discuss salty during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về mặn trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 136,
    "word": "slightly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/slˈaɪtli/",
    "meaning": "hơi",
    "ex1": "People discuss slightly during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về hơi trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 137,
    "word": "smoky",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈoʊki/",
    "meaning": "ám khói",
    "ex1": "People discuss smoky during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về ám khói trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 138,
    "word": "directly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/dɝˈɛktli/",
    "meaning": "trực tiếp",
    "ex1": "People directly prepare seafood for family meals at home.",
    "ex1_vi": "Mọi người trực tiếp chuẩn bị hải sản cho các bữa ăn gia đình ở nhà."
  },
  {
    "id": 139,
    "word": "shells",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɛlz/",
    "meaning": "vỏ",
    "ex1": "Fresh seafood can include shells in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có vỏ."
  },
  {
    "id": 140,
    "word": "spoon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈun/",
    "meaning": "thìa",
    "ex1": "People enjoy spoon during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức thìa trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 141,
    "word": "common",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɑmʌn/",
    "meaning": "phổ biến",
    "ex1": "They are common at seafood restaurants, street stalls, and outdoor parties.",
    "ex1_vi": "Món này phổ biến ở nhà hàng hải sản, quầy hàng đường phố và tiệc ngoài trời."
  },
  {
    "id": 142,
    "word": "restaurants",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɛstɝˌɑnts/",
    "meaning": "nhà hàng",
    "ex1": "They are common at seafood restaurants, street stalls, and outdoor parties.",
    "ex1_vi": "Món này phổ biến ở nhà hàng hải sản, quầy hàng đường phố và tiệc ngoài trời."
  },
  {
    "id": 143,
    "word": "street",
    "type": "noun",
    "cat": "n",
    "phonetic": "/strˈit/",
    "meaning": "đường phố",
    "ex1": "People discuss street during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về đường phố trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 144,
    "word": "stalls",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈɔlz/",
    "meaning": "quầy hàng",
    "ex1": "People discuss stalls during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về quầy hàng trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 145,
    "word": "outdoor",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈaʊtdˌɔr/",
    "meaning": "ngoài trời",
    "ex1": "People discuss outdoor during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về ngoài trời trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 146,
    "word": "parties",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrtiz/",
    "meaning": "bữa tiệc",
    "ex1": "People discuss parties during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về bữa tiệc trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 147,
    "word": "properly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/prˈɑpɝli/",
    "meaning": "đúng cách",
    "ex1": "People discuss properly during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về đúng cách trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 148,
    "word": "safety",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈeɪfti/",
    "meaning": "an toàn",
    "ex1": "People discuss safety during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về an toàn trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 149,
    "word": "prepared",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pripˈɛrd/",
    "meaning": "được chuẩn bị",
    "ex1": "When prepared well, they are soft, juicy, and full of flavor.",
    "ex1_vi": "Khi được chuẩn bị tốt, chúng mềm, mọng nước và đầy hương vị."
  },
  {
    "id": 150,
    "word": "well",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈɛl/",
    "meaning": "tốt",
    "ex1": "People discuss well during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về tốt trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 151,
    "word": "juicy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈusi/",
    "meaning": "mọng nước",
    "ex1": "People discuss juicy during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về mọng nước trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 152,
    "word": "full",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈʊl/",
    "meaning": "đầy",
    "ex1": "People discuss full during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về đầy trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 153,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thưởng thức",
    "ex1": "Families enjoy fresh seafood during relaxed weekend meals.",
    "ex1_vi": "Các gia đình thưởng thức hải sản tươi trong những bữa ăn cuối tuần thư giãn."
  },
  {
    "id": 154,
    "word": "trying",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/trˈaɪɪŋ/",
    "meaning": "việc thử",
    "ex1": "Fresh seafood can include trying in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có việc thử."
  },
  {
    "id": 155,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "A well-prepared seafood meal can feel different and satisfying.",
    "ex1_vi": "Một bữa hải sản được chuẩn bị tốt có thể khác nhau và làm no."
  },
  {
    "id": 156,
    "word": "toppings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɑpɪŋz/",
    "meaning": "các phần phủ",
    "ex1": "Families talk about toppings during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về các phần phủ trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 157,
    "word": "sharing",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/ʃˈɛrɪŋ/",
    "meaning": "việc chia sẻ",
    "ex1": "Fresh seafood can include sharing in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có việc chia sẻ."
  },
  {
    "id": 158,
    "word": "several",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈɛvrʌl/",
    "meaning": "một số",
    "ex1": "Several families enjoy fresh seafood during weekend gatherings.",
    "ex1_vi": "Một số gia đình thích hải sản tươi trong các buổi tụ họp cuối tuần."
  },
  {
    "id": 159,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌɡˈɛðɝ/",
    "meaning": "cùng nhau",
    "ex1": "People together prepare seafood for family meals at home.",
    "ex1_vi": "Mọi người cùng nhau chuẩn bị hải sản cho các bữa ăn gia đình ở nhà."
  },
  {
    "id": 160,
    "word": "friends",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈɛndz/",
    "meaning": "bạn bè",
    "ex1": "Fresh seafood can include friends in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có bạn bè."
  },
  {
    "id": 161,
    "word": "golden",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈoʊldʌn/",
    "meaning": "vàng",
    "ex1": "A well-prepared seafood meal can feel golden and satisfying.",
    "ex1_vi": "Một bữa hải sản được chuẩn bị tốt có thể vàng và làm no."
  },
  {
    "id": 162,
    "word": "then",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ðˈɛn/",
    "meaning": "sau đó",
    "ex1": "People then prepare seafood for family meals at home.",
    "ex1_vi": "Mọi người sau đó chuẩn bị hải sản cho các bữa ăn gia đình ở nhà."
  },
  {
    "id": 163,
    "word": "covered",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌvɝd/",
    "meaning": "được phủ",
    "ex1": "People can covered seafood carefully for a family dinner.",
    "ex1_vi": "Mọi người có thể được phủ hải sản cẩn thận cho một bữa tối gia đình."
  },
  {
    "id": 164,
    "word": "made",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪd/",
    "meaning": "được làm",
    "ex1": "Cooks made seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu được làm hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 165,
    "word": "tomatoes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʌmˈeɪtoʊz/",
    "meaning": "cà chua",
    "ex1": "Families talk about tomatoes during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về cà chua trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 166,
    "word": "pineapple",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈaɪnˌæpʌl/",
    "meaning": "dứa",
    "ex1": "Fresh seafood can include pineapple in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có dứa."
  },
  {
    "id": 167,
    "word": "sugar",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈʊɡɝ/",
    "meaning": "đường",
    "ex1": "People enjoy sugar during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức đường trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 168,
    "word": "vinegar",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪnʌɡɝ/",
    "meaning": "giấm",
    "ex1": "Families talk about vinegar during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về giấm trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 169,
    "word": "bright",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/brˈaɪt/",
    "meaning": "sáng",
    "ex1": "People discuss bright during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về sáng trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 170,
    "word": "appearance",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌpˈɪrʌns/",
    "meaning": "vẻ ngoài",
    "ex1": "People discuss appearance during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về vẻ ngoài trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 171,
    "word": "crispy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈɪspi/",
    "meaning": "giòn",
    "ex1": "People discuss crispy during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về giòn trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 172,
    "word": "outside",
    "type": "adverb/noun",
    "cat": "adv",
    "phonetic": "/ˈaʊtsˈaɪd/",
    "meaning": "bên ngoài",
    "ex1": "People discuss outside during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về bên ngoài trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 173,
    "word": "inside",
    "type": "adverb/preposition",
    "cat": "adv",
    "phonetic": "/ˌɪnsˈaɪd/",
    "meaning": "bên trong",
    "ex1": "People discuss inside during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về bên trong trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 174,
    "word": "tastes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪsts/",
    "meaning": "có vị",
    "ex1": "People discuss tastes during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về có vị trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 175,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "People can eat seafood carefully for a family dinner.",
    "ex1_vi": "Mọi người có thể ăn hải sản cẩn thận cho một bữa tối gia đình."
  },
  {
    "id": 176,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "People enjoy family during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức gia đình trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 177,
    "word": "meals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈilz/",
    "meaning": "bữa ăn",
    "ex1": "Families talk about meals during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về bữa ăn trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 178,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "Seafood is popular because it has many delicious flavors.",
    "ex1_vi": "Hải sản phổ biến vì có nhiều hương vị ngon."
  },
  {
    "id": 179,
    "word": "combines",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌmbˈaɪnz/",
    "meaning": "kết hợp",
    "ex1": "Cooks combines seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu kết hợp hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 180,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋ/",
    "meaning": "đậm; mạnh",
    "ex1": "Fresh seafood can taste strong during a warm family meal.",
    "ex1_vi": "Hải sản tươi có thể có vị đậm; mạnh trong một bữa ăn gia đình ấm áp."
  },
  {
    "id": 181,
    "word": "children",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪldrʌn/",
    "meaning": "trẻ em",
    "ex1": "Fresh seafood can include children in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có trẻ em."
  },
  {
    "id": 182,
    "word": "adults",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌdˈʌlts/",
    "meaning": "người lớn",
    "ex1": "People enjoy adults during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức người lớn trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 183,
    "word": "keep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈip/",
    "meaning": "giữ; duy trì",
    "ex1": "Families keep fresh seafood during relaxed weekend meals.",
    "ex1_vi": "Các gia đình giữ; duy trì hải sản tươi trong những bữa ăn cuối tuần thư giãn."
  },
  {
    "id": 184,
    "word": "tender",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈɛndɝ/",
    "meaning": "mềm",
    "ex1": "This seafood dish looks tender when served at the table.",
    "ex1_vi": "Món hải sản này trông mềm khi được phục vụ tại bàn."
  }
];

const newReadingVocabOrder = [
  "seafood",
  "fried",
  "rice",
  "colorful",
  "and",
  "satisfying",
  "dish",
  "cooked",
  "shrimp",
  "squid",
  "eggs",
  "carrots",
  "peas",
  "onions",
  "simple",
  "seasonings",
  "cook",
  "mixes",
  "everything",
  "hot",
  "pan",
  "until",
  "becomes",
  "dry",
  "fragrant",
  "evenly",
  "heated",
  "often",
  "served",
  "cucumber",
  "tomato",
  "chili",
  "sauce",
  "or",
  "soy",
  "adds",
  "sweet",
  "taste",
  "while",
  "vegetables",
  "make",
  "meal",
  "fresh",
  "attractive",
  "suitable",
  "lunch",
  "dinner",
  "easy",
  "prepare",
  "leftover",
  "small",
  "amounts",
  "also",
  "convenient",
  "busy",
  "families",
  "good",
  "plate",
  "should",
  "have",
  "separate",
  "grains",
  "balanced",
  "flavors",
  "ingredients",
  "throughout",
  "noodles",
  "popular",
  "many",
  "asian",
  "countries",
  "bowl",
  "usually",
  "contains",
  "fish",
  "balls",
  "flavorful",
  "broth",
  "soup",
  "can",
  "clear",
  "spicy",
  "sour",
  "creamy",
  "depending",
  "local",
  "cooking",
  "style",
  "people",
  "add",
  "green",
  "herbs",
  "lime",
  "juice",
  "before",
  "eating",
  "soft",
  "gives",
  "flavor",
  "commonly",
  "eaten",
  "breakfast",
  "filling",
  "but",
  "not",
  "too",
  "heavy",
  "provide",
  "energy",
  "protein",
  "one",
  "especially",
  "enjoyable",
  "rainy",
  "days",
  "when",
  "want",
  "quick",
  "comforting",
  "grilled",
  "oysters",
  "rich",
  "opened",
  "carefully",
  "placed",
  "grill",
  "cheese",
  "butter",
  "garlic",
  "peanuts",
  "ready",
  "topping",
  "melts",
  "meat",
  "salty",
  "slightly",
  "smoky",
  "directly",
  "shells",
  "spoon",
  "common",
  "restaurants",
  "street",
  "stalls",
  "outdoor",
  "parties",
  "properly",
  "safety",
  "prepared",
  "well",
  "juicy",
  "full",
  "enjoy",
  "trying",
  "different",
  "toppings",
  "sharing",
  "several",
  "together",
  "friends",
  "golden",
  "then",
  "covered",
  "made",
  "tomatoes",
  "pineapple",
  "sugar",
  "vinegar",
  "bright",
  "appearance",
  "crispy",
  "outside",
  "inside",
  "tastes",
  "eat",
  "family",
  "meals",
  "because",
  "combines",
  "strong",
  "children",
  "adults",
  "keep",
  "tender"
];
