const newEssayData = [
  {
    "text": "Chapter 7. Seafood Fried Rice – Cơm Chiên Hải Sản\nSeafood fried rice is a colorful and satisfying dish. Cooked rice is fried with shrimp, squid, eggs, carrots, peas, onions, and simple seasonings. The cook mixes everything in a hot pan until the rice becomes dry, fragrant, and evenly heated.\n\nThis dish is often served with cucumber, tomato, chili sauce, or soy sauce. The seafood adds a sweet taste, while the vegetables make the meal fresh and attractive. It is suitable for lunch or dinner.\n\nSeafood fried rice is easy to prepare with leftover rice and small amounts of seafood. It is also convenient for busy families. A good plate should have separate grains, balanced flavors, and fresh ingredients throughout.",
    "vi": "Chương 7. Cơm chiên hải sản\nCơm chiên hải sản là một món ăn nhiều màu sắc và no bụng. Cơm chín được chiên với tôm, mực, trứng, cà rốt, đậu Hà Lan, hành và gia vị đơn giản. Người nấu trộn mọi thứ trong chảo nóng cho đến khi cơm trở nên khô, thơm và nóng đều.\n\nMón này thường được phục vụ với dưa leo, cà chua, tương ớt hoặc nước tương. Hải sản thêm vị ngọt, trong khi rau làm bữa ăn tươi và hấp dẫn. Món này phù hợp cho bữa trưa hoặc bữa tối.\n\nCơm chiên hải sản dễ chuẩn bị với cơm thừa và lượng nhỏ hải sản. Món này cũng tiện lợi cho các gia đình bận rộn. Một đĩa ngon nên có hạt cơm rời, hương vị cân bằng và nguyên liệu tươi đều khắp."
  },
  {
    "text": "Chapter 8. Seafood Noodles – Mì Hải Sản\nSeafood noodles are a popular meal in many Asian countries. A bowl usually contains noodles, shrimp, squid, fish balls, vegetables, and a flavorful broth. The soup can be clear, spicy, sour, or creamy, depending on the local cooking style.\n\nPeople often add green onions, herbs, lime juice, and chili before eating. The noodles are soft, while the seafood gives the dish a fresh and sweet flavor. It is commonly eaten for breakfast, lunch, or dinner.\n\nSeafood noodles are filling but not too heavy. They provide energy, protein, and vegetables in one bowl. A hot bowl is especially enjoyable on rainy days or when people want a quick and comforting meal.",
    "vi": "Chương 8. Mì hải sản\nMì hải sản là một bữa ăn phổ biến ở nhiều quốc gia châu Á. Một tô thường có mì, tôm, mực, chả cá, rau và nước dùng đậm vị. Nước dùng có thể trong, cay, chua hoặc béo, tùy theo phong cách nấu địa phương.\n\nMọi người thường thêm hành lá, rau thơm, nước cốt chanh và ớt trước khi ăn. Sợi mì mềm, trong khi hải sản mang lại vị tươi và ngọt cho món ăn. Món này thường được ăn vào bữa sáng, trưa hoặc tối.\n\nMì hải sản làm no nhưng không quá nặng bụng. Chúng cung cấp năng lượng, protein và rau trong một tô. Một tô nóng đặc biệt dễ chịu vào những ngày mưa hoặc khi mọi người muốn một bữa ăn nhanh và ấm bụng."
  },
  {
    "text": "Chapter 9. Grilled Oysters – Hàu Nướng\nGrilled oysters are a rich and popular seafood dish. Fresh oysters are opened carefully and placed on a grill. People often add cheese, butter, garlic, green onions, or peanuts before cooking. The oysters are ready when the topping melts and the meat becomes hot.\n\nThe flavor is creamy, salty, sweet, and slightly smoky. Grilled oysters are usually eaten directly from the shells with a small spoon. They are common at seafood restaurants, street stalls, and outdoor parties.\n\nOysters should be fresh and cooked properly for safety. When prepared well, they are soft, juicy, and full of flavor. Many people enjoy trying different toppings and sharing several oysters together with friends.",
    "vi": "Chương 9. Hàu nướng\nHàu nướng là một món hải sản đậm đà và phổ biến. Hàu tươi được mở cẩn thận và đặt lên vỉ nướng. Mọi người thường thêm phô mai, bơ, tỏi, hành lá hoặc đậu phộng trước khi nướng. Hàu chín khi phần phủ tan chảy và thịt trở nên nóng.\n\nHương vị béo, mặn, ngọt và hơi ám khói. Hàu nướng thường được ăn trực tiếp từ vỏ bằng thìa nhỏ. Món này phổ biến ở nhà hàng hải sản, quầy hàng đường phố và tiệc ngoài trời.\n\nHàu nên tươi và được nấu đúng cách để bảo đảm an toàn. Khi được chuẩn bị tốt, chúng mềm, mọng nước và đầy hương vị. Nhiều người thích thử các loại phần phủ khác nhau và cùng bạn bè chia sẻ nhiều con hàu."
  },
  {
    "text": "Chapter 10. Sweet and Sour Fish – Cá Sốt Chua Ngọt\nSweet and sour fish is a colorful seafood dish with a balanced flavor. Fresh fish is fried until golden, then covered with a sauce made from tomatoes, pineapple, onions, sugar, vinegar, and fish sauce. The sauce gives the dish a bright and attractive appearance.\n\nThe fish is crispy outside and soft inside. The sauce tastes sweet, sour, and slightly salty. People often eat this dish with hot rice, vegetables, or soup during family meals.\n\nSweet and sour fish is popular because it combines simple ingredients with a strong flavor. It is suitable for children and adults. A well cooked dish should keep the fish tender, and evenly covered with sauce.",
    "vi": "Chương 10. Cá sốt chua ngọt\nCá sốt chua ngọt là một món hải sản nhiều màu sắc với hương vị cân bằng. Cá tươi được chiên đến khi vàng, sau đó phủ nước sốt làm từ cà chua, dứa, hành, đường, giấm và nước mắm. Nước sốt làm món ăn có vẻ ngoài sáng và hấp dẫn.\n\nCá giòn bên ngoài và mềm bên trong. Nước sốt có vị ngọt, chua và hơi mặn. Mọi người thường ăn món này với cơm nóng, rau hoặc canh trong các bữa ăn gia đình.\n\nCá sốt chua ngọt phổ biến vì kết hợp nguyên liệu đơn giản với hương vị đậm. Món này phù hợp cho trẻ em và người lớn. Một món nấu ngon nên giữ cá mềm và được phủ đều nước sốt."
  }
];
