const newEssayData = [
  {
    "text": "Chapter 1. Grilled Shrimp – Tôm Nướng\nGrilled shrimp is a popular seafood dish in many coastal areas. Fresh shrimp are cleaned, seasoned with salt, pepper, garlic, and a little oil, then cooked over hot charcoal. The smell becomes very attractive while the shrimp slowly turn orange.\n\nPeople often eat grilled shrimp with vegetables, rice paper, or a simple dipping sauce. The shrimp taste sweet, juicy, and slightly smoky. This dish is common at family meals, seafood restaurants, and weekend parties.\n\nGrilled shrimp are easy to prepare and do not need many ingredients. They provide protein and important nutrients. Eating them while they are hot makes the meal more delicious and enjoyable for everyone at the table.",
    "vi": "Chương 1. Tôm nướng\nTôm nướng là một món hải sản phổ biến ở nhiều khu vực ven biển. Tôm tươi được làm sạch, nêm muối, tiêu, tỏi và một ít dầu, sau đó nướng trên than nóng. Mùi thơm trở nên rất hấp dẫn trong khi tôm từ từ chuyển sang màu cam.\n\nMọi người thường ăn tôm nướng với rau, bánh tráng hoặc một loại nước chấm đơn giản. Tôm có vị ngọt, mọng nước và hơi ám khói. Món này phổ biến trong các bữa ăn gia đình, nhà hàng hải sản và tiệc cuối tuần.\n\nTôm nướng dễ chuẩn bị và không cần nhiều nguyên liệu. Chúng cung cấp protein và các chất dinh dưỡng quan trọng. Ăn khi tôm còn nóng làm bữa ăn ngon và thú vị hơn cho mọi người tại bàn."
  },
  {
    "text": "Chapter 2. Steamed Crab – Cua Hấp\nSteamed crab is a simple and delicious seafood dish. Fresh crabs are washed carefully and placed in a steamer with lemongrass, ginger, or beer. After cooking, the crab shells become bright orange, and the meat inside stays sweet, soft, and juicy.\n\nPeople usually break the shells and eat the crab meat with salt, pepper, and lime juice. Some families also prepare a spicy seafood sauce. Steamed crab is often served at parties, family gatherings, and restaurants near the sea.\n\nThis cooking method keeps the natural flavor of the crab. It also uses little oil, so the dish feels light and healthy. Many seafood lovers enjoy steamed crab during special occasions.",
    "vi": "Chương 2. Cua hấp\nCua hấp là một món hải sản đơn giản và ngon. Cua tươi được rửa cẩn thận và đặt vào nồi hấp cùng sả, gừng hoặc bia. Sau khi nấu, vỏ cua chuyển màu cam sáng, còn thịt bên trong vẫn ngọt, mềm và mọng nước.\n\nMọi người thường bẻ vỏ và ăn thịt cua với muối, tiêu và nước cốt chanh. Một số gia đình cũng chuẩn bị nước chấm hải sản cay. Cua hấp thường được phục vụ tại các bữa tiệc, buổi tụ họp gia đình và nhà hàng gần biển.\n\nPhương pháp nấu này giữ hương vị tự nhiên của cua. Nó cũng dùng ít dầu nên món ăn có cảm giác nhẹ và lành mạnh. Nhiều người yêu hải sản thích cua hấp trong những dịp đặc biệt."
  },
  {
    "text": "Chapter 3. Fried Squid – Mực Chiên\nFried squid is a tasty seafood dish enjoyed by many people. Fresh squid are cleaned, cut into rings, and covered with flour, egg, or breadcrumbs. They are then fried in hot oil until the outside becomes golden and crispy.\n\nFried squid is often served with chili sauce, mayonnaise, or fresh vegetables. The outside is crunchy, while the inside remains soft and slightly sweet. Children and adults usually enjoy this dish because it is easy to eat.\n\nAlthough fried squid is delicious, people should not eat too much because it contains oil. It is best served hot as a snack, an appetizer, or part of a family meal with close friends.",
    "vi": "Chương 3. Mực chiên\nMực chiên là một món hải sản ngon được nhiều người yêu thích. Mực tươi được làm sạch, cắt thành khoanh và phủ bột, trứng hoặc vụn bánh mì. Sau đó mực được chiên trong dầu nóng cho đến khi bên ngoài vàng và giòn.\n\nMực chiên thường được phục vụ với tương ớt, sốt mayonnaise hoặc rau tươi. Bên ngoài giòn, trong khi bên trong vẫn mềm và hơi ngọt. Trẻ em và người lớn thường thích món này vì dễ ăn.\n\nMặc dù mực chiên ngon, mọi người không nên ăn quá nhiều vì món này chứa dầu. Tốt nhất nên dùng nóng như món ăn vặt, món khai vị hoặc một phần của bữa ăn gia đình với bạn bè thân thiết."
  }
];
