const lessonVocabularyWords = [
  "grilled",
  "shrimp",
  "popular",
  "seafood",
  "dish",
  "many",
  "coastal",
  "areas",
  "fresh",
  "cleaned",
  "seasoned",
  "salt",
  "pepper",
  "garlic",
  "and",
  "little",
  "oil",
  "then",
  "cooked",
  "hot",
  "charcoal",
  "smell",
  "becomes",
  "very",
  "attractive",
  "while",
  "slowly",
  "turn",
  "orange",
  "people",
  "often",
  "eat",
  "vegetables",
  "rice",
  "paper",
  "or",
  "simple",
  "dipping",
  "sauce",
  "taste",
  "sweet",
  "juicy",
  "slightly",
  "smoky",
  "common",
  "family",
  "meals",
  "restaurants",
  "weekend",
  "parties",
  "easy",
  "prepare",
  "do",
  "not",
  "need",
  "ingredients",
  "provide",
  "protein",
  "important",
  "nutrients",
  "eating",
  "makes",
  "meal",
  "more",
  "delicious",
  "enjoyable",
  "everyone",
  "table",
  "steamed",
  "crab",
  "crabs",
  "washed",
  "carefully",
  "placed",
  "steamer",
  "lemongrass",
  "ginger",
  "beer",
  "after",
  "cooking",
  "shells",
  "become",
  "bright",
  "meat",
  "inside",
  "stays",
  "soft",
  "usually",
  "break",
  "lime",
  "juice",
  "some",
  "families",
  "also",
  "spicy",
  "served",
  "gatherings",
  "sea",
  "method",
  "keeps",
  "natural",
  "flavor",
  "uses",
  "so",
  "feels",
  "light",
  "healthy",
  "lovers",
  "enjoy",
  "special",
  "occasions",
  "fried",
  "squid",
  "tasty",
  "enjoyed",
  "cut",
  "rings",
  "covered",
  "flour",
  "egg",
  "breadcrumbs",
  "until",
  "outside",
  "golden",
  "crispy",
  "chili",
  "mayonnaise",
  "crunchy",
  "remains",
  "children",
  "adults",
  "because",
  "although",
  "should",
  "too",
  "much",
  "contains",
  "best",
  "snack",
  "appetizer",
  "part",
  "close",
  "friends"
];

const newVocabData = [
  {
    "id": 1,
    "word": "grilled",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈɪld/",
    "meaning": "nướng",
    "ex1": "Grilled shrimp is a popular seafood dish in many coastal areas.",
    "ex1_vi": "Tôm nướng là một món hải sản phổ biến ở nhiều khu vực ven biển."
  },
  {
    "id": 2,
    "word": "shrimp",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃrˈɪmp/",
    "meaning": "tôm",
    "ex1": "The shrimp taste sweet, juicy, and slightly smoky.",
    "ex1_vi": "Tôm có vị ngọt, mọng nước và hơi ám khói."
  },
  {
    "id": 3,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "Grilled shrimp is a popular seafood dish in many coastal areas.",
    "ex1_vi": "Tôm nướng là một món hải sản phổ biến ở nhiều khu vực ven biển."
  },
  {
    "id": 4,
    "word": "seafood",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsiːfuːd/",
    "meaning": "hải sản",
    "ex1": "Some families also prepare a spicy seafood sauce.",
    "ex1_vi": "Một số gia đình cũng chuẩn bị nước chấm hải sản cay."
  },
  {
    "id": 5,
    "word": "dish",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪʃ/",
    "meaning": "món ăn",
    "ex1": "Steamed crab is a simple and delicious seafood dish.",
    "ex1_vi": "Cua hấp là một món hải sản đơn giản và ngon."
  },
  {
    "id": 6,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Many seafood lovers enjoy steamed crab during special occasions.",
    "ex1_vi": "Nhiều người yêu hải sản thích cua hấp trong những dịp đặc biệt."
  },
  {
    "id": 7,
    "word": "coastal",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈoʊstʌl/",
    "meaning": "ven biển",
    "ex1": "People discuss coastal during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về ven biển trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 8,
    "word": "areas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛriʌz/",
    "meaning": "khu vực",
    "ex1": "People discuss areas during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về khu vực trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 9,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi",
    "ex1": "Fried squid is often served with chili sauce, mayonnaise, or fresh vegetables.",
    "ex1_vi": "Mực chiên thường được phục vụ với tương ớt, sốt mayonnaise hoặc rau tươi."
  },
  {
    "id": 10,
    "word": "cleaned",
    "type": "verb",
    "cat": "v",
    "phonetic": "/klˈind/",
    "meaning": "được làm sạch",
    "ex1": "People can cleaned seafood carefully for a family dinner.",
    "ex1_vi": "Mọi người có thể được làm sạch hải sản cẩn thận cho một bữa tối gia đình."
  },
  {
    "id": 11,
    "word": "seasoned",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈizʌnd/",
    "meaning": "được nêm gia vị",
    "ex1": "Cooks seasoned seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu được nêm gia vị hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 12,
    "word": "salt",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔlt/",
    "meaning": "muối",
    "ex1": "Families talk about salt during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về muối trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 13,
    "word": "pepper",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɛpɝ/",
    "meaning": "tiêu",
    "ex1": "Fresh seafood can include pepper in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có tiêu."
  },
  {
    "id": 14,
    "word": "garlic",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɑrlɪk/",
    "meaning": "tỏi",
    "ex1": "People enjoy garlic during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức tỏi trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 15,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "People eat seafood and vegetables together during family meals.",
    "ex1_vi": "Mọi người ăn hải sản và rau cùng nhau trong các bữa ăn gia đình."
  },
  {
    "id": 16,
    "word": "little",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/lˈɪtʌl/",
    "meaning": "một ít",
    "ex1": "It also uses little oil, so the dish feels light and healthy.",
    "ex1_vi": "Nó cũng dùng ít dầu nên món ăn có cảm giác nhẹ và lành mạnh."
  },
  {
    "id": 17,
    "word": "oil",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔɪl/",
    "meaning": "dầu",
    "ex1": "It also uses little oil, so the dish feels light and healthy.",
    "ex1_vi": "Nó cũng dùng ít dầu nên món ăn có cảm giác nhẹ và lành mạnh."
  },
  {
    "id": 18,
    "word": "then",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ðˈɛn/",
    "meaning": "sau đó",
    "ex1": "People then prepare seafood for family meals at home.",
    "ex1_vi": "Mọi người sau đó chuẩn bị hải sản cho các bữa ăn gia đình ở nhà."
  },
  {
    "id": 19,
    "word": "cooked",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʊkt/",
    "meaning": "được nấu",
    "ex1": "This seafood dish looks cooked when served at the table.",
    "ex1_vi": "Món hải sản này trông được nấu khi được phục vụ tại bàn."
  },
  {
    "id": 20,
    "word": "hot",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑt/",
    "meaning": "nóng",
    "ex1": "A well-prepared seafood meal can feel hot and satisfying.",
    "ex1_vi": "Một bữa hải sản được chuẩn bị tốt có thể nóng và làm no."
  },
  {
    "id": 21,
    "word": "charcoal",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɑrkˌoʊl/",
    "meaning": "than",
    "ex1": "Families talk about charcoal during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về than trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 22,
    "word": "smell",
    "type": "verb",
    "cat": "v",
    "phonetic": "/smˈɛl/",
    "meaning": "mùi",
    "ex1": "The smell becomes very attractive while the shrimp slowly turn orange.",
    "ex1_vi": "Mùi thơm trở nên rất hấp dẫn trong khi tôm từ từ chuyển sang màu cam."
  },
  {
    "id": 23,
    "word": "becomes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌmz/",
    "meaning": "trở nên",
    "ex1": "The smell becomes very attractive while the shrimp slowly turn orange.",
    "ex1_vi": "Mùi thơm trở nên rất hấp dẫn trong khi tôm từ từ chuyển sang màu cam."
  },
  {
    "id": 24,
    "word": "very",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/vˈɛri/",
    "meaning": "rất",
    "ex1": "People discuss very during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về rất trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 25,
    "word": "attractive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌtrˈæktɪv/",
    "meaning": "hấp dẫn",
    "ex1": "People discuss attractive during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về hấp dẫn trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 26,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "People discuss while during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về trong khi trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 27,
    "word": "slowly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/slˈoʊli/",
    "meaning": "từ từ",
    "ex1": "People discuss slowly during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về từ từ trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 28,
    "word": "turn",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɝn/",
    "meaning": "chuyển sang",
    "ex1": "People discuss turn during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về chuyển sang trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 29,
    "word": "orange",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔrʌndʒ/",
    "meaning": "màu cam",
    "ex1": "People discuss orange during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về màu cam trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 30,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "Fried squid is a tasty seafood dish enjoyed by many people.",
    "ex1_vi": "Mực chiên là một món hải sản ngon được nhiều người yêu thích."
  },
  {
    "id": 31,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "Fried squid is often served with chili sauce, mayonnaise, or fresh vegetables.",
    "ex1_vi": "Mực chiên thường được phục vụ với tương ớt, sốt mayonnaise hoặc rau tươi."
  },
  {
    "id": 32,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "Cooks eat seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu ăn hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 33,
    "word": "vegetables",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɛdʒtʌbʌlz/",
    "meaning": "rau",
    "ex1": "People discuss vegetables during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về rau trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 34,
    "word": "rice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪs/",
    "meaning": "cơm; gạo",
    "ex1": "Fresh seafood can include rice in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có cơm; gạo."
  },
  {
    "id": 35,
    "word": "paper",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈeɪpɝ/",
    "meaning": "bánh tráng; giấy",
    "ex1": "People enjoy paper during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức bánh tráng; giấy trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 36,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "People discuss or during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về hoặc trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 37,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "Steamed crab is a simple and delicious seafood dish.",
    "ex1_vi": "Cua hấp là một món hải sản đơn giản và ngon."
  },
  {
    "id": 38,
    "word": "dipping",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈɪpɪŋ/",
    "meaning": "chấm",
    "ex1": "Cooks dipping seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu chấm hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 39,
    "word": "sauce",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔs/",
    "meaning": "nước sốt; nước chấm",
    "ex1": "Some families also prepare a spicy seafood sauce.",
    "ex1_vi": "Một số gia đình cũng chuẩn bị nước chấm hải sản cay."
  },
  {
    "id": 40,
    "word": "taste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪst/",
    "meaning": "có vị",
    "ex1": "The shrimp taste sweet, juicy, and slightly smoky.",
    "ex1_vi": "Tôm có vị ngọt, mọng nước và hơi ám khói."
  },
  {
    "id": 41,
    "word": "sweet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/swˈit/",
    "meaning": "ngọt",
    "ex1": "People discuss sweet during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về ngọt trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 42,
    "word": "juicy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈusi/",
    "meaning": "mọng nước",
    "ex1": "People discuss juicy during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về mọng nước trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 43,
    "word": "slightly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/slˈaɪtli/",
    "meaning": "hơi",
    "ex1": "People discuss slightly during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về hơi trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 44,
    "word": "smoky",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈoʊki/",
    "meaning": "ám khói",
    "ex1": "People discuss smoky during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về ám khói trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 45,
    "word": "common",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɑmʌn/",
    "meaning": "phổ biến",
    "ex1": "This dish is common at family meals, seafood restaurants, and weekend parties.",
    "ex1_vi": "Món này phổ biến trong các bữa ăn gia đình, nhà hàng hải sản và tiệc cuối tuần."
  },
  {
    "id": 46,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "This dish is common at family meals, seafood restaurants, and weekend parties.",
    "ex1_vi": "Món này phổ biến trong các bữa ăn gia đình, nhà hàng hải sản và tiệc cuối tuần."
  },
  {
    "id": 47,
    "word": "meals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈilz/",
    "meaning": "bữa ăn",
    "ex1": "People discuss meals during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về bữa ăn trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 48,
    "word": "restaurants",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɛstɝˌɑnts/",
    "meaning": "nhà hàng",
    "ex1": "People discuss restaurants during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về nhà hàng trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 49,
    "word": "weekend",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈikˌɛnd/",
    "meaning": "cuối tuần",
    "ex1": "People discuss weekend during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về cuối tuần trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 50,
    "word": "parties",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrtiz/",
    "meaning": "bữa tiệc",
    "ex1": "People discuss parties during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về bữa tiệc trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 51,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "Grilled shrimp are easy to prepare and do not need many ingredients.",
    "ex1_vi": "Tôm nướng dễ chuẩn bị và không cần nhiều nguyên liệu."
  },
  {
    "id": 52,
    "word": "prepare",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pripˈɛr/",
    "meaning": "chuẩn bị",
    "ex1": "People discuss prepare during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về chuẩn bị trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 53,
    "word": "do",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈu/",
    "meaning": "làm",
    "ex1": "Grilled shrimp are easy to prepare and do not need many ingredients.",
    "ex1_vi": "Tôm nướng dễ chuẩn bị và không cần nhiều nguyên liệu."
  },
  {
    "id": 54,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "People discuss not during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về không trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 55,
    "word": "need",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈid/",
    "meaning": "cần",
    "ex1": "People discuss need during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về cần trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 56,
    "word": "ingredients",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnɡrˈidiʌnts/",
    "meaning": "nguyên liệu",
    "ex1": "People discuss ingredients during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về nguyên liệu trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 57,
    "word": "provide",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌvˈaɪd/",
    "meaning": "cung cấp",
    "ex1": "Families provide fresh seafood during relaxed weekend meals.",
    "ex1_vi": "Các gia đình cung cấp hải sản tươi trong những bữa ăn cuối tuần thư giãn."
  },
  {
    "id": 58,
    "word": "protein",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈoʊtˌin/",
    "meaning": "protein",
    "ex1": "Fresh seafood can include protein in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có protein."
  },
  {
    "id": 59,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔrtʌnt/",
    "meaning": "quan trọng",
    "ex1": "A well-prepared seafood meal can feel important and satisfying.",
    "ex1_vi": "Một bữa hải sản được chuẩn bị tốt có thể quan trọng và làm no."
  },
  {
    "id": 60,
    "word": "nutrients",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈutriʌnts/",
    "meaning": "chất dinh dưỡng",
    "ex1": "Families talk about nutrients during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về chất dinh dưỡng trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 61,
    "word": "eating",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈitɪŋ/",
    "meaning": "việc ăn",
    "ex1": "Fresh seafood can include eating in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có việc ăn."
  },
  {
    "id": 62,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm cho",
    "ex1": "Cooks makes seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu làm cho hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 63,
    "word": "meal",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈil/",
    "meaning": "bữa ăn",
    "ex1": "Families talk about meal during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về bữa ăn trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 64,
    "word": "more",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "hơn",
    "ex1": "More families enjoy fresh seafood during weekend gatherings.",
    "ex1_vi": "Hơn gia đình thích hải sản tươi trong các buổi tụ họp cuối tuần."
  },
  {
    "id": 65,
    "word": "delicious",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dɪlˈɪʃʌs/",
    "meaning": "ngon",
    "ex1": "People discuss delicious during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về ngon trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 66,
    "word": "enjoyable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɛndʒˈɔɪʌbʌl/",
    "meaning": "thú vị",
    "ex1": "Fresh seafood can taste enjoyable during a warm family meal.",
    "ex1_vi": "Hải sản tươi có thể có vị thú vị trong một bữa ăn gia đình ấm áp."
  },
  {
    "id": 67,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvriwˌʌn/",
    "meaning": "mọi người",
    "ex1": "Everyone enjoys sharing hot seafood during family gatherings.",
    "ex1_vi": "Mọi người thích chia sẻ hải sản nóng trong các buổi tụ họp gia đình."
  },
  {
    "id": 68,
    "word": "table",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪbʌl/",
    "meaning": "bàn",
    "ex1": "People enjoy table during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức bàn trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 69,
    "word": "steamed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈimd/",
    "meaning": "hấp",
    "ex1": "People discuss steamed during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về hấp trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 70,
    "word": "crab",
    "type": "noun",
    "cat": "n",
    "phonetic": "/krˈæb/",
    "meaning": "cua",
    "ex1": "People discuss crab during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về cua trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 71,
    "word": "crabs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/krˈæbz/",
    "meaning": "cua",
    "ex1": "People enjoy crabs during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức cua trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 72,
    "word": "washed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɑʃt/",
    "meaning": "được rửa",
    "ex1": "Families washed fresh seafood during relaxed weekend meals.",
    "ex1_vi": "Các gia đình được rửa hải sản tươi trong những bữa ăn cuối tuần thư giãn."
  },
  {
    "id": 73,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "Families carefully enjoy seafood together during weekend gatherings.",
    "ex1_vi": "Các gia đình cẩn thận thưởng thức hải sản cùng nhau trong các buổi tụ họp cuối tuần."
  },
  {
    "id": 74,
    "word": "placed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪst/",
    "meaning": "được đặt",
    "ex1": "Cooks placed seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu được đặt hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 75,
    "word": "steamer",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈimɝ/",
    "meaning": "nồi hấp",
    "ex1": "Families talk about steamer during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về nồi hấp trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 76,
    "word": "lemongrass",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈlɛmənˌɡræs/",
    "meaning": "sả",
    "ex1": "Fresh seafood can include lemongrass in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có sả."
  },
  {
    "id": 77,
    "word": "ginger",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɪndʒɝ/",
    "meaning": "gừng",
    "ex1": "People enjoy ginger during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức gừng trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 78,
    "word": "beer",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɪr/",
    "meaning": "bia",
    "ex1": "Families talk about beer during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về bia trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 79,
    "word": "after",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/ˈæftɝ/",
    "meaning": "sau",
    "ex1": "People eat seafood after it is cooked properly.",
    "ex1_vi": "Mọi người ăn hải sản sau khi được nấu đúng cách."
  },
  {
    "id": 80,
    "word": "cooking",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/kˈʊkɪŋ/",
    "meaning": "việc nấu",
    "ex1": "This cooking method keeps the natural flavor of the crab.",
    "ex1_vi": "Phương pháp nấu này giữ hương vị tự nhiên của cua."
  },
  {
    "id": 81,
    "word": "shells",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɛlz/",
    "meaning": "vỏ",
    "ex1": "Families talk about shells during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về vỏ trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 82,
    "word": "become",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌm/",
    "meaning": "trở nên",
    "ex1": "People can become seafood carefully for a family dinner.",
    "ex1_vi": "Mọi người có thể trở nên hải sản cẩn thận cho một bữa tối gia đình."
  },
  {
    "id": 83,
    "word": "bright",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/brˈaɪt/",
    "meaning": "sáng",
    "ex1": "A well-prepared seafood meal can feel bright and satisfying.",
    "ex1_vi": "Một bữa hải sản được chuẩn bị tốt có thể sáng và làm no."
  },
  {
    "id": 84,
    "word": "meat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈit/",
    "meaning": "thịt",
    "ex1": "Families talk about meat during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về thịt trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 85,
    "word": "inside",
    "type": "adverb/preposition",
    "cat": "adv",
    "phonetic": "/ˌɪnsˈaɪd/",
    "meaning": "bên trong",
    "ex1": "The outside is crunchy, while the inside remains soft and slightly sweet.",
    "ex1_vi": "Bên ngoài giòn, trong khi bên trong vẫn mềm và hơi ngọt."
  },
  {
    "id": 86,
    "word": "stays",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈeɪz/",
    "meaning": "vẫn giữ",
    "ex1": "Cooks stays seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu vẫn giữ hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 87,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "The outside is crunchy, while the inside remains soft and slightly sweet.",
    "ex1_vi": "Bên ngoài giòn, trong khi bên trong vẫn mềm và hơi ngọt."
  },
  {
    "id": 88,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "Families usually enjoy seafood together during weekend gatherings.",
    "ex1_vi": "Các gia đình thường thưởng thức hải sản cùng nhau trong các buổi tụ họp cuối tuần."
  },
  {
    "id": 89,
    "word": "break",
    "type": "verb",
    "cat": "v",
    "phonetic": "/brˈeɪk/",
    "meaning": "bẻ",
    "ex1": "Cooks break seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu bẻ hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 90,
    "word": "lime",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪm/",
    "meaning": "chanh",
    "ex1": "Families talk about lime during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về chanh trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 91,
    "word": "juice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈus/",
    "meaning": "nước cốt; nước ép",
    "ex1": "Fresh seafood can include juice in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có nước cốt; nước ép."
  },
  {
    "id": 92,
    "word": "some",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌm/",
    "meaning": "một số",
    "ex1": "People discuss some during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về một số trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 93,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌliz/",
    "meaning": "các gia đình",
    "ex1": "People discuss families during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về các gia đình trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 94,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "People discuss also during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về cũng trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 95,
    "word": "spicy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/spˈaɪsi/",
    "meaning": "cay",
    "ex1": "People discuss spicy during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về cay trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 96,
    "word": "served",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɝvd/",
    "meaning": "được phục vụ",
    "ex1": "People discuss served during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về được phục vụ trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 97,
    "word": "gatherings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈæðɝɪŋz/",
    "meaning": "buổi tụ họp",
    "ex1": "Fresh seafood can include gatherings in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có buổi tụ họp."
  },
  {
    "id": 98,
    "word": "sea",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈi/",
    "meaning": "biển",
    "ex1": "People enjoy sea during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức biển trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 99,
    "word": "method",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛθʌd/",
    "meaning": "phương pháp",
    "ex1": "This cooking method keeps the natural flavor of the crab.",
    "ex1_vi": "Phương pháp nấu này giữ hương vị tự nhiên của cua."
  },
  {
    "id": 100,
    "word": "keeps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈips/",
    "meaning": "giữ",
    "ex1": "People discuss keeps during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về giữ trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 101,
    "word": "natural",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈætʃɝʌl/",
    "meaning": "tự nhiên",
    "ex1": "People discuss natural during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về tự nhiên trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 102,
    "word": "flavor",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝ/",
    "meaning": "hương vị",
    "ex1": "People discuss flavor during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về hương vị trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 103,
    "word": "uses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈusʌz/",
    "meaning": "sử dụng",
    "ex1": "People discuss uses during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về sử dụng trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 104,
    "word": "so",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/sˈoʊ/",
    "meaning": "vì vậy",
    "ex1": "People discuss so during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về vì vậy trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 105,
    "word": "feels",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈilz/",
    "meaning": "cảm thấy",
    "ex1": "People discuss feels during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về cảm thấy trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 106,
    "word": "light",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈaɪt/",
    "meaning": "nhẹ",
    "ex1": "People discuss light during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về nhẹ trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 107,
    "word": "healthy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlθi/",
    "meaning": "lành mạnh",
    "ex1": "People discuss healthy during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về lành mạnh trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 108,
    "word": "lovers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈʌvɝz/",
    "meaning": "người yêu thích",
    "ex1": "Many seafood lovers enjoy steamed crab during special occasions.",
    "ex1_vi": "Nhiều người yêu hải sản thích cua hấp trong những dịp đặc biệt."
  },
  {
    "id": 109,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thưởng thức",
    "ex1": "People discuss enjoy during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về thưởng thức trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 110,
    "word": "special",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/spˈɛʃʌl/",
    "meaning": "đặc biệt",
    "ex1": "People discuss special during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về đặc biệt trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 111,
    "word": "occasions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌkˈeɪʒʌnz/",
    "meaning": "dịp",
    "ex1": "People discuss occasions during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về dịp trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 112,
    "word": "fried",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈaɪd/",
    "meaning": "chiên",
    "ex1": "Fried squid is a tasty seafood dish enjoyed by many people.",
    "ex1_vi": "Mực chiên là một món hải sản ngon được nhiều người yêu thích."
  },
  {
    "id": 113,
    "word": "squid",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skwˈɪd/",
    "meaning": "mực",
    "ex1": "People discuss squid during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về mực trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 114,
    "word": "tasty",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈeɪsti/",
    "meaning": "ngon",
    "ex1": "People discuss tasty during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về ngon trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 115,
    "word": "enjoyed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪd/",
    "meaning": "được yêu thích",
    "ex1": "People discuss enjoyed during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về được yêu thích trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 116,
    "word": "cut",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌt/",
    "meaning": "cắt",
    "ex1": "Cooks cut seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu cắt hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 117,
    "word": "rings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɪŋz/",
    "meaning": "khoanh",
    "ex1": "Families talk about rings during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về khoanh trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 118,
    "word": "covered",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌvɝd/",
    "meaning": "được phủ",
    "ex1": "People can covered seafood carefully for a family dinner.",
    "ex1_vi": "Mọi người có thể được phủ hải sản cẩn thận cho một bữa tối gia đình."
  },
  {
    "id": 119,
    "word": "flour",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈaʊɝ/",
    "meaning": "bột",
    "ex1": "People enjoy flour during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức bột trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 120,
    "word": "egg",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛɡ/",
    "meaning": "trứng",
    "ex1": "Families talk about egg during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về trứng trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 121,
    "word": "breadcrumbs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈbrɛdkrʌmz/",
    "meaning": "vụn bánh mì",
    "ex1": "Fresh seafood can include breadcrumbs in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có vụn bánh mì."
  },
  {
    "id": 122,
    "word": "until",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌntˈɪl/",
    "meaning": "cho đến khi",
    "ex1": "The seafood cooks until it becomes hot and ready.",
    "ex1_vi": "Hải sản được nấu cho đến khi nóng và sẵn sàng."
  },
  {
    "id": 123,
    "word": "outside",
    "type": "adverb/noun",
    "cat": "adv",
    "phonetic": "/ˈaʊtsˈaɪd/",
    "meaning": "bên ngoài",
    "ex1": "People discuss outside during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về bên ngoài trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 124,
    "word": "golden",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈoʊldʌn/",
    "meaning": "vàng",
    "ex1": "This seafood dish looks golden when served at the table.",
    "ex1_vi": "Món hải sản này trông vàng khi được phục vụ tại bàn."
  },
  {
    "id": 125,
    "word": "crispy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈɪspi/",
    "meaning": "giòn",
    "ex1": "A well-prepared seafood meal can feel crispy and satisfying.",
    "ex1_vi": "Một bữa hải sản được chuẩn bị tốt có thể giòn và làm no."
  },
  {
    "id": 126,
    "word": "chili",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪli/",
    "meaning": "ớt",
    "ex1": "People discuss chili during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về ớt trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 127,
    "word": "mayonnaise",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌmeɪəˈneɪz/",
    "meaning": "sốt mayonnaise",
    "ex1": "People discuss mayonnaise during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về sốt mayonnaise trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 128,
    "word": "crunchy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈʌntʃi/",
    "meaning": "giòn",
    "ex1": "People discuss crunchy during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về giòn trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 129,
    "word": "remains",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rɪmˈeɪnz/",
    "meaning": "vẫn giữ",
    "ex1": "People discuss remains during fresh seafood meals at home.",
    "ex1_vi": "Mọi người nói về vẫn giữ trong những bữa hải sản tươi ở nhà."
  },
  {
    "id": 130,
    "word": "children",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪldrʌn/",
    "meaning": "trẻ em",
    "ex1": "Fresh seafood can include children in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có trẻ em."
  },
  {
    "id": 131,
    "word": "adults",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌdˈʌlts/",
    "meaning": "người lớn",
    "ex1": "People enjoy adults during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức người lớn trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 132,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "Seafood is popular because it has many delicious flavors.",
    "ex1_vi": "Hải sản phổ biến vì có nhiều hương vị ngon."
  },
  {
    "id": 133,
    "word": "although",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˌɔlðˈoʊ/",
    "meaning": "mặc dù",
    "ex1": "Although fried squid is tasty, people should eat moderately.",
    "ex1_vi": "Mặc dù mực chiên ngon, mọi người nên ăn vừa phải."
  },
  {
    "id": 134,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "People should cook fresh seafood properly for safety.",
    "ex1_vi": "Mọi người nên nấu hải sản tươi đúng cách để bảo đảm an toàn."
  },
  {
    "id": 135,
    "word": "too",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tˈu/",
    "meaning": "quá",
    "ex1": "People too prepare seafood for family meals at home.",
    "ex1_vi": "Mọi người quá chuẩn bị hải sản cho các bữa ăn gia đình ở nhà."
  },
  {
    "id": 136,
    "word": "much",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈʌtʃ/",
    "meaning": "nhiều",
    "ex1": "Much families enjoy fresh seafood during weekend gatherings.",
    "ex1_vi": "Nhiều gia đình thích hải sản tươi trong các buổi tụ họp cuối tuần."
  },
  {
    "id": 137,
    "word": "contains",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈeɪnz/",
    "meaning": "chứa",
    "ex1": "Cooks contains seafood with simple ingredients in the kitchen.",
    "ex1_vi": "Người nấu chứa hải sản với những nguyên liệu đơn giản trong bếp."
  },
  {
    "id": 138,
    "word": "best",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/bˈɛst/",
    "meaning": "tốt nhất",
    "ex1": "People best prepare seafood for family meals at home.",
    "ex1_vi": "Mọi người tốt nhất chuẩn bị hải sản cho các bữa ăn gia đình ở nhà."
  },
  {
    "id": 139,
    "word": "snack",
    "type": "noun",
    "cat": "n",
    "phonetic": "/snˈæk/",
    "meaning": "món ăn vặt",
    "ex1": "Fresh seafood can include snack in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có món ăn vặt."
  },
  {
    "id": 140,
    "word": "appetizer",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈæpɪˌtaɪzər/",
    "meaning": "món khai vị",
    "ex1": "People enjoy appetizer during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức món khai vị trong những bữa hải sản thư giãn với bạn bè."
  },
  {
    "id": 141,
    "word": "part",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrt/",
    "meaning": "phần",
    "ex1": "Families talk about part during simple seafood meals together.",
    "ex1_vi": "Các gia đình nói về phần trong những bữa hải sản đơn giản cùng nhau."
  },
  {
    "id": 142,
    "word": "close",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈoʊs/",
    "meaning": "thân thiết",
    "ex1": "Fresh seafood can include close in a family meal.",
    "ex1_vi": "Một bữa ăn gia đình với hải sản tươi có thể có thân thiết."
  },
  {
    "id": 143,
    "word": "friends",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈɛndz/",
    "meaning": "bạn bè",
    "ex1": "People enjoy friends during relaxed seafood meals with friends.",
    "ex1_vi": "Mọi người thưởng thức bạn bè trong những bữa hải sản thư giãn với bạn bè."
  }
];

const newReadingVocabOrder = [
  "grilled",
  "shrimp",
  "popular",
  "seafood",
  "dish",
  "many",
  "coastal",
  "areas",
  "fresh",
  "cleaned",
  "seasoned",
  "salt",
  "pepper",
  "garlic",
  "and",
  "little",
  "oil",
  "then",
  "cooked",
  "hot",
  "charcoal",
  "smell",
  "becomes",
  "very",
  "attractive",
  "while",
  "slowly",
  "turn",
  "orange",
  "people",
  "often",
  "eat",
  "vegetables",
  "rice",
  "paper",
  "or",
  "simple",
  "dipping",
  "sauce",
  "taste",
  "sweet",
  "juicy",
  "slightly",
  "smoky",
  "common",
  "family",
  "meals",
  "restaurants",
  "weekend",
  "parties",
  "easy",
  "prepare",
  "do",
  "not",
  "need",
  "ingredients",
  "provide",
  "protein",
  "important",
  "nutrients",
  "eating",
  "makes",
  "meal",
  "more",
  "delicious",
  "enjoyable",
  "everyone",
  "table",
  "steamed",
  "crab",
  "crabs",
  "washed",
  "carefully",
  "placed",
  "steamer",
  "lemongrass",
  "ginger",
  "beer",
  "after",
  "cooking",
  "shells",
  "become",
  "bright",
  "meat",
  "inside",
  "stays",
  "soft",
  "usually",
  "break",
  "lime",
  "juice",
  "some",
  "families",
  "also",
  "spicy",
  "served",
  "gatherings",
  "sea",
  "method",
  "keeps",
  "natural",
  "flavor",
  "uses",
  "so",
  "feels",
  "light",
  "healthy",
  "lovers",
  "enjoy",
  "special",
  "occasions",
  "fried",
  "squid",
  "tasty",
  "enjoyed",
  "cut",
  "rings",
  "covered",
  "flour",
  "egg",
  "breadcrumbs",
  "until",
  "outside",
  "golden",
  "crispy",
  "chili",
  "mayonnaise",
  "crunchy",
  "remains",
  "children",
  "adults",
  "because",
  "although",
  "should",
  "too",
  "much",
  "contains",
  "best",
  "snack",
  "appetizer",
  "part",
  "close",
  "friends"
];
