const newEssayData = [
  {
    "text": "4. Wild Animals\nWild animals live in forests, mountains, grasslands, and deserts around the world. Lions, elephants, wolves, and monkeys have different habits and food sources. Look! A family of elephants is walking slowly across the open grassland this afternoon.\n\nMany wild animals have already lost their habitats because people are cutting down forests. Last year, several rescued animals were moved to protected areas where they could live safely again. These programs have brought hope to many species.\n\nPeople should respect wildlife and must never hunt endangered animals. If everyone protects nature, wild animals will continue living freely for many generations.",
    "vi": "4. Động vật hoang dã\nĐộng vật hoang dã sống trong rừng, núi, đồng cỏ và sa mạc trên khắp thế giới. Sư tử, voi, sói và khỉ có tập tính và nguồn thức ăn khác nhau. Nhìn kìa! Một gia đình voi đang đi chậm qua đồng cỏ rộng vào chiều nay.\n\nNhiều động vật hoang dã đã mất môi trường sống vì con người đang chặt rừng. Năm ngoái, một số động vật được cứu hộ đã được chuyển đến các khu vực được bảo vệ, nơi chúng có thể sống an toàn trở lại. Những chương trình này đã mang lại hy vọng cho nhiều loài.\n\nMọi người nên tôn trọng động vật hoang dã và tuyệt đối không được săn các loài có nguy cơ tuyệt chủng. Nếu mọi người bảo vệ thiên nhiên, động vật hoang dã sẽ tiếp tục sống tự do qua nhiều thế hệ."
  },
  {
    "text": "5. National Parks\nNational parks protect beautiful landscapes, rare plants, and many kinds of wildlife. Visitors enjoy walking along forest trails, taking photographs, and learning about nature. Look! A group of tourists is following a park guide through a peaceful forest today.\n\nMany national parks have already welcomed thousands of visitors this year. Last summer, several students joined a nature camp and learned how to protect local wildlife. Their activities inspired many young people to care for nature.\n\nEveryone should follow park rules and keep the environment clean. If visitors respect nature, national parks will remain beautiful and safe for future generations.",
    "vi": "5. Công viên quốc gia\nCông viên quốc gia bảo vệ những cảnh quan đẹp, thực vật quý hiếm và nhiều loại động vật hoang dã. Du khách thích đi bộ dọc các đường mòn trong rừng, chụp ảnh và tìm hiểu thiên nhiên. Nhìn kìa! Một nhóm du khách đang đi theo hướng dẫn viên công viên qua một khu rừng yên bình hôm nay.\n\nNhiều công viên quốc gia đã đón hàng nghìn du khách trong năm nay. Mùa hè năm ngoái, một số học sinh tham gia trại thiên nhiên và học cách bảo vệ động vật hoang dã địa phương. Những hoạt động của họ đã truyền cảm hứng cho nhiều người trẻ quan tâm đến thiên nhiên.\n\nMọi người nên tuân theo quy định công viên và giữ môi trường sạch. Nếu du khách tôn trọng thiên nhiên, các công viên quốc gia sẽ vẫn đẹp và an toàn cho các thế hệ tương lai."
  },
  {
    "text": "6. Planting Trees\nPlanting trees is one of the best ways to protect the environment. Trees provide fresh air, reduce pollution, and offer homes for many animals. Look! Volunteers are planting young trees in a community park this morning with great care.\n\nMany cities have already started tree-planting programs to create greener neighborhoods. Last month, hundreds of students planted trees near their schools and learned about environmental protection. Their hard work made the area cleaner and more attractive.\n\nEveryone should plant more trees whenever possible. If people continue these activities, cities will become greener, healthier, and more comfortable places to live for everyone.",
    "vi": "6. Trồng cây\nTrồng cây là một trong những cách tốt nhất để bảo vệ môi trường. Cây cung cấp không khí trong lành, giảm ô nhiễm và tạo nơi ở cho nhiều động vật. Nhìn kìa! Các tình nguyện viên đang trồng cây non trong một công viên cộng đồng sáng nay với sự chăm sóc tận tình.\n\nNhiều thành phố đã bắt đầu các chương trình trồng cây để tạo ra những khu dân cư xanh hơn. Tháng trước, hàng trăm học sinh đã trồng cây gần trường và tìm hiểu về bảo vệ môi trường. Công việc chăm chỉ của họ làm khu vực sạch hơn và hấp dẫn hơn.\n\nMọi người nên trồng thêm cây bất cứ khi nào có thể. Nếu mọi người tiếp tục các hoạt động này, thành phố sẽ trở nên xanh hơn, khỏe mạnh hơn và thoải mái hơn để mọi người sinh sống."
  }
];
