const newEssayData = [
  {
    "text": "1. Beautiful Forests\nForests are important because they provide homes for many plants and animals. Tall trees, colorful flowers, and fresh streams make forests beautiful places. Look! Several birds are building nests while butterflies are flying among the green leaves today.\n\nMany forests have already become smaller because too many trees were cut down. Last year, volunteers planted thousands of young trees to restore damaged areas. These efforts have helped many animals return to their natural habitats.\n\nPeople should protect forests and never waste natural resources. If everyone plants more trees, forests will become greener, healthier, and more beautiful for future generations.",
    "vi": "1. Những khu rừng tươi đẹp\nRừng rất quan trọng vì chúng cung cấp nơi ở cho nhiều loài thực vật và động vật. Những cây cao, hoa nhiều màu sắc và các dòng suối trong lành làm cho rừng trở thành những nơi tuyệt đẹp. Nhìn kìa! Một số con chim đang xây tổ trong khi bướm đang bay giữa những chiếc lá xanh hôm nay.\n\nNhiều khu rừng đã trở nên nhỏ hơn vì quá nhiều cây đã bị chặt. Năm ngoái, các tình nguyện viên đã trồng hàng nghìn cây non để phục hồi những khu vực bị hư hại. Những nỗ lực này đã giúp nhiều loài động vật trở lại môi trường sống tự nhiên của chúng.\n\nMọi người nên bảo vệ rừng và không bao giờ lãng phí tài nguyên thiên nhiên. Nếu mọi người trồng thêm cây, rừng sẽ trở nên xanh hơn, khỏe mạnh hơn và đẹp hơn cho các thế hệ tương lai."
  },
  {
    "text": "2. Rivers and Lakes\nRivers and lakes provide fresh water for people, animals, and plants. Many fish, birds, and insects live near clean water every day. Look! Several ducks are swimming across a peaceful lake while children are watching them happily.\n\nMany rivers have already become cleaner because local communities started environmental projects. Last spring, volunteers collected plastic bottles and other rubbish along the riverbanks. Their hard work improved the natural environment greatly.\n\nEveryone should keep rivers and lakes clean. If people stop throwing rubbish into the water, aquatic life will grow well, and future generations will enjoy these beautiful places together.",
    "vi": "2. Sông và hồ\nSông và hồ cung cấp nước ngọt cho con người, động vật và thực vật. Nhiều loài cá, chim và côn trùng sống gần nguồn nước sạch mỗi ngày. Nhìn kìa! Một số con vịt đang bơi qua một hồ nước yên bình trong khi trẻ em đang vui vẻ quan sát chúng.\n\nNhiều con sông đã trở nên sạch hơn vì các cộng đồng địa phương bắt đầu những dự án môi trường. Mùa xuân năm ngoái, các tình nguyện viên đã thu gom chai nhựa và rác khác dọc theo bờ sông. Công việc chăm chỉ của họ đã cải thiện đáng kể môi trường tự nhiên.\n\nMọi người nên giữ sông và hồ sạch sẽ. Nếu mọi người ngừng ném rác xuống nước, sinh vật thủy sinh sẽ phát triển tốt và các thế hệ tương lai sẽ cùng tận hưởng những nơi tuyệt đẹp này."
  },
  {
    "text": "3. A Day in the Countryside\nThe countryside is peaceful and full of natural beauty. Green fields, quiet rivers, and small villages create a relaxing environment. Look! Farmers are working in the rice fields while birds are singing in nearby trees this morning.\n\nMany visitors have already discovered the beauty of rural areas. Last weekend, several families visited local farms, picked fresh vegetables, and learned about traditional farming. Everyone enjoyed the fresh air and friendly atmosphere.\n\nPeople should protect the countryside and respect local traditions. If villages remain clean and green, more visitors will come, and rural communities will continue growing successfully.",
    "vi": "3. Một ngày ở vùng quê\nVùng quê yên bình và tràn đầy vẻ đẹp tự nhiên. Những cánh đồng xanh, dòng sông yên tĩnh và làng nhỏ tạo nên một môi trường thư giãn. Nhìn kìa! Nông dân đang làm việc trên ruộng lúa trong khi chim đang hót trên những cây gần đó sáng nay.\n\nNhiều du khách đã khám phá vẻ đẹp của vùng nông thôn. Cuối tuần trước, một số gia đình đã thăm các nông trại địa phương, hái rau tươi và tìm hiểu về cách canh tác truyền thống. Mọi người đều thích không khí trong lành và bầu không khí thân thiện.\n\nMọi người nên bảo vệ vùng quê và tôn trọng truyền thống địa phương. Nếu các làng vẫn sạch và xanh, nhiều du khách hơn sẽ đến và các cộng đồng nông thôn sẽ tiếp tục phát triển thành công."
  }
];
