const newEssayData = [
  {
    "text": "1. Why People Love Sports\nMany people love sports because they are fun and healthy. Some play football, while others swim or ride bikes. Children often play after school, and many adults exercise before work. Look! Some students are playing basketball now.\n\nLast weekend, my family joined a sports festival. We played games, won small prizes, and met new friends. I have already learned that sports help people become stronger and happier. Everyone enjoyed the exciting activities together.\n\nNext month, our class is going to have another sports day. I will join the football team again. If the weather is nice, we will play outside. Everyone should exercise every day to stay healthy and active.",
    "vi": "1. Vì sao mọi người yêu thể thao\nNhiều người yêu thích thể thao vì chúng vui và tốt cho sức khỏe. Một số người chơi bóng đá, trong khi những người khác bơi hoặc đi xe đạp. Trẻ em thường chơi sau giờ học và nhiều người lớn tập thể dục trước khi làm việc. Nhìn kìa! Một số học sinh đang chơi bóng rổ lúc này.\n\nCuối tuần trước, gia đình tôi tham gia một lễ hội thể thao. Chúng tôi chơi trò chơi, giành những giải thưởng nhỏ và gặp những người bạn mới. Tôi đã nhận ra rằng thể thao giúp con người trở nên khỏe mạnh và vui vẻ hơn. Mọi người cùng nhau tận hưởng những hoạt động hào hứng.\n\nTháng tới, lớp chúng tôi sẽ có một ngày hội thể thao khác. Tôi sẽ lại tham gia đội bóng đá. Nếu thời tiết đẹp, chúng tôi sẽ chơi bên ngoài. Mọi người nên tập thể dục mỗi ngày để luôn khỏe mạnh và năng động."
  },
  {
    "text": "2. Playing Football\nFootball is one of the most popular sports in the world. Many students play it after school because it is exciting and helps them stay healthy. My friends and I usually practice twice a week. Look! We are training on the school field now.\n\nLast Saturday, our team played against another class. We worked together, passed the ball well, and won the match. Our coach has already praised our teamwork, so we feel proud and confident.\n\nNext weekend, we are going to join another competition. I think we will play even better. If we keep practicing, we will become a stronger team. Everyone should play fairly and respect every player.",
    "vi": "2. Chơi bóng đá\nBóng đá là một trong những môn thể thao phổ biến nhất trên thế giới. Nhiều học sinh chơi môn này sau giờ học vì nó hào hứng và giúp các em khỏe mạnh. Bạn bè tôi và tôi thường luyện tập hai lần một tuần. Nhìn kìa! Chúng tôi đang tập trên sân trường lúc này.\n\nThứ Bảy tuần trước, đội của chúng tôi thi đấu với một lớp khác. Chúng tôi phối hợp cùng nhau, chuyền bóng tốt và thắng trận đấu. Huấn luyện viên đã khen tinh thần đồng đội của chúng tôi, vì vậy chúng tôi cảm thấy tự hào và tự tin.\n\nCuối tuần tới, chúng tôi sẽ tham gia một cuộc thi khác. Tôi nghĩ chúng tôi sẽ chơi tốt hơn nữa. Nếu chúng tôi tiếp tục luyện tập, chúng tôi sẽ trở thành một đội mạnh hơn. Mọi người nên chơi công bằng và tôn trọng mọi cầu thủ."
  },
  {
    "text": "3. Swimming for Health\nSwimming is a great sport for people of all ages. It keeps the body strong and helps the heart stay healthy. Many children learn to swim during summer. Look! My little brother is swimming happily in the pool now.\n\nLast year, I could not swim well, but I practiced every weekend. Now I have already become much more confident in the water. My teacher says swimming is safer when we follow the rules carefully.\n\nNext month, I am going to join a swimming club. I hope I will improve my skills quickly. If you want to stay healthy, you should learn to swim safely.",
    "vi": "3. Bơi lội vì sức khỏe\nBơi lội là một môn thể thao tuyệt vời cho mọi lứa tuổi. Nó giúp cơ thể khỏe mạnh và giúp tim luôn khỏe. Nhiều trẻ em học bơi trong mùa hè. Nhìn kìa! Em trai tôi đang vui vẻ bơi trong hồ lúc này.\n\nNăm ngoái, tôi không thể bơi tốt, nhưng tôi đã luyện tập mỗi cuối tuần. Bây giờ tôi đã trở nên tự tin hơn nhiều khi ở dưới nước. Giáo viên của tôi nói bơi lội an toàn hơn khi chúng ta tuân theo quy tắc cẩn thận.\n\nTháng tới, tôi sẽ tham gia một câu lạc bộ bơi lội. Tôi hy vọng mình sẽ cải thiện kỹ năng nhanh chóng. Nếu bạn muốn khỏe mạnh, bạn nên học bơi an toàn."
  }
];
