const lessonVocabularyWords = [
  "why",
  "people",
  "love",
  "sports",
  "many",
  "because",
  "fun",
  "and",
  "healthy",
  "some",
  "play",
  "football",
  "while",
  "others",
  "swim",
  "or",
  "ride",
  "bikes",
  "children",
  "often",
  "after",
  "school",
  "adults",
  "exercise",
  "before",
  "work",
  "look",
  "students",
  "playing",
  "basketball",
  "now",
  "last",
  "weekend",
  "family",
  "joined",
  "festival",
  "played",
  "games",
  "won",
  "small",
  "prizes",
  "met",
  "new",
  "friends",
  "have",
  "already",
  "learned",
  "help",
  "become",
  "stronger",
  "happier",
  "everyone",
  "enjoyed",
  "exciting",
  "activities",
  "together",
  "next",
  "month",
  "class",
  "going",
  "another",
  "day",
  "will",
  "join",
  "team",
  "again",
  "if",
  "weather",
  "nice",
  "outside",
  "should",
  "every",
  "stay",
  "active",
  "one",
  "most",
  "popular",
  "world",
  "helps",
  "usually",
  "practice",
  "twice",
  "week",
  "training",
  "field",
  "saturday",
  "against",
  "worked",
  "passed",
  "ball",
  "well",
  "match",
  "coach",
  "has",
  "praised",
  "teamwork",
  "so",
  "feel",
  "proud",
  "confident",
  "competition",
  "think",
  "even",
  "better",
  "keep",
  "practicing",
  "fairly",
  "respect",
  "player",
  "swimming",
  "health",
  "great",
  "sport",
  "all",
  "ages",
  "keeps",
  "body",
  "strong",
  "heart",
  "learn",
  "summer",
  "little",
  "brother",
  "happily",
  "pool",
  "year",
  "could",
  "not",
  "but",
  "practiced",
  "much",
  "more",
  "water",
  "teacher",
  "says",
  "safer",
  "when",
  "follow",
  "rules",
  "carefully",
  "club",
  "hope",
  "improve",
  "skills",
  "quickly",
  "want",
  "safely"
];

const newVocabData = [
  {
    "id": 1,
    "word": "why",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈaɪ/",
    "meaning": "vì sao",
    "ex1": "Students why practice sports during weekly school activities.",
    "ex1_vi": "Học sinh vì sao luyện tập thể thao trong các hoạt động hằng tuần ở trường."
  },
  {
    "id": 2,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "Many people love sports because they are fun and healthy.",
    "ex1_vi": "Nhiều người yêu thích thể thao vì chúng vui và tốt cho sức khỏe."
  },
  {
    "id": 3,
    "word": "love",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʌv/",
    "meaning": "yêu thích",
    "ex1": "Many people love sports because they are fun and healthy.",
    "ex1_vi": "Nhiều người yêu thích thể thao vì chúng vui và tốt cho sức khỏe."
  },
  {
    "id": 4,
    "word": "sports",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈɔrts/",
    "meaning": "thể thao",
    "ex1": "Last weekend, my family joined a sports festival.",
    "ex1_vi": "Cuối tuần trước, gia đình tôi tham gia một lễ hội thể thao."
  },
  {
    "id": 5,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Many students enjoy healthy sports activities after school.",
    "ex1_vi": "Nhiều học sinh thích các hoạt động thể thao lành mạnh sau giờ học."
  },
  {
    "id": 6,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "Students discuss because during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về bởi vì trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 7,
    "word": "fun",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈʌn/",
    "meaning": "vui",
    "ex1": "Students discuss fun during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về vui trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 8,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Everyone should play fairly and respect every player.",
    "ex1_vi": "Mọi người nên chơi công bằng và tôn trọng mọi cầu thủ."
  },
  {
    "id": 9,
    "word": "healthy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlθi/",
    "meaning": "khỏe mạnh",
    "ex1": "Students discuss healthy during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về khỏe mạnh trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 10,
    "word": "some",
    "type": "determiner/pronoun",
    "cat": "adj",
    "phonetic": "/sˈʌm/",
    "meaning": "một số",
    "ex1": "Some students enjoy healthy sports activities after school.",
    "ex1_vi": "Một số học sinh thích các hoạt động thể thao lành mạnh sau giờ học."
  },
  {
    "id": 11,
    "word": "play",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪ/",
    "meaning": "chơi",
    "ex1": "Students can play during regular sports practice after school.",
    "ex1_vi": "Học sinh có thể chơi trong buổi luyện tập thể thao thường xuyên sau giờ học."
  },
  {
    "id": 12,
    "word": "football",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈʊtbˌɔl/",
    "meaning": "bóng đá",
    "ex1": "Students learn about football during regular sports activities.",
    "ex1_vi": "Học sinh học về bóng đá trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 13,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "Some play football, while others swim or ride bikes.",
    "ex1_vi": "Một số người chơi bóng đá, trong khi những người khác bơi hoặc đi xe đạp."
  },
  {
    "id": 14,
    "word": "others",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈʌðɝz/",
    "meaning": "những người khác",
    "ex1": "Some play football, while others swim or ride bikes.",
    "ex1_vi": "Một số người chơi bóng đá, trong khi những người khác bơi hoặc đi xe đạp."
  },
  {
    "id": 15,
    "word": "swim",
    "type": "verb",
    "cat": "v",
    "phonetic": "/swˈɪm/",
    "meaning": "bơi",
    "ex1": "Students can swim during regular sports practice after school.",
    "ex1_vi": "Học sinh có thể bơi trong buổi luyện tập thể thao thường xuyên sau giờ học."
  },
  {
    "id": 16,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "Students discuss or during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về hoặc trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 17,
    "word": "ride",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪd/",
    "meaning": "đi; cưỡi",
    "ex1": "Students discuss ride during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về đi; cưỡi trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 18,
    "word": "bikes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈaɪks/",
    "meaning": "xe đạp",
    "ex1": "Students discuss bikes during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về xe đạp trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 19,
    "word": "children",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪldrʌn/",
    "meaning": "trẻ em",
    "ex1": "Students learn about children during regular sports activities.",
    "ex1_vi": "Học sinh học về trẻ em trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 20,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "Children often play after school, and many adults exercise before work.",
    "ex1_vi": "Trẻ em thường chơi sau giờ học và nhiều người lớn tập thể dục trước khi làm việc."
  },
  {
    "id": 21,
    "word": "after",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/ˈæftɝ/",
    "meaning": "sau",
    "ex1": "Children often play after school, and many adults exercise before work.",
    "ex1_vi": "Trẻ em thường chơi sau giờ học và nhiều người lớn tập thể dục trước khi làm việc."
  },
  {
    "id": 22,
    "word": "school",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈul/",
    "meaning": "trường học",
    "ex1": "We are training on the school field now.",
    "ex1_vi": "Chúng tôi đang tập trên sân trường lúc này."
  },
  {
    "id": 23,
    "word": "adults",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌdˈʌlts/",
    "meaning": "người lớn",
    "ex1": "Students discuss adults during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về người lớn trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 24,
    "word": "exercise",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛksɝsˌaɪz/",
    "meaning": "tập thể dục",
    "ex1": "Everyone should exercise every day to stay healthy and active.",
    "ex1_vi": "Mọi người nên tập thể dục mỗi ngày để luôn khỏe mạnh và năng động."
  },
  {
    "id": 25,
    "word": "before",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/bɪfˈɔr/",
    "meaning": "trước",
    "ex1": "Students discuss before during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về trước trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 26,
    "word": "work",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝk/",
    "meaning": "công việc; làm việc",
    "ex1": "Students discuss work during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về công việc; làm việc trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 27,
    "word": "look",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊk/",
    "meaning": "nhìn",
    "ex1": "Students can look during regular sports practice after school.",
    "ex1_vi": "Học sinh có thể nhìn trong buổi luyện tập thể thao thường xuyên sau giờ học."
  },
  {
    "id": 28,
    "word": "students",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈudʌnts/",
    "meaning": "học sinh",
    "ex1": "Students learn about students during regular sports activities.",
    "ex1_vi": "Học sinh học về học sinh trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 29,
    "word": "playing",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/plˈeɪɪŋ/",
    "meaning": "đang chơi",
    "ex1": "Students learn about playing during regular sports activities.",
    "ex1_vi": "Học sinh học về đang chơi trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 30,
    "word": "basketball",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈæskʌtbˌɔl/",
    "meaning": "bóng rổ",
    "ex1": "Students learn about basketball during regular sports activities.",
    "ex1_vi": "Học sinh học về bóng rổ trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 31,
    "word": "now",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈaʊ/",
    "meaning": "bây giờ",
    "ex1": "Students now practice sports during weekly school activities.",
    "ex1_vi": "Học sinh bây giờ luyện tập thể thao trong các hoạt động hằng tuần ở trường."
  },
  {
    "id": 32,
    "word": "last",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈæst/",
    "meaning": "trước",
    "ex1": "Last weekend, my family joined a sports festival.",
    "ex1_vi": "Cuối tuần trước, gia đình tôi tham gia một lễ hội thể thao."
  },
  {
    "id": 33,
    "word": "weekend",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈikˌɛnd/",
    "meaning": "cuối tuần",
    "ex1": "Students discuss weekend during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về cuối tuần trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 34,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "Students discuss family during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về gia đình trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 35,
    "word": "joined",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dʒˈɔɪnd/",
    "meaning": "đã tham gia",
    "ex1": "Students discuss joined during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về đã tham gia trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 36,
    "word": "festival",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɛstʌvʌl/",
    "meaning": "lễ hội",
    "ex1": "Students discuss festival during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về lễ hội trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 37,
    "word": "played",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪd/",
    "meaning": "đã chơi",
    "ex1": "Last Saturday, our team played against another class.",
    "ex1_vi": "Thứ Bảy tuần trước, đội của chúng tôi thi đấu với một lớp khác."
  },
  {
    "id": 38,
    "word": "games",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈeɪmz/",
    "meaning": "trò chơi",
    "ex1": "We played games, won small prizes, and met new friends.",
    "ex1_vi": "Chúng tôi chơi trò chơi, giành những giải thưởng nhỏ và gặp những người bạn mới."
  },
  {
    "id": 39,
    "word": "won",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈʌn/",
    "meaning": "đã thắng; giành",
    "ex1": "We played games, won small prizes, and met new friends.",
    "ex1_vi": "Chúng tôi chơi trò chơi, giành những giải thưởng nhỏ và gặp những người bạn mới."
  },
  {
    "id": 40,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "Students discuss small during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về nhỏ trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 41,
    "word": "prizes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈaɪzʌz/",
    "meaning": "giải thưởng",
    "ex1": "Students discuss prizes during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về giải thưởng trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 42,
    "word": "met",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛt/",
    "meaning": "đã gặp",
    "ex1": "Students discuss met during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về đã gặp trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 43,
    "word": "new",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈu/",
    "meaning": "mới",
    "ex1": "Students discuss new during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về mới trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 44,
    "word": "friends",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈɛndz/",
    "meaning": "bạn bè",
    "ex1": "My friends and I usually practice twice a week.",
    "ex1_vi": "Bạn bè tôi và tôi thường luyện tập hai lần một tuần."
  },
  {
    "id": 45,
    "word": "have",
    "type": "verb/auxiliary",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có; trợ động từ",
    "ex1": "Next month, our class is going to have another sports day.",
    "ex1_vi": "Tháng tới, lớp chúng tôi sẽ có một ngày hội thể thao khác."
  },
  {
    "id": 46,
    "word": "already",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɔlrˈɛdi/",
    "meaning": "đã",
    "ex1": "Now I have already become much more confident in the water.",
    "ex1_vi": "Bây giờ tôi đã trở nên tự tin hơn nhiều khi ở dưới nước."
  },
  {
    "id": 47,
    "word": "learned",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɝnd/",
    "meaning": "đã học; nhận ra",
    "ex1": "I have already learned that sports help people become stronger and happier.",
    "ex1_vi": "Tôi đã nhận ra rằng thể thao giúp con người trở nên khỏe mạnh và vui vẻ hơn."
  },
  {
    "id": 48,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "I have already learned that sports help people become stronger and happier.",
    "ex1_vi": "Tôi đã nhận ra rằng thể thao giúp con người trở nên khỏe mạnh và vui vẻ hơn."
  },
  {
    "id": 49,
    "word": "become",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌm/",
    "meaning": "trở nên",
    "ex1": "If we keep practicing, we will become a stronger team.",
    "ex1_vi": "Nếu chúng tôi tiếp tục luyện tập, chúng tôi sẽ trở thành một đội mạnh hơn."
  },
  {
    "id": 50,
    "word": "stronger",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋɝ/",
    "meaning": "khỏe hơn",
    "ex1": "If we keep practicing, we will become a stronger team.",
    "ex1_vi": "Nếu chúng tôi tiếp tục luyện tập, chúng tôi sẽ trở thành một đội mạnh hơn."
  },
  {
    "id": 51,
    "word": "happier",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈæpiɝ/",
    "meaning": "vui hơn",
    "ex1": "Students discuss happier during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về vui hơn trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 52,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvriwˌʌn/",
    "meaning": "mọi người",
    "ex1": "Students learn about everyone during regular sports activities.",
    "ex1_vi": "Học sinh học về mọi người trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 53,
    "word": "enjoyed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪd/",
    "meaning": "đã thích",
    "ex1": "We enjoyed together during an exciting sports activity.",
    "ex1_vi": "Chúng tôi đã thích cùng nhau trong một hoạt động thể thao hào hứng."
  },
  {
    "id": 54,
    "word": "exciting",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪksˈaɪtɪŋ/",
    "meaning": "hào hứng",
    "ex1": "This sports activity is exciting for students and families.",
    "ex1_vi": "Hoạt động thể thao này hào hứng đối với học sinh và gia đình."
  },
  {
    "id": 55,
    "word": "activities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/æktˈɪvʌtiz/",
    "meaning": "hoạt động",
    "ex1": "Students learn about activities during regular sports activities.",
    "ex1_vi": "Học sinh học về hoạt động trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 56,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌɡˈɛðɝ/",
    "meaning": "cùng nhau",
    "ex1": "Students together practice sports during weekly school activities.",
    "ex1_vi": "Học sinh cùng nhau luyện tập thể thao trong các hoạt động hằng tuần ở trường."
  },
  {
    "id": 57,
    "word": "next",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈɛkst/",
    "meaning": "tiếp theo",
    "ex1": "Next weekend, we are going to join another competition.",
    "ex1_vi": "Cuối tuần tới, chúng tôi sẽ tham gia một cuộc thi khác."
  },
  {
    "id": 58,
    "word": "month",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌnθ/",
    "meaning": "tháng",
    "ex1": "Next month, I am going to join a swimming club.",
    "ex1_vi": "Tháng tới, tôi sẽ tham gia một câu lạc bộ bơi lội."
  },
  {
    "id": 59,
    "word": "class",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈæs/",
    "meaning": "lớp",
    "ex1": "Last Saturday, our team played against another class.",
    "ex1_vi": "Thứ Bảy tuần trước, đội của chúng tôi thi đấu với một lớp khác."
  },
  {
    "id": 60,
    "word": "going",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/ɡˈoʊɪŋ/",
    "meaning": "sắp; đang",
    "ex1": "Next weekend, we are going to join another competition.",
    "ex1_vi": "Cuối tuần tới, chúng tôi sẽ tham gia một cuộc thi khác."
  },
  {
    "id": 61,
    "word": "another",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ʌnˈʌðɝ/",
    "meaning": "khác",
    "ex1": "Students discuss another during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về khác trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 62,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "Everyone should exercise every day to stay healthy and active.",
    "ex1_vi": "Mọi người nên tập thể dục mỗi ngày để luôn khỏe mạnh và năng động."
  },
  {
    "id": 63,
    "word": "will",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/wˈɪl/",
    "meaning": "sẽ",
    "ex1": "Our team will practice again before the next competition.",
    "ex1_vi": "Đội chúng tôi sẽ luyện tập lại trước cuộc thi tiếp theo."
  },
  {
    "id": 64,
    "word": "join",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dʒˈɔɪn/",
    "meaning": "tham gia",
    "ex1": "Students can join during regular sports practice after school.",
    "ex1_vi": "Học sinh có thể tham gia trong buổi luyện tập thể thao thường xuyên sau giờ học."
  },
  {
    "id": 65,
    "word": "team",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈim/",
    "meaning": "đội",
    "ex1": "Students learn about team during regular sports activities.",
    "ex1_vi": "Học sinh học về đội trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 66,
    "word": "again",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌɡˈɛn/",
    "meaning": "lại",
    "ex1": "Students again practice sports during weekly school activities.",
    "ex1_vi": "Học sinh lại luyện tập thể thao trong các hoạt động hằng tuần ở trường."
  },
  {
    "id": 67,
    "word": "if",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɪf/",
    "meaning": "nếu",
    "ex1": "If the weather is nice, we will play outside.",
    "ex1_vi": "Nếu thời tiết đẹp, chúng tôi sẽ chơi bên ngoài."
  },
  {
    "id": 68,
    "word": "weather",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɛðɝ/",
    "meaning": "thời tiết",
    "ex1": "If the weather is nice, we will play outside.",
    "ex1_vi": "Nếu thời tiết đẹp, chúng tôi sẽ chơi bên ngoài."
  },
  {
    "id": 69,
    "word": "nice",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈaɪs/",
    "meaning": "đẹp; dễ chịu",
    "ex1": "Students discuss nice during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về đẹp; dễ chịu trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 70,
    "word": "outside",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈaʊtsˈaɪd/",
    "meaning": "bên ngoài",
    "ex1": "Students discuss outside during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về bên ngoài trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 71,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "Everyone should play fairly and respect every player.",
    "ex1_vi": "Mọi người nên chơi công bằng và tôn trọng mọi cầu thủ."
  },
  {
    "id": 72,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɝi/",
    "meaning": "mỗi",
    "ex1": "Students discuss every during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về mỗi trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 73,
    "word": "stay",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈeɪ/",
    "meaning": "giữ; ở",
    "ex1": "Students discuss stay during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về giữ; ở trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 74,
    "word": "active",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈæktɪv/",
    "meaning": "năng động",
    "ex1": "Students discuss active during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về năng động trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 75,
    "word": "one",
    "type": "number/pronoun",
    "cat": "adj",
    "phonetic": "/wˈʌn/",
    "meaning": "một",
    "ex1": "Football is one of the most popular sports in the world.",
    "ex1_vi": "Bóng đá là một trong những môn thể thao phổ biến nhất trên thế giới."
  },
  {
    "id": 76,
    "word": "most",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈoʊst/",
    "meaning": "nhất",
    "ex1": "Football is one of the most popular sports in the world.",
    "ex1_vi": "Bóng đá là một trong những môn thể thao phổ biến nhất trên thế giới."
  },
  {
    "id": 77,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "Students discuss popular during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về phổ biến trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 78,
    "word": "world",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝld/",
    "meaning": "thế giới",
    "ex1": "Students discuss world during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về thế giới trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 79,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "It keeps the body strong and helps the heart stay healthy.",
    "ex1_vi": "Nó giúp cơ thể khỏe mạnh và giúp tim luôn khỏe."
  },
  {
    "id": 80,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "My friends and I usually practice twice a week.",
    "ex1_vi": "Bạn bè tôi và tôi thường luyện tập hai lần một tuần."
  },
  {
    "id": 81,
    "word": "practice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈæktʌs/",
    "meaning": "luyện tập",
    "ex1": "Students discuss practice during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về luyện tập trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 82,
    "word": "twice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/twˈaɪs/",
    "meaning": "hai lần",
    "ex1": "Students discuss twice during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về hai lần trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 83,
    "word": "week",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈik/",
    "meaning": "tuần",
    "ex1": "Students discuss week during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về tuần trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 84,
    "word": "training",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈeɪnɪŋ/",
    "meaning": "đang tập luyện",
    "ex1": "We are training on the school field now.",
    "ex1_vi": "Chúng tôi đang tập trên sân trường lúc này."
  },
  {
    "id": 85,
    "word": "field",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈild/",
    "meaning": "sân",
    "ex1": "Students discuss field during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về sân trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 86,
    "word": "saturday",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈætɝdi/",
    "meaning": "Thứ Bảy",
    "ex1": "Students discuss saturday during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về Thứ Bảy trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 87,
    "word": "against",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ʌɡˈɛnst/",
    "meaning": "đối đầu; chống lại",
    "ex1": "Students discuss against during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về đối đầu; chống lại trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 88,
    "word": "worked",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝkt/",
    "meaning": "đã làm việc",
    "ex1": "We worked together, passed the ball well, and won the match.",
    "ex1_vi": "Chúng tôi phối hợp cùng nhau, chuyền bóng tốt và thắng trận đấu."
  },
  {
    "id": 89,
    "word": "passed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pˈæst/",
    "meaning": "đã chuyền",
    "ex1": "We worked together, passed the ball well, and won the match.",
    "ex1_vi": "Chúng tôi phối hợp cùng nhau, chuyền bóng tốt và thắng trận đấu."
  },
  {
    "id": 90,
    "word": "ball",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɔl/",
    "meaning": "bóng",
    "ex1": "Students discuss ball during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về bóng trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 91,
    "word": "well",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈɛl/",
    "meaning": "tốt",
    "ex1": "Students discuss well during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về tốt trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 92,
    "word": "match",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈætʃ/",
    "meaning": "trận đấu",
    "ex1": "Students discuss match during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về trận đấu trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 93,
    "word": "coach",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈoʊtʃ/",
    "meaning": "huấn luyện viên",
    "ex1": "Students learn about coach during regular sports activities.",
    "ex1_vi": "Học sinh học về huấn luyện viên trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 94,
    "word": "has",
    "type": "verb/auxiliary",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có; trợ động từ",
    "ex1": "Students learn about has during regular sports activities.",
    "ex1_vi": "Học sinh học về có; trợ động từ trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 95,
    "word": "praised",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prˈeɪzd/",
    "meaning": "đã khen",
    "ex1": "We praised together during an exciting sports activity.",
    "ex1_vi": "Chúng tôi đã khen cùng nhau trong một hoạt động thể thao hào hứng."
  },
  {
    "id": 96,
    "word": "teamwork",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈtiːmwɜːrk/",
    "meaning": "tinh thần đồng đội",
    "ex1": "Students learn about teamwork during regular sports activities.",
    "ex1_vi": "Học sinh học về tinh thần đồng đội trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 97,
    "word": "so",
    "type": "conjunction/adverb",
    "cat": "conj",
    "phonetic": "/sˈoʊ/",
    "meaning": "vì vậy",
    "ex1": "We practiced hard, so our coach felt proud.",
    "ex1_vi": "Chúng tôi luyện tập chăm chỉ nên huấn luyện viên cảm thấy tự hào."
  },
  {
    "id": 98,
    "word": "feel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈil/",
    "meaning": "cảm thấy",
    "ex1": "Students can feel during regular sports practice after school.",
    "ex1_vi": "Học sinh có thể cảm thấy trong buổi luyện tập thể thao thường xuyên sau giờ học."
  },
  {
    "id": 99,
    "word": "proud",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/prˈaʊd/",
    "meaning": "tự hào",
    "ex1": "This sports activity is proud for students and families.",
    "ex1_vi": "Hoạt động thể thao này tự hào đối với học sinh và gia đình."
  },
  {
    "id": 100,
    "word": "confident",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɑnfʌdʌnt/",
    "meaning": "tự tin",
    "ex1": "Now I have already become much more confident in the water.",
    "ex1_vi": "Bây giờ tôi đã trở nên tự tin hơn nhiều khi ở dưới nước."
  },
  {
    "id": 101,
    "word": "competition",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˌɑmpʌtˈɪʃʌn/",
    "meaning": "cuộc thi",
    "ex1": "Students discuss competition during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về cuộc thi trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 102,
    "word": "think",
    "type": "verb",
    "cat": "v",
    "phonetic": "/θˈɪŋk/",
    "meaning": "nghĩ",
    "ex1": "Students can think during regular sports practice after school.",
    "ex1_vi": "Học sinh có thể nghĩ trong buổi luyện tập thể thao thường xuyên sau giờ học."
  },
  {
    "id": 103,
    "word": "even",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈivɪn/",
    "meaning": "thậm chí",
    "ex1": "Students even practice sports during weekly school activities.",
    "ex1_vi": "Học sinh thậm chí luyện tập thể thao trong các hoạt động hằng tuần ở trường."
  },
  {
    "id": 104,
    "word": "better",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/bˈɛtɝ/",
    "meaning": "tốt hơn",
    "ex1": "Students better practice sports during weekly school activities.",
    "ex1_vi": "Học sinh tốt hơn luyện tập thể thao trong các hoạt động hằng tuần ở trường."
  },
  {
    "id": 105,
    "word": "keep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈip/",
    "meaning": "tiếp tục; giữ",
    "ex1": "Students discuss keep during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về tiếp tục; giữ trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 106,
    "word": "practicing",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/prˈæktʌsɪŋ/",
    "meaning": "đang luyện tập",
    "ex1": "Students discuss practicing during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về đang luyện tập trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 107,
    "word": "fairly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/fˈɛrli/",
    "meaning": "công bằng",
    "ex1": "Students discuss fairly during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về công bằng trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 108,
    "word": "respect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪspˈɛkt/",
    "meaning": "tôn trọng",
    "ex1": "Students discuss respect during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về tôn trọng trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 109,
    "word": "player",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪɝ/",
    "meaning": "cầu thủ",
    "ex1": "Students discuss player during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về cầu thủ trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 110,
    "word": "swimming",
    "type": "verb",
    "cat": "v",
    "phonetic": "/swˈɪmɪŋ/",
    "meaning": "bơi lội",
    "ex1": "Swimming is a great sport for people of all ages.",
    "ex1_vi": "Bơi lội là một môn thể thao tuyệt vời cho mọi lứa tuổi."
  },
  {
    "id": 111,
    "word": "health",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛlθ/",
    "meaning": "sức khỏe",
    "ex1": "Students learn about health during regular sports activities.",
    "ex1_vi": "Học sinh học về sức khỏe trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 112,
    "word": "great",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈeɪt/",
    "meaning": "tuyệt vời",
    "ex1": "Swimming is a great sport for people of all ages.",
    "ex1_vi": "Bơi lội là một môn thể thao tuyệt vời cho mọi lứa tuổi."
  },
  {
    "id": 113,
    "word": "sport",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈɔrt/",
    "meaning": "môn thể thao",
    "ex1": "Students discuss sport during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về môn thể thao trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 114,
    "word": "all",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɔl/",
    "meaning": "tất cả",
    "ex1": "Students discuss all during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về tất cả trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 115,
    "word": "ages",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈeɪdʒʌz/",
    "meaning": "độ tuổi",
    "ex1": "Students discuss ages during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về độ tuổi trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 116,
    "word": "keeps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈips/",
    "meaning": "giữ",
    "ex1": "It keeps the body strong and helps the heart stay healthy.",
    "ex1_vi": "Nó giúp cơ thể khỏe mạnh và giúp tim luôn khỏe."
  },
  {
    "id": 117,
    "word": "body",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɑdi/",
    "meaning": "cơ thể",
    "ex1": "Students discuss body during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về cơ thể trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 118,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋ/",
    "meaning": "khỏe mạnh",
    "ex1": "Students discuss strong during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về khỏe mạnh trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 119,
    "word": "heart",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɑrt/",
    "meaning": "tim",
    "ex1": "Students discuss heart during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về tim trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 120,
    "word": "learn",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɝn/",
    "meaning": "học",
    "ex1": "Students can learn during regular sports practice after school.",
    "ex1_vi": "Học sinh có thể học trong buổi luyện tập thể thao thường xuyên sau giờ học."
  },
  {
    "id": 121,
    "word": "summer",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈʌmɝ/",
    "meaning": "mùa hè",
    "ex1": "Students learn about summer during regular sports activities.",
    "ex1_vi": "Học sinh học về mùa hè trong các hoạt động thể thao thường xuyên."
  },
  {
    "id": 122,
    "word": "little",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/lˈɪtʌl/",
    "meaning": "nhỏ; em",
    "ex1": "My little brother is swimming happily in the pool now.",
    "ex1_vi": "Em trai tôi đang vui vẻ bơi trong hồ lúc này."
  },
  {
    "id": 123,
    "word": "brother",
    "type": "noun",
    "cat": "n",
    "phonetic": "/brˈʌðɝ/",
    "meaning": "em trai",
    "ex1": "My little brother is swimming happily in the pool now.",
    "ex1_vi": "Em trai tôi đang vui vẻ bơi trong hồ lúc này."
  },
  {
    "id": 124,
    "word": "happily",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/hˈæpʌli/",
    "meaning": "vui vẻ",
    "ex1": "Students discuss happily during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về vui vẻ trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 125,
    "word": "pool",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈul/",
    "meaning": "hồ bơi",
    "ex1": "Students discuss pool during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về hồ bơi trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 126,
    "word": "year",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈɪr/",
    "meaning": "năm",
    "ex1": "Last year, I could not swim well, but I practiced every weekend.",
    "ex1_vi": "Năm ngoái, tôi không thể bơi tốt, nhưng tôi đã luyện tập mỗi cuối tuần."
  },
  {
    "id": 127,
    "word": "could",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈʊd/",
    "meaning": "có thể",
    "ex1": "Last year, I could not swim well, but I practiced every weekend.",
    "ex1_vi": "Năm ngoái, tôi không thể bơi tốt, nhưng tôi đã luyện tập mỗi cuối tuần."
  },
  {
    "id": 128,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "Students discuss not during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về không trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 129,
    "word": "but",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bˈʌt/",
    "meaning": "nhưng",
    "ex1": "Students discuss but during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về nhưng trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 130,
    "word": "practiced",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prˈæktʌst/",
    "meaning": "đã luyện tập",
    "ex1": "Students discuss practiced during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về đã luyện tập trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 131,
    "word": "much",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/mˈʌtʃ/",
    "meaning": "nhiều",
    "ex1": "Students discuss much during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về nhiều trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 132,
    "word": "more",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "hơn; nhiều hơn",
    "ex1": "Students discuss more during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về hơn; nhiều hơn trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 133,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước",
    "ex1": "Students discuss water during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về nước trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 134,
    "word": "teacher",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈitʃɝ/",
    "meaning": "giáo viên",
    "ex1": "My teacher says swimming is safer when we follow the rules carefully.",
    "ex1_vi": "Giáo viên của tôi nói bơi lội an toàn hơn khi chúng ta tuân theo quy tắc cẩn thận."
  },
  {
    "id": 135,
    "word": "says",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛz/",
    "meaning": "nói",
    "ex1": "My teacher says swimming is safer when we follow the rules carefully.",
    "ex1_vi": "Giáo viên của tôi nói bơi lội an toàn hơn khi chúng ta tuân theo quy tắc cẩn thận."
  },
  {
    "id": 136,
    "word": "safer",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪfɝ/",
    "meaning": "an toàn hơn",
    "ex1": "Students discuss safer during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về an toàn hơn trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 137,
    "word": "when",
    "type": "conjunction/adverb",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "Students discuss when during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về khi trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 138,
    "word": "follow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɑloʊ/",
    "meaning": "noi theo; theo",
    "ex1": "Students discuss follow during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về noi theo; theo trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 139,
    "word": "rules",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈulz/",
    "meaning": "quy tắc",
    "ex1": "Students discuss rules during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về quy tắc trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 140,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "Students discuss carefully during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về cẩn thận trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 141,
    "word": "club",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈʌb/",
    "meaning": "câu lạc bộ",
    "ex1": "Next month, I am going to join a swimming club.",
    "ex1_vi": "Tháng tới, tôi sẽ tham gia một câu lạc bộ bơi lội."
  },
  {
    "id": 142,
    "word": "hope",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊp/",
    "meaning": "hy vọng",
    "ex1": "I hope I will improve my skills quickly.",
    "ex1_vi": "Tôi hy vọng mình sẽ cải thiện kỹ năng nhanh chóng."
  },
  {
    "id": 143,
    "word": "improve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪmprˈuv/",
    "meaning": "cải thiện",
    "ex1": "I hope I will improve my skills quickly.",
    "ex1_vi": "Tôi hy vọng mình sẽ cải thiện kỹ năng nhanh chóng."
  },
  {
    "id": 144,
    "word": "skills",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪlz/",
    "meaning": "kỹ năng",
    "ex1": "Students discuss skills during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về kỹ năng trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 145,
    "word": "quickly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kwˈɪkli/",
    "meaning": "nhanh chóng",
    "ex1": "Students discuss quickly during useful sports practice after school.",
    "ex1_vi": "Học sinh thảo luận về nhanh chóng trong buổi luyện tập thể thao hữu ích sau giờ học."
  },
  {
    "id": 146,
    "word": "want",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɑnt/",
    "meaning": "muốn",
    "ex1": "If you want to stay healthy, you should learn to swim safely.",
    "ex1_vi": "Nếu bạn muốn khỏe mạnh, bạn nên học bơi an toàn."
  },
  {
    "id": 147,
    "word": "safely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sˈeɪfli/",
    "meaning": "an toàn",
    "ex1": "If you want to stay healthy, you should learn to swim safely.",
    "ex1_vi": "Nếu bạn muốn khỏe mạnh, bạn nên học bơi an toàn."
  }
];

const newReadingVocabOrder = [
  "why",
  "people",
  "love",
  "sports",
  "many",
  "because",
  "fun",
  "and",
  "healthy",
  "some",
  "play",
  "football",
  "while",
  "others",
  "swim",
  "or",
  "ride",
  "bikes",
  "children",
  "often",
  "after",
  "school",
  "adults",
  "exercise",
  "before",
  "work",
  "look",
  "students",
  "playing",
  "basketball",
  "now",
  "last",
  "weekend",
  "family",
  "joined",
  "festival",
  "played",
  "games",
  "won",
  "small",
  "prizes",
  "met",
  "new",
  "friends",
  "have",
  "already",
  "learned",
  "help",
  "become",
  "stronger",
  "happier",
  "everyone",
  "enjoyed",
  "exciting",
  "activities",
  "together",
  "next",
  "month",
  "class",
  "going",
  "another",
  "day",
  "will",
  "join",
  "team",
  "again",
  "if",
  "weather",
  "nice",
  "outside",
  "should",
  "every",
  "stay",
  "active",
  "one",
  "most",
  "popular",
  "world",
  "helps",
  "usually",
  "practice",
  "twice",
  "week",
  "training",
  "field",
  "saturday",
  "against",
  "worked",
  "passed",
  "ball",
  "well",
  "match",
  "coach",
  "has",
  "praised",
  "teamwork",
  "so",
  "feel",
  "proud",
  "confident",
  "competition",
  "think",
  "even",
  "better",
  "keep",
  "practicing",
  "fairly",
  "respect",
  "player",
  "swimming",
  "health",
  "great",
  "sport",
  "all",
  "ages",
  "keeps",
  "body",
  "strong",
  "heart",
  "learn",
  "summer",
  "little",
  "brother",
  "happily",
  "pool",
  "year",
  "could",
  "not",
  "but",
  "practiced",
  "much",
  "more",
  "water",
  "teacher",
  "says",
  "safer",
  "when",
  "follow",
  "rules",
  "carefully",
  "club",
  "hope",
  "improve",
  "skills",
  "quickly",
  "want",
  "safely"
];
