const newEssayData = [
  {
    "text": "Chapter 1. The Bed\nA bed is the most important piece of furniture in a bedroom. It usually has a frame, a mattress, pillows, and a blanket. Beds come in different sizes, such as single, double, queen, and king size.\n\nPeople use a bed to sleep, rest, or relax after a long day. A comfortable mattress can help the body feel better and improve sleep quality.\n\nThe bed should be kept clean and tidy. Changing the bedsheets regularly makes the sleeping area fresh, comfortable, and healthy.",
    "vi": "Chương 1. Chiếc giường\nGiường là món đồ nội thất quan trọng nhất trong phòng ngủ. Giường thường có khung, nệm, gối và chăn. Giường có nhiều kích cỡ khác nhau như giường đơn, giường đôi, cỡ queen và cỡ king.\n\nMọi người dùng giường để ngủ, nghỉ ngơi hoặc thư giãn sau một ngày dài. Một tấm nệm thoải mái có thể giúp cơ thể cảm thấy dễ chịu hơn và cải thiện chất lượng giấc ngủ.\n\nGiường nên được giữ sạch sẽ và gọn gàng. Thay ga giường thường xuyên giúp khu vực ngủ luôn tươi mới, thoải mái và lành mạnh."
  },
  {
    "text": "Chapter 2. The Pillow\nA pillow is a soft object placed under the head while sleeping. It is usually filled with cotton, feathers, foam, or other soft materials. Pillows can have different shapes and sizes.\n\nA good pillow supports the head and neck. It helps people sleep comfortably and may prevent neck pain. Some people also use extra pillows to support their back or legs.\n\nPillowcases should be washed regularly because they can collect dust and sweat. A clean pillow makes the bed more pleasant and comfortable.",
    "vi": "Chương 2. Chiếc gối\nGối là một vật mềm được đặt dưới đầu khi ngủ. Gối thường được nhồi bằng bông, lông vũ, mút xốp hoặc các vật liệu mềm khác. Gối có thể có nhiều hình dạng và kích cỡ khác nhau.\n\nMột chiếc gối tốt nâng đỡ đầu và cổ. Nó giúp mọi người ngủ thoải mái và có thể ngăn đau cổ. Một số người còn dùng thêm gối để đỡ lưng hoặc chân.\n\nVỏ gối nên được giặt thường xuyên vì chúng có thể tích tụ bụi và mồ hôi. Một chiếc gối sạch làm cho giường dễ chịu và thoải mái hơn."
  },
  {
    "text": "Chapter 3. The Blanket\nA blanket is a large piece of soft fabric used to keep the body warm. It is usually placed on top of the bedsheet. Blankets can be made from cotton, wool, or other materials.\n\nPeople use thick blankets during cold weather and light blankets during warm seasons. Some blankets have beautiful colors, patterns, or pictures that decorate the bedroom.\n\nA blanket should be washed and dried carefully. Keeping it clean helps people feel warm, relaxed, and comfortable while sleeping.",
    "vi": "Chương 3. Chiếc chăn\nChăn là một tấm vải mềm lớn được dùng để giữ ấm cơ thể. Chăn thường được đặt trên ga giường. Chăn có thể được làm từ bông, len hoặc các vật liệu khác.\n\nMọi người dùng chăn dày trong thời tiết lạnh và chăn nhẹ vào mùa ấm. Một số chiếc chăn có màu sắc, hoa văn hoặc hình ảnh đẹp giúp trang trí phòng ngủ.\n\nChăn nên được giặt và phơi khô cẩn thận. Giữ chăn sạch giúp mọi người cảm thấy ấm áp, thư giãn và thoải mái khi ngủ."
  }
];
