const lessonVocabularyWords = [
  "mirror",
  "object",
  "smooth",
  "surface",
  "reflects",
  "images",
  "bedroom",
  "mirrors",
  "may",
  "attached",
  "wardrobe",
  "placed",
  "dressing",
  "table",
  "or",
  "hung",
  "wall",
  "people",
  "use",
  "when",
  "getting",
  "dressed",
  "brushing",
  "hair",
  "checking",
  "appearance",
  "large",
  "can",
  "also",
  "make",
  "small",
  "look",
  "brighter",
  "and",
  "more",
  "spacious",
  "should",
  "cleaned",
  "regularly",
  "because",
  "dust",
  "marks",
  "appear",
  "clean",
  "gives",
  "clear",
  "reflection",
  "improves",
  "room’s",
  "alarm",
  "clock",
  "device",
  "tells",
  "time",
  "makes",
  "sound",
  "chosen",
  "hour",
  "digital",
  "have",
  "traditional",
  "hands",
  "wake",
  "up",
  "school",
  "work",
  "other",
  "activities",
  "some",
  "modern",
  "clocks",
  "radios",
  "lights",
  "different",
  "sounds",
  "usually",
  "near",
  "bed",
  "loud",
  "enough",
  "person",
  "but",
  "not",
  "too",
  "disturbing",
  "unpleasant",
  "curtains",
  "pieces",
  "fabric",
  "cover",
  "windows",
  "available",
  "many",
  "colors",
  "patterns",
  "lengths",
  "materials",
  "provide",
  "privacy",
  "control",
  "amount",
  "sunlight",
  "entering",
  "room",
  "thick",
  "block",
  "strong",
  "light",
  "while",
  "thin",
  "allow",
  "gentle",
  "natural",
  "enter",
  "attractive",
  "washed",
  "occasionally",
  "remove",
  "keep",
  "fresh",
  "bookshelf",
  "piece",
  "furniture",
  "used",
  "storing",
  "books",
  "magazines",
  "objects",
  "tall",
  "short",
  "wide",
  "narrow",
  "keeps",
  "reading",
  "organized",
  "easy",
  "find",
  "place",
  "photographs",
  "plants",
  "decorations",
  "shelves",
  "arranged",
  "neatly",
  "so",
  "shelf",
  "does",
  "crowded",
  "useful",
  "relaxing"
];

const newVocabData = [
  {
    "id": 1,
    "word": "mirror",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɪrɝ/",
    "meaning": "gương",
    "ex1": "A mirror is an object with a smooth surface that reflects images.",
    "ex1_vi": "Gương là một vật có bề mặt nhẵn phản chiếu hình ảnh."
  },
  {
    "id": 2,
    "word": "object",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɑbdʒɛkt/",
    "meaning": "vật",
    "ex1": "A mirror is an object with a smooth surface that reflects images.",
    "ex1_vi": "Gương là một vật có bề mặt nhẵn phản chiếu hình ảnh."
  },
  {
    "id": 3,
    "word": "smooth",
    "type": "noun",
    "cat": "n",
    "phonetic": "/smˈuð/",
    "meaning": "nhẵn",
    "ex1": "People discuss smooth while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về nhẵn khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 4,
    "word": "surface",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɝfʌs/",
    "meaning": "bề mặt",
    "ex1": "People discuss surface while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về bề mặt khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 5,
    "word": "reflects",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rɪflˈɛkts/",
    "meaning": "phản chiếu",
    "ex1": "People discuss reflects while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về phản chiếu khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 6,
    "word": "images",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɪmʌdʒʌz/",
    "meaning": "hình ảnh",
    "ex1": "People discuss images while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về hình ảnh khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 7,
    "word": "bedroom",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɛdrˌum/",
    "meaning": "phòng ngủ",
    "ex1": "Curtains also make the bedroom look more attractive.",
    "ex1_vi": "Rèm cửa cũng làm phòng ngủ trông hấp dẫn hơn."
  },
  {
    "id": 8,
    "word": "mirrors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɪrɝz/",
    "meaning": "gương",
    "ex1": "Families arrange mirrors carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp gương cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 9,
    "word": "may",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈeɪ/",
    "meaning": "có thể",
    "ex1": "It may be tall, short, wide, or narrow.",
    "ex1_vi": "Kệ có thể cao, thấp, rộng hoặc hẹp."
  },
  {
    "id": 10,
    "word": "attached",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌtˈætʃt/",
    "meaning": "được gắn",
    "ex1": "Families can attached this bedroom item safely every day.",
    "ex1_vi": "Các gia đình có thể được gắn vật dụng phòng ngủ này an toàn mỗi ngày."
  },
  {
    "id": 11,
    "word": "wardrobe",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔrdrˌoʊb/",
    "meaning": "tủ quần áo",
    "ex1": "Families arrange wardrobe carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp tủ quần áo cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 12,
    "word": "placed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪst/",
    "meaning": "được đặt",
    "ex1": "The clock is usually placed near the bed.",
    "ex1_vi": "Đồng hồ thường được đặt gần giường."
  },
  {
    "id": 13,
    "word": "dressing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/drˈɛsɪŋ/",
    "meaning": "trang điểm",
    "ex1": "Families can dressing this bedroom item safely every day.",
    "ex1_vi": "Các gia đình có thể trang điểm vật dụng phòng ngủ này an toàn mỗi ngày."
  },
  {
    "id": 14,
    "word": "table",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪbʌl/",
    "meaning": "bàn",
    "ex1": "Families arrange table carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp bàn cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 15,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "It may be tall, short, wide, or narrow.",
    "ex1_vi": "Kệ có thể cao, thấp, rộng hoặc hẹp."
  },
  {
    "id": 16,
    "word": "hung",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/hˈʌŋ/",
    "meaning": "được treo",
    "ex1": "People keep hung clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ được treo sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 17,
    "word": "wall",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔl/",
    "meaning": "tường",
    "ex1": "Families arrange wall carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp tường cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 18,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "Some people also place photographs, small plants, or decorations on its shelves.",
    "ex1_vi": "Một số người còn đặt ảnh, cây nhỏ hoặc đồ trang trí trên các kệ."
  },
  {
    "id": 19,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "Families can use this bedroom item safely every day.",
    "ex1_vi": "Các gia đình có thể sử dụng vật dụng phòng ngủ này an toàn mỗi ngày."
  },
  {
    "id": 20,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "The lamp should be off when nobody needs it.",
    "ex1_vi": "Đèn nên tắt khi không ai cần dùng."
  },
  {
    "id": 21,
    "word": "getting",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɛtɪŋ/",
    "meaning": "việc",
    "ex1": "A bedroom can include getting for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có việc để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 22,
    "word": "dressed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/drˈɛst/",
    "meaning": "mặc quần áo",
    "ex1": "Families can dressed this bedroom item safely every day.",
    "ex1_vi": "Các gia đình có thể mặc quần áo vật dụng phòng ngủ này an toàn mỗi ngày."
  },
  {
    "id": 23,
    "word": "brushing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/brˈʌʃɪŋ/",
    "meaning": "chải",
    "ex1": "People often brushing bedroom furniture before going to sleep.",
    "ex1_vi": "Mọi người thường chải đồ nội thất phòng ngủ trước khi đi ngủ."
  },
  {
    "id": 24,
    "word": "hair",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛr/",
    "meaning": "tóc",
    "ex1": "A bedroom can include hair for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có tóc để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 25,
    "word": "checking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈɛkɪŋ/",
    "meaning": "kiểm tra",
    "ex1": "Families can checking this bedroom item safely every day.",
    "ex1_vi": "Các gia đình có thể kiểm tra vật dụng phòng ngủ này an toàn mỗi ngày."
  },
  {
    "id": 26,
    "word": "appearance",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌpˈɪrʌns/",
    "meaning": "vẻ ngoài",
    "ex1": "Families arrange appearance carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp vẻ ngoài cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 27,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒ/",
    "meaning": "lớn",
    "ex1": "This bedroom item can feel large during daily use.",
    "ex1_vi": "Vật dụng phòng ngủ này có thể cảm thấy lớn khi sử dụng hằng ngày."
  },
  {
    "id": 28,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "A comfortable bed can improve sleep quality at night.",
    "ex1_vi": "Một chiếc giường thoải mái có thể cải thiện chất lượng giấc ngủ vào ban đêm."
  },
  {
    "id": 29,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "Curtains also make the bedroom look more attractive.",
    "ex1_vi": "Rèm cửa cũng làm phòng ngủ trông hấp dẫn hơn."
  },
  {
    "id": 30,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm cho",
    "ex1": "People discuss make while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về làm cho khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 31,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "Some people also place photographs, small plants, or decorations on its shelves.",
    "ex1_vi": "Một số người còn đặt ảnh, cây nhỏ hoặc đồ trang trí trên các kệ."
  },
  {
    "id": 32,
    "word": "look",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊk/",
    "meaning": "trông",
    "ex1": "People discuss look while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về trông khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 33,
    "word": "brighter",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/brˈaɪtɝ/",
    "meaning": "sáng hơn",
    "ex1": "This bedroom item can feel brighter during daily use.",
    "ex1_vi": "Vật dụng phòng ngủ này có thể cảm thấy sáng hơn khi sử dụng hằng ngày."
  },
  {
    "id": 34,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "They are available in many colors, patterns, lengths, and materials.",
    "ex1_vi": "Chúng có nhiều màu sắc, hoa văn, độ dài và chất liệu."
  },
  {
    "id": 35,
    "word": "more",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "nhiều hơn",
    "ex1": "People discuss more while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về nhiều hơn khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 36,
    "word": "spacious",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/spˈeɪʃʌs/",
    "meaning": "rộng rãi",
    "ex1": "This bedroom item can feel spacious during daily use.",
    "ex1_vi": "Vật dụng phòng ngủ này có thể cảm thấy rộng rãi khi sử dụng hằng ngày."
  },
  {
    "id": 37,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "Bedroom furniture should be kept clean and tidy.",
    "ex1_vi": "Đồ nội thất phòng ngủ nên được giữ sạch sẽ và gọn gàng."
  },
  {
    "id": 38,
    "word": "cleaned",
    "type": "verb",
    "cat": "v",
    "phonetic": "/klˈind/",
    "meaning": "được làm sạch",
    "ex1": "People often cleaned bedroom furniture before going to sleep.",
    "ex1_vi": "Mọi người thường được làm sạch đồ nội thất phòng ngủ trước khi đi ngủ."
  },
  {
    "id": 39,
    "word": "regularly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/rˈɛɡjʌlɝli/",
    "meaning": "thường xuyên",
    "ex1": "People regularly clean bedroom items during regular home care.",
    "ex1_vi": "Mọi người thường xuyên làm sạch vật dụng phòng ngủ khi chăm sóc nhà cửa thường xuyên."
  },
  {
    "id": 40,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "Pillowcases need washing because they collect dust and sweat.",
    "ex1_vi": "Vỏ gối cần được giặt vì chúng tích tụ bụi và mồ hôi."
  },
  {
    "id": 41,
    "word": "dust",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈʌst/",
    "meaning": "bụi",
    "ex1": "Families arrange dust carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp bụi cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 42,
    "word": "marks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɑrks/",
    "meaning": "vết bẩn",
    "ex1": "A bedroom can include marks for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có vết bẩn để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 43,
    "word": "appear",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌpˈɪr/",
    "meaning": "xuất hiện",
    "ex1": "Families can appear this bedroom item safely every day.",
    "ex1_vi": "Các gia đình có thể xuất hiện vật dụng phòng ngủ này an toàn mỗi ngày."
  },
  {
    "id": 44,
    "word": "clean",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈin/",
    "meaning": "sạch",
    "ex1": "People prefer clean bedroom items for comfortable daily use.",
    "ex1_vi": "Mọi người thích các vật dụng phòng ngủ sạch để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 45,
    "word": "gives",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvz/",
    "meaning": "cho",
    "ex1": "People gives bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người cho các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 46,
    "word": "clear",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈɪr/",
    "meaning": "rõ ràng",
    "ex1": "A bedroom looks clear when furniture is well arranged.",
    "ex1_vi": "Một phòng ngủ trông rõ ràng khi đồ nội thất được sắp xếp tốt."
  },
  {
    "id": 47,
    "word": "reflection",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rɪflˈɛkʃʌn/",
    "meaning": "hình phản chiếu",
    "ex1": "Families arrange reflection carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp hình phản chiếu cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 48,
    "word": "improves",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪmprˈuvz/",
    "meaning": "cải thiện",
    "ex1": "People improves bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người cải thiện các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 49,
    "word": "room’s",
    "type": "possessive noun",
    "cat": "n",
    "phonetic": "/ruːmz/",
    "meaning": "của căn phòng",
    "ex1": "People keep room’s clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ của căn phòng sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 50,
    "word": "alarm",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌlˈɑrm/",
    "meaning": "báo thức",
    "ex1": "Some modern alarm clocks also have radios, lights, or different alarm sounds.",
    "ex1_vi": "Một số đồng hồ báo thức hiện đại còn có radio, đèn hoặc nhiều âm báo khác nhau."
  },
  {
    "id": 51,
    "word": "clock",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈɑk/",
    "meaning": "đồng hồ",
    "ex1": "The clock is usually placed near the bed.",
    "ex1_vi": "Đồng hồ thường được đặt gần giường."
  },
  {
    "id": 52,
    "word": "device",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪvˈaɪs/",
    "meaning": "thiết bị",
    "ex1": "People keep device clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ thiết bị sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 53,
    "word": "tells",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛlz/",
    "meaning": "cho biết",
    "ex1": "Families arrange tells carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp cho biết cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 54,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "A bedroom can include time for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có thời gian để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 55,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm cho",
    "ex1": "Families can makes this bedroom item safely every day.",
    "ex1_vi": "Các gia đình có thể làm cho vật dụng phòng ngủ này an toàn mỗi ngày."
  },
  {
    "id": 56,
    "word": "sound",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaʊnd/",
    "meaning": "âm thanh",
    "ex1": "Families arrange sound carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp âm thanh cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 57,
    "word": "chosen",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈoʊzʌn/",
    "meaning": "được chọn",
    "ex1": "A bedroom can include chosen for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có được chọn để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 58,
    "word": "hour",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaʊɝ/",
    "meaning": "giờ",
    "ex1": "People keep hour clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ giờ sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 59,
    "word": "digital",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪdʒʌtʌl/",
    "meaning": "điện tử",
    "ex1": "It may be digital or have traditional clock hands.",
    "ex1_vi": "Nó có thể là loại điện tử hoặc có kim đồng hồ truyền thống."
  },
  {
    "id": 60,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có",
    "ex1": "It may be digital or have traditional clock hands.",
    "ex1_vi": "Nó có thể là loại điện tử hoặc có kim đồng hồ truyền thống."
  },
  {
    "id": 61,
    "word": "traditional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trʌdˈɪʃʌnʌl/",
    "meaning": "truyền thống",
    "ex1": "People discuss traditional while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về truyền thống khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 62,
    "word": "hands",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈændz/",
    "meaning": "kim đồng hồ",
    "ex1": "People discuss hands while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về kim đồng hồ khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 63,
    "word": "wake",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈeɪk/",
    "meaning": "đánh thức",
    "ex1": "People wake bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người đánh thức các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 64,
    "word": "up",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈʌp/",
    "meaning": "dậy",
    "ex1": "Families up arrange bedroom furniture to keep things tidy.",
    "ex1_vi": "Các gia đình dậy sắp xếp đồ nội thất phòng ngủ để giữ mọi thứ gọn gàng."
  },
  {
    "id": 65,
    "word": "school",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈul/",
    "meaning": "trường học",
    "ex1": "Families arrange school carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp trường học cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 66,
    "word": "work",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝk/",
    "meaning": "công việc",
    "ex1": "People work bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người công việc các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 67,
    "word": "other",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈʌðɝ/",
    "meaning": "khác",
    "ex1": "A bedroom looks other when furniture is well arranged.",
    "ex1_vi": "Một phòng ngủ trông khác khi đồ nội thất được sắp xếp tốt."
  },
  {
    "id": 68,
    "word": "activities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/æktˈɪvʌtiz/",
    "meaning": "hoạt động",
    "ex1": "Families arrange activities carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp hoạt động cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 69,
    "word": "some",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌm/",
    "meaning": "một số",
    "ex1": "Some modern alarm clocks also have radios, lights, or different alarm sounds.",
    "ex1_vi": "Một số đồng hồ báo thức hiện đại còn có radio, đèn hoặc nhiều âm báo khác nhau."
  },
  {
    "id": 70,
    "word": "modern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈɑdɝn/",
    "meaning": "hiện đại",
    "ex1": "People discuss modern while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về hiện đại khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 71,
    "word": "clocks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈɑks/",
    "meaning": "đồng hồ",
    "ex1": "People discuss clocks while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về đồng hồ khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 72,
    "word": "radios",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈeɪdiˌoʊz/",
    "meaning": "radio",
    "ex1": "People discuss radios while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về radio khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 73,
    "word": "lights",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪts/",
    "meaning": "đèn",
    "ex1": "People discuss lights while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về đèn khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 74,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "People discuss different while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về khác nhau khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 75,
    "word": "sounds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaʊndz/",
    "meaning": "âm thanh",
    "ex1": "People discuss sounds while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về âm thanh khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 76,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "People discuss usually while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về thường khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 77,
    "word": "near",
    "type": "preposition/adverb",
    "cat": "adv",
    "phonetic": "/nˈɪr/",
    "meaning": "gần",
    "ex1": "People discuss near while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về gần khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 78,
    "word": "bed",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɛd/",
    "meaning": "giường",
    "ex1": "People discuss bed while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về giường khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 79,
    "word": "loud",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈaʊd/",
    "meaning": "to",
    "ex1": "A bedroom looks loud when furniture is well arranged.",
    "ex1_vi": "Một phòng ngủ trông to khi đồ nội thất được sắp xếp tốt."
  },
  {
    "id": 80,
    "word": "enough",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/ɪnˈʌf/",
    "meaning": "đủ",
    "ex1": "Enough bedroom items help people feel comfortable at home.",
    "ex1_vi": "Đủ vật dụng phòng ngủ giúp mọi người cảm thấy thoải mái ở nhà."
  },
  {
    "id": 81,
    "word": "person",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɝsʌn/",
    "meaning": "người",
    "ex1": "A bedroom can include person for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có người để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 82,
    "word": "but",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bˈʌt/",
    "meaning": "nhưng",
    "ex1": "The alarm should be loud but not unpleasant.",
    "ex1_vi": "Âm báo nên to nhưng không gây khó chịu."
  },
  {
    "id": 83,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "A tidy shelf does not look crowded or messy.",
    "ex1_vi": "Một chiếc kệ gọn gàng không trông chật chội hay lộn xộn."
  },
  {
    "id": 84,
    "word": "too",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tˈu/",
    "meaning": "quá",
    "ex1": "People too clean bedroom items during regular home care.",
    "ex1_vi": "Mọi người quá làm sạch vật dụng phòng ngủ khi chăm sóc nhà cửa thường xuyên."
  },
  {
    "id": 85,
    "word": "disturbing",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dɪstˈɝbɪŋ/",
    "meaning": "gây khó chịu",
    "ex1": "A bedroom looks disturbing when furniture is well arranged.",
    "ex1_vi": "Một phòng ngủ trông gây khó chịu khi đồ nội thất được sắp xếp tốt."
  },
  {
    "id": 86,
    "word": "unpleasant",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌnplˈɛzʌnt/",
    "meaning": "khó chịu",
    "ex1": "People prefer unpleasant bedroom items for comfortable daily use.",
    "ex1_vi": "Mọi người thích các vật dụng phòng ngủ khó chịu để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 87,
    "word": "curtains",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɝtʌnz/",
    "meaning": "rèm cửa",
    "ex1": "People discuss curtains while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về rèm cửa khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 88,
    "word": "pieces",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈisʌz/",
    "meaning": "tấm; mảnh",
    "ex1": "Curtains are pieces of fabric that cover bedroom windows.",
    "ex1_vi": "Rèm cửa là những tấm vải che cửa sổ phòng ngủ."
  },
  {
    "id": 89,
    "word": "fabric",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæbrɪk/",
    "meaning": "vải",
    "ex1": "Curtains are pieces of fabric that cover bedroom windows.",
    "ex1_vi": "Rèm cửa là những tấm vải che cửa sổ phòng ngủ."
  },
  {
    "id": 90,
    "word": "cover",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌvɝ/",
    "meaning": "che",
    "ex1": "People discuss cover while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về che khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 91,
    "word": "windows",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɪndoʊz/",
    "meaning": "cửa sổ",
    "ex1": "People discuss windows while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về cửa sổ khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 92,
    "word": "available",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌvˈeɪlʌbʌl/",
    "meaning": "có sẵn",
    "ex1": "They are available in many colors, patterns, lengths, and materials.",
    "ex1_vi": "Chúng có nhiều màu sắc, hoa văn, độ dài và chất liệu."
  },
  {
    "id": 93,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "People discuss many while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về nhiều khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 94,
    "word": "colors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌlɝz/",
    "meaning": "màu sắc",
    "ex1": "People discuss colors while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về màu sắc khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 95,
    "word": "patterns",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈætɝnz/",
    "meaning": "hoa văn",
    "ex1": "People discuss patterns while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về hoa văn khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 96,
    "word": "lengths",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɛŋkθs/",
    "meaning": "độ dài",
    "ex1": "People discuss lengths while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về độ dài khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 97,
    "word": "materials",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mʌtˈɪriʌlz/",
    "meaning": "vật liệu",
    "ex1": "People discuss materials while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về vật liệu khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 98,
    "word": "provide",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌvˈaɪd/",
    "meaning": "cung cấp",
    "ex1": "Curtains provide privacy and control the amount of sunlight entering the room.",
    "ex1_vi": "Rèm cửa tạo sự riêng tư và kiểm soát lượng ánh sáng mặt trời đi vào phòng."
  },
  {
    "id": 99,
    "word": "privacy",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈaɪvʌsi/",
    "meaning": "sự riêng tư",
    "ex1": "Curtains provide privacy and control the amount of sunlight entering the room.",
    "ex1_vi": "Rèm cửa tạo sự riêng tư và kiểm soát lượng ánh sáng mặt trời đi vào phòng."
  },
  {
    "id": 100,
    "word": "control",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntrˈoʊl/",
    "meaning": "kiểm soát",
    "ex1": "People discuss control while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về kiểm soát khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 101,
    "word": "amount",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌmˈaʊnt/",
    "meaning": "lượng",
    "ex1": "People discuss amount while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về lượng khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 102,
    "word": "sunlight",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈʌnlˌaɪt/",
    "meaning": "ánh sáng mặt trời",
    "ex1": "People discuss sunlight while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về ánh sáng mặt trời khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 103,
    "word": "entering",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɛntɝɪŋ/",
    "meaning": "đi vào",
    "ex1": "People discuss entering while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về đi vào khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 104,
    "word": "room",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈum/",
    "meaning": "phòng",
    "ex1": "People discuss room while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về phòng khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 105,
    "word": "thick",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈɪk/",
    "meaning": "dày",
    "ex1": "A bedroom can include thick for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có dày để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 106,
    "word": "block",
    "type": "noun",
    "cat": "n",
    "phonetic": "/blˈɑk/",
    "meaning": "chặn",
    "ex1": "People keep block clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ chặn sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 107,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋ/",
    "meaning": "mạnh",
    "ex1": "People prefer strong bedroom items for comfortable daily use.",
    "ex1_vi": "Mọi người thích các vật dụng phòng ngủ mạnh để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 108,
    "word": "light",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈaɪt/",
    "meaning": "nhẹ; ánh sáng",
    "ex1": "This bedroom item can feel light during daily use.",
    "ex1_vi": "Vật dụng phòng ngủ này có thể cảm thấy nhẹ; ánh sáng khi sử dụng hằng ngày."
  },
  {
    "id": 109,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "People use soft pillows while sleeping at night.",
    "ex1_vi": "Mọi người dùng gối mềm trong khi ngủ vào ban đêm."
  },
  {
    "id": 110,
    "word": "thin",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈɪn/",
    "meaning": "mỏng",
    "ex1": "Families arrange thin carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp mỏng cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 111,
    "word": "allow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌlˈaʊ/",
    "meaning": "cho phép",
    "ex1": "People allow bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người cho phép các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 112,
    "word": "gentle",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈɛntʌl/",
    "meaning": "dịu",
    "ex1": "A bedroom looks gentle when furniture is well arranged.",
    "ex1_vi": "Một phòng ngủ trông dịu khi đồ nội thất được sắp xếp tốt."
  },
  {
    "id": 113,
    "word": "natural",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈætʃɝʌl/",
    "meaning": "tự nhiên",
    "ex1": "People prefer natural bedroom items for comfortable daily use.",
    "ex1_vi": "Mọi người thích các vật dụng phòng ngủ tự nhiên để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 114,
    "word": "enter",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɛntɝ/",
    "meaning": "đi vào",
    "ex1": "People enter bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người đi vào các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 115,
    "word": "attractive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌtrˈæktɪv/",
    "meaning": "hấp dẫn",
    "ex1": "People discuss attractive while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về hấp dẫn khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 116,
    "word": "washed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɑʃt/",
    "meaning": "được giặt",
    "ex1": "People often washed bedroom furniture before going to sleep.",
    "ex1_vi": "Mọi người thường được giặt đồ nội thất phòng ngủ trước khi đi ngủ."
  },
  {
    "id": 117,
    "word": "occasionally",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌkˈeɪʒʌnʌli/",
    "meaning": "thỉnh thoảng",
    "ex1": "People occasionally clean bedroom items during regular home care.",
    "ex1_vi": "Mọi người thỉnh thoảng làm sạch vật dụng phòng ngủ khi chăm sóc nhà cửa thường xuyên."
  },
  {
    "id": 118,
    "word": "remove",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rimˈuv/",
    "meaning": "loại bỏ",
    "ex1": "Families can remove this bedroom item safely every day.",
    "ex1_vi": "Các gia đình có thể loại bỏ vật dụng phòng ngủ này an toàn mỗi ngày."
  },
  {
    "id": 119,
    "word": "keep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈip/",
    "meaning": "giữ",
    "ex1": "People often keep bedroom furniture before going to sleep.",
    "ex1_vi": "Mọi người thường giữ đồ nội thất phòng ngủ trước khi đi ngủ."
  },
  {
    "id": 120,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi mới",
    "ex1": "This bedroom item can feel fresh during daily use.",
    "ex1_vi": "Vật dụng phòng ngủ này có thể cảm thấy tươi mới khi sử dụng hằng ngày."
  },
  {
    "id": 121,
    "word": "bookshelf",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈbʊkʃɛlf/",
    "meaning": "kệ sách",
    "ex1": "A bookshelf keeps reading materials organized and easy to find.",
    "ex1_vi": "Kệ sách giữ tài liệu đọc ngăn nắp và dễ tìm."
  },
  {
    "id": 122,
    "word": "piece",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈis/",
    "meaning": "món; chiếc",
    "ex1": "Families arrange piece carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp món; chiếc cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 123,
    "word": "furniture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɝnɪtʃɝ/",
    "meaning": "đồ nội thất",
    "ex1": "A bedroom can include furniture for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có đồ nội thất để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 124,
    "word": "used",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzd/",
    "meaning": "được sử dụng",
    "ex1": "Families can used this bedroom item safely every day.",
    "ex1_vi": "Các gia đình có thể được sử dụng vật dụng phòng ngủ này an toàn mỗi ngày."
  },
  {
    "id": 125,
    "word": "storing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈɔrɪŋ/",
    "meaning": "việc cất giữ",
    "ex1": "People often storing bedroom furniture before going to sleep.",
    "ex1_vi": "Mọi người thường việc cất giữ đồ nội thất phòng ngủ trước khi đi ngủ."
  },
  {
    "id": 126,
    "word": "books",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʊks/",
    "meaning": "sách",
    "ex1": "A bedroom can include books for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có sách để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 127,
    "word": "magazines",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈæɡʌzˌinz/",
    "meaning": "tạp chí",
    "ex1": "People keep magazines clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ tạp chí sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 128,
    "word": "objects",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɑbdʒɛkts/",
    "meaning": "đồ vật",
    "ex1": "Families arrange objects carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp đồ vật cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 129,
    "word": "tall",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈɔl/",
    "meaning": "cao",
    "ex1": "People discuss tall while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về cao khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 130,
    "word": "short",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɔrt/",
    "meaning": "thấp",
    "ex1": "People discuss short while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về thấp khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 131,
    "word": "wide",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈaɪd/",
    "meaning": "rộng",
    "ex1": "People discuss wide while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về rộng khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 132,
    "word": "narrow",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈɛroʊ/",
    "meaning": "hẹp",
    "ex1": "People discuss narrow while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về hẹp khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 133,
    "word": "keeps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈips/",
    "meaning": "giữ",
    "ex1": "A bookshelf keeps reading materials organized and easy to find.",
    "ex1_vi": "Kệ sách giữ tài liệu đọc ngăn nắp và dễ tìm."
  },
  {
    "id": 134,
    "word": "reading",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈidɪŋ/",
    "meaning": "việc đọc",
    "ex1": "People discuss reading while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về việc đọc khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 135,
    "word": "organized",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɔrɡʌnˌaɪzd/",
    "meaning": "ngăn nắp",
    "ex1": "People discuss organized while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về ngăn nắp khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 136,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "People discuss easy while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về dễ khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 137,
    "word": "find",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪnd/",
    "meaning": "tìm",
    "ex1": "People discuss find while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về tìm khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 138,
    "word": "place",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪs/",
    "meaning": "nơi; địa điểm",
    "ex1": "People discuss place while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về nơi; địa điểm khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 139,
    "word": "photographs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈoʊtʌɡrˌæfs/",
    "meaning": "ảnh",
    "ex1": "People discuss photographs while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về ảnh khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 140,
    "word": "plants",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈænts/",
    "meaning": "cây",
    "ex1": "People discuss plants while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về cây khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 141,
    "word": "decorations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˌɛkɝˈeɪʃʌnz/",
    "meaning": "đồ trang trí",
    "ex1": "People discuss decorations while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về đồ trang trí khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 142,
    "word": "shelves",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɛlvz/",
    "meaning": "kệ",
    "ex1": "People discuss shelves while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về kệ khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 143,
    "word": "arranged",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɝˈeɪndʒd/",
    "meaning": "được sắp xếp",
    "ex1": "People often arranged bedroom furniture before going to sleep.",
    "ex1_vi": "Mọi người thường được sắp xếp đồ nội thất phòng ngủ trước khi đi ngủ."
  },
  {
    "id": 144,
    "word": "neatly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈitli/",
    "meaning": "gọn gàng",
    "ex1": "People neatly clean bedroom items during regular home care.",
    "ex1_vi": "Mọi người gọn gàng làm sạch vật dụng phòng ngủ khi chăm sóc nhà cửa thường xuyên."
  },
  {
    "id": 145,
    "word": "so",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/sˈoʊ/",
    "meaning": "để; vì vậy",
    "ex1": "Books are arranged neatly so the shelf looks tidy.",
    "ex1_vi": "Sách được sắp xếp gọn gàng để kệ trông ngăn nắp."
  },
  {
    "id": 146,
    "word": "shelf",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɛlf/",
    "meaning": "kệ",
    "ex1": "Families arrange shelf carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp kệ cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 147,
    "word": "does",
    "type": "auxiliary verb",
    "cat": "v",
    "phonetic": "/dˈʌz/",
    "meaning": "trợ động từ do",
    "ex1": "A tidy shelf does not look crowded or messy.",
    "ex1_vi": "Một chiếc kệ gọn gàng không trông chật chội hay lộn xộn."
  },
  {
    "id": 148,
    "word": "crowded",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈaʊdʌd/",
    "meaning": "chật chội",
    "ex1": "A bedroom looks crowded when furniture is well arranged.",
    "ex1_vi": "Một phòng ngủ trông chật chội khi đồ nội thất được sắp xếp tốt."
  },
  {
    "id": 149,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈusfʌl/",
    "meaning": "hữu ích",
    "ex1": "People prefer useful bedroom items for comfortable daily use.",
    "ex1_vi": "Mọi người thích các vật dụng phòng ngủ hữu ích để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 150,
    "word": "relaxing",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪlˈæksɪŋ/",
    "meaning": "việc thư giãn",
    "ex1": "This bedroom item can feel relaxing during daily use.",
    "ex1_vi": "Vật dụng phòng ngủ này có thể cảm thấy việc thư giãn khi sử dụng hằng ngày."
  }
];

const newReadingVocabOrder = [
  "mirror",
  "object",
  "smooth",
  "surface",
  "reflects",
  "images",
  "bedroom",
  "mirrors",
  "may",
  "attached",
  "wardrobe",
  "placed",
  "dressing",
  "table",
  "or",
  "hung",
  "wall",
  "people",
  "use",
  "when",
  "getting",
  "dressed",
  "brushing",
  "hair",
  "checking",
  "appearance",
  "large",
  "can",
  "also",
  "make",
  "small",
  "look",
  "brighter",
  "and",
  "more",
  "spacious",
  "should",
  "cleaned",
  "regularly",
  "because",
  "dust",
  "marks",
  "appear",
  "clean",
  "gives",
  "clear",
  "reflection",
  "improves",
  "room’s",
  "alarm",
  "clock",
  "device",
  "tells",
  "time",
  "makes",
  "sound",
  "chosen",
  "hour",
  "digital",
  "have",
  "traditional",
  "hands",
  "wake",
  "up",
  "school",
  "work",
  "other",
  "activities",
  "some",
  "modern",
  "clocks",
  "radios",
  "lights",
  "different",
  "sounds",
  "usually",
  "near",
  "bed",
  "loud",
  "enough",
  "person",
  "but",
  "not",
  "too",
  "disturbing",
  "unpleasant",
  "curtains",
  "pieces",
  "fabric",
  "cover",
  "windows",
  "available",
  "many",
  "colors",
  "patterns",
  "lengths",
  "materials",
  "provide",
  "privacy",
  "control",
  "amount",
  "sunlight",
  "entering",
  "room",
  "thick",
  "block",
  "strong",
  "light",
  "while",
  "thin",
  "allow",
  "gentle",
  "natural",
  "enter",
  "attractive",
  "washed",
  "occasionally",
  "remove",
  "keep",
  "fresh",
  "bookshelf",
  "piece",
  "furniture",
  "used",
  "storing",
  "books",
  "magazines",
  "objects",
  "tall",
  "short",
  "wide",
  "narrow",
  "keeps",
  "reading",
  "organized",
  "easy",
  "find",
  "place",
  "photographs",
  "plants",
  "decorations",
  "shelves",
  "arranged",
  "neatly",
  "so",
  "shelf",
  "does",
  "crowded",
  "useful",
  "relaxing"
];
