const lessonVocabularyWords = [
  "wardrobe",
  "large",
  "piece",
  "furniture",
  "used",
  "storing",
  "clothes",
  "usually",
  "has",
  "doors",
  "shelves",
  "drawers",
  "and",
  "space",
  "hanging",
  "shirts",
  "dresses",
  "or",
  "jackets",
  "helps",
  "keep",
  "bedroom",
  "organized",
  "can",
  "arranged",
  "type",
  "color",
  "season",
  "shoes",
  "bags",
  "other",
  "personal",
  "items",
  "may",
  "also",
  "stored",
  "inside",
  "should",
  "cleaned",
  "regularly",
  "tidy",
  "makes",
  "easier",
  "find",
  "keeps",
  "neat",
  "bedside",
  "table",
  "small",
  "placed",
  "next",
  "bed",
  "often",
  "one",
  "more",
  "people",
  "put",
  "lamp",
  "alarm",
  "clock",
  "book",
  "phone",
  "glass",
  "water",
  "easy",
  "reach",
  "during",
  "night",
  "not",
  "hold",
  "too",
  "many",
  "things",
  "keeping",
  "clean",
  "simple",
  "look",
  "peaceful",
  "comfortable",
  "provides",
  "light",
  "reading",
  "relaxing",
  "moving",
  "around",
  "desk",
  "wall",
  "lamps",
  "give",
  "soft",
  "warm",
  "kind",
  "creates",
  "calm",
  "atmosphere",
  "eyes",
  "feel",
  "before",
  "bedtime",
  "safe",
  "position",
  "turned",
  "off",
  "when",
  "needed",
  "save",
  "electricity",
  "reduce",
  "risk",
  "accidents"
];

const newVocabData = [
  {
    "id": 1,
    "word": "wardrobe",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔrdrˌoʊb/",
    "meaning": "tủ quần áo",
    "ex1": "People keep wardrobe clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ tủ quần áo sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 2,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒ/",
    "meaning": "lớn",
    "ex1": "A wardrobe is a large piece of furniture used for storing clothes.",
    "ex1_vi": "Tủ quần áo là một món đồ nội thất lớn dùng để cất quần áo."
  },
  {
    "id": 3,
    "word": "piece",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈis/",
    "meaning": "món; chiếc",
    "ex1": "A wardrobe is a large piece of furniture used for storing clothes.",
    "ex1_vi": "Tủ quần áo là một món đồ nội thất lớn dùng để cất quần áo."
  },
  {
    "id": 4,
    "word": "furniture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɝnɪtʃɝ/",
    "meaning": "đồ nội thất",
    "ex1": "People discuss furniture while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về đồ nội thất khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 5,
    "word": "used",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzd/",
    "meaning": "được sử dụng",
    "ex1": "People discuss used while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về được sử dụng khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 6,
    "word": "storing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈɔrɪŋ/",
    "meaning": "việc cất giữ",
    "ex1": "People discuss storing while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về việc cất giữ khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 7,
    "word": "clothes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈoʊðz/",
    "meaning": "quần áo",
    "ex1": "Clothes can be arranged by type, color, or season.",
    "ex1_vi": "Quần áo có thể được sắp xếp theo loại, màu sắc hoặc mùa."
  },
  {
    "id": 8,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "People usually use this item before going to sleep.",
    "ex1_vi": "Mọi người thường dùng vật dụng này trước khi đi ngủ."
  },
  {
    "id": 9,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "It often has one or more drawers for storing small personal items.",
    "ex1_vi": "Bàn thường có một hoặc nhiều ngăn kéo để cất những đồ dùng cá nhân nhỏ."
  },
  {
    "id": 10,
    "word": "doors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɔrz/",
    "meaning": "cửa",
    "ex1": "People keep doors clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ cửa sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 11,
    "word": "shelves",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɛlvz/",
    "meaning": "kệ",
    "ex1": "Families arrange shelves carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp kệ cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 12,
    "word": "drawers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɔrz/",
    "meaning": "ngăn kéo",
    "ex1": "It often has one or more drawers for storing small personal items.",
    "ex1_vi": "Bàn thường có một hoặc nhiều ngăn kéo để cất những đồ dùng cá nhân nhỏ."
  },
  {
    "id": 13,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "The wardrobe should be cleaned and organized regularly.",
    "ex1_vi": "Tủ quần áo nên được làm sạch và sắp xếp thường xuyên."
  },
  {
    "id": 14,
    "word": "space",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈeɪs/",
    "meaning": "khoảng trống",
    "ex1": "Families arrange space carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp khoảng trống cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 15,
    "word": "hanging",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæŋɪŋ/",
    "meaning": "việc treo",
    "ex1": "People hanging bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người việc treo các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 16,
    "word": "shirts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɝts/",
    "meaning": "áo sơ mi",
    "ex1": "People keep shirts clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ áo sơ mi sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 17,
    "word": "dresses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɛsʌz/",
    "meaning": "váy",
    "ex1": "Families arrange dresses carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp váy cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 18,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "Clothes can be arranged by type, color, or season.",
    "ex1_vi": "Quần áo có thể được sắp xếp theo loại, màu sắc hoặc mùa."
  },
  {
    "id": 19,
    "word": "jackets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈækɪts/",
    "meaning": "áo khoác",
    "ex1": "People keep jackets clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ áo khoác sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 20,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "People often helps bedroom furniture before going to sleep.",
    "ex1_vi": "Mọi người thường giúp đồ nội thất phòng ngủ trước khi đi ngủ."
  },
  {
    "id": 21,
    "word": "keep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈip/",
    "meaning": "giữ",
    "ex1": "People keep bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người giữ các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 22,
    "word": "bedroom",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɛdrˌum/",
    "meaning": "phòng ngủ",
    "ex1": "People keep bedroom clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ phòng ngủ sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 23,
    "word": "organized",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɔrɡʌnˌaɪzd/",
    "meaning": "ngăn nắp",
    "ex1": "People often organized bedroom furniture before going to sleep.",
    "ex1_vi": "Mọi người thường ngăn nắp đồ nội thất phòng ngủ trước khi đi ngủ."
  },
  {
    "id": 24,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "People discuss can while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về có thể khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 25,
    "word": "arranged",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɝˈeɪndʒd/",
    "meaning": "được sắp xếp",
    "ex1": "People discuss arranged while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về được sắp xếp khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 26,
    "word": "type",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪp/",
    "meaning": "loại",
    "ex1": "People discuss type while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về loại khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 27,
    "word": "color",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌlɝ/",
    "meaning": "màu sắc",
    "ex1": "People discuss color while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về màu sắc khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 28,
    "word": "season",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈizʌn/",
    "meaning": "mùa",
    "ex1": "People discuss season while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về mùa khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 29,
    "word": "shoes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈuz/",
    "meaning": "giày",
    "ex1": "Shoes, bags, and other personal items may also be stored inside.",
    "ex1_vi": "Giày, túi và các đồ dùng cá nhân khác cũng có thể được cất bên trong."
  },
  {
    "id": 30,
    "word": "bags",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈæɡz/",
    "meaning": "túi",
    "ex1": "Shoes, bags, and other personal items may also be stored inside.",
    "ex1_vi": "Giày, túi và các đồ dùng cá nhân khác cũng có thể được cất bên trong."
  },
  {
    "id": 31,
    "word": "other",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈʌðɝ/",
    "meaning": "khác",
    "ex1": "People discuss other while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về khác khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 32,
    "word": "personal",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɝsɪnʌl/",
    "meaning": "cá nhân",
    "ex1": "People discuss personal while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về cá nhân khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 33,
    "word": "items",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪtʌmz/",
    "meaning": "đồ dùng",
    "ex1": "These items are easy to reach during the night.",
    "ex1_vi": "Những đồ này dễ lấy vào ban đêm."
  },
  {
    "id": 34,
    "word": "may",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈeɪ/",
    "meaning": "có thể",
    "ex1": "People discuss may while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về có thể khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 35,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "People discuss also while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về cũng khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 36,
    "word": "stored",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈɔrd/",
    "meaning": "được cất",
    "ex1": "People discuss stored while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về được cất khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 37,
    "word": "inside",
    "type": "adverb/preposition",
    "cat": "adv",
    "phonetic": "/ˌɪnsˈaɪd/",
    "meaning": "bên trong",
    "ex1": "People discuss inside while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về bên trong khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 38,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "The wardrobe should be cleaned and organized regularly.",
    "ex1_vi": "Tủ quần áo nên được làm sạch và sắp xếp thường xuyên."
  },
  {
    "id": 39,
    "word": "cleaned",
    "type": "verb",
    "cat": "v",
    "phonetic": "/klˈind/",
    "meaning": "được làm sạch",
    "ex1": "People discuss cleaned while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về được làm sạch khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 40,
    "word": "regularly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/rˈɛɡjʌlɝli/",
    "meaning": "thường xuyên",
    "ex1": "People discuss regularly while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về thường xuyên khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 41,
    "word": "tidy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈaɪdi/",
    "meaning": "gọn gàng",
    "ex1": "People prefer tidy bedroom items for comfortable daily use.",
    "ex1_vi": "Mọi người thích các vật dụng phòng ngủ gọn gàng để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 42,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm cho",
    "ex1": "People makes bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người làm cho các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 43,
    "word": "easier",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈiziɝ/",
    "meaning": "dễ hơn",
    "ex1": "A bedroom looks easier when furniture is well arranged.",
    "ex1_vi": "Một phòng ngủ trông dễ hơn khi đồ nội thất được sắp xếp tốt."
  },
  {
    "id": 44,
    "word": "find",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪnd/",
    "meaning": "tìm",
    "ex1": "People often find bedroom furniture before going to sleep.",
    "ex1_vi": "Mọi người thường tìm đồ nội thất phòng ngủ trước khi đi ngủ."
  },
  {
    "id": 45,
    "word": "keeps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈips/",
    "meaning": "giữ",
    "ex1": "People keeps bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người giữ các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 46,
    "word": "neat",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈit/",
    "meaning": "ngăn nắp",
    "ex1": "A bedroom looks neat when furniture is well arranged.",
    "ex1_vi": "Một phòng ngủ trông ngăn nắp khi đồ nội thất được sắp xếp tốt."
  },
  {
    "id": 47,
    "word": "bedside",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈbɛdsaɪd/",
    "meaning": "đầu giường",
    "ex1": "It is often placed on a bedside table, desk, or wall.",
    "ex1_vi": "Đèn thường được đặt trên bàn đầu giường, bàn làm việc hoặc tường."
  },
  {
    "id": 48,
    "word": "table",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪbʌl/",
    "meaning": "bàn",
    "ex1": "The table should not hold too many things.",
    "ex1_vi": "Bàn không nên để quá nhiều đồ."
  },
  {
    "id": 49,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "A bedside table is a small table placed next to the bed.",
    "ex1_vi": "Bàn đầu giường là một chiếc bàn nhỏ đặt cạnh giường."
  },
  {
    "id": 50,
    "word": "placed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪst/",
    "meaning": "được đặt",
    "ex1": "The lamp should be placed in a safe position.",
    "ex1_vi": "Đèn nên được đặt ở vị trí an toàn."
  },
  {
    "id": 51,
    "word": "next",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈɛkst/",
    "meaning": "kế bên",
    "ex1": "A bedside table is a small table placed next to the bed.",
    "ex1_vi": "Bàn đầu giường là một chiếc bàn nhỏ đặt cạnh giường."
  },
  {
    "id": 52,
    "word": "bed",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɛd/",
    "meaning": "giường",
    "ex1": "People discuss bed while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về giường khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 53,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "It is often placed on a bedside table, desk, or wall.",
    "ex1_vi": "Đèn thường được đặt trên bàn đầu giường, bàn làm việc hoặc tường."
  },
  {
    "id": 54,
    "word": "one",
    "type": "number",
    "cat": "adj",
    "phonetic": "/wˈʌn/",
    "meaning": "một",
    "ex1": "People discuss one while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về một khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 55,
    "word": "more",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "nhiều hơn",
    "ex1": "People discuss more while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về nhiều hơn khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 56,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "Families arrange people carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp mọi người cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 57,
    "word": "put",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pˈʊt/",
    "meaning": "đặt",
    "ex1": "People put bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người đặt các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 58,
    "word": "lamp",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈæmp/",
    "meaning": "đèn",
    "ex1": "The lamp should be placed in a safe position.",
    "ex1_vi": "Đèn nên được đặt ở vị trí an toàn."
  },
  {
    "id": 59,
    "word": "alarm",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌlˈɑrm/",
    "meaning": "báo thức",
    "ex1": "Families arrange alarm carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp báo thức cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 60,
    "word": "clock",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈɑk/",
    "meaning": "đồng hồ",
    "ex1": "A bedroom can include clock for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có đồng hồ để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 61,
    "word": "book",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʊk/",
    "meaning": "sách",
    "ex1": "People keep book clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ sách sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 62,
    "word": "phone",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈoʊn/",
    "meaning": "điện thoại",
    "ex1": "Families arrange phone carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp điện thoại cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 63,
    "word": "glass",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡlˈæs/",
    "meaning": "ly",
    "ex1": "A bedroom can include glass for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có ly để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 64,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước",
    "ex1": "People keep water clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ nước sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 65,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "These items are easy to reach during the night.",
    "ex1_vi": "Những đồ này dễ lấy vào ban đêm."
  },
  {
    "id": 66,
    "word": "reach",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈitʃ/",
    "meaning": "với tới",
    "ex1": "People discuss reach while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về với tới khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 67,
    "word": "during",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/dˈʊrɪŋ/",
    "meaning": "trong",
    "ex1": "People discuss during while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về trong khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 68,
    "word": "night",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈaɪt/",
    "meaning": "ban đêm",
    "ex1": "People discuss night while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về ban đêm khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 69,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "The table should not hold too many things.",
    "ex1_vi": "Bàn không nên để quá nhiều đồ."
  },
  {
    "id": 70,
    "word": "hold",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈoʊld/",
    "meaning": "chứa; giữ",
    "ex1": "People discuss hold while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về chứa; giữ khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 71,
    "word": "too",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tˈu/",
    "meaning": "quá",
    "ex1": "People discuss too while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về quá khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 72,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "People discuss many while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về nhiều khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 73,
    "word": "things",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈɪŋz/",
    "meaning": "đồ vật",
    "ex1": "People discuss things while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về đồ vật khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 74,
    "word": "keeping",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈipɪŋ/",
    "meaning": "việc giữ",
    "ex1": "Families arrange keeping carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp việc giữ cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 75,
    "word": "clean",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈin/",
    "meaning": "sạch",
    "ex1": "This bedroom item can feel clean during daily use.",
    "ex1_vi": "Vật dụng phòng ngủ này có thể cảm thấy sạch khi sử dụng hằng ngày."
  },
  {
    "id": 76,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "A bedroom looks simple when furniture is well arranged.",
    "ex1_vi": "Một phòng ngủ trông đơn giản khi đồ nội thất được sắp xếp tốt."
  },
  {
    "id": 77,
    "word": "look",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊk/",
    "meaning": "trông",
    "ex1": "People often look bedroom furniture before going to sleep.",
    "ex1_vi": "Mọi người thường trông đồ nội thất phòng ngủ trước khi đi ngủ."
  },
  {
    "id": 78,
    "word": "peaceful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈisfʌl/",
    "meaning": "yên bình",
    "ex1": "This bedroom item can feel peaceful during daily use.",
    "ex1_vi": "Vật dụng phòng ngủ này có thể cảm thấy yên bình khi sử dụng hằng ngày."
  },
  {
    "id": 79,
    "word": "comfortable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌmfɝtʌbʌl/",
    "meaning": "thoải mái",
    "ex1": "A bedroom looks comfortable when furniture is well arranged.",
    "ex1_vi": "Một phòng ngủ trông thoải mái khi đồ nội thất được sắp xếp tốt."
  },
  {
    "id": 80,
    "word": "provides",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌvˈaɪdz/",
    "meaning": "cung cấp",
    "ex1": "People often provides bedroom furniture before going to sleep.",
    "ex1_vi": "Mọi người thường cung cấp đồ nội thất phòng ngủ trước khi đi ngủ."
  },
  {
    "id": 81,
    "word": "light",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈaɪt/",
    "meaning": "nhẹ; ánh sáng",
    "ex1": "Many bedroom lamps give soft and warm light.",
    "ex1_vi": "Nhiều đèn phòng ngủ cho ánh sáng dịu và ấm."
  },
  {
    "id": 82,
    "word": "reading",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈidɪŋ/",
    "meaning": "việc đọc",
    "ex1": "Families can reading this bedroom item safely every day.",
    "ex1_vi": "Các gia đình có thể việc đọc vật dụng phòng ngủ này an toàn mỗi ngày."
  },
  {
    "id": 83,
    "word": "relaxing",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪlˈæksɪŋ/",
    "meaning": "việc thư giãn",
    "ex1": "People prefer relaxing bedroom items for comfortable daily use.",
    "ex1_vi": "Mọi người thích các vật dụng phòng ngủ việc thư giãn để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 84,
    "word": "moving",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈuvɪŋ/",
    "meaning": "việc di chuyển",
    "ex1": "People moving bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người việc di chuyển các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 85,
    "word": "around",
    "type": "preposition/adverb",
    "cat": "adv",
    "phonetic": "/ɝˈaʊnd/",
    "meaning": "xung quanh",
    "ex1": "Families use around in simple sentences about bedroom furniture.",
    "ex1_vi": "Các gia đình dùng “around” trong những câu đơn giản về đồ nội thất phòng ngủ."
  },
  {
    "id": 86,
    "word": "desk",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɛsk/",
    "meaning": "bàn làm việc",
    "ex1": "People discuss desk while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về bàn làm việc khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 87,
    "word": "wall",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔl/",
    "meaning": "tường",
    "ex1": "People discuss wall while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về tường khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 88,
    "word": "lamps",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈæmps/",
    "meaning": "đèn",
    "ex1": "Many bedroom lamps give soft and warm light.",
    "ex1_vi": "Nhiều đèn phòng ngủ cho ánh sáng dịu và ấm."
  },
  {
    "id": 89,
    "word": "give",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪv/",
    "meaning": "cho",
    "ex1": "People discuss give while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về cho khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 90,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "People discuss soft while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về mềm khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 91,
    "word": "warm",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈɔrm/",
    "meaning": "ấm",
    "ex1": "People discuss warm while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về ấm khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 92,
    "word": "kind",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈaɪnd/",
    "meaning": "loại",
    "ex1": "People prefer kind bedroom items for comfortable daily use.",
    "ex1_vi": "Mọi người thích các vật dụng phòng ngủ loại để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 93,
    "word": "creates",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪts/",
    "meaning": "tạo ra",
    "ex1": "People creates bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người tạo ra các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 94,
    "word": "calm",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɑm/",
    "meaning": "yên tĩnh",
    "ex1": "A bedroom looks calm when furniture is well arranged.",
    "ex1_vi": "Một phòng ngủ trông yên tĩnh khi đồ nội thất được sắp xếp tốt."
  },
  {
    "id": 95,
    "word": "atmosphere",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈætmʌsfˌɪr/",
    "meaning": "bầu không khí",
    "ex1": "Families arrange atmosphere carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp bầu không khí cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 96,
    "word": "eyes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪz/",
    "meaning": "mắt",
    "ex1": "A bedroom can include eyes for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có mắt để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 97,
    "word": "feel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈil/",
    "meaning": "cảm thấy",
    "ex1": "Families can feel this bedroom item safely every day.",
    "ex1_vi": "Các gia đình có thể cảm thấy vật dụng phòng ngủ này an toàn mỗi ngày."
  },
  {
    "id": 98,
    "word": "before",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/bɪfˈɔr/",
    "meaning": "trước",
    "ex1": "People use before naturally when describing bedroom objects.",
    "ex1_vi": "Mọi người dùng “before” tự nhiên khi mô tả các đồ vật trong phòng ngủ."
  },
  {
    "id": 99,
    "word": "bedtime",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈbɛdtaɪm/",
    "meaning": "giờ đi ngủ",
    "ex1": "A bedroom can include bedtime for comfortable daily use.",
    "ex1_vi": "Một phòng ngủ có thể có giờ đi ngủ để sử dụng thoải mái hằng ngày."
  },
  {
    "id": 100,
    "word": "safe",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪf/",
    "meaning": "an toàn",
    "ex1": "People discuss safe while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về an toàn khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 101,
    "word": "position",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pʌzˈɪʃʌn/",
    "meaning": "vị trí",
    "ex1": "People discuss position while arranging bedroom items at home.",
    "ex1_vi": "Mọi người nói về vị trí khi sắp xếp các vật dụng phòng ngủ ở nhà."
  },
  {
    "id": 102,
    "word": "turned",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈɝnd/",
    "meaning": "được tắt/bật",
    "ex1": "People turned bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người được tắt/bật các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 103,
    "word": "off",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔf/",
    "meaning": "tắt",
    "ex1": "Families off arrange bedroom furniture to keep things tidy.",
    "ex1_vi": "Các gia đình tắt sắp xếp đồ nội thất phòng ngủ để giữ mọi thứ gọn gàng."
  },
  {
    "id": 104,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "The lamp should be off when nobody needs it.",
    "ex1_vi": "Đèn nên tắt khi không ai cần dùng."
  },
  {
    "id": 105,
    "word": "needed",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈidʌd/",
    "meaning": "cần thiết",
    "ex1": "This bedroom item can feel needed during daily use.",
    "ex1_vi": "Vật dụng phòng ngủ này có thể cảm thấy cần thiết khi sử dụng hằng ngày."
  },
  {
    "id": 106,
    "word": "save",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪv/",
    "meaning": "tiết kiệm",
    "ex1": "Families can save this bedroom item safely every day.",
    "ex1_vi": "Các gia đình có thể tiết kiệm vật dụng phòng ngủ này an toàn mỗi ngày."
  },
  {
    "id": 107,
    "word": "electricity",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪlˌɛktrˈɪsʌti/",
    "meaning": "điện",
    "ex1": "Families arrange electricity carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp điện cẩn thận để giữ phòng ngủ gọn gàng."
  },
  {
    "id": 108,
    "word": "reduce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rʌdˈus/",
    "meaning": "giảm",
    "ex1": "People reduce bedroom items during simple daily routines.",
    "ex1_vi": "Mọi người giảm các vật dụng phòng ngủ trong sinh hoạt hằng ngày."
  },
  {
    "id": 109,
    "word": "risk",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɪsk/",
    "meaning": "nguy cơ",
    "ex1": "People keep risk clean in a comfortable bedroom.",
    "ex1_vi": "Mọi người giữ nguy cơ sạch sẽ trong một phòng ngủ thoải mái."
  },
  {
    "id": 110,
    "word": "accidents",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈæksʌdʌnts/",
    "meaning": "tai nạn",
    "ex1": "Families arrange accidents carefully to keep the bedroom tidy.",
    "ex1_vi": "Các gia đình sắp xếp tai nạn cẩn thận để giữ phòng ngủ gọn gàng."
  }
];

const newReadingVocabOrder = [
  "wardrobe",
  "large",
  "piece",
  "furniture",
  "used",
  "storing",
  "clothes",
  "usually",
  "has",
  "doors",
  "shelves",
  "drawers",
  "and",
  "space",
  "hanging",
  "shirts",
  "dresses",
  "or",
  "jackets",
  "helps",
  "keep",
  "bedroom",
  "organized",
  "can",
  "arranged",
  "type",
  "color",
  "season",
  "shoes",
  "bags",
  "other",
  "personal",
  "items",
  "may",
  "also",
  "stored",
  "inside",
  "should",
  "cleaned",
  "regularly",
  "tidy",
  "makes",
  "easier",
  "find",
  "keeps",
  "neat",
  "bedside",
  "table",
  "small",
  "placed",
  "next",
  "bed",
  "often",
  "one",
  "more",
  "people",
  "put",
  "lamp",
  "alarm",
  "clock",
  "book",
  "phone",
  "glass",
  "water",
  "easy",
  "reach",
  "during",
  "night",
  "not",
  "hold",
  "too",
  "many",
  "things",
  "keeping",
  "clean",
  "simple",
  "look",
  "peaceful",
  "comfortable",
  "provides",
  "light",
  "reading",
  "relaxing",
  "moving",
  "around",
  "desk",
  "wall",
  "lamps",
  "give",
  "soft",
  "warm",
  "kind",
  "creates",
  "calm",
  "atmosphere",
  "eyes",
  "feel",
  "before",
  "bedtime",
  "safe",
  "position",
  "turned",
  "off",
  "when",
  "needed",
  "save",
  "electricity",
  "reduce",
  "risk",
  "accidents"
];
