// ===== traffic01 VOCABULARY =====

const lessonVocabularyWords = [
  "city",
  "traffic",
  "busy",
  "every",
  "day",
  "especially",
  "morning",
  "and",
  "evening",
  "many",
  "people",
  "travel",
  "work",
  "school",
  "or",
  "market",
  "cars",
  "buses",
  "motorbikes",
  "bicycles",
  "trucks",
  "share",
  "same",
  "roads",
  "streets",
  "often",
  "become",
  "crowded",
  "rush",
  "hours",
  "waiting",
  "vehicles",
  "together",
  "lights",
  "road",
  "signs",
  "police",
  "officers",
  "help",
  "keep",
  "safe",
  "organized",
  "drivers",
  "should",
  "stop",
  "red",
  "follow",
  "speed",
  "limits",
  "carefully",
  "pedestrians",
  "need",
  "use",
  "crosswalks",
  "crossing",
  "heavy",
  "can",
  "cause",
  "delays",
  "air",
  "pollution",
  "public",
  "transport",
  "ride",
  "walk",
  "short",
  "distances",
  "careful",
  "driving",
  "helps",
  "everyone",
  "safely",
  "comfortably",
  "transportation",
  "important",
  "part",
  "life",
  "take",
  "trains",
  "subways",
  "carry",
  "passengers",
  "reduce",
  "usually",
  "cheaper",
  "than",
  "private",
  "wait",
  "patiently",
  "bus",
  "stops",
  "train",
  "stations",
  "buy",
  "tickets",
  "stand",
  "line",
  "respect",
  "other",
  "travelers",
  "giving",
  "seats",
  "older",
  "pregnant",
  "women",
  "shows",
  "kindness",
  "good",
  "manners",
  "saves",
  "time",
  "fuel",
  "money",
  "families",
  "more",
  "because",
  "cleaner",
  "protect",
  "environment",
  "improve",
  "rules",
  "cyclists",
  "understand",
  "lane",
  "markings",
  "give",
  "directions",
  "neighborhood",
  "must",
  "wear",
  "seat",
  "belts",
  "avoid",
  "using",
  "mobile",
  "phones",
  "while",
  "motorbike",
  "riders",
  "always",
  "helmets",
  "cross",
  "green",
  "following",
  "reduces",
  "accidents",
  "protects",
  "lives",
  "patient",
  "responsible",
  "make",
  "trip",
  "safer",
  "habits",
  "create",
  "friendlier",
  "cities"
];

const newVocabData = [
  {
    "id": 1,
    "word": "city",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪti/",
    "meaning": "thành phố",
    "ex1": "City traffic is busy every day, especially in the morning and evening.",
    "ex1_vi": "Giao thông thành phố đông đúc mỗi ngày, đặc biệt vào buổi sáng và buổi tối."
  },
  {
    "id": 2,
    "word": "traffic",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈæfɪk/",
    "meaning": "giao thông",
    "ex1": "In daily city life, city traffic is busy every day, especially in the morning and evening.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, giao thông thành phố đông đúc mỗi ngày, đặc biệt vào buổi sáng và buổi tối."
  },
  {
    "id": 3,
    "word": "busy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈbɪzi/",
    "meaning": "bận rộn; đông đúc",
    "ex1": "For safe travel, city traffic is busy every day, especially in the morning and evening.",
    "ex1_vi": "Để đi lại an toàn, giao thông thành phố đông đúc mỗi ngày, đặc biệt vào buổi sáng và buổi tối."
  },
  {
    "id": 4,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ɛvɚi/",
    "meaning": "mỗi",
    "ex1": "On busy city streets, city traffic is busy every day, especially in the morning and evening.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, giao thông thành phố đông đúc mỗi ngày, đặc biệt vào buổi sáng và buổi tối."
  },
  {
    "id": 5,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/deɪ/",
    "meaning": "ngày",
    "ex1": "During everyday travel, city traffic is busy every day, especially in the morning and evening.",
    "ex1_vi": "Trong việc đi lại hằng ngày, giao thông thành phố đông đúc mỗi ngày, đặc biệt vào buổi sáng và buổi tối."
  },
  {
    "id": 6,
    "word": "especially",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɪspˈɛʃəli/",
    "meaning": "đặc biệt",
    "ex1": "For road safety, city traffic is busy every day, especially in the morning and evening.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, giao thông thành phố đông đúc mỗi ngày, đặc biệt vào buổi sáng và buổi tối."
  },
  {
    "id": 7,
    "word": "morning",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɔːɹnɪŋ/",
    "meaning": "buổi sáng",
    "ex1": "In many neighborhoods, city traffic is busy every day, especially in the morning and evening.",
    "ex1_vi": "Ở nhiều khu phố, giao thông thành phố đông đúc mỗi ngày, đặc biệt vào buổi sáng và buổi tối."
  },
  {
    "id": 8,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ənd/",
    "meaning": "và",
    "ex1": "On a normal weekday, city traffic is busy every day, especially in the morning and evening.",
    "ex1_vi": "Vào một ngày thường, giao thông thành phố đông đúc mỗi ngày, đặc biệt vào buổi sáng và buổi tối."
  },
  {
    "id": 9,
    "word": "evening",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈivnɪŋ/",
    "meaning": "buổi tối",
    "ex1": "City traffic is busy every day, especially in the morning and evening.",
    "ex1_vi": "Giao thông thành phố đông đúc mỗi ngày, đặc biệt vào buổi sáng và buổi tối."
  },
  {
    "id": 10,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mɛni/",
    "meaning": "nhiều",
    "ex1": "Many people travel to work, school, or the market.",
    "ex1_vi": "Nhiều người đi làm, đi học hoặc đi chợ."
  },
  {
    "id": 11,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipəl/",
    "meaning": "mọi người",
    "ex1": "In daily city life, many people travel to work, school, or the market.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, nhiều người đi làm, đi học hoặc đi chợ."
  },
  {
    "id": 12,
    "word": "travel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tɹˈævəl/",
    "meaning": "di chuyển; đi lại",
    "ex1": "For safe travel, many people travel to work, school, or the market.",
    "ex1_vi": "Để đi lại an toàn, nhiều người đi làm, đi học hoặc đi chợ."
  },
  {
    "id": 13,
    "word": "work",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝk/",
    "meaning": "nơi làm việc; công việc",
    "ex1": "On busy city streets, many people travel to work, school, or the market.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, nhiều người đi làm, đi học hoặc đi chợ."
  },
  {
    "id": 14,
    "word": "school",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈul/",
    "meaning": "trường học",
    "ex1": "During everyday travel, many people travel to work, school, or the market.",
    "ex1_vi": "Trong việc đi lại hằng ngày, nhiều người đi làm, đi học hoặc đi chợ."
  },
  {
    "id": 15,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ɔr/",
    "meaning": "hoặc",
    "ex1": "For road safety, many people travel to work, school, or the market.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, nhiều người đi làm, đi học hoặc đi chợ."
  },
  {
    "id": 16,
    "word": "market",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɑrkʌt/",
    "meaning": "chợ",
    "ex1": "In many neighborhoods, many people travel to work, school, or the market.",
    "ex1_vi": "Ở nhiều khu phố, nhiều người đi làm, đi học hoặc đi chợ."
  },
  {
    "id": 17,
    "word": "cars",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑrz/",
    "meaning": "ô tô",
    "ex1": "Cars, buses, motorbikes, bicycles, and trucks share the same roads.",
    "ex1_vi": "Ô tô, xe buýt, xe máy, xe đạp và xe tải cùng sử dụng những con đường."
  },
  {
    "id": 18,
    "word": "buses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʌsɪz/",
    "meaning": "xe buýt",
    "ex1": "In daily city life, cars, buses, motorbikes, bicycles, and trucks share the same roads.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, ô tô, xe buýt, xe máy, xe đạp và xe tải cùng sử dụng những con đường."
  },
  {
    "id": 19,
    "word": "motorbikes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈoʊtɝbˌaɪks/",
    "meaning": "xe máy",
    "ex1": "For safe travel, cars, buses, motorbikes, bicycles, and trucks share the same roads.",
    "ex1_vi": "Để đi lại an toàn, ô tô, xe buýt, xe máy, xe đạp và xe tải cùng sử dụng những con đường."
  },
  {
    "id": 20,
    "word": "bicycles",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈaɪsɪkʌlz/",
    "meaning": "xe đạp",
    "ex1": "On busy city streets, cars, buses, motorbikes, bicycles, and trucks share the same roads.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, ô tô, xe buýt, xe máy, xe đạp và xe tải cùng sử dụng những con đường."
  },
  {
    "id": 21,
    "word": "trucks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈʌks/",
    "meaning": "xe tải",
    "ex1": "During everyday travel, cars, buses, motorbikes, bicycles, and trucks share the same roads.",
    "ex1_vi": "Trong việc đi lại hằng ngày, ô tô, xe buýt, xe máy, xe đạp và xe tải cùng sử dụng những con đường."
  },
  {
    "id": 22,
    "word": "share",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈɛɹ/",
    "meaning": "cùng sử dụng; chia sẻ",
    "ex1": "For road safety, cars, buses, motorbikes, bicycles, and trucks share the same roads.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, ô tô, xe buýt, xe máy, xe đạp và xe tải cùng sử dụng những con đường."
  },
  {
    "id": 23,
    "word": "same",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪm/",
    "meaning": "cùng một",
    "ex1": "In many neighborhoods, cars, buses, motorbikes, bicycles, and trucks share the same roads.",
    "ex1_vi": "Ở nhiều khu phố, ô tô, xe buýt, xe máy, xe đạp và xe tải cùng sử dụng những con đường."
  },
  {
    "id": 24,
    "word": "roads",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈoʊdz/",
    "meaning": "đường",
    "ex1": "On a normal weekday, cars, buses, motorbikes, bicycles, and trucks share the same roads.",
    "ex1_vi": "Vào một ngày thường, ô tô, xe buýt, xe máy, xe đạp và xe tải cùng sử dụng những con đường."
  },
  {
    "id": 25,
    "word": "streets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/strˈits/",
    "meaning": "các con phố",
    "ex1": "Busy streets often become crowded during rush hours with many waiting vehicles together.",
    "ex1_vi": "Những con phố đông đúc thường trở nên chật kín vào giờ cao điểm với nhiều phương tiện cùng chờ đợi."
  },
  {
    "id": 26,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɔfən/",
    "meaning": "thường xuyên",
    "ex1": "In daily city life, busy streets often become crowded during rush hours with many waiting vehicles together.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, những con phố đông đúc thường trở nên chật kín vào giờ cao điểm với nhiều phương tiện cùng chờ đợi."
  },
  {
    "id": 27,
    "word": "become",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌm/",
    "meaning": "trở nên",
    "ex1": "For safe travel, busy streets often become crowded during rush hours with many waiting vehicles together.",
    "ex1_vi": "Để đi lại an toàn, những con phố đông đúc thường trở nên chật kín vào giờ cao điểm với nhiều phương tiện cùng chờ đợi."
  },
  {
    "id": 28,
    "word": "crowded",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈaʊdʌd/",
    "meaning": "đông đúc",
    "ex1": "On busy city streets, busy streets often become crowded during rush hours with many waiting vehicles together.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, những con phố đông đúc thường trở nên chật kín vào giờ cao điểm với nhiều phương tiện cùng chờ đợi."
  },
  {
    "id": 29,
    "word": "rush",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈʌʃ/",
    "meaning": "cao điểm; vội vã",
    "ex1": "During everyday travel, busy streets often become crowded during rush hours with many waiting vehicles together.",
    "ex1_vi": "Trong việc đi lại hằng ngày, những con phố đông đúc thường trở nên chật kín vào giờ cao điểm với nhiều phương tiện cùng chờ đợi."
  },
  {
    "id": 30,
    "word": "hours",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaʊɝz/",
    "meaning": "giờ",
    "ex1": "For road safety, busy streets often become crowded during rush hours with many waiting vehicles together.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, những con phố đông đúc thường trở nên chật kín vào giờ cao điểm với nhiều phương tiện cùng chờ đợi."
  },
  {
    "id": 31,
    "word": "waiting",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈeɪtɪŋ/",
    "meaning": "đang chờ",
    "ex1": "In many neighborhoods, busy streets often become crowded during rush hours with many waiting vehicles together.",
    "ex1_vi": "Ở nhiều khu phố, những con phố đông đúc thường trở nên chật kín vào giờ cao điểm với nhiều phương tiện cùng chờ đợi."
  },
  {
    "id": 32,
    "word": "vehicles",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈihɪkʌlz/",
    "meaning": "phương tiện",
    "ex1": "On a normal weekday, busy streets often become crowded during rush hours with many waiting vehicles together.",
    "ex1_vi": "Vào một ngày thường, những con phố đông đúc thường trở nên chật kín vào giờ cao điểm với nhiều phương tiện cùng chờ đợi."
  },
  {
    "id": 33,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/təɡˈɛðɚ/",
    "meaning": "cùng nhau",
    "ex1": "Busy streets often become crowded during rush hours with many waiting vehicles together.",
    "ex1_vi": "Những con phố đông đúc thường trở nên chật kín vào giờ cao điểm với nhiều phương tiện cùng chờ đợi."
  },
  {
    "id": 34,
    "word": "lights",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪts/",
    "meaning": "đèn",
    "ex1": "Traffic lights, road signs, and police officers help keep traffic safe and organized.",
    "ex1_vi": "Đèn giao thông, biển báo đường bộ và cảnh sát giúp giữ cho giao thông an toàn và có trật tự."
  },
  {
    "id": 35,
    "word": "road",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈoʊd/",
    "meaning": "đường",
    "ex1": "In daily city life, traffic lights, road signs, and police officers help keep traffic safe and organized.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, đèn giao thông, biển báo đường bộ và cảnh sát giúp giữ cho giao thông an toàn và có trật tự."
  },
  {
    "id": 36,
    "word": "signs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaɪnz/",
    "meaning": "biển báo",
    "ex1": "For safe travel, traffic lights, road signs, and police officers help keep traffic safe and organized.",
    "ex1_vi": "Để đi lại an toàn, đèn giao thông, biển báo đường bộ và cảnh sát giúp giữ cho giao thông an toàn và có trật tự."
  },
  {
    "id": 37,
    "word": "police",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pʌlˈis/",
    "meaning": "cảnh sát",
    "ex1": "On busy city streets, traffic lights, road signs, and police officers help keep traffic safe and organized.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, đèn giao thông, biển báo đường bộ và cảnh sát giúp giữ cho giao thông an toàn và có trật tự."
  },
  {
    "id": 38,
    "word": "officers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔfʌsɝz/",
    "meaning": "nhân viên; cảnh sát",
    "ex1": "During everyday travel, traffic lights, road signs, and police officers help keep traffic safe and organized.",
    "ex1_vi": "Trong việc đi lại hằng ngày, đèn giao thông, biển báo đường bộ và cảnh sát giúp giữ cho giao thông an toàn và có trật tự."
  },
  {
    "id": 39,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "For road safety, traffic lights, road signs, and police officers help keep traffic safe and organized.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, đèn giao thông, biển báo đường bộ và cảnh sát giúp giữ cho giao thông an toàn và có trật tự."
  },
  {
    "id": 40,
    "word": "keep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈip/",
    "meaning": "giữ; duy trì",
    "ex1": "In many neighborhoods, traffic lights, road signs, and police officers help keep traffic safe and organized.",
    "ex1_vi": "Ở nhiều khu phố, đèn giao thông, biển báo đường bộ và cảnh sát giúp giữ cho giao thông an toàn và có trật tự."
  },
  {
    "id": 41,
    "word": "safe",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/seɪf/",
    "meaning": "an toàn",
    "ex1": "On a normal weekday, traffic lights, road signs, and police officers help keep traffic safe and organized.",
    "ex1_vi": "Vào một ngày thường, đèn giao thông, biển báo đường bộ và cảnh sát giúp giữ cho giao thông an toàn và có trật tự."
  },
  {
    "id": 42,
    "word": "organized",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɔːɹɡɐnˌaɪzd/",
    "meaning": "có trật tự",
    "ex1": "Traffic lights, road signs, and police officers help keep traffic safe and organized.",
    "ex1_vi": "Đèn giao thông, biển báo đường bộ và cảnh sát giúp giữ cho giao thông an toàn và có trật tự."
  },
  {
    "id": 43,
    "word": "drivers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈaɪvɝz/",
    "meaning": "người lái xe",
    "ex1": "Drivers should stop at red lights and follow speed limits carefully.",
    "ex1_vi": "Người lái xe nên dừng ở đèn đỏ và tuân thủ giới hạn tốc độ cẩn thận."
  },
  {
    "id": 44,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "In daily city life, drivers should stop at red lights and follow speed limits carefully.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người lái xe nên dừng ở đèn đỏ và tuân thủ giới hạn tốc độ cẩn thận."
  },
  {
    "id": 45,
    "word": "stop",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈɑp/",
    "meaning": "dừng",
    "ex1": "For safe travel, drivers should stop at red lights and follow speed limits carefully.",
    "ex1_vi": "Để đi lại an toàn, người lái xe nên dừng ở đèn đỏ và tuân thủ giới hạn tốc độ cẩn thận."
  },
  {
    "id": 46,
    "word": "red",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛd/",
    "meaning": "đỏ",
    "ex1": "On busy city streets, drivers should stop at red lights and follow speed limits carefully.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, người lái xe nên dừng ở đèn đỏ và tuân thủ giới hạn tốc độ cẩn thận."
  },
  {
    "id": 47,
    "word": "follow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɑːloʊ/",
    "meaning": "theo",
    "ex1": "During everyday travel, drivers should stop at red lights and follow speed limits carefully.",
    "ex1_vi": "Trong việc đi lại hằng ngày, người lái xe nên dừng ở đèn đỏ và tuân thủ giới hạn tốc độ cẩn thận."
  },
  {
    "id": 48,
    "word": "speed",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈiːd/",
    "meaning": "tốc độ",
    "ex1": "For road safety, drivers should stop at red lights and follow speed limits carefully.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, người lái xe nên dừng ở đèn đỏ và tuân thủ giới hạn tốc độ cẩn thận."
  },
  {
    "id": 49,
    "word": "limits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɪmʌts/",
    "meaning": "giới hạn",
    "ex1": "In many neighborhoods, drivers should stop at red lights and follow speed limits carefully.",
    "ex1_vi": "Ở nhiều khu phố, người lái xe nên dừng ở đèn đỏ và tuân thủ giới hạn tốc độ cẩn thận."
  },
  {
    "id": 50,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛɹfəli/",
    "meaning": "một cách cẩn thận",
    "ex1": "On a normal weekday, drivers should stop at red lights and follow speed limits carefully.",
    "ex1_vi": "Vào một ngày thường, người lái xe nên dừng ở đèn đỏ và tuân thủ giới hạn tốc độ cẩn thận."
  },
  {
    "id": 51,
    "word": "pedestrians",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pʌdˈɛstriʌnz/",
    "meaning": "người đi bộ",
    "ex1": "Pedestrians need to use crosswalks before crossing busy roads every day.",
    "ex1_vi": "Người đi bộ cần sử dụng vạch qua đường trước khi băng qua những con đường đông đúc mỗi ngày."
  },
  {
    "id": 52,
    "word": "need",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nid/",
    "meaning": "cần",
    "ex1": "In daily city life, pedestrians need to use crosswalks before crossing busy roads every day.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người đi bộ cần sử dụng vạch qua đường trước khi băng qua những con đường đông đúc mỗi ngày."
  },
  {
    "id": 53,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "For safe travel, pedestrians need to use crosswalks before crossing busy roads every day.",
    "ex1_vi": "Để đi lại an toàn, người đi bộ cần sử dụng vạch qua đường trước khi băng qua những con đường đông đúc mỗi ngày."
  },
  {
    "id": 54,
    "word": "crosswalks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/krˈɑswˌɑks/",
    "meaning": "vạch qua đường",
    "ex1": "On busy city streets, pedestrians need to use crosswalks before crossing busy roads every day.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, người đi bộ cần sử dụng vạch qua đường trước khi băng qua những con đường đông đúc mỗi ngày."
  },
  {
    "id": 55,
    "word": "crossing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kɹˈɔsɪŋ/",
    "meaning": "băng qua",
    "ex1": "During everyday travel, pedestrians need to use crosswalks before crossing busy roads every day.",
    "ex1_vi": "Trong việc đi lại hằng ngày, người đi bộ cần sử dụng vạch qua đường trước khi băng qua những con đường đông đúc mỗi ngày."
  },
  {
    "id": 56,
    "word": "heavy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛvi/",
    "meaning": "đông đúc; nặng",
    "ex1": "Heavy traffic can cause delays and air pollution.",
    "ex1_vi": "Giao thông đông đúc có thể gây chậm trễ và ô nhiễm không khí."
  },
  {
    "id": 57,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "In daily city life, heavy traffic can cause delays and air pollution.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, giao thông đông đúc có thể gây chậm trễ và ô nhiễm không khí."
  },
  {
    "id": 58,
    "word": "cause",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈɑz/",
    "meaning": "gây ra",
    "ex1": "For safe travel, heavy traffic can cause delays and air pollution.",
    "ex1_vi": "Để đi lại an toàn, giao thông đông đúc có thể gây chậm trễ và ô nhiễm không khí."
  },
  {
    "id": 59,
    "word": "delays",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪlˈeɪz/",
    "meaning": "sự chậm trễ",
    "ex1": "On busy city streets, heavy traffic can cause delays and air pollution.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, giao thông đông đúc có thể gây chậm trễ và ô nhiễm không khí."
  },
  {
    "id": 60,
    "word": "air",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛr/",
    "meaning": "không khí",
    "ex1": "During everyday travel, heavy traffic can cause delays and air pollution.",
    "ex1_vi": "Trong việc đi lại hằng ngày, giao thông đông đúc có thể gây chậm trễ và ô nhiễm không khí."
  },
  {
    "id": 61,
    "word": "pollution",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pəlˈuːʃən/",
    "meaning": "ô nhiễm",
    "ex1": "For road safety, heavy traffic can cause delays and air pollution.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, giao thông đông đúc có thể gây chậm trễ và ô nhiễm không khí."
  },
  {
    "id": 62,
    "word": "public",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈʌblɪk/",
    "meaning": "công cộng",
    "ex1": "People should use public transport, ride bicycles, or walk short distances.",
    "ex1_vi": "Mọi người nên sử dụng phương tiện công cộng, đi xe đạp hoặc đi bộ những quãng đường ngắn."
  },
  {
    "id": 63,
    "word": "transport",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trænspˈɔrt/",
    "meaning": "phương tiện giao thông",
    "ex1": "In daily city life, people should use public transport, ride bicycles, or walk short distances.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, mọi người nên sử dụng phương tiện công cộng, đi xe đạp hoặc đi bộ những quãng đường ngắn."
  },
  {
    "id": 64,
    "word": "ride",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈaɪd/",
    "meaning": "đi; đi xe",
    "ex1": "For safe travel, people should use public transport, ride bicycles, or walk short distances.",
    "ex1_vi": "Để đi lại an toàn, mọi người nên sử dụng phương tiện công cộng, đi xe đạp hoặc đi bộ những quãng đường ngắn."
  },
  {
    "id": 65,
    "word": "walk",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɔk/",
    "meaning": "đi bộ",
    "ex1": "On busy city streets, people should use public transport, ride bicycles, or walk short distances.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, mọi người nên sử dụng phương tiện công cộng, đi xe đạp hoặc đi bộ những quãng đường ngắn."
  },
  {
    "id": 66,
    "word": "short",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɔɹt/",
    "meaning": "ngắn",
    "ex1": "During everyday travel, people should use public transport, ride bicycles, or walk short distances.",
    "ex1_vi": "Trong việc đi lại hằng ngày, mọi người nên sử dụng phương tiện công cộng, đi xe đạp hoặc đi bộ những quãng đường ngắn."
  },
  {
    "id": 67,
    "word": "distances",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪstənsəz/",
    "meaning": "khoảng cách",
    "ex1": "For road safety, people should use public transport, ride bicycles, or walk short distances.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, mọi người nên sử dụng phương tiện công cộng, đi xe đạp hoặc đi bộ những quãng đường ngắn."
  },
  {
    "id": 68,
    "word": "careful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɛɹfəl/",
    "meaning": "cẩn thận",
    "ex1": "Careful driving helps everyone travel safely and comfortably.",
    "ex1_vi": "Lái xe cẩn thận giúp mọi người di chuyển an toàn và thoải mái."
  },
  {
    "id": 69,
    "word": "driving",
    "type": "verb",
    "cat": "v",
    "phonetic": "/drˈaɪvɪŋ/",
    "meaning": "việc lái xe",
    "ex1": "In daily city life, careful driving helps everyone travel safely and comfortably.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, lái xe cẩn thận giúp mọi người di chuyển an toàn và thoải mái."
  },
  {
    "id": 70,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "For safe travel, careful driving helps everyone travel safely and comfortably.",
    "ex1_vi": "Để đi lại an toàn, lái xe cẩn thận giúp mọi người di chuyển an toàn và thoải mái."
  },
  {
    "id": 71,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ɛvriwʌn/",
    "meaning": "mọi người",
    "ex1": "On busy city streets, careful driving helps everyone travel safely and comfortably.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, lái xe cẩn thận giúp mọi người di chuyển an toàn và thoải mái."
  },
  {
    "id": 72,
    "word": "safely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/seɪfli/",
    "meaning": "một cách an toàn",
    "ex1": "During everyday travel, careful driving helps everyone travel safely and comfortably.",
    "ex1_vi": "Trong việc đi lại hằng ngày, lái xe cẩn thận giúp mọi người di chuyển an toàn và thoải mái."
  },
  {
    "id": 73,
    "word": "comfortably",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈʌmfɚtəbli/",
    "meaning": "một cách thoải mái",
    "ex1": "For road safety, careful driving helps everyone travel safely and comfortably.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, lái xe cẩn thận giúp mọi người di chuyển an toàn và thoải mái."
  },
  {
    "id": 74,
    "word": "transportation",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˌænspɝtˈeɪʃʌn/",
    "meaning": "giao thông; phương tiện đi lại",
    "ex1": "Public transportation is an important part of city life.",
    "ex1_vi": "Phương tiện giao thông công cộng là một phần quan trọng của cuộc sống thành phố."
  },
  {
    "id": 75,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔɹtənt/",
    "meaning": "quan trọng",
    "ex1": "In daily city life, public transportation is an important part of city life.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, phương tiện giao thông công cộng là một phần quan trọng của cuộc sống thành phố."
  },
  {
    "id": 76,
    "word": "part",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑɹt/",
    "meaning": "phần",
    "ex1": "For safe travel, public transportation is an important part of city life.",
    "ex1_vi": "Để đi lại an toàn, phương tiện giao thông công cộng là một phần quan trọng của cuộc sống thành phố."
  },
  {
    "id": 77,
    "word": "life",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪf/",
    "meaning": "cuộc sống",
    "ex1": "On busy city streets, public transportation is an important part of city life.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, phương tiện giao thông công cộng là một phần quan trọng của cuộc sống thành phố."
  },
  {
    "id": 78,
    "word": "take",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪk/",
    "meaning": "đi; lấy",
    "ex1": "Many people take buses, trains, or subways every day.",
    "ex1_vi": "Nhiều người đi xe buýt, tàu hỏa hoặc tàu điện ngầm mỗi ngày."
  },
  {
    "id": 79,
    "word": "trains",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈeɪnz/",
    "meaning": "tàu hỏa",
    "ex1": "In daily city life, many people take buses, trains, or subways every day.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, nhiều người đi xe buýt, tàu hỏa hoặc tàu điện ngầm mỗi ngày."
  },
  {
    "id": 80,
    "word": "subways",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈʌbwˌeɪz/",
    "meaning": "tàu điện ngầm",
    "ex1": "For safe travel, many people take buses, trains, or subways every day.",
    "ex1_vi": "Để đi lại an toàn, nhiều người đi xe buýt, tàu hỏa hoặc tàu điện ngầm mỗi ngày."
  },
  {
    "id": 81,
    "word": "carry",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈæri/",
    "meaning": "chở; mang",
    "ex1": "These vehicles carry many passengers and help reduce traffic on busy roads.",
    "ex1_vi": "Những phương tiện này chở nhiều hành khách và giúp giảm giao thông trên những con đường đông đúc."
  },
  {
    "id": 82,
    "word": "passengers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈæsʌndʒɝz/",
    "meaning": "hành khách",
    "ex1": "In daily city life, these vehicles carry many passengers and help reduce traffic on busy roads.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, những phương tiện này chở nhiều hành khách và giúp giảm giao thông trên những con đường đông đúc."
  },
  {
    "id": 83,
    "word": "reduce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹədˈus/",
    "meaning": "giảm",
    "ex1": "For safe travel, these vehicles carry many passengers and help reduce traffic on busy roads.",
    "ex1_vi": "Để đi lại an toàn, những phương tiện này chở nhiều hành khách và giúp giảm giao thông trên những con đường đông đúc."
  },
  {
    "id": 84,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/juʒəwəli/",
    "meaning": "thường",
    "ex1": "They are usually cheaper than driving private cars every day.",
    "ex1_vi": "Chúng thường rẻ hơn so với việc lái ô tô riêng mỗi ngày."
  },
  {
    "id": 85,
    "word": "cheaper",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/tʃˈipɝ/",
    "meaning": "rẻ hơn",
    "ex1": "In daily city life, they are usually cheaper than driving private cars every day.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, chúng thường rẻ hơn so với việc lái ô tô riêng mỗi ngày."
  },
  {
    "id": 86,
    "word": "than",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ðæn/",
    "meaning": "hơn",
    "ex1": "For safe travel, they are usually cheaper than driving private cars every day.",
    "ex1_vi": "Để đi lại an toàn, chúng thường rẻ hơn so với việc lái ô tô riêng mỗi ngày."
  },
  {
    "id": 87,
    "word": "private",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/prˈaɪvʌt/",
    "meaning": "riêng; cá nhân",
    "ex1": "On busy city streets, they are usually cheaper than driving private cars every day.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, chúng thường rẻ hơn so với việc lái ô tô riêng mỗi ngày."
  },
  {
    "id": 88,
    "word": "wait",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈeɪt/",
    "meaning": "chờ",
    "ex1": "Passengers should wait patiently at bus stops or train stations.",
    "ex1_vi": "Hành khách nên kiên nhẫn chờ tại trạm xe buýt hoặc nhà ga."
  },
  {
    "id": 89,
    "word": "patiently",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/pˈeɪʃʌntli/",
    "meaning": "một cách kiên nhẫn",
    "ex1": "In daily city life, passengers should wait patiently at bus stops or train stations.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, hành khách nên kiên nhẫn chờ tại trạm xe buýt hoặc nhà ga."
  },
  {
    "id": 90,
    "word": "bus",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʌs/",
    "meaning": "xe buýt",
    "ex1": "For safe travel, passengers should wait patiently at bus stops or train stations.",
    "ex1_vi": "Để đi lại an toàn, hành khách nên kiên nhẫn chờ tại trạm xe buýt hoặc nhà ga."
  },
  {
    "id": 91,
    "word": "stops",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈɑps/",
    "meaning": "trạm; điểm dừng",
    "ex1": "On busy city streets, passengers should wait patiently at bus stops or train stations.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, hành khách nên kiên nhẫn chờ tại trạm xe buýt hoặc nhà ga."
  },
  {
    "id": 92,
    "word": "train",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tɹˈeɪn/",
    "meaning": "tàu hỏa",
    "ex1": "During everyday travel, passengers should wait patiently at bus stops or train stations.",
    "ex1_vi": "Trong việc đi lại hằng ngày, hành khách nên kiên nhẫn chờ tại trạm xe buýt hoặc nhà ga."
  },
  {
    "id": 93,
    "word": "stations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈeɪʃənz/",
    "meaning": "trạm",
    "ex1": "For road safety, passengers should wait patiently at bus stops or train stations.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, hành khách nên kiên nhẫn chờ tại trạm xe buýt hoặc nhà ga."
  },
  {
    "id": 94,
    "word": "buy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈaɪ/",
    "meaning": "mua",
    "ex1": "They need to buy tickets, stand in line, and respect other travelers.",
    "ex1_vi": "Họ cần mua vé, xếp hàng và tôn trọng những người đi lại khác."
  },
  {
    "id": 95,
    "word": "tickets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɪkʌts/",
    "meaning": "vé",
    "ex1": "In daily city life, they need to buy tickets, stand in line, and respect other travelers.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, họ cần mua vé, xếp hàng và tôn trọng những người đi lại khác."
  },
  {
    "id": 96,
    "word": "stand",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈænd/",
    "meaning": "đứng",
    "ex1": "For safe travel, they need to buy tickets, stand in line, and respect other travelers.",
    "ex1_vi": "Để đi lại an toàn, họ cần mua vé, xếp hàng và tôn trọng những người đi lại khác."
  },
  {
    "id": 97,
    "word": "line",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪn/",
    "meaning": "hàng",
    "ex1": "On busy city streets, they need to buy tickets, stand in line, and respect other travelers.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, họ cần mua vé, xếp hàng và tôn trọng những người đi lại khác."
  },
  {
    "id": 98,
    "word": "respect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪspˈɛkt/",
    "meaning": "tôn trọng",
    "ex1": "During everyday travel, they need to buy tickets, stand in line, and respect other travelers.",
    "ex1_vi": "Trong việc đi lại hằng ngày, họ cần mua vé, xếp hàng và tôn trọng những người đi lại khác."
  },
  {
    "id": 99,
    "word": "other",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ʌðɚ/",
    "meaning": "khác",
    "ex1": "For road safety, they need to buy tickets, stand in line, and respect other travelers.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, họ cần mua vé, xếp hàng và tôn trọng những người đi lại khác."
  },
  {
    "id": 100,
    "word": "travelers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈævʌlɝz/",
    "meaning": "người đi lại",
    "ex1": "In many neighborhoods, they need to buy tickets, stand in line, and respect other travelers.",
    "ex1_vi": "Ở nhiều khu phố, họ cần mua vé, xếp hàng và tôn trọng những người đi lại khác."
  },
  {
    "id": 101,
    "word": "giving",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvɪŋ/",
    "meaning": "việc nhường; việc cho",
    "ex1": "Giving seats to older people or pregnant women shows kindness and good manners.",
    "ex1_vi": "Nhường ghế cho người lớn tuổi hoặc phụ nữ mang thai thể hiện lòng tốt và cách cư xử lịch sự."
  },
  {
    "id": 102,
    "word": "seats",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈits/",
    "meaning": "ghế",
    "ex1": "In daily city life, giving seats to older people or pregnant women shows kindness and good manners.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, nhường ghế cho người lớn tuổi hoặc phụ nữ mang thai thể hiện lòng tốt và cách cư xử lịch sự."
  },
  {
    "id": 103,
    "word": "older",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/ˈoʊldɝ/",
    "meaning": "lớn tuổi hơn",
    "ex1": "For safe travel, giving seats to older people or pregnant women shows kindness and good manners.",
    "ex1_vi": "Để đi lại an toàn, nhường ghế cho người lớn tuổi hoặc phụ nữ mang thai thể hiện lòng tốt và cách cư xử lịch sự."
  },
  {
    "id": 104,
    "word": "pregnant",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/prˈɛɡnʌnt/",
    "meaning": "mang thai",
    "ex1": "On busy city streets, giving seats to older people or pregnant women shows kindness and good manners.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, nhường ghế cho người lớn tuổi hoặc phụ nữ mang thai thể hiện lòng tốt và cách cư xử lịch sự."
  },
  {
    "id": 105,
    "word": "women",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɪmʌn/",
    "meaning": "phụ nữ",
    "ex1": "During everyday travel, giving seats to older people or pregnant women shows kindness and good manners.",
    "ex1_vi": "Trong việc đi lại hằng ngày, nhường ghế cho người lớn tuổi hoặc phụ nữ mang thai thể hiện lòng tốt và cách cư xử lịch sự."
  },
  {
    "id": 106,
    "word": "shows",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈoʊz/",
    "meaning": "thể hiện",
    "ex1": "For road safety, giving seats to older people or pregnant women shows kindness and good manners.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, nhường ghế cho người lớn tuổi hoặc phụ nữ mang thai thể hiện lòng tốt và cách cư xử lịch sự."
  },
  {
    "id": 107,
    "word": "kindness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈaɪndnʌs/",
    "meaning": "lòng tốt",
    "ex1": "In many neighborhoods, giving seats to older people or pregnant women shows kindness and good manners.",
    "ex1_vi": "Ở nhiều khu phố, nhường ghế cho người lớn tuổi hoặc phụ nữ mang thai thể hiện lòng tốt và cách cư xử lịch sự."
  },
  {
    "id": 108,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "On a normal weekday, giving seats to older people or pregnant women shows kindness and good manners.",
    "ex1_vi": "Vào một ngày thường, nhường ghế cho người lớn tuổi hoặc phụ nữ mang thai thể hiện lòng tốt và cách cư xử lịch sự."
  },
  {
    "id": 109,
    "word": "manners",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈænɝz/",
    "meaning": "cách cư xử",
    "ex1": "Giving seats to older people or pregnant women shows kindness and good manners.",
    "ex1_vi": "Nhường ghế cho người lớn tuổi hoặc phụ nữ mang thai thể hiện lòng tốt và cách cư xử lịch sự."
  },
  {
    "id": 110,
    "word": "saves",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪvz/",
    "meaning": "tiết kiệm",
    "ex1": "Public transportation saves time, fuel, and money for many families.",
    "ex1_vi": "Phương tiện giao thông công cộng tiết kiệm thời gian, nhiên liệu và tiền bạc cho nhiều gia đình."
  },
  {
    "id": 111,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "In daily city life, public transportation saves time, fuel, and money for many families.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, phương tiện giao thông công cộng tiết kiệm thời gian, nhiên liệu và tiền bạc cho nhiều gia đình."
  },
  {
    "id": 112,
    "word": "fuel",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fjˈuʌl/",
    "meaning": "nhiên liệu",
    "ex1": "For safe travel, public transportation saves time, fuel, and money for many families.",
    "ex1_vi": "Để đi lại an toàn, phương tiện giao thông công cộng tiết kiệm thời gian, nhiên liệu và tiền bạc cho nhiều gia đình."
  },
  {
    "id": 113,
    "word": "money",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌni/",
    "meaning": "tiền",
    "ex1": "On busy city streets, public transportation saves time, fuel, and money for many families.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, phương tiện giao thông công cộng tiết kiệm thời gian, nhiên liệu và tiền bạc cho nhiều gia đình."
  },
  {
    "id": 114,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fæməliz/",
    "meaning": "gia đình",
    "ex1": "During everyday travel, public transportation saves time, fuel, and money for many families.",
    "ex1_vi": "Trong việc đi lại hằng ngày, phương tiện giao thông công cộng tiết kiệm thời gian, nhiên liệu và tiền bạc cho nhiều gia đình."
  },
  {
    "id": 115,
    "word": "more",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mɔr/",
    "meaning": "nhiều hơn",
    "ex1": "More people should use it often because cleaner transportation helps protect the environment and improve city life.",
    "ex1_vi": "Nhiều người nên sử dụng nó thường xuyên vì phương tiện sạch hơn giúp bảo vệ môi trường và cải thiện cuộc sống thành phố."
  },
  {
    "id": 116,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkɔz/",
    "meaning": "bởi vì",
    "ex1": "In daily city life, more people should use it often because cleaner transportation helps protect the environment and improve city life.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, nhiều người nên sử dụng nó thường xuyên vì phương tiện sạch hơn giúp bảo vệ môi trường và cải thiện cuộc sống thành phố."
  },
  {
    "id": 117,
    "word": "cleaner",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈklinər/",
    "meaning": "sạch hơn",
    "ex1": "For safe travel, more people should use it often because cleaner transportation helps protect the environment and improve city life.",
    "ex1_vi": "Để đi lại an toàn, nhiều người nên sử dụng nó thường xuyên vì phương tiện sạch hơn giúp bảo vệ môi trường và cải thiện cuộc sống thành phố."
  },
  {
    "id": 118,
    "word": "protect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹətˈɛkt/",
    "meaning": "bảo vệ",
    "ex1": "On busy city streets, more people should use it often because cleaner transportation helps protect the environment and improve city life.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, nhiều người nên sử dụng nó thường xuyên vì phương tiện sạch hơn giúp bảo vệ môi trường và cải thiện cuộc sống thành phố."
  },
  {
    "id": 119,
    "word": "environment",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪnvaɪrənmənt/",
    "meaning": "môi trường",
    "ex1": "During everyday travel, more people should use it often because cleaner transportation helps protect the environment and improve city life.",
    "ex1_vi": "Trong việc đi lại hằng ngày, nhiều người nên sử dụng nó thường xuyên vì phương tiện sạch hơn giúp bảo vệ môi trường và cải thiện cuộc sống thành phố."
  },
  {
    "id": 120,
    "word": "improve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɪmpɹˈuːv/",
    "meaning": "cải thiện",
    "ex1": "For road safety, more people should use it often because cleaner transportation helps protect the environment and improve city life.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, nhiều người nên sử dụng nó thường xuyên vì phương tiện sạch hơn giúp bảo vệ môi trường và cải thiện cuộc sống thành phố."
  },
  {
    "id": 121,
    "word": "rules",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈulz/",
    "meaning": "quy tắc",
    "ex1": "Traffic rules help keep everyone safe on the roads.",
    "ex1_vi": "Luật giao thông giúp giữ an toàn cho mọi người trên đường."
  },
  {
    "id": 122,
    "word": "cyclists",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaɪkʌlɪsts/",
    "meaning": "người đi xe đạp",
    "ex1": "Drivers, cyclists, and pedestrians should understand and follow these rules every day.",
    "ex1_vi": "Người lái xe, người đi xe đạp và người đi bộ nên hiểu và tuân theo các quy tắc này mỗi ngày."
  },
  {
    "id": 123,
    "word": "understand",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌʌndɝstˈænd/",
    "meaning": "hiểu",
    "ex1": "In daily city life, drivers, cyclists, and pedestrians should understand and follow these rules every day.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người lái xe, người đi xe đạp và người đi bộ nên hiểu và tuân theo các quy tắc này mỗi ngày."
  },
  {
    "id": 124,
    "word": "lane",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈeɪn/",
    "meaning": "làn đường",
    "ex1": "Road signs, traffic lights, and lane markings give important directions for safe travel in every neighborhood.",
    "ex1_vi": "Biển báo đường bộ, đèn giao thông và vạch phân làn đưa ra những chỉ dẫn quan trọng cho việc di chuyển an toàn trong mọi khu phố."
  },
  {
    "id": 125,
    "word": "markings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɑrkɪŋz/",
    "meaning": "vạch kẻ",
    "ex1": "In daily city life, road signs, traffic lights, and lane markings give important directions for safe travel in every neighborhood.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, biển báo đường bộ, đèn giao thông và vạch phân làn đưa ra những chỉ dẫn quan trọng cho việc di chuyển an toàn trong mọi khu phố."
  },
  {
    "id": 126,
    "word": "give",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪv/",
    "meaning": "mang lại",
    "ex1": "For safe travel, road signs, traffic lights, and lane markings give important directions for safe travel in every neighborhood.",
    "ex1_vi": "Để đi lại an toàn, biển báo đường bộ, đèn giao thông và vạch phân làn đưa ra những chỉ dẫn quan trọng cho việc di chuyển an toàn trong mọi khu phố."
  },
  {
    "id": 127,
    "word": "directions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɚɹˈɛkʃənz/",
    "meaning": "chỉ dẫn",
    "ex1": "On busy city streets, road signs, traffic lights, and lane markings give important directions for safe travel in every neighborhood.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, biển báo đường bộ, đèn giao thông và vạch phân làn đưa ra những chỉ dẫn quan trọng cho việc di chuyển an toàn trong mọi khu phố."
  },
  {
    "id": 128,
    "word": "neighborhood",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈeɪbɝhˌʊd/",
    "meaning": "khu phố",
    "ex1": "During everyday travel, road signs, traffic lights, and lane markings give important directions for safe travel in every neighborhood.",
    "ex1_vi": "Trong việc đi lại hằng ngày, biển báo đường bộ, đèn giao thông và vạch phân làn đưa ra những chỉ dẫn quan trọng cho việc di chuyển an toàn trong mọi khu phố."
  },
  {
    "id": 129,
    "word": "must",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈʌst/",
    "meaning": "phải",
    "ex1": "Drivers must wear seat belts and avoid using mobile phones while driving.",
    "ex1_vi": "Người lái xe phải thắt dây an toàn và tránh sử dụng điện thoại di động khi lái xe."
  },
  {
    "id": 130,
    "word": "wear",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɛɹ/",
    "meaning": "mặc; đội; thắt",
    "ex1": "In daily city life, drivers must wear seat belts and avoid using mobile phones while driving.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người lái xe phải thắt dây an toàn và tránh sử dụng điện thoại di động khi lái xe."
  },
  {
    "id": 131,
    "word": "seat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈit/",
    "meaning": "ghế",
    "ex1": "For safe travel, drivers must wear seat belts and avoid using mobile phones while driving.",
    "ex1_vi": "Để đi lại an toàn, người lái xe phải thắt dây an toàn và tránh sử dụng điện thoại di động khi lái xe."
  },
  {
    "id": 132,
    "word": "belts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɛlts/",
    "meaning": "dây đai",
    "ex1": "On busy city streets, drivers must wear seat belts and avoid using mobile phones while driving.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, người lái xe phải thắt dây an toàn và tránh sử dụng điện thoại di động khi lái xe."
  },
  {
    "id": 133,
    "word": "avoid",
    "type": "verb",
    "cat": "v",
    "phonetic": "/əvˈɔɪd/",
    "meaning": "tránh",
    "ex1": "During everyday travel, drivers must wear seat belts and avoid using mobile phones while driving.",
    "ex1_vi": "Trong việc đi lại hằng ngày, người lái xe phải thắt dây an toàn và tránh sử dụng điện thoại di động khi lái xe."
  },
  {
    "id": 134,
    "word": "using",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzɪŋ/",
    "meaning": "việc sử dụng",
    "ex1": "For road safety, drivers must wear seat belts and avoid using mobile phones while driving.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, người lái xe phải thắt dây an toàn và tránh sử dụng điện thoại di động khi lái xe."
  },
  {
    "id": 135,
    "word": "mobile",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈoʊbʌl/",
    "meaning": "di động",
    "ex1": "In many neighborhoods, drivers must wear seat belts and avoid using mobile phones while driving.",
    "ex1_vi": "Ở nhiều khu phố, người lái xe phải thắt dây an toàn và tránh sử dụng điện thoại di động khi lái xe."
  },
  {
    "id": 136,
    "word": "phones",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈoʊnz/",
    "meaning": "điện thoại",
    "ex1": "On a normal weekday, drivers must wear seat belts and avoid using mobile phones while driving.",
    "ex1_vi": "Vào một ngày thường, người lái xe phải thắt dây an toàn và tránh sử dụng điện thoại di động khi lái xe."
  },
  {
    "id": 137,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/waɪl/",
    "meaning": "trong khi",
    "ex1": "Drivers must wear seat belts and avoid using mobile phones while driving.",
    "ex1_vi": "Người lái xe phải thắt dây an toàn và tránh sử dụng điện thoại di động khi lái xe."
  },
  {
    "id": 138,
    "word": "motorbike",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈoʊtɝbˌaɪk/",
    "meaning": "xe máy",
    "ex1": "Motorbike riders should always wear helmets.",
    "ex1_vi": "Người đi xe máy nên luôn đội mũ bảo hiểm."
  },
  {
    "id": 139,
    "word": "riders",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪdɝz/",
    "meaning": "người đi xe",
    "ex1": "In daily city life, motorbike riders should always wear helmets.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người đi xe máy nên luôn đội mũ bảo hiểm."
  },
  {
    "id": 140,
    "word": "always",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlwˌeɪz/",
    "meaning": "luôn luôn",
    "ex1": "For safe travel, motorbike riders should always wear helmets.",
    "ex1_vi": "Để đi lại an toàn, người đi xe máy nên luôn đội mũ bảo hiểm."
  },
  {
    "id": 141,
    "word": "helmets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛlmʌts/",
    "meaning": "mũ bảo hiểm",
    "ex1": "On busy city streets, motorbike riders should always wear helmets.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, người đi xe máy nên luôn đội mũ bảo hiểm."
  },
  {
    "id": 142,
    "word": "cross",
    "type": "verb",
    "cat": "v",
    "phonetic": "/krˈɔs/",
    "meaning": "băng qua",
    "ex1": "Pedestrians need to cross at crosswalks and wait for green lights before crossing busy streets safely.",
    "ex1_vi": "Người đi bộ cần băng qua tại vạch qua đường và chờ đèn xanh trước khi sang những con phố đông đúc một cách an toàn."
  },
  {
    "id": 143,
    "word": "green",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈin/",
    "meaning": "xanh",
    "ex1": "In daily city life, pedestrians need to cross at crosswalks and wait for green lights before crossing busy streets safely.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người đi bộ cần băng qua tại vạch qua đường và chờ đèn xanh trước khi sang những con phố đông đúc một cách an toàn."
  },
  {
    "id": 144,
    "word": "following",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɑloʊɪŋ/",
    "meaning": "việc tuân theo",
    "ex1": "Following traffic rules reduces accidents and protects many lives.",
    "ex1_vi": "Tuân thủ luật giao thông làm giảm tai nạn và bảo vệ nhiều sinh mạng."
  },
  {
    "id": 145,
    "word": "reduces",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪdˈuːsɪz/",
    "meaning": "làm giảm",
    "ex1": "In daily city life, following traffic rules reduces accidents and protects many lives.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, tuân thủ luật giao thông làm giảm tai nạn và bảo vệ nhiều sinh mạng."
  },
  {
    "id": 146,
    "word": "accidents",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈæksʌdʌnts/",
    "meaning": "tai nạn",
    "ex1": "For safe travel, following traffic rules reduces accidents and protects many lives.",
    "ex1_vi": "Để đi lại an toàn, tuân thủ luật giao thông làm giảm tai nạn và bảo vệ nhiều sinh mạng."
  },
  {
    "id": 147,
    "word": "protects",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌtˈɛkts/",
    "meaning": "bảo vệ",
    "ex1": "On busy city streets, following traffic rules reduces accidents and protects many lives.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, tuân thủ luật giao thông làm giảm tai nạn và bảo vệ nhiều sinh mạng."
  },
  {
    "id": 148,
    "word": "lives",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɪvz/",
    "meaning": "sinh mạng",
    "ex1": "During everyday travel, following traffic rules reduces accidents and protects many lives.",
    "ex1_vi": "Trong việc đi lại hằng ngày, tuân thủ luật giao thông làm giảm tai nạn và bảo vệ nhiều sinh mạng."
  },
  {
    "id": 149,
    "word": "patient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈeɪʃənt/",
    "meaning": "kiên nhẫn",
    "ex1": "Careful drivers, patient pedestrians, and responsible cyclists make every trip safer.",
    "ex1_vi": "Người lái xe cẩn thận, người đi bộ kiên nhẫn và người đi xe đạp có trách nhiệm làm cho mỗi chuyến đi an toàn hơn."
  },
  {
    "id": 150,
    "word": "responsible",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rispˈɑnsʌbʌl/",
    "meaning": "có trách nhiệm",
    "ex1": "In daily city life, careful drivers, patient pedestrians, and responsible cyclists make every trip safer.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người lái xe cẩn thận, người đi bộ kiên nhẫn và người đi xe đạp có trách nhiệm làm cho mỗi chuyến đi an toàn hơn."
  },
  {
    "id": 151,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/meɪk/",
    "meaning": "làm cho",
    "ex1": "For safe travel, careful drivers, patient pedestrians, and responsible cyclists make every trip safer.",
    "ex1_vi": "Để đi lại an toàn, người lái xe cẩn thận, người đi bộ kiên nhẫn và người đi xe đạp có trách nhiệm làm cho mỗi chuyến đi an toàn hơn."
  },
  {
    "id": 152,
    "word": "trip",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈɪp/",
    "meaning": "chuyến đi",
    "ex1": "On busy city streets, careful drivers, patient pedestrians, and responsible cyclists make every trip safer.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, người lái xe cẩn thận, người đi bộ kiên nhẫn và người đi xe đạp có trách nhiệm làm cho mỗi chuyến đi an toàn hơn."
  },
  {
    "id": 153,
    "word": "safer",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/seɪfɚ/",
    "meaning": "an toàn hơn",
    "ex1": "During everyday travel, careful drivers, patient pedestrians, and responsible cyclists make every trip safer.",
    "ex1_vi": "Trong việc đi lại hằng ngày, người lái xe cẩn thận, người đi bộ kiên nhẫn và người đi xe đạp có trách nhiệm làm cho mỗi chuyến đi an toàn hơn."
  },
  {
    "id": 154,
    "word": "habits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hæbəts/",
    "meaning": "thói quen",
    "ex1": "Good habits create cleaner, safer, and friendlier cities for everyone.",
    "ex1_vi": "Những thói quen tốt tạo ra các thành phố sạch hơn, an toàn hơn và thân thiện hơn cho mọi người."
  },
  {
    "id": 155,
    "word": "create",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪt/",
    "meaning": "tạo ra",
    "ex1": "In daily city life, good habits create cleaner, safer, and friendlier cities for everyone.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, những thói quen tốt tạo ra các thành phố sạch hơn, an toàn hơn và thân thiện hơn cho mọi người."
  },
  {
    "id": 156,
    "word": "friendlier",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/frɛndliɚ/",
    "meaning": "thân thiện hơn",
    "ex1": "For safe travel, good habits create cleaner, safer, and friendlier cities for everyone.",
    "ex1_vi": "Để đi lại an toàn, những thói quen tốt tạo ra các thành phố sạch hơn, an toàn hơn và thân thiện hơn cho mọi người."
  },
  {
    "id": 157,
    "word": "cities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪtiz/",
    "meaning": "các thành phố",
    "ex1": "On busy city streets, good habits create cleaner, safer, and friendlier cities for everyone.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, những thói quen tốt tạo ra các thành phố sạch hơn, an toàn hơn và thân thiện hơn cho mọi người."
  }
];

const newReadingVocabOrder = [
  "city",
  "traffic",
  "busy",
  "every",
  "day",
  "especially",
  "morning",
  "and",
  "evening",
  "many",
  "people",
  "travel",
  "work",
  "school",
  "or",
  "market",
  "cars",
  "buses",
  "motorbikes",
  "bicycles",
  "trucks",
  "share",
  "same",
  "roads",
  "streets",
  "often",
  "become",
  "crowded",
  "rush",
  "hours",
  "waiting",
  "vehicles",
  "together",
  "lights",
  "road",
  "signs",
  "police",
  "officers",
  "help",
  "keep",
  "safe",
  "organized",
  "drivers",
  "should",
  "stop",
  "red",
  "follow",
  "speed",
  "limits",
  "carefully",
  "pedestrians",
  "need",
  "use",
  "crosswalks",
  "crossing",
  "heavy",
  "can",
  "cause",
  "delays",
  "air",
  "pollution",
  "public",
  "transport",
  "ride",
  "walk",
  "short",
  "distances",
  "careful",
  "driving",
  "helps",
  "everyone",
  "safely",
  "comfortably",
  "transportation",
  "important",
  "part",
  "life",
  "take",
  "trains",
  "subways",
  "carry",
  "passengers",
  "reduce",
  "usually",
  "cheaper",
  "than",
  "private",
  "wait",
  "patiently",
  "bus",
  "stops",
  "train",
  "stations",
  "buy",
  "tickets",
  "stand",
  "line",
  "respect",
  "other",
  "travelers",
  "giving",
  "seats",
  "older",
  "pregnant",
  "women",
  "shows",
  "kindness",
  "good",
  "manners",
  "saves",
  "time",
  "fuel",
  "money",
  "families",
  "more",
  "because",
  "cleaner",
  "protect",
  "environment",
  "improve",
  "rules",
  "cyclists",
  "understand",
  "lane",
  "markings",
  "give",
  "directions",
  "neighborhood",
  "must",
  "wear",
  "seat",
  "belts",
  "avoid",
  "using",
  "mobile",
  "phones",
  "while",
  "motorbike",
  "riders",
  "always",
  "helmets",
  "cross",
  "green",
  "following",
  "reduces",
  "accidents",
  "protects",
  "lives",
  "patient",
  "responsible",
  "make",
  "trip",
  "safer",
  "habits",
  "create",
  "friendlier",
  "cities"
];
