const newEssayData = [
  {
    "text": "1. Pop Music – Nhạc Pop\nPop music is one of the most popular types of music in the world. It usually has a clear beat, simple words, and an easy melody. Many young people enjoy listening to pop songs daily.\n\nPop singers often sing about love, friendship, dreams, and daily life. Their songs are easy to remember, so people can quickly sing along. Music videos also help pop artists become famous.\n\nPop music is played on radio, television, social media, and music apps. It is common at parties, shops, schools, and public events.\n\nI like pop music because it makes me feel relaxed and happy. It is enjoyable, modern, and suitable for many different listeners.",
    "vi": "1. Nhạc Pop\nNhạc pop là một trong những thể loại âm nhạc phổ biến nhất trên thế giới. Nó thường có nhịp rõ ràng, lời đơn giản và giai điệu dễ nghe. Nhiều người trẻ thích nghe các bài hát pop hằng ngày.\n\nCa sĩ pop thường hát về tình yêu, tình bạn, ước mơ và cuộc sống hằng ngày. Các bài hát của họ dễ nhớ nên mọi người có thể nhanh chóng hát theo. Video âm nhạc cũng giúp nghệ sĩ pop trở nên nổi tiếng.\n\nNhạc pop được phát trên radio, truyền hình, mạng xã hội và các ứng dụng âm nhạc. Nó phổ biến ở các bữa tiệc, cửa hàng, trường học và sự kiện công cộng.\n\nTôi thích nhạc pop vì nó làm tôi cảm thấy thư giãn và vui vẻ. Nó thú vị, hiện đại và phù hợp với nhiều người nghe khác nhau."
  },
  {
    "text": "2. Rock Music – Nhạc Rock\nRock music is a strong and energetic type of music. It often uses electric guitars, bass guitars, drums, and powerful singing. The sound can be loud, exciting, and full of energy.\n\nRock songs may talk about freedom, youth, love, problems, or social change. Some songs are fast and wild, while others are slower and more emotional.\n\nRock bands usually have several members. Each person plays an instrument or sings. During live concerts, musicians move around the stage and connect with the audience.\n\nMany people around the world like rock music because it feels powerful and honest. It can give listeners real courage, fresh energy, and a strong feeling of freedom.",
    "vi": "2. Nhạc Rock\nNhạc rock là một thể loại âm nhạc mạnh mẽ và tràn đầy năng lượng. Nó thường sử dụng guitar điện, guitar bass, trống và giọng hát mạnh. Âm thanh có thể lớn, hào hứng và đầy năng lượng.\n\nCác bài hát rock có thể nói về tự do, tuổi trẻ, tình yêu, vấn đề hoặc thay đổi xã hội. Một số bài nhanh và hoang dã, trong khi những bài khác chậm hơn và giàu cảm xúc hơn.\n\nCác ban nhạc rock thường có vài thành viên. Mỗi người chơi một nhạc cụ hoặc hát. Trong các buổi hòa nhạc trực tiếp, nhạc sĩ di chuyển quanh sân khấu và kết nối với khán giả.\n\nNhiều người trên thế giới thích nhạc rock vì nó tạo cảm giác mạnh mẽ và chân thật. Nó có thể mang lại cho người nghe lòng can đảm thực sự, năng lượng mới và cảm giác tự do mạnh mẽ."
  },
  {
    "text": "3. Classical Music – Nhạc Cổ điển\nClassical music is a beautiful and traditional type of music. It is often played with the piano, violin, cello, flute, and other instruments in an orchestra. The sound can be soft, strong, peaceful, or dramatic.\n\nMany famous classical pieces were written hundreds of years ago. Composers such as Mozart and Beethoven created music that people still enjoy today.\n\nClassical music is often performed in concert halls, theaters, schools, and special events. Musicians must practise carefully because the pieces can be long and difficult.\n\nI really enjoy classical music because it helps me relax and think clearly. It can also improve concentration while studying, reading, writing, or working quietly each day.",
    "vi": "3. Nhạc Cổ điển\nNhạc cổ điển là một thể loại âm nhạc đẹp và truyền thống. Nó thường được chơi bằng piano, violin, cello, sáo và các nhạc cụ khác trong dàn nhạc. Âm thanh có thể nhẹ nhàng, mạnh mẽ, yên bình hoặc kịch tính.\n\nNhiều tác phẩm cổ điển nổi tiếng được viết từ hàng trăm năm trước. Các nhà soạn nhạc như Mozart và Beethoven đã tạo ra âm nhạc mà mọi người vẫn thưởng thức ngày nay.\n\nNhạc cổ điển thường được biểu diễn trong phòng hòa nhạc, nhà hát, trường học và các sự kiện đặc biệt. Nhạc sĩ phải luyện tập cẩn thận vì các tác phẩm có thể dài và khó.\n\nTôi rất thích nhạc cổ điển vì nó giúp tôi thư giãn và suy nghĩ rõ ràng. Nó cũng có thể cải thiện sự tập trung khi học, đọc, viết hoặc làm việc yên tĩnh mỗi ngày."
  }
];
