const newEssayData = [
  {
    "text": "4. Jazz Music – Nhạc Jazz\nJazz music is a creative and emotional type of music. It often uses the piano, trumpet, saxophone, drums, and double bass. Jazz has flexible rhythms and a special sound that is easy to recognize.\n\nOne important part of jazz is improvisation. This means musicians create some music while they are playing. Each performance can sound different and fresh.\n\nJazz began in the United States and later became popular in many countries. People often listen to jazz in clubs, cafes, theaters, and music festivals.\n\nI like jazz because it feels free and full of life. It can be calm, joyful, exciting, or sad, depending on the song and the performer’s style.",
    "vi": "4. Nhạc Jazz\nNhạc jazz là một thể loại âm nhạc sáng tạo và giàu cảm xúc. Nó thường sử dụng piano, kèn trumpet, saxophone, trống và contrabass. Jazz có nhịp điệu linh hoạt và âm thanh đặc biệt dễ nhận biết.\n\nMột phần quan trọng của jazz là sự ứng tác. Điều này có nghĩa là nhạc sĩ tạo ra một phần âm nhạc ngay khi đang chơi. Mỗi phần biểu diễn có thể nghe khác nhau và mới mẻ.\n\nJazz bắt đầu ở Hoa Kỳ và sau đó trở nên phổ biến ở nhiều quốc gia. Mọi người thường nghe jazz trong câu lạc bộ, quán cà phê, nhà hát và lễ hội âm nhạc.\n\nTôi thích jazz vì nó tạo cảm giác tự do và tràn đầy sức sống. Nó có thể bình yên, vui tươi, hào hứng hoặc buồn, tùy thuộc vào bài hát và phong cách của người biểu diễn."
  },
  {
    "text": "5. Hip-hop Music – Nhạc Hip-hop\nHip-hop music combines rap, strong beats, and electronic sounds. Rappers speak or sing words in rhythm instead of using a normal melody. The music is modern, direct, fresh, and often very energetic.\n\nHip-hop songs may talk about daily life, family, friendship, success, problems, and society. Some artists use music to share personal stories or important messages.\n\nHip-hop culture also includes dance, fashion, and street art. Breakdancing and graffiti are closely connected with this music style.\n\nMany young people around the world enjoy hip-hop because it is powerful and expressive today. It often helps artists speak honestly about their lives, and it gives listeners energy, confidence, and a sense of connection.",
    "vi": "5. Nhạc Hip-hop\nNhạc hip-hop kết hợp rap, nhịp mạnh và âm thanh điện tử. Rapper nói hoặc hát các từ theo nhịp thay vì sử dụng giai điệu thông thường. Âm nhạc hiện đại, trực tiếp, mới mẻ và thường rất giàu năng lượng.\n\nCác bài hip-hop có thể nói về cuộc sống hằng ngày, gia đình, tình bạn, thành công, vấn đề và xã hội. Một số nghệ sĩ dùng âm nhạc để chia sẻ câu chuyện cá nhân hoặc thông điệp quan trọng.\n\nVăn hóa hip-hop cũng bao gồm khiêu vũ, thời trang và nghệ thuật đường phố. Breakdance và graffiti gắn bó chặt chẽ với phong cách âm nhạc này.\n\nNhiều người trẻ trên thế giới thích hip-hop vì ngày nay nó mạnh mẽ và giàu tính biểu đạt. Nó thường giúp nghệ sĩ nói thật về cuộc sống của mình và mang lại cho người nghe năng lượng, sự tự tin và cảm giác kết nối."
  },
  {
    "text": "6. Country Music – Nhạc Đồng quê\nCountry music is a gentle and simple type of music. It often uses acoustic guitars, banjos, violins, and soft drums. The melody is usually warm, clear, gentle, and easy to follow.\n\nCountry songs often tell stories about family, love, work, nature, and life in small towns. The words are simple, but they can carry strong feelings.\n\nThis music is especially popular in the United States, but people in many countries also enjoy it. Country singers often wear casual clothes and perform with a band.\n\nI really like country music because it feels honest and peaceful. It reminds listeners of home, close relationships, quiet places, and the beauty of everyday life.",
    "vi": "6. Nhạc Đồng quê\nNhạc đồng quê là một thể loại âm nhạc nhẹ nhàng và đơn giản. Nó thường sử dụng guitar acoustic, banjo, violin và trống nhẹ. Giai điệu thường ấm áp, rõ ràng, nhẹ nhàng và dễ theo.\n\nCác bài hát đồng quê thường kể chuyện về gia đình, tình yêu, công việc, thiên nhiên và cuộc sống ở các thị trấn nhỏ. Lời ca đơn giản nhưng có thể truyền tải cảm xúc mạnh.\n\nÂm nhạc này đặc biệt phổ biến ở Hoa Kỳ, nhưng người dân ở nhiều quốc gia cũng yêu thích nó. Ca sĩ đồng quê thường mặc quần áo giản dị và biểu diễn cùng ban nhạc.\n\nTôi rất thích nhạc đồng quê vì nó tạo cảm giác chân thật và yên bình. Nó gợi người nghe nhớ về mái nhà, các mối quan hệ gần gũi, những nơi yên tĩnh và vẻ đẹp của cuộc sống thường ngày."
  }
];
