const newEssayData = [
  {
    "text": "7. Electronic Dance Music – Nhạc Điện tử\nElectronic dance music, or EDM, is made with computers, keyboards, and other electronic equipment. It usually has a fast beat, repeated sounds, and a strong rhythm that makes people want to dance.\n\nDJs create and mix EDM songs. They often perform at clubs, concerts, and large music festivals. Bright lights and colorful screens make these events more exciting.\n\nEDM has many styles, from soft and relaxing music to very fast and powerful tracks. Most songs have few words or short repeated lines.\n\nMany young people around the world enjoy EDM because it is modern and energetic. It creates a lively atmosphere and helps people dance, have fun, and celebrate together.",
    "vi": "7. Nhạc Điện tử\nNhạc dance điện tử, hay EDM, được tạo bằng máy tính, bàn phím điện tử và các thiết bị điện tử khác. Nó thường có nhịp nhanh, âm thanh lặp lại và tiết tấu mạnh khiến mọi người muốn nhảy.\n\nCác DJ tạo và phối các bài EDM. Họ thường biểu diễn ở câu lạc bộ, buổi hòa nhạc và các lễ hội âm nhạc lớn. Ánh sáng rực rỡ và màn hình nhiều màu làm những sự kiện này hào hứng hơn.\n\nEDM có nhiều phong cách, từ nhạc nhẹ và thư giãn đến những bản rất nhanh và mạnh. Phần lớn bài hát có ít lời hoặc các câu ngắn lặp lại.\n\nNhiều người trẻ trên thế giới thích EDM vì nó hiện đại và giàu năng lượng. Nó tạo bầu không khí sôi động và giúp mọi người nhảy, vui chơi và cùng nhau ăn mừng."
  },
  {
    "text": "8. Folk Music – Nhạc Dân gian\nFolk music is traditional music from a country, region, or community. It often uses local instruments and simple melodies. The songs are carefully passed from one generation to the next over many years.\n\nFolk songs usually describe village life, work, nature, family, festivals, and important events. They can also tell old stories, legends, and lessons.\n\nPeople perform folk music at cultural shows, weddings, holidays, and community celebrations. Singers may wear traditional clothes while musicians play instruments from their region.\n\nI enjoy folk music because it teaches us many useful things about history and culture. It also helps people remember their own roots and keeps old customs alive for future generations.",
    "vi": "8. Nhạc Dân gian\nNhạc dân gian là âm nhạc truyền thống từ một quốc gia, vùng miền hoặc cộng đồng. Nó thường sử dụng nhạc cụ địa phương và giai điệu đơn giản. Các bài hát được truyền lại cẩn thận từ thế hệ này sang thế hệ tiếp theo qua nhiều năm.\n\nCác bài dân ca thường mô tả đời sống làng quê, công việc, thiên nhiên, gia đình, lễ hội và các sự kiện quan trọng. Chúng cũng có thể kể những câu chuyện cổ, truyền thuyết và bài học.\n\nMọi người biểu diễn nhạc dân gian tại các chương trình văn hóa, đám cưới, ngày lễ và lễ kỷ niệm cộng đồng. Ca sĩ có thể mặc trang phục truyền thống trong khi nhạc sĩ chơi nhạc cụ của vùng mình.\n\nTôi thích nhạc dân gian vì nó dạy chúng ta nhiều điều hữu ích về lịch sử và văn hóa. Nó cũng giúp mọi người nhớ về cội nguồn của mình và giữ những phong tục cũ sống mãi cho các thế hệ tương lai."
  },
  {
    "text": "9. Blues Music – Nhạc Blues\nBlues music is a deep and emotional type of music. It often uses guitars, piano, harmonica, and drums. The rhythm is usually slow, and the melody can sound deeply sad or thoughtful.\n\nBlues songs often describe pain, hard work, lost love, and difficult times. However, the music can also give people hope, comfort, courage, and strength.\n\nBlues began in the African American community in the United States. Later, it influenced jazz, rock, and many other modern music styles.\n\nI really like blues because it feels honest, personal, and meaningful. The singer’s voice and the simple instruments can express strong emotions, helping listeners understand sadness, courage, and the challenges of life.",
    "vi": "9. Nhạc Blues\nNhạc blues là một thể loại âm nhạc sâu lắng và giàu cảm xúc. Nó thường sử dụng guitar, piano, harmonica và trống. Nhịp thường chậm và giai điệu có thể nghe rất buồn hoặc trầm tư.\n\nCác bài blues thường mô tả nỗi đau, công việc vất vả, tình yêu đã mất và những thời điểm khó khăn. Tuy nhiên, âm nhạc cũng có thể mang đến hy vọng, sự an ủi, lòng can đảm và sức mạnh.\n\nBlues bắt đầu trong cộng đồng người Mỹ gốc Phi ở Hoa Kỳ. Sau đó, nó ảnh hưởng đến jazz, rock và nhiều phong cách âm nhạc hiện đại khác.\n\nTôi rất thích blues vì nó tạo cảm giác chân thật, cá nhân và có ý nghĩa. Giọng ca sĩ và các nhạc cụ đơn giản có thể diễn tả cảm xúc mạnh, giúp người nghe hiểu nỗi buồn, lòng can đảm và những thử thách của cuộc sống."
  },
  {
    "text": "10. Ballad Music – Nhạc Ballad\nBallad music is usually slow, soft, gentle, and full of deep emotion. It usually has a gentle melody and clear words. Piano, guitar, and violin are common instruments in many ballad songs.\n\nBallads often talk about love, memories, separation, hope, and personal feelings. The singer usually performs with a calm and emotional voice.\n\nMany people listen to ballads when they are relaxing, thinking, or feeling sad. These songs are also popular at weddings, cafes, and quiet evening events.\n\nI really enjoy ballad music because it helps me understand my feelings. The slow rhythm and meaningful lyrics can bring comfort, create beautiful memories, and make listeners feel close to the singer.",
    "vi": "10. Nhạc Ballad\nNhạc ballad thường chậm, nhẹ, dịu dàng và đầy cảm xúc sâu sắc. Nó thường có giai điệu nhẹ nhàng và lời rõ ràng. Piano, guitar và violin là những nhạc cụ phổ biến trong nhiều bài ballad.\n\nBallad thường nói về tình yêu, ký ức, chia ly, hy vọng và cảm xúc cá nhân. Ca sĩ thường biểu diễn với giọng bình tĩnh và giàu cảm xúc.\n\nNhiều người nghe ballad khi họ đang thư giãn, suy nghĩ hoặc cảm thấy buồn. Những bài hát này cũng phổ biến ở đám cưới, quán cà phê và các sự kiện buổi tối yên tĩnh.\n\nTôi rất thích nhạc ballad vì nó giúp tôi hiểu cảm xúc của mình. Nhịp chậm và lời ca có ý nghĩa có thể mang lại sự an ủi, tạo những ký ức đẹp và khiến người nghe cảm thấy gần gũi với ca sĩ."
  }
];
