const lessonVocabularyWords = [
  "pop",
  "music",
  "one",
  "most",
  "popular",
  "types",
  "world",
  "usually",
  "has",
  "clear",
  "beat",
  "simple",
  "words",
  "and",
  "easy",
  "melody",
  "many",
  "young",
  "people",
  "enjoy",
  "listening",
  "songs",
  "daily",
  "singers",
  "often",
  "sing",
  "about",
  "love",
  "friendship",
  "dreams",
  "life",
  "remember",
  "so",
  "can",
  "quickly",
  "along",
  "videos",
  "also",
  "help",
  "artists",
  "become",
  "famous",
  "played",
  "radio",
  "television",
  "social",
  "media",
  "apps",
  "common",
  "parties",
  "shops",
  "schools",
  "public",
  "events",
  "like",
  "because",
  "makes",
  "feel",
  "relaxed",
  "happy",
  "enjoyable",
  "modern",
  "suitable",
  "different",
  "listeners",
  "rock",
  "strong",
  "energetic",
  "type",
  "uses",
  "electric",
  "guitars",
  "bass",
  "drums",
  "powerful",
  "singing",
  "sound",
  "loud",
  "exciting",
  "full",
  "energy",
  "may",
  "talk",
  "freedom",
  "youth",
  "problems",
  "or",
  "change",
  "some",
  "fast",
  "wild",
  "while",
  "others",
  "slower",
  "more",
  "emotional",
  "bands",
  "have",
  "several",
  "members",
  "each",
  "person",
  "plays",
  "instrument",
  "sings",
  "live",
  "concerts",
  "musicians",
  "move",
  "around",
  "stage",
  "connect",
  "audience",
  "feels",
  "honest",
  "give",
  "real",
  "courage",
  "fresh",
  "feeling",
  "classical",
  "beautiful",
  "traditional",
  "piano",
  "violin",
  "cello",
  "flute",
  "other",
  "instruments",
  "orchestra",
  "soft",
  "peaceful",
  "dramatic",
  "pieces",
  "written",
  "hundreds",
  "years",
  "ago",
  "composers",
  "such",
  "as",
  "mozart",
  "beethoven",
  "created",
  "still",
  "today",
  "performed",
  "concert",
  "halls",
  "theaters",
  "special",
  "must",
  "practise",
  "carefully",
  "long",
  "difficult",
  "really",
  "helps",
  "relax",
  "think",
  "clearly",
  "improve",
  "concentration",
  "studying",
  "reading",
  "writing",
  "working",
  "quietly",
  "day"
];

const newVocabData = [
  {
    "id": 1,
    "word": "pop",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑp/",
    "meaning": "nhạc pop",
    "ex1": "Students learn about pop while exploring different music styles.",
    "ex1_vi": "Học sinh học về nhạc pop khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 2,
    "word": "music",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mjˈuzɪk/",
    "meaning": "âm nhạc",
    "ex1": "Students learn about music while exploring different music styles.",
    "ex1_vi": "Học sinh học về âm nhạc khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 3,
    "word": "one",
    "type": "number/determiner",
    "cat": "adj",
    "phonetic": "/wˈʌn/",
    "meaning": "một",
    "ex1": "One listeners enjoy different music styles around the world.",
    "ex1_vi": "Một người nghe thích các phong cách âm nhạc khác nhau trên thế giới."
  },
  {
    "id": 4,
    "word": "most",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈoʊst/",
    "meaning": "nhất; phần lớn",
    "ex1": "Most listeners enjoy different music styles around the world.",
    "ex1_vi": "Nhất; phần lớn người nghe thích các phong cách âm nhạc khác nhau trên thế giới."
  },
  {
    "id": 5,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "This music style sounds popular during live performances.",
    "ex1_vi": "Phong cách âm nhạc này nghe phổ biến trong các buổi biểu diễn trực tiếp."
  },
  {
    "id": 6,
    "word": "types",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪps/",
    "meaning": "các loại",
    "ex1": "Students learn about types while exploring different music styles.",
    "ex1_vi": "Học sinh học về các loại khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 7,
    "word": "world",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝld/",
    "meaning": "thế giới",
    "ex1": "Students learn about world while exploring different music styles.",
    "ex1_vi": "Học sinh học về thế giới khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 8,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "It usually has a clear beat, simple words, and an easy melody.",
    "ex1_vi": "Nó thường có nhịp rõ ràng, lời đơn giản và giai điệu dễ nghe."
  },
  {
    "id": 9,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "It usually has a clear beat, simple words, and an easy melody.",
    "ex1_vi": "Nó thường có nhịp rõ ràng, lời đơn giản và giai điệu dễ nghe."
  },
  {
    "id": 10,
    "word": "clear",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈɪr/",
    "meaning": "trong",
    "ex1": "Students discuss clear during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về trong trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 11,
    "word": "beat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈit/",
    "meaning": "nhịp",
    "ex1": "Students discuss beat during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về nhịp trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 12,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "Students discuss simple during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về đơn giản trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 13,
    "word": "words",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝdz/",
    "meaning": "lời nói; từ ngữ",
    "ex1": "Students discuss words during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về lời nói; từ ngữ trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 14,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Students discuss and during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về và trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 15,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "Students discuss easy during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về dễ trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 16,
    "word": "melody",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛlʌdi/",
    "meaning": "giai điệu",
    "ex1": "Students discuss melody during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về giai điệu trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 17,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Many young people enjoy listening to pop songs daily.",
    "ex1_vi": "Nhiều người trẻ thích nghe các bài hát pop hằng ngày."
  },
  {
    "id": 18,
    "word": "young",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈʌŋ/",
    "meaning": "non; trẻ",
    "ex1": "Many young people enjoy listening to pop songs daily.",
    "ex1_vi": "Nhiều người trẻ thích nghe các bài hát pop hằng ngày."
  },
  {
    "id": 19,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người; con người",
    "ex1": "Students discuss people during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về mọi người; con người trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 20,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thích; tận hưởng",
    "ex1": "Students discuss enjoy during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về thích; tận hưởng trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 21,
    "word": "listening",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/lˈɪsʌnɪŋ/",
    "meaning": "việc lắng nghe",
    "ex1": "Students discuss listening during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về việc lắng nghe trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 22,
    "word": "songs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔŋz/",
    "meaning": "bài hát",
    "ex1": "Students discuss songs during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về bài hát trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 23,
    "word": "daily",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈeɪli/",
    "meaning": "hằng ngày",
    "ex1": "Students discuss daily during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về hằng ngày trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 24,
    "word": "singers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪŋɝz/",
    "meaning": "ca sĩ",
    "ex1": "Pop singers often sing about love, friendship, dreams, and daily life.",
    "ex1_vi": "Ca sĩ pop thường hát về tình yêu, tình bạn, ước mơ và cuộc sống hằng ngày."
  },
  {
    "id": 25,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường xuyên",
    "ex1": "Pop singers often sing about love, friendship, dreams, and daily life.",
    "ex1_vi": "Ca sĩ pop thường hát về tình yêu, tình bạn, ước mơ và cuộc sống hằng ngày."
  },
  {
    "id": 26,
    "word": "sing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɪŋ/",
    "meaning": "hát",
    "ex1": "Students discuss sing during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về hát trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 27,
    "word": "about",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ʌbˈaʊt/",
    "meaning": "về",
    "ex1": "Students discuss about during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về về trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 28,
    "word": "love",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʌv/",
    "meaning": "yêu thích",
    "ex1": "Students discuss love during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về yêu thích trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 29,
    "word": "friendship",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈɛndʃɪp/",
    "meaning": "tình bạn",
    "ex1": "Students discuss friendship during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về tình bạn trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 30,
    "word": "dreams",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈimz/",
    "meaning": "ước mơ",
    "ex1": "Students discuss dreams during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về ước mơ trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 31,
    "word": "life",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪf/",
    "meaning": "cuộc sống",
    "ex1": "Students discuss life during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về cuộc sống trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 32,
    "word": "remember",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪmˈɛmbɝ/",
    "meaning": "tưởng nhớ",
    "ex1": "Their songs are easy to remember, so people can quickly sing along.",
    "ex1_vi": "Các bài hát của họ dễ nhớ nên mọi người có thể nhanh chóng hát theo."
  },
  {
    "id": 33,
    "word": "so",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/sˈoʊ/",
    "meaning": "vì vậy; nên",
    "ex1": "Their songs are easy to remember, so people can quickly sing along.",
    "ex1_vi": "Các bài hát của họ dễ nhớ nên mọi người có thể nhanh chóng hát theo."
  },
  {
    "id": 34,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Students discuss can during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về có thể trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 35,
    "word": "quickly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kwˈɪkli/",
    "meaning": "nhanh chóng",
    "ex1": "Students discuss quickly during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về nhanh chóng trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 36,
    "word": "along",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ʌlˈɔŋ/",
    "meaning": "dọc theo",
    "ex1": "Students discuss along during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về dọc theo trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 37,
    "word": "videos",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪdioʊz/",
    "meaning": "video",
    "ex1": "Music videos also help pop artists become famous.",
    "ex1_vi": "Video âm nhạc cũng giúp nghệ sĩ pop trở nên nổi tiếng."
  },
  {
    "id": 38,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "Music videos also help pop artists become famous.",
    "ex1_vi": "Video âm nhạc cũng giúp nghệ sĩ pop trở nên nổi tiếng."
  },
  {
    "id": 39,
    "word": "help",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛlp/",
    "meaning": "sự giúp đỡ; giúp",
    "ex1": "Students discuss help during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về sự giúp đỡ; giúp trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 40,
    "word": "artists",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɑrtɪsts/",
    "meaning": "nghệ sĩ",
    "ex1": "Students discuss artists during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về nghệ sĩ trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 41,
    "word": "become",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌm/",
    "meaning": "trở nên",
    "ex1": "Students discuss become during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về trở nên trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 42,
    "word": "famous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈeɪmʌs/",
    "meaning": "nổi tiếng",
    "ex1": "Students discuss famous during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về nổi tiếng trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 43,
    "word": "played",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪd/",
    "meaning": "đã chơi",
    "ex1": "Pop music is played on radio, television, social media, and music apps.",
    "ex1_vi": "Nhạc pop được phát trên radio, truyền hình, mạng xã hội và các ứng dụng âm nhạc."
  },
  {
    "id": 44,
    "word": "radio",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈeɪdiˌoʊ/",
    "meaning": "radio",
    "ex1": "Pop music is played on radio, television, social media, and music apps.",
    "ex1_vi": "Nhạc pop được phát trên radio, truyền hình, mạng xã hội và các ứng dụng âm nhạc."
  },
  {
    "id": 45,
    "word": "television",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛlʌvˌɪʒʌn/",
    "meaning": "tivi",
    "ex1": "Students discuss television during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về tivi trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 46,
    "word": "social",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈoʊʃʌl/",
    "meaning": "xã hội",
    "ex1": "Students discuss social during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về xã hội trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 47,
    "word": "media",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈidiʌ/",
    "meaning": "truyền thông",
    "ex1": "Students discuss media during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về truyền thông trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 48,
    "word": "apps",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈæps/",
    "meaning": "ứng dụng",
    "ex1": "Students discuss apps during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về ứng dụng trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 49,
    "word": "common",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɑmʌn/",
    "meaning": "phổ biến; thông thường",
    "ex1": "It is common at parties, shops, schools, and public events.",
    "ex1_vi": "Nó phổ biến ở các bữa tiệc, cửa hàng, trường học và sự kiện công cộng."
  },
  {
    "id": 50,
    "word": "parties",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrtiz/",
    "meaning": "bữa tiệc",
    "ex1": "It is common at parties, shops, schools, and public events.",
    "ex1_vi": "Nó phổ biến ở các bữa tiệc, cửa hàng, trường học và sự kiện công cộng."
  },
  {
    "id": 51,
    "word": "shops",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɑps/",
    "meaning": "cửa hàng",
    "ex1": "Students discuss shops during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về cửa hàng trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 52,
    "word": "schools",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈulz/",
    "meaning": "trường học",
    "ex1": "Students discuss schools during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về trường học trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 53,
    "word": "public",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈʌblɪk/",
    "meaning": "công cộng",
    "ex1": "Students discuss public during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về công cộng trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 54,
    "word": "events",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪvˈɛnts/",
    "meaning": "sự kiện",
    "ex1": "Students discuss events during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về sự kiện trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 55,
    "word": "like",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈaɪk/",
    "meaning": "thích",
    "ex1": "I like pop music because it makes me feel relaxed and happy.",
    "ex1_vi": "Tôi thích nhạc pop vì nó làm tôi cảm thấy thư giãn và vui vẻ."
  },
  {
    "id": 56,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "I like pop music because it makes me feel relaxed and happy.",
    "ex1_vi": "Tôi thích nhạc pop vì nó làm tôi cảm thấy thư giãn và vui vẻ."
  },
  {
    "id": 57,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm; khiến",
    "ex1": "Students discuss makes during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về làm; khiến trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 58,
    "word": "feel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈil/",
    "meaning": "cảm thấy",
    "ex1": "Students discuss feel during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về cảm thấy trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 59,
    "word": "relaxed",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪlˈækst/",
    "meaning": "thư giãn",
    "ex1": "Students discuss relaxed during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về thư giãn trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 60,
    "word": "happy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈæpi/",
    "meaning": "vui vẻ",
    "ex1": "Students discuss happy during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về vui vẻ trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 61,
    "word": "enjoyable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɛndʒˈɔɪʌbʌl/",
    "meaning": "thú vị; dễ chịu",
    "ex1": "It is enjoyable, modern, and suitable for many different listeners.",
    "ex1_vi": "Nó thú vị, hiện đại và phù hợp với nhiều người nghe khác nhau."
  },
  {
    "id": 62,
    "word": "modern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈɑdɝn/",
    "meaning": "hiện đại",
    "ex1": "It is enjoyable, modern, and suitable for many different listeners.",
    "ex1_vi": "Nó thú vị, hiện đại và phù hợp với nhiều người nghe khác nhau."
  },
  {
    "id": 63,
    "word": "suitable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈutʌbʌl/",
    "meaning": "phù hợp",
    "ex1": "Students discuss suitable during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về phù hợp trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 64,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "Students discuss different during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về khác nhau trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 65,
    "word": "listeners",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɪsʌnɝz/",
    "meaning": "người nghe",
    "ex1": "Students discuss listeners during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về người nghe trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 66,
    "word": "rock",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɑk/",
    "meaning": "nhạc rock",
    "ex1": "Rock music is a strong and energetic type of music.",
    "ex1_vi": "Nhạc rock là một thể loại âm nhạc mạnh mẽ và tràn đầy năng lượng."
  },
  {
    "id": 67,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋ/",
    "meaning": "khỏe; mạnh",
    "ex1": "Rock music is a strong and energetic type of music.",
    "ex1_vi": "Nhạc rock là một thể loại âm nhạc mạnh mẽ và tràn đầy năng lượng."
  },
  {
    "id": 68,
    "word": "energetic",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɛnɝdʒˈɛtɪk/",
    "meaning": "tràn đầy năng lượng",
    "ex1": "Students discuss energetic during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về tràn đầy năng lượng trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 69,
    "word": "type",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪp/",
    "meaning": "loại",
    "ex1": "Students discuss type during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về loại trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 70,
    "word": "uses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈusʌz/",
    "meaning": "sử dụng",
    "ex1": "It often uses electric guitars, bass guitars, drums, and powerful singing.",
    "ex1_vi": "Nó thường sử dụng guitar điện, guitar bass, trống và giọng hát mạnh."
  },
  {
    "id": 71,
    "word": "electric",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪlˈɛktrɪk/",
    "meaning": "thuộc điện",
    "ex1": "It often uses electric guitars, bass guitars, drums, and powerful singing.",
    "ex1_vi": "Nó thường sử dụng guitar điện, guitar bass, trống và giọng hát mạnh."
  },
  {
    "id": 72,
    "word": "guitars",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡɪtˈɑrz/",
    "meaning": "đàn guitar",
    "ex1": "Students discuss guitars during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về đàn guitar trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 73,
    "word": "bass",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈæs/",
    "meaning": "bass; âm trầm",
    "ex1": "Students discuss bass during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về bass; âm trầm trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 74,
    "word": "drums",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈʌmz/",
    "meaning": "trống",
    "ex1": "Students discuss drums during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về trống trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 75,
    "word": "powerful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈaʊɝfʌl/",
    "meaning": "mạnh mẽ",
    "ex1": "Students discuss powerful during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về mạnh mẽ trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 76,
    "word": "singing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɪŋɪŋ/",
    "meaning": "đang hót",
    "ex1": "Students discuss singing during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về đang hót trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 77,
    "word": "sound",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaʊnd/",
    "meaning": "âm thanh",
    "ex1": "The sound can be loud, exciting, and full of energy.",
    "ex1_vi": "Âm thanh có thể lớn, hào hứng và đầy năng lượng."
  },
  {
    "id": 78,
    "word": "loud",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈaʊd/",
    "meaning": "ồn; lớn tiếng",
    "ex1": "The sound can be loud, exciting, and full of energy.",
    "ex1_vi": "Âm thanh có thể lớn, hào hứng và đầy năng lượng."
  },
  {
    "id": 79,
    "word": "exciting",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪksˈaɪtɪŋ/",
    "meaning": "hào hứng",
    "ex1": "Students discuss exciting during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về hào hứng trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 80,
    "word": "full",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈʊl/",
    "meaning": "trọn vẹn",
    "ex1": "Students discuss full during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về trọn vẹn trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 81,
    "word": "energy",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛnɝdʒi/",
    "meaning": "năng lượng",
    "ex1": "Students discuss energy during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về năng lượng trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 82,
    "word": "may",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈeɪ/",
    "meaning": "có thể",
    "ex1": "Rock songs may talk about freedom, youth, love, problems, or social change.",
    "ex1_vi": "Các bài hát rock có thể nói về tự do, tuổi trẻ, tình yêu, vấn đề hoặc thay đổi xã hội."
  },
  {
    "id": 83,
    "word": "talk",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈɔk/",
    "meaning": "nói chuyện",
    "ex1": "Rock songs may talk about freedom, youth, love, problems, or social change.",
    "ex1_vi": "Các bài hát rock có thể nói về tự do, tuổi trẻ, tình yêu, vấn đề hoặc thay đổi xã hội."
  },
  {
    "id": 84,
    "word": "freedom",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈidʌm/",
    "meaning": "tự do",
    "ex1": "Students discuss freedom during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về tự do trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 85,
    "word": "youth",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈuθ/",
    "meaning": "tuổi trẻ",
    "ex1": "Students discuss youth during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về tuổi trẻ trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 86,
    "word": "problems",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑblʌmz/",
    "meaning": "vấn đề",
    "ex1": "Students discuss problems during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về vấn đề trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 87,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "Students discuss or during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về hoặc trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 88,
    "word": "change",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈeɪndʒ/",
    "meaning": "thay đổi",
    "ex1": "Students discuss change during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về thay đổi trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 89,
    "word": "some",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌm/",
    "meaning": "một số",
    "ex1": "Some listeners enjoy different music styles around the world.",
    "ex1_vi": "Một số người nghe thích các phong cách âm nhạc khác nhau trên thế giới."
  },
  {
    "id": 90,
    "word": "fast",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈæst/",
    "meaning": "nhanh",
    "ex1": "This music style sounds fast during live performances.",
    "ex1_vi": "Phong cách âm nhạc này nghe nhanh trong các buổi biểu diễn trực tiếp."
  },
  {
    "id": 91,
    "word": "wild",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈaɪld/",
    "meaning": "hoang dã",
    "ex1": "This music style sounds wild during live performances.",
    "ex1_vi": "Phong cách âm nhạc này nghe hoang dã trong các buổi biểu diễn trực tiếp."
  },
  {
    "id": 92,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "Musicians create new sounds while they perform together.",
    "ex1_vi": "Nhạc sĩ tạo âm thanh mới trong khi cùng biểu diễn."
  },
  {
    "id": 93,
    "word": "others",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈʌðɝz/",
    "meaning": "những loài khác",
    "ex1": "Students learn about others while exploring different music styles.",
    "ex1_vi": "Học sinh học về những loài khác khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 94,
    "word": "slower",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/slˈoʊɝ/",
    "meaning": "chậm hơn",
    "ex1": "This music style sounds slower during live performances.",
    "ex1_vi": "Phong cách âm nhạc này nghe chậm hơn trong các buổi biểu diễn trực tiếp."
  },
  {
    "id": 95,
    "word": "more",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "nhiều hơn",
    "ex1": "More listeners enjoy different music styles around the world.",
    "ex1_vi": "Nhiều hơn người nghe thích các phong cách âm nhạc khác nhau trên thế giới."
  },
  {
    "id": 96,
    "word": "emotional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪmˈoʊʃʌnʌl/",
    "meaning": "giàu cảm xúc",
    "ex1": "This music style sounds emotional during live performances.",
    "ex1_vi": "Phong cách âm nhạc này nghe giàu cảm xúc trong các buổi biểu diễn trực tiếp."
  },
  {
    "id": 97,
    "word": "bands",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈændz/",
    "meaning": "ban nhạc",
    "ex1": "Students learn about bands while exploring different music styles.",
    "ex1_vi": "Học sinh học về ban nhạc khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 98,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có",
    "ex1": "Musicians can have during creative performances and music lessons.",
    "ex1_vi": "Nhạc sĩ có thể có trong các buổi biểu diễn và bài học âm nhạc sáng tạo."
  },
  {
    "id": 99,
    "word": "several",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈɛvrʌl/",
    "meaning": "một vài",
    "ex1": "Several listeners enjoy different music styles around the world.",
    "ex1_vi": "Một vài người nghe thích các phong cách âm nhạc khác nhau trên thế giới."
  },
  {
    "id": 100,
    "word": "members",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛmbɝz/",
    "meaning": "các thành viên",
    "ex1": "Students learn about members while exploring different music styles.",
    "ex1_vi": "Học sinh học về các thành viên khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 101,
    "word": "each",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈitʃ/",
    "meaning": "mỗi",
    "ex1": "Each listeners enjoy different music styles around the world.",
    "ex1_vi": "Mỗi người nghe thích các phong cách âm nhạc khác nhau trên thế giới."
  },
  {
    "id": 102,
    "word": "person",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɝsʌn/",
    "meaning": "người",
    "ex1": "Students learn about person while exploring different music styles.",
    "ex1_vi": "Học sinh học về người khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 103,
    "word": "plays",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪz/",
    "meaning": "đóng; chơi",
    "ex1": "Students learn about plays while exploring different music styles.",
    "ex1_vi": "Học sinh học về đóng; chơi khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 104,
    "word": "instrument",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɪnstrʌmʌnt/",
    "meaning": "nhạc cụ",
    "ex1": "Students learn about instrument while exploring different music styles.",
    "ex1_vi": "Học sinh học về nhạc cụ khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 105,
    "word": "sings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪŋz/",
    "meaning": "hát",
    "ex1": "Students learn about sings while exploring different music styles.",
    "ex1_vi": "Học sinh học về hát khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 106,
    "word": "live",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈaɪv/",
    "meaning": "sống",
    "ex1": "Musicians can live during creative performances and music lessons.",
    "ex1_vi": "Nhạc sĩ có thể sống trong các buổi biểu diễn và bài học âm nhạc sáng tạo."
  },
  {
    "id": 107,
    "word": "concerts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑnsɝts/",
    "meaning": "buổi hòa nhạc",
    "ex1": "Students learn about concerts while exploring different music styles.",
    "ex1_vi": "Học sinh học về buổi hòa nhạc khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 108,
    "word": "musicians",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mjuzˈɪʃʌnz/",
    "meaning": "nhạc sĩ",
    "ex1": "Students learn about musicians while exploring different music styles.",
    "ex1_vi": "Học sinh học về nhạc sĩ khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 109,
    "word": "move",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈuv/",
    "meaning": "di chuyển",
    "ex1": "Musicians can move during creative performances and music lessons.",
    "ex1_vi": "Nhạc sĩ có thể di chuyển trong các buổi biểu diễn và bài học âm nhạc sáng tạo."
  },
  {
    "id": 110,
    "word": "around",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɝˈaʊnd/",
    "meaning": "khắp; xung quanh",
    "ex1": "Musicians around perform songs for different audiences today.",
    "ex1_vi": "Nhạc sĩ khắp; xung quanh biểu diễn các bài hát cho những khán giả khác nhau ngày nay."
  },
  {
    "id": 111,
    "word": "stage",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈeɪdʒ/",
    "meaning": "sân khấu",
    "ex1": "Students learn about stage while exploring different music styles.",
    "ex1_vi": "Học sinh học về sân khấu khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 112,
    "word": "connect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌnˈɛkt/",
    "meaning": "kết nối",
    "ex1": "Musicians can connect during creative performances and music lessons.",
    "ex1_vi": "Nhạc sĩ có thể kết nối trong các buổi biểu diễn và bài học âm nhạc sáng tạo."
  },
  {
    "id": 113,
    "word": "audience",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɑdiʌns/",
    "meaning": "khán giả",
    "ex1": "Students learn about audience while exploring different music styles.",
    "ex1_vi": "Học sinh học về khán giả khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 114,
    "word": "feels",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈilz/",
    "meaning": "cảm thấy",
    "ex1": "This music style feels listeners during live performances.",
    "ex1_vi": "Phong cách âm nhạc này cảm thấy người nghe trong các buổi biểu diễn trực tiếp."
  },
  {
    "id": 115,
    "word": "honest",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɑnʌst/",
    "meaning": "trung thực",
    "ex1": "This music style sounds honest during live performances.",
    "ex1_vi": "Phong cách âm nhạc này nghe trung thực trong các buổi biểu diễn trực tiếp."
  },
  {
    "id": 116,
    "word": "give",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪv/",
    "meaning": "mang lại",
    "ex1": "Musicians can give during creative performances and music lessons.",
    "ex1_vi": "Nhạc sĩ có thể mang lại trong các buổi biểu diễn và bài học âm nhạc sáng tạo."
  },
  {
    "id": 117,
    "word": "real",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈil/",
    "meaning": "thực tế; thật",
    "ex1": "This music style sounds real during live performances.",
    "ex1_vi": "Phong cách âm nhạc này nghe thực tế; thật trong các buổi biểu diễn trực tiếp."
  },
  {
    "id": 118,
    "word": "courage",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɝʌdʒ/",
    "meaning": "lòng dũng cảm",
    "ex1": "Students learn about courage while exploring different music styles.",
    "ex1_vi": "Học sinh học về lòng dũng cảm khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 119,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi; trong lành",
    "ex1": "This music style sounds fresh during live performances.",
    "ex1_vi": "Phong cách âm nhạc này nghe tươi; trong lành trong các buổi biểu diễn trực tiếp."
  },
  {
    "id": 120,
    "word": "feeling",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈilɪŋ/",
    "meaning": "cảm giác",
    "ex1": "Students learn about feeling while exploring different music styles.",
    "ex1_vi": "Học sinh học về cảm giác khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 121,
    "word": "classical",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈæsɪkʌl/",
    "meaning": "cổ điển",
    "ex1": "Classical music is a beautiful and traditional type of music.",
    "ex1_vi": "Nhạc cổ điển là một thể loại âm nhạc đẹp và truyền thống."
  },
  {
    "id": 122,
    "word": "beautiful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bjˈutʌfʌl/",
    "meaning": "đẹp",
    "ex1": "Classical music is a beautiful and traditional type of music.",
    "ex1_vi": "Nhạc cổ điển là một thể loại âm nhạc đẹp và truyền thống."
  },
  {
    "id": 123,
    "word": "traditional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trʌdˈɪʃʌnʌl/",
    "meaning": "truyền thống",
    "ex1": "Students discuss traditional during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về truyền thống trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 124,
    "word": "piano",
    "type": "noun",
    "cat": "n",
    "phonetic": "/piˈænoʊ/",
    "meaning": "đàn piano",
    "ex1": "Students learn about piano while exploring different music styles.",
    "ex1_vi": "Học sinh học về đàn piano khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 125,
    "word": "violin",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vaɪʌlˈɪn/",
    "meaning": "đàn violin",
    "ex1": "Students learn about violin while exploring different music styles.",
    "ex1_vi": "Học sinh học về đàn violin khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 126,
    "word": "cello",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈtʃɛloʊ/",
    "meaning": "đàn cello",
    "ex1": "Students learn about cello while exploring different music styles.",
    "ex1_vi": "Học sinh học về đàn cello khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 127,
    "word": "flute",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈut/",
    "meaning": "sáo",
    "ex1": "Students learn about flute while exploring different music styles.",
    "ex1_vi": "Học sinh học về sáo khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 128,
    "word": "other",
    "type": "determiner/adjective",
    "cat": "adj",
    "phonetic": "/ˈʌðɝ/",
    "meaning": "khác",
    "ex1": "Other listeners enjoy different music styles around the world.",
    "ex1_vi": "Khác người nghe thích các phong cách âm nhạc khác nhau trên thế giới."
  },
  {
    "id": 129,
    "word": "instruments",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɪnstrʌmʌnts/",
    "meaning": "nhạc cụ",
    "ex1": "Students learn about instruments while exploring different music styles.",
    "ex1_vi": "Học sinh học về nhạc cụ khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 130,
    "word": "orchestra",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔrkʌstrʌ/",
    "meaning": "dàn nhạc",
    "ex1": "Students learn about orchestra while exploring different music styles.",
    "ex1_vi": "Học sinh học về dàn nhạc khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 131,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "The sound can be soft, strong, peaceful, or dramatic.",
    "ex1_vi": "Âm thanh có thể nhẹ nhàng, mạnh mẽ, yên bình hoặc kịch tính."
  },
  {
    "id": 132,
    "word": "peaceful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈisfʌl/",
    "meaning": "yên bình",
    "ex1": "The sound can be soft, strong, peaceful, or dramatic.",
    "ex1_vi": "Âm thanh có thể nhẹ nhàng, mạnh mẽ, yên bình hoặc kịch tính."
  },
  {
    "id": 133,
    "word": "dramatic",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/drʌmˈætɪk/",
    "meaning": "kịch tính",
    "ex1": "Students discuss dramatic during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về kịch tính trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 134,
    "word": "pieces",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈisʌz/",
    "meaning": "miếng",
    "ex1": "Many famous classical pieces were written hundreds of years ago.",
    "ex1_vi": "Nhiều tác phẩm cổ điển nổi tiếng được viết từ hàng trăm năm trước."
  },
  {
    "id": 135,
    "word": "written",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɪtʌn/",
    "meaning": "được viết",
    "ex1": "Many famous classical pieces were written hundreds of years ago.",
    "ex1_vi": "Nhiều tác phẩm cổ điển nổi tiếng được viết từ hàng trăm năm trước."
  },
  {
    "id": 136,
    "word": "hundreds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈʌndrʌdz/",
    "meaning": "hàng trăm",
    "ex1": "Students discuss hundreds during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về hàng trăm trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 137,
    "word": "years",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈɪrz/",
    "meaning": "năm",
    "ex1": "Students discuss years during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về năm trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 138,
    "word": "ago",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌɡˈoʊ/",
    "meaning": "trước đây",
    "ex1": "Students discuss ago during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về trước đây trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 139,
    "word": "composers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌmpˈoʊzɝz/",
    "meaning": "nhà soạn nhạc",
    "ex1": "Students learn about composers while exploring different music styles.",
    "ex1_vi": "Học sinh học về nhà soạn nhạc khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 140,
    "word": "such",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌtʃ/",
    "meaning": "như vậy; như thế",
    "ex1": "Such listeners enjoy different music styles around the world.",
    "ex1_vi": "Như vậy; như thế người nghe thích các phong cách âm nhạc khác nhau trên thế giới."
  },
  {
    "id": 141,
    "word": "as",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ˈæz/",
    "meaning": "như; bằng",
    "ex1": "Students learn about as while exploring different music styles.",
    "ex1_vi": "Học sinh học về như; bằng khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 142,
    "word": "mozart",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈmoʊtsɑːrt/",
    "meaning": "Mozart",
    "ex1": "Students learn about mozart while exploring different music styles.",
    "ex1_vi": "Học sinh học về Mozart khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 143,
    "word": "beethoven",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈbeɪtoʊvən/",
    "meaning": "Beethoven",
    "ex1": "Students learn about beethoven while exploring different music styles.",
    "ex1_vi": "Học sinh học về Beethoven khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 144,
    "word": "created",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪtʌd/",
    "meaning": "đã tạo",
    "ex1": "The song was created during a special music performance.",
    "ex1_vi": "Bài hát đã được đã tạo trong một phần biểu diễn âm nhạc đặc biệt."
  },
  {
    "id": 145,
    "word": "still",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/stˈɪl/",
    "meaning": "vẫn",
    "ex1": "Musicians still perform songs for different audiences today.",
    "ex1_vi": "Nhạc sĩ vẫn biểu diễn các bài hát cho những khán giả khác nhau ngày nay."
  },
  {
    "id": 146,
    "word": "today",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌdˈeɪ/",
    "meaning": "hôm nay",
    "ex1": "Musicians today perform songs for different audiences today.",
    "ex1_vi": "Nhạc sĩ hôm nay biểu diễn các bài hát cho những khán giả khác nhau ngày nay."
  },
  {
    "id": 147,
    "word": "performed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɝfˈɔrmd/",
    "meaning": "đã biểu diễn",
    "ex1": "The song was performed during a special music performance.",
    "ex1_vi": "Bài hát đã được đã biểu diễn trong một phần biểu diễn âm nhạc đặc biệt."
  },
  {
    "id": 148,
    "word": "concert",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑnsɝt/",
    "meaning": "hòa nhạc",
    "ex1": "Students learn about concert while exploring different music styles.",
    "ex1_vi": "Học sinh học về hòa nhạc khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 149,
    "word": "halls",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɔlz/",
    "meaning": "phòng; hội trường",
    "ex1": "Students learn about halls while exploring different music styles.",
    "ex1_vi": "Học sinh học về phòng; hội trường khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 150,
    "word": "theaters",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈiʌtɝz/",
    "meaning": "nhà hát",
    "ex1": "Students learn about theaters while exploring different music styles.",
    "ex1_vi": "Học sinh học về nhà hát khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 151,
    "word": "special",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/spˈɛʃʌl/",
    "meaning": "đặc biệt",
    "ex1": "This music style sounds special during live performances.",
    "ex1_vi": "Phong cách âm nhạc này nghe đặc biệt trong các buổi biểu diễn trực tiếp."
  },
  {
    "id": 152,
    "word": "must",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈʌst/",
    "meaning": "phải",
    "ex1": "Musicians must practise carefully because the pieces can be long and difficult.",
    "ex1_vi": "Nhạc sĩ phải luyện tập cẩn thận vì các tác phẩm có thể dài và khó."
  },
  {
    "id": 153,
    "word": "practise",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prˈæktɪs/",
    "meaning": "luyện tập",
    "ex1": "Musicians must practise carefully because the pieces can be long and difficult.",
    "ex1_vi": "Nhạc sĩ phải luyện tập cẩn thận vì các tác phẩm có thể dài và khó."
  },
  {
    "id": 154,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "Students discuss carefully during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về cẩn thận trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 155,
    "word": "long",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɔŋ/",
    "meaning": "dài",
    "ex1": "Students discuss long during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về dài trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 156,
    "word": "difficult",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfʌkʌlt/",
    "meaning": "khó khăn",
    "ex1": "Students discuss difficult during useful lessons about music styles.",
    "ex1_vi": "Học sinh thảo luận về khó khăn trong các bài học hữu ích về phong cách âm nhạc."
  },
  {
    "id": 157,
    "word": "really",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/rˈɪli/",
    "meaning": "thật sự; rất",
    "ex1": "Musicians really perform songs for different audiences today.",
    "ex1_vi": "Nhạc sĩ thật sự; rất biểu diễn các bài hát cho những khán giả khác nhau ngày nay."
  },
  {
    "id": 158,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp đỡ",
    "ex1": "This music style helps listeners during live performances.",
    "ex1_vi": "Phong cách âm nhạc này giúp đỡ người nghe trong các buổi biểu diễn trực tiếp."
  },
  {
    "id": 159,
    "word": "relax",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪlˈæks/",
    "meaning": "thư giãn",
    "ex1": "Musicians can relax during creative performances and music lessons.",
    "ex1_vi": "Nhạc sĩ có thể thư giãn trong các buổi biểu diễn và bài học âm nhạc sáng tạo."
  },
  {
    "id": 160,
    "word": "think",
    "type": "verb",
    "cat": "v",
    "phonetic": "/θˈɪŋk/",
    "meaning": "nghĩ",
    "ex1": "Musicians can think during creative performances and music lessons.",
    "ex1_vi": "Nhạc sĩ có thể nghĩ trong các buổi biểu diễn và bài học âm nhạc sáng tạo."
  },
  {
    "id": 161,
    "word": "clearly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/klˈɪrli/",
    "meaning": "rõ ràng",
    "ex1": "Musicians clearly perform songs for different audiences today.",
    "ex1_vi": "Nhạc sĩ rõ ràng biểu diễn các bài hát cho những khán giả khác nhau ngày nay."
  },
  {
    "id": 162,
    "word": "improve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪmprˈuv/",
    "meaning": "cải thiện",
    "ex1": "Musicians can improve during creative performances and music lessons.",
    "ex1_vi": "Nhạc sĩ có thể cải thiện trong các buổi biểu diễn và bài học âm nhạc sáng tạo."
  },
  {
    "id": 163,
    "word": "concentration",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˌɑnsʌntrˈeɪʃʌn/",
    "meaning": "sự tập trung",
    "ex1": "Students learn about concentration while exploring different music styles.",
    "ex1_vi": "Học sinh học về sự tập trung khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 164,
    "word": "studying",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/stˈʌdiɪŋ/",
    "meaning": "việc học; đang học",
    "ex1": "Students learn about studying while exploring different music styles.",
    "ex1_vi": "Học sinh học về việc học; đang học khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 165,
    "word": "reading",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈidɪŋ/",
    "meaning": "đọc",
    "ex1": "Students enjoy reading during creative music activities at school.",
    "ex1_vi": "Học sinh thích đọc trong các hoạt động âm nhạc sáng tạo ở trường."
  },
  {
    "id": 166,
    "word": "writing",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪtɪŋ/",
    "meaning": "việc viết",
    "ex1": "Students learn about writing while exploring different music styles.",
    "ex1_vi": "Học sinh học về việc viết khi khám phá các phong cách âm nhạc khác nhau."
  },
  {
    "id": 167,
    "word": "working",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝkɪŋ/",
    "meaning": "việc làm việc",
    "ex1": "Students enjoy working during creative music activities at school.",
    "ex1_vi": "Học sinh thích việc làm việc trong các hoạt động âm nhạc sáng tạo ở trường."
  },
  {
    "id": 168,
    "word": "quietly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kwˈaɪʌtli/",
    "meaning": "một cách nhỏ nhẹ",
    "ex1": "Musicians quietly perform songs for different audiences today.",
    "ex1_vi": "Nhạc sĩ một cách nhỏ nhẹ biểu diễn các bài hát cho những khán giả khác nhau ngày nay."
  },
  {
    "id": 169,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "Students learn about day while exploring different music styles.",
    "ex1_vi": "Học sinh học về ngày khi khám phá các phong cách âm nhạc khác nhau."
  }
];

const newReadingVocabOrder = [
  "pop",
  "music",
  "one",
  "most",
  "popular",
  "types",
  "world",
  "usually",
  "has",
  "clear",
  "beat",
  "simple",
  "words",
  "and",
  "easy",
  "melody",
  "many",
  "young",
  "people",
  "enjoy",
  "listening",
  "songs",
  "daily",
  "singers",
  "often",
  "sing",
  "about",
  "love",
  "friendship",
  "dreams",
  "life",
  "remember",
  "so",
  "can",
  "quickly",
  "along",
  "videos",
  "also",
  "help",
  "artists",
  "become",
  "famous",
  "played",
  "radio",
  "television",
  "social",
  "media",
  "apps",
  "common",
  "parties",
  "shops",
  "schools",
  "public",
  "events",
  "like",
  "because",
  "makes",
  "feel",
  "relaxed",
  "happy",
  "enjoyable",
  "modern",
  "suitable",
  "different",
  "listeners",
  "rock",
  "strong",
  "energetic",
  "type",
  "uses",
  "electric",
  "guitars",
  "bass",
  "drums",
  "powerful",
  "singing",
  "sound",
  "loud",
  "exciting",
  "full",
  "energy",
  "may",
  "talk",
  "freedom",
  "youth",
  "problems",
  "or",
  "change",
  "some",
  "fast",
  "wild",
  "while",
  "others",
  "slower",
  "more",
  "emotional",
  "bands",
  "have",
  "several",
  "members",
  "each",
  "person",
  "plays",
  "instrument",
  "sings",
  "live",
  "concerts",
  "musicians",
  "move",
  "around",
  "stage",
  "connect",
  "audience",
  "feels",
  "honest",
  "give",
  "real",
  "courage",
  "fresh",
  "feeling",
  "classical",
  "beautiful",
  "traditional",
  "piano",
  "violin",
  "cello",
  "flute",
  "other",
  "instruments",
  "orchestra",
  "soft",
  "peaceful",
  "dramatic",
  "pieces",
  "written",
  "hundreds",
  "years",
  "ago",
  "composers",
  "such",
  "as",
  "mozart",
  "beethoven",
  "created",
  "still",
  "today",
  "performed",
  "concert",
  "halls",
  "theaters",
  "special",
  "must",
  "practise",
  "carefully",
  "long",
  "difficult",
  "really",
  "helps",
  "relax",
  "think",
  "clearly",
  "improve",
  "concentration",
  "studying",
  "reading",
  "writing",
  "working",
  "quietly",
  "day"
];
