// ===== room03 ESSAY =====

const newEssayData = [
  {
    "text": "7. The Guest Room\nThe guest room is located on the ground floor, near the bathroom. It has a comfortable bed, a wardrobe, a small table, and a chair. There are also clean blankets, pillows, and towels for visitors.\n\nWhen relatives or friends stay at our house, they sleep in this room. Before they arrive, my family cleans the room, changes the bedsheets, and prepares some drinking water. We want our guests to feel welcome.\n\nThe guest room is usually empty, but it is still an important part of the house. A clean and comfortable guest room shows kindness and respect to visitors.",
    "vi": "7. Phòng dành cho khách\nPhòng dành cho khách nằm ở tầng trệt, gần phòng tắm. Phòng có một chiếc giường thoải mái, tủ quần áo, một chiếc bàn nhỏ và một chiếc ghế. Ngoài ra còn có chăn, gối và khăn sạch dành cho khách.\n\nKhi người thân hoặc bạn bè ở lại nhà chúng tôi, họ ngủ trong căn phòng này. Trước khi họ đến, gia đình tôi dọn phòng, thay ga giường và chuẩn bị một ít nước uống. Chúng tôi muốn khách cảm thấy được chào đón.\n\nPhòng khách thường để trống nhưng vẫn là một phần quan trọng của ngôi nhà. Một phòng khách sạch sẽ và thoải mái thể hiện sự tử tế và tôn trọng đối với khách."
  },
  {
    "text": "8. The Laundry Room\nThe laundry room is at the back of my house, near the kitchen. It contains a washing machine, some baskets, detergent, clothes hangers, and cleaning tools. There is also a window that brings fresh air into the room.\n\nMy family uses this room to wash and organize clothes. We separate white clothes from colored clothes before washing them. After that, we hang the clothes outside or use a drying machine.\n\nThe laundry room helps us keep the house organized. We should store cleaning products safely and keep them away from children. A tidy laundry room makes washing clothes easier and faster.",
    "vi": "8. Phòng giặt\nPhòng giặt nằm ở phía sau nhà tôi, gần nhà bếp. Phòng có máy giặt, vài chiếc giỏ, chất giặt tẩy, móc quần áo và dụng cụ vệ sinh. Ngoài ra còn có một cửa sổ đưa không khí trong lành vào phòng.\n\nGia đình tôi dùng căn phòng này để giặt và sắp xếp quần áo. Chúng tôi tách quần áo trắng khỏi quần áo màu trước khi giặt. Sau đó, chúng tôi phơi quần áo bên ngoài hoặc dùng máy sấy.\n\nPhòng giặt giúp chúng tôi giữ ngôi nhà ngăn nắp. Chúng ta nên cất các sản phẩm vệ sinh một cách an toàn và để chúng xa trẻ em. Một phòng giặt gọn gàng giúp việc giặt quần áo dễ dàng và nhanh hơn."
  },
  {
    "text": "9. The Storage Room\nThe storage room is under the stairs. It is a small room where my family keeps things that we do not use every day. There are boxes, old books, suitcases, tools, and seasonal decorations inside.\n\nWe organize the items into different groups and write labels on the boxes. This helps us find things quickly when we need them. We also check the room regularly and throw away broken or unnecessary objects.\n\nA storage room is useful because it keeps other rooms clean and spacious. However, it should not become too crowded. Good organization makes the storage room safer and more convenient.",
    "vi": "9. Phòng chứa đồ\nPhòng chứa đồ nằm dưới cầu thang. Đây là một căn phòng nhỏ nơi gia đình tôi cất những thứ mà chúng tôi không dùng hằng ngày. Bên trong có các hộp, sách cũ, va-li, dụng cụ và đồ trang trí theo mùa.\n\nChúng tôi sắp xếp các đồ vật thành những nhóm khác nhau và viết nhãn lên các hộp. Điều này giúp chúng tôi tìm đồ nhanh chóng khi cần. Chúng tôi cũng thường xuyên kiểm tra căn phòng và vứt bỏ những vật bị hỏng hoặc không cần thiết.\n\nPhòng chứa đồ rất hữu ích vì nó giúp những căn phòng khác sạch sẽ và rộng rãi. Tuy nhiên, phòng không nên trở nên quá chật chội. Việc sắp xếp tốt làm cho phòng chứa đồ an toàn hơn và thuận tiện hơn."
  },
  {
    "text": "10. The Garage\nThe garage is on the left side of my house. It has enough space for a car, two motorbikes, and some bicycles. My family also keeps helmets, tools, and cleaning equipment in this area.\n\nEvery morning, we take our vehicles out of the garage before going to work or school. In the evening, we put them back and lock the garage door carefully. We clean the floor and check the vehicles regularly.\n\nThe garage protects our vehicles from rain, sunlight, and theft. It should always be clean, bright, and secure. A well-organized garage makes travelling more convenient for the whole family.",
    "vi": "10. Ga-ra\nGa-ra nằm ở phía bên trái ngôi nhà của tôi. Nơi đây có đủ chỗ cho một chiếc ô tô, hai xe máy và một số xe đạp. Gia đình tôi cũng để mũ bảo hiểm, dụng cụ và thiết bị vệ sinh trong khu vực này.\n\nMỗi sáng, chúng tôi đưa các phương tiện ra khỏi ga-ra trước khi đi làm hoặc đi học. Vào buổi tối, chúng tôi đưa chúng trở lại và khóa cửa ga-ra cẩn thận. Chúng tôi lau sàn và kiểm tra các phương tiện thường xuyên.\n\nGa-ra bảo vệ các phương tiện của chúng tôi khỏi mưa, ánh nắng và trộm cắp. Nơi đây luôn nên sạch sẽ, sáng sủa và an toàn. Một ga-ra được sắp xếp tốt giúp việc đi lại thuận tiện hơn cho cả gia đình."
  }
];
