// ===== room02 ESSAY =====

const newEssayData = [
  {
    "text": "4. The Dining Room\nThe dining room is between the kitchen and the living room. It has a large dining table, several chairs, a cupboard, and a light above the table. We also put some flowers in the middle of the table.\n\nMy family usually has breakfast and dinner together in this room. During meals, we talk about our work, school, and daily activities. We try not to use our phones while eating.\n\nI enjoy spending time in the dining room because family meals are important. They give us time to communicate and understand each other. A clean and comfortable dining room makes every meal more enjoyable and meaningful.",
    "vi": "4. Phòng ăn\nPhòng ăn nằm giữa nhà bếp và phòng khách. Phòng có một bàn ăn lớn, vài chiếc ghế, một chiếc tủ và một bóng đèn phía trên bàn. Chúng tôi cũng đặt một ít hoa ở giữa bàn.\n\nGia đình tôi thường ăn sáng và ăn tối cùng nhau trong căn phòng này. Trong bữa ăn, chúng tôi nói về công việc, trường học và các hoạt động hằng ngày. Chúng tôi cố gắng không dùng điện thoại khi đang ăn.\n\nTôi thích dành thời gian trong phòng ăn vì những bữa cơm gia đình rất quan trọng. Chúng cho chúng tôi thời gian để giao tiếp và hiểu nhau hơn. Một phòng ăn sạch sẽ và thoải mái làm cho mỗi bữa ăn thú vị và ý nghĩa hơn."
  },
  {
    "text": "5. The Bathroom\nThe bathroom is next to my bedroom. It is not very large, but it is clean and useful. There is a shower, a toilet, a sink, a mirror, and a small cupboard for towels and personal items.\n\nI use the bathroom every morning and evening. I brush my teeth, wash my face, take a shower, and prepare myself for the day. After using it, I always turn off the water and keep the floor dry.\n\nA clean bathroom is important for good health. Everyone in the family should keep it tidy and save water. We should also clean the sink, mirror, and floor regularly.",
    "vi": "5. Phòng tắm\nPhòng tắm ở cạnh phòng ngủ của tôi. Nó không quá lớn nhưng sạch sẽ và hữu ích. Trong phòng có vòi sen, bồn cầu, bồn rửa, gương và một chiếc tủ nhỏ để khăn tắm cùng các đồ dùng cá nhân.\n\nTôi sử dụng phòng tắm mỗi sáng và tối. Tôi đánh răng, rửa mặt, tắm và chuẩn bị cho ngày mới. Sau khi sử dụng, tôi luôn khóa nước và giữ sàn khô ráo.\n\nMột phòng tắm sạch rất quan trọng đối với sức khỏe tốt. Mọi người trong gia đình nên giữ phòng gọn gàng và tiết kiệm nước. Chúng ta cũng nên thường xuyên làm sạch bồn rửa, gương và sàn nhà."
  },
  {
    "text": "6. The Study Room\nThe study room is in a quiet area of my house. It has a desk, a comfortable chair, a bookshelf, a computer, and a reading lamp. The room is simple, but it helps me focus on my work.\n\nI often use this room to study English, read books, and complete important tasks. My children also use it to do their homework. We try to keep the room quiet and avoid unnecessary distractions.\n\nI like the study room because it supports learning and creativity. I organize my books and documents carefully. A peaceful study room can help people work better and learn new things every day.",
    "vi": "6. Phòng học\nPhòng học nằm ở một khu vực yên tĩnh trong nhà tôi. Phòng có bàn học, một chiếc ghế thoải mái, giá sách, máy tính và đèn đọc sách. Căn phòng đơn giản nhưng giúp tôi tập trung vào công việc.\n\nTôi thường dùng căn phòng này để học tiếng Anh, đọc sách và hoàn thành các nhiệm vụ quan trọng. Các con tôi cũng dùng phòng để làm bài tập về nhà. Chúng tôi cố gắng giữ phòng yên tĩnh và tránh những điều gây xao nhãng không cần thiết.\n\nTôi thích phòng học vì nó hỗ trợ việc học và sự sáng tạo. Tôi sắp xếp sách và tài liệu cẩn thận. Một phòng học yên bình có thể giúp mọi người làm việc tốt hơn và học những điều mới mỗi ngày."
  }
];
