// ===== room01 ESSAY =====

const newEssayData = [
  {
    "text": "1. The Living Room\nThe living room is an important place in my house. It is usually at the front of the house, near the main door. There is a sofa, a television, a coffee table, and some family pictures on the wall.\n\nMy family often spends time together in this room. We watch television, talk about our day, listen to music, or welcome visitors. Sometimes, my children sit on the sofa and read books.\n\nI like the living room because it is comfortable and friendly. I always keep it clean and tidy. It is a wonderful place where my family can relax and enjoy happy moments together.",
    "vi": "1. Phòng khách\nPhòng khách là một nơi quan trọng trong ngôi nhà của tôi. Nó thường ở phía trước ngôi nhà, gần cửa chính. Trong phòng có một chiếc ghế sofa, một chiếc tivi, một bàn trà và một số ảnh gia đình trên tường.\n\nGia đình tôi thường dành thời gian cùng nhau trong căn phòng này. Chúng tôi xem tivi, trò chuyện về một ngày của mình, nghe nhạc hoặc đón khách. Đôi khi, các con tôi ngồi trên ghế sofa và đọc sách.\n\nTôi thích phòng khách vì nó thoải mái và thân thiện. Tôi luôn giữ phòng sạch sẽ và gọn gàng. Đây là một nơi tuyệt vời để gia đình tôi thư giãn và tận hưởng những khoảnh khắc vui vẻ bên nhau."
  },
  {
    "text": "2. The Bedroom\nMy bedroom is a quiet and comfortable room. It is located upstairs, next to the bathroom. Inside the room, there is a bed, a wardrobe, a small desk, a chair, and a lamp.\n\nI usually study or read books at my desk in the evening. Before going to sleep, I prepare my clothes for the next day and put my phone away. I also open the window to get some fresh air.\n\nI like my bedroom because it gives me privacy and peace. I keep my clothes and personal things organized. After a busy day, my bedroom is the best place to rest and sleep.",
    "vi": "2. Phòng ngủ\nPhòng ngủ của tôi là một căn phòng yên tĩnh và thoải mái. Nó nằm ở tầng trên, cạnh phòng tắm. Bên trong phòng có một chiếc giường, một tủ quần áo, một bàn nhỏ, một chiếc ghế và một chiếc đèn.\n\nTôi thường học hoặc đọc sách tại bàn vào buổi tối. Trước khi đi ngủ, tôi chuẩn bị quần áo cho ngày hôm sau và cất điện thoại sang một bên. Tôi cũng mở cửa sổ để đón không khí trong lành.\n\nTôi thích phòng ngủ vì nó mang lại cho tôi sự riêng tư và bình yên. Tôi giữ quần áo và đồ dùng cá nhân ngăn nắp. Sau một ngày bận rộn, phòng ngủ là nơi tốt nhất để tôi nghỉ ngơi và ngủ."
  },
  {
    "text": "3. The Kitchen\nThe kitchen is at the back of my house, near the dining room. It has a refrigerator, a cooker, a sink, some cupboards, and many cooking tools. The room is bright, clean, and well organized.\n\nMy family prepares meals in the kitchen every day. We cook rice, soup, vegetables, meat, and other delicious dishes. Sometimes, my children help wash vegetables, prepare plates, or clean the table.\n\nThe kitchen is one of my favorite rooms because it is always full of wonderful smells. Cooking together helps my family become closer. We should always keep the kitchen clean and safe after preparing food.",
    "vi": "3. Nhà bếp\nNhà bếp nằm ở phía sau nhà tôi, gần phòng ăn. Trong bếp có tủ lạnh, bếp nấu, bồn rửa, một số tủ đựng đồ và nhiều dụng cụ nấu ăn. Căn phòng sáng sủa, sạch sẽ và được sắp xếp ngăn nắp.\n\nGia đình tôi chuẩn bị các bữa ăn trong bếp mỗi ngày. Chúng tôi nấu cơm, canh, rau, thịt và các món ăn ngon khác. Đôi khi, các con tôi giúp rửa rau, chuẩn bị đĩa hoặc lau bàn.\n\nNhà bếp là một trong những căn phòng yêu thích của tôi vì nơi đây luôn đầy những mùi thơm tuyệt vời. Nấu ăn cùng nhau giúp gia đình tôi gần gũi hơn. Chúng ta nên luôn giữ bếp sạch sẽ và an toàn sau khi chuẩn bị thức ăn."
  }
];
