// ===== festival02 ESSAY =====

const newEssayData = [
  {
    "text": "4. Giong Festival – Lễ hội Gióng\nGiong Festival is held in Hanoi to honor Saint Giong, a legendary Vietnamese hero. The festival usually takes place in the fourth lunar month. It remembers his fight to protect the country from foreign enemies.\n\nDuring the main ceremony, villagers act out important parts of the old story. People carry flags, drums, and special objects through the village. The event is lively and meaningful.\n\nMany visitors watch traditional performances and join local activities. They also visit temples, offer incense, and pray for peace.\n\nGiong Festival teaches courage, unity, and love for the country. It is an important part of Vietnamese history and spiritual life for young and old people today.",
    "vi": "4. Giong Festival – Lễ hội Gióng\nLễ hội Gióng được tổ chức tại Hà Nội để tôn vinh Thánh Gióng, một vị anh hùng huyền thoại của Việt Nam. Lễ hội thường diễn ra vào tháng tư âm lịch. Lễ hội tưởng nhớ cuộc chiến của ngài để bảo vệ đất nước khỏi kẻ thù ngoại xâm.\n\nTrong nghi lễ chính, dân làng diễn lại những phần quan trọng của câu chuyện xưa. Mọi người mang cờ, trống và các vật phẩm đặc biệt đi qua làng. Sự kiện sôi động và đầy ý nghĩa.\n\nNhiều du khách xem các màn biểu diễn truyền thống và tham gia hoạt động địa phương. Họ cũng đến các đền, dâng hương và cầu bình an.\n\nLễ hội Gióng dạy về lòng dũng cảm, sự đoàn kết và tình yêu đất nước. Đây là một phần quan trọng của lịch sử và đời sống tâm linh Việt Nam đối với cả người trẻ và người lớn tuổi ngày nay."
  },
  {
    "text": "5. Yen Tu Festival – Lễ hội Yên Tử\nYen Tu Festival is held in Quang Ninh Province after the Lunar New Year. It attracts many visitors who want to explore nature and learn about Vietnamese Buddhism.\n\nPeople climb Yen Tu Mountain or use a cable car to reach temples and pagodas. Along the way, they see forests, clouds, old trees, and beautiful mountain views.\n\nThe most famous place is Dong Pagoda, located near the top. Visitors light incense, pray for peace, and enjoy the quiet air. Some people also visit Hoa Yen Pagoda.\n\nThe festival is a spiritual journey and a healthy outdoor activity. It helps people feel calm, patient, and connected with nature during the festival season.",
    "vi": "5. Yen Tu Festival – Lễ hội Yên Tử\nLễ hội Yên Tử được tổ chức tại tỉnh Quảng Ninh sau Tết Nguyên đán. Lễ hội thu hút nhiều du khách muốn khám phá thiên nhiên và tìm hiểu về Phật giáo Việt Nam.\n\nMọi người leo núi Yên Tử hoặc đi cáp treo để đến các đền và chùa. Dọc đường, họ nhìn thấy rừng, mây, cây cổ thụ và cảnh núi non đẹp.\n\nĐịa điểm nổi tiếng nhất là chùa Đồng, nằm gần đỉnh núi. Du khách thắp hương, cầu bình an và tận hưởng không khí yên tĩnh. Một số người cũng đến chùa Hoa Yên.\n\nLễ hội là một hành trình tâm linh và một hoạt động ngoài trời lành mạnh. Nó giúp mọi người cảm thấy bình tĩnh, kiên nhẫn và gắn kết với thiên nhiên trong mùa lễ hội."
  },
  {
    "text": "6. The Whale Worship Festival – Lễ hội Cầu Ngư\nThe Whale Worship Festival is held in many coastal areas of central Vietnam. Fishermen organize it to thank the whale and pray for safe trips, good weather, and a successful fishing season.\n\nThe festival begins with respectful ceremonies at a temple or near the sea. People offer food, flowers, and incense. Elders read prayers, while boats are decorated with bright flags.\n\nAfter the ceremony, visitors can watch boat races, folk singing, and traditional dances. The atmosphere is exciting and friendly.\n\nThis festival shows the strong relationship between coastal people and the sea. It also protects local beliefs, traditions, and community spirit in towns along the coast today for future generations.",
    "vi": "6. The Whale Worship Festival – Lễ hội Cầu Ngư\nLễ hội Cầu Ngư được tổ chức tại nhiều vùng ven biển miền Trung Việt Nam. Ngư dân tổ chức lễ hội để cảm tạ cá voi và cầu mong những chuyến đi an toàn, thời tiết tốt và một mùa đánh bắt thành công.\n\nLễ hội bắt đầu bằng các nghi lễ trang nghiêm tại một ngôi đền hoặc gần biển. Mọi người dâng thức ăn, hoa và hương. Các bậc cao niên đọc lời cầu nguyện, trong khi thuyền được trang trí bằng những lá cờ rực rỡ.\n\nSau nghi lễ, du khách có thể xem đua thuyền, hát dân gian và các điệu múa truyền thống. Bầu không khí sôi động và thân thiện.\n\nLễ hội này thể hiện mối quan hệ bền chặt giữa người dân ven biển và biển cả. Nó cũng bảo tồn tín ngưỡng, truyền thống và tinh thần cộng đồng địa phương ở các thị trấn dọc bờ biển ngày nay cho các thế hệ tương lai."
  }
];
