// ===== festival01 VOCABULARY =====

const lessonVocabularyWords = [
  "hung",
  "kings",
  "festival",
  "held",
  "phu",
  "tho",
  "province",
  "every",
  "year",
  "takes",
  "place",
  "tenth",
  "day",
  "third",
  "lunar",
  "month",
  "many",
  "people",
  "visit",
  "temple",
  "remember",
  "ancient",
  "vietnam",
  "offer",
  "flowers",
  "fruit",
  "rice",
  "cakes",
  "and",
  "incense",
  "important",
  "ceremonies",
  "serious",
  "respectful",
  "way",
  "traditional",
  "music",
  "drum",
  "performances",
  "create",
  "special",
  "atmosphere",
  "visitors",
  "can",
  "also",
  "watch",
  "folk",
  "games",
  "wrestling",
  "cultural",
  "shows",
  "local",
  "wear",
  "beautiful",
  "clothes",
  "welcome",
  "guests",
  "warmly",
  "teaches",
  "young",
  "vietnamese",
  "history",
  "respect",
  "ancestors",
  "reminds",
  "everyone",
  "protect",
  "national",
  "traditions",
  "together",
  "today",
  "perfume",
  "pagoda",
  "one",
  "largest",
  "religious",
  "festivals",
  "hanoi",
  "first",
  "thousands",
  "come",
  "pray",
  "health",
  "luck",
  "happiness",
  "journey",
  "begins",
  "boat",
  "ride",
  "yen",
  "stream",
  "water",
  "calm",
  "mountains",
  "views",
  "then",
  "walk",
  "or",
  "take",
  "cable",
  "car",
  "pagodas",
  "huong",
  "tich",
  "cave",
  "thien",
  "tru",
  "other",
  "sacred",
  "places",
  "light",
  "enjoy",
  "peaceful",
  "both",
  "trip",
  "nature",
  "tour",
  "helps",
  "relax",
  "think",
  "positively",
  "appreciate",
  "culture",
  "lim",
  "famous",
  "bac",
  "ninh",
  "usually",
  "thirteenth",
  "well",
  "known",
  "quan",
  "ho",
  "songs",
  "male",
  "female",
  "singers",
  "sing",
  "often",
  "perform",
  "boats",
  "hills",
  "village",
  "stages",
  "gentle",
  "emotional",
  "full",
  "bamboo",
  "swinging",
  "human",
  "chess",
  "taste",
  "food",
  "meet",
  "friendly",
  "protects",
  "northern",
  "brings",
  "communities",
  "understand",
  "love",
  "heritage"
];

const newVocabData = [
  {
    "id": 1,
    "word": "hung",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/hʊŋ/",
    "meaning": "Hùng",
    "ex1": "The Hung Kings Festival is held in Phu Tho Province every year.",
    "ex1_vi": "Lễ hội Đền Hùng được tổ chức tại tỉnh Phú Thọ hằng năm."
  },
  {
    "id": 2,
    "word": "kings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɪŋz/",
    "meaning": "các vị vua",
    "ex1": "The Hung Kings Festival is held in Phu Tho Province every year.",
    "ex1_vi": "Lễ hội Đền Hùng được tổ chức tại tỉnh Phú Thọ hằng năm."
  },
  {
    "id": 3,
    "word": "festival",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɛstʌvʌl/",
    "meaning": "lễ hội",
    "ex1": "During the festival, people offer flowers, fruit, rice cakes, and incense.",
    "ex1_vi": "Trong lễ hội, mọi người dâng hoa, trái cây, bánh gạo và hương."
  },
  {
    "id": 4,
    "word": "held",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛld/",
    "meaning": "được tổ chức",
    "ex1": "Important ceremonies are held in a serious and respectful way.",
    "ex1_vi": "Các nghi lễ quan trọng được tổ chức theo cách trang nghiêm và kính cẩn."
  },
  {
    "id": 5,
    "word": "phu",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/fuː/",
    "meaning": "Phú",
    "ex1": "Visitors learn about phu during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Phú trong lễ hội Việt Nam này."
  },
  {
    "id": 6,
    "word": "tho",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/tɔː/",
    "meaning": "Thọ",
    "ex1": "Visitors learn about tho during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Thọ trong lễ hội Việt Nam này."
  },
  {
    "id": 7,
    "word": "province",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑvʌns/",
    "meaning": "tỉnh",
    "ex1": "Lim Festival is a famous cultural festival in Bac Ninh Province.",
    "ex1_vi": "Hội Lim là một lễ hội văn hóa nổi tiếng ở tỉnh Bắc Ninh."
  },
  {
    "id": 8,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ɛvɚi/",
    "meaning": "mỗi",
    "ex1": "Every visitors enjoy the cultural activities during the festival.",
    "ex1_vi": "Mỗi du khách thưởng thức các hoạt động văn hóa trong lễ hội."
  },
  {
    "id": 9,
    "word": "year",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jɪr/",
    "meaning": "năm",
    "ex1": "Visitors learn about year during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về năm trong lễ hội Việt Nam này."
  },
  {
    "id": 10,
    "word": "takes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪks/",
    "meaning": "diễn ra",
    "ex1": "It takes place on the tenth day of the third lunar month.",
    "ex1_vi": "Lễ hội diễn ra vào ngày mùng mười tháng ba âm lịch."
  },
  {
    "id": 11,
    "word": "place",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪs/",
    "meaning": "nơi; địa điểm",
    "ex1": "It takes place on the tenth day of the third lunar month.",
    "ex1_vi": "Lễ hội diễn ra vào ngày mùng mười tháng ba âm lịch."
  },
  {
    "id": 12,
    "word": "tenth",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈɛnθ/",
    "meaning": "thứ mười",
    "ex1": "The festival has a tenth feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét thứ mười mà du khách có thể nhận thấy."
  },
  {
    "id": 13,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/deɪ/",
    "meaning": "ngày",
    "ex1": "It usually takes place on the thirteenth day of the first lunar month.",
    "ex1_vi": "Lễ hội thường diễn ra vào ngày mười ba tháng giêng âm lịch."
  },
  {
    "id": 14,
    "word": "third",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/θˈɝd/",
    "meaning": "thứ ba",
    "ex1": "It is held in Hanoi from the first to the third lunar month.",
    "ex1_vi": "Lễ hội được tổ chức tại Hà Nội từ tháng giêng đến tháng ba âm lịch."
  },
  {
    "id": 15,
    "word": "lunar",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈunɝ/",
    "meaning": "âm lịch",
    "ex1": "It is held in Hanoi from the first to the third lunar month.",
    "ex1_vi": "Lễ hội được tổ chức tại Hà Nội từ tháng giêng đến tháng ba âm lịch."
  },
  {
    "id": 16,
    "word": "month",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌnθ/",
    "meaning": "tháng",
    "ex1": "It usually takes place on the thirteenth day of the first lunar month.",
    "ex1_vi": "Lễ hội thường diễn ra vào ngày mười ba tháng giêng âm lịch."
  },
  {
    "id": 17,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mɛni/",
    "meaning": "nhiều",
    "ex1": "Many people visit the Hung Temple to remember the ancient kings of Vietnam.",
    "ex1_vi": "Nhiều người đến Đền Hùng để tưởng nhớ các vị vua cổ của Việt Nam."
  },
  {
    "id": 18,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipəl/",
    "meaning": "mọi người",
    "ex1": "Many people visit the Hung Temple to remember the ancient kings of Vietnam.",
    "ex1_vi": "Nhiều người đến Đền Hùng để tưởng nhớ các vị vua cổ của Việt Nam."
  },
  {
    "id": 19,
    "word": "visit",
    "type": "verb",
    "cat": "v",
    "phonetic": "/vˈɪzɪt/",
    "meaning": "thăm",
    "ex1": "People visit Huong Tich Cave, Thien Tru Pagoda, and other sacred places.",
    "ex1_vi": "Mọi người đến thăm động Hương Tích, chùa Thiên Trù và những địa điểm linh thiêng khác."
  },
  {
    "id": 20,
    "word": "temple",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛmpʌl/",
    "meaning": "đền",
    "ex1": "Visitors learn about temple during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về đền trong lễ hội Việt Nam này."
  },
  {
    "id": 21,
    "word": "remember",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪmˈɛmbɝ/",
    "meaning": "tưởng nhớ",
    "ex1": "Local people remember during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương tưởng nhớ trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 22,
    "word": "ancient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈeɪnʃənt/",
    "meaning": "cổ xưa",
    "ex1": "The festival has a ancient feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét cổ xưa mà du khách có thể nhận thấy."
  },
  {
    "id": 23,
    "word": "vietnam",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/ˌviːɛtˈnɑːm/",
    "meaning": "Việt Nam",
    "ex1": "The Perfume Pagoda Festival is one of the largest religious festivals in Vietnam.",
    "ex1_vi": "Lễ hội Chùa Hương là một trong những lễ hội tôn giáo lớn nhất ở Việt Nam."
  },
  {
    "id": 24,
    "word": "offer",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɔfɝ/",
    "meaning": "dâng; cúng",
    "ex1": "During the festival, people offer flowers, fruit, rice cakes, and incense.",
    "ex1_vi": "Trong lễ hội, mọi người dâng hoa, trái cây, bánh gạo và hương."
  },
  {
    "id": 25,
    "word": "flowers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈaʊɝz/",
    "meaning": "hoa",
    "ex1": "Visitors learn about flowers during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về hoa trong lễ hội Việt Nam này."
  },
  {
    "id": 26,
    "word": "fruit",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fɹˈuːt/",
    "meaning": "trái cây",
    "ex1": "Visitors learn about fruit during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về trái cây trong lễ hội Việt Nam này."
  },
  {
    "id": 27,
    "word": "rice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɹˈaɪs/",
    "meaning": "gạo",
    "ex1": "Visitors learn about rice during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về gạo trong lễ hội Việt Nam này."
  },
  {
    "id": 28,
    "word": "cakes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈeɪks/",
    "meaning": "bánh",
    "ex1": "Visitors learn about cakes during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về bánh trong lễ hội Việt Nam này."
  },
  {
    "id": 29,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ənd/",
    "meaning": "và",
    "ex1": "Important ceremonies are held in a serious and respectful way.",
    "ex1_vi": "Các nghi lễ quan trọng được tổ chức theo cách trang nghiêm và kính cẩn."
  },
  {
    "id": 30,
    "word": "incense",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnsˈɛns/",
    "meaning": "hương",
    "ex1": "They light incense and enjoy the peaceful atmosphere.",
    "ex1_vi": "Họ thắp hương và tận hưởng bầu không khí thanh bình."
  },
  {
    "id": 31,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔɹtənt/",
    "meaning": "quan trọng",
    "ex1": "The festival has a important feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét quan trọng mà du khách có thể nhận thấy."
  },
  {
    "id": 32,
    "word": "ceremonies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛrʌmˌoʊniz/",
    "meaning": "nghi lễ",
    "ex1": "Visitors learn about ceremonies during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về nghi lễ trong lễ hội Việt Nam này."
  },
  {
    "id": 33,
    "word": "serious",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪriʌs/",
    "meaning": "trang nghiêm",
    "ex1": "The festival has a serious feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét trang nghiêm mà du khách có thể nhận thấy."
  },
  {
    "id": 34,
    "word": "respectful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪspˈɛktfʌl/",
    "meaning": "kính cẩn",
    "ex1": "The festival has a respectful feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét kính cẩn mà du khách có thể nhận thấy."
  },
  {
    "id": 35,
    "word": "way",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪ/",
    "meaning": "cách",
    "ex1": "Visitors learn about way during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về cách trong lễ hội Việt Nam này."
  },
  {
    "id": 36,
    "word": "traditional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trʌdˈɪʃʌnʌl/",
    "meaning": "truyền thống",
    "ex1": "Traditional music and drum performances create a special atmosphere.",
    "ex1_vi": "Âm nhạc truyền thống và các màn biểu diễn trống tạo nên một bầu không khí đặc biệt."
  },
  {
    "id": 37,
    "word": "music",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mjˈuzɪk/",
    "meaning": "âm nhạc",
    "ex1": "Traditional music and drum performances create a special atmosphere.",
    "ex1_vi": "Âm nhạc truyền thống và các màn biểu diễn trống tạo nên một bầu không khí đặc biệt."
  },
  {
    "id": 38,
    "word": "drum",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈʌm/",
    "meaning": "trống",
    "ex1": "Visitors learn about drum during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về trống trong lễ hội Việt Nam này."
  },
  {
    "id": 39,
    "word": "performances",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɝfˈɔrmʌnsʌz/",
    "meaning": "các màn biểu diễn",
    "ex1": "Visitors learn about performances during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các màn biểu diễn trong lễ hội Việt Nam này."
  },
  {
    "id": 40,
    "word": "create",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪt/",
    "meaning": "tạo ra",
    "ex1": "The water is calm, and the mountains create beautiful views.",
    "ex1_vi": "Nước yên ả và những ngọn núi tạo nên cảnh đẹp."
  },
  {
    "id": 41,
    "word": "special",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/spˈɛʃəl/",
    "meaning": "đặc biệt",
    "ex1": "The festival has a special feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét đặc biệt mà du khách có thể nhận thấy."
  },
  {
    "id": 42,
    "word": "atmosphere",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈætməsfˌɪr/",
    "meaning": "bầu không khí",
    "ex1": "They light incense and enjoy the peaceful atmosphere.",
    "ex1_vi": "Họ thắp hương và tận hưởng bầu không khí thanh bình."
  },
  {
    "id": 43,
    "word": "visitors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪzɪtɝz/",
    "meaning": "du khách",
    "ex1": "Visitors can also watch folk games, wrestling, and cultural shows.",
    "ex1_vi": "Du khách cũng có thể xem các trò chơi dân gian, đấu vật và các chương trình văn hóa."
  },
  {
    "id": 44,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Visitors can also watch folk games, wrestling, and cultural shows.",
    "ex1_vi": "Du khách cũng có thể xem các trò chơi dân gian, đấu vật và các chương trình văn hóa."
  },
  {
    "id": 45,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "It also shows respect for ancestors and reminds everyone to protect national traditions together today.",
    "ex1_vi": "Lễ hội cũng thể hiện sự kính trọng tổ tiên và nhắc nhở mọi người cùng bảo vệ các truyền thống dân tộc ngày nay."
  },
  {
    "id": 46,
    "word": "watch",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɑtʃ/",
    "meaning": "xem",
    "ex1": "Local people watch during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương xem trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 47,
    "word": "folk",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈoʊk/",
    "meaning": "dân gian",
    "ex1": "The festival is well known for Quan Ho folk songs.",
    "ex1_vi": "Lễ hội nổi tiếng với những làn điệu dân ca Quan họ."
  },
  {
    "id": 48,
    "word": "games",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈeɪmz/",
    "meaning": "trò chơi",
    "ex1": "Visitors can enjoy wrestling, bamboo swinging, human chess, and other folk games.",
    "ex1_vi": "Du khách có thể thưởng thức đấu vật, đánh đu tre, cờ người và các trò chơi dân gian khác."
  },
  {
    "id": 49,
    "word": "wrestling",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈɛslɪŋ/",
    "meaning": "đấu vật",
    "ex1": "Visitors can enjoy wrestling, bamboo swinging, human chess, and other folk games.",
    "ex1_vi": "Du khách có thể thưởng thức đấu vật, đánh đu tre, cờ người và các trò chơi dân gian khác."
  },
  {
    "id": 50,
    "word": "cultural",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌltʃɝʌl/",
    "meaning": "thuộc văn hóa",
    "ex1": "Lim Festival is a famous cultural festival in Bac Ninh Province.",
    "ex1_vi": "Hội Lim là một lễ hội văn hóa nổi tiếng ở tỉnh Bắc Ninh."
  },
  {
    "id": 51,
    "word": "shows",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈoʊz/",
    "meaning": "các chương trình; thể hiện",
    "ex1": "It also shows respect for ancestors and reminds everyone to protect national traditions together today.",
    "ex1_vi": "Lễ hội cũng thể hiện sự kính trọng tổ tiên và nhắc nhở mọi người cùng bảo vệ các truyền thống dân tộc ngày nay."
  },
  {
    "id": 52,
    "word": "local",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈoʊkəl/",
    "meaning": "địa phương",
    "ex1": "Local people wear beautiful traditional clothes and welcome guests warmly.",
    "ex1_vi": "Người dân địa phương mặc trang phục truyền thống đẹp và nồng nhiệt chào đón khách."
  },
  {
    "id": 53,
    "word": "wear",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɛɹ/",
    "meaning": "mặc",
    "ex1": "Local people wear beautiful traditional clothes and welcome guests warmly.",
    "ex1_vi": "Người dân địa phương mặc trang phục truyền thống đẹp và nồng nhiệt chào đón khách."
  },
  {
    "id": 54,
    "word": "beautiful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bjutəfəl/",
    "meaning": "đẹp",
    "ex1": "The water is calm, and the mountains create beautiful views.",
    "ex1_vi": "Nước yên ả và những ngọn núi tạo nên cảnh đẹp."
  },
  {
    "id": 55,
    "word": "clothes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈoʊðz/",
    "meaning": "quần áo",
    "ex1": "Male and female singers wear traditional clothes and sing together.",
    "ex1_vi": "Nam và nữ liền anh liền chị mặc trang phục truyền thống và hát cùng nhau."
  },
  {
    "id": 56,
    "word": "welcome",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɛlkʌm/",
    "meaning": "chào đón",
    "ex1": "Local people welcome during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương chào đón trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 57,
    "word": "guests",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɛsts/",
    "meaning": "khách",
    "ex1": "Visitors learn about guests during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về khách trong lễ hội Việt Nam này."
  },
  {
    "id": 58,
    "word": "warmly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈɔrmli/",
    "meaning": "nồng nhiệt",
    "ex1": "Local people welcome festival visitors warmly each year.",
    "ex1_vi": "Người dân địa phương chào đón du khách nồng nhiệt mỗi năm."
  },
  {
    "id": 59,
    "word": "teaches",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈiːtʃɪz/",
    "meaning": "dạy",
    "ex1": "The festival teaches young people about Vietnamese history.",
    "ex1_vi": "Lễ hội dạy người trẻ về lịch sử Việt Nam."
  },
  {
    "id": 60,
    "word": "young",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jʌŋ/",
    "meaning": "trẻ",
    "ex1": "The festival teaches young people about Vietnamese history.",
    "ex1_vi": "Lễ hội dạy người trẻ về lịch sử Việt Nam."
  },
  {
    "id": 61,
    "word": "vietnamese",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/viˌɛtnɑmˈis/",
    "meaning": "thuộc Việt Nam; người Việt",
    "ex1": "It helps people relax, think positively, and appreciate Vietnamese culture today.",
    "ex1_vi": "Lễ hội giúp mọi người thư giãn, suy nghĩ tích cực và trân trọng văn hóa Việt Nam ngày nay."
  },
  {
    "id": 62,
    "word": "history",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɪstɚɹi/",
    "meaning": "lịch sử",
    "ex1": "Visitors learn about history during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về lịch sử trong lễ hội Việt Nam này."
  },
  {
    "id": 63,
    "word": "respect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪspˈɛkt/",
    "meaning": "sự kính trọng; tôn trọng",
    "ex1": "Local people respect during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương sự kính trọng; tôn trọng trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 64,
    "word": "ancestors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈænsˌɛstɝz/",
    "meaning": "tổ tiên",
    "ex1": "Visitors learn about ancestors during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về tổ tiên trong lễ hội Việt Nam này."
  },
  {
    "id": 65,
    "word": "reminds",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rimˈaɪndz/",
    "meaning": "nhắc nhở",
    "ex1": "The festival reminds an important cultural idea each year.",
    "ex1_vi": "Lễ hội nhắc nhở một ý nghĩa văn hóa quan trọng mỗi năm."
  },
  {
    "id": 66,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ɛvriwʌn/",
    "meaning": "mọi người",
    "ex1": "Local people everyone during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương mọi người trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 67,
    "word": "protect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹətˈɛkt/",
    "meaning": "bảo vệ",
    "ex1": "Local people protect during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương bảo vệ trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 68,
    "word": "national",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈæʃənəl/",
    "meaning": "quốc gia",
    "ex1": "The festival has a national feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét quốc gia mà du khách có thể nhận thấy."
  },
  {
    "id": 69,
    "word": "traditions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trʌdˈɪʃʌnz/",
    "meaning": "truyền thống",
    "ex1": "Visitors learn about traditions during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về truyền thống trong lễ hội Việt Nam này."
  },
  {
    "id": 70,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/təɡˈɛðɚ/",
    "meaning": "cùng nhau",
    "ex1": "Male and female singers wear traditional clothes and sing together.",
    "ex1_vi": "Nam và nữ liền anh liền chị mặc trang phục truyền thống và hát cùng nhau."
  },
  {
    "id": 71,
    "word": "today",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tədˈeɪ/",
    "meaning": "ngày nay",
    "ex1": "It helps people relax, think positively, and appreciate Vietnamese culture today.",
    "ex1_vi": "Lễ hội giúp mọi người thư giãn, suy nghĩ tích cực và trân trọng văn hóa Việt Nam ngày nay."
  },
  {
    "id": 72,
    "word": "perfume",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɝfjˈum/",
    "meaning": "Hương; hương thơm",
    "ex1": "The Perfume Pagoda Festival is one of the largest religious festivals in Vietnam.",
    "ex1_vi": "Lễ hội Chùa Hương là một trong những lễ hội tôn giáo lớn nhất ở Việt Nam."
  },
  {
    "id": 73,
    "word": "pagoda",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pʌɡˈoʊdʌ/",
    "meaning": "chùa",
    "ex1": "People visit Huong Tich Cave, Thien Tru Pagoda, and other sacred places.",
    "ex1_vi": "Mọi người đến thăm động Hương Tích, chùa Thiên Trù và những địa điểm linh thiêng khác."
  },
  {
    "id": 74,
    "word": "one",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/wˈʌn/",
    "meaning": "một",
    "ex1": "One visitors enjoy the cultural activities during the festival.",
    "ex1_vi": "Một du khách thưởng thức các hoạt động văn hóa trong lễ hội."
  },
  {
    "id": 75,
    "word": "largest",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑɹdʒəst/",
    "meaning": "lớn nhất",
    "ex1": "The festival has a largest feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét lớn nhất mà du khách có thể nhận thấy."
  },
  {
    "id": 76,
    "word": "religious",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪlˈɪdʒʌs/",
    "meaning": "thuộc tôn giáo",
    "ex1": "The festival is both a religious trip and a nature tour.",
    "ex1_vi": "Lễ hội vừa là một chuyến hành hương tôn giáo vừa là một chuyến tham quan thiên nhiên."
  },
  {
    "id": 77,
    "word": "festivals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɛstʌvʌlz/",
    "meaning": "các lễ hội",
    "ex1": "Visitors learn about festivals during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các lễ hội trong lễ hội Việt Nam này."
  },
  {
    "id": 78,
    "word": "hanoi",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/hæˈnɔɪ/",
    "meaning": "Hà Nội",
    "ex1": "Visitors learn about hanoi during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Hà Nội trong lễ hội Việt Nam này."
  },
  {
    "id": 79,
    "word": "first",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɜːst/",
    "meaning": "thứ nhất; đầu tiên",
    "ex1": "The festival has a first feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét thứ nhất; đầu tiên mà du khách có thể nhận thấy."
  },
  {
    "id": 80,
    "word": "thousands",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈaʊzəndz/",
    "meaning": "hàng nghìn",
    "ex1": "Thousands of visitors come to pray for health, luck, and happiness.",
    "ex1_vi": "Hàng nghìn du khách đến cầu sức khỏe, may mắn và hạnh phúc."
  },
  {
    "id": 81,
    "word": "come",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌm/",
    "meaning": "đến",
    "ex1": "Thousands of visitors come to pray for health, luck, and happiness.",
    "ex1_vi": "Hàng nghìn du khách đến cầu sức khỏe, may mắn và hạnh phúc."
  },
  {
    "id": 82,
    "word": "pray",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prˈeɪ/",
    "meaning": "cầu nguyện",
    "ex1": "Local people pray during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương cầu nguyện trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 83,
    "word": "health",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛlθ/",
    "meaning": "sức khỏe",
    "ex1": "Visitors learn about health during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về sức khỏe trong lễ hội Việt Nam này."
  },
  {
    "id": 84,
    "word": "luck",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈʌk/",
    "meaning": "may mắn",
    "ex1": "Visitors learn about luck during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về may mắn trong lễ hội Việt Nam này."
  },
  {
    "id": 85,
    "word": "happiness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈæpinəs/",
    "meaning": "hạnh phúc",
    "ex1": "Visitors learn about happiness during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về hạnh phúc trong lễ hội Việt Nam này."
  },
  {
    "id": 86,
    "word": "journey",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɜːni/",
    "meaning": "hành trình",
    "ex1": "The journey begins with a boat ride along Yen Stream.",
    "ex1_vi": "Hành trình bắt đầu bằng một chuyến đi thuyền dọc theo suối Yến."
  },
  {
    "id": 87,
    "word": "begins",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪɡˈɪnz/",
    "meaning": "bắt đầu",
    "ex1": "The journey begins with a boat ride along Yen Stream.",
    "ex1_vi": "Hành trình bắt đầu bằng một chuyến đi thuyền dọc theo suối Yến."
  },
  {
    "id": 88,
    "word": "boat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/boʊt/",
    "meaning": "thuyền",
    "ex1": "Visitors learn about boat during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về thuyền trong lễ hội Việt Nam này."
  },
  {
    "id": 89,
    "word": "ride",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪd/",
    "meaning": "chuyến đi",
    "ex1": "Visitors learn about ride during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về chuyến đi trong lễ hội Việt Nam này."
  },
  {
    "id": 90,
    "word": "yen",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/jɛn/",
    "meaning": "Yên",
    "ex1": "Visitors learn about yen during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Yên trong lễ hội Việt Nam này."
  },
  {
    "id": 91,
    "word": "stream",
    "type": "noun",
    "cat": "n",
    "phonetic": "/strˈim/",
    "meaning": "suối",
    "ex1": "Visitors learn about stream during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về suối trong lễ hội Việt Nam này."
  },
  {
    "id": 92,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɚ/",
    "meaning": "nước",
    "ex1": "Visitors learn about water during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về nước trong lễ hội Việt Nam này."
  },
  {
    "id": 93,
    "word": "calm",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɑm/",
    "meaning": "yên ả; bình tĩnh",
    "ex1": "The festival has a calm feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét yên ả; bình tĩnh mà du khách có thể nhận thấy."
  },
  {
    "id": 94,
    "word": "mountains",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈmaʊntənz/",
    "meaning": "núi",
    "ex1": "Visitors learn about mountains during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về núi trong lễ hội Việt Nam này."
  },
  {
    "id": 95,
    "word": "views",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vjˈuz/",
    "meaning": "cảnh quan",
    "ex1": "Visitors learn about views during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về cảnh quan trong lễ hội Việt Nam này."
  },
  {
    "id": 96,
    "word": "then",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ðˈɛn/",
    "meaning": "sau đó",
    "ex1": "Visitors then walk or take a cable car to the pagodas.",
    "ex1_vi": "Sau đó, du khách đi bộ hoặc đi cáp treo đến các ngôi chùa."
  },
  {
    "id": 97,
    "word": "walk",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɔk/",
    "meaning": "đi bộ",
    "ex1": "Visitors then walk or take a cable car to the pagodas.",
    "ex1_vi": "Sau đó, du khách đi bộ hoặc đi cáp treo đến các ngôi chùa."
  },
  {
    "id": 98,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ɔr/",
    "meaning": "hoặc",
    "ex1": "They often perform on boats, hills, or village stages.",
    "ex1_vi": "Họ thường biểu diễn trên thuyền, trên đồi hoặc sân khấu làng."
  },
  {
    "id": 99,
    "word": "take",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪk/",
    "meaning": "đi; lấy",
    "ex1": "Local people take during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương đi; lấy trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 100,
    "word": "cable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈeɪbʌl/",
    "meaning": "cáp",
    "ex1": "The festival has a cable feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét cáp mà du khách có thể nhận thấy."
  },
  {
    "id": 101,
    "word": "car",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑr/",
    "meaning": "xe",
    "ex1": "Visitors learn about car during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về xe trong lễ hội Việt Nam này."
  },
  {
    "id": 102,
    "word": "pagodas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pʌɡˈoʊdʌz/",
    "meaning": "các ngôi chùa",
    "ex1": "Visitors learn about pagodas during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các ngôi chùa trong lễ hội Việt Nam này."
  },
  {
    "id": 103,
    "word": "huong",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/hwəŋ/",
    "meaning": "Hương",
    "ex1": "Visitors learn about huong during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Hương trong lễ hội Việt Nam này."
  },
  {
    "id": 104,
    "word": "tich",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/tɪk/",
    "meaning": "Tích",
    "ex1": "Visitors learn about tich during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Tích trong lễ hội Việt Nam này."
  },
  {
    "id": 105,
    "word": "cave",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈeɪv/",
    "meaning": "động; hang",
    "ex1": "Visitors learn about cave during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về động; hang trong lễ hội Việt Nam này."
  },
  {
    "id": 106,
    "word": "thien",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/tiːən/",
    "meaning": "Thiên",
    "ex1": "Visitors learn about thien during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Thiên trong lễ hội Việt Nam này."
  },
  {
    "id": 107,
    "word": "tru",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/truː/",
    "meaning": "Trù",
    "ex1": "Visitors learn about tru during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Trù trong lễ hội Việt Nam này."
  },
  {
    "id": 108,
    "word": "other",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ʌðɚ/",
    "meaning": "khác",
    "ex1": "Other visitors enjoy the cultural activities during the festival.",
    "ex1_vi": "Khác du khách thưởng thức các hoạt động văn hóa trong lễ hội."
  },
  {
    "id": 109,
    "word": "sacred",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪkrʌd/",
    "meaning": "linh thiêng",
    "ex1": "The festival has a sacred feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét linh thiêng mà du khách có thể nhận thấy."
  },
  {
    "id": 110,
    "word": "places",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪsəz/",
    "meaning": "nơi chốn",
    "ex1": "The festival places an important cultural idea each year.",
    "ex1_vi": "Lễ hội nơi chốn một ý nghĩa văn hóa quan trọng mỗi năm."
  },
  {
    "id": 111,
    "word": "light",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈaɪt/",
    "meaning": "thắp; ánh sáng",
    "ex1": "Local people light during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương thắp; ánh sáng trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 112,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɛndʒɔɪ/",
    "meaning": "tận hưởng",
    "ex1": "Local people enjoy during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương tận hưởng trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 113,
    "word": "peaceful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈisfəl/",
    "meaning": "thanh bình",
    "ex1": "The festival has a peaceful feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét thanh bình mà du khách có thể nhận thấy."
  },
  {
    "id": 114,
    "word": "both",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/boʊθ/",
    "meaning": "cả hai",
    "ex1": "The festival is both a religious trip and a nature tour.",
    "ex1_vi": "Lễ hội vừa là một chuyến hành hương tôn giáo vừa là một chuyến tham quan thiên nhiên."
  },
  {
    "id": 115,
    "word": "trip",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈɪp/",
    "meaning": "chuyến đi",
    "ex1": "Visitors learn about trip during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về chuyến đi trong lễ hội Việt Nam này."
  },
  {
    "id": 116,
    "word": "nature",
    "type": "noun",
    "cat": "n",
    "phonetic": "/neɪtʃɚ/",
    "meaning": "thiên nhiên",
    "ex1": "Visitors learn about nature during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về thiên nhiên trong lễ hội Việt Nam này."
  },
  {
    "id": 117,
    "word": "tour",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈʊr/",
    "meaning": "chuyến tham quan",
    "ex1": "Visitors learn about tour during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về chuyến tham quan trong lễ hội Việt Nam này."
  },
  {
    "id": 118,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "It brings communities together and helps young people understand and love their cultural heritage together today.",
    "ex1_vi": "Lễ hội gắn kết cộng đồng và giúp người trẻ hiểu và yêu di sản văn hóa của mình ngày nay."
  },
  {
    "id": 119,
    "word": "relax",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪlˈæks/",
    "meaning": "thư giãn",
    "ex1": "Local people relax during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương thư giãn trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 120,
    "word": "think",
    "type": "verb",
    "cat": "v",
    "phonetic": "/θˈɪŋk/",
    "meaning": "suy nghĩ",
    "ex1": "Local people think during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương suy nghĩ trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 121,
    "word": "positively",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/pˈɑzʌtɪvli/",
    "meaning": "một cách tích cực",
    "ex1": "Local people welcome festival visitors positively each year.",
    "ex1_vi": "Người dân địa phương chào đón du khách một cách tích cực mỗi năm."
  },
  {
    "id": 122,
    "word": "appreciate",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌprˈiʃiˌeɪt/",
    "meaning": "trân trọng",
    "ex1": "Local people appreciate during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương trân trọng trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 123,
    "word": "culture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌltʃɝ/",
    "meaning": "văn hóa",
    "ex1": "Their songs are gentle, emotional, and full of local culture.",
    "ex1_vi": "Những bài hát của họ nhẹ nhàng, giàu cảm xúc và đậm nét văn hóa địa phương."
  },
  {
    "id": 124,
    "word": "lim",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/lɪm/",
    "meaning": "Lim",
    "ex1": "Lim Festival protects the traditional music of northern Vietnam.",
    "ex1_vi": "Hội Lim bảo tồn âm nhạc truyền thống của miền Bắc Việt Nam."
  },
  {
    "id": 125,
    "word": "famous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈeɪməs/",
    "meaning": "nổi tiếng",
    "ex1": "The festival has a famous feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét nổi tiếng mà du khách có thể nhận thấy."
  },
  {
    "id": 126,
    "word": "bac",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/bæk/",
    "meaning": "Bắc",
    "ex1": "Visitors learn about bac during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Bắc trong lễ hội Việt Nam này."
  },
  {
    "id": 127,
    "word": "ninh",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/nɪŋ/",
    "meaning": "Ninh",
    "ex1": "Visitors learn about ninh during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Ninh trong lễ hội Việt Nam này."
  },
  {
    "id": 128,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/juʒəwəli/",
    "meaning": "thường",
    "ex1": "Local people welcome festival visitors usually each year.",
    "ex1_vi": "Người dân địa phương chào đón du khách thường mỗi năm."
  },
  {
    "id": 129,
    "word": "thirteenth",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/θˈɝtˈinθ/",
    "meaning": "thứ mười ba",
    "ex1": "The festival has a thirteenth feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét thứ mười ba mà du khách có thể nhận thấy."
  },
  {
    "id": 130,
    "word": "well",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wɛl/",
    "meaning": "tốt; rõ",
    "ex1": "The festival is well known for Quan Ho folk songs.",
    "ex1_vi": "Lễ hội nổi tiếng với những làn điệu dân ca Quan họ."
  },
  {
    "id": 131,
    "word": "known",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈoʊn/",
    "meaning": "được biết đến",
    "ex1": "The festival has a known feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét được biết đến mà du khách có thể nhận thấy."
  },
  {
    "id": 132,
    "word": "quan",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/kwɑːn/",
    "meaning": "Quan",
    "ex1": "Visitors learn about quan during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Quan trong lễ hội Việt Nam này."
  },
  {
    "id": 133,
    "word": "ho",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/hoʊ/",
    "meaning": "Họ",
    "ex1": "Visitors learn about ho during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Họ trong lễ hội Việt Nam này."
  },
  {
    "id": 134,
    "word": "songs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔŋz/",
    "meaning": "bài hát",
    "ex1": "Their songs are gentle, emotional, and full of local culture.",
    "ex1_vi": "Những bài hát của họ nhẹ nhàng, giàu cảm xúc và đậm nét văn hóa địa phương."
  },
  {
    "id": 135,
    "word": "male",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈeɪl/",
    "meaning": "nam",
    "ex1": "The festival has a male feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét nam mà du khách có thể nhận thấy."
  },
  {
    "id": 136,
    "word": "female",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈimˌeɪl/",
    "meaning": "nữ",
    "ex1": "The festival has a female feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét nữ mà du khách có thể nhận thấy."
  },
  {
    "id": 137,
    "word": "singers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪŋɝz/",
    "meaning": "người hát",
    "ex1": "Visitors learn about singers during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về người hát trong lễ hội Việt Nam này."
  },
  {
    "id": 138,
    "word": "sing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɪŋ/",
    "meaning": "hát",
    "ex1": "Local people sing during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương hát trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 139,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɔfən/",
    "meaning": "thường",
    "ex1": "They often perform on boats, hills, or village stages.",
    "ex1_vi": "Họ thường biểu diễn trên thuyền, trên đồi hoặc sân khấu làng."
  },
  {
    "id": 140,
    "word": "perform",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɚfˈɔːɹm/",
    "meaning": "biểu diễn",
    "ex1": "Local people perform during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương biểu diễn trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 141,
    "word": "boats",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈoʊts/",
    "meaning": "thuyền",
    "ex1": "Visitors learn about boats during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về thuyền trong lễ hội Việt Nam này."
  },
  {
    "id": 142,
    "word": "hills",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɪlz/",
    "meaning": "đồi",
    "ex1": "Visitors learn about hills during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về đồi trong lễ hội Việt Nam này."
  },
  {
    "id": 143,
    "word": "village",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪlʌdʒ/",
    "meaning": "làng",
    "ex1": "Visitors learn about village during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về làng trong lễ hội Việt Nam này."
  },
  {
    "id": 144,
    "word": "stages",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈeɪdʒʌz/",
    "meaning": "sân khấu",
    "ex1": "Visitors learn about stages during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về sân khấu trong lễ hội Việt Nam này."
  },
  {
    "id": 145,
    "word": "gentle",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈɛntʌl/",
    "meaning": "nhẹ nhàng",
    "ex1": "The festival has a gentle feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét nhẹ nhàng mà du khách có thể nhận thấy."
  },
  {
    "id": 146,
    "word": "emotional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪmˈoʊʃʌnʌl/",
    "meaning": "giàu cảm xúc",
    "ex1": "The festival has a emotional feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét giàu cảm xúc mà du khách có thể nhận thấy."
  },
  {
    "id": 147,
    "word": "full",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈʊl/",
    "meaning": "đầy",
    "ex1": "The festival has a full feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét đầy mà du khách có thể nhận thấy."
  },
  {
    "id": 148,
    "word": "bamboo",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bæmbˈu/",
    "meaning": "tre",
    "ex1": "Visitors learn about bamboo during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về tre trong lễ hội Việt Nam này."
  },
  {
    "id": 149,
    "word": "swinging",
    "type": "noun",
    "cat": "n",
    "phonetic": "/swˈɪŋɪŋ/",
    "meaning": "đánh đu",
    "ex1": "Visitors learn about swinging during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về đánh đu trong lễ hội Việt Nam này."
  },
  {
    "id": 150,
    "word": "human",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hjˈumən/",
    "meaning": "con người",
    "ex1": "The festival has a human feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét con người mà du khách có thể nhận thấy."
  },
  {
    "id": 151,
    "word": "chess",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɛs/",
    "meaning": "cờ",
    "ex1": "Visitors learn about chess during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về cờ trong lễ hội Việt Nam này."
  },
  {
    "id": 152,
    "word": "taste",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪst/",
    "meaning": "nếm; thưởng thức",
    "ex1": "They can also taste local food and meet friendly people.",
    "ex1_vi": "Họ cũng có thể nếm món ăn địa phương và gặp gỡ những người thân thiện."
  },
  {
    "id": 153,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thức ăn",
    "ex1": "They can also taste local food and meet friendly people.",
    "ex1_vi": "Họ cũng có thể nếm món ăn địa phương và gặp gỡ những người thân thiện."
  },
  {
    "id": 154,
    "word": "meet",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈit/",
    "meaning": "gặp gỡ",
    "ex1": "Local people meet during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương gặp gỡ trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 155,
    "word": "friendly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/frˈɛndli/",
    "meaning": "thân thiện",
    "ex1": "Local people welcome festival visitors friendly each year.",
    "ex1_vi": "Người dân địa phương chào đón du khách thân thiện mỗi năm."
  },
  {
    "id": 156,
    "word": "protects",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌtˈɛkts/",
    "meaning": "bảo vệ",
    "ex1": "Lim Festival protects the traditional music of northern Vietnam.",
    "ex1_vi": "Hội Lim bảo tồn âm nhạc truyền thống của miền Bắc Việt Nam."
  },
  {
    "id": 157,
    "word": "northern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈɔrðɝn/",
    "meaning": "thuộc miền Bắc",
    "ex1": "The festival has a northern feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét thuộc miền Bắc mà du khách có thể nhận thấy."
  },
  {
    "id": 158,
    "word": "brings",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɹˈɪŋz/",
    "meaning": "mang lại",
    "ex1": "It brings communities together and helps young people understand and love their cultural heritage together today.",
    "ex1_vi": "Lễ hội gắn kết cộng đồng và giúp người trẻ hiểu và yêu di sản văn hóa của mình ngày nay."
  },
  {
    "id": 159,
    "word": "communities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌmjˈunʌtiz/",
    "meaning": "các cộng đồng",
    "ex1": "Visitors learn about communities during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các cộng đồng trong lễ hội Việt Nam này."
  },
  {
    "id": 160,
    "word": "understand",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌʌndɝstˈænd/",
    "meaning": "hiểu",
    "ex1": "Local people understand during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương hiểu trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 161,
    "word": "love",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʌv/",
    "meaning": "yêu",
    "ex1": "Local people love during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương yêu trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 162,
    "word": "heritage",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛrʌtʌdʒ/",
    "meaning": "di sản",
    "ex1": "Visitors learn about heritage during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về di sản trong lễ hội Việt Nam này."
  }
];

const newReadingVocabOrder = [
  "hung",
  "kings",
  "festival",
  "held",
  "phu",
  "tho",
  "province",
  "every",
  "year",
  "takes",
  "place",
  "tenth",
  "day",
  "third",
  "lunar",
  "month",
  "many",
  "people",
  "visit",
  "temple",
  "remember",
  "ancient",
  "vietnam",
  "offer",
  "flowers",
  "fruit",
  "rice",
  "cakes",
  "and",
  "incense",
  "important",
  "ceremonies",
  "serious",
  "respectful",
  "way",
  "traditional",
  "music",
  "drum",
  "performances",
  "create",
  "special",
  "atmosphere",
  "visitors",
  "can",
  "also",
  "watch",
  "folk",
  "games",
  "wrestling",
  "cultural",
  "shows",
  "local",
  "wear",
  "beautiful",
  "clothes",
  "welcome",
  "guests",
  "warmly",
  "teaches",
  "young",
  "vietnamese",
  "history",
  "respect",
  "ancestors",
  "reminds",
  "everyone",
  "protect",
  "national",
  "traditions",
  "together",
  "today",
  "perfume",
  "pagoda",
  "one",
  "largest",
  "religious",
  "festivals",
  "hanoi",
  "first",
  "thousands",
  "come",
  "pray",
  "health",
  "luck",
  "happiness",
  "journey",
  "begins",
  "boat",
  "ride",
  "yen",
  "stream",
  "water",
  "calm",
  "mountains",
  "views",
  "then",
  "walk",
  "or",
  "take",
  "cable",
  "car",
  "pagodas",
  "huong",
  "tich",
  "cave",
  "thien",
  "tru",
  "other",
  "sacred",
  "places",
  "light",
  "enjoy",
  "peaceful",
  "both",
  "trip",
  "nature",
  "tour",
  "helps",
  "relax",
  "think",
  "positively",
  "appreciate",
  "culture",
  "lim",
  "famous",
  "bac",
  "ninh",
  "usually",
  "thirteenth",
  "well",
  "known",
  "quan",
  "ho",
  "songs",
  "male",
  "female",
  "singers",
  "sing",
  "often",
  "perform",
  "boats",
  "hills",
  "village",
  "stages",
  "gentle",
  "emotional",
  "full",
  "bamboo",
  "swinging",
  "human",
  "chess",
  "taste",
  "food",
  "meet",
  "friendly",
  "protects",
  "northern",
  "brings",
  "communities",
  "understand",
  "love",
  "heritage"
];
