// ===== festival03 ESSAY =====

const newEssayData = [
  {
    "text": "7. Kate Festival – Lễ hội Kate\nKate Festival is an important celebration of the Cham people in Ninh Thuan and Binh Thuan. It usually takes place in the seventh month of the Cham calendar.\n\nPeople visit ancient towers to honor gods, heroes, and ancestors. Religious leaders perform special ceremonies, open the tower doors, and dress sacred statues in traditional clothes.\n\nThe festival includes music, dancing, drums, and colorful costumes. Families prepare food, visit relatives, and share happy moments together. Visitors can also learn about Cham crafts and customs.\n\nKate Festival protects Cham culture and brings the community closer. It is a joyful time of respect, gratitude, family love, and cultural pride among both young and old.",
    "vi": "7. Kate Festival – Lễ hội Kate\nLễ hội Kate là một lễ kỷ niệm quan trọng của người Chăm ở Ninh Thuận và Bình Thuận. Lễ hội thường diễn ra vào tháng bảy theo lịch Chăm.\n\nMọi người đến các tháp cổ để tôn vinh các vị thần, anh hùng và tổ tiên. Các chức sắc tôn giáo thực hiện những nghi lễ đặc biệt, mở cửa tháp và mặc trang phục truyền thống cho các tượng thiêng.\n\nLễ hội có âm nhạc, múa, trống và trang phục đầy màu sắc. Các gia đình chuẩn bị thức ăn, thăm họ hàng và chia sẻ những khoảnh khắc vui vẻ bên nhau. Du khách cũng có thể tìm hiểu về nghề thủ công và phong tục của người Chăm.\n\nLễ hội Kate bảo tồn văn hóa Chăm và gắn kết cộng đồng hơn. Đây là thời gian vui tươi của sự kính trọng, lòng biết ơn, tình yêu gia đình và niềm tự hào văn hóa giữa cả người trẻ và người lớn tuổi."
  },
  {
    "text": "8. The Bay Nui Cow Racing Festival – Lễ hội Đua bò Bảy Núi\nThe Bay Nui Cow Racing Festival is a famous event in An Giang Province. It is organized by Khmer people during the Sene Dolta holiday, usually in the rainy season.\n\nPairs of cows race across a wet and muddy field. Each driver stands on a small wooden board and controls the animals carefully. The race is fast, exciting, and sometimes surprising.\n\nLarge crowds cheer loudly around the field. Visitors can also enjoy Khmer music, local food, and traditional activities.\n\nThe festival celebrates farming life, strength, and teamwork. It brings joy to local villages and helps protect the special culture of the Khmer community in southern Vietnam for many years ahead.",
    "vi": "8. The Bay Nui Cow Racing Festival – Lễ hội Đua bò Bảy Núi\nLễ hội Đua bò Bảy Núi là một sự kiện nổi tiếng ở tỉnh An Giang. Lễ hội do người Khmer tổ chức trong dịp lễ Sene Dolta, thường vào mùa mưa.\n\nCác cặp bò đua trên một cánh đồng ướt và lầy lội. Mỗi người điều khiển đứng trên một tấm ván gỗ nhỏ và điều khiển các con vật cẩn thận. Cuộc đua nhanh, hấp dẫn và đôi khi đầy bất ngờ.\n\nĐám đông lớn reo hò vang dội quanh sân. Du khách cũng có thể thưởng thức âm nhạc Khmer, món ăn địa phương và các hoạt động truyền thống.\n\nLễ hội tôn vinh đời sống nông nghiệp, sức mạnh và tinh thần đồng đội. Nó mang niềm vui đến các làng địa phương và giúp bảo tồn văn hóa đặc sắc của cộng đồng Khmer ở miền Nam Việt Nam trong nhiều năm tới."
  },
  {
    "text": "9. Nghinh Ong Festival – Lễ hội Nghinh Ông\nNghinh Ong Festival is celebrated in many coastal towns in southern Vietnam. It honors the whale, which fishermen believe protects people during dangerous journeys at sea.\n\nThe festival often begins with a boat parade. Fishing boats are decorated with flags, flowers, and bright colors. People carry offerings and invite the whale spirit to the temple.\n\nTraditional ceremonies, lion dances, music, and games attract many visitors. Fishermen pray for calm seas, good weather, and a successful fishing year.\n\nThe festival shows gratitude to nature and strengthens community relationships. It also keeps local beliefs alive and teaches younger generations about the culture of coastal life in Vietnam now and in the future.",
    "vi": "9. Nghinh Ong Festival – Lễ hội Nghinh Ông\nLễ hội Nghinh Ông được tổ chức tại nhiều thị trấn ven biển ở miền Nam Việt Nam. Lễ hội tôn vinh cá voi, loài vật mà ngư dân tin rằng bảo vệ con người trong những chuyến đi nguy hiểm trên biển.\n\nLễ hội thường bắt đầu bằng một cuộc diễu hành thuyền. Thuyền đánh cá được trang trí bằng cờ, hoa và màu sắc rực rỡ. Mọi người mang lễ vật và rước thần cá voi về đền.\n\nCác nghi lễ truyền thống, múa lân, âm nhạc và trò chơi thu hút nhiều du khách. Ngư dân cầu biển yên, thời tiết tốt và một năm đánh bắt thành công.\n\nLễ hội thể hiện lòng biết ơn đối với thiên nhiên và củng cố các mối quan hệ cộng đồng. Nó cũng giữ cho tín ngưỡng địa phương được tiếp nối và dạy thế hệ trẻ về văn hóa đời sống ven biển ở Việt Nam hiện nay và trong tương lai."
  },
  {
    "text": "10. The Ban Flower Festival – Lễ hội Hoa Ban\nThe Ban Flower Festival is held in Dien Bien Province every March. It celebrates the white ban flower and the rich culture of ethnic groups in northwestern Vietnam.\n\nVisitors can watch traditional dances, listen to folk songs, and see colorful clothes. Local people also perform music with drums, flutes, and other traditional instruments.\n\nThe festival offers sports, food fairs, beauty contests, and cultural exhibitions. Tourists can try local dishes, buy handmade products, and learn about village life.\n\nThe Ban Flower Festival promotes tourism and protects local traditions. It also brings people together and shows the natural beauty, friendly spirit, and cultural diversity of Dien Bien to visitors from many places.",
    "vi": "10. The Ban Flower Festival – Lễ hội Hoa Ban\nLễ hội Hoa Ban được tổ chức tại tỉnh Điện Biên vào tháng ba hằng năm. Lễ hội tôn vinh hoa ban trắng và nền văn hóa phong phú của các nhóm dân tộc ở vùng Tây Bắc Việt Nam.\n\nDu khách có thể xem các điệu múa truyền thống, nghe dân ca và ngắm trang phục đầy màu sắc. Người dân địa phương cũng biểu diễn âm nhạc với trống, sáo và các nhạc cụ truyền thống khác.\n\nLễ hội có các hoạt động thể thao, hội chợ ẩm thực, cuộc thi sắc đẹp và triển lãm văn hóa. Khách du lịch có thể thử món ăn địa phương, mua sản phẩm thủ công và tìm hiểu về đời sống làng quê.\n\nLễ hội Hoa Ban thúc đẩy du lịch và bảo tồn truyền thống địa phương. Lễ hội cũng gắn kết mọi người và giới thiệu vẻ đẹp thiên nhiên, tinh thần thân thiện và sự đa dạng văn hóa của Điện Biên đến du khách từ nhiều nơi."
  }
];
