// ===== festival03 VOCABULARY =====

const lessonVocabularyWords = [
  "kate",
  "festival",
  "important",
  "celebration",
  "cham",
  "people",
  "ninh",
  "thuan",
  "and",
  "binh",
  "usually",
  "takes",
  "place",
  "seventh",
  "month",
  "calendar",
  "visit",
  "ancient",
  "towers",
  "honor",
  "gods",
  "heroes",
  "ancestors",
  "religious",
  "leaders",
  "perform",
  "special",
  "ceremonies",
  "open",
  "tower",
  "doors",
  "dress",
  "sacred",
  "statues",
  "traditional",
  "clothes",
  "includes",
  "music",
  "dancing",
  "drums",
  "colorful",
  "costumes",
  "families",
  "prepare",
  "food",
  "relatives",
  "share",
  "happy",
  "moments",
  "together",
  "visitors",
  "can",
  "also",
  "learn",
  "crafts",
  "customs",
  "protects",
  "culture",
  "brings",
  "community",
  "closer",
  "joyful",
  "time",
  "respect",
  "gratitude",
  "family",
  "love",
  "cultural",
  "pride",
  "both",
  "young",
  "old",
  "bay",
  "nui",
  "cow",
  "racing",
  "famous",
  "event",
  "giang",
  "province",
  "organized",
  "khmer",
  "sene",
  "dolta",
  "holiday",
  "rainy",
  "season",
  "pairs",
  "cows",
  "race",
  "wet",
  "muddy",
  "field",
  "each",
  "driver",
  "stands",
  "small",
  "wooden",
  "board",
  "controls",
  "animals",
  "carefully",
  "fast",
  "exciting",
  "sometimes",
  "surprising",
  "large",
  "crowds",
  "cheer",
  "loudly",
  "enjoy",
  "local",
  "activities",
  "celebrates",
  "farming",
  "life",
  "strength",
  "teamwork",
  "joy",
  "villages",
  "helps",
  "protect",
  "southern",
  "vietnam",
  "many",
  "years",
  "ahead",
  "nghinh",
  "ong",
  "celebrated",
  "coastal",
  "towns",
  "honors",
  "whale",
  "fishermen",
  "believe",
  "dangerous",
  "journeys",
  "sea",
  "often",
  "begins",
  "boat",
  "parade",
  "fishing",
  "boats",
  "decorated",
  "flags",
  "flowers",
  "bright",
  "colors",
  "carry",
  "offerings",
  "invite",
  "spirit",
  "temple",
  "lion",
  "dances",
  "games",
  "attract",
  "pray",
  "calm",
  "seas",
  "good",
  "weather",
  "successful",
  "year",
  "shows",
  "nature",
  "strengthens",
  "relationships",
  "keeps",
  "beliefs",
  "alive",
  "teaches",
  "younger",
  "generations",
  "now",
  "future",
  "ban",
  "flower",
  "held",
  "dien",
  "bien",
  "every",
  "march",
  "white",
  "rich",
  "ethnic",
  "groups",
  "northwestern",
  "watch",
  "listen",
  "folk",
  "songs",
  "see",
  "flutes",
  "other",
  "instruments",
  "offers",
  "sports",
  "fairs",
  "beauty",
  "contests",
  "exhibitions",
  "tourists",
  "try",
  "dishes",
  "buy",
  "handmade",
  "products",
  "village",
  "promotes",
  "tourism",
  "traditions",
  "natural",
  "friendly",
  "diversity",
  "places"
];

const newVocabData = [
  {
    "id": 1,
    "word": "kate",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/ˈkɑːteɪ/",
    "meaning": "Kate",
    "ex1": "Kate Festival is an important celebration of the Cham people in Ninh Thuan and Binh Thuan.",
    "ex1_vi": "Lễ hội Kate là một lễ kỷ niệm quan trọng của người Chăm ở Ninh Thuận và Bình Thuận."
  },
  {
    "id": 2,
    "word": "festival",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɛstʌvʌl/",
    "meaning": "lễ hội",
    "ex1": "Kate Festival is an important celebration of the Cham people in Ninh Thuan and Binh Thuan.",
    "ex1_vi": "Lễ hội Kate là một lễ kỷ niệm quan trọng của người Chăm ở Ninh Thuận và Bình Thuận."
  },
  {
    "id": 3,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔɹtənt/",
    "meaning": "quan trọng",
    "ex1": "The festival has a important feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét quan trọng mà du khách có thể nhận thấy."
  },
  {
    "id": 4,
    "word": "celebration",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˌɛləbɹˈeɪʃən/",
    "meaning": "lễ kỷ niệm",
    "ex1": "Visitors learn about celebration during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về lễ kỷ niệm trong lễ hội Việt Nam này."
  },
  {
    "id": 5,
    "word": "cham",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/tʃɑːm/",
    "meaning": "Chăm",
    "ex1": "It usually takes place in the seventh month of the Cham calendar.",
    "ex1_vi": "Lễ hội thường diễn ra vào tháng bảy theo lịch Chăm."
  },
  {
    "id": 6,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipəl/",
    "meaning": "mọi người",
    "ex1": "People visit ancient towers to honor gods, heroes, and ancestors.",
    "ex1_vi": "Mọi người đến các tháp cổ để tôn vinh các vị thần, anh hùng và tổ tiên."
  },
  {
    "id": 7,
    "word": "ninh",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/nɪŋ/",
    "meaning": "Ninh",
    "ex1": "Visitors learn about ninh during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Ninh trong lễ hội Việt Nam này."
  },
  {
    "id": 8,
    "word": "thuan",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/twɑːn/",
    "meaning": "Thuận",
    "ex1": "Visitors learn about thuan during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Thuận trong lễ hội Việt Nam này."
  },
  {
    "id": 9,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ənd/",
    "meaning": "và",
    "ex1": "People visit ancient towers to honor gods, heroes, and ancestors.",
    "ex1_vi": "Mọi người đến các tháp cổ để tôn vinh các vị thần, anh hùng và tổ tiên."
  },
  {
    "id": 10,
    "word": "binh",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/bɪŋ/",
    "meaning": "Bình",
    "ex1": "Visitors learn about binh during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Bình trong lễ hội Việt Nam này."
  },
  {
    "id": 11,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/juʒəwəli/",
    "meaning": "thường",
    "ex1": "It usually takes place in the seventh month of the Cham calendar.",
    "ex1_vi": "Lễ hội thường diễn ra vào tháng bảy theo lịch Chăm."
  },
  {
    "id": 12,
    "word": "takes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪks/",
    "meaning": "diễn ra",
    "ex1": "The festival takes an important cultural idea each year.",
    "ex1_vi": "Lễ hội diễn ra một ý nghĩa văn hóa quan trọng mỗi năm."
  },
  {
    "id": 13,
    "word": "place",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪs/",
    "meaning": "nơi; địa điểm",
    "ex1": "Visitors learn about place during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về nơi; địa điểm trong lễ hội Việt Nam này."
  },
  {
    "id": 14,
    "word": "seventh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɛvʌnθ/",
    "meaning": "thứ bảy",
    "ex1": "The festival has a seventh feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét thứ bảy mà du khách có thể nhận thấy."
  },
  {
    "id": 15,
    "word": "month",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌnθ/",
    "meaning": "tháng",
    "ex1": "Visitors learn about month during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về tháng trong lễ hội Việt Nam này."
  },
  {
    "id": 16,
    "word": "calendar",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈælʌndɝ/",
    "meaning": "lịch",
    "ex1": "Visitors learn about calendar during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về lịch trong lễ hội Việt Nam này."
  },
  {
    "id": 17,
    "word": "visit",
    "type": "verb",
    "cat": "v",
    "phonetic": "/vˈɪzɪt/",
    "meaning": "thăm",
    "ex1": "Families prepare food, visit relatives, and share happy moments together.",
    "ex1_vi": "Các gia đình chuẩn bị thức ăn, thăm họ hàng và chia sẻ những khoảnh khắc vui vẻ bên nhau."
  },
  {
    "id": 18,
    "word": "ancient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈeɪnʃənt/",
    "meaning": "cổ xưa",
    "ex1": "The festival has a ancient feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét cổ xưa mà du khách có thể nhận thấy."
  },
  {
    "id": 19,
    "word": "towers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaʊɝz/",
    "meaning": "các tháp",
    "ex1": "Visitors learn about towers during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các tháp trong lễ hội Việt Nam này."
  },
  {
    "id": 20,
    "word": "honor",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɑnɝ/",
    "meaning": "tôn vinh",
    "ex1": "Local people honor during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương tôn vinh trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 21,
    "word": "gods",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɑdz/",
    "meaning": "các vị thần",
    "ex1": "Visitors learn about gods during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các vị thần trong lễ hội Việt Nam này."
  },
  {
    "id": 22,
    "word": "heroes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɪroʊz/",
    "meaning": "các anh hùng",
    "ex1": "Visitors learn about heroes during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các anh hùng trong lễ hội Việt Nam này."
  },
  {
    "id": 23,
    "word": "ancestors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈænsˌɛstɝz/",
    "meaning": "tổ tiên",
    "ex1": "Visitors learn about ancestors during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về tổ tiên trong lễ hội Việt Nam này."
  },
  {
    "id": 24,
    "word": "religious",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪlˈɪdʒʌs/",
    "meaning": "thuộc tôn giáo",
    "ex1": "Religious leaders perform special ceremonies, open the tower doors, and dress sacred statues in traditional clothes.",
    "ex1_vi": "Các chức sắc tôn giáo thực hiện những nghi lễ đặc biệt, mở cửa tháp và mặc trang phục truyền thống cho các tượng thiêng."
  },
  {
    "id": 25,
    "word": "leaders",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈidɝz/",
    "meaning": "chức sắc; người lãnh đạo",
    "ex1": "Religious leaders perform special ceremonies, open the tower doors, and dress sacred statues in traditional clothes.",
    "ex1_vi": "Các chức sắc tôn giáo thực hiện những nghi lễ đặc biệt, mở cửa tháp và mặc trang phục truyền thống cho các tượng thiêng."
  },
  {
    "id": 26,
    "word": "perform",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɚfˈɔːɹm/",
    "meaning": "biểu diễn",
    "ex1": "Local people also perform music with drums, flutes, and other traditional instruments.",
    "ex1_vi": "Người dân địa phương cũng biểu diễn âm nhạc với trống, sáo và các nhạc cụ truyền thống khác."
  },
  {
    "id": 27,
    "word": "special",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/spˈɛʃəl/",
    "meaning": "đặc biệt",
    "ex1": "It brings joy to local villages and helps protect the special culture of the Khmer community in southern Vietnam for many years ahead.",
    "ex1_vi": "Nó mang niềm vui đến các làng địa phương và giúp bảo tồn văn hóa đặc sắc của cộng đồng Khmer ở miền Nam Việt Nam trong nhiều năm tới."
  },
  {
    "id": 28,
    "word": "ceremonies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛrʌmˌoʊniz/",
    "meaning": "nghi lễ",
    "ex1": "Traditional ceremonies, lion dances, music, and games attract many visitors.",
    "ex1_vi": "Các nghi lễ truyền thống, múa lân, âm nhạc và trò chơi thu hút nhiều du khách."
  },
  {
    "id": 29,
    "word": "open",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈoʊpʌn/",
    "meaning": "mở",
    "ex1": "Visitors learn about open during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về mở trong lễ hội Việt Nam này."
  },
  {
    "id": 30,
    "word": "tower",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaʊɝ/",
    "meaning": "tháp",
    "ex1": "Visitors learn about tower during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về tháp trong lễ hội Việt Nam này."
  },
  {
    "id": 31,
    "word": "doors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɔrz/",
    "meaning": "cửa",
    "ex1": "Visitors learn about doors during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về cửa trong lễ hội Việt Nam này."
  },
  {
    "id": 32,
    "word": "dress",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɛs/",
    "meaning": "mặc trang phục cho",
    "ex1": "Visitors learn about dress during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về mặc trang phục cho trong lễ hội Việt Nam này."
  },
  {
    "id": 33,
    "word": "sacred",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪkrʌd/",
    "meaning": "linh thiêng",
    "ex1": "The festival has a sacred feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét linh thiêng mà du khách có thể nhận thấy."
  },
  {
    "id": 34,
    "word": "statues",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈætʃˌuz/",
    "meaning": "tượng",
    "ex1": "Visitors learn about statues during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về tượng trong lễ hội Việt Nam này."
  },
  {
    "id": 35,
    "word": "traditional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trʌdˈɪʃʌnʌl/",
    "meaning": "truyền thống",
    "ex1": "Visitors can also enjoy Khmer music, local food, and traditional activities.",
    "ex1_vi": "Du khách cũng có thể thưởng thức âm nhạc Khmer, món ăn địa phương và các hoạt động truyền thống."
  },
  {
    "id": 36,
    "word": "clothes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈoʊðz/",
    "meaning": "quần áo",
    "ex1": "Visitors can watch traditional dances, listen to folk songs, and see colorful clothes.",
    "ex1_vi": "Du khách có thể xem các điệu múa truyền thống, nghe dân ca và ngắm trang phục đầy màu sắc."
  },
  {
    "id": 37,
    "word": "includes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɪnklˈuːdz/",
    "meaning": "bao gồm",
    "ex1": "The festival includes music, dancing, drums, and colorful costumes.",
    "ex1_vi": "Lễ hội có âm nhạc, múa, trống và trang phục đầy màu sắc."
  },
  {
    "id": 38,
    "word": "music",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mjˈuzɪk/",
    "meaning": "âm nhạc",
    "ex1": "The festival includes music, dancing, drums, and colorful costumes.",
    "ex1_vi": "Lễ hội có âm nhạc, múa, trống và trang phục đầy màu sắc."
  },
  {
    "id": 39,
    "word": "dancing",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈænsɪŋ/",
    "meaning": "múa",
    "ex1": "Visitors learn about dancing during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về múa trong lễ hội Việt Nam này."
  },
  {
    "id": 40,
    "word": "drums",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈʌmz/",
    "meaning": "trống",
    "ex1": "Local people also perform music with drums, flutes, and other traditional instruments.",
    "ex1_vi": "Người dân địa phương cũng biểu diễn âm nhạc với trống, sáo và các nhạc cụ truyền thống khác."
  },
  {
    "id": 41,
    "word": "colorful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kʌlɚfəl/",
    "meaning": "đầy màu sắc",
    "ex1": "Visitors can watch traditional dances, listen to folk songs, and see colorful clothes.",
    "ex1_vi": "Du khách có thể xem các điệu múa truyền thống, nghe dân ca và ngắm trang phục đầy màu sắc."
  },
  {
    "id": 42,
    "word": "costumes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kɑstˈumz/",
    "meaning": "trang phục",
    "ex1": "Visitors learn about costumes during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về trang phục trong lễ hội Việt Nam này."
  },
  {
    "id": 43,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fæməliz/",
    "meaning": "các gia đình",
    "ex1": "Families prepare food, visit relatives, and share happy moments together.",
    "ex1_vi": "Các gia đình chuẩn bị thức ăn, thăm họ hàng và chia sẻ những khoảnh khắc vui vẻ bên nhau."
  },
  {
    "id": 44,
    "word": "prepare",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹɪpˈɛɹ/",
    "meaning": "chuẩn bị",
    "ex1": "Local people prepare during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương chuẩn bị trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 45,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thức ăn",
    "ex1": "Visitors can also enjoy Khmer music, local food, and traditional activities.",
    "ex1_vi": "Du khách cũng có thể thưởng thức âm nhạc Khmer, món ăn địa phương và các hoạt động truyền thống."
  },
  {
    "id": 46,
    "word": "relatives",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɛlʌtɪvz/",
    "meaning": "họ hàng",
    "ex1": "Visitors learn about relatives during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về họ hàng trong lễ hội Việt Nam này."
  },
  {
    "id": 47,
    "word": "share",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈɛɹ/",
    "meaning": "chia sẻ",
    "ex1": "Local people share during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương chia sẻ trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 48,
    "word": "happy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈæpi/",
    "meaning": "vui vẻ",
    "ex1": "The festival has a happy feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét vui vẻ mà du khách có thể nhận thấy."
  },
  {
    "id": 49,
    "word": "moments",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈoʊmənts/",
    "meaning": "khoảnh khắc",
    "ex1": "Visitors learn about moments during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về khoảnh khắc trong lễ hội Việt Nam này."
  },
  {
    "id": 50,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/təɡˈɛðɚ/",
    "meaning": "cùng nhau",
    "ex1": "It also brings people together and shows the natural beauty, friendly spirit, and cultural diversity of Dien Bien to visitors from many places.",
    "ex1_vi": "Lễ hội cũng gắn kết mọi người và giới thiệu vẻ đẹp thiên nhiên, tinh thần thân thiện và sự đa dạng văn hóa của Điện Biên đến du khách từ nhiều nơi."
  },
  {
    "id": 51,
    "word": "visitors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪzɪtɝz/",
    "meaning": "du khách",
    "ex1": "Visitors can also learn about Cham crafts and customs.",
    "ex1_vi": "Du khách cũng có thể tìm hiểu về nghề thủ công và phong tục của người Chăm."
  },
  {
    "id": 52,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Visitors can also learn about Cham crafts and customs.",
    "ex1_vi": "Du khách cũng có thể tìm hiểu về nghề thủ công và phong tục của người Chăm."
  },
  {
    "id": 53,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "It also keeps local beliefs alive and teaches younger generations about the culture of coastal life in Vietnam now and in the future.",
    "ex1_vi": "Nó cũng giữ cho tín ngưỡng địa phương được tiếp nối và dạy thế hệ trẻ về văn hóa đời sống ven biển ở Việt Nam hiện nay và trong tương lai."
  },
  {
    "id": 54,
    "word": "learn",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɝn/",
    "meaning": "học; tìm hiểu",
    "ex1": "Tourists can try local dishes, buy handmade products, and learn about village life.",
    "ex1_vi": "Khách du lịch có thể thử món ăn địa phương, mua sản phẩm thủ công và tìm hiểu về đời sống làng quê."
  },
  {
    "id": 55,
    "word": "crafts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/krˈæfts/",
    "meaning": "nghề thủ công",
    "ex1": "Visitors learn about crafts during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về nghề thủ công trong lễ hội Việt Nam này."
  },
  {
    "id": 56,
    "word": "customs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌstʌmz/",
    "meaning": "phong tục",
    "ex1": "Visitors learn about customs during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về phong tục trong lễ hội Việt Nam này."
  },
  {
    "id": 57,
    "word": "protects",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌtˈɛkts/",
    "meaning": "bảo vệ",
    "ex1": "Kate Festival protects Cham culture and brings the community closer.",
    "ex1_vi": "Lễ hội Kate bảo tồn văn hóa Chăm và gắn kết cộng đồng hơn."
  },
  {
    "id": 58,
    "word": "culture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌltʃɝ/",
    "meaning": "văn hóa",
    "ex1": "Kate Festival protects Cham culture and brings the community closer.",
    "ex1_vi": "Lễ hội Kate bảo tồn văn hóa Chăm và gắn kết cộng đồng hơn."
  },
  {
    "id": 59,
    "word": "brings",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɹˈɪŋz/",
    "meaning": "mang lại",
    "ex1": "It brings joy to local villages and helps protect the special culture of the Khmer community in southern Vietnam for many years ahead.",
    "ex1_vi": "Nó mang niềm vui đến các làng địa phương và giúp bảo tồn văn hóa đặc sắc của cộng đồng Khmer ở miền Nam Việt Nam trong nhiều năm tới."
  },
  {
    "id": 60,
    "word": "community",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌmjˈunʌti/",
    "meaning": "cộng đồng",
    "ex1": "The festival shows gratitude to nature and strengthens community relationships.",
    "ex1_vi": "Lễ hội thể hiện lòng biết ơn đối với thiên nhiên và củng cố các mối quan hệ cộng đồng."
  },
  {
    "id": 61,
    "word": "closer",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/klˈoʊsɚ/",
    "meaning": "gần gũi hơn",
    "ex1": "Local people welcome festival visitors closer each year.",
    "ex1_vi": "Người dân địa phương chào đón du khách gần gũi hơn mỗi năm."
  },
  {
    "id": 62,
    "word": "joyful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈɔɪfʌl/",
    "meaning": "vui tươi",
    "ex1": "It is a joyful time of respect, gratitude, family love, and cultural pride among both young and old.",
    "ex1_vi": "Đây là thời gian vui tươi của sự kính trọng, lòng biết ơn, tình yêu gia đình và niềm tự hào văn hóa giữa cả người trẻ và người lớn tuổi."
  },
  {
    "id": 63,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "It is a joyful time of respect, gratitude, family love, and cultural pride among both young and old.",
    "ex1_vi": "Đây là thời gian vui tươi của sự kính trọng, lòng biết ơn, tình yêu gia đình và niềm tự hào văn hóa giữa cả người trẻ và người lớn tuổi."
  },
  {
    "id": 64,
    "word": "respect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪspˈɛkt/",
    "meaning": "sự kính trọng; tôn trọng",
    "ex1": "Local people respect during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương sự kính trọng; tôn trọng trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 65,
    "word": "gratitude",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡrˈætʌtˌud/",
    "meaning": "lòng biết ơn",
    "ex1": "The festival shows gratitude to nature and strengthens community relationships.",
    "ex1_vi": "Lễ hội thể hiện lòng biết ơn đối với thiên nhiên và củng cố các mối quan hệ cộng đồng."
  },
  {
    "id": 66,
    "word": "family",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/fˈæmɪli/",
    "meaning": "gia đình",
    "ex1": "Local people welcome festival visitors family each year.",
    "ex1_vi": "Người dân địa phương chào đón du khách gia đình mỗi năm."
  },
  {
    "id": 67,
    "word": "love",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʌv/",
    "meaning": "yêu",
    "ex1": "Local people love during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương yêu trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 68,
    "word": "cultural",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌltʃɝʌl/",
    "meaning": "thuộc văn hóa",
    "ex1": "The festival offers sports, food fairs, beauty contests, and cultural exhibitions.",
    "ex1_vi": "Lễ hội có các hoạt động thể thao, hội chợ ẩm thực, cuộc thi sắc đẹp và triển lãm văn hóa."
  },
  {
    "id": 69,
    "word": "pride",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɹˈaɪd/",
    "meaning": "niềm tự hào",
    "ex1": "Visitors learn about pride during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về niềm tự hào trong lễ hội Việt Nam này."
  },
  {
    "id": 70,
    "word": "both",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/boʊθ/",
    "meaning": "cả hai",
    "ex1": "People sing both enjoy traditional activities at the festival.",
    "ex1_vi": "Mọi người ca hát cả hai tham gia các hoạt động truyền thống tại lễ hội."
  },
  {
    "id": 71,
    "word": "young",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jʌŋ/",
    "meaning": "trẻ",
    "ex1": "The festival has a young feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét trẻ mà du khách có thể nhận thấy."
  },
  {
    "id": 72,
    "word": "old",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈoʊld/",
    "meaning": "xưa; cũ",
    "ex1": "The festival has a old feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét xưa; cũ mà du khách có thể nhận thấy."
  },
  {
    "id": 73,
    "word": "bay",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/beɪ/",
    "meaning": "Bảy",
    "ex1": "The Bay Nui Cow Racing Festival is a famous event in An Giang Province.",
    "ex1_vi": "Lễ hội Đua bò Bảy Núi là một sự kiện nổi tiếng ở tỉnh An Giang."
  },
  {
    "id": 74,
    "word": "nui",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/nuːi/",
    "meaning": "Núi",
    "ex1": "The Bay Nui Cow Racing Festival is a famous event in An Giang Province.",
    "ex1_vi": "Lễ hội Đua bò Bảy Núi là một sự kiện nổi tiếng ở tỉnh An Giang."
  },
  {
    "id": 75,
    "word": "cow",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈaʊ/",
    "meaning": "bò",
    "ex1": "Visitors learn about cow during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về bò trong lễ hội Việt Nam này."
  },
  {
    "id": 76,
    "word": "racing",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈeɪsɪŋ/",
    "meaning": "đua",
    "ex1": "Visitors learn about racing during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về đua trong lễ hội Việt Nam này."
  },
  {
    "id": 77,
    "word": "famous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈeɪməs/",
    "meaning": "nổi tiếng",
    "ex1": "The festival has a famous feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét nổi tiếng mà du khách có thể nhận thấy."
  },
  {
    "id": 78,
    "word": "event",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪvˈɛnt/",
    "meaning": "sự kiện",
    "ex1": "Visitors learn about event during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về sự kiện trong lễ hội Việt Nam này."
  },
  {
    "id": 79,
    "word": "giang",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/zɑːŋ/",
    "meaning": "Giang",
    "ex1": "Visitors learn about giang during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Giang trong lễ hội Việt Nam này."
  },
  {
    "id": 80,
    "word": "province",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑvʌns/",
    "meaning": "tỉnh",
    "ex1": "The Ban Flower Festival is held in Dien Bien Province every March.",
    "ex1_vi": "Lễ hội Hoa Ban được tổ chức tại tỉnh Điện Biên vào tháng ba hằng năm."
  },
  {
    "id": 81,
    "word": "organized",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɔːɹɡɐnˌaɪzd/",
    "meaning": "được tổ chức",
    "ex1": "It is organized by Khmer people during the Sene Dolta holiday, usually in the rainy season.",
    "ex1_vi": "Lễ hội do người Khmer tổ chức trong dịp lễ Sene Dolta, thường vào mùa mưa."
  },
  {
    "id": 82,
    "word": "khmer",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/kmɛr/",
    "meaning": "Khmer",
    "ex1": "It is organized by Khmer people during the Sene Dolta holiday, usually in the rainy season.",
    "ex1_vi": "Lễ hội do người Khmer tổ chức trong dịp lễ Sene Dolta, thường vào mùa mưa."
  },
  {
    "id": 83,
    "word": "sene",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/səˈneɪ/",
    "meaning": "Sene",
    "ex1": "Visitors learn about sene during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Sene trong lễ hội Việt Nam này."
  },
  {
    "id": 84,
    "word": "dolta",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/ˈdoʊltə/",
    "meaning": "Dolta",
    "ex1": "Visitors learn about dolta during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Dolta trong lễ hội Việt Nam này."
  },
  {
    "id": 85,
    "word": "holiday",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɑlʌdˌeɪ/",
    "meaning": "ngày lễ",
    "ex1": "Visitors learn about holiday during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về ngày lễ trong lễ hội Việt Nam này."
  },
  {
    "id": 86,
    "word": "rainy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈeɪni/",
    "meaning": "có mưa; mùa mưa",
    "ex1": "The festival has a rainy feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét có mưa; mùa mưa mà du khách có thể nhận thấy."
  },
  {
    "id": 87,
    "word": "season",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsizən/",
    "meaning": "mùa",
    "ex1": "Visitors learn about season during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về mùa trong lễ hội Việt Nam này."
  },
  {
    "id": 88,
    "word": "pairs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɛrz/",
    "meaning": "các cặp",
    "ex1": "Pairs of cows race across a wet and muddy field.",
    "ex1_vi": "Các cặp bò đua trên một cánh đồng ướt và lầy lội."
  },
  {
    "id": 89,
    "word": "cows",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kaʊz/",
    "meaning": "bò",
    "ex1": "Pairs of cows race across a wet and muddy field.",
    "ex1_vi": "Các cặp bò đua trên một cánh đồng ướt và lầy lội."
  },
  {
    "id": 90,
    "word": "race",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɹˈeɪs/",
    "meaning": "cuộc đua; đua",
    "ex1": "The race is fast, exciting, and sometimes surprising.",
    "ex1_vi": "Cuộc đua nhanh, hấp dẫn và đôi khi đầy bất ngờ."
  },
  {
    "id": 91,
    "word": "wet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈɛt/",
    "meaning": "ướt",
    "ex1": "The festival has a wet feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét ướt mà du khách có thể nhận thấy."
  },
  {
    "id": 92,
    "word": "muddy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈʌdi/",
    "meaning": "lầy lội",
    "ex1": "The festival has a muddy feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét lầy lội mà du khách có thể nhận thấy."
  },
  {
    "id": 93,
    "word": "field",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈild/",
    "meaning": "cánh đồng",
    "ex1": "Large crowds cheer loudly around the field.",
    "ex1_vi": "Đám đông lớn reo hò vang dội quanh sân."
  },
  {
    "id": 94,
    "word": "each",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈitʃ/",
    "meaning": "mỗi",
    "ex1": "Each driver stands on a small wooden board and controls the animals carefully.",
    "ex1_vi": "Mỗi người điều khiển đứng trên một tấm ván gỗ nhỏ và điều khiển các con vật cẩn thận."
  },
  {
    "id": 95,
    "word": "driver",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈaɪvɝ/",
    "meaning": "người điều khiển",
    "ex1": "Each driver stands on a small wooden board and controls the animals carefully.",
    "ex1_vi": "Mỗi người điều khiển đứng trên một tấm ván gỗ nhỏ và điều khiển các con vật cẩn thận."
  },
  {
    "id": 96,
    "word": "stands",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈændz/",
    "meaning": "đứng",
    "ex1": "The festival stands an important cultural idea each year.",
    "ex1_vi": "Lễ hội đứng một ý nghĩa văn hóa quan trọng mỗi năm."
  },
  {
    "id": 97,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "The festival has a small feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét nhỏ mà du khách có thể nhận thấy."
  },
  {
    "id": 98,
    "word": "wooden",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈʊdʌn/",
    "meaning": "bằng gỗ",
    "ex1": "The festival has a wooden feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét bằng gỗ mà du khách có thể nhận thấy."
  },
  {
    "id": 99,
    "word": "board",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɔrd/",
    "meaning": "tấm ván",
    "ex1": "Visitors learn about board during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về tấm ván trong lễ hội Việt Nam này."
  },
  {
    "id": 100,
    "word": "controls",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntrˈoʊlz/",
    "meaning": "điều khiển",
    "ex1": "The festival controls an important cultural idea each year.",
    "ex1_vi": "Lễ hội điều khiển một ý nghĩa văn hóa quan trọng mỗi năm."
  },
  {
    "id": 101,
    "word": "animals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈænɪməlz/",
    "meaning": "động vật",
    "ex1": "Visitors learn about animals during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về động vật trong lễ hội Việt Nam này."
  },
  {
    "id": 102,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛɹfəli/",
    "meaning": "cẩn thận",
    "ex1": "Local people welcome festival visitors carefully each year.",
    "ex1_vi": "Người dân địa phương chào đón du khách cẩn thận mỗi năm."
  },
  {
    "id": 103,
    "word": "fast",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈæst/",
    "meaning": "nhanh",
    "ex1": "The race is fast, exciting, and sometimes surprising.",
    "ex1_vi": "Cuộc đua nhanh, hấp dẫn và đôi khi đầy bất ngờ."
  },
  {
    "id": 104,
    "word": "exciting",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɛksˈaɪɾɪŋ/",
    "meaning": "hấp dẫn; sôi động",
    "ex1": "The festival has a exciting feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét hấp dẫn; sôi động mà du khách có thể nhận thấy."
  },
  {
    "id": 105,
    "word": "sometimes",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sʌmtˈaɪmz/",
    "meaning": "đôi khi",
    "ex1": "Local people welcome festival visitors sometimes each year.",
    "ex1_vi": "Người dân địa phương chào đón du khách đôi khi mỗi năm."
  },
  {
    "id": 106,
    "word": "surprising",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sɚpɹˈaɪzɪŋ/",
    "meaning": "đáng ngạc nhiên",
    "ex1": "The festival has a surprising feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét đáng ngạc nhiên mà du khách có thể nhận thấy."
  },
  {
    "id": 107,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑɹdʒ/",
    "meaning": "lớn",
    "ex1": "Large crowds cheer loudly around the field.",
    "ex1_vi": "Đám đông lớn reo hò vang dội quanh sân."
  },
  {
    "id": 108,
    "word": "crowds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/krˈaʊdz/",
    "meaning": "đám đông",
    "ex1": "Visitors learn about crowds during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về đám đông trong lễ hội Việt Nam này."
  },
  {
    "id": 109,
    "word": "cheer",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈɪɹ/",
    "meaning": "reo hò",
    "ex1": "Local people cheer during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương reo hò trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 110,
    "word": "loudly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/lˈaʊdli/",
    "meaning": "vang dội",
    "ex1": "Local people welcome festival visitors loudly each year.",
    "ex1_vi": "Người dân địa phương chào đón du khách vang dội mỗi năm."
  },
  {
    "id": 111,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɛndʒɔɪ/",
    "meaning": "tận hưởng",
    "ex1": "Local people enjoy during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương tận hưởng trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 112,
    "word": "local",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈoʊkəl/",
    "meaning": "địa phương",
    "ex1": "It also keeps local beliefs alive and teaches younger generations about the culture of coastal life in Vietnam now and in the future.",
    "ex1_vi": "Nó cũng giữ cho tín ngưỡng địa phương được tiếp nối và dạy thế hệ trẻ về văn hóa đời sống ven biển ở Việt Nam hiện nay và trong tương lai."
  },
  {
    "id": 113,
    "word": "activities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/æktˈɪvətiz/",
    "meaning": "hoạt động",
    "ex1": "Visitors learn about activities during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về hoạt động trong lễ hội Việt Nam này."
  },
  {
    "id": 114,
    "word": "celebrates",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɛlʌbrˌeɪts/",
    "meaning": "tôn vinh; kỷ niệm",
    "ex1": "The festival celebrates farming life, strength, and teamwork.",
    "ex1_vi": "Lễ hội tôn vinh đời sống nông nghiệp, sức mạnh và tinh thần đồng đội."
  },
  {
    "id": 115,
    "word": "farming",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɑrmɪŋ/",
    "meaning": "nông nghiệp",
    "ex1": "The festival celebrates farming life, strength, and teamwork.",
    "ex1_vi": "Lễ hội tôn vinh đời sống nông nghiệp, sức mạnh và tinh thần đồng đội."
  },
  {
    "id": 116,
    "word": "life",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪf/",
    "meaning": "cuộc sống",
    "ex1": "Tourists can try local dishes, buy handmade products, and learn about village life.",
    "ex1_vi": "Khách du lịch có thể thử món ăn địa phương, mua sản phẩm thủ công và tìm hiểu về đời sống làng quê."
  },
  {
    "id": 117,
    "word": "strength",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stɹˈɛŋθ/",
    "meaning": "sức mạnh",
    "ex1": "Visitors learn about strength during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về sức mạnh trong lễ hội Việt Nam này."
  },
  {
    "id": 118,
    "word": "teamwork",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈimwˌɝk/",
    "meaning": "tinh thần đồng đội",
    "ex1": "Visitors learn about teamwork during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về tinh thần đồng đội trong lễ hội Việt Nam này."
  },
  {
    "id": 119,
    "word": "joy",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɔɪ/",
    "meaning": "niềm vui",
    "ex1": "Visitors learn about joy during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về niềm vui trong lễ hội Việt Nam này."
  },
  {
    "id": 120,
    "word": "villages",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪlʌdʒʌz/",
    "meaning": "các làng",
    "ex1": "Visitors learn about villages during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các làng trong lễ hội Việt Nam này."
  },
  {
    "id": 121,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "The festival helps an important cultural idea each year.",
    "ex1_vi": "Lễ hội giúp một ý nghĩa văn hóa quan trọng mỗi năm."
  },
  {
    "id": 122,
    "word": "protect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹətˈɛkt/",
    "meaning": "bảo vệ",
    "ex1": "Local people protect during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương bảo vệ trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 123,
    "word": "southern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈʌðɝn/",
    "meaning": "thuộc miền Nam",
    "ex1": "Nghinh Ong Festival is celebrated in many coastal towns in southern Vietnam.",
    "ex1_vi": "Lễ hội Nghinh Ông được tổ chức tại nhiều thị trấn ven biển ở miền Nam Việt Nam."
  },
  {
    "id": 124,
    "word": "vietnam",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/ˌviːɛtˈnɑːm/",
    "meaning": "Việt Nam",
    "ex1": "Nghinh Ong Festival is celebrated in many coastal towns in southern Vietnam.",
    "ex1_vi": "Lễ hội Nghinh Ông được tổ chức tại nhiều thị trấn ven biển ở miền Nam Việt Nam."
  },
  {
    "id": 125,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mɛni/",
    "meaning": "nhiều",
    "ex1": "Traditional ceremonies, lion dances, music, and games attract many visitors.",
    "ex1_vi": "Các nghi lễ truyền thống, múa lân, âm nhạc và trò chơi thu hút nhiều du khách."
  },
  {
    "id": 126,
    "word": "years",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jɪrz/",
    "meaning": "năm",
    "ex1": "Visitors learn about years during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về năm trong lễ hội Việt Nam này."
  },
  {
    "id": 127,
    "word": "ahead",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/əhɛd/",
    "meaning": "sắp tới",
    "ex1": "Local people welcome festival visitors ahead each year.",
    "ex1_vi": "Người dân địa phương chào đón du khách sắp tới mỗi năm."
  },
  {
    "id": 128,
    "word": "nghinh",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/nɪŋ/",
    "meaning": "Nghinh",
    "ex1": "Visitors learn about nghinh during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Nghinh trong lễ hội Việt Nam này."
  },
  {
    "id": 129,
    "word": "ong",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/ɔŋ/",
    "meaning": "Ông",
    "ex1": "Visitors learn about ong during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Ông trong lễ hội Việt Nam này."
  },
  {
    "id": 130,
    "word": "celebrated",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɛlʌbrˌeɪtɪd/",
    "meaning": "được tổ chức",
    "ex1": "The activity is celebrated as part of the festival tradition.",
    "ex1_vi": "Hoạt động được được tổ chức như một phần của truyền thống lễ hội."
  },
  {
    "id": 131,
    "word": "coastal",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈoʊstʌl/",
    "meaning": "ven biển",
    "ex1": "The festival has a coastal feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét ven biển mà du khách có thể nhận thấy."
  },
  {
    "id": 132,
    "word": "towns",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaʊnz/",
    "meaning": "thị trấn",
    "ex1": "Visitors learn about towns during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về thị trấn trong lễ hội Việt Nam này."
  },
  {
    "id": 133,
    "word": "honors",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɑnɝz/",
    "meaning": "tôn vinh",
    "ex1": "It honors the whale, which fishermen believe protects people during dangerous journeys at sea.",
    "ex1_vi": "Lễ hội tôn vinh cá voi, loài vật mà ngư dân tin rằng bảo vệ con người trong những chuyến đi nguy hiểm trên biển."
  },
  {
    "id": 134,
    "word": "whale",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪl/",
    "meaning": "cá voi",
    "ex1": "It honors the whale, which fishermen believe protects people during dangerous journeys at sea.",
    "ex1_vi": "Lễ hội tôn vinh cá voi, loài vật mà ngư dân tin rằng bảo vệ con người trong những chuyến đi nguy hiểm trên biển."
  },
  {
    "id": 135,
    "word": "fishermen",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɪʃɝmɪn/",
    "meaning": "ngư dân",
    "ex1": "Fishermen pray for calm seas, good weather, and a successful fishing year.",
    "ex1_vi": "Ngư dân cầu biển yên, thời tiết tốt và một năm đánh bắt thành công."
  },
  {
    "id": 136,
    "word": "believe",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪliv/",
    "meaning": "tin rằng",
    "ex1": "Local people believe during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương tin rằng trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 137,
    "word": "dangerous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈeɪndʒɝʌs/",
    "meaning": "nguy hiểm",
    "ex1": "The festival has a dangerous feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét nguy hiểm mà du khách có thể nhận thấy."
  },
  {
    "id": 138,
    "word": "journeys",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɝniz/",
    "meaning": "các hành trình",
    "ex1": "Visitors learn about journeys during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các hành trình trong lễ hội Việt Nam này."
  },
  {
    "id": 139,
    "word": "sea",
    "type": "noun",
    "cat": "n",
    "phonetic": "/si/",
    "meaning": "biển",
    "ex1": "Visitors learn about sea during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về biển trong lễ hội Việt Nam này."
  },
  {
    "id": 140,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɔfən/",
    "meaning": "thường",
    "ex1": "The festival often begins with a boat parade.",
    "ex1_vi": "Lễ hội thường bắt đầu bằng một cuộc diễu hành thuyền."
  },
  {
    "id": 141,
    "word": "begins",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪɡˈɪnz/",
    "meaning": "bắt đầu",
    "ex1": "The festival often begins with a boat parade.",
    "ex1_vi": "Lễ hội thường bắt đầu bằng một cuộc diễu hành thuyền."
  },
  {
    "id": 142,
    "word": "boat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/boʊt/",
    "meaning": "thuyền",
    "ex1": "Visitors learn about boat during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về thuyền trong lễ hội Việt Nam này."
  },
  {
    "id": 143,
    "word": "parade",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɝˈeɪd/",
    "meaning": "cuộc diễu hành",
    "ex1": "Visitors learn about parade during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về cuộc diễu hành trong lễ hội Việt Nam này."
  },
  {
    "id": 144,
    "word": "fishing",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɪʃɪŋ/",
    "meaning": "đánh cá",
    "ex1": "Fishing boats are decorated with flags, flowers, and bright colors.",
    "ex1_vi": "Thuyền đánh cá được trang trí bằng cờ, hoa và màu sắc rực rỡ."
  },
  {
    "id": 145,
    "word": "boats",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈoʊts/",
    "meaning": "thuyền",
    "ex1": "Fishing boats are decorated with flags, flowers, and bright colors.",
    "ex1_vi": "Thuyền đánh cá được trang trí bằng cờ, hoa và màu sắc rực rỡ."
  },
  {
    "id": 146,
    "word": "decorated",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈɛkɝˌeɪtɪd/",
    "meaning": "được trang trí",
    "ex1": "The activity is decorated as part of the festival tradition.",
    "ex1_vi": "Hoạt động được được trang trí như một phần của truyền thống lễ hội."
  },
  {
    "id": 147,
    "word": "flags",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈæɡz/",
    "meaning": "cờ",
    "ex1": "Visitors learn about flags during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về cờ trong lễ hội Việt Nam này."
  },
  {
    "id": 148,
    "word": "flowers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈaʊɝz/",
    "meaning": "hoa",
    "ex1": "Visitors learn about flowers during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về hoa trong lễ hội Việt Nam này."
  },
  {
    "id": 149,
    "word": "bright",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/brˈaɪt/",
    "meaning": "rực rỡ",
    "ex1": "The festival has a bright feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét rực rỡ mà du khách có thể nhận thấy."
  },
  {
    "id": 150,
    "word": "colors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌlɚz/",
    "meaning": "màu sắc",
    "ex1": "Visitors learn about colors during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về màu sắc trong lễ hội Việt Nam này."
  },
  {
    "id": 151,
    "word": "carry",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈæri/",
    "meaning": "mang",
    "ex1": "People carry offerings and invite the whale spirit to the temple.",
    "ex1_vi": "Mọi người mang lễ vật và rước thần cá voi về đền."
  },
  {
    "id": 152,
    "word": "offerings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔfɝɪŋz/",
    "meaning": "lễ vật",
    "ex1": "People carry offerings and invite the whale spirit to the temple.",
    "ex1_vi": "Mọi người mang lễ vật và rước thần cá voi về đền."
  },
  {
    "id": 153,
    "word": "invite",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪnvˈaɪt/",
    "meaning": "mời; rước",
    "ex1": "Local people invite during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương mời; rước trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 154,
    "word": "spirit",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈɪrʌt/",
    "meaning": "tinh thần; thần linh",
    "ex1": "It also brings people together and shows the natural beauty, friendly spirit, and cultural diversity of Dien Bien to visitors from many places.",
    "ex1_vi": "Lễ hội cũng gắn kết mọi người và giới thiệu vẻ đẹp thiên nhiên, tinh thần thân thiện và sự đa dạng văn hóa của Điện Biên đến du khách từ nhiều nơi."
  },
  {
    "id": 155,
    "word": "temple",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛmpʌl/",
    "meaning": "đền",
    "ex1": "Visitors learn about temple during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về đền trong lễ hội Việt Nam này."
  },
  {
    "id": 156,
    "word": "lion",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪʌn/",
    "meaning": "sư tử; lân",
    "ex1": "Visitors learn about lion during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về sư tử; lân trong lễ hội Việt Nam này."
  },
  {
    "id": 157,
    "word": "dances",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈænsʌz/",
    "meaning": "các điệu múa",
    "ex1": "Visitors learn about dances during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các điệu múa trong lễ hội Việt Nam này."
  },
  {
    "id": 158,
    "word": "games",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈeɪmz/",
    "meaning": "trò chơi",
    "ex1": "Visitors learn about games during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về trò chơi trong lễ hội Việt Nam này."
  },
  {
    "id": 159,
    "word": "attract",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ətrˈækt/",
    "meaning": "thu hút",
    "ex1": "Local people attract during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương thu hút trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 160,
    "word": "pray",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prˈeɪ/",
    "meaning": "cầu nguyện",
    "ex1": "Fishermen pray for calm seas, good weather, and a successful fishing year.",
    "ex1_vi": "Ngư dân cầu biển yên, thời tiết tốt và một năm đánh bắt thành công."
  },
  {
    "id": 161,
    "word": "calm",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɑm/",
    "meaning": "yên ả; bình tĩnh",
    "ex1": "The festival has a calm feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét yên ả; bình tĩnh mà du khách có thể nhận thấy."
  },
  {
    "id": 162,
    "word": "seas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/siz/",
    "meaning": "biển",
    "ex1": "Visitors learn about seas during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về biển trong lễ hội Việt Nam này."
  },
  {
    "id": 163,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "The festival has a good feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét tốt mà du khách có thể nhận thấy."
  },
  {
    "id": 164,
    "word": "weather",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɛðɝ/",
    "meaning": "thời tiết",
    "ex1": "Visitors learn about weather during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về thời tiết trong lễ hội Việt Nam này."
  },
  {
    "id": 165,
    "word": "successful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/səksˈɛsfəl/",
    "meaning": "thành công",
    "ex1": "The festival has a successful feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét thành công mà du khách có thể nhận thấy."
  },
  {
    "id": 166,
    "word": "year",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jɪr/",
    "meaning": "năm",
    "ex1": "Visitors learn about year during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về năm trong lễ hội Việt Nam này."
  },
  {
    "id": 167,
    "word": "shows",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈoʊz/",
    "meaning": "các chương trình; thể hiện",
    "ex1": "The festival shows an important cultural idea each year.",
    "ex1_vi": "Lễ hội các chương trình; thể hiện một ý nghĩa văn hóa quan trọng mỗi năm."
  },
  {
    "id": 168,
    "word": "nature",
    "type": "noun",
    "cat": "n",
    "phonetic": "/neɪtʃɚ/",
    "meaning": "thiên nhiên",
    "ex1": "Visitors learn about nature during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về thiên nhiên trong lễ hội Việt Nam này."
  },
  {
    "id": 169,
    "word": "strengthens",
    "type": "verb",
    "cat": "v",
    "phonetic": "/strˈɛŋθənz/",
    "meaning": "củng cố",
    "ex1": "The festival strengthens an important cultural idea each year.",
    "ex1_vi": "Lễ hội củng cố một ý nghĩa văn hóa quan trọng mỗi năm."
  },
  {
    "id": 170,
    "word": "relationships",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rilˈeɪʃʌnʃˌɪps/",
    "meaning": "các mối quan hệ",
    "ex1": "Visitors learn about relationships during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các mối quan hệ trong lễ hội Việt Nam này."
  },
  {
    "id": 171,
    "word": "keeps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈips/",
    "meaning": "giữ",
    "ex1": "The festival keeps an important cultural idea each year.",
    "ex1_vi": "Lễ hội giữ một ý nghĩa văn hóa quan trọng mỗi năm."
  },
  {
    "id": 172,
    "word": "beliefs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bɪlˈifs/",
    "meaning": "tín ngưỡng",
    "ex1": "Visitors learn about beliefs during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về tín ngưỡng trong lễ hội Việt Nam này."
  },
  {
    "id": 173,
    "word": "alive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌlˈaɪv/",
    "meaning": "còn tồn tại; sống",
    "ex1": "The festival has a alive feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét còn tồn tại; sống mà du khách có thể nhận thấy."
  },
  {
    "id": 174,
    "word": "teaches",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈiːtʃɪz/",
    "meaning": "dạy",
    "ex1": "The festival teaches an important cultural idea each year.",
    "ex1_vi": "Lễ hội dạy một ý nghĩa văn hóa quan trọng mỗi năm."
  },
  {
    "id": 175,
    "word": "younger",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈʌŋɡɝ/",
    "meaning": "trẻ hơn",
    "ex1": "The festival has a younger feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét trẻ hơn mà du khách có thể nhận thấy."
  },
  {
    "id": 176,
    "word": "generations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒɛnɚeɪʃənz/",
    "meaning": "các thế hệ",
    "ex1": "Visitors learn about generations during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các thế hệ trong lễ hội Việt Nam này."
  },
  {
    "id": 177,
    "word": "now",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/naʊ/",
    "meaning": "hiện nay",
    "ex1": "Local people welcome festival visitors now each year.",
    "ex1_vi": "Người dân địa phương chào đón du khách hiện nay mỗi năm."
  },
  {
    "id": 178,
    "word": "future",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fjutʃɚ/",
    "meaning": "tương lai",
    "ex1": "Visitors learn about future during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về tương lai trong lễ hội Việt Nam này."
  },
  {
    "id": 179,
    "word": "ban",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈæn/",
    "meaning": "ban",
    "ex1": "The Ban Flower Festival is held in Dien Bien Province every March.",
    "ex1_vi": "Lễ hội Hoa Ban được tổ chức tại tỉnh Điện Biên vào tháng ba hằng năm."
  },
  {
    "id": 180,
    "word": "flower",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈaʊɝ/",
    "meaning": "hoa",
    "ex1": "It celebrates the white ban flower and the rich culture of ethnic groups in northwestern Vietnam.",
    "ex1_vi": "Lễ hội tôn vinh hoa ban trắng và nền văn hóa phong phú của các nhóm dân tộc ở vùng Tây Bắc Việt Nam."
  },
  {
    "id": 181,
    "word": "held",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛld/",
    "meaning": "được tổ chức",
    "ex1": "Local people held during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương được tổ chức trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 182,
    "word": "dien",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/diːɛn/",
    "meaning": "Điện",
    "ex1": "Visitors learn about dien during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Điện trong lễ hội Việt Nam này."
  },
  {
    "id": 183,
    "word": "bien",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/biːɛn/",
    "meaning": "Biên",
    "ex1": "Visitors learn about bien during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về Biên trong lễ hội Việt Nam này."
  },
  {
    "id": 184,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ɛvɚi/",
    "meaning": "mỗi",
    "ex1": "Every visitors enjoy the cultural activities during the festival.",
    "ex1_vi": "Mỗi du khách thưởng thức các hoạt động văn hóa trong lễ hội."
  },
  {
    "id": 185,
    "word": "march",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɑrtʃ/",
    "meaning": "tháng ba",
    "ex1": "Visitors learn about march during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về tháng ba trong lễ hội Việt Nam này."
  },
  {
    "id": 186,
    "word": "white",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈaɪt/",
    "meaning": "trắng",
    "ex1": "It celebrates the white ban flower and the rich culture of ethnic groups in northwestern Vietnam.",
    "ex1_vi": "Lễ hội tôn vinh hoa ban trắng và nền văn hóa phong phú của các nhóm dân tộc ở vùng Tây Bắc Việt Nam."
  },
  {
    "id": 187,
    "word": "rich",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɪtʃ/",
    "meaning": "phong phú",
    "ex1": "The festival has a rich feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét phong phú mà du khách có thể nhận thấy."
  },
  {
    "id": 188,
    "word": "ethnic",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɛθnɪk/",
    "meaning": "thuộc dân tộc",
    "ex1": "The festival has a ethnic feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét thuộc dân tộc mà du khách có thể nhận thấy."
  },
  {
    "id": 189,
    "word": "groups",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡɹˈuːps/",
    "meaning": "các nhóm",
    "ex1": "Visitors learn about groups during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về các nhóm trong lễ hội Việt Nam này."
  },
  {
    "id": 190,
    "word": "northwestern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˌɔrθwˈɛstɝn/",
    "meaning": "thuộc vùng Tây Bắc",
    "ex1": "The festival has a northwestern feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét thuộc vùng Tây Bắc mà du khách có thể nhận thấy."
  },
  {
    "id": 191,
    "word": "watch",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɑtʃ/",
    "meaning": "xem",
    "ex1": "Local people watch during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương xem trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 192,
    "word": "listen",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɪsən/",
    "meaning": "lắng nghe",
    "ex1": "Local people listen during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương lắng nghe trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 193,
    "word": "folk",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈoʊk/",
    "meaning": "dân gian",
    "ex1": "Visitors learn about folk during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về dân gian trong lễ hội Việt Nam này."
  },
  {
    "id": 194,
    "word": "songs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔŋz/",
    "meaning": "bài hát",
    "ex1": "Visitors learn about songs during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về bài hát trong lễ hội Việt Nam này."
  },
  {
    "id": 195,
    "word": "see",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈi/",
    "meaning": "nhìn thấy",
    "ex1": "Local people see during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương nhìn thấy trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 196,
    "word": "flutes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈuts/",
    "meaning": "sáo",
    "ex1": "Visitors learn about flutes during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về sáo trong lễ hội Việt Nam này."
  },
  {
    "id": 197,
    "word": "other",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ʌðɚ/",
    "meaning": "khác",
    "ex1": "Other visitors enjoy the cultural activities during the festival.",
    "ex1_vi": "Khác du khách thưởng thức các hoạt động văn hóa trong lễ hội."
  },
  {
    "id": 198,
    "word": "instruments",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɪnstrʌmʌnts/",
    "meaning": "nhạc cụ",
    "ex1": "Visitors learn about instruments during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về nhạc cụ trong lễ hội Việt Nam này."
  },
  {
    "id": 199,
    "word": "offers",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɔfɝz/",
    "meaning": "có; cung cấp",
    "ex1": "The festival offers sports, food fairs, beauty contests, and cultural exhibitions.",
    "ex1_vi": "Lễ hội có các hoạt động thể thao, hội chợ ẩm thực, cuộc thi sắc đẹp và triển lãm văn hóa."
  },
  {
    "id": 200,
    "word": "sports",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈoːɹts/",
    "meaning": "thể thao",
    "ex1": "Visitors learn about sports during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về thể thao trong lễ hội Việt Nam này."
  },
  {
    "id": 201,
    "word": "fairs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɛrz/",
    "meaning": "hội chợ",
    "ex1": "Visitors learn about fairs during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về hội chợ trong lễ hội Việt Nam này."
  },
  {
    "id": 202,
    "word": "beauty",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bjˈuti/",
    "meaning": "vẻ đẹp",
    "ex1": "Visitors learn about beauty during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về vẻ đẹp trong lễ hội Việt Nam này."
  },
  {
    "id": 203,
    "word": "contests",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑntɛsts/",
    "meaning": "cuộc thi",
    "ex1": "Visitors learn about contests during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về cuộc thi trong lễ hội Việt Nam này."
  },
  {
    "id": 204,
    "word": "exhibitions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɛksʌbˈɪʃʌnz/",
    "meaning": "triển lãm",
    "ex1": "Visitors learn about exhibitions during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về triển lãm trong lễ hội Việt Nam này."
  },
  {
    "id": 205,
    "word": "tourists",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈʊrʌsts/",
    "meaning": "khách du lịch",
    "ex1": "Visitors learn about tourists during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về khách du lịch trong lễ hội Việt Nam này."
  },
  {
    "id": 206,
    "word": "try",
    "type": "verb",
    "cat": "v",
    "phonetic": "/trˈaɪ/",
    "meaning": "thử",
    "ex1": "Local people try during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương thử trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 207,
    "word": "dishes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪʃʌz/",
    "meaning": "món ăn",
    "ex1": "Visitors learn about dishes during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về món ăn trong lễ hội Việt Nam này."
  },
  {
    "id": 208,
    "word": "buy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈaɪ/",
    "meaning": "mua",
    "ex1": "Local people buy during the festival to preserve tradition.",
    "ex1_vi": "Người dân địa phương mua trong lễ hội để gìn giữ truyền thống."
  },
  {
    "id": 209,
    "word": "handmade",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈændmˈeɪd/",
    "meaning": "làm thủ công",
    "ex1": "The festival has a handmade feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét làm thủ công mà du khách có thể nhận thấy."
  },
  {
    "id": 210,
    "word": "products",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑdʌkts/",
    "meaning": "sản phẩm",
    "ex1": "Visitors learn about products during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về sản phẩm trong lễ hội Việt Nam này."
  },
  {
    "id": 211,
    "word": "village",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪlʌdʒ/",
    "meaning": "làng",
    "ex1": "Visitors learn about village during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về làng trong lễ hội Việt Nam này."
  },
  {
    "id": 212,
    "word": "promotes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌmˈoʊts/",
    "meaning": "thúc đẩy",
    "ex1": "The Ban Flower Festival promotes tourism and protects local traditions.",
    "ex1_vi": "Lễ hội Hoa Ban thúc đẩy du lịch và bảo tồn truyền thống địa phương."
  },
  {
    "id": 213,
    "word": "tourism",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈʊrˌɪzəm/",
    "meaning": "du lịch",
    "ex1": "The Ban Flower Festival promotes tourism and protects local traditions.",
    "ex1_vi": "Lễ hội Hoa Ban thúc đẩy du lịch và bảo tồn truyền thống địa phương."
  },
  {
    "id": 214,
    "word": "traditions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trʌdˈɪʃʌnz/",
    "meaning": "truyền thống",
    "ex1": "Visitors learn about traditions during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về truyền thống trong lễ hội Việt Nam này."
  },
  {
    "id": 215,
    "word": "natural",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nætʃɚəl/",
    "meaning": "thuộc thiên nhiên",
    "ex1": "The festival has a natural feature that visitors can notice.",
    "ex1_vi": "Lễ hội có một nét thuộc thiên nhiên mà du khách có thể nhận thấy."
  },
  {
    "id": 216,
    "word": "friendly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/frˈɛndli/",
    "meaning": "thân thiện",
    "ex1": "Local people welcome festival visitors friendly each year.",
    "ex1_vi": "Người dân địa phương chào đón du khách thân thiện mỗi năm."
  },
  {
    "id": 217,
    "word": "diversity",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪvˈɝsɪti/",
    "meaning": "sự đa dạng",
    "ex1": "Visitors learn about diversity during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về sự đa dạng trong lễ hội Việt Nam này."
  },
  {
    "id": 218,
    "word": "places",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪsəz/",
    "meaning": "nơi chốn",
    "ex1": "The festival places an important cultural idea each year.",
    "ex1_vi": "Lễ hội nơi chốn một ý nghĩa văn hóa quan trọng mỗi năm."
  }
];

const newReadingVocabOrder = [
  "kate",
  "festival",
  "important",
  "celebration",
  "cham",
  "people",
  "ninh",
  "thuan",
  "and",
  "binh",
  "usually",
  "takes",
  "place",
  "seventh",
  "month",
  "calendar",
  "visit",
  "ancient",
  "towers",
  "honor",
  "gods",
  "heroes",
  "ancestors",
  "religious",
  "leaders",
  "perform",
  "special",
  "ceremonies",
  "open",
  "tower",
  "doors",
  "dress",
  "sacred",
  "statues",
  "traditional",
  "clothes",
  "includes",
  "music",
  "dancing",
  "drums",
  "colorful",
  "costumes",
  "families",
  "prepare",
  "food",
  "relatives",
  "share",
  "happy",
  "moments",
  "together",
  "visitors",
  "can",
  "also",
  "learn",
  "crafts",
  "customs",
  "protects",
  "culture",
  "brings",
  "community",
  "closer",
  "joyful",
  "time",
  "respect",
  "gratitude",
  "family",
  "love",
  "cultural",
  "pride",
  "both",
  "young",
  "old",
  "bay",
  "nui",
  "cow",
  "racing",
  "famous",
  "event",
  "giang",
  "province",
  "organized",
  "khmer",
  "sene",
  "dolta",
  "holiday",
  "rainy",
  "season",
  "pairs",
  "cows",
  "race",
  "wet",
  "muddy",
  "field",
  "each",
  "driver",
  "stands",
  "small",
  "wooden",
  "board",
  "controls",
  "animals",
  "carefully",
  "fast",
  "exciting",
  "sometimes",
  "surprising",
  "large",
  "crowds",
  "cheer",
  "loudly",
  "enjoy",
  "local",
  "activities",
  "celebrates",
  "farming",
  "life",
  "strength",
  "teamwork",
  "joy",
  "villages",
  "helps",
  "protect",
  "southern",
  "vietnam",
  "many",
  "years",
  "ahead",
  "nghinh",
  "ong",
  "celebrated",
  "coastal",
  "towns",
  "honors",
  "whale",
  "fishermen",
  "believe",
  "dangerous",
  "journeys",
  "sea",
  "often",
  "begins",
  "boat",
  "parade",
  "fishing",
  "boats",
  "decorated",
  "flags",
  "flowers",
  "bright",
  "colors",
  "carry",
  "offerings",
  "invite",
  "spirit",
  "temple",
  "lion",
  "dances",
  "games",
  "attract",
  "pray",
  "calm",
  "seas",
  "good",
  "weather",
  "successful",
  "year",
  "shows",
  "nature",
  "strengthens",
  "relationships",
  "keeps",
  "beliefs",
  "alive",
  "teaches",
  "younger",
  "generations",
  "now",
  "future",
  "ban",
  "flower",
  "held",
  "dien",
  "bien",
  "every",
  "march",
  "white",
  "rich",
  "ethnic",
  "groups",
  "northwestern",
  "watch",
  "listen",
  "folk",
  "songs",
  "see",
  "flutes",
  "other",
  "instruments",
  "offers",
  "sports",
  "fairs",
  "beauty",
  "contests",
  "exhibitions",
  "tourists",
  "try",
  "dishes",
  "buy",
  "handmade",
  "products",
  "village",
  "promotes",
  "tourism",
  "traditions",
  "natural",
  "friendly",
  "diversity",
  "places"
];
