// ===== festival01 ESSAY =====

const newEssayData = [
  {
    "text": "1. The Hung Kings Festival – Lễ hội Đền Hùng\nThe Hung Kings Festival is held in Phu Tho Province every year. It takes place on the tenth day of the third lunar month. Many people visit the Hung Temple to remember the ancient kings of Vietnam.\n\nDuring the festival, people offer flowers, fruit, rice cakes, and incense. Important ceremonies are held in a serious and respectful way. Traditional music and drum performances create a special atmosphere.\n\nVisitors can also watch folk games, wrestling, and cultural shows. Local people wear beautiful traditional clothes and welcome guests warmly.\n\nThe festival teaches young people about Vietnamese history. It also shows respect for ancestors and reminds everyone to protect national traditions together today.",
    "vi": "1. The Hung Kings Festival – Lễ hội Đền Hùng\nLễ hội Đền Hùng được tổ chức tại tỉnh Phú Thọ hằng năm. Lễ hội diễn ra vào ngày mùng mười tháng ba âm lịch. Nhiều người đến Đền Hùng để tưởng nhớ các vị vua cổ của Việt Nam.\n\nTrong lễ hội, mọi người dâng hoa, trái cây, bánh gạo và hương. Các nghi lễ quan trọng được tổ chức theo cách trang nghiêm và kính cẩn. Âm nhạc truyền thống và các màn biểu diễn trống tạo nên một bầu không khí đặc biệt.\n\nDu khách cũng có thể xem các trò chơi dân gian, đấu vật và các chương trình văn hóa. Người dân địa phương mặc trang phục truyền thống đẹp và nồng nhiệt chào đón khách.\n\nLễ hội dạy người trẻ về lịch sử Việt Nam. Lễ hội cũng thể hiện sự kính trọng tổ tiên và nhắc nhở mọi người cùng bảo vệ các truyền thống dân tộc ngày nay."
  },
  {
    "text": "2. The Perfume Pagoda Festival – Lễ hội Chùa Hương\nThe Perfume Pagoda Festival is one of the largest religious festivals in Vietnam. It is held in Hanoi from the first to the third lunar month. Thousands of visitors come to pray for health, luck, and happiness.\n\nThe journey begins with a boat ride along Yen Stream. The water is calm, and the mountains create beautiful views. Visitors then walk or take a cable car to the pagodas.\n\nPeople visit Huong Tich Cave, Thien Tru Pagoda, and other sacred places. They light incense and enjoy the peaceful atmosphere.\n\nThe festival is both a religious trip and a nature tour. It helps people relax, think positively, and appreciate Vietnamese culture today.",
    "vi": "2. The Perfume Pagoda Festival – Lễ hội Chùa Hương\nLễ hội Chùa Hương là một trong những lễ hội tôn giáo lớn nhất ở Việt Nam. Lễ hội được tổ chức tại Hà Nội từ tháng giêng đến tháng ba âm lịch. Hàng nghìn du khách đến cầu sức khỏe, may mắn và hạnh phúc.\n\nHành trình bắt đầu bằng một chuyến đi thuyền dọc theo suối Yến. Nước yên ả và những ngọn núi tạo nên cảnh đẹp. Sau đó, du khách đi bộ hoặc đi cáp treo đến các ngôi chùa.\n\nMọi người đến thăm động Hương Tích, chùa Thiên Trù và những địa điểm linh thiêng khác. Họ thắp hương và tận hưởng bầu không khí thanh bình.\n\nLễ hội vừa là một chuyến hành hương tôn giáo vừa là một chuyến tham quan thiên nhiên. Lễ hội giúp mọi người thư giãn, suy nghĩ tích cực và trân trọng văn hóa Việt Nam ngày nay."
  },
  {
    "text": "3. Lim Festival – Hội Lim\nLim Festival is a famous cultural festival in Bac Ninh Province. It usually takes place on the thirteenth day of the first lunar month. The festival is well known for Quan Ho folk songs.\n\nMale and female singers wear traditional clothes and sing together. They often perform on boats, hills, or village stages. Their songs are gentle, emotional, and full of local culture.\n\nVisitors can enjoy wrestling, bamboo swinging, human chess, and other folk games. They can also taste local food and meet friendly people.\n\nLim Festival protects the traditional music of northern Vietnam. It brings communities together and helps young people understand and love their cultural heritage together today.",
    "vi": "3. Lim Festival – Hội Lim\nHội Lim là một lễ hội văn hóa nổi tiếng ở tỉnh Bắc Ninh. Lễ hội thường diễn ra vào ngày mười ba tháng giêng âm lịch. Lễ hội nổi tiếng với những làn điệu dân ca Quan họ.\n\nNam và nữ liền anh liền chị mặc trang phục truyền thống và hát cùng nhau. Họ thường biểu diễn trên thuyền, trên đồi hoặc sân khấu làng. Những bài hát của họ nhẹ nhàng, giàu cảm xúc và đậm nét văn hóa địa phương.\n\nDu khách có thể thưởng thức đấu vật, đánh đu tre, cờ người và các trò chơi dân gian khác. Họ cũng có thể nếm món ăn địa phương và gặp gỡ những người thân thiện.\n\nHội Lim bảo tồn âm nhạc truyền thống của miền Bắc Việt Nam. Lễ hội gắn kết cộng đồng và giúp người trẻ hiểu và yêu di sản văn hóa của mình ngày nay."
  }
];
