const lessonVocabularyWords = [
  "packing",
  "essentials",
  "for",
  "travelers",
  "pack",
  "light",
  "travel",
  "right",
  "carefully",
  "can",
  "make",
  "your",
  "trip",
  "easier",
  "more",
  "comfortable",
  "and",
  "less",
  "stressful",
  "before",
  "traveling",
  "list",
  "of",
  "important",
  "things",
  "you",
  "need",
  "to",
  "bring",
  "with",
  "clothes",
  "weather",
  "do",
  "not",
  "forget",
  "passport",
  "tickets",
  "phone",
  "charger",
  "medicine",
  "water",
  "bottle",
  "convenience",
  "during",
  "try",
  "carry",
  "too",
  "many",
  "because",
  "heavy",
  "bags",
  "difficult",
  "move",
  "smart",
  "saves",
  "time",
  "gives",
  "freedom",
  "every",
  "journey",
  "apps",
  "should",
  "use",
  "technology",
  "makes",
  "today",
  "useful",
  "their",
  "trips",
  "better",
  "help",
  "people",
  "save",
  "find",
  "information",
  "quickly",
  "everywhere",
  "map",
  "places",
  "choose",
  "best",
  "routes",
  "available",
  "translation",
  "communicate",
  "local",
  "in",
  "different",
  "countries",
  "easily",
  "some",
  "book",
  "hotels",
  "activities",
  "only",
  "few",
  "touches",
  "using",
  "safer",
  "faster",
  "convenient",
  "everyone",
  "eco-friendly",
  "protect",
  "nature",
  "while",
  "exploring",
  "enjoyable",
  "but",
  "we",
  "also",
  "care",
  "our",
  "beautiful",
  "environment",
  "responsible",
  "reduce",
  "waste",
  "reusable",
  "bottles",
  "instead",
  "single-use",
  "plastic",
  "items",
  "whenever",
  "possible",
  "leave",
  "rubbish",
  "behind",
  "always",
  "respect",
  "animals",
  "plants",
  "natural",
  "areas",
  "walking",
  "cycling",
  "public",
  "transport",
  "pollution",
  "energy",
  "small",
  "actions",
  "by",
  "keep",
  "planet",
  "clean"
];

const newVocabData = [
  {
    "id": 1,
    "word": "packing",
    "type": "gerund/noun",
    "cat": "n",
    "phonetic": "/pˈækɪŋ/",
    "meaning": "đóng hành lý",
    "ex1": "Packing carefully can make your trip easier, more comfortable, and less stressful.",
    "ex1_vi": "Đóng hành lý cẩn thận có thể làm chuyến đi dễ dàng, thoải mái và bớt căng thẳng hơn."
  },
  {
    "id": 2,
    "word": "essentials",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɛsˈɛnʃʌlz/",
    "meaning": "những đồ thiết yếu",
    "ex1": "Packing essentials include a passport, charger, and medicine.",
    "ex1_vi": "Đồ thiết yếu khi đóng hành lý gồm hộ chiếu, bộ sạc và thuốc."
  },
  {
    "id": 3,
    "word": "for",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/fˈɔr/",
    "meaning": "cho; để",
    "ex1": "Pack clothes for the weather and do not forget your passport and tickets.",
    "ex1_vi": "Hãy xếp quần áo phù hợp với thời tiết và đừng quên hộ chiếu cùng vé."
  },
  {
    "id": 4,
    "word": "travelers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈævʌlɝz/",
    "meaning": "du khách",
    "ex1": "Smart packing saves time and gives travelers more freedom during every journey.",
    "ex1_vi": "Đóng hành lý thông minh tiết kiệm thời gian và cho du khách nhiều tự do hơn trong mỗi hành trình."
  },
  {
    "id": 5,
    "word": "pack",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pˈæk/",
    "meaning": "xếp; đóng gói",
    "ex1": "Pack clothes for the weather and do not forget your passport and tickets.",
    "ex1_vi": "Hãy xếp quần áo phù hợp với thời tiết và đừng quên hộ chiếu cùng vé."
  },
  {
    "id": 6,
    "word": "light",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪt/",
    "meaning": "nhẹ",
    "ex1": "Travelers pack light to move more easily between places.",
    "ex1_vi": "Du khách đóng hành lý nhẹ để di chuyển dễ dàng hơn giữa các nơi."
  },
  {
    "id": 7,
    "word": "travel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/trˈævʌl/",
    "meaning": "du lịch; đi lại",
    "ex1": "Travel apps can help people save time and find information quickly everywhere.",
    "ex1_vi": "Ứng dụng du lịch có thể giúp mọi người tiết kiệm thời gian và nhanh chóng tìm thông tin ở mọi nơi."
  },
  {
    "id": 8,
    "word": "right",
    "type": "adverb/adjective",
    "cat": "adv",
    "phonetic": "/rˈaɪt/",
    "meaning": "ngay; đúng",
    "ex1": "The right travel choices can reduce unnecessary stress.",
    "ex1_vi": "Những lựa chọn du lịch đúng đắn có thể giảm căng thẳng không cần thiết."
  },
  {
    "id": 9,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "Packing carefully can make your trip easier, more comfortable, and less stressful.",
    "ex1_vi": "Đóng hành lý cẩn thận có thể làm chuyến đi dễ dàng, thoải mái và bớt căng thẳng hơn."
  },
  {
    "id": 10,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Travel apps can help people save time and find information quickly everywhere.",
    "ex1_vi": "Ứng dụng du lịch có thể giúp mọi người tiết kiệm thời gian và nhanh chóng tìm thông tin ở mọi nơi."
  },
  {
    "id": 11,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm cho",
    "ex1": "Today, many travelers use useful apps to make their trips easier and better.",
    "ex1_vi": "Ngày nay, nhiều du khách sử dụng các ứng dụng hữu ích để làm chuyến đi dễ dàng và tốt hơn."
  },
  {
    "id": 12,
    "word": "your",
    "type": "possessive determiner",
    "cat": "adj",
    "phonetic": "/jˈɔr/",
    "meaning": "của bạn",
    "ex1": "Bring your phone charger, medicine, and a water bottle for convenience during travel.",
    "ex1_vi": "Mang bộ sạc điện thoại, thuốc và một chai nước để thuận tiện khi đi lại."
  },
  {
    "id": 13,
    "word": "trip",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈɪp/",
    "meaning": "chuyến đi",
    "ex1": "During a trip, packing carefully can make your trip easier, more comfortable, and less stressful.",
    "ex1_vi": "Trong một chuyến đi, đóng hành lý cẩn thận có thể làm chuyến đi dễ dàng, thoải mái và bớt căng thẳng hơn."
  },
  {
    "id": 14,
    "word": "easier",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈiziɝ/",
    "meaning": "dễ hơn",
    "ex1": "Today, many travelers use useful apps to make their trips easier and better.",
    "ex1_vi": "Ngày nay, nhiều du khách sử dụng các ứng dụng hữu ích để làm chuyến đi dễ dàng và tốt hơn."
  },
  {
    "id": 15,
    "word": "more",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "nhiều hơn",
    "ex1": "Smart packing saves time and gives travelers more freedom during every journey.",
    "ex1_vi": "Đóng hành lý thông minh tiết kiệm thời gian và cho du khách nhiều tự do hơn trong mỗi hành trình."
  },
  {
    "id": 16,
    "word": "comfortable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌmfɝtʌbʌl/",
    "meaning": "thoải mái",
    "ex1": "For many travelers, packing carefully can make your trip easier, more comfortable, and less stressful.",
    "ex1_vi": "Đối với nhiều du khách, đóng hành lý cẩn thận có thể làm chuyến đi dễ dàng, thoải mái và bớt căng thẳng hơn."
  },
  {
    "id": 17,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Responsible travelers try to reduce waste and protect nature during every journey.",
    "ex1_vi": "Những du khách có trách nhiệm cố gắng giảm rác thải và bảo vệ thiên nhiên trong mỗi hành trình."
  },
  {
    "id": 18,
    "word": "less",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/lˈɛs/",
    "meaning": "ít hơn",
    "ex1": "Smart planning can make a trip less stressful.",
    "ex1_vi": "Lập kế hoạch thông minh có thể làm chuyến đi bớt căng thẳng."
  },
  {
    "id": 19,
    "word": "stressful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɛsfʌl/",
    "meaning": "căng thẳng",
    "ex1": "In daily travel, packing carefully can make your trip easier, more comfortable, and less stressful.",
    "ex1_vi": "Trong việc du lịch hằng ngày, đóng hành lý cẩn thận có thể làm chuyến đi dễ dàng, thoải mái và bớt căng thẳng hơn."
  },
  {
    "id": 20,
    "word": "before",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/bɪfˈɔr/",
    "meaning": "trước",
    "ex1": "Before traveling, make a list of important things you need to bring with you.",
    "ex1_vi": "Trước khi đi du lịch, hãy lập danh sách những thứ quan trọng bạn cần mang theo."
  },
  {
    "id": 21,
    "word": "traveling",
    "type": "gerund/noun",
    "cat": "n",
    "phonetic": "/ˈtrævəlɪŋ/",
    "meaning": "du lịch; việc đi du lịch",
    "ex1": "Traveling is enjoyable, but we should also care for our beautiful environment everywhere.",
    "ex1_vi": "Du lịch rất thú vị, nhưng chúng ta cũng nên quan tâm đến môi trường tươi đẹp ở khắp mọi nơi."
  },
  {
    "id": 22,
    "word": "list",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɪst/",
    "meaning": "danh sách",
    "ex1": "Before traveling, make a list of important things you need to bring with you.",
    "ex1_vi": "Trước khi đi du lịch, hãy lập danh sách những thứ quan trọng bạn cần mang theo."
  },
  {
    "id": 23,
    "word": "of",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ˈʌv/",
    "meaning": "của",
    "ex1": "Use reusable bottles and bags instead of single-use plastic items whenever possible.",
    "ex1_vi": "Hãy dùng chai và túi tái sử dụng thay cho các vật dụng nhựa dùng một lần bất cứ khi nào có thể."
  },
  {
    "id": 24,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔrtʌnt/",
    "meaning": "quan trọng",
    "ex1": "During a trip, before traveling, make a list of important things you need to bring with you.",
    "ex1_vi": "Trong một chuyến đi, trước khi đi du lịch, hãy lập danh sách những thứ quan trọng bạn cần mang theo."
  },
  {
    "id": 25,
    "word": "things",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈɪŋz/",
    "meaning": "đồ vật; những thứ",
    "ex1": "Try not to carry too many things because heavy bags are difficult to move.",
    "ex1_vi": "Cố gắng không mang quá nhiều đồ vì những chiếc túi nặng khó di chuyển."
  },
  {
    "id": 26,
    "word": "you",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/jˈu/",
    "meaning": "bạn",
    "ex1": "You can save money by booking tickets early.",
    "ex1_vi": "Bạn có thể tiết kiệm tiền bằng cách đặt vé sớm."
  },
  {
    "id": 27,
    "word": "need",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈid/",
    "meaning": "cần",
    "ex1": "For many travelers, before traveling, make a list of important things you need to bring with you.",
    "ex1_vi": "Đối với nhiều du khách, trước khi đi du lịch, hãy lập danh sách những thứ quan trọng bạn cần mang theo."
  },
  {
    "id": 28,
    "word": "to",
    "type": "preposition/infinitive marker",
    "cat": "adv",
    "phonetic": "/tˈu/",
    "meaning": "để; tới",
    "ex1": "Responsible travelers try to reduce waste and protect nature during every journey.",
    "ex1_vi": "Những du khách có trách nhiệm cố gắng giảm rác thải và bảo vệ thiên nhiên trong mỗi hành trình."
  },
  {
    "id": 29,
    "word": "bring",
    "type": "verb",
    "cat": "v",
    "phonetic": "/brˈɪŋ/",
    "meaning": "mang",
    "ex1": "Bring your phone charger, medicine, and a water bottle for convenience during travel.",
    "ex1_vi": "Mang bộ sạc điện thoại, thuốc và một chai nước để thuận tiện khi đi lại."
  },
  {
    "id": 30,
    "word": "with",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/wˈɪð/",
    "meaning": "với",
    "ex1": "Translation apps help people communicate with local people in different countries more easily.",
    "ex1_vi": "Ứng dụng dịch thuật giúp mọi người giao tiếp dễ dàng hơn với người địa phương ở các quốc gia khác nhau."
  },
  {
    "id": 31,
    "word": "clothes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈoʊðz/",
    "meaning": "quần áo",
    "ex1": "During a trip, pack clothes for the weather and do not forget your passport and tickets.",
    "ex1_vi": "Trong một chuyến đi, hãy xếp quần áo phù hợp với thời tiết và đừng quên hộ chiếu cùng vé."
  },
  {
    "id": 32,
    "word": "weather",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɛðɝ/",
    "meaning": "thời tiết",
    "ex1": "For many travelers, pack clothes for the weather and do not forget your passport and tickets.",
    "ex1_vi": "Đối với nhiều du khách, hãy xếp quần áo phù hợp với thời tiết và đừng quên hộ chiếu cùng vé."
  },
  {
    "id": 33,
    "word": "do",
    "type": "auxiliary/verb",
    "cat": "v",
    "phonetic": "/dˈu/",
    "meaning": "trợ động từ; làm",
    "ex1": "Do not leave rubbish behind and always respect animals, plants, and natural areas.",
    "ex1_vi": "Đừng để rác lại phía sau và luôn tôn trọng động vật, thực vật cùng các khu vực tự nhiên."
  },
  {
    "id": 34,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "Do not leave rubbish behind and always respect animals, plants, and natural areas.",
    "ex1_vi": "Đừng để rác lại phía sau và luôn tôn trọng động vật, thực vật cùng các khu vực tự nhiên."
  },
  {
    "id": 35,
    "word": "forget",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fɝɡˈɛt/",
    "meaning": "quên",
    "ex1": "In daily travel, pack clothes for the weather and do not forget your passport and tickets.",
    "ex1_vi": "Trong việc du lịch hằng ngày, hãy xếp quần áo phù hợp với thời tiết và đừng quên hộ chiếu cùng vé."
  },
  {
    "id": 36,
    "word": "passport",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈæspˌɔrt/",
    "meaning": "hộ chiếu",
    "ex1": "While exploring, pack clothes for the weather and do not forget your passport and tickets.",
    "ex1_vi": "Khi khám phá, hãy xếp quần áo phù hợp với thời tiết và đừng quên hộ chiếu cùng vé."
  },
  {
    "id": 37,
    "word": "tickets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɪkʌts/",
    "meaning": "vé",
    "ex1": "Some apps can book hotels, tickets, and activities with only a few touches.",
    "ex1_vi": "Một số ứng dụng có thể đặt khách sạn, vé và hoạt động chỉ với vài lần chạm."
  },
  {
    "id": 38,
    "word": "phone",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈoʊn/",
    "meaning": "điện thoại",
    "ex1": "During a trip, bring your phone charger, medicine, and a water bottle for convenience during travel.",
    "ex1_vi": "Trong một chuyến đi, mang bộ sạc điện thoại, thuốc và một chai nước để thuận tiện khi đi lại."
  },
  {
    "id": 39,
    "word": "charger",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈtʃɑːrdʒər/",
    "meaning": "bộ sạc",
    "ex1": "For many travelers, bring your phone charger, medicine, and a water bottle for convenience during travel.",
    "ex1_vi": "Đối với nhiều du khách, mang bộ sạc điện thoại, thuốc và một chai nước để thuận tiện khi đi lại."
  },
  {
    "id": 40,
    "word": "medicine",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛdʌsʌn/",
    "meaning": "thuốc",
    "ex1": "In daily travel, bring your phone charger, medicine, and a water bottle for convenience during travel.",
    "ex1_vi": "Trong việc du lịch hằng ngày, mang bộ sạc điện thoại, thuốc và một chai nước để thuận tiện khi đi lại."
  },
  {
    "id": 41,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước",
    "ex1": "While exploring, bring your phone charger, medicine, and a water bottle for convenience during travel.",
    "ex1_vi": "Khi khám phá, mang bộ sạc điện thoại, thuốc và một chai nước để thuận tiện khi đi lại."
  },
  {
    "id": 42,
    "word": "bottle",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɑtʌl/",
    "meaning": "chai",
    "ex1": "On a journey, bring your phone charger, medicine, and a water bottle for convenience during travel.",
    "ex1_vi": "Trong một hành trình, mang bộ sạc điện thoại, thuốc và một chai nước để thuận tiện khi đi lại."
  },
  {
    "id": 43,
    "word": "convenience",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌnvˈinjʌns/",
    "meaning": "sự tiện lợi",
    "ex1": "Before departure, bring your phone charger, medicine, and a water bottle for convenience during travel.",
    "ex1_vi": "Trước khi khởi hành, mang bộ sạc điện thoại, thuốc và một chai nước để thuận tiện khi đi lại."
  },
  {
    "id": 44,
    "word": "during",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/dˈʊrɪŋ/",
    "meaning": "trong khi; suốt",
    "ex1": "During a trip, smart packing saves time and gives travelers more freedom during every journey.",
    "ex1_vi": "Trong một chuyến đi, đóng hành lý thông minh tiết kiệm thời gian và cho du khách nhiều tự do hơn trong mỗi hành trình."
  },
  {
    "id": 45,
    "word": "try",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈaɪ/",
    "meaning": "cố gắng",
    "ex1": "Try not to carry too many things because heavy bags are difficult to move.",
    "ex1_vi": "Cố gắng không mang quá nhiều đồ vì những chiếc túi nặng khó di chuyển."
  },
  {
    "id": 46,
    "word": "carry",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈæri/",
    "meaning": "mang",
    "ex1": "During a trip, try not to carry too many things because heavy bags are difficult to move.",
    "ex1_vi": "Trong một chuyến đi, cố gắng không mang quá nhiều đồ vì những chiếc túi nặng khó di chuyển."
  },
  {
    "id": 47,
    "word": "too",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tˈu/",
    "meaning": "quá",
    "ex1": "Walking, cycling, and public transport can reduce pollution and save energy too.",
    "ex1_vi": "Đi bộ, đạp xe và giao thông công cộng có thể giảm ô nhiễm và tiết kiệm năng lượng."
  },
  {
    "id": 48,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Many travelers enjoy learning about local culture.",
    "ex1_vi": "Nhiều du khách thích tìm hiểu văn hóa địa phương."
  },
  {
    "id": 49,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "Smart travelers pack lightly because heavy bags are difficult.",
    "ex1_vi": "Du khách thông minh đóng hành lý nhẹ vì túi nặng rất khó mang."
  },
  {
    "id": 50,
    "word": "heavy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛvi/",
    "meaning": "nặng",
    "ex1": "For many travelers, try not to carry too many things because heavy bags are difficult to move.",
    "ex1_vi": "Đối với nhiều du khách, cố gắng không mang quá nhiều đồ vì những chiếc túi nặng khó di chuyển."
  },
  {
    "id": 51,
    "word": "bags",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈæɡz/",
    "meaning": "túi; hành lý",
    "ex1": "Use reusable bottles and bags instead of single-use plastic items whenever possible.",
    "ex1_vi": "Hãy dùng chai và túi tái sử dụng thay cho các vật dụng nhựa dùng một lần bất cứ khi nào có thể."
  },
  {
    "id": 52,
    "word": "difficult",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfʌkʌlt/",
    "meaning": "khó",
    "ex1": "In daily travel, try not to carry too many things because heavy bags are difficult to move.",
    "ex1_vi": "Trong việc du lịch hằng ngày, cố gắng không mang quá nhiều đồ vì những chiếc túi nặng khó di chuyển."
  },
  {
    "id": 53,
    "word": "move",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈuv/",
    "meaning": "di chuyển",
    "ex1": "While exploring, try not to carry too many things because heavy bags are difficult to move.",
    "ex1_vi": "Khi khám phá, cố gắng không mang quá nhiều đồ vì những chiếc túi nặng khó di chuyển."
  },
  {
    "id": 54,
    "word": "smart",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɑrt/",
    "meaning": "thông minh",
    "ex1": "Smart travelers keep important documents in a safe place.",
    "ex1_vi": "Du khách thông minh giữ giấy tờ quan trọng ở nơi an toàn."
  },
  {
    "id": 55,
    "word": "saves",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪvz/",
    "meaning": "tiết kiệm",
    "ex1": "For many travelers, smart packing saves time and gives travelers more freedom during every journey.",
    "ex1_vi": "Đối với nhiều du khách, đóng hành lý thông minh tiết kiệm thời gian và cho du khách nhiều tự do hơn trong mỗi hành trình."
  },
  {
    "id": 56,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "Good planning saves time during a busy journey.",
    "ex1_vi": "Lập kế hoạch tốt tiết kiệm thời gian trong một hành trình bận rộn."
  },
  {
    "id": 57,
    "word": "gives",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvz/",
    "meaning": "mang lại",
    "ex1": "In daily travel, smart packing saves time and gives travelers more freedom during every journey.",
    "ex1_vi": "Trong việc du lịch hằng ngày, đóng hành lý thông minh tiết kiệm thời gian và cho du khách nhiều tự do hơn trong mỗi hành trình."
  },
  {
    "id": 58,
    "word": "freedom",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈidʌm/",
    "meaning": "sự tự do",
    "ex1": "While exploring, smart packing saves time and gives travelers more freedom during every journey.",
    "ex1_vi": "Khi khám phá, đóng hành lý thông minh tiết kiệm thời gian và cho du khách nhiều tự do hơn trong mỗi hành trình."
  },
  {
    "id": 59,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɝi/",
    "meaning": "mỗi",
    "ex1": "Every trip can create valuable memories and new experiences.",
    "ex1_vi": "Mỗi chuyến đi có thể tạo nên những kỷ niệm và trải nghiệm quý giá."
  },
  {
    "id": 60,
    "word": "journey",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɝni/",
    "meaning": "hành trình",
    "ex1": "On a journey, smart packing saves time and gives travelers more freedom during every journey.",
    "ex1_vi": "Trong một hành trình, đóng hành lý thông minh tiết kiệm thời gian và cho du khách nhiều tự do hơn trong mỗi hành trình."
  },
  {
    "id": 61,
    "word": "apps",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈæps/",
    "meaning": "ứng dụng",
    "ex1": "Map apps help travelers find places and choose the best travel routes available.",
    "ex1_vi": "Ứng dụng bản đồ giúp du khách tìm địa điểm và chọn những tuyến đường du lịch tốt nhất hiện có."
  },
  {
    "id": 62,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "Traveling is enjoyable, but we should also care for our beautiful environment everywhere.",
    "ex1_vi": "Du lịch rất thú vị, nhưng chúng ta cũng nên quan tâm đến môi trường tươi đẹp ở khắp mọi nơi."
  },
  {
    "id": 63,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "During a trip, use reusable bottles and bags instead of single-use plastic items whenever possible.",
    "ex1_vi": "Trong một chuyến đi, hãy dùng chai và túi tái sử dụng thay cho các vật dụng nhựa dùng một lần bất cứ khi nào có thể."
  },
  {
    "id": 64,
    "word": "technology",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tɛknˈɑlʌdʒi/",
    "meaning": "công nghệ",
    "ex1": "Travel technology helps people find routes and hotels quickly.",
    "ex1_vi": "Công nghệ du lịch giúp mọi người nhanh chóng tìm tuyến đường và khách sạn."
  },
  {
    "id": 65,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm cho",
    "ex1": "Using travel apps makes trips safer, faster, and more convenient for everyone today.",
    "ex1_vi": "Việc sử dụng ứng dụng du lịch làm các chuyến đi an toàn hơn, nhanh hơn và thuận tiện hơn cho mọi người ngày nay."
  },
  {
    "id": 66,
    "word": "today",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌdˈeɪ/",
    "meaning": "ngày nay",
    "ex1": "Using travel apps makes trips safer, faster, and more convenient for everyone today.",
    "ex1_vi": "Việc sử dụng ứng dụng du lịch làm các chuyến đi an toàn hơn, nhanh hơn và thuận tiện hơn cho mọi người ngày nay."
  },
  {
    "id": 67,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈusfʌl/",
    "meaning": "hữu ích",
    "ex1": "During a trip, today, many travelers use useful apps to make their trips easier and better.",
    "ex1_vi": "Trong một chuyến đi, ngày nay, nhiều du khách sử dụng các ứng dụng hữu ích để làm chuyến đi dễ dàng và tốt hơn."
  },
  {
    "id": 68,
    "word": "their",
    "type": "possessive determiner",
    "cat": "adj",
    "phonetic": "/ðˈɛr/",
    "meaning": "của họ",
    "ex1": "Travelers can make their own plans when traveling alone.",
    "ex1_vi": "Du khách có thể tự lập kế hoạch khi đi du lịch một mình."
  },
  {
    "id": 69,
    "word": "trips",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈɪps/",
    "meaning": "các chuyến đi",
    "ex1": "For many travelers, today, many travelers use useful apps to make their trips easier and better.",
    "ex1_vi": "Đối với nhiều du khách, ngày nay, nhiều du khách sử dụng các ứng dụng hữu ích để làm chuyến đi dễ dàng và tốt hơn."
  },
  {
    "id": 70,
    "word": "better",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɛtɝ/",
    "meaning": "tốt hơn",
    "ex1": "In daily travel, today, many travelers use useful apps to make their trips easier and better.",
    "ex1_vi": "Trong việc du lịch hằng ngày, ngày nay, nhiều du khách sử dụng các ứng dụng hữu ích để làm chuyến đi dễ dàng và tốt hơn."
  },
  {
    "id": 71,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "Map apps help travelers find places and choose the best travel routes available.",
    "ex1_vi": "Ứng dụng bản đồ giúp du khách tìm địa điểm và chọn những tuyến đường du lịch tốt nhất hiện có."
  },
  {
    "id": 72,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "Translation apps help people communicate with local people in different countries more easily.",
    "ex1_vi": "Ứng dụng dịch thuật giúp mọi người giao tiếp dễ dàng hơn với người địa phương ở các quốc gia khác nhau."
  },
  {
    "id": 73,
    "word": "save",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪv/",
    "meaning": "tiết kiệm; lưu",
    "ex1": "Walking, cycling, and public transport can reduce pollution and save energy too.",
    "ex1_vi": "Đi bộ, đạp xe và giao thông công cộng có thể giảm ô nhiễm và tiết kiệm năng lượng."
  },
  {
    "id": 74,
    "word": "find",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪnd/",
    "meaning": "tìm",
    "ex1": "During a trip, travel apps can help people save time and find information quickly everywhere.",
    "ex1_vi": "Trong một chuyến đi, ứng dụng du lịch có thể giúp mọi người tiết kiệm thời gian và nhanh chóng tìm thông tin ở mọi nơi."
  },
  {
    "id": 75,
    "word": "information",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnfɝmˈeɪʃʌn/",
    "meaning": "thông tin",
    "ex1": "For many travelers, travel apps can help people save time and find information quickly everywhere.",
    "ex1_vi": "Đối với nhiều du khách, ứng dụng du lịch có thể giúp mọi người tiết kiệm thời gian và nhanh chóng tìm thông tin ở mọi nơi."
  },
  {
    "id": 76,
    "word": "quickly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kwˈɪkli/",
    "meaning": "nhanh chóng",
    "ex1": "In daily travel, travel apps can help people save time and find information quickly everywhere.",
    "ex1_vi": "Trong việc du lịch hằng ngày, ứng dụng du lịch có thể giúp mọi người tiết kiệm thời gian và nhanh chóng tìm thông tin ở mọi nơi."
  },
  {
    "id": 77,
    "word": "everywhere",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɛvriwˌɛr/",
    "meaning": "mọi nơi",
    "ex1": "While exploring, travel apps can help people save time and find information quickly everywhere.",
    "ex1_vi": "Khi khám phá, ứng dụng du lịch có thể giúp mọi người tiết kiệm thời gian và nhanh chóng tìm thông tin ở mọi nơi."
  },
  {
    "id": 78,
    "word": "map",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈæp/",
    "meaning": "bản đồ",
    "ex1": "During a trip, map apps help travelers find places and choose the best travel routes available.",
    "ex1_vi": "Trong một chuyến đi, ứng dụng bản đồ giúp du khách tìm địa điểm và chọn những tuyến đường du lịch tốt nhất hiện có."
  },
  {
    "id": 79,
    "word": "places",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪsʌz/",
    "meaning": "nơi",
    "ex1": "For many travelers, map apps help travelers find places and choose the best travel routes available.",
    "ex1_vi": "Đối với nhiều du khách, ứng dụng bản đồ giúp du khách tìm địa điểm và chọn những tuyến đường du lịch tốt nhất hiện có."
  },
  {
    "id": 80,
    "word": "choose",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈuz/",
    "meaning": "chọn",
    "ex1": "In daily travel, map apps help travelers find places and choose the best travel routes available.",
    "ex1_vi": "Trong việc du lịch hằng ngày, ứng dụng bản đồ giúp du khách tìm địa điểm và chọn những tuyến đường du lịch tốt nhất hiện có."
  },
  {
    "id": 81,
    "word": "best",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɛst/",
    "meaning": "tốt nhất",
    "ex1": "While exploring, map apps help travelers find places and choose the best travel routes available.",
    "ex1_vi": "Khi khám phá, ứng dụng bản đồ giúp du khách tìm địa điểm và chọn những tuyến đường du lịch tốt nhất hiện có."
  },
  {
    "id": 82,
    "word": "routes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈuts/",
    "meaning": "tuyến đường",
    "ex1": "On a journey, map apps help travelers find places and choose the best travel routes available.",
    "ex1_vi": "Trong một hành trình, ứng dụng bản đồ giúp du khách tìm địa điểm và chọn những tuyến đường du lịch tốt nhất hiện có."
  },
  {
    "id": 83,
    "word": "available",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌvˈeɪlʌbʌl/",
    "meaning": "có sẵn",
    "ex1": "Before departure, map apps help travelers find places and choose the best travel routes available.",
    "ex1_vi": "Trước khi khởi hành, ứng dụng bản đồ giúp du khách tìm địa điểm và chọn những tuyến đường du lịch tốt nhất hiện có."
  },
  {
    "id": 84,
    "word": "translation",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trænzlˈeɪʃʌn/",
    "meaning": "dịch thuật",
    "ex1": "During a trip, translation apps help people communicate with local people in different countries more easily.",
    "ex1_vi": "Trong một chuyến đi, ứng dụng dịch thuật giúp mọi người giao tiếp dễ dàng hơn với người địa phương ở các quốc gia khác nhau."
  },
  {
    "id": 85,
    "word": "communicate",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌmjˈunʌkˌeɪt/",
    "meaning": "giao tiếp",
    "ex1": "For many travelers, translation apps help people communicate with local people in different countries more easily.",
    "ex1_vi": "Đối với nhiều du khách, ứng dụng dịch thuật giúp mọi người giao tiếp dễ dàng hơn với người địa phương ở các quốc gia khác nhau."
  },
  {
    "id": 86,
    "word": "local",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈoʊkʌl/",
    "meaning": "địa phương",
    "ex1": "In daily travel, translation apps help people communicate with local people in different countries more easily.",
    "ex1_vi": "Trong việc du lịch hằng ngày, ứng dụng dịch thuật giúp mọi người giao tiếp dễ dàng hơn với người địa phương ở các quốc gia khác nhau."
  },
  {
    "id": 87,
    "word": "in",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ɪn/",
    "meaning": "trong",
    "ex1": "While exploring, translation apps help people communicate with local people in different countries more easily.",
    "ex1_vi": "Khi khám phá, ứng dụng dịch thuật giúp mọi người giao tiếp dễ dàng hơn với người địa phương ở các quốc gia khác nhau."
  },
  {
    "id": 88,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "On a journey, translation apps help people communicate with local people in different countries more easily.",
    "ex1_vi": "Trong một hành trình, ứng dụng dịch thuật giúp mọi người giao tiếp dễ dàng hơn với người địa phương ở các quốc gia khác nhau."
  },
  {
    "id": 89,
    "word": "countries",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌntriz/",
    "meaning": "quốc gia",
    "ex1": "Before departure, translation apps help people communicate with local people in different countries more easily.",
    "ex1_vi": "Trước khi khởi hành, ứng dụng dịch thuật giúp mọi người giao tiếp dễ dàng hơn với người địa phương ở các quốc gia khác nhau."
  },
  {
    "id": 90,
    "word": "easily",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈizʌli/",
    "meaning": "dễ dàng",
    "ex1": "During careful planning, translation apps help people communicate with local people in different countries more easily.",
    "ex1_vi": "Trong quá trình lên kế hoạch cẩn thận, ứng dụng dịch thuật giúp mọi người giao tiếp dễ dàng hơn với người địa phương ở các quốc gia khác nhau."
  },
  {
    "id": 91,
    "word": "some",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌm/",
    "meaning": "một ít; một số",
    "ex1": "Some apps can book hotels, tickets, and activities with only a few touches.",
    "ex1_vi": "Một số ứng dụng có thể đặt khách sạn, vé và hoạt động chỉ với vài lần chạm."
  },
  {
    "id": 92,
    "word": "book",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈʊk/",
    "meaning": "đặt; sách",
    "ex1": "During a trip, some apps can book hotels, tickets, and activities with only a few touches.",
    "ex1_vi": "Trong một chuyến đi, một số ứng dụng có thể đặt khách sạn, vé và hoạt động chỉ với vài lần chạm."
  },
  {
    "id": 93,
    "word": "hotels",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hoʊtˈɛlz/",
    "meaning": "khách sạn",
    "ex1": "For many travelers, some apps can book hotels, tickets, and activities with only a few touches.",
    "ex1_vi": "Đối với nhiều du khách, một số ứng dụng có thể đặt khách sạn, vé và hoạt động chỉ với vài lần chạm."
  },
  {
    "id": 94,
    "word": "activities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/æktˈɪvʌtiz/",
    "meaning": "hoạt động",
    "ex1": "In daily travel, some apps can book hotels, tickets, and activities with only a few touches.",
    "ex1_vi": "Trong việc du lịch hằng ngày, một số ứng dụng có thể đặt khách sạn, vé và hoạt động chỉ với vài lần chạm."
  },
  {
    "id": 95,
    "word": "only",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈoʊnli/",
    "meaning": "chỉ",
    "ex1": "Some apps book hotels with only a few touches.",
    "ex1_vi": "Một số ứng dụng đặt khách sạn chỉ với vài lần chạm."
  },
  {
    "id": 96,
    "word": "few",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/fjˈu/",
    "meaning": "một vài",
    "ex1": "While exploring, some apps can book hotels, tickets, and activities with only a few touches.",
    "ex1_vi": "Khi khám phá, một số ứng dụng có thể đặt khách sạn, vé và hoạt động chỉ với vài lần chạm."
  },
  {
    "id": 97,
    "word": "touches",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈʌtʃʌz/",
    "meaning": "lần chạm",
    "ex1": "On a journey, some apps can book hotels, tickets, and activities with only a few touches.",
    "ex1_vi": "Trong một hành trình, một số ứng dụng có thể đặt khách sạn, vé và hoạt động chỉ với vài lần chạm."
  },
  {
    "id": 98,
    "word": "using",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzɪŋ/",
    "meaning": "sử dụng",
    "ex1": "During a trip, using travel apps makes trips safer, faster, and more convenient for everyone today.",
    "ex1_vi": "Trong một chuyến đi, việc sử dụng ứng dụng du lịch làm các chuyến đi an toàn hơn, nhanh hơn và thuận tiện hơn cho mọi người ngày nay."
  },
  {
    "id": 99,
    "word": "safer",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈeɪfɝ/",
    "meaning": "an toàn hơn",
    "ex1": "For many travelers, using travel apps makes trips safer, faster, and more convenient for everyone today.",
    "ex1_vi": "Đối với nhiều du khách, việc sử dụng ứng dụng du lịch làm các chuyến đi an toàn hơn, nhanh hơn và thuận tiện hơn cho mọi người ngày nay."
  },
  {
    "id": 100,
    "word": "faster",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæstɝ/",
    "meaning": "nhanh hơn",
    "ex1": "In daily travel, using travel apps makes trips safer, faster, and more convenient for everyone today.",
    "ex1_vi": "Trong việc du lịch hằng ngày, việc sử dụng ứng dụng du lịch làm các chuyến đi an toàn hơn, nhanh hơn và thuận tiện hơn cho mọi người ngày nay."
  },
  {
    "id": 101,
    "word": "convenient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kʌnvˈinjʌnt/",
    "meaning": "thuận tiện",
    "ex1": "While exploring, using travel apps makes trips safer, faster, and more convenient for everyone today.",
    "ex1_vi": "Khi khám phá, việc sử dụng ứng dụng du lịch làm các chuyến đi an toàn hơn, nhanh hơn và thuận tiện hơn cho mọi người ngày nay."
  },
  {
    "id": 102,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvriwˌʌn/",
    "meaning": "mọi người",
    "ex1": "On a journey, using travel apps makes trips safer, faster, and more convenient for everyone today.",
    "ex1_vi": "Trong một hành trình, việc sử dụng ứng dụng du lịch làm các chuyến đi an toàn hơn, nhanh hơn và thuận tiện hơn cho mọi người ngày nay."
  },
  {
    "id": 103,
    "word": "eco-friendly",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌiːkoʊ ˈfrɛndli/",
    "meaning": "thân thiện với môi trường",
    "ex1": "Eco-friendly travel protects nature and reduces plastic waste.",
    "ex1_vi": "Du lịch thân thiện với môi trường bảo vệ thiên nhiên và giảm rác thải nhựa."
  },
  {
    "id": 104,
    "word": "protect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌtˈɛkt/",
    "meaning": "bảo vệ",
    "ex1": "During a trip, responsible travelers try to reduce waste and protect nature during every journey.",
    "ex1_vi": "Trong một chuyến đi, những du khách có trách nhiệm cố gắng giảm rác thải và bảo vệ thiên nhiên trong mỗi hành trình."
  },
  {
    "id": 105,
    "word": "nature",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈeɪtʃɝ/",
    "meaning": "thiên nhiên",
    "ex1": "For many travelers, responsible travelers try to reduce waste and protect nature during every journey.",
    "ex1_vi": "Đối với nhiều du khách, những du khách có trách nhiệm cố gắng giảm rác thải và bảo vệ thiên nhiên trong mỗi hành trình."
  },
  {
    "id": 106,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "People learn about culture while exploring local markets.",
    "ex1_vi": "Mọi người tìm hiểu văn hóa khi khám phá các khu chợ địa phương."
  },
  {
    "id": 107,
    "word": "exploring",
    "type": "verb/gerund",
    "cat": "v",
    "phonetic": "/ɪksplˈɔrɪŋ/",
    "meaning": "khám phá",
    "ex1": "Exploring local places helps travelers understand culture better.",
    "ex1_vi": "Khám phá địa phương giúp du khách hiểu văn hóa tốt hơn."
  },
  {
    "id": 108,
    "word": "enjoyable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɛndʒˈɔɪʌbʌl/",
    "meaning": "thú vị; ngon",
    "ex1": "During a trip, traveling is enjoyable, but we should also care for our beautiful environment everywhere.",
    "ex1_vi": "Trong một chuyến đi, du lịch rất thú vị, nhưng chúng ta cũng nên quan tâm đến môi trường tươi đẹp ở khắp mọi nơi."
  },
  {
    "id": 109,
    "word": "but",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bˈʌt/",
    "meaning": "nhưng",
    "ex1": "Traveling is exciting, but safety remains very important.",
    "ex1_vi": "Du lịch rất thú vị, nhưng an toàn vẫn rất quan trọng."
  },
  {
    "id": 110,
    "word": "we",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/wˈi/",
    "meaning": "chúng ta",
    "ex1": "We learn new things when we travel abroad.",
    "ex1_vi": "Chúng ta học những điều mới khi đi du lịch nước ngoài."
  },
  {
    "id": 111,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "For many travelers, traveling is enjoyable, but we should also care for our beautiful environment everywhere.",
    "ex1_vi": "Đối với nhiều du khách, du lịch rất thú vị, nhưng chúng ta cũng nên quan tâm đến môi trường tươi đẹp ở khắp mọi nơi."
  },
  {
    "id": 112,
    "word": "care",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɛr/",
    "meaning": "sự chăm sóc; chăm sóc",
    "ex1": "In daily travel, traveling is enjoyable, but we should also care for our beautiful environment everywhere.",
    "ex1_vi": "Trong việc du lịch hằng ngày, du lịch rất thú vị, nhưng chúng ta cũng nên quan tâm đến môi trường tươi đẹp ở khắp mọi nơi."
  },
  {
    "id": 113,
    "word": "our",
    "type": "possessive determiner",
    "cat": "adj",
    "phonetic": "/ˈaʊɝ/",
    "meaning": "của chúng ta",
    "ex1": "Small actions by travelers can help keep our planet clean and beautiful always.",
    "ex1_vi": "Những hành động nhỏ của du khách có thể giúp giữ hành tinh của chúng ta luôn sạch và đẹp."
  },
  {
    "id": 114,
    "word": "beautiful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bjˈutʌfʌl/",
    "meaning": "đẹp",
    "ex1": "Small actions by travelers can help keep our planet clean and beautiful always.",
    "ex1_vi": "Những hành động nhỏ của du khách có thể giúp giữ hành tinh của chúng ta luôn sạch và đẹp."
  },
  {
    "id": 115,
    "word": "environment",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪnvˈaɪrʌnmʌnt/",
    "meaning": "môi trường",
    "ex1": "While exploring, traveling is enjoyable, but we should also care for our beautiful environment everywhere.",
    "ex1_vi": "Khi khám phá, du lịch rất thú vị, nhưng chúng ta cũng nên quan tâm đến môi trường tươi đẹp ở khắp mọi nơi."
  },
  {
    "id": 116,
    "word": "responsible",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rispˈɑnsʌbʌl/",
    "meaning": "có trách nhiệm",
    "ex1": "In daily travel, responsible travelers try to reduce waste and protect nature during every journey.",
    "ex1_vi": "Trong việc du lịch hằng ngày, những du khách có trách nhiệm cố gắng giảm rác thải và bảo vệ thiên nhiên trong mỗi hành trình."
  },
  {
    "id": 117,
    "word": "reduce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rʌdˈus/",
    "meaning": "giảm",
    "ex1": "While exploring, responsible travelers try to reduce waste and protect nature during every journey.",
    "ex1_vi": "Khi khám phá, những du khách có trách nhiệm cố gắng giảm rác thải và bảo vệ thiên nhiên trong mỗi hành trình."
  },
  {
    "id": 118,
    "word": "waste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪst/",
    "meaning": "rác thải; lãng phí",
    "ex1": "On a journey, responsible travelers try to reduce waste and protect nature during every journey.",
    "ex1_vi": "Trong một hành trình, những du khách có trách nhiệm cố gắng giảm rác thải và bảo vệ thiên nhiên trong mỗi hành trình."
  },
  {
    "id": 119,
    "word": "reusable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌriːˈjuːzəbəl/",
    "meaning": "tái sử dụng",
    "ex1": "For many travelers, use reusable bottles and bags instead of single-use plastic items whenever possible.",
    "ex1_vi": "Đối với nhiều du khách, hãy dùng chai và túi tái sử dụng thay cho các vật dụng nhựa dùng một lần bất cứ khi nào có thể."
  },
  {
    "id": 120,
    "word": "bottles",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɑtʌlz/",
    "meaning": "chai",
    "ex1": "In daily travel, use reusable bottles and bags instead of single-use plastic items whenever possible.",
    "ex1_vi": "Trong việc du lịch hằng ngày, hãy dùng chai và túi tái sử dụng thay cho các vật dụng nhựa dùng một lần bất cứ khi nào có thể."
  },
  {
    "id": 121,
    "word": "instead",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˌɪnstˈɛd/",
    "meaning": "thay vì",
    "ex1": "Use public transport instead of a private car when possible.",
    "ex1_vi": "Hãy dùng giao thông công cộng thay vì xe riêng khi có thể."
  },
  {
    "id": 122,
    "word": "single-use",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌsɪŋɡəl ˈjuːs/",
    "meaning": "dùng một lần",
    "ex1": "While exploring, use reusable bottles and bags instead of single-use plastic items whenever possible.",
    "ex1_vi": "Khi khám phá, hãy dùng chai và túi tái sử dụng thay cho các vật dụng nhựa dùng một lần bất cứ khi nào có thể."
  },
  {
    "id": 123,
    "word": "plastic",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/plˈæstɪk/",
    "meaning": "nhựa",
    "ex1": "On a journey, use reusable bottles and bags instead of single-use plastic items whenever possible.",
    "ex1_vi": "Trong một hành trình, hãy dùng chai và túi tái sử dụng thay cho các vật dụng nhựa dùng một lần bất cứ khi nào có thể."
  },
  {
    "id": 124,
    "word": "items",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪtʌmz/",
    "meaning": "vật dụng",
    "ex1": "Before departure, use reusable bottles and bags instead of single-use plastic items whenever possible.",
    "ex1_vi": "Trước khi khởi hành, hãy dùng chai và túi tái sử dụng thay cho các vật dụng nhựa dùng một lần bất cứ khi nào có thể."
  },
  {
    "id": 125,
    "word": "whenever",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wɛnˈɛvɝ/",
    "meaning": "bất cứ khi nào",
    "ex1": "Use a reusable bottle whenever clean water is available.",
    "ex1_vi": "Hãy dùng chai tái sử dụng bất cứ khi nào có nước sạch."
  },
  {
    "id": 126,
    "word": "possible",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑsʌbʌl/",
    "meaning": "có thể",
    "ex1": "During careful planning, use reusable bottles and bags instead of single-use plastic items whenever possible.",
    "ex1_vi": "Trong quá trình lên kế hoạch cẩn thận, hãy dùng chai và túi tái sử dụng thay cho các vật dụng nhựa dùng một lần bất cứ khi nào có thể."
  },
  {
    "id": 127,
    "word": "leave",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈiv/",
    "meaning": "rời đi",
    "ex1": "During a trip, do not leave rubbish behind and always respect animals, plants, and natural areas.",
    "ex1_vi": "Trong một chuyến đi, đừng để rác lại phía sau và luôn tôn trọng động vật, thực vật cùng các khu vực tự nhiên."
  },
  {
    "id": 128,
    "word": "rubbish",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈʌbɪʃ/",
    "meaning": "rác",
    "ex1": "For many travelers, do not leave rubbish behind and always respect animals, plants, and natural areas.",
    "ex1_vi": "Đối với nhiều du khách, đừng để rác lại phía sau và luôn tôn trọng động vật, thực vật cùng các khu vực tự nhiên."
  },
  {
    "id": 129,
    "word": "behind",
    "type": "adverb/preposition",
    "cat": "adv",
    "phonetic": "/bɪhˈaɪnd/",
    "meaning": "phía sau",
    "ex1": "In daily travel, do not leave rubbish behind and always respect animals, plants, and natural areas.",
    "ex1_vi": "Trong việc du lịch hằng ngày, đừng để rác lại phía sau và luôn tôn trọng động vật, thực vật cùng các khu vực tự nhiên."
  },
  {
    "id": 130,
    "word": "always",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlwˌeɪz/",
    "meaning": "luôn luôn",
    "ex1": "Solo travelers should always stay in regular contact.",
    "ex1_vi": "Người du lịch một mình nên luôn giữ liên lạc thường xuyên."
  },
  {
    "id": 131,
    "word": "respect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪspˈɛkt/",
    "meaning": "tôn trọng",
    "ex1": "Travelers respect local customs when visiting another country.",
    "ex1_vi": "Du khách tôn trọng phong tục địa phương khi đến một quốc gia khác."
  },
  {
    "id": 132,
    "word": "animals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈænʌmʌlz/",
    "meaning": "động vật",
    "ex1": "While exploring, do not leave rubbish behind and always respect animals, plants, and natural areas.",
    "ex1_vi": "Khi khám phá, đừng để rác lại phía sau và luôn tôn trọng động vật, thực vật cùng các khu vực tự nhiên."
  },
  {
    "id": 133,
    "word": "plants",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈænts/",
    "meaning": "thực vật",
    "ex1": "On a journey, do not leave rubbish behind and always respect animals, plants, and natural areas.",
    "ex1_vi": "Trong một hành trình, đừng để rác lại phía sau và luôn tôn trọng động vật, thực vật cùng các khu vực tự nhiên."
  },
  {
    "id": 134,
    "word": "natural",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈætʃɝʌl/",
    "meaning": "tự nhiên",
    "ex1": "Before departure, do not leave rubbish behind and always respect animals, plants, and natural areas.",
    "ex1_vi": "Trước khi khởi hành, đừng để rác lại phía sau và luôn tôn trọng động vật, thực vật cùng các khu vực tự nhiên."
  },
  {
    "id": 135,
    "word": "areas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛriʌz/",
    "meaning": "khu vực",
    "ex1": "During careful planning, do not leave rubbish behind and always respect animals, plants, and natural areas.",
    "ex1_vi": "Trong quá trình lên kế hoạch cẩn thận, đừng để rác lại phía sau và luôn tôn trọng động vật, thực vật cùng các khu vực tự nhiên."
  },
  {
    "id": 136,
    "word": "walking",
    "type": "gerund/noun",
    "cat": "n",
    "phonetic": "/wˈɔkɪŋ/",
    "meaning": "đi bộ",
    "ex1": "During a trip, walking, cycling, and public transport can reduce pollution and save energy too.",
    "ex1_vi": "Trong một chuyến đi, đi bộ, đạp xe và giao thông công cộng có thể giảm ô nhiễm và tiết kiệm năng lượng."
  },
  {
    "id": 137,
    "word": "cycling",
    "type": "gerund/noun",
    "cat": "n",
    "phonetic": "/sˈaɪkʌlɪŋ/",
    "meaning": "đạp xe",
    "ex1": "For many travelers, walking, cycling, and public transport can reduce pollution and save energy too.",
    "ex1_vi": "Đối với nhiều du khách, đi bộ, đạp xe và giao thông công cộng có thể giảm ô nhiễm và tiết kiệm năng lượng."
  },
  {
    "id": 138,
    "word": "public",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈʌblɪk/",
    "meaning": "công cộng",
    "ex1": "In daily travel, walking, cycling, and public transport can reduce pollution and save energy too.",
    "ex1_vi": "Trong việc du lịch hằng ngày, đi bộ, đạp xe và giao thông công cộng có thể giảm ô nhiễm và tiết kiệm năng lượng."
  },
  {
    "id": 139,
    "word": "transport",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trænspˈɔrt/",
    "meaning": "giao thông",
    "ex1": "While exploring, walking, cycling, and public transport can reduce pollution and save energy too.",
    "ex1_vi": "Khi khám phá, đi bộ, đạp xe và giao thông công cộng có thể giảm ô nhiễm và tiết kiệm năng lượng."
  },
  {
    "id": 140,
    "word": "pollution",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pʌlˈuʃʌn/",
    "meaning": "ô nhiễm",
    "ex1": "On a journey, walking, cycling, and public transport can reduce pollution and save energy too.",
    "ex1_vi": "Trong một hành trình, đi bộ, đạp xe và giao thông công cộng có thể giảm ô nhiễm và tiết kiệm năng lượng."
  },
  {
    "id": 141,
    "word": "energy",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛnɝdʒi/",
    "meaning": "năng lượng",
    "ex1": "Before departure, walking, cycling, and public transport can reduce pollution and save energy too.",
    "ex1_vi": "Trước khi khởi hành, đi bộ, đạp xe và giao thông công cộng có thể giảm ô nhiễm và tiết kiệm năng lượng."
  },
  {
    "id": 142,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "During a trip, small actions by travelers can help keep our planet clean and beautiful always.",
    "ex1_vi": "Trong một chuyến đi, những hành động nhỏ của du khách có thể giúp giữ hành tinh của chúng ta luôn sạch và đẹp."
  },
  {
    "id": 143,
    "word": "actions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈækʃʌnz/",
    "meaning": "hành động",
    "ex1": "For many travelers, small actions by travelers can help keep our planet clean and beautiful always.",
    "ex1_vi": "Đối với nhiều du khách, những hành động nhỏ của du khách có thể giúp giữ hành tinh của chúng ta luôn sạch và đẹp."
  },
  {
    "id": 144,
    "word": "by",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/bˈaɪ/",
    "meaning": "bằng; bởi",
    "ex1": "By planning early, travelers can save time and money.",
    "ex1_vi": "Bằng cách lên kế hoạch sớm, du khách có thể tiết kiệm thời gian và tiền."
  },
  {
    "id": 145,
    "word": "keep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈip/",
    "meaning": "giữ",
    "ex1": "In daily travel, small actions by travelers can help keep our planet clean and beautiful always.",
    "ex1_vi": "Trong việc du lịch hằng ngày, những hành động nhỏ của du khách có thể giúp giữ hành tinh của chúng ta luôn sạch và đẹp."
  },
  {
    "id": 146,
    "word": "planet",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈænʌt/",
    "meaning": "hành tinh",
    "ex1": "While exploring, small actions by travelers can help keep our planet clean and beautiful always.",
    "ex1_vi": "Khi khám phá, những hành động nhỏ của du khách có thể giúp giữ hành tinh của chúng ta luôn sạch và đẹp."
  },
  {
    "id": 147,
    "word": "clean",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈin/",
    "meaning": "sạch",
    "ex1": "On a journey, small actions by travelers can help keep our planet clean and beautiful always.",
    "ex1_vi": "Trong một hành trình, những hành động nhỏ của du khách có thể giúp giữ hành tinh của chúng ta luôn sạch và đẹp."
  }
];

const newReadingVocabOrder = [
  "packing",
  "essentials",
  "for",
  "travelers",
  "pack",
  "light",
  "travel",
  "right",
  "carefully",
  "can",
  "make",
  "your",
  "trip",
  "easier",
  "more",
  "comfortable",
  "and",
  "less",
  "stressful",
  "before",
  "traveling",
  "list",
  "of",
  "important",
  "things",
  "you",
  "need",
  "to",
  "bring",
  "with",
  "clothes",
  "weather",
  "do",
  "not",
  "forget",
  "passport",
  "tickets",
  "phone",
  "charger",
  "medicine",
  "water",
  "bottle",
  "convenience",
  "during",
  "try",
  "carry",
  "too",
  "many",
  "because",
  "heavy",
  "bags",
  "difficult",
  "move",
  "smart",
  "saves",
  "time",
  "gives",
  "freedom",
  "every",
  "journey",
  "apps",
  "should",
  "use",
  "technology",
  "makes",
  "today",
  "useful",
  "their",
  "trips",
  "better",
  "help",
  "people",
  "save",
  "find",
  "information",
  "quickly",
  "everywhere",
  "map",
  "places",
  "choose",
  "best",
  "routes",
  "available",
  "translation",
  "communicate",
  "local",
  "in",
  "different",
  "countries",
  "easily",
  "some",
  "book",
  "hotels",
  "activities",
  "only",
  "few",
  "touches",
  "using",
  "safer",
  "faster",
  "convenient",
  "everyone",
  "eco-friendly",
  "protect",
  "nature",
  "while",
  "exploring",
  "enjoyable",
  "but",
  "we",
  "also",
  "care",
  "our",
  "beautiful",
  "environment",
  "responsible",
  "reduce",
  "waste",
  "reusable",
  "bottles",
  "instead",
  "single-use",
  "plastic",
  "items",
  "whenever",
  "possible",
  "leave",
  "rubbish",
  "behind",
  "always",
  "respect",
  "animals",
  "plants",
  "natural",
  "areas",
  "walking",
  "cycling",
  "public",
  "transport",
  "pollution",
  "energy",
  "small",
  "actions",
  "by",
  "keep",
  "planet",
  "clean"
];
