const newEssayData = [
  {
    "text": "1. Traveling\nA Journey That Enriches the Soul\nTraveling is a wonderful journey of personal growth and global exploration. Every trip opens new doors, introducing us to unique cultures and breathtaking landscapes.\n\nBy stepping outside our comfort zones, we build independence and broaden our perspectives. Standing before vast oceans or majestic mountains, daily pressures simply fade away.\n\nTraveling also strengthens human connections, creating priceless memories with loved ones or kind strangers. We return home with a richer soul, not just beautiful photos.\n\nSo, pack your bags and explore the world whenever you can. The world is a book, and those who do not travel read only one page.",
    "vi": "1. Du lịch\nMột hành trình làm giàu tâm hồn\nDu lịch là một hành trình tuyệt vời của sự trưởng thành cá nhân và khám phá toàn cầu. Mỗi chuyến đi mở ra những cánh cửa mới, giới thiệu cho chúng ta các nền văn hóa độc đáo và những cảnh quan ngoạn mục.\n\nBằng cách bước ra khỏi vùng an toàn, chúng ta xây dựng tính tự lập và mở rộng góc nhìn. Khi đứng trước những đại dương bao la hoặc những ngọn núi hùng vĩ, áp lực hằng ngày dần tan biến.\n\nDu lịch cũng củng cố các mối kết nối giữa con người, tạo nên những kỷ niệm vô giá với người thân yêu hoặc những người lạ tốt bụng. Chúng ta trở về nhà với một tâm hồn phong phú hơn, chứ không chỉ là những bức ảnh đẹp.\n\nVì vậy, hãy xếp hành lý và khám phá thế giới bất cứ khi nào bạn có thể. Thế giới là một cuốn sách, và những ai không đi du lịch chỉ đọc một trang."
  },
  {
    "text": "2. How to Prepare for a Trip\nPlan Well, Travel Well\nA good trip starts with good planning. First, choose your destination and check the weather. Then book your hotel and buy your tickets early to save money.\n\nNext, pack your clothes, passport, phone charger, and some medicine. Right now, many people are using travel apps to find hotels and maps. They make traveling easier and safer.\n\nBefore you leave, tell your family about your trip. Bring some cash and keep your important documents in a safe place. Good preparation helps you enjoy every moment without worrying about unexpected problems.",
    "vi": "2. Cách chuẩn bị cho một chuyến đi\nLên kế hoạch tốt, du lịch tốt\nMột chuyến đi tốt bắt đầu bằng sự chuẩn bị tốt. Trước tiên, hãy chọn điểm đến và kiểm tra thời tiết. Sau đó đặt khách sạn và mua vé sớm để tiết kiệm tiền.\n\nTiếp theo, hãy xếp quần áo, hộ chiếu, bộ sạc điện thoại và một ít thuốc. Ngay lúc này, nhiều người đang sử dụng các ứng dụng du lịch để tìm khách sạn và bản đồ. Chúng làm cho việc du lịch dễ dàng và an toàn hơn.\n\nTrước khi rời đi, hãy nói với gia đình về chuyến đi của bạn. Mang theo một ít tiền mặt và giữ các giấy tờ quan trọng ở nơi an toàn. Sự chuẩn bị tốt giúp bạn tận hưởng từng khoảnh khắc mà không phải lo lắng về những vấn đề bất ngờ."
  },
  {
    "text": "3. Travel Safety Tips\nStay Safe, Travel Smart\nTraveling is exciting, but safety is very important for every traveler. Before your trip, learn about your destination and check local rules and weather conditions carefully.\n\nKeep your passport, money, and phone in a safe place at all times. Avoid carrying too much cash and be careful in crowded areas and busy streets.\n\nTell your family where you are going and save emergency numbers on your phone. Good safety habits help you enjoy your trip and avoid unexpected problems easily.",
    "vi": "3. Mẹo an toàn khi du lịch\nGiữ an toàn, du lịch thông minh\nDu lịch rất thú vị, nhưng an toàn rất quan trọng đối với mọi du khách. Trước chuyến đi, hãy tìm hiểu về điểm đến và kiểm tra kỹ các quy định địa phương cùng điều kiện thời tiết.\n\nGiữ hộ chiếu, tiền và điện thoại ở nơi an toàn mọi lúc. Tránh mang quá nhiều tiền mặt và hãy cẩn thận ở những khu vực đông người và đường phố nhộn nhịp.\n\nHãy cho gia đình biết bạn đang đi đâu và lưu các số khẩn cấp trong điện thoại. Những thói quen an toàn tốt giúp bạn tận hưởng chuyến đi và dễ dàng tránh các vấn đề bất ngờ."
  }
];
