const newEssayData = [
  {
    "text": "Chapter 1. The Front Yard\nThe front yard is the outdoor area in front of a house. It is usually located between the main entrance and the street. Some front yards are small, while others have enough space for trees, flowers, or a driveway.\n\nPeople often use the front yard to welcome visitors and make the house look attractive. It may contain a gate, a path, a lawn, or some decorative plants. In some homes, children can also play there.\n\nA clean front yard creates a good first impression. It should be kept tidy, safe, and free from rubbish. Plants and flowers can make this area more beautiful and welcoming.",
    "vi": "Chương 1. Sân trước\nSân trước là khu vực ngoài trời ở phía trước một ngôi nhà. Nó thường nằm giữa lối vào chính và đường phố. Một số sân trước nhỏ, trong khi những sân khác có đủ chỗ cho cây, hoa hoặc lối xe vào.\n\nMọi người thường dùng sân trước để chào đón khách và làm cho ngôi nhà trông hấp dẫn. Khu vực này có thể có cổng, lối đi, bãi cỏ hoặc một số cây trang trí. Ở một số ngôi nhà, trẻ em cũng có thể chơi ở đó.\n\nMột sân trước sạch sẽ tạo ấn tượng ban đầu tốt. Nó nên được giữ gọn gàng, an toàn và không có rác. Cây và hoa có thể làm khu vực này đẹp và thân thiện hơn."
  },
  {
    "text": "Chapter 2. The Backyard\nThe backyard is the outdoor space behind a house. It is usually more private than the front yard because it cannot be easily seen from the street. A fence often surrounds this area.\n\nMany families use the backyard for relaxing, gardening, or having meals outdoors. Children may play games there, and adults may grow vegetables or keep small plants. Some backyards also have tables, chairs, or a small swimming pool.\n\nA backyard gives people extra space for daily activities. It can be a quiet place to enjoy fresh air, sunshine, and time with family or friends.",
    "vi": "Chương 2. Sân sau\nSân sau là không gian ngoài trời phía sau một ngôi nhà. Nó thường riêng tư hơn sân trước vì không dễ nhìn thấy từ đường phố. Một hàng rào thường bao quanh khu vực này.\n\nNhiều gia đình dùng sân sau để thư giãn, làm vườn hoặc dùng bữa ngoài trời. Trẻ em có thể chơi trò chơi ở đó, và người lớn có thể trồng rau hoặc chăm những cây nhỏ. Một số sân sau cũng có bàn, ghế hoặc một hồ bơi nhỏ.\n\nSân sau cho mọi người thêm không gian cho các hoạt động hằng ngày. Nó có thể là nơi yên tĩnh để tận hưởng không khí trong lành, ánh nắng và thời gian bên gia đình hoặc bạn bè."
  },
  {
    "text": "Chapter 3. The Garden\nA garden is an area where flowers, trees, vegetables, or herbs are grown. It can be located in the front yard, backyard, beside the house, or even on a rooftop.\n\nGardens make a home look greener and more attractive. Flowers add color, while trees provide shade and fresh air. Vegetable gardens can also provide healthy food for a family.\n\nTaking care of a garden requires regular work. Plants need water, sunlight, and good soil. Weeds must be removed, and dry leaves should be cleaned. A well-kept garden creates a peaceful and pleasant environment around a house.",
    "vi": "Chương 3. Khu vườn\nKhu vườn là khu vực nơi hoa, cây, rau hoặc thảo mộc được trồng. Nó có thể nằm ở sân trước, sân sau, bên cạnh nhà hoặc thậm chí trên sân thượng.\n\nKhu vườn làm ngôi nhà trông xanh hơn và hấp dẫn hơn. Hoa thêm màu sắc, trong khi cây tạo bóng mát và không khí trong lành. Vườn rau cũng có thể cung cấp thực phẩm lành mạnh cho gia đình.\n\nChăm sóc khu vườn đòi hỏi công việc thường xuyên. Cây cần nước, ánh nắng và đất tốt. Cỏ dại phải được loại bỏ, và lá khô nên được dọn sạch. Một khu vườn được chăm sóc tốt tạo ra môi trường yên bình và dễ chịu quanh ngôi nhà."
  }
];
