const newEssayData = [
  {
    "text": "Chapter 4. The Hallway\nA hallway is a narrow space inside a house that connects different rooms. It is often located near the entrance or between the living room, bedrooms, kitchen, and bathroom.\n\nPeople walk through the hallway many times every day. It helps them move easily from one part of the house to another. Some hallways have pictures, mirrors, small tables, or lights on the walls.\n\nA hallway should be bright, clean, and free from unnecessary objects. Shoes, boxes, and furniture should not block the way. A clear hallway makes the house safer and more comfortable for everyone.",
    "vi": "Chương 4. Hành lang\nHành lang là một không gian hẹp bên trong ngôi nhà nối các phòng khác nhau. Nó thường nằm gần lối vào hoặc giữa phòng khách, phòng ngủ, bếp và phòng tắm.\n\nMọi người đi qua hành lang nhiều lần mỗi ngày. Nó giúp họ di chuyển dễ dàng từ phần này của ngôi nhà sang phần khác. Một số hành lang có tranh, gương, bàn nhỏ hoặc đèn trên tường.\n\nHành lang nên sáng, sạch và không có đồ vật không cần thiết. Giày, hộp và đồ nội thất không nên chặn lối đi. Một hành lang thông thoáng làm ngôi nhà an toàn và thoải mái hơn cho mọi người."
  },
  {
    "text": "Chapter 5. The Staircase\nA staircase is a group of steps that connects different floors of a house. It is usually located near the hallway, living room, or entrance. Some staircases are straight, while others are curved or turn at a corner.\n\nA staircase allows people to move between the lower and upper floors. It normally has a handrail to help people walk safely. Good lighting is also important, especially at night.\n\nStaircases should always be kept clear. Toys, shoes, and other objects can cause accidents. Strong steps, secure handrails, and careful walking make this area safer for children and adults.",
    "vi": "Chương 5. Cầu thang\nCầu thang là một nhóm bậc nối các tầng khác nhau của ngôi nhà. Nó thường nằm gần hành lang, phòng khách hoặc lối vào. Một số cầu thang thẳng, trong khi những cầu thang khác cong hoặc đổi hướng ở góc.\n\nCầu thang cho phép mọi người di chuyển giữa tầng dưới và tầng trên. Nó thường có tay vịn để giúp mọi người đi lại an toàn. Ánh sáng tốt cũng quan trọng, đặc biệt vào ban đêm.\n\nCầu thang luôn nên được giữ thông thoáng. Đồ chơi, giày và các vật khác có thể gây tai nạn. Bậc chắc chắn, tay vịn an toàn và việc đi lại cẩn thận làm khu vực này an toàn hơn cho trẻ em và người lớn."
  },
  {
    "text": "Chapter 6. The Entrance\nThe entrance is the main place where people enter or leave a house. It normally includes the front door, a gate, a small porch, or an entrance hall.\n\nVisitors usually see the entrance before any other part of the house. For this reason, it often creates the first impression. A welcome mat, plants, lights, or a clean door can make the area look friendly.\n\nThe entrance should be secure and easy to use. The door needs a strong lock, and the pathway should not be blocked. Good lighting helps people enter safely, especially during the evening or rainy weather.",
    "vi": "Chương 6. Lối vào\nLối vào là nơi chính mà mọi người đi vào hoặc rời khỏi một ngôi nhà. Nó thường gồm cửa trước, cổng, hiên nhỏ hoặc sảnh vào.\n\nKhách thường nhìn thấy lối vào trước bất kỳ phần nào khác của ngôi nhà. Vì lý do này, nó thường tạo ấn tượng đầu tiên. Thảm chào, cây, đèn hoặc một cánh cửa sạch có thể làm khu vực trông thân thiện.\n\nLối vào nên chắc chắn và dễ sử dụng. Cửa cần khóa chắc, và lối đi không nên bị chặn. Ánh sáng tốt giúp mọi người đi vào an toàn, đặc biệt vào buổi tối hoặc khi thời tiết mưa."
  }
];
