// ===== family02 VOCABULARY =====

const lessonVocabularyWords = [
  "healthy",
  "family",
  "meal",
  "provides",
  "nutrients",
  "body",
  "needs",
  "often",
  "includes",
  "rice",
  "vegetables",
  "fruits",
  "fish",
  "meat",
  "or",
  "eggs",
  "drinking",
  "enough",
  "water",
  "also",
  "important",
  "good",
  "health",
  "families",
  "should",
  "try",
  "eat",
  "fresh",
  "foods",
  "instead",
  "too",
  "much",
  "fast",
  "food",
  "ingredients",
  "contain",
  "vitamins",
  "and",
  "minerals",
  "help",
  "people",
  "stay",
  "strong",
  "active",
  "meals",
  "support",
  "growth",
  "improve",
  "overall",
  "well-being",
  "eating",
  "habits",
  "start",
  "home",
  "when",
  "parents",
  "choose",
  "children",
  "learn",
  "make",
  "better",
  "choices",
  "benefits",
  "every",
  "member",
  "talking",
  "dinner",
  "table",
  "place",
  "where",
  "can",
  "communicate",
  "while",
  "members",
  "talk",
  "about",
  "daily",
  "experiences",
  "plans",
  "ideas",
  "conversations",
  "life",
  "more",
  "enjoyable",
  "ask",
  "school",
  "friends",
  "advice",
  "listening",
  "carefully",
  "shows",
  "respect",
  "helps",
  "build",
  "stronger",
  "relationships",
  "creates",
  "friendly",
  "atmosphere",
  "feel",
  "comfortable",
  "sharing",
  "thoughts",
  "feelings",
  "regular",
  "connected",
  "one",
  "another",
  "traditional",
  "vietnamese",
  "simple",
  "balanced",
  "delicious",
  "typical",
  "soup",
  "dish",
  "provide",
  "nutrition",
  "reflect",
  "culture",
  "usually",
  "sit",
  "together",
  "share",
  "dishes",
  "placed",
  "center",
  "style",
  "encourages",
  "togetherness",
  "enjoy",
  "different",
  "flavors",
  "part",
  "vietnam",
  "bring",
  "preserve",
  "cultural",
  "values",
  "many",
  "continue",
  "tradition",
  "day"
];

const newVocabData = [
  {
    "id": 1,
    "word": "healthy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlθi/",
    "meaning": "lành mạnh",
    "ex1": "Healthy meals support growth and improve overall well-being.",
    "ex1_vi": "Những bữa ăn lành mạnh hỗ trợ sự phát triển và cải thiện sức khỏe tổng thể."
  },
  {
    "id": 2,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "Children learn about family through simple family activities.",
    "ex1_vi": "Trẻ em học về gia đình qua những hoạt động gia đình đơn giản."
  },
  {
    "id": 3,
    "word": "meal",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈil/",
    "meaning": "bữa ăn",
    "ex1": "A healthy family meal benefits every member of the family.",
    "ex1_vi": "Một bữa ăn gia đình lành mạnh mang lại lợi ích cho mọi thành viên trong gia đình."
  },
  {
    "id": 4,
    "word": "provides",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌvˈaɪdz/",
    "meaning": "cung cấp",
    "ex1": "A healthy family meal provides the nutrients that the body needs.",
    "ex1_vi": "Một bữa ăn gia đình lành mạnh cung cấp các chất dinh dưỡng mà cơ thể cần."
  },
  {
    "id": 5,
    "word": "nutrients",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈutriʌnts/",
    "meaning": "chất dinh dưỡng",
    "ex1": "A healthy family meal provides the nutrients that the body needs.",
    "ex1_vi": "Một bữa ăn gia đình lành mạnh cung cấp các chất dinh dưỡng mà cơ thể cần."
  },
  {
    "id": 6,
    "word": "body",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɑdi/",
    "meaning": "cơ thể",
    "ex1": "At home, families discuss body during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về cơ thể trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 7,
    "word": "needs",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈidz/",
    "meaning": "cần",
    "ex1": "At home, families discuss needs during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về cần trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 8,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "It often includes rice, vegetables, fruits, fish, meat, or eggs.",
    "ex1_vi": "Bữa ăn thường gồm cơm, rau, trái cây, cá, thịt hoặc trứng."
  },
  {
    "id": 9,
    "word": "includes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪnklˈudz/",
    "meaning": "bao gồm",
    "ex1": "It often includes rice, vegetables, fruits, fish, meat, or eggs.",
    "ex1_vi": "Bữa ăn thường gồm cơm, rau, trái cây, cá, thịt hoặc trứng."
  },
  {
    "id": 10,
    "word": "rice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪs/",
    "meaning": "cơm; gạo",
    "ex1": "At home, families discuss rice during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về cơm; gạo trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 11,
    "word": "vegetables",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɛdʒtʌbʌlz/",
    "meaning": "rau",
    "ex1": "At home, families discuss vegetables during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về rau trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 12,
    "word": "fruits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈuts/",
    "meaning": "trái cây",
    "ex1": "At home, families discuss fruits during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về trái cây trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 13,
    "word": "fish",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɪʃ/",
    "meaning": "cá",
    "ex1": "At home, families discuss fish during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về cá trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 14,
    "word": "meat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈit/",
    "meaning": "thịt",
    "ex1": "At home, families discuss meat during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về thịt trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 15,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "At home, families discuss or during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về hoặc trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 16,
    "word": "eggs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛɡz/",
    "meaning": "trứng",
    "ex1": "At home, families discuss eggs during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về trứng trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 17,
    "word": "drinking",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɪŋkɪŋ/",
    "meaning": "việc uống",
    "ex1": "Drinking enough water is also important for good health.",
    "ex1_vi": "Uống đủ nước cũng quan trọng đối với sức khỏe tốt."
  },
  {
    "id": 18,
    "word": "enough",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ɪnˈʌf/",
    "meaning": "đủ",
    "ex1": "Drinking enough water is also important for good health.",
    "ex1_vi": "Uống đủ nước cũng quan trọng đối với sức khỏe tốt."
  },
  {
    "id": 19,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước",
    "ex1": "At home, families discuss water during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về nước trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 20,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "At home, families discuss also during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về cũng trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 21,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔrtʌnt/",
    "meaning": "quan trọng",
    "ex1": "At home, families discuss important during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về quan trọng trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 22,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "This family activity feels good during a relaxed evening.",
    "ex1_vi": "Hoạt động gia đình này mang cảm giác tốt trong một buổi tối thư giãn."
  },
  {
    "id": 23,
    "word": "health",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛlθ/",
    "meaning": "sức khỏe",
    "ex1": "At home, families discuss health during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về sức khỏe trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 24,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌliz/",
    "meaning": "các gia đình",
    "ex1": "Family members talk about families during relaxed meals together.",
    "ex1_vi": "Các thành viên gia đình nói về các gia đình trong những bữa ăn thư giãn cùng nhau."
  },
  {
    "id": 25,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "Families should choose fresh food for healthy meals.",
    "ex1_vi": "Các gia đình nên chọn thực phẩm tươi cho những bữa ăn lành mạnh."
  },
  {
    "id": 26,
    "word": "try",
    "type": "verb",
    "cat": "v",
    "phonetic": "/trˈaɪ/",
    "meaning": "cố gắng",
    "ex1": "Parents often try together while preparing a family meal.",
    "ex1_vi": "Cha mẹ thường cố gắng cùng nhau khi chuẩn bị một bữa ăn gia đình."
  },
  {
    "id": 27,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "Everyone can eat during warm and meaningful family time.",
    "ex1_vi": "Mọi người có thể ăn trong khoảng thời gian gia đình ấm áp và ý nghĩa."
  },
  {
    "id": 28,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi",
    "ex1": "A family meal can feel fresh when everyone joins.",
    "ex1_vi": "Một bữa ăn gia đình có thể mang cảm giác tươi khi mọi người cùng tham gia."
  },
  {
    "id": 29,
    "word": "foods",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈudz/",
    "meaning": "thực phẩm",
    "ex1": "These foods provide nutrition and reflect Vietnamese culture.",
    "ex1_vi": "Những thực phẩm này cung cấp dinh dưỡng và phản ánh văn hóa Việt Nam."
  },
  {
    "id": 30,
    "word": "instead",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˌɪnstˈɛd/",
    "meaning": "thay vào đó",
    "ex1": "Families choose fresh food instead of fast food.",
    "ex1_vi": "Các gia đình chọn thực phẩm tươi thay vì thức ăn nhanh."
  },
  {
    "id": 31,
    "word": "too",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tˈu/",
    "meaning": "quá",
    "ex1": "Families too prepare simple meals and eat together.",
    "ex1_vi": "Các gia đình quá chuẩn bị những bữa ăn đơn giản và ăn cùng nhau."
  },
  {
    "id": 32,
    "word": "much",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈʌtʃ/",
    "meaning": "nhiều",
    "ex1": "Much families enjoy simple meals together at home each day.",
    "ex1_vi": "Nhiều gia đình thưởng thức những bữa ăn đơn giản cùng nhau ở nhà mỗi ngày."
  },
  {
    "id": 33,
    "word": "fast",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈæst/",
    "meaning": "nhanh",
    "ex1": "Good family time is often fast for children and parents.",
    "ex1_vi": "Khoảng thời gian gia đình tốt thường nhanh đối với trẻ em và cha mẹ."
  },
  {
    "id": 34,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thức ăn",
    "ex1": "When parents choose healthy foods, children learn to make better food choices.",
    "ex1_vi": "Khi cha mẹ chọn thực phẩm lành mạnh, trẻ em học cách đưa ra lựa chọn thực phẩm tốt hơn."
  },
  {
    "id": 35,
    "word": "ingredients",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnɡrˈidiʌnts/",
    "meaning": "nguyên liệu",
    "ex1": "Parents discuss ingredients during everyday conversations at home.",
    "ex1_vi": "Cha mẹ thảo luận về nguyên liệu trong những cuộc trò chuyện hằng ngày ở nhà."
  },
  {
    "id": 36,
    "word": "contain",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈeɪn/",
    "meaning": "chứa",
    "ex1": "Family members contain together during a relaxed evening meal.",
    "ex1_vi": "Các thành viên gia đình chứa cùng nhau trong một bữa tối thư giãn."
  },
  {
    "id": 37,
    "word": "vitamins",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈaɪtʌmʌnz/",
    "meaning": "vitamin",
    "ex1": "A warm family dinner can include vitamins in daily life.",
    "ex1_vi": "Một bữa tối gia đình ấm áp có thể bao gồm vitamin trong cuộc sống hằng ngày."
  },
  {
    "id": 38,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Healthy meals support growth and improve overall well-being.",
    "ex1_vi": "Những bữa ăn lành mạnh hỗ trợ sự phát triển và cải thiện sức khỏe tổng thể."
  },
  {
    "id": 39,
    "word": "minerals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɪnɝʌlz/",
    "meaning": "khoáng chất",
    "ex1": "Parents discuss minerals during everyday conversations at home.",
    "ex1_vi": "Cha mẹ thảo luận về khoáng chất trong những cuộc trò chuyện hằng ngày ở nhà."
  },
  {
    "id": 40,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "They bring people together and help preserve cultural values.",
    "ex1_vi": "Chúng mang mọi người lại gần nhau và giúp gìn giữ các giá trị văn hóa."
  },
  {
    "id": 41,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "They bring people together and help preserve cultural values.",
    "ex1_vi": "Chúng mang mọi người lại gần nhau và giúp gìn giữ các giá trị văn hóa."
  },
  {
    "id": 42,
    "word": "stay",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈeɪ/",
    "meaning": "duy trì; ở lại",
    "ex1": "Regular conversations help families stay connected and support one another.",
    "ex1_vi": "Những cuộc trò chuyện thường xuyên giúp các gia đình luôn gắn kết và hỗ trợ lẫn nhau."
  },
  {
    "id": 43,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋ/",
    "meaning": "khỏe; mạnh",
    "ex1": "Shared meals can make home life feel strong.",
    "ex1_vi": "Những bữa ăn chung có thể làm cuộc sống gia đình trở nên khỏe; mạnh."
  },
  {
    "id": 44,
    "word": "active",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈæktɪv/",
    "meaning": "năng động",
    "ex1": "A family meal can feel active when everyone joins.",
    "ex1_vi": "Một bữa ăn gia đình có thể mang cảm giác năng động khi mọi người cùng tham gia."
  },
  {
    "id": 45,
    "word": "meals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈilz/",
    "meaning": "các bữa ăn",
    "ex1": "A warm family dinner can include meals in daily life.",
    "ex1_vi": "Một bữa tối gia đình ấm áp có thể bao gồm các bữa ăn trong cuộc sống hằng ngày."
  },
  {
    "id": 46,
    "word": "support",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sʌpˈɔrt/",
    "meaning": "hỗ trợ",
    "ex1": "At home, families discuss support during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về hỗ trợ trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 47,
    "word": "growth",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡrˈoʊθ/",
    "meaning": "sự phát triển",
    "ex1": "At home, families discuss growth during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về sự phát triển trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 48,
    "word": "improve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪmprˈuv/",
    "meaning": "cải thiện",
    "ex1": "At home, families discuss improve during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về cải thiện trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 49,
    "word": "overall",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈoʊvɝˌɔl/",
    "meaning": "tổng thể",
    "ex1": "At home, families discuss overall during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về tổng thể trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 50,
    "word": "well-being",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌwɛlˈbiːɪŋ/",
    "meaning": "sức khỏe và trạng thái tốt",
    "ex1": "At home, families discuss well-being during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về sức khỏe và trạng thái tốt trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 51,
    "word": "eating",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈitɪŋ/",
    "meaning": "việc ăn",
    "ex1": "Parents discuss eating during everyday conversations at home.",
    "ex1_vi": "Cha mẹ thảo luận về việc ăn trong những cuộc trò chuyện hằng ngày ở nhà."
  },
  {
    "id": 52,
    "word": "habits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈæbʌts/",
    "meaning": "thói quen",
    "ex1": "Family members talk about habits during relaxed meals together.",
    "ex1_vi": "Các thành viên gia đình nói về thói quen trong những bữa ăn thư giãn cùng nhau."
  },
  {
    "id": 53,
    "word": "start",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈɑrt/",
    "meaning": "bắt đầu",
    "ex1": "Children can start at home during simple family activities.",
    "ex1_vi": "Trẻ em có thể bắt đầu ở nhà trong các hoạt động gia đình đơn giản."
  },
  {
    "id": 54,
    "word": "home",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊm/",
    "meaning": "gia đình; nhà",
    "ex1": "Children learn about home through simple family activities.",
    "ex1_vi": "Trẻ em học về gia đình; nhà qua những hoạt động gia đình đơn giản."
  },
  {
    "id": 55,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "When parents choose healthy foods, children learn to make better food choices.",
    "ex1_vi": "Khi cha mẹ chọn thực phẩm lành mạnh, trẻ em học cách đưa ra lựa chọn thực phẩm tốt hơn."
  },
  {
    "id": 56,
    "word": "parents",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɛrʌnts/",
    "meaning": "cha mẹ",
    "ex1": "Parents can ask children about school and their friends.",
    "ex1_vi": "Cha mẹ có thể hỏi trẻ về trường học và bạn bè."
  },
  {
    "id": 57,
    "word": "choose",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈuz/",
    "meaning": "chọn",
    "ex1": "At home, families discuss choose during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về chọn trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 58,
    "word": "children",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪldrʌn/",
    "meaning": "trẻ em; con cái",
    "ex1": "Parents can ask children about school and their friends.",
    "ex1_vi": "Cha mẹ có thể hỏi trẻ về trường học và bạn bè."
  },
  {
    "id": 59,
    "word": "learn",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɝn/",
    "meaning": "học",
    "ex1": "Children can learn from their parents' advice and experiences.",
    "ex1_vi": "Trẻ em có thể học từ lời khuyên và trải nghiệm của cha mẹ."
  },
  {
    "id": 60,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm",
    "ex1": "Family members make together during a relaxed evening meal.",
    "ex1_vi": "Các thành viên gia đình làm cùng nhau trong một bữa tối thư giãn."
  },
  {
    "id": 61,
    "word": "better",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/bˈɛtɝ/",
    "meaning": "tốt hơn",
    "ex1": "At home, families discuss better during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về tốt hơn trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 62,
    "word": "choices",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɔɪsʌz/",
    "meaning": "lựa chọn",
    "ex1": "At home, families discuss choices during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về lựa chọn trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 63,
    "word": "benefits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɛnʌfɪts/",
    "meaning": "mang lại lợi ích",
    "ex1": "A healthy family meal benefits every member of the family.",
    "ex1_vi": "Một bữa ăn gia đình lành mạnh mang lại lợi ích cho mọi thành viên trong gia đình."
  },
  {
    "id": 64,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɝi/",
    "meaning": "mỗi",
    "ex1": "Every families enjoy simple meals together at home each day.",
    "ex1_vi": "Mỗi gia đình thưởng thức những bữa ăn đơn giản cùng nhau ở nhà mỗi ngày."
  },
  {
    "id": 65,
    "word": "member",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛmbɝ/",
    "meaning": "thành viên",
    "ex1": "At home, families discuss member during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về thành viên trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 66,
    "word": "talking",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/tˈɔkɪŋ/",
    "meaning": "việc trò chuyện",
    "ex1": "Children learn about talking through simple family activities.",
    "ex1_vi": "Trẻ em học về việc trò chuyện qua những hoạt động gia đình đơn giản."
  },
  {
    "id": 67,
    "word": "dinner",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪnɝ/",
    "meaning": "bữa tối",
    "ex1": "The dinner table is a place where families can communicate.",
    "ex1_vi": "Bàn ăn là nơi các gia đình có thể giao tiếp."
  },
  {
    "id": 68,
    "word": "table",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪbʌl/",
    "meaning": "bàn",
    "ex1": "The dinner table is a place where families can communicate.",
    "ex1_vi": "Bàn ăn là nơi các gia đình có thể giao tiếp."
  },
  {
    "id": 69,
    "word": "place",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪs/",
    "meaning": "nơi",
    "ex1": "At home, families discuss place during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về nơi trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 70,
    "word": "where",
    "type": "adverb/conjunction",
    "cat": "adv",
    "phonetic": "/wˈɛr/",
    "meaning": "nơi mà",
    "ex1": "At home, families discuss where during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về nơi mà trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 71,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "At home, families discuss can during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về có thể trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 72,
    "word": "communicate",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌmjˈunʌkˌeɪt/",
    "meaning": "giao tiếp",
    "ex1": "At home, families discuss communicate during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về giao tiếp trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 73,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "Children talk while parents prepare food for dinner.",
    "ex1_vi": "Trẻ em trò chuyện trong khi cha mẹ chuẩn bị thức ăn cho bữa tối."
  },
  {
    "id": 74,
    "word": "members",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛmbɝz/",
    "meaning": "các thành viên",
    "ex1": "Family members feel comfortable sharing their thoughts and feelings.",
    "ex1_vi": "Các thành viên gia đình cảm thấy thoải mái khi chia sẻ suy nghĩ và cảm xúc."
  },
  {
    "id": 75,
    "word": "talk",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈɔk/",
    "meaning": "nói chuyện",
    "ex1": "Everyone can talk during warm and meaningful family time.",
    "ex1_vi": "Mọi người có thể nói chuyện trong khoảng thời gian gia đình ấm áp và ý nghĩa."
  },
  {
    "id": 76,
    "word": "about",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ʌbˈaʊt/",
    "meaning": "về",
    "ex1": "At home, families discuss about during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về về trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 77,
    "word": "daily",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈeɪli/",
    "meaning": "hằng ngày",
    "ex1": "Good family time is often daily for children and parents.",
    "ex1_vi": "Khoảng thời gian gia đình tốt thường hằng ngày đối với trẻ em và cha mẹ."
  },
  {
    "id": 78,
    "word": "experiences",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪkspˈɪriʌnsɪz/",
    "meaning": "trải nghiệm",
    "ex1": "Children can learn from their parents' advice and experiences.",
    "ex1_vi": "Trẻ em có thể học từ lời khuyên và trải nghiệm của cha mẹ."
  },
  {
    "id": 79,
    "word": "plans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈænz/",
    "meaning": "kế hoạch",
    "ex1": "Parents discuss plans during everyday conversations at home.",
    "ex1_vi": "Cha mẹ thảo luận về kế hoạch trong những cuộc trò chuyện hằng ngày ở nhà."
  },
  {
    "id": 80,
    "word": "ideas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/aɪdˈiʌz/",
    "meaning": "ý tưởng",
    "ex1": "Family members talk about ideas during relaxed meals together.",
    "ex1_vi": "Các thành viên gia đình nói về ý tưởng trong những bữa ăn thư giãn cùng nhau."
  },
  {
    "id": 81,
    "word": "conversations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˌɑnvɝsˈeɪʃʌnz/",
    "meaning": "các cuộc trò chuyện",
    "ex1": "A warm family dinner can include conversations in daily life.",
    "ex1_vi": "Một bữa tối gia đình ấm áp có thể bao gồm các cuộc trò chuyện trong cuộc sống hằng ngày."
  },
  {
    "id": 82,
    "word": "life",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪf/",
    "meaning": "cuộc sống",
    "ex1": "Children learn about life through simple family activities.",
    "ex1_vi": "Trẻ em học về cuộc sống qua những hoạt động gia đình đơn giản."
  },
  {
    "id": 83,
    "word": "more",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "hơn; nhiều hơn",
    "ex1": "More children learn good habits from regular family meals.",
    "ex1_vi": "Hơn; nhiều hơn trẻ em học thói quen tốt từ những bữa ăn gia đình thường xuyên."
  },
  {
    "id": 84,
    "word": "enjoyable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɛndʒˈɔɪʌbʌl/",
    "meaning": "thú vị",
    "ex1": "A family meal can feel enjoyable when everyone joins.",
    "ex1_vi": "Một bữa ăn gia đình có thể mang cảm giác thú vị khi mọi người cùng tham gia."
  },
  {
    "id": 85,
    "word": "ask",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈæsk/",
    "meaning": "hỏi",
    "ex1": "At home, families discuss ask during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về hỏi trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 86,
    "word": "school",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈul/",
    "meaning": "trường học",
    "ex1": "At home, families discuss school during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về trường học trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 87,
    "word": "friends",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈɛndz/",
    "meaning": "bạn bè",
    "ex1": "At home, families discuss friends during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về bạn bè trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 88,
    "word": "advice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ædvˈaɪs/",
    "meaning": "lời khuyên",
    "ex1": "At home, families discuss advice during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về lời khuyên trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 89,
    "word": "listening",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/lˈɪsʌnɪŋ/",
    "meaning": "việc lắng nghe",
    "ex1": "Listening carefully shows respect and helps build stronger relationships.",
    "ex1_vi": "Lắng nghe cẩn thận thể hiện sự tôn trọng và giúp xây dựng các mối quan hệ bền chặt hơn."
  },
  {
    "id": 90,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "Listening carefully shows respect and helps build stronger relationships.",
    "ex1_vi": "Lắng nghe cẩn thận thể hiện sự tôn trọng và giúp xây dựng các mối quan hệ bền chặt hơn."
  },
  {
    "id": 91,
    "word": "shows",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈoʊz/",
    "meaning": "thể hiện",
    "ex1": "At home, families discuss shows during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về thể hiện trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 92,
    "word": "respect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪspˈɛkt/",
    "meaning": "sự tôn trọng",
    "ex1": "At home, families discuss respect during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về sự tôn trọng trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 93,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "At home, families discuss helps during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về giúp trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 94,
    "word": "build",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɪld/",
    "meaning": "xây dựng",
    "ex1": "At home, families discuss build during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về xây dựng trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 95,
    "word": "stronger",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋɝ/",
    "meaning": "bền chặt hơn",
    "ex1": "At home, families discuss stronger during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về bền chặt hơn trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 96,
    "word": "relationships",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rɪˈleɪʃənˌʃɪps/",
    "meaning": "các mối quan hệ",
    "ex1": "At home, families discuss relationships during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về các mối quan hệ trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 97,
    "word": "creates",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪts/",
    "meaning": "tạo ra",
    "ex1": "Children can creates at home during simple family activities.",
    "ex1_vi": "Trẻ em có thể tạo ra ở nhà trong các hoạt động gia đình đơn giản."
  },
  {
    "id": 98,
    "word": "friendly",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛndli/",
    "meaning": "thân thiện",
    "ex1": "This family activity feels friendly during a relaxed evening.",
    "ex1_vi": "Hoạt động gia đình này mang cảm giác thân thiện trong một buổi tối thư giãn."
  },
  {
    "id": 99,
    "word": "atmosphere",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈætmʌsfˌɪr/",
    "meaning": "bầu không khí",
    "ex1": "Parents discuss atmosphere during everyday conversations at home.",
    "ex1_vi": "Cha mẹ thảo luận về bầu không khí trong những cuộc trò chuyện hằng ngày ở nhà."
  },
  {
    "id": 100,
    "word": "feel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈil/",
    "meaning": "cảm thấy",
    "ex1": "Family members feel comfortable sharing their thoughts and feelings.",
    "ex1_vi": "Các thành viên gia đình cảm thấy thoải mái khi chia sẻ suy nghĩ và cảm xúc."
  },
  {
    "id": 101,
    "word": "comfortable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌmfɝtʌbʌl/",
    "meaning": "thoải mái",
    "ex1": "At home, families discuss comfortable during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về thoải mái trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 102,
    "word": "sharing",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/ʃˈɛrɪŋ/",
    "meaning": "việc chia sẻ",
    "ex1": "This style of eating encourages sharing and togetherness.",
    "ex1_vi": "Kiểu ăn này khuyến khích sự chia sẻ và tinh thần gắn bó."
  },
  {
    "id": 103,
    "word": "thoughts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈɔts/",
    "meaning": "suy nghĩ",
    "ex1": "At home, families discuss thoughts during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về suy nghĩ trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 104,
    "word": "feelings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈilɪŋz/",
    "meaning": "cảm xúc",
    "ex1": "At home, families discuss feelings during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về cảm xúc trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 105,
    "word": "regular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛɡjʌlɝ/",
    "meaning": "thường xuyên",
    "ex1": "Regular conversations help families stay connected and support one another.",
    "ex1_vi": "Những cuộc trò chuyện thường xuyên giúp các gia đình luôn gắn kết và hỗ trợ lẫn nhau."
  },
  {
    "id": 106,
    "word": "connected",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌnˈɛktɪd/",
    "meaning": "gắn kết",
    "ex1": "At home, families discuss connected during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về gắn kết trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 107,
    "word": "one",
    "type": "number",
    "cat": "adj",
    "phonetic": "/wˈʌn/",
    "meaning": "một",
    "ex1": "At home, families discuss one during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về một trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 108,
    "word": "another",
    "type": "pronoun/determiner",
    "cat": "n",
    "phonetic": "/ʌnˈʌðɝ/",
    "meaning": "người/cái khác",
    "ex1": "At home, families discuss another during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về người/cái khác trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 109,
    "word": "traditional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trʌdˈɪʃʌnʌl/",
    "meaning": "truyền thống",
    "ex1": "Traditional Vietnamese family meals are simple, balanced, and delicious.",
    "ex1_vi": "Những bữa ăn gia đình truyền thống Việt Nam đơn giản, cân bằng và ngon miệng."
  },
  {
    "id": 110,
    "word": "vietnamese",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/viˌɛtnɑmˈis/",
    "meaning": "thuộc Việt Nam; người Việt Nam",
    "ex1": "These foods provide nutrition and reflect Vietnamese culture.",
    "ex1_vi": "Những thực phẩm này cung cấp dinh dưỡng và phản ánh văn hóa Việt Nam."
  },
  {
    "id": 111,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "Traditional Vietnamese family meals are simple, balanced, and delicious.",
    "ex1_vi": "Những bữa ăn gia đình truyền thống Việt Nam đơn giản, cân bằng và ngon miệng."
  },
  {
    "id": 112,
    "word": "balanced",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈælʌnst/",
    "meaning": "cân bằng",
    "ex1": "At home, families discuss balanced during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về cân bằng trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 113,
    "word": "delicious",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dɪlˈɪʃʌs/",
    "meaning": "ngon",
    "ex1": "At home, families discuss delicious during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về ngon trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 114,
    "word": "typical",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈɪpʌkʌl/",
    "meaning": "điển hình",
    "ex1": "This family activity feels typical during a relaxed evening.",
    "ex1_vi": "Hoạt động gia đình này mang cảm giác điển hình trong một buổi tối thư giãn."
  },
  {
    "id": 115,
    "word": "soup",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈup/",
    "meaning": "canh; súp",
    "ex1": "Parents discuss soup during everyday conversations at home.",
    "ex1_vi": "Cha mẹ thảo luận về canh; súp trong những cuộc trò chuyện hằng ngày ở nhà."
  },
  {
    "id": 116,
    "word": "dish",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪʃ/",
    "meaning": "món ăn",
    "ex1": "Family members talk about dish during relaxed meals together.",
    "ex1_vi": "Các thành viên gia đình nói về món ăn trong những bữa ăn thư giãn cùng nhau."
  },
  {
    "id": 117,
    "word": "provide",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌvˈaɪd/",
    "meaning": "cung cấp",
    "ex1": "At home, families discuss provide during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về cung cấp trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 118,
    "word": "nutrition",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nutrˈɪʃʌn/",
    "meaning": "dinh dưỡng",
    "ex1": "At home, families discuss nutrition during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về dinh dưỡng trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 119,
    "word": "reflect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪflˈɛkt/",
    "meaning": "phản ánh",
    "ex1": "At home, families discuss reflect during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về phản ánh trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 120,
    "word": "culture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌltʃɝ/",
    "meaning": "văn hóa",
    "ex1": "At home, families discuss culture during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về văn hóa trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 121,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "Parents and children usually share ideas during family meals.",
    "ex1_vi": "Cha mẹ và con cái thường chia sẻ ý tưởng trong các bữa ăn gia đình."
  },
  {
    "id": 122,
    "word": "sit",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɪt/",
    "meaning": "ngồi",
    "ex1": "Parents often sit together while preparing a family meal.",
    "ex1_vi": "Cha mẹ thường ngồi cùng nhau khi chuẩn bị một bữa ăn gia đình."
  },
  {
    "id": 123,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌɡˈɛðɝ/",
    "meaning": "cùng nhau",
    "ex1": "At home, families discuss together during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về cùng nhau trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 124,
    "word": "share",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈɛr/",
    "meaning": "chia sẻ",
    "ex1": "Family members share together during a relaxed evening meal.",
    "ex1_vi": "Các thành viên gia đình chia sẻ cùng nhau trong một bữa tối thư giãn."
  },
  {
    "id": 125,
    "word": "dishes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪʃʌz/",
    "meaning": "món ăn",
    "ex1": "A warm family dinner can include dishes in daily life.",
    "ex1_vi": "Một bữa tối gia đình ấm áp có thể bao gồm món ăn trong cuộc sống hằng ngày."
  },
  {
    "id": 126,
    "word": "placed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪst/",
    "meaning": "được đặt",
    "ex1": "Parents often placed together while preparing a family meal.",
    "ex1_vi": "Cha mẹ thường được đặt cùng nhau khi chuẩn bị một bữa ăn gia đình."
  },
  {
    "id": 127,
    "word": "center",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛntɝ/",
    "meaning": "giữa; trung tâm",
    "ex1": "Parents discuss center during everyday conversations at home.",
    "ex1_vi": "Cha mẹ thảo luận về giữa; trung tâm trong những cuộc trò chuyện hằng ngày ở nhà."
  },
  {
    "id": 128,
    "word": "style",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈaɪl/",
    "meaning": "kiểu",
    "ex1": "This style of eating encourages sharing and togetherness.",
    "ex1_vi": "Kiểu ăn này khuyến khích sự chia sẻ và tinh thần gắn bó."
  },
  {
    "id": 129,
    "word": "encourages",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɛnkˈɝɪdʒɪz/",
    "meaning": "khuyến khích",
    "ex1": "At home, families discuss encourages during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về khuyến khích trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 130,
    "word": "togetherness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/təˈɡɛðərnəs/",
    "meaning": "sự gắn bó",
    "ex1": "At home, families discuss togetherness during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về sự gắn bó trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 131,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thưởng thức",
    "ex1": "It also helps people enjoy different flavors in one meal.",
    "ex1_vi": "Nó cũng giúp mọi người thưởng thức nhiều hương vị khác nhau trong một bữa ăn."
  },
  {
    "id": 132,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "It also helps people enjoy different flavors in one meal.",
    "ex1_vi": "Nó cũng giúp mọi người thưởng thức nhiều hương vị khác nhau trong một bữa ăn."
  },
  {
    "id": 133,
    "word": "flavors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝz/",
    "meaning": "hương vị",
    "ex1": "At home, families discuss flavors during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về hương vị trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 134,
    "word": "part",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrt/",
    "meaning": "phần",
    "ex1": "Traditional meals are an important part of family life in Vietnam.",
    "ex1_vi": "Những bữa ăn truyền thống là một phần quan trọng của đời sống gia đình ở Việt Nam."
  },
  {
    "id": 135,
    "word": "vietnam",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/viˌɛtnˈɑm/",
    "meaning": "Việt Nam",
    "ex1": "Traditional meals are an important part of family life in Vietnam.",
    "ex1_vi": "Những bữa ăn truyền thống là một phần quan trọng của đời sống gia đình ở Việt Nam."
  },
  {
    "id": 136,
    "word": "bring",
    "type": "verb",
    "cat": "v",
    "phonetic": "/brˈɪŋ/",
    "meaning": "mang lại",
    "ex1": "At home, families discuss bring during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về mang lại trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 137,
    "word": "preserve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌzˈɝv/",
    "meaning": "gìn giữ",
    "ex1": "At home, families discuss preserve during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về gìn giữ trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 138,
    "word": "cultural",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌltʃɝʌl/",
    "meaning": "thuộc văn hóa",
    "ex1": "At home, families discuss cultural during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về thuộc văn hóa trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 139,
    "word": "values",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈæljuz/",
    "meaning": "giá trị",
    "ex1": "At home, families discuss values during shared daily activities.",
    "ex1_vi": "Ở nhà, các gia đình thảo luận về giá trị trong các hoạt động hằng ngày cùng nhau."
  },
  {
    "id": 140,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Many families enjoy simple meals together at home each day.",
    "ex1_vi": "Nhiều gia đình thưởng thức những bữa ăn đơn giản cùng nhau ở nhà mỗi ngày."
  },
  {
    "id": 141,
    "word": "continue",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈɪnju/",
    "meaning": "tiếp tục",
    "ex1": "Children can continue at home during simple family activities.",
    "ex1_vi": "Trẻ em có thể tiếp tục ở nhà trong các hoạt động gia đình đơn giản."
  },
  {
    "id": 142,
    "word": "tradition",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trʌdˈɪʃʌn/",
    "meaning": "truyền thống",
    "ex1": "Children learn about tradition through simple family activities.",
    "ex1_vi": "Trẻ em học về truyền thống qua những hoạt động gia đình đơn giản."
  },
  {
    "id": 143,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "Parents discuss day during everyday conversations at home.",
    "ex1_vi": "Cha mẹ thảo luận về ngày trong những cuộc trò chuyện hằng ngày ở nhà."
  }
];

const newReadingVocabOrder = [
  "healthy",
  "family",
  "meal",
  "provides",
  "nutrients",
  "body",
  "needs",
  "often",
  "includes",
  "rice",
  "vegetables",
  "fruits",
  "fish",
  "meat",
  "or",
  "eggs",
  "drinking",
  "enough",
  "water",
  "also",
  "important",
  "good",
  "health",
  "families",
  "should",
  "try",
  "eat",
  "fresh",
  "foods",
  "instead",
  "too",
  "much",
  "fast",
  "food",
  "ingredients",
  "contain",
  "vitamins",
  "and",
  "minerals",
  "help",
  "people",
  "stay",
  "strong",
  "active",
  "meals",
  "support",
  "growth",
  "improve",
  "overall",
  "well-being",
  "eating",
  "habits",
  "start",
  "home",
  "when",
  "parents",
  "choose",
  "children",
  "learn",
  "make",
  "better",
  "choices",
  "benefits",
  "every",
  "member",
  "talking",
  "dinner",
  "table",
  "place",
  "where",
  "can",
  "communicate",
  "while",
  "members",
  "talk",
  "about",
  "daily",
  "experiences",
  "plans",
  "ideas",
  "conversations",
  "life",
  "more",
  "enjoyable",
  "ask",
  "school",
  "friends",
  "advice",
  "listening",
  "carefully",
  "shows",
  "respect",
  "helps",
  "build",
  "stronger",
  "relationships",
  "creates",
  "friendly",
  "atmosphere",
  "feel",
  "comfortable",
  "sharing",
  "thoughts",
  "feelings",
  "regular",
  "connected",
  "one",
  "another",
  "traditional",
  "vietnamese",
  "simple",
  "balanced",
  "delicious",
  "typical",
  "soup",
  "dish",
  "provide",
  "nutrition",
  "reflect",
  "culture",
  "usually",
  "sit",
  "together",
  "share",
  "dishes",
  "placed",
  "center",
  "style",
  "encourages",
  "togetherness",
  "enjoy",
  "different",
  "flavors",
  "part",
  "vietnam",
  "bring",
  "preserve",
  "cultural",
  "values",
  "many",
  "continue",
  "tradition",
  "day"
];
