const newEssayData = [
  {
    "text": "The Brain – Não bộ\nThe brain is an important organ inside the head. The skull protects it from many injuries. It is soft, complex, and connected to the nerves in the body.\n\nThe brain works all day and night. It helps us think, learn, remember, speak, and make decisions. It also controls movement, breathing, feelings, and the five senses.\n\nDifferent parts of the brain do different jobs, but they work together. To keep the brain healthy, people should sleep enough, eat good food, and exercise often. Reading books,\nsolving problems, and learning new skills are also useful. Wearing a helmet during sports can protect the brain from serious injury. Quiet time and regular breaks help the mind stay calm.",
    "vi": "Não bộ\nNão là một cơ quan quan trọng bên trong đầu. Hộp sọ bảo vệ não khỏi nhiều chấn thương. Não mềm, phức tạp và được kết nối với các dây thần kinh trong cơ thể.\n\nNão hoạt động cả ngày lẫn đêm. Não giúp chúng ta suy nghĩ, học, ghi nhớ, nói và đưa ra quyết định. Não cũng kiểm soát vận động, hô hấp, cảm xúc và năm giác quan.\n\nCác phần khác nhau của não đảm nhiệm những công việc khác nhau, nhưng chúng phối hợp với nhau. Để giữ não khỏe mạnh, mọi người nên ngủ đủ, ăn thực phẩm tốt và tập thể dục thường xuyên. Đọc sách,\ngiải quyết vấn đề và học kỹ năng mới cũng rất hữu ích. Đội mũ bảo hiểm khi chơi thể thao có thể bảo vệ não khỏi chấn thương nghiêm trọng. Thời gian yên tĩnh và những khoảng nghỉ đều đặn giúp tinh thần bình tĩnh."
  },
  {
    "text": "The Heart – Tim\nThe heart is a strong organ in the chest. It is about the size of a fist and sits slightly to the left. The heart is made of muscle and works every minute of life.\n\nIts main job is to pump blood around the body. Blood carries oxygen and nutrients to every part. It also takes waste away. The heart beats faster when we run, exercise, or feel excited.\n\nTo protect the heart, people should exercise regularly and eat healthy food. Fruits, vegetables, and whole grains are good choices. Too much salt, sugar, and fat can be harmful. Rest, sleep, and regular health checks also help keep the heart strong. Drinking enough water is helpful.",
    "vi": "Tim\nTim là một cơ quan khỏe nằm trong lồng ngực. Tim có kích thước khoảng bằng một nắm tay và nằm hơi lệch về bên trái. Tim được tạo thành từ cơ và hoạt động từng phút trong suốt cuộc đời.\n\nNhiệm vụ chính của tim là bơm máu đi khắp cơ thể. Máu mang oxy và chất dinh dưỡng đến mọi bộ phận. Máu cũng mang chất thải đi. Tim đập nhanh hơn khi chúng ta chạy, tập thể dục hoặc cảm thấy phấn khích.\n\nĐể bảo vệ tim, mọi người nên tập thể dục thường xuyên và ăn thực phẩm lành mạnh. Trái cây, rau và ngũ cốc nguyên hạt là những lựa chọn tốt. Quá nhiều muối, đường và chất béo có thể gây hại. Nghỉ ngơi, ngủ và kiểm tra sức khỏe định kỳ cũng giúp tim khỏe mạnh. Uống đủ nước rất có ích."
  },
  {
    "text": "The Lungs – Phổi\nThe lungs are two soft organs inside the chest. They are protected by the ribs and sit on both sides of the heart. The right lung is a little larger than the left lung.\n\nThe lungs help us breathe. When we breathe in, oxygen enters the body. When we breathe out, carbon dioxide leaves. The lungs work with the nose, throat, and breathing muscles every moment.\n\nTo keep the lungs healthy, people should avoid smoke, dust, and polluted air. Regular exercise can make breathing stronger and easier. Opening windows can bring fresh air into a room. Wearing a mask in dirty places may also protect the lungs from harmful particles. Deep breathing can feel relaxing.",
    "vi": "Phổi\nPhổi là hai cơ quan mềm bên trong lồng ngực. Chúng được xương sườn bảo vệ và nằm ở hai bên tim. Phổi phải lớn hơn phổi trái một chút.\n\nPhổi giúp chúng ta thở. Khi chúng ta hít vào, oxy đi vào cơ thể. Khi chúng ta thở ra, khí cacbonic rời khỏi cơ thể. Phổi phối hợp với mũi, họng và các cơ hô hấp trong từng khoảnh khắc.\n\nĐể giữ phổi khỏe mạnh, mọi người nên tránh khói, bụi và không khí ô nhiễm. Tập thể dục đều đặn có thể làm cho việc hô hấp khỏe và dễ dàng hơn. Mở cửa sổ có thể đưa không khí trong lành vào phòng. Đeo khẩu trang ở những nơi bẩn có thể giúp bảo vệ phổi khỏi các hạt có hại. Hít thở sâu có thể mang lại cảm giác thư giãn."
  }
];
