const newEssayData = [
  {
    "text": "The Intestines – Ruột\nThe intestines are long, soft organs inside the abdomen. They include the small intestine and the large intestine. Together, they form an important part of the digestive system and help process food.\n\nThe small intestine receives food from the stomach and absorbs most nutrients. The large intestine absorbs water and forms solid waste. Helpful bacteria also live there and support digestion and general health.\n\nTo keep the intestines healthy, people should eat vegetables, fruits, and whole grains. These foods contain fiber, which helps waste move easily. Drinking enough water and exercising regularly are also useful. Clean food and regular meals can reduce stomach and intestinal problems. Slow eating also helps the digestive system work comfortably.",
    "vi": "Ruột\nRuột là những cơ quan dài và mềm bên trong ổ bụng. Chúng bao gồm ruột non và ruột già. Cùng nhau, chúng tạo thành một phần quan trọng của hệ tiêu hóa và giúp xử lý thức ăn.\n\nRuột non nhận thức ăn từ dạ dày và hấp thụ phần lớn chất dinh dưỡng. Ruột già hấp thụ nước và tạo thành chất thải rắn. Vi khuẩn có lợi cũng sống ở đó và hỗ trợ tiêu hóa cũng như sức khỏe nói chung.\n\nĐể giữ ruột khỏe mạnh, mọi người nên ăn rau, trái cây và ngũ cốc nguyên hạt. Những thực phẩm này chứa chất xơ, giúp chất thải di chuyển dễ dàng. Uống đủ nước và tập thể dục thường xuyên cũng rất hữu ích. Thực phẩm sạch và các bữa ăn đều đặn có thể giảm các vấn đề về dạ dày và đường ruột. Ăn chậm cũng giúp hệ tiêu hóa hoạt động thoải mái."
  },
  {
    "text": "The Eyes – Đôi mắt\nThe eyes are important organs on the face. They sit inside the eye sockets and are protected by the eyelids and eyelashes. Each eye has several small parts that work together.\n\nThe eyes collect light and send information to the brain. They help us see colors, shapes, distances, and movement. The pupils change size when the light becomes brighter or darker.\n\nTo protect the eyes, people should read in good light and rest after using screens. Looking far away for a short time can reduce tiredness. Sunglasses can protect the eyes from strong sunlight. Clean hands should be used around the eyes. Regular eye checks can find vision problems early. Sleep gives the eyes rest.",
    "vi": "Đôi mắt\nMắt là những cơ quan quan trọng trên khuôn mặt. Chúng nằm trong hốc mắt và được mí mắt cùng lông mi bảo vệ. Mỗi mắt có một số bộ phận nhỏ phối hợp với nhau.\n\nMắt thu nhận ánh sáng và gửi thông tin đến não. Mắt giúp chúng ta nhìn thấy màu sắc, hình dạng, khoảng cách và chuyển động. Đồng tử thay đổi kích thước khi ánh sáng trở nên sáng hơn hoặc tối hơn.\n\nĐể bảo vệ mắt, mọi người nên đọc ở nơi đủ sáng và nghỉ sau khi dùng màn hình. Nhìn ra xa trong một khoảng thời gian ngắn có thể giảm mỏi mắt. Kính râm có thể bảo vệ mắt khỏi ánh nắng mạnh. Nên dùng tay sạch quanh mắt. Kiểm tra mắt định kỳ có thể phát hiện sớm các vấn đề về thị lực. Giấc ngủ giúp mắt được nghỉ ngơi."
  },
  {
    "text": "The Ears – Đôi tai\nThe ears are organs on both sides of the head. Each ear has an outer, middle, and inner part. These parts work together to receive sounds and help the body stay balanced.\n\nSound waves enter the outer ear and travel inward. Small bones in the middle ear move and pass the sound to the inner ear. Signals then travel to the brain, where they become meaningful sounds.\n\nTo protect the ears, people should avoid very loud music and noisy places. Earphones should not be used at high volume for long periods. Nothing sharp should be placed inside the ear. Keeping the ears dry and having hearing checks can prevent problems. Quiet breaks can protect hearing.",
    "vi": "Đôi tai\nTai là các cơ quan nằm ở hai bên đầu. Mỗi tai có phần ngoài, phần giữa và phần trong. Những bộ phận này phối hợp để tiếp nhận âm thanh và giúp cơ thể giữ thăng bằng.\n\nSóng âm đi vào tai ngoài và truyền vào phía trong. Những xương nhỏ ở tai giữa chuyển động và truyền âm thanh đến tai trong. Sau đó các tín hiệu truyền đến não, nơi chúng trở thành những âm thanh có ý nghĩa.\n\nĐể bảo vệ tai, mọi người nên tránh âm nhạc quá lớn và những nơi ồn ào. Không nên sử dụng tai nghe ở âm lượng cao trong thời gian dài. Không nên đặt vật sắc nhọn vào bên trong tai. Giữ tai khô và kiểm tra thính lực có thể ngăn ngừa vấn đề. Những khoảng nghỉ yên tĩnh có thể bảo vệ thính giác."
  },
  {
    "text": "The Skin – Da\nThe skin is the largest organ of the human body. It covers the outside of the body and has several layers. Skin color and thickness can vary, but all skin has important protective jobs.\n\nThe skin keeps harmful germs and dirt outside the body. It helps control body temperature through sweat. It also allows us to feel heat, cold, pressure, pain, and touch.\n\nTo keep the skin healthy, people should wash gently and use clean water. Drinking enough water and eating fresh food are helpful. Strong sunlight can damage the skin, so hats and sunscreen may provide protection. Clean clothes, enough sleep, and early care for skin problems are also important. Moisturizer can help skin.",
    "vi": "Da\nDa là cơ quan lớn nhất của cơ thể người. Da bao phủ bên ngoài cơ thể và có nhiều lớp. Màu sắc và độ dày của da có thể khác nhau, nhưng mọi loại da đều có nhiệm vụ bảo vệ quan trọng.\n\nDa ngăn vi trùng và bụi bẩn có hại xâm nhập cơ thể. Da giúp kiểm soát nhiệt độ cơ thể thông qua mồ hôi. Da cũng cho phép chúng ta cảm nhận nóng, lạnh, áp lực, đau và xúc giác.\n\nĐể giữ da khỏe mạnh, mọi người nên rửa nhẹ nhàng và dùng nước sạch. Uống đủ nước và ăn thực phẩm tươi rất có ích. Ánh nắng mạnh có thể làm tổn thương da, vì vậy mũ và kem chống nắng có thể giúp bảo vệ. Quần áo sạch, ngủ đủ và chăm sóc sớm các vấn đề về da cũng rất quan trọng. Kem dưỡng ẩm có thể giúp ích cho da."
  }
];
