const lessonVocabularyWords = [
  "intestines",
  "long",
  "soft",
  "organs",
  "inside",
  "abdomen",
  "include",
  "small",
  "intestine",
  "and",
  "large",
  "together",
  "form",
  "important",
  "part",
  "digestive",
  "system",
  "help",
  "process",
  "food",
  "receives",
  "stomach",
  "absorbs",
  "most",
  "nutrients",
  "water",
  "forms",
  "solid",
  "waste",
  "helpful",
  "bacteria",
  "also",
  "live",
  "there",
  "support",
  "digestion",
  "general",
  "health",
  "keep",
  "healthy",
  "people",
  "should",
  "eat",
  "vegetables",
  "fruits",
  "whole",
  "grains",
  "foods",
  "contain",
  "fiber",
  "which",
  "helps",
  "move",
  "easily",
  "drinking",
  "enough",
  "exercising",
  "regularly",
  "useful",
  "clean",
  "regular",
  "meals",
  "can",
  "reduce",
  "intestinal",
  "problems",
  "slow",
  "eating",
  "work",
  "comfortably",
  "eyes",
  "face",
  "sit",
  "eye",
  "sockets",
  "protected",
  "eyelids",
  "eyelashes",
  "each",
  "has",
  "several",
  "parts",
  "collect",
  "light",
  "send",
  "information",
  "brain",
  "see",
  "colors",
  "shapes",
  "distances",
  "movement",
  "pupils",
  "change",
  "size",
  "when",
  "becomes",
  "brighter",
  "or",
  "darker",
  "protect",
  "read",
  "good",
  "rest",
  "after",
  "using",
  "screens",
  "looking",
  "far",
  "away",
  "short",
  "time",
  "tiredness",
  "sunglasses",
  "strong",
  "sunlight",
  "hands",
  "used",
  "around",
  "checks",
  "find",
  "vision",
  "early",
  "sleep",
  "gives",
  "ears",
  "both",
  "sides",
  "head",
  "ear",
  "outer",
  "middle",
  "inner",
  "receive",
  "sounds",
  "body",
  "stay",
  "balanced",
  "sound",
  "waves",
  "enter",
  "travel",
  "inward",
  "bones",
  "pass",
  "signals",
  "then",
  "where",
  "become",
  "meaningful",
  "avoid",
  "very",
  "loud",
  "music",
  "noisy",
  "places",
  "earphones",
  "not",
  "high",
  "volume",
  "periods",
  "nothing",
  "sharp",
  "placed",
  "keeping",
  "dry",
  "having",
  "hearing",
  "prevent",
  "quiet",
  "breaks",
  "skin",
  "largest",
  "organ",
  "human",
  "covers",
  "outside",
  "layers",
  "color",
  "thickness",
  "vary",
  "but",
  "all",
  "protective",
  "jobs",
  "keeps",
  "harmful",
  "germs",
  "dirt",
  "control",
  "temperature",
  "sweat",
  "allows",
  "feel",
  "heat",
  "cold",
  "pressure",
  "pain",
  "touch",
  "wash",
  "gently",
  "use",
  "fresh",
  "damage",
  "so",
  "hats",
  "sunscreen",
  "may",
  "provide",
  "protection",
  "clothes",
  "care",
  "moisturizer"
];

const newVocabData = [
  {
    "id": 1,
    "word": "intestines",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪnˈtɛstɪnz/",
    "meaning": "ruột",
    "ex1": "The intestines are long, soft organs inside the abdomen.",
    "ex1_vi": "Ruột là những cơ quan dài và mềm bên trong ổ bụng."
  },
  {
    "id": 2,
    "word": "long",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɔŋ/",
    "meaning": "dài",
    "ex1": "The intestines are long, soft organs inside the abdomen.",
    "ex1_vi": "Ruột là những cơ quan dài và mềm bên trong ổ bụng."
  },
  {
    "id": 3,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "People learn about soft when studying healthy body functions.",
    "ex1_vi": "Mọi người học về mềm khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 4,
    "word": "organs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔrɡʌnz/",
    "meaning": "cơ quan",
    "ex1": "The eyes are important organs on the face.",
    "ex1_vi": "Mắt là những cơ quan quan trọng trên khuôn mặt."
  },
  {
    "id": 5,
    "word": "inside",
    "type": "preposition/adverb",
    "cat": "adv",
    "phonetic": "/ˌɪnsˈaɪd/",
    "meaning": "bên trong",
    "ex1": "Nothing sharp should be placed inside the ear.",
    "ex1_vi": "Không nên đặt vật sắc nhọn vào bên trong tai."
  },
  {
    "id": 6,
    "word": "abdomen",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈæbdəmən/",
    "meaning": "ổ bụng",
    "ex1": "People learn about abdomen when studying healthy body functions.",
    "ex1_vi": "Mọi người học về ổ bụng khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 7,
    "word": "include",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪnklˈud/",
    "meaning": "bao gồm",
    "ex1": "They include the small intestine and the large intestine.",
    "ex1_vi": "Chúng bao gồm ruột non và ruột già."
  },
  {
    "id": 8,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "They include the small intestine and the large intestine.",
    "ex1_vi": "Chúng bao gồm ruột non và ruột già."
  },
  {
    "id": 9,
    "word": "intestine",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪnˈtɛstɪn/",
    "meaning": "ruột",
    "ex1": "People learn about intestine when studying healthy body functions.",
    "ex1_vi": "Mọi người học về ruột khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 10,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "People learn about and when studying healthy body functions.",
    "ex1_vi": "Mọi người học về và khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 11,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒ/",
    "meaning": "lớn",
    "ex1": "People learn about large when studying healthy body functions.",
    "ex1_vi": "Mọi người học về lớn khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 12,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌɡˈɛðɝ/",
    "meaning": "cùng nhau",
    "ex1": "Each eye has several small parts that work together.",
    "ex1_vi": "Mỗi mắt có một số bộ phận nhỏ phối hợp với nhau."
  },
  {
    "id": 13,
    "word": "form",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɔrm/",
    "meaning": "hình thành",
    "ex1": "Healthy organs can form normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể hình thành bình thường suốt ngày."
  },
  {
    "id": 14,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔrtʌnt/",
    "meaning": "quan trọng",
    "ex1": "The eyes are important organs on the face.",
    "ex1_vi": "Mắt là những cơ quan quan trọng trên khuôn mặt."
  },
  {
    "id": 15,
    "word": "part",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrt/",
    "meaning": "bộ phận; phần",
    "ex1": "Each ear has an outer, middle, and inner part.",
    "ex1_vi": "Mỗi tai có phần ngoài, phần giữa và phần trong."
  },
  {
    "id": 16,
    "word": "digestive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/daɪˈdʒɛstɪv/",
    "meaning": "thuộc tiêu hóa",
    "ex1": "Slow eating also helps the digestive system work comfortably.",
    "ex1_vi": "Ăn chậm cũng giúp hệ tiêu hóa hoạt động thoải mái."
  },
  {
    "id": 17,
    "word": "system",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪstʌm/",
    "meaning": "hệ thống",
    "ex1": "Slow eating also helps the digestive system work comfortably.",
    "ex1_vi": "Ăn chậm cũng giúp hệ tiêu hóa hoạt động thoải mái."
  },
  {
    "id": 18,
    "word": "help",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "Doctors explain help when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích giúp khi dạy mọi người về cơ thể người."
  },
  {
    "id": 19,
    "word": "process",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prˈɑsˌɛs/",
    "meaning": "xử lý",
    "ex1": "This organ process normally when the body stays healthy.",
    "ex1_vi": "Cơ quan này xử lý bình thường khi cơ thể khỏe mạnh."
  },
  {
    "id": 20,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thức ăn",
    "ex1": "Drinking enough water and eating fresh food are helpful.",
    "ex1_vi": "Uống đủ nước và ăn thực phẩm tươi rất có ích."
  },
  {
    "id": 21,
    "word": "receives",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rʌsˈivz/",
    "meaning": "nhận",
    "ex1": "The small intestine receives food from the stomach and absorbs most nutrients.",
    "ex1_vi": "Ruột non nhận thức ăn từ dạ dày và hấp thụ phần lớn chất dinh dưỡng."
  },
  {
    "id": 22,
    "word": "stomach",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈstʌmək/",
    "meaning": "dạ dày",
    "ex1": "Clean food and regular meals can reduce stomach and intestinal problems.",
    "ex1_vi": "Thực phẩm sạch và các bữa ăn đều đặn có thể giảm các vấn đề về dạ dày và đường ruột."
  },
  {
    "id": 23,
    "word": "absorbs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌbzˈɔrbz/",
    "meaning": "hấp thụ",
    "ex1": "The large intestine absorbs water and forms solid waste.",
    "ex1_vi": "Ruột già hấp thụ nước và tạo thành chất thải rắn."
  },
  {
    "id": 24,
    "word": "most",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈoʊst/",
    "meaning": "phần lớn",
    "ex1": "The small intestine receives food from the stomach and absorbs most nutrients.",
    "ex1_vi": "Ruột non nhận thức ăn từ dạ dày và hấp thụ phần lớn chất dinh dưỡng."
  },
  {
    "id": 25,
    "word": "nutrients",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈnuːtriənts/",
    "meaning": "chất dinh dưỡng",
    "ex1": "People learn about nutrients when studying healthy body functions.",
    "ex1_vi": "Mọi người học về chất dinh dưỡng khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 26,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước",
    "ex1": "The large intestine absorbs water and forms solid waste.",
    "ex1_vi": "Ruột già hấp thụ nước và tạo thành chất thải rắn."
  },
  {
    "id": 27,
    "word": "forms",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɔrmz/",
    "meaning": "hình thành",
    "ex1": "People learn about forms when studying healthy body functions.",
    "ex1_vi": "Mọi người học về hình thành khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 28,
    "word": "solid",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑlʌd/",
    "meaning": "rắn",
    "ex1": "People learn about solid when studying healthy body functions.",
    "ex1_vi": "Mọi người học về rắn khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 29,
    "word": "waste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪst/",
    "meaning": "chất thải",
    "ex1": "People learn about waste when studying healthy body functions.",
    "ex1_vi": "Mọi người học về chất thải khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 30,
    "word": "helpful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlpfʌl/",
    "meaning": "hữu ích",
    "ex1": "Drinking enough water and eating fresh food are helpful.",
    "ex1_vi": "Uống đủ nước và ăn thực phẩm tươi rất có ích."
  },
  {
    "id": 31,
    "word": "bacteria",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bækˈtɪriə/",
    "meaning": "vi khuẩn",
    "ex1": "Helpful bacteria also live there and support digestion and general health.",
    "ex1_vi": "Vi khuẩn có lợi cũng sống ở đó và hỗ trợ tiêu hóa cũng như sức khỏe nói chung."
  },
  {
    "id": 32,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "Drinking enough water and exercising regularly are also useful.",
    "ex1_vi": "Uống đủ nước và tập thể dục thường xuyên cũng rất hữu ích."
  },
  {
    "id": 33,
    "word": "live",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈaɪv/",
    "meaning": "sống",
    "ex1": "Helpful bacteria also live there and support digestion and general health.",
    "ex1_vi": "Vi khuẩn có lợi cũng sống ở đó và hỗ trợ tiêu hóa cũng như sức khỏe nói chung."
  },
  {
    "id": 34,
    "word": "there",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ðˈɛr/",
    "meaning": "ở đó",
    "ex1": "People learn about there when studying healthy body functions.",
    "ex1_vi": "Mọi người học về ở đó khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 35,
    "word": "support",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sʌpˈɔrt/",
    "meaning": "hỗ trợ",
    "ex1": "People learn about support when studying healthy body functions.",
    "ex1_vi": "Mọi người học về hỗ trợ khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 36,
    "word": "digestion",
    "type": "noun",
    "cat": "n",
    "phonetic": "/daɪˈdʒɛstʃən/",
    "meaning": "sự tiêu hóa",
    "ex1": "People learn about digestion when studying healthy body functions.",
    "ex1_vi": "Mọi người học về sự tiêu hóa khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 37,
    "word": "general",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈɛnɝʌl/",
    "meaning": "nói chung",
    "ex1": "People learn about general when studying healthy body functions.",
    "ex1_vi": "Mọi người học về nói chung khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 38,
    "word": "health",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛlθ/",
    "meaning": "sức khỏe",
    "ex1": "People learn about health when studying healthy body functions.",
    "ex1_vi": "Mọi người học về sức khỏe khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 39,
    "word": "keep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈip/",
    "meaning": "giữ",
    "ex1": "Healthy organs can keep normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể giữ bình thường suốt ngày."
  },
  {
    "id": 40,
    "word": "healthy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlθi/",
    "meaning": "khỏe mạnh",
    "ex1": "Healthy organs stay healthy when people follow good habits.",
    "ex1_vi": "Các cơ quan khỏe mạnh vẫn khỏe mạnh khi mọi người duy trì thói quen tốt."
  },
  {
    "id": 41,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "Doctors explain people when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích mọi người khi dạy mọi người về cơ thể người."
  },
  {
    "id": 42,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "Clean hands should be used around the eyes.",
    "ex1_vi": "Nên dùng tay sạch quanh mắt."
  },
  {
    "id": 43,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "Healthy organs can eat normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể ăn bình thường suốt ngày."
  },
  {
    "id": 44,
    "word": "vegetables",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɛdʒtʌbʌlz/",
    "meaning": "rau",
    "ex1": "Doctors explain vegetables when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích rau khi dạy mọi người về cơ thể người."
  },
  {
    "id": 45,
    "word": "fruits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈuts/",
    "meaning": "trái cây",
    "ex1": "Doctors explain fruits when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích trái cây khi dạy mọi người về cơ thể người."
  },
  {
    "id": 46,
    "word": "whole",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/hˈoʊl/",
    "meaning": "nguyên hạt; toàn bộ",
    "ex1": "Whole organs need healthy habits and regular medical care.",
    "ex1_vi": "Nguyên hạt; toàn bộ cơ quan cần thói quen lành mạnh và chăm sóc y tế đều đặn."
  },
  {
    "id": 47,
    "word": "grains",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡrˈeɪnz/",
    "meaning": "ngũ cốc",
    "ex1": "Doctors explain grains when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích ngũ cốc khi dạy mọi người về cơ thể người."
  },
  {
    "id": 48,
    "word": "foods",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈudz/",
    "meaning": "thực phẩm",
    "ex1": "These foods contain fiber, which helps waste move easily.",
    "ex1_vi": "Những thực phẩm này chứa chất xơ, giúp chất thải di chuyển dễ dàng."
  },
  {
    "id": 49,
    "word": "contain",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈeɪn/",
    "meaning": "chứa",
    "ex1": "These foods contain fiber, which helps waste move easily.",
    "ex1_vi": "Những thực phẩm này chứa chất xơ, giúp chất thải di chuyển dễ dàng."
  },
  {
    "id": 50,
    "word": "fiber",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈfaɪbər/",
    "meaning": "chất xơ",
    "ex1": "People learn about fiber when studying healthy body functions.",
    "ex1_vi": "Mọi người học về chất xơ khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 51,
    "word": "which",
    "type": "relative pronoun",
    "cat": "n",
    "phonetic": "/wˈɪtʃ/",
    "meaning": "mà",
    "ex1": "People learn about which when studying healthy body functions.",
    "ex1_vi": "Mọi người học về mà khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 52,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "This organ helps normally when the body stays healthy.",
    "ex1_vi": "Cơ quan này giúp bình thường khi cơ thể khỏe mạnh."
  },
  {
    "id": 53,
    "word": "move",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈuv/",
    "meaning": "di chuyển",
    "ex1": "People learn about move when studying healthy body functions.",
    "ex1_vi": "Mọi người học về di chuyển khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 54,
    "word": "easily",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈizʌli/",
    "meaning": "dễ dàng",
    "ex1": "People learn about easily when studying healthy body functions.",
    "ex1_vi": "Mọi người học về dễ dàng khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 55,
    "word": "drinking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/drˈɪŋkɪŋ/",
    "meaning": "uống",
    "ex1": "Drinking enough water and exercising regularly are also useful.",
    "ex1_vi": "Uống đủ nước và tập thể dục thường xuyên cũng rất hữu ích."
  },
  {
    "id": 56,
    "word": "enough",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/ɪnˈʌf/",
    "meaning": "đủ",
    "ex1": "People learn about enough when studying healthy body functions.",
    "ex1_vi": "Mọi người học về đủ khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 57,
    "word": "exercising",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛksɝsˌaɪzɪŋ/",
    "meaning": "tập thể dục",
    "ex1": "People learn about exercising when studying healthy body functions.",
    "ex1_vi": "Mọi người học về tập thể dục khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 58,
    "word": "regularly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/rˈɛɡjʌlɝli/",
    "meaning": "thường xuyên",
    "ex1": "People learn about regularly when studying healthy body functions.",
    "ex1_vi": "Mọi người học về thường xuyên khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 59,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈusfʌl/",
    "meaning": "hữu ích",
    "ex1": "People learn about useful when studying healthy body functions.",
    "ex1_vi": "Mọi người học về hữu ích khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 60,
    "word": "clean",
    "type": "verb",
    "cat": "v",
    "phonetic": "/klˈin/",
    "meaning": "sạch",
    "ex1": "Clean hands should be used around the eyes.",
    "ex1_vi": "Nên dùng tay sạch quanh mắt."
  },
  {
    "id": 61,
    "word": "regular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛɡjʌlɝ/",
    "meaning": "đều đặn",
    "ex1": "Regular eye checks can find vision problems early.",
    "ex1_vi": "Kiểm tra mắt định kỳ có thể phát hiện sớm các vấn đề về thị lực."
  },
  {
    "id": 62,
    "word": "meals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈilz/",
    "meaning": "bữa ăn",
    "ex1": "Clean food and regular meals can reduce stomach and intestinal problems.",
    "ex1_vi": "Thực phẩm sạch và các bữa ăn đều đặn có thể giảm các vấn đề về dạ dày và đường ruột."
  },
  {
    "id": 63,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Regular exercise can support the heart and lungs.",
    "ex1_vi": "Tập thể dục đều đặn có thể hỗ trợ tim và phổi."
  },
  {
    "id": 64,
    "word": "reduce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rʌdˈus/",
    "meaning": "giảm",
    "ex1": "Looking far away for a short time can reduce tiredness.",
    "ex1_vi": "Nhìn ra xa trong một khoảng thời gian ngắn có thể giảm mỏi mắt."
  },
  {
    "id": 65,
    "word": "intestinal",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪnˈtɛstɪnəl/",
    "meaning": "thuộc đường ruột",
    "ex1": "People learn about intestinal when studying healthy body functions.",
    "ex1_vi": "Mọi người học về thuộc đường ruột khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 66,
    "word": "problems",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑblʌmz/",
    "meaning": "vấn đề",
    "ex1": "Regular eye checks can find vision problems early.",
    "ex1_vi": "Kiểm tra mắt định kỳ có thể phát hiện sớm các vấn đề về thị lực."
  },
  {
    "id": 67,
    "word": "slow",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/slˈoʊ/",
    "meaning": "chậm",
    "ex1": "People learn about slow when studying healthy body functions.",
    "ex1_vi": "Mọi người học về chậm khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 68,
    "word": "eating",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/ˈitɪŋ/",
    "meaning": "ăn",
    "ex1": "People learn about eating when studying healthy body functions.",
    "ex1_vi": "Mọi người học về ăn khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 69,
    "word": "work",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝk/",
    "meaning": "hoạt động; làm việc",
    "ex1": "People learn about work when studying healthy body functions.",
    "ex1_vi": "Mọi người học về hoạt động; làm việc khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 70,
    "word": "comfortably",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈʌmfɝtʌbli/",
    "meaning": "thoải mái",
    "ex1": "People learn about comfortably when studying healthy body functions.",
    "ex1_vi": "Mọi người học về thoải mái khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 71,
    "word": "eyes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪz/",
    "meaning": "mắt",
    "ex1": "Healthy habits help protect the eyes every day.",
    "ex1_vi": "Thói quen lành mạnh giúp bảo vệ mắt mỗi ngày."
  },
  {
    "id": 72,
    "word": "face",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈeɪs/",
    "meaning": "khuôn mặt",
    "ex1": "People learn about face when studying healthy body functions.",
    "ex1_vi": "Mọi người học về khuôn mặt khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 73,
    "word": "sit",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɪt/",
    "meaning": "nằm",
    "ex1": "Healthy organs can sit normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể nằm bình thường suốt ngày."
  },
  {
    "id": 74,
    "word": "eye",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪ/",
    "meaning": "mắt",
    "ex1": "People learn about eye when studying healthy body functions.",
    "ex1_vi": "Mọi người học về mắt khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 75,
    "word": "sockets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɑkʌts/",
    "meaning": "hốc mắt",
    "ex1": "Doctors explain sockets when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích hốc mắt khi dạy mọi người về cơ thể người."
  },
  {
    "id": 76,
    "word": "protected",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌtˈɛktɪd/",
    "meaning": "được bảo vệ",
    "ex1": "The organ was protected during careful medical treatment.",
    "ex1_vi": "Cơ quan đã được bảo vệ trong quá trình điều trị y tế cẩn thận."
  },
  {
    "id": 77,
    "word": "eyelids",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪlɪdz/",
    "meaning": "mí mắt",
    "ex1": "Doctors explain eyelids when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích mí mắt khi dạy mọi người về cơ thể người."
  },
  {
    "id": 78,
    "word": "eyelashes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪlæʃɪz/",
    "meaning": "lông mi",
    "ex1": "Doctors explain eyelashes when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích lông mi khi dạy mọi người về cơ thể người."
  },
  {
    "id": 79,
    "word": "each",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈitʃ/",
    "meaning": "mỗi",
    "ex1": "Each eye has several small parts that work together.",
    "ex1_vi": "Mỗi mắt có một số bộ phận nhỏ phối hợp với nhau."
  },
  {
    "id": 80,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "People learn about has when studying healthy body functions.",
    "ex1_vi": "Mọi người học về có khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 81,
    "word": "several",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈɛvrʌl/",
    "meaning": "một số",
    "ex1": "People learn about several when studying healthy body functions.",
    "ex1_vi": "Mọi người học về một số khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 82,
    "word": "parts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrts/",
    "meaning": "bộ phận",
    "ex1": "People learn about parts when studying healthy body functions.",
    "ex1_vi": "Mọi người học về bộ phận khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 83,
    "word": "collect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌlˈɛkt/",
    "meaning": "thu nhận",
    "ex1": "The eyes collect light and send information to the brain.",
    "ex1_vi": "Mắt thu nhận ánh sáng và gửi thông tin đến não."
  },
  {
    "id": 84,
    "word": "light",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈaɪt/",
    "meaning": "ánh sáng",
    "ex1": "The eyes collect light and send information to the brain.",
    "ex1_vi": "Mắt thu nhận ánh sáng và gửi thông tin đến não."
  },
  {
    "id": 85,
    "word": "send",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɛnd/",
    "meaning": "gửi",
    "ex1": "People learn about send when studying healthy body functions.",
    "ex1_vi": "Mọi người học về gửi khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 86,
    "word": "information",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnfɝmˈeɪʃʌn/",
    "meaning": "thông tin",
    "ex1": "People learn about information when studying healthy body functions.",
    "ex1_vi": "Mọi người học về thông tin khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 87,
    "word": "brain",
    "type": "noun",
    "cat": "n",
    "phonetic": "/breɪn/",
    "meaning": "não",
    "ex1": "People learn about brain when studying healthy body functions.",
    "ex1_vi": "Mọi người học về não khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 88,
    "word": "see",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈi/",
    "meaning": "nhìn thấy",
    "ex1": "They help us see colors, shapes, distances, and movement.",
    "ex1_vi": "Mắt giúp chúng ta nhìn thấy màu sắc, hình dạng, khoảng cách và chuyển động."
  },
  {
    "id": 89,
    "word": "colors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌlɝz/",
    "meaning": "màu sắc",
    "ex1": "They help us see colors, shapes, distances, and movement.",
    "ex1_vi": "Mắt giúp chúng ta nhìn thấy màu sắc, hình dạng, khoảng cách và chuyển động."
  },
  {
    "id": 90,
    "word": "shapes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈeɪps/",
    "meaning": "hình dạng",
    "ex1": "People learn about shapes when studying healthy body functions.",
    "ex1_vi": "Mọi người học về hình dạng khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 91,
    "word": "distances",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪstʌnsʌz/",
    "meaning": "khoảng cách",
    "ex1": "People learn about distances when studying healthy body functions.",
    "ex1_vi": "Mọi người học về khoảng cách khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 92,
    "word": "movement",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈuvmʌnt/",
    "meaning": "vận động",
    "ex1": "People learn about movement when studying healthy body functions.",
    "ex1_vi": "Mọi người học về vận động khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 93,
    "word": "pupils",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈpjuːpəlz/",
    "meaning": "đồng tử",
    "ex1": "The pupils change size when the light becomes brighter or darker.",
    "ex1_vi": "Đồng tử thay đổi kích thước khi ánh sáng trở nên sáng hơn hoặc tối hơn."
  },
  {
    "id": 94,
    "word": "change",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈeɪndʒ/",
    "meaning": "thay đổi",
    "ex1": "The pupils change size when the light becomes brighter or darker.",
    "ex1_vi": "Đồng tử thay đổi kích thước khi ánh sáng trở nên sáng hơn hoặc tối hơn."
  },
  {
    "id": 95,
    "word": "size",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaɪz/",
    "meaning": "kích thước",
    "ex1": "People learn about size when studying healthy body functions.",
    "ex1_vi": "Mọi người học về kích thước khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 96,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "People learn about when when studying healthy body functions.",
    "ex1_vi": "Mọi người học về khi khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 97,
    "word": "becomes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌmz/",
    "meaning": "trở thành",
    "ex1": "People learn about becomes when studying healthy body functions.",
    "ex1_vi": "Mọi người học về trở thành khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 98,
    "word": "brighter",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/brˈaɪtɝ/",
    "meaning": "sáng hơn",
    "ex1": "People learn about brighter when studying healthy body functions.",
    "ex1_vi": "Mọi người học về sáng hơn khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 99,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "People learn about or when studying healthy body functions.",
    "ex1_vi": "Mọi người học về hoặc khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 100,
    "word": "darker",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɑrkɝ/",
    "meaning": "tối hơn",
    "ex1": "People learn about darker when studying healthy body functions.",
    "ex1_vi": "Mọi người học về tối hơn khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 101,
    "word": "protect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌtˈɛkt/",
    "meaning": "bảo vệ",
    "ex1": "Healthy organs can protect normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể bảo vệ bình thường suốt ngày."
  },
  {
    "id": 102,
    "word": "read",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈɛd/",
    "meaning": "đọc",
    "ex1": "Healthy organs can read normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể đọc bình thường suốt ngày."
  },
  {
    "id": 103,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "Healthy organs stay good when people follow good habits.",
    "ex1_vi": "Các cơ quan khỏe mạnh vẫn tốt khi mọi người duy trì thói quen tốt."
  },
  {
    "id": 104,
    "word": "rest",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈɛst/",
    "meaning": "nghỉ ngơi",
    "ex1": "Healthy organs can rest normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể nghỉ ngơi bình thường suốt ngày."
  },
  {
    "id": 105,
    "word": "after",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/ˈæftɝ/",
    "meaning": "sau",
    "ex1": "People use after naturally when describing how body organs work.",
    "ex1_vi": "Mọi người dùng “after” tự nhiên khi mô tả cách các cơ quan hoạt động."
  },
  {
    "id": 106,
    "word": "using",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈuzɪŋ/",
    "meaning": "sử dụng",
    "ex1": "Doctors explain using when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích sử dụng khi dạy mọi người về cơ thể người."
  },
  {
    "id": 107,
    "word": "screens",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skrˈinz/",
    "meaning": "màn hình",
    "ex1": "Doctors explain screens when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích màn hình khi dạy mọi người về cơ thể người."
  },
  {
    "id": 108,
    "word": "looking",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/lˈʊkɪŋ/",
    "meaning": "nhìn",
    "ex1": "Looking far away for a short time can reduce tiredness.",
    "ex1_vi": "Nhìn ra xa trong một khoảng thời gian ngắn có thể giảm mỏi mắt."
  },
  {
    "id": 109,
    "word": "far",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/fˈɑr/",
    "meaning": "xa",
    "ex1": "People learn about far when studying healthy body functions.",
    "ex1_vi": "Mọi người học về xa khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 110,
    "word": "away",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌwˈeɪ/",
    "meaning": "đi; ra xa",
    "ex1": "People learn about away when studying healthy body functions.",
    "ex1_vi": "Mọi người học về đi; ra xa khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 111,
    "word": "short",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɔrt/",
    "meaning": "ngắn",
    "ex1": "People learn about short when studying healthy body functions.",
    "ex1_vi": "Mọi người học về ngắn khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 112,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "People learn about time when studying healthy body functions.",
    "ex1_vi": "Mọi người học về thời gian khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 113,
    "word": "tiredness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈtaɪərdnəs/",
    "meaning": "sự mệt mỏi",
    "ex1": "People learn about tiredness when studying healthy body functions.",
    "ex1_vi": "Mọi người học về sự mệt mỏi khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 114,
    "word": "sunglasses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsʌnˌɡlæsɪz/",
    "meaning": "kính râm",
    "ex1": "Sunglasses can protect the eyes from strong sunlight.",
    "ex1_vi": "Kính râm có thể bảo vệ mắt khỏi ánh nắng mạnh."
  },
  {
    "id": 115,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋ/",
    "meaning": "khỏe; mạnh",
    "ex1": "Sunglasses can protect the eyes from strong sunlight.",
    "ex1_vi": "Kính râm có thể bảo vệ mắt khỏi ánh nắng mạnh."
  },
  {
    "id": 116,
    "word": "sunlight",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsʌnlaɪt/",
    "meaning": "ánh nắng",
    "ex1": "People learn about sunlight when studying healthy body functions.",
    "ex1_vi": "Mọi người học về ánh nắng khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 117,
    "word": "hands",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈændz/",
    "meaning": "tay",
    "ex1": "People learn about hands when studying healthy body functions.",
    "ex1_vi": "Mọi người học về tay khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 118,
    "word": "used",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzd/",
    "meaning": "được sử dụng",
    "ex1": "People learn about used when studying healthy body functions.",
    "ex1_vi": "Mọi người học về được sử dụng khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 119,
    "word": "around",
    "type": "preposition/adverb",
    "cat": "adv",
    "phonetic": "/ɝˈaʊnd/",
    "meaning": "khắp; quanh",
    "ex1": "People learn about around when studying healthy body functions.",
    "ex1_vi": "Mọi người học về khắp; quanh khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 120,
    "word": "checks",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈɛks/",
    "meaning": "kiểm tra",
    "ex1": "People learn about checks when studying healthy body functions.",
    "ex1_vi": "Mọi người học về kiểm tra khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 121,
    "word": "find",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪnd/",
    "meaning": "phát hiện",
    "ex1": "People learn about find when studying healthy body functions.",
    "ex1_vi": "Mọi người học về phát hiện khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 122,
    "word": "vision",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪʒʌn/",
    "meaning": "thị lực",
    "ex1": "People learn about vision when studying healthy body functions.",
    "ex1_vi": "Mọi người học về thị lực khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 123,
    "word": "early",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɝli/",
    "meaning": "sớm",
    "ex1": "People learn about early when studying healthy body functions.",
    "ex1_vi": "Mọi người học về sớm khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 124,
    "word": "sleep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/slˈip/",
    "meaning": "ngủ",
    "ex1": "Healthy organs can sleep normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể ngủ bình thường suốt ngày."
  },
  {
    "id": 125,
    "word": "gives",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvz/",
    "meaning": "mang lại",
    "ex1": "This organ gives normally when the body stays healthy.",
    "ex1_vi": "Cơ quan này mang lại bình thường khi cơ thể khỏe mạnh."
  },
  {
    "id": 126,
    "word": "ears",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪrz/",
    "meaning": "tai",
    "ex1": "The ears are organs on both sides of the head.",
    "ex1_vi": "Tai là các cơ quan nằm ở hai bên đầu."
  },
  {
    "id": 127,
    "word": "both",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/bˈoʊθ/",
    "meaning": "cả hai",
    "ex1": "The ears are organs on both sides of the head.",
    "ex1_vi": "Tai là các cơ quan nằm ở hai bên đầu."
  },
  {
    "id": 128,
    "word": "sides",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaɪdz/",
    "meaning": "bên",
    "ex1": "People learn about sides when studying healthy body functions.",
    "ex1_vi": "Mọi người học về bên khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 129,
    "word": "head",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛd/",
    "meaning": "đầu",
    "ex1": "People learn about head when studying healthy body functions.",
    "ex1_vi": "Mọi người học về đầu khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 130,
    "word": "ear",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪr/",
    "meaning": "tai",
    "ex1": "Nothing sharp should be placed inside the ear.",
    "ex1_vi": "Không nên đặt vật sắc nhọn vào bên trong tai."
  },
  {
    "id": 131,
    "word": "outer",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈaʊtɝ/",
    "meaning": "bên ngoài",
    "ex1": "Each ear has an outer, middle, and inner part.",
    "ex1_vi": "Mỗi tai có phần ngoài, phần giữa và phần trong."
  },
  {
    "id": 132,
    "word": "middle",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈɪdʌl/",
    "meaning": "ở giữa",
    "ex1": "People learn about middle when studying healthy body functions.",
    "ex1_vi": "Mọi người học về ở giữa khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 133,
    "word": "inner",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɪnɝ/",
    "meaning": "bên trong",
    "ex1": "People learn about inner when studying healthy body functions.",
    "ex1_vi": "Mọi người học về bên trong khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 134,
    "word": "receive",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rʌsˈiv/",
    "meaning": "tiếp nhận",
    "ex1": "Healthy organs can receive normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể tiếp nhận bình thường suốt ngày."
  },
  {
    "id": 135,
    "word": "sounds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaʊndz/",
    "meaning": "âm thanh",
    "ex1": "Signals then travel to the brain, where they become meaningful sounds.",
    "ex1_vi": "Sau đó các tín hiệu truyền đến não, nơi chúng trở thành những âm thanh có ý nghĩa."
  },
  {
    "id": 136,
    "word": "body",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɑdi/",
    "meaning": "cơ thể",
    "ex1": "Doctors explain body when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích cơ thể khi dạy mọi người về cơ thể người."
  },
  {
    "id": 137,
    "word": "stay",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈeɪ/",
    "meaning": "giữ; ở",
    "ex1": "Healthy organs can stay normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể giữ; ở bình thường suốt ngày."
  },
  {
    "id": 138,
    "word": "balanced",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈælʌnst/",
    "meaning": "cân bằng",
    "ex1": "Healthy organs stay balanced when people follow good habits.",
    "ex1_vi": "Các cơ quan khỏe mạnh vẫn cân bằng khi mọi người duy trì thói quen tốt."
  },
  {
    "id": 139,
    "word": "sound",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaʊnd/",
    "meaning": "âm thanh",
    "ex1": "Sound waves enter the outer ear and travel inward.",
    "ex1_vi": "Sóng âm đi vào tai ngoài và truyền vào phía trong."
  },
  {
    "id": 140,
    "word": "waves",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪvz/",
    "meaning": "sóng",
    "ex1": "Sound waves enter the outer ear and travel inward.",
    "ex1_vi": "Sóng âm đi vào tai ngoài và truyền vào phía trong."
  },
  {
    "id": 141,
    "word": "enter",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɛntɝ/",
    "meaning": "đi vào",
    "ex1": "People learn about enter when studying healthy body functions.",
    "ex1_vi": "Mọi người học về đi vào khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 142,
    "word": "travel",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈævʌl/",
    "meaning": "truyền; di chuyển",
    "ex1": "People learn about travel when studying healthy body functions.",
    "ex1_vi": "Mọi người học về truyền; di chuyển khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 143,
    "word": "inward",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɪnwərd/",
    "meaning": "vào trong",
    "ex1": "People learn about inward when studying healthy body functions.",
    "ex1_vi": "Mọi người học về vào trong khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 144,
    "word": "bones",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈoʊnz/",
    "meaning": "xương",
    "ex1": "Doctors explain bones when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích xương khi dạy mọi người về cơ thể người."
  },
  {
    "id": 145,
    "word": "pass",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pˈæs/",
    "meaning": "truyền",
    "ex1": "This organ pass normally when the body stays healthy.",
    "ex1_vi": "Cơ quan này truyền bình thường khi cơ thể khỏe mạnh."
  },
  {
    "id": 146,
    "word": "signals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪɡnʌlz/",
    "meaning": "tín hiệu",
    "ex1": "Signals then travel to the brain, where they become meaningful sounds.",
    "ex1_vi": "Sau đó các tín hiệu truyền đến não, nơi chúng trở thành những âm thanh có ý nghĩa."
  },
  {
    "id": 147,
    "word": "then",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ðˈɛn/",
    "meaning": "sau đó",
    "ex1": "People learn about then when studying healthy body functions.",
    "ex1_vi": "Mọi người học về sau đó khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 148,
    "word": "where",
    "type": "relative adverb",
    "cat": "adv",
    "phonetic": "/wˈɛr/",
    "meaning": "nơi mà",
    "ex1": "People learn about where when studying healthy body functions.",
    "ex1_vi": "Mọi người học về nơi mà khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 149,
    "word": "become",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌm/",
    "meaning": "trở nên",
    "ex1": "People learn about become when studying healthy body functions.",
    "ex1_vi": "Mọi người học về trở nên khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 150,
    "word": "meaningful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈinɪŋfʌl/",
    "meaning": "có ý nghĩa",
    "ex1": "People learn about meaningful when studying healthy body functions.",
    "ex1_vi": "Mọi người học về có ý nghĩa khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 151,
    "word": "avoid",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌvˈɔɪd/",
    "meaning": "tránh",
    "ex1": "Healthy organs can avoid normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể tránh bình thường suốt ngày."
  },
  {
    "id": 152,
    "word": "very",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/vˈɛri/",
    "meaning": "rất",
    "ex1": "Body organs work very when healthy habits are maintained.",
    "ex1_vi": "Các cơ quan hoạt động rất khi duy trì thói quen lành mạnh."
  },
  {
    "id": 153,
    "word": "loud",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈaʊd/",
    "meaning": "lớn",
    "ex1": "Healthy organs stay loud when people follow good habits.",
    "ex1_vi": "Các cơ quan khỏe mạnh vẫn lớn khi mọi người duy trì thói quen tốt."
  },
  {
    "id": 154,
    "word": "music",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mjˈuzɪk/",
    "meaning": "âm nhạc",
    "ex1": "Doctors explain music when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích âm nhạc khi dạy mọi người về cơ thể người."
  },
  {
    "id": 155,
    "word": "noisy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈɔɪzi/",
    "meaning": "ồn ào",
    "ex1": "Healthy organs stay noisy when people follow good habits.",
    "ex1_vi": "Các cơ quan khỏe mạnh vẫn ồn ào khi mọi người duy trì thói quen tốt."
  },
  {
    "id": 156,
    "word": "places",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪsʌz/",
    "meaning": "nơi",
    "ex1": "Doctors explain places when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích nơi khi dạy mọi người về cơ thể người."
  },
  {
    "id": 157,
    "word": "earphones",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɪrfoʊnz/",
    "meaning": "tai nghe",
    "ex1": "Earphones should not be used at high volume for long periods.",
    "ex1_vi": "Không nên sử dụng tai nghe ở âm lượng cao trong thời gian dài."
  },
  {
    "id": 158,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "Earphones should not be used at high volume for long periods.",
    "ex1_vi": "Không nên sử dụng tai nghe ở âm lượng cao trong thời gian dài."
  },
  {
    "id": 159,
    "word": "high",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈaɪ/",
    "meaning": "cao",
    "ex1": "People learn about high when studying healthy body functions.",
    "ex1_vi": "Mọi người học về cao khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 160,
    "word": "volume",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɑljum/",
    "meaning": "âm lượng",
    "ex1": "People learn about volume when studying healthy body functions.",
    "ex1_vi": "Mọi người học về âm lượng khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 161,
    "word": "periods",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɪriʌdz/",
    "meaning": "khoảng thời gian",
    "ex1": "People learn about periods when studying healthy body functions.",
    "ex1_vi": "Mọi người học về khoảng thời gian khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 162,
    "word": "nothing",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/nˈʌθɪŋ/",
    "meaning": "không gì",
    "ex1": "People learn about nothing when studying healthy body functions.",
    "ex1_vi": "Mọi người học về không gì khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 163,
    "word": "sharp",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɑrp/",
    "meaning": "sắc nhọn",
    "ex1": "People learn about sharp when studying healthy body functions.",
    "ex1_vi": "Mọi người học về sắc nhọn khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 164,
    "word": "placed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪst/",
    "meaning": "được đặt",
    "ex1": "People learn about placed when studying healthy body functions.",
    "ex1_vi": "Mọi người học về được đặt khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 165,
    "word": "keeping",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈipɪŋ/",
    "meaning": "giữ",
    "ex1": "Keeping the ears dry and having hearing checks can prevent problems.",
    "ex1_vi": "Giữ tai khô và kiểm tra thính lực có thể ngăn ngừa vấn đề."
  },
  {
    "id": 166,
    "word": "dry",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/drˈaɪ/",
    "meaning": "khô",
    "ex1": "Keeping the ears dry and having hearing checks can prevent problems.",
    "ex1_vi": "Giữ tai khô và kiểm tra thính lực có thể ngăn ngừa vấn đề."
  },
  {
    "id": 167,
    "word": "having",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈævɪŋ/",
    "meaning": "việc có",
    "ex1": "People learn about having when studying healthy body functions.",
    "ex1_vi": "Mọi người học về việc có khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 168,
    "word": "hearing",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈirɪŋ/",
    "meaning": "thính giác",
    "ex1": "Doctors explain hearing when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích thính giác khi dạy mọi người về cơ thể người."
  },
  {
    "id": 169,
    "word": "prevent",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prɪvˈɛnt/",
    "meaning": "ngăn ngừa",
    "ex1": "People learn about prevent when studying healthy body functions.",
    "ex1_vi": "Mọi người học về ngăn ngừa khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 170,
    "word": "quiet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kwˈaɪʌt/",
    "meaning": "yên tĩnh",
    "ex1": "Healthy organs stay quiet when people follow good habits.",
    "ex1_vi": "Các cơ quan khỏe mạnh vẫn yên tĩnh khi mọi người duy trì thói quen tốt."
  },
  {
    "id": 171,
    "word": "breaks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/brˈeɪks/",
    "meaning": "khoảng nghỉ",
    "ex1": "Doctors explain breaks when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích khoảng nghỉ khi dạy mọi người về cơ thể người."
  },
  {
    "id": 172,
    "word": "skin",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skɪn/",
    "meaning": "da",
    "ex1": "Healthy habits help protect the skin every day.",
    "ex1_vi": "Thói quen lành mạnh giúp bảo vệ da mỗi ngày."
  },
  {
    "id": 173,
    "word": "largest",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒʌst/",
    "meaning": "lớn nhất",
    "ex1": "The skin is the largest organ of the human body.",
    "ex1_vi": "Da là cơ quan lớn nhất của cơ thể người."
  },
  {
    "id": 174,
    "word": "organ",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔrɡʌn/",
    "meaning": "cơ quan",
    "ex1": "The skin is the largest organ of the human body.",
    "ex1_vi": "Da là cơ quan lớn nhất của cơ thể người."
  },
  {
    "id": 175,
    "word": "human",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hjˈumʌn/",
    "meaning": "con người",
    "ex1": "People learn about human when studying healthy body functions.",
    "ex1_vi": "Mọi người học về con người khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 176,
    "word": "covers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌvɝz/",
    "meaning": "bao phủ",
    "ex1": "It covers the outside of the body and has several layers.",
    "ex1_vi": "Da bao phủ bên ngoài cơ thể và có nhiều lớp."
  },
  {
    "id": 177,
    "word": "outside",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ˈaʊtsˈaɪd/",
    "meaning": "bên ngoài",
    "ex1": "The skin keeps harmful germs and dirt outside the body.",
    "ex1_vi": "Da ngăn vi trùng và bụi bẩn có hại xâm nhập cơ thể."
  },
  {
    "id": 178,
    "word": "layers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈeɪɝz/",
    "meaning": "lớp",
    "ex1": "It covers the outside of the body and has several layers.",
    "ex1_vi": "Da bao phủ bên ngoài cơ thể và có nhiều lớp."
  },
  {
    "id": 179,
    "word": "color",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌlɝ/",
    "meaning": "màu sắc",
    "ex1": "Doctors explain color when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích màu sắc khi dạy mọi người về cơ thể người."
  },
  {
    "id": 180,
    "word": "thickness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈɪknʌs/",
    "meaning": "độ dày",
    "ex1": "Doctors explain thickness when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích độ dày khi dạy mọi người về cơ thể người."
  },
  {
    "id": 181,
    "word": "vary",
    "type": "verb",
    "cat": "v",
    "phonetic": "/vˈɛri/",
    "meaning": "thay đổi",
    "ex1": "Healthy organs can vary normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể thay đổi bình thường suốt ngày."
  },
  {
    "id": 182,
    "word": "but",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bˈʌt/",
    "meaning": "nhưng",
    "ex1": "Body organs have different jobs but work together.",
    "ex1_vi": "Các cơ quan có nhiệm vụ khác nhau nhưng phối hợp với nhau."
  },
  {
    "id": 183,
    "word": "all",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɔl/",
    "meaning": "tất cả",
    "ex1": "All organs need healthy habits and regular medical care.",
    "ex1_vi": "Tất cả cơ quan cần thói quen lành mạnh và chăm sóc y tế đều đặn."
  },
  {
    "id": 184,
    "word": "protective",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/prʌtˈɛktɪv/",
    "meaning": "bảo vệ",
    "ex1": "Healthy organs stay protective when people follow good habits.",
    "ex1_vi": "Các cơ quan khỏe mạnh vẫn bảo vệ khi mọi người duy trì thói quen tốt."
  },
  {
    "id": 185,
    "word": "jobs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɑbz/",
    "meaning": "nhiệm vụ",
    "ex1": "Doctors explain jobs when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích nhiệm vụ khi dạy mọi người về cơ thể người."
  },
  {
    "id": 186,
    "word": "keeps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈips/",
    "meaning": "giữ; ngăn",
    "ex1": "The skin keeps harmful germs and dirt outside the body.",
    "ex1_vi": "Da ngăn vi trùng và bụi bẩn có hại xâm nhập cơ thể."
  },
  {
    "id": 187,
    "word": "harmful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑrmfʌl/",
    "meaning": "có hại",
    "ex1": "People learn about harmful when studying healthy body functions.",
    "ex1_vi": "Mọi người học về có hại khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 188,
    "word": "germs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɝmz/",
    "meaning": "vi trùng",
    "ex1": "People learn about germs when studying healthy body functions.",
    "ex1_vi": "Mọi người học về vi trùng khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 189,
    "word": "dirt",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɝt/",
    "meaning": "bụi bẩn",
    "ex1": "People learn about dirt when studying healthy body functions.",
    "ex1_vi": "Mọi người học về bụi bẩn khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 190,
    "word": "control",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntrˈoʊl/",
    "meaning": "kiểm soát",
    "ex1": "Healthy organs can control normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể kiểm soát bình thường suốt ngày."
  },
  {
    "id": 191,
    "word": "temperature",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛmprʌtʃɝ/",
    "meaning": "nhiệt độ",
    "ex1": "The body uses temperature as part of normal daily functions.",
    "ex1_vi": "Cơ thể sử dụng nhiệt độ như một phần của các chức năng hằng ngày."
  },
  {
    "id": 192,
    "word": "sweat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/swˈɛt/",
    "meaning": "mồ hôi",
    "ex1": "The body uses sweat as part of normal daily functions.",
    "ex1_vi": "Cơ thể sử dụng mồ hôi như một phần của các chức năng hằng ngày."
  },
  {
    "id": 193,
    "word": "allows",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌlˈaʊz/",
    "meaning": "cho phép",
    "ex1": "It also allows us to feel heat, cold, pressure, pain, and touch.",
    "ex1_vi": "Da cũng cho phép chúng ta cảm nhận nóng, lạnh, áp lực, đau và xúc giác."
  },
  {
    "id": 194,
    "word": "feel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈil/",
    "meaning": "cảm thấy",
    "ex1": "It also allows us to feel heat, cold, pressure, pain, and touch.",
    "ex1_vi": "Da cũng cho phép chúng ta cảm nhận nóng, lạnh, áp lực, đau và xúc giác."
  },
  {
    "id": 195,
    "word": "heat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈit/",
    "meaning": "nóng; nhiệt",
    "ex1": "People learn about heat when studying healthy body functions.",
    "ex1_vi": "Mọi người học về nóng; nhiệt khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 196,
    "word": "cold",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈoʊld/",
    "meaning": "lạnh",
    "ex1": "People learn about cold when studying healthy body functions.",
    "ex1_vi": "Mọi người học về lạnh khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 197,
    "word": "pressure",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɛʃɝ/",
    "meaning": "áp lực",
    "ex1": "People learn about pressure when studying healthy body functions.",
    "ex1_vi": "Mọi người học về áp lực khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 198,
    "word": "pain",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈeɪn/",
    "meaning": "đau",
    "ex1": "People learn about pain when studying healthy body functions.",
    "ex1_vi": "Mọi người học về đau khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 199,
    "word": "touch",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈʌtʃ/",
    "meaning": "xúc giác",
    "ex1": "People learn about touch when studying healthy body functions.",
    "ex1_vi": "Mọi người học về xúc giác khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 200,
    "word": "wash",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɑʃ/",
    "meaning": "rửa",
    "ex1": "Healthy organs can wash normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể rửa bình thường suốt ngày."
  },
  {
    "id": 201,
    "word": "gently",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/dʒˈɛntli/",
    "meaning": "nhẹ nhàng",
    "ex1": "Body organs work gently when healthy habits are maintained.",
    "ex1_vi": "Các cơ quan hoạt động nhẹ nhàng khi duy trì thói quen lành mạnh."
  },
  {
    "id": 202,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "Healthy organs can use normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể sử dụng bình thường suốt ngày."
  },
  {
    "id": 203,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "trong lành; tươi",
    "ex1": "People learn about fresh when studying healthy body functions.",
    "ex1_vi": "Mọi người học về trong lành; tươi khi tìm hiểu các chức năng cơ thể khỏe mạnh."
  },
  {
    "id": 204,
    "word": "damage",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈæmʌdʒ/",
    "meaning": "làm tổn thương",
    "ex1": "Doctors explain damage when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích làm tổn thương khi dạy mọi người về cơ thể người."
  },
  {
    "id": 205,
    "word": "so",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/sˈoʊ/",
    "meaning": "vì vậy; nên",
    "ex1": "People use so naturally when describing how body organs work.",
    "ex1_vi": "Mọi người dùng “so” tự nhiên khi mô tả cách các cơ quan hoạt động."
  },
  {
    "id": 206,
    "word": "hats",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈæts/",
    "meaning": "mũ",
    "ex1": "Doctors explain hats when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích mũ khi dạy mọi người về cơ thể người."
  },
  {
    "id": 207,
    "word": "sunscreen",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsʌnskriːn/",
    "meaning": "kem chống nắng",
    "ex1": "The body uses sunscreen as part of normal daily functions.",
    "ex1_vi": "Cơ thể sử dụng kem chống nắng như một phần của các chức năng hằng ngày."
  },
  {
    "id": 208,
    "word": "may",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈeɪ/",
    "meaning": "có thể",
    "ex1": "Too much salt may make the kidneys work harder.",
    "ex1_vi": "Quá nhiều muối có thể khiến thận làm việc vất vả hơn."
  },
  {
    "id": 209,
    "word": "provide",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌvˈaɪd/",
    "meaning": "cung cấp",
    "ex1": "Healthy organs can provide normally throughout the day.",
    "ex1_vi": "Các cơ quan khỏe mạnh có thể cung cấp bình thường suốt ngày."
  },
  {
    "id": 210,
    "word": "protection",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prʌtˈɛkʃʌn/",
    "meaning": "sự bảo vệ",
    "ex1": "Doctors explain protection when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích sự bảo vệ khi dạy mọi người về cơ thể người."
  },
  {
    "id": 211,
    "word": "clothes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈoʊðz/",
    "meaning": "quần áo",
    "ex1": "Doctors explain clothes when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích quần áo khi dạy mọi người về cơ thể người."
  },
  {
    "id": 212,
    "word": "care",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɛr/",
    "meaning": "sự chăm sóc",
    "ex1": "Doctors explain care when teaching people about the human body.",
    "ex1_vi": "Bác sĩ giải thích sự chăm sóc khi dạy mọi người về cơ thể người."
  },
  {
    "id": 213,
    "word": "moisturizer",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈmɔɪstʃəraɪzər/",
    "meaning": "kem dưỡng ẩm",
    "ex1": "The body uses moisturizer as part of normal daily functions.",
    "ex1_vi": "Cơ thể sử dụng kem dưỡng ẩm như một phần của các chức năng hằng ngày."
  }
];

const newReadingVocabOrder = [
  "intestines",
  "long",
  "soft",
  "organs",
  "inside",
  "abdomen",
  "include",
  "small",
  "intestine",
  "and",
  "large",
  "together",
  "form",
  "important",
  "part",
  "digestive",
  "system",
  "help",
  "process",
  "food",
  "receives",
  "stomach",
  "absorbs",
  "most",
  "nutrients",
  "water",
  "forms",
  "solid",
  "waste",
  "helpful",
  "bacteria",
  "also",
  "live",
  "there",
  "support",
  "digestion",
  "general",
  "health",
  "keep",
  "healthy",
  "people",
  "should",
  "eat",
  "vegetables",
  "fruits",
  "whole",
  "grains",
  "foods",
  "contain",
  "fiber",
  "which",
  "helps",
  "move",
  "easily",
  "drinking",
  "enough",
  "exercising",
  "regularly",
  "useful",
  "clean",
  "regular",
  "meals",
  "can",
  "reduce",
  "intestinal",
  "problems",
  "slow",
  "eating",
  "work",
  "comfortably",
  "eyes",
  "face",
  "sit",
  "eye",
  "sockets",
  "protected",
  "eyelids",
  "eyelashes",
  "each",
  "has",
  "several",
  "parts",
  "collect",
  "light",
  "send",
  "information",
  "brain",
  "see",
  "colors",
  "shapes",
  "distances",
  "movement",
  "pupils",
  "change",
  "size",
  "when",
  "becomes",
  "brighter",
  "or",
  "darker",
  "protect",
  "read",
  "good",
  "rest",
  "after",
  "using",
  "screens",
  "looking",
  "far",
  "away",
  "short",
  "time",
  "tiredness",
  "sunglasses",
  "strong",
  "sunlight",
  "hands",
  "used",
  "around",
  "checks",
  "find",
  "vision",
  "early",
  "sleep",
  "gives",
  "ears",
  "both",
  "sides",
  "head",
  "ear",
  "outer",
  "middle",
  "inner",
  "receive",
  "sounds",
  "body",
  "stay",
  "balanced",
  "sound",
  "waves",
  "enter",
  "travel",
  "inward",
  "bones",
  "pass",
  "signals",
  "then",
  "where",
  "become",
  "meaningful",
  "avoid",
  "very",
  "loud",
  "music",
  "noisy",
  "places",
  "earphones",
  "not",
  "high",
  "volume",
  "periods",
  "nothing",
  "sharp",
  "placed",
  "keeping",
  "dry",
  "having",
  "hearing",
  "prevent",
  "quiet",
  "breaks",
  "skin",
  "largest",
  "organ",
  "human",
  "covers",
  "outside",
  "layers",
  "color",
  "thickness",
  "vary",
  "but",
  "all",
  "protective",
  "jobs",
  "keeps",
  "harmful",
  "germs",
  "dirt",
  "control",
  "temperature",
  "sweat",
  "allows",
  "feel",
  "heat",
  "cold",
  "pressure",
  "pain",
  "touch",
  "wash",
  "gently",
  "use",
  "fresh",
  "damage",
  "so",
  "hats",
  "sunscreen",
  "may",
  "provide",
  "protection",
  "clothes",
  "care",
  "moisturizer"
];
