// ===== food01 VOCABULARY =====

const lessonVocabularyWords = [
  "popular",
  "street",
  "food",
  "countries",
  "around",
  "world",
  "people",
  "enjoy",
  "eating",
  "quick",
  "tasty",
  "meals",
  "small",
  "stalls",
  "carts",
  "foods",
  "include",
  "sandwiches",
  "noodles",
  "grilled",
  "meat",
  "fried",
  "rice",
  "and",
  "fresh",
  "fruit",
  "usually",
  "cheap",
  "easy",
  "find",
  "busy",
  "places",
  "sellers",
  "cook",
  "front",
  "customers",
  "smells",
  "delicious",
  "looks",
  "colorful",
  "buy",
  "way",
  "work",
  "school",
  "home",
  "can",
  "eat",
  "while",
  "walking",
  "sitting",
  "nearby",
  "important",
  "part",
  "local",
  "culture",
  "brings",
  "together",
  "lets",
  "visitors",
  "traditional",
  "flavors",
  "travelers",
  "trying",
  "different",
  "wherever",
  "go",
  "buying",
  "simple",
  "enjoyable",
  "visit",
  "when",
  "feel",
  "hungry",
  "want",
  "meal",
  "look",
  "menu",
  "choose",
  "favorite",
  "order",
  "seller",
  "most",
  "pay",
  "cash",
  "mobile",
  "payment",
  "app",
  "prepares",
  "carefully",
  "serves",
  "wait",
  "only",
  "minutes",
  "receiving",
  "often",
  "drinks",
  "desserts",
  "make",
  "complete",
  "fast",
  "convenient",
  "affordable",
  "good",
  "choice",
  "without",
  "spending",
  "much",
  "money",
  "chicken",
  "has",
  "tender",
  "vegetables",
  "sauce",
  "warm",
  "filling",
  "because",
  "wonderful",
  "smell",
  "rich",
  "flavor",
  "friendly",
  "near",
  "cooks",
  "over",
  "hot",
  "charcoal",
  "salad",
  "clean",
  "prepared",
  "every",
  "day",
  "family",
  "friends",
  "always",
  "makes",
  "happy",
  "never",
  "get",
  "tired",
  "great",
  "taste"
];

const newVocabData = [
  {
    "id": 1,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "Street food is popular in many countries around the world.",
    "ex1_vi": "Đồ ăn đường phố phổ biến ở nhiều quốc gia trên thế giới."
  },
  {
    "id": 2,
    "word": "street",
    "type": "noun",
    "cat": "n",
    "phonetic": "/strˈit/",
    "meaning": "đường phố",
    "ex1": "Street food is popular in many countries around the world.",
    "ex1_vi": "Đồ ăn đường phố phổ biến ở nhiều quốc gia trên thế giới."
  },
  {
    "id": 3,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thức ăn",
    "ex1": "At a local market, street food is popular in many countries around the world.",
    "ex1_vi": "Tại một khu chợ địa phương, đồ ăn đường phố phổ biến ở nhiều quốc gia trên thế giới."
  },
  {
    "id": 4,
    "word": "countries",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌntriz/",
    "meaning": "quốc gia",
    "ex1": "In everyday city life, street food is popular in many countries around the world.",
    "ex1_vi": "Trong cuộc sống thành thị hằng ngày, đồ ăn đường phố phổ biến ở nhiều quốc gia trên thế giới."
  },
  {
    "id": 5,
    "word": "around",
    "type": "preposition",
    "cat": "prep",
    "phonetic": "/ɝˈaʊnd/",
    "meaning": "xung quanh; quanh",
    "ex1": "At an evening market, street food is popular in many countries around the world.",
    "ex1_vi": "Tại một khu chợ buổi tối, đồ ăn đường phố phổ biến ở nhiều quốc gia trên thế giới."
  },
  {
    "id": 6,
    "word": "world",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝld/",
    "meaning": "thế giới",
    "ex1": "In this street food lesson, street food is popular in many countries around the world.",
    "ex1_vi": "Trong bài học về đồ ăn đường phố này, đồ ăn đường phố phổ biến ở nhiều quốc gia trên thế giới."
  },
  {
    "id": 7,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "People enjoy eating quick, tasty meals from small food stalls or carts.",
    "ex1_vi": "Mọi người thích ăn những bữa ăn nhanh và ngon từ các quầy hoặc xe bán đồ ăn nhỏ."
  },
  {
    "id": 8,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thích; tận hưởng",
    "ex1": "People enjoy eating quick, tasty meals from small food stalls or carts.",
    "ex1_vi": "Mọi người thích ăn những bữa ăn nhanh và ngon từ các quầy hoặc xe bán đồ ăn nhỏ."
  },
  {
    "id": 9,
    "word": "eating",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/ˈitɪŋ/",
    "meaning": "việc ăn",
    "ex1": "In this street food lesson, people enjoy eating quick, tasty meals from small food stalls or carts.",
    "ex1_vi": "Trong bài học về đồ ăn đường phố này, mọi người thích ăn những bữa ăn nhanh và ngon từ các quầy hoặc xe bán đồ ăn nhỏ."
  },
  {
    "id": 10,
    "word": "quick",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kwˈɪk/",
    "meaning": "nhanh",
    "ex1": "At a busy food stall, people enjoy eating quick, tasty meals from small food stalls or carts.",
    "ex1_vi": "Tại một quầy đồ ăn đông khách, mọi người thích ăn những bữa ăn nhanh và ngon từ các quầy hoặc xe bán đồ ăn nhỏ."
  },
  {
    "id": 11,
    "word": "tasty",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈeɪsti/",
    "meaning": "ngon",
    "ex1": "During a quick meal, people enjoy eating quick, tasty meals from small food stalls or carts.",
    "ex1_vi": "Trong một bữa ăn nhanh, mọi người thích ăn những bữa ăn nhanh và ngon từ các quầy hoặc xe bán đồ ăn nhỏ."
  },
  {
    "id": 12,
    "word": "meals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈilz/",
    "meaning": "bữa ăn",
    "ex1": "At a local market, people enjoy eating quick, tasty meals from small food stalls or carts.",
    "ex1_vi": "Tại một khu chợ địa phương, mọi người thích ăn những bữa ăn nhanh và ngon từ các quầy hoặc xe bán đồ ăn nhỏ."
  },
  {
    "id": 13,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "In everyday city life, people enjoy eating quick, tasty meals from small food stalls or carts.",
    "ex1_vi": "Trong cuộc sống thành thị hằng ngày, mọi người thích ăn những bữa ăn nhanh và ngon từ các quầy hoặc xe bán đồ ăn nhỏ."
  },
  {
    "id": 14,
    "word": "stalls",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈɔlz/",
    "meaning": "quầy hàng",
    "ex1": "At an evening market, people enjoy eating quick, tasty meals from small food stalls or carts.",
    "ex1_vi": "Tại một khu chợ buổi tối, mọi người thích ăn những bữa ăn nhanh và ngon từ các quầy hoặc xe bán đồ ăn nhỏ."
  },
  {
    "id": 15,
    "word": "carts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑrts/",
    "meaning": "xe đẩy bán hàng",
    "ex1": "In this street food lesson, people enjoy eating quick, tasty meals from small food stalls or carts.",
    "ex1_vi": "Trong bài học về đồ ăn đường phố này, mọi người thích ăn những bữa ăn nhanh và ngon từ các quầy hoặc xe bán đồ ăn nhỏ."
  },
  {
    "id": 16,
    "word": "foods",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈudz/",
    "meaning": "thức ăn",
    "ex1": "Popular street foods include sandwiches, noodles, grilled meat, fried rice, and fresh fruit.",
    "ex1_vi": "Những món ăn đường phố phổ biến gồm bánh mì kẹp, mì, thịt nướng, cơm chiên và trái cây tươi."
  },
  {
    "id": 17,
    "word": "include",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪnklˈud/",
    "meaning": "bao gồm",
    "ex1": "Popular street foods include sandwiches, noodles, grilled meat, fried rice, and fresh fruit.",
    "ex1_vi": "Những món ăn đường phố phổ biến gồm bánh mì kẹp, mì, thịt nướng, cơm chiên và trái cây tươi."
  },
  {
    "id": 18,
    "word": "sandwiches",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈændwɪtʃɪz/",
    "meaning": "bánh mì kẹp",
    "ex1": "During a food trip, popular street foods include sandwiches, noodles, grilled meat, fried rice, and fresh fruit.",
    "ex1_vi": "Trong một chuyến khám phá ẩm thực, những món ăn đường phố phổ biến gồm bánh mì kẹp, mì, thịt nướng, cơm chiên và trái cây tươi."
  },
  {
    "id": 19,
    "word": "noodles",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈudʌlz/",
    "meaning": "mì",
    "ex1": "For many travelers, popular street foods include sandwiches, noodles, grilled meat, fried rice, and fresh fruit.",
    "ex1_vi": "Đối với nhiều du khách, những món ăn đường phố phổ biến gồm bánh mì kẹp, mì, thịt nướng, cơm chiên và trái cây tươi."
  },
  {
    "id": 20,
    "word": "grilled",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈɪld/",
    "meaning": "nướng",
    "ex1": "In street food culture, popular street foods include sandwiches, noodles, grilled meat, fried rice, and fresh fruit.",
    "ex1_vi": "Trong văn hóa ẩm thực đường phố, những món ăn đường phố phổ biến gồm bánh mì kẹp, mì, thịt nướng, cơm chiên và trái cây tươi."
  },
  {
    "id": 21,
    "word": "meat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈit/",
    "meaning": "thịt",
    "ex1": "For local customers, popular street foods include sandwiches, noodles, grilled meat, fried rice, and fresh fruit.",
    "ex1_vi": "Đối với khách hàng địa phương, những món ăn đường phố phổ biến gồm bánh mì kẹp, mì, thịt nướng, cơm chiên và trái cây tươi."
  },
  {
    "id": 22,
    "word": "fried",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈaɪd/",
    "meaning": "chiên; rán",
    "ex1": "On a busy day, popular street foods include sandwiches, noodles, grilled meat, fried rice, and fresh fruit.",
    "ex1_vi": "Vào một ngày bận rộn, những món ăn đường phố phổ biến gồm bánh mì kẹp, mì, thịt nướng, cơm chiên và trái cây tươi."
  },
  {
    "id": 23,
    "word": "rice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪs/",
    "meaning": "cơm; gạo",
    "ex1": "For hungry visitors, popular street foods include sandwiches, noodles, grilled meat, fried rice, and fresh fruit.",
    "ex1_vi": "Đối với những du khách đang đói, những món ăn đường phố phổ biến gồm bánh mì kẹp, mì, thịt nướng, cơm chiên và trái cây tươi."
  },
  {
    "id": 24,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "During a food trip, popular street foods include sandwiches, noodles, grilled meat, fried rice, and fresh fruit.",
    "ex1_vi": "Trong một chuyến khám phá ẩm thực, những món ăn đường phố phổ biến gồm bánh mì kẹp, mì, thịt nướng, cơm chiên và trái cây tươi."
  },
  {
    "id": 25,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi; trong lành",
    "ex1": "For many travelers, popular street foods include sandwiches, noodles, grilled meat, fried rice, and fresh fruit.",
    "ex1_vi": "Đối với nhiều du khách, những món ăn đường phố phổ biến gồm bánh mì kẹp, mì, thịt nướng, cơm chiên và trái cây tươi."
  },
  {
    "id": 26,
    "word": "fruit",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈut/",
    "meaning": "trái cây",
    "ex1": "In street food culture, popular street foods include sandwiches, noodles, grilled meat, fried rice, and fresh fruit.",
    "ex1_vi": "Trong văn hóa ẩm thực đường phố, những món ăn đường phố phổ biến gồm bánh mì kẹp, mì, thịt nướng, cơm chiên và trái cây tươi."
  },
  {
    "id": 27,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "These foods are usually cheap and easy to find in busy places.",
    "ex1_vi": "Những món này thường rẻ và dễ tìm ở những nơi đông đúc."
  },
  {
    "id": 28,
    "word": "cheap",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tʃˈip/",
    "meaning": "rẻ",
    "ex1": "These foods are usually cheap and easy to find in busy places.",
    "ex1_vi": "Những món này thường rẻ và dễ tìm ở những nơi đông đúc."
  },
  {
    "id": 29,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "In everyday city life, these foods are usually cheap and easy to find in busy places.",
    "ex1_vi": "Trong cuộc sống thành thị hằng ngày, những món này thường rẻ và dễ tìm ở những nơi đông đúc."
  },
  {
    "id": 30,
    "word": "find",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪnd/",
    "meaning": "phát hiện; tìm thấy",
    "ex1": "At an evening market, these foods are usually cheap and easy to find in busy places.",
    "ex1_vi": "Tại một khu chợ buổi tối, những món này thường rẻ và dễ tìm ở những nơi đông đúc."
  },
  {
    "id": 31,
    "word": "busy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɪzi/",
    "meaning": "nhộn nhịp",
    "ex1": "In this street food lesson, these foods are usually cheap and easy to find in busy places.",
    "ex1_vi": "Trong bài học về đồ ăn đường phố này, những món này thường rẻ và dễ tìm ở những nơi đông đúc."
  },
  {
    "id": 32,
    "word": "places",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪsʌz/",
    "meaning": "những nơi",
    "ex1": "At a busy food stall, these foods are usually cheap and easy to find in busy places.",
    "ex1_vi": "Tại một quầy đồ ăn đông khách, những món này thường rẻ và dễ tìm ở những nơi đông đúc."
  },
  {
    "id": 33,
    "word": "sellers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛlɝz/",
    "meaning": "những người bán hàng",
    "ex1": "Street food sellers cook meals in front of customers.",
    "ex1_vi": "Những người bán đồ ăn đường phố nấu các món ăn ngay trước mặt khách hàng."
  },
  {
    "id": 34,
    "word": "cook",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʊk/",
    "meaning": "nấu ăn",
    "ex1": "Street food sellers cook meals in front of customers.",
    "ex1_vi": "Những người bán đồ ăn đường phố nấu các món ăn ngay trước mặt khách hàng."
  },
  {
    "id": 35,
    "word": "front",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈʌnt/",
    "meaning": "phía trước",
    "ex1": "At a busy food stall, street food sellers cook meals in front of customers.",
    "ex1_vi": "Tại một quầy đồ ăn đông khách, những người bán đồ ăn đường phố nấu các món ăn ngay trước mặt khách hàng."
  },
  {
    "id": 36,
    "word": "customers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌstʌmɝz/",
    "meaning": "khách hàng",
    "ex1": "During a quick meal, street food sellers cook meals in front of customers.",
    "ex1_vi": "Trong một bữa ăn nhanh, những người bán đồ ăn đường phố nấu các món ăn ngay trước mặt khách hàng."
  },
  {
    "id": 37,
    "word": "smells",
    "type": "verb",
    "cat": "v",
    "phonetic": "/smˈɛlz/",
    "meaning": "có mùi; ngửi",
    "ex1": "The food smells delicious and looks colorful.",
    "ex1_vi": "Thức ăn có mùi thơm ngon và trông đầy màu sắc."
  },
  {
    "id": 38,
    "word": "delicious",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dɪlˈɪʃʌs/",
    "meaning": "ngon",
    "ex1": "The food smells delicious and looks colorful.",
    "ex1_vi": "Thức ăn có mùi thơm ngon và trông đầy màu sắc."
  },
  {
    "id": 39,
    "word": "looks",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊks/",
    "meaning": "trông có vẻ",
    "ex1": "At a local market, the food smells delicious and looks colorful.",
    "ex1_vi": "Tại một khu chợ địa phương, thức ăn có mùi thơm ngon và trông đầy màu sắc."
  },
  {
    "id": 40,
    "word": "colorful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌlɝfʌl/",
    "meaning": "đầy màu sắc",
    "ex1": "In everyday city life, the food smells delicious and looks colorful.",
    "ex1_vi": "Trong cuộc sống thành thị hằng ngày, thức ăn có mùi thơm ngon và trông đầy màu sắc."
  },
  {
    "id": 41,
    "word": "buy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈaɪ/",
    "meaning": "mua",
    "ex1": "Many people buy street food on their way to work, school, or home.",
    "ex1_vi": "Nhiều người mua đồ ăn đường phố trên đường đi làm, đi học hoặc về nhà."
  },
  {
    "id": 42,
    "word": "way",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪ/",
    "meaning": "cách",
    "ex1": "Many people buy street food on their way to work, school, or home.",
    "ex1_vi": "Nhiều người mua đồ ăn đường phố trên đường đi làm, đi học hoặc về nhà."
  },
  {
    "id": 43,
    "word": "work",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝk/",
    "meaning": "hoạt động; làm việc",
    "ex1": "At an evening market, many people buy street food on their way to work, school, or home.",
    "ex1_vi": "Tại một khu chợ buổi tối, nhiều người mua đồ ăn đường phố trên đường đi làm, đi học hoặc về nhà."
  },
  {
    "id": 44,
    "word": "school",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈul/",
    "meaning": "trường học",
    "ex1": "In this street food lesson, many people buy street food on their way to work, school, or home.",
    "ex1_vi": "Trong bài học về đồ ăn đường phố này, nhiều người mua đồ ăn đường phố trên đường đi làm, đi học hoặc về nhà."
  },
  {
    "id": 45,
    "word": "home",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊm/",
    "meaning": "nơi sinh sống; nhà",
    "ex1": "At a busy food stall, many people buy street food on their way to work, school, or home.",
    "ex1_vi": "Tại một quầy đồ ăn đông khách, nhiều người mua đồ ăn đường phố trên đường đi làm, đi học hoặc về nhà."
  },
  {
    "id": 46,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "They can eat while walking or sitting nearby.",
    "ex1_vi": "Họ có thể ăn trong khi đi bộ hoặc ngồi gần đó."
  },
  {
    "id": 47,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "They can eat while walking or sitting nearby.",
    "ex1_vi": "Họ có thể ăn trong khi đi bộ hoặc ngồi gần đó."
  },
  {
    "id": 48,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "For local customers, they can eat while walking or sitting nearby.",
    "ex1_vi": "Đối với khách hàng địa phương, họ có thể ăn trong khi đi bộ hoặc ngồi gần đó."
  },
  {
    "id": 49,
    "word": "walking",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/wˈɔkɪŋ/",
    "meaning": "việc đi bộ",
    "ex1": "On a busy day, they can eat while walking or sitting nearby.",
    "ex1_vi": "Vào một ngày bận rộn, họ có thể ăn trong khi đi bộ hoặc ngồi gần đó."
  },
  {
    "id": 50,
    "word": "sitting",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/sˈɪtɪŋ/",
    "meaning": "việc ngồi; đang ngồi",
    "ex1": "For hungry visitors, they can eat while walking or sitting nearby.",
    "ex1_vi": "Đối với những du khách đang đói, họ có thể ăn trong khi đi bộ hoặc ngồi gần đó."
  },
  {
    "id": 51,
    "word": "nearby",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɪrbˈaɪ/",
    "meaning": "gần đó",
    "ex1": "During a food trip, they can eat while walking or sitting nearby.",
    "ex1_vi": "Trong một chuyến khám phá ẩm thực, họ có thể ăn trong khi đi bộ hoặc ngồi gần đó."
  },
  {
    "id": 52,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔrtʌnt/",
    "meaning": "quan trọng",
    "ex1": "Street food is an important part of local culture.",
    "ex1_vi": "Đồ ăn đường phố là một phần quan trọng của văn hóa địa phương."
  },
  {
    "id": 53,
    "word": "part",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrt/",
    "meaning": "phần",
    "ex1": "Street food is an important part of local culture.",
    "ex1_vi": "Đồ ăn đường phố là một phần quan trọng của văn hóa địa phương."
  },
  {
    "id": 54,
    "word": "local",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈoʊkʌl/",
    "meaning": "địa phương",
    "ex1": "During a food trip, street food is an important part of local culture.",
    "ex1_vi": "Trong một chuyến khám phá ẩm thực, đồ ăn đường phố là một phần quan trọng của văn hóa địa phương."
  },
  {
    "id": 55,
    "word": "culture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌltʃɝ/",
    "meaning": "văn hóa",
    "ex1": "For many travelers, street food is an important part of local culture.",
    "ex1_vi": "Đối với nhiều du khách, đồ ăn đường phố là một phần quan trọng của văn hóa địa phương."
  },
  {
    "id": 56,
    "word": "brings",
    "type": "verb",
    "cat": "v",
    "phonetic": "/brˈɪŋz/",
    "meaning": "mang lại",
    "ex1": "It brings people together and lets visitors enjoy traditional flavors.",
    "ex1_vi": "Nó gắn kết mọi người và cho phép du khách thưởng thức những hương vị truyền thống."
  },
  {
    "id": 57,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌɡˈɛðɝ/",
    "meaning": "cùng nhau",
    "ex1": "It brings people together and lets visitors enjoy traditional flavors.",
    "ex1_vi": "Nó gắn kết mọi người và cho phép du khách thưởng thức những hương vị truyền thống."
  },
  {
    "id": 58,
    "word": "lets",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɛts/",
    "meaning": "cho phép",
    "ex1": "In street food culture, it brings people together and lets visitors enjoy traditional flavors.",
    "ex1_vi": "Trong văn hóa ẩm thực đường phố, nó gắn kết mọi người và cho phép du khách thưởng thức những hương vị truyền thống."
  },
  {
    "id": 59,
    "word": "visitors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪzɪtɝz/",
    "meaning": "du khách",
    "ex1": "For local customers, it brings people together and lets visitors enjoy traditional flavors.",
    "ex1_vi": "Đối với khách hàng địa phương, nó gắn kết mọi người và cho phép du khách thưởng thức những hương vị truyền thống."
  },
  {
    "id": 60,
    "word": "traditional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trʌdˈɪʃʌnʌl/",
    "meaning": "truyền thống",
    "ex1": "On a busy day, it brings people together and lets visitors enjoy traditional flavors.",
    "ex1_vi": "Vào một ngày bận rộn, nó gắn kết mọi người và cho phép du khách thưởng thức những hương vị truyền thống."
  },
  {
    "id": 61,
    "word": "flavors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝz/",
    "meaning": "các hương vị",
    "ex1": "For hungry visitors, it brings people together and lets visitors enjoy traditional flavors.",
    "ex1_vi": "Đối với những du khách đang đói, nó gắn kết mọi người và cho phép du khách thưởng thức những hương vị truyền thống."
  },
  {
    "id": 62,
    "word": "travelers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈævʌlɝz/",
    "meaning": "du khách; người đi đường",
    "ex1": "Many travelers like trying different street foods wherever they go.",
    "ex1_vi": "Nhiều du khách thích thử các món ăn đường phố khác nhau ở bất cứ nơi nào họ đến."
  },
  {
    "id": 63,
    "word": "trying",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/trˈaɪɪŋ/",
    "meaning": "việc thử",
    "ex1": "Many travelers like trying different street foods wherever they go.",
    "ex1_vi": "Nhiều du khách thích thử các món ăn đường phố khác nhau ở bất cứ nơi nào họ đến."
  },
  {
    "id": 64,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "For hungry visitors, many travelers like trying different street foods wherever they go.",
    "ex1_vi": "Đối với những du khách đang đói, nhiều du khách thích thử các món ăn đường phố khác nhau ở bất cứ nơi nào họ đến."
  },
  {
    "id": 65,
    "word": "wherever",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wɛrˈɛvɝ/",
    "meaning": "bất cứ nơi đâu",
    "ex1": "During a food trip, many travelers like trying different street foods wherever they go.",
    "ex1_vi": "Trong một chuyến khám phá ẩm thực, nhiều du khách thích thử các món ăn đường phố khác nhau ở bất cứ nơi nào họ đến."
  },
  {
    "id": 66,
    "word": "go",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈoʊ/",
    "meaning": "đi",
    "ex1": "For many travelers, many travelers like trying different street foods wherever they go.",
    "ex1_vi": "Đối với nhiều du khách, nhiều du khách thích thử các món ăn đường phố khác nhau ở bất cứ nơi nào họ đến."
  },
  {
    "id": 67,
    "word": "buying",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈaɪɪŋ/",
    "meaning": "mua",
    "ex1": "Buying street food is simple and enjoyable.",
    "ex1_vi": "Mua đồ ăn đường phố rất đơn giản và thú vị."
  },
  {
    "id": 68,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "Buying street food is simple and enjoyable.",
    "ex1_vi": "Mua đồ ăn đường phố rất đơn giản và thú vị."
  },
  {
    "id": 69,
    "word": "enjoyable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɛndʒˈɔɪʌbʌl/",
    "meaning": "thú vị; dễ chịu",
    "ex1": "In this street food lesson, buying street food is simple and enjoyable.",
    "ex1_vi": "Trong bài học về đồ ăn đường phố này, mua đồ ăn đường phố rất đơn giản và thú vị."
  },
  {
    "id": 70,
    "word": "visit",
    "type": "verb",
    "cat": "v",
    "phonetic": "/vˈɪzɪt/",
    "meaning": "thăm",
    "ex1": "People visit food stalls when they feel hungry or want a quick meal.",
    "ex1_vi": "Mọi người ghé các quầy đồ ăn khi họ cảm thấy đói hoặc muốn một bữa ăn nhanh."
  },
  {
    "id": 71,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "People visit food stalls when they feel hungry or want a quick meal.",
    "ex1_vi": "Mọi người ghé các quầy đồ ăn khi họ cảm thấy đói hoặc muốn một bữa ăn nhanh."
  },
  {
    "id": 72,
    "word": "feel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈil/",
    "meaning": "cảm thấy",
    "ex1": "For local customers, people visit food stalls when they feel hungry or want a quick meal.",
    "ex1_vi": "Đối với khách hàng địa phương, mọi người ghé các quầy đồ ăn khi họ cảm thấy đói hoặc muốn một bữa ăn nhanh."
  },
  {
    "id": 73,
    "word": "hungry",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈʌŋɡri/",
    "meaning": "đói",
    "ex1": "On a busy day, people visit food stalls when they feel hungry or want a quick meal.",
    "ex1_vi": "Vào một ngày bận rộn, mọi người ghé các quầy đồ ăn khi họ cảm thấy đói hoặc muốn một bữa ăn nhanh."
  },
  {
    "id": 74,
    "word": "want",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɑnt/",
    "meaning": "muốn",
    "ex1": "For hungry visitors, people visit food stalls when they feel hungry or want a quick meal.",
    "ex1_vi": "Đối với những du khách đang đói, mọi người ghé các quầy đồ ăn khi họ cảm thấy đói hoặc muốn một bữa ăn nhanh."
  },
  {
    "id": 75,
    "word": "meal",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈil/",
    "meaning": "bữa ăn",
    "ex1": "During a food trip, people visit food stalls when they feel hungry or want a quick meal.",
    "ex1_vi": "Trong một chuyến khám phá ẩm thực, mọi người ghé các quầy đồ ăn khi họ cảm thấy đói hoặc muốn một bữa ăn nhanh."
  },
  {
    "id": 76,
    "word": "look",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊk/",
    "meaning": "nhìn",
    "ex1": "They look at the menu, choose their favorite food, and order it from the seller.",
    "ex1_vi": "Họ xem thực đơn, chọn món yêu thích và gọi món từ người bán."
  },
  {
    "id": 77,
    "word": "menu",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛnju/",
    "meaning": "thực đơn",
    "ex1": "They look at the menu, choose their favorite food, and order it from the seller.",
    "ex1_vi": "Họ xem thực đơn, chọn món yêu thích và gọi món từ người bán."
  },
  {
    "id": 78,
    "word": "choose",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈuz/",
    "meaning": "chọn",
    "ex1": "During a food trip, they look at the menu, choose their favorite food, and order it from the seller.",
    "ex1_vi": "Trong một chuyến khám phá ẩm thực, họ xem thực đơn, chọn món yêu thích và gọi món từ người bán."
  },
  {
    "id": 79,
    "word": "favorite",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈeɪvɝɪt/",
    "meaning": "yêu thích",
    "ex1": "For many travelers, they look at the menu, choose their favorite food, and order it from the seller.",
    "ex1_vi": "Đối với nhiều du khách, họ xem thực đơn, chọn món yêu thích và gọi món từ người bán."
  },
  {
    "id": 80,
    "word": "order",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɔrdɝ/",
    "meaning": "gọi; đặt",
    "ex1": "In street food culture, they look at the menu, choose their favorite food, and order it from the seller.",
    "ex1_vi": "Trong văn hóa ẩm thực đường phố, họ xem thực đơn, chọn món yêu thích và gọi món từ người bán."
  },
  {
    "id": 81,
    "word": "seller",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛlɝ/",
    "meaning": "người bán hàng",
    "ex1": "For local customers, they look at the menu, choose their favorite food, and order it from the seller.",
    "ex1_vi": "Đối với khách hàng địa phương, họ xem thực đơn, chọn món yêu thích và gọi món từ người bán."
  },
  {
    "id": 82,
    "word": "most",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈoʊst/",
    "meaning": "hầu hết",
    "ex1": "Most customers pay with cash or a mobile payment app.",
    "ex1_vi": "Hầu hết khách hàng thanh toán bằng tiền mặt hoặc ứng dụng thanh toán trên điện thoại."
  },
  {
    "id": 83,
    "word": "pay",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pˈeɪ/",
    "meaning": "thanh toán",
    "ex1": "Most customers pay with cash or a mobile payment app.",
    "ex1_vi": "Hầu hết khách hàng thanh toán bằng tiền mặt hoặc ứng dụng thanh toán trên điện thoại."
  },
  {
    "id": 84,
    "word": "cash",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈæʃ/",
    "meaning": "tiền mặt",
    "ex1": "For local customers, most customers pay with cash or a mobile payment app.",
    "ex1_vi": "Đối với khách hàng địa phương, hầu hết khách hàng thanh toán bằng tiền mặt hoặc ứng dụng thanh toán trên điện thoại."
  },
  {
    "id": 85,
    "word": "mobile",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈoʊbʌl/",
    "meaning": "di động",
    "ex1": "On a busy day, most customers pay with cash or a mobile payment app.",
    "ex1_vi": "Vào một ngày bận rộn, hầu hết khách hàng thanh toán bằng tiền mặt hoặc ứng dụng thanh toán trên điện thoại."
  },
  {
    "id": 86,
    "word": "payment",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈeɪmʌnt/",
    "meaning": "thanh toán",
    "ex1": "For hungry visitors, most customers pay with cash or a mobile payment app.",
    "ex1_vi": "Đối với những du khách đang đói, hầu hết khách hàng thanh toán bằng tiền mặt hoặc ứng dụng thanh toán trên điện thoại."
  },
  {
    "id": 87,
    "word": "app",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈæp/",
    "meaning": "ứng dụng",
    "ex1": "During a food trip, most customers pay with cash or a mobile payment app.",
    "ex1_vi": "Trong một chuyến khám phá ẩm thực, hầu hết khách hàng thanh toán bằng tiền mặt hoặc ứng dụng thanh toán trên điện thoại."
  },
  {
    "id": 88,
    "word": "prepares",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pripˈɛrz/",
    "meaning": "chuẩn bị",
    "ex1": "The seller prepares the food carefully and serves it fresh.",
    "ex1_vi": "Người bán chuẩn bị thức ăn cẩn thận và phục vụ khi còn tươi."
  },
  {
    "id": 89,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "The seller prepares the food carefully and serves it fresh.",
    "ex1_vi": "Người bán chuẩn bị thức ăn cẩn thận và phục vụ khi còn tươi."
  },
  {
    "id": 90,
    "word": "serves",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɝvz/",
    "meaning": "phục vụ",
    "ex1": "During a food trip, the seller prepares the food carefully and serves it fresh.",
    "ex1_vi": "Trong một chuyến khám phá ẩm thực, người bán chuẩn bị thức ăn cẩn thận và phục vụ khi còn tươi."
  },
  {
    "id": 91,
    "word": "wait",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈeɪt/",
    "meaning": "chờ",
    "ex1": "Customers usually wait only a few minutes before receiving their meals.",
    "ex1_vi": "Khách hàng thường chỉ chờ vài phút trước khi nhận bữa ăn của mình."
  },
  {
    "id": 92,
    "word": "only",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈoʊnli/",
    "meaning": "chỉ",
    "ex1": "Customers usually wait only a few minutes before receiving their meals.",
    "ex1_vi": "Khách hàng thường chỉ chờ vài phút trước khi nhận bữa ăn của mình."
  },
  {
    "id": 93,
    "word": "minutes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɪnʌts/",
    "meaning": "phút",
    "ex1": "In this street food lesson, customers usually wait only a few minutes before receiving their meals.",
    "ex1_vi": "Trong bài học về đồ ăn đường phố này, khách hàng thường chỉ chờ vài phút trước khi nhận bữa ăn của mình."
  },
  {
    "id": 94,
    "word": "receiving",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/rʌsˈivɪŋ/",
    "meaning": "việc nhận",
    "ex1": "At a busy food stall, customers usually wait only a few minutes before receiving their meals.",
    "ex1_vi": "Tại một quầy đồ ăn đông khách, khách hàng thường chỉ chờ vài phút trước khi nhận bữa ăn của mình."
  },
  {
    "id": 95,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường xuyên",
    "ex1": "They often buy drinks or desserts with their food to make the meal complete.",
    "ex1_vi": "Họ thường mua đồ uống hoặc món tráng miệng cùng thức ăn để bữa ăn đầy đủ hơn."
  },
  {
    "id": 96,
    "word": "drinks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɪŋks/",
    "meaning": "đồ uống",
    "ex1": "They often buy drinks or desserts with their food to make the meal complete.",
    "ex1_vi": "Họ thường mua đồ uống hoặc món tráng miệng cùng thức ăn để bữa ăn đầy đủ hơn."
  },
  {
    "id": 97,
    "word": "desserts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪzˈɝts/",
    "meaning": "món tráng miệng",
    "ex1": "During a quick meal, they often buy drinks or desserts with their food to make the meal complete.",
    "ex1_vi": "Trong một bữa ăn nhanh, họ thường mua đồ uống hoặc món tráng miệng cùng thức ăn để bữa ăn đầy đủ hơn."
  },
  {
    "id": 98,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm cho",
    "ex1": "At a local market, they often buy drinks or desserts with their food to make the meal complete.",
    "ex1_vi": "Tại một khu chợ địa phương, họ thường mua đồ uống hoặc món tráng miệng cùng thức ăn để bữa ăn đầy đủ hơn."
  },
  {
    "id": 99,
    "word": "complete",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kʌmplˈit/",
    "meaning": "đầy đủ; hoàn chỉnh",
    "ex1": "In everyday city life, they often buy drinks or desserts with their food to make the meal complete.",
    "ex1_vi": "Trong cuộc sống thành thị hằng ngày, họ thường mua đồ uống hoặc món tráng miệng cùng thức ăn để bữa ăn đầy đủ hơn."
  },
  {
    "id": 100,
    "word": "fast",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈæst/",
    "meaning": "nhanh",
    "ex1": "Buying street food is fast, convenient, and affordable.",
    "ex1_vi": "Mua đồ ăn đường phố nhanh chóng, tiện lợi và phải chăng."
  },
  {
    "id": 101,
    "word": "convenient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kʌnvˈinjʌnt/",
    "meaning": "thuận tiện",
    "ex1": "Buying street food is fast, convenient, and affordable.",
    "ex1_vi": "Mua đồ ăn đường phố nhanh chóng, tiện lợi và phải chăng."
  },
  {
    "id": 102,
    "word": "affordable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌfˈɔrdʌbʌl/",
    "meaning": "có giá phải chăng",
    "ex1": "During a food trip, buying street food is fast, convenient, and affordable.",
    "ex1_vi": "Trong một chuyến khám phá ẩm thực, mua đồ ăn đường phố nhanh chóng, tiện lợi và phải chăng."
  },
  {
    "id": 103,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "It is a good choice for busy people who want tasty food without spending too much money.",
    "ex1_vi": "Đây là lựa chọn tốt cho những người bận rộn muốn món ăn ngon mà không phải tiêu quá nhiều tiền."
  },
  {
    "id": 104,
    "word": "choice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɔɪs/",
    "meaning": "sự lựa chọn",
    "ex1": "It is a good choice for busy people who want tasty food without spending too much money.",
    "ex1_vi": "Đây là lựa chọn tốt cho những người bận rộn muốn món ăn ngon mà không phải tiêu quá nhiều tiền."
  },
  {
    "id": 105,
    "word": "without",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/wɪθˈaʊt/",
    "meaning": "không có; mà không",
    "ex1": "In this street food lesson, it is a good choice for busy people who want tasty food without spending too much money.",
    "ex1_vi": "Trong bài học về đồ ăn đường phố này, đây là lựa chọn tốt cho những người bận rộn muốn món ăn ngon mà không phải tiêu quá nhiều tiền."
  },
  {
    "id": 106,
    "word": "spending",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/spˈɛndɪŋ/",
    "meaning": "việc chi tiêu",
    "ex1": "At a busy food stall, it is a good choice for busy people who want tasty food without spending too much money.",
    "ex1_vi": "Tại một quầy đồ ăn đông khách, đây là lựa chọn tốt cho những người bận rộn muốn món ăn ngon mà không phải tiêu quá nhiều tiền."
  },
  {
    "id": 107,
    "word": "much",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/mˈʌtʃ/",
    "meaning": "nhiều; rất",
    "ex1": "During a quick meal, it is a good choice for busy people who want tasty food without spending too much money.",
    "ex1_vi": "Trong một bữa ăn nhanh, đây là lựa chọn tốt cho những người bận rộn muốn món ăn ngon mà không phải tiêu quá nhiều tiền."
  },
  {
    "id": 108,
    "word": "money",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌni/",
    "meaning": "tiền",
    "ex1": "At a local market, it is a good choice for busy people who want tasty food without spending too much money.",
    "ex1_vi": "Tại một khu chợ địa phương, đây là lựa chọn tốt cho những người bận rộn muốn món ăn ngon mà không phải tiêu quá nhiều tiền."
  },
  {
    "id": 109,
    "word": "chicken",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪkʌn/",
    "meaning": "thịt gà; gà",
    "ex1": "My favorite street food is grilled chicken with rice.",
    "ex1_vi": "Món ăn đường phố yêu thích của tôi là gà nướng với cơm."
  },
  {
    "id": 110,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "It has tender meat, fresh vegetables, and tasty sauce.",
    "ex1_vi": "Món ăn có thịt mềm, rau tươi và nước sốt ngon."
  },
  {
    "id": 111,
    "word": "tender",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈɛndɝ/",
    "meaning": "mềm; mềm mọng",
    "ex1": "It has tender meat, fresh vegetables, and tasty sauce.",
    "ex1_vi": "Món ăn có thịt mềm, rau tươi và nước sốt ngon."
  },
  {
    "id": 112,
    "word": "vegetables",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɛdʒtʌbʌlz/",
    "meaning": "rau củ",
    "ex1": "For hungry visitors, it has tender meat, fresh vegetables, and tasty sauce.",
    "ex1_vi": "Đối với những du khách đang đói, món ăn có thịt mềm, rau tươi và nước sốt ngon."
  },
  {
    "id": 113,
    "word": "sauce",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔs/",
    "meaning": "nước sốt",
    "ex1": "During a food trip, it has tender meat, fresh vegetables, and tasty sauce.",
    "ex1_vi": "Trong một chuyến khám phá ẩm thực, món ăn có thịt mềm, rau tươi và nước sốt ngon."
  },
  {
    "id": 114,
    "word": "warm",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈɔrm/",
    "meaning": "ấm",
    "ex1": "The food is warm, delicious, and filling.",
    "ex1_vi": "Thức ăn ấm, thơm ngon và no bụng."
  },
  {
    "id": 115,
    "word": "filling",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɪlɪŋ/",
    "meaning": "no bụng",
    "ex1": "The food is warm, delicious, and filling.",
    "ex1_vi": "Thức ăn ấm, thơm ngon và no bụng."
  },
  {
    "id": 116,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "I like eating it because it has a wonderful smell and rich flavor.",
    "ex1_vi": "Tôi thích ăn món này vì nó có mùi thơm tuyệt vời và hương vị đậm đà."
  },
  {
    "id": 117,
    "word": "wonderful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈʌndɝfʌl/",
    "meaning": "tuyệt vời",
    "ex1": "I like eating it because it has a wonderful smell and rich flavor.",
    "ex1_vi": "Tôi thích ăn món này vì nó có mùi thơm tuyệt vời và hương vị đậm đà."
  },
  {
    "id": 118,
    "word": "smell",
    "type": "verb",
    "cat": "v",
    "phonetic": "/smˈɛl/",
    "meaning": "ngửi",
    "ex1": "In street food culture, i like eating it because it has a wonderful smell and rich flavor.",
    "ex1_vi": "Trong văn hóa ẩm thực đường phố, tôi thích ăn món này vì nó có mùi thơm tuyệt vời và hương vị đậm đà."
  },
  {
    "id": 119,
    "word": "rich",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɪtʃ/",
    "meaning": "phong phú",
    "ex1": "For local customers, i like eating it because it has a wonderful smell and rich flavor.",
    "ex1_vi": "Đối với khách hàng địa phương, tôi thích ăn món này vì nó có mùi thơm tuyệt vời và hương vị đậm đà."
  },
  {
    "id": 120,
    "word": "flavor",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝ/",
    "meaning": "hương vị",
    "ex1": "On a busy day, i like eating it because it has a wonderful smell and rich flavor.",
    "ex1_vi": "Vào một ngày bận rộn, tôi thích ăn món này vì nó có mùi thơm tuyệt vời và hương vị đậm đà."
  },
  {
    "id": 121,
    "word": "friendly",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛndli/",
    "meaning": "thân thiện",
    "ex1": "I usually buy this meal from a friendly street food seller near my school.",
    "ex1_vi": "Tôi thường mua bữa ăn này từ một người bán đồ ăn đường phố thân thiện gần trường."
  },
  {
    "id": 122,
    "word": "near",
    "type": "preposition",
    "cat": "prep",
    "phonetic": "/nˈɪr/",
    "meaning": "gần",
    "ex1": "I usually buy this meal from a friendly street food seller near my school.",
    "ex1_vi": "Tôi thường mua bữa ăn này từ một người bán đồ ăn đường phố thân thiện gần trường."
  },
  {
    "id": 123,
    "word": "cooks",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʊks/",
    "meaning": "nấu",
    "ex1": "The seller cooks the chicken over hot charcoal and serves it with fresh salad.",
    "ex1_vi": "Người bán nướng gà trên than nóng và phục vụ cùng salad tươi."
  },
  {
    "id": 124,
    "word": "over",
    "type": "preposition",
    "cat": "prep",
    "phonetic": "/ˈoʊvɝ/",
    "meaning": "trên; qua",
    "ex1": "The seller cooks the chicken over hot charcoal and serves it with fresh salad.",
    "ex1_vi": "Người bán nướng gà trên than nóng và phục vụ cùng salad tươi."
  },
  {
    "id": 125,
    "word": "hot",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑt/",
    "meaning": "nóng",
    "ex1": "In everyday city life, the seller cooks the chicken over hot charcoal and serves it with fresh salad.",
    "ex1_vi": "Trong cuộc sống thành thị hằng ngày, người bán nướng gà trên than nóng và phục vụ cùng salad tươi."
  },
  {
    "id": 126,
    "word": "charcoal",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɑrkˌoʊl/",
    "meaning": "than củi",
    "ex1": "At an evening market, the seller cooks the chicken over hot charcoal and serves it with fresh salad.",
    "ex1_vi": "Tại một khu chợ buổi tối, người bán nướng gà trên than nóng và phục vụ cùng salad tươi."
  },
  {
    "id": 127,
    "word": "salad",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈælʌd/",
    "meaning": "salad; món rau trộn",
    "ex1": "In this street food lesson, the seller cooks the chicken over hot charcoal and serves it with fresh salad.",
    "ex1_vi": "Trong bài học về đồ ăn đường phố này, người bán nướng gà trên than nóng và phục vụ cùng salad tươi."
  },
  {
    "id": 128,
    "word": "clean",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈin/",
    "meaning": "sạch",
    "ex1": "Everything is clean and carefully prepared every day.",
    "ex1_vi": "Mọi thứ đều sạch sẽ và được chuẩn bị cẩn thận mỗi ngày."
  },
  {
    "id": 129,
    "word": "prepared",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pripˈɛrd/",
    "meaning": "được chuẩn bị",
    "ex1": "Everything is clean and carefully prepared every day.",
    "ex1_vi": "Mọi thứ đều sạch sẽ và được chuẩn bị cẩn thận mỗi ngày."
  },
  {
    "id": 130,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɝi/",
    "meaning": "mỗi",
    "ex1": "In street food culture, everything is clean and carefully prepared every day.",
    "ex1_vi": "Trong văn hóa ẩm thực đường phố, mọi thứ đều sạch sẽ và được chuẩn bị cẩn thận mỗi ngày."
  },
  {
    "id": 131,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "For local customers, everything is clean and carefully prepared every day.",
    "ex1_vi": "Đối với khách hàng địa phương, mọi thứ đều sạch sẽ và được chuẩn bị cẩn thận mỗi ngày."
  },
  {
    "id": 132,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "I enjoy eating this street food with my family or friends.",
    "ex1_vi": "Tôi thích ăn món ăn đường phố này với gia đình hoặc bạn bè."
  },
  {
    "id": 133,
    "word": "friends",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈɛndz/",
    "meaning": "bạn bè",
    "ex1": "I enjoy eating this street food with my family or friends.",
    "ex1_vi": "Tôi thích ăn món ăn đường phố này với gia đình hoặc bạn bè."
  },
  {
    "id": 134,
    "word": "always",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlwˌeɪz/",
    "meaning": "luôn luôn",
    "ex1": "It always makes me happy, and I never get tired of its great taste.",
    "ex1_vi": "Nó luôn làm tôi vui và tôi không bao giờ chán hương vị tuyệt vời của nó."
  },
  {
    "id": 135,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm; khiến",
    "ex1": "It always makes me happy, and I never get tired of its great taste.",
    "ex1_vi": "Nó luôn làm tôi vui và tôi không bao giờ chán hương vị tuyệt vời của nó."
  },
  {
    "id": 136,
    "word": "happy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈæpi/",
    "meaning": "vui vẻ",
    "ex1": "For hungry visitors, it always makes me happy, and I never get tired of its great taste.",
    "ex1_vi": "Đối với những du khách đang đói, nó luôn làm tôi vui và tôi không bao giờ chán hương vị tuyệt vời của nó."
  },
  {
    "id": 137,
    "word": "never",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɛvɝ/",
    "meaning": "không bao giờ",
    "ex1": "During a food trip, it always makes me happy, and I never get tired of its great taste.",
    "ex1_vi": "Trong một chuyến khám phá ẩm thực, nó luôn làm tôi vui và tôi không bao giờ chán hương vị tuyệt vời của nó."
  },
  {
    "id": 138,
    "word": "get",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɛt/",
    "meaning": "có được; nhận",
    "ex1": "For many travelers, it always makes me happy, and I never get tired of its great taste.",
    "ex1_vi": "Đối với nhiều du khách, nó luôn làm tôi vui và tôi không bao giờ chán hương vị tuyệt vời của nó."
  },
  {
    "id": 139,
    "word": "tired",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈaɪɝd/",
    "meaning": "mệt",
    "ex1": "In street food culture, it always makes me happy, and I never get tired of its great taste.",
    "ex1_vi": "Trong văn hóa ẩm thực đường phố, nó luôn làm tôi vui và tôi không bao giờ chán hương vị tuyệt vời của nó."
  },
  {
    "id": 140,
    "word": "great",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈeɪt/",
    "meaning": "rất lớn; tuyệt vời",
    "ex1": "For local customers, it always makes me happy, and I never get tired of its great taste.",
    "ex1_vi": "Đối với khách hàng địa phương, nó luôn làm tôi vui và tôi không bao giờ chán hương vị tuyệt vời của nó."
  },
  {
    "id": 141,
    "word": "taste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪst/",
    "meaning": "hương vị",
    "ex1": "On a busy day, it always makes me happy, and I never get tired of its great taste.",
    "ex1_vi": "Vào một ngày bận rộn, nó luôn làm tôi vui và tôi không bao giờ chán hương vị tuyệt vời của nó."
  }
];

const newReadingVocabOrder = [
  "popular",
  "street",
  "food",
  "countries",
  "around",
  "world",
  "people",
  "enjoy",
  "eating",
  "quick",
  "tasty",
  "meals",
  "small",
  "stalls",
  "carts",
  "foods",
  "include",
  "sandwiches",
  "noodles",
  "grilled",
  "meat",
  "fried",
  "rice",
  "and",
  "fresh",
  "fruit",
  "usually",
  "cheap",
  "easy",
  "find",
  "busy",
  "places",
  "sellers",
  "cook",
  "front",
  "customers",
  "smells",
  "delicious",
  "looks",
  "colorful",
  "buy",
  "way",
  "work",
  "school",
  "home",
  "can",
  "eat",
  "while",
  "walking",
  "sitting",
  "nearby",
  "important",
  "part",
  "local",
  "culture",
  "brings",
  "together",
  "lets",
  "visitors",
  "traditional",
  "flavors",
  "travelers",
  "trying",
  "different",
  "wherever",
  "go",
  "buying",
  "simple",
  "enjoyable",
  "visit",
  "when",
  "feel",
  "hungry",
  "want",
  "meal",
  "look",
  "menu",
  "choose",
  "favorite",
  "order",
  "seller",
  "most",
  "pay",
  "cash",
  "mobile",
  "payment",
  "app",
  "prepares",
  "carefully",
  "serves",
  "wait",
  "only",
  "minutes",
  "receiving",
  "often",
  "drinks",
  "desserts",
  "make",
  "complete",
  "fast",
  "convenient",
  "affordable",
  "good",
  "choice",
  "without",
  "spending",
  "much",
  "money",
  "chicken",
  "has",
  "tender",
  "vegetables",
  "sauce",
  "warm",
  "filling",
  "because",
  "wonderful",
  "smell",
  "rich",
  "flavor",
  "friendly",
  "near",
  "cooks",
  "over",
  "hot",
  "charcoal",
  "salad",
  "clean",
  "prepared",
  "every",
  "day",
  "family",
  "friends",
  "always",
  "makes",
  "happy",
  "never",
  "get",
  "tired",
  "great",
  "taste"
];
