// ===== food02 ESSAY =====

const newEssayData = [
  {
    "text": "4. A Street Food Market\nA street food market is a lively place full of delicious smells and happy people. There are many colorful food stalls selling different kinds of meals, snacks, drinks, and desserts. Visitors walk around and choose the food they like best.\n\nThe market becomes very busy in the evening. Families, tourists, and friends enjoy eating together while listening to music. Some people take photos because the food looks beautiful and interesting. The friendly sellers smile and welcome every customer warmly.\n\nA street food market is a wonderful place to enjoy local food. It offers tasty meals and creates happy memories for everyone.",
    "vi": "4. Chợ ẩm thực đường phố\nChợ ẩm thực đường phố là một nơi sôi động, đầy những mùi thơm ngon và những người vui vẻ. Có nhiều quầy đồ ăn đầy màu sắc bán nhiều loại bữa ăn, đồ ăn nhẹ, đồ uống và món tráng miệng. Du khách đi quanh và chọn món họ thích nhất.\n\nKhu chợ trở nên rất đông vào buổi tối. Các gia đình, khách du lịch và bạn bè thích ăn cùng nhau trong khi nghe nhạc. Một số người chụp ảnh vì thức ăn trông đẹp và thú vị. Những người bán hàng thân thiện mỉm cười và nồng nhiệt chào đón mọi khách hàng.\n\nChợ ẩm thực đường phố là một nơi tuyệt vời để thưởng thức món ăn địa phương. Nơi đây cung cấp những bữa ăn ngon và tạo ra những kỷ niệm vui vẻ cho mọi người."
  },
  {
    "text": "5. Healthy Street Food\nSome street food is healthy and good for our bodies. Fresh fruit, vegetable salad, grilled fish, and fresh juice are popular healthy choices. These foods provide vitamins, minerals, and energy for daily activities.\n\nHealthy street food is usually made with fresh ingredients. Sellers wash vegetables, prepare food carefully, and keep everything clean. Customers should choose stalls that look tidy and follow good hygiene practices. Drinking enough water is also important during meals.\n\nEating healthy street food helps people stay strong and active. Good food choices improve health while allowing everyone to enjoy delicious meals outside.",
    "vi": "5. Đồ ăn đường phố lành mạnh\nMột số món ăn đường phố lành mạnh và tốt cho cơ thể chúng ta. Trái cây tươi, salad rau, cá nướng và nước ép tươi là những lựa chọn lành mạnh phổ biến. Những thực phẩm này cung cấp vitamin, khoáng chất và năng lượng cho các hoạt động hằng ngày.\n\nĐồ ăn đường phố lành mạnh thường được làm từ nguyên liệu tươi. Người bán rửa rau, chuẩn bị thức ăn cẩn thận và giữ mọi thứ sạch sẽ. Khách hàng nên chọn những quầy trông gọn gàng và tuân theo các thực hành vệ sinh tốt. Uống đủ nước cũng quan trọng trong bữa ăn.\n\nĂn đồ ăn đường phố lành mạnh giúp mọi người khỏe mạnh và năng động. Những lựa chọn thực phẩm tốt cải thiện sức khỏe đồng thời cho phép mọi người thưởng thức các bữa ăn ngon ở bên ngoài."
  },
  {
    "text": "6. Street Food Around the World\nStreet food is different in every country. Each place has special dishes with unique flavors and cooking styles. People enjoy local ingredients and traditional recipes that make every meal interesting. Visitors often try street food to learn about local culture.\n\nSome countries are famous for noodles, while others are known for tacos, kebabs, dumplings, or grilled seafood. Sweet snacks and fresh drinks are also popular in many cities. Every country has something special to offer.\n\nStreet food connects people from different cultures. It is a fun way to discover new tastes and enjoy delicious meals during travel.",
    "vi": "6. Đồ ăn đường phố trên thế giới\nĐồ ăn đường phố khác nhau ở mỗi quốc gia. Mỗi nơi có những món đặc biệt với hương vị và phong cách nấu ăn độc đáo. Mọi người thưởng thức nguyên liệu địa phương và công thức truyền thống khiến mỗi bữa ăn trở nên thú vị. Du khách thường thử đồ ăn đường phố để tìm hiểu về văn hóa địa phương.\n\nMột số quốc gia nổi tiếng với mì, trong khi những nơi khác được biết đến với taco, kebab, bánh há cảo hoặc hải sản nướng. Đồ ăn nhẹ ngọt và thức uống tươi mát cũng phổ biến ở nhiều thành phố. Mỗi quốc gia đều có điều đặc biệt để giới thiệu.\n\nĐồ ăn đường phố kết nối mọi người từ các nền văn hóa khác nhau. Đây là một cách thú vị để khám phá hương vị mới và thưởng thức các bữa ăn ngon trong khi du lịch."
  }
];
