const newEssayData = [
  {
    "text": "Chapter 10. Currant – Lý Chua\nCurrants are tiny berries that grow together in small hanging clusters. They are not true grapes, although their bunches may look similar to miniature grape clusters. Currants can be red, black, or white.\n\nRed currants have a bright and sour taste, while black currants have a stronger smell and deeper flavor. People often use these berries to make jam, jelly, juice, sauce, cakes, and desserts. They can also decorate fruit plates.\n\nCurrants grow best in cool climates and are not widely cultivated commercially in Vietnam. Fresh currants are delicate and may be difficult to find. Imported frozen, dried, or processed currant products are often easier to buy and store.",
    "vi": "Chương 10. Lý Chua\nLý chua là những quả mọng rất nhỏ mọc cùng nhau thành các chùm nhỏ rủ xuống. Chúng không phải nho thật, mặc dù các chùm có thể trông giống những chùm nho thu nhỏ. Lý chua có thể màu đỏ, đen hoặc trắng.\n\nLý chua đỏ có vị sáng và chua, trong khi lý chua đen có mùi mạnh hơn và hương vị sâu hơn. Mọi người thường dùng những quả này để làm mứt, thạch, nước ép, nước sốt, bánh và món tráng miệng. Chúng cũng có thể trang trí đĩa trái cây.\n\nLý chua phát triển tốt nhất ở khí hậu mát và không được trồng thương mại rộng rãi ở Việt Nam. Lý chua tươi mỏng manh và có thể khó tìm. Các sản phẩm lý chua đông lạnh, sấy hoặc chế biến nhập khẩu thường dễ mua và bảo quản hơn."
  },
  {
    "text": "Chapter 11. Witch Fingers Grape – Nho Ngón Tay\nWitch Fingers grapes are unusual grapes with a long, thin, and slightly curved shape. Their appearance looks like small fingers, which gives them their special name. They usually have dark purple or reddish skin.\n\nThese grapes are seedless and have crisp, sweet flesh. People can wash and eat them fresh as a snack. They are also attractive additions to fruit plates, salads, parties, and gift baskets.\n\nWitch Fingers grapes were specially developed through plant breeding. They need suitable growing conditions and careful farming methods. In Vietnam, they are mainly sold as imported premium grapes. Their unique shape, sweet taste, and limited supply often make them more expensive than ordinary grapes.",
    "vi": "Chương 11. Nho Ngón Tay\nNho Witch Fingers là loại nho khác lạ có hình dài, mảnh và hơi cong. Vẻ ngoài của chúng giống những ngón tay nhỏ, điều này tạo nên tên gọi đặc biệt. Chúng thường có vỏ tím sẫm hoặc đỏ tím.\n\nNhững quả nho này không hạt và có phần thịt giòn, ngọt. Mọi người có thể rửa và ăn tươi như món ăn vặt. Chúng cũng là phần bổ sung hấp dẫn cho đĩa trái cây, salad, tiệc và giỏ quà.\n\nNho Witch Fingers được phát triển đặc biệt thông qua lai tạo cây trồng. Chúng cần điều kiện trồng phù hợp và phương pháp canh tác cẩn thận. Ở Việt Nam, chúng chủ yếu được bán như nho cao cấp nhập khẩu. Hình dạng độc đáo, vị ngọt và nguồn cung hạn chế thường khiến chúng đắt hơn nho thông thường."
  },
  {
    "text": "Chapter 12. Sapphire Grape – Nho Sapphire\nSapphire grapes are long, dark-colored grapes with an unusual finger-like shape. They are also known as Sweet Sapphire grapes. Their skin is usually deep purple or almost black, while the flesh inside is light green.\n\nThese grapes are seedless, crisp, and naturally sweet. People often eat them fresh because they are easy to wash and serve. They can also be used in fruit salads, desserts, cheese plates, or decorative gift baskets.\n\nSapphire grapes are mainly imported into Vietnam from countries with suitable grape-growing areas, such as the United States and Australia. Their special shape and premium quality make them popular. They should be stored in the refrigerator to keep them firm and fresh.",
    "vi": "Chương 12. Nho Sapphire\nNho Sapphire là loại nho dài, màu sẫm với hình dạng giống ngón tay khác lạ. Chúng còn được biết đến với tên nho Sweet Sapphire. Vỏ thường tím đậm hoặc gần như đen, trong khi phần thịt bên trong màu xanh nhạt.\n\nNhững quả nho này không hạt, giòn và ngọt tự nhiên. Mọi người thường ăn tươi vì chúng dễ rửa và phục vụ. Chúng cũng có thể được dùng trong salad trái cây, món tráng miệng, đĩa phô mai hoặc giỏ quà trang trí.\n\nNho Sapphire chủ yếu được nhập vào Việt Nam từ các nước có vùng trồng nho phù hợp, như Hoa Kỳ và Úc. Hình dạng đặc biệt và chất lượng cao cấp làm chúng phổ biến. Chúng nên được bảo quản trong tủ lạnh để giữ chắc và tươi."
  }
];
