// ===== money02 ESSAY =====

const newEssayData = [
  {
    "text": "Chapter 4. How to Make a Simple Budget\nA budget is a plan for using money. It shows how much money a person earns, spends, and saves. Making a budget can help people understand where their money goes every month.\n\nFirst, write down all sources of income. Next, list important expenses, such as food, transport, school fees, and electricity. After that, decide how much money can be saved and how much can be used for entertainment.\n\nA simple budget helps people avoid spending too much. It also makes it easier to reach financial goals. People should check their budget regularly and change it when their income or expenses are different.",
    "vi": "Chương 4. Cách lập một ngân sách đơn giản\nNgân sách là một kế hoạch sử dụng tiền. Nó cho biết một người kiếm được, chi tiêu và tiết kiệm bao nhiêu tiền. Lập ngân sách có thể giúp mọi người hiểu tiền của họ đi đâu mỗi tháng.\n\nTrước tiên, hãy viết ra tất cả các nguồn thu nhập. Tiếp theo, liệt kê những khoản chi quan trọng như thực phẩm, giao thông, học phí và tiền điện. Sau đó, quyết định có thể tiết kiệm bao nhiêu tiền và có thể dùng bao nhiêu cho giải trí.\n\nMột ngân sách đơn giản giúp mọi người tránh chi tiêu quá nhiều. Nó cũng giúp việc đạt các mục tiêu tài chính dễ dàng hơn. Mọi người nên kiểm tra ngân sách thường xuyên và thay đổi khi thu nhập hoặc chi phí của họ thay đổi."
  },
  {
    "text": "Chapter 5. Needs and Wants\nNeeds are things that are necessary for a healthy and safe life. They include food, clean water, basic clothes, medicine, education, and a place to live. People should pay for their needs before buying other things.\n\nWants are things that we would like to have but can live without. A new phone, expensive shoes, games, and luxury food are common examples. Wants can make life enjoyable, but they are not always necessary.\n\nUnderstanding the difference between needs and wants helps people control their spending. Before buying something, we should stop and think carefully. This habit can help us save money and avoid waste.",
    "vi": "Chương 5. Nhu cầu và mong muốn\nNhu cầu là những thứ cần thiết cho một cuộc sống khỏe mạnh và an toàn. Chúng bao gồm thực phẩm, nước sạch, quần áo cơ bản, thuốc men, giáo dục và một nơi để sống. Mọi người nên chi trả cho nhu cầu trước khi mua những thứ khác.\n\nMong muốn là những thứ chúng ta muốn có nhưng vẫn có thể sống mà không có chúng. Một chiếc điện thoại mới, giày đắt tiền, trò chơi và thực phẩm xa xỉ là những ví dụ phổ biến. Mong muốn có thể làm cuộc sống thú vị hơn, nhưng chúng không phải lúc nào cũng cần thiết.\n\nHiểu sự khác biệt giữa nhu cầu và mong muốn giúp mọi người kiểm soát việc chi tiêu. Trước khi mua một thứ gì đó, chúng ta nên dừng lại và suy nghĩ cẩn thận. Thói quen này có thể giúp chúng ta tiết kiệm tiền và tránh lãng phí."
  },
  {
    "text": "Chapter 6. Shopping Wisely\nShopping wisely means buying useful products at reasonable prices. Before going shopping, people should make a list of what they need. A shopping list helps them stay focused and avoid buying unnecessary items.\n\nIt is also helpful to compare prices at different shops. People should check the quality, size, and expiry date of a product. A cheaper item is not always better if it breaks quickly or cannot be used for long.\n\nSpecial offers can save money, but buyers should be careful. Sometimes people buy more because they see a discount. Smart shoppers only buy products they truly need and can afford.",
    "vi": "Chương 6. Mua sắm khôn ngoan\nMua sắm khôn ngoan có nghĩa là mua những sản phẩm hữu ích với giá hợp lý. Trước khi đi mua sắm, mọi người nên lập danh sách những thứ họ cần. Danh sách mua sắm giúp họ tập trung và tránh mua những món không cần thiết.\n\nViệc so sánh giá ở những cửa hàng khác nhau cũng hữu ích. Mọi người nên kiểm tra chất lượng, kích thước và hạn sử dụng của một sản phẩm. Một món hàng rẻ hơn không phải lúc nào cũng tốt hơn nếu nó nhanh hỏng hoặc không thể dùng lâu.\n\nƯu đãi đặc biệt có thể giúp tiết kiệm tiền, nhưng người mua nên cẩn thận. Đôi khi mọi người mua nhiều hơn vì họ thấy có giảm giá. Người mua sắm thông minh chỉ mua những sản phẩm họ thật sự cần và có khả năng chi trả."
  }
];
