// ===== money01 ESSAY =====

const newEssayData = [
  {
    "text": "Chapter 1. What Is Money?\nMoney is something people use to buy goods and services. It can be coins, banknotes, or digital money in a bank account. Every day, people use money to pay for food, clothes, transport, education, and other important things.\n\nMoney also helps us compare the prices of different products. Without money, people would need to exchange goods directly. This method could be difficult because both people might not want what the other person has.\n\nMoney is important, but we should use it carefully. We need to earn, save, and spend it wisely. Money cannot buy love or true friendship, but it can make daily life easier and more comfortable.",
    "vi": "Chương 1. Tiền là gì?\nTiền là thứ mọi người dùng để mua hàng hóa và dịch vụ. Tiền có thể là tiền xu, tiền giấy hoặc tiền kỹ thuật số trong tài khoản ngân hàng. Mỗi ngày, mọi người dùng tiền để trả cho thực phẩm, quần áo, giao thông, giáo dục và những thứ quan trọng khác.\n\nTiền cũng giúp chúng ta so sánh giá của các sản phẩm khác nhau. Nếu không có tiền, mọi người sẽ phải trao đổi hàng hóa trực tiếp. Cách này có thể khó khăn vì cả hai người có thể không muốn thứ mà người kia có.\n\nTiền quan trọng, nhưng chúng ta nên sử dụng nó cẩn thận. Chúng ta cần kiếm, tiết kiệm và chi tiêu tiền một cách khôn ngoan. Tiền không thể mua được tình yêu hay tình bạn chân thật, nhưng nó có thể làm cho cuộc sống hằng ngày dễ dàng và thoải mái hơn."
  },
  {
    "text": "Chapter 2. Why Do We Need Money?\nPeople need money to pay for their basic needs. We use it to buy food, water, clothes, and medicine. Families also need money to pay for electricity, transport, education, and a safe place to live.\n\nMoney allows people to choose the products and services they need. It can also help them prepare for important events, such as studying at university, buying a house, or starting a small business.\n\nHowever, having more money does not always mean having a happier life. Good health, family, and friendship are also important. We should see money as a useful tool and learn to manage it responsibly.",
    "vi": "Chương 2. Tại sao chúng ta cần tiền?\nMọi người cần tiền để chi trả cho những nhu cầu cơ bản. Chúng ta dùng tiền để mua thực phẩm, nước, quần áo và thuốc men. Các gia đình cũng cần tiền để trả tiền điện, giao thông, giáo dục và một nơi ở an toàn.\n\nTiền cho phép mọi người lựa chọn những sản phẩm và dịch vụ họ cần. Tiền cũng có thể giúp họ chuẩn bị cho những sự kiện quan trọng, chẳng hạn như học đại học, mua nhà hoặc bắt đầu một công việc kinh doanh nhỏ.\n\nTuy nhiên, có nhiều tiền hơn không phải lúc nào cũng có nghĩa là có một cuộc sống hạnh phúc hơn. Sức khỏe tốt, gia đình và tình bạn cũng quan trọng. Chúng ta nên xem tiền như một công cụ hữu ích và học cách quản lý nó có trách nhiệm."
  },
  {
    "text": "Chapter 3. Saving Money Every Day\nSaving money is a good habit that everyone can practice. We do not need to save a large amount at one time. Even putting a small amount into a box or bank account every day can make a difference.\n\nPeople can save money by bringing lunch from home, turning off unused lights, and avoiding unnecessary shopping. Before buying something, they should ask whether they truly need it or only want it.\n\nSaving money helps us prepare for future plans and unexpected problems. It can reduce stress when we need to repair something or pay an urgent bill. Small daily savings can slowly become a useful amount of money.",
    "vi": "Chương 3. Tiết kiệm tiền mỗi ngày\nTiết kiệm tiền là một thói quen tốt mà mọi người đều có thể thực hành. Chúng ta không cần tiết kiệm một khoản lớn cùng một lúc. Ngay cả việc bỏ một khoản nhỏ vào hộp hoặc tài khoản ngân hàng mỗi ngày cũng có thể tạo ra khác biệt.\n\nMọi người có thể tiết kiệm tiền bằng cách mang bữa trưa từ nhà, tắt những đèn không sử dụng và tránh mua sắm không cần thiết. Trước khi mua một thứ gì đó, họ nên tự hỏi liệu họ thật sự cần nó hay chỉ muốn nó.\n\nTiết kiệm tiền giúp chúng ta chuẩn bị cho các kế hoạch tương lai và những vấn đề bất ngờ. Nó có thể giảm căng thẳng khi chúng ta cần sửa một thứ gì đó hoặc thanh toán một hóa đơn khẩn cấp. Những khoản tiết kiệm nhỏ hằng ngày có thể dần trở thành một khoản tiền hữu ích."
  }
];
