// ===== money03 ESSAY =====

const newEssayData = [
  {
    "text": "Chapter 7. Using Cash and Bank Cards\nCash includes coins and banknotes that people can hold and use directly. It is simple and useful for small purchases. Paying with cash can also help people see clearly how much money they are spending.\n\nBank cards and digital payments are convenient because people do not need to carry much cash. They can pay for products in shops or online. However, users must protect their passwords and personal banking information.\n\nBoth payment methods have advantages and disadvantages. People should choose the safest and most suitable method for each situation. They should also check their bank accounts regularly to find mistakes or unusual payments.",
    "vi": "Chương 7. Sử dụng tiền mặt và thẻ ngân hàng\nTiền mặt gồm tiền xu và tiền giấy mà mọi người có thể cầm và sử dụng trực tiếp. Nó đơn giản và hữu ích cho những khoản mua nhỏ. Thanh toán bằng tiền mặt cũng có thể giúp mọi người thấy rõ họ đang chi bao nhiêu tiền.\n\nThẻ ngân hàng và thanh toán kỹ thuật số tiện lợi vì mọi người không cần mang nhiều tiền mặt. Họ có thể thanh toán sản phẩm tại cửa hàng hoặc trực tuyến. Tuy nhiên, người dùng phải bảo vệ mật khẩu và thông tin ngân hàng cá nhân.\n\nCả hai phương thức thanh toán đều có ưu điểm và nhược điểm. Mọi người nên chọn phương thức an toàn nhất và phù hợp nhất cho từng tình huống. Họ cũng nên kiểm tra tài khoản ngân hàng thường xuyên để tìm lỗi hoặc những khoản thanh toán bất thường."
  },
  {
    "text": "Chapter 8. Earning Money from Work\nMost adults earn money by working. They may work in offices, factories, schools, hospitals, shops, or farms. Some people also run businesses or work online from home.\n\nThe amount of money a person earns often depends on their skills, education, experience, and responsibilities. Learning new skills can help workers find better opportunities. Good workers are usually responsible, honest, and willing to improve.\n\nEarning money requires time and effort, so people should use it carefully. They need to pay for important expenses, save for the future, and avoid wasting money. Respecting our work also teaches us to respect the value of money.",
    "vi": "Chương 8. Kiếm tiền từ công việc\nHầu hết người lớn kiếm tiền bằng cách làm việc. Họ có thể làm việc trong văn phòng, nhà máy, trường học, bệnh viện, cửa hàng hoặc trang trại. Một số người cũng điều hành doanh nghiệp hoặc làm việc trực tuyến tại nhà.\n\nSố tiền một người kiếm được thường phụ thuộc vào kỹ năng, giáo dục, kinh nghiệm và trách nhiệm của họ. Học kỹ năng mới có thể giúp người lao động tìm được cơ hội tốt hơn. Người lao động tốt thường có trách nhiệm, trung thực và sẵn sàng cải thiện.\n\nKiếm tiền đòi hỏi thời gian và công sức, vì vậy mọi người nên sử dụng tiền cẩn thận. Họ cần chi trả những khoản quan trọng, tiết kiệm cho tương lai và tránh lãng phí tiền. Tôn trọng công việc của mình cũng dạy chúng ta tôn trọng giá trị của tiền."
  },
  {
    "text": "Chapter 9. The Importance of Emergency Savings\nEmergency savings are money kept for unexpected situations. A person may suddenly become sick, lose a job, or need to repair a motorbike or household item. These problems can happen without warning.\n\nHaving emergency savings helps people pay urgent expenses without borrowing too much money. It also gives families a feeling of safety and reduces financial stress during difficult times.\n\nPeople can build an emergency fund by saving a small amount from their income each month. The money should be kept in a safe place and used only for real emergencies. Regular saving can create strong financial protection for the future.",
    "vi": "Chương 9. Tầm quan trọng của khoản tiết kiệm khẩn cấp\nTiết kiệm khẩn cấp là tiền được giữ cho những tình huống bất ngờ. Một người có thể đột nhiên bị bệnh, mất việc hoặc cần sửa xe máy hay đồ dùng trong nhà. Những vấn đề này có thể xảy ra mà không báo trước.\n\nCó khoản tiết kiệm khẩn cấp giúp mọi người thanh toán các chi phí cấp bách mà không phải vay quá nhiều tiền. Nó cũng mang lại cho gia đình cảm giác an toàn và giảm căng thẳng tài chính trong những thời điểm khó khăn.\n\nMọi người có thể xây dựng quỹ khẩn cấp bằng cách tiết kiệm một khoản nhỏ từ thu nhập mỗi tháng. Tiền nên được giữ ở nơi an toàn và chỉ dùng cho những trường hợp khẩn cấp thực sự. Tiết kiệm đều đặn có thể tạo ra sự bảo vệ tài chính vững chắc cho tương lai."
  },
  {
    "text": "Chapter 10. Money and a Happy Life\nMoney can make life easier because it helps people meet their needs. It allows families to buy food, receive medical care, study, travel, and enjoy different activities. Financial stability can also reduce worry.\n\nHowever, money alone cannot create a truly happy life. People also need good health, loving relationships, meaningful work, and time to relax. A rich person may still feel lonely or unhappy.\n\nThe best way to use money is to create a balanced life. People should spend responsibly, save for the future, and help others when possible. Money is valuable, but happiness also comes from kindness, gratitude, and time with loved ones.",
    "vi": "Chương 10. Tiền và một cuộc sống hạnh phúc\nTiền có thể làm cuộc sống dễ dàng hơn vì nó giúp mọi người đáp ứng nhu cầu của mình. Nó cho phép các gia đình mua thực phẩm, nhận chăm sóc y tế, học tập, du lịch và tận hưởng những hoạt động khác nhau. Sự ổn định tài chính cũng có thể giảm lo lắng.\n\nTuy nhiên, chỉ tiền thôi không thể tạo ra một cuộc sống thật sự hạnh phúc. Mọi người cũng cần sức khỏe tốt, những mối quan hệ yêu thương, công việc có ý nghĩa và thời gian thư giãn. Một người giàu vẫn có thể cảm thấy cô đơn hoặc không hạnh phúc.\n\nCách tốt nhất để sử dụng tiền là tạo ra một cuộc sống cân bằng. Mọi người nên chi tiêu có trách nhiệm, tiết kiệm cho tương lai và giúp đỡ người khác khi có thể. Tiền có giá trị, nhưng hạnh phúc cũng đến từ lòng tốt, sự biết ơn và thời gian bên những người thân yêu."
  }
];
