// ===== money03 VOCABULARY =====

const lessonVocabularyWords = [
  "using",
  "cash",
  "and",
  "bank",
  "cards",
  "includes",
  "coins",
  "banknotes",
  "people",
  "can",
  "hold",
  "use",
  "directly",
  "simple",
  "useful",
  "small",
  "purchases",
  "paying",
  "also",
  "help",
  "see",
  "clearly",
  "how",
  "much",
  "money",
  "spending",
  "digital",
  "payments",
  "convenient",
  "because",
  "do",
  "not",
  "need",
  "carry",
  "pay",
  "products",
  "shops",
  "or",
  "online",
  "however",
  "users",
  "must",
  "protect",
  "passwords",
  "personal",
  "banking",
  "information",
  "both",
  "payment",
  "methods",
  "have",
  "advantages",
  "disadvantages",
  "should",
  "choose",
  "safest",
  "most",
  "suitable",
  "method",
  "each",
  "situation",
  "check",
  "accounts",
  "regularly",
  "find",
  "mistakes",
  "unusual",
  "earning",
  "work",
  "adults",
  "earn",
  "working",
  "may",
  "offices",
  "factories",
  "schools",
  "hospitals",
  "farms",
  "some",
  "run",
  "businesses",
  "home",
  "amount",
  "person",
  "earns",
  "often",
  "depends",
  "skills",
  "education",
  "experience",
  "responsibilities",
  "learning",
  "new",
  "workers",
  "better",
  "opportunities",
  "good",
  "usually",
  "responsible",
  "honest",
  "willing",
  "improve",
  "requires",
  "time",
  "effort",
  "so",
  "carefully",
  "important",
  "expenses",
  "save",
  "future",
  "avoid",
  "wasting",
  "respecting",
  "teaches",
  "respect",
  "value",
  "importance",
  "emergency",
  "savings",
  "kept",
  "unexpected",
  "situations",
  "suddenly",
  "become",
  "sick",
  "lose",
  "job",
  "repair",
  "motorbike",
  "household",
  "item",
  "problems",
  "happen",
  "without",
  "warning",
  "having",
  "helps",
  "urgent",
  "borrowing",
  "too",
  "gives",
  "families",
  "feeling",
  "safety",
  "reduces",
  "financial",
  "stress",
  "difficult",
  "times",
  "build",
  "fund",
  "saving",
  "income",
  "month",
  "safe",
  "place",
  "used",
  "only",
  "real",
  "emergencies",
  "regular",
  "create",
  "strong",
  "protection",
  "happy",
  "life",
  "make",
  "easier",
  "meet",
  "needs",
  "allows",
  "buy",
  "food",
  "receive",
  "medical",
  "care",
  "study",
  "travel",
  "enjoy",
  "different",
  "activities",
  "stability",
  "reduce",
  "worry",
  "alone",
  "cannot",
  "truly",
  "health",
  "loving",
  "relationships",
  "meaningful",
  "relax",
  "rich",
  "still",
  "feel",
  "lonely",
  "unhappy",
  "best",
  "way",
  "balanced",
  "spend",
  "responsibly",
  "others",
  "when",
  "possible",
  "valuable",
  "but",
  "happiness",
  "comes",
  "kindness",
  "gratitude",
  "loved",
  "ones"
];

const newVocabData = [
  {
    "id": 1,
    "word": "using",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈuzɪŋ/",
    "meaning": "việc sử dụng",
    "ex1": "In daily life, people can learn about using through simple examples about money.",
    "ex1_vi": "Trong cuộc sống hằng ngày, mọi người có thể tìm hiểu về việc sử dụng qua những ví dụ đơn giản về tiền."
  },
  {
    "id": 2,
    "word": "cash",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈæʃ/",
    "meaning": "tiền mặt",
    "ex1": "For many families, cash includes coins and banknotes that people can hold and use directly.",
    "ex1_vi": "Đối với nhiều gia đình, tiền mặt gồm tiền xu và tiền giấy mà mọi người có thể cầm và sử dụng trực tiếp."
  },
  {
    "id": 3,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "When managing money, cash includes coins and banknotes that people can hold and use directly.",
    "ex1_vi": "Khi quản lý tiền, tiền mặt gồm tiền xu và tiền giấy mà mọi người có thể cầm và sử dụng trực tiếp."
  },
  {
    "id": 4,
    "word": "bank",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈæŋk/",
    "meaning": "ngân hàng",
    "ex1": "In everyday spending, bank cards and digital payments are convenient because people do not need to carry much cash.",
    "ex1_vi": "Trong việc chi tiêu hằng ngày, thẻ ngân hàng và thanh toán kỹ thuật số tiện lợi vì mọi người không cần mang nhiều tiền mặt."
  },
  {
    "id": 5,
    "word": "cards",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑrdz/",
    "meaning": "thẻ ngân hàng",
    "ex1": "For careful planning, bank cards and digital payments are convenient because people do not need to carry much cash.",
    "ex1_vi": "Để lập kế hoạch cẩn thận, thẻ ngân hàng và thanh toán kỹ thuật số tiện lợi vì mọi người không cần mang nhiều tiền mặt."
  },
  {
    "id": 6,
    "word": "includes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɪnklˈuːdz/",
    "meaning": "bao gồm",
    "ex1": "When thinking about money, cash includes coins and banknotes that people can hold and use directly.",
    "ex1_vi": "Khi suy nghĩ về tiền, tiền mặt gồm tiền xu và tiền giấy mà mọi người có thể cầm và sử dụng trực tiếp."
  },
  {
    "id": 7,
    "word": "coins",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɔɪnz/",
    "meaning": "tiền xu",
    "ex1": "In a simple financial example, cash includes coins and banknotes that people can hold and use directly.",
    "ex1_vi": "Trong một ví dụ tài chính đơn giản, tiền mặt gồm tiền xu và tiền giấy mà mọi người có thể cầm và sử dụng trực tiếp."
  },
  {
    "id": 8,
    "word": "banknotes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈæŋknˌoʊts/",
    "meaning": "tiền giấy",
    "ex1": "For responsible choices, cash includes coins and banknotes that people can hold and use directly.",
    "ex1_vi": "Để có những lựa chọn có trách nhiệm, tiền mặt gồm tiền xu và tiền giấy mà mọi người có thể cầm và sử dụng trực tiếp."
  },
  {
    "id": 9,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "When planning for the future, cash includes coins and banknotes that people can hold and use directly.",
    "ex1_vi": "Khi lập kế hoạch cho tương lai, tiền mặt gồm tiền xu và tiền giấy mà mọi người có thể cầm và sử dụng trực tiếp."
  },
  {
    "id": 10,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "In common money situations, cash includes coins and banknotes that people can hold and use directly.",
    "ex1_vi": "Trong những tình huống tiền bạc thường gặp, tiền mặt gồm tiền xu và tiền giấy mà mọi người có thể cầm và sử dụng trực tiếp."
  },
  {
    "id": 11,
    "word": "hold",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈoʊld/",
    "meaning": "cầm; giữ",
    "ex1": "For a family budget, cash includes coins and banknotes that people can hold and use directly.",
    "ex1_vi": "Đối với ngân sách gia đình, tiền mặt gồm tiền xu và tiền giấy mà mọi người có thể cầm và sử dụng trực tiếp."
  },
  {
    "id": 12,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "When making daily choices, cash includes coins and banknotes that people can hold and use directly.",
    "ex1_vi": "Khi đưa ra lựa chọn hằng ngày, tiền mặt gồm tiền xu và tiền giấy mà mọi người có thể cầm và sử dụng trực tiếp."
  },
  {
    "id": 13,
    "word": "directly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/dɝˈɛktli/",
    "meaning": "trực tiếp",
    "ex1": "In practical life, cash includes coins and banknotes that people can hold and use directly.",
    "ex1_vi": "Trong cuộc sống thực tế, tiền mặt gồm tiền xu và tiền giấy mà mọi người có thể cầm và sử dụng trực tiếp."
  },
  {
    "id": 14,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "For smart spending, it is simple and useful for small purchases.",
    "ex1_vi": "Để chi tiêu thông minh, nó đơn giản và hữu ích cho những khoản mua nhỏ."
  },
  {
    "id": 15,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈusfʌl/",
    "meaning": "hữu ích",
    "ex1": "When saving money, it is simple and useful for small purchases.",
    "ex1_vi": "Khi tiết kiệm tiền, nó đơn giản và hữu ích cho những khoản mua nhỏ."
  },
  {
    "id": 16,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "In ordinary shopping, it is simple and useful for small purchases.",
    "ex1_vi": "Trong việc mua sắm thông thường, nó đơn giản và hữu ích cho những khoản mua nhỏ."
  },
  {
    "id": 17,
    "word": "purchases",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɝtʃʌsʌz/",
    "meaning": "các khoản mua; hàng mua",
    "ex1": "For good financial habits, it is simple and useful for small purchases.",
    "ex1_vi": "Để có thói quen tài chính tốt, nó đơn giản và hữu ích cho những khoản mua nhỏ."
  },
  {
    "id": 18,
    "word": "paying",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈeɪɪŋ/",
    "meaning": "việc chú ý; đang trả",
    "ex1": "When people plan expenses, paying with cash can also help people see clearly how much money they are spending.",
    "ex1_vi": "Khi mọi người lên kế hoạch chi tiêu, thanh toán bằng tiền mặt cũng có thể giúp mọi người thấy rõ họ đang chi bao nhiêu tiền."
  },
  {
    "id": 19,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "In a careful household plan, paying with cash can also help people see clearly how much money they are spending.",
    "ex1_vi": "Trong một kế hoạch gia đình cẩn thận, thanh toán bằng tiền mặt cũng có thể giúp mọi người thấy rõ họ đang chi bao nhiêu tiền."
  },
  {
    "id": 20,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "For everyday financial decisions, paying with cash can also help people see clearly how much money they are spending.",
    "ex1_vi": "Đối với các quyết định tài chính hằng ngày, thanh toán bằng tiền mặt cũng có thể giúp mọi người thấy rõ họ đang chi bao nhiêu tiền."
  },
  {
    "id": 21,
    "word": "see",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈi/",
    "meaning": "nhìn thấy",
    "ex1": "In daily life, paying with cash can also help people see clearly how much money they are spending.",
    "ex1_vi": "Trong cuộc sống hằng ngày, thanh toán bằng tiền mặt cũng có thể giúp mọi người thấy rõ họ đang chi bao nhiêu tiền."
  },
  {
    "id": 22,
    "word": "clearly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/klˈɪrli/",
    "meaning": "rõ ràng",
    "ex1": "For many families, paying with cash can also help people see clearly how much money they are spending.",
    "ex1_vi": "Đối với nhiều gia đình, thanh toán bằng tiền mặt cũng có thể giúp mọi người thấy rõ họ đang chi bao nhiêu tiền."
  },
  {
    "id": 23,
    "word": "how",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/hˈaʊ/",
    "meaning": "như thế nào",
    "ex1": "When managing money, paying with cash can also help people see clearly how much money they are spending.",
    "ex1_vi": "Khi quản lý tiền, thanh toán bằng tiền mặt cũng có thể giúp mọi người thấy rõ họ đang chi bao nhiêu tiền."
  },
  {
    "id": 24,
    "word": "much",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈʌtʃ/",
    "meaning": "nhiều",
    "ex1": "In everyday spending, paying with cash can also help people see clearly how much money they are spending.",
    "ex1_vi": "Trong việc chi tiêu hằng ngày, thanh toán bằng tiền mặt cũng có thể giúp mọi người thấy rõ họ đang chi bao nhiêu tiền."
  },
  {
    "id": 25,
    "word": "money",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌni/",
    "meaning": "tiền",
    "ex1": "For careful planning, paying with cash can also help people see clearly how much money they are spending.",
    "ex1_vi": "Để lập kế hoạch cẩn thận, thanh toán bằng tiền mặt cũng có thể giúp mọi người thấy rõ họ đang chi bao nhiêu tiền."
  },
  {
    "id": 26,
    "word": "spending",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈɛndɪŋ/",
    "meaning": "việc chi tiêu",
    "ex1": "When thinking about money, paying with cash can also help people see clearly how much money they are spending.",
    "ex1_vi": "Khi suy nghĩ về tiền, thanh toán bằng tiền mặt cũng có thể giúp mọi người thấy rõ họ đang chi bao nhiêu tiền."
  },
  {
    "id": 27,
    "word": "digital",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪdʒʌtʌl/",
    "meaning": "kỹ thuật số",
    "ex1": "In a simple financial example, bank cards and digital payments are convenient because people do not need to carry much cash.",
    "ex1_vi": "Trong một ví dụ tài chính đơn giản, thẻ ngân hàng và thanh toán kỹ thuật số tiện lợi vì mọi người không cần mang nhiều tiền mặt."
  },
  {
    "id": 28,
    "word": "payments",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈeɪmʌnts/",
    "meaning": "các khoản thanh toán",
    "ex1": "For responsible choices, bank cards and digital payments are convenient because people do not need to carry much cash.",
    "ex1_vi": "Để có những lựa chọn có trách nhiệm, thẻ ngân hàng và thanh toán kỹ thuật số tiện lợi vì mọi người không cần mang nhiều tiền mặt."
  },
  {
    "id": 29,
    "word": "convenient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kʌnvˈinjʌnt/",
    "meaning": "thuận tiện",
    "ex1": "When planning for the future, bank cards and digital payments are convenient because people do not need to carry much cash.",
    "ex1_vi": "Khi lập kế hoạch cho tương lai, thẻ ngân hàng và thanh toán kỹ thuật số tiện lợi vì mọi người không cần mang nhiều tiền mặt."
  },
  {
    "id": 30,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "In common money situations, bank cards and digital payments are convenient because people do not need to carry much cash.",
    "ex1_vi": "Trong những tình huống tiền bạc thường gặp, thẻ ngân hàng và thanh toán kỹ thuật số tiện lợi vì mọi người không cần mang nhiều tiền mặt."
  },
  {
    "id": 31,
    "word": "do",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈu/",
    "meaning": "làm",
    "ex1": "For a family budget, bank cards and digital payments are convenient because people do not need to carry much cash.",
    "ex1_vi": "Đối với ngân sách gia đình, thẻ ngân hàng và thanh toán kỹ thuật số tiện lợi vì mọi người không cần mang nhiều tiền mặt."
  },
  {
    "id": 32,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "When making daily choices, bank cards and digital payments are convenient because people do not need to carry much cash.",
    "ex1_vi": "Khi đưa ra lựa chọn hằng ngày, thẻ ngân hàng và thanh toán kỹ thuật số tiện lợi vì mọi người không cần mang nhiều tiền mặt."
  },
  {
    "id": 33,
    "word": "need",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈid/",
    "meaning": "cần; nhu cầu",
    "ex1": "In practical life, bank cards and digital payments are convenient because people do not need to carry much cash.",
    "ex1_vi": "Trong cuộc sống thực tế, thẻ ngân hàng và thanh toán kỹ thuật số tiện lợi vì mọi người không cần mang nhiều tiền mặt."
  },
  {
    "id": 34,
    "word": "carry",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈæri/",
    "meaning": "mang",
    "ex1": "For smart spending, bank cards and digital payments are convenient because people do not need to carry much cash.",
    "ex1_vi": "Để chi tiêu thông minh, thẻ ngân hàng và thanh toán kỹ thuật số tiện lợi vì mọi người không cần mang nhiều tiền mặt."
  },
  {
    "id": 35,
    "word": "pay",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pˈeɪ/",
    "meaning": "thanh toán",
    "ex1": "When saving money, they can pay for products in shops or online.",
    "ex1_vi": "Khi tiết kiệm tiền, họ có thể thanh toán sản phẩm tại cửa hàng hoặc trực tuyến."
  },
  {
    "id": 36,
    "word": "products",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑdʌkts/",
    "meaning": "sản phẩm",
    "ex1": "In ordinary shopping, they can pay for products in shops or online.",
    "ex1_vi": "Trong việc mua sắm thông thường, họ có thể thanh toán sản phẩm tại cửa hàng hoặc trực tuyến."
  },
  {
    "id": 37,
    "word": "shops",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɑps/",
    "meaning": "cửa hàng",
    "ex1": "For good financial habits, they can pay for products in shops or online.",
    "ex1_vi": "Để có thói quen tài chính tốt, họ có thể thanh toán sản phẩm tại cửa hàng hoặc trực tuyến."
  },
  {
    "id": 38,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "When people plan expenses, they can pay for products in shops or online.",
    "ex1_vi": "Khi mọi người lên kế hoạch chi tiêu, họ có thể thanh toán sản phẩm tại cửa hàng hoặc trực tuyến."
  },
  {
    "id": 39,
    "word": "online",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔnlˌaɪn/",
    "meaning": "trực tuyến",
    "ex1": "In a careful household plan, they can pay for products in shops or online.",
    "ex1_vi": "Trong một kế hoạch gia đình cẩn thận, họ có thể thanh toán sản phẩm tại cửa hàng hoặc trực tuyến."
  },
  {
    "id": 40,
    "word": "however",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/hˌaʊˈɛvɝ/",
    "meaning": "tuy nhiên",
    "ex1": "For everyday financial decisions, however, users must protect their passwords and personal banking information.",
    "ex1_vi": "Đối với các quyết định tài chính hằng ngày, tuy nhiên, người dùng phải bảo vệ mật khẩu và thông tin ngân hàng cá nhân."
  },
  {
    "id": 41,
    "word": "users",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈjuːzərz/",
    "meaning": "người dùng",
    "ex1": "In daily life, however, users must protect their passwords and personal banking information.",
    "ex1_vi": "Trong cuộc sống hằng ngày, tuy nhiên, người dùng phải bảo vệ mật khẩu và thông tin ngân hàng cá nhân."
  },
  {
    "id": 42,
    "word": "must",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈʌst/",
    "meaning": "phải",
    "ex1": "For many families, however, users must protect their passwords and personal banking information.",
    "ex1_vi": "Đối với nhiều gia đình, tuy nhiên, người dùng phải bảo vệ mật khẩu và thông tin ngân hàng cá nhân."
  },
  {
    "id": 43,
    "word": "protect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌtˈɛkt/",
    "meaning": "bảo vệ",
    "ex1": "When managing money, however, users must protect their passwords and personal banking information.",
    "ex1_vi": "Khi quản lý tiền, tuy nhiên, người dùng phải bảo vệ mật khẩu và thông tin ngân hàng cá nhân."
  },
  {
    "id": 44,
    "word": "passwords",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈæswˌɝdz/",
    "meaning": "mật khẩu",
    "ex1": "In everyday spending, however, users must protect their passwords and personal banking information.",
    "ex1_vi": "Trong việc chi tiêu hằng ngày, tuy nhiên, người dùng phải bảo vệ mật khẩu và thông tin ngân hàng cá nhân."
  },
  {
    "id": 45,
    "word": "personal",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɜːsənəl/",
    "meaning": "cá nhân",
    "ex1": "For careful planning, however, users must protect their passwords and personal banking information.",
    "ex1_vi": "Để lập kế hoạch cẩn thận, tuy nhiên, người dùng phải bảo vệ mật khẩu và thông tin ngân hàng cá nhân."
  },
  {
    "id": 46,
    "word": "banking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈæŋkɪŋ/",
    "meaning": "thuộc ngân hàng",
    "ex1": "When thinking about money, however, users must protect their passwords and personal banking information.",
    "ex1_vi": "Khi suy nghĩ về tiền, tuy nhiên, người dùng phải bảo vệ mật khẩu và thông tin ngân hàng cá nhân."
  },
  {
    "id": 47,
    "word": "information",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnfɚmˈeɪʃən/",
    "meaning": "thông tin",
    "ex1": "In a simple financial example, however, users must protect their passwords and personal banking information.",
    "ex1_vi": "Trong một ví dụ tài chính đơn giản, tuy nhiên, người dùng phải bảo vệ mật khẩu và thông tin ngân hàng cá nhân."
  },
  {
    "id": 48,
    "word": "both",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/boʊθ/",
    "meaning": "cả hai",
    "ex1": "For responsible choices, both payment methods have advantages and disadvantages.",
    "ex1_vi": "Để có những lựa chọn có trách nhiệm, cả hai phương thức thanh toán đều có ưu điểm và nhược điểm."
  },
  {
    "id": 49,
    "word": "payment",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈeɪmʌnt/",
    "meaning": "thanh toán",
    "ex1": "When planning for the future, both payment methods have advantages and disadvantages.",
    "ex1_vi": "Khi lập kế hoạch cho tương lai, cả hai phương thức thanh toán đều có ưu điểm và nhược điểm."
  },
  {
    "id": 50,
    "word": "methods",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛθʌdz/",
    "meaning": "phương thức",
    "ex1": "In common money situations, both payment methods have advantages and disadvantages.",
    "ex1_vi": "Trong những tình huống tiền bạc thường gặp, cả hai phương thức thanh toán đều có ưu điểm và nhược điểm."
  },
  {
    "id": 51,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có; dùng",
    "ex1": "For a family budget, both payment methods have advantages and disadvantages.",
    "ex1_vi": "Đối với ngân sách gia đình, cả hai phương thức thanh toán đều có ưu điểm và nhược điểm."
  },
  {
    "id": 52,
    "word": "advantages",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ædvˈæntɪdʒɪz/",
    "meaning": "ưu điểm",
    "ex1": "When making daily choices, both payment methods have advantages and disadvantages.",
    "ex1_vi": "Khi đưa ra lựa chọn hằng ngày, cả hai phương thức thanh toán đều có ưu điểm và nhược điểm."
  },
  {
    "id": 53,
    "word": "disadvantages",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˌɪsʌdvˈæntɪdʒɪz/",
    "meaning": "nhược điểm",
    "ex1": "In practical life, both payment methods have advantages and disadvantages.",
    "ex1_vi": "Trong cuộc sống thực tế, cả hai phương thức thanh toán đều có ưu điểm và nhược điểm."
  },
  {
    "id": 54,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "For smart spending, people should choose the safest and most suitable method for each situation.",
    "ex1_vi": "Để chi tiêu thông minh, mọi người nên chọn phương thức an toàn nhất và phù hợp nhất cho từng tình huống."
  },
  {
    "id": 55,
    "word": "choose",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈuz/",
    "meaning": "chọn",
    "ex1": "When saving money, people should choose the safest and most suitable method for each situation.",
    "ex1_vi": "Khi tiết kiệm tiền, mọi người nên chọn phương thức an toàn nhất và phù hợp nhất cho từng tình huống."
  },
  {
    "id": 56,
    "word": "safest",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪfʌst/",
    "meaning": "an toàn nhất",
    "ex1": "In ordinary shopping, people should choose the safest and most suitable method for each situation.",
    "ex1_vi": "Trong việc mua sắm thông thường, mọi người nên chọn phương thức an toàn nhất và phù hợp nhất cho từng tình huống."
  },
  {
    "id": 57,
    "word": "most",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈoʊst/",
    "meaning": "phần lớn",
    "ex1": "For good financial habits, people should choose the safest and most suitable method for each situation.",
    "ex1_vi": "Để có thói quen tài chính tốt, mọi người nên chọn phương thức an toàn nhất và phù hợp nhất cho từng tình huống."
  },
  {
    "id": 58,
    "word": "suitable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈutʌbʌl/",
    "meaning": "phù hợp",
    "ex1": "When people plan expenses, people should choose the safest and most suitable method for each situation.",
    "ex1_vi": "Khi mọi người lên kế hoạch chi tiêu, mọi người nên chọn phương thức an toàn nhất và phù hợp nhất cho từng tình huống."
  },
  {
    "id": 59,
    "word": "method",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛθʌd/",
    "meaning": "phương pháp; cách thức",
    "ex1": "In a careful household plan, people should choose the safest and most suitable method for each situation.",
    "ex1_vi": "Trong một kế hoạch gia đình cẩn thận, mọi người nên chọn phương thức an toàn nhất và phù hợp nhất cho từng tình huống."
  },
  {
    "id": 60,
    "word": "each",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈitʃ/",
    "meaning": "mỗi",
    "ex1": "For everyday financial decisions, people should choose the safest and most suitable method for each situation.",
    "ex1_vi": "Đối với các quyết định tài chính hằng ngày, mọi người nên chọn phương thức an toàn nhất và phù hợp nhất cho từng tình huống."
  },
  {
    "id": 61,
    "word": "situation",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˌɪtʃuˈeɪʃʌn/",
    "meaning": "tình huống",
    "ex1": "In daily life, people should choose the safest and most suitable method for each situation.",
    "ex1_vi": "Trong cuộc sống hằng ngày, mọi người nên chọn phương thức an toàn nhất và phù hợp nhất cho từng tình huống."
  },
  {
    "id": 62,
    "word": "check",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈɛk/",
    "meaning": "kiểm tra",
    "ex1": "For many families, they should also check their bank accounts regularly to find mistakes or unusual payments.",
    "ex1_vi": "Đối với nhiều gia đình, họ cũng nên kiểm tra tài khoản ngân hàng thường xuyên để tìm lỗi hoặc những khoản thanh toán bất thường."
  },
  {
    "id": 63,
    "word": "accounts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌkˈaʊnts/",
    "meaning": "tài khoản",
    "ex1": "When managing money, they should also check their bank accounts regularly to find mistakes or unusual payments.",
    "ex1_vi": "Khi quản lý tiền, họ cũng nên kiểm tra tài khoản ngân hàng thường xuyên để tìm lỗi hoặc những khoản thanh toán bất thường."
  },
  {
    "id": 64,
    "word": "regularly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/rˈɛɡjʌlɝli/",
    "meaning": "thường xuyên",
    "ex1": "In everyday spending, they should also check their bank accounts regularly to find mistakes or unusual payments.",
    "ex1_vi": "Trong việc chi tiêu hằng ngày, họ cũng nên kiểm tra tài khoản ngân hàng thường xuyên để tìm lỗi hoặc những khoản thanh toán bất thường."
  },
  {
    "id": 65,
    "word": "find",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪnd/",
    "meaning": "phát hiện; tìm thấy",
    "ex1": "For careful planning, they should also check their bank accounts regularly to find mistakes or unusual payments.",
    "ex1_vi": "Để lập kế hoạch cẩn thận, họ cũng nên kiểm tra tài khoản ngân hàng thường xuyên để tìm lỗi hoặc những khoản thanh toán bất thường."
  },
  {
    "id": 66,
    "word": "mistakes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mɪstˈeɪks/",
    "meaning": "sai lầm",
    "ex1": "When thinking about money, they should also check their bank accounts regularly to find mistakes or unusual payments.",
    "ex1_vi": "Khi suy nghĩ về tiền, họ cũng nên kiểm tra tài khoản ngân hàng thường xuyên để tìm lỗi hoặc những khoản thanh toán bất thường."
  },
  {
    "id": 67,
    "word": "unusual",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌnjˈuʒˌuʌl/",
    "meaning": "bất thường",
    "ex1": "In a simple financial example, they should also check their bank accounts regularly to find mistakes or unusual payments.",
    "ex1_vi": "Trong một ví dụ tài chính đơn giản, họ cũng nên kiểm tra tài khoản ngân hàng thường xuyên để tìm lỗi hoặc những khoản thanh toán bất thường."
  },
  {
    "id": 68,
    "word": "earning",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɝnɪŋ/",
    "meaning": "việc kiếm tiền",
    "ex1": "For responsible choices, earning money requires time and effort, so people should use it carefully.",
    "ex1_vi": "Để có những lựa chọn có trách nhiệm, kiếm tiền đòi hỏi thời gian và công sức, vì vậy mọi người nên sử dụng tiền cẩn thận."
  },
  {
    "id": 69,
    "word": "work",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝk/",
    "meaning": "hoạt động; làm việc",
    "ex1": "When planning for the future, they may work in offices, factories, schools, hospitals, shops, or farms.",
    "ex1_vi": "Khi lập kế hoạch cho tương lai, họ có thể làm việc trong văn phòng, nhà máy, trường học, bệnh viện, cửa hàng hoặc trang trại."
  },
  {
    "id": 70,
    "word": "adults",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌdˈʌlts/",
    "meaning": "người lớn",
    "ex1": "In common money situations, most adults earn money by working.",
    "ex1_vi": "Trong những tình huống tiền bạc thường gặp, hầu hết người lớn kiếm tiền bằng cách làm việc."
  },
  {
    "id": 71,
    "word": "earn",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɝn/",
    "meaning": "kiếm tiền; kiếm được",
    "ex1": "For a family budget, most adults earn money by working.",
    "ex1_vi": "Đối với ngân sách gia đình, hầu hết người lớn kiếm tiền bằng cách làm việc."
  },
  {
    "id": 72,
    "word": "working",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɜːkɪŋ/",
    "meaning": "làm việc",
    "ex1": "When making daily choices, most adults earn money by working.",
    "ex1_vi": "Khi đưa ra lựa chọn hằng ngày, hầu hết người lớn kiếm tiền bằng cách làm việc."
  },
  {
    "id": 73,
    "word": "may",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈeɪ/",
    "meaning": "có thể",
    "ex1": "In practical life, they may work in offices, factories, schools, hospitals, shops, or farms.",
    "ex1_vi": "Trong cuộc sống thực tế, họ có thể làm việc trong văn phòng, nhà máy, trường học, bệnh viện, cửa hàng hoặc trang trại."
  },
  {
    "id": 74,
    "word": "offices",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɒfɪsɪz/",
    "meaning": "các văn phòng",
    "ex1": "For smart spending, they may work in offices, factories, schools, hospitals, shops, or farms.",
    "ex1_vi": "Để chi tiêu thông minh, họ có thể làm việc trong văn phòng, nhà máy, trường học, bệnh viện, cửa hàng hoặc trang trại."
  },
  {
    "id": 75,
    "word": "factories",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæktɝiz/",
    "meaning": "nhà máy",
    "ex1": "When saving money, they may work in offices, factories, schools, hospitals, shops, or farms.",
    "ex1_vi": "Khi tiết kiệm tiền, họ có thể làm việc trong văn phòng, nhà máy, trường học, bệnh viện, cửa hàng hoặc trang trại."
  },
  {
    "id": 76,
    "word": "schools",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈulz/",
    "meaning": "trường học",
    "ex1": "In ordinary shopping, they may work in offices, factories, schools, hospitals, shops, or farms.",
    "ex1_vi": "Trong việc mua sắm thông thường, họ có thể làm việc trong văn phòng, nhà máy, trường học, bệnh viện, cửa hàng hoặc trang trại."
  },
  {
    "id": 77,
    "word": "hospitals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɑspˌɪtʌlz/",
    "meaning": "bệnh viện",
    "ex1": "For good financial habits, they may work in offices, factories, schools, hospitals, shops, or farms.",
    "ex1_vi": "Để có thói quen tài chính tốt, họ có thể làm việc trong văn phòng, nhà máy, trường học, bệnh viện, cửa hàng hoặc trang trại."
  },
  {
    "id": 78,
    "word": "farms",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fɑrmz/",
    "meaning": "các nông trại",
    "ex1": "When people plan expenses, they may work in offices, factories, schools, hospitals, shops, or farms.",
    "ex1_vi": "Khi mọi người lên kế hoạch chi tiêu, họ có thể làm việc trong văn phòng, nhà máy, trường học, bệnh viện, cửa hàng hoặc trang trại."
  },
  {
    "id": 79,
    "word": "some",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌm/",
    "meaning": "một ít; một số",
    "ex1": "In a careful household plan, some people also run businesses or work online from home.",
    "ex1_vi": "Trong một kế hoạch gia đình cẩn thận, một số người cũng điều hành doanh nghiệp hoặc làm việc trực tuyến tại nhà."
  },
  {
    "id": 80,
    "word": "run",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈʌn/",
    "meaning": "điều hành; chạy",
    "ex1": "For everyday financial decisions, some people also run businesses or work online from home.",
    "ex1_vi": "Đối với các quyết định tài chính hằng ngày, một số người cũng điều hành doanh nghiệp hoặc làm việc trực tuyến tại nhà."
  },
  {
    "id": 81,
    "word": "businesses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɪznʌsʌz/",
    "meaning": "doanh nghiệp",
    "ex1": "In daily life, some people also run businesses or work online from home.",
    "ex1_vi": "Trong cuộc sống hằng ngày, một số người cũng điều hành doanh nghiệp hoặc làm việc trực tuyến tại nhà."
  },
  {
    "id": 82,
    "word": "home",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊm/",
    "meaning": "nơi sinh sống; nhà",
    "ex1": "For many families, some people also run businesses or work online from home.",
    "ex1_vi": "Đối với nhiều gia đình, một số người cũng điều hành doanh nghiệp hoặc làm việc trực tuyến tại nhà."
  },
  {
    "id": 83,
    "word": "amount",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌmˈaʊnt/",
    "meaning": "số tiền; lượng",
    "ex1": "When managing money, the amount of money a person earns often depends on their skills, education, experience, and responsibilities.",
    "ex1_vi": "Khi quản lý tiền, số tiền một người kiếm được thường phụ thuộc vào kỹ năng, giáo dục, kinh nghiệm và trách nhiệm của họ."
  },
  {
    "id": 84,
    "word": "person",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɝsʌn/",
    "meaning": "người",
    "ex1": "In everyday spending, the amount of money a person earns often depends on their skills, education, experience, and responsibilities.",
    "ex1_vi": "Trong việc chi tiêu hằng ngày, số tiền một người kiếm được thường phụ thuộc vào kỹ năng, giáo dục, kinh nghiệm và trách nhiệm của họ."
  },
  {
    "id": 85,
    "word": "earns",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɝnz/",
    "meaning": "kiếm được",
    "ex1": "For careful planning, the amount of money a person earns often depends on their skills, education, experience, and responsibilities.",
    "ex1_vi": "Để lập kế hoạch cẩn thận, số tiền một người kiếm được thường phụ thuộc vào kỹ năng, giáo dục, kinh nghiệm và trách nhiệm của họ."
  },
  {
    "id": 86,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "When thinking about money, the amount of money a person earns often depends on their skills, education, experience, and responsibilities.",
    "ex1_vi": "Khi suy nghĩ về tiền, số tiền một người kiếm được thường phụ thuộc vào kỹ năng, giáo dục, kinh nghiệm và trách nhiệm của họ."
  },
  {
    "id": 87,
    "word": "depends",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dɪpˈɛndz/",
    "meaning": "phụ thuộc",
    "ex1": "In a simple financial example, the amount of money a person earns often depends on their skills, education, experience, and responsibilities.",
    "ex1_vi": "Trong một ví dụ tài chính đơn giản, số tiền một người kiếm được thường phụ thuộc vào kỹ năng, giáo dục, kinh nghiệm và trách nhiệm của họ."
  },
  {
    "id": 88,
    "word": "skills",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪlz/",
    "meaning": "kỹ năng",
    "ex1": "For responsible choices, the amount of money a person earns often depends on their skills, education, experience, and responsibilities.",
    "ex1_vi": "Để có những lựa chọn có trách nhiệm, số tiền một người kiếm được thường phụ thuộc vào kỹ năng, giáo dục, kinh nghiệm và trách nhiệm của họ."
  },
  {
    "id": 89,
    "word": "education",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɛdʒʌkˈeɪʃʌn/",
    "meaning": "giáo dục",
    "ex1": "When planning for the future, the amount of money a person earns often depends on their skills, education, experience, and responsibilities.",
    "ex1_vi": "Khi lập kế hoạch cho tương lai, số tiền một người kiếm được thường phụ thuộc vào kỹ năng, giáo dục, kinh nghiệm và trách nhiệm của họ."
  },
  {
    "id": 90,
    "word": "experience",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪkspˈɪriʌns/",
    "meaning": "trải nghiệm",
    "ex1": "In common money situations, the amount of money a person earns often depends on their skills, education, experience, and responsibilities.",
    "ex1_vi": "Trong những tình huống tiền bạc thường gặp, số tiền một người kiếm được thường phụ thuộc vào kỹ năng, giáo dục, kinh nghiệm và trách nhiệm của họ."
  },
  {
    "id": 91,
    "word": "responsibilities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rispˌɑnsʌbˈɪlʌtiz/",
    "meaning": "trách nhiệm",
    "ex1": "For a family budget, the amount of money a person earns often depends on their skills, education, experience, and responsibilities.",
    "ex1_vi": "Đối với ngân sách gia đình, số tiền một người kiếm được thường phụ thuộc vào kỹ năng, giáo dục, kinh nghiệm và trách nhiệm của họ."
  },
  {
    "id": 92,
    "word": "learning",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɝnɪŋ/",
    "meaning": "việc học",
    "ex1": "When making daily choices, learning new skills can help workers find better opportunities.",
    "ex1_vi": "Khi đưa ra lựa chọn hằng ngày, học kỹ năng mới có thể giúp người lao động tìm được cơ hội tốt hơn."
  },
  {
    "id": 93,
    "word": "new",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈu/",
    "meaning": "mới",
    "ex1": "In practical life, learning new skills can help workers find better opportunities.",
    "ex1_vi": "Trong cuộc sống thực tế, học kỹ năng mới có thể giúp người lao động tìm được cơ hội tốt hơn."
  },
  {
    "id": 94,
    "word": "workers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɜːkɚz/",
    "meaning": "nhân viên",
    "ex1": "For smart spending, learning new skills can help workers find better opportunities.",
    "ex1_vi": "Để chi tiêu thông minh, học kỹ năng mới có thể giúp người lao động tìm được cơ hội tốt hơn."
  },
  {
    "id": 95,
    "word": "better",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɛtɝ/",
    "meaning": "tốt hơn",
    "ex1": "When saving money, learning new skills can help workers find better opportunities.",
    "ex1_vi": "Khi tiết kiệm tiền, học kỹ năng mới có thể giúp người lao động tìm được cơ hội tốt hơn."
  },
  {
    "id": 96,
    "word": "opportunities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɑpɝtˈunʌtiz/",
    "meaning": "cơ hội",
    "ex1": "In ordinary shopping, learning new skills can help workers find better opportunities.",
    "ex1_vi": "Trong việc mua sắm thông thường, học kỹ năng mới có thể giúp người lao động tìm được cơ hội tốt hơn."
  },
  {
    "id": 97,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "For good financial habits, good workers are usually responsible, honest, and willing to improve.",
    "ex1_vi": "Để có thói quen tài chính tốt, người lao động tốt thường có trách nhiệm, trung thực và sẵn sàng cải thiện."
  },
  {
    "id": 98,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "When people plan expenses, good workers are usually responsible, honest, and willing to improve.",
    "ex1_vi": "Khi mọi người lên kế hoạch chi tiêu, người lao động tốt thường có trách nhiệm, trung thực và sẵn sàng cải thiện."
  },
  {
    "id": 99,
    "word": "responsible",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rispˈɑnsʌbʌl/",
    "meaning": "có trách nhiệm",
    "ex1": "In a careful household plan, good workers are usually responsible, honest, and willing to improve.",
    "ex1_vi": "Trong một kế hoạch gia đình cẩn thận, người lao động tốt thường có trách nhiệm, trung thực và sẵn sàng cải thiện."
  },
  {
    "id": 100,
    "word": "honest",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɑnʌst/",
    "meaning": "trung thực",
    "ex1": "For everyday financial decisions, good workers are usually responsible, honest, and willing to improve.",
    "ex1_vi": "Đối với các quyết định tài chính hằng ngày, người lao động tốt thường có trách nhiệm, trung thực và sẵn sàng cải thiện."
  },
  {
    "id": 101,
    "word": "willing",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈɪlɪŋ/",
    "meaning": "sẵn sàng",
    "ex1": "In daily life, good workers are usually responsible, honest, and willing to improve.",
    "ex1_vi": "Trong cuộc sống hằng ngày, người lao động tốt thường có trách nhiệm, trung thực và sẵn sàng cải thiện."
  },
  {
    "id": 102,
    "word": "improve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪmprˈuv/",
    "meaning": "cải thiện",
    "ex1": "For many families, good workers are usually responsible, honest, and willing to improve.",
    "ex1_vi": "Đối với nhiều gia đình, người lao động tốt thường có trách nhiệm, trung thực và sẵn sàng cải thiện."
  },
  {
    "id": 103,
    "word": "requires",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪkwˈaɪɚz/",
    "meaning": "đòi hỏi",
    "ex1": "When managing money, earning money requires time and effort, so people should use it carefully.",
    "ex1_vi": "Khi quản lý tiền, kiếm tiền đòi hỏi thời gian và công sức, vì vậy mọi người nên sử dụng tiền cẩn thận."
  },
  {
    "id": 104,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "In everyday spending, earning money requires time and effort, so people should use it carefully.",
    "ex1_vi": "Trong việc chi tiêu hằng ngày, kiếm tiền đòi hỏi thời gian và công sức, vì vậy mọi người nên sử dụng tiền cẩn thận."
  },
  {
    "id": 105,
    "word": "effort",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛfɝt/",
    "meaning": "nỗ lực",
    "ex1": "For careful planning, earning money requires time and effort, so people should use it carefully.",
    "ex1_vi": "Để lập kế hoạch cẩn thận, kiếm tiền đòi hỏi thời gian và công sức, vì vậy mọi người nên sử dụng tiền cẩn thận."
  },
  {
    "id": 106,
    "word": "so",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/sˈoʊ/",
    "meaning": "vì vậy",
    "ex1": "When thinking about money, earning money requires time and effort, so people should use it carefully.",
    "ex1_vi": "Khi suy nghĩ về tiền, kiếm tiền đòi hỏi thời gian và công sức, vì vậy mọi người nên sử dụng tiền cẩn thận."
  },
  {
    "id": 107,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "In a simple financial example, earning money requires time and effort, so people should use it carefully.",
    "ex1_vi": "Trong một ví dụ tài chính đơn giản, kiếm tiền đòi hỏi thời gian và công sức, vì vậy mọi người nên sử dụng tiền cẩn thận."
  },
  {
    "id": 108,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔrtʌnt/",
    "meaning": "quan trọng",
    "ex1": "For responsible choices, they need to pay for important expenses, save for the future, and avoid wasting money.",
    "ex1_vi": "Để có những lựa chọn có trách nhiệm, họ cần chi trả những khoản quan trọng, tiết kiệm cho tương lai và tránh lãng phí tiền."
  },
  {
    "id": 109,
    "word": "expenses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪkspˈɛnsʌz/",
    "meaning": "chi phí",
    "ex1": "When planning for the future, they need to pay for important expenses, save for the future, and avoid wasting money.",
    "ex1_vi": "Khi lập kế hoạch cho tương lai, họ cần chi trả những khoản quan trọng, tiết kiệm cho tương lai và tránh lãng phí tiền."
  },
  {
    "id": 110,
    "word": "save",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪv/",
    "meaning": "tiết kiệm",
    "ex1": "In common money situations, they need to pay for important expenses, save for the future, and avoid wasting money.",
    "ex1_vi": "Trong những tình huống tiền bạc thường gặp, họ cần chi trả những khoản quan trọng, tiết kiệm cho tương lai và tránh lãng phí tiền."
  },
  {
    "id": 111,
    "word": "future",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fjutʃɚ/",
    "meaning": "tương lai",
    "ex1": "For a family budget, they need to pay for important expenses, save for the future, and avoid wasting money.",
    "ex1_vi": "Đối với ngân sách gia đình, họ cần chi trả những khoản quan trọng, tiết kiệm cho tương lai và tránh lãng phí tiền."
  },
  {
    "id": 112,
    "word": "avoid",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌvˈɔɪd/",
    "meaning": "tránh",
    "ex1": "When making daily choices, they need to pay for important expenses, save for the future, and avoid wasting money.",
    "ex1_vi": "Khi đưa ra lựa chọn hằng ngày, họ cần chi trả những khoản quan trọng, tiết kiệm cho tương lai và tránh lãng phí tiền."
  },
  {
    "id": 113,
    "word": "wasting",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪstɪŋ/",
    "meaning": "việc lãng phí",
    "ex1": "In practical life, they need to pay for important expenses, save for the future, and avoid wasting money.",
    "ex1_vi": "Trong cuộc sống thực tế, họ cần chi trả những khoản quan trọng, tiết kiệm cho tương lai và tránh lãng phí tiền."
  },
  {
    "id": 114,
    "word": "respecting",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rispˈɛktɪŋ/",
    "meaning": "việc tôn trọng",
    "ex1": "For smart spending, respecting our work also teaches us to respect the value of money.",
    "ex1_vi": "Để chi tiêu thông minh, tôn trọng công việc của mình cũng dạy chúng ta tôn trọng giá trị của tiền."
  },
  {
    "id": 115,
    "word": "teaches",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈitʃʌz/",
    "meaning": "dạy",
    "ex1": "When saving money, respecting our work also teaches us to respect the value of money.",
    "ex1_vi": "Khi tiết kiệm tiền, tôn trọng công việc của mình cũng dạy chúng ta tôn trọng giá trị của tiền."
  },
  {
    "id": 116,
    "word": "respect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪspˈɛkt/",
    "meaning": "tôn trọng",
    "ex1": "In ordinary shopping, respecting our work also teaches us to respect the value of money.",
    "ex1_vi": "Trong việc mua sắm thông thường, tôn trọng công việc của mình cũng dạy chúng ta tôn trọng giá trị của tiền."
  },
  {
    "id": 117,
    "word": "value",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈælju/",
    "meaning": "trân trọng; coi trọng",
    "ex1": "For good financial habits, respecting our work also teaches us to respect the value of money.",
    "ex1_vi": "Để có thói quen tài chính tốt, tôn trọng công việc của mình cũng dạy chúng ta tôn trọng giá trị của tiền."
  },
  {
    "id": 118,
    "word": "importance",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪmpˈɔrtʌns/",
    "meaning": "tầm quan trọng",
    "ex1": "When people plan expenses, people can learn about importance through simple examples about money.",
    "ex1_vi": "Khi mọi người lên kế hoạch chi tiêu, mọi người có thể tìm hiểu về tầm quan trọng qua những ví dụ đơn giản về tiền."
  },
  {
    "id": 119,
    "word": "emergency",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪmˈɝdʒʌnsi/",
    "meaning": "khẩn cấp",
    "ex1": "In a careful household plan, emergency savings are money kept for unexpected situations.",
    "ex1_vi": "Trong một kế hoạch gia đình cẩn thận, tiết kiệm khẩn cấp là tiền được giữ cho những tình huống bất ngờ."
  },
  {
    "id": 120,
    "word": "savings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈeɪvɪŋz/",
    "meaning": "khoản tiết kiệm",
    "ex1": "For everyday financial decisions, emergency savings are money kept for unexpected situations.",
    "ex1_vi": "Đối với các quyết định tài chính hằng ngày, tiết kiệm khẩn cấp là tiền được giữ cho những tình huống bất ngờ."
  },
  {
    "id": 121,
    "word": "kept",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɛpt/",
    "meaning": "được giữ",
    "ex1": "In daily life, emergency savings are money kept for unexpected situations.",
    "ex1_vi": "Trong cuộc sống hằng ngày, tiết kiệm khẩn cấp là tiền được giữ cho những tình huống bất ngờ."
  },
  {
    "id": 122,
    "word": "unexpected",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌʌnɪkspˈɛktɪd/",
    "meaning": "bất ngờ; không dự kiến",
    "ex1": "For many families, emergency savings are money kept for unexpected situations.",
    "ex1_vi": "Đối với nhiều gia đình, tiết kiệm khẩn cấp là tiền được giữ cho những tình huống bất ngờ."
  },
  {
    "id": 123,
    "word": "situations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˌɪtʃuˈeɪʃʌnz/",
    "meaning": "tình huống",
    "ex1": "When managing money, emergency savings are money kept for unexpected situations.",
    "ex1_vi": "Khi quản lý tiền, tiết kiệm khẩn cấp là tiền được giữ cho những tình huống bất ngờ."
  },
  {
    "id": 124,
    "word": "suddenly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sˈʌdʌnli/",
    "meaning": "đột nhiên",
    "ex1": "In everyday spending, a person may suddenly become sick, lose a job, or need to repair a motorbike or household item.",
    "ex1_vi": "Trong việc chi tiêu hằng ngày, một người có thể đột nhiên bị bệnh, mất việc hoặc cần sửa xe máy hay đồ dùng trong nhà."
  },
  {
    "id": 125,
    "word": "become",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌm/",
    "meaning": "trở nên",
    "ex1": "For careful planning, a person may suddenly become sick, lose a job, or need to repair a motorbike or household item.",
    "ex1_vi": "Để lập kế hoạch cẩn thận, một người có thể đột nhiên bị bệnh, mất việc hoặc cần sửa xe máy hay đồ dùng trong nhà."
  },
  {
    "id": 126,
    "word": "sick",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪk/",
    "meaning": "ốm; bị bệnh",
    "ex1": "When thinking about money, a person may suddenly become sick, lose a job, or need to repair a motorbike or household item.",
    "ex1_vi": "Khi suy nghĩ về tiền, một người có thể đột nhiên bị bệnh, mất việc hoặc cần sửa xe máy hay đồ dùng trong nhà."
  },
  {
    "id": 127,
    "word": "lose",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈuz/",
    "meaning": "mất",
    "ex1": "In a simple financial example, a person may suddenly become sick, lose a job, or need to repair a motorbike or household item.",
    "ex1_vi": "Trong một ví dụ tài chính đơn giản, một người có thể đột nhiên bị bệnh, mất việc hoặc cần sửa xe máy hay đồ dùng trong nhà."
  },
  {
    "id": 128,
    "word": "job",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɑb/",
    "meaning": "công việc",
    "ex1": "For responsible choices, a person may suddenly become sick, lose a job, or need to repair a motorbike or household item.",
    "ex1_vi": "Để có những lựa chọn có trách nhiệm, một người có thể đột nhiên bị bệnh, mất việc hoặc cần sửa xe máy hay đồ dùng trong nhà."
  },
  {
    "id": 129,
    "word": "repair",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪpˈɛr/",
    "meaning": "sửa chữa",
    "ex1": "When planning for the future, a person may suddenly become sick, lose a job, or need to repair a motorbike or household item.",
    "ex1_vi": "Khi lập kế hoạch cho tương lai, một người có thể đột nhiên bị bệnh, mất việc hoặc cần sửa xe máy hay đồ dùng trong nhà."
  },
  {
    "id": 130,
    "word": "motorbike",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈoʊtɝbˌaɪk/",
    "meaning": "xe máy",
    "ex1": "In common money situations, a person may suddenly become sick, lose a job, or need to repair a motorbike or household item.",
    "ex1_vi": "Trong những tình huống tiền bạc thường gặp, một người có thể đột nhiên bị bệnh, mất việc hoặc cần sửa xe máy hay đồ dùng trong nhà."
  },
  {
    "id": 131,
    "word": "household",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈaʊshˌoʊld/",
    "meaning": "thuộc gia đình; đồ dùng gia đình",
    "ex1": "For a family budget, a person may suddenly become sick, lose a job, or need to repair a motorbike or household item.",
    "ex1_vi": "Đối với ngân sách gia đình, một người có thể đột nhiên bị bệnh, mất việc hoặc cần sửa xe máy hay đồ dùng trong nhà."
  },
  {
    "id": 132,
    "word": "item",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪtʌm/",
    "meaning": "món hàng; vật",
    "ex1": "When making daily choices, a person may suddenly become sick, lose a job, or need to repair a motorbike or household item.",
    "ex1_vi": "Khi đưa ra lựa chọn hằng ngày, một người có thể đột nhiên bị bệnh, mất việc hoặc cần sửa xe máy hay đồ dùng trong nhà."
  },
  {
    "id": 133,
    "word": "problems",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑblʌmz/",
    "meaning": "vấn đề",
    "ex1": "In practical life, these problems can happen without warning.",
    "ex1_vi": "Trong cuộc sống thực tế, những vấn đề này có thể xảy ra mà không báo trước."
  },
  {
    "id": 134,
    "word": "happen",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæpʌn/",
    "meaning": "xảy ra",
    "ex1": "For smart spending, these problems can happen without warning.",
    "ex1_vi": "Để chi tiêu thông minh, những vấn đề này có thể xảy ra mà không báo trước."
  },
  {
    "id": 135,
    "word": "without",
    "type": "preposition",
    "cat": "prep",
    "phonetic": "/wɪθˈaʊt/",
    "meaning": "không có; không bị",
    "ex1": "When saving money, these problems can happen without warning.",
    "ex1_vi": "Khi tiết kiệm tiền, những vấn đề này có thể xảy ra mà không báo trước."
  },
  {
    "id": 136,
    "word": "warning",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔrnɪŋ/",
    "meaning": "cảnh báo",
    "ex1": "In ordinary shopping, these problems can happen without warning.",
    "ex1_vi": "Trong việc mua sắm thông thường, những vấn đề này có thể xảy ra mà không báo trước."
  },
  {
    "id": 137,
    "word": "having",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈævɪŋ/",
    "meaning": "việc có; đang có",
    "ex1": "For good financial habits, having emergency savings helps people pay urgent expenses without borrowing too much money.",
    "ex1_vi": "Để có thói quen tài chính tốt, có khoản tiết kiệm khẩn cấp giúp mọi người thanh toán các chi phí cấp bách mà không phải vay quá nhiều tiền."
  },
  {
    "id": 138,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "When people plan expenses, having emergency savings helps people pay urgent expenses without borrowing too much money.",
    "ex1_vi": "Khi mọi người lên kế hoạch chi tiêu, có khoản tiết kiệm khẩn cấp giúp mọi người thanh toán các chi phí cấp bách mà không phải vay quá nhiều tiền."
  },
  {
    "id": 139,
    "word": "urgent",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɝdʒʌnt/",
    "meaning": "khẩn cấp",
    "ex1": "In a careful household plan, having emergency savings helps people pay urgent expenses without borrowing too much money.",
    "ex1_vi": "Trong một kế hoạch gia đình cẩn thận, có khoản tiết kiệm khẩn cấp giúp mọi người thanh toán các chi phí cấp bách mà không phải vay quá nhiều tiền."
  },
  {
    "id": 140,
    "word": "borrowing",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɑroʊɪŋ/",
    "meaning": "việc vay",
    "ex1": "For everyday financial decisions, having emergency savings helps people pay urgent expenses without borrowing too much money.",
    "ex1_vi": "Đối với các quyết định tài chính hằng ngày, có khoản tiết kiệm khẩn cấp giúp mọi người thanh toán các chi phí cấp bách mà không phải vay quá nhiều tiền."
  },
  {
    "id": 141,
    "word": "too",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tˈu/",
    "meaning": "cũng; quá",
    "ex1": "In daily life, having emergency savings helps people pay urgent expenses without borrowing too much money.",
    "ex1_vi": "Trong cuộc sống hằng ngày, có khoản tiết kiệm khẩn cấp giúp mọi người thanh toán các chi phí cấp bách mà không phải vay quá nhiều tiền."
  },
  {
    "id": 142,
    "word": "gives",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvz/",
    "meaning": "cho; mang lại",
    "ex1": "For many families, it also gives families a feeling of safety and reduces financial stress during difficult times.",
    "ex1_vi": "Đối với nhiều gia đình, nó cũng mang lại cho gia đình cảm giác an toàn và giảm căng thẳng tài chính trong những thời điểm khó khăn."
  },
  {
    "id": 143,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌliz/",
    "meaning": "gia đình",
    "ex1": "When managing money, it also gives families a feeling of safety and reduces financial stress during difficult times.",
    "ex1_vi": "Khi quản lý tiền, nó cũng mang lại cho gia đình cảm giác an toàn và giảm căng thẳng tài chính trong những thời điểm khó khăn."
  },
  {
    "id": 144,
    "word": "feeling",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈilɪŋ/",
    "meaning": "cảm xúc",
    "ex1": "In everyday spending, it also gives families a feeling of safety and reduces financial stress during difficult times.",
    "ex1_vi": "Trong việc chi tiêu hằng ngày, nó cũng mang lại cho gia đình cảm giác an toàn và giảm căng thẳng tài chính trong những thời điểm khó khăn."
  },
  {
    "id": 145,
    "word": "safety",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈeɪfti/",
    "meaning": "sự an toàn",
    "ex1": "For careful planning, it also gives families a feeling of safety and reduces financial stress during difficult times.",
    "ex1_vi": "Để lập kế hoạch cẩn thận, nó cũng mang lại cho gia đình cảm giác an toàn và giảm căng thẳng tài chính trong những thời điểm khó khăn."
  },
  {
    "id": 146,
    "word": "reduces",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪdˈuːsɪz/",
    "meaning": "giảm",
    "ex1": "When thinking about money, it also gives families a feeling of safety and reduces financial stress during difficult times.",
    "ex1_vi": "Khi suy nghĩ về tiền, nó cũng mang lại cho gia đình cảm giác an toàn và giảm căng thẳng tài chính trong những thời điểm khó khăn."
  },
  {
    "id": 147,
    "word": "financial",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fʌnˈænʃʌl/",
    "meaning": "thuộc tài chính",
    "ex1": "In a simple financial example, it also gives families a feeling of safety and reduces financial stress during difficult times.",
    "ex1_vi": "Trong một ví dụ tài chính đơn giản, nó cũng mang lại cho gia đình cảm giác an toàn và giảm căng thẳng tài chính trong những thời điểm khó khăn."
  },
  {
    "id": 148,
    "word": "stress",
    "type": "noun",
    "cat": "n",
    "phonetic": "/strˈɛs/",
    "meaning": "căng thẳng",
    "ex1": "For responsible choices, it also gives families a feeling of safety and reduces financial stress during difficult times.",
    "ex1_vi": "Để có những lựa chọn có trách nhiệm, nó cũng mang lại cho gia đình cảm giác an toàn và giảm căng thẳng tài chính trong những thời điểm khó khăn."
  },
  {
    "id": 149,
    "word": "difficult",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfʌkʌlt/",
    "meaning": "khó khăn",
    "ex1": "When planning for the future, it also gives families a feeling of safety and reduces financial stress during difficult times.",
    "ex1_vi": "Khi lập kế hoạch cho tương lai, nó cũng mang lại cho gia đình cảm giác an toàn và giảm căng thẳng tài chính trong những thời điểm khó khăn."
  },
  {
    "id": 150,
    "word": "times",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪmz/",
    "meaning": "những lúc; thời điểm",
    "ex1": "In common money situations, it also gives families a feeling of safety and reduces financial stress during difficult times.",
    "ex1_vi": "Trong những tình huống tiền bạc thường gặp, nó cũng mang lại cho gia đình cảm giác an toàn và giảm căng thẳng tài chính trong những thời điểm khó khăn."
  },
  {
    "id": 151,
    "word": "build",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɪld/",
    "meaning": "xây dựng",
    "ex1": "For a family budget, people can build an emergency fund by saving a small amount from their income each month.",
    "ex1_vi": "Đối với ngân sách gia đình, mọi người có thể xây dựng quỹ khẩn cấp bằng cách tiết kiệm một khoản nhỏ từ thu nhập mỗi tháng."
  },
  {
    "id": 152,
    "word": "fund",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈʌnd/",
    "meaning": "quỹ",
    "ex1": "When making daily choices, people can build an emergency fund by saving a small amount from their income each month.",
    "ex1_vi": "Khi đưa ra lựa chọn hằng ngày, mọi người có thể xây dựng quỹ khẩn cấp bằng cách tiết kiệm một khoản nhỏ từ thu nhập mỗi tháng."
  },
  {
    "id": 153,
    "word": "saving",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈeɪvɪŋ/",
    "meaning": "việc tiết kiệm",
    "ex1": "In practical life, people can build an emergency fund by saving a small amount from their income each month.",
    "ex1_vi": "Trong cuộc sống thực tế, mọi người có thể xây dựng quỹ khẩn cấp bằng cách tiết kiệm một khoản nhỏ từ thu nhập mỗi tháng."
  },
  {
    "id": 154,
    "word": "income",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɪnkˌʌm/",
    "meaning": "thu nhập",
    "ex1": "For smart spending, people can build an emergency fund by saving a small amount from their income each month.",
    "ex1_vi": "Để chi tiêu thông minh, mọi người có thể xây dựng quỹ khẩn cấp bằng cách tiết kiệm một khoản nhỏ từ thu nhập mỗi tháng."
  },
  {
    "id": 155,
    "word": "month",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌnθ/",
    "meaning": "tháng",
    "ex1": "When saving money, people can build an emergency fund by saving a small amount from their income each month.",
    "ex1_vi": "Khi tiết kiệm tiền, mọi người có thể xây dựng quỹ khẩn cấp bằng cách tiết kiệm một khoản nhỏ từ thu nhập mỗi tháng."
  },
  {
    "id": 156,
    "word": "safe",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪf/",
    "meaning": "an toàn",
    "ex1": "In ordinary shopping, the money should be kept in a safe place and used only for real emergencies.",
    "ex1_vi": "Trong việc mua sắm thông thường, tiền nên được giữ ở nơi an toàn và chỉ dùng cho những trường hợp khẩn cấp thực sự."
  },
  {
    "id": 157,
    "word": "place",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪs/",
    "meaning": "nơi; địa điểm",
    "ex1": "For good financial habits, the money should be kept in a safe place and used only for real emergencies.",
    "ex1_vi": "Để có thói quen tài chính tốt, tiền nên được giữ ở nơi an toàn và chỉ dùng cho những trường hợp khẩn cấp thực sự."
  },
  {
    "id": 158,
    "word": "used",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzd/",
    "meaning": "được sử dụng",
    "ex1": "When people plan expenses, the money should be kept in a safe place and used only for real emergencies.",
    "ex1_vi": "Khi mọi người lên kế hoạch chi tiêu, tiền nên được giữ ở nơi an toàn và chỉ dùng cho những trường hợp khẩn cấp thực sự."
  },
  {
    "id": 159,
    "word": "only",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈoʊnli/",
    "meaning": "chỉ",
    "ex1": "In a careful household plan, the money should be kept in a safe place and used only for real emergencies.",
    "ex1_vi": "Trong một kế hoạch gia đình cẩn thận, tiền nên được giữ ở nơi an toàn và chỉ dùng cho những trường hợp khẩn cấp thực sự."
  },
  {
    "id": 160,
    "word": "real",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈil/",
    "meaning": "thực tế; thật",
    "ex1": "For everyday financial decisions, the money should be kept in a safe place and used only for real emergencies.",
    "ex1_vi": "Đối với các quyết định tài chính hằng ngày, tiền nên được giữ ở nơi an toàn và chỉ dùng cho những trường hợp khẩn cấp thực sự."
  },
  {
    "id": 161,
    "word": "emergencies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪmˈɝdʒʌnsiz/",
    "meaning": "trường hợp khẩn cấp",
    "ex1": "In daily life, the money should be kept in a safe place and used only for real emergencies.",
    "ex1_vi": "Trong cuộc sống hằng ngày, tiền nên được giữ ở nơi an toàn và chỉ dùng cho những trường hợp khẩn cấp thực sự."
  },
  {
    "id": 162,
    "word": "regular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛɡjʌlɝ/",
    "meaning": "đều đặn",
    "ex1": "For many families, regular saving can create strong financial protection for the future.",
    "ex1_vi": "Đối với nhiều gia đình, tiết kiệm đều đặn có thể tạo ra sự bảo vệ tài chính vững chắc cho tương lai."
  },
  {
    "id": 163,
    "word": "create",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪt/",
    "meaning": "tạo ra",
    "ex1": "When managing money, regular saving can create strong financial protection for the future.",
    "ex1_vi": "Khi quản lý tiền, tiết kiệm đều đặn có thể tạo ra sự bảo vệ tài chính vững chắc cho tương lai."
  },
  {
    "id": 164,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋ/",
    "meaning": "khỏe; mạnh",
    "ex1": "In everyday spending, regular saving can create strong financial protection for the future.",
    "ex1_vi": "Trong việc chi tiêu hằng ngày, tiết kiệm đều đặn có thể tạo ra sự bảo vệ tài chính vững chắc cho tương lai."
  },
  {
    "id": 165,
    "word": "protection",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɹətˈɛkʃən/",
    "meaning": "sự bảo vệ",
    "ex1": "For careful planning, regular saving can create strong financial protection for the future.",
    "ex1_vi": "Để lập kế hoạch cẩn thận, tiết kiệm đều đặn có thể tạo ra sự bảo vệ tài chính vững chắc cho tương lai."
  },
  {
    "id": 166,
    "word": "happy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈæpi/",
    "meaning": "vui vẻ",
    "ex1": "When thinking about money, however, money alone cannot create a truly happy life.",
    "ex1_vi": "Khi suy nghĩ về tiền, tuy nhiên, chỉ tiền thôi không thể tạo ra một cuộc sống thật sự hạnh phúc."
  },
  {
    "id": 167,
    "word": "life",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪf/",
    "meaning": "cuộc sống",
    "ex1": "In a simple financial example, money can make life easier because it helps people meet their needs.",
    "ex1_vi": "Trong một ví dụ tài chính đơn giản, tiền có thể làm cuộc sống dễ dàng hơn vì nó giúp mọi người đáp ứng nhu cầu của mình."
  },
  {
    "id": 168,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm; tạo",
    "ex1": "For responsible choices, money can make life easier because it helps people meet their needs.",
    "ex1_vi": "Để có những lựa chọn có trách nhiệm, tiền có thể làm cuộc sống dễ dàng hơn vì nó giúp mọi người đáp ứng nhu cầu của mình."
  },
  {
    "id": 169,
    "word": "easier",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈiziɝ/",
    "meaning": "dễ hơn",
    "ex1": "When planning for the future, money can make life easier because it helps people meet their needs.",
    "ex1_vi": "Khi lập kế hoạch cho tương lai, tiền có thể làm cuộc sống dễ dàng hơn vì nó giúp mọi người đáp ứng nhu cầu của mình."
  },
  {
    "id": 170,
    "word": "meet",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈit/",
    "meaning": "gặp gỡ",
    "ex1": "In common money situations, money can make life easier because it helps people meet their needs.",
    "ex1_vi": "Trong những tình huống tiền bạc thường gặp, tiền có thể làm cuộc sống dễ dàng hơn vì nó giúp mọi người đáp ứng nhu cầu của mình."
  },
  {
    "id": 171,
    "word": "needs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈidz/",
    "meaning": "nhu cầu; cần",
    "ex1": "For a family budget, money can make life easier because it helps people meet their needs.",
    "ex1_vi": "Đối với ngân sách gia đình, tiền có thể làm cuộc sống dễ dàng hơn vì nó giúp mọi người đáp ứng nhu cầu của mình."
  },
  {
    "id": 172,
    "word": "allows",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌlˈaʊz/",
    "meaning": "cho phép",
    "ex1": "When making daily choices, it allows families to buy food, receive medical care, study, travel, and enjoy different activities.",
    "ex1_vi": "Khi đưa ra lựa chọn hằng ngày, nó cho phép các gia đình mua thực phẩm, nhận chăm sóc y tế, học tập, du lịch và tận hưởng những hoạt động khác nhau."
  },
  {
    "id": 173,
    "word": "buy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈaɪ/",
    "meaning": "mua",
    "ex1": "In practical life, it allows families to buy food, receive medical care, study, travel, and enjoy different activities.",
    "ex1_vi": "Trong cuộc sống thực tế, nó cho phép các gia đình mua thực phẩm, nhận chăm sóc y tế, học tập, du lịch và tận hưởng những hoạt động khác nhau."
  },
  {
    "id": 174,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thức ăn",
    "ex1": "For smart spending, it allows families to buy food, receive medical care, study, travel, and enjoy different activities.",
    "ex1_vi": "Để chi tiêu thông minh, nó cho phép các gia đình mua thực phẩm, nhận chăm sóc y tế, học tập, du lịch và tận hưởng những hoạt động khác nhau."
  },
  {
    "id": 175,
    "word": "receive",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rʌsˈiv/",
    "meaning": "nhận",
    "ex1": "When saving money, it allows families to buy food, receive medical care, study, travel, and enjoy different activities.",
    "ex1_vi": "Khi tiết kiệm tiền, nó cho phép các gia đình mua thực phẩm, nhận chăm sóc y tế, học tập, du lịch và tận hưởng những hoạt động khác nhau."
  },
  {
    "id": 176,
    "word": "medical",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈɛdʌkʌl/",
    "meaning": "thuộc y tế",
    "ex1": "In ordinary shopping, it allows families to buy food, receive medical care, study, travel, and enjoy different activities.",
    "ex1_vi": "Trong việc mua sắm thông thường, nó cho phép các gia đình mua thực phẩm, nhận chăm sóc y tế, học tập, du lịch và tận hưởng những hoạt động khác nhau."
  },
  {
    "id": 177,
    "word": "care",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɛr/",
    "meaning": "quan tâm",
    "ex1": "For good financial habits, it allows families to buy food, receive medical care, study, travel, and enjoy different activities.",
    "ex1_vi": "Để có thói quen tài chính tốt, nó cho phép các gia đình mua thực phẩm, nhận chăm sóc y tế, học tập, du lịch và tận hưởng những hoạt động khác nhau."
  },
  {
    "id": 178,
    "word": "study",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈʌdi/",
    "meaning": "học",
    "ex1": "When people plan expenses, it allows families to buy food, receive medical care, study, travel, and enjoy different activities.",
    "ex1_vi": "Khi mọi người lên kế hoạch chi tiêu, nó cho phép các gia đình mua thực phẩm, nhận chăm sóc y tế, học tập, du lịch và tận hưởng những hoạt động khác nhau."
  },
  {
    "id": 179,
    "word": "travel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tɹˈævəl/",
    "meaning": "du lịch; việc đi lại",
    "ex1": "In a careful household plan, it allows families to buy food, receive medical care, study, travel, and enjoy different activities.",
    "ex1_vi": "Trong một kế hoạch gia đình cẩn thận, nó cho phép các gia đình mua thực phẩm, nhận chăm sóc y tế, học tập, du lịch và tận hưởng những hoạt động khác nhau."
  },
  {
    "id": 180,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thích; tận hưởng",
    "ex1": "For everyday financial decisions, it allows families to buy food, receive medical care, study, travel, and enjoy different activities.",
    "ex1_vi": "Đối với các quyết định tài chính hằng ngày, nó cho phép các gia đình mua thực phẩm, nhận chăm sóc y tế, học tập, du lịch và tận hưởng những hoạt động khác nhau."
  },
  {
    "id": 181,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "In daily life, it allows families to buy food, receive medical care, study, travel, and enjoy different activities.",
    "ex1_vi": "Trong cuộc sống hằng ngày, nó cho phép các gia đình mua thực phẩm, nhận chăm sóc y tế, học tập, du lịch và tận hưởng những hoạt động khác nhau."
  },
  {
    "id": 182,
    "word": "activities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/æktˈɪvʌtiz/",
    "meaning": "các hoạt động",
    "ex1": "For many families, it allows families to buy food, receive medical care, study, travel, and enjoy different activities.",
    "ex1_vi": "Đối với nhiều gia đình, nó cho phép các gia đình mua thực phẩm, nhận chăm sóc y tế, học tập, du lịch và tận hưởng những hoạt động khác nhau."
  },
  {
    "id": 183,
    "word": "stability",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stʌbˈɪlɪti/",
    "meaning": "sự ổn định",
    "ex1": "When managing money, financial stability can also reduce worry.",
    "ex1_vi": "Khi quản lý tiền, sự ổn định tài chính cũng có thể giảm lo lắng."
  },
  {
    "id": 184,
    "word": "reduce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹədˈus/",
    "meaning": "giảm",
    "ex1": "In everyday spending, financial stability can also reduce worry.",
    "ex1_vi": "Trong việc chi tiêu hằng ngày, sự ổn định tài chính cũng có thể giảm lo lắng."
  },
  {
    "id": 185,
    "word": "worry",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝi/",
    "meaning": "sự lo lắng",
    "ex1": "For careful planning, financial stability can also reduce worry.",
    "ex1_vi": "Để lập kế hoạch cẩn thận, sự ổn định tài chính cũng có thể giảm lo lắng."
  },
  {
    "id": 186,
    "word": "alone",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌlˈoʊn/",
    "meaning": "một mình; chỉ riêng",
    "ex1": "When thinking about money, however, money alone cannot create a truly happy life.",
    "ex1_vi": "Khi suy nghĩ về tiền, tuy nhiên, chỉ tiền thôi không thể tạo ra một cuộc sống thật sự hạnh phúc."
  },
  {
    "id": 187,
    "word": "cannot",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈænɑt/",
    "meaning": "không thể",
    "ex1": "In a simple financial example, however, money alone cannot create a truly happy life.",
    "ex1_vi": "Trong một ví dụ tài chính đơn giản, tuy nhiên, chỉ tiền thôi không thể tạo ra một cuộc sống thật sự hạnh phúc."
  },
  {
    "id": 188,
    "word": "truly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/trˈuli/",
    "meaning": "thật sự",
    "ex1": "For responsible choices, however, money alone cannot create a truly happy life.",
    "ex1_vi": "Để có những lựa chọn có trách nhiệm, tuy nhiên, chỉ tiền thôi không thể tạo ra một cuộc sống thật sự hạnh phúc."
  },
  {
    "id": 189,
    "word": "health",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛlθ/",
    "meaning": "sức khỏe",
    "ex1": "When planning for the future, people also need good health, loving relationships, meaningful work, and time to relax.",
    "ex1_vi": "Khi lập kế hoạch cho tương lai, mọi người cũng cần sức khỏe tốt, những mối quan hệ yêu thương, công việc có ý nghĩa và thời gian thư giãn."
  },
  {
    "id": 190,
    "word": "loving",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈʌvɪŋ/",
    "meaning": "yêu thương",
    "ex1": "In common money situations, people also need good health, loving relationships, meaningful work, and time to relax.",
    "ex1_vi": "Trong những tình huống tiền bạc thường gặp, mọi người cũng cần sức khỏe tốt, những mối quan hệ yêu thương, công việc có ý nghĩa và thời gian thư giãn."
  },
  {
    "id": 191,
    "word": "relationships",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rilˈeɪʃʌnʃˌɪps/",
    "meaning": "các mối quan hệ",
    "ex1": "For a family budget, people also need good health, loving relationships, meaningful work, and time to relax.",
    "ex1_vi": "Đối với ngân sách gia đình, mọi người cũng cần sức khỏe tốt, những mối quan hệ yêu thương, công việc có ý nghĩa và thời gian thư giãn."
  },
  {
    "id": 192,
    "word": "meaningful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈinɪŋfʌl/",
    "meaning": "có ý nghĩa",
    "ex1": "When making daily choices, people also need good health, loving relationships, meaningful work, and time to relax.",
    "ex1_vi": "Khi đưa ra lựa chọn hằng ngày, mọi người cũng cần sức khỏe tốt, những mối quan hệ yêu thương, công việc có ý nghĩa và thời gian thư giãn."
  },
  {
    "id": 193,
    "word": "relax",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪlˈæks/",
    "meaning": "thư giãn",
    "ex1": "In practical life, people also need good health, loving relationships, meaningful work, and time to relax.",
    "ex1_vi": "Trong cuộc sống thực tế, mọi người cũng cần sức khỏe tốt, những mối quan hệ yêu thương, công việc có ý nghĩa và thời gian thư giãn."
  },
  {
    "id": 194,
    "word": "rich",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɪtʃ/",
    "meaning": "phong phú",
    "ex1": "For smart spending, a rich person may still feel lonely or unhappy.",
    "ex1_vi": "Để chi tiêu thông minh, một người giàu vẫn có thể cảm thấy cô đơn hoặc không hạnh phúc."
  },
  {
    "id": 195,
    "word": "still",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/stˈɪl/",
    "meaning": "vẫn",
    "ex1": "When saving money, a rich person may still feel lonely or unhappy.",
    "ex1_vi": "Khi tiết kiệm tiền, một người giàu vẫn có thể cảm thấy cô đơn hoặc không hạnh phúc."
  },
  {
    "id": 196,
    "word": "feel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈil/",
    "meaning": "cảm thấy",
    "ex1": "In ordinary shopping, a rich person may still feel lonely or unhappy.",
    "ex1_vi": "Trong việc mua sắm thông thường, một người giàu vẫn có thể cảm thấy cô đơn hoặc không hạnh phúc."
  },
  {
    "id": 197,
    "word": "lonely",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈoʊnli/",
    "meaning": "cô đơn",
    "ex1": "For good financial habits, a rich person may still feel lonely or unhappy.",
    "ex1_vi": "Để có thói quen tài chính tốt, một người giàu vẫn có thể cảm thấy cô đơn hoặc không hạnh phúc."
  },
  {
    "id": 198,
    "word": "unhappy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌnhˈæpi/",
    "meaning": "không vui",
    "ex1": "When people plan expenses, a rich person may still feel lonely or unhappy.",
    "ex1_vi": "Khi mọi người lên kế hoạch chi tiêu, một người giàu vẫn có thể cảm thấy cô đơn hoặc không hạnh phúc."
  },
  {
    "id": 199,
    "word": "best",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɛst/",
    "meaning": "tốt nhất",
    "ex1": "In a careful household plan, the best way to use money is to create a balanced life.",
    "ex1_vi": "Trong một kế hoạch gia đình cẩn thận, cách tốt nhất để sử dụng tiền là tạo ra một cuộc sống cân bằng."
  },
  {
    "id": 200,
    "word": "way",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪ/",
    "meaning": "cách",
    "ex1": "For everyday financial decisions, the best way to use money is to create a balanced life.",
    "ex1_vi": "Đối với các quyết định tài chính hằng ngày, cách tốt nhất để sử dụng tiền là tạo ra một cuộc sống cân bằng."
  },
  {
    "id": 201,
    "word": "balanced",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈælʌnst/",
    "meaning": "cân bằng",
    "ex1": "In daily life, the best way to use money is to create a balanced life.",
    "ex1_vi": "Trong cuộc sống hằng ngày, cách tốt nhất để sử dụng tiền là tạo ra một cuộc sống cân bằng."
  },
  {
    "id": 202,
    "word": "spend",
    "type": "verb",
    "cat": "v",
    "phonetic": "/spˈɛnd/",
    "meaning": "chi tiêu",
    "ex1": "For many families, people should spend responsibly, save for the future, and help others when possible.",
    "ex1_vi": "Đối với nhiều gia đình, mọi người nên chi tiêu có trách nhiệm, tiết kiệm cho tương lai và giúp đỡ người khác khi có thể."
  },
  {
    "id": 203,
    "word": "responsibly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/rɪspˈɑnsʌbli/",
    "meaning": "có trách nhiệm",
    "ex1": "When managing money, people should spend responsibly, save for the future, and help others when possible.",
    "ex1_vi": "Khi quản lý tiền, mọi người nên chi tiêu có trách nhiệm, tiết kiệm cho tương lai và giúp đỡ người khác khi có thể."
  },
  {
    "id": 204,
    "word": "others",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈʌðɝz/",
    "meaning": "những loài khác",
    "ex1": "In everyday spending, people should spend responsibly, save for the future, and help others when possible.",
    "ex1_vi": "Trong việc chi tiêu hằng ngày, mọi người nên chi tiêu có trách nhiệm, tiết kiệm cho tương lai và giúp đỡ người khác khi có thể."
  },
  {
    "id": 205,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "For careful planning, people should spend responsibly, save for the future, and help others when possible.",
    "ex1_vi": "Để lập kế hoạch cẩn thận, mọi người nên chi tiêu có trách nhiệm, tiết kiệm cho tương lai và giúp đỡ người khác khi có thể."
  },
  {
    "id": 206,
    "word": "possible",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑsʌbʌl/",
    "meaning": "có thể; khả thi",
    "ex1": "When thinking about money, people should spend responsibly, save for the future, and help others when possible.",
    "ex1_vi": "Khi suy nghĩ về tiền, mọi người nên chi tiêu có trách nhiệm, tiết kiệm cho tương lai và giúp đỡ người khác khi có thể."
  },
  {
    "id": 207,
    "word": "valuable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/vˈæljʌbʌl/",
    "meaning": "quý giá",
    "ex1": "In a simple financial example, money is valuable, but happiness also comes from kindness, gratitude, and time with loved ones.",
    "ex1_vi": "Trong một ví dụ tài chính đơn giản, tiền có giá trị, nhưng hạnh phúc cũng đến từ lòng tốt, sự biết ơn và thời gian bên những người thân yêu."
  },
  {
    "id": 208,
    "word": "but",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bˈʌt/",
    "meaning": "nhưng",
    "ex1": "For responsible choices, money is valuable, but happiness also comes from kindness, gratitude, and time with loved ones.",
    "ex1_vi": "Để có những lựa chọn có trách nhiệm, tiền có giá trị, nhưng hạnh phúc cũng đến từ lòng tốt, sự biết ơn và thời gian bên những người thân yêu."
  },
  {
    "id": 209,
    "word": "happiness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈæpinʌs/",
    "meaning": "hạnh phúc",
    "ex1": "When planning for the future, money is valuable, but happiness also comes from kindness, gratitude, and time with loved ones.",
    "ex1_vi": "Khi lập kế hoạch cho tương lai, tiền có giá trị, nhưng hạnh phúc cũng đến từ lòng tốt, sự biết ơn và thời gian bên những người thân yêu."
  },
  {
    "id": 210,
    "word": "comes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌmz/",
    "meaning": "đến",
    "ex1": "In common money situations, money is valuable, but happiness also comes from kindness, gratitude, and time with loved ones.",
    "ex1_vi": "Trong những tình huống tiền bạc thường gặp, tiền có giá trị, nhưng hạnh phúc cũng đến từ lòng tốt, sự biết ơn và thời gian bên những người thân yêu."
  },
  {
    "id": 211,
    "word": "kindness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈaɪndnʌs/",
    "meaning": "lòng tốt",
    "ex1": "For a family budget, money is valuable, but happiness also comes from kindness, gratitude, and time with loved ones.",
    "ex1_vi": "Đối với ngân sách gia đình, tiền có giá trị, nhưng hạnh phúc cũng đến từ lòng tốt, sự biết ơn và thời gian bên những người thân yêu."
  },
  {
    "id": 212,
    "word": "gratitude",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡrˈætʌtˌud/",
    "meaning": "lòng biết ơn",
    "ex1": "When making daily choices, money is valuable, but happiness also comes from kindness, gratitude, and time with loved ones.",
    "ex1_vi": "Khi đưa ra lựa chọn hằng ngày, tiền có giá trị, nhưng hạnh phúc cũng đến từ lòng tốt, sự biết ơn và thời gian bên những người thân yêu."
  },
  {
    "id": 213,
    "word": "loved",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʌvd/",
    "meaning": "được yêu thương",
    "ex1": "In practical life, money is valuable, but happiness also comes from kindness, gratitude, and time with loved ones.",
    "ex1_vi": "Trong cuộc sống thực tế, tiền có giá trị, nhưng hạnh phúc cũng đến từ lòng tốt, sự biết ơn và thời gian bên những người thân yêu."
  },
  {
    "id": 214,
    "word": "ones",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈʌnz/",
    "meaning": "những người; những thứ",
    "ex1": "For smart spending, money is valuable, but happiness also comes from kindness, gratitude, and time with loved ones.",
    "ex1_vi": "Để chi tiêu thông minh, tiền có giá trị, nhưng hạnh phúc cũng đến từ lòng tốt, sự biết ơn và thời gian bên những người thân yêu."
  }
];

const newReadingVocabOrder = [
  "using",
  "cash",
  "and",
  "bank",
  "cards",
  "includes",
  "coins",
  "banknotes",
  "people",
  "can",
  "hold",
  "use",
  "directly",
  "simple",
  "useful",
  "small",
  "purchases",
  "paying",
  "also",
  "help",
  "see",
  "clearly",
  "how",
  "much",
  "money",
  "spending",
  "digital",
  "payments",
  "convenient",
  "because",
  "do",
  "not",
  "need",
  "carry",
  "pay",
  "products",
  "shops",
  "or",
  "online",
  "however",
  "users",
  "must",
  "protect",
  "passwords",
  "personal",
  "banking",
  "information",
  "both",
  "payment",
  "methods",
  "have",
  "advantages",
  "disadvantages",
  "should",
  "choose",
  "safest",
  "most",
  "suitable",
  "method",
  "each",
  "situation",
  "check",
  "accounts",
  "regularly",
  "find",
  "mistakes",
  "unusual",
  "earning",
  "work",
  "adults",
  "earn",
  "working",
  "may",
  "offices",
  "factories",
  "schools",
  "hospitals",
  "farms",
  "some",
  "run",
  "businesses",
  "home",
  "amount",
  "person",
  "earns",
  "often",
  "depends",
  "skills",
  "education",
  "experience",
  "responsibilities",
  "learning",
  "new",
  "workers",
  "better",
  "opportunities",
  "good",
  "usually",
  "responsible",
  "honest",
  "willing",
  "improve",
  "requires",
  "time",
  "effort",
  "so",
  "carefully",
  "important",
  "expenses",
  "save",
  "future",
  "avoid",
  "wasting",
  "respecting",
  "teaches",
  "respect",
  "value",
  "importance",
  "emergency",
  "savings",
  "kept",
  "unexpected",
  "situations",
  "suddenly",
  "become",
  "sick",
  "lose",
  "job",
  "repair",
  "motorbike",
  "household",
  "item",
  "problems",
  "happen",
  "without",
  "warning",
  "having",
  "helps",
  "urgent",
  "borrowing",
  "too",
  "gives",
  "families",
  "feeling",
  "safety",
  "reduces",
  "financial",
  "stress",
  "difficult",
  "times",
  "build",
  "fund",
  "saving",
  "income",
  "month",
  "safe",
  "place",
  "used",
  "only",
  "real",
  "emergencies",
  "regular",
  "create",
  "strong",
  "protection",
  "happy",
  "life",
  "make",
  "easier",
  "meet",
  "needs",
  "allows",
  "buy",
  "food",
  "receive",
  "medical",
  "care",
  "study",
  "travel",
  "enjoy",
  "different",
  "activities",
  "stability",
  "reduce",
  "worry",
  "alone",
  "cannot",
  "truly",
  "health",
  "loving",
  "relationships",
  "meaningful",
  "relax",
  "rich",
  "still",
  "feel",
  "lonely",
  "unhappy",
  "best",
  "way",
  "balanced",
  "spend",
  "responsibly",
  "others",
  "when",
  "possible",
  "valuable",
  "but",
  "happiness",
  "comes",
  "kindness",
  "gratitude",
  "loved",
  "ones"
];
