const newEssayData = [
  {
    "text": "4. MY SCHOOL\nA Place to Learn and Grow\nMy school is located near my house, so it only takes me a few minutes to get there every morning. Although it is not very large, it is clean and beautiful.\n\nThere are many classrooms, trees, and flowers in the school yard. The teachers are friendly and helpful. They always encourage students to study hard and join school activities.\n\nI enjoy going to school because I can learn many useful things and meet my friends every day. My favorite subjects are English and Science. I am proud to be a student at my school.",
    "vi": "4. TRƯỜNG HỌC CỦA TÔI\nNơi để học tập và trưởng thành\nTrường tôi nằm gần nhà nên mỗi sáng tôi chỉ mất vài phút để đến đó. Mặc dù trường không quá lớn, nó sạch sẽ và đẹp.\n\nCó nhiều phòng học, cây và hoa trong sân trường. Các giáo viên thân thiện và nhiệt tình. Họ luôn khuyến khích học sinh học chăm chỉ và tham gia các hoạt động của trường.\n\nTôi thích đi học vì tôi có thể học nhiều điều hữu ích và gặp bạn bè mỗi ngày. Môn học yêu thích của tôi là tiếng Anh và Khoa học. Tôi tự hào là học sinh của trường mình."
  },
  {
    "text": "5. MY FAVORITE FOOD\nA Delicious Meal I Love\nMy favorite food is pizza because it is delicious and easy to eat. Pizza comes in many different flavors, so everyone can choose the one they like best.\n\nI usually eat pizza with my family or friends on weekends or special occasions. My favorite pizza has cheese, chicken, tomatoes, and mushrooms. The smell of fresh pizza always makes me hungry.\n\nAlthough I love pizza very much, I know that eating too much fast food is not healthy. Therefore, I also eat vegetables, fruit, and fish regularly to stay healthy and strong.",
    "vi": "5. MÓN ĂN YÊU THÍCH CỦA TÔI\nMột bữa ăn ngon mà tôi yêu thích\nMón ăn yêu thích của tôi là pizza vì nó ngon và dễ ăn. Pizza có nhiều hương vị khác nhau nên mọi người có thể chọn loại mình thích nhất.\n\nTôi thường ăn pizza với gia đình hoặc bạn bè vào cuối tuần hoặc những dịp đặc biệt. Pizza yêu thích của tôi có phô mai, thịt gà, cà chua và nấm. Mùi pizza tươi luôn làm tôi thấy đói.\n\nMặc dù tôi rất thích pizza, tôi biết rằng ăn quá nhiều thức ăn nhanh không tốt cho sức khỏe. Vì vậy, tôi cũng ăn rau, trái cây và cá thường xuyên để luôn khỏe mạnh."
  },
  {
    "text": "6. MY DREAM JOB\nMy Future Career Goal\nMy dream job is to become a doctor in the future. I want to help sick people and make their lives better. I think doctors play an important role in society.\n\nTo achieve my dream, I study hard every day, especially Biology and English. I also try to improve my communication skills because doctors need to talk to patients clearly.\n\nI know becoming a doctor is not easy because it requires many years of study and training. However, I will continue to work hard and never give up on my dream.",
    "vi": "6. CÔNG VIỆC MƠ ƯỚC CỦA TÔI\nMục tiêu nghề nghiệp trong tương lai\nCông việc mơ ước của tôi là trở thành bác sĩ trong tương lai. Tôi muốn giúp người bệnh và làm cuộc sống của họ tốt hơn. Tôi nghĩ bác sĩ đóng vai trò quan trọng trong xã hội.\n\nĐể đạt được ước mơ, tôi học chăm chỉ mỗi ngày, đặc biệt là Sinh học và tiếng Anh. Tôi cũng cố gắng cải thiện kỹ năng giao tiếp vì bác sĩ cần nói chuyện rõ ràng với bệnh nhân.\n\nTôi biết trở thành bác sĩ không dễ vì việc đó đòi hỏi nhiều năm học tập và đào tạo. Tuy nhiên, tôi sẽ tiếp tục làm việc chăm chỉ và không bao giờ từ bỏ ước mơ."
  }
];
