const newEssayData = [
  {
    "text": "1. MY FAMILY\nLove and Support at Home\nMy family has four people: my father, my mother, my younger sister, and me. We live in a small but comfortable house in the city. My family is very important to me because they always care about me and help me in difficult times.\n\nMy father works in an office, and my mother is a teacher. My sister is a student and enjoys drawing pictures. During the day, everyone is busy with work or study, but we always make time for each other.\n\nIn the evening, we usually have dinner together and talk about our day. On weekends, we sometimes visit our grandparents or go shopping. I love my family very much because they always support me.",
    "vi": "1. GIA ĐÌNH CỦA TÔI\nTình yêu và sự hỗ trợ trong gia đình\nGia đình tôi có bốn người: cha tôi, mẹ tôi, em gái tôi và tôi. Chúng tôi sống trong một ngôi nhà nhỏ nhưng thoải mái ở thành phố. Gia đình rất quan trọng với tôi vì họ luôn quan tâm và giúp đỡ tôi trong những lúc khó khăn.\n\nCha tôi làm việc trong một văn phòng, còn mẹ tôi là giáo viên. Em gái tôi là học sinh và thích vẽ tranh. Ban ngày, mọi người đều bận rộn với công việc hoặc học tập, nhưng chúng tôi luôn dành thời gian cho nhau.\n\nBuổi tối, chúng tôi thường ăn tối cùng nhau và trò chuyện về một ngày của mình. Vào cuối tuần, đôi khi chúng tôi thăm ông bà hoặc đi mua sắm. Tôi rất yêu gia đình vì họ luôn ủng hộ tôi."
  },
  {
    "text": "2. MY HOBBIES\nActivities That Make Me Happy\nEveryone has hobbies, and I have several hobbies that I enjoy in my free time. My favorite hobby is listening to music because it helps me relax and feel happy after studying.\n\nI usually listen to pop songs on my phone or computer. Sometimes, I sing along with my favorite songs. I also enjoy reading books and watching interesting videos online.\n\nBesides that, I like playing badminton with my friends in the afternoon. These hobbies help me stay active and reduce stress. I think hobbies are important because they make life more enjoyable and interesting.",
    "vi": "2. SỞ THÍCH CỦA TÔI\nNhững hoạt động làm tôi vui\nMọi người đều có sở thích, và tôi có một số sở thích mà tôi yêu thích trong thời gian rảnh. Sở thích yêu thích nhất của tôi là nghe nhạc vì nó giúp tôi thư giãn và cảm thấy vui sau khi học.\n\nTôi thường nghe nhạc pop trên điện thoại hoặc máy tính. Đôi khi, tôi hát theo những bài hát yêu thích. Tôi cũng thích đọc sách và xem những video thú vị trên mạng.\n\nNgoài ra, tôi thích chơi cầu lông với bạn bè vào buổi chiều. Những sở thích này giúp tôi năng động và giảm căng thẳng. Tôi nghĩ sở thích rất quan trọng vì chúng làm cuộc sống thú vị và vui hơn."
  },
  {
    "text": "3. MY BEST FRIEND\nA Special Person in My Life\nMy best friend is Nam. He is sixteen years old and studies in the same class as me. He is friendly, kind, and always ready to help other people.\n\nNam is very good at English and Mathematics. Whenever I do not understand my homework, he explains it to me patiently. Thanks to his help, my grades have improved a lot this year.\n\nWe spend a lot of time together after school. We often play football, watch movies, or study in the library. I feel lucky to have such a wonderful friend in my life.",
    "vi": "3. NGƯỜI BẠN THÂN NHẤT CỦA TÔI\nMột người đặc biệt trong cuộc đời tôi\nNgười bạn thân nhất của tôi là Nam. Bạn ấy mười sáu tuổi và học cùng lớp với tôi. Bạn ấy thân thiện, tốt bụng và luôn sẵn sàng giúp đỡ người khác.\n\nNam rất giỏi tiếng Anh và Toán. Bất cứ khi nào tôi không hiểu bài tập về nhà, bạn ấy kiên nhẫn giải thích cho tôi. Nhờ sự giúp đỡ của bạn ấy, điểm số của tôi đã cải thiện rất nhiều trong năm nay.\n\nChúng tôi dành nhiều thời gian bên nhau sau giờ học. Chúng tôi thường chơi bóng đá, xem phim hoặc học trong thư viện. Tôi cảm thấy may mắn khi có một người bạn tuyệt vời như vậy trong cuộc đời."
  }
];
