// ===== happy01 ESSAY =====

const newEssayData = [
  {
    "text": "1. What Is Happiness?\nHappiness is a warm feeling that makes life brighter and more meaningful. It can come from many simple things, such as a kind smile, a good meal, or a peaceful morning. Different people may understand happiness in different ways.\n\nSome people feel happy when they achieve a goal, while others enjoy spending time with family and friends. Happiness does not always depend on money or success. Often, small moments can bring the greatest joy.\n\nTo live happily, we should notice the good things around us. We can be thankful, help others, and take care of ourselves. A happy life grows from positive thoughts, loving relationships, and simple daily choices today.",
    "vi": "1. Hạnh phúc là gì?\nHạnh phúc là một cảm giác ấm áp khiến cuộc sống tươi sáng và ý nghĩa hơn. Nó có thể đến từ nhiều điều đơn giản, chẳng hạn như một nụ cười tử tế, một bữa ăn ngon hoặc một buổi sáng yên bình. Mỗi người có thể hiểu hạnh phúc theo những cách khác nhau.\n\nMột số người cảm thấy hạnh phúc khi đạt được mục tiêu, trong khi những người khác thích dành thời gian với gia đình và bạn bè. Hạnh phúc không phải lúc nào cũng phụ thuộc vào tiền bạc hay thành công. Thường thì những khoảnh khắc nhỏ bé có thể mang lại niềm vui lớn nhất.\n\nĐể sống hạnh phúc, chúng ta nên chú ý đến những điều tốt đẹp quanh mình. Chúng ta có thể biết ơn, giúp đỡ người khác và chăm sóc bản thân. Một cuộc sống hạnh phúc lớn lên từ những suy nghĩ tích cực, những mối quan hệ yêu thương và những lựa chọn đơn giản hằng ngày."
  },
  {
    "text": "2. Happiness in Everyday Life\nHappiness can be found in ordinary moments every day. Waking up to a sunny morning, drinking a favorite drink, or hearing a friendly voice can make us smile. We do not need a special event to feel happy.\n\nDaily life becomes better when we slow down and enjoy small experiences. A short walk, a funny story, or a quiet rest can improve our mood. These moments may seem simple, but they are important.\n\nWe can create more happiness by paying attention to what is good. Instead of always wanting more, we should value what we already have. Simple joy helps us feel calm, grateful, and more satisfied with life today.",
    "vi": "2. Hạnh phúc trong cuộc sống hằng ngày\nHạnh phúc có thể được tìm thấy trong những khoảnh khắc bình thường mỗi ngày. Thức dậy vào một buổi sáng đầy nắng, uống thức uống yêu thích hoặc nghe một giọng nói thân thiện có thể khiến chúng ta mỉm cười. Chúng ta không cần một sự kiện đặc biệt để cảm thấy hạnh phúc.\n\nCuộc sống hằng ngày trở nên tốt đẹp hơn khi chúng ta sống chậm lại và tận hưởng những trải nghiệm nhỏ. Một cuộc đi bộ ngắn, một câu chuyện vui hoặc một khoảng nghỉ yên tĩnh có thể cải thiện tâm trạng. Những khoảnh khắc này có vẻ đơn giản nhưng rất quan trọng.\n\nChúng ta có thể tạo thêm hạnh phúc bằng cách chú ý đến những điều tốt đẹp. Thay vì luôn muốn nhiều hơn, chúng ta nên trân trọng những gì mình đã có. Niềm vui giản dị giúp chúng ta cảm thấy bình tĩnh, biết ơn và hài lòng hơn với cuộc sống."
  },
  {
    "text": "3. Spending Time with Family\nFamily is an important source of happiness for many people. Parents, children, brothers, and sisters share love, care, and support. Being together helps everyone feel safe, understood, and less lonely in difficult times.\n\nFamilies can enjoy simple activities such as eating dinner, watching a film, or taking a walk. These moments create good memories and make relationships stronger. Talking openly also helps family members understand each other better.\n\nA happy family does not need to be perfect. People may disagree, but kindness and respect can solve many problems. When family members listen, forgive, and help one another, the home becomes a warmer, safer, and much happier place for everyone together.",
    "vi": "3. Dành thời gian với gia đình\nGia đình là một nguồn hạnh phúc quan trọng đối với nhiều người. Cha mẹ, con cái, anh em trai và chị em gái chia sẻ tình yêu, sự quan tâm và hỗ trợ. Ở bên nhau giúp mọi người cảm thấy an toàn, được thấu hiểu và bớt cô đơn trong những lúc khó khăn.\n\nCác gia đình có thể tận hưởng những hoạt động đơn giản như ăn tối, xem phim hoặc đi dạo. Những khoảnh khắc này tạo nên kỷ niệm đẹp và làm các mối quan hệ bền chặt hơn. Trò chuyện cởi mở cũng giúp các thành viên trong gia đình hiểu nhau hơn.\n\nMột gia đình hạnh phúc không cần phải hoàn hảo. Mọi người có thể bất đồng, nhưng lòng tốt và sự tôn trọng có thể giải quyết nhiều vấn đề. Khi các thành viên lắng nghe, tha thứ và giúp đỡ nhau, ngôi nhà trở thành một nơi ấm áp, an toàn và hạnh phúc hơn nhiều cho mọi người."
  }
];
