const lessonVocabularyWords = [
  "watering",
  "can",
  "useful",
  "tool",
  "taking",
  "care",
  "plants",
  "usually",
  "has",
  "handle",
  "large",
  "container",
  "and",
  "long",
  "spout",
  "cans",
  "often",
  "made",
  "plastic",
  "or",
  "metal",
  "come",
  "many",
  "sizes",
  "gardeners",
  "use",
  "give",
  "water",
  "flowers",
  "vegetables",
  "small",
  "trees",
  "helps",
  "direct",
  "toward",
  "soil",
  "without",
  "damaging",
  "leaves",
  "especially",
  "pots",
  "after",
  "using",
  "should",
  "emptied",
  "kept",
  "dry",
  "place",
  "regular",
  "grow",
  "strong",
  "healthy",
  "however",
  "people",
  "not",
  "too",
  "much",
  "because",
  "wet",
  "damage",
  "roots",
  "garden",
  "hose",
  "flexible",
  "tube",
  "used",
  "carry",
  "connected",
  "outdoor",
  "tap",
  "some",
  "hoses",
  "have",
  "spray",
  "nozzle",
  "allows",
  "control",
  "strength",
  "direction",
  "lawns",
  "vegetable",
  "gardens",
  "faster",
  "more",
  "convenient",
  "than",
  "carrying",
  "buckets",
  "also",
  "clean",
  "paths",
  "tools",
  "furniture",
  "turned",
  "off",
  "completely",
  "rolled",
  "up",
  "carefully",
  "prevent",
  "twisting",
  "breaking",
  "keeping",
  "away",
  "sunlight",
  "help",
  "last",
  "longer",
  "shovel",
  "gardening",
  "wide",
  "blade",
  "commonly",
  "steel",
  "wood",
  "different",
  "shovels",
  "shapes",
  "jobs",
  "dig",
  "holes",
  "move",
  "plant",
  "sand",
  "compost",
  "when",
  "preparing",
  "new",
  "area",
  "sharp",
  "makes",
  "heavy",
  "work",
  "easier",
  "wear",
  "suitable",
  "shoes",
  "both",
  "hands",
  "working",
  "cleaned",
  "remove",
  "stored",
  "rust"
];

const newVocabData = [
  {
    "id": 1,
    "word": "watering",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɔtɝɪŋ/",
    "meaning": "việc tưới nước",
    "ex1": "For safe gardening, a watering can is a useful tool for taking care of plants.",
    "ex1_vi": "Để làm vườn an toàn, bình tưới cây là một dụng cụ hữu ích để chăm sóc cây."
  },
  {
    "id": 2,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể; bình (trong 'watering can')",
    "ex1": "During regular garden work, a watering can is a useful tool for taking care of plants.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, bình tưới cây là một dụng cụ hữu ích để chăm sóc cây."
  },
  {
    "id": 3,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈusfʌl/",
    "meaning": "hữu ích",
    "ex1": "When caring for plants, a watering can is a useful tool for taking care of plants.",
    "ex1_vi": "Khi chăm sóc cây, bình tưới cây là một dụng cụ hữu ích để chăm sóc cây."
  },
  {
    "id": 4,
    "word": "tool",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈul/",
    "meaning": "dụng cụ",
    "ex1": "For everyday garden tasks, a watering can is a useful tool for taking care of plants.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, bình tưới cây là một dụng cụ hữu ích để chăm sóc cây."
  },
  {
    "id": 5,
    "word": "taking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪkɪŋ/",
    "meaning": "việc chăm sóc/lấy",
    "ex1": "In practical gardening, a watering can is a useful tool for taking care of plants.",
    "ex1_vi": "Trong việc làm vườn thực tế, bình tưới cây là một dụng cụ hữu ích để chăm sóc cây."
  },
  {
    "id": 6,
    "word": "care",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɛr/",
    "meaning": "sự chăm sóc",
    "ex1": "In a well-kept garden, a watering can is a useful tool for taking care of plants.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, bình tưới cây là một dụng cụ hữu ích để chăm sóc cây."
  },
  {
    "id": 7,
    "word": "plants",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈænts/",
    "meaning": "cây cối",
    "ex1": "For safe gardening, a watering can is a useful tool for taking care of plants.",
    "ex1_vi": "Để làm vườn an toàn, bình tưới cây là một dụng cụ hữu ích để chăm sóc cây."
  },
  {
    "id": 8,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "During regular garden work, it usually has a handle, a large container, and a long spout.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, nó thường có tay cầm, một bình chứa lớn và một vòi dài."
  },
  {
    "id": 9,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "When caring for plants, it usually has a handle, a large container, and a long spout.",
    "ex1_vi": "Khi chăm sóc cây, nó thường có tay cầm, một bình chứa lớn và một vòi dài."
  },
  {
    "id": 10,
    "word": "handle",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈændʌl/",
    "meaning": "tay cầm",
    "ex1": "For everyday garden tasks, it usually has a handle, a large container, and a long spout.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, nó thường có tay cầm, một bình chứa lớn và một vòi dài."
  },
  {
    "id": 11,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒ/",
    "meaning": "lớn",
    "ex1": "In practical gardening, it usually has a handle, a large container, and a long spout.",
    "ex1_vi": "Trong việc làm vườn thực tế, nó thường có tay cầm, một bình chứa lớn và một vòi dài."
  },
  {
    "id": 12,
    "word": "container",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌntˈeɪnɝ/",
    "meaning": "bình/thùng chứa",
    "ex1": "In a well-kept garden, it usually has a handle, a large container, and a long spout.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, nó thường có tay cầm, một bình chứa lớn và một vòi dài."
  },
  {
    "id": 13,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "For safe gardening, it usually has a handle, a large container, and a long spout.",
    "ex1_vi": "Để làm vườn an toàn, nó thường có tay cầm, một bình chứa lớn và một vòi dài."
  },
  {
    "id": 14,
    "word": "long",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɔŋ/",
    "meaning": "dài",
    "ex1": "During regular garden work, it usually has a handle, a large container, and a long spout.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, nó thường có tay cầm, một bình chứa lớn và một vòi dài."
  },
  {
    "id": 15,
    "word": "spout",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈaʊt/",
    "meaning": "vòi rót; vòi tưới",
    "ex1": "When caring for plants, it usually has a handle, a large container, and a long spout.",
    "ex1_vi": "Khi chăm sóc cây, nó thường có tay cầm, một bình chứa lớn và một vòi dài."
  },
  {
    "id": 16,
    "word": "cans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈænz/",
    "meaning": "các bình",
    "ex1": "For everyday garden tasks, watering cans are often made of plastic or metal and come in many sizes.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, bình tưới cây thường được làm bằng nhựa hoặc kim loại và có nhiều kích cỡ."
  },
  {
    "id": 17,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "In practical gardening, watering cans are often made of plastic or metal and come in many sizes.",
    "ex1_vi": "Trong việc làm vườn thực tế, bình tưới cây thường được làm bằng nhựa hoặc kim loại và có nhiều kích cỡ."
  },
  {
    "id": 18,
    "word": "made",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪd/",
    "meaning": "được làm",
    "ex1": "In a well-kept garden, watering cans are often made of plastic or metal and come in many sizes.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, bình tưới cây thường được làm bằng nhựa hoặc kim loại và có nhiều kích cỡ."
  },
  {
    "id": 19,
    "word": "plastic",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/plˈæstɪk/",
    "meaning": "nhựa",
    "ex1": "For safe gardening, watering cans are often made of plastic or metal and come in many sizes.",
    "ex1_vi": "Để làm vườn an toàn, bình tưới cây thường được làm bằng nhựa hoặc kim loại và có nhiều kích cỡ."
  },
  {
    "id": 20,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "During regular garden work, watering cans are often made of plastic or metal and come in many sizes.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, bình tưới cây thường được làm bằng nhựa hoặc kim loại và có nhiều kích cỡ."
  },
  {
    "id": 21,
    "word": "metal",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈɛtʌl/",
    "meaning": "kim loại",
    "ex1": "When caring for plants, watering cans are often made of plastic or metal and come in many sizes.",
    "ex1_vi": "Khi chăm sóc cây, bình tưới cây thường được làm bằng nhựa hoặc kim loại và có nhiều kích cỡ."
  },
  {
    "id": 22,
    "word": "come",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌm/",
    "meaning": "có; xuất hiện",
    "ex1": "For everyday garden tasks, watering cans are often made of plastic or metal and come in many sizes.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, bình tưới cây thường được làm bằng nhựa hoặc kim loại và có nhiều kích cỡ."
  },
  {
    "id": 23,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "In practical gardening, watering cans are often made of plastic or metal and come in many sizes.",
    "ex1_vi": "Trong việc làm vườn thực tế, bình tưới cây thường được làm bằng nhựa hoặc kim loại và có nhiều kích cỡ."
  },
  {
    "id": 24,
    "word": "sizes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaɪzʌz/",
    "meaning": "kích cỡ",
    "ex1": "In a well-kept garden, watering cans are often made of plastic or metal and come in many sizes.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, bình tưới cây thường được làm bằng nhựa hoặc kim loại và có nhiều kích cỡ."
  },
  {
    "id": 25,
    "word": "gardeners",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɑrdʌnɝz/",
    "meaning": "người làm vườn",
    "ex1": "For safe gardening, gardeners use a watering can to give water to flowers, vegetables, and small trees.",
    "ex1_vi": "Để làm vườn an toàn, người làm vườn dùng bình tưới để tưới nước cho hoa, rau và cây nhỏ."
  },
  {
    "id": 26,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "During regular garden work, gardeners use a watering can to give water to flowers, vegetables, and small trees.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, người làm vườn dùng bình tưới để tưới nước cho hoa, rau và cây nhỏ."
  },
  {
    "id": 27,
    "word": "give",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪv/",
    "meaning": "cho; cung cấp",
    "ex1": "When caring for plants, gardeners use a watering can to give water to flowers, vegetables, and small trees.",
    "ex1_vi": "Khi chăm sóc cây, người làm vườn dùng bình tưới để tưới nước cho hoa, rau và cây nhỏ."
  },
  {
    "id": 28,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước; tưới nước",
    "ex1": "For everyday garden tasks, gardeners use a watering can to give water to flowers, vegetables, and small trees.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, người làm vườn dùng bình tưới để tưới nước cho hoa, rau và cây nhỏ."
  },
  {
    "id": 29,
    "word": "flowers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈaʊɝz/",
    "meaning": "hoa",
    "ex1": "In practical gardening, gardeners use a watering can to give water to flowers, vegetables, and small trees.",
    "ex1_vi": "Trong việc làm vườn thực tế, người làm vườn dùng bình tưới để tưới nước cho hoa, rau và cây nhỏ."
  },
  {
    "id": 30,
    "word": "vegetables",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɛdʒtʌbʌlz/",
    "meaning": "rau",
    "ex1": "In a well-kept garden, gardeners use a watering can to give water to flowers, vegetables, and small trees.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, người làm vườn dùng bình tưới để tưới nước cho hoa, rau và cây nhỏ."
  },
  {
    "id": 31,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "For safe gardening, gardeners use a watering can to give water to flowers, vegetables, and small trees.",
    "ex1_vi": "Để làm vườn an toàn, người làm vườn dùng bình tưới để tưới nước cho hoa, rau và cây nhỏ."
  },
  {
    "id": 32,
    "word": "trees",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈiz/",
    "meaning": "cây",
    "ex1": "During regular garden work, gardeners use a watering can to give water to flowers, vegetables, and small trees.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, người làm vườn dùng bình tưới để tưới nước cho hoa, rau và cây nhỏ."
  },
  {
    "id": 33,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "When caring for plants, the long spout helps direct water toward the soil without damaging the leaves.",
    "ex1_vi": "Khi chăm sóc cây, vòi dài giúp hướng nước về phía đất mà không làm hỏng lá."
  },
  {
    "id": 34,
    "word": "direct",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dɝˈɛkt/",
    "meaning": "hướng; trực tiếp",
    "ex1": "For everyday garden tasks, the long spout helps direct water toward the soil without damaging the leaves.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, vòi dài giúp hướng nước về phía đất mà không làm hỏng lá."
  },
  {
    "id": 35,
    "word": "toward",
    "type": "preposition",
    "cat": "prep",
    "phonetic": "/tʌwˈɔrd/",
    "meaning": "về phía",
    "ex1": "In practical gardening, the long spout helps direct water toward the soil without damaging the leaves.",
    "ex1_vi": "Trong việc làm vườn thực tế, vòi dài giúp hướng nước về phía đất mà không làm hỏng lá."
  },
  {
    "id": 36,
    "word": "soil",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔɪl/",
    "meaning": "đất",
    "ex1": "In a well-kept garden, the long spout helps direct water toward the soil without damaging the leaves.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, vòi dài giúp hướng nước về phía đất mà không làm hỏng lá."
  },
  {
    "id": 37,
    "word": "without",
    "type": "preposition",
    "cat": "prep",
    "phonetic": "/wɪθˈaʊt/",
    "meaning": "mà không",
    "ex1": "For safe gardening, the long spout helps direct water toward the soil without damaging the leaves.",
    "ex1_vi": "Để làm vườn an toàn, vòi dài giúp hướng nước về phía đất mà không làm hỏng lá."
  },
  {
    "id": 38,
    "word": "damaging",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈæmɪdʒɪŋ/",
    "meaning": "làm hỏng",
    "ex1": "During regular garden work, the long spout helps direct water toward the soil without damaging the leaves.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, vòi dài giúp hướng nước về phía đất mà không làm hỏng lá."
  },
  {
    "id": 39,
    "word": "leaves",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈivz/",
    "meaning": "lá",
    "ex1": "When caring for plants, the long spout helps direct water toward the soil without damaging the leaves.",
    "ex1_vi": "Khi chăm sóc cây, vòi dài giúp hướng nước về phía đất mà không làm hỏng lá."
  },
  {
    "id": 40,
    "word": "especially",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌspˈɛʃli/",
    "meaning": "đặc biệt",
    "ex1": "For everyday garden tasks, it is especially useful for plants in pots.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, nó đặc biệt hữu ích cho cây trồng trong chậu."
  },
  {
    "id": 41,
    "word": "pots",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑts/",
    "meaning": "chậu",
    "ex1": "In practical gardening, it is especially useful for plants in pots.",
    "ex1_vi": "Trong việc làm vườn thực tế, nó đặc biệt hữu ích cho cây trồng trong chậu."
  },
  {
    "id": 42,
    "word": "after",
    "type": "preposition/conjunction",
    "cat": "prep",
    "phonetic": "/ˈæftɝ/",
    "meaning": "sau",
    "ex1": "In a well-kept garden, after using it, the watering can should be emptied and kept in a dry place.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, sau khi sử dụng, bình tưới nên được đổ hết nước và cất ở nơi khô ráo."
  },
  {
    "id": 43,
    "word": "using",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈuzɪŋ/",
    "meaning": "việc sử dụng",
    "ex1": "For safe gardening, after using it, the watering can should be emptied and kept in a dry place.",
    "ex1_vi": "Để làm vườn an toàn, sau khi sử dụng, bình tưới nên được đổ hết nước và cất ở nơi khô ráo."
  },
  {
    "id": 44,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "During regular garden work, after using it, the watering can should be emptied and kept in a dry place.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, sau khi sử dụng, bình tưới nên được đổ hết nước và cất ở nơi khô ráo."
  },
  {
    "id": 45,
    "word": "emptied",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɛmptid/",
    "meaning": "được đổ hết",
    "ex1": "When caring for plants, after using it, the watering can should be emptied and kept in a dry place.",
    "ex1_vi": "Khi chăm sóc cây, sau khi sử dụng, bình tưới nên được đổ hết nước và cất ở nơi khô ráo."
  },
  {
    "id": 46,
    "word": "kept",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɛpt/",
    "meaning": "được giữ/cất",
    "ex1": "For everyday garden tasks, after using it, the watering can should be emptied and kept in a dry place.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, sau khi sử dụng, bình tưới nên được đổ hết nước và cất ở nơi khô ráo."
  },
  {
    "id": 47,
    "word": "dry",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/drˈaɪ/",
    "meaning": "khô",
    "ex1": "In practical gardening, after using it, the watering can should be emptied and kept in a dry place.",
    "ex1_vi": "Trong việc làm vườn thực tế, sau khi sử dụng, bình tưới nên được đổ hết nước và cất ở nơi khô ráo."
  },
  {
    "id": 48,
    "word": "place",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪs/",
    "meaning": "nơi",
    "ex1": "In a well-kept garden, after using it, the watering can should be emptied and kept in a dry place.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, sau khi sử dụng, bình tưới nên được đổ hết nước và cất ở nơi khô ráo."
  },
  {
    "id": 49,
    "word": "regular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛɡjʌlɝ/",
    "meaning": "đều đặn",
    "ex1": "For safe gardening, regular watering helps plants grow strong and healthy.",
    "ex1_vi": "Để làm vườn an toàn, tưới nước đều đặn giúp cây phát triển khỏe mạnh."
  },
  {
    "id": 50,
    "word": "grow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡrˈoʊ/",
    "meaning": "phát triển",
    "ex1": "During regular garden work, regular watering helps plants grow strong and healthy.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, tưới nước đều đặn giúp cây phát triển khỏe mạnh."
  },
  {
    "id": 51,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋ/",
    "meaning": "khỏe/chắc",
    "ex1": "When caring for plants, regular watering helps plants grow strong and healthy.",
    "ex1_vi": "Khi chăm sóc cây, tưới nước đều đặn giúp cây phát triển khỏe mạnh."
  },
  {
    "id": 52,
    "word": "healthy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlθi/",
    "meaning": "khỏe mạnh",
    "ex1": "For everyday garden tasks, regular watering helps plants grow strong and healthy.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, tưới nước đều đặn giúp cây phát triển khỏe mạnh."
  },
  {
    "id": 53,
    "word": "however",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/hˌaʊˈɛvɝ/",
    "meaning": "tuy nhiên",
    "ex1": "In practical gardening, however, people should not give plants too much water because wet soil can damage their roots.",
    "ex1_vi": "Trong việc làm vườn thực tế, tuy nhiên, mọi người không nên tưới quá nhiều nước vì đất quá ướt có thể làm hỏng rễ cây."
  },
  {
    "id": 54,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "In a well-kept garden, however, people should not give plants too much water because wet soil can damage their roots.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, tuy nhiên, mọi người không nên tưới quá nhiều nước vì đất quá ướt có thể làm hỏng rễ cây."
  },
  {
    "id": 55,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "For safe gardening, however, people should not give plants too much water because wet soil can damage their roots.",
    "ex1_vi": "Để làm vườn an toàn, tuy nhiên, mọi người không nên tưới quá nhiều nước vì đất quá ướt có thể làm hỏng rễ cây."
  },
  {
    "id": 56,
    "word": "too",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tˈu/",
    "meaning": "quá",
    "ex1": "During regular garden work, however, people should not give plants too much water because wet soil can damage their roots.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, tuy nhiên, mọi người không nên tưới quá nhiều nước vì đất quá ướt có thể làm hỏng rễ cây."
  },
  {
    "id": 57,
    "word": "much",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈʌtʃ/",
    "meaning": "nhiều",
    "ex1": "When caring for plants, however, people should not give plants too much water because wet soil can damage their roots.",
    "ex1_vi": "Khi chăm sóc cây, tuy nhiên, mọi người không nên tưới quá nhiều nước vì đất quá ướt có thể làm hỏng rễ cây."
  },
  {
    "id": 58,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "For everyday garden tasks, however, people should not give plants too much water because wet soil can damage their roots.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, tuy nhiên, mọi người không nên tưới quá nhiều nước vì đất quá ướt có thể làm hỏng rễ cây."
  },
  {
    "id": 59,
    "word": "wet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈɛt/",
    "meaning": "ướt",
    "ex1": "In practical gardening, however, people should not give plants too much water because wet soil can damage their roots.",
    "ex1_vi": "Trong việc làm vườn thực tế, tuy nhiên, mọi người không nên tưới quá nhiều nước vì đất quá ướt có thể làm hỏng rễ cây."
  },
  {
    "id": 60,
    "word": "damage",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈæmʌdʒ/",
    "meaning": "làm hỏng",
    "ex1": "In a well-kept garden, however, people should not give plants too much water because wet soil can damage their roots.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, tuy nhiên, mọi người không nên tưới quá nhiều nước vì đất quá ướt có thể làm hỏng rễ cây."
  },
  {
    "id": 61,
    "word": "roots",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈuts/",
    "meaning": "rễ",
    "ex1": "For safe gardening, however, people should not give plants too much water because wet soil can damage their roots.",
    "ex1_vi": "Để làm vườn an toàn, tuy nhiên, mọi người không nên tưới quá nhiều nước vì đất quá ướt có thể làm hỏng rễ cây."
  },
  {
    "id": 62,
    "word": "garden",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɑrdʌn/",
    "meaning": "vườn",
    "ex1": "During regular garden work, a garden hose is a long, flexible tube used to carry water.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, vòi tưới vườn là một ống dài, mềm dẻo dùng để dẫn nước."
  },
  {
    "id": 63,
    "word": "hose",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊz/",
    "meaning": "vòi tưới",
    "ex1": "When caring for plants, a garden hose is a long, flexible tube used to carry water.",
    "ex1_vi": "Khi chăm sóc cây, vòi tưới vườn là một ống dài, mềm dẻo dùng để dẫn nước."
  },
  {
    "id": 64,
    "word": "flexible",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/flˈɛksʌbʌl/",
    "meaning": "mềm dẻo",
    "ex1": "For everyday garden tasks, a garden hose is a long, flexible tube used to carry water.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, vòi tưới vườn là một ống dài, mềm dẻo dùng để dẫn nước."
  },
  {
    "id": 65,
    "word": "tube",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈub/",
    "meaning": "ống",
    "ex1": "In practical gardening, a garden hose is a long, flexible tube used to carry water.",
    "ex1_vi": "Trong việc làm vườn thực tế, vòi tưới vườn là một ống dài, mềm dẻo dùng để dẫn nước."
  },
  {
    "id": 66,
    "word": "used",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzd/",
    "meaning": "được sử dụng",
    "ex1": "In a well-kept garden, a garden hose is a long, flexible tube used to carry water.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, vòi tưới vườn là một ống dài, mềm dẻo dùng để dẫn nước."
  },
  {
    "id": 67,
    "word": "carry",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈæri/",
    "meaning": "mang; dẫn",
    "ex1": "For safe gardening, a garden hose is a long, flexible tube used to carry water.",
    "ex1_vi": "Để làm vườn an toàn, vòi tưới vườn là một ống dài, mềm dẻo dùng để dẫn nước."
  },
  {
    "id": 68,
    "word": "connected",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌnˈɛktɪd/",
    "meaning": "được nối",
    "ex1": "During regular garden work, it is usually connected to an outdoor tap.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, nó thường được nối với vòi nước ngoài trời."
  },
  {
    "id": 69,
    "word": "outdoor",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈaʊtdˌɔr/",
    "meaning": "ngoài trời",
    "ex1": "When caring for plants, it is usually connected to an outdoor tap.",
    "ex1_vi": "Khi chăm sóc cây, nó thường được nối với vòi nước ngoài trời."
  },
  {
    "id": 70,
    "word": "tap",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈæp/",
    "meaning": "vòi nước",
    "ex1": "For everyday garden tasks, it is usually connected to an outdoor tap.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, nó thường được nối với vòi nước ngoài trời."
  },
  {
    "id": 71,
    "word": "some",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌm/",
    "meaning": "một số",
    "ex1": "In practical gardening, some hoses have a spray nozzle that allows people to control the strength and direction of the water.",
    "ex1_vi": "Trong việc làm vườn thực tế, một số vòi có đầu phun cho phép mọi người kiểm soát lực và hướng của dòng nước."
  },
  {
    "id": 72,
    "word": "hoses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊzɪz/",
    "meaning": "các vòi",
    "ex1": "In a well-kept garden, some hoses have a spray nozzle that allows people to control the strength and direction of the water.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, một số vòi có đầu phun cho phép mọi người kiểm soát lực và hướng của dòng nước."
  },
  {
    "id": 73,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có",
    "ex1": "For safe gardening, some hoses have a spray nozzle that allows people to control the strength and direction of the water.",
    "ex1_vi": "Để làm vườn an toàn, một số vòi có đầu phun cho phép mọi người kiểm soát lực và hướng của dòng nước."
  },
  {
    "id": 74,
    "word": "spray",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sprˈeɪ/",
    "meaning": "phun",
    "ex1": "During regular garden work, some hoses have a spray nozzle that allows people to control the strength and direction of the water.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, một số vòi có đầu phun cho phép mọi người kiểm soát lực và hướng của dòng nước."
  },
  {
    "id": 75,
    "word": "nozzle",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈɑzʌl/",
    "meaning": "đầu phun",
    "ex1": "When caring for plants, some hoses have a spray nozzle that allows people to control the strength and direction of the water.",
    "ex1_vi": "Khi chăm sóc cây, một số vòi có đầu phun cho phép mọi người kiểm soát lực và hướng của dòng nước."
  },
  {
    "id": 76,
    "word": "allows",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌlˈaʊz/",
    "meaning": "cho phép",
    "ex1": "For everyday garden tasks, some hoses have a spray nozzle that allows people to control the strength and direction of the water.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, một số vòi có đầu phun cho phép mọi người kiểm soát lực và hướng của dòng nước."
  },
  {
    "id": 77,
    "word": "control",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntrˈoʊl/",
    "meaning": "kiểm soát",
    "ex1": "In practical gardening, some hoses have a spray nozzle that allows people to control the strength and direction of the water.",
    "ex1_vi": "Trong việc làm vườn thực tế, một số vòi có đầu phun cho phép mọi người kiểm soát lực và hướng của dòng nước."
  },
  {
    "id": 78,
    "word": "strength",
    "type": "noun",
    "cat": "n",
    "phonetic": "/strˈɛŋkθ/",
    "meaning": "lực; độ mạnh",
    "ex1": "In a well-kept garden, some hoses have a spray nozzle that allows people to control the strength and direction of the water.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, một số vòi có đầu phun cho phép mọi người kiểm soát lực và hướng của dòng nước."
  },
  {
    "id": 79,
    "word": "direction",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɝˈɛkʃʌn/",
    "meaning": "hướng",
    "ex1": "For safe gardening, some hoses have a spray nozzle that allows people to control the strength and direction of the water.",
    "ex1_vi": "Để làm vườn an toàn, một số vòi có đầu phun cho phép mọi người kiểm soát lực và hướng của dòng nước."
  },
  {
    "id": 80,
    "word": "lawns",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɔnz/",
    "meaning": "bãi cỏ",
    "ex1": "During regular garden work, gardeners use a hose to water lawns, trees, flowers, and vegetable gardens.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, người làm vườn dùng vòi để tưới bãi cỏ, cây, hoa và vườn rau."
  },
  {
    "id": 81,
    "word": "vegetable",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɛdʒtʌbʌl/",
    "meaning": "thuộc rau; rau",
    "ex1": "When caring for plants, gardeners use a hose to water lawns, trees, flowers, and vegetable gardens.",
    "ex1_vi": "Khi chăm sóc cây, người làm vườn dùng vòi để tưới bãi cỏ, cây, hoa và vườn rau."
  },
  {
    "id": 82,
    "word": "gardens",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɑrdʌnz/",
    "meaning": "các khu vườn",
    "ex1": "For everyday garden tasks, gardeners use a hose to water lawns, trees, flowers, and vegetable gardens.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, người làm vườn dùng vòi để tưới bãi cỏ, cây, hoa và vườn rau."
  },
  {
    "id": 83,
    "word": "faster",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈæstɝ/",
    "meaning": "nhanh hơn",
    "ex1": "In practical gardening, it is faster and more convenient than carrying many buckets of water.",
    "ex1_vi": "Trong việc làm vườn thực tế, nó nhanh và tiện lợi hơn việc mang nhiều xô nước."
  },
  {
    "id": 84,
    "word": "more",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "hơn; nhiều hơn",
    "ex1": "In a well-kept garden, it is faster and more convenient than carrying many buckets of water.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, nó nhanh và tiện lợi hơn việc mang nhiều xô nước."
  },
  {
    "id": 85,
    "word": "convenient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kʌnvˈinjʌnt/",
    "meaning": "tiện lợi",
    "ex1": "For safe gardening, it is faster and more convenient than carrying many buckets of water.",
    "ex1_vi": "Để làm vườn an toàn, nó nhanh và tiện lợi hơn việc mang nhiều xô nước."
  },
  {
    "id": 86,
    "word": "than",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ðˈæn/",
    "meaning": "hơn",
    "ex1": "During regular garden work, it is faster and more convenient than carrying many buckets of water.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, nó nhanh và tiện lợi hơn việc mang nhiều xô nước."
  },
  {
    "id": 87,
    "word": "carrying",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/kˈæriɪŋ/",
    "meaning": "việc mang",
    "ex1": "When caring for plants, it is faster and more convenient than carrying many buckets of water.",
    "ex1_vi": "Khi chăm sóc cây, nó nhanh và tiện lợi hơn việc mang nhiều xô nước."
  },
  {
    "id": 88,
    "word": "buckets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʌkʌts/",
    "meaning": "xô",
    "ex1": "For everyday garden tasks, it is faster and more convenient than carrying many buckets of water.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, nó nhanh và tiện lợi hơn việc mang nhiều xô nước."
  },
  {
    "id": 89,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "In practical gardening, a hose can also be used to clean garden paths, tools, and outdoor furniture.",
    "ex1_vi": "Trong việc làm vườn thực tế, vòi cũng có thể được dùng để làm sạch lối đi trong vườn, dụng cụ và đồ nội thất ngoài trời."
  },
  {
    "id": 90,
    "word": "clean",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈin/",
    "meaning": "làm sạch; sạch",
    "ex1": "In a well-kept garden, a hose can also be used to clean garden paths, tools, and outdoor furniture.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, vòi cũng có thể được dùng để làm sạch lối đi trong vườn, dụng cụ và đồ nội thất ngoài trời."
  },
  {
    "id": 91,
    "word": "paths",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈæðz/",
    "meaning": "lối đi",
    "ex1": "For safe gardening, a hose can also be used to clean garden paths, tools, and outdoor furniture.",
    "ex1_vi": "Để làm vườn an toàn, vòi cũng có thể được dùng để làm sạch lối đi trong vườn, dụng cụ và đồ nội thất ngoài trời."
  },
  {
    "id": 92,
    "word": "tools",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈulz/",
    "meaning": "dụng cụ",
    "ex1": "During regular garden work, a hose can also be used to clean garden paths, tools, and outdoor furniture.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, vòi cũng có thể được dùng để làm sạch lối đi trong vườn, dụng cụ và đồ nội thất ngoài trời."
  },
  {
    "id": 93,
    "word": "furniture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɝnɪtʃɝ/",
    "meaning": "đồ nội thất",
    "ex1": "When caring for plants, a hose can also be used to clean garden paths, tools, and outdoor furniture.",
    "ex1_vi": "Khi chăm sóc cây, vòi cũng có thể được dùng để làm sạch lối đi trong vườn, dụng cụ và đồ nội thất ngoài trời."
  },
  {
    "id": 94,
    "word": "turned",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈɝnd/",
    "meaning": "được xoay/tắt",
    "ex1": "For everyday garden tasks, after use, the tap should be turned off completely.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, sau khi sử dụng, vòi nước nên được khóa hoàn toàn."
  },
  {
    "id": 95,
    "word": "off",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔf/",
    "meaning": "tắt",
    "ex1": "In practical gardening, after use, the tap should be turned off completely.",
    "ex1_vi": "Trong việc làm vườn thực tế, sau khi sử dụng, vòi nước nên được khóa hoàn toàn."
  },
  {
    "id": 96,
    "word": "completely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kʌmplˈitli/",
    "meaning": "hoàn toàn",
    "ex1": "In a well-kept garden, after use, the tap should be turned off completely.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, sau khi sử dụng, vòi nước nên được khóa hoàn toàn."
  },
  {
    "id": 97,
    "word": "rolled",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈoʊld/",
    "meaning": "được cuộn",
    "ex1": "For safe gardening, the hose should be rolled up carefully to prevent it from twisting or breaking.",
    "ex1_vi": "Để làm vườn an toàn, ống nên được cuộn lại cẩn thận để tránh bị xoắn hoặc gãy."
  },
  {
    "id": 98,
    "word": "up",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈʌp/",
    "meaning": "lên; lại",
    "ex1": "During regular garden work, the hose should be rolled up carefully to prevent it from twisting or breaking.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, ống nên được cuộn lại cẩn thận để tránh bị xoắn hoặc gãy."
  },
  {
    "id": 99,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "When caring for plants, the hose should be rolled up carefully to prevent it from twisting or breaking.",
    "ex1_vi": "Khi chăm sóc cây, ống nên được cuộn lại cẩn thận để tránh bị xoắn hoặc gãy."
  },
  {
    "id": 100,
    "word": "prevent",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prɪvˈɛnt/",
    "meaning": "ngăn",
    "ex1": "For everyday garden tasks, the hose should be rolled up carefully to prevent it from twisting or breaking.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, ống nên được cuộn lại cẩn thận để tránh bị xoắn hoặc gãy."
  },
  {
    "id": 101,
    "word": "twisting",
    "type": "verb",
    "cat": "v",
    "phonetic": "/twˈɪstɪŋ/",
    "meaning": "bị xoắn",
    "ex1": "In practical gardening, the hose should be rolled up carefully to prevent it from twisting or breaking.",
    "ex1_vi": "Trong việc làm vườn thực tế, ống nên được cuộn lại cẩn thận để tránh bị xoắn hoặc gãy."
  },
  {
    "id": 102,
    "word": "breaking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/brˈeɪkɪŋ/",
    "meaning": "bị gãy",
    "ex1": "In a well-kept garden, the hose should be rolled up carefully to prevent it from twisting or breaking.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, ống nên được cuộn lại cẩn thận để tránh bị xoắn hoặc gãy."
  },
  {
    "id": 103,
    "word": "keeping",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈipɪŋ/",
    "meaning": "việc giữ",
    "ex1": "For safe gardening, keeping it away from strong sunlight can help it last longer.",
    "ex1_vi": "Để làm vườn an toàn, giữ nó tránh ánh nắng mạnh có thể giúp nó bền lâu hơn."
  },
  {
    "id": 104,
    "word": "away",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌwˈeɪ/",
    "meaning": "xa",
    "ex1": "During regular garden work, keeping it away from strong sunlight can help it last longer.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, giữ nó tránh ánh nắng mạnh có thể giúp nó bền lâu hơn."
  },
  {
    "id": 105,
    "word": "sunlight",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈʌnlˌaɪt/",
    "meaning": "ánh nắng",
    "ex1": "When caring for plants, keeping it away from strong sunlight can help it last longer.",
    "ex1_vi": "Khi chăm sóc cây, giữ nó tránh ánh nắng mạnh có thể giúp nó bền lâu hơn."
  },
  {
    "id": 106,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "For everyday garden tasks, keeping it away from strong sunlight can help it last longer.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, giữ nó tránh ánh nắng mạnh có thể giúp nó bền lâu hơn."
  },
  {
    "id": 107,
    "word": "last",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈæst/",
    "meaning": "kéo dài",
    "ex1": "In practical gardening, keeping it away from strong sunlight can help it last longer.",
    "ex1_vi": "Trong việc làm vườn thực tế, giữ nó tránh ánh nắng mạnh có thể giúp nó bền lâu hơn."
  },
  {
    "id": 108,
    "word": "longer",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/lˈɔŋɡɝ/",
    "meaning": "lâu hơn",
    "ex1": "In a well-kept garden, keeping it away from strong sunlight can help it last longer.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, giữ nó tránh ánh nắng mạnh có thể giúp nó bền lâu hơn."
  },
  {
    "id": 109,
    "word": "shovel",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈʌvʌl/",
    "meaning": "xẻng",
    "ex1": "For safe gardening, a shovel is a strong gardening tool with a wide metal blade and a long handle.",
    "ex1_vi": "Để làm vườn an toàn, xẻng là một dụng cụ làm vườn chắc chắn với lưỡi kim loại rộng và cán dài."
  },
  {
    "id": 110,
    "word": "gardening",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/ɡˈɑrdʌnɪŋ/",
    "meaning": "việc làm vườn",
    "ex1": "During regular garden work, a shovel is a strong gardening tool with a wide metal blade and a long handle.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, xẻng là một dụng cụ làm vườn chắc chắn với lưỡi kim loại rộng và cán dài."
  },
  {
    "id": 111,
    "word": "wide",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈaɪd/",
    "meaning": "rộng",
    "ex1": "When caring for plants, a shovel is a strong gardening tool with a wide metal blade and a long handle.",
    "ex1_vi": "Khi chăm sóc cây, xẻng là một dụng cụ làm vườn chắc chắn với lưỡi kim loại rộng và cán dài."
  },
  {
    "id": 112,
    "word": "blade",
    "type": "noun",
    "cat": "n",
    "phonetic": "/blˈeɪd/",
    "meaning": "lưỡi",
    "ex1": "For everyday garden tasks, a shovel is a strong gardening tool with a wide metal blade and a long handle.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, xẻng là một dụng cụ làm vườn chắc chắn với lưỡi kim loại rộng và cán dài."
  },
  {
    "id": 113,
    "word": "commonly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɑmʌnli/",
    "meaning": "thường",
    "ex1": "In practical gardening, it is commonly made of steel and wood or plastic.",
    "ex1_vi": "Trong việc làm vườn thực tế, nó thường được làm bằng thép và gỗ hoặc nhựa."
  },
  {
    "id": 114,
    "word": "steel",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈil/",
    "meaning": "thép",
    "ex1": "In a well-kept garden, it is commonly made of steel and wood or plastic.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, nó thường được làm bằng thép và gỗ hoặc nhựa."
  },
  {
    "id": 115,
    "word": "wood",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈʊd/",
    "meaning": "gỗ",
    "ex1": "For safe gardening, it is commonly made of steel and wood or plastic.",
    "ex1_vi": "Để làm vườn an toàn, nó thường được làm bằng thép và gỗ hoặc nhựa."
  },
  {
    "id": 116,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "During regular garden work, different shovels have different blade shapes for different gardening jobs.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, những chiếc xẻng khác nhau có hình dạng lưỡi khác nhau cho các công việc làm vườn khác nhau."
  },
  {
    "id": 117,
    "word": "shovels",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈʌvʌlz/",
    "meaning": "những chiếc xẻng",
    "ex1": "When caring for plants, different shovels have different blade shapes for different gardening jobs.",
    "ex1_vi": "Khi chăm sóc cây, những chiếc xẻng khác nhau có hình dạng lưỡi khác nhau cho các công việc làm vườn khác nhau."
  },
  {
    "id": 118,
    "word": "shapes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈeɪps/",
    "meaning": "hình dạng",
    "ex1": "For everyday garden tasks, different shovels have different blade shapes for different gardening jobs.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, những chiếc xẻng khác nhau có hình dạng lưỡi khác nhau cho các công việc làm vườn khác nhau."
  },
  {
    "id": 119,
    "word": "jobs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɑbz/",
    "meaning": "công việc",
    "ex1": "In practical gardening, different shovels have different blade shapes for different gardening jobs.",
    "ex1_vi": "Trong việc làm vườn thực tế, những chiếc xẻng khác nhau có hình dạng lưỡi khác nhau cho các công việc làm vườn khác nhau."
  },
  {
    "id": 120,
    "word": "dig",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈɪɡ/",
    "meaning": "đào",
    "ex1": "In a well-kept garden, people use a shovel to dig holes, move soil, plant trees, and carry sand or compost.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, mọi người dùng xẻng để đào hố, chuyển đất, trồng cây và xúc cát hoặc phân ủ."
  },
  {
    "id": 121,
    "word": "holes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊlz/",
    "meaning": "hố",
    "ex1": "For safe gardening, people use a shovel to dig holes, move soil, plant trees, and carry sand or compost.",
    "ex1_vi": "Để làm vườn an toàn, mọi người dùng xẻng để đào hố, chuyển đất, trồng cây và xúc cát hoặc phân ủ."
  },
  {
    "id": 122,
    "word": "move",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈuv/",
    "meaning": "di chuyển",
    "ex1": "During regular garden work, people use a shovel to dig holes, move soil, plant trees, and carry sand or compost.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, mọi người dùng xẻng để đào hố, chuyển đất, trồng cây và xúc cát hoặc phân ủ."
  },
  {
    "id": 123,
    "word": "plant",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈænt/",
    "meaning": "trồng; cây",
    "ex1": "When caring for plants, people use a shovel to dig holes, move soil, plant trees, and carry sand or compost.",
    "ex1_vi": "Khi chăm sóc cây, mọi người dùng xẻng để đào hố, chuyển đất, trồng cây và xúc cát hoặc phân ủ."
  },
  {
    "id": 124,
    "word": "sand",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈænd/",
    "meaning": "cát",
    "ex1": "For everyday garden tasks, people use a shovel to dig holes, move soil, plant trees, and carry sand or compost.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, mọi người dùng xẻng để đào hố, chuyển đất, trồng cây và xúc cát hoặc phân ủ."
  },
  {
    "id": 125,
    "word": "compost",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑmpoʊst/",
    "meaning": "phân ủ",
    "ex1": "In practical gardening, people use a shovel to dig holes, move soil, plant trees, and carry sand or compost.",
    "ex1_vi": "Trong việc làm vườn thực tế, mọi người dùng xẻng để đào hố, chuyển đất, trồng cây và xúc cát hoặc phân ủ."
  },
  {
    "id": 126,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "In a well-kept garden, it is especially useful when preparing a new garden area.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, nó đặc biệt hữu ích khi chuẩn bị một khu vườn mới."
  },
  {
    "id": 127,
    "word": "preparing",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/pripˈɛrɪŋ/",
    "meaning": "việc chuẩn bị",
    "ex1": "For safe gardening, it is especially useful when preparing a new garden area.",
    "ex1_vi": "Để làm vườn an toàn, nó đặc biệt hữu ích khi chuẩn bị một khu vườn mới."
  },
  {
    "id": 128,
    "word": "new",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈu/",
    "meaning": "mới",
    "ex1": "During regular garden work, it is especially useful when preparing a new garden area.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, nó đặc biệt hữu ích khi chuẩn bị một khu vườn mới."
  },
  {
    "id": 129,
    "word": "area",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛriʌ/",
    "meaning": "khu vực",
    "ex1": "When caring for plants, it is especially useful when preparing a new garden area.",
    "ex1_vi": "Khi chăm sóc cây, nó đặc biệt hữu ích khi chuẩn bị một khu vườn mới."
  },
  {
    "id": 130,
    "word": "sharp",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɑrp/",
    "meaning": "sắc",
    "ex1": "For everyday garden tasks, a sharp and strong shovel makes heavy work easier.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, một chiếc xẻng sắc và chắc giúp công việc nặng trở nên dễ dàng hơn."
  },
  {
    "id": 131,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm cho",
    "ex1": "In practical gardening, a sharp and strong shovel makes heavy work easier.",
    "ex1_vi": "Trong việc làm vườn thực tế, một chiếc xẻng sắc và chắc giúp công việc nặng trở nên dễ dàng hơn."
  },
  {
    "id": 132,
    "word": "heavy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛvi/",
    "meaning": "nặng",
    "ex1": "In a well-kept garden, a sharp and strong shovel makes heavy work easier.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, một chiếc xẻng sắc và chắc giúp công việc nặng trở nên dễ dàng hơn."
  },
  {
    "id": 133,
    "word": "work",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝk/",
    "meaning": "công việc; làm việc",
    "ex1": "For safe gardening, a sharp and strong shovel makes heavy work easier.",
    "ex1_vi": "Để làm vườn an toàn, một chiếc xẻng sắc và chắc giúp công việc nặng trở nên dễ dàng hơn."
  },
  {
    "id": 134,
    "word": "easier",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈiziɝ/",
    "meaning": "dễ hơn",
    "ex1": "During regular garden work, a sharp and strong shovel makes heavy work easier.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, một chiếc xẻng sắc và chắc giúp công việc nặng trở nên dễ dàng hơn."
  },
  {
    "id": 135,
    "word": "wear",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɛr/",
    "meaning": "mang/đeo",
    "ex1": "When caring for plants, gardeners should wear suitable shoes and use both hands when working with a shovel.",
    "ex1_vi": "Khi chăm sóc cây, người làm vườn nên mang giày phù hợp và dùng cả hai tay khi làm việc với xẻng."
  },
  {
    "id": 136,
    "word": "suitable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈutʌbʌl/",
    "meaning": "phù hợp",
    "ex1": "For everyday garden tasks, gardeners should wear suitable shoes and use both hands when working with a shovel.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, người làm vườn nên mang giày phù hợp và dùng cả hai tay khi làm việc với xẻng."
  },
  {
    "id": 137,
    "word": "shoes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈuz/",
    "meaning": "giày",
    "ex1": "In practical gardening, gardeners should wear suitable shoes and use both hands when working with a shovel.",
    "ex1_vi": "Trong việc làm vườn thực tế, người làm vườn nên mang giày phù hợp và dùng cả hai tay khi làm việc với xẻng."
  },
  {
    "id": 138,
    "word": "both",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/bˈoʊθ/",
    "meaning": "cả hai",
    "ex1": "In a well-kept garden, gardeners should wear suitable shoes and use both hands when working with a shovel.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, người làm vườn nên mang giày phù hợp và dùng cả hai tay khi làm việc với xẻng."
  },
  {
    "id": 139,
    "word": "hands",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈændz/",
    "meaning": "bàn tay",
    "ex1": "For safe gardening, gardeners should wear suitable shoes and use both hands when working with a shovel.",
    "ex1_vi": "Để làm vườn an toàn, người làm vườn nên mang giày phù hợp và dùng cả hai tay khi làm việc với xẻng."
  },
  {
    "id": 140,
    "word": "working",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝkɪŋ/",
    "meaning": "làm việc",
    "ex1": "During regular garden work, gardeners should wear suitable shoes and use both hands when working with a shovel.",
    "ex1_vi": "Trong công việc làm vườn thường xuyên, người làm vườn nên mang giày phù hợp và dùng cả hai tay khi làm việc với xẻng."
  },
  {
    "id": 141,
    "word": "cleaned",
    "type": "verb",
    "cat": "v",
    "phonetic": "/klˈind/",
    "meaning": "được làm sạch",
    "ex1": "When caring for plants, after use, the blade should be cleaned to remove wet soil.",
    "ex1_vi": "Khi chăm sóc cây, sau khi dùng, lưỡi xẻng nên được làm sạch để loại bỏ đất ướt."
  },
  {
    "id": 142,
    "word": "remove",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rimˈuv/",
    "meaning": "loại bỏ",
    "ex1": "For everyday garden tasks, after use, the blade should be cleaned to remove wet soil.",
    "ex1_vi": "Đối với các công việc làm vườn hằng ngày, sau khi dùng, lưỡi xẻng nên được làm sạch để loại bỏ đất ướt."
  },
  {
    "id": 143,
    "word": "stored",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈɔrd/",
    "meaning": "được cất",
    "ex1": "In practical gardening, the shovel should be stored in a dry place to prevent rust.",
    "ex1_vi": "Trong việc làm vườn thực tế, xẻng nên được cất ở nơi khô ráo để tránh gỉ."
  },
  {
    "id": 144,
    "word": "rust",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈʌst/",
    "meaning": "gỉ",
    "ex1": "In a well-kept garden, the shovel should be stored in a dry place to prevent rust.",
    "ex1_vi": "Trong một khu vườn được chăm sóc tốt, xẻng nên được cất ở nơi khô ráo để tránh gỉ."
  }
];

const newReadingVocabOrder = [
  "watering",
  "can",
  "useful",
  "tool",
  "taking",
  "care",
  "plants",
  "usually",
  "has",
  "handle",
  "large",
  "container",
  "and",
  "long",
  "spout",
  "cans",
  "often",
  "made",
  "plastic",
  "or",
  "metal",
  "come",
  "many",
  "sizes",
  "gardeners",
  "use",
  "give",
  "water",
  "flowers",
  "vegetables",
  "small",
  "trees",
  "helps",
  "direct",
  "toward",
  "soil",
  "without",
  "damaging",
  "leaves",
  "especially",
  "pots",
  "after",
  "using",
  "should",
  "emptied",
  "kept",
  "dry",
  "place",
  "regular",
  "grow",
  "strong",
  "healthy",
  "however",
  "people",
  "not",
  "too",
  "much",
  "because",
  "wet",
  "damage",
  "roots",
  "garden",
  "hose",
  "flexible",
  "tube",
  "used",
  "carry",
  "connected",
  "outdoor",
  "tap",
  "some",
  "hoses",
  "have",
  "spray",
  "nozzle",
  "allows",
  "control",
  "strength",
  "direction",
  "lawns",
  "vegetable",
  "gardens",
  "faster",
  "more",
  "convenient",
  "than",
  "carrying",
  "buckets",
  "also",
  "clean",
  "paths",
  "tools",
  "furniture",
  "turned",
  "off",
  "completely",
  "rolled",
  "up",
  "carefully",
  "prevent",
  "twisting",
  "breaking",
  "keeping",
  "away",
  "sunlight",
  "help",
  "last",
  "longer",
  "shovel",
  "gardening",
  "wide",
  "blade",
  "commonly",
  "steel",
  "wood",
  "different",
  "shovels",
  "shapes",
  "jobs",
  "dig",
  "holes",
  "move",
  "plant",
  "sand",
  "compost",
  "when",
  "preparing",
  "new",
  "area",
  "sharp",
  "makes",
  "heavy",
  "work",
  "easier",
  "wear",
  "suitable",
  "shoes",
  "both",
  "hands",
  "working",
  "cleaned",
  "remove",
  "stored",
  "rust"
];
