const newEssayData = [
  {
    "text": "Chapter 1. The Watering Can\nA watering can is a useful tool for taking care of plants. It usually has a handle, a large container, and a long spout. Watering cans are often made of plastic or metal and come in many sizes.\n\nGardeners use a watering can to give water to flowers, vegetables, and small trees. The long spout helps direct water toward the soil without damaging the leaves. It is especially useful for plants in pots.\n\nAfter using it, the watering can should be emptied and kept in a dry place. Regular watering helps plants grow strong and healthy. However, people should not give plants too much water because wet soil can damage their roots.",
    "vi": "Chương 1. Bình tưới cây\nBình tưới cây là một dụng cụ hữu ích để chăm sóc cây. Nó thường có tay cầm, một bình chứa lớn và một vòi dài. Bình tưới cây thường được làm bằng nhựa hoặc kim loại và có nhiều kích cỡ.\n\nNgười làm vườn dùng bình tưới để tưới nước cho hoa, rau và cây nhỏ. Vòi dài giúp hướng nước về phía đất mà không làm hỏng lá. Nó đặc biệt hữu ích cho cây trồng trong chậu.\n\nSau khi sử dụng, bình tưới nên được đổ hết nước và cất ở nơi khô ráo. Tưới nước đều đặn giúp cây phát triển khỏe mạnh. Tuy nhiên, mọi người không nên tưới quá nhiều nước vì đất quá ướt có thể làm hỏng rễ cây."
  },
  {
    "text": "Chapter 2. The Garden Hose\nA garden hose is a long, flexible tube used to carry water. It is usually connected to an outdoor tap. Some hoses have a spray nozzle that allows people to control the strength and direction of the water.\n\nGardeners use a hose to water lawns, trees, flowers, and vegetable gardens. It is faster and more convenient than carrying many buckets of water. A hose can also be used to clean garden paths, tools, and outdoor furniture.\n\nAfter use, the tap should be turned off completely. The hose should be rolled up carefully to prevent it from twisting or breaking. Keeping it away from strong sunlight can help it last longer.",
    "vi": "Chương 2. Vòi tưới vườn\nVòi tưới vườn là một ống dài, mềm dẻo dùng để dẫn nước. Nó thường được nối với vòi nước ngoài trời. Một số vòi có đầu phun cho phép mọi người kiểm soát lực và hướng của dòng nước.\n\nNgười làm vườn dùng vòi để tưới bãi cỏ, cây, hoa và vườn rau. Nó nhanh và tiện lợi hơn việc mang nhiều xô nước. Vòi cũng có thể được dùng để làm sạch lối đi trong vườn, dụng cụ và đồ nội thất ngoài trời.\n\nSau khi sử dụng, vòi nước nên được khóa hoàn toàn. Ống nên được cuộn lại cẩn thận để tránh bị xoắn hoặc gãy. Giữ nó tránh ánh nắng mạnh có thể giúp nó bền lâu hơn."
  },
  {
    "text": "Chapter 3. The Shovel\nA shovel is a strong gardening tool with a wide metal blade and a long handle. It is commonly made of steel and wood or plastic. Different shovels have different blade shapes for different gardening jobs.\n\nPeople use a shovel to dig holes, move soil, plant trees, and carry sand or compost. It is especially useful when preparing a new garden area. A sharp and strong shovel makes heavy work easier.\n\nGardeners should wear suitable shoes and use both hands when working with a shovel. After use, the blade should be cleaned to remove wet soil. The shovel should be stored in a dry place to prevent rust.",
    "vi": "Chương 3. Xẻng\nXẻng là một dụng cụ làm vườn chắc chắn với lưỡi kim loại rộng và cán dài. Nó thường được làm bằng thép và gỗ hoặc nhựa. Những chiếc xẻng khác nhau có hình dạng lưỡi khác nhau cho các công việc làm vườn khác nhau.\n\nMọi người dùng xẻng để đào hố, chuyển đất, trồng cây và xúc cát hoặc phân ủ. Nó đặc biệt hữu ích khi chuẩn bị một khu vườn mới. Một chiếc xẻng sắc và chắc giúp công việc nặng trở nên dễ dàng hơn.\n\nNgười làm vườn nên mang giày phù hợp và dùng cả hai tay khi làm việc với xẻng. Sau khi dùng, lưỡi xẻng nên được làm sạch để loại bỏ đất ướt. Xẻng nên được cất ở nơi khô ráo để tránh gỉ."
  }
];
