const newEssayData = [
  {
    "text": "Chapter 7. Gardening Gloves\nGardening gloves protect the hands while people work outside. They are made from materials such as cotton, rubber, leather, or strong fabric. Some gloves are thin, while others are thick and waterproof.\n\nGardeners wear gloves when digging, planting, pulling weeds, or touching thorny plants. Gloves help prevent cuts, scratches, insect bites, and dirty fingernails. They also make it safer to handle soil and garden waste.\n\nThe correct glove size is important because gloves that are too large may make work difficult. After gardening, reusable gloves should be washed and dried. Damaged gloves should be replaced so that the hands remain protected.",
    "vi": "Chương 7. Găng tay làm vườn\nGăng tay làm vườn bảo vệ bàn tay khi mọi người làm việc ngoài trời. Chúng được làm từ các vật liệu như bông, cao su, da hoặc vải chắc. Một số găng mỏng, trong khi những loại khác dày và chống nước.\n\nNgười làm vườn đeo găng khi đào, trồng cây, nhổ cỏ dại hoặc chạm vào cây có gai. Găng giúp ngăn vết cắt, vết xước, côn trùng cắn và móng tay bẩn. Chúng cũng giúp việc xử lý đất và rác vườn an toàn hơn.\n\nKích cỡ găng phù hợp rất quan trọng vì găng quá lớn có thể khiến công việc khó khăn. Sau khi làm vườn, găng tái sử dụng nên được giặt và phơi khô. Găng bị hỏng nên được thay để bàn tay luôn được bảo vệ."
  },
  {
    "text": "Chapter 8. The Wheelbarrow\nA wheelbarrow is a small cart with one or two wheels, two handles, and a large container. It is designed to carry heavy materials around a garden. Most wheelbarrows are made of metal or strong plastic.\n\nGardeners use a wheelbarrow to transport soil, compost, stones, plants, tools, and garden waste. It saves time and reduces the need to carry heavy objects by hand. The wheel helps move the load more easily.\n\nHeavy materials should be placed evenly inside the wheelbarrow to keep it balanced. Gardeners should push it slowly on uneven ground. After use, it should be cleaned and kept under a roof to protect it from rain and rust.",
    "vi": "Chương 8. Xe cút kít\nXe cút kít là một xe đẩy nhỏ có một hoặc hai bánh, hai tay cầm và một thùng chứa lớn. Nó được thiết kế để chở vật liệu nặng quanh vườn. Hầu hết xe cút kít được làm bằng kim loại hoặc nhựa chắc.\n\nNgười làm vườn dùng xe cút kít để vận chuyển đất, phân ủ, đá, cây, dụng cụ và rác vườn. Nó tiết kiệm thời gian và giảm nhu cầu mang vật nặng bằng tay. Bánh xe giúp di chuyển tải dễ dàng hơn.\n\nVật liệu nặng nên được đặt đều bên trong xe cút kít để giữ cân bằng. Người làm vườn nên đẩy nó chậm trên mặt đất không bằng phẳng. Sau khi dùng, nó nên được làm sạch và cất dưới mái che để bảo vệ khỏi mưa và gỉ."
  },
  {
    "text": "Chapter 9. The Garden Hoe\nA garden hoe has a long handle and a flat metal blade. It is a traditional tool used in gardens and farms. The long handle allows gardeners to work while standing instead of bending down.\n\nPeople use a hoe to remove weeds, loosen soil, make planting rows, and mix fertilizer into the ground. It is especially useful in vegetable gardens. Regular hoeing keeps weeds from taking water and nutrients from other plants.\n\nGardeners should hold the hoe firmly and work at a safe distance from other people. The blade should be cleaned after use and sharpened when necessary. A well-maintained hoe makes gardening work faster and easier.",
    "vi": "Chương 9. Cuốc làm vườn\nCuốc làm vườn có cán dài và lưỡi kim loại phẳng. Đây là một dụng cụ truyền thống dùng trong vườn và nông trại. Cán dài cho phép người làm vườn làm việc khi đứng thay vì cúi xuống.\n\nMọi người dùng cuốc để nhổ cỏ, làm tơi đất, tạo hàng trồng và trộn phân bón vào đất. Nó đặc biệt hữu ích trong vườn rau. Việc cuốc thường xuyên ngăn cỏ dại lấy nước và chất dinh dưỡng từ các cây khác.\n\nNgười làm vườn nên cầm cuốc chắc chắn và làm việc ở khoảng cách an toàn với người khác. Lưỡi cuốc nên được làm sạch sau khi dùng và mài sắc khi cần. Một chiếc cuốc được bảo dưỡng tốt giúp công việc làm vườn nhanh và dễ hơn."
  },
  {
    "text": "Chapter 10. The Lawn Mower\nA lawn mower is a machine used to cut grass. It may run on electricity, fuel, or batteries. Lawn mowers have sharp blades underneath and usually have a handle that allows the user to push or guide the machine.\n\nPeople use a lawn mower to keep lawns short, smooth, and tidy. Cutting the grass regularly helps the garden look clean and prevents unwanted plants from growing too tall.\n\nBefore mowing, stones, sticks, and toys should be removed from the lawn. The machine must be turned off before anyone touches the blades. Children should stay away while it is operating. After use, the lawn mower should be cleaned and stored safely.",
    "vi": "Chương 10. Máy cắt cỏ\nMáy cắt cỏ là một chiếc máy dùng để cắt cỏ. Nó có thể chạy bằng điện, nhiên liệu hoặc pin. Máy cắt cỏ có lưỡi sắc bên dưới và thường có tay cầm cho phép người dùng đẩy hoặc điều khiển máy.\n\nMọi người dùng máy cắt cỏ để giữ bãi cỏ ngắn, phẳng và gọn gàng. Cắt cỏ thường xuyên giúp khu vườn trông sạch sẽ và ngăn cây không mong muốn mọc quá cao.\n\nTrước khi cắt cỏ, đá, que và đồ chơi nên được dọn khỏi bãi cỏ. Máy phải được tắt trước khi bất kỳ ai chạm vào lưỡi dao. Trẻ em nên tránh xa khi máy đang hoạt động. Sau khi dùng, máy cắt cỏ nên được làm sạch và cất an toàn."
  }
];
