const newEssayData = [
  {
    "text": "Chapter 7. The Knife\nA knife is a useful kitchen tool with a sharp blade and a handle. Kitchen knives come in different shapes and sizes. Some are used for cutting meat, vegetables, fruit, or bread.\n\nA sharp knife helps people prepare food quickly and easily. It can slice, chop, peel, or cut ingredients into smaller pieces. People should always use it carefully to avoid accidents.\n\nKnives should be washed and dried after use. They should be stored in a knife block, drawer, or safe place. Children should never play with kitchen knives.",
    "vi": "Chương 7. Dao\nDao là một dụng cụ nhà bếp hữu ích có lưỡi sắc và cán cầm. Dao bếp có nhiều hình dạng và kích thước khác nhau. Một số dao được dùng để cắt thịt, rau, trái cây hoặc bánh mì.\n\nMột con dao sắc giúp mọi người chuẩn bị thức ăn nhanh và dễ dàng. Nó có thể thái lát, băm, gọt hoặc cắt nguyên liệu thành những miếng nhỏ hơn. Mọi người luôn nên dùng dao cẩn thận để tránh tai nạn.\n\nDao nên được rửa và lau khô sau khi dùng. Chúng nên được cất trong giá dao, ngăn kéo hoặc nơi an toàn. Trẻ em không bao giờ nên chơi với dao bếp."
  },
  {
    "text": "Chapter 8. The Cutting Board\nA cutting board is a flat surface used for preparing food. It can be made of wood, plastic, bamboo, or other safe materials. Cutting boards also come in different sizes.\n\nPeople place vegetables, fruit, meat, or bread on the board before cutting them. It protects the kitchen counter and provides a stable surface for using a knife.\n\nThe cutting board should be washed after every use. It is better to use separate boards for raw meat and other food. This helps prevent bacteria from spreading and keeps food safe.",
    "vi": "Chương 8. Thớt\nThớt là một bề mặt phẳng dùng để chuẩn bị thức ăn. Nó có thể được làm bằng gỗ, nhựa, tre hoặc các vật liệu an toàn khác. Thớt cũng có nhiều kích thước khác nhau.\n\nMọi người đặt rau, trái cây, thịt hoặc bánh mì lên thớt trước khi cắt. Nó bảo vệ mặt bàn bếp và tạo bề mặt ổn định để sử dụng dao.\n\nThớt nên được rửa sau mỗi lần dùng. Tốt hơn là dùng thớt riêng cho thịt sống và các thức ăn khác. Điều này giúp ngăn vi khuẩn lây lan và giữ thức ăn an toàn."
  },
  {
    "text": "Chapter 9. Plates, Bowls, and Dishes\nPlates, bowls, and dishes are common items used for serving food. Plates are usually flat, while bowls are deep and round. They can be made of ceramic, glass, plastic, or metal.\n\nPeople use plates for rice, meat, vegetables, and snacks. Bowls are useful for soup, noodles, cereal, and other liquid food. Different sizes are used for different meals.\n\nThese items should be washed after every meal. They should be dried and stored carefully in a cupboard. Broken or cracked dishes should not be used because they may be unsafe.",
    "vi": "Chương 9. Đĩa, bát và đồ đựng thức ăn\nĐĩa, bát và các đồ đựng thức ăn là những vật dụng phổ biến dùng để phục vụ thức ăn. Đĩa thường phẳng, trong khi bát sâu và tròn. Chúng có thể được làm bằng gốm, thủy tinh, nhựa hoặc kim loại.\n\nMọi người dùng đĩa cho cơm, thịt, rau và đồ ăn nhẹ. Bát hữu ích cho súp, mì, ngũ cốc và thức ăn dạng lỏng khác. Các kích thước khác nhau được dùng cho những bữa ăn khác nhau.\n\nNhững vật dụng này nên được rửa sau mỗi bữa ăn. Chúng nên được làm khô và cất cẩn thận trong tủ. Đồ đựng bị vỡ hoặc nứt không nên được sử dụng vì chúng có thể không an toàn."
  },
  {
    "text": "Chapter 10. Spoons, Forks, and Chopsticks\nSpoons, forks, and chopsticks are eating utensils found in many kitchens. Spoons have a round end, forks have several pointed parts, and chopsticks are long, thin sticks.\n\nPeople use spoons for soup, rice, or soft food. Forks are useful for picking up meat, vegetables, and pasta. Chopsticks are commonly used for noodles, rice, and many Asian dishes.\n\nThese utensils should be washed after every use. They must be dried before being placed in a drawer or holder. Clean utensils make every meal safer and more enjoyable.",
    "vi": "Chương 10. Thìa, nĩa và đũa\nThìa, nĩa và đũa là những dụng cụ ăn uống có trong nhiều căn bếp. Thìa có đầu tròn, nĩa có vài đầu nhọn và đũa là những que dài, mảnh.\n\nMọi người dùng thìa cho súp, cơm hoặc thức ăn mềm. Nĩa hữu ích để gắp thịt, rau và mì Ý. Đũa thường được dùng cho mì, cơm và nhiều món ăn châu Á.\n\nNhững dụng cụ này nên được rửa sau mỗi lần dùng. Chúng phải được làm khô trước khi đặt vào ngăn kéo hoặc ống đựng. Dụng cụ sạch giúp mỗi bữa ăn an toàn và thú vị hơn."
  }
];
