// ===== environment03 VOCABULARY =====

const lessonVocabularyWords = [
  "saving",
  "energy",
  "future",
  "needed",
  "lights",
  "machines",
  "transport",
  "cooking",
  "and",
  "many",
  "daily",
  "activities",
  "however",
  "producing",
  "often",
  "uses",
  "coal",
  "oil",
  "or",
  "gas",
  "fuels",
  "can",
  "create",
  "pollution",
  "contribute",
  "climate",
  "change",
  "save",
  "turning",
  "off",
  "fans",
  "computers",
  "televisions",
  "when",
  "not",
  "using",
  "bulbs",
  "efficient",
  "appliances",
  "also",
  "helpful",
  "opening",
  "windows",
  "day",
  "reduce",
  "need",
  "air",
  "conditioners",
  "renewable",
  "sun",
  "wind",
  "water",
  "cleaner",
  "planet",
  "governments",
  "businesses",
  "should",
  "invest",
  "sources",
  "everyone",
  "wisely",
  "money",
  "protect",
  "natural",
  "resources",
  "generations",
  "come",
  "protecting",
  "forests",
  "wildlife",
  "home",
  "plants",
  "animals",
  "people",
  "provide",
  "clean",
  "food",
  "medicine",
  "wood",
  "protection",
  "floods",
  "trees",
  "absorb",
  "carbon",
  "dioxide",
  "help",
  "control",
  "earth",
  "temperature",
  "cut",
  "down",
  "loses",
  "shelter",
  "some",
  "may",
  "become",
  "endangered",
  "disappear",
  "forever",
  "deforestation",
  "cause",
  "soil",
  "erosion",
  "hotter",
  "weather",
  "problems",
  "less",
  "paper",
  "recycling",
  "planting",
  "buying",
  "responsible",
  "products",
  "hunt",
  "wild",
  "destroy",
  "habitats",
  "must",
  "protected",
  "areas",
  "stop",
  "illegal",
  "logging",
  "healthy",
  "important",
  "nature",
  "human",
  "life",
  "balance",
  "effects",
  "means",
  "long",
  "term",
  "changes",
  "patterns",
  "especially",
  "burning",
  "release",
  "gases",
  "trap",
  "heat",
  "atmosphere",
  "becomes",
  "warmer",
  "glaciers",
  "melt",
  "sea",
  "levels",
  "rise",
  "more",
  "extreme",
  "places",
  "face",
  "stronger",
  "storms",
  "droughts",
  "wildfires",
  "affects",
  "farming",
  "health",
  "reducing",
  "waste",
  "public",
  "supporting",
  "companies",
  "make",
  "larger",
  "harmful",
  "emissions",
  "working",
  "together",
  "necessary",
  "because",
  "every",
  "country",
  "actions",
  "today",
  "will",
  "shape",
  "building",
  "greener",
  "where",
  "live",
  "well",
  "without",
  "damaging",
  "cities",
  "healthier",
  "green",
  "buildings",
  "schools",
  "teach",
  "children",
  "how",
  "environment",
  "use",
  "safe",
  "materials",
  "last",
  "longer",
  "strong",
  "laws",
  "oceans",
  "person",
  "has",
  "role",
  "choose",
  "reusable",
  "eat",
  "responsibly",
  "support",
  "environmental",
  "projects",
  "requires",
  "cooperation",
  "patience",
  "good",
  "decisions",
  "care",
  "better",
  "present"
];

const newVocabData = [
  {
    "id": 1,
    "word": "saving",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪvɪŋ/",
    "meaning": "tiết kiệm",
    "ex1": "Using energy-saving bulbs and efficient appliances is also helpful.",
    "ex1_vi": "Câu này minh họa từ “saving” với nghĩa “tiết kiệm” trong chủ đề môi trường."
  },
  {
    "id": 2,
    "word": "energy",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛnɚdʒi/",
    "meaning": "năng lượng",
    "ex1": "Careful runners learn about energy during marathon preparation.",
    "ex1_vi": "Những người chạy cẩn thận tìm hiểu về năng lượng trong quá trình chuẩn bị marathon."
  },
  {
    "id": 3,
    "word": "future",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fjutʃɚ/",
    "meaning": "tương lai",
    "ex1": "Healthy forests are important for future generations everywhere.",
    "ex1_vi": "Những khu rừng khỏe mạnh rất quan trọng đối với các thế hệ tương lai ở khắp nơi."
  },
  {
    "id": 4,
    "word": "needed",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈidʌd/",
    "meaning": "cần thiết",
    "ex1": "People noticed something needed during a friendly conversation today.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “cần thiết” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 5,
    "word": "lights",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪts/",
    "meaning": "đèn",
    "ex1": "They may also mention traffic lights at school.",
    "ex1_vi": "Mọi người thường nhắc đến đèn trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 6,
    "word": "machines",
    "type": "noun",
    "cat": "n",
    "phonetic": "/məʃˈiːnz/",
    "meaning": "máy móc",
    "ex1": "On a typical weekday, they must use office equipment correctly and report broken machines immediately.",
    "ex1_vi": "Vào một ngày làm việc điển hình, họ phải sử dụng thiết bị văn phòng đúng cách và báo cáo máy móc bị hỏng ngay lập tức."
  },
  {
    "id": 7,
    "word": "transport",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trænspˈɔrt/",
    "meaning": "giao thông; phương tiện",
    "ex1": "In daily city life, people should use public transport, ride bicycles, or walk short distances.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, mọi người nên sử dụng phương tiện công cộng, đi xe đạp hoặc đi bộ những quãng đường ngắn."
  },
  {
    "id": 8,
    "word": "cooking",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/kˈʊkɪŋ/",
    "meaning": "việc nấu ăn",
    "ex1": "In this street food lesson, each place has special dishes with unique flavors and cooking styles.",
    "ex1_vi": "Trong bài học về đồ ăn đường phố này, mỗi nơi có những món đặc biệt với hương vị và phong cách nấu ăn độc đáo."
  },
  {
    "id": 9,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ənd/",
    "meaning": "và",
    "ex1": "The brain controls movement and helps the body stay balanced.",
    "ex1_vi": "Não kiểm soát vận động và giúp cơ thể giữ thăng bằng."
  },
  {
    "id": 10,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mɛni/",
    "meaning": "nhiều",
    "ex1": "Many animals depend on clean forests for food and shelter.",
    "ex1_vi": "Nhiều loài động vật phụ thuộc vào rừng sạch để có thức ăn và nơi trú ẩn."
  },
  {
    "id": 11,
    "word": "daily",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈeɪli/",
    "meaning": "hằng ngày",
    "ex1": "Clear communication make daily life more convenient every day.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “hằng ngày” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 12,
    "word": "activities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/æktˈɪvətiz/",
    "meaning": "hoạt động",
    "ex1": "Running is one of the best activities for a healthy life.",
    "ex1_vi": "Chạy bộ là một trong những hoạt động tốt nhất cho một cuộc sống khỏe mạnh."
  },
  {
    "id": 13,
    "word": "however",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/hˌaʊˈɛvɝ/",
    "meaning": "tuy nhiên",
    "ex1": "However, spending too much time on screens can make me tired.",
    "ex1_vi": "Tuy nhiên, dành quá nhiều thời gian trước màn hình có thể khiến tôi mệt."
  },
  {
    "id": 14,
    "word": "producing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌdˈusɪŋ/",
    "meaning": "sản xuất",
    "ex1": "However, producing energy often uses coal, oil, or gas.",
    "ex1_vi": "Câu này minh họa từ “producing” với nghĩa “sản xuất” trong chủ đề môi trường."
  },
  {
    "id": 15,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɔfən/",
    "meaning": "thường xuyên",
    "ex1": "Cats are often quieter than many other common pets.",
    "ex1_vi": "Mèo thường yên tĩnh hơn nhiều loài thú cưng phổ biến khác."
  },
  {
    "id": 16,
    "word": "uses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈusʌz/",
    "meaning": "sử dụng",
    "ex1": "When everyone uses energy wisely, we reduce pollution, save money, and protect natural resources for generations to come.",
    "ex1_vi": "Câu này minh họa từ “uses” với nghĩa “sử dụng” trong chủ đề môi trường."
  },
  {
    "id": 17,
    "word": "coal",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈoʊl/",
    "meaning": "than",
    "ex1": "Human activities, especially burning coal, oil, and gas, release gases that trap heat in the atmosphere.",
    "ex1_vi": "Câu này minh họa từ “coal” với nghĩa “than” trong chủ đề môi trường."
  },
  {
    "id": 18,
    "word": "oil",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔɪl/",
    "meaning": "dầu",
    "ex1": "The lesson explains oil clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “oil” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 19,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ɔr/",
    "meaning": "hoặc",
    "ex1": "Some animals live in forests or mountains throughout the year.",
    "ex1_vi": "Một số loài động vật sống trong rừng hoặc vùng núi quanh năm."
  },
  {
    "id": 20,
    "word": "gas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈæs/",
    "meaning": "khí đốt",
    "ex1": "The lesson explains gas clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “gas” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 21,
    "word": "fuels",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fjˈuʌlz/",
    "meaning": "nhiên liệu",
    "ex1": "These fuels can create pollution and contribute to climate change.",
    "ex1_vi": "Câu này minh họa từ “fuels” với nghĩa “nhiên liệu” trong chủ đề môi trường."
  },
  {
    "id": 22,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Regular exercise can make breathing easier and stronger.",
    "ex1_vi": "Tập thể dục đều đặn có thể giúp việc hô hấp dễ dàng và khỏe hơn."
  },
  {
    "id": 23,
    "word": "create",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪt/",
    "meaning": "tạo ra",
    "ex1": "The water is calm, and the mountains create beautiful views.",
    "ex1_vi": "Nước yên ả và những ngọn núi tạo nên cảnh đẹp."
  },
  {
    "id": 24,
    "word": "pollution",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pəlˈuːʃən/",
    "meaning": "ô nhiễm",
    "ex1": "Pollution can damage natural habitats and threaten wild animals.",
    "ex1_vi": "Ô nhiễm có thể làm hại môi trường sống tự nhiên và đe dọa động vật hoang dã."
  },
  {
    "id": 25,
    "word": "contribute",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌntrˈɪbjut/",
    "meaning": "góp phần",
    "ex1": "The lesson explains contribute clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “contribute” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 26,
    "word": "climate",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈaɪmʌt/",
    "meaning": "khí hậu",
    "ex1": "Deforestation can also cause soil erosion, hotter weather, and climate problems.",
    "ex1_vi": "Câu này minh họa từ “climate” với nghĩa “khí hậu” trong chủ đề môi trường."
  },
  {
    "id": 27,
    "word": "change",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈeɪndʒ/",
    "meaning": "thay đổi",
    "ex1": "Good daily choices help people change their bodies safely.",
    "ex1_vi": "Những lựa chọn tốt hằng ngày giúp mọi người thay đổi cơ thể một cách an toàn."
  },
  {
    "id": 28,
    "word": "save",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪv/",
    "meaning": "cứu; bảo vệ",
    "ex1": "Conservation programs can save rare animals from serious danger.",
    "ex1_vi": "Các chương trình bảo tồn có thể cứu các loài động vật quý hiếm khỏi nguy hiểm nghiêm trọng."
  },
  {
    "id": 29,
    "word": "turning",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈɝnɪŋ/",
    "meaning": "biến; chuyển",
    "ex1": "We can save energy by turning off lights, fans, computers, and televisions when they are not needed.",
    "ex1_vi": "Câu này minh họa từ “turning” với nghĩa “biến; chuyển” trong chủ đề môi trường."
  },
  {
    "id": 30,
    "word": "off",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔf/",
    "meaning": "tắt",
    "ex1": "People learn how to use off correctly when talking about environmental action.",
    "ex1_vi": "Mọi người học cách dùng “off” đúng khi nói về hành động bảo vệ môi trường."
  },
  {
    "id": 31,
    "word": "fans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈænz/",
    "meaning": "quạt",
    "ex1": "The lesson explains fans clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “fans” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 32,
    "word": "computers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kəmpjˈuːtəz/",
    "meaning": "máy tính",
    "ex1": "Computers, smartphones, and software help employees organize information, communicate easily, and finish important tasks with greater accuracy and efficiency every single day.",
    "ex1_vi": "Máy tính, điện thoại thông minh và phần mềm giúp nhân viên sắp xếp thông tin, giao tiếp dễ dàng và hoàn thành các nhiệm vụ quan trọng với độ chính xác và hiệu quả cao hơn mỗi ngày."
  },
  {
    "id": 33,
    "word": "televisions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛlʌvˌɪʒʌnz/",
    "meaning": "tivi",
    "ex1": "The lesson explains televisions clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “televisions” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 34,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "Pupils become smaller when bright light reaches the eyes.",
    "ex1_vi": "Đồng tử nhỏ lại khi ánh sáng mạnh chiếu vào mắt."
  },
  {
    "id": 35,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "Earphones should not be used at very high volume.",
    "ex1_vi": "Không nên sử dụng tai nghe ở mức âm lượng quá cao."
  },
  {
    "id": 36,
    "word": "using",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈuzɪŋ/",
    "meaning": "việc sử dụng",
    "ex1": "This body lesson explains using through a clear example.",
    "ex1_vi": "Bài học về cơ thể giải thích việc sử dụng bằng một ví dụ rõ ràng."
  },
  {
    "id": 37,
    "word": "bulbs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʌlbz/",
    "meaning": "bóng đèn",
    "ex1": "The lesson explains bulbs clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “bulbs” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 38,
    "word": "efficient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪfˈɪʃʌnt/",
    "meaning": "hiệu quả; tiết kiệm",
    "ex1": "Students practice the word efficient in a simple sentence about the environment.",
    "ex1_vi": "Học sinh luyện từ “efficient” trong một câu đơn giản về môi trường."
  },
  {
    "id": 39,
    "word": "appliances",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌplˈaɪʌnsʌz/",
    "meaning": "thiết bị",
    "ex1": "The lesson explains appliances clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “appliances” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 40,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "The liver also stores energy for later use.",
    "ex1_vi": "Gan cũng dự trữ năng lượng để sử dụng sau này."
  },
  {
    "id": 41,
    "word": "helpful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlpfəl/",
    "meaning": "hữu ích",
    "ex1": "A helpful body part needs proper care every day.",
    "ex1_vi": "Một bộ phận cơ thể hữu ích cần được chăm sóc đúng cách mỗi ngày."
  },
  {
    "id": 42,
    "word": "opening",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈoʊpʌnɪŋ/",
    "meaning": "mở",
    "ex1": "Opening windows during the day can reduce the need for lights and air conditioners.",
    "ex1_vi": "Câu này minh họa từ “opening” với nghĩa “mở” trong chủ đề môi trường."
  },
  {
    "id": 43,
    "word": "windows",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɪndoʊz/",
    "meaning": "cửa sổ",
    "ex1": "The lesson explains windows clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “windows” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 44,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/deɪ/",
    "meaning": "ngày",
    "ex1": "Responsible pet owners provide fresh food every day.",
    "ex1_vi": "Những người nuôi thú cưng có trách nhiệm cung cấp thức ăn tươi mỗi ngày."
  },
  {
    "id": 45,
    "word": "reduce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹədˈus/",
    "meaning": "giảm",
    "ex1": "Healthy habits can reduce the body in many ways.",
    "ex1_vi": "Những thói quen lành mạnh có thể giảm cơ thể theo nhiều cách."
  },
  {
    "id": 46,
    "word": "need",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nid/",
    "meaning": "cần",
    "ex1": "Wild animals need clean habitats to survive and grow.",
    "ex1_vi": "Động vật hoang dã cần môi trường sống sạch để tồn tại và phát triển."
  },
  {
    "id": 47,
    "word": "air",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛr/",
    "meaning": "không khí",
    "ex1": "Visitors learn about air during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về không khí trong lễ hội Việt Nam này."
  },
  {
    "id": 48,
    "word": "conditioners",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌndˈɪʃʌnɝz/",
    "meaning": "máy điều hòa",
    "ex1": "The lesson explains conditioners clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “conditioners” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 49,
    "word": "renewable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rinˈuʌbʌl/",
    "meaning": "tái tạo được",
    "ex1": "Renewable energy from the sun, wind, and water is cleaner for the planet.",
    "ex1_vi": "Câu này minh họa từ “renewable” với nghĩa “tái tạo được” trong chủ đề môi trường."
  },
  {
    "id": 50,
    "word": "sun",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈʌn/",
    "meaning": "mặt trời; ánh nắng",
    "ex1": "Marathon runners often talk about sun during training sessions.",
    "ex1_vi": "Người chạy marathon thường nói về mặt trời; ánh nắng trong các buổi tập."
  },
  {
    "id": 51,
    "word": "wind",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈaɪnd/",
    "meaning": "gió",
    "ex1": "Strong wind may slow runners during an outdoor marathon event.",
    "ex1_vi": "Gió mạnh có thể làm người chạy chậm lại trong một sự kiện marathon ngoài trời."
  },
  {
    "id": 52,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɚ/",
    "meaning": "nước",
    "ex1": "Doctors often discuss water during regular health checks.",
    "ex1_vi": "Bác sĩ thường trao đổi về nước trong các lần khám sức khỏe định kỳ."
  },
  {
    "id": 53,
    "word": "cleaner",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈklinər/",
    "meaning": "sạch hơn",
    "ex1": "Protecting oceans gives sea animals cleaner waters to enjoy.",
    "ex1_vi": "Bảo vệ đại dương mang lại cho động vật biển những vùng nước sạch hơn để sinh sống."
  },
  {
    "id": 54,
    "word": "planet",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈænʌt/",
    "meaning": "hành tinh",
    "ex1": "Healthy forests and wildlife are important for nature, human life, and the balance of our planet.",
    "ex1_vi": "Câu này minh họa từ “planet” với nghĩa “hành tinh” trong chủ đề môi trường."
  },
  {
    "id": 55,
    "word": "governments",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈʌvɝmʌnts/",
    "meaning": "chính phủ",
    "ex1": "Governments and businesses should invest in these sources.",
    "ex1_vi": "Câu này minh họa từ “governments” với nghĩa “chính phủ” trong chủ đề môi trường."
  },
  {
    "id": 56,
    "word": "businesses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɪznʌsʌz/",
    "meaning": "doanh nghiệp",
    "ex1": "Today, businesses for different reasons in daily life.",
    "ex1_vi": "Mọi người thường nhắc đến doanh nghiệp trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 57,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "People should rest their eyes after using screens.",
    "ex1_vi": "Mọi người nên cho mắt nghỉ sau khi dùng màn hình."
  },
  {
    "id": 58,
    "word": "invest",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnvˈɛst/",
    "meaning": "đầu tư",
    "ex1": "The lesson explains invest clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “invest” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 59,
    "word": "sources",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔrsʌz/",
    "meaning": "nguồn",
    "ex1": "The lesson explains sources clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “sources” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 60,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ɛvriwʌn/",
    "meaning": "mọi người",
    "ex1": "Healthy wildlife habitats create benefits that everyone can enjoy.",
    "ex1_vi": "Môi trường sống lành mạnh của động vật hoang dã mang lại lợi ích cho mọi người."
  },
  {
    "id": 61,
    "word": "wisely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈaɪzli/",
    "meaning": "một cách khôn ngoan",
    "ex1": "Planning helps me use my time wisely and avoid forgetting important things.",
    "ex1_vi": "Lập kế hoạch giúp tôi sử dụng thời gian khôn ngoan và tránh quên những việc quan trọng."
  },
  {
    "id": 62,
    "word": "money",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌni/",
    "meaning": "tiền",
    "ex1": "On busy city streets, public transportation saves time, fuel, and money for many families.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, phương tiện giao thông công cộng tiết kiệm thời gian, nhiên liệu và tiền bạc cho nhiều gia đình."
  },
  {
    "id": 63,
    "word": "protect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹətˈɛkt/",
    "meaning": "bảo vệ",
    "ex1": "Good daily choices help people protect their bodies safely.",
    "ex1_vi": "Những lựa chọn tốt hằng ngày giúp mọi người bảo vệ cơ thể một cách an toàn."
  },
  {
    "id": 64,
    "word": "natural",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nætʃɚəl/",
    "meaning": "tự nhiên",
    "ex1": "Wild animals depend on healthy natural habitats for survival.",
    "ex1_vi": "Động vật hoang dã phụ thuộc vào môi trường sống tự nhiên khỏe mạnh để tồn tại."
  },
  {
    "id": 65,
    "word": "resources",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈisɔrsɪz/",
    "meaning": "tài nguyên",
    "ex1": "The lesson explains resources clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “resources” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 66,
    "word": "generations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒɛnɚeɪʃənz/",
    "meaning": "các thế hệ",
    "ex1": "Healthy habitats provide space and resources for generations.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp không gian và tài nguyên cho các thế hệ."
  },
  {
    "id": 67,
    "word": "come",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌm/",
    "meaning": "đến",
    "ex1": "Thousands of visitors come to pray for health, luck, and happiness.",
    "ex1_vi": "Hàng nghìn du khách đến cầu sức khỏe, may mắn và hạnh phúc."
  },
  {
    "id": 68,
    "word": "protecting",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹətˈɛktɪŋ/",
    "meaning": "đang bảo vệ",
    "ex1": "Wildlife workers are protecting young animals inside the reserve.",
    "ex1_vi": "Nhân viên bảo vệ động vật hoang dã đang bảo vệ những con vật non trong khu bảo tồn."
  },
  {
    "id": 69,
    "word": "forests",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈfɔrɪsts/",
    "meaning": "rừng",
    "ex1": "Children can learn about forests during visits to nature parks.",
    "ex1_vi": "Trẻ em có thể tìm hiểu về rừng khi đến thăm các công viên thiên nhiên."
  },
  {
    "id": 70,
    "word": "wildlife",
    "type": "noun",
    "cat": "n",
    "phonetic": "/waɪldlaɪf/",
    "meaning": "động vật hoang dã",
    "ex1": "People protect wildlife by keeping forests and rivers clean.",
    "ex1_vi": "Con người bảo vệ động vật hoang dã bằng cách giữ rừng và sông sạch."
  },
  {
    "id": 71,
    "word": "home",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hoʊm/",
    "meaning": "nơi sinh sống; nhà",
    "ex1": "A healthy forest can be home to many animal species.",
    "ex1_vi": "Một khu rừng khỏe mạnh có thể là nơi sinh sống của nhiều loài động vật."
  },
  {
    "id": 72,
    "word": "plants",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈænts/",
    "meaning": "cây",
    "ex1": "In everyday life, I also sweep the floor, take out the rubbish, and water the plants.",
    "ex1_vi": "Trong cuộc sống hằng ngày, tôi cũng quét sàn, đổ rác và tưới cây."
  },
  {
    "id": 73,
    "word": "animals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈænɪməlz/",
    "meaning": "động vật",
    "ex1": "Children can learn about animals during visits to nature parks.",
    "ex1_vi": "Trẻ em có thể tìm hiểu về động vật khi đến thăm các công viên thiên nhiên."
  },
  {
    "id": 74,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipəl/",
    "meaning": "mọi người",
    "ex1": "We can understand people better through everyday health examples.",
    "ex1_vi": "Chúng ta có thể hiểu mọi người rõ hơn qua những ví dụ sức khỏe hằng ngày."
  },
  {
    "id": 75,
    "word": "provide",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹəvˈaɪd/",
    "meaning": "cung cấp",
    "ex1": "Good daily choices help people provide their bodies safely.",
    "ex1_vi": "Những lựa chọn tốt hằng ngày giúp mọi người cung cấp cơ thể một cách an toàn."
  },
  {
    "id": 76,
    "word": "clean",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈin/",
    "meaning": "sạch; làm sạch",
    "ex1": "Doctors check whether the tissue remains clean and healthy.",
    "ex1_vi": "Bác sĩ kiểm tra xem mô có còn sạch; làm sạch và khỏe mạnh hay không."
  },
  {
    "id": 77,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thức ăn",
    "ex1": "Healthy routines reduce problems involving food over time.",
    "ex1_vi": "Thói quen lành mạnh giúp giảm các vấn đề liên quan đến thức ăn theo thời gian."
  },
  {
    "id": 78,
    "word": "medicine",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛdʌsʌn/",
    "meaning": "thuốc; dược phẩm",
    "ex1": "They provide clean air, food, medicine, wood, and protection from floods.",
    "ex1_vi": "Câu này minh họa từ “medicine” với nghĩa “thuốc; dược phẩm” trong chủ đề môi trường."
  },
  {
    "id": 79,
    "word": "wood",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈʊd/",
    "meaning": "gỗ",
    "ex1": "We can protect forests by using less paper, recycling, planting trees, and buying responsible wood products.",
    "ex1_vi": "Câu này minh họa từ “wood” với nghĩa “gỗ” trong chủ đề môi trường."
  },
  {
    "id": 80,
    "word": "protection",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɹətˈɛkʃən/",
    "meaning": "sự bảo vệ",
    "ex1": "The body depends on healthy protection for normal function.",
    "ex1_vi": "Cơ thể phụ thuộc vào sự bảo vệ khỏe mạnh để hoạt động bình thường."
  },
  {
    "id": 81,
    "word": "floods",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈʌdz/",
    "meaning": "lũ lụt",
    "ex1": "Some places face stronger storms, floods, droughts, or wildfires.",
    "ex1_vi": "Câu này minh họa từ “floods” với nghĩa “lũ lụt” trong chủ đề môi trường."
  },
  {
    "id": 82,
    "word": "trees",
    "type": "noun",
    "cat": "n",
    "phonetic": "/triz/",
    "meaning": "cây",
    "ex1": "Wildlife guides often observe trees in protected natural areas.",
    "ex1_vi": "Các hướng dẫn viên thiên nhiên thường quan sát cây trong những khu vực tự nhiên được bảo vệ."
  },
  {
    "id": 83,
    "word": "absorb",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌbzˈɔrb/",
    "meaning": "hấp thụ",
    "ex1": "Trees also absorb carbon dioxide and help control the Earth’s temperature.",
    "ex1_vi": "Câu này minh họa từ “absorb” với nghĩa “hấp thụ” trong chủ đề môi trường."
  },
  {
    "id": 84,
    "word": "carbon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑrbʌn/",
    "meaning": "cacbon",
    "ex1": "The lesson explains carbon clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “carbon” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 85,
    "word": "dioxide",
    "type": "noun",
    "cat": "n",
    "phonetic": "/daɪˈɑksˌaɪd/",
    "meaning": "đioxit",
    "ex1": "The lesson explains dioxide clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “dioxide” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 86,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "Healthy habits can help the body in many ways.",
    "ex1_vi": "Những thói quen lành mạnh có thể giúp cơ thể theo nhiều cách."
  },
  {
    "id": 87,
    "word": "control",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kəntɹˈoʊl/",
    "meaning": "kiểm soát",
    "ex1": "Healthy habits can control the body in many ways.",
    "ex1_vi": "Những thói quen lành mạnh có thể kiểm soát cơ thể theo nhiều cách."
  },
  {
    "id": 88,
    "word": "earth",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɝθ/",
    "meaning": "Trái Đất",
    "ex1": "Climate change means long-term changes in the Earth’s temperature and weather patterns.",
    "ex1_vi": "Câu này minh họa từ “earth” với nghĩa “Trái Đất” trong chủ đề môi trường."
  },
  {
    "id": 89,
    "word": "temperature",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛmpɹətʃɚ/",
    "meaning": "nhiệt độ",
    "ex1": "The body depends on healthy temperature for normal function.",
    "ex1_vi": "Cơ thể phụ thuộc vào nhiệt độ khỏe mạnh để hoạt động bình thường."
  },
  {
    "id": 90,
    "word": "cut",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌt/",
    "meaning": "chặt; cắt",
    "ex1": "People sometimes cut trees, but forests need careful protection.",
    "ex1_vi": "Con người đôi khi chặt cây, nhưng rừng cần được bảo vệ cẩn thận."
  },
  {
    "id": 91,
    "word": "down",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/daʊn/",
    "meaning": "xuống",
    "ex1": "People should not cut down too many forest trees.",
    "ex1_vi": "Con người không nên chặt quá nhiều cây rừng."
  },
  {
    "id": 92,
    "word": "loses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈuzʌz/",
    "meaning": "mất",
    "ex1": "When forests are cut down, wildlife loses food and shelter.",
    "ex1_vi": "Câu này minh họa từ “loses” với nghĩa “mất” trong chủ đề môi trường."
  },
  {
    "id": 93,
    "word": "shelter",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɛltɚ/",
    "meaning": "nơi trú ẩn",
    "ex1": "Wild animals need safe shelter during difficult weather conditions.",
    "ex1_vi": "Động vật hoang dã cần nơi trú ẩn an toàn khi điều kiện thời tiết khó khăn."
  },
  {
    "id": 94,
    "word": "some",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sʌm/",
    "meaning": "một số",
    "ex1": "Some monkeys climb tall trees near colorful forest birds.",
    "ex1_vi": "Một số con khỉ trèo lên cây cao gần những con chim rừng đầy màu sắc."
  },
  {
    "id": 95,
    "word": "may",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈeɪ/",
    "meaning": "có thể",
    "ex1": "Too much salt may make the kidneys work harder.",
    "ex1_vi": "Quá nhiều muối có thể khiến thận phải làm việc vất vả hơn."
  },
  {
    "id": 96,
    "word": "become",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌm/",
    "meaning": "trở nên",
    "ex1": "Healthy habits can become the body in many ways.",
    "ex1_vi": "Những thói quen lành mạnh có thể trở nên cơ thể theo nhiều cách."
  },
  {
    "id": 97,
    "word": "endangered",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɛndˈeɪndʒɚd/",
    "meaning": "nguy cấp",
    "ex1": "Many endangered animals need help because their habitats are disappearing quickly.",
    "ex1_vi": "Nhiều loài động vật có nguy cơ tuyệt chủng cần được giúp đỡ vì môi trường sống của chúng đang biến mất nhanh chóng."
  },
  {
    "id": 98,
    "word": "disappear",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˌɪsʌpˈɪr/",
    "meaning": "biến mất",
    "ex1": "Some animals may become endangered or disappear forever.",
    "ex1_vi": "Câu này minh họa từ “disappear” với nghĩa “biến mất” trong chủ đề môi trường."
  },
  {
    "id": 99,
    "word": "forever",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/fɝˈɛvɝ/",
    "meaning": "mãi mãi",
    "ex1": "People learn how to use forever correctly when talking about environmental action.",
    "ex1_vi": "Mọi người học cách dùng “forever” đúng khi nói về hành động bảo vệ môi trường."
  },
  {
    "id": 100,
    "word": "deforestation",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪfˌɔrɪstˈeɪʃʌn/",
    "meaning": "nạn phá rừng",
    "ex1": "The lesson explains deforestation clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “deforestation” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 101,
    "word": "cause",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈɑz/",
    "meaning": "gây ra",
    "ex1": "Hot temperatures may cause dehydration, while rain and strong wind make running more difficult.",
    "ex1_vi": "Nhiệt độ cao có thể gây mất nước, trong khi mưa và gió mạnh khiến việc chạy trở nên khó khăn hơn."
  },
  {
    "id": 102,
    "word": "soil",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔɪl/",
    "meaning": "đất",
    "ex1": "The lesson explains soil clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “soil” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 103,
    "word": "erosion",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪrˈoʊʒʌn/",
    "meaning": "xói mòn",
    "ex1": "The lesson explains erosion clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “erosion” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 104,
    "word": "hotter",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑtɝ/",
    "meaning": "nóng hơn",
    "ex1": "Students practice the word hotter in a simple sentence about the environment.",
    "ex1_vi": "Học sinh luyện từ “hotter” trong một câu đơn giản về môi trường."
  },
  {
    "id": 105,
    "word": "weather",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɛðɝ/",
    "meaning": "thời tiết",
    "ex1": "The weather also affects marathon performance.",
    "ex1_vi": "Thời tiết cũng ảnh hưởng đến thành tích marathon."
  },
  {
    "id": 106,
    "word": "problems",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɹˈɑbləmz/",
    "meaning": "vấn đề",
    "ex1": "Healthy routines reduce problems involving problems over time.",
    "ex1_vi": "Thói quen lành mạnh giúp giảm các vấn đề liên quan đến vấn đề theo thời gian."
  },
  {
    "id": 107,
    "word": "less",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/lˈɛs/",
    "meaning": "ít hơn",
    "ex1": "Cleaning takes less time when I do a little each day, so I try not to be lazy.",
    "ex1_vi": "Việc dọn dẹp tốn ít thời gian hơn khi tôi làm một chút mỗi ngày, vì vậy tôi cố gắng không lười biếng."
  },
  {
    "id": 108,
    "word": "paper",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈeɪpə/",
    "meaning": "giấy",
    "ex1": "Printers make paper copies of documents.",
    "ex1_vi": "Máy in tạo các bản sao tài liệu trên giấy."
  },
  {
    "id": 109,
    "word": "recycling",
    "type": "verb",
    "cat": "v",
    "phonetic": "/risˈaɪkʌlɪŋ/",
    "meaning": "việc tái chế",
    "ex1": "People learn how to use recycling correctly when talking about environmental action.",
    "ex1_vi": "Mọi người học cách dùng “recycling” đúng khi nói về hành động bảo vệ môi trường."
  },
  {
    "id": 110,
    "word": "planting",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈæntɪŋ/",
    "meaning": "việc trồng",
    "ex1": "Planting more trees helps improve air quality in busy neighborhoods too.",
    "ex1_vi": "Trồng thêm cây cũng giúp cải thiện chất lượng không khí ở những khu phố đông đúc."
  },
  {
    "id": 111,
    "word": "buying",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈaɪɪŋ/",
    "meaning": "mua",
    "ex1": "Buying regularly helps people practice useful communication skills daily.",
    "ex1_vi": "Hoạt động mua xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 112,
    "word": "responsible",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rispˈɑnsʌbʌl/",
    "meaning": "có trách nhiệm",
    "ex1": "In daily city life, careful drivers, patient pedestrians, and responsible cyclists make every trip safer.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người lái xe cẩn thận, người đi bộ kiên nhẫn và người đi xe đạp có trách nhiệm làm cho mỗi chuyến đi an toàn hơn."
  },
  {
    "id": 113,
    "word": "products",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑdʌkts/",
    "meaning": "sản phẩm",
    "ex1": "Visitors learn about products during this Vietnamese festival.",
    "ex1_vi": "Du khách tìm hiểu về sản phẩm trong lễ hội Việt Nam này."
  },
  {
    "id": 114,
    "word": "hunt",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈʌnt/",
    "meaning": "săn",
    "ex1": "People must not hunt rare animals in nature reserves.",
    "ex1_vi": "Con người không được săn các loài động vật quý hiếm trong khu bảo tồn thiên nhiên."
  },
  {
    "id": 115,
    "word": "wild",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/waɪld/",
    "meaning": "hoang dã",
    "ex1": "Wild animals need safe forests to live and survive.",
    "ex1_vi": "Động vật hoang dã cần những khu rừng an toàn để sống và tồn tại."
  },
  {
    "id": 116,
    "word": "destroy",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪstrˈɔɪ/",
    "meaning": "phá hủy",
    "ex1": "People should not hunt wild animals or destroy their habitats.",
    "ex1_vi": "Câu này minh họa từ “destroy” với nghĩa “phá hủy” trong chủ đề môi trường."
  },
  {
    "id": 117,
    "word": "habitats",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hæbətæts/",
    "meaning": "môi trường sống",
    "ex1": "Wildlife guides often observe habitats in protected natural areas.",
    "ex1_vi": "Các hướng dẫn viên thiên nhiên thường quan sát môi trường sống trong những khu vực tự nhiên được bảo vệ."
  },
  {
    "id": 118,
    "word": "must",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈʌst/",
    "meaning": "phải",
    "ex1": "Everyone should care about wild animals and must protect nature.",
    "ex1_vi": "Mọi người nên quan tâm đến động vật hoang dã và phải bảo vệ thiên nhiên."
  },
  {
    "id": 119,
    "word": "protected",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹətˈɛktɪd/",
    "meaning": "bảo vệ",
    "ex1": "The lungs are protected by the ribs inside the chest.",
    "ex1_vi": "Phổi được xương sườn bảo vệ bên trong lồng ngực."
  },
  {
    "id": 120,
    "word": "areas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɛriəz/",
    "meaning": "khu vực",
    "ex1": "Healthy habitats provide space and resources for areas.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp không gian và tài nguyên cho khu vực."
  },
  {
    "id": 121,
    "word": "stop",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈɑp/",
    "meaning": "dừng",
    "ex1": "For safe travel, drivers should stop at red lights and follow speed limits carefully.",
    "ex1_vi": "Để đi lại an toàn, người lái xe nên dừng ở đèn đỏ và tuân thủ giới hạn tốc độ cẩn thận."
  },
  {
    "id": 122,
    "word": "illegal",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪlˈiɡʌl/",
    "meaning": "bất hợp pháp",
    "ex1": "Governments must create protected areas and stop illegal logging.",
    "ex1_vi": "Câu này minh họa từ “illegal” với nghĩa “bất hợp pháp” trong chủ đề môi trường."
  },
  {
    "id": 123,
    "word": "logging",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɔɡɪŋ/",
    "meaning": "khai thác gỗ",
    "ex1": "People learn how to use logging correctly when talking about environmental action.",
    "ex1_vi": "Mọi người học cách dùng “logging” đúng khi nói về hành động bảo vệ môi trường."
  },
  {
    "id": 124,
    "word": "healthy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlθi/",
    "meaning": "lành mạnh",
    "ex1": "This organ stays healthy when healthy habits are maintained.",
    "ex1_vi": "Cơ quan này giữ trạng thái khỏe mạnh khi duy trì thói quen lành mạnh."
  },
  {
    "id": 125,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔɹtənt/",
    "meaning": "quan trọng",
    "ex1": "Doctors check whether the tissue remains important and healthy.",
    "ex1_vi": "Bác sĩ kiểm tra xem mô có còn quan trọng và khỏe mạnh hay không."
  },
  {
    "id": 126,
    "word": "nature",
    "type": "noun",
    "cat": "n",
    "phonetic": "/neɪtʃɚ/",
    "meaning": "thiên nhiên",
    "ex1": "Nature provides many animals with food and safe shelter.",
    "ex1_vi": "Thiên nhiên cung cấp thức ăn và nơi trú ẩn an toàn cho nhiều loài động vật."
  },
  {
    "id": 127,
    "word": "human",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hjˈumən/",
    "meaning": "thuộc con người",
    "ex1": "This organ stays human when healthy habits are maintained.",
    "ex1_vi": "Cơ quan này giữ trạng thái con người; thuộc con người khi duy trì thói quen lành mạnh."
  },
  {
    "id": 128,
    "word": "life",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪf/",
    "meaning": "cuộc sống",
    "ex1": "When we care for Earth, we create a better life for present and future generations.",
    "ex1_vi": "Câu này minh họa từ “life” với nghĩa “cuộc sống” trong chủ đề môi trường."
  },
  {
    "id": 129,
    "word": "balance",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈaləns/",
    "meaning": "sự cân bằng",
    "ex1": "Workers should balance work and personal life to stay healthy and relaxed.",
    "ex1_vi": "Nhân viên nên cân bằng công việc và cuộc sống cá nhân để luôn khỏe mạnh và thư giãn."
  },
  {
    "id": 130,
    "word": "effects",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪfˈɛkts/",
    "meaning": "các tác động",
    "ex1": "The lesson explains effects clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “effects” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 131,
    "word": "means",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈinz/",
    "meaning": "có nghĩa là",
    "ex1": "It means caring for ourselves in sensible ways.",
    "ex1_vi": "Nó có nghĩa là chăm sóc bản thân theo những cách hợp lý."
  },
  {
    "id": 132,
    "word": "long",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɔŋ/",
    "meaning": "dài",
    "ex1": "Doctors check whether the tissue remains long and healthy.",
    "ex1_vi": "Bác sĩ kiểm tra xem mô có còn dài và khỏe mạnh hay không."
  },
  {
    "id": 133,
    "word": "term",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɝm/",
    "meaning": "dài hạn",
    "ex1": "The lesson explains term clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “term” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 134,
    "word": "changes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈeɪndʒʌz/",
    "meaning": "những thay đổi",
    "ex1": "Governments and companies must make larger changes to reduce harmful emissions.",
    "ex1_vi": "Câu này minh họa từ “changes” với nghĩa “những thay đổi” trong chủ đề môi trường."
  },
  {
    "id": 135,
    "word": "patterns",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈætɝnz/",
    "meaning": "kiểu; mô hình",
    "ex1": "The lesson explains patterns clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “patterns” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 136,
    "word": "especially",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌspˈɛʃli/",
    "meaning": "đặc biệt",
    "ex1": "For road safety, city traffic is busy every day, especially in the morning and evening.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, giao thông thành phố đông đúc mỗi ngày, đặc biệt vào buổi sáng và buổi tối."
  },
  {
    "id": 137,
    "word": "burning",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɝnɪŋ/",
    "meaning": "đốt",
    "ex1": "People learn how to use burning correctly when talking about environmental action.",
    "ex1_vi": "Mọi người học cách dùng “burning” đúng khi nói về hành động bảo vệ môi trường."
  },
  {
    "id": 138,
    "word": "release",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rilˈis/",
    "meaning": "thải ra",
    "ex1": "The lesson explains release clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “release” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 139,
    "word": "gases",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈæsʌz/",
    "meaning": "các loại khí",
    "ex1": "The lesson explains gases clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “gases” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 140,
    "word": "trap",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈæp/",
    "meaning": "giữ lại",
    "ex1": "The lesson explains trap clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “trap” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 141,
    "word": "heat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈit/",
    "meaning": "nhiệt; nóng",
    "ex1": "The body depends on healthy heat for normal function.",
    "ex1_vi": "Cơ thể phụ thuộc vào nhiệt; nóng khỏe mạnh để hoạt động bình thường."
  },
  {
    "id": 142,
    "word": "atmosphere",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈætməsfˌɪr/",
    "meaning": "khí quyển",
    "ex1": "The London Marathon is famous for its exciting atmosphere and charity activities.",
    "ex1_vi": "London Marathon nổi tiếng với bầu không khí sôi động và các hoạt động từ thiện."
  },
  {
    "id": 143,
    "word": "becomes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌmz/",
    "meaning": "trở nên",
    "ex1": "The body becomes naturally when its organs remain healthy.",
    "ex1_vi": "Cơ thể trở nên tự nhiên khi các cơ quan vẫn khỏe mạnh."
  },
  {
    "id": 144,
    "word": "warmer",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈwɔrmər/",
    "meaning": "ấm hơn",
    "ex1": "Migrating birds travel long distances to find warmer places.",
    "ex1_vi": "Chim di cư đi quãng đường dài để tìm những nơi ấm hơn."
  },
  {
    "id": 145,
    "word": "glaciers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡlˈeɪʃɝz/",
    "meaning": "sông băng",
    "ex1": "As the planet becomes warmer, glaciers melt, sea levels rise, and weather becomes more extreme.",
    "ex1_vi": "Câu này minh họa từ “glaciers” với nghĩa “sông băng” trong chủ đề môi trường."
  },
  {
    "id": 146,
    "word": "melt",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛlt/",
    "meaning": "tan chảy",
    "ex1": "The lesson explains melt clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “melt” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 147,
    "word": "sea",
    "type": "noun",
    "cat": "n",
    "phonetic": "/si/",
    "meaning": "biển",
    "ex1": "Visitors often learn about sea during guided animal activities.",
    "ex1_vi": "Khách tham quan thường tìm hiểu về biển trong các hoạt động tìm hiểu động vật có hướng dẫn."
  },
  {
    "id": 148,
    "word": "levels",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɛvʌlz/",
    "meaning": "mức",
    "ex1": "The lesson explains levels clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “levels” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 149,
    "word": "rise",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪz/",
    "meaning": "dâng; tăng",
    "ex1": "The lesson explains rise clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “rise” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 150,
    "word": "more",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mɔr/",
    "meaning": "nhiều hơn",
    "ex1": "More animals can survive when people protect natural habitats.",
    "ex1_vi": "Nhiều động vật hơn có thể sống sót khi con người bảo vệ môi trường sống tự nhiên."
  },
  {
    "id": 151,
    "word": "extreme",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɛkstrˈim/",
    "meaning": "cực đoan",
    "ex1": "Students practice the word extreme in a simple sentence about the environment.",
    "ex1_vi": "Học sinh luyện từ “extreme” trong một câu đơn giản về môi trường."
  },
  {
    "id": 152,
    "word": "places",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪsəz/",
    "meaning": "nơi; đặt",
    "ex1": "This organ places continuously to support normal body function.",
    "ex1_vi": "Cơ quan này nơi; đặt liên tục để hỗ trợ chức năng bình thường của cơ thể."
  },
  {
    "id": 153,
    "word": "face",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈeɪs/",
    "meaning": "khuôn mặt",
    "ex1": "Healthy habits can protect face and improve overall wellbeing.",
    "ex1_vi": "Thói quen lành mạnh có thể bảo vệ khuôn mặt và cải thiện sức khỏe tổng thể."
  },
  {
    "id": 154,
    "word": "stronger",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/stɹˈɔŋɡɚ/",
    "meaning": "khỏe hơn",
    "ex1": "Regular training helps runners become stronger in body and mind.",
    "ex1_vi": "Tập luyện thường xuyên giúp người chạy trở nên mạnh mẽ hơn về thể chất và tinh thần."
  },
  {
    "id": 155,
    "word": "storms",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈɔrmz/",
    "meaning": "bão",
    "ex1": "The lesson explains storms clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “storms” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 156,
    "word": "droughts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈaʊts/",
    "meaning": "hạn hán",
    "ex1": "The lesson explains droughts clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “droughts” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 157,
    "word": "wildfires",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈaɪldfˌaɪɝz/",
    "meaning": "cháy rừng",
    "ex1": "The lesson explains wildfires clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “wildfires” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 158,
    "word": "affects",
    "type": "verb",
    "cat": "v",
    "phonetic": "/əfˈɛkts/",
    "meaning": "ảnh hưởng",
    "ex1": "Climate change also affects farming, wildlife, water, and human health.",
    "ex1_vi": "Câu này minh họa từ “affects” với nghĩa “ảnh hưởng” trong chủ đề môi trường."
  },
  {
    "id": 159,
    "word": "farming",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɑrmɪŋ/",
    "meaning": "nông nghiệp",
    "ex1": "The festival celebrates farming life, strength, and teamwork.",
    "ex1_vi": "Lễ hội tôn vinh đời sống nông nghiệp, sức mạnh và tinh thần đồng đội."
  },
  {
    "id": 160,
    "word": "health",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛlθ/",
    "meaning": "sức khỏe",
    "ex1": "Good sleep and balanced meals can improve health.",
    "ex1_vi": "Ngủ đủ và ăn uống cân bằng có thể cải thiện sức khỏe."
  },
  {
    "id": 161,
    "word": "reducing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rʌdˈusɪŋ/",
    "meaning": "giảm",
    "ex1": "People can help by saving energy, reducing waste, using public transport, and supporting renewable energy.",
    "ex1_vi": "Câu này minh họa từ “reducing” với nghĩa “giảm” trong chủ đề môi trường."
  },
  {
    "id": 162,
    "word": "waste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪst/",
    "meaning": "chất thải",
    "ex1": "The body depends on healthy waste for normal function.",
    "ex1_vi": "Cơ thể phụ thuộc vào chất thải khỏe mạnh để hoạt động bình thường."
  },
  {
    "id": 163,
    "word": "public",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈʌblɪk/",
    "meaning": "công cộng",
    "ex1": "People should use public transport, ride bicycles, or walk short distances.",
    "ex1_vi": "Mọi người nên sử dụng phương tiện công cộng, đi xe đạp hoặc đi bộ những quãng đường ngắn."
  },
  {
    "id": 164,
    "word": "supporting",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sʌpˈɔrtɪŋ/",
    "meaning": "ủng hộ",
    "ex1": "People learn how to use supporting correctly when talking about environmental action.",
    "ex1_vi": "Mọi người học cách dùng “supporting” đúng khi nói về hành động bảo vệ môi trường."
  },
  {
    "id": 165,
    "word": "companies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌmpʌnˌiz/",
    "meaning": "các công ty",
    "ex1": "The lesson explains companies clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “companies” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 166,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/meɪk/",
    "meaning": "làm cho",
    "ex1": "Friendly pets make many family homes happier and warmer.",
    "ex1_vi": "Những thú cưng thân thiện làm cho nhiều ngôi nhà gia đình vui vẻ và ấm áp hơn."
  },
  {
    "id": 167,
    "word": "larger",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lɑrdʒɚ/",
    "meaning": "lớn hơn",
    "ex1": "Larger pets usually need more space inside family homes.",
    "ex1_vi": "Thú cưng lớn hơn thường cần nhiều không gian hơn trong nhà."
  },
  {
    "id": 168,
    "word": "harmful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑɹmfəl/",
    "meaning": "có hại",
    "ex1": "A harmful body part needs proper care every day.",
    "ex1_vi": "Một bộ phận cơ thể có hại cần được chăm sóc đúng cách mỗi ngày."
  },
  {
    "id": 169,
    "word": "emissions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪmˈɪʃʌnz/",
    "meaning": "khí thải",
    "ex1": "The lesson explains emissions clearly in a discussion about protecting nature.",
    "ex1_vi": "Bài học giải thích rõ “emissions” trong một cuộc thảo luận về bảo vệ thiên nhiên."
  },
  {
    "id": 170,
    "word": "working",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɜːkɪŋ/",
    "meaning": "làm việc",
    "ex1": "People are working together to protect endangered animal species.",
    "ex1_vi": "Mọi người đang cùng nhau làm việc để bảo vệ các loài động vật có nguy cơ tuyệt chủng."
  },
  {
    "id": 171,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/təɡˈɛðɚ/",
    "meaning": "cùng nhau",
    "ex1": "Healthy people together follow simple routines for body care.",
    "ex1_vi": "Người khỏe mạnh cùng nhau duy trì những thói quen đơn giản để chăm sóc cơ thể."
  },
  {
    "id": 172,
    "word": "necessary",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈɛsʌsˌɛri/",
    "meaning": "cần thiết",
    "ex1": "Working together is necessary because climate change affects every country.",
    "ex1_vi": "Câu này minh họa từ “necessary” với nghĩa “cần thiết” trong chủ đề môi trường."
  },
  {
    "id": 173,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkɔz/",
    "meaning": "bởi vì",
    "ex1": "Animals need forests because these places provide food and shelter.",
    "ex1_vi": "Động vật cần rừng bởi vì những nơi này cung cấp thức ăn và nơi trú ẩn."
  },
  {
    "id": 174,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ɛvɚi/",
    "meaning": "mỗi",
    "ex1": "Pets need fresh food and clean water every day.",
    "ex1_vi": "Thú cưng cần thức ăn tươi và nước sạch mỗi ngày."
  },
  {
    "id": 175,
    "word": "country",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌntri/",
    "meaning": "quốc gia",
    "ex1": "Giong Festival teaches courage, unity, and love for the country.",
    "ex1_vi": "Lễ hội Gióng dạy về lòng dũng cảm, sự đoàn kết và tình yêu đất nước."
  },
  {
    "id": 176,
    "word": "actions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈækʃʌnz/",
    "meaning": "hành động",
    "ex1": "For safe travel, small daily actions can reduce pollution and protect nature.",
    "ex1_vi": "Để đi lại an toàn, những hành động nhỏ hằng ngày có thể giảm ô nhiễm và bảo vệ thiên nhiên."
  },
  {
    "id": 177,
    "word": "today",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tədˈeɪ/",
    "meaning": "hôm nay",
    "ex1": "Today, marathons are organized in many countries and welcome runners of different ages and abilities from around the world.",
    "ex1_vi": "Ngày nay, các cuộc marathon được tổ chức ở nhiều quốc gia và chào đón những người chạy ở nhiều độ tuổi và khả năng khác nhau từ khắp nơi trên thế giới."
  },
  {
    "id": 178,
    "word": "will",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/wɪl/",
    "meaning": "sẽ",
    "ex1": "Healthy forests will support wildlife for many future generations.",
    "ex1_vi": "Những khu rừng khỏe mạnh sẽ hỗ trợ động vật hoang dã trong nhiều năm."
  },
  {
    "id": 179,
    "word": "shape",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈeɪp/",
    "meaning": "định hình",
    "ex1": "Our actions today will shape the future of the planet for everyone.",
    "ex1_vi": "Câu này minh họa từ “shape” với nghĩa “định hình” trong chủ đề môi trường."
  },
  {
    "id": 180,
    "word": "building",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈbɪldɪŋ/",
    "meaning": "đang xây",
    "ex1": "Several birds are building a new nest in a tall tree today.",
    "ex1_vi": "Một vài con chim đang xây một chiếc tổ mới trên một cây cao hôm nay."
  },
  {
    "id": 181,
    "word": "greener",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈinɝ/",
    "meaning": "xanh hơn",
    "ex1": "A greener future is a future where people live well without damaging nature.",
    "ex1_vi": "Câu này minh họa từ “greener” với nghĩa “xanh hơn” trong chủ đề môi trường."
  },
  {
    "id": 182,
    "word": "where",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈɛɹ/",
    "meaning": "nơi mà; ở đâu",
    "ex1": "The inner ear is where important balance signals begin.",
    "ex1_vi": "Tai trong là nơi các tín hiệu thăng bằng quan trọng bắt đầu."
  },
  {
    "id": 183,
    "word": "live",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈaɪv/",
    "meaning": "sống",
    "ex1": "Healthy habits can live the body in many ways.",
    "ex1_vi": "Những thói quen lành mạnh có thể sống cơ thể theo nhiều cách."
  },
  {
    "id": 184,
    "word": "well",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wɛl/",
    "meaning": "tốt",
    "ex1": "The rescued pandas are growing well in their new habitat.",
    "ex1_vi": "Những con gấu trúc được cứu hộ đang phát triển tốt trong môi trường sống mới."
  },
  {
    "id": 185,
    "word": "without",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/wɪθˈaʊt/",
    "meaning": "không có; mà không",
    "ex1": "People listen without interrupting during respectful conversations with friends.",
    "ex1_vi": "Du khách đi băng qua đường sau khi nhận được chỉ dẫn rõ ràng."
  },
  {
    "id": 186,
    "word": "damaging",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈæmɪdʒɪŋ/",
    "meaning": "làm tổn hại",
    "ex1": "People learn how to use damaging correctly when talking about environmental action.",
    "ex1_vi": "Mọi người học cách dùng “damaging” đúng khi nói về hành động bảo vệ môi trường."
  },
  {
    "id": 187,
    "word": "cities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪtiz/",
    "meaning": "các thành phố",
    "ex1": "Many cities organize famous marathon races every year.",
    "ex1_vi": "Nhiều thành phố tổ chức các cuộc đua marathon nổi tiếng hằng năm."
  },
  {
    "id": 188,
    "word": "healthier",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hɛlθiɚ/",
    "meaning": "khỏe mạnh hơn",
    "ex1": "Clean habitats help nature become healthier for future generations.",
    "ex1_vi": "Môi trường sống sạch giúp thiên nhiên trở nên khỏe mạnh hơn cho các thế hệ tương lai."
  },
  {
    "id": 189,
    "word": "green",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈin/",
    "meaning": "xanh",
    "ex1": "Green rice fields create beautiful views along rural marathon routes.",
    "ex1_vi": "Những cánh đồng lúa xanh tạo nên cảnh đẹp dọc các cung đường marathon nông thôn."
  },
  {
    "id": 190,
    "word": "buildings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɪldɪŋz/",
    "meaning": "các tòa nhà",
    "ex1": "Today, large buildings as landmarks in daily life.",
    "ex1_vi": "Mọi người thường nhắc đến tòa nhà trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 191,
    "word": "schools",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈulz/",
    "meaning": "trường học",
    "ex1": "Visitors often need help finding schools at school.",
    "ex1_vi": "Mọi người thường nhắc đến trường học trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 192,
    "word": "teach",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈitʃ/",
    "meaning": "dạy",
    "ex1": "Schools can teach children how to protect the environment.",
    "ex1_vi": "Câu này minh họa từ “teach” với nghĩa “dạy” trong chủ đề môi trường."
  },
  {
    "id": 193,
    "word": "children",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃɪldrən/",
    "meaning": "trẻ em",
    "ex1": "Wildlife guides often observe children in protected natural areas.",
    "ex1_vi": "Các hướng dẫn viên thiên nhiên thường quan sát trẻ em trong những khu vực tự nhiên được bảo vệ."
  },
  {
    "id": 194,
    "word": "how",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/hˈaʊ/",
    "meaning": "như thế nào",
    "ex1": "People learn how to use how correctly when talking about environmental action.",
    "ex1_vi": "Mọi người học cách dùng “how” đúng khi nói về hành động bảo vệ môi trường."
  },
  {
    "id": 195,
    "word": "environment",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪnvaɪrənmənt/",
    "meaning": "môi trường",
    "ex1": "A clean environment helps wild animals live more safely.",
    "ex1_vi": "Môi trường sạch giúp động vật hoang dã sống an toàn hơn."
  },
  {
    "id": 196,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "Doctors recommend routines that use healthy body functions naturally.",
    "ex1_vi": "Bác sĩ khuyến nghị những thói quen giúp sử dụng các chức năng cơ thể một cách tự nhiên."
  },
  {
    "id": 197,
    "word": "safe",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/seɪf/",
    "meaning": "an toàn",
    "ex1": "Forests provide safe places for many animal species.",
    "ex1_vi": "Rừng cung cấp những nơi an toàn cho nhiều loài động vật."
  },
  {
    "id": 198,
    "word": "materials",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mətˈiəɹɪəlz/",
    "meaning": "vật liệu",
    "ex1": "Careful runners learn about materials during marathon preparation.",
    "ex1_vi": "Những người chạy cẩn thận tìm hiểu về vật liệu; chất liệu trong quá trình chuẩn bị marathon."
  },
  {
    "id": 199,
    "word": "last",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/læst/",
    "meaning": "trước; vừa qua",
    "ex1": "Several young pandas moved to safer areas last year.",
    "ex1_vi": "Một số gấu trúc non đã chuyển đến khu vực an toàn hơn vào năm ngoái."
  },
  {
    "id": 200,
    "word": "longer",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/lɔŋɡɚ/",
    "meaning": "lâu hơn",
    "ex1": "Well-cared-for pets often live longer and stay healthier.",
    "ex1_vi": "Những thú cưng được chăm sóc tốt thường sống lâu hơn và khỏe mạnh hơn."
  },
  {
    "id": 201,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/stɹˈɔŋ/",
    "meaning": "khỏe; mạnh",
    "ex1": "A strong body part needs proper care every day.",
    "ex1_vi": "Một bộ phận cơ thể khỏe; mạnh cần được chăm sóc đúng cách mỗi ngày."
  },
  {
    "id": 202,
    "word": "laws",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɔz/",
    "meaning": "luật",
    "ex1": "Governments can make strong laws to control pollution and protect forests, oceans, and wildlife.",
    "ex1_vi": "Câu này minh họa từ “laws” với nghĩa “luật” trong chủ đề môi trường."
  },
  {
    "id": 203,
    "word": "oceans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈoʊʃənz/",
    "meaning": "đại dương",
    "ex1": "Healthy habitats provide space and resources for oceans.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp không gian và tài nguyên cho đại dương."
  },
  {
    "id": 204,
    "word": "person",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɝsʌn/",
    "meaning": "người",
    "ex1": "During a normal workday, every office job is important because each person has different responsibilities.",
    "ex1_vi": "Trong một ngày làm việc bình thường, mỗi công việc văn phòng đều quan trọng vì mỗi người có những trách nhiệm khác nhau."
  },
  {
    "id": 205,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "Healthy habits can has the body in many ways.",
    "ex1_vi": "Những thói quen lành mạnh có thể có cơ thể theo nhiều cách."
  },
  {
    "id": 206,
    "word": "role",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈoʊl/",
    "meaning": "vai trò",
    "ex1": "Every person has an important role.",
    "ex1_vi": "Câu này minh họa từ “role” với nghĩa “vai trò” trong chủ đề môi trường."
  },
  {
    "id": 207,
    "word": "choose",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈuz/",
    "meaning": "chọn",
    "ex1": "Customers communicate with waiters to choose food every day.",
    "ex1_vi": "Hoạt động chọn xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 208,
    "word": "reusable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/riˈuzʌbʌl/",
    "meaning": "có thể tái sử dụng",
    "ex1": "We can choose reusable products, save energy, eat responsibly, and support environmental projects.",
    "ex1_vi": "Câu này minh họa từ “reusable” với nghĩa “có thể tái sử dụng” trong chủ đề môi trường."
  },
  {
    "id": 209,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "Doctors recommend routines that eat healthy body functions naturally.",
    "ex1_vi": "Bác sĩ khuyến nghị những thói quen giúp ăn các chức năng cơ thể một cách tự nhiên."
  },
  {
    "id": 210,
    "word": "responsibly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/rɪspˈɑnsʌbli/",
    "meaning": "có trách nhiệm",
    "ex1": "Teachers and colleagues appreciate people who communicate respectfully and responsibly every day.",
    "ex1_vi": "Mọi người giao tiếp có trách nhiệm trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 211,
    "word": "support",
    "type": "verb",
    "cat": "v",
    "phonetic": "/səpˈɔɹt/",
    "meaning": "hỗ trợ",
    "ex1": "Good daily choices help people support their bodies safely.",
    "ex1_vi": "Những lựa chọn tốt hằng ngày giúp mọi người hỗ trợ cơ thể một cách an toàn."
  },
  {
    "id": 212,
    "word": "environmental",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪnvˌaɪrʌnmˈɛntʌl/",
    "meaning": "thuộc môi trường",
    "ex1": "Students practice the word environmental in a simple sentence about the environment.",
    "ex1_vi": "Học sinh luyện từ “environmental” trong một câu đơn giản về môi trường."
  },
  {
    "id": 213,
    "word": "projects",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑdʒɛkts/",
    "meaning": "dự án",
    "ex1": "We discussed projects during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến dự án trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 214,
    "word": "requires",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪkwˈaɪɚz/",
    "meaning": "đòi hỏi",
    "ex1": "Running a marathon requires careful preparation.",
    "ex1_vi": "Chạy marathon đòi hỏi sự chuẩn bị cẩn thận."
  },
  {
    "id": 215,
    "word": "cooperation",
    "type": "noun",
    "cat": "n",
    "phonetic": "/koʊˌɑpɝˈeɪʃʌn/",
    "meaning": "sự hợp tác",
    "ex1": "We discussed cooperation during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến sự hợp tác trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 216,
    "word": "patience",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈeɪʃəns/",
    "meaning": "sự kiên nhẫn",
    "ex1": "Marathon training teaches patience during long periods of practice.",
    "ex1_vi": "Tập luyện marathon dạy sự kiên nhẫn trong những giai đoạn luyện tập dài."
  },
  {
    "id": 217,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "This organ stays good when healthy habits are maintained.",
    "ex1_vi": "Cơ quan này giữ trạng thái tốt khi duy trì thói quen lành mạnh."
  },
  {
    "id": 218,
    "word": "decisions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪsˈɪʒənz/",
    "meaning": "quyết định",
    "ex1": "During busy working hours, managers listen to different opinions before making decisions.",
    "ex1_vi": "Trong những giờ làm việc bận rộn, các quản lý lắng nghe những ý kiến khác nhau trước khi đưa ra quyết định."
  },
  {
    "id": 219,
    "word": "care",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɛɹ/",
    "meaning": "sự chăm sóc; chăm sóc",
    "ex1": "Doctors often discuss care during regular health checks.",
    "ex1_vi": "Bác sĩ thường trao đổi về sự chăm sóc; chăm sóc trong các lần khám sức khỏe định kỳ."
  },
  {
    "id": 220,
    "word": "better",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/bˈɛɾɚ/",
    "meaning": "tốt hơn",
    "ex1": "It also helps runners perform better and enjoy every training session.",
    "ex1_vi": "Nó cũng giúp người chạy thể hiện tốt hơn và tận hưởng mỗi buổi tập."
  },
  {
    "id": 221,
    "word": "present",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/prˈɛzʌnt/",
    "meaning": "hiện tại",
    "ex1": "Students practice the word present in a simple sentence about the environment.",
    "ex1_vi": "Học sinh luyện từ “present” trong một câu đơn giản về môi trường."
  }
];

const newReadingVocabOrder = [
  "saving",
  "energy",
  "future",
  "needed",
  "lights",
  "machines",
  "transport",
  "cooking",
  "and",
  "many",
  "daily",
  "activities",
  "however",
  "producing",
  "often",
  "uses",
  "coal",
  "oil",
  "or",
  "gas",
  "fuels",
  "can",
  "create",
  "pollution",
  "contribute",
  "climate",
  "change",
  "save",
  "turning",
  "off",
  "fans",
  "computers",
  "televisions",
  "when",
  "not",
  "using",
  "bulbs",
  "efficient",
  "appliances",
  "also",
  "helpful",
  "opening",
  "windows",
  "day",
  "reduce",
  "need",
  "air",
  "conditioners",
  "renewable",
  "sun",
  "wind",
  "water",
  "cleaner",
  "planet",
  "governments",
  "businesses",
  "should",
  "invest",
  "sources",
  "everyone",
  "wisely",
  "money",
  "protect",
  "natural",
  "resources",
  "generations",
  "come",
  "protecting",
  "forests",
  "wildlife",
  "home",
  "plants",
  "animals",
  "people",
  "provide",
  "clean",
  "food",
  "medicine",
  "wood",
  "protection",
  "floods",
  "trees",
  "absorb",
  "carbon",
  "dioxide",
  "help",
  "control",
  "earth",
  "temperature",
  "cut",
  "down",
  "loses",
  "shelter",
  "some",
  "may",
  "become",
  "endangered",
  "disappear",
  "forever",
  "deforestation",
  "cause",
  "soil",
  "erosion",
  "hotter",
  "weather",
  "problems",
  "less",
  "paper",
  "recycling",
  "planting",
  "buying",
  "responsible",
  "products",
  "hunt",
  "wild",
  "destroy",
  "habitats",
  "must",
  "protected",
  "areas",
  "stop",
  "illegal",
  "logging",
  "healthy",
  "important",
  "nature",
  "human",
  "life",
  "balance",
  "effects",
  "means",
  "long",
  "term",
  "changes",
  "patterns",
  "especially",
  "burning",
  "release",
  "gases",
  "trap",
  "heat",
  "atmosphere",
  "becomes",
  "warmer",
  "glaciers",
  "melt",
  "sea",
  "levels",
  "rise",
  "more",
  "extreme",
  "places",
  "face",
  "stronger",
  "storms",
  "droughts",
  "wildfires",
  "affects",
  "farming",
  "health",
  "reducing",
  "waste",
  "public",
  "supporting",
  "companies",
  "make",
  "larger",
  "harmful",
  "emissions",
  "working",
  "together",
  "necessary",
  "because",
  "every",
  "country",
  "actions",
  "today",
  "will",
  "shape",
  "building",
  "greener",
  "where",
  "live",
  "well",
  "without",
  "damaging",
  "cities",
  "healthier",
  "green",
  "buildings",
  "schools",
  "teach",
  "children",
  "how",
  "environment",
  "use",
  "safe",
  "materials",
  "last",
  "longer",
  "strong",
  "laws",
  "oceans",
  "person",
  "has",
  "role",
  "choose",
  "reusable",
  "eat",
  "responsibly",
  "support",
  "environmental",
  "projects",
  "requires",
  "cooperation",
  "patience",
  "good",
  "decisions",
  "care",
  "better",
  "present"
];
