// ===== environment01 ESSAY =====

const newEssayData = [
  {
    "text": "1. What Is the Environment?\nThe environment is everything around us, including air, water, land, plants, animals, and people. It gives us the natural resources we need to live, such as food, clean water, and fresh air.\nA healthy environment is important for every living thing. When rivers are polluted or forests are destroyed, animals lose their homes, and people may become sick. Small changes in nature can affect the whole planet.\nWe should learn to respect and protect the environment. We can save water, reduce waste, plant trees, and keep our neighborhoods clean. By making responsible choices every day, we help create a safer, healthier, and more beautiful world for everyone today and tomorrow.",
    "vi": "1. Môi trường là gì?\nMôi trường là mọi thứ xung quanh chúng ta, bao gồm không khí, nước, đất, thực vật, động vật và con người. Môi trường cung cấp những tài nguyên thiên nhiên mà chúng ta cần để sống, chẳng hạn như thực phẩm, nước sạch và không khí trong lành.\n\nMột môi trường lành mạnh rất quan trọng đối với mọi sinh vật. Khi sông ngòi bị ô nhiễm hoặc rừng bị tàn phá, động vật mất nơi ở và con người có thể bị bệnh. Những thay đổi nhỏ trong tự nhiên có thể ảnh hưởng đến toàn bộ hành tinh.\n\nChúng ta nên học cách tôn trọng và bảo vệ môi trường. Chúng ta có thể tiết kiệm nước, giảm rác thải, trồng cây và giữ khu dân cư sạch sẽ. Bằng cách đưa ra những lựa chọn có trách nhiệm mỗi ngày, chúng ta góp phần tạo nên một thế giới an toàn hơn, lành mạnh hơn và đẹp hơn cho mọi người hôm nay và mai sau."
  },
  {
    "text": "2. Protecting the Environment Every Day\nProtecting the environment can begin with simple actions in our daily lives. We do not need to make big changes immediately. Small habits, when practiced by many people, can create a strong positive effect.\nAt home, we can turn off lights, use less water, and avoid single-use plastic. We can carry reusable bags, bottles, and lunch boxes. Walking, cycling, or using public transport also helps reduce pollution.\nAt school or work, we should keep places clean and recycle paper, cans, and plastic correctly. We can also remind friends and family to care for nature. Every responsible action protects the planet and encourages others to do the same each new day.",
    "vi": "2. Bảo vệ môi trường mỗi ngày\nViệc bảo vệ môi trường có thể bắt đầu từ những hành động đơn giản trong cuộc sống hằng ngày. Chúng ta không cần tạo ra những thay đổi lớn ngay lập tức. Những thói quen nhỏ, khi được nhiều người thực hiện, có thể tạo ra tác động tích cực mạnh mẽ.\n\nỞ nhà, chúng ta có thể tắt đèn, dùng ít nước hơn và tránh nhựa dùng một lần. Chúng ta có thể mang theo túi, chai và hộp đựng bữa trưa có thể tái sử dụng. Đi bộ, đi xe đạp hoặc dùng phương tiện công cộng cũng giúp giảm ô nhiễm.\n\nỞ trường hoặc nơi làm việc, chúng ta nên giữ nơi chốn sạch sẽ và tái chế giấy, lon và nhựa đúng cách. Chúng ta cũng có thể nhắc bạn bè và gia đình quan tâm đến thiên nhiên. Mỗi hành động có trách nhiệm đều bảo vệ hành tinh và khuyến khích người khác làm điều tương tự mỗi ngày."
  },
  {
    "text": "3. The Problem of Air Pollution\nAir pollution happens when harmful gases, smoke, and dust enter the air. Cars, factories, fires, and construction work are common causes. Polluted air can be difficult to see, but it can still harm our health.\nPeople who breathe dirty air may cough, feel tired, or have breathing problems. Air pollution also damages plants, animals, buildings, and the climate. Children and older people are often more affected by it.\nWe can help reduce air pollution by using public transport, riding bicycles, and saving electricity. Governments should control factory smoke and support clean energy. Planting more trees is also helpful because trees clean the air and make cities cooler and healthier everywhere.",
    "vi": "3. Vấn đề ô nhiễm không khí\nÔ nhiễm không khí xảy ra khi các loại khí có hại, khói và bụi đi vào không khí. Ô tô, nhà máy, đám cháy và công trình xây dựng là những nguyên nhân phổ biến. Không khí bị ô nhiễm có thể khó nhìn thấy, nhưng vẫn có thể gây hại cho sức khỏe.\n\nNhững người hít thở không khí bẩn có thể ho, cảm thấy mệt hoặc gặp vấn đề về hô hấp. Ô nhiễm không khí cũng gây hại cho thực vật, động vật, các tòa nhà và khí hậu. Trẻ em và người lớn tuổi thường bị ảnh hưởng nhiều hơn.\n\nChúng ta có thể giúp giảm ô nhiễm không khí bằng cách dùng phương tiện công cộng, đi xe đạp và tiết kiệm điện. Chính phủ nên kiểm soát khói nhà máy và hỗ trợ năng lượng sạch. Trồng thêm cây cũng hữu ích vì cây làm sạch không khí và giúp thành phố mát mẻ, lành mạnh hơn."
  }
];
