const lessonVocabularyWords = [
  "fruit",
  "smoothies",
  "thick",
  "cold",
  "drinks",
  "made",
  "fresh",
  "vietnam",
  "popular",
  "include",
  "avocado",
  "mango",
  "strawberry",
  "banana",
  "and",
  "soursop",
  "make",
  "smoothie",
  "people",
  "put",
  "ice",
  "milk",
  "sugar",
  "blender",
  "machine",
  "mixes",
  "everything",
  "until",
  "becomes",
  "smooth",
  "common",
  "cafes",
  "juice",
  "shops",
  "family",
  "kitchens",
  "often",
  "served",
  "tall",
  "glasses",
  "straw",
  "spoon",
  "like",
  "because",
  "sweet",
  "creamy",
  "full",
  "flavor",
  "usually",
  "choose",
  "less",
  "more",
  "can",
  "tasty",
  "snack",
  "after",
  "school",
  "or",
  "work",
  "hot",
  "days",
  "when",
  "want",
  "something",
  "filling",
  "soy",
  "simple",
  "drink",
  "soybeans",
  "soak",
  "water",
  "grind",
  "cook",
  "liquid",
  "may",
  "added",
  "sweeter",
  "taste",
  "many",
  "breakfast",
  "sold",
  "schools",
  "markets",
  "bakeries",
  "small",
  "food",
  "stalls",
  "morning",
  "warm",
  "soft",
  "light",
  "comforting",
  "also",
  "provides",
  "protein",
  "body",
  "some",
  "sellers",
  "add",
  "pandan",
  "leaves",
  "sesame",
  "peanuts",
  "create",
  "different",
  "flavors",
  "smells",
  "gentle",
  "suitable",
  "both",
  "children",
  "adults",
  "fizzy",
  "easy",
  "find",
  "come",
  "such",
  "as",
  "cola",
  "orange",
  "lemon",
  "soda",
  "contain",
  "flavoring",
  "gas",
  "creates",
  "bubbles",
  "gives",
  "sharp",
  "feeling",
  "serve",
  "parties",
  "restaurants",
  "weddings",
  "celebrations",
  "enjoyed",
  "sometimes",
  "fast",
  "but",
  "try",
  "not",
  "have",
  "every",
  "day",
  "too",
  "much",
  "good",
  "health",
  "better",
  "daily",
  "choices",
  "still",
  "occasional",
  "glass",
  "fun",
  "refreshing",
  "bottled",
  "mineral",
  "clean",
  "convenient",
  "used",
  "across",
  "offices",
  "bus",
  "stations",
  "comes",
  "natural",
  "underground",
  "sources",
  "amounts",
  "calcium",
  "magnesium",
  "other",
  "useful",
  "minerals",
  "carry",
  "travel",
  "exercise",
  "study",
  "outdoors",
  "closed",
  "bottle",
  "keep",
  "bag",
  "needs",
  "enough",
  "well",
  "finishing",
  "recycling",
  "bin",
  "possible",
  "using",
  "reusable",
  "reduce",
  "plastic",
  "waste",
  "healthy",
  "choice",
  "busy"
];

const newVocabData = [
  {
    "id": 1,
    "word": "fruit",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈut/",
    "meaning": "trái cây",
    "ex1": "Fruit smoothies are thick, cold drinks made from fresh fruit.",
    "ex1_vi": "Sinh tố trái cây là những thức uống đặc, lạnh được làm từ trái cây tươi."
  },
  {
    "id": 2,
    "word": "smoothies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsmuːðiz/",
    "meaning": "sinh tố",
    "ex1": "Fruit smoothies are thick, cold drinks made from fresh fruit.",
    "ex1_vi": "Sinh tố trái cây là những thức uống đặc, lạnh được làm từ trái cây tươi."
  },
  {
    "id": 3,
    "word": "thick",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈɪk/",
    "meaning": "đặc",
    "ex1": "People discuss thick when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về đặc khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 4,
    "word": "cold",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈoʊld/",
    "meaning": "lạnh",
    "ex1": "People discuss cold when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về lạnh khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 5,
    "word": "drinks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɪŋks/",
    "meaning": "thức uống",
    "ex1": "People discuss drinks when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về thức uống khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 6,
    "word": "made",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪd/",
    "meaning": "được làm; pha",
    "ex1": "People discuss made when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về được làm; pha khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 7,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi; sảng khoái",
    "ex1": "People discuss fresh when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về tươi; sảng khoái khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 8,
    "word": "vietnam",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/viˌɛtnˈɑm/",
    "meaning": "Việt Nam",
    "ex1": "In Vietnam, popular smoothies include avocado, mango, strawberry, banana, and soursop.",
    "ex1_vi": "Ở Việt Nam, các loại sinh tố phổ biến gồm bơ, xoài, dâu tây, chuối và mãng cầu."
  },
  {
    "id": 9,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "In Vietnam, popular smoothies include avocado, mango, strawberry, banana, and soursop.",
    "ex1_vi": "Ở Việt Nam, các loại sinh tố phổ biến gồm bơ, xoài, dâu tây, chuối và mãng cầu."
  },
  {
    "id": 10,
    "word": "include",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪnklˈud/",
    "meaning": "bao gồm",
    "ex1": "People discuss include when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về bao gồm khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 11,
    "word": "avocado",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌævəˈkɑːdoʊ/",
    "meaning": "bơ",
    "ex1": "People discuss avocado when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về bơ khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 12,
    "word": "mango",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈæŋɡoʊ/",
    "meaning": "xoài",
    "ex1": "People discuss mango when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về xoài khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 13,
    "word": "strawberry",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈstrɔːbɛri/",
    "meaning": "dâu tây",
    "ex1": "People discuss strawberry when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về dâu tây khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 14,
    "word": "banana",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bʌnˈænʌ/",
    "meaning": "chuối",
    "ex1": "People discuss banana when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về chuối khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 15,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "People discuss and when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về và khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 16,
    "word": "soursop",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsaʊərsɑːp/",
    "meaning": "mãng cầu",
    "ex1": "People discuss soursop when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về mãng cầu khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 17,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm",
    "ex1": "People can make drinks during simple preparation at home.",
    "ex1_vi": "Mọi người có thể làm đồ uống trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 18,
    "word": "smoothie",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsmuːði/",
    "meaning": "sinh tố",
    "ex1": "People learn about smoothie when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về sinh tố khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 19,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "People learn about people when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về mọi người khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 20,
    "word": "put",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pˈʊt/",
    "meaning": "cho; đặt",
    "ex1": "People can put drinks during simple preparation at home.",
    "ex1_vi": "Mọi người có thể cho; đặt đồ uống trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 21,
    "word": "ice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪs/",
    "meaning": "đá",
    "ex1": "People add ice to make many drinks cold.",
    "ex1_vi": "Mọi người thêm đá để làm nhiều thức uống trở nên lạnh."
  },
  {
    "id": 22,
    "word": "milk",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɪlk/",
    "meaning": "sữa",
    "ex1": "Milk can make some drinks softer and creamier.",
    "ex1_vi": "Sữa có thể làm một số thức uống nhẹ và béo hơn."
  },
  {
    "id": 23,
    "word": "sugar",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈʊɡɝ/",
    "meaning": "đường",
    "ex1": "Too much sugar can hide the natural fruit taste.",
    "ex1_vi": "Quá nhiều đường có thể che mất vị tự nhiên của trái cây."
  },
  {
    "id": 24,
    "word": "blender",
    "type": "noun",
    "cat": "n",
    "phonetic": "/blˈɛndɝ/",
    "meaning": "máy xay",
    "ex1": "People learn about blender when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về máy xay khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 25,
    "word": "machine",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mʌʃˈin/",
    "meaning": "máy",
    "ex1": "The machine mixes everything until it becomes smooth.",
    "ex1_vi": "Máy trộn mọi thứ cho đến khi trở nên mịn."
  },
  {
    "id": 26,
    "word": "mixes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɪksʌz/",
    "meaning": "trộn",
    "ex1": "The machine mixes everything until it becomes smooth.",
    "ex1_vi": "Máy trộn mọi thứ cho đến khi trở nên mịn."
  },
  {
    "id": 27,
    "word": "everything",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvriθˌɪŋ/",
    "meaning": "mọi thứ",
    "ex1": "People discuss everything when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về mọi thứ khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 28,
    "word": "until",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌntˈɪl/",
    "meaning": "cho đến khi",
    "ex1": "People discuss until when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về cho đến khi khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 29,
    "word": "becomes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌmz/",
    "meaning": "trở nên",
    "ex1": "People discuss becomes when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về trở nên khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 30,
    "word": "smooth",
    "type": "noun",
    "cat": "n",
    "phonetic": "/smˈuð/",
    "meaning": "mịn",
    "ex1": "People discuss smooth when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về mịn khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 31,
    "word": "common",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɑmʌn/",
    "meaning": "phổ biến",
    "ex1": "Smoothies are common in cafés, juice shops, and family kitchens.",
    "ex1_vi": "Sinh tố phổ biến ở quán cà phê, cửa hàng nước ép và bếp gia đình."
  },
  {
    "id": 32,
    "word": "cafes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kæˈfeɪz/",
    "meaning": "quán cà phê",
    "ex1": "Smoothies are common in cafés, juice shops, and family kitchens.",
    "ex1_vi": "Sinh tố phổ biến ở quán cà phê, cửa hàng nước ép và bếp gia đình."
  },
  {
    "id": 33,
    "word": "juice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈus/",
    "meaning": "nước ép; nước",
    "ex1": "People discuss juice when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về nước ép; nước khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 34,
    "word": "shops",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɑps/",
    "meaning": "cửa hàng",
    "ex1": "People discuss shops when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về cửa hàng khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 35,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "People discuss family when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về gia đình khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 36,
    "word": "kitchens",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɪtʃʌnz/",
    "meaning": "bếp",
    "ex1": "People discuss kitchens when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về bếp khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 37,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "They are often served in tall glasses with a straw and spoon.",
    "ex1_vi": "Chúng thường được phục vụ trong những ly cao với ống hút và thìa."
  },
  {
    "id": 38,
    "word": "served",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɝvd/",
    "meaning": "được phục vụ",
    "ex1": "They are often served in tall glasses with a straw and spoon.",
    "ex1_vi": "Chúng thường được phục vụ trong những ly cao với ống hút và thìa."
  },
  {
    "id": 39,
    "word": "tall",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈɔl/",
    "meaning": "cao",
    "ex1": "People discuss tall when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về cao khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 40,
    "word": "glasses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡlˈæsʌz/",
    "meaning": "ly",
    "ex1": "People discuss glasses when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về ly khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 41,
    "word": "straw",
    "type": "noun",
    "cat": "n",
    "phonetic": "/strˈɔ/",
    "meaning": "ống hút",
    "ex1": "People discuss straw when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về ống hút khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 42,
    "word": "spoon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈun/",
    "meaning": "thìa",
    "ex1": "People discuss spoon when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về thìa khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 43,
    "word": "like",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈaɪk/",
    "meaning": "thích",
    "ex1": "People can like drinks during simple preparation at home.",
    "ex1_vi": "Mọi người có thể thích đồ uống trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 44,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "I choose coconut water because it tastes fresh and light.",
    "ex1_vi": "Tôi chọn nước dừa vì nó có vị tươi và nhẹ."
  },
  {
    "id": 45,
    "word": "sweet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/swˈit/",
    "meaning": "ngọt",
    "ex1": "This drink is sweet and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này ngọt và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 46,
    "word": "creamy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈimi/",
    "meaning": "béo; sánh",
    "ex1": "This drink is creamy and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này béo; sánh và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 47,
    "word": "full",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈʊl/",
    "meaning": "trọn vẹn",
    "ex1": "This drink is full and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này trọn vẹn và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 48,
    "word": "flavor",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝ/",
    "meaning": "hương vị",
    "ex1": "Fresh fruit gives each drink a natural flavor.",
    "ex1_vi": "Trái cây tươi mang lại hương vị tự nhiên cho mỗi thức uống."
  },
  {
    "id": 49,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "I usually choose less sugar and more fruit.",
    "ex1_vi": "Tôi thường chọn ít đường và nhiều trái cây hơn."
  },
  {
    "id": 50,
    "word": "choose",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈuz/",
    "meaning": "chọn",
    "ex1": "I usually choose less sugar and more fruit.",
    "ex1_vi": "Tôi thường chọn ít đường và nhiều trái cây hơn."
  },
  {
    "id": 51,
    "word": "less",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/lˈɛs/",
    "meaning": "ít hơn",
    "ex1": "People discuss less when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về ít hơn khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 52,
    "word": "more",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "nhiều hơn",
    "ex1": "People discuss more when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về nhiều hơn khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 53,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "A smoothie can be a tasty snack after school or work.",
    "ex1_vi": "Một ly sinh tố có thể là món ăn nhẹ ngon sau giờ học hoặc làm việc."
  },
  {
    "id": 54,
    "word": "tasty",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈeɪsti/",
    "meaning": "ngon",
    "ex1": "A smoothie can be a tasty snack after school or work.",
    "ex1_vi": "Một ly sinh tố có thể là món ăn nhẹ ngon sau giờ học hoặc làm việc."
  },
  {
    "id": 55,
    "word": "snack",
    "type": "noun",
    "cat": "n",
    "phonetic": "/snˈæk/",
    "meaning": "món ăn nhẹ",
    "ex1": "People discuss snack when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về món ăn nhẹ khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 56,
    "word": "after",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/ˈæftɝ/",
    "meaning": "sau",
    "ex1": "People discuss after when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về sau khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 57,
    "word": "school",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈul/",
    "meaning": "trường học",
    "ex1": "People discuss school when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về trường học khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 58,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "People discuss or when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về hoặc khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 59,
    "word": "work",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝk/",
    "meaning": "làm việc",
    "ex1": "People discuss work when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về làm việc khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 60,
    "word": "hot",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑt/",
    "meaning": "nóng",
    "ex1": "This drink is hot and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này nóng và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 61,
    "word": "days",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪz/",
    "meaning": "ngày",
    "ex1": "People learn about days when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về ngày khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 62,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "People carry bottled water when they travel outdoors.",
    "ex1_vi": "Mọi người mang nước đóng chai khi đi du lịch ngoài trời."
  },
  {
    "id": 63,
    "word": "want",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɑnt/",
    "meaning": "muốn",
    "ex1": "People can want drinks during simple preparation at home.",
    "ex1_vi": "Mọi người có thể muốn đồ uống trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 64,
    "word": "something",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/sˈʌmθɪŋ/",
    "meaning": "thứ gì đó",
    "ex1": "People learn about something when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về thứ gì đó khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 65,
    "word": "filling",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɪlɪŋ/",
    "meaning": "no bụng",
    "ex1": "This drink is filling and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này no bụng và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 66,
    "word": "soy",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔɪ/",
    "meaning": "đậu nành",
    "ex1": "Soy milk is a simple drink made from soybeans.",
    "ex1_vi": "Sữa đậu nành là một thức uống đơn giản làm từ đậu nành."
  },
  {
    "id": 67,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "Soy milk is a simple drink made from soybeans.",
    "ex1_vi": "Sữa đậu nành là một thức uống đơn giản làm từ đậu nành."
  },
  {
    "id": 68,
    "word": "drink",
    "type": "verb",
    "cat": "v",
    "phonetic": "/drˈɪŋk/",
    "meaning": "thức uống; uống",
    "ex1": "People discuss drink when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về thức uống; uống khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 69,
    "word": "soybeans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsɔɪbiːnz/",
    "meaning": "đậu nành",
    "ex1": "People discuss soybeans when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về đậu nành khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 70,
    "word": "soak",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈoʊk/",
    "meaning": "ngâm",
    "ex1": "People can soak drinks during simple preparation at home.",
    "ex1_vi": "Mọi người có thể ngâm đồ uống trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 71,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước",
    "ex1": "People should drink enough water throughout a busy day.",
    "ex1_vi": "Mọi người nên uống đủ nước trong một ngày bận rộn."
  },
  {
    "id": 72,
    "word": "grind",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡrˈaɪnd/",
    "meaning": "xay",
    "ex1": "People can grind drinks during simple preparation at home.",
    "ex1_vi": "Mọi người có thể xay đồ uống trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 73,
    "word": "cook",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʊk/",
    "meaning": "nấu",
    "ex1": "People can cook drinks during simple preparation at home.",
    "ex1_vi": "Mọi người có thể nấu đồ uống trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 74,
    "word": "liquid",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɪkwʌd/",
    "meaning": "chất lỏng",
    "ex1": "This drink is liquid and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này chất lỏng và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 75,
    "word": "may",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈeɪ/",
    "meaning": "có thể",
    "ex1": "Sugar may be added for a sweeter taste.",
    "ex1_vi": "Có thể thêm đường để có vị ngọt hơn."
  },
  {
    "id": 76,
    "word": "added",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈædʌd/",
    "meaning": "được thêm",
    "ex1": "Sugar may be added for a sweeter taste.",
    "ex1_vi": "Có thể thêm đường để có vị ngọt hơn."
  },
  {
    "id": 77,
    "word": "sweeter",
    "type": "noun",
    "cat": "n",
    "phonetic": "/swˈitɝ/",
    "meaning": "ngọt hơn",
    "ex1": "People discuss sweeter when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về ngọt hơn khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 78,
    "word": "taste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪst/",
    "meaning": "hương vị; vị",
    "ex1": "People discuss taste when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về hương vị; vị khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 79,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Many drinks can be refreshing during hot Vietnamese afternoons.",
    "ex1_vi": "Nhiều thức uống có thể sảng khoái trong những buổi chiều nóng ở Việt Nam."
  },
  {
    "id": 80,
    "word": "breakfast",
    "type": "noun",
    "cat": "n",
    "phonetic": "/brˈɛkfʌst/",
    "meaning": "bữa sáng",
    "ex1": "People learn about breakfast when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về bữa sáng khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 81,
    "word": "sold",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈoʊld/",
    "meaning": "được bán",
    "ex1": "People learn about sold when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về được bán khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 82,
    "word": "schools",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈulz/",
    "meaning": "trường học",
    "ex1": "People learn about schools when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về trường học khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 83,
    "word": "markets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɑrkʌts/",
    "meaning": "chợ",
    "ex1": "People learn about markets when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về chợ khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 84,
    "word": "bakeries",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈeɪkɝiz/",
    "meaning": "tiệm bánh",
    "ex1": "People learn about bakeries when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về tiệm bánh khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 85,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "This drink is small and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này nhỏ và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 86,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thức ăn",
    "ex1": "People learn about food when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về thức ăn khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 87,
    "word": "stalls",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈɔlz/",
    "meaning": "quầy hàng",
    "ex1": "People learn about stalls when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về quầy hàng khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 88,
    "word": "morning",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɔrnɪŋ/",
    "meaning": "buổi sáng",
    "ex1": "People learn about morning when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về buổi sáng khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 89,
    "word": "warm",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈɔrm/",
    "meaning": "ấm",
    "ex1": "I like warm soy milk because it is soft, light, and comforting.",
    "ex1_vi": "Tôi thích sữa đậu nành ấm vì nó mềm nhẹ và dễ chịu."
  },
  {
    "id": 90,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "I like warm soy milk because it is soft, light, and comforting.",
    "ex1_vi": "Tôi thích sữa đậu nành ấm vì nó mềm nhẹ và dễ chịu."
  },
  {
    "id": 91,
    "word": "light",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈaɪt/",
    "meaning": "nhẹ",
    "ex1": "People discuss light when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về nhẹ khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 92,
    "word": "comforting",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌmfɝtɪŋ/",
    "meaning": "dễ chịu",
    "ex1": "People discuss comforting when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về dễ chịu khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 93,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "People also enjoy fresh drinks during hot afternoons.",
    "ex1_vi": "Mọi người cũng thưởng thức đồ uống tươi trong những buổi chiều nóng."
  },
  {
    "id": 94,
    "word": "provides",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌvˈaɪdz/",
    "meaning": "cung cấp",
    "ex1": "This drink provides naturally during simple preparation at home.",
    "ex1_vi": "Thức uống này cung cấp một cách tự nhiên trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 95,
    "word": "protein",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈoʊtˌin/",
    "meaning": "protein",
    "ex1": "People learn about protein when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về protein khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 96,
    "word": "body",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɑdi/",
    "meaning": "cơ thể",
    "ex1": "People learn about body when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về cơ thể khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 97,
    "word": "some",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌm/",
    "meaning": "một số",
    "ex1": "Some drinks can be refreshing during hot Vietnamese afternoons.",
    "ex1_vi": "Một số thức uống có thể sảng khoái trong những buổi chiều nóng ở Việt Nam."
  },
  {
    "id": 98,
    "word": "sellers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛlɝz/",
    "meaning": "người bán",
    "ex1": "People learn about sellers when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về người bán khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 99,
    "word": "add",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈæd/",
    "meaning": "thêm",
    "ex1": "People can add drinks during simple preparation at home.",
    "ex1_vi": "Mọi người có thể thêm đồ uống trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 100,
    "word": "pandan",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈpændən/",
    "meaning": "lá dứa",
    "ex1": "People learn about pandan when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về lá dứa khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 101,
    "word": "leaves",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈivz/",
    "meaning": "lá",
    "ex1": "People learn about leaves when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về lá khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 102,
    "word": "sesame",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsɛsəmi/",
    "meaning": "mè",
    "ex1": "People learn about sesame when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về mè khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 103,
    "word": "peanuts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈinʌts/",
    "meaning": "đậu phộng",
    "ex1": "People learn about peanuts when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về đậu phộng khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 104,
    "word": "create",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪt/",
    "meaning": "tạo ra",
    "ex1": "People can create drinks during simple preparation at home.",
    "ex1_vi": "Mọi người có thể tạo ra đồ uống trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 105,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "This drink is different and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này khác nhau và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 106,
    "word": "flavors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝz/",
    "meaning": "hương vị",
    "ex1": "People learn about flavors when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về hương vị khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 107,
    "word": "smells",
    "type": "verb",
    "cat": "v",
    "phonetic": "/smˈɛlz/",
    "meaning": "mùi",
    "ex1": "This drink smells naturally during simple preparation at home.",
    "ex1_vi": "Thức uống này mùi một cách tự nhiên trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 108,
    "word": "gentle",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈɛntʌl/",
    "meaning": "nhẹ nhàng",
    "ex1": "This drink is gentle and suitable for both children and adults.",
    "ex1_vi": "Thức uống này nhẹ nhàng và phù hợp cho cả trẻ em lẫn người lớn."
  },
  {
    "id": 109,
    "word": "suitable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈutʌbʌl/",
    "meaning": "phù hợp",
    "ex1": "This drink is gentle and suitable for both children and adults.",
    "ex1_vi": "Thức uống này nhẹ nhàng và phù hợp cho cả trẻ em lẫn người lớn."
  },
  {
    "id": 110,
    "word": "both",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/bˈoʊθ/",
    "meaning": "cả hai",
    "ex1": "People discuss both when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về cả hai khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 111,
    "word": "children",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪldrʌn/",
    "meaning": "trẻ em",
    "ex1": "People discuss children when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về trẻ em khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 112,
    "word": "adults",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌdˈʌlts/",
    "meaning": "người lớn",
    "ex1": "People discuss adults when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về người lớn khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 113,
    "word": "fizzy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈfɪzi/",
    "meaning": "có ga",
    "ex1": "This drink is fizzy and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này có ga và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 114,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "This drink is easy and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này dễ và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 115,
    "word": "find",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪnd/",
    "meaning": "tìm thấy",
    "ex1": "People can find drinks during simple preparation at home.",
    "ex1_vi": "Mọi người có thể tìm thấy đồ uống trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 116,
    "word": "come",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌm/",
    "meaning": "có; đến",
    "ex1": "They come in many flavors, such as cola, orange, lemon, and soda.",
    "ex1_vi": "Chúng có nhiều hương vị như cola, cam, chanh và soda."
  },
  {
    "id": 117,
    "word": "such",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌtʃ/",
    "meaning": "như",
    "ex1": "They come in many flavors, such as cola, orange, lemon, and soda.",
    "ex1_vi": "Chúng có nhiều hương vị như cola, cam, chanh và soda."
  },
  {
    "id": 118,
    "word": "as",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ˈæz/",
    "meaning": "như; bằng",
    "ex1": "People discuss as when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về như; bằng khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 119,
    "word": "cola",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈoʊlʌ/",
    "meaning": "cola",
    "ex1": "People discuss cola when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về cola khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 120,
    "word": "orange",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔrʌndʒ/",
    "meaning": "cam",
    "ex1": "People discuss orange when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về cam khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 121,
    "word": "lemon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɛmʌn/",
    "meaning": "chanh vàng",
    "ex1": "People discuss lemon when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về chanh vàng khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 122,
    "word": "soda",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈoʊdʌ/",
    "meaning": "soda",
    "ex1": "People discuss soda when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về soda khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 123,
    "word": "contain",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈeɪn/",
    "meaning": "chứa",
    "ex1": "These drinks contain water, sugar, flavoring, and gas.",
    "ex1_vi": "Những thức uống này chứa nước, đường, hương liệu và khí."
  },
  {
    "id": 124,
    "word": "flavoring",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈfleɪvərɪŋ/",
    "meaning": "hương liệu",
    "ex1": "These drinks contain water, sugar, flavoring, and gas.",
    "ex1_vi": "Những thức uống này chứa nước, đường, hương liệu và khí."
  },
  {
    "id": 125,
    "word": "gas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈæs/",
    "meaning": "khí ga",
    "ex1": "People discuss gas when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về khí ga khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 126,
    "word": "creates",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪts/",
    "meaning": "tạo ra",
    "ex1": "The gas creates small bubbles and gives the drink a sharp feeling.",
    "ex1_vi": "Khí tạo ra các bong bóng nhỏ và mang lại cảm giác sắc, sủi."
  },
  {
    "id": 127,
    "word": "bubbles",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʌbʌlz/",
    "meaning": "bong bóng",
    "ex1": "The gas creates small bubbles and gives the drink a sharp feeling.",
    "ex1_vi": "Khí tạo ra các bong bóng nhỏ và mang lại cảm giác sắc, sủi."
  },
  {
    "id": 128,
    "word": "gives",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvz/",
    "meaning": "mang lại",
    "ex1": "People discuss gives when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về mang lại khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 129,
    "word": "sharp",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɑrp/",
    "meaning": "sắc; mạnh",
    "ex1": "People discuss sharp when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về sắc; mạnh khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 130,
    "word": "feeling",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈilɪŋ/",
    "meaning": "cảm giác",
    "ex1": "People discuss feeling when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về cảm giác khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 131,
    "word": "serve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɝv/",
    "meaning": "phục vụ",
    "ex1": "People often serve soft drinks at parties, restaurants, weddings, and family celebrations.",
    "ex1_vi": "Mọi người thường phục vụ nước ngọt tại các bữa tiệc, nhà hàng, đám cưới và lễ kỷ niệm gia đình."
  },
  {
    "id": 132,
    "word": "parties",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrtiz/",
    "meaning": "bữa tiệc",
    "ex1": "People often serve soft drinks at parties, restaurants, weddings, and family celebrations.",
    "ex1_vi": "Mọi người thường phục vụ nước ngọt tại các bữa tiệc, nhà hàng, đám cưới và lễ kỷ niệm gia đình."
  },
  {
    "id": 133,
    "word": "restaurants",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɛstɝˌɑnts/",
    "meaning": "nhà hàng",
    "ex1": "People discuss restaurants when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về nhà hàng khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 134,
    "word": "weddings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɛdɪŋz/",
    "meaning": "đám cưới",
    "ex1": "People discuss weddings when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về đám cưới khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 135,
    "word": "celebrations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˌɛlʌbrˈeɪʃʌnz/",
    "meaning": "lễ kỷ niệm",
    "ex1": "People discuss celebrations when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về lễ kỷ niệm khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 136,
    "word": "enjoyed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪd/",
    "meaning": "được thưởng thức",
    "ex1": "The drink was enjoyed carefully before customers enjoyed it.",
    "ex1_vi": "Thức uống được được thưởng thức cẩn thận trước khi khách hàng thưởng thức."
  },
  {
    "id": 137,
    "word": "sometimes",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sʌmtˈaɪmz/",
    "meaning": "đôi khi",
    "ex1": "People sometimes enjoy fresh drinks during hot afternoons.",
    "ex1_vi": "Mọi người đôi khi thưởng thức đồ uống tươi trong những buổi chiều nóng."
  },
  {
    "id": 138,
    "word": "fast",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈæst/",
    "meaning": "nhanh; đồ ăn nhanh",
    "ex1": "This drink is fast and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này nhanh; đồ ăn nhanh và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 139,
    "word": "but",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bˈʌt/",
    "meaning": "nhưng",
    "ex1": "Fresh juice is sweet but still tastes light.",
    "ex1_vi": "Nước ép tươi ngọt nhưng vẫn có vị nhẹ."
  },
  {
    "id": 140,
    "word": "try",
    "type": "verb",
    "cat": "v",
    "phonetic": "/trˈaɪ/",
    "meaning": "cố gắng",
    "ex1": "People can try drinks during simple preparation at home.",
    "ex1_vi": "Mọi người có thể cố gắng đồ uống trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 141,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "People not enjoy fresh drinks during hot afternoons.",
    "ex1_vi": "Mọi người không thưởng thức đồ uống tươi trong những buổi chiều nóng."
  },
  {
    "id": 142,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có; uống",
    "ex1": "People can have drinks during simple preparation at home.",
    "ex1_vi": "Mọi người có thể có; uống đồ uống trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 143,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɝi/",
    "meaning": "mỗi",
    "ex1": "Every drinks can be refreshing during hot Vietnamese afternoons.",
    "ex1_vi": "Mỗi thức uống có thể sảng khoái trong những buổi chiều nóng ở Việt Nam."
  },
  {
    "id": 144,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "People learn about day when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về ngày khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 145,
    "word": "too",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tˈu/",
    "meaning": "quá",
    "ex1": "Too much sugar is not good for health.",
    "ex1_vi": "Quá nhiều đường không tốt cho sức khỏe."
  },
  {
    "id": 146,
    "word": "much",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈʌtʃ/",
    "meaning": "nhiều",
    "ex1": "Too much sugar is not good for health.",
    "ex1_vi": "Quá nhiều đường không tốt cho sức khỏe."
  },
  {
    "id": 147,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "People discuss good when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về tốt khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 148,
    "word": "health",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛlθ/",
    "meaning": "sức khỏe",
    "ex1": "People discuss health when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về sức khỏe khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 149,
    "word": "better",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/bˈɛtɝ/",
    "meaning": "tốt hơn",
    "ex1": "Water, milk, and fresh juice are better daily choices.",
    "ex1_vi": "Nước, sữa và nước ép tươi là những lựa chọn hằng ngày tốt hơn."
  },
  {
    "id": 150,
    "word": "daily",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈeɪli/",
    "meaning": "hằng ngày",
    "ex1": "Water, milk, and fresh juice are better daily choices.",
    "ex1_vi": "Nước, sữa và nước ép tươi là những lựa chọn hằng ngày tốt hơn."
  },
  {
    "id": 151,
    "word": "choices",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɔɪsʌz/",
    "meaning": "lựa chọn",
    "ex1": "People discuss choices when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về lựa chọn khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 152,
    "word": "still",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/stˈɪl/",
    "meaning": "tuy vậy",
    "ex1": "Still, an occasional cold glass can be fun and refreshing too.",
    "ex1_vi": "Tuy vậy, thỉnh thoảng một ly lạnh cũng có thể vui và sảng khoái."
  },
  {
    "id": 153,
    "word": "occasional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌkˈeɪʒʌnʌl/",
    "meaning": "thỉnh thoảng",
    "ex1": "Still, an occasional cold glass can be fun and refreshing too.",
    "ex1_vi": "Tuy vậy, thỉnh thoảng một ly lạnh cũng có thể vui và sảng khoái."
  },
  {
    "id": 154,
    "word": "glass",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡlˈæs/",
    "meaning": "ly",
    "ex1": "People discuss glass when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về ly khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 155,
    "word": "fun",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈʌn/",
    "meaning": "vui",
    "ex1": "People discuss fun when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về vui khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 156,
    "word": "refreshing",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪfrˈɛʃɪŋ/",
    "meaning": "sảng khoái",
    "ex1": "People discuss refreshing when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về sảng khoái khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 157,
    "word": "bottled",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈbɑːtəld/",
    "meaning": "đóng chai",
    "ex1": "Bottled mineral water is a clean and convenient drink used across Vietnam.",
    "ex1_vi": "Nước khoáng đóng chai là một thức uống sạch và tiện lợi được sử dụng trên khắp Việt Nam."
  },
  {
    "id": 158,
    "word": "mineral",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈɪnɝʌl/",
    "meaning": "khoáng",
    "ex1": "Bottled mineral water is a clean and convenient drink used across Vietnam.",
    "ex1_vi": "Nước khoáng đóng chai là một thức uống sạch và tiện lợi được sử dụng trên khắp Việt Nam."
  },
  {
    "id": 159,
    "word": "clean",
    "type": "verb",
    "cat": "v",
    "phonetic": "/klˈin/",
    "meaning": "sạch",
    "ex1": "People discuss clean when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về sạch khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 160,
    "word": "convenient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kʌnvˈinjʌnt/",
    "meaning": "tiện lợi",
    "ex1": "People discuss convenient when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về tiện lợi khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 161,
    "word": "used",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzd/",
    "meaning": "được sử dụng",
    "ex1": "People discuss used when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về được sử dụng khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 162,
    "word": "across",
    "type": "preposition/adverb",
    "cat": "adv",
    "phonetic": "/ʌkrˈɔs/",
    "meaning": "khắp; qua",
    "ex1": "People discuss across when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về khắp; qua khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 163,
    "word": "offices",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔfʌsʌz/",
    "meaning": "văn phòng",
    "ex1": "It is sold in shops, schools, offices, restaurants, and bus stations.",
    "ex1_vi": "Nó được bán ở cửa hàng, trường học, văn phòng, nhà hàng và trạm xe buýt."
  },
  {
    "id": 164,
    "word": "bus",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʌs/",
    "meaning": "xe buýt",
    "ex1": "It is sold in shops, schools, offices, restaurants, and bus stations.",
    "ex1_vi": "Nó được bán ở cửa hàng, trường học, văn phòng, nhà hàng và trạm xe buýt."
  },
  {
    "id": 165,
    "word": "stations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈeɪʃʌnz/",
    "meaning": "trạm",
    "ex1": "People discuss stations when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về trạm khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 166,
    "word": "comes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌmz/",
    "meaning": "đến; có nguồn gốc",
    "ex1": "This drink comes naturally during simple preparation at home.",
    "ex1_vi": "Thức uống này đến; có nguồn gốc một cách tự nhiên trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 167,
    "word": "natural",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈætʃɝʌl/",
    "meaning": "tự nhiên",
    "ex1": "This drink is natural and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này tự nhiên và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 168,
    "word": "underground",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈʌndɝɡrˌaʊnd/",
    "meaning": "dưới lòng đất",
    "ex1": "People underground enjoy fresh drinks during hot afternoons.",
    "ex1_vi": "Mọi người dưới lòng đất thưởng thức đồ uống tươi trong những buổi chiều nóng."
  },
  {
    "id": 169,
    "word": "sources",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔrsʌz/",
    "meaning": "nguồn",
    "ex1": "People learn about sources when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về nguồn khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 170,
    "word": "amounts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌmˈaʊnts/",
    "meaning": "lượng",
    "ex1": "It may contain small amounts of calcium, magnesium, and other useful minerals.",
    "ex1_vi": "Nó có thể chứa một lượng nhỏ canxi, magiê và các khoáng chất hữu ích khác."
  },
  {
    "id": 171,
    "word": "calcium",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈælsiʌm/",
    "meaning": "canxi",
    "ex1": "It may contain small amounts of calcium, magnesium, and other useful minerals.",
    "ex1_vi": "Nó có thể chứa một lượng nhỏ canxi, magiê và các khoáng chất hữu ích khác."
  },
  {
    "id": 172,
    "word": "magnesium",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mæɡˈniːziəm/",
    "meaning": "magiê",
    "ex1": "People discuss magnesium when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về magiê khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 173,
    "word": "other",
    "type": "determiner/adjective",
    "cat": "adj",
    "phonetic": "/ˈʌðɝ/",
    "meaning": "khác",
    "ex1": "People discuss other when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về khác khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 174,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈusfʌl/",
    "meaning": "hữu ích",
    "ex1": "People discuss useful when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về hữu ích khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 175,
    "word": "minerals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɪnɝʌlz/",
    "meaning": "khoáng chất",
    "ex1": "People discuss minerals when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về khoáng chất khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 176,
    "word": "carry",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈæri/",
    "meaning": "mang theo",
    "ex1": "People carry bottled water when they travel, exercise, study, or work outdoors.",
    "ex1_vi": "Mọi người mang nước đóng chai khi họ đi du lịch, tập thể dục, học tập hoặc làm việc ngoài trời."
  },
  {
    "id": 177,
    "word": "travel",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈævʌl/",
    "meaning": "đi du lịch",
    "ex1": "People carry bottled water when they travel, exercise, study, or work outdoors.",
    "ex1_vi": "Mọi người mang nước đóng chai khi họ đi du lịch, tập thể dục, học tập hoặc làm việc ngoài trời."
  },
  {
    "id": 178,
    "word": "exercise",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛksɝsˌaɪz/",
    "meaning": "tập thể dục",
    "ex1": "People discuss exercise when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về tập thể dục khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 179,
    "word": "study",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈʌdi/",
    "meaning": "học",
    "ex1": "People discuss study when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về học khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 180,
    "word": "outdoors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaʊtdˈɔrz/",
    "meaning": "ngoài trời",
    "ex1": "People discuss outdoors when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về ngoài trời khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 181,
    "word": "closed",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈoʊzd/",
    "meaning": "đóng kín",
    "ex1": "A closed bottle is easy to keep in a bag.",
    "ex1_vi": "Một chai đóng kín dễ giữ trong túi."
  },
  {
    "id": 182,
    "word": "bottle",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɑtʌl/",
    "meaning": "chai",
    "ex1": "A closed bottle is easy to keep in a bag.",
    "ex1_vi": "Một chai đóng kín dễ giữ trong túi."
  },
  {
    "id": 183,
    "word": "keep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈip/",
    "meaning": "giữ",
    "ex1": "People discuss keep when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về giữ khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 184,
    "word": "bag",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈæɡ/",
    "meaning": "túi",
    "ex1": "People discuss bag when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về túi khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 185,
    "word": "needs",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈidz/",
    "meaning": "cần",
    "ex1": "This drink needs naturally during simple preparation at home.",
    "ex1_vi": "Thức uống này cần một cách tự nhiên trong quá trình chuẩn bị đơn giản tại nhà."
  },
  {
    "id": 186,
    "word": "enough",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/ɪnˈʌf/",
    "meaning": "đủ",
    "ex1": "Enough drinks can be refreshing during hot Vietnamese afternoons.",
    "ex1_vi": "Đủ thức uống có thể sảng khoái trong những buổi chiều nóng ở Việt Nam."
  },
  {
    "id": 187,
    "word": "well",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈɛl/",
    "meaning": "tốt",
    "ex1": "People well enjoy fresh drinks during hot afternoons.",
    "ex1_vi": "Mọi người tốt thưởng thức đồ uống tươi trong những buổi chiều nóng."
  },
  {
    "id": 188,
    "word": "finishing",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɪnɪʃɪŋ/",
    "meaning": "dùng hết; hoàn thành",
    "ex1": "People learn about finishing when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về dùng hết; hoàn thành khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 189,
    "word": "recycling",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌriːˈsaɪklɪŋ/",
    "meaning": "tái chế",
    "ex1": "People enjoy recycling during simple drink preparation at home.",
    "ex1_vi": "Mọi người thích tái chế trong quá trình chuẩn bị đồ uống đơn giản tại nhà."
  },
  {
    "id": 190,
    "word": "bin",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɪn/",
    "meaning": "thùng",
    "ex1": "People learn about bin when discussing popular Vietnamese drinks.",
    "ex1_vi": "Mọi người học về thùng khi thảo luận các thức uống phổ biến ở Việt Nam."
  },
  {
    "id": 191,
    "word": "possible",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑsʌbʌl/",
    "meaning": "có thể",
    "ex1": "This drink is possible and pleasant on hot afternoons.",
    "ex1_vi": "Thức uống này có thể và dễ chịu vào những buổi chiều nóng."
  },
  {
    "id": 192,
    "word": "using",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈuzɪŋ/",
    "meaning": "sử dụng",
    "ex1": "Using a reusable bottle can also reduce plastic waste.",
    "ex1_vi": "Sử dụng chai tái sử dụng cũng có thể giảm rác thải nhựa."
  },
  {
    "id": 193,
    "word": "reusable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌriːˈjuːzəbəl/",
    "meaning": "tái sử dụng",
    "ex1": "Using a reusable bottle can also reduce plastic waste.",
    "ex1_vi": "Sử dụng chai tái sử dụng cũng có thể giảm rác thải nhựa."
  },
  {
    "id": 194,
    "word": "reduce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rʌdˈus/",
    "meaning": "giảm",
    "ex1": "People discuss reduce when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về giảm khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 195,
    "word": "plastic",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/plˈæstɪk/",
    "meaning": "nhựa",
    "ex1": "People discuss plastic when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về nhựa khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 196,
    "word": "waste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪst/",
    "meaning": "rác thải",
    "ex1": "People discuss waste when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về rác thải khi học về đồ uống lành mạnh hằng ngày."
  },
  {
    "id": 197,
    "word": "healthy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlθi/",
    "meaning": "lành mạnh",
    "ex1": "It is a healthy choice during every busy day.",
    "ex1_vi": "Đây là một lựa chọn lành mạnh trong mỗi ngày bận rộn."
  },
  {
    "id": 198,
    "word": "choice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɔɪs/",
    "meaning": "lựa chọn",
    "ex1": "It is a healthy choice during every busy day.",
    "ex1_vi": "Đây là một lựa chọn lành mạnh trong mỗi ngày bận rộn."
  },
  {
    "id": 199,
    "word": "busy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɪzi/",
    "meaning": "đông đúc; bận rộn",
    "ex1": "People discuss busy when learning about healthy daily drinks.",
    "ex1_vi": "Mọi người thảo luận về đông đúc; bận rộn khi học về đồ uống lành mạnh hằng ngày."
  }
];

const newReadingVocabOrder = [
  "fruit",
  "smoothies",
  "thick",
  "cold",
  "drinks",
  "made",
  "fresh",
  "vietnam",
  "popular",
  "include",
  "avocado",
  "mango",
  "strawberry",
  "banana",
  "and",
  "soursop",
  "make",
  "smoothie",
  "people",
  "put",
  "ice",
  "milk",
  "sugar",
  "blender",
  "machine",
  "mixes",
  "everything",
  "until",
  "becomes",
  "smooth",
  "common",
  "cafes",
  "juice",
  "shops",
  "family",
  "kitchens",
  "often",
  "served",
  "tall",
  "glasses",
  "straw",
  "spoon",
  "like",
  "because",
  "sweet",
  "creamy",
  "full",
  "flavor",
  "usually",
  "choose",
  "less",
  "more",
  "can",
  "tasty",
  "snack",
  "after",
  "school",
  "or",
  "work",
  "hot",
  "days",
  "when",
  "want",
  "something",
  "filling",
  "soy",
  "simple",
  "drink",
  "soybeans",
  "soak",
  "water",
  "grind",
  "cook",
  "liquid",
  "may",
  "added",
  "sweeter",
  "taste",
  "many",
  "breakfast",
  "sold",
  "schools",
  "markets",
  "bakeries",
  "small",
  "food",
  "stalls",
  "morning",
  "warm",
  "soft",
  "light",
  "comforting",
  "also",
  "provides",
  "protein",
  "body",
  "some",
  "sellers",
  "add",
  "pandan",
  "leaves",
  "sesame",
  "peanuts",
  "create",
  "different",
  "flavors",
  "smells",
  "gentle",
  "suitable",
  "both",
  "children",
  "adults",
  "fizzy",
  "easy",
  "find",
  "come",
  "such",
  "as",
  "cola",
  "orange",
  "lemon",
  "soda",
  "contain",
  "flavoring",
  "gas",
  "creates",
  "bubbles",
  "gives",
  "sharp",
  "feeling",
  "serve",
  "parties",
  "restaurants",
  "weddings",
  "celebrations",
  "enjoyed",
  "sometimes",
  "fast",
  "but",
  "try",
  "not",
  "have",
  "every",
  "day",
  "too",
  "much",
  "good",
  "health",
  "better",
  "daily",
  "choices",
  "still",
  "occasional",
  "glass",
  "fun",
  "refreshing",
  "bottled",
  "mineral",
  "clean",
  "convenient",
  "used",
  "across",
  "offices",
  "bus",
  "stations",
  "comes",
  "natural",
  "underground",
  "sources",
  "amounts",
  "calcium",
  "magnesium",
  "other",
  "useful",
  "minerals",
  "carry",
  "travel",
  "exercise",
  "study",
  "outdoors",
  "closed",
  "bottle",
  "keep",
  "bag",
  "needs",
  "enough",
  "well",
  "finishing",
  "recycling",
  "bin",
  "possible",
  "using",
  "reusable",
  "reduce",
  "plastic",
  "waste",
  "healthy",
  "choice",
  "busy"
];
