const newEssayData = [
  {
    "text": "1. Iced Tea – Trà đá\nIced tea is one of the most common drinks in Vietnam. It is simple, cheap, and easy to find in restaurants, cafés, and small food shops.\n\nThe drink is made by putting tea leaves in hot water. After the tea becomes strong, people add ice to make it cool and fresh.\n\nMany Vietnamese people drink iced tea with lunch or dinner. It helps them feel relaxed, especially on hot and sunny days.\n\nI like iced tea because it is light and not too sweet. It is also a friendly drink because people often enjoy it while talking with family or friends. It is perfect for sharing during a quiet afternoon.",
    "vi": "1. Trà đá\nTrà đá là một trong những thức uống phổ biến nhất ở Việt Nam. Nó đơn giản, rẻ và dễ tìm thấy ở nhà hàng, quán cà phê và các quán ăn nhỏ.\n\nThức uống này được pha bằng cách cho lá trà vào nước nóng. Sau khi trà trở nên đậm, người ta thêm đá để làm trà mát và tươi.\n\nNhiều người Việt Nam uống trà đá cùng bữa trưa hoặc bữa tối. Nó giúp họ cảm thấy thư giãn, đặc biệt vào những ngày nóng và nắng.\n\nTôi thích trà đá vì nó nhẹ và không quá ngọt. Đây cũng là một thức uống thân thiện vì mọi người thường thưởng thức nó khi trò chuyện với gia đình hoặc bạn bè. Nó rất phù hợp để cùng chia sẻ trong một buổi chiều yên tĩnh."
  },
  {
    "text": "2. Sugarcane Juice – Nước mía\nSugarcane juice is a popular street drink in Vietnam. It is sweet, cold, and very refreshing, especially during hot weather.\n\nTo make this drink, sellers put fresh sugarcane through a machine. The machine presses the cane and collects the juice in a cup.\n\nPeople often add ice, lime, or kumquat to improve the taste. Some shops also mix sugarcane juice with orange or pineapple.\n\nI enjoy sugarcane juice because it has a natural sweet flavor. However, I do not drink too much because it contains a lot of sugar. One cold glass is enough to make me feel fresh. It is also cheap and easy to buy on busy streets.",
    "vi": "2. Nước mía\nNước mía là một thức uống đường phố phổ biến ở Việt Nam. Nó ngọt, lạnh và rất sảng khoái, đặc biệt trong thời tiết nóng.\n\nĐể làm thức uống này, người bán cho mía tươi qua máy. Máy ép cây mía và hứng nước vào một chiếc cốc.\n\nMọi người thường thêm đá, chanh hoặc tắc để cải thiện hương vị. Một số cửa hàng cũng pha nước mía với cam hoặc dứa.\n\nTôi thích nước mía vì nó có vị ngọt tự nhiên. Tuy nhiên, tôi không uống quá nhiều vì nó chứa nhiều đường. Một ly lạnh là đủ để làm tôi cảm thấy sảng khoái. Nó cũng rẻ và dễ mua trên những con phố đông đúc."
  },
  {
    "text": "3. Coconut Water – Nước dừa\nCoconut water is a natural drink that is very popular in Vietnam. It comes from young green coconuts and has a light, sweet taste.\n\nSellers usually cut the top of the coconut and put in a straw. People can drink the water directly from the fruit.\n\nCoconut water is common at beaches, markets, cafés, and tourist places. It is especially enjoyable after exercise or outdoor activities.\n\nI like coconut water because it is fresh and simple. It also contains useful minerals that help the body. After drinking the water, people can eat the soft white coconut meat with a spoon. This makes the drink both useful and enjoyable for everyone.",
    "vi": "3. Nước dừa\nNước dừa là một thức uống tự nhiên rất phổ biến ở Việt Nam. Nó đến từ những quả dừa xanh non và có vị ngọt nhẹ.\n\nNgười bán thường cắt phần trên của quả dừa và cắm ống hút vào. Mọi người có thể uống nước trực tiếp từ quả.\n\nNước dừa phổ biến ở bãi biển, chợ, quán cà phê và các địa điểm du lịch. Nó đặc biệt thú vị sau khi tập thể dục hoặc hoạt động ngoài trời.\n\nTôi thích nước dừa vì nó tươi và đơn giản. Nó cũng chứa các khoáng chất hữu ích cho cơ thể. Sau khi uống nước, mọi người có thể ăn phần cơm dừa trắng mềm bằng thìa. Điều này làm cho thức uống vừa hữu ích vừa thú vị đối với mọi người."
  }
];
