const newEssayData = [
  {
    "text": "Chapter 7: Common Challenges During a Marathon\nRunning a marathon is not always easy. Many runners face physical and mental challenges during the race. They may feel tired, thirsty, or have sore muscles after many kilometers. Staying calm and focused helps them continue moving forward.\n\nSome runners experience leg cramps, blisters, or small injuries. Others feel nervous before the race or lose confidence during difficult moments. Regular training, proper stretching, and suitable running shoes can reduce these common problems and improve comfort.\n\nThe weather also affects marathon performance. Hot temperatures may cause dehydration, while rain and strong wind make running more difficult. Runners should check the weather forecast and wear suitable clothing before every race for better safety.\n\nEvery challenge teaches an important lesson. By staying patient and never giving up, runners become stronger in both body and mind. Each finished marathon builds confidence and prepares them for even greater goals ahead.",
    "vi": "Chương 7: Những thử thách thường gặp trong marathon\nChạy marathon không phải lúc nào cũng dễ. Nhiều người chạy đối mặt với thử thách thể chất và tinh thần trong cuộc đua. Họ có thể cảm thấy mệt, khát hoặc đau cơ sau nhiều ki-lô-mét. Giữ bình tĩnh và tập trung giúp họ tiếp tục tiến về phía trước.\n\nMột số người chạy bị chuột rút ở chân, phồng rộp hoặc chấn thương nhỏ. Những người khác cảm thấy lo lắng trước cuộc đua hoặc mất tự tin trong những khoảnh khắc khó khăn. Tập luyện đều đặn, giãn cơ đúng cách và giày chạy phù hợp có thể giảm những vấn đề thường gặp này và cải thiện sự thoải mái.\n\nThời tiết cũng ảnh hưởng đến thành tích marathon. Nhiệt độ cao có thể gây mất nước, trong khi mưa và gió mạnh làm cho việc chạy khó hơn. Người chạy nên kiểm tra dự báo thời tiết và mặc trang phục phù hợp trước mỗi cuộc đua để an toàn hơn.\n\nMỗi thử thách dạy một bài học quan trọng. Bằng cách kiên nhẫn và không bao giờ bỏ cuộc, người chạy trở nên mạnh hơn cả về thể chất lẫn tinh thần. Mỗi cuộc marathon hoàn thành xây dựng sự tự tin và chuẩn bị họ cho những mục tiêu lớn hơn phía trước."
  },
  {
    "text": "Chapter 8: Famous Marathon Races Around the World\nMany cities organize famous marathon races every year. These events welcome both professional athletes and amateur runners from many countries. They celebrate sports, friendship, and healthy living while bringing people together through the joy of running.\n\nThe Boston Marathon is one of the oldest and most respected races. The London Marathon is famous for its exciting atmosphere and charity activities. The Berlin Marathon is well known because many world records have been set there.\n\nThe New York City Marathon passes through all five boroughs and attracts thousands of runners and spectators. The Tokyo Marathon combines modern city life with excellent organization. Each race offers a special experience and unforgettable memories for every participant.\n\nThese famous marathons inspire millions of people to start running. They show that success comes from preparation, patience, and determination. Every runner, whether fast or slow, can enjoy the challenge and celebrate reaching the finish line together.",
    "vi": "Chương 8: Những cuộc marathon nổi tiếng trên thế giới\nNhiều thành phố tổ chức các cuộc marathon nổi tiếng mỗi năm. Những sự kiện này chào đón cả vận động viên chuyên nghiệp và người chạy nghiệp dư từ nhiều quốc gia. Chúng tôn vinh thể thao, tình bạn và lối sống lành mạnh đồng thời đưa mọi người đến gần nhau qua niềm vui chạy bộ.\n\nBoston Marathon là một trong những cuộc đua lâu đời và được kính trọng nhất. London Marathon nổi tiếng với bầu không khí hào hứng và các hoạt động từ thiện. Berlin Marathon được biết đến rộng rãi vì nhiều kỷ lục thế giới đã được thiết lập tại đó.\n\nNew York City Marathon đi qua cả năm quận và thu hút hàng nghìn người chạy cùng khán giả. Tokyo Marathon kết hợp cuộc sống thành phố hiện đại với tổ chức xuất sắc. Mỗi cuộc đua mang lại trải nghiệm đặc biệt và ký ức khó quên cho mỗi người tham gia.\n\nNhững cuộc marathon nổi tiếng này truyền cảm hứng cho hàng triệu người bắt đầu chạy. Chúng cho thấy thành công đến từ sự chuẩn bị, kiên nhẫn và quyết tâm. Mỗi người chạy, dù nhanh hay chậm, đều có thể tận hưởng thử thách và cùng ăn mừng việc chạm tới vạch đích."
  },
  {
    "text": "Chapter 9: Famous Marathon Races in Vietnam\nVietnam has many exciting marathon races every year. These events attract professional athletes, beginners, families, and international visitors. Beautiful landscapes, friendly volunteers, and local culture make each marathon a special experience for every runner and supporter.\n\nThe VnExpress Marathon is held in several famous cities across Vietnam. The Ho Chi Minh City International Marathon welcomes thousands of runners from many countries. The Da Nang International Marathon is popular because of its beautiful beaches and modern streets.\n\nThe Tien Phong Marathon is one of the oldest running events in Vietnam. The Mekong Delta Marathon allows runners to enjoy peaceful rivers, green rice fields, and warm local hospitality. Every race offers different challenges and unforgettable memories for participants.\n\nThese marathon events encourage healthy lifestyles and promote tourism across Vietnam. They inspire more people to exercise regularly, explore beautiful places, and achieve personal goals. Every runner can enjoy friendship, confidence, and the happiness of crossing the finish line together.",
    "vi": "Chương 9: Những cuộc marathon nổi tiếng ở Việt Nam\nViệt Nam có nhiều cuộc marathon hào hứng mỗi năm. Những sự kiện này thu hút vận động viên chuyên nghiệp, người mới bắt đầu, gia đình và du khách quốc tế. Cảnh quan đẹp, tình nguyện viên thân thiện và văn hóa địa phương làm cho mỗi cuộc marathon trở thành trải nghiệm đặc biệt đối với mỗi người chạy và người ủng hộ.\n\nVnExpress Marathon được tổ chức ở một số thành phố nổi tiếng trên khắp Việt Nam. Ho Chi Minh City International Marathon chào đón hàng nghìn người chạy từ nhiều quốc gia. Da Nang International Marathon phổ biến vì những bãi biển đẹp và đường phố hiện đại.\n\nTien Phong Marathon là một trong những sự kiện chạy lâu đời nhất ở Việt Nam. Mekong Delta Marathon cho phép người chạy tận hưởng những dòng sông yên bình, cánh đồng lúa xanh và lòng hiếu khách ấm áp của địa phương. Mỗi cuộc đua mang lại những thử thách khác nhau và ký ức khó quên cho người tham gia.\n\nNhững sự kiện marathon này khuyến khích lối sống lành mạnh và thúc đẩy du lịch trên khắp Việt Nam. Chúng truyền cảm hứng cho nhiều người tập thể dục đều đặn hơn, khám phá những nơi đẹp và đạt mục tiêu cá nhân. Mỗi người chạy có thể tận hưởng tình bạn, sự tự tin và niềm hạnh phúc khi cùng băng qua vạch đích."
  },
  {
    "text": "Chapter 10: The Benefits of Running and My Marathon Dream\nRunning is one of the best activities for a healthy life. It strengthens the heart, improves breathing, and helps control body weight. Regular running also reduces stress, increases energy, and helps people feel happier and more confident every day.\n\nMarathon training teaches many valuable life lessons. Runners learn patience, discipline, responsibility, and determination through every practice session. They understand that success comes from hard work, good preparation, and never giving up when challenges become difficult.\n\nMy dream is to complete a full marathon one day. I know the journey will require time, effort, and commitment. By training regularly, eating healthy food, and believing in myself, I can continue improving step by step toward my goal.\n\nEvery marathon begins with a single step. No matter your age or experience, you can start running today. Believe in yourself, enjoy the journey, and keep moving forward. Your next finish line may become your greatest achievement.",
    "vi": "Chương 10: Lợi ích của chạy bộ và ước mơ marathon của tôi\nChạy bộ là một trong những hoạt động tốt nhất cho cuộc sống khỏe mạnh. Nó làm tim khỏe hơn, cải thiện hô hấp và giúp kiểm soát cân nặng cơ thể. Chạy thường xuyên cũng giảm căng thẳng, tăng năng lượng và giúp mọi người cảm thấy vui vẻ, tự tin hơn mỗi ngày.\n\nTập marathon dạy nhiều bài học cuộc sống quý giá. Người chạy học sự kiên nhẫn, kỷ luật, trách nhiệm và quyết tâm qua mỗi buổi tập. Họ hiểu rằng thành công đến từ làm việc chăm chỉ, chuẩn bị tốt và không bao giờ bỏ cuộc khi thử thách trở nên khó khăn.\n\nƯớc mơ của tôi là hoàn thành một cuộc marathon đầy đủ vào một ngày nào đó. Tôi biết hành trình sẽ đòi hỏi thời gian, nỗ lực và cam kết. Bằng cách tập luyện đều đặn, ăn thực phẩm lành mạnh và tin vào bản thân, tôi có thể tiếp tục tiến bộ từng bước hướng tới mục tiêu.\n\nMỗi cuộc marathon bắt đầu bằng một bước đơn lẻ. Bất kể tuổi tác hay kinh nghiệm, bạn có thể bắt đầu chạy hôm nay. Hãy tin vào bản thân, tận hưởng hành trình và tiếp tục tiến về phía trước. Vạch đích tiếp theo có thể trở thành thành tựu lớn nhất của bạn."
  }
];
