const newEssayData = [
  {
    "text": "Chapter 1: What Is a Marathon?\nA marathon is a long-distance running race with an official distance of 42.195 kilometers. Every year, millions of people around the world join marathon events. Some runners compete for prizes, while many others simply enjoy finishing the race with personal pride.\n\nThe marathon has a long and interesting history. It is connected to ancient Greece and an old story about a brave messenger. Today, marathons are organized in many countries and welcome runners of different ages and abilities from around the world.\n\nRunning a marathon requires careful preparation. Most runners train for several months before race day. They gradually increase their distance, eat healthy meals, drink enough water, and get enough sleep. Good preparation helps improve strength, confidence, and overall performance.\n\nCompleting a marathon is a special achievement. It teaches patience, determination, and self-confidence. Every step brings runners closer to their goal, and crossing the finish line becomes an unforgettable moment that inspires future challenges.",
    "vi": "Chương 1: Marathon là gì?\nMarathon là một cuộc đua chạy đường dài với cự ly chính thức là 42,195 ki-lô-mét. Mỗi năm, hàng triệu người trên khắp thế giới tham gia các sự kiện marathon. Một số vận động viên thi đấu để giành giải thưởng, trong khi nhiều người khác đơn giản là tận hưởng niềm tự hào cá nhân khi hoàn thành cuộc đua.\n\nMarathon có một lịch sử lâu đời và thú vị. Nó gắn với Hy Lạp cổ đại và một câu chuyện xưa về một người đưa tin dũng cảm. Ngày nay, các cuộc marathon được tổ chức ở nhiều quốc gia và chào đón người chạy ở nhiều độ tuổi, năng lực khác nhau từ khắp thế giới.\n\nChạy marathon đòi hỏi sự chuẩn bị cẩn thận. Hầu hết người chạy tập luyện trong vài tháng trước ngày đua. Họ dần tăng cự ly, ăn các bữa lành mạnh, uống đủ nước và ngủ đủ giấc. Sự chuẩn bị tốt giúp cải thiện sức mạnh, sự tự tin và thành tích tổng thể.\n\nHoàn thành một cuộc marathon là một thành tựu đặc biệt. Nó dạy sự kiên nhẫn, quyết tâm và tự tin. Mỗi bước đưa người chạy đến gần mục tiêu hơn, và việc băng qua vạch đích trở thành một khoảnh khắc khó quên truyền cảm hứng cho những thử thách trong tương lai."
  },
  {
    "text": "Chapter 2: The History of the Marathon\nThe history of the marathon began in ancient Greece more than two thousand years ago. According to a famous story, a Greek messenger named Pheidippides ran from the town of Marathon to Athens after an important battle to deliver good news.\n\nAfter completing his long journey, the messenger announced the victory and then collapsed from exhaustion. Although historians still discuss some details, this story became a powerful symbol of courage, endurance, and determination throughout many generations around the world.\n\nThe modern marathon became an Olympic event in 1896 during the first modern Olympic Games. Later, the official distance was changed to 42.195 kilometers. Since then, marathon races have become more popular and are now held in many countries every year.\n\nToday, people run marathons for different reasons. Some athletes compete for medals and records, while many others run to improve their health, raise money for charity, or achieve an important personal goal through dedication.",
    "vi": "Chương 2: Lịch sử marathon\nLịch sử marathon bắt đầu ở Hy Lạp cổ đại hơn hai nghìn năm trước. Theo một câu chuyện nổi tiếng, một người đưa tin Hy Lạp tên Pheidippides đã chạy từ thị trấn Marathon đến Athens sau một trận chiến quan trọng để chuyển tin chiến thắng.\n\nSau khi hoàn thành hành trình dài, người đưa tin công bố chiến thắng rồi gục xuống vì kiệt sức. Mặc dù các nhà sử học vẫn tranh luận một số chi tiết, câu chuyện này đã trở thành biểu tượng mạnh mẽ của lòng dũng cảm, sức bền và quyết tâm qua nhiều thế hệ trên khắp thế giới.\n\nMarathon hiện đại trở thành một nội dung Olympic vào năm 1896 trong kỳ Thế vận hội Olympic hiện đại đầu tiên. Sau đó, cự ly chính thức được đổi thành 42,195 ki-lô-mét. Kể từ đó, các cuộc đua marathon trở nên phổ biến hơn và hiện được tổ chức ở nhiều quốc gia mỗi năm.\n\nNgày nay, mọi người chạy marathon vì nhiều lý do khác nhau. Một số vận động viên thi đấu để giành huy chương và lập kỷ lục, trong khi nhiều người khác chạy để cải thiện sức khỏe, gây quỹ từ thiện hoặc đạt một mục tiêu cá nhân quan trọng bằng sự tận tâm."
  },
  {
    "text": "Chapter 3: Preparing for Marathon Training\nTraining for a marathon takes time, patience, and planning. Most runners follow a training program for several months. They begin with short runs and slowly increase the distance each week. Regular practice helps improve strength, endurance, and overall fitness.\n\nA good training plan includes running, strength exercises, stretching, and rest days. Long runs build endurance, while shorter runs improve speed. Rest is also important because it allows muscles to recover and reduces the risk of injury during training.\n\nHealthy eating and enough water are essential before every workout. Runners should eat balanced meals with carbohydrates, protein, fruit, and vegetables. Getting enough sleep every night also helps the body recover faster and prepares runners for the next training session.\n\nMental preparation is just as important as physical training. Runners should set realistic goals, stay positive, and never give up when training becomes difficult. With patience, discipline, and consistent practice, anyone can prepare successfully for a marathon and enjoy the journey.",
    "vi": "Chương 3: Chuẩn bị cho quá trình tập marathon\nTập luyện cho marathon cần thời gian, sự kiên nhẫn và kế hoạch. Hầu hết người chạy theo một chương trình tập luyện trong vài tháng. Họ bắt đầu bằng những quãng chạy ngắn rồi từ từ tăng cự ly mỗi tuần. Việc luyện tập đều đặn giúp cải thiện sức mạnh, sức bền và thể lực tổng thể.\n\nMột kế hoạch tập tốt gồm chạy, bài tập sức mạnh, giãn cơ và ngày nghỉ. Những buổi chạy dài xây dựng sức bền, trong khi những buổi chạy ngắn hơn cải thiện tốc độ. Nghỉ ngơi cũng quan trọng vì nó cho phép cơ bắp hồi phục và giảm nguy cơ chấn thương trong quá trình tập.\n\nĂn uống lành mạnh và đủ nước là điều thiết yếu trước mỗi buổi tập. Người chạy nên ăn các bữa cân bằng với carbohydrate, protein, trái cây và rau. Ngủ đủ mỗi đêm cũng giúp cơ thể hồi phục nhanh hơn và chuẩn bị người chạy cho buổi tập tiếp theo.\n\nChuẩn bị tinh thần cũng quan trọng như luyện tập thể chất. Người chạy nên đặt mục tiêu thực tế, giữ thái độ tích cực và không bao giờ bỏ cuộc khi việc tập luyện trở nên khó khăn. Với sự kiên nhẫn, kỷ luật và luyện tập nhất quán, bất kỳ ai cũng có thể chuẩn bị thành công cho marathon và tận hưởng hành trình."
  }
];
