const lessonVocabularyWords = [
  "life",
  "farm",
  "animals",
  "help",
  "people",
  "many",
  "ways",
  "every",
  "day",
  "cows",
  "give",
  "milk",
  "chickens",
  "lay",
  "eggs",
  "and",
  "sheep",
  "provide",
  "wool",
  "farmers",
  "have",
  "feed",
  "before",
  "sunrise",
  "must",
  "keep",
  "barns",
  "clean",
  "last",
  "spring",
  "young",
  "born",
  "local",
  "farms",
  "visitors",
  "enjoyed",
  "watching",
  "play",
  "fields",
  "after",
  "breakfast",
  "water",
  "fresh",
  "food",
  "helped",
  "animal",
  "grow",
  "strong",
  "healthy",
  "always",
  "treat",
  "kindly",
  "never",
  "frighten",
  "if",
  "care",
  "well",
  "will",
  "produce",
  "better",
  "everyone",
  "benefit",
  "hard",
  "work",
  "sea",
  "live",
  "oceans",
  "seas",
  "around",
  "world",
  "dolphins",
  "turtles",
  "whales",
  "octopuses",
  "among",
  "most",
  "amazing",
  "creatures",
  "look",
  "group",
  "swimming",
  "boat",
  "can",
  "stay",
  "underwater",
  "long",
  "time",
  "scientists",
  "already",
  "discovered",
  "thousands",
  "species",
  "but",
  "others",
  "still",
  "remain",
  "unknown",
  "year",
  "rare",
  "turtle",
  "rescued",
  "returned",
  "ocean",
  "safely",
  "survive",
  "should",
  "reduce",
  "plastic",
  "waste",
  "protect",
  "marine",
  "works",
  "together",
  "enjoy",
  "cleaner",
  "waters",
  "safer",
  "habitats",
  "future",
  "birds",
  "sky",
  "different",
  "forests",
  "busy",
  "cities",
  "eagles",
  "parrots",
  "owls",
  "sparrows",
  "colors",
  "sizes",
  "flying",
  "skills",
  "several",
  "building",
  "new",
  "nest",
  "tall",
  "tree",
  "today",
  "autumn",
  "traveled",
  "kilometers",
  "find",
  "warmer",
  "places",
  "flew",
  "because",
  "journey",
  "difficult",
  "next",
  "going",
  "return",
  "original",
  "homes",
  "again",
  "trees",
  "need",
  "safe",
  "rest",
  "continue",
  "filling",
  "beautiful",
  "songs",
  "season"
];

const newVocabData = [
  {
    "id": 1,
    "word": "life",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪf/",
    "meaning": "cuộc sống",
    "ex1": "People should reduce plastic waste and protect marine life.",
    "ex1_vi": "Mọi người nên giảm rác thải nhựa và bảo vệ sinh vật biển."
  },
  {
    "id": 2,
    "word": "farm",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɑrm/",
    "meaning": "nông trại",
    "ex1": "Farm animals help people in many ways every day.",
    "ex1_vi": "Động vật nông trại giúp con người theo nhiều cách mỗi ngày."
  },
  {
    "id": 3,
    "word": "animals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈænʌmʌlz/",
    "meaning": "động vật",
    "ex1": "Farm animals help people in many ways every day.",
    "ex1_vi": "Động vật nông trại giúp con người theo nhiều cách mỗi ngày."
  },
  {
    "id": 4,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "sự giúp đỡ; giúp",
    "ex1": "People can help animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể sự giúp đỡ; giúp động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 5,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "Students discuss people during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về mọi người trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 6,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Students discuss many during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về nhiều trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 7,
    "word": "ways",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪz/",
    "meaning": "cách",
    "ex1": "Students discuss ways during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cách trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 8,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɝi/",
    "meaning": "mỗi",
    "ex1": "Every animals need clean water and safe natural habitats.",
    "ex1_vi": "Mỗi động vật cần nước sạch và môi trường sống tự nhiên an toàn."
  },
  {
    "id": 9,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "Students discuss day during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về ngày trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 10,
    "word": "cows",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈaʊz/",
    "meaning": "bò",
    "ex1": "Cows give milk, chickens lay eggs, and sheep provide wool.",
    "ex1_vi": "Bò cho sữa, gà đẻ trứng và cừu cung cấp len."
  },
  {
    "id": 11,
    "word": "give",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪv/",
    "meaning": "cho",
    "ex1": "Cows give milk, chickens lay eggs, and sheep provide wool.",
    "ex1_vi": "Bò cho sữa, gà đẻ trứng và cừu cung cấp len."
  },
  {
    "id": 12,
    "word": "milk",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɪlk/",
    "meaning": "sữa",
    "ex1": "Students discuss milk during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về sữa trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 13,
    "word": "chickens",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪkʌnz/",
    "meaning": "gà",
    "ex1": "Students discuss chickens during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về gà trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 14,
    "word": "lay",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈeɪ/",
    "meaning": "đẻ",
    "ex1": "Students discuss lay during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đẻ trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 15,
    "word": "eggs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛɡz/",
    "meaning": "trứng",
    "ex1": "Students discuss eggs during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về trứng trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 16,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Always treat farm animals kindly and never frighten them.",
    "ex1_vi": "Luôn đối xử tử tế với động vật nông trại và đừng bao giờ làm chúng hoảng sợ."
  },
  {
    "id": 17,
    "word": "sheep",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈip/",
    "meaning": "cừu",
    "ex1": "Students discuss sheep during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cừu trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 18,
    "word": "provide",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌvˈaɪd/",
    "meaning": "cung cấp",
    "ex1": "Students discuss provide during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cung cấp trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 19,
    "word": "wool",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈʊl/",
    "meaning": "len",
    "ex1": "Students discuss wool during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về len trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 20,
    "word": "farmers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɑrmɝz/",
    "meaning": "nông dân",
    "ex1": "People discuss farmers during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về nông dân trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 21,
    "word": "have",
    "type": "verb/auxiliary",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có; phải trong have to",
    "ex1": "Eagles, parrots, owls, and sparrows have different colors, sizes, and flying skills.",
    "ex1_vi": "Đại bàng, vẹt, cú và chim sẻ có màu sắc, kích thước và kỹ năng bay khác nhau."
  },
  {
    "id": 22,
    "word": "feed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈid/",
    "meaning": "cho ăn",
    "ex1": "People can feed animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể cho ăn động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 23,
    "word": "before",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/bɪfˈɔr/",
    "meaning": "trước",
    "ex1": "Students use before in simple sentences about animal life.",
    "ex1_vi": "Học sinh dùng “before” trong những câu đơn giản về đời sống động vật."
  },
  {
    "id": 24,
    "word": "sunrise",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈʌnrˌaɪz/",
    "meaning": "bình minh",
    "ex1": "Students learn about sunrise when studying wild animals.",
    "ex1_vi": "Học sinh học về bình minh khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 25,
    "word": "must",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈʌst/",
    "meaning": "phải",
    "ex1": "People must protect rare animals from serious danger.",
    "ex1_vi": "Con người phải bảo vệ động vật quý hiếm khỏi nguy hiểm nghiêm trọng."
  },
  {
    "id": 26,
    "word": "keep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈip/",
    "meaning": "giữ",
    "ex1": "Animals keep together when their habitats remain safe.",
    "ex1_vi": "Động vật giữ cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 27,
    "word": "barns",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɑrnz/",
    "meaning": "chuồng trại",
    "ex1": "Students learn about barns when studying wild animals.",
    "ex1_vi": "Học sinh học về chuồng trại khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 28,
    "word": "clean",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈin/",
    "meaning": "sạch",
    "ex1": "Clean water and fresh food helped every animal grow strong and healthy.",
    "ex1_vi": "Nước sạch và thức ăn tươi giúp mọi con vật phát triển khỏe mạnh."
  },
  {
    "id": 29,
    "word": "last",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈæst/",
    "meaning": "trước; vừa qua",
    "ex1": "Last spring, many young animals were born on local farms.",
    "ex1_vi": "Mùa xuân năm ngoái, nhiều động vật non được sinh ra ở các trang trại địa phương."
  },
  {
    "id": 30,
    "word": "spring",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sprˈɪŋ/",
    "meaning": "mùa xuân",
    "ex1": "Last spring, many young animals were born on local farms.",
    "ex1_vi": "Mùa xuân năm ngoái, nhiều động vật non được sinh ra ở các trang trại địa phương."
  },
  {
    "id": 31,
    "word": "young",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈʌŋ/",
    "meaning": "non; trẻ",
    "ex1": "Students discuss young during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về non; trẻ trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 32,
    "word": "born",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɔrn/",
    "meaning": "được sinh ra",
    "ex1": "Students discuss born during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về được sinh ra trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 33,
    "word": "local",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈoʊkʌl/",
    "meaning": "địa phương",
    "ex1": "Students discuss local during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về địa phương trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 34,
    "word": "farms",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɑrmz/",
    "meaning": "nông trại",
    "ex1": "Students discuss farms during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về nông trại trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 35,
    "word": "visitors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪzɪtɝz/",
    "meaning": "du khách",
    "ex1": "Visitors enjoyed watching them play in the fields after breakfast.",
    "ex1_vi": "Du khách thích ngắm chúng chơi trên cánh đồng sau bữa sáng."
  },
  {
    "id": 36,
    "word": "enjoyed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪd/",
    "meaning": "đã thích",
    "ex1": "Visitors enjoyed watching them play in the fields after breakfast.",
    "ex1_vi": "Du khách thích ngắm chúng chơi trên cánh đồng sau bữa sáng."
  },
  {
    "id": 37,
    "word": "watching",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɑtʃɪŋ/",
    "meaning": "việc ngắm",
    "ex1": "Students discuss watching during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về việc ngắm trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 38,
    "word": "play",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪ/",
    "meaning": "chơi",
    "ex1": "Students discuss play during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về chơi trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 39,
    "word": "fields",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈildz/",
    "meaning": "cánh đồng",
    "ex1": "Students discuss fields during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cánh đồng trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 40,
    "word": "after",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/ˈæftɝ/",
    "meaning": "sau",
    "ex1": "Students discuss after during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về sau trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 41,
    "word": "breakfast",
    "type": "noun",
    "cat": "n",
    "phonetic": "/brˈɛkfʌst/",
    "meaning": "bữa sáng",
    "ex1": "Students discuss breakfast during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về bữa sáng trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 42,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước",
    "ex1": "Clean water and fresh food helped every animal grow strong and healthy.",
    "ex1_vi": "Nước sạch và thức ăn tươi giúp mọi con vật phát triển khỏe mạnh."
  },
  {
    "id": 43,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi",
    "ex1": "Students discuss fresh during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về tươi trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 44,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thức ăn",
    "ex1": "Students discuss food during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về thức ăn trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 45,
    "word": "helped",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlpt/",
    "meaning": "đã giúp",
    "ex1": "Students discuss helped during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đã giúp trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 46,
    "word": "animal",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈænʌmʌl/",
    "meaning": "động vật",
    "ex1": "Healthy habitats provide animal for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp động vật cho động vật trên khắp thế giới."
  },
  {
    "id": 47,
    "word": "grow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡrˈoʊ/",
    "meaning": "lớn lên",
    "ex1": "Students discuss grow during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về lớn lên trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 48,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋ/",
    "meaning": "khỏe mạnh",
    "ex1": "Students discuss strong during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về khỏe mạnh trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 49,
    "word": "healthy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlθi/",
    "meaning": "khỏe mạnh",
    "ex1": "A healthy animal can survive in a protected area.",
    "ex1_vi": "Một động vật khỏe mạnh có thể sống sót trong khu vực được bảo vệ."
  },
  {
    "id": 50,
    "word": "always",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlwˌeɪz/",
    "meaning": "luôn luôn",
    "ex1": "Always treat farm animals kindly and never frighten them.",
    "ex1_vi": "Luôn đối xử tử tế với động vật nông trại và đừng bao giờ làm chúng hoảng sợ."
  },
  {
    "id": 51,
    "word": "treat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/trˈit/",
    "meaning": "đối xử",
    "ex1": "Students discuss treat during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đối xử trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 52,
    "word": "kindly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈaɪndli/",
    "meaning": "tử tế",
    "ex1": "Students discuss kindly during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về tử tế trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 53,
    "word": "never",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɛvɝ/",
    "meaning": "không bao giờ",
    "ex1": "Students discuss never during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về không bao giờ trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 54,
    "word": "frighten",
    "type": "verb",
    "cat": "v",
    "phonetic": "/frˈaɪtʌn/",
    "meaning": "làm hoảng sợ",
    "ex1": "Students discuss frighten during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về làm hoảng sợ trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 55,
    "word": "if",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɪf/",
    "meaning": "nếu",
    "ex1": "If people protect nature, animals can live safely.",
    "ex1_vi": "Nếu con người bảo vệ thiên nhiên, động vật có thể sống an toàn."
  },
  {
    "id": 56,
    "word": "care",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɛr/",
    "meaning": "chăm sóc",
    "ex1": "People discuss care during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về chăm sóc trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 57,
    "word": "well",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈɛl/",
    "meaning": "tốt",
    "ex1": "Animals well live together in protected natural areas.",
    "ex1_vi": "Động vật tốt sống cùng nhau trong các khu vực tự nhiên được bảo vệ."
  },
  {
    "id": 58,
    "word": "will",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/wˈɪl/",
    "meaning": "sẽ",
    "ex1": "Healthy habitats will help animals survive for years.",
    "ex1_vi": "Môi trường sống khỏe mạnh sẽ giúp động vật tồn tại nhiều năm."
  },
  {
    "id": 59,
    "word": "produce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌdˈus/",
    "meaning": "sản xuất",
    "ex1": "Animals produce together when their habitats remain safe.",
    "ex1_vi": "Động vật sản xuất cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 60,
    "word": "better",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/bˈɛtɝ/",
    "meaning": "tốt hơn",
    "ex1": "Animals better live together in protected natural areas.",
    "ex1_vi": "Động vật tốt hơn sống cùng nhau trong các khu vực tự nhiên được bảo vệ."
  },
  {
    "id": 61,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvriwˌʌn/",
    "meaning": "mọi người",
    "ex1": "Healthy habitats provide everyone for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp mọi người cho động vật trên khắp thế giới."
  },
  {
    "id": 62,
    "word": "benefit",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɛnʌfɪt/",
    "meaning": "hưởng lợi",
    "ex1": "Animals benefit together when their habitats remain safe.",
    "ex1_vi": "Động vật hưởng lợi cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 63,
    "word": "hard",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑrd/",
    "meaning": "vất vả",
    "ex1": "These animals are hard and need safe habitats.",
    "ex1_vi": "Những động vật này vất vả và cần môi trường sống an toàn."
  },
  {
    "id": 64,
    "word": "work",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝk/",
    "meaning": "làm việc",
    "ex1": "People can work animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể làm việc động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 65,
    "word": "sea",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈi/",
    "meaning": "biển",
    "ex1": "Sea animals live in oceans and seas around the world.",
    "ex1_vi": "Động vật biển sống trong các đại dương và vùng biển trên khắp thế giới."
  },
  {
    "id": 66,
    "word": "live",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈaɪv/",
    "meaning": "sống",
    "ex1": "Sea animals live in oceans and seas around the world.",
    "ex1_vi": "Động vật biển sống trong các đại dương và vùng biển trên khắp thế giới."
  },
  {
    "id": 67,
    "word": "oceans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈoʊʃʌnz/",
    "meaning": "đại dương",
    "ex1": "Healthy habitats provide oceans for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp đại dương cho động vật trên khắp thế giới."
  },
  {
    "id": 68,
    "word": "seas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈiz/",
    "meaning": "các vùng biển",
    "ex1": "Students discuss seas during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về các vùng biển trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 69,
    "word": "around",
    "type": "adverb/preposition",
    "cat": "adv",
    "phonetic": "/ɝˈaʊnd/",
    "meaning": "khắp; xung quanh",
    "ex1": "Students discuss around during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về khắp; xung quanh trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 70,
    "word": "world",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝld/",
    "meaning": "thế giới",
    "ex1": "Students discuss world during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về thế giới trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 71,
    "word": "dolphins",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɑlfʌnz/",
    "meaning": "cá heo",
    "ex1": "A group of dolphins is swimming near a boat.",
    "ex1_vi": "Một đàn cá heo đang bơi gần một chiếc thuyền."
  },
  {
    "id": 72,
    "word": "turtles",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɝtʌlz/",
    "meaning": "rùa",
    "ex1": "Dolphins, turtles, whales, and octopuses are among the most amazing creatures.",
    "ex1_vi": "Cá heo, rùa, cá voi và bạch tuộc là những sinh vật tuyệt vời nhất."
  },
  {
    "id": 73,
    "word": "whales",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪlz/",
    "meaning": "cá voi",
    "ex1": "Dolphins, turtles, whales, and octopuses are among the most amazing creatures.",
    "ex1_vi": "Cá heo, rùa, cá voi và bạch tuộc là những sinh vật tuyệt vời nhất."
  },
  {
    "id": 74,
    "word": "octopuses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɒktəpʊsɪz/",
    "meaning": "bạch tuộc",
    "ex1": "Students discuss octopuses during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về bạch tuộc trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 75,
    "word": "among",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ʌmˈʌŋ/",
    "meaning": "trong số",
    "ex1": "Students discuss among during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về trong số trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 76,
    "word": "most",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈoʊst/",
    "meaning": "nhất",
    "ex1": "Students discuss most during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về nhất trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 77,
    "word": "amazing",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌmˈeɪzɪŋ/",
    "meaning": "tuyệt vời",
    "ex1": "Students discuss amazing during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về tuyệt vời trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 78,
    "word": "creatures",
    "type": "noun",
    "cat": "n",
    "phonetic": "/krˈitʃɝz/",
    "meaning": "sinh vật",
    "ex1": "Students discuss creatures during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về sinh vật trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 79,
    "word": "look",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊk/",
    "meaning": "nhìn",
    "ex1": "People can look animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể nhìn động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 80,
    "word": "group",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡrˈup/",
    "meaning": "nhóm; đàn",
    "ex1": "A group of dolphins is swimming near a boat.",
    "ex1_vi": "Một đàn cá heo đang bơi gần một chiếc thuyền."
  },
  {
    "id": 81,
    "word": "swimming",
    "type": "verb",
    "cat": "v",
    "phonetic": "/swˈɪmɪŋ/",
    "meaning": "đang bơi",
    "ex1": "Students discuss swimming during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đang bơi trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 82,
    "word": "boat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈoʊt/",
    "meaning": "thuyền",
    "ex1": "Students discuss boat during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về thuyền trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 83,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Many sea animals can stay underwater for a long time.",
    "ex1_vi": "Nhiều loài động vật biển có thể ở dưới nước trong thời gian dài."
  },
  {
    "id": 84,
    "word": "stay",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈeɪ/",
    "meaning": "ở; sống",
    "ex1": "Many sea animals can stay underwater for a long time.",
    "ex1_vi": "Nhiều loài động vật biển có thể ở dưới nước trong thời gian dài."
  },
  {
    "id": 85,
    "word": "underwater",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˌʌndərˈwɔːtər/",
    "meaning": "dưới nước",
    "ex1": "Students discuss underwater during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về dưới nước trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 86,
    "word": "long",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɔŋ/",
    "meaning": "dài",
    "ex1": "Students discuss long during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về dài trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 87,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "Students discuss time during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về thời gian trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 88,
    "word": "scientists",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaɪʌntɪsts/",
    "meaning": "nhà khoa học",
    "ex1": "Healthy habitats provide scientists for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp nhà khoa học cho động vật trên khắp thế giới."
  },
  {
    "id": 89,
    "word": "already",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɔlrˈɛdi/",
    "meaning": "đã",
    "ex1": "Wild animals already find food in healthy habitats.",
    "ex1_vi": "Động vật hoang dã đã tìm thức ăn trong môi trường sống khỏe mạnh."
  },
  {
    "id": 90,
    "word": "discovered",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dɪskˈʌvɝd/",
    "meaning": "đã khám phá",
    "ex1": "Wild animals discovered safely in healthy natural habitats.",
    "ex1_vi": "Động vật hoang dã đã khám phá an toàn trong môi trường sống tự nhiên khỏe mạnh."
  },
  {
    "id": 91,
    "word": "thousands",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈaʊzʌndz/",
    "meaning": "hàng nghìn",
    "ex1": "Last autumn, many birds traveled thousands of kilometers to find warmer places.",
    "ex1_vi": "Mùa thu năm ngoái, nhiều con chim đã bay hàng nghìn kilômét để tìm nơi ấm hơn."
  },
  {
    "id": 92,
    "word": "species",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈiʃiz/",
    "meaning": "loài",
    "ex1": "People discuss species during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về loài trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 93,
    "word": "but",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bˈʌt/",
    "meaning": "nhưng",
    "ex1": "Students use but in simple sentences about animal life.",
    "ex1_vi": "Học sinh dùng “but” trong những câu đơn giản về đời sống động vật."
  },
  {
    "id": 94,
    "word": "others",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈʌðɝz/",
    "meaning": "những loài/người khác",
    "ex1": "Healthy habitats provide others for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp những loài/người khác cho động vật trên khắp thế giới."
  },
  {
    "id": 95,
    "word": "still",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/stˈɪl/",
    "meaning": "vẫn",
    "ex1": "Wild animals still find food in healthy habitats.",
    "ex1_vi": "Động vật hoang dã vẫn tìm thức ăn trong môi trường sống khỏe mạnh."
  },
  {
    "id": 96,
    "word": "remain",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪmˈeɪn/",
    "meaning": "vẫn còn",
    "ex1": "Wild animals remain safely in healthy natural habitats.",
    "ex1_vi": "Động vật hoang dã vẫn còn an toàn trong môi trường sống tự nhiên khỏe mạnh."
  },
  {
    "id": 97,
    "word": "unknown",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌnnˈoʊn/",
    "meaning": "chưa biết",
    "ex1": "A unknown animal can survive in a protected area.",
    "ex1_vi": "Một động vật chưa biết có thể sống sót trong khu vực được bảo vệ."
  },
  {
    "id": 98,
    "word": "year",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈɪr/",
    "meaning": "năm",
    "ex1": "People discuss year during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về năm trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 99,
    "word": "rare",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛr/",
    "meaning": "quý hiếm",
    "ex1": "These animals are rare and need safe habitats.",
    "ex1_vi": "Những động vật này quý hiếm và cần môi trường sống an toàn."
  },
  {
    "id": 100,
    "word": "turtle",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɝtʌl/",
    "meaning": "rùa",
    "ex1": "Healthy habitats provide turtle for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp rùa cho động vật trên khắp thế giới."
  },
  {
    "id": 101,
    "word": "rescued",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛskjud/",
    "meaning": "được cứu hộ",
    "ex1": "People want wildlife habitats to remain rescued and safe.",
    "ex1_vi": "Con người muốn môi trường sống hoang dã vẫn được cứu hộ và an toàn."
  },
  {
    "id": 102,
    "word": "returned",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪtˈɝnd/",
    "meaning": "được đưa trở lại",
    "ex1": "Wild animals returned safely in healthy natural habitats.",
    "ex1_vi": "Động vật hoang dã được đưa trở lại an toàn trong môi trường sống tự nhiên khỏe mạnh."
  },
  {
    "id": 103,
    "word": "ocean",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈoʊʃʌn/",
    "meaning": "đại dương",
    "ex1": "Healthy habitats provide ocean for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp đại dương cho động vật trên khắp thế giới."
  },
  {
    "id": 104,
    "word": "safely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sˈeɪfli/",
    "meaning": "an toàn",
    "ex1": "Wild animals safely find food in healthy habitats.",
    "ex1_vi": "Động vật hoang dã an toàn tìm thức ăn trong môi trường sống khỏe mạnh."
  },
  {
    "id": 105,
    "word": "survive",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sɝvˈaɪv/",
    "meaning": "sống sót",
    "ex1": "Wild animals survive safely in healthy natural habitats.",
    "ex1_vi": "Động vật hoang dã sống sót an toàn trong môi trường sống tự nhiên khỏe mạnh."
  },
  {
    "id": 106,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "People should reduce plastic waste and protect marine life.",
    "ex1_vi": "Mọi người nên giảm rác thải nhựa và bảo vệ sinh vật biển."
  },
  {
    "id": 107,
    "word": "reduce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rʌdˈus/",
    "meaning": "giảm",
    "ex1": "Students discuss reduce during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về giảm trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 108,
    "word": "plastic",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/plˈæstɪk/",
    "meaning": "nhựa",
    "ex1": "Students discuss plastic during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về nhựa trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 109,
    "word": "waste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪst/",
    "meaning": "rác thải",
    "ex1": "Students discuss waste during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về rác thải trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 110,
    "word": "protect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌtˈɛkt/",
    "meaning": "bảo vệ",
    "ex1": "Students discuss protect during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về bảo vệ trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 111,
    "word": "marine",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mɝˈin/",
    "meaning": "thuộc biển",
    "ex1": "Students discuss marine during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về thuộc biển trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 112,
    "word": "works",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝks/",
    "meaning": "làm việc",
    "ex1": "People can works animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể làm việc động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 113,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌɡˈɛðɝ/",
    "meaning": "cùng nhau",
    "ex1": "They flew together because the journey was long and difficult.",
    "ex1_vi": "Chúng bay cùng nhau vì hành trình dài và khó khăn."
  },
  {
    "id": 114,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thích; thưởng thức",
    "ex1": "Wild animals enjoy safely in healthy natural habitats.",
    "ex1_vi": "Động vật hoang dã thích; thưởng thức an toàn trong môi trường sống tự nhiên khỏe mạnh."
  },
  {
    "id": 115,
    "word": "cleaner",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈinɝ/",
    "meaning": "sạch hơn",
    "ex1": "A cleaner animal can survive in a protected area.",
    "ex1_vi": "Một động vật sạch hơn có thể sống sót trong khu vực được bảo vệ."
  },
  {
    "id": 116,
    "word": "waters",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝz/",
    "meaning": "vùng nước",
    "ex1": "People discuss waters during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về vùng nước trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 117,
    "word": "safer",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪfɝ/",
    "meaning": "an toàn hơn",
    "ex1": "These animals are safer and need safe habitats.",
    "ex1_vi": "Những động vật này an toàn hơn và cần môi trường sống an toàn."
  },
  {
    "id": 118,
    "word": "habitats",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈhæbɪtæts/",
    "meaning": "môi trường sống",
    "ex1": "Birds live in many different habitats, from forests to busy cities.",
    "ex1_vi": "Chim sống ở nhiều môi trường sống khác nhau, từ rừng đến các thành phố bận rộn."
  },
  {
    "id": 119,
    "word": "future",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fjˈutʃɝ/",
    "meaning": "tương lai",
    "ex1": "People discuss future during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về tương lai trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 120,
    "word": "birds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɝdz/",
    "meaning": "chim",
    "ex1": "Birds live in many different habitats, from forests to busy cities.",
    "ex1_vi": "Chim sống ở nhiều môi trường sống khác nhau, từ rừng đến các thành phố bận rộn."
  },
  {
    "id": 121,
    "word": "sky",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈaɪ/",
    "meaning": "bầu trời",
    "ex1": "Healthy habitats provide sky for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp bầu trời cho động vật trên khắp thế giới."
  },
  {
    "id": 122,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "Students discuss different during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về khác nhau trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 123,
    "word": "forests",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɔrʌsts/",
    "meaning": "rừng",
    "ex1": "Students discuss forests during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về rừng trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 124,
    "word": "busy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɪzi/",
    "meaning": "bận rộn",
    "ex1": "Students discuss busy during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về bận rộn trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 125,
    "word": "cities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪtiz/",
    "meaning": "thành phố",
    "ex1": "Students discuss cities during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về thành phố trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 126,
    "word": "eagles",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈiɡʌlz/",
    "meaning": "đại bàng",
    "ex1": "Eagles, parrots, owls, and sparrows have different colors, sizes, and flying skills.",
    "ex1_vi": "Đại bàng, vẹt, cú và chim sẻ có màu sắc, kích thước và kỹ năng bay khác nhau."
  },
  {
    "id": 127,
    "word": "parrots",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɛrʌts/",
    "meaning": "vẹt",
    "ex1": "Students discuss parrots during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về vẹt trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 128,
    "word": "owls",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaʊlz/",
    "meaning": "cú",
    "ex1": "Students discuss owls during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cú trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 129,
    "word": "sparrows",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈɛroʊz/",
    "meaning": "chim sẻ",
    "ex1": "Students discuss sparrows during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về chim sẻ trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 130,
    "word": "colors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌlɝz/",
    "meaning": "màu sắc",
    "ex1": "Students discuss colors during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về màu sắc trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 131,
    "word": "sizes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaɪzʌz/",
    "meaning": "kích thước",
    "ex1": "Students discuss sizes during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về kích thước trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 132,
    "word": "flying",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/flˈaɪɪŋ/",
    "meaning": "bay",
    "ex1": "Students discuss flying during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về bay trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 133,
    "word": "skills",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪlz/",
    "meaning": "kỹ năng",
    "ex1": "Students discuss skills during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về kỹ năng trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 134,
    "word": "several",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈɛvrʌl/",
    "meaning": "một số",
    "ex1": "Several birds are building a new nest in a tall tree today.",
    "ex1_vi": "Một số con chim đang xây một chiếc tổ mới trên cây cao hôm nay."
  },
  {
    "id": 135,
    "word": "building",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɪldɪŋ/",
    "meaning": "đang xây",
    "ex1": "Several birds are building a new nest in a tall tree today.",
    "ex1_vi": "Một số con chim đang xây một chiếc tổ mới trên cây cao hôm nay."
  },
  {
    "id": 136,
    "word": "new",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈu/",
    "meaning": "mới",
    "ex1": "Students discuss new during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về mới trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 137,
    "word": "nest",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈɛst/",
    "meaning": "tổ",
    "ex1": "Students discuss nest during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về tổ trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 138,
    "word": "tall",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈɔl/",
    "meaning": "cao",
    "ex1": "Students discuss tall during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cao trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 139,
    "word": "tree",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈi/",
    "meaning": "cây",
    "ex1": "Students discuss tree during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cây trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 140,
    "word": "today",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌdˈeɪ/",
    "meaning": "hôm nay",
    "ex1": "Students discuss today during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về hôm nay trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 141,
    "word": "autumn",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔtʌm/",
    "meaning": "mùa thu",
    "ex1": "Last autumn, many birds traveled thousands of kilometers to find warmer places.",
    "ex1_vi": "Mùa thu năm ngoái, nhiều con chim đã bay hàng nghìn kilômét để tìm nơi ấm hơn."
  },
  {
    "id": 142,
    "word": "traveled",
    "type": "verb",
    "cat": "v",
    "phonetic": "/trˈævʌld/",
    "meaning": "đã di chuyển",
    "ex1": "Students discuss traveled during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đã di chuyển trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 143,
    "word": "kilometers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kɪˈlɒmɪtərz/",
    "meaning": "kilômét",
    "ex1": "Students discuss kilometers during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về kilômét trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 144,
    "word": "find",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪnd/",
    "meaning": "tìm",
    "ex1": "Students discuss find during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về tìm trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 145,
    "word": "warmer",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈɔrmɝ/",
    "meaning": "ấm hơn",
    "ex1": "Students discuss warmer during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về ấm hơn trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 146,
    "word": "places",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪsʌz/",
    "meaning": "nơi",
    "ex1": "People should protect trees because birds need safe places to rest.",
    "ex1_vi": "Mọi người nên bảo vệ cây vì chim cần nơi an toàn để nghỉ ngơi."
  },
  {
    "id": 147,
    "word": "flew",
    "type": "verb",
    "cat": "v",
    "phonetic": "/flˈu/",
    "meaning": "đã bay",
    "ex1": "They flew together because the journey was long and difficult.",
    "ex1_vi": "Chúng bay cùng nhau vì hành trình dài và khó khăn."
  },
  {
    "id": 148,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "Students discuss because during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về bởi vì trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 149,
    "word": "journey",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɝni/",
    "meaning": "hành trình",
    "ex1": "Students discuss journey during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về hành trình trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 150,
    "word": "difficult",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfʌkʌlt/",
    "meaning": "khó khăn",
    "ex1": "Students discuss difficult during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về khó khăn trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 151,
    "word": "next",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈɛkst/",
    "meaning": "tiếp theo",
    "ex1": "Next spring, they are going to return to their original homes again.",
    "ex1_vi": "Mùa xuân tới, chúng sẽ trở về nơi ở ban đầu một lần nữa."
  },
  {
    "id": 152,
    "word": "going",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/ɡˈoʊɪŋ/",
    "meaning": "sắp; đang",
    "ex1": "Next spring, they are going to return to their original homes again.",
    "ex1_vi": "Mùa xuân tới, chúng sẽ trở về nơi ở ban đầu một lần nữa."
  },
  {
    "id": 153,
    "word": "return",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪtˈɝn/",
    "meaning": "trở về",
    "ex1": "Students discuss return during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về trở về trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 154,
    "word": "original",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɝˈɪdʒʌnʌl/",
    "meaning": "ban đầu",
    "ex1": "Students discuss original during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về ban đầu trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 155,
    "word": "homes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊmz/",
    "meaning": "nơi ở",
    "ex1": "Students discuss homes during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về nơi ở trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 156,
    "word": "again",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌɡˈɛn/",
    "meaning": "lại",
    "ex1": "Students discuss again during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về lại trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 157,
    "word": "trees",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈiz/",
    "meaning": "cây",
    "ex1": "People should protect trees because birds need safe places to rest.",
    "ex1_vi": "Mọi người nên bảo vệ cây vì chim cần nơi an toàn để nghỉ ngơi."
  },
  {
    "id": 158,
    "word": "need",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈid/",
    "meaning": "cần",
    "ex1": "Students discuss need during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cần trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 159,
    "word": "safe",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪf/",
    "meaning": "an toàn",
    "ex1": "Students discuss safe during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về an toàn trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 160,
    "word": "rest",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈɛst/",
    "meaning": "nghỉ ngơi",
    "ex1": "Students discuss rest during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về nghỉ ngơi trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 161,
    "word": "continue",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈɪnju/",
    "meaning": "tiếp tục",
    "ex1": "Animals continue together when their habitats remain safe.",
    "ex1_vi": "Động vật tiếp tục cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 162,
    "word": "filling",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɪlɪŋ/",
    "meaning": "làm đầy",
    "ex1": "These animals are filling and need safe habitats.",
    "ex1_vi": "Những động vật này làm đầy và cần môi trường sống an toàn."
  },
  {
    "id": 163,
    "word": "beautiful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bjˈutʌfʌl/",
    "meaning": "đẹp",
    "ex1": "A beautiful animal can survive in a protected area.",
    "ex1_vi": "Một động vật đẹp có thể sống sót trong khu vực được bảo vệ."
  },
  {
    "id": 164,
    "word": "songs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔŋz/",
    "meaning": "bài hát",
    "ex1": "People discuss songs during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về bài hát trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 165,
    "word": "season",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈizʌn/",
    "meaning": "mùa",
    "ex1": "Students learn about season when studying wild animals.",
    "ex1_vi": "Học sinh học về mùa khi tìm hiểu động vật hoang dã."
  }
];

const newReadingVocabOrder = [
  "life",
  "farm",
  "animals",
  "help",
  "people",
  "many",
  "ways",
  "every",
  "day",
  "cows",
  "give",
  "milk",
  "chickens",
  "lay",
  "eggs",
  "and",
  "sheep",
  "provide",
  "wool",
  "farmers",
  "have",
  "feed",
  "before",
  "sunrise",
  "must",
  "keep",
  "barns",
  "clean",
  "last",
  "spring",
  "young",
  "born",
  "local",
  "farms",
  "visitors",
  "enjoyed",
  "watching",
  "play",
  "fields",
  "after",
  "breakfast",
  "water",
  "fresh",
  "food",
  "helped",
  "animal",
  "grow",
  "strong",
  "healthy",
  "always",
  "treat",
  "kindly",
  "never",
  "frighten",
  "if",
  "care",
  "well",
  "will",
  "produce",
  "better",
  "everyone",
  "benefit",
  "hard",
  "work",
  "sea",
  "live",
  "oceans",
  "seas",
  "around",
  "world",
  "dolphins",
  "turtles",
  "whales",
  "octopuses",
  "among",
  "most",
  "amazing",
  "creatures",
  "look",
  "group",
  "swimming",
  "boat",
  "can",
  "stay",
  "underwater",
  "long",
  "time",
  "scientists",
  "already",
  "discovered",
  "thousands",
  "species",
  "but",
  "others",
  "still",
  "remain",
  "unknown",
  "year",
  "rare",
  "turtle",
  "rescued",
  "returned",
  "ocean",
  "safely",
  "survive",
  "should",
  "reduce",
  "plastic",
  "waste",
  "protect",
  "marine",
  "works",
  "together",
  "enjoy",
  "cleaner",
  "waters",
  "safer",
  "habitats",
  "future",
  "birds",
  "sky",
  "different",
  "forests",
  "busy",
  "cities",
  "eagles",
  "parrots",
  "owls",
  "sparrows",
  "colors",
  "sizes",
  "flying",
  "skills",
  "several",
  "building",
  "new",
  "nest",
  "tall",
  "tree",
  "today",
  "autumn",
  "traveled",
  "kilometers",
  "find",
  "warmer",
  "places",
  "flew",
  "because",
  "journey",
  "difficult",
  "next",
  "going",
  "return",
  "original",
  "homes",
  "again",
  "trees",
  "need",
  "safe",
  "rest",
  "continue",
  "filling",
  "beautiful",
  "songs",
  "season"
];
