const newEssayData = [
  {
    "text": "Chapter 7. Endangered Animals\nMany endangered animals need help because their habitats are disappearing quickly. Tigers, elephants, rhinos, and pandas face many dangers every year. Look! Wildlife workers are protecting young animals in a special nature reserve today.\n\nSeveral countries have already created national parks to save rare species. Last year, many rescued animals were released into safer forests after careful treatment. These efforts have given them another chance to survive.\n\nEveryone should protect wildlife and must never hunt rare animals. If people respect nature, endangered species will have a brighter future and continue living safely.",
    "vi": "Chương 7. Động vật có nguy cơ tuyệt chủng\nNhiều loài động vật có nguy cơ tuyệt chủng cần được giúp đỡ vì môi trường sống của chúng đang biến mất nhanh chóng. Hổ, voi, tê giác và gấu trúc đối mặt với nhiều nguy hiểm mỗi năm. Nhìn kìa! Các nhân viên bảo tồn đang bảo vệ động vật non trong một khu bảo tồn thiên nhiên đặc biệt hôm nay.\n\nMột số quốc gia đã thành lập các công viên quốc gia để cứu các loài quý hiếm. Năm ngoái, nhiều động vật được cứu hộ đã được thả vào những khu rừng an toàn hơn sau khi được điều trị cẩn thận. Những nỗ lực này đã cho chúng thêm một cơ hội để sống sót.\n\nMọi người nên bảo vệ động vật hoang dã và tuyệt đối không được săn động vật quý hiếm. Nếu con người tôn trọng thiên nhiên, các loài có nguy cơ tuyệt chủng sẽ có tương lai tươi sáng hơn và tiếp tục sống an toàn."
  },
  {
    "text": "Chapter 8. Animal Communication\nAnimals communicate in many interesting ways every day. Birds sing beautiful songs, bees dance to share information, and elephants make deep sounds across long distances. Look! Several monkeys are using different calls to warn each other about danger nearby.\n\nScientists have studied animal communication for many years and have already discovered many surprising facts. Last summer, researchers recorded new whale sounds in the Pacific Ocean. These discoveries help people understand wildlife much better.\n\nPeople should respect animals and protect their habitats. If animals communicate safely, they will find food, avoid danger, and live peacefully in nature together every day.",
    "vi": "Chương 8. Giao tiếp của động vật\nĐộng vật giao tiếp theo nhiều cách thú vị mỗi ngày. Chim hót những bài ca đẹp, ong nhảy để chia sẻ thông tin và voi tạo ra âm thanh trầm ở những khoảng cách xa. Nhìn kìa! Một số con khỉ đang dùng những tiếng gọi khác nhau để cảnh báo nhau về nguy hiểm gần đó.\n\nCác nhà khoa học đã nghiên cứu cách giao tiếp của động vật trong nhiều năm và đã khám phá nhiều sự thật đáng ngạc nhiên. Mùa hè năm ngoái, các nhà nghiên cứu đã ghi lại những âm thanh mới của cá voi ở Thái Bình Dương. Những khám phá này giúp mọi người hiểu động vật hoang dã tốt hơn nhiều.\n\nMọi người nên tôn trọng động vật và bảo vệ môi trường sống của chúng. Nếu động vật giao tiếp an toàn, chúng sẽ tìm thức ăn, tránh nguy hiểm và sống yên bình cùng nhau trong tự nhiên mỗi ngày."
  },
  {
    "text": "Chapter 9. Animal Homes\nAnimals build different homes to stay safe and comfortable. Birds make nests in trees, rabbits dig holes underground, and bees live together inside large hives. Look! A family of squirrels is collecting leaves for a warm nest today.\n\nMany animals have already changed their homes because weather conditions are changing. Last winter, several foxes moved to nearby forests to find more food and shelter. Safe homes help animals grow and survive.\n\nPeople should protect forests and natural habitats. If every animal has a safe home, nature will remain healthy, beautiful, and full of life for everyone.",
    "vi": "Chương 9. Nhà của động vật\nĐộng vật xây những nơi ở khác nhau để được an toàn và thoải mái. Chim làm tổ trên cây, thỏ đào hang dưới đất và ong sống cùng nhau bên trong những tổ ong lớn. Nhìn kìa! Một gia đình sóc đang thu gom lá để làm một chiếc tổ ấm hôm nay.\n\nNhiều loài động vật đã thay đổi nơi ở vì điều kiện thời tiết đang thay đổi. Mùa đông năm ngoái, một số con cáo đã chuyển đến những khu rừng gần đó để tìm thêm thức ăn và nơi trú ẩn. Nơi ở an toàn giúp động vật lớn lên và sống sót.\n\nMọi người nên bảo vệ rừng và môi trường sống tự nhiên. Nếu mọi con vật có một nơi ở an toàn, thiên nhiên sẽ vẫn khỏe mạnh, tươi đẹp và tràn đầy sự sống cho mọi người."
  },
  {
    "text": "Chapter 10. Helping Wild Animals\nWild animals face many problems because forests are becoming smaller and pollution is increasing. Many organizations work hard to protect wildlife every year. Look! Volunteers are feeding injured animals at a rescue center this morning with great care.\n\nConservation groups have already saved many rare animals from danger. Last year, several young bears were treated by animal doctors before returning to the forest. These successful programs give wildlife new hope for survival.\n\nEveryone should care about wild animals and must protect nature. If people continue working together, more species will survive, and future generations will enjoy a richer natural world.",
    "vi": "Chương 10. Giúp đỡ động vật hoang dã\nĐộng vật hoang dã đối mặt với nhiều vấn đề vì rừng đang nhỏ dần và ô nhiễm đang tăng lên. Nhiều tổ chức làm việc chăm chỉ để bảo vệ động vật hoang dã mỗi năm. Nhìn kìa! Các tình nguyện viên đang cho những con vật bị thương ăn tại một trung tâm cứu hộ sáng nay với sự chăm sóc tận tình.\n\nCác nhóm bảo tồn đã cứu nhiều động vật quý hiếm khỏi nguy hiểm. Năm ngoái, một số gấu non được bác sĩ thú y điều trị trước khi trở lại rừng. Những chương trình thành công này mang lại hy vọng mới cho động vật hoang dã sống sót.\n\nMọi người nên quan tâm đến động vật hoang dã và phải bảo vệ thiên nhiên. Nếu mọi người tiếp tục cùng làm việc, nhiều loài hơn sẽ sống sót và các thế hệ tương lai sẽ được tận hưởng một thế giới tự nhiên phong phú hơn."
  }
];
