const lessonVocabularyWords = [
  "endangered",
  "animals",
  "many",
  "need",
  "help",
  "because",
  "habitats",
  "disappearing",
  "quickly",
  "tigers",
  "elephants",
  "rhinos",
  "and",
  "pandas",
  "face",
  "dangers",
  "every",
  "year",
  "look",
  "wildlife",
  "workers",
  "protecting",
  "young",
  "special",
  "nature",
  "reserve",
  "today",
  "several",
  "countries",
  "have",
  "already",
  "created",
  "national",
  "parks",
  "save",
  "rare",
  "species",
  "last",
  "rescued",
  "released",
  "safer",
  "forests",
  "after",
  "careful",
  "treatment",
  "efforts",
  "given",
  "another",
  "chance",
  "survive",
  "everyone",
  "should",
  "protect",
  "must",
  "never",
  "hunt",
  "if",
  "people",
  "respect",
  "will",
  "brighter",
  "future",
  "continue",
  "living",
  "safely",
  "animal",
  "communication",
  "communicate",
  "interesting",
  "ways",
  "day",
  "birds",
  "sing",
  "beautiful",
  "songs",
  "bees",
  "dance",
  "share",
  "information",
  "make",
  "deep",
  "sounds",
  "across",
  "long",
  "distances",
  "monkeys",
  "using",
  "different",
  "calls",
  "warn",
  "each",
  "other",
  "about",
  "danger",
  "nearby",
  "scientists",
  "studied",
  "years",
  "discovered",
  "surprising",
  "facts",
  "summer",
  "researchers",
  "recorded",
  "new",
  "whale",
  "pacific",
  "ocean",
  "discoveries",
  "understand",
  "much",
  "better",
  "find",
  "food",
  "avoid",
  "live",
  "peacefully",
  "together",
  "homes",
  "build",
  "stay",
  "safe",
  "comfortable",
  "nests",
  "trees",
  "rabbits",
  "dig",
  "holes",
  "underground",
  "inside",
  "large",
  "hives",
  "family",
  "squirrels",
  "collecting",
  "leaves",
  "warm",
  "nest",
  "changed",
  "weather",
  "conditions",
  "changing",
  "winter",
  "foxes",
  "moved",
  "more",
  "shelter",
  "grow",
  "natural",
  "has",
  "home",
  "remain",
  "healthy",
  "full",
  "life",
  "helping",
  "wild",
  "problems",
  "becoming",
  "smaller",
  "pollution",
  "increasing",
  "organizations",
  "work",
  "hard",
  "volunteers",
  "feeding",
  "injured",
  "rescue",
  "center",
  "morning",
  "great",
  "care",
  "conservation",
  "groups",
  "saved",
  "bears",
  "treated",
  "doctors",
  "before",
  "returning",
  "forest",
  "successful",
  "programs",
  "give",
  "hope",
  "survival",
  "working",
  "generations",
  "enjoy",
  "richer",
  "world"
];

const newVocabData = [
  {
    "id": 1,
    "word": "endangered",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪnˈdeɪndʒərd/",
    "meaning": "có nguy cơ tuyệt chủng",
    "ex1": "Many endangered animals need help because their habitats are disappearing quickly.",
    "ex1_vi": "Nhiều loài động vật có nguy cơ tuyệt chủng cần được giúp đỡ vì môi trường sống của chúng đang biến mất nhanh chóng."
  },
  {
    "id": 2,
    "word": "animals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈænʌmʌlz/",
    "meaning": "động vật",
    "ex1": "People discuss animals during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về động vật trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 3,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Animals communicate in many interesting ways every day.",
    "ex1_vi": "Động vật giao tiếp theo nhiều cách thú vị mỗi ngày."
  },
  {
    "id": 4,
    "word": "need",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈid/",
    "meaning": "cần",
    "ex1": "Many endangered animals need help because their habitats are disappearing quickly.",
    "ex1_vi": "Nhiều loài động vật có nguy cơ tuyệt chủng cần được giúp đỡ vì môi trường sống của chúng đang biến mất nhanh chóng."
  },
  {
    "id": 5,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "sự giúp đỡ; giúp",
    "ex1": "Animals help together when their habitats remain safe.",
    "ex1_vi": "Động vật sự giúp đỡ; giúp cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 6,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "Students discuss because during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về bởi vì trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 7,
    "word": "habitats",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈhæbɪtæts/",
    "meaning": "môi trường sống",
    "ex1": "Healthy habitats provide habitats for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp môi trường sống cho động vật trên khắp thế giới."
  },
  {
    "id": 8,
    "word": "disappearing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˌɪsʌpˈɪrɪŋ/",
    "meaning": "đang biến mất",
    "ex1": "Students discuss disappearing during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đang biến mất trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 9,
    "word": "quickly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kwˈɪkli/",
    "meaning": "nhanh chóng",
    "ex1": "Students discuss quickly during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về nhanh chóng trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 10,
    "word": "tigers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪɡɝz/",
    "meaning": "hổ",
    "ex1": "Tigers, elephants, rhinos, and pandas face many dangers every year.",
    "ex1_vi": "Hổ, voi, tê giác và gấu trúc đối mặt với nhiều nguy hiểm mỗi năm."
  },
  {
    "id": 11,
    "word": "elephants",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛlʌfʌnts/",
    "meaning": "voi",
    "ex1": "Tigers, elephants, rhinos, and pandas face many dangers every year.",
    "ex1_vi": "Hổ, voi, tê giác và gấu trúc đối mặt với nhiều nguy hiểm mỗi năm."
  },
  {
    "id": 12,
    "word": "rhinos",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈraɪnoʊz/",
    "meaning": "tê giác",
    "ex1": "Students discuss rhinos during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về tê giác trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 13,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Animals need food and clean water to stay healthy.",
    "ex1_vi": "Động vật cần thức ăn và nước sạch để luôn khỏe mạnh."
  },
  {
    "id": 14,
    "word": "pandas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈpændəz/",
    "meaning": "gấu trúc",
    "ex1": "Students discuss pandas during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về gấu trúc trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 15,
    "word": "face",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈeɪs/",
    "meaning": "đối mặt",
    "ex1": "Students discuss face during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đối mặt trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 16,
    "word": "dangers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪndʒɝz/",
    "meaning": "nguy hiểm",
    "ex1": "Students discuss dangers during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về nguy hiểm trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 17,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɝi/",
    "meaning": "mỗi",
    "ex1": "Animals communicate in many interesting ways every day.",
    "ex1_vi": "Động vật giao tiếp theo nhiều cách thú vị mỗi ngày."
  },
  {
    "id": 18,
    "word": "year",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈɪr/",
    "meaning": "năm",
    "ex1": "Many organizations work hard to protect wildlife every year.",
    "ex1_vi": "Nhiều tổ chức làm việc chăm chỉ để bảo vệ động vật hoang dã mỗi năm."
  },
  {
    "id": 19,
    "word": "look",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊk/",
    "meaning": "nhìn",
    "ex1": "People can look animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể nhìn động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 20,
    "word": "wildlife",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈwaɪldlaɪf/",
    "meaning": "động vật hoang dã",
    "ex1": "These discoveries help people understand wildlife much better.",
    "ex1_vi": "Những khám phá này giúp mọi người hiểu động vật hoang dã tốt hơn nhiều."
  },
  {
    "id": 21,
    "word": "workers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝkɝz/",
    "meaning": "nhân viên",
    "ex1": "Wildlife workers are protecting young animals in a special nature reserve today.",
    "ex1_vi": "Các nhân viên bảo tồn đang bảo vệ động vật non trong một khu bảo tồn thiên nhiên đặc biệt hôm nay."
  },
  {
    "id": 22,
    "word": "protecting",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌtˈɛktɪŋ/",
    "meaning": "đang bảo vệ",
    "ex1": "Wildlife workers are protecting young animals in a special nature reserve today.",
    "ex1_vi": "Các nhân viên bảo tồn đang bảo vệ động vật non trong một khu bảo tồn thiên nhiên đặc biệt hôm nay."
  },
  {
    "id": 23,
    "word": "young",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈʌŋ/",
    "meaning": "non; trẻ",
    "ex1": "Students discuss young during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về non; trẻ trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 24,
    "word": "special",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/spˈɛʃʌl/",
    "meaning": "đặc biệt",
    "ex1": "Students discuss special during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đặc biệt trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 25,
    "word": "nature",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈeɪtʃɝ/",
    "meaning": "thiên nhiên",
    "ex1": "Everyone should care about wild animals and must protect nature.",
    "ex1_vi": "Mọi người nên quan tâm đến động vật hoang dã và phải bảo vệ thiên nhiên."
  },
  {
    "id": 26,
    "word": "reserve",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rɪzˈɝv/",
    "meaning": "khu bảo tồn",
    "ex1": "Students discuss reserve during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về khu bảo tồn trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 27,
    "word": "today",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌdˈeɪ/",
    "meaning": "hôm nay",
    "ex1": "Students discuss today during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về hôm nay trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 28,
    "word": "several",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈɛvrʌl/",
    "meaning": "một số",
    "ex1": "Several countries have already created national parks to save rare species.",
    "ex1_vi": "Một số quốc gia đã thành lập các công viên quốc gia để cứu các loài quý hiếm."
  },
  {
    "id": 29,
    "word": "countries",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌntriz/",
    "meaning": "quốc gia",
    "ex1": "Several countries have already created national parks to save rare species.",
    "ex1_vi": "Một số quốc gia đã thành lập các công viên quốc gia để cứu các loài quý hiếm."
  },
  {
    "id": 30,
    "word": "have",
    "type": "verb/auxiliary",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có; phải trong have to",
    "ex1": "These efforts have given them another chance to survive.",
    "ex1_vi": "Những nỗ lực này đã cho chúng thêm một cơ hội để sống sót."
  },
  {
    "id": 31,
    "word": "already",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɔlrˈɛdi/",
    "meaning": "đã",
    "ex1": "Conservation groups have already saved many rare animals from danger.",
    "ex1_vi": "Các nhóm bảo tồn đã cứu nhiều động vật quý hiếm khỏi nguy hiểm."
  },
  {
    "id": 32,
    "word": "created",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪtʌd/",
    "meaning": "đã tạo",
    "ex1": "Students discuss created during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đã tạo trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 33,
    "word": "national",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈæʃʌnʌl/",
    "meaning": "quốc gia",
    "ex1": "Students discuss national during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về quốc gia trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 34,
    "word": "parks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrks/",
    "meaning": "công viên",
    "ex1": "Students discuss parks during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về công viên trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 35,
    "word": "save",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪv/",
    "meaning": "cứu",
    "ex1": "Students discuss save during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cứu trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 36,
    "word": "rare",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛr/",
    "meaning": "quý hiếm",
    "ex1": "Everyone should protect wildlife and must never hunt rare animals.",
    "ex1_vi": "Mọi người nên bảo vệ động vật hoang dã và tuyệt đối không được săn động vật quý hiếm."
  },
  {
    "id": 37,
    "word": "species",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈiʃiz/",
    "meaning": "loài",
    "ex1": "Students discuss species during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về loài trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 38,
    "word": "last",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈæst/",
    "meaning": "trước; vừa qua",
    "ex1": "Last summer, researchers recorded new whale sounds in the Pacific Ocean.",
    "ex1_vi": "Mùa hè năm ngoái, các nhà nghiên cứu đã ghi lại những âm thanh mới của cá voi ở Thái Bình Dương."
  },
  {
    "id": 39,
    "word": "rescued",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛskjud/",
    "meaning": "được cứu hộ",
    "ex1": "These animals are rescued and need safe habitats.",
    "ex1_vi": "Những động vật này được cứu hộ và cần môi trường sống an toàn."
  },
  {
    "id": 40,
    "word": "released",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rilˈist/",
    "meaning": "được thả",
    "ex1": "People can released animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể được thả động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 41,
    "word": "safer",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪfɝ/",
    "meaning": "an toàn hơn",
    "ex1": "People want wildlife habitats to remain safer and safe.",
    "ex1_vi": "Con người muốn môi trường sống hoang dã vẫn an toàn hơn và an toàn."
  },
  {
    "id": 42,
    "word": "forests",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɔrʌsts/",
    "meaning": "rừng",
    "ex1": "Students learn about forests when studying wild animals.",
    "ex1_vi": "Học sinh học về rừng khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 43,
    "word": "after",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/ˈæftɝ/",
    "meaning": "sau",
    "ex1": "Students use after in simple sentences about animal life.",
    "ex1_vi": "Học sinh dùng “after” trong những câu đơn giản về đời sống động vật."
  },
  {
    "id": 44,
    "word": "careful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɛrfʌl/",
    "meaning": "cẩn thận",
    "ex1": "People want wildlife habitats to remain careful and safe.",
    "ex1_vi": "Con người muốn môi trường sống hoang dã vẫn cẩn thận và an toàn."
  },
  {
    "id": 45,
    "word": "treatment",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈitmʌnt/",
    "meaning": "việc điều trị",
    "ex1": "Students learn about treatment when studying wild animals.",
    "ex1_vi": "Học sinh học về việc điều trị khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 46,
    "word": "efforts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛfɝts/",
    "meaning": "nỗ lực",
    "ex1": "These efforts have given them another chance to survive.",
    "ex1_vi": "Những nỗ lực này đã cho chúng thêm một cơ hội để sống sót."
  },
  {
    "id": 47,
    "word": "given",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvʌn/",
    "meaning": "đã cho",
    "ex1": "Students discuss given during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đã cho trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 48,
    "word": "another",
    "type": "determiner/pronoun",
    "cat": "adj",
    "phonetic": "/ʌnˈʌðɝ/",
    "meaning": "một cơ hội/cái khác",
    "ex1": "Students discuss another during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về một cơ hội/cái khác trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 49,
    "word": "chance",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈæns/",
    "meaning": "cơ hội",
    "ex1": "Students discuss chance during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cơ hội trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 50,
    "word": "survive",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sɝvˈaɪv/",
    "meaning": "sống sót",
    "ex1": "Animals survive together when their habitats remain safe.",
    "ex1_vi": "Động vật sống sót cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 51,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvriwˌʌn/",
    "meaning": "mọi người",
    "ex1": "Everyone should protect wildlife and must never hunt rare animals.",
    "ex1_vi": "Mọi người nên bảo vệ động vật hoang dã và tuyệt đối không được săn động vật quý hiếm."
  },
  {
    "id": 52,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "People should protect wildlife and keep habitats clean.",
    "ex1_vi": "Mọi người nên bảo vệ động vật hoang dã và giữ môi trường sống sạch."
  },
  {
    "id": 53,
    "word": "protect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌtˈɛkt/",
    "meaning": "bảo vệ",
    "ex1": "Animals protect together when their habitats remain safe.",
    "ex1_vi": "Động vật bảo vệ cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 54,
    "word": "must",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈʌst/",
    "meaning": "phải",
    "ex1": "Students discuss must during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về phải trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 55,
    "word": "never",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɛvɝ/",
    "meaning": "không bao giờ",
    "ex1": "Students discuss never during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về không bao giờ trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 56,
    "word": "hunt",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈʌnt/",
    "meaning": "săn",
    "ex1": "Students discuss hunt during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về săn trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 57,
    "word": "if",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɪf/",
    "meaning": "nếu",
    "ex1": "If people protect nature, animals can live safely.",
    "ex1_vi": "Nếu con người bảo vệ thiên nhiên, động vật có thể sống an toàn."
  },
  {
    "id": 58,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "Healthy habitats provide people for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp mọi người cho động vật trên khắp thế giới."
  },
  {
    "id": 59,
    "word": "respect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪspˈɛkt/",
    "meaning": "tôn trọng",
    "ex1": "People should respect animals and protect their habitats.",
    "ex1_vi": "Mọi người nên tôn trọng động vật và bảo vệ môi trường sống của chúng."
  },
  {
    "id": 60,
    "word": "will",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/wˈɪl/",
    "meaning": "sẽ",
    "ex1": "Healthy habitats will help animals survive for years.",
    "ex1_vi": "Môi trường sống khỏe mạnh sẽ giúp động vật tồn tại nhiều năm."
  },
  {
    "id": 61,
    "word": "brighter",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/brˈaɪtɝ/",
    "meaning": "tươi sáng hơn",
    "ex1": "A brighter animal can survive in a protected area.",
    "ex1_vi": "Một động vật tươi sáng hơn có thể sống sót trong khu vực được bảo vệ."
  },
  {
    "id": 62,
    "word": "future",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fjˈutʃɝ/",
    "meaning": "tương lai",
    "ex1": "People discuss future during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về tương lai trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 63,
    "word": "continue",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈɪnju/",
    "meaning": "tiếp tục",
    "ex1": "Wild animals continue safely in healthy natural habitats.",
    "ex1_vi": "Động vật hoang dã tiếp tục an toàn trong môi trường sống tự nhiên khỏe mạnh."
  },
  {
    "id": 64,
    "word": "living",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɪvɪŋ/",
    "meaning": "việc sống",
    "ex1": "People can living animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể việc sống động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 65,
    "word": "safely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sˈeɪfli/",
    "meaning": "an toàn",
    "ex1": "Wild animals safely find food in healthy habitats.",
    "ex1_vi": "Động vật hoang dã an toàn tìm thức ăn trong môi trường sống khỏe mạnh."
  },
  {
    "id": 66,
    "word": "animal",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈænʌmʌl/",
    "meaning": "động vật",
    "ex1": "Students learn about animal when studying wild animals.",
    "ex1_vi": "Học sinh học về động vật khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 67,
    "word": "communication",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kəˌmjuːnɪˈkeɪʃən/",
    "meaning": "giao tiếp",
    "ex1": "Healthy habitats provide communication for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp giao tiếp cho động vật trên khắp thế giới."
  },
  {
    "id": 68,
    "word": "communicate",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌmjˈunʌkˌeɪt/",
    "meaning": "giao tiếp",
    "ex1": "Students discuss communicate during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về giao tiếp trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 69,
    "word": "interesting",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɪntrʌstɪŋ/",
    "meaning": "thú vị",
    "ex1": "Students discuss interesting during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về thú vị trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 70,
    "word": "ways",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪz/",
    "meaning": "cách",
    "ex1": "Students discuss ways during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cách trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 71,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "Students discuss day during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về ngày trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 72,
    "word": "birds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɝdz/",
    "meaning": "chim",
    "ex1": "Students learn about birds when studying wild animals.",
    "ex1_vi": "Học sinh học về chim khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 73,
    "word": "sing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɪŋ/",
    "meaning": "hót",
    "ex1": "People can sing animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể hót động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 74,
    "word": "beautiful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bjˈutʌfʌl/",
    "meaning": "đẹp",
    "ex1": "People want wildlife habitats to remain beautiful and safe.",
    "ex1_vi": "Con người muốn môi trường sống hoang dã vẫn đẹp và an toàn."
  },
  {
    "id": 75,
    "word": "songs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔŋz/",
    "meaning": "bài hát",
    "ex1": "Students learn about songs when studying wild animals.",
    "ex1_vi": "Học sinh học về bài hát khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 76,
    "word": "bees",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈiz/",
    "meaning": "ong",
    "ex1": "Healthy habitats provide bees for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp ong cho động vật trên khắp thế giới."
  },
  {
    "id": 77,
    "word": "dance",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈæns/",
    "meaning": "nhảy",
    "ex1": "Animals dance together when their habitats remain safe.",
    "ex1_vi": "Động vật nhảy cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 78,
    "word": "share",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈɛr/",
    "meaning": "chia sẻ",
    "ex1": "Wild animals share safely in healthy natural habitats.",
    "ex1_vi": "Động vật hoang dã chia sẻ an toàn trong môi trường sống tự nhiên khỏe mạnh."
  },
  {
    "id": 79,
    "word": "information",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnfɝmˈeɪʃʌn/",
    "meaning": "thông tin",
    "ex1": "Healthy habitats provide information for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp thông tin cho động vật trên khắp thế giới."
  },
  {
    "id": 80,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm cho",
    "ex1": "Animals make together when their habitats remain safe.",
    "ex1_vi": "Động vật làm cho cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 81,
    "word": "deep",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈip/",
    "meaning": "trầm; sâu",
    "ex1": "These animals are deep and need safe habitats.",
    "ex1_vi": "Những động vật này trầm; sâu và cần môi trường sống an toàn."
  },
  {
    "id": 82,
    "word": "sounds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaʊndz/",
    "meaning": "âm thanh",
    "ex1": "Last summer, researchers recorded new whale sounds in the Pacific Ocean.",
    "ex1_vi": "Mùa hè năm ngoái, các nhà nghiên cứu đã ghi lại những âm thanh mới của cá voi ở Thái Bình Dương."
  },
  {
    "id": 83,
    "word": "across",
    "type": "preposition/adverb",
    "cat": "adv",
    "phonetic": "/ʌkrˈɔs/",
    "meaning": "qua; trên khắp",
    "ex1": "Students use across in simple sentences about animal life.",
    "ex1_vi": "Học sinh dùng “across” trong những câu đơn giản về đời sống động vật."
  },
  {
    "id": 84,
    "word": "long",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɔŋ/",
    "meaning": "dài",
    "ex1": "These animals are long and need safe habitats.",
    "ex1_vi": "Những động vật này dài và cần môi trường sống an toàn."
  },
  {
    "id": 85,
    "word": "distances",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪstʌnsʌz/",
    "meaning": "khoảng cách",
    "ex1": "Healthy habitats provide distances for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp khoảng cách cho động vật trên khắp thế giới."
  },
  {
    "id": 86,
    "word": "monkeys",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌŋkiz/",
    "meaning": "khỉ",
    "ex1": "People discuss monkeys during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về khỉ trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 87,
    "word": "using",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈuzɪŋ/",
    "meaning": "đang sử dụng",
    "ex1": "Students learn about using when studying wild animals.",
    "ex1_vi": "Học sinh học về đang sử dụng khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 88,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "Animals build different homes to stay safe and comfortable.",
    "ex1_vi": "Động vật xây những nơi ở khác nhau để được an toàn và thoải mái."
  },
  {
    "id": 89,
    "word": "calls",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɔlz/",
    "meaning": "tiếng gọi",
    "ex1": "People discuss calls during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về tiếng gọi trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 90,
    "word": "warn",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɔrn/",
    "meaning": "cảnh báo",
    "ex1": "Wild animals warn safely in healthy natural habitats.",
    "ex1_vi": "Động vật hoang dã cảnh báo an toàn trong môi trường sống tự nhiên khỏe mạnh."
  },
  {
    "id": 91,
    "word": "each",
    "type": "determiner/pronoun",
    "cat": "adj",
    "phonetic": "/ˈitʃ/",
    "meaning": "mỗi",
    "ex1": "Each people help protect wildlife in different countries.",
    "ex1_vi": "Mỗi người giúp bảo vệ động vật hoang dã ở các quốc gia khác nhau."
  },
  {
    "id": 92,
    "word": "other",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈʌðɝ/",
    "meaning": "khác",
    "ex1": "Other animals need clean water and safe natural habitats.",
    "ex1_vi": "Khác động vật cần nước sạch và môi trường sống tự nhiên an toàn."
  },
  {
    "id": 93,
    "word": "about",
    "type": "preposition/adverb",
    "cat": "adv",
    "phonetic": "/ʌbˈaʊt/",
    "meaning": "về",
    "ex1": "Everyone should care about wild animals and must protect nature.",
    "ex1_vi": "Mọi người nên quan tâm đến động vật hoang dã và phải bảo vệ thiên nhiên."
  },
  {
    "id": 94,
    "word": "danger",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪndʒɝ/",
    "meaning": "nguy hiểm",
    "ex1": "Conservation groups have already saved many rare animals from danger.",
    "ex1_vi": "Các nhóm bảo tồn đã cứu nhiều động vật quý hiếm khỏi nguy hiểm."
  },
  {
    "id": 95,
    "word": "nearby",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɪrbˈaɪ/",
    "meaning": "gần đó",
    "ex1": "Wild animals nearby find food in healthy habitats.",
    "ex1_vi": "Động vật hoang dã gần đó tìm thức ăn trong môi trường sống khỏe mạnh."
  },
  {
    "id": 96,
    "word": "scientists",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaɪʌntɪsts/",
    "meaning": "nhà khoa học",
    "ex1": "Students learn about scientists when studying wild animals.",
    "ex1_vi": "Học sinh học về nhà khoa học khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 97,
    "word": "studied",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈʌdid/",
    "meaning": "đã nghiên cứu",
    "ex1": "People can studied animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể đã nghiên cứu động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 98,
    "word": "years",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈɪrz/",
    "meaning": "năm",
    "ex1": "People discuss years during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về năm trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 99,
    "word": "discovered",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dɪskˈʌvɝd/",
    "meaning": "đã khám phá",
    "ex1": "Wild animals discovered safely in healthy natural habitats.",
    "ex1_vi": "Động vật hoang dã đã khám phá an toàn trong môi trường sống tự nhiên khỏe mạnh."
  },
  {
    "id": 100,
    "word": "surprising",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sɝprˈaɪzɪŋ/",
    "meaning": "đáng ngạc nhiên",
    "ex1": "A surprising animal can survive in a protected area.",
    "ex1_vi": "Một động vật đáng ngạc nhiên có thể sống sót trong khu vực được bảo vệ."
  },
  {
    "id": 101,
    "word": "facts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈækts/",
    "meaning": "sự thật",
    "ex1": "People discuss facts during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về sự thật trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 102,
    "word": "summer",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈʌmɝ/",
    "meaning": "mùa hè",
    "ex1": "Students discuss summer during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về mùa hè trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 103,
    "word": "researchers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈisɝtʃɝz/",
    "meaning": "nhà nghiên cứu",
    "ex1": "Students discuss researchers during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về nhà nghiên cứu trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 104,
    "word": "recorded",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rʌkˈɔrdɪd/",
    "meaning": "đã ghi lại",
    "ex1": "Students discuss recorded during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đã ghi lại trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 105,
    "word": "new",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈu/",
    "meaning": "mới",
    "ex1": "These successful programs give wildlife new hope for survival.",
    "ex1_vi": "Những chương trình thành công này mang lại hy vọng mới cho động vật hoang dã sống sót."
  },
  {
    "id": 106,
    "word": "whale",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪl/",
    "meaning": "cá voi",
    "ex1": "Students discuss whale during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cá voi trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 107,
    "word": "pacific",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pʌsˈɪfɪk/",
    "meaning": "Thái Bình Dương",
    "ex1": "Students discuss pacific during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về Thái Bình Dương trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 108,
    "word": "ocean",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈoʊʃʌn/",
    "meaning": "đại dương",
    "ex1": "Students discuss ocean during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đại dương trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 109,
    "word": "discoveries",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪskˈʌvɝiz/",
    "meaning": "khám phá",
    "ex1": "These discoveries help people understand wildlife much better.",
    "ex1_vi": "Những khám phá này giúp mọi người hiểu động vật hoang dã tốt hơn nhiều."
  },
  {
    "id": 110,
    "word": "understand",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌʌndɝstˈænd/",
    "meaning": "hiểu",
    "ex1": "Students discuss understand during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về hiểu trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 111,
    "word": "much",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/mˈʌtʃ/",
    "meaning": "nhiều",
    "ex1": "Students discuss much during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về nhiều trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 112,
    "word": "better",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/bˈɛtɝ/",
    "meaning": "tốt hơn",
    "ex1": "Students discuss better during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về tốt hơn trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 113,
    "word": "find",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪnd/",
    "meaning": "tìm",
    "ex1": "Animals find together when their habitats remain safe.",
    "ex1_vi": "Động vật tìm cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 114,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thức ăn",
    "ex1": "Students learn about food when studying wild animals.",
    "ex1_vi": "Học sinh học về thức ăn khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 115,
    "word": "avoid",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌvˈɔɪd/",
    "meaning": "tránh",
    "ex1": "People can avoid animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể tránh động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 116,
    "word": "live",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈaɪv/",
    "meaning": "sống",
    "ex1": "Animals live together when their habitats remain safe.",
    "ex1_vi": "Động vật sống cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 117,
    "word": "peacefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/pˈisfʌli/",
    "meaning": "yên bình",
    "ex1": "Animals peacefully live together in protected natural areas.",
    "ex1_vi": "Động vật yên bình sống cùng nhau trong các khu vực tự nhiên được bảo vệ."
  },
  {
    "id": 118,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌɡˈɛðɝ/",
    "meaning": "cùng nhau",
    "ex1": "People discuss together during lessons about animal protection.",
    "ex1_vi": "Mọi người thảo luận về cùng nhau trong các bài học về bảo vệ động vật."
  },
  {
    "id": 119,
    "word": "homes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊmz/",
    "meaning": "nơi ở",
    "ex1": "People discuss homes during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về nơi ở trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 120,
    "word": "build",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɪld/",
    "meaning": "xây",
    "ex1": "Animals build different homes to stay safe and comfortable.",
    "ex1_vi": "Động vật xây những nơi ở khác nhau để được an toàn và thoải mái."
  },
  {
    "id": 121,
    "word": "stay",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈeɪ/",
    "meaning": "ở; sống",
    "ex1": "Students discuss stay during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về ở; sống trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 122,
    "word": "safe",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪf/",
    "meaning": "an toàn",
    "ex1": "People want wildlife habitats to remain safe and safe.",
    "ex1_vi": "Con người muốn môi trường sống hoang dã vẫn an toàn và an toàn."
  },
  {
    "id": 123,
    "word": "comfortable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌmfɝtʌbʌl/",
    "meaning": "thoải mái",
    "ex1": "Students discuss comfortable during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về thoải mái trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 124,
    "word": "nests",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈɛsts/",
    "meaning": "tổ",
    "ex1": "Healthy habitats provide nests for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp tổ cho động vật trên khắp thế giới."
  },
  {
    "id": 125,
    "word": "trees",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈiz/",
    "meaning": "cây",
    "ex1": "People discuss trees during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về cây trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 126,
    "word": "rabbits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈæbʌts/",
    "meaning": "thỏ",
    "ex1": "Students learn about rabbits when studying wild animals.",
    "ex1_vi": "Học sinh học về thỏ khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 127,
    "word": "dig",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈɪɡ/",
    "meaning": "đào",
    "ex1": "People can dig animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể đào động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 128,
    "word": "holes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊlz/",
    "meaning": "hang; lỗ",
    "ex1": "People discuss holes during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về hang; lỗ trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 129,
    "word": "underground",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈʌndɝɡrˌaʊnd/",
    "meaning": "dưới đất",
    "ex1": "Animals underground live together in protected natural areas.",
    "ex1_vi": "Động vật dưới đất sống cùng nhau trong các khu vực tự nhiên được bảo vệ."
  },
  {
    "id": 130,
    "word": "inside",
    "type": "preposition/adverb",
    "cat": "adv",
    "phonetic": "/ˌɪnsˈaɪd/",
    "meaning": "bên trong",
    "ex1": "People use inside naturally when talking about wild animals.",
    "ex1_vi": "Mọi người dùng “inside” tự nhiên khi nói về động vật hoang dã."
  },
  {
    "id": 131,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒ/",
    "meaning": "lớn",
    "ex1": "People want wildlife habitats to remain large and safe.",
    "ex1_vi": "Con người muốn môi trường sống hoang dã vẫn lớn và an toàn."
  },
  {
    "id": 132,
    "word": "hives",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈaɪvz/",
    "meaning": "tổ ong",
    "ex1": "Students learn about hives when studying wild animals.",
    "ex1_vi": "Học sinh học về tổ ong khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 133,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "A family of squirrels is collecting leaves for a warm nest today.",
    "ex1_vi": "Một gia đình sóc đang thu gom lá để làm một chiếc tổ ấm hôm nay."
  },
  {
    "id": 134,
    "word": "squirrels",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈskwɪrəlz/",
    "meaning": "sóc",
    "ex1": "A family of squirrels is collecting leaves for a warm nest today.",
    "ex1_vi": "Một gia đình sóc đang thu gom lá để làm một chiếc tổ ấm hôm nay."
  },
  {
    "id": 135,
    "word": "collecting",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌlˈɛktɪŋ/",
    "meaning": "đang thu gom",
    "ex1": "Students discuss collecting during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đang thu gom trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 136,
    "word": "leaves",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈivz/",
    "meaning": "lá",
    "ex1": "Students discuss leaves during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về lá trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 137,
    "word": "warm",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈɔrm/",
    "meaning": "ấm",
    "ex1": "Students discuss warm during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về ấm trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 138,
    "word": "nest",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈɛst/",
    "meaning": "tổ",
    "ex1": "Students discuss nest during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về tổ trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 139,
    "word": "changed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈeɪndʒd/",
    "meaning": "được thay đổi",
    "ex1": "Many animals have already changed their homes because weather conditions are changing.",
    "ex1_vi": "Nhiều loài động vật đã thay đổi nơi ở vì điều kiện thời tiết đang thay đổi."
  },
  {
    "id": 140,
    "word": "weather",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɛðɝ/",
    "meaning": "thời tiết",
    "ex1": "Many animals have already changed their homes because weather conditions are changing.",
    "ex1_vi": "Nhiều loài động vật đã thay đổi nơi ở vì điều kiện thời tiết đang thay đổi."
  },
  {
    "id": 141,
    "word": "conditions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌndˈɪʃʌnz/",
    "meaning": "điều kiện",
    "ex1": "Students discuss conditions during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về điều kiện trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 142,
    "word": "changing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈeɪndʒɪŋ/",
    "meaning": "đang thay đổi",
    "ex1": "Students discuss changing during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đang thay đổi trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 143,
    "word": "winter",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɪntɝ/",
    "meaning": "mùa đông",
    "ex1": "People discuss winter during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về mùa đông trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 144,
    "word": "foxes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɑksʌz/",
    "meaning": "cáo",
    "ex1": "Students learn about foxes when studying wild animals.",
    "ex1_vi": "Học sinh học về cáo khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 145,
    "word": "moved",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈuvd/",
    "meaning": "được chuyển",
    "ex1": "People can moved animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể được chuyển động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 146,
    "word": "more",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "nhiều hơn",
    "ex1": "More animals need clean water and safe natural habitats.",
    "ex1_vi": "Nhiều hơn động vật cần nước sạch và môi trường sống tự nhiên an toàn."
  },
  {
    "id": 147,
    "word": "shelter",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɛltɝ/",
    "meaning": "nơi trú ẩn",
    "ex1": "Students learn about shelter when studying wild animals.",
    "ex1_vi": "Học sinh học về nơi trú ẩn khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 148,
    "word": "grow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡrˈoʊ/",
    "meaning": "lớn lên",
    "ex1": "People can grow animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể lớn lên động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 149,
    "word": "natural",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈætʃɝʌl/",
    "meaning": "tự nhiên",
    "ex1": "People want wildlife habitats to remain natural and safe.",
    "ex1_vi": "Con người muốn môi trường sống hoang dã vẫn tự nhiên và an toàn."
  },
  {
    "id": 150,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "Wild animals has safely in healthy natural habitats.",
    "ex1_vi": "Động vật hoang dã có an toàn trong môi trường sống tự nhiên khỏe mạnh."
  },
  {
    "id": 151,
    "word": "home",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊm/",
    "meaning": "nhà; nơi sinh sống",
    "ex1": "Healthy habitats provide home for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp nhà; nơi sinh sống cho động vật trên khắp thế giới."
  },
  {
    "id": 152,
    "word": "remain",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪmˈeɪn/",
    "meaning": "vẫn còn",
    "ex1": "Animals remain together when their habitats remain safe.",
    "ex1_vi": "Động vật vẫn còn cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 153,
    "word": "healthy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlθi/",
    "meaning": "khỏe mạnh",
    "ex1": "These animals are healthy and need safe habitats.",
    "ex1_vi": "Những động vật này khỏe mạnh và cần môi trường sống an toàn."
  },
  {
    "id": 154,
    "word": "full",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈʊl/",
    "meaning": "đầy",
    "ex1": "A full animal can survive in a protected area.",
    "ex1_vi": "Một động vật đầy có thể sống sót trong khu vực được bảo vệ."
  },
  {
    "id": 155,
    "word": "life",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪf/",
    "meaning": "cuộc sống",
    "ex1": "People discuss life during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về cuộc sống trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 156,
    "word": "helping",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/hˈɛlpɪŋ/",
    "meaning": "việc giúp",
    "ex1": "Students learn about helping when studying wild animals.",
    "ex1_vi": "Học sinh học về việc giúp khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 157,
    "word": "wild",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈaɪld/",
    "meaning": "hoang dã",
    "ex1": "Students discuss wild during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về hoang dã trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 158,
    "word": "problems",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑblʌmz/",
    "meaning": "vấn đề",
    "ex1": "People discuss problems during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về vấn đề trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 159,
    "word": "becoming",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌmɪŋ/",
    "meaning": "đang trở nên",
    "ex1": "Wild animals becoming safely in healthy natural habitats.",
    "ex1_vi": "Động vật hoang dã đang trở nên an toàn trong môi trường sống tự nhiên khỏe mạnh."
  },
  {
    "id": 160,
    "word": "smaller",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔlɝ/",
    "meaning": "nhỏ hơn",
    "ex1": "A smaller animal can survive in a protected area.",
    "ex1_vi": "Một động vật nhỏ hơn có thể sống sót trong khu vực được bảo vệ."
  },
  {
    "id": 161,
    "word": "pollution",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pʌlˈuʃʌn/",
    "meaning": "ô nhiễm",
    "ex1": "People discuss pollution during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về ô nhiễm trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 162,
    "word": "increasing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪnkrˈisɪŋ/",
    "meaning": "đang tăng",
    "ex1": "Wild animals increasing safely in healthy natural habitats.",
    "ex1_vi": "Động vật hoang dã đang tăng an toàn trong môi trường sống tự nhiên khỏe mạnh."
  },
  {
    "id": 163,
    "word": "organizations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɔrɡʌnʌzˈeɪʃʌnz/",
    "meaning": "tổ chức",
    "ex1": "Many organizations work hard to protect wildlife every year.",
    "ex1_vi": "Nhiều tổ chức làm việc chăm chỉ để bảo vệ động vật hoang dã mỗi năm."
  },
  {
    "id": 164,
    "word": "work",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝk/",
    "meaning": "làm việc",
    "ex1": "Students discuss work during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về làm việc trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 165,
    "word": "hard",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑrd/",
    "meaning": "vất vả",
    "ex1": "Students discuss hard during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về vất vả trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 166,
    "word": "volunteers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˌɑlʌntˈɪrz/",
    "meaning": "tình nguyện viên",
    "ex1": "Healthy habitats provide volunteers for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp tình nguyện viên cho động vật trên khắp thế giới."
  },
  {
    "id": 167,
    "word": "feeding",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/fˈidɪŋ/",
    "meaning": "đang cho ăn",
    "ex1": "People discuss feeding during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về đang cho ăn trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 168,
    "word": "injured",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɪndʒɝd/",
    "meaning": "bị thương",
    "ex1": "These animals are injured and need safe habitats.",
    "ex1_vi": "Những động vật này bị thương và cần môi trường sống an toàn."
  },
  {
    "id": 169,
    "word": "rescue",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɛskju/",
    "meaning": "cứu hộ",
    "ex1": "Healthy habitats provide rescue for animals around the world.",
    "ex1_vi": "Môi trường sống khỏe mạnh cung cấp cứu hộ cho động vật trên khắp thế giới."
  },
  {
    "id": 170,
    "word": "center",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛntɝ/",
    "meaning": "trung tâm",
    "ex1": "People discuss center during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về trung tâm trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 171,
    "word": "morning",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɔrnɪŋ/",
    "meaning": "buổi sáng",
    "ex1": "Students learn about morning when studying wild animals.",
    "ex1_vi": "Học sinh học về buổi sáng khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 172,
    "word": "great",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈeɪt/",
    "meaning": "tận tình; tuyệt vời",
    "ex1": "A great animal can survive in a protected area.",
    "ex1_vi": "Một động vật tận tình; tuyệt vời có thể sống sót trong khu vực được bảo vệ."
  },
  {
    "id": 173,
    "word": "care",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɛr/",
    "meaning": "chăm sóc",
    "ex1": "Students discuss care during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về chăm sóc trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 174,
    "word": "conservation",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌkɒnsərˈveɪʃən/",
    "meaning": "bảo tồn",
    "ex1": "Students discuss conservation during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về bảo tồn trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 175,
    "word": "groups",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡrˈups/",
    "meaning": "nhóm",
    "ex1": "Students discuss groups during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về nhóm trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 176,
    "word": "saved",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪvd/",
    "meaning": "đã cứu",
    "ex1": "Students discuss saved during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về đã cứu trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 177,
    "word": "bears",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɛrz/",
    "meaning": "gấu",
    "ex1": "Students learn about bears when studying wild animals.",
    "ex1_vi": "Học sinh học về gấu khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 178,
    "word": "treated",
    "type": "verb",
    "cat": "v",
    "phonetic": "/trˈitɪd/",
    "meaning": "được điều trị",
    "ex1": "People can treated animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể được điều trị động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 179,
    "word": "doctors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɑktɝz/",
    "meaning": "bác sĩ",
    "ex1": "People discuss doctors during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về bác sĩ trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 180,
    "word": "before",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/bɪfˈɔr/",
    "meaning": "trước",
    "ex1": "People use before naturally when talking about wild animals.",
    "ex1_vi": "Mọi người dùng “before” tự nhiên khi nói về động vật hoang dã."
  },
  {
    "id": 181,
    "word": "returning",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪtˈɝnɪŋ/",
    "meaning": "việc trở lại",
    "ex1": "People can returning animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể việc trở lại động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 182,
    "word": "forest",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɔrʌst/",
    "meaning": "rừng",
    "ex1": "People discuss forest during lessons about wildlife protection.",
    "ex1_vi": "Mọi người thảo luận về rừng trong các bài học về bảo vệ động vật hoang dã."
  },
  {
    "id": 183,
    "word": "successful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sʌksˈɛsfʌl/",
    "meaning": "thành công",
    "ex1": "These successful programs give wildlife new hope for survival.",
    "ex1_vi": "Những chương trình thành công này mang lại hy vọng mới cho động vật hoang dã sống sót."
  },
  {
    "id": 184,
    "word": "programs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈoʊɡrˌæmz/",
    "meaning": "chương trình",
    "ex1": "Students discuss programs during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về chương trình trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 185,
    "word": "give",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪv/",
    "meaning": "cho",
    "ex1": "Students discuss give during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về cho trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 186,
    "word": "hope",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊp/",
    "meaning": "hy vọng",
    "ex1": "Students discuss hope during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về hy vọng trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 187,
    "word": "survival",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sɝvˈaɪvʌl/",
    "meaning": "sự sống sót",
    "ex1": "Students discuss survival during lessons about animal habitats.",
    "ex1_vi": "Học sinh thảo luận về sự sống sót trong các bài học về môi trường sống của động vật."
  },
  {
    "id": 188,
    "word": "working",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝkɪŋ/",
    "meaning": "việc làm việc",
    "ex1": "Animals working together when their habitats remain safe.",
    "ex1_vi": "Động vật việc làm việc cùng nhau khi môi trường sống của chúng vẫn an toàn."
  },
  {
    "id": 189,
    "word": "generations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˌɛnɝˈeɪʃʌnz/",
    "meaning": "thế hệ",
    "ex1": "Students learn about generations when studying wild animals.",
    "ex1_vi": "Học sinh học về thế hệ khi tìm hiểu động vật hoang dã."
  },
  {
    "id": 190,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thích; thưởng thức",
    "ex1": "People can enjoy animals through careful wildlife protection.",
    "ex1_vi": "Con người có thể thích; thưởng thức động vật thông qua việc bảo vệ động vật hoang dã cẩn thận."
  },
  {
    "id": 191,
    "word": "richer",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɪtʃɝ/",
    "meaning": "phong phú hơn",
    "ex1": "People want wildlife habitats to remain richer and safe.",
    "ex1_vi": "Con người muốn môi trường sống hoang dã vẫn phong phú hơn và an toàn."
  },
  {
    "id": 192,
    "word": "world",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝld/",
    "meaning": "thế giới",
    "ex1": "Students learn about world when studying wild animals.",
    "ex1_vi": "Học sinh học về thế giới khi tìm hiểu động vật hoang dã."
  }
];

const newReadingVocabOrder = [
  "endangered",
  "animals",
  "many",
  "need",
  "help",
  "because",
  "habitats",
  "disappearing",
  "quickly",
  "tigers",
  "elephants",
  "rhinos",
  "and",
  "pandas",
  "face",
  "dangers",
  "every",
  "year",
  "look",
  "wildlife",
  "workers",
  "protecting",
  "young",
  "special",
  "nature",
  "reserve",
  "today",
  "several",
  "countries",
  "have",
  "already",
  "created",
  "national",
  "parks",
  "save",
  "rare",
  "species",
  "last",
  "rescued",
  "released",
  "safer",
  "forests",
  "after",
  "careful",
  "treatment",
  "efforts",
  "given",
  "another",
  "chance",
  "survive",
  "everyone",
  "should",
  "protect",
  "must",
  "never",
  "hunt",
  "if",
  "people",
  "respect",
  "will",
  "brighter",
  "future",
  "continue",
  "living",
  "safely",
  "animal",
  "communication",
  "communicate",
  "interesting",
  "ways",
  "day",
  "birds",
  "sing",
  "beautiful",
  "songs",
  "bees",
  "dance",
  "share",
  "information",
  "make",
  "deep",
  "sounds",
  "across",
  "long",
  "distances",
  "monkeys",
  "using",
  "different",
  "calls",
  "warn",
  "each",
  "other",
  "about",
  "danger",
  "nearby",
  "scientists",
  "studied",
  "years",
  "discovered",
  "surprising",
  "facts",
  "summer",
  "researchers",
  "recorded",
  "new",
  "whale",
  "pacific",
  "ocean",
  "discoveries",
  "understand",
  "much",
  "better",
  "find",
  "food",
  "avoid",
  "live",
  "peacefully",
  "together",
  "homes",
  "build",
  "stay",
  "safe",
  "comfortable",
  "nests",
  "trees",
  "rabbits",
  "dig",
  "holes",
  "underground",
  "inside",
  "large",
  "hives",
  "family",
  "squirrels",
  "collecting",
  "leaves",
  "warm",
  "nest",
  "changed",
  "weather",
  "conditions",
  "changing",
  "winter",
  "foxes",
  "moved",
  "more",
  "shelter",
  "grow",
  "natural",
  "has",
  "home",
  "remain",
  "healthy",
  "full",
  "life",
  "helping",
  "wild",
  "problems",
  "becoming",
  "smaller",
  "pollution",
  "increasing",
  "organizations",
  "work",
  "hard",
  "volunteers",
  "feeding",
  "injured",
  "rescue",
  "center",
  "morning",
  "great",
  "care",
  "conservation",
  "groups",
  "saved",
  "bears",
  "treated",
  "doctors",
  "before",
  "returning",
  "forest",
  "successful",
  "programs",
  "give",
  "hope",
  "survival",
  "working",
  "generations",
  "enjoy",
  "richer",
  "world"
];
