// ===== traffic02 ESSAY =====

const newEssayData = [
  {
    "text": "4. Rush Hour\nRush hour is the busiest time of the day in many cities. People leave home early for work and school. Roads become crowded with cars, buses, motorbikes, and bicycles. Traffic moves slowly because many vehicles travel together at once.\n\nMany drivers become impatient during heavy traffic and long waits. They should stay calm, keep safe distances, and obey traffic lights carefully. Listening to traffic reports helps people choose better routes before leaving home.\n\nRush hour can waste time and increase pollution. People should leave earlier, use public transportation, or work from home when possible. Smart travel plans make daily journeys easier and safer.",
    "vi": "4. Giờ cao điểm\nGiờ cao điểm là thời gian bận rộn nhất trong ngày ở nhiều thành phố. Mọi người rời nhà sớm để đi làm và đi học. Đường phố trở nên đông đúc với ô tô, xe buýt, xe máy và xe đạp. Giao thông di chuyển chậm vì nhiều phương tiện cùng đi một lúc.\n\nNhiều người lái xe trở nên mất kiên nhẫn khi giao thông đông đúc và phải chờ lâu. Họ nên giữ bình tĩnh, giữ khoảng cách an toàn và tuân thủ đèn giao thông cẩn thận. Nghe báo cáo giao thông giúp mọi người chọn tuyến đường tốt hơn trước khi rời nhà.\n\nGiờ cao điểm có thể làm lãng phí thời gian và làm tăng ô nhiễm. Mọi người nên rời đi sớm hơn, sử dụng phương tiện công cộng hoặc làm việc tại nhà khi có thể. Kế hoạch di chuyển thông minh làm cho hành trình hằng ngày dễ dàng và an toàn hơn."
  },
  {
    "text": "5. Safe Crossing\nCrossing the road safely is an important skill for everyone. Busy streets have many cars, buses, motorbikes, and bicycles moving quickly. Children should learn road safety from parents and teachers before walking alone in the city every day.\n\nPeople should use crosswalks and traffic lights whenever possible. Before crossing, look left, right, and left again carefully. Never run across busy roads or use mobile phones while walking through traffic areas.\n\nSafe crossing helps prevent accidents and injuries every day. Everyone should stay alert and follow traffic rules carefully. Good road safety habits protect families, friends, and all people in the community.",
    "vi": "5. Băng qua đường an toàn\nBăng qua đường an toàn là một kỹ năng quan trọng đối với mọi người. Những con phố đông đúc có nhiều ô tô, xe buýt, xe máy và xe đạp di chuyển nhanh. Trẻ em nên học an toàn giao thông từ cha mẹ và giáo viên trước khi tự đi bộ trong thành phố mỗi ngày.\n\nMọi người nên sử dụng vạch qua đường và đèn giao thông bất cứ khi nào có thể. Trước khi băng qua, hãy nhìn trái, phải rồi nhìn trái một lần nữa thật cẩn thận. Không bao giờ chạy băng qua những con đường đông đúc hoặc dùng điện thoại di động khi đi bộ qua khu vực giao thông.\n\nBăng qua đường an toàn giúp ngăn ngừa tai nạn và thương tích mỗi ngày. Mọi người nên luôn cảnh giác và tuân thủ luật giao thông cẩn thận. Những thói quen an toàn đường bộ tốt bảo vệ gia đình, bạn bè và tất cả mọi người trong cộng đồng."
  },
  {
    "text": "6. Riding a Bicycle\nRiding a bicycle is a healthy and enjoyable way to travel. Many students and workers ride bicycles to school or work every day. Bicycles do not cause air pollution and help reduce traffic on busy city roads.\n\nCyclists should wear helmets and check their bicycles before every trip. They must follow traffic signs, use hand signals, and stay in bicycle lanes whenever possible. Bright clothes help drivers see cyclists more easily.\n\nCycling keeps people healthy and saves transportation costs. More people should ride bicycles for short trips instead of driving cars. Cleaner transportation creates safer roads and a better environment for everyone.",
    "vi": "6. Đi xe đạp\nĐi xe đạp là một cách di chuyển lành mạnh và thú vị. Nhiều học sinh và người lao động đi xe đạp đến trường hoặc nơi làm việc mỗi ngày. Xe đạp không gây ô nhiễm không khí và giúp giảm giao thông trên những con đường thành phố đông đúc.\n\nNgười đi xe đạp nên đội mũ bảo hiểm và kiểm tra xe trước mỗi chuyến đi. Họ phải tuân theo biển báo giao thông, dùng tín hiệu tay và đi trong làn xe đạp bất cứ khi nào có thể. Quần áo sáng màu giúp người lái xe nhìn thấy người đi xe đạp dễ dàng hơn.\n\nĐạp xe giúp mọi người khỏe mạnh và tiết kiệm chi phí đi lại. Nhiều người nên đi xe đạp cho những chuyến đi ngắn thay vì lái ô tô. Phương tiện sạch hơn tạo ra những con đường an toàn hơn và môi trường tốt hơn cho mọi người."
  }
];
