// ===== traffic03 VOCABULARY =====

const lessonVocabularyWords = [
  "driving",
  "carefully",
  "important",
  "every",
  "road",
  "user",
  "city",
  "drivers",
  "should",
  "stay",
  "focused",
  "and",
  "always",
  "watch",
  "other",
  "vehicles",
  "cyclists",
  "pedestrians",
  "safe",
  "helps",
  "prevent",
  "accidents",
  "protects",
  "everyone",
  "traveling",
  "busy",
  "roads",
  "day",
  "must",
  "obey",
  "speed",
  "limits",
  "stop",
  "completely",
  "red",
  "lights",
  "avoid",
  "using",
  "mobile",
  "phones",
  "while",
  "because",
  "distractions",
  "dangerous",
  "keeping",
  "enough",
  "distance",
  "makes",
  "much",
  "safer",
  "careful",
  "creates",
  "streets",
  "happier",
  "communities",
  "responsible",
  "show",
  "respect",
  "people",
  "following",
  "traffic",
  "rules",
  "good",
  "habits",
  "help",
  "reach",
  "destinations",
  "safely",
  "comfortably",
  "air",
  "pollution",
  "heavy",
  "causes",
  "many",
  "large",
  "cities",
  "cars",
  "buses",
  "trucks",
  "motorbikes",
  "produce",
  "smoke",
  "dirty",
  "poor",
  "quality",
  "can",
  "affect",
  "people's",
  "health",
  "especially",
  "children",
  "older",
  "adults",
  "living",
  "nearby",
  "reduce",
  "public",
  "transportation",
  "more",
  "often",
  "walking",
  "cycling",
  "or",
  "sharing",
  "also",
  "lowers",
  "number",
  "planting",
  "trees",
  "improve",
  "neighborhoods",
  "too",
  "cleaner",
  "benefits",
  "small",
  "daily",
  "actions",
  "protect",
  "nature",
  "healthy",
  "life",
  "better",
  "families",
  "workers",
  "students",
  "future",
  "generations",
  "everywhere",
  "bus",
  "ride",
  "taking",
  "easy",
  "way",
  "travel",
  "visitors",
  "use",
  "affordable",
  "convenient",
  "places",
  "making",
  "simple",
  "passengers",
  "arrive",
  "early",
  "wait",
  "politely",
  "need",
  "buy",
  "tickets",
  "keep",
  "clean",
  "speaking",
  "quietly",
  "giving",
  "seats",
  "manners",
  "choose",
  "instead",
  "private",
  "journeys",
  "cheaper",
  "environment",
  "one",
  "healthiest",
  "ways",
  "walk",
  "school",
  "work",
  "shops",
  "parks",
  "costs",
  "nothing",
  "enjoy",
  "fresh",
  "regular",
  "exercise",
  "together",
  "sidewalks",
  "whenever",
  "possible",
  "cross",
  "follow",
  "alert",
  "intersections",
  "looking",
  "both",
  "crossing",
  "keeps",
  "outside",
  "reduces",
  "fitness",
  "save",
  "create",
  "quieter",
  "friendlier",
  "age"
];

const newVocabData = [
  {
    "id": 1,
    "word": "driving",
    "type": "verb",
    "cat": "v",
    "phonetic": "/drˈaɪvɪŋ/",
    "meaning": "việc lái xe",
    "ex1": "Driving carefully is important for every road user in the city.",
    "ex1_vi": "Lái xe cẩn thận là điều quan trọng đối với mọi người sử dụng đường trong thành phố."
  },
  {
    "id": 2,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛɹfəli/",
    "meaning": "một cách cẩn thận",
    "ex1": "In daily city life, driving carefully is important for every road user in the city.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, lái xe cẩn thận là điều quan trọng đối với mọi người sử dụng đường trong thành phố."
  },
  {
    "id": 3,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔɹtənt/",
    "meaning": "quan trọng",
    "ex1": "For safe travel, driving carefully is important for every road user in the city.",
    "ex1_vi": "Để đi lại an toàn, lái xe cẩn thận là điều quan trọng đối với mọi người sử dụng đường trong thành phố."
  },
  {
    "id": 4,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ɛvɚi/",
    "meaning": "mỗi",
    "ex1": "On busy city streets, driving carefully is important for every road user in the city.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, lái xe cẩn thận là điều quan trọng đối với mọi người sử dụng đường trong thành phố."
  },
  {
    "id": 5,
    "word": "road",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈoʊd/",
    "meaning": "đường",
    "ex1": "During everyday travel, driving carefully is important for every road user in the city.",
    "ex1_vi": "Trong việc đi lại hằng ngày, lái xe cẩn thận là điều quan trọng đối với mọi người sử dụng đường trong thành phố."
  },
  {
    "id": 6,
    "word": "user",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈuzɝ/",
    "meaning": "người sử dụng",
    "ex1": "For road safety, driving carefully is important for every road user in the city.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, lái xe cẩn thận là điều quan trọng đối với mọi người sử dụng đường trong thành phố."
  },
  {
    "id": 7,
    "word": "city",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪti/",
    "meaning": "thành phố",
    "ex1": "In many neighborhoods, driving carefully is important for every road user in the city.",
    "ex1_vi": "Ở nhiều khu phố, lái xe cẩn thận là điều quan trọng đối với mọi người sử dụng đường trong thành phố."
  },
  {
    "id": 8,
    "word": "drivers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈaɪvɝz/",
    "meaning": "người lái xe",
    "ex1": "Drivers should stay focused and always watch other vehicles, cyclists, and pedestrians.",
    "ex1_vi": "Người lái xe nên tập trung và luôn quan sát các phương tiện khác, người đi xe đạp và người đi bộ."
  },
  {
    "id": 9,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "In daily city life, drivers should stay focused and always watch other vehicles, cyclists, and pedestrians.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người lái xe nên tập trung và luôn quan sát các phương tiện khác, người đi xe đạp và người đi bộ."
  },
  {
    "id": 10,
    "word": "stay",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈeɪ/",
    "meaning": "giữ; ở lại",
    "ex1": "For safe travel, drivers should stay focused and always watch other vehicles, cyclists, and pedestrians.",
    "ex1_vi": "Để đi lại an toàn, người lái xe nên tập trung và luôn quan sát các phương tiện khác, người đi xe đạp và người đi bộ."
  },
  {
    "id": 11,
    "word": "focused",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈoʊkəst/",
    "meaning": "tập trung",
    "ex1": "On busy city streets, drivers should stay focused and always watch other vehicles, cyclists, and pedestrians.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, người lái xe nên tập trung và luôn quan sát các phương tiện khác, người đi xe đạp và người đi bộ."
  },
  {
    "id": 12,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ənd/",
    "meaning": "và",
    "ex1": "During everyday travel, drivers should stay focused and always watch other vehicles, cyclists, and pedestrians.",
    "ex1_vi": "Trong việc đi lại hằng ngày, người lái xe nên tập trung và luôn quan sát các phương tiện khác, người đi xe đạp và người đi bộ."
  },
  {
    "id": 13,
    "word": "always",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlwˌeɪz/",
    "meaning": "luôn luôn",
    "ex1": "For road safety, drivers should stay focused and always watch other vehicles, cyclists, and pedestrians.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, người lái xe nên tập trung và luôn quan sát các phương tiện khác, người đi xe đạp và người đi bộ."
  },
  {
    "id": 14,
    "word": "watch",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɑtʃ/",
    "meaning": "quan sát",
    "ex1": "In many neighborhoods, drivers should stay focused and always watch other vehicles, cyclists, and pedestrians.",
    "ex1_vi": "Ở nhiều khu phố, người lái xe nên tập trung và luôn quan sát các phương tiện khác, người đi xe đạp và người đi bộ."
  },
  {
    "id": 15,
    "word": "other",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ʌðɚ/",
    "meaning": "khác",
    "ex1": "On a normal weekday, drivers should stay focused and always watch other vehicles, cyclists, and pedestrians.",
    "ex1_vi": "Vào một ngày thường, người lái xe nên tập trung và luôn quan sát các phương tiện khác, người đi xe đạp và người đi bộ."
  },
  {
    "id": 16,
    "word": "vehicles",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈihɪkʌlz/",
    "meaning": "phương tiện",
    "ex1": "Drivers should stay focused and always watch other vehicles, cyclists, and pedestrians.",
    "ex1_vi": "Người lái xe nên tập trung và luôn quan sát các phương tiện khác, người đi xe đạp và người đi bộ."
  },
  {
    "id": 17,
    "word": "cyclists",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaɪkʌlɪsts/",
    "meaning": "người đi xe đạp",
    "ex1": "In daily city life, drivers should stay focused and always watch other vehicles, cyclists, and pedestrians.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người lái xe nên tập trung và luôn quan sát các phương tiện khác, người đi xe đạp và người đi bộ."
  },
  {
    "id": 18,
    "word": "pedestrians",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pʌdˈɛstriʌnz/",
    "meaning": "người đi bộ",
    "ex1": "For safe travel, drivers should stay focused and always watch other vehicles, cyclists, and pedestrians.",
    "ex1_vi": "Để đi lại an toàn, người lái xe nên tập trung và luôn quan sát các phương tiện khác, người đi xe đạp và người đi bộ."
  },
  {
    "id": 19,
    "word": "safe",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/seɪf/",
    "meaning": "an toàn",
    "ex1": "Safe driving helps prevent accidents and protects everyone traveling on busy roads every day.",
    "ex1_vi": "Lái xe an toàn giúp ngăn ngừa tai nạn và bảo vệ mọi người đang di chuyển trên những con đường đông đúc mỗi ngày."
  },
  {
    "id": 20,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "In daily city life, safe driving helps prevent accidents and protects everyone traveling on busy roads every day.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, lái xe an toàn giúp ngăn ngừa tai nạn và bảo vệ mọi người đang di chuyển trên những con đường đông đúc mỗi ngày."
  },
  {
    "id": 21,
    "word": "prevent",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹɪvˈɛnt/",
    "meaning": "ngăn ngừa",
    "ex1": "For safe travel, safe driving helps prevent accidents and protects everyone traveling on busy roads every day.",
    "ex1_vi": "Để đi lại an toàn, lái xe an toàn giúp ngăn ngừa tai nạn và bảo vệ mọi người đang di chuyển trên những con đường đông đúc mỗi ngày."
  },
  {
    "id": 22,
    "word": "accidents",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈæksʌdʌnts/",
    "meaning": "tai nạn",
    "ex1": "On busy city streets, safe driving helps prevent accidents and protects everyone traveling on busy roads every day.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, lái xe an toàn giúp ngăn ngừa tai nạn và bảo vệ mọi người đang di chuyển trên những con đường đông đúc mỗi ngày."
  },
  {
    "id": 23,
    "word": "protects",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prʌtˈɛkts/",
    "meaning": "bảo vệ",
    "ex1": "During everyday travel, safe driving helps prevent accidents and protects everyone traveling on busy roads every day.",
    "ex1_vi": "Trong việc đi lại hằng ngày, lái xe an toàn giúp ngăn ngừa tai nạn và bảo vệ mọi người đang di chuyển trên những con đường đông đúc mỗi ngày."
  },
  {
    "id": 24,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ɛvriwʌn/",
    "meaning": "mọi người",
    "ex1": "For road safety, safe driving helps prevent accidents and protects everyone traveling on busy roads every day.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, lái xe an toàn giúp ngăn ngừa tai nạn và bảo vệ mọi người đang di chuyển trên những con đường đông đúc mỗi ngày."
  },
  {
    "id": 25,
    "word": "traveling",
    "type": "verb",
    "cat": "v",
    "phonetic": "/trˈævʌlɪŋ/",
    "meaning": "đang di chuyển",
    "ex1": "In many neighborhoods, safe driving helps prevent accidents and protects everyone traveling on busy roads every day.",
    "ex1_vi": "Ở nhiều khu phố, lái xe an toàn giúp ngăn ngừa tai nạn và bảo vệ mọi người đang di chuyển trên những con đường đông đúc mỗi ngày."
  },
  {
    "id": 26,
    "word": "busy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈbɪzi/",
    "meaning": "bận rộn; đông đúc",
    "ex1": "On a normal weekday, safe driving helps prevent accidents and protects everyone traveling on busy roads every day.",
    "ex1_vi": "Vào một ngày thường, lái xe an toàn giúp ngăn ngừa tai nạn và bảo vệ mọi người đang di chuyển trên những con đường đông đúc mỗi ngày."
  },
  {
    "id": 27,
    "word": "roads",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈoʊdz/",
    "meaning": "đường",
    "ex1": "Safe driving helps prevent accidents and protects everyone traveling on busy roads every day.",
    "ex1_vi": "Lái xe an toàn giúp ngăn ngừa tai nạn và bảo vệ mọi người đang di chuyển trên những con đường đông đúc mỗi ngày."
  },
  {
    "id": 28,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/deɪ/",
    "meaning": "ngày",
    "ex1": "In daily city life, safe driving helps prevent accidents and protects everyone traveling on busy roads every day.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, lái xe an toàn giúp ngăn ngừa tai nạn và bảo vệ mọi người đang di chuyển trên những con đường đông đúc mỗi ngày."
  },
  {
    "id": 29,
    "word": "must",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈʌst/",
    "meaning": "phải",
    "ex1": "Drivers must obey speed limits and stop completely at red lights.",
    "ex1_vi": "Người lái xe phải tuân thủ giới hạn tốc độ và dừng hẳn khi đèn đỏ."
  },
  {
    "id": 30,
    "word": "obey",
    "type": "verb",
    "cat": "v",
    "phonetic": "/oʊbˈeɪ/",
    "meaning": "tuân thủ",
    "ex1": "In daily city life, drivers must obey speed limits and stop completely at red lights.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người lái xe phải tuân thủ giới hạn tốc độ và dừng hẳn khi đèn đỏ."
  },
  {
    "id": 31,
    "word": "speed",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈiːd/",
    "meaning": "tốc độ",
    "ex1": "For safe travel, drivers must obey speed limits and stop completely at red lights.",
    "ex1_vi": "Để đi lại an toàn, người lái xe phải tuân thủ giới hạn tốc độ và dừng hẳn khi đèn đỏ."
  },
  {
    "id": 32,
    "word": "limits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɪmʌts/",
    "meaning": "giới hạn",
    "ex1": "On busy city streets, drivers must obey speed limits and stop completely at red lights.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, người lái xe phải tuân thủ giới hạn tốc độ và dừng hẳn khi đèn đỏ."
  },
  {
    "id": 33,
    "word": "stop",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈɑp/",
    "meaning": "dừng",
    "ex1": "During everyday travel, drivers must obey speed limits and stop completely at red lights.",
    "ex1_vi": "Trong việc đi lại hằng ngày, người lái xe phải tuân thủ giới hạn tốc độ và dừng hẳn khi đèn đỏ."
  },
  {
    "id": 34,
    "word": "completely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kʌmplˈitli/",
    "meaning": "hoàn toàn",
    "ex1": "For road safety, drivers must obey speed limits and stop completely at red lights.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, người lái xe phải tuân thủ giới hạn tốc độ và dừng hẳn khi đèn đỏ."
  },
  {
    "id": 35,
    "word": "red",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛd/",
    "meaning": "đỏ",
    "ex1": "In many neighborhoods, drivers must obey speed limits and stop completely at red lights.",
    "ex1_vi": "Ở nhiều khu phố, người lái xe phải tuân thủ giới hạn tốc độ và dừng hẳn khi đèn đỏ."
  },
  {
    "id": 36,
    "word": "lights",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪts/",
    "meaning": "đèn",
    "ex1": "On a normal weekday, drivers must obey speed limits and stop completely at red lights.",
    "ex1_vi": "Vào một ngày thường, người lái xe phải tuân thủ giới hạn tốc độ và dừng hẳn khi đèn đỏ."
  },
  {
    "id": 37,
    "word": "avoid",
    "type": "verb",
    "cat": "v",
    "phonetic": "/əvˈɔɪd/",
    "meaning": "tránh",
    "ex1": "They should avoid using mobile phones while driving because distractions are dangerous.",
    "ex1_vi": "Họ nên tránh dùng điện thoại di động khi lái xe vì sự xao nhãng rất nguy hiểm."
  },
  {
    "id": 38,
    "word": "using",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzɪŋ/",
    "meaning": "việc sử dụng",
    "ex1": "In daily city life, they should avoid using mobile phones while driving because distractions are dangerous.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, họ nên tránh dùng điện thoại di động khi lái xe vì sự xao nhãng rất nguy hiểm."
  },
  {
    "id": 39,
    "word": "mobile",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈoʊbʌl/",
    "meaning": "di động",
    "ex1": "For safe travel, they should avoid using mobile phones while driving because distractions are dangerous.",
    "ex1_vi": "Để đi lại an toàn, họ nên tránh dùng điện thoại di động khi lái xe vì sự xao nhãng rất nguy hiểm."
  },
  {
    "id": 40,
    "word": "phones",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈoʊnz/",
    "meaning": "điện thoại",
    "ex1": "On busy city streets, they should avoid using mobile phones while driving because distractions are dangerous.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, họ nên tránh dùng điện thoại di động khi lái xe vì sự xao nhãng rất nguy hiểm."
  },
  {
    "id": 41,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/waɪl/",
    "meaning": "trong khi",
    "ex1": "During everyday travel, they should avoid using mobile phones while driving because distractions are dangerous.",
    "ex1_vi": "Trong việc đi lại hằng ngày, họ nên tránh dùng điện thoại di động khi lái xe vì sự xao nhãng rất nguy hiểm."
  },
  {
    "id": 42,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkɔz/",
    "meaning": "bởi vì",
    "ex1": "For road safety, they should avoid using mobile phones while driving because distractions are dangerous.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, họ nên tránh dùng điện thoại di động khi lái xe vì sự xao nhãng rất nguy hiểm."
  },
  {
    "id": 43,
    "word": "distractions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪstrˈækʃʌnz/",
    "meaning": "sự xao nhãng",
    "ex1": "In many neighborhoods, they should avoid using mobile phones while driving because distractions are dangerous.",
    "ex1_vi": "Ở nhiều khu phố, họ nên tránh dùng điện thoại di động khi lái xe vì sự xao nhãng rất nguy hiểm."
  },
  {
    "id": 44,
    "word": "dangerous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈeɪndʒɝʌs/",
    "meaning": "nguy hiểm",
    "ex1": "On a normal weekday, they should avoid using mobile phones while driving because distractions are dangerous.",
    "ex1_vi": "Vào một ngày thường, họ nên tránh dùng điện thoại di động khi lái xe vì sự xao nhãng rất nguy hiểm."
  },
  {
    "id": 45,
    "word": "keeping",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈipɪŋ/",
    "meaning": "việc giữ; duy trì",
    "ex1": "Keeping enough distance from other vehicles makes driving much safer for everyone.",
    "ex1_vi": "Giữ đủ khoảng cách với các phương tiện khác làm cho việc lái xe an toàn hơn nhiều đối với mọi người."
  },
  {
    "id": 46,
    "word": "enough",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ɪnˈʌf/",
    "meaning": "đủ",
    "ex1": "In daily city life, keeping enough distance from other vehicles makes driving much safer for everyone.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, giữ đủ khoảng cách với các phương tiện khác làm cho việc lái xe an toàn hơn nhiều đối với mọi người."
  },
  {
    "id": 47,
    "word": "distance",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪstəns/",
    "meaning": "khoảng cách; cự ly",
    "ex1": "For safe travel, keeping enough distance from other vehicles makes driving much safer for everyone.",
    "ex1_vi": "Để đi lại an toàn, giữ đủ khoảng cách với các phương tiện khác làm cho việc lái xe an toàn hơn nhiều đối với mọi người."
  },
  {
    "id": 48,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm cho",
    "ex1": "On busy city streets, keeping enough distance from other vehicles makes driving much safer for everyone.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, giữ đủ khoảng cách với các phương tiện khác làm cho việc lái xe an toàn hơn nhiều đối với mọi người."
  },
  {
    "id": 49,
    "word": "much",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/mˈʌtʃ/",
    "meaning": "nhiều; rất",
    "ex1": "During everyday travel, keeping enough distance from other vehicles makes driving much safer for everyone.",
    "ex1_vi": "Trong việc đi lại hằng ngày, giữ đủ khoảng cách với các phương tiện khác làm cho việc lái xe an toàn hơn nhiều đối với mọi người."
  },
  {
    "id": 50,
    "word": "safer",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/seɪfɚ/",
    "meaning": "an toàn hơn",
    "ex1": "For road safety, keeping enough distance from other vehicles makes driving much safer for everyone.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, giữ đủ khoảng cách với các phương tiện khác làm cho việc lái xe an toàn hơn nhiều đối với mọi người."
  },
  {
    "id": 51,
    "word": "careful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɛɹfəl/",
    "meaning": "cẩn thận",
    "ex1": "Careful driving creates safer streets and happier communities.",
    "ex1_vi": "Lái xe cẩn thận tạo ra những con phố an toàn hơn và cộng đồng hạnh phúc hơn."
  },
  {
    "id": 52,
    "word": "creates",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪts/",
    "meaning": "tạo ra",
    "ex1": "In daily city life, careful driving creates safer streets and happier communities.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, lái xe cẩn thận tạo ra những con phố an toàn hơn và cộng đồng hạnh phúc hơn."
  },
  {
    "id": 53,
    "word": "streets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/strˈits/",
    "meaning": "các con phố",
    "ex1": "For safe travel, careful driving creates safer streets and happier communities.",
    "ex1_vi": "Để đi lại an toàn, lái xe cẩn thận tạo ra những con phố an toàn hơn và cộng đồng hạnh phúc hơn."
  },
  {
    "id": 54,
    "word": "happier",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/hæpiɚ/",
    "meaning": "vui vẻ hơn",
    "ex1": "On busy city streets, careful driving creates safer streets and happier communities.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, lái xe cẩn thận tạo ra những con phố an toàn hơn và cộng đồng hạnh phúc hơn."
  },
  {
    "id": 55,
    "word": "communities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌmjˈunʌtiz/",
    "meaning": "cộng đồng",
    "ex1": "During everyday travel, careful driving creates safer streets and happier communities.",
    "ex1_vi": "Trong việc đi lại hằng ngày, lái xe cẩn thận tạo ra những con phố an toàn hơn và cộng đồng hạnh phúc hơn."
  },
  {
    "id": 56,
    "word": "responsible",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rispˈɑnsʌbʌl/",
    "meaning": "có trách nhiệm",
    "ex1": "Responsible drivers show respect for other people by following traffic rules every day.",
    "ex1_vi": "Người lái xe có trách nhiệm thể hiện sự tôn trọng đối với người khác bằng cách tuân thủ luật giao thông mỗi ngày."
  },
  {
    "id": 57,
    "word": "show",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈoʊ/",
    "meaning": "cho thấy",
    "ex1": "In daily city life, responsible drivers show respect for other people by following traffic rules every day.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người lái xe có trách nhiệm thể hiện sự tôn trọng đối với người khác bằng cách tuân thủ luật giao thông mỗi ngày."
  },
  {
    "id": 58,
    "word": "respect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪspˈɛkt/",
    "meaning": "tôn trọng",
    "ex1": "For safe travel, responsible drivers show respect for other people by following traffic rules every day.",
    "ex1_vi": "Để đi lại an toàn, người lái xe có trách nhiệm thể hiện sự tôn trọng đối với người khác bằng cách tuân thủ luật giao thông mỗi ngày."
  },
  {
    "id": 59,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipəl/",
    "meaning": "mọi người",
    "ex1": "On busy city streets, responsible drivers show respect for other people by following traffic rules every day.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, người lái xe có trách nhiệm thể hiện sự tôn trọng đối với người khác bằng cách tuân thủ luật giao thông mỗi ngày."
  },
  {
    "id": 60,
    "word": "following",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɑloʊɪŋ/",
    "meaning": "việc tuân theo",
    "ex1": "During everyday travel, responsible drivers show respect for other people by following traffic rules every day.",
    "ex1_vi": "Trong việc đi lại hằng ngày, người lái xe có trách nhiệm thể hiện sự tôn trọng đối với người khác bằng cách tuân thủ luật giao thông mỗi ngày."
  },
  {
    "id": 61,
    "word": "traffic",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈæfɪk/",
    "meaning": "giao thông",
    "ex1": "For road safety, responsible drivers show respect for other people by following traffic rules every day.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, người lái xe có trách nhiệm thể hiện sự tôn trọng đối với người khác bằng cách tuân thủ luật giao thông mỗi ngày."
  },
  {
    "id": 62,
    "word": "rules",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈulz/",
    "meaning": "quy tắc",
    "ex1": "In many neighborhoods, responsible drivers show respect for other people by following traffic rules every day.",
    "ex1_vi": "Ở nhiều khu phố, người lái xe có trách nhiệm thể hiện sự tôn trọng đối với người khác bằng cách tuân thủ luật giao thông mỗi ngày."
  },
  {
    "id": 63,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "Good driving habits help everyone reach their destinations safely and comfortably.",
    "ex1_vi": "Những thói quen lái xe tốt giúp mọi người đến nơi an toàn và thoải mái."
  },
  {
    "id": 64,
    "word": "habits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hæbəts/",
    "meaning": "thói quen",
    "ex1": "In daily city life, good driving habits help everyone reach their destinations safely and comfortably.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, những thói quen lái xe tốt giúp mọi người đến nơi an toàn và thoải mái."
  },
  {
    "id": 65,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "For safe travel, good driving habits help everyone reach their destinations safely and comfortably.",
    "ex1_vi": "Để đi lại an toàn, những thói quen lái xe tốt giúp mọi người đến nơi an toàn và thoải mái."
  },
  {
    "id": 66,
    "word": "reach",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈitʃ/",
    "meaning": "đến; đạt tới",
    "ex1": "On busy city streets, good driving habits help everyone reach their destinations safely and comfortably.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, những thói quen lái xe tốt giúp mọi người đến nơi an toàn và thoải mái."
  },
  {
    "id": 67,
    "word": "destinations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˌɛstʌnˈeɪʃʌnz/",
    "meaning": "điểm đến",
    "ex1": "During everyday travel, good driving habits help everyone reach their destinations safely and comfortably.",
    "ex1_vi": "Trong việc đi lại hằng ngày, những thói quen lái xe tốt giúp mọi người đến nơi an toàn và thoải mái."
  },
  {
    "id": 68,
    "word": "safely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/seɪfli/",
    "meaning": "một cách an toàn",
    "ex1": "For road safety, good driving habits help everyone reach their destinations safely and comfortably.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, những thói quen lái xe tốt giúp mọi người đến nơi an toàn và thoải mái."
  },
  {
    "id": 69,
    "word": "comfortably",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈʌmfɚtəbli/",
    "meaning": "một cách thoải mái",
    "ex1": "In many neighborhoods, good driving habits help everyone reach their destinations safely and comfortably.",
    "ex1_vi": "Ở nhiều khu phố, những thói quen lái xe tốt giúp mọi người đến nơi an toàn và thoải mái."
  },
  {
    "id": 70,
    "word": "air",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛr/",
    "meaning": "không khí",
    "ex1": "Heavy traffic causes air pollution in many large cities every day.",
    "ex1_vi": "Giao thông đông đúc gây ô nhiễm không khí ở nhiều thành phố lớn mỗi ngày."
  },
  {
    "id": 71,
    "word": "pollution",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pəlˈuːʃən/",
    "meaning": "ô nhiễm",
    "ex1": "In daily city life, heavy traffic causes air pollution in many large cities every day.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, giao thông đông đúc gây ô nhiễm không khí ở nhiều thành phố lớn mỗi ngày."
  },
  {
    "id": 72,
    "word": "heavy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛvi/",
    "meaning": "đông đúc; nặng",
    "ex1": "For safe travel, heavy traffic causes air pollution in many large cities every day.",
    "ex1_vi": "Để đi lại an toàn, giao thông đông đúc gây ô nhiễm không khí ở nhiều thành phố lớn mỗi ngày."
  },
  {
    "id": 73,
    "word": "causes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈɑzʌz/",
    "meaning": "gây ra",
    "ex1": "On busy city streets, heavy traffic causes air pollution in many large cities every day.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, giao thông đông đúc gây ô nhiễm không khí ở nhiều thành phố lớn mỗi ngày."
  },
  {
    "id": 74,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mɛni/",
    "meaning": "nhiều",
    "ex1": "During everyday travel, heavy traffic causes air pollution in many large cities every day.",
    "ex1_vi": "Trong việc đi lại hằng ngày, giao thông đông đúc gây ô nhiễm không khí ở nhiều thành phố lớn mỗi ngày."
  },
  {
    "id": 75,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑɹdʒ/",
    "meaning": "lớn",
    "ex1": "For road safety, heavy traffic causes air pollution in many large cities every day.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, giao thông đông đúc gây ô nhiễm không khí ở nhiều thành phố lớn mỗi ngày."
  },
  {
    "id": 76,
    "word": "cities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪtiz/",
    "meaning": "các thành phố",
    "ex1": "In many neighborhoods, heavy traffic causes air pollution in many large cities every day.",
    "ex1_vi": "Ở nhiều khu phố, giao thông đông đúc gây ô nhiễm không khí ở nhiều thành phố lớn mỗi ngày."
  },
  {
    "id": 77,
    "word": "cars",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑrz/",
    "meaning": "ô tô",
    "ex1": "Cars, buses, trucks, and motorbikes produce smoke that makes the air dirty.",
    "ex1_vi": "Ô tô, xe buýt, xe tải và xe máy tạo ra khói khiến không khí bẩn."
  },
  {
    "id": 78,
    "word": "buses",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʌsɪz/",
    "meaning": "xe buýt",
    "ex1": "In daily city life, cars, buses, trucks, and motorbikes produce smoke that makes the air dirty.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, ô tô, xe buýt, xe tải và xe máy tạo ra khói khiến không khí bẩn."
  },
  {
    "id": 79,
    "word": "trucks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈʌks/",
    "meaning": "xe tải",
    "ex1": "For safe travel, cars, buses, trucks, and motorbikes produce smoke that makes the air dirty.",
    "ex1_vi": "Để đi lại an toàn, ô tô, xe buýt, xe tải và xe máy tạo ra khói khiến không khí bẩn."
  },
  {
    "id": 80,
    "word": "motorbikes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈoʊtɝbˌaɪks/",
    "meaning": "xe máy",
    "ex1": "On busy city streets, cars, buses, trucks, and motorbikes produce smoke that makes the air dirty.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, ô tô, xe buýt, xe tải và xe máy tạo ra khói khiến không khí bẩn."
  },
  {
    "id": 81,
    "word": "produce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prəˈdus/",
    "meaning": "sản xuất",
    "ex1": "During everyday travel, cars, buses, trucks, and motorbikes produce smoke that makes the air dirty.",
    "ex1_vi": "Trong việc đi lại hằng ngày, ô tô, xe buýt, xe tải và xe máy tạo ra khói khiến không khí bẩn."
  },
  {
    "id": 82,
    "word": "smoke",
    "type": "noun",
    "cat": "n",
    "phonetic": "/smˈoʊk/",
    "meaning": "khói",
    "ex1": "For road safety, cars, buses, trucks, and motorbikes produce smoke that makes the air dirty.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, ô tô, xe buýt, xe tải và xe máy tạo ra khói khiến không khí bẩn."
  },
  {
    "id": 83,
    "word": "dirty",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɝti/",
    "meaning": "bẩn",
    "ex1": "In many neighborhoods, cars, buses, trucks, and motorbikes produce smoke that makes the air dirty.",
    "ex1_vi": "Ở nhiều khu phố, ô tô, xe buýt, xe tải và xe máy tạo ra khói khiến không khí bẩn."
  },
  {
    "id": 84,
    "word": "poor",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈur/",
    "meaning": "kém",
    "ex1": "Poor air quality can affect people's health, especially children and older adults living nearby.",
    "ex1_vi": "Chất lượng không khí kém có thể ảnh hưởng đến sức khỏe của mọi người, đặc biệt là trẻ em và người lớn tuổi sống gần đó."
  },
  {
    "id": 85,
    "word": "quality",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kwˈɑlʌti/",
    "meaning": "chất lượng",
    "ex1": "In daily city life, poor air quality can affect people's health, especially children and older adults living nearby.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, chất lượng không khí kém có thể ảnh hưởng đến sức khỏe của mọi người, đặc biệt là trẻ em và người lớn tuổi sống gần đó."
  },
  {
    "id": 86,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "For safe travel, poor air quality can affect people's health, especially children and older adults living nearby.",
    "ex1_vi": "Để đi lại an toàn, chất lượng không khí kém có thể ảnh hưởng đến sức khỏe của mọi người, đặc biệt là trẻ em và người lớn tuổi sống gần đó."
  },
  {
    "id": 87,
    "word": "affect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌfˈɛkt/",
    "meaning": "ảnh hưởng",
    "ex1": "On busy city streets, poor air quality can affect people's health, especially children and older adults living nearby.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, chất lượng không khí kém có thể ảnh hưởng đến sức khỏe của mọi người, đặc biệt là trẻ em và người lớn tuổi sống gần đó."
  },
  {
    "id": 88,
    "word": "people's",
    "type": "possessive noun",
    "cat": "n",
    "phonetic": "/pˈipʌlz/",
    "meaning": "của mọi người",
    "ex1": "During everyday travel, poor air quality can affect people's health, especially children and older adults living nearby.",
    "ex1_vi": "Trong việc đi lại hằng ngày, chất lượng không khí kém có thể ảnh hưởng đến sức khỏe của mọi người, đặc biệt là trẻ em và người lớn tuổi sống gần đó."
  },
  {
    "id": 89,
    "word": "health",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛlθ/",
    "meaning": "sức khỏe",
    "ex1": "For road safety, poor air quality can affect people's health, especially children and older adults living nearby.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, chất lượng không khí kém có thể ảnh hưởng đến sức khỏe của mọi người, đặc biệt là trẻ em và người lớn tuổi sống gần đó."
  },
  {
    "id": 90,
    "word": "especially",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɪspˈɛʃəli/",
    "meaning": "đặc biệt",
    "ex1": "In many neighborhoods, poor air quality can affect people's health, especially children and older adults living nearby.",
    "ex1_vi": "Ở nhiều khu phố, chất lượng không khí kém có thể ảnh hưởng đến sức khỏe của mọi người, đặc biệt là trẻ em và người lớn tuổi sống gần đó."
  },
  {
    "id": 91,
    "word": "children",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃɪldrən/",
    "meaning": "trẻ em",
    "ex1": "On a normal weekday, poor air quality can affect people's health, especially children and older adults living nearby.",
    "ex1_vi": "Vào một ngày thường, chất lượng không khí kém có thể ảnh hưởng đến sức khỏe của mọi người, đặc biệt là trẻ em và người lớn tuổi sống gần đó."
  },
  {
    "id": 92,
    "word": "older",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈoʊldɝ/",
    "meaning": "lớn tuổi hơn",
    "ex1": "Poor air quality can affect people's health, especially children and older adults living nearby.",
    "ex1_vi": "Chất lượng không khí kém có thể ảnh hưởng đến sức khỏe của mọi người, đặc biệt là trẻ em và người lớn tuổi sống gần đó."
  },
  {
    "id": 93,
    "word": "adults",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ədʌlts/",
    "meaning": "người lớn",
    "ex1": "In daily city life, poor air quality can affect people's health, especially children and older adults living nearby.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, chất lượng không khí kém có thể ảnh hưởng đến sức khỏe của mọi người, đặc biệt là trẻ em và người lớn tuổi sống gần đó."
  },
  {
    "id": 94,
    "word": "living",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lɪvɪŋ/",
    "meaning": "sống; việc sống",
    "ex1": "For safe travel, poor air quality can affect people's health, especially children and older adults living nearby.",
    "ex1_vi": "Để đi lại an toàn, chất lượng không khí kém có thể ảnh hưởng đến sức khỏe của mọi người, đặc biệt là trẻ em và người lớn tuổi sống gần đó."
  },
  {
    "id": 95,
    "word": "nearby",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nɪrbaɪ/",
    "meaning": "gần đó",
    "ex1": "On busy city streets, poor air quality can affect people's health, especially children and older adults living nearby.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, chất lượng không khí kém có thể ảnh hưởng đến sức khỏe của mọi người, đặc biệt là trẻ em và người lớn tuổi sống gần đó."
  },
  {
    "id": 96,
    "word": "reduce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹədˈus/",
    "meaning": "giảm",
    "ex1": "People can help reduce pollution by using public transportation more often.",
    "ex1_vi": "Mọi người có thể giúp giảm ô nhiễm bằng cách sử dụng phương tiện công cộng thường xuyên hơn."
  },
  {
    "id": 97,
    "word": "public",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈʌblɪk/",
    "meaning": "công cộng",
    "ex1": "In daily city life, people can help reduce pollution by using public transportation more often.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, mọi người có thể giúp giảm ô nhiễm bằng cách sử dụng phương tiện công cộng thường xuyên hơn."
  },
  {
    "id": 98,
    "word": "transportation",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˌænspɝtˈeɪʃʌn/",
    "meaning": "giao thông; phương tiện đi lại",
    "ex1": "For safe travel, people can help reduce pollution by using public transportation more often.",
    "ex1_vi": "Để đi lại an toàn, mọi người có thể giúp giảm ô nhiễm bằng cách sử dụng phương tiện công cộng thường xuyên hơn."
  },
  {
    "id": 99,
    "word": "more",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mɔr/",
    "meaning": "nhiều hơn",
    "ex1": "On busy city streets, people can help reduce pollution by using public transportation more often.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, mọi người có thể giúp giảm ô nhiễm bằng cách sử dụng phương tiện công cộng thường xuyên hơn."
  },
  {
    "id": 100,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɔfən/",
    "meaning": "thường xuyên",
    "ex1": "During everyday travel, people can help reduce pollution by using public transportation more often.",
    "ex1_vi": "Trong việc đi lại hằng ngày, mọi người có thể giúp giảm ô nhiễm bằng cách sử dụng phương tiện công cộng thường xuyên hơn."
  },
  {
    "id": 101,
    "word": "walking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɔkɪŋ/",
    "meaning": "việc đi bộ",
    "ex1": "Walking, cycling, or sharing cars also lowers the number of vehicles on roads.",
    "ex1_vi": "Đi bộ, đạp xe hoặc đi chung ô tô cũng làm giảm số lượng phương tiện trên đường."
  },
  {
    "id": 102,
    "word": "cycling",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈaɪkʌlɪŋ/",
    "meaning": "việc đạp xe",
    "ex1": "In daily city life, walking, cycling, or sharing cars also lowers the number of vehicles on roads.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, đi bộ, đạp xe hoặc đi chung ô tô cũng làm giảm số lượng phương tiện trên đường."
  },
  {
    "id": 103,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ɔr/",
    "meaning": "hoặc",
    "ex1": "For safe travel, walking, cycling, or sharing cars also lowers the number of vehicles on roads.",
    "ex1_vi": "Để đi lại an toàn, đi bộ, đạp xe hoặc đi chung ô tô cũng làm giảm số lượng phương tiện trên đường."
  },
  {
    "id": 104,
    "word": "sharing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈɛrɪŋ/",
    "meaning": "việc chia sẻ; đi chung",
    "ex1": "On busy city streets, walking, cycling, or sharing cars also lowers the number of vehicles on roads.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, đi bộ, đạp xe hoặc đi chung ô tô cũng làm giảm số lượng phương tiện trên đường."
  },
  {
    "id": 105,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "During everyday travel, walking, cycling, or sharing cars also lowers the number of vehicles on roads.",
    "ex1_vi": "Trong việc đi lại hằng ngày, đi bộ, đạp xe hoặc đi chung ô tô cũng làm giảm số lượng phương tiện trên đường."
  },
  {
    "id": 106,
    "word": "lowers",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈoʊɝz/",
    "meaning": "làm giảm",
    "ex1": "For road safety, walking, cycling, or sharing cars also lowers the number of vehicles on roads.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, đi bộ, đạp xe hoặc đi chung ô tô cũng làm giảm số lượng phương tiện trên đường."
  },
  {
    "id": 107,
    "word": "number",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈʌmbɚ/",
    "meaning": "số",
    "ex1": "In many neighborhoods, walking, cycling, or sharing cars also lowers the number of vehicles on roads.",
    "ex1_vi": "Ở nhiều khu phố, đi bộ, đạp xe hoặc đi chung ô tô cũng làm giảm số lượng phương tiện trên đường."
  },
  {
    "id": 108,
    "word": "planting",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈæntɪŋ/",
    "meaning": "việc trồng",
    "ex1": "Planting more trees helps improve air quality in busy neighborhoods too.",
    "ex1_vi": "Trồng thêm cây cũng giúp cải thiện chất lượng không khí ở những khu phố đông đúc."
  },
  {
    "id": 109,
    "word": "trees",
    "type": "noun",
    "cat": "n",
    "phonetic": "/triz/",
    "meaning": "cây",
    "ex1": "In daily city life, planting more trees helps improve air quality in busy neighborhoods too.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, trồng thêm cây cũng giúp cải thiện chất lượng không khí ở những khu phố đông đúc."
  },
  {
    "id": 110,
    "word": "improve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɪmpɹˈuːv/",
    "meaning": "cải thiện",
    "ex1": "For safe travel, planting more trees helps improve air quality in busy neighborhoods too.",
    "ex1_vi": "Để đi lại an toàn, trồng thêm cây cũng giúp cải thiện chất lượng không khí ở những khu phố đông đúc."
  },
  {
    "id": 111,
    "word": "neighborhoods",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈeɪbɝhˌʊdz/",
    "meaning": "các khu phố",
    "ex1": "On busy city streets, planting more trees helps improve air quality in busy neighborhoods too.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, trồng thêm cây cũng giúp cải thiện chất lượng không khí ở những khu phố đông đúc."
  },
  {
    "id": 112,
    "word": "too",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tu/",
    "meaning": "quá",
    "ex1": "During everyday travel, planting more trees helps improve air quality in busy neighborhoods too.",
    "ex1_vi": "Trong việc đi lại hằng ngày, trồng thêm cây cũng giúp cải thiện chất lượng không khí ở những khu phố đông đúc."
  },
  {
    "id": 113,
    "word": "cleaner",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈklinər/",
    "meaning": "sạch hơn",
    "ex1": "Cleaner transportation benefits everyone in the city.",
    "ex1_vi": "Phương tiện sạch hơn mang lại lợi ích cho mọi người trong thành phố."
  },
  {
    "id": 114,
    "word": "benefits",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɛnəfɪts/",
    "meaning": "mang lại lợi ích",
    "ex1": "In daily city life, cleaner transportation benefits everyone in the city.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, phương tiện sạch hơn mang lại lợi ích cho mọi người trong thành phố."
  },
  {
    "id": 115,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "Small daily actions can reduce pollution and protect nature.",
    "ex1_vi": "Những hành động nhỏ hằng ngày có thể giảm ô nhiễm và bảo vệ thiên nhiên."
  },
  {
    "id": 116,
    "word": "daily",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈeɪli/",
    "meaning": "hằng ngày",
    "ex1": "In daily city life, small daily actions can reduce pollution and protect nature.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, những hành động nhỏ hằng ngày có thể giảm ô nhiễm và bảo vệ thiên nhiên."
  },
  {
    "id": 117,
    "word": "actions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈækʃʌnz/",
    "meaning": "hành động",
    "ex1": "For safe travel, small daily actions can reduce pollution and protect nature.",
    "ex1_vi": "Để đi lại an toàn, những hành động nhỏ hằng ngày có thể giảm ô nhiễm và bảo vệ thiên nhiên."
  },
  {
    "id": 118,
    "word": "protect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹətˈɛkt/",
    "meaning": "bảo vệ",
    "ex1": "On busy city streets, small daily actions can reduce pollution and protect nature.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, những hành động nhỏ hằng ngày có thể giảm ô nhiễm và bảo vệ thiên nhiên."
  },
  {
    "id": 119,
    "word": "nature",
    "type": "noun",
    "cat": "n",
    "phonetic": "/neɪtʃɚ/",
    "meaning": "thiên nhiên",
    "ex1": "During everyday travel, small daily actions can reduce pollution and protect nature.",
    "ex1_vi": "Trong việc đi lại hằng ngày, những hành động nhỏ hằng ngày có thể giảm ô nhiễm và bảo vệ thiên nhiên."
  },
  {
    "id": 120,
    "word": "healthy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlθi/",
    "meaning": "lành mạnh",
    "ex1": "Healthy air makes life better for families, workers, students, and future generations everywhere.",
    "ex1_vi": "Không khí trong lành làm cuộc sống tốt hơn cho gia đình, người lao động, học sinh và các thế hệ tương lai ở khắp nơi."
  },
  {
    "id": 121,
    "word": "life",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪf/",
    "meaning": "cuộc sống",
    "ex1": "In daily city life, healthy air makes life better for families, workers, students, and future generations everywhere.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, không khí trong lành làm cuộc sống tốt hơn cho gia đình, người lao động, học sinh và các thế hệ tương lai ở khắp nơi."
  },
  {
    "id": 122,
    "word": "better",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɛɾɚ/",
    "meaning": "tốt hơn",
    "ex1": "For safe travel, healthy air makes life better for families, workers, students, and future generations everywhere.",
    "ex1_vi": "Để đi lại an toàn, không khí trong lành làm cuộc sống tốt hơn cho gia đình, người lao động, học sinh và các thế hệ tương lai ở khắp nơi."
  },
  {
    "id": 123,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fæməliz/",
    "meaning": "gia đình",
    "ex1": "On busy city streets, healthy air makes life better for families, workers, students, and future generations everywhere.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, không khí trong lành làm cuộc sống tốt hơn cho gia đình, người lao động, học sinh và các thế hệ tương lai ở khắp nơi."
  },
  {
    "id": 124,
    "word": "workers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɜːkɚz/",
    "meaning": "nhân viên",
    "ex1": "During everyday travel, healthy air makes life better for families, workers, students, and future generations everywhere.",
    "ex1_vi": "Trong việc đi lại hằng ngày, không khí trong lành làm cuộc sống tốt hơn cho gia đình, người lao động, học sinh và các thế hệ tương lai ở khắp nơi."
  },
  {
    "id": 125,
    "word": "students",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈudʌnts/",
    "meaning": "học sinh; sinh viên",
    "ex1": "For road safety, healthy air makes life better for families, workers, students, and future generations everywhere.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, không khí trong lành làm cuộc sống tốt hơn cho gia đình, người lao động, học sinh và các thế hệ tương lai ở khắp nơi."
  },
  {
    "id": 126,
    "word": "future",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fjutʃɚ/",
    "meaning": "tương lai",
    "ex1": "In many neighborhoods, healthy air makes life better for families, workers, students, and future generations everywhere.",
    "ex1_vi": "Ở nhiều khu phố, không khí trong lành làm cuộc sống tốt hơn cho gia đình, người lao động, học sinh và các thế hệ tương lai ở khắp nơi."
  },
  {
    "id": 127,
    "word": "generations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒɛnɚeɪʃənz/",
    "meaning": "thế hệ",
    "ex1": "On a normal weekday, healthy air makes life better for families, workers, students, and future generations everywhere.",
    "ex1_vi": "Vào một ngày thường, không khí trong lành làm cuộc sống tốt hơn cho gia đình, người lao động, học sinh và các thế hệ tương lai ở khắp nơi."
  },
  {
    "id": 128,
    "word": "everywhere",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɛvriwɛr/",
    "meaning": "khắp mọi nơi",
    "ex1": "Healthy air makes life better for families, workers, students, and future generations everywhere.",
    "ex1_vi": "Không khí trong lành làm cuộc sống tốt hơn cho gia đình, người lao động, học sinh và các thế hệ tương lai ở khắp nơi."
  },
  {
    "id": 129,
    "word": "bus",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʌs/",
    "meaning": "xe buýt",
    "ex1": "Taking a bus is an easy way to travel around the city.",
    "ex1_vi": "Đi xe buýt là một cách dễ dàng để di chuyển quanh thành phố."
  },
  {
    "id": 130,
    "word": "ride",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪd/",
    "meaning": "chuyến đi",
    "ex1": "A bus ride can be an easy way to travel around the city.",
    "ex1_vi": "Một chuyến xe buýt có thể là cách dễ dàng để đi lại quanh thành phố."
  },
  {
    "id": 131,
    "word": "taking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪkɪŋ/",
    "meaning": "việc đi; việc lấy",
    "ex1": "In daily city life, taking a bus is an easy way to travel around the city.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, đi xe buýt là một cách dễ dàng để di chuyển quanh thành phố."
  },
  {
    "id": 132,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈiːzi/",
    "meaning": "dễ",
    "ex1": "For safe travel, taking a bus is an easy way to travel around the city.",
    "ex1_vi": "Để đi lại an toàn, đi xe buýt là một cách dễ dàng để di chuyển quanh thành phố."
  },
  {
    "id": 133,
    "word": "way",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪ/",
    "meaning": "cách; đường",
    "ex1": "On busy city streets, taking a bus is an easy way to travel around the city.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, đi xe buýt là một cách dễ dàng để di chuyển quanh thành phố."
  },
  {
    "id": 134,
    "word": "travel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tɹˈævəl/",
    "meaning": "di chuyển; đi lại",
    "ex1": "During everyday travel, taking a bus is an easy way to travel around the city.",
    "ex1_vi": "Trong việc đi lại hằng ngày, đi xe buýt là một cách dễ dàng để di chuyển quanh thành phố."
  },
  {
    "id": 135,
    "word": "visitors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪzɪtɝz/",
    "meaning": "du khách",
    "ex1": "Many students, workers, and visitors use buses every day because they are affordable and convenient.",
    "ex1_vi": "Nhiều học sinh, người lao động và du khách sử dụng xe buýt mỗi ngày vì chúng có giá phải chăng và tiện lợi."
  },
  {
    "id": 136,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "In daily city life, many students, workers, and visitors use buses every day because they are affordable and convenient.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, nhiều học sinh, người lao động và du khách sử dụng xe buýt mỗi ngày vì chúng có giá phải chăng và tiện lợi."
  },
  {
    "id": 137,
    "word": "affordable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌfˈɔrdʌbʌl/",
    "meaning": "có giá phải chăng",
    "ex1": "For safe travel, many students, workers, and visitors use buses every day because they are affordable and convenient.",
    "ex1_vi": "Để đi lại an toàn, nhiều học sinh, người lao động và du khách sử dụng xe buýt mỗi ngày vì chúng có giá phải chăng và tiện lợi."
  },
  {
    "id": 138,
    "word": "convenient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kʌnvˈinjʌnt/",
    "meaning": "tiện lợi",
    "ex1": "On busy city streets, many students, workers, and visitors use buses every day because they are affordable and convenient.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, nhiều học sinh, người lao động và du khách sử dụng xe buýt mỗi ngày vì chúng có giá phải chăng và tiện lợi."
  },
  {
    "id": 139,
    "word": "places",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪsəz/",
    "meaning": "nơi",
    "ex1": "Buses stop at many places, making travel simple for everyone nearby.",
    "ex1_vi": "Xe buýt dừng ở nhiều nơi, làm cho việc đi lại trở nên đơn giản đối với mọi người ở gần."
  },
  {
    "id": 140,
    "word": "making",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪkɪŋ/",
    "meaning": "việc làm cho",
    "ex1": "In daily city life, buses stop at many places, making travel simple for everyone nearby.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, xe buýt dừng ở nhiều nơi, làm cho việc đi lại trở nên đơn giản đối với mọi người ở gần."
  },
  {
    "id": 141,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "For safe travel, buses stop at many places, making travel simple for everyone nearby.",
    "ex1_vi": "Để đi lại an toàn, xe buýt dừng ở nhiều nơi, làm cho việc đi lại trở nên đơn giản đối với mọi người ở gần."
  },
  {
    "id": 142,
    "word": "passengers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈæsʌndʒɝz/",
    "meaning": "hành khách",
    "ex1": "Passengers should arrive early and wait politely at the bus stop.",
    "ex1_vi": "Hành khách nên đến sớm và lịch sự chờ tại trạm xe buýt."
  },
  {
    "id": 143,
    "word": "arrive",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɚɹˈaɪv/",
    "meaning": "đến",
    "ex1": "In daily city life, passengers should arrive early and wait politely at the bus stop.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, hành khách nên đến sớm và lịch sự chờ tại trạm xe buýt."
  },
  {
    "id": 144,
    "word": "early",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɝli/",
    "meaning": "sớm",
    "ex1": "For safe travel, passengers should arrive early and wait politely at the bus stop.",
    "ex1_vi": "Để đi lại an toàn, hành khách nên đến sớm và lịch sự chờ tại trạm xe buýt."
  },
  {
    "id": 145,
    "word": "wait",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈeɪt/",
    "meaning": "chờ",
    "ex1": "On busy city streets, passengers should arrive early and wait politely at the bus stop.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, hành khách nên đến sớm và lịch sự chờ tại trạm xe buýt."
  },
  {
    "id": 146,
    "word": "politely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/pʌlˈaɪtli/",
    "meaning": "một cách lịch sự",
    "ex1": "During everyday travel, passengers should arrive early and wait politely at the bus stop.",
    "ex1_vi": "Trong việc đi lại hằng ngày, hành khách nên đến sớm và lịch sự chờ tại trạm xe buýt."
  },
  {
    "id": 147,
    "word": "need",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nid/",
    "meaning": "cần",
    "ex1": "They need to buy tickets, keep the bus clean, and respect other passengers.",
    "ex1_vi": "Họ cần mua vé, giữ xe buýt sạch sẽ và tôn trọng những hành khách khác."
  },
  {
    "id": 148,
    "word": "buy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈaɪ/",
    "meaning": "mua",
    "ex1": "In daily city life, they need to buy tickets, keep the bus clean, and respect other passengers.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, họ cần mua vé, giữ xe buýt sạch sẽ và tôn trọng những hành khách khác."
  },
  {
    "id": 149,
    "word": "tickets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɪkʌts/",
    "meaning": "vé",
    "ex1": "For safe travel, they need to buy tickets, keep the bus clean, and respect other passengers.",
    "ex1_vi": "Để đi lại an toàn, họ cần mua vé, giữ xe buýt sạch sẽ và tôn trọng những hành khách khác."
  },
  {
    "id": 150,
    "word": "keep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈip/",
    "meaning": "giữ; duy trì",
    "ex1": "On busy city streets, they need to buy tickets, keep the bus clean, and respect other passengers.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, họ cần mua vé, giữ xe buýt sạch sẽ và tôn trọng những hành khách khác."
  },
  {
    "id": 151,
    "word": "clean",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈin/",
    "meaning": "sạch; làm sạch",
    "ex1": "During everyday travel, they need to buy tickets, keep the bus clean, and respect other passengers.",
    "ex1_vi": "Trong việc đi lại hằng ngày, họ cần mua vé, giữ xe buýt sạch sẽ và tôn trọng những hành khách khác."
  },
  {
    "id": 152,
    "word": "speaking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/spˈikɪŋ/",
    "meaning": "việc nói",
    "ex1": "Speaking quietly and giving seats to older people show good manners every day.",
    "ex1_vi": "Nói chuyện nhỏ nhẹ và nhường ghế cho người lớn tuổi thể hiện cách cư xử tốt mỗi ngày."
  },
  {
    "id": 153,
    "word": "quietly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kwˈaɪʌtli/",
    "meaning": "một cách nhỏ nhẹ",
    "ex1": "In daily city life, speaking quietly and giving seats to older people show good manners every day.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, nói chuyện nhỏ nhẹ và nhường ghế cho người lớn tuổi thể hiện cách cư xử tốt mỗi ngày."
  },
  {
    "id": 154,
    "word": "giving",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvɪŋ/",
    "meaning": "việc nhường; việc cho",
    "ex1": "For safe travel, speaking quietly and giving seats to older people show good manners every day.",
    "ex1_vi": "Để đi lại an toàn, nói chuyện nhỏ nhẹ và nhường ghế cho người lớn tuổi thể hiện cách cư xử tốt mỗi ngày."
  },
  {
    "id": 155,
    "word": "seats",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈits/",
    "meaning": "ghế",
    "ex1": "On busy city streets, speaking quietly and giving seats to older people show good manners every day.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, nói chuyện nhỏ nhẹ và nhường ghế cho người lớn tuổi thể hiện cách cư xử tốt mỗi ngày."
  },
  {
    "id": 156,
    "word": "manners",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈænɝz/",
    "meaning": "cách cư xử",
    "ex1": "During everyday travel, speaking quietly and giving seats to older people show good manners every day.",
    "ex1_vi": "Trong việc đi lại hằng ngày, nói chuyện nhỏ nhẹ và nhường ghế cho người lớn tuổi thể hiện cách cư xử tốt mỗi ngày."
  },
  {
    "id": 157,
    "word": "choose",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈuːz/",
    "meaning": "chọn",
    "ex1": "More people should choose buses instead of private cars.",
    "ex1_vi": "Nhiều người nên chọn xe buýt thay vì ô tô riêng."
  },
  {
    "id": 158,
    "word": "instead",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˌɪnstˈɛd/",
    "meaning": "thay vì",
    "ex1": "In daily city life, more people should choose buses instead of private cars.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, nhiều người nên chọn xe buýt thay vì ô tô riêng."
  },
  {
    "id": 159,
    "word": "private",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/prˈaɪvʌt/",
    "meaning": "riêng; cá nhân",
    "ex1": "For safe travel, more people should choose buses instead of private cars.",
    "ex1_vi": "Để đi lại an toàn, nhiều người nên chọn xe buýt thay vì ô tô riêng."
  },
  {
    "id": 160,
    "word": "journeys",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɝniz/",
    "meaning": "hành trình",
    "ex1": "Public transportation makes daily journeys cheaper, safer, and better for the environment.",
    "ex1_vi": "Phương tiện công cộng làm cho hành trình hằng ngày rẻ hơn, an toàn hơn và tốt hơn cho môi trường."
  },
  {
    "id": 161,
    "word": "cheaper",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/tʃˈipɝ/",
    "meaning": "rẻ hơn",
    "ex1": "In daily city life, public transportation makes daily journeys cheaper, safer, and better for the environment.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, phương tiện công cộng làm cho hành trình hằng ngày rẻ hơn, an toàn hơn và tốt hơn cho môi trường."
  },
  {
    "id": 162,
    "word": "environment",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪnvaɪrənmənt/",
    "meaning": "môi trường",
    "ex1": "For safe travel, public transportation makes daily journeys cheaper, safer, and better for the environment.",
    "ex1_vi": "Để đi lại an toàn, phương tiện công cộng làm cho hành trình hằng ngày rẻ hơn, an toàn hơn và tốt hơn cho môi trường."
  },
  {
    "id": 163,
    "word": "one",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/wˈʌn/",
    "meaning": "một",
    "ex1": "Walking is one of the healthiest ways to travel in the city.",
    "ex1_vi": "Đi bộ là một trong những cách di chuyển lành mạnh nhất trong thành phố."
  },
  {
    "id": 164,
    "word": "healthiest",
    "type": "superlative adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlθiɪst/",
    "meaning": "lành mạnh nhất",
    "ex1": "In daily city life, walking is one of the healthiest ways to travel in the city.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, đi bộ là một trong những cách di chuyển lành mạnh nhất trong thành phố."
  },
  {
    "id": 165,
    "word": "ways",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪz/",
    "meaning": "cách thức",
    "ex1": "For safe travel, walking is one of the healthiest ways to travel in the city.",
    "ex1_vi": "Để đi lại an toàn, đi bộ là một trong những cách di chuyển lành mạnh nhất trong thành phố."
  },
  {
    "id": 166,
    "word": "walk",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɔk/",
    "meaning": "đi bộ",
    "ex1": "Many people walk to school, work, shops, or nearby parks every day.",
    "ex1_vi": "Nhiều người đi bộ đến trường, nơi làm việc, cửa hàng hoặc công viên gần đó mỗi ngày."
  },
  {
    "id": 167,
    "word": "school",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈul/",
    "meaning": "trường học",
    "ex1": "In daily city life, many people walk to school, work, shops, or nearby parks every day.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, nhiều người đi bộ đến trường, nơi làm việc, cửa hàng hoặc công viên gần đó mỗi ngày."
  },
  {
    "id": 168,
    "word": "work",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝk/",
    "meaning": "nơi làm việc; công việc",
    "ex1": "For safe travel, many people walk to school, work, shops, or nearby parks every day.",
    "ex1_vi": "Để đi lại an toàn, nhiều người đi bộ đến trường, nơi làm việc, cửa hàng hoặc công viên gần đó mỗi ngày."
  },
  {
    "id": 169,
    "word": "shops",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɑps/",
    "meaning": "cửa hàng",
    "ex1": "On busy city streets, many people walk to school, work, shops, or nearby parks every day.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, nhiều người đi bộ đến trường, nơi làm việc, cửa hàng hoặc công viên gần đó mỗi ngày."
  },
  {
    "id": 170,
    "word": "parks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑːɹks/",
    "meaning": "công viên",
    "ex1": "During everyday travel, many people walk to school, work, shops, or nearby parks every day.",
    "ex1_vi": "Trong việc đi lại hằng ngày, nhiều người đi bộ đến trường, nơi làm việc, cửa hàng hoặc công viên gần đó mỗi ngày."
  },
  {
    "id": 171,
    "word": "costs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑsts/",
    "meaning": "chi phí",
    "ex1": "Walking costs nothing and helps people enjoy fresh air and regular exercise together.",
    "ex1_vi": "Đi bộ không tốn chi phí và giúp mọi người tận hưởng không khí trong lành cùng việc tập thể dục thường xuyên."
  },
  {
    "id": 172,
    "word": "nothing",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/nˈʌθɪŋ/",
    "meaning": "không gì",
    "ex1": "In daily city life, walking costs nothing and helps people enjoy fresh air and regular exercise together.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, đi bộ không tốn chi phí và giúp mọi người tận hưởng không khí trong lành cùng việc tập thể dục thường xuyên."
  },
  {
    "id": 173,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɛndʒɔɪ/",
    "meaning": "thích; tận hưởng",
    "ex1": "For safe travel, walking costs nothing and helps people enjoy fresh air and regular exercise together.",
    "ex1_vi": "Để đi lại an toàn, đi bộ không tốn chi phí và giúp mọi người tận hưởng không khí trong lành cùng việc tập thể dục thường xuyên."
  },
  {
    "id": 174,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fɹˈɛʃ/",
    "meaning": "tươi; trong lành",
    "ex1": "On busy city streets, walking costs nothing and helps people enjoy fresh air and regular exercise together.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, đi bộ không tốn chi phí và giúp mọi người tận hưởng không khí trong lành cùng việc tập thể dục thường xuyên."
  },
  {
    "id": 175,
    "word": "regular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɹˈɛɡjəlɚ/",
    "meaning": "đều đặn; định kỳ",
    "ex1": "During everyday travel, walking costs nothing and helps people enjoy fresh air and regular exercise together.",
    "ex1_vi": "Trong việc đi lại hằng ngày, đi bộ không tốn chi phí và giúp mọi người tận hưởng không khí trong lành cùng việc tập thể dục thường xuyên."
  },
  {
    "id": 176,
    "word": "exercise",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛksɚsˌaɪz/",
    "meaning": "tập thể dục",
    "ex1": "For road safety, walking costs nothing and helps people enjoy fresh air and regular exercise together.",
    "ex1_vi": "Để bảo đảm an toàn đường bộ, đi bộ không tốn chi phí và giúp mọi người tận hưởng không khí trong lành cùng việc tập thể dục thường xuyên."
  },
  {
    "id": 177,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/təɡˈɛðɚ/",
    "meaning": "cùng nhau",
    "ex1": "In many neighborhoods, walking costs nothing and helps people enjoy fresh air and regular exercise together.",
    "ex1_vi": "Ở nhiều khu phố, đi bộ không tốn chi phí và giúp mọi người tận hưởng không khí trong lành cùng việc tập thể dục thường xuyên."
  },
  {
    "id": 178,
    "word": "sidewalks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaɪdwˌɔks/",
    "meaning": "vỉa hè",
    "ex1": "Pedestrians should use sidewalks whenever possible and cross roads carefully.",
    "ex1_vi": "Người đi bộ nên sử dụng vỉa hè bất cứ khi nào có thể và băng qua đường cẩn thận."
  },
  {
    "id": 179,
    "word": "whenever",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wɛnˈɛvɝ/",
    "meaning": "bất cứ khi nào",
    "ex1": "In daily city life, pedestrians should use sidewalks whenever possible and cross roads carefully.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người đi bộ nên sử dụng vỉa hè bất cứ khi nào có thể và băng qua đường cẩn thận."
  },
  {
    "id": 180,
    "word": "possible",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑsʌbʌl/",
    "meaning": "có thể",
    "ex1": "For safe travel, pedestrians should use sidewalks whenever possible and cross roads carefully.",
    "ex1_vi": "Để đi lại an toàn, người đi bộ nên sử dụng vỉa hè bất cứ khi nào có thể và băng qua đường cẩn thận."
  },
  {
    "id": 181,
    "word": "cross",
    "type": "verb",
    "cat": "v",
    "phonetic": "/krˈɔs/",
    "meaning": "băng qua",
    "ex1": "On busy city streets, pedestrians should use sidewalks whenever possible and cross roads carefully.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, người đi bộ nên sử dụng vỉa hè bất cứ khi nào có thể và băng qua đường cẩn thận."
  },
  {
    "id": 182,
    "word": "follow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɑːloʊ/",
    "meaning": "theo",
    "ex1": "They need to follow traffic lights and stay alert near busy intersections.",
    "ex1_vi": "Họ cần tuân theo đèn giao thông và luôn cảnh giác gần các giao lộ đông đúc."
  },
  {
    "id": 183,
    "word": "alert",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌlˈɝt/",
    "meaning": "cảnh giác",
    "ex1": "In daily city life, they need to follow traffic lights and stay alert near busy intersections.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, họ cần tuân theo đèn giao thông và luôn cảnh giác gần các giao lộ đông đúc."
  },
  {
    "id": 184,
    "word": "intersections",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪntɝsˈɛkʃʌnz/",
    "meaning": "giao lộ",
    "ex1": "For safe travel, they need to follow traffic lights and stay alert near busy intersections.",
    "ex1_vi": "Để đi lại an toàn, họ cần tuân theo đèn giao thông và luôn cảnh giác gần các giao lộ đông đúc."
  },
  {
    "id": 185,
    "word": "looking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊkɪŋ/",
    "meaning": "nhìn",
    "ex1": "Looking both ways before crossing helps prevent accidents and keeps everyone safe outside.",
    "ex1_vi": "Nhìn cả hai phía trước khi băng qua giúp ngăn ngừa tai nạn và giữ mọi người an toàn bên ngoài."
  },
  {
    "id": 186,
    "word": "both",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/boʊθ/",
    "meaning": "cả hai",
    "ex1": "In daily city life, looking both ways before crossing helps prevent accidents and keeps everyone safe outside.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, nhìn cả hai phía trước khi băng qua giúp ngăn ngừa tai nạn và giữ mọi người an toàn bên ngoài."
  },
  {
    "id": 187,
    "word": "crossing",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kɹˈɔsɪŋ/",
    "meaning": "việc băng qua",
    "ex1": "For safe travel, looking both ways before crossing helps prevent accidents and keeps everyone safe outside.",
    "ex1_vi": "Để đi lại an toàn, nhìn cả hai phía trước khi băng qua giúp ngăn ngừa tai nạn và giữ mọi người an toàn bên ngoài."
  },
  {
    "id": 188,
    "word": "keeps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈips/",
    "meaning": "giữ; duy trì",
    "ex1": "On busy city streets, looking both ways before crossing helps prevent accidents and keeps everyone safe outside.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, nhìn cả hai phía trước khi băng qua giúp ngăn ngừa tai nạn và giữ mọi người an toàn bên ngoài."
  },
  {
    "id": 189,
    "word": "outside",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈaʊtsˈaɪd/",
    "meaning": "bên ngoài",
    "ex1": "During everyday travel, looking both ways before crossing helps prevent accidents and keeps everyone safe outside.",
    "ex1_vi": "Trong việc đi lại hằng ngày, nhìn cả hai phía trước khi băng qua giúp ngăn ngừa tai nạn và giữ mọi người an toàn bên ngoài."
  },
  {
    "id": 190,
    "word": "reduces",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɹɪdˈuːsɪz/",
    "meaning": "làm giảm",
    "ex1": "Walking reduces traffic and protects the environment every day.",
    "ex1_vi": "Đi bộ làm giảm giao thông và bảo vệ môi trường mỗi ngày."
  },
  {
    "id": 191,
    "word": "fitness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɪtnəs/",
    "meaning": "thể lực",
    "ex1": "Healthy walking habits improve fitness and save transportation costs.",
    "ex1_vi": "Thói quen đi bộ lành mạnh cải thiện thể lực và tiết kiệm chi phí đi lại."
  },
  {
    "id": 192,
    "word": "save",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪv/",
    "meaning": "tiết kiệm",
    "ex1": "In daily city life, healthy walking habits improve fitness and save transportation costs.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, thói quen đi bộ lành mạnh cải thiện thể lực và tiết kiệm chi phí đi lại."
  },
  {
    "id": 193,
    "word": "create",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪt/",
    "meaning": "tạo ra",
    "ex1": "Safe pedestrians help create cleaner, quieter, and friendlier cities for people of every age.",
    "ex1_vi": "Người đi bộ an toàn giúp tạo ra các thành phố sạch hơn, yên tĩnh hơn và thân thiện hơn cho mọi lứa tuổi."
  },
  {
    "id": 194,
    "word": "quieter",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/kwaɪətɚ/",
    "meaning": "yên tĩnh hơn",
    "ex1": "In daily city life, safe pedestrians help create cleaner, quieter, and friendlier cities for people of every age.",
    "ex1_vi": "Trong cuộc sống thành phố hằng ngày, người đi bộ an toàn giúp tạo ra các thành phố sạch hơn, yên tĩnh hơn và thân thiện hơn cho mọi lứa tuổi."
  },
  {
    "id": 195,
    "word": "friendlier",
    "type": "comparative adjective",
    "cat": "adj",
    "phonetic": "/frɛndliɚ/",
    "meaning": "thân thiện hơn",
    "ex1": "For safe travel, safe pedestrians help create cleaner, quieter, and friendlier cities for people of every age.",
    "ex1_vi": "Để đi lại an toàn, người đi bộ an toàn giúp tạo ra các thành phố sạch hơn, yên tĩnh hơn và thân thiện hơn cho mọi lứa tuổi."
  },
  {
    "id": 196,
    "word": "age",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈeɪdʒ/",
    "meaning": "tuổi",
    "ex1": "On busy city streets, safe pedestrians help create cleaner, quieter, and friendlier cities for people of every age.",
    "ex1_vi": "Trên những con phố thành phố đông đúc, người đi bộ an toàn giúp tạo ra các thành phố sạch hơn, yên tĩnh hơn và thân thiện hơn cho mọi lứa tuổi."
  }
];

const newReadingVocabOrder = [
  "driving",
  "carefully",
  "important",
  "every",
  "road",
  "user",
  "city",
  "drivers",
  "should",
  "stay",
  "focused",
  "and",
  "always",
  "watch",
  "other",
  "vehicles",
  "cyclists",
  "pedestrians",
  "safe",
  "helps",
  "prevent",
  "accidents",
  "protects",
  "everyone",
  "traveling",
  "busy",
  "roads",
  "day",
  "must",
  "obey",
  "speed",
  "limits",
  "stop",
  "completely",
  "red",
  "lights",
  "avoid",
  "using",
  "mobile",
  "phones",
  "while",
  "because",
  "distractions",
  "dangerous",
  "keeping",
  "enough",
  "distance",
  "makes",
  "much",
  "safer",
  "careful",
  "creates",
  "streets",
  "happier",
  "communities",
  "responsible",
  "show",
  "respect",
  "people",
  "following",
  "traffic",
  "rules",
  "good",
  "habits",
  "help",
  "reach",
  "destinations",
  "safely",
  "comfortably",
  "air",
  "pollution",
  "heavy",
  "causes",
  "many",
  "large",
  "cities",
  "cars",
  "buses",
  "trucks",
  "motorbikes",
  "produce",
  "smoke",
  "dirty",
  "poor",
  "quality",
  "can",
  "affect",
  "people's",
  "health",
  "especially",
  "children",
  "older",
  "adults",
  "living",
  "nearby",
  "reduce",
  "public",
  "transportation",
  "more",
  "often",
  "walking",
  "cycling",
  "or",
  "sharing",
  "also",
  "lowers",
  "number",
  "planting",
  "trees",
  "improve",
  "neighborhoods",
  "too",
  "cleaner",
  "benefits",
  "small",
  "daily",
  "actions",
  "protect",
  "nature",
  "healthy",
  "life",
  "better",
  "families",
  "workers",
  "students",
  "future",
  "generations",
  "everywhere",
  "bus",
  "ride",
  "taking",
  "easy",
  "way",
  "travel",
  "visitors",
  "use",
  "affordable",
  "convenient",
  "places",
  "making",
  "simple",
  "passengers",
  "arrive",
  "early",
  "wait",
  "politely",
  "need",
  "buy",
  "tickets",
  "keep",
  "clean",
  "speaking",
  "quietly",
  "giving",
  "seats",
  "manners",
  "choose",
  "instead",
  "private",
  "journeys",
  "cheaper",
  "environment",
  "one",
  "healthiest",
  "ways",
  "walk",
  "school",
  "work",
  "shops",
  "parks",
  "costs",
  "nothing",
  "enjoy",
  "fresh",
  "regular",
  "exercise",
  "together",
  "sidewalks",
  "whenever",
  "possible",
  "cross",
  "follow",
  "alert",
  "intersections",
  "looking",
  "both",
  "crossing",
  "keeps",
  "outside",
  "reduces",
  "fitness",
  "save",
  "create",
  "quieter",
  "friendlier",
  "age"
];
