// ===== AI01 ESSAY =====

const newEssayData = [
  {
    "text": "1. What Is Chat AI?\nChat AI is a smart computer program that can talk with people through text or voice. It can answer questions, explain ideas, write sentences, translate languages, and help users learn new things. Many people use Chat AI because it is fast, friendly, and easy to use.\n\nChat AI does not think like a human, but it can understand many questions and give useful answers. It learns from a large amount of information and uses patterns to respond.\n\nToday, Chat AI is used in education, work, business, and daily life. It is a helpful tool, but users should still check important information carefully.",
    "vi": "1. Chat AI là gì?\nChat AI là một chương trình máy tính thông minh có thể trò chuyện với con người qua văn bản hoặc giọng nói. Nó có thể trả lời câu hỏi, giải thích ý tưởng, viết câu, dịch ngôn ngữ và giúp người dùng học những điều mới. Nhiều người sử dụng Chat AI vì nó nhanh, thân thiện và dễ sử dụng.\n\nChat AI không suy nghĩ giống con người, nhưng nó có thể hiểu nhiều câu hỏi và đưa ra câu trả lời hữu ích. Nó học từ một lượng lớn thông tin và sử dụng các mẫu để phản hồi.\n\nNgày nay, Chat AI được sử dụng trong giáo dục, công việc, kinh doanh và cuộc sống hằng ngày. Đây là một công cụ hữu ích, nhưng người dùng vẫn nên kiểm tra cẩn thận những thông tin quan trọng."
  },
  {
    "text": "2. Using Chat AI Every Day\nChat AI can help people in many daily activities. Students can use it to study English, write essays, or review lessons. Workers can use it to write emails, make plans, and solve simple problems. It can also help people translate words, create ideas, and learn new skills.\n\nUsing Chat AI every day can save time and make learning easier. It is available anytime, so users can ask questions whenever they need help.\n\nHowever, people should not depend on Chat AI too much. It is a support tool, not a replacement for human thinking. We should use it wisely and carefully.",
    "vi": "2. Sử dụng Chat AI mỗi ngày\nChat AI có thể giúp mọi người trong nhiều hoạt động hằng ngày. Học sinh có thể dùng nó để học tiếng Anh, viết bài luận hoặc ôn lại bài học. Người đi làm có thể dùng nó để viết email, lập kế hoạch và giải quyết các vấn đề đơn giản. Nó cũng có thể giúp mọi người dịch từ, tạo ý tưởng và học các kỹ năng mới.\n\nSử dụng Chat AI mỗi ngày có thể tiết kiệm thời gian và làm cho việc học dễ dàng hơn. Nó luôn sẵn có, vì vậy người dùng có thể đặt câu hỏi bất cứ khi nào họ cần trợ giúp.\n\nTuy nhiên, mọi người không nên phụ thuộc quá nhiều vào Chat AI. Đây là một công cụ hỗ trợ, không phải sự thay thế cho tư duy của con người. Chúng ta nên sử dụng nó một cách khôn ngoan và cẩn thận."
  },
  {
    "text": "3. Learning English with Chat AI\nChat AI is a useful partner for learning English. Students can practice vocabulary, grammar, reading, writing, and simple conversations at home. It gives quick answers and explains many language rules in easy words.\n\nLearners can ask Chat AI to correct sentences, translate words, create quizzes, or write short stories. They can also practice speaking by reading the answers aloud. Regular practice helps improve confidence and communication skills.\n\nChat AI supports learning, but it cannot replace teachers or real conversations. Students should practice with other people, listen to English often, and keep studying every day for better results.",
    "vi": "3. Học tiếng Anh với Chat AI\nChat AI là một người bạn đồng hành hữu ích cho việc học tiếng Anh. Học sinh có thể luyện từ vựng, ngữ pháp, đọc, viết và các cuộc hội thoại đơn giản tại nhà. Nó đưa ra câu trả lời nhanh và giải thích nhiều quy tắc ngôn ngữ bằng những từ dễ hiểu.\n\nNgười học có thể yêu cầu Chat AI sửa câu, dịch từ, tạo câu đố hoặc viết truyện ngắn. Họ cũng có thể luyện nói bằng cách đọc to các câu trả lời. Việc luyện tập thường xuyên giúp cải thiện sự tự tin và kỹ năng giao tiếp.\n\nChat AI hỗ trợ việc học, nhưng nó không thể thay thế giáo viên hoặc các cuộc trò chuyện thực tế. Học sinh nên luyện tập với người khác, thường xuyên nghe tiếng Anh và tiếp tục học mỗi ngày để có kết quả tốt hơn."
  }
];
