// ===== AI02 VOCABULARY =====

const lessonVocabularyWords = [
  "chat",
  "ai",
  "students",
  "helpful",
  "because",
  "can",
  "explain",
  "lessons",
  "simple",
  "way",
  "when",
  "do",
  "not",
  "understand",
  "topic",
  "ask",
  "examples",
  "summaries",
  "or",
  "practice",
  "questions",
  "this",
  "makes",
  "learning",
  "faster",
  "and",
  "more",
  "interesting",
  "use",
  "prepare",
  "presentations",
  "check",
  "grammar",
  "improve",
  "writing",
  "review",
  "before",
  "exams",
  "also",
  "help",
  "manage",
  "study",
  "time",
  "create",
  "plans",
  "however",
  "should",
  "copy",
  "answers",
  "without",
  "thinking",
  "learn",
  "cheat",
  "good",
  "technology",
  "responsibly",
  "try",
  "lesson",
  "work",
  "becoming",
  "popular",
  "many",
  "workplaces",
  "workers",
  "write",
  "emails",
  "reports",
  "summarize",
  "documents",
  "ideas",
  "projects",
  "saves",
  "helps",
  "people",
  "efficiently",
  "offices",
  "support",
  "customer",
  "service",
  "marketing",
  "planning",
  "communication",
  "new",
  "skills",
  "difficult",
  "information",
  "quickly",
  "careful",
  "using",
  "private",
  "company",
  "important",
  "decisions",
  "still",
  "checked",
  "humans",
  "useful",
  "assistant",
  "but",
  "used",
  "responsibility",
  "judgment",
  "clear",
  "creating",
  "content",
  "types",
  "social",
  "media",
  "posts",
  "short",
  "stories",
  "advertisements",
  "video",
  "scripts",
  "notes",
  "product",
  "descriptions",
  "very",
  "teachers",
  "business",
  "owners",
  "creators",
  "users",
  "save",
  "get",
  "make",
  "shorter",
  "longer",
  "simpler",
  "professional",
  "edit",
  "posting",
  "may",
  "mistakes",
  "boring",
  "sentences",
  "human",
  "creativity",
  "best",
  "comes",
  "combining",
  "personal"
];

const newVocabData = [
  {
    "id": 1,
    "word": "chat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃæt/",
    "meaning": "trò chuyện; cuộc trò chuyện",
    "ex1": "Students discuss chat while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về trò chuyện khi học cách sử dụng Chat AI."
  },
  {
    "id": 2,
    "word": "ai",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌeɪˈaɪ/",
    "meaning": "trí tuệ nhân tạo",
    "ex1": "Students discuss ai while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về trí tuệ nhân tạo khi học cách sử dụng Chat AI."
  },
  {
    "id": 3,
    "word": "students",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈudʌnts/",
    "meaning": "học sinh; sinh viên",
    "ex1": "Students discuss students while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về học sinh khi học cách sử dụng Chat AI."
  },
  {
    "id": 4,
    "word": "helpful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛlpfəl/",
    "meaning": "hữu ích",
    "ex1": "A helpful example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ hữu ích có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 5,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkɔz/",
    "meaning": "bởi vì",
    "ex1": "People use Chat AI because it can save time.",
    "ex1_vi": "Mọi người dùng Chat AI vì nó có thể tiết kiệm thời gian."
  },
  {
    "id": 6,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Chat AI can support simple learning tasks every day.",
    "ex1_vi": "Chat AI có thể hỗ trợ các nhiệm vụ học tập đơn giản mỗi ngày."
  },
  {
    "id": 7,
    "word": "explain",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɪksplˈeɪn/",
    "meaning": "giải thích",
    "ex1": "Chat AI can explain difficult ideas in simple language.",
    "ex1_vi": "Chat AI có thể giải thích các ý khó bằng ngôn ngữ đơn giản."
  },
  {
    "id": 8,
    "word": "lessons",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɛsʌnz/",
    "meaning": "những bài học",
    "ex1": "Students discuss lessons while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về những bài học khi học cách sử dụng Chat AI."
  },
  {
    "id": 9,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "A simple example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ đơn giản có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 10,
    "word": "way",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪ/",
    "meaning": "cách",
    "ex1": "Students discuss way while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về cách khi học cách sử dụng Chat AI."
  },
  {
    "id": 11,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "Students learn better when they practice English regularly.",
    "ex1_vi": "Học sinh học tốt hơn khi luyện tiếng Anh thường xuyên."
  },
  {
    "id": 12,
    "word": "do",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈu/",
    "meaning": "làm",
    "ex1": "Students do not need to copy every AI answer.",
    "ex1_vi": "Học sinh không cần sao chép mọi câu trả lời của AI."
  },
  {
    "id": 13,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "Students should not copy answers without understanding the lesson.",
    "ex1_vi": "Học sinh không nên sao chép câu trả lời mà không hiểu bài."
  },
  {
    "id": 14,
    "word": "understand",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌʌndɝstˈænd/",
    "meaning": "hiểu",
    "ex1": "Clear explanations help students understand difficult English grammar.",
    "ex1_vi": "Giải thích rõ ràng giúp học sinh hiểu ngữ pháp tiếng Anh khó."
  },
  {
    "id": 15,
    "word": "topic",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈtɑːpɪk/",
    "meaning": "chủ đề",
    "ex1": "Students discuss topic while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về chủ đề khi học cách sử dụng Chat AI."
  },
  {
    "id": 16,
    "word": "ask",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈæsk/",
    "meaning": "hỏi",
    "ex1": "Users can ask Chat AI clear questions about English.",
    "ex1_vi": "Người dùng có thể hỏi Chat AI các câu hỏi rõ ràng về tiếng Anh."
  },
  {
    "id": 17,
    "word": "examples",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪɡˈzæmpəlz/",
    "meaning": "ví dụ",
    "ex1": "Students discuss examples while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về ví dụ khi học cách sử dụng Chat AI."
  },
  {
    "id": 18,
    "word": "summaries",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsʌməriz/",
    "meaning": "bản tóm tắt",
    "ex1": "Students discuss summaries while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về bản tóm tắt khi học cách sử dụng Chat AI."
  },
  {
    "id": 19,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ɔr/",
    "meaning": "hoặc",
    "ex1": "Users can type a question or speak it aloud.",
    "ex1_vi": "Người dùng có thể gõ câu hỏi hoặc nói thành tiếng."
  },
  {
    "id": 20,
    "word": "practice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈæktʌs/",
    "meaning": "sự luyện tập",
    "ex1": "Regular practice helps students use Chat AI more effectively.",
    "ex1_vi": "Việc luyện tập thường xuyên giúp học sinh sử dụng Chat AI hiệu quả hơn."
  },
  {
    "id": 21,
    "word": "questions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kwˈɛstʃʌnz/",
    "meaning": "câu hỏi",
    "ex1": "Students discuss questions while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về câu hỏi khi học cách sử dụng Chat AI."
  },
  {
    "id": 22,
    "word": "this",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ðɪs/",
    "meaning": "này",
    "ex1": "This tool can support students during everyday language practice.",
    "ex1_vi": "Công cụ này có thể hỗ trợ học sinh trong việc luyện ngôn ngữ hằng ngày."
  },
  {
    "id": 23,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm; khiến",
    "ex1": "Chat AI makes some work faster in many fields.",
    "ex1_vi": "Chat AI làm cho một số công việc nhanh hơn trong nhiều lĩnh vực."
  },
  {
    "id": 24,
    "word": "learning",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɝnɪŋ/",
    "meaning": "việc học",
    "ex1": "Students discuss learning while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về việc học khi học cách sử dụng Chat AI."
  },
  {
    "id": 25,
    "word": "faster",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈæstɚ/",
    "meaning": "nhanh hơn",
    "ex1": "Clear prompts can help users get faster results.",
    "ex1_vi": "Câu lệnh rõ ràng có thể giúp người dùng nhận kết quả nhanh hơn."
  },
  {
    "id": 26,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ənd/",
    "meaning": "và",
    "ex1": "AI can explain ideas and support daily language practice.",
    "ex1_vi": "AI có thể giải thích ý tưởng và hỗ trợ luyện ngôn ngữ hằng ngày."
  },
  {
    "id": 27,
    "word": "more",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/mɔr/",
    "meaning": "hơn; nhiều hơn",
    "ex1": "Clear prompts can help users get more useful answers.",
    "ex1_vi": "Câu lệnh rõ ràng có thể giúp người dùng nhận câu trả lời hữu ích hơn."
  },
  {
    "id": 28,
    "word": "interesting",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɪntrʌstɪŋ/",
    "meaning": "thú vị",
    "ex1": "An interesting example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ thú vị có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 29,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "People can use Chat AI for many daily tasks.",
    "ex1_vi": "Mọi người có thể sử dụng Chat AI cho nhiều nhiệm vụ hằng ngày."
  },
  {
    "id": 30,
    "word": "prepare",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɹɪpˈɛɹ/",
    "meaning": "chuẩn bị",
    "ex1": "Teachers can prepare simple lessons with careful AI support.",
    "ex1_vi": "Giáo viên có thể chuẩn bị bài học đơn giản với sự hỗ trợ AI cẩn thận."
  },
  {
    "id": 31,
    "word": "presentations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌprɛzənˈteɪʃənz/",
    "meaning": "bài thuyết trình",
    "ex1": "Students discuss presentations while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về bài thuyết trình khi học cách sử dụng Chat AI."
  },
  {
    "id": 32,
    "word": "check",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈɛk/",
    "meaning": "kiểm tra",
    "ex1": "Users should check important information before trusting AI output.",
    "ex1_vi": "Người dùng nên kiểm tra thông tin quan trọng trước khi tin đầu ra AI."
  },
  {
    "id": 33,
    "word": "grammar",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɡræmər/",
    "meaning": "ngữ pháp",
    "ex1": "Students discuss grammar while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về ngữ pháp khi học cách sử dụng Chat AI."
  },
  {
    "id": 34,
    "word": "improve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪmprˈuv/",
    "meaning": "cải thiện",
    "ex1": "Students can improve writing through careful daily practice.",
    "ex1_vi": "Học sinh có thể cải thiện kỹ năng viết qua luyện tập hằng ngày cẩn thận."
  },
  {
    "id": 35,
    "word": "writing",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪtɪŋ/",
    "meaning": "việc viết",
    "ex1": "Students discuss writing while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về việc viết khi học cách sử dụng Chat AI."
  },
  {
    "id": 36,
    "word": "review",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˌivjˈu/",
    "meaning": "ôn lại",
    "ex1": "Students can review lessons with simple AI practice questions.",
    "ex1_vi": "Học sinh có thể ôn bài bằng các câu hỏi luyện tập AI đơn giản."
  },
  {
    "id": 37,
    "word": "before",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/bɪfˈoːɹ/",
    "meaning": "trước",
    "ex1": "Users should check important information before sharing it online.",
    "ex1_vi": "Người dùng nên kiểm tra thông tin quan trọng trước khi chia sẻ trực tuyến."
  },
  {
    "id": 38,
    "word": "exams",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪɡˈzæmz/",
    "meaning": "kỳ thi",
    "ex1": "Students discuss exams while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về kỳ thi khi học cách sử dụng Chat AI."
  },
  {
    "id": 39,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "Chat AI also helps users create ideas for projects.",
    "ex1_vi": "Chat AI cũng giúp người dùng tạo ý tưởng cho dự án."
  },
  {
    "id": 40,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "Chat AI can help students review lessons more efficiently.",
    "ex1_vi": "Chat AI có thể giúp học sinh ôn bài hiệu quả hơn."
  },
  {
    "id": 41,
    "word": "manage",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈmænɪdʒ/",
    "meaning": "quản lý",
    "ex1": "AI tools can help students manage their study time.",
    "ex1_vi": "Công cụ AI có thể giúp học sinh quản lý thời gian học."
  },
  {
    "id": 42,
    "word": "study",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈʌdi/",
    "meaning": "việc học; học tập",
    "ex1": "A clear study plan helps students manage their time.",
    "ex1_vi": "Một kế hoạch học tập rõ ràng giúp học sinh quản lý thời gian."
  },
  {
    "id": 43,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "Students discuss time while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về thời gian khi học cách sử dụng Chat AI."
  },
  {
    "id": 44,
    "word": "create",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪt/",
    "meaning": "tạo ra",
    "ex1": "Chat AI can create useful ideas for writing practice.",
    "ex1_vi": "Chat AI có thể tạo ý tưởng hữu ích cho luyện viết."
  },
  {
    "id": 45,
    "word": "plans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈænz/",
    "meaning": "kế hoạch",
    "ex1": "Students discuss plans while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về kế hoạch khi học cách sử dụng Chat AI."
  },
  {
    "id": 46,
    "word": "however",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/hˌaʊˈɛvɝ/",
    "meaning": "tuy nhiên",
    "ex1": "However, users should still check important AI information carefully.",
    "ex1_vi": "Tuy nhiên, người dùng vẫn nên kiểm tra cẩn thận thông tin AI quan trọng."
  },
  {
    "id": 47,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "Users should check important AI answers before using them.",
    "ex1_vi": "Người dùng nên kiểm tra các câu trả lời AI quan trọng trước khi sử dụng."
  },
  {
    "id": 48,
    "word": "copy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈkɑːpi/",
    "meaning": "sao chép",
    "ex1": "Students should not copy AI answers without understanding them.",
    "ex1_vi": "Học sinh không nên sao chép câu trả lời AI mà không hiểu."
  },
  {
    "id": 49,
    "word": "answers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈænsɝz/",
    "meaning": "câu trả lời",
    "ex1": "Students discuss answers while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về câu trả lời khi học cách sử dụng Chat AI."
  },
  {
    "id": 50,
    "word": "without",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/wɪθˈaʊt/",
    "meaning": "không có; mà không",
    "ex1": "Students should not use AI without thinking for themselves.",
    "ex1_vi": "Học sinh không nên dùng AI mà không tự suy nghĩ."
  },
  {
    "id": 51,
    "word": "thinking",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈθɪŋkɪŋ/",
    "meaning": "tư duy",
    "ex1": "Students discuss thinking while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về tư duy khi học cách sử dụng Chat AI."
  },
  {
    "id": 52,
    "word": "learn",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɝn/",
    "meaning": "học",
    "ex1": "Students can learn new skills through regular practice.",
    "ex1_vi": "Học sinh có thể học các kỹ năng mới qua luyện tập thường xuyên."
  },
  {
    "id": 53,
    "word": "cheat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃiːt/",
    "meaning": "gian lận",
    "ex1": "Students should never cheat by copying AI answers directly.",
    "ex1_vi": "Học sinh không bao giờ nên gian lận bằng cách chép trực tiếp câu trả lời AI."
  },
  {
    "id": 54,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "A good example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ tốt có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 55,
    "word": "technology",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tɛknˈɒlədʒi/",
    "meaning": "công nghệ",
    "ex1": "Students discuss technology while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về công nghệ khi học cách sử dụng Chat AI."
  },
  {
    "id": 56,
    "word": "responsibly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/rɪspˈɑnsʌbli/",
    "meaning": "có trách nhiệm",
    "ex1": "Students should use Chat AI responsibly during school activities.",
    "ex1_vi": "Học sinh nên sử dụng Chat AI có trách nhiệm trong các hoạt động ở trường."
  },
  {
    "id": 57,
    "word": "try",
    "type": "verb",
    "cat": "v",
    "phonetic": "/trˈaɪ/",
    "meaning": "thử",
    "ex1": "Students should try to understand lessons by themselves.",
    "ex1_vi": "Học sinh nên cố gắng tự mình hiểu bài."
  },
  {
    "id": 58,
    "word": "lesson",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɛsʌn/",
    "meaning": "bài học",
    "ex1": "Students discuss lesson while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về bài học khi học cách sử dụng Chat AI."
  },
  {
    "id": 59,
    "word": "work",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝk/",
    "meaning": "công việc",
    "ex1": "Students discuss work while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về công việc khi học cách sử dụng Chat AI."
  },
  {
    "id": 60,
    "word": "becoming",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkʌmɪŋ/",
    "meaning": "đang trở nên",
    "ex1": "Chat AI is becoming popular in many modern workplaces.",
    "ex1_vi": "Chat AI đang trở nên phổ biến tại nhiều nơi làm việc hiện đại."
  },
  {
    "id": 61,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pɑpjəlɚ/",
    "meaning": "phổ biến",
    "ex1": "A popular example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ phổ biến có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 62,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mɛni/",
    "meaning": "nhiều",
    "ex1": "Many students use Chat AI to review difficult lessons.",
    "ex1_vi": "Nhiều học sinh sử dụng Chat AI để ôn lại các bài khó."
  },
  {
    "id": 63,
    "word": "workplaces",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝkplˌeɪsɪz/",
    "meaning": "nơi làm việc",
    "ex1": "Students discuss workplaces while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về nơi làm việc khi học cách sử dụng Chat AI."
  },
  {
    "id": 64,
    "word": "workers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɜːkɚz/",
    "meaning": "nhân viên",
    "ex1": "Students discuss workers while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về nhân viên khi học cách sử dụng Chat AI."
  },
  {
    "id": 65,
    "word": "write",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈaɪt/",
    "meaning": "viết",
    "ex1": "Students can write short sentences with careful AI support.",
    "ex1_vi": "Học sinh có thể viết các câu ngắn với sự hỗ trợ AI cẩn thận."
  },
  {
    "id": 66,
    "word": "emails",
    "type": "noun",
    "cat": "n",
    "phonetic": "/imˈeɪlz/",
    "meaning": "email",
    "ex1": "Students discuss emails while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về email khi học cách sử dụng Chat AI."
  },
  {
    "id": 67,
    "word": "reports",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rɪpˈɔrts/",
    "meaning": "báo cáo",
    "ex1": "Workers can use Chat AI to prepare simple reports.",
    "ex1_vi": "Người lao động có thể dùng Chat AI để chuẩn bị các báo cáo đơn giản."
  },
  {
    "id": 68,
    "word": "summarize",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈsʌməˌraɪz/",
    "meaning": "tóm tắt",
    "ex1": "Chat AI can summarize short documents for busy workers.",
    "ex1_vi": "Chat AI có thể tóm tắt tài liệu ngắn cho người lao động bận rộn."
  },
  {
    "id": 69,
    "word": "documents",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɒkjuːmənts/",
    "meaning": "tài liệu",
    "ex1": "Students discuss documents while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về tài liệu khi học cách sử dụng Chat AI."
  },
  {
    "id": 70,
    "word": "ideas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/aɪdˈiʌz/",
    "meaning": "ý tưởng",
    "ex1": "Students discuss ideas while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về ý tưởng khi học cách sử dụng Chat AI."
  },
  {
    "id": 71,
    "word": "projects",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑdʒɛkts/",
    "meaning": "dự án",
    "ex1": "Students discuss projects while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về dự án khi học cách sử dụng Chat AI."
  },
  {
    "id": 72,
    "word": "saves",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪvz/",
    "meaning": "tiết kiệm",
    "ex1": "Chat AI saves time on some routine work tasks.",
    "ex1_vi": "Chat AI tiết kiệm thời gian cho một số nhiệm vụ công việc thường lệ."
  },
  {
    "id": 73,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "Regular practice helps students improve communication skills.",
    "ex1_vi": "Luyện tập thường xuyên giúp học sinh cải thiện kỹ năng giao tiếp."
  },
  {
    "id": 74,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipəl/",
    "meaning": "mọi người",
    "ex1": "Students discuss people while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về mọi người khi học cách sử dụng Chat AI."
  },
  {
    "id": 75,
    "word": "efficiently",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ɪˈfɪʃəntli/",
    "meaning": "hiệu quả",
    "ex1": "Workers can use Chat AI efficiently for routine office tasks.",
    "ex1_vi": "Người lao động có thể sử dụng Chat AI hiệu quả cho các nhiệm vụ văn phòng thường lệ."
  },
  {
    "id": 76,
    "word": "offices",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɒfɪsɪz/",
    "meaning": "các văn phòng",
    "ex1": "Students discuss offices while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về các văn phòng khi học cách sử dụng Chat AI."
  },
  {
    "id": 77,
    "word": "support",
    "type": "verb",
    "cat": "v",
    "phonetic": "/səpˈɔɹt/",
    "meaning": "hỗ trợ",
    "ex1": "Chat AI can support students and workers with simple tasks.",
    "ex1_vi": "Chat AI có thể hỗ trợ học sinh và người lao động với các nhiệm vụ đơn giản."
  },
  {
    "id": 78,
    "word": "customer",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌstʌmɝ/",
    "meaning": "khách hàng",
    "ex1": "Students discuss customer while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về khách hàng khi học cách sử dụng Chat AI."
  },
  {
    "id": 79,
    "word": "service",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɝvʌs/",
    "meaning": "dịch vụ",
    "ex1": "Students discuss service while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về dịch vụ khi học cách sử dụng Chat AI."
  },
  {
    "id": 80,
    "word": "marketing",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈmɑːrkɪtɪŋ/",
    "meaning": "tiếp thị",
    "ex1": "Students discuss marketing while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về tiếp thị khi học cách sử dụng Chat AI."
  },
  {
    "id": 81,
    "word": "planning",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈænɪŋ/",
    "meaning": "lập kế hoạch",
    "ex1": "Students discuss planning while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về lập kế hoạch khi học cách sử dụng Chat AI."
  },
  {
    "id": 82,
    "word": "communication",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kəmjˌuːnɪkˈeɪʃən/",
    "meaning": "sự giao tiếp",
    "ex1": "Students discuss communication while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về sự giao tiếp khi học cách sử dụng Chat AI."
  },
  {
    "id": 83,
    "word": "new",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈu/",
    "meaning": "mới",
    "ex1": "A new example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ mới có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 84,
    "word": "skills",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪlz/",
    "meaning": "kỹ năng",
    "ex1": "Students discuss skills while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về kỹ năng khi học cách sử dụng Chat AI."
  },
  {
    "id": 85,
    "word": "difficult",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɪkəlt/",
    "meaning": "khó khăn",
    "ex1": "A difficult example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ khó khăn có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 86,
    "word": "information",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnfɚmˈeɪʃən/",
    "meaning": "thông tin",
    "ex1": "Students discuss information while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về thông tin khi học cách sử dụng Chat AI."
  },
  {
    "id": 87,
    "word": "quickly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kwˈɪkli/",
    "meaning": "nhanh chóng",
    "ex1": "Chat AI can quickly provide ideas for simple tasks.",
    "ex1_vi": "Chat AI có thể nhanh chóng cung cấp ý tưởng cho các nhiệm vụ đơn giản."
  },
  {
    "id": 88,
    "word": "careful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɛɹfəl/",
    "meaning": "cẩn thận",
    "ex1": "A careful example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ cẩn thận có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 89,
    "word": "using",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈuzɪŋ/",
    "meaning": "việc sử dụng",
    "ex1": "Students discuss using while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về việc sử dụng khi học cách sử dụng Chat AI."
  },
  {
    "id": 90,
    "word": "private",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/prˈaɪvʌt/",
    "meaning": "riêng tư",
    "ex1": "A private example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ riêng tư có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 91,
    "word": "company",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌmpəni/",
    "meaning": "công ty",
    "ex1": "Students discuss company while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về công ty khi học cách sử dụng Chat AI."
  },
  {
    "id": 92,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔɹtənt/",
    "meaning": "quan trọng",
    "ex1": "An important example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ quan trọng có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 93,
    "word": "decisions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪsˈɪʒənz/",
    "meaning": "quyết định",
    "ex1": "Students discuss decisions while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về quyết định khi học cách sử dụng Chat AI."
  },
  {
    "id": 94,
    "word": "still",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/stɪl/",
    "meaning": "vẫn",
    "ex1": "Human judgment is still important when using Chat AI.",
    "ex1_vi": "Phán đoán của con người vẫn quan trọng khi sử dụng Chat AI."
  },
  {
    "id": 95,
    "word": "checked",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃɛkt/",
    "meaning": "được kiểm tra",
    "ex1": "Important AI information should be checked by responsible humans.",
    "ex1_vi": "Thông tin AI quan trọng nên được con người có trách nhiệm kiểm tra."
  },
  {
    "id": 96,
    "word": "humans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈhjuːmənz/",
    "meaning": "con người",
    "ex1": "Students discuss humans while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về con người khi học cách sử dụng Chat AI."
  },
  {
    "id": 97,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈusfəl/",
    "meaning": "hữu ích",
    "ex1": "An useful example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ hữu ích có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 98,
    "word": "assistant",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌsˈɪstʌnt/",
    "meaning": "trợ lý",
    "ex1": "Chat AI can act as a useful study assistant.",
    "ex1_vi": "Chat AI có thể hoạt động như một trợ lý học tập hữu ích."
  },
  {
    "id": 99,
    "word": "but",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bˈʌt/",
    "meaning": "nhưng",
    "ex1": "Chat AI is useful, but important facts need checking.",
    "ex1_vi": "Chat AI hữu ích, nhưng các sự thật quan trọng cần được kiểm tra."
  },
  {
    "id": 100,
    "word": "used",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzd/",
    "meaning": "được sử dụng",
    "ex1": "Chat AI is used in education and daily work.",
    "ex1_vi": "Chat AI được sử dụng trong giáo dục và công việc hằng ngày."
  },
  {
    "id": 101,
    "word": "responsibility",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rispˌɑnsʌbˈɪlʌti/",
    "meaning": "trách nhiệm",
    "ex1": "Students discuss responsibility while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về trách nhiệm khi học cách sử dụng Chat AI."
  },
  {
    "id": 102,
    "word": "judgment",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈdʒʌdʒmənt/",
    "meaning": "sự phán đoán",
    "ex1": "Students discuss judgment while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về sự phán đoán khi học cách sử dụng Chat AI."
  },
  {
    "id": 103,
    "word": "clear",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈɪr/",
    "meaning": "rõ ràng",
    "ex1": "A clear example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ rõ ràng có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 104,
    "word": "creating",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kriˈeɪtɪŋ/",
    "meaning": "việc tạo nội dung",
    "ex1": "Creating useful content requires both AI support and human ideas.",
    "ex1_vi": "Tạo nội dung hữu ích cần cả hỗ trợ AI và ý tưởng con người."
  },
  {
    "id": 105,
    "word": "content",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈkɑːntɛnt/",
    "meaning": "nội dung",
    "ex1": "Students discuss content while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về nội dung khi học cách sử dụng Chat AI."
  },
  {
    "id": 106,
    "word": "types",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪps/",
    "meaning": "các loại",
    "ex1": "Students discuss types while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về các loại khi học cách sử dụng Chat AI."
  },
  {
    "id": 107,
    "word": "social",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈoʊʃʌl/",
    "meaning": "xã hội",
    "ex1": "A social example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ xã hội có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 108,
    "word": "media",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈidiʌ/",
    "meaning": "truyền thông",
    "ex1": "Students discuss media while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về truyền thông khi học cách sử dụng Chat AI."
  },
  {
    "id": 109,
    "word": "posts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/poʊsts/",
    "meaning": "bài đăng",
    "ex1": "Students discuss posts while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về bài đăng khi học cách sử dụng Chat AI."
  },
  {
    "id": 110,
    "word": "short",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɔrt/",
    "meaning": "ngắn",
    "ex1": "A short example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ ngắn có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 111,
    "word": "stories",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈɔriz/",
    "meaning": "câu chuyện",
    "ex1": "Students discuss stories while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về câu chuyện khi học cách sử dụng Chat AI."
  },
  {
    "id": 112,
    "word": "advertisements",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌædvərˈtaɪzmənts/",
    "meaning": "quảng cáo",
    "ex1": "Students discuss advertisements while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về quảng cáo khi học cách sử dụng Chat AI."
  },
  {
    "id": 113,
    "word": "video",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈvɪdioʊ/",
    "meaning": "video",
    "ex1": "Students discuss video while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về video khi học cách sử dụng Chat AI."
  },
  {
    "id": 114,
    "word": "scripts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skrɪpts/",
    "meaning": "kịch bản",
    "ex1": "Students discuss scripts while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về kịch bản khi học cách sử dụng Chat AI."
  },
  {
    "id": 115,
    "word": "notes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/noʊts/",
    "meaning": "ghi chú",
    "ex1": "Students discuss notes while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về ghi chú khi học cách sử dụng Chat AI."
  },
  {
    "id": 116,
    "word": "product",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑdʌkt/",
    "meaning": "sản phẩm",
    "ex1": "Students discuss product while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về sản phẩm khi học cách sử dụng Chat AI."
  },
  {
    "id": 117,
    "word": "descriptions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪˈskrɪpʃənz/",
    "meaning": "mô tả",
    "ex1": "Students discuss descriptions while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về mô tả khi học cách sử dụng Chat AI."
  },
  {
    "id": 118,
    "word": "very",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/vˈɛɹi/",
    "meaning": "rất",
    "ex1": "Responsible use of Chat AI is very important today.",
    "ex1_vi": "Việc sử dụng Chat AI có trách nhiệm rất quan trọng ngày nay."
  },
  {
    "id": 119,
    "word": "teachers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈitʃɝz/",
    "meaning": "giáo viên",
    "ex1": "Students discuss teachers while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về giáo viên khi học cách sử dụng Chat AI."
  },
  {
    "id": 120,
    "word": "business",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɪznəs/",
    "meaning": "kinh doanh; doanh nghiệp",
    "ex1": "Students discuss business while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về kinh doanh khi học cách sử dụng Chat AI."
  },
  {
    "id": 121,
    "word": "owners",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈoʊnərz/",
    "meaning": "chủ sở hữu",
    "ex1": "Students discuss owners while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về chủ sở hữu khi học cách sử dụng Chat AI."
  },
  {
    "id": 122,
    "word": "creators",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kriˈeɪtərz/",
    "meaning": "người sáng tạo",
    "ex1": "Students discuss creators while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về người sáng tạo khi học cách sử dụng Chat AI."
  },
  {
    "id": 123,
    "word": "users",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈjuːzərz/",
    "meaning": "người dùng",
    "ex1": "Students discuss users while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về người dùng khi học cách sử dụng Chat AI."
  },
  {
    "id": 124,
    "word": "save",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪv/",
    "meaning": "tiết kiệm",
    "ex1": "Using Chat AI carefully can save time on routine tasks.",
    "ex1_vi": "Sử dụng Chat AI cẩn thận có thể tiết kiệm thời gian cho các nhiệm vụ thường lệ."
  },
  {
    "id": 125,
    "word": "get",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɛt/",
    "meaning": "có được; nhận",
    "ex1": "Users can get many ideas quickly with Chat AI.",
    "ex1_vi": "Người dùng có thể nhanh chóng nhận nhiều ý tưởng với Chat AI."
  },
  {
    "id": 126,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/meɪk/",
    "meaning": "làm cho",
    "ex1": "Users can make better plans with clear information.",
    "ex1_vi": "Người dùng có thể lập kế hoạch tốt hơn với thông tin rõ ràng."
  },
  {
    "id": 127,
    "word": "shorter",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɔːɹɾɚ/",
    "meaning": "ngắn hơn",
    "ex1": "A shorter example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ ngắn hơn có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 128,
    "word": "longer",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lɔŋɡɚ/",
    "meaning": "dài hơn",
    "ex1": "Users can ask Chat AI to make a passage longer.",
    "ex1_vi": "Người dùng có thể yêu cầu Chat AI làm một đoạn văn dài hơn."
  },
  {
    "id": 129,
    "word": "simpler",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈsɪmplər/",
    "meaning": "đơn giản hơn",
    "ex1": "A simpler example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ đơn giản hơn có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 130,
    "word": "professional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/prəfˈɛʃənəl/",
    "meaning": "chuyên nghiệp",
    "ex1": "A professional example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ chuyên nghiệp có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 131,
    "word": "edit",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɛdɪt/",
    "meaning": "chỉnh sửa",
    "ex1": "Users should edit AI content before posting it publicly.",
    "ex1_vi": "Người dùng nên chỉnh sửa nội dung AI trước khi đăng công khai."
  },
  {
    "id": 132,
    "word": "posting",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈpoʊstɪŋ/",
    "meaning": "việc đăng nội dung",
    "ex1": "Posting AI content requires careful checking before publication.",
    "ex1_vi": "Đăng nội dung AI đòi hỏi kiểm tra cẩn thận trước khi công bố."
  },
  {
    "id": 133,
    "word": "may",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈeɪ/",
    "meaning": "có thể",
    "ex1": "AI may make mistakes, so users should check facts.",
    "ex1_vi": "AI có thể mắc lỗi, vì vậy người dùng nên kiểm tra sự thật."
  },
  {
    "id": 134,
    "word": "mistakes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mɪstˈeɪks/",
    "meaning": "sai lầm",
    "ex1": "Students discuss mistakes while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về sai lầm khi học cách sử dụng Chat AI."
  },
  {
    "id": 135,
    "word": "boring",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈbɔːrɪŋ/",
    "meaning": "nhàm chán",
    "ex1": "A boring example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ nhàm chán có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 136,
    "word": "sentences",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛntʌnsʌz/",
    "meaning": "câu",
    "ex1": "Students discuss sentences while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về câu khi học cách sử dụng Chat AI."
  },
  {
    "id": 137,
    "word": "human",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hjˈumən/",
    "meaning": "thuộc con người",
    "ex1": "A human example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ thuộc con người có thể làm cho việc luyện tập với Chat AI dễ hơn."
  },
  {
    "id": 138,
    "word": "creativity",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌkriːeɪˈtɪvəti/",
    "meaning": "sự sáng tạo",
    "ex1": "Students discuss creativity while learning how to use Chat AI.",
    "ex1_vi": "Học sinh thảo luận về sự sáng tạo khi học cách sử dụng Chat AI."
  },
  {
    "id": 139,
    "word": "best",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɛst/",
    "meaning": "tốt nhất",
    "ex1": "The best results combine AI support with human ideas.",
    "ex1_vi": "Kết quả tốt nhất kết hợp sự hỗ trợ của AI với ý tưởng con người."
  },
  {
    "id": 140,
    "word": "comes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌmz/",
    "meaning": "đến",
    "ex1": "Good content comes from combining technology with personal ideas.",
    "ex1_vi": "Nội dung tốt đến từ việc kết hợp công nghệ với ý tưởng cá nhân."
  },
  {
    "id": 141,
    "word": "combining",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kəmˈbaɪnɪŋ/",
    "meaning": "việc kết hợp",
    "ex1": "Combining AI support with human creativity can improve content.",
    "ex1_vi": "Kết hợp hỗ trợ AI với sáng tạo của con người có thể cải thiện nội dung."
  },
  {
    "id": 142,
    "word": "personal",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɜːsənəl/",
    "meaning": "cá nhân",
    "ex1": "A personal example can make Chat AI practice easier.",
    "ex1_vi": "Một ví dụ cá nhân có thể làm cho việc luyện tập với Chat AI dễ hơn."
  }
];

const newReadingVocabOrder = [
  "chat",
  "ai",
  "students",
  "helpful",
  "because",
  "can",
  "explain",
  "lessons",
  "simple",
  "way",
  "when",
  "do",
  "not",
  "understand",
  "topic",
  "ask",
  "examples",
  "summaries",
  "or",
  "practice",
  "questions",
  "this",
  "makes",
  "learning",
  "faster",
  "and",
  "more",
  "interesting",
  "use",
  "prepare",
  "presentations",
  "check",
  "grammar",
  "improve",
  "writing",
  "review",
  "before",
  "exams",
  "also",
  "help",
  "manage",
  "study",
  "time",
  "create",
  "plans",
  "however",
  "should",
  "copy",
  "answers",
  "without",
  "thinking",
  "learn",
  "cheat",
  "good",
  "technology",
  "responsibly",
  "try",
  "lesson",
  "work",
  "becoming",
  "popular",
  "many",
  "workplaces",
  "workers",
  "write",
  "emails",
  "reports",
  "summarize",
  "documents",
  "ideas",
  "projects",
  "saves",
  "helps",
  "people",
  "efficiently",
  "offices",
  "support",
  "customer",
  "service",
  "marketing",
  "planning",
  "communication",
  "new",
  "skills",
  "difficult",
  "information",
  "quickly",
  "careful",
  "using",
  "private",
  "company",
  "important",
  "decisions",
  "still",
  "checked",
  "humans",
  "useful",
  "assistant",
  "but",
  "used",
  "responsibility",
  "judgment",
  "clear",
  "creating",
  "content",
  "types",
  "social",
  "media",
  "posts",
  "short",
  "stories",
  "advertisements",
  "video",
  "scripts",
  "notes",
  "product",
  "descriptions",
  "very",
  "teachers",
  "business",
  "owners",
  "creators",
  "users",
  "save",
  "get",
  "make",
  "shorter",
  "longer",
  "simpler",
  "professional",
  "edit",
  "posting",
  "may",
  "mistakes",
  "boring",
  "sentences",
  "human",
  "creativity",
  "best",
  "comes",
  "combining",
  "personal"
];
