// ===== communication02 VOCABULARY =====

const lessonVocabularyWords = [
  "sending",
  "messages",
  "fast",
  "and",
  "easy",
  "way",
  "communicate",
  "today",
  "people",
  "use",
  "mobile",
  "phones",
  "emails",
  "social",
  "media",
  "share",
  "information",
  "help",
  "friends",
  "families",
  "classmates",
  "coworkers",
  "stay",
  "connected",
  "wherever",
  "every",
  "day",
  "send",
  "make",
  "plans",
  "ask",
  "questions",
  "give",
  "reminders",
  "or",
  "good",
  "news",
  "short",
  "clear",
  "sentences",
  "understand",
  "using",
  "polite",
  "words",
  "checking",
  "spelling",
  "can",
  "prevent",
  "confusion",
  "improve",
  "communication",
  "between",
  "should",
  "friendly",
  "respectful",
  "read",
  "reply",
  "time",
  "when",
  "possible",
  "avoid",
  "unnecessary",
  "helps",
  "build",
  "stronger",
  "relationships",
  "save",
  "daily",
  "life",
  "more",
  "convenient",
  "asking",
  "normal",
  "part",
  "everyday",
  "everyone",
  "sometimes",
  "needs",
  "support",
  "school",
  "work",
  "shopping",
  "other",
  "activities",
  "politely",
  "makes",
  "others",
  "feel",
  "respected",
  "willing",
  "offer",
  "useful",
  "assistance",
  "needed",
  "teachers",
  "family",
  "members",
  "neighbors",
  "explain",
  "problem",
  "clearly",
  "listen",
  "carefully",
  "advice",
  "saying",
  "please",
  "thank",
  "shows",
  "manners",
  "appreciation",
  "another",
  "person's",
  "helping",
  "each",
  "creates",
  "happier",
  "communities",
  "never",
  "embarrassed",
  "requesting",
  "kindness",
  "respect",
  "gratitude",
  "easier",
  "working",
  "together",
  "solve",
  "problems",
  "learn",
  "new",
  "skills",
  "giving",
  "directions",
  "important",
  "skill",
  "visitors",
  "often",
  "need",
  "finding",
  "schools",
  "hospitals",
  "restaurants",
  "bus",
  "stations",
  "parks",
  "arrive",
  "safely",
  "during",
  "journeys",
  "usually",
  "simple",
  "like",
  "left",
  "right",
  "straight",
  "across",
  "next",
  "may",
  "also",
  "mention",
  "traffic",
  "lights",
  "bridges",
  "large",
  "buildings",
  "landmarks",
  "speaking",
  "slowly",
  "correctly",
  "patient",
  "if",
  "repeat",
  "draw",
  "map",
  "reduces",
  "welcome",
  "strangers",
  "caring",
  "community"
];

const newVocabData = [
  {
    "id": 1,
    "word": "sending",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɛndɪŋ/",
    "meaning": "gửi",
    "ex1": "Sending messages helps friends stay connected every day.",
    "ex1_vi": "Hoạt động gửi xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 2,
    "word": "messages",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛsʌdʒʌz/",
    "meaning": "tin nhắn",
    "ex1": "Sending messages is a fast and easy way to communicate today.",
    "ex1_vi": "Gửi tin nhắn là một cách giao tiếp nhanh chóng và dễ dàng ngày nay."
  },
  {
    "id": 3,
    "word": "fast",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈæst/",
    "meaning": "nhanh",
    "ex1": "Sending messages is a fast way to communicate today.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “nhanh” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 4,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Sending messages is a fast and easy way to communicate today.",
    "ex1_vi": "Gửi tin nhắn là một cách giao tiếp nhanh chóng và dễ dàng ngày nay."
  },
  {
    "id": 5,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ dàng",
    "ex1": "Clear messages are easy to understand in daily communication.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “dễ dàng” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 6,
    "word": "way",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈeɪ/",
    "meaning": "cách",
    "ex1": "Phone calls are a common way to communicate every day.",
    "ex1_vi": "Mọi người thường nhắc đến cách trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 7,
    "word": "communicate",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌmjˈunʌkˌeɪt/",
    "meaning": "giao tiếp",
    "ex1": "People communicate clearly and politely in daily life.",
    "ex1_vi": "Hoạt động giao tiếp xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 8,
    "word": "today",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌdˈeɪ/",
    "meaning": "hôm nay",
    "ex1": "People use messages to communicate quickly and clearly today.",
    "ex1_vi": "Mọi người giao tiếp hôm nay trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 9,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "Today, People use mobile phones in daily life.",
    "ex1_vi": "Mọi người thường nhắc đến mọi người trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 10,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "Today, People use mobile phones in daily life.",
    "ex1_vi": "Hoạt động sử dụng xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 11,
    "word": "mobile",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈoʊbʌl/",
    "meaning": "di động",
    "ex1": "Usually, People use mobile phones in daily life.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “di động” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 12,
    "word": "phones",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈoʊnz/",
    "meaning": "điện thoại",
    "ex1": "Usually, People use mobile phones in daily life.",
    "ex1_vi": "Mọi người thường nhắc đến điện thoại trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 13,
    "word": "emails",
    "type": "noun",
    "cat": "n",
    "phonetic": "/imˈeɪlz/",
    "meaning": "email",
    "ex1": "We discussed emails during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến email trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 14,
    "word": "social",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈoʊʃʌl/",
    "meaning": "xã hội",
    "ex1": "People use social media to share information every day.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “xã hội” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 15,
    "word": "media",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈidiʌ/",
    "meaning": "truyền thông",
    "ex1": "People use social media to share information every day.",
    "ex1_vi": "Mọi người thường nhắc đến truyền thông trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 16,
    "word": "share",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈɛr/",
    "meaning": "chia sẻ",
    "ex1": "People share useful information through messages every day.",
    "ex1_vi": "Hoạt động chia sẻ xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 17,
    "word": "information",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnfɝmˈeɪʃʌn/",
    "meaning": "thông tin",
    "ex1": "Messages help people share important information quickly every day.",
    "ex1_vi": "Mọi người thường nhắc đến thông tin trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 18,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp đỡ",
    "ex1": "Friends help each other solve problems during conversations every day.",
    "ex1_vi": "Hoạt động giúp đỡ xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 19,
    "word": "friends",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈɛndz/",
    "meaning": "bạn bè",
    "ex1": "At school, Messages help friends in daily life.",
    "ex1_vi": "Mọi người thường nhắc đến bạn bè trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 20,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌliz/",
    "meaning": "các gia đình",
    "ex1": "We discussed families during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến các gia đình trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 21,
    "word": "classmates",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈæsmˌeɪts/",
    "meaning": "bạn cùng lớp",
    "ex1": "We discussed classmates during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến bạn cùng lớp trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 22,
    "word": "coworkers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈoʊwˈɝkɝz/",
    "meaning": "đồng nghiệp",
    "ex1": "Coworkers use messages to stay connected during busy workdays.",
    "ex1_vi": "Mọi người thường nhắc đến đồng nghiệp trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 23,
    "word": "stay",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈeɪ/",
    "meaning": "duy trì; ở lại",
    "ex1": "Friends stay connected by sending clear messages every day.",
    "ex1_vi": "Hoạt động duy trì; ở lại xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 24,
    "word": "connected",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌnˈɛktɪd/",
    "meaning": "kết nối",
    "ex1": "Messages help friends stay connected wherever they are every day.",
    "ex1_vi": "Hoạt động kết nối xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 25,
    "word": "wherever",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wɛrˈɛvɝ/",
    "meaning": "bất cứ nơi đâu",
    "ex1": "Messages keep people connected wherever they are during the day.",
    "ex1_vi": "Mọi người giao tiếp bất cứ nơi đâu trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 26,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɝi/",
    "meaning": "mỗi",
    "ex1": "People can practice clear communication every day with others.",
    "ex1_vi": "Giao tiếp tốt giúp mọi người hiểu nhau mỗi ngày."
  },
  {
    "id": 27,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "People send useful messages during the day when necessary.",
    "ex1_vi": "Mọi người thường nhắc đến ngày trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 28,
    "word": "send",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɛnd/",
    "meaning": "gửi",
    "ex1": "People send messages to make plans every day.",
    "ex1_vi": "Hoạt động gửi xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 29,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm; khiến",
    "ex1": "Respect and patience make shopping more enjoyable for everyone.",
    "ex1_vi": "Hoạt động làm; khiến xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 30,
    "word": "plans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈænz/",
    "meaning": "kế hoạch",
    "ex1": "Friends often make plans together during conversations after school.",
    "ex1_vi": "Mọi người thường nhắc đến kế hoạch trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 31,
    "word": "ask",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈæsk/",
    "meaning": "hỏi",
    "ex1": "At school, People ask questions in daily life.",
    "ex1_vi": "Hoạt động hỏi xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 32,
    "word": "questions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kwˈɛstʃʌnz/",
    "meaning": "câu hỏi",
    "ex1": "At school, People ask questions in daily life.",
    "ex1_vi": "Mọi người thường nhắc đến câu hỏi trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 33,
    "word": "give",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪv/",
    "meaning": "đưa; cho",
    "ex1": "At school, People give reminders in daily life.",
    "ex1_vi": "Hoạt động đưa; cho xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 34,
    "word": "reminders",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rimˈaɪndɝz/",
    "meaning": "lời nhắc",
    "ex1": "At school, People give reminders in daily life.",
    "ex1_vi": "Mọi người thường nhắc đến lời nhắc trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 35,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "People can call or send messages when they need help.",
    "ex1_vi": "Mọi người có thể gọi điện hoặc gửi tin nhắn khi họ cần giúp đỡ."
  },
  {
    "id": 36,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "Today, People share good news in daily life.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “tốt” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 37,
    "word": "news",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈuz/",
    "meaning": "tin tức",
    "ex1": "Today, People share good news in daily life.",
    "ex1_vi": "Mọi người thường nhắc đến tin tức trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 38,
    "word": "short",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɔrt/",
    "meaning": "ngắn",
    "ex1": "Short and clear sentences make messages easy to understand.",
    "ex1_vi": "Những câu ngắn và rõ ràng làm cho tin nhắn dễ hiểu."
  },
  {
    "id": 39,
    "word": "clear",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈɪr/",
    "meaning": "rõ ràng",
    "ex1": "Clear communication makes shopping easier and more enjoyable for everyone.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “rõ ràng” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 40,
    "word": "sentences",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛntʌnsʌz/",
    "meaning": "câu",
    "ex1": "Short and clear sentences make messages easy to understand.",
    "ex1_vi": "Những câu ngắn và rõ ràng làm cho tin nhắn dễ hiểu."
  },
  {
    "id": 41,
    "word": "understand",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌʌndɝstˈænd/",
    "meaning": "hiểu",
    "ex1": "Good conversations help people understand each other much better.",
    "ex1_vi": "Hoạt động hiểu xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 42,
    "word": "using",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzɪŋ/",
    "meaning": "sử dụng",
    "ex1": "Using regularly helps people practice useful communication skills daily.",
    "ex1_vi": "Hoạt động sử dụng xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 43,
    "word": "polite",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pʌlˈaɪt/",
    "meaning": "lịch sự",
    "ex1": "Polite language helps people communicate respectfully in many situations.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “lịch sự” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 44,
    "word": "words",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝdz/",
    "meaning": "lời nói; từ ngữ",
    "ex1": "We discussed words during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến lời nói; từ ngữ trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 45,
    "word": "checking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈɛkɪŋ/",
    "meaning": "kiểm tra",
    "ex1": "Checking regularly helps people practice useful communication skills daily.",
    "ex1_vi": "Hoạt động kiểm tra xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 46,
    "word": "spelling",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈɛlɪŋ/",
    "meaning": "chính tả",
    "ex1": "We discussed spelling during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến chính tả trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 47,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "People can communicate clearly and politely with others every day.",
    "ex1_vi": "Mọi người có thể giao tiếp rõ ràng và lịch sự với người khác mỗi ngày."
  },
  {
    "id": 48,
    "word": "prevent",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prɪvˈɛnt/",
    "meaning": "ngăn ngừa",
    "ex1": "People often prevent during friendly communication activities every day.",
    "ex1_vi": "Hoạt động ngăn ngừa xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 49,
    "word": "confusion",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌnfjˈuʒʌn/",
    "meaning": "sự nhầm lẫn",
    "ex1": "We discussed confusion during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến sự nhầm lẫn trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 50,
    "word": "improve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪmprˈuv/",
    "meaning": "cải thiện",
    "ex1": "People can improve communication through regular practice every day.",
    "ex1_vi": "Hoạt động cải thiện xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 51,
    "word": "communication",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌmjˌunʌkˈeɪʃʌn/",
    "meaning": "giao tiếp",
    "ex1": "We discussed communication during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến giao tiếp trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 52,
    "word": "between",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/bɪtwˈin/",
    "meaning": "giữa",
    "ex1": "Clear messages improve communication between people in daily life.",
    "ex1_vi": "Du khách đi băng qua đường sau khi nhận được chỉ dẫn rõ ràng."
  },
  {
    "id": 53,
    "word": "should",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/ʃˈʊd/",
    "meaning": "nên",
    "ex1": "Good messages should be friendly in daily life.",
    "ex1_vi": "Mọi người nên giao tiếp rõ ràng và lịch sự với người khác mỗi ngày."
  },
  {
    "id": 54,
    "word": "friendly",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛndli/",
    "meaning": "thân thiện",
    "ex1": "Good messages should be friendly in daily life.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “thân thiện” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 55,
    "word": "respectful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪspˈɛktfʌl/",
    "meaning": "tôn trọng; lịch sự",
    "ex1": "People noticed something respectful during a friendly conversation today.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “tôn trọng; lịch sự” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 56,
    "word": "read",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈɛd/",
    "meaning": "đọc",
    "ex1": "At school, easy to read in daily life.",
    "ex1_vi": "Hoạt động đọc xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 57,
    "word": "reply",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪplˈaɪ/",
    "meaning": "trả lời",
    "ex1": "People should reply on time when possible and avoid sending unnecessary messages.",
    "ex1_vi": "Mọi người nên trả lời đúng lúc khi có thể và tránh gửi những tin nhắn không cần thiết."
  },
  {
    "id": 58,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "People should reply on time when possible and avoid sending unnecessary messages.",
    "ex1_vi": "Mọi người nên trả lời đúng lúc khi có thể và tránh gửi những tin nhắn không cần thiết."
  },
  {
    "id": 59,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "People listen carefully when friends share important ideas together.",
    "ex1_vi": "Mọi người lắng nghe cẩn thận khi bạn bè chia sẻ những ý tưởng quan trọng."
  },
  {
    "id": 60,
    "word": "possible",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑsʌbʌl/",
    "meaning": "có thể",
    "ex1": "People noticed something possible during a friendly conversation today.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “có thể” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 61,
    "word": "avoid",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌvˈɔɪd/",
    "meaning": "tránh",
    "ex1": "People can avoid misunderstandings by speaking clearly and politely.",
    "ex1_vi": "Hoạt động tránh xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 62,
    "word": "unnecessary",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌnnˈɛsʌsˌɛri/",
    "meaning": "không cần thiết",
    "ex1": "People noticed something unnecessary during a friendly conversation today.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “không cần thiết” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 63,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "Clear communication helps people solve problems more easily.",
    "ex1_vi": "Hoạt động giúp xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 64,
    "word": "build",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɪld/",
    "meaning": "xây dựng",
    "ex1": "Honest conversations build strong friendships between people over time.",
    "ex1_vi": "Hoạt động xây dựng xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 65,
    "word": "stronger",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋɝ/",
    "meaning": "bền chặt hơn",
    "ex1": "Clear communication helps build stronger relationships every day.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “bền chặt hơn” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 66,
    "word": "relationships",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rilˈeɪʃʌnʃˌɪps/",
    "meaning": "các mối quan hệ",
    "ex1": "Clear communication helps build stronger relationships every day.",
    "ex1_vi": "Mọi người thường nhắc đến các mối quan hệ trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 67,
    "word": "save",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪv/",
    "meaning": "tiết kiệm",
    "ex1": "Today, Clear communication save time in daily life.",
    "ex1_vi": "Hoạt động tiết kiệm xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 68,
    "word": "daily",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈeɪli/",
    "meaning": "hằng ngày",
    "ex1": "Clear communication make daily life more convenient every day.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “hằng ngày” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 69,
    "word": "life",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪf/",
    "meaning": "cuộc sống",
    "ex1": "Good communication skills are important in daily life and work.",
    "ex1_vi": "Mọi người thường nhắc đến cuộc sống trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 70,
    "word": "more",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "hơn; nhiều hơn",
    "ex1": "Polite communication makes shopping more enjoyable for both sides.",
    "ex1_vi": "Tin nhắn rõ ràng làm cho giao tiếp hằng ngày thuận tiện hơn."
  },
  {
    "id": 71,
    "word": "convenient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kʌnvˈinjʌnt/",
    "meaning": "thuận tiện",
    "ex1": "Clear communication make daily life more convenient every day.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “thuận tiện” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 72,
    "word": "asking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈæskɪŋ/",
    "meaning": "việc hỏi",
    "ex1": "Asking for help is a normal part of everyday life.",
    "ex1_vi": "Nhờ giúp đỡ là một phần bình thường của cuộc sống hằng ngày."
  },
  {
    "id": 73,
    "word": "normal",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈɔrmʌl/",
    "meaning": "bình thường",
    "ex1": "Asking for help is a normal part of everyday life.",
    "ex1_vi": "Nhờ giúp đỡ là một phần bình thường của cuộc sống hằng ngày."
  },
  {
    "id": 74,
    "word": "part",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrt/",
    "meaning": "phần",
    "ex1": "Asking for help is a normal part of everyday life every day.",
    "ex1_vi": "Mọi người thường nhắc đến phần trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 75,
    "word": "everyday",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɛvridˈeɪ/",
    "meaning": "hằng ngày",
    "ex1": "Communication skills are useful in everyday life and work.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “hằng ngày” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 76,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvriwˌʌn/",
    "meaning": "mọi người",
    "ex1": "Everyone sometimes needs support with school every day.",
    "ex1_vi": "Đại từ này được dùng tự nhiên khi mọi người giao tiếp và nói về mọi người."
  },
  {
    "id": 77,
    "word": "sometimes",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sʌmtˈaɪmz/",
    "meaning": "đôi khi",
    "ex1": "Everyone sometimes needs support with school every day.",
    "ex1_vi": "Mọi người giao tiếp đôi khi trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 78,
    "word": "needs",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈidz/",
    "meaning": "cần",
    "ex1": "Everyone sometimes needs support with school with friends.",
    "ex1_vi": "Hoạt động cần xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 79,
    "word": "support",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sʌpˈɔrt/",
    "meaning": "hỗ trợ",
    "ex1": "Everyone sometimes needs support with school with friends.",
    "ex1_vi": "Hoạt động hỗ trợ xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 80,
    "word": "school",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈul/",
    "meaning": "trường học",
    "ex1": "Everyone sometimes needs support with school at school.",
    "ex1_vi": "Mọi người thường nhắc đến trường học trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 81,
    "word": "work",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝk/",
    "meaning": "công việc; làm việc",
    "ex1": "People discuss work tasks with colleagues during daily meetings.",
    "ex1_vi": "Mọi người thường nhắc đến công việc; làm việc trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 82,
    "word": "shopping",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɑpɪŋ/",
    "meaning": "mua sắm",
    "ex1": "Shopping conversations help customers find suitable products more easily.",
    "ex1_vi": "Mọi người thường nhắc đến mua sắm trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 83,
    "word": "other",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈʌðɝ/",
    "meaning": "khác; nhau",
    "ex1": "People sometimes need help with other daily activities too.",
    "ex1_vi": "Đại từ này được dùng tự nhiên khi mọi người giao tiếp và nói về khác; nhau."
  },
  {
    "id": 84,
    "word": "activities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/æktˈɪvʌtiz/",
    "meaning": "hoạt động",
    "ex1": "Friends enjoy different activities and talk about them together.",
    "ex1_vi": "Mọi người thường nhắc đến hoạt động trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 85,
    "word": "politely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/pʌlˈaɪtli/",
    "meaning": "một cách lịch sự",
    "ex1": "Friends communicated politely during a friendly conversation at school.",
    "ex1_vi": "Mọi người giao tiếp một cách lịch sự trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 86,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm; khiến",
    "ex1": "People often makes during friendly communication activities every day.",
    "ex1_vi": "Hoạt động làm; khiến xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 87,
    "word": "others",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈʌðɝz/",
    "meaning": "những người khác",
    "ex1": "Polite people listen carefully and show interest in others.",
    "ex1_vi": "Đại từ này được dùng tự nhiên khi mọi người giao tiếp và nói về những người khác."
  },
  {
    "id": 88,
    "word": "feel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈil/",
    "meaning": "cảm thấy",
    "ex1": "People often feel during friendly communication activities every day.",
    "ex1_vi": "Hoạt động cảm thấy xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 89,
    "word": "respected",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪspˈɛktɪd/",
    "meaning": "được tôn trọng",
    "ex1": "People noticed something respected during a friendly conversation today.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “được tôn trọng” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 90,
    "word": "willing",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈɪlɪŋ/",
    "meaning": "sẵn lòng",
    "ex1": "People noticed something willing during a friendly conversation today.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “sẵn lòng” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 91,
    "word": "offer",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɔfɝ/",
    "meaning": "đề nghị; cung cấp",
    "ex1": "People often offer during friendly communication activities every day.",
    "ex1_vi": "Hoạt động đề nghị; cung cấp xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 92,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈusfʌl/",
    "meaning": "hữu ích",
    "ex1": "People noticed something useful during a friendly conversation today.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “hữu ích” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 93,
    "word": "assistance",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌsˈɪstʌns/",
    "meaning": "sự giúp đỡ",
    "ex1": "We discussed assistance during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến sự giúp đỡ trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 94,
    "word": "needed",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈidʌd/",
    "meaning": "cần thiết",
    "ex1": "People noticed something needed during a friendly conversation today.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “cần thiết” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 95,
    "word": "teachers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈitʃɝz/",
    "meaning": "giáo viên",
    "ex1": "Today, People can ask teachers in daily life.",
    "ex1_vi": "Mọi người thường nhắc đến giáo viên trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 96,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "People can ask family members for help when needed.",
    "ex1_vi": "Mọi người thường nhắc đến gia đình trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 97,
    "word": "members",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛmbɝz/",
    "meaning": "thành viên",
    "ex1": "Family members often help each other with daily problems.",
    "ex1_vi": "Mọi người thường nhắc đến thành viên trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 98,
    "word": "neighbors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈeɪbɝz/",
    "meaning": "hàng xóm",
    "ex1": "We discussed neighbors during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến hàng xóm trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 99,
    "word": "explain",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɪksplˈeɪn/",
    "meaning": "giải thích",
    "ex1": "They should explain the problem clearly and listen carefully to the advice.",
    "ex1_vi": "Họ nên giải thích vấn đề rõ ràng và lắng nghe lời khuyên cẩn thận."
  },
  {
    "id": 100,
    "word": "problem",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑblʌm/",
    "meaning": "vấn đề",
    "ex1": "People should explain the problem clearly when asking for help.",
    "ex1_vi": "Mọi người thường nhắc đến vấn đề trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 101,
    "word": "clearly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/klˈɪrli/",
    "meaning": "rõ ràng",
    "ex1": "They should explain the problem clearly and listen carefully to the advice.",
    "ex1_vi": "Họ nên giải thích vấn đề rõ ràng và lắng nghe lời khuyên cẩn thận."
  },
  {
    "id": 102,
    "word": "listen",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɪsʌn/",
    "meaning": "lắng nghe",
    "ex1": "People listen carefully when others give useful advice.",
    "ex1_vi": "Hoạt động lắng nghe xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 103,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "Friends communicated carefully during a friendly conversation at school.",
    "ex1_vi": "Mọi người giao tiếp cẩn thận trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 104,
    "word": "advice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ædvˈaɪs/",
    "meaning": "lời khuyên",
    "ex1": "We discussed advice during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến lời khuyên trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 105,
    "word": "saying",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈeɪɪŋ/",
    "meaning": "việc nói",
    "ex1": "Saying regularly helps people practice useful communication skills daily.",
    "ex1_vi": "Hoạt động việc nói xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 106,
    "word": "please",
    "type": "interjection",
    "cat": "adv",
    "phonetic": "/plˈiz/",
    "meaning": "làm ơn",
    "ex1": "People say please when they ask others for help politely.",
    "ex1_vi": "Mọi người nói “làm ơn” khi họ lịch sự nhờ người khác giúp đỡ."
  },
  {
    "id": 107,
    "word": "thank",
    "type": "verb",
    "cat": "v",
    "phonetic": "/θˈæŋk/",
    "meaning": "cảm ơn",
    "ex1": "Customers thank shop assistants after receiving useful help.",
    "ex1_vi": "Hoạt động cảm ơn xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 108,
    "word": "shows",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈoʊz/",
    "meaning": "cho thấy",
    "ex1": "Listening carefully shows respect during friendly conversations with others.",
    "ex1_vi": "Hoạt động cho thấy xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 109,
    "word": "manners",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈænɝz/",
    "meaning": "phép lịch sự",
    "ex1": "We discussed manners during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến phép lịch sự trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 110,
    "word": "appreciation",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌprˌiʃiˈeɪʃʌn/",
    "meaning": "sự cảm kích",
    "ex1": "We discussed appreciation during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến sự cảm kích trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 111,
    "word": "another",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ʌnˈʌðɝ/",
    "meaning": "một người khác",
    "ex1": "People can ask another person for help when necessary.",
    "ex1_vi": "Mọi người có thể nhờ một người khác giúp đỡ khi cần."
  },
  {
    "id": 112,
    "word": "person's",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɝsʌnz/",
    "meaning": "của một người",
    "ex1": "We discussed person's during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến của một người trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 113,
    "word": "helping",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlpɪŋ/",
    "meaning": "giúp đỡ",
    "ex1": "Helping each other creates stronger relationships and happier communities.",
    "ex1_vi": "Giúp đỡ lẫn nhau tạo nên những mối quan hệ bền chặt hơn và cộng đồng hạnh phúc hơn."
  },
  {
    "id": 114,
    "word": "each",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈitʃ/",
    "meaning": "mỗi",
    "ex1": "Helping each other creates stronger relationships and happier communities.",
    "ex1_vi": "Giúp đỡ lẫn nhau tạo nên những mối quan hệ bền chặt hơn và cộng đồng hạnh phúc hơn."
  },
  {
    "id": 115,
    "word": "creates",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪts/",
    "meaning": "tạo ra",
    "ex1": "Helping each other creates stronger relationships and happier communities every day.",
    "ex1_vi": "Hoạt động tạo ra xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 116,
    "word": "happier",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈæpiɝ/",
    "meaning": "vui hơn",
    "ex1": "Good communication can create happier workplaces for many people.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “vui hơn” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 117,
    "word": "communities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌmjˈunʌtiz/",
    "meaning": "cộng đồng",
    "ex1": "Helping each other creates stronger relationships and happier communities every day.",
    "ex1_vi": "Mọi người thường nhắc đến cộng đồng trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 118,
    "word": "never",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɛvɝ/",
    "meaning": "không bao giờ",
    "ex1": "People should never feel embarrassed about asking questions or requesting support.",
    "ex1_vi": "Mọi người không bao giờ nên cảm thấy xấu hổ khi đặt câu hỏi hoặc yêu cầu hỗ trợ."
  },
  {
    "id": 119,
    "word": "embarrassed",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪmbˈɛrʌst/",
    "meaning": "ngại ngùng",
    "ex1": "People should never feel embarrassed about asking questions or requesting support.",
    "ex1_vi": "Mọi người không bao giờ nên cảm thấy xấu hổ khi đặt câu hỏi hoặc yêu cầu hỗ trợ."
  },
  {
    "id": 120,
    "word": "requesting",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪkwˈɛstɪŋ/",
    "meaning": "yêu cầu",
    "ex1": "People should never feel embarrassed about asking questions or requesting support today.",
    "ex1_vi": "Hoạt động yêu cầu xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 121,
    "word": "kindness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈaɪndnʌs/",
    "meaning": "lòng tốt",
    "ex1": "We discussed kindness during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến lòng tốt trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 122,
    "word": "respect",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rɪspˈɛkt/",
    "meaning": "sự tôn trọng; tôn trọng",
    "ex1": "We discussed respect during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến sự tôn trọng; tôn trọng trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 123,
    "word": "gratitude",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡrˈætʌtˌud/",
    "meaning": "lòng biết ơn",
    "ex1": "Today, gratitude make communication easier in daily life.",
    "ex1_vi": "Mọi người thường nhắc đến lòng biết ơn trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 124,
    "word": "easier",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈiziɝ/",
    "meaning": "dễ hơn",
    "ex1": "Today, gratitude make communication easier in daily life.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “dễ hơn” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 125,
    "word": "working",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝkɪŋ/",
    "meaning": "làm việc",
    "ex1": "Working with others helps people build stronger communication skills.",
    "ex1_vi": "Hoạt động làm việc xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 126,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌɡˈɛðɝ/",
    "meaning": "cùng nhau",
    "ex1": "Friends often talk and solve problems together after school.",
    "ex1_vi": "Mọi người giao tiếp cùng nhau trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 127,
    "word": "solve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɑlv/",
    "meaning": "giải quyết",
    "ex1": "Working together helps everyone solve problems and learn new skills.",
    "ex1_vi": "Cùng làm việc giúp mọi người giải quyết vấn đề và học những kỹ năng mới."
  },
  {
    "id": 128,
    "word": "problems",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑblʌmz/",
    "meaning": "vấn đề",
    "ex1": "Working together helps everyone solve problems and learn new skills.",
    "ex1_vi": "Cùng làm việc giúp mọi người giải quyết vấn đề và học những kỹ năng mới."
  },
  {
    "id": 129,
    "word": "learn",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɝn/",
    "meaning": "học",
    "ex1": "Working together helps everyone solve problems and learn new skills every day.",
    "ex1_vi": "Hoạt động học xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 130,
    "word": "new",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈu/",
    "meaning": "mới",
    "ex1": "Working together helps everyone solve problems and learn new skills every day.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “mới” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 131,
    "word": "skills",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪlz/",
    "meaning": "kỹ năng",
    "ex1": "Working together helps everyone solve problems and learn new skills today.",
    "ex1_vi": "Mọi người thường nhắc đến kỹ năng trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 132,
    "word": "giving",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvɪŋ/",
    "meaning": "chỉ dẫn; đưa",
    "ex1": "Giving directions is an important communication skill in daily life.",
    "ex1_vi": "Chỉ đường là một kỹ năng giao tiếp quan trọng trong cuộc sống hằng ngày."
  },
  {
    "id": 133,
    "word": "directions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɝˈɛkʃʌnz/",
    "meaning": "chỉ đường",
    "ex1": "Giving directions is an important communication skill in daily life.",
    "ex1_vi": "Chỉ đường là một kỹ năng giao tiếp quan trọng trong cuộc sống hằng ngày."
  },
  {
    "id": 134,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔrtʌnt/",
    "meaning": "quan trọng",
    "ex1": "Giving directions is an important communication skill in daily life every day.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “quan trọng” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 135,
    "word": "skill",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪl/",
    "meaning": "kỹ năng",
    "ex1": "Giving directions is an important communication skill in daily life every day.",
    "ex1_vi": "Mọi người thường nhắc đến kỹ năng trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 136,
    "word": "visitors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪzɪtɝz/",
    "meaning": "du khách",
    "ex1": "Visitors often need help finding schools every day.",
    "ex1_vi": "Mọi người thường nhắc đến du khách trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 137,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường xuyên",
    "ex1": "Visitors often need help finding schools every day.",
    "ex1_vi": "Mọi người giao tiếp thường xuyên trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 138,
    "word": "need",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈid/",
    "meaning": "cần",
    "ex1": "Visitors often need help finding schools with friends.",
    "ex1_vi": "Hoạt động cần xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 139,
    "word": "finding",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪndɪŋ/",
    "meaning": "tìm",
    "ex1": "Visitors often need help finding schools with friends.",
    "ex1_vi": "Hoạt động tìm xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 140,
    "word": "schools",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈulz/",
    "meaning": "trường học",
    "ex1": "Visitors often need help finding schools at school.",
    "ex1_vi": "Mọi người thường nhắc đến trường học trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 141,
    "word": "hospitals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɑspˌɪtʌlz/",
    "meaning": "bệnh viện",
    "ex1": "We discussed hospitals during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến bệnh viện trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 142,
    "word": "restaurants",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɛstɝˌɑnts/",
    "meaning": "nhà hàng",
    "ex1": "We discussed restaurants during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến nhà hàng trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 143,
    "word": "bus",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʌs/",
    "meaning": "xe buýt",
    "ex1": "Visitors may need directions to a bus station nearby.",
    "ex1_vi": "Mọi người thường nhắc đến xe buýt trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 144,
    "word": "stations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈeɪʃʌnz/",
    "meaning": "trạm; nhà ga",
    "ex1": "Clear directions help visitors find bus stations more easily.",
    "ex1_vi": "Mọi người thường nhắc đến trạm; nhà ga trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 145,
    "word": "parks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrks/",
    "meaning": "công viên",
    "ex1": "We discussed parks during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến công viên trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 146,
    "word": "arrive",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɝˈaɪv/",
    "meaning": "đến",
    "ex1": "People often arrive during friendly communication activities every day.",
    "ex1_vi": "Hoạt động đến xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 147,
    "word": "safely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sˈeɪfli/",
    "meaning": "an toàn",
    "ex1": "Friends communicated safely during a friendly conversation at school.",
    "ex1_vi": "Mọi người giao tiếp an toàn trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 148,
    "word": "during",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/dˈʊrɪŋ/",
    "meaning": "trong suốt; trong khi",
    "ex1": "People speak clearly during friendly conversations with others every day.",
    "ex1_vi": "Du khách đi băng qua đường sau khi nhận được chỉ dẫn rõ ràng."
  },
  {
    "id": 149,
    "word": "journeys",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɝniz/",
    "meaning": "hành trình",
    "ex1": "We discussed journeys during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến hành trình trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 150,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "People usually introduce themselves before starting a new conversation.",
    "ex1_vi": "Mọi người giao tiếp thường trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 151,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "People usually use simple words like left every day.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “đơn giản” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 152,
    "word": "like",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪk/",
    "meaning": "như",
    "ex1": "People usually use simple words like left every day.",
    "ex1_vi": "Mọi người thường nhắc đến như trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 153,
    "word": "left",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/lˈɛft/",
    "meaning": "trái",
    "ex1": "People usually use simple words like left today.",
    "ex1_vi": "Mọi người giao tiếp trái trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 154,
    "word": "right",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/rˈaɪt/",
    "meaning": "phải",
    "ex1": "At school, People usually right in daily life.",
    "ex1_vi": "Mọi người giao tiếp phải trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 155,
    "word": "straight",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/strˈeɪt/",
    "meaning": "thẳng",
    "ex1": "At school, People usually straight in daily life.",
    "ex1_vi": "Mọi người giao tiếp thẳng trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 156,
    "word": "across",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ʌkrˈɔs/",
    "meaning": "băng qua; đối diện",
    "ex1": "Visitors walk across the street after receiving clear directions.",
    "ex1_vi": "Du khách đi băng qua đường sau khi nhận được chỉ dẫn rõ ràng."
  },
  {
    "id": 157,
    "word": "next",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɛkst/",
    "meaning": "kế tiếp",
    "ex1": "Today, People usually next to in daily life.",
    "ex1_vi": "Mọi người giao tiếp kế tiếp trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 158,
    "word": "may",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈeɪ/",
    "meaning": "có thể",
    "ex1": "They may also mention traffic lights every day.",
    "ex1_vi": "Mọi người có thể giao tiếp rõ ràng và lịch sự với người khác mỗi ngày."
  },
  {
    "id": 159,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "They may also mention traffic lights every day.",
    "ex1_vi": "Mọi người giao tiếp cũng trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 160,
    "word": "mention",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈɛnʃʌn/",
    "meaning": "đề cập",
    "ex1": "They may also mention traffic lights with friends.",
    "ex1_vi": "Hoạt động đề cập xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 161,
    "word": "traffic",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈæfɪk/",
    "meaning": "giao thông",
    "ex1": "They may also mention traffic lights with friends.",
    "ex1_vi": "Mọi người thường nhắc đến giao thông trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 162,
    "word": "lights",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪts/",
    "meaning": "đèn",
    "ex1": "They may also mention traffic lights at school.",
    "ex1_vi": "Mọi người thường nhắc đến đèn trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 163,
    "word": "bridges",
    "type": "noun",
    "cat": "n",
    "phonetic": "/brˈɪdʒʌz/",
    "meaning": "cầu",
    "ex1": "We discussed bridges during a friendly conversation at school today.",
    "ex1_vi": "Mọi người thường nhắc đến cầu trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 164,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒ/",
    "meaning": "lớn",
    "ex1": "Today, large buildings as landmarks in daily life.",
    "ex1_vi": "Ngữ cảnh giao tiếp cho thấy ý nghĩa “lớn” một cách tự nhiên và dễ hiểu."
  },
  {
    "id": 165,
    "word": "buildings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɪldɪŋz/",
    "meaning": "tòa nhà",
    "ex1": "Today, large buildings as landmarks in daily life.",
    "ex1_vi": "Mọi người thường nhắc đến tòa nhà trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 166,
    "word": "landmarks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈændmˌɑrks/",
    "meaning": "địa danh; mốc",
    "ex1": "Usually, large buildings as landmarks in daily life.",
    "ex1_vi": "Mọi người thường nhắc đến địa danh; mốc trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 167,
    "word": "speaking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/spˈikɪŋ/",
    "meaning": "việc nói",
    "ex1": "Speaking clearly helps people avoid misunderstandings during phone calls.",
    "ex1_vi": "Hoạt động việc nói xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 168,
    "word": "slowly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/slˈoʊli/",
    "meaning": "chậm rãi",
    "ex1": "Speaking slowly and clearly makes directions easier for everyone to understand correctly.",
    "ex1_vi": "Nói chậm và rõ ràng giúp mọi người hiểu chỉ dẫn chính xác hơn."
  },
  {
    "id": 169,
    "word": "correctly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kɝˈɛktli/",
    "meaning": "chính xác",
    "ex1": "Speaking slowly and clearly makes directions easier for everyone to understand correctly.",
    "ex1_vi": "Nói chậm và rõ ràng giúp mọi người hiểu chỉ dẫn chính xác hơn."
  },
  {
    "id": 170,
    "word": "patient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈeɪʃʌnt/",
    "meaning": "kiên nhẫn",
    "ex1": "Being patient and polite is important when helping others.",
    "ex1_vi": "Kiên nhẫn và lịch sự rất quan trọng khi giúp người khác."
  },
  {
    "id": 171,
    "word": "if",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɪf/",
    "meaning": "nếu",
    "ex1": "If possible, people can repeat the directions slowly and clearly.",
    "ex1_vi": "Mọi người có thể nhờ giúp đỡ nếu họ cảm thấy bối rối."
  },
  {
    "id": 172,
    "word": "repeat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪpˈit/",
    "meaning": "lặp lại",
    "ex1": "People can repeat directions slowly when visitors need more help.",
    "ex1_vi": "Hoạt động lặp lại xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 173,
    "word": "draw",
    "type": "verb",
    "cat": "v",
    "phonetic": "/drˈɔ/",
    "meaning": "vẽ",
    "ex1": "People can draw a simple map to explain directions clearly.",
    "ex1_vi": "Hoạt động vẽ xuất hiện tự nhiên trong giao tiếp hằng ngày và giúp mọi người kết nối."
  },
  {
    "id": 174,
    "word": "map",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈæp/",
    "meaning": "bản đồ",
    "ex1": "A simple map can help visitors understand directions more easily.",
    "ex1_vi": "Mọi người thường nhắc đến bản đồ trong những cuộc trò chuyện thân thiện mỗi ngày."
  },
  {
    "id": 175,
    "word": "reduces",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rʌdˈusʌz/",
    "meaning": "giảm",
    "ex1": "Good communication reduces confusion and makes visitors feel welcome.",
    "ex1_vi": "Giao tiếp tốt làm giảm sự nhầm lẫn và khiến du khách cảm thấy được chào đón."
  },
  {
    "id": 176,
    "word": "welcome",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɛlkʌm/",
    "meaning": "được chào đón; chào mừng",
    "ex1": "Good communication reduces confusion and makes visitors feel welcome.",
    "ex1_vi": "Giao tiếp tốt làm giảm sự nhầm lẫn và khiến du khách cảm thấy được chào đón."
  },
  {
    "id": 177,
    "word": "strangers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/strˈeɪndʒɝz/",
    "meaning": "người lạ",
    "ex1": "Helping strangers also creates a friendly and caring community.",
    "ex1_vi": "Giúp đỡ người lạ cũng tạo nên một cộng đồng thân thiện và biết quan tâm."
  },
  {
    "id": 178,
    "word": "caring",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɛrɪŋ/",
    "meaning": "quan tâm",
    "ex1": "Helping strangers also creates a friendly and caring community.",
    "ex1_vi": "Giúp đỡ người lạ cũng tạo nên một cộng đồng thân thiện và biết quan tâm."
  },
  {
    "id": 179,
    "word": "community",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌmjˈunʌti/",
    "meaning": "cộng đồng",
    "ex1": "Helping strangers also creates a friendly and caring community every day.",
    "ex1_vi": "Mọi người thường nhắc đến cộng đồng trong những cuộc trò chuyện thân thiện mỗi ngày."
  }
];

const newReadingVocabOrder = [
  "sending",
  "messages",
  "fast",
  "and",
  "easy",
  "way",
  "communicate",
  "today",
  "people",
  "use",
  "mobile",
  "phones",
  "emails",
  "social",
  "media",
  "share",
  "information",
  "help",
  "friends",
  "families",
  "classmates",
  "coworkers",
  "stay",
  "connected",
  "wherever",
  "every",
  "day",
  "send",
  "make",
  "plans",
  "ask",
  "questions",
  "give",
  "reminders",
  "or",
  "good",
  "news",
  "short",
  "clear",
  "sentences",
  "understand",
  "using",
  "polite",
  "words",
  "checking",
  "spelling",
  "can",
  "prevent",
  "confusion",
  "improve",
  "communication",
  "between",
  "should",
  "friendly",
  "respectful",
  "read",
  "reply",
  "time",
  "when",
  "possible",
  "avoid",
  "unnecessary",
  "helps",
  "build",
  "stronger",
  "relationships",
  "save",
  "daily",
  "life",
  "more",
  "convenient",
  "asking",
  "normal",
  "part",
  "everyday",
  "everyone",
  "sometimes",
  "needs",
  "support",
  "school",
  "work",
  "shopping",
  "other",
  "activities",
  "politely",
  "makes",
  "others",
  "feel",
  "respected",
  "willing",
  "offer",
  "useful",
  "assistance",
  "needed",
  "teachers",
  "family",
  "members",
  "neighbors",
  "explain",
  "problem",
  "clearly",
  "listen",
  "carefully",
  "advice",
  "saying",
  "please",
  "thank",
  "shows",
  "manners",
  "appreciation",
  "another",
  "person's",
  "helping",
  "each",
  "creates",
  "happier",
  "communities",
  "never",
  "embarrassed",
  "requesting",
  "kindness",
  "respect",
  "gratitude",
  "easier",
  "working",
  "together",
  "solve",
  "problems",
  "learn",
  "new",
  "skills",
  "giving",
  "directions",
  "important",
  "skill",
  "visitors",
  "often",
  "need",
  "finding",
  "schools",
  "hospitals",
  "restaurants",
  "bus",
  "stations",
  "parks",
  "arrive",
  "safely",
  "during",
  "journeys",
  "usually",
  "simple",
  "like",
  "left",
  "right",
  "straight",
  "across",
  "next",
  "may",
  "also",
  "mention",
  "traffic",
  "lights",
  "bridges",
  "large",
  "buildings",
  "landmarks",
  "speaking",
  "slowly",
  "correctly",
  "patient",
  "if",
  "repeat",
  "draw",
  "map",
  "reduces",
  "welcome",
  "strangers",
  "caring",
  "community"
];
