// ===== routine02 VOCABULARY =====

const lessonVocabularyWords = [
  "drinking",
  "enough",
  "water",
  "important",
  "habit",
  "daily",
  "life",
  "drink",
  "glass",
  "waking",
  "and",
  "carry",
  "bottle",
  "also",
  "meals",
  "exercise",
  "helps",
  "body",
  "work",
  "well",
  "keeps",
  "active",
  "weather",
  "hot",
  "more",
  "because",
  "lose",
  "sweat",
  "choose",
  "clean",
  "instead",
  "sweet",
  "drinks",
  "most",
  "time",
  "remember",
  "put",
  "desk",
  "fill",
  "again",
  "becomes",
  "empty",
  "regularly",
  "simple",
  "inexpensive",
  "good",
  "health",
  "every",
  "single",
  "day",
  "family",
  "follows",
  "too",
  "keeping",
  "room",
  "tidy",
  "like",
  "neat",
  "comfortable",
  "space",
  "morning",
  "make",
  "bed",
  "dirty",
  "clothes",
  "basket",
  "return",
  "books",
  "school",
  "things",
  "places",
  "weekends",
  "spend",
  "cleaning",
  "sweep",
  "floor",
  "wipe",
  "open",
  "window",
  "fresh",
  "air",
  "sometimes",
  "give",
  "away",
  "old",
  "items",
  "no",
  "longer",
  "need",
  "find",
  "quickly",
  "study",
  "better",
  "makes",
  "feel",
  "calm",
  "happy",
  "takes",
  "less",
  "do",
  "little",
  "each",
  "so",
  "try",
  "not",
  "lazy",
  "everyone",
  "enjoys",
  "home",
  "practicing",
  "english",
  "part",
  "routine",
  "learn",
  "five",
  "new",
  "words",
  "review",
  "evening",
  "listen",
  "short",
  "videos",
  "songs",
  "or",
  "conversations",
  "online",
  "improve",
  "speaking",
  "read",
  "sentences",
  "aloud",
  "talk",
  "myself",
  "practice",
  "classmates",
  "ask",
  "easy",
  "questions",
  "correct",
  "small",
  "mistakes",
  "encourage",
  "other",
  "continue",
  "learning",
  "language",
  "patient",
  "long",
  "lesson",
  "once",
  "month",
  "useful",
  "confident",
  "communicate",
  "people",
  "everywhere",
  "can",
  "see",
  "steady",
  "progress"
];

const newVocabData = [
  {
    "id": 1,
    "word": "drinking",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɪŋkɪŋ/",
    "meaning": "việc uống",
    "ex1": "Drinking enough water is an important habit in my daily life.",
    "ex1_vi": "Uống đủ nước là một thói quen quan trọng trong cuộc sống hằng ngày của tôi."
  },
  {
    "id": 2,
    "word": "enough",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ɪnˈʌf/",
    "meaning": "đủ",
    "ex1": "Drinking enough water is an important habit in my daily life.",
    "ex1_vi": "Uống đủ nước là một thói quen quan trọng trong cuộc sống hằng ngày của tôi."
  },
  {
    "id": 3,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước",
    "ex1": "In a healthy routine, drinking enough water is an important habit in my daily life.",
    "ex1_vi": "Trong một thói quen lành mạnh, uống đủ nước là một thói quen quan trọng trong cuộc sống hằng ngày của tôi."
  },
  {
    "id": 4,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔrtʌnt/",
    "meaning": "quan trọng",
    "ex1": "During a normal day, drinking enough water is an important habit in my daily life.",
    "ex1_vi": "Trong một ngày bình thường, uống đủ nước là một thói quen quan trọng trong cuộc sống hằng ngày của tôi."
  },
  {
    "id": 5,
    "word": "habit",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈæbʌt/",
    "meaning": "thói quen",
    "ex1": "For good daily habits, drinking enough water is an important habit in my daily life.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, uống đủ nước là một thói quen quan trọng trong cuộc sống hằng ngày của tôi."
  },
  {
    "id": 6,
    "word": "daily",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈeɪli/",
    "meaning": "hằng ngày",
    "ex1": "At home each day, drinking enough water is an important habit in my daily life.",
    "ex1_vi": "Ở nhà mỗi ngày, uống đủ nước là một thói quen quan trọng trong cuộc sống hằng ngày của tôi."
  },
  {
    "id": 7,
    "word": "life",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪf/",
    "meaning": "cuộc sống",
    "ex1": "In everyday life, drinking enough water is an important habit in my daily life.",
    "ex1_vi": "Trong cuộc sống hằng ngày, uống đủ nước là một thói quen quan trọng trong cuộc sống hằng ngày của tôi."
  },
  {
    "id": 8,
    "word": "drink",
    "type": "verb",
    "cat": "v",
    "phonetic": "/drˈɪŋk/",
    "meaning": "uống",
    "ex1": "I drink a glass of water after waking up and carry a bottle with me.",
    "ex1_vi": "Tôi uống một cốc nước sau khi thức dậy và mang theo một chai nước."
  },
  {
    "id": 9,
    "word": "glass",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡlˈæs/",
    "meaning": "cốc; ly",
    "ex1": "I drink a glass of water after waking up and carry a bottle with me.",
    "ex1_vi": "Tôi uống một cốc nước sau khi thức dậy và mang theo một chai nước."
  },
  {
    "id": 10,
    "word": "waking",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/wˈeɪkɪŋ/",
    "meaning": "việc thức dậy",
    "ex1": "In a healthy routine, I drink a glass of water after waking up and carry a bottle with me.",
    "ex1_vi": "Trong một thói quen lành mạnh, tôi uống một cốc nước sau khi thức dậy và mang theo một chai nước."
  },
  {
    "id": 11,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "During a normal day, I drink a glass of water after waking up and carry a bottle with me.",
    "ex1_vi": "Trong một ngày bình thường, tôi uống một cốc nước sau khi thức dậy và mang theo một chai nước."
  },
  {
    "id": 12,
    "word": "carry",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈæri/",
    "meaning": "mang",
    "ex1": "For good daily habits, I drink a glass of water after waking up and carry a bottle with me.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, tôi uống một cốc nước sau khi thức dậy và mang theo một chai nước."
  },
  {
    "id": 13,
    "word": "bottle",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɑtʌl/",
    "meaning": "chai",
    "ex1": "At home each day, I drink a glass of water after waking up and carry a bottle with me.",
    "ex1_vi": "Ở nhà mỗi ngày, tôi uống một cốc nước sau khi thức dậy và mang theo một chai nước."
  },
  {
    "id": 14,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "I also drink water during meals and after exercise.",
    "ex1_vi": "Tôi cũng uống nước trong bữa ăn và sau khi tập thể dục."
  },
  {
    "id": 15,
    "word": "meals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈilz/",
    "meaning": "bữa ăn",
    "ex1": "I also drink water during meals and after exercise.",
    "ex1_vi": "Tôi cũng uống nước trong bữa ăn và sau khi tập thể dục."
  },
  {
    "id": 16,
    "word": "exercise",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛksɝsˌaɪz/",
    "meaning": "tập thể dục",
    "ex1": "In a healthy routine, I also drink water during meals and after exercise.",
    "ex1_vi": "Trong một thói quen lành mạnh, tôi cũng uống nước trong bữa ăn và sau khi tập thể dục."
  },
  {
    "id": 17,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "Water helps my body work well and keeps me active.",
    "ex1_vi": "Nước giúp cơ thể tôi hoạt động tốt và giữ cho tôi năng động."
  },
  {
    "id": 18,
    "word": "body",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɑdi/",
    "meaning": "cơ thể",
    "ex1": "Water helps my body work well and keeps me active.",
    "ex1_vi": "Nước giúp cơ thể tôi hoạt động tốt và giữ cho tôi năng động."
  },
  {
    "id": 19,
    "word": "work",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɝk/",
    "meaning": "hoạt động; làm việc",
    "ex1": "In a healthy routine, water helps my body work well and keeps me active.",
    "ex1_vi": "Trong một thói quen lành mạnh, nước giúp cơ thể tôi hoạt động tốt và giữ cho tôi năng động."
  },
  {
    "id": 20,
    "word": "well",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈɛl/",
    "meaning": "tốt",
    "ex1": "During a normal day, water helps my body work well and keeps me active.",
    "ex1_vi": "Trong một ngày bình thường, nước giúp cơ thể tôi hoạt động tốt và giữ cho tôi năng động."
  },
  {
    "id": 21,
    "word": "keeps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈips/",
    "meaning": "giữ; duy trì",
    "ex1": "For good daily habits, water helps my body work well and keeps me active.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, nước giúp cơ thể tôi hoạt động tốt và giữ cho tôi năng động."
  },
  {
    "id": 22,
    "word": "active",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈæktɪv/",
    "meaning": "năng động",
    "ex1": "At home each day, water helps my body work well and keeps me active.",
    "ex1_vi": "Ở nhà mỗi ngày, nước giúp cơ thể tôi hoạt động tốt và giữ cho tôi năng động."
  },
  {
    "id": 23,
    "word": "weather",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɛðɝ/",
    "meaning": "thời tiết",
    "ex1": "When the weather is hot, I drink more because I lose water through sweat.",
    "ex1_vi": "Khi thời tiết nóng, tôi uống nhiều hơn vì cơ thể mất nước qua mồ hôi."
  },
  {
    "id": 24,
    "word": "hot",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑt/",
    "meaning": "nóng",
    "ex1": "When the weather is hot, I drink more because I lose water through sweat.",
    "ex1_vi": "Khi thời tiết nóng, tôi uống nhiều hơn vì cơ thể mất nước qua mồ hôi."
  },
  {
    "id": 25,
    "word": "more",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/mˈɔr/",
    "meaning": "hơn; nhiều hơn",
    "ex1": "In a healthy routine, when the weather is hot, I drink more because I lose water through sweat.",
    "ex1_vi": "Trong một thói quen lành mạnh, khi thời tiết nóng, tôi uống nhiều hơn vì cơ thể mất nước qua mồ hôi."
  },
  {
    "id": 26,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "During a normal day, when the weather is hot, I drink more because I lose water through sweat.",
    "ex1_vi": "Trong một ngày bình thường, khi thời tiết nóng, tôi uống nhiều hơn vì cơ thể mất nước qua mồ hôi."
  },
  {
    "id": 27,
    "word": "lose",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈuz/",
    "meaning": "mất",
    "ex1": "For good daily habits, when the weather is hot, I drink more because I lose water through sweat.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, khi thời tiết nóng, tôi uống nhiều hơn vì cơ thể mất nước qua mồ hôi."
  },
  {
    "id": 28,
    "word": "sweat",
    "type": "noun",
    "cat": "n",
    "phonetic": "/swˈɛt/",
    "meaning": "mồ hôi",
    "ex1": "At home each day, when the weather is hot, I drink more because I lose water through sweat.",
    "ex1_vi": "Ở nhà mỗi ngày, khi thời tiết nóng, tôi uống nhiều hơn vì cơ thể mất nước qua mồ hôi."
  },
  {
    "id": 29,
    "word": "choose",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tʃˈuz/",
    "meaning": "chọn",
    "ex1": "I choose clean water instead of sweet drinks most of the time.",
    "ex1_vi": "Hầu hết thời gian tôi chọn nước sạch thay vì đồ uống ngọt."
  },
  {
    "id": 30,
    "word": "clean",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈin/",
    "meaning": "sạch",
    "ex1": "I choose clean water instead of sweet drinks most of the time.",
    "ex1_vi": "Hầu hết thời gian tôi chọn nước sạch thay vì đồ uống ngọt."
  },
  {
    "id": 31,
    "word": "instead",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˌɪnstˈɛd/",
    "meaning": "thay vào đó",
    "ex1": "In a healthy routine, I choose clean water instead of sweet drinks most of the time.",
    "ex1_vi": "Trong một thói quen lành mạnh, hầu hết thời gian tôi chọn nước sạch thay vì đồ uống ngọt."
  },
  {
    "id": 32,
    "word": "sweet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/swˈit/",
    "meaning": "ngọt",
    "ex1": "During a normal day, I choose clean water instead of sweet drinks most of the time.",
    "ex1_vi": "Trong một ngày bình thường, hầu hết thời gian tôi chọn nước sạch thay vì đồ uống ngọt."
  },
  {
    "id": 33,
    "word": "drinks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɪŋks/",
    "meaning": "đồ uống",
    "ex1": "For good daily habits, I choose clean water instead of sweet drinks most of the time.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, hầu hết thời gian tôi chọn nước sạch thay vì đồ uống ngọt."
  },
  {
    "id": 34,
    "word": "most",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈoʊst/",
    "meaning": "phần lớn",
    "ex1": "At home each day, I choose clean water instead of sweet drinks most of the time.",
    "ex1_vi": "Ở nhà mỗi ngày, hầu hết thời gian tôi chọn nước sạch thay vì đồ uống ngọt."
  },
  {
    "id": 35,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "In everyday life, I choose clean water instead of sweet drinks most of the time.",
    "ex1_vi": "Trong cuộc sống hằng ngày, hầu hết thời gian tôi chọn nước sạch thay vì đồ uống ngọt."
  },
  {
    "id": 36,
    "word": "remember",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪmˈɛmbɝ/",
    "meaning": "tưởng nhớ",
    "ex1": "To remember this habit, I put my bottle on my desk.",
    "ex1_vi": "Để nhớ thói quen này, tôi đặt chai nước trên bàn."
  },
  {
    "id": 37,
    "word": "put",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pˈʊt/",
    "meaning": "đặt; để",
    "ex1": "To remember this habit, I put my bottle on my desk.",
    "ex1_vi": "Để nhớ thói quen này, tôi đặt chai nước trên bàn."
  },
  {
    "id": 38,
    "word": "desk",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɛsk/",
    "meaning": "bàn học; bàn làm việc",
    "ex1": "In a healthy routine, to remember this habit, I put my bottle on my desk.",
    "ex1_vi": "Trong một thói quen lành mạnh, để nhớ thói quen này, tôi đặt chai nước trên bàn."
  },
  {
    "id": 39,
    "word": "fill",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɪl/",
    "meaning": "lấp đầy; lan tỏa",
    "ex1": "I fill it again when it becomes empty.",
    "ex1_vi": "Tôi lại đổ đầy khi chai hết."
  },
  {
    "id": 40,
    "word": "again",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌɡˈɛn/",
    "meaning": "lại; một lần nữa",
    "ex1": "I fill it again when it becomes empty.",
    "ex1_vi": "Tôi lại đổ đầy khi chai hết."
  },
  {
    "id": 41,
    "word": "becomes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌmz/",
    "meaning": "trở nên",
    "ex1": "In a healthy routine, I fill it again when it becomes empty.",
    "ex1_vi": "Trong một thói quen lành mạnh, tôi lại đổ đầy khi chai hết."
  },
  {
    "id": 42,
    "word": "empty",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɛmpti/",
    "meaning": "trống; hết",
    "ex1": "During a normal day, I fill it again when it becomes empty.",
    "ex1_vi": "Trong một ngày bình thường, tôi lại đổ đầy khi chai hết."
  },
  {
    "id": 43,
    "word": "regularly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/rˈɛɡjʌlɝli/",
    "meaning": "thường xuyên",
    "ex1": "Drinking water regularly is simple, inexpensive, and good for my health every single day.",
    "ex1_vi": "Uống nước thường xuyên là việc đơn giản, ít tốn kém và tốt cho sức khỏe của tôi mỗi ngày."
  },
  {
    "id": 44,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "Drinking water regularly is simple, inexpensive, and good for my health every single day.",
    "ex1_vi": "Uống nước thường xuyên là việc đơn giản, ít tốn kém và tốt cho sức khỏe của tôi mỗi ngày."
  },
  {
    "id": 45,
    "word": "inexpensive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪnɪkspˈɛnsɪv/",
    "meaning": "không đắt; ít tốn kém",
    "ex1": "In a healthy routine, drinking water regularly is simple, inexpensive, and good for my health every single day.",
    "ex1_vi": "Trong một thói quen lành mạnh, uống nước thường xuyên là việc đơn giản, ít tốn kém và tốt cho sức khỏe của tôi mỗi ngày."
  },
  {
    "id": 46,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "During a normal day, drinking water regularly is simple, inexpensive, and good for my health every single day.",
    "ex1_vi": "Trong một ngày bình thường, uống nước thường xuyên là việc đơn giản, ít tốn kém và tốt cho sức khỏe của tôi mỗi ngày."
  },
  {
    "id": 47,
    "word": "health",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛlθ/",
    "meaning": "sức khỏe",
    "ex1": "For good daily habits, drinking water regularly is simple, inexpensive, and good for my health every single day.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, uống nước thường xuyên là việc đơn giản, ít tốn kém và tốt cho sức khỏe của tôi mỗi ngày."
  },
  {
    "id": 48,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɝi/",
    "meaning": "mỗi",
    "ex1": "At home each day, drinking water regularly is simple, inexpensive, and good for my health every single day.",
    "ex1_vi": "Ở nhà mỗi ngày, uống nước thường xuyên là việc đơn giản, ít tốn kém và tốt cho sức khỏe của tôi mỗi ngày."
  },
  {
    "id": 49,
    "word": "single",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪŋɡʌl/",
    "meaning": "duy nhất",
    "ex1": "In everyday life, drinking water regularly is simple, inexpensive, and good for my health every single day.",
    "ex1_vi": "Trong cuộc sống hằng ngày, uống nước thường xuyên là việc đơn giản, ít tốn kém và tốt cho sức khỏe của tôi mỗi ngày."
  },
  {
    "id": 50,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "For a balanced routine, drinking water regularly is simple, inexpensive, and good for my health every single day.",
    "ex1_vi": "Để có một lịch sinh hoạt cân bằng, uống nước thường xuyên là việc đơn giản, ít tốn kém và tốt cho sức khỏe của tôi mỗi ngày."
  },
  {
    "id": 51,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "My family follows this habit too.",
    "ex1_vi": "Gia đình tôi cũng duy trì thói quen này."
  },
  {
    "id": 52,
    "word": "follows",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɑloʊz/",
    "meaning": "làm theo; duy trì",
    "ex1": "My family follows this habit too.",
    "ex1_vi": "Gia đình tôi cũng duy trì thói quen này."
  },
  {
    "id": 53,
    "word": "too",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tˈu/",
    "meaning": "cũng; quá",
    "ex1": "In a healthy routine, my family follows this habit too.",
    "ex1_vi": "Trong một thói quen lành mạnh, gia đình tôi cũng duy trì thói quen này."
  },
  {
    "id": 54,
    "word": "keeping",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/kˈipɪŋ/",
    "meaning": "việc giữ",
    "ex1": "Keeping my room tidy makes daily life more comfortable.",
    "ex1_vi": "Giữ phòng gọn gàng làm cuộc sống hằng ngày thoải mái hơn."
  },
  {
    "id": 55,
    "word": "room",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈum/",
    "meaning": "phòng",
    "ex1": "I clean my room regularly because I like a neat and comfortable space.",
    "ex1_vi": "Tôi dọn phòng thường xuyên vì tôi thích một không gian ngăn nắp và thoải mái."
  },
  {
    "id": 56,
    "word": "tidy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈaɪdi/",
    "meaning": "gọn gàng",
    "ex1": "A tidy room helps me find things quickly and study better.",
    "ex1_vi": "Một căn phòng gọn gàng giúp tôi tìm đồ nhanh và học tốt hơn."
  },
  {
    "id": 57,
    "word": "like",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈaɪk/",
    "meaning": "thích",
    "ex1": "I clean my room regularly because I like a neat and comfortable space.",
    "ex1_vi": "Tôi dọn phòng thường xuyên vì tôi thích một không gian ngăn nắp và thoải mái."
  },
  {
    "id": 58,
    "word": "neat",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈit/",
    "meaning": "ngăn nắp",
    "ex1": "In a healthy routine, I clean my room regularly because I like a neat and comfortable space.",
    "ex1_vi": "Trong một thói quen lành mạnh, tôi dọn phòng thường xuyên vì tôi thích một không gian ngăn nắp và thoải mái."
  },
  {
    "id": 59,
    "word": "comfortable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌmfɝtʌbʌl/",
    "meaning": "thoải mái",
    "ex1": "During a normal day, I clean my room regularly because I like a neat and comfortable space.",
    "ex1_vi": "Trong một ngày bình thường, tôi dọn phòng thường xuyên vì tôi thích một không gian ngăn nắp và thoải mái."
  },
  {
    "id": 60,
    "word": "space",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈeɪs/",
    "meaning": "không gian",
    "ex1": "For good daily habits, I clean my room regularly because I like a neat and comfortable space.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, tôi dọn phòng thường xuyên vì tôi thích một không gian ngăn nắp và thoải mái."
  },
  {
    "id": 61,
    "word": "morning",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɔrnɪŋ/",
    "meaning": "buổi sáng",
    "ex1": "Every morning, I make my bed and put dirty clothes in a basket.",
    "ex1_vi": "Mỗi sáng, tôi dọn giường và bỏ quần áo bẩn vào giỏ."
  },
  {
    "id": 62,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm; tạo",
    "ex1": "Every morning, I make my bed and put dirty clothes in a basket.",
    "ex1_vi": "Mỗi sáng, tôi dọn giường và bỏ quần áo bẩn vào giỏ."
  },
  {
    "id": 63,
    "word": "bed",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɛd/",
    "meaning": "giường",
    "ex1": "In a healthy routine, every morning, I make my bed and put dirty clothes in a basket.",
    "ex1_vi": "Trong một thói quen lành mạnh, mỗi sáng, tôi dọn giường và bỏ quần áo bẩn vào giỏ."
  },
  {
    "id": 64,
    "word": "dirty",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɝti/",
    "meaning": "bẩn",
    "ex1": "During a normal day, every morning, I make my bed and put dirty clothes in a basket.",
    "ex1_vi": "Trong một ngày bình thường, mỗi sáng, tôi dọn giường và bỏ quần áo bẩn vào giỏ."
  },
  {
    "id": 65,
    "word": "clothes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈoʊðz/",
    "meaning": "quần áo",
    "ex1": "For good daily habits, every morning, I make my bed and put dirty clothes in a basket.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, mỗi sáng, tôi dọn giường và bỏ quần áo bẩn vào giỏ."
  },
  {
    "id": 66,
    "word": "basket",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈæskʌt/",
    "meaning": "giỏ",
    "ex1": "At home each day, every morning, I make my bed and put dirty clothes in a basket.",
    "ex1_vi": "Ở nhà mỗi ngày, mỗi sáng, tôi dọn giường và bỏ quần áo bẩn vào giỏ."
  },
  {
    "id": 67,
    "word": "return",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪtˈɝn/",
    "meaning": "trở về",
    "ex1": "I also return books and school things to their places.",
    "ex1_vi": "Tôi cũng trả sách và đồ dùng học tập về đúng chỗ."
  },
  {
    "id": 68,
    "word": "books",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʊks/",
    "meaning": "sách",
    "ex1": "I also return books and school things to their places.",
    "ex1_vi": "Tôi cũng trả sách và đồ dùng học tập về đúng chỗ."
  },
  {
    "id": 69,
    "word": "school",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈul/",
    "meaning": "trường học",
    "ex1": "In a healthy routine, I also return books and school things to their places.",
    "ex1_vi": "Trong một thói quen lành mạnh, tôi cũng trả sách và đồ dùng học tập về đúng chỗ."
  },
  {
    "id": 70,
    "word": "things",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈɪŋz/",
    "meaning": "đồ vật; việc",
    "ex1": "During a normal day, I also return books and school things to their places.",
    "ex1_vi": "Trong một ngày bình thường, tôi cũng trả sách và đồ dùng học tập về đúng chỗ."
  },
  {
    "id": 71,
    "word": "places",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪsʌz/",
    "meaning": "nơi; đặt",
    "ex1": "For good daily habits, I also return books and school things to their places.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, tôi cũng trả sách và đồ dùng học tập về đúng chỗ."
  },
  {
    "id": 72,
    "word": "weekends",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈikˌɛndz/",
    "meaning": "các cuối tuần",
    "ex1": "At weekends, I spend more time cleaning.",
    "ex1_vi": "Vào cuối tuần, tôi dành nhiều thời gian hơn để dọn dẹp."
  },
  {
    "id": 73,
    "word": "spend",
    "type": "verb",
    "cat": "v",
    "phonetic": "/spˈɛnd/",
    "meaning": "dành (thời gian)",
    "ex1": "At weekends, I spend more time cleaning.",
    "ex1_vi": "Vào cuối tuần, tôi dành nhiều thời gian hơn để dọn dẹp."
  },
  {
    "id": 74,
    "word": "cleaning",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/klˈinɪŋ/",
    "meaning": "việc dọn dẹp",
    "ex1": "In a healthy routine, at weekends, I spend more time cleaning.",
    "ex1_vi": "Trong một thói quen lành mạnh, vào cuối tuần, tôi dành nhiều thời gian hơn để dọn dẹp."
  },
  {
    "id": 75,
    "word": "sweep",
    "type": "verb",
    "cat": "v",
    "phonetic": "/swˈip/",
    "meaning": "quét",
    "ex1": "I sweep the floor, wipe the desk, and open the window for fresh air.",
    "ex1_vi": "Tôi quét sàn, lau bàn và mở cửa sổ để đón không khí trong lành."
  },
  {
    "id": 76,
    "word": "floor",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈɔr/",
    "meaning": "sàn nhà",
    "ex1": "I sweep the floor, wipe the desk, and open the window for fresh air.",
    "ex1_vi": "Tôi quét sàn, lau bàn và mở cửa sổ để đón không khí trong lành."
  },
  {
    "id": 77,
    "word": "wipe",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈaɪp/",
    "meaning": "lau",
    "ex1": "In a healthy routine, I sweep the floor, wipe the desk, and open the window for fresh air.",
    "ex1_vi": "Trong một thói quen lành mạnh, tôi quét sàn, lau bàn và mở cửa sổ để đón không khí trong lành."
  },
  {
    "id": 78,
    "word": "open",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈoʊpʌn/",
    "meaning": "mở",
    "ex1": "During a normal day, I sweep the floor, wipe the desk, and open the window for fresh air.",
    "ex1_vi": "Trong một ngày bình thường, tôi quét sàn, lau bàn và mở cửa sổ để đón không khí trong lành."
  },
  {
    "id": 79,
    "word": "window",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɪndoʊ/",
    "meaning": "cửa sổ",
    "ex1": "For good daily habits, I sweep the floor, wipe the desk, and open the window for fresh air.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, tôi quét sàn, lau bàn và mở cửa sổ để đón không khí trong lành."
  },
  {
    "id": 80,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi; trong lành",
    "ex1": "At home each day, I sweep the floor, wipe the desk, and open the window for fresh air.",
    "ex1_vi": "Ở nhà mỗi ngày, tôi quét sàn, lau bàn và mở cửa sổ để đón không khí trong lành."
  },
  {
    "id": 81,
    "word": "air",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛr/",
    "meaning": "không khí",
    "ex1": "In everyday life, I sweep the floor, wipe the desk, and open the window for fresh air.",
    "ex1_vi": "Trong cuộc sống hằng ngày, tôi quét sàn, lau bàn và mở cửa sổ để đón không khí trong lành."
  },
  {
    "id": 82,
    "word": "sometimes",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sʌmtˈaɪmz/",
    "meaning": "đôi khi",
    "ex1": "Sometimes I give away old items that I no longer need.",
    "ex1_vi": "Đôi khi tôi cho đi những món đồ cũ mà mình không còn cần."
  },
  {
    "id": 83,
    "word": "give",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪv/",
    "meaning": "mang lại",
    "ex1": "Sometimes I give away old items that I no longer need.",
    "ex1_vi": "Đôi khi tôi cho đi những món đồ cũ mà mình không còn cần."
  },
  {
    "id": 84,
    "word": "away",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌwˈeɪ/",
    "meaning": "ra xa",
    "ex1": "In a healthy routine, sometimes I give away old items that I no longer need.",
    "ex1_vi": "Trong một thói quen lành mạnh, đôi khi tôi cho đi những món đồ cũ mà mình không còn cần."
  },
  {
    "id": 85,
    "word": "old",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈoʊld/",
    "meaning": "xưa; cũ",
    "ex1": "During a normal day, sometimes I give away old items that I no longer need.",
    "ex1_vi": "Trong một ngày bình thường, đôi khi tôi cho đi những món đồ cũ mà mình không còn cần."
  },
  {
    "id": 86,
    "word": "items",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪtʌmz/",
    "meaning": "mặt hàng",
    "ex1": "For good daily habits, sometimes I give away old items that I no longer need.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, đôi khi tôi cho đi những món đồ cũ mà mình không còn cần."
  },
  {
    "id": 87,
    "word": "no",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/nˈoʊ/",
    "meaning": "không; không còn",
    "ex1": "At home each day, sometimes I give away old items that I no longer need.",
    "ex1_vi": "Ở nhà mỗi ngày, đôi khi tôi cho đi những món đồ cũ mà mình không còn cần."
  },
  {
    "id": 88,
    "word": "longer",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/lˈɔŋɡɝ/",
    "meaning": "lâu hơn; nữa",
    "ex1": "In everyday life, sometimes I give away old items that I no longer need.",
    "ex1_vi": "Trong cuộc sống hằng ngày, đôi khi tôi cho đi những món đồ cũ mà mình không còn cần."
  },
  {
    "id": 89,
    "word": "need",
    "type": "verb",
    "cat": "v",
    "phonetic": "/nˈid/",
    "meaning": "cần",
    "ex1": "For a balanced routine, sometimes I give away old items that I no longer need.",
    "ex1_vi": "Để có một lịch sinh hoạt cân bằng, đôi khi tôi cho đi những món đồ cũ mà mình không còn cần."
  },
  {
    "id": 90,
    "word": "find",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪnd/",
    "meaning": "phát hiện; tìm thấy",
    "ex1": "A tidy room helps me find things quickly and study better.",
    "ex1_vi": "Một căn phòng gọn gàng giúp tôi tìm đồ nhanh và học tốt hơn."
  },
  {
    "id": 91,
    "word": "quickly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kwˈɪkli/",
    "meaning": "nhanh chóng",
    "ex1": "In a healthy routine, a tidy room helps me find things quickly and study better.",
    "ex1_vi": "Trong một thói quen lành mạnh, một căn phòng gọn gàng giúp tôi tìm đồ nhanh và học tốt hơn."
  },
  {
    "id": 92,
    "word": "study",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈʌdi/",
    "meaning": "học",
    "ex1": "During a normal day, a tidy room helps me find things quickly and study better.",
    "ex1_vi": "Trong một ngày bình thường, một căn phòng gọn gàng giúp tôi tìm đồ nhanh và học tốt hơn."
  },
  {
    "id": 93,
    "word": "better",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/bˈɛtɝ/",
    "meaning": "tốt hơn",
    "ex1": "For good daily habits, a tidy room helps me find things quickly and study better.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, một căn phòng gọn gàng giúp tôi tìm đồ nhanh và học tốt hơn."
  },
  {
    "id": 94,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm; khiến",
    "ex1": "It also makes me feel calm and happy.",
    "ex1_vi": "Nó cũng khiến tôi cảm thấy bình tĩnh và vui vẻ."
  },
  {
    "id": 95,
    "word": "feel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈil/",
    "meaning": "cảm thấy",
    "ex1": "It also makes me feel calm and happy.",
    "ex1_vi": "Nó cũng khiến tôi cảm thấy bình tĩnh và vui vẻ."
  },
  {
    "id": 96,
    "word": "calm",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɑm/",
    "meaning": "bình tĩnh",
    "ex1": "In a healthy routine, it also makes me feel calm and happy.",
    "ex1_vi": "Trong một thói quen lành mạnh, nó cũng khiến tôi cảm thấy bình tĩnh và vui vẻ."
  },
  {
    "id": 97,
    "word": "happy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈæpi/",
    "meaning": "vui vẻ",
    "ex1": "During a normal day, it also makes me feel calm and happy.",
    "ex1_vi": "Trong một ngày bình thường, nó cũng khiến tôi cảm thấy bình tĩnh và vui vẻ."
  },
  {
    "id": 98,
    "word": "takes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪks/",
    "meaning": "diễn ra",
    "ex1": "Cleaning takes less time when I do a little each day, so I try not to be lazy.",
    "ex1_vi": "Việc dọn dẹp tốn ít thời gian hơn khi tôi làm một chút mỗi ngày, vì vậy tôi cố gắng không lười biếng."
  },
  {
    "id": 99,
    "word": "less",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/lˈɛs/",
    "meaning": "ít hơn",
    "ex1": "Cleaning takes less time when I do a little each day, so I try not to be lazy.",
    "ex1_vi": "Việc dọn dẹp tốn ít thời gian hơn khi tôi làm một chút mỗi ngày, vì vậy tôi cố gắng không lười biếng."
  },
  {
    "id": 100,
    "word": "do",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈu/",
    "meaning": "làm",
    "ex1": "In a healthy routine, cleaning takes less time when I do a little each day, so I try not to be lazy.",
    "ex1_vi": "Trong một thói quen lành mạnh, việc dọn dẹp tốn ít thời gian hơn khi tôi làm một chút mỗi ngày, vì vậy tôi cố gắng không lười biếng."
  },
  {
    "id": 101,
    "word": "little",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/lˈɪtʌl/",
    "meaning": "một chút; ít",
    "ex1": "During a normal day, cleaning takes less time when I do a little each day, so I try not to be lazy.",
    "ex1_vi": "Trong một ngày bình thường, việc dọn dẹp tốn ít thời gian hơn khi tôi làm một chút mỗi ngày, vì vậy tôi cố gắng không lười biếng."
  },
  {
    "id": 102,
    "word": "each",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈitʃ/",
    "meaning": "mỗi",
    "ex1": "For good daily habits, cleaning takes less time when I do a little each day, so I try not to be lazy.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, việc dọn dẹp tốn ít thời gian hơn khi tôi làm một chút mỗi ngày, vì vậy tôi cố gắng không lười biếng."
  },
  {
    "id": 103,
    "word": "so",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/sˈoʊ/",
    "meaning": "vì vậy",
    "ex1": "At home each day, cleaning takes less time when I do a little each day, so I try not to be lazy.",
    "ex1_vi": "Ở nhà mỗi ngày, việc dọn dẹp tốn ít thời gian hơn khi tôi làm một chút mỗi ngày, vì vậy tôi cố gắng không lười biếng."
  },
  {
    "id": 104,
    "word": "try",
    "type": "verb",
    "cat": "v",
    "phonetic": "/trˈaɪ/",
    "meaning": "thử",
    "ex1": "In everyday life, cleaning takes less time when I do a little each day, so I try not to be lazy.",
    "ex1_vi": "Trong cuộc sống hằng ngày, việc dọn dẹp tốn ít thời gian hơn khi tôi làm một chút mỗi ngày, vì vậy tôi cố gắng không lười biếng."
  },
  {
    "id": 105,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "For a balanced routine, cleaning takes less time when I do a little each day, so I try not to be lazy.",
    "ex1_vi": "Để có một lịch sinh hoạt cân bằng, việc dọn dẹp tốn ít thời gian hơn khi tôi làm một chút mỗi ngày, vì vậy tôi cố gắng không lười biếng."
  },
  {
    "id": 106,
    "word": "lazy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈeɪzi/",
    "meaning": "lười biếng",
    "ex1": "During regular practice, cleaning takes less time when I do a little each day, so I try not to be lazy.",
    "ex1_vi": "Trong quá trình luyện tập thường xuyên, việc dọn dẹp tốn ít thời gian hơn khi tôi làm một chút mỗi ngày, vì vậy tôi cố gắng không lười biếng."
  },
  {
    "id": 107,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvriwˌʌn/",
    "meaning": "mọi người",
    "ex1": "Everyone enjoys a clean home.",
    "ex1_vi": "Mọi người đều thích một ngôi nhà sạch sẽ."
  },
  {
    "id": 108,
    "word": "enjoys",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪz/",
    "meaning": "thích; tận hưởng",
    "ex1": "Everyone enjoys a clean home.",
    "ex1_vi": "Mọi người đều thích một ngôi nhà sạch sẽ."
  },
  {
    "id": 109,
    "word": "home",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊm/",
    "meaning": "nơi sinh sống; nhà",
    "ex1": "In a healthy routine, everyone enjoys a clean home.",
    "ex1_vi": "Trong một thói quen lành mạnh, mọi người đều thích một ngôi nhà sạch sẽ."
  },
  {
    "id": 110,
    "word": "practicing",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/prˈæktʌsɪŋ/",
    "meaning": "việc luyện tập",
    "ex1": "Practicing English is part of my daily routine.",
    "ex1_vi": "Luyện tập tiếng Anh là một phần trong thói quen hằng ngày của tôi."
  },
  {
    "id": 111,
    "word": "english",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/ˈɪŋɡlɪʃ/",
    "meaning": "tiếng Anh",
    "ex1": "Practicing English is part of my daily routine.",
    "ex1_vi": "Luyện tập tiếng Anh là một phần trong thói quen hằng ngày của tôi."
  },
  {
    "id": 112,
    "word": "part",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrt/",
    "meaning": "phần",
    "ex1": "In a healthy routine, practicing English is part of my daily routine.",
    "ex1_vi": "Trong một thói quen lành mạnh, luyện tập tiếng Anh là một phần trong thói quen hằng ngày của tôi."
  },
  {
    "id": 113,
    "word": "routine",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rutˈin/",
    "meaning": "thói quen",
    "ex1": "During a normal day, practicing English is part of my daily routine.",
    "ex1_vi": "Trong một ngày bình thường, luyện tập tiếng Anh là một phần trong thói quen hằng ngày của tôi."
  },
  {
    "id": 114,
    "word": "learn",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɝn/",
    "meaning": "học",
    "ex1": "I learn five new words each morning and review them in the evening.",
    "ex1_vi": "Mỗi sáng tôi học năm từ mới và ôn lại vào buổi tối."
  },
  {
    "id": 115,
    "word": "five",
    "type": "number",
    "cat": "adj",
    "phonetic": "/fˈaɪv/",
    "meaning": "năm",
    "ex1": "I learn five new words each morning and review them in the evening.",
    "ex1_vi": "Mỗi sáng tôi học năm từ mới và ôn lại vào buổi tối."
  },
  {
    "id": 116,
    "word": "new",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈu/",
    "meaning": "mới",
    "ex1": "In a healthy routine, I learn five new words each morning and review them in the evening.",
    "ex1_vi": "Trong một thói quen lành mạnh, mỗi sáng tôi học năm từ mới và ôn lại vào buổi tối."
  },
  {
    "id": 117,
    "word": "words",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝdz/",
    "meaning": "lời nói; từ ngữ",
    "ex1": "During a normal day, I learn five new words each morning and review them in the evening.",
    "ex1_vi": "Trong một ngày bình thường, mỗi sáng tôi học năm từ mới và ôn lại vào buổi tối."
  },
  {
    "id": 118,
    "word": "review",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˌivjˈu/",
    "meaning": "ôn lại",
    "ex1": "For good daily habits, I learn five new words each morning and review them in the evening.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, mỗi sáng tôi học năm từ mới và ôn lại vào buổi tối."
  },
  {
    "id": 119,
    "word": "evening",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈivnɪŋ/",
    "meaning": "buổi tối",
    "ex1": "At home each day, I learn five new words each morning and review them in the evening.",
    "ex1_vi": "Ở nhà mỗi ngày, mỗi sáng tôi học năm từ mới và ôn lại vào buổi tối."
  },
  {
    "id": 120,
    "word": "listen",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɪsʌn/",
    "meaning": "lắng nghe",
    "ex1": "I also listen to short English videos, songs, or simple conversations online.",
    "ex1_vi": "Tôi cũng nghe các video tiếng Anh ngắn, bài hát hoặc những đoạn hội thoại đơn giản trên mạng."
  },
  {
    "id": 121,
    "word": "short",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɔrt/",
    "meaning": "ngắn",
    "ex1": "I also listen to short English videos, songs, or simple conversations online.",
    "ex1_vi": "Tôi cũng nghe các video tiếng Anh ngắn, bài hát hoặc những đoạn hội thoại đơn giản trên mạng."
  },
  {
    "id": 122,
    "word": "videos",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪdioʊz/",
    "meaning": "video",
    "ex1": "In a healthy routine, I also listen to short English videos, songs, or simple conversations online.",
    "ex1_vi": "Trong một thói quen lành mạnh, tôi cũng nghe các video tiếng Anh ngắn, bài hát hoặc những đoạn hội thoại đơn giản trên mạng."
  },
  {
    "id": 123,
    "word": "songs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔŋz/",
    "meaning": "bài hát; tiếng hót",
    "ex1": "During a normal day, I also listen to short English videos, songs, or simple conversations online.",
    "ex1_vi": "Trong một ngày bình thường, tôi cũng nghe các video tiếng Anh ngắn, bài hát hoặc những đoạn hội thoại đơn giản trên mạng."
  },
  {
    "id": 124,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "For good daily habits, I also listen to short English videos, songs, or simple conversations online.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, tôi cũng nghe các video tiếng Anh ngắn, bài hát hoặc những đoạn hội thoại đơn giản trên mạng."
  },
  {
    "id": 125,
    "word": "conversations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˌɑnvɝsˈeɪʃʌnz/",
    "meaning": "các cuộc trò chuyện",
    "ex1": "At home each day, I also listen to short English videos, songs, or simple conversations online.",
    "ex1_vi": "Ở nhà mỗi ngày, tôi cũng nghe các video tiếng Anh ngắn, bài hát hoặc những đoạn hội thoại đơn giản trên mạng."
  },
  {
    "id": 126,
    "word": "online",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔnlˌaɪn/",
    "meaning": "trực tuyến",
    "ex1": "In everyday life, I also listen to short English videos, songs, or simple conversations online.",
    "ex1_vi": "Trong cuộc sống hằng ngày, tôi cũng nghe các video tiếng Anh ngắn, bài hát hoặc những đoạn hội thoại đơn giản trên mạng."
  },
  {
    "id": 127,
    "word": "improve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪmprˈuv/",
    "meaning": "cải thiện",
    "ex1": "To improve my speaking, I read sentences aloud and talk to myself about my day.",
    "ex1_vi": "Để cải thiện kỹ năng nói, tôi đọc to các câu và tự nói về ngày của mình."
  },
  {
    "id": 128,
    "word": "speaking",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/spˈikɪŋ/",
    "meaning": "việc nói",
    "ex1": "To improve my speaking, I read sentences aloud and talk to myself about my day.",
    "ex1_vi": "Để cải thiện kỹ năng nói, tôi đọc to các câu và tự nói về ngày của mình."
  },
  {
    "id": 129,
    "word": "read",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈɛd/",
    "meaning": "đọc",
    "ex1": "In a healthy routine, to improve my speaking, I read sentences aloud and talk to myself about my day.",
    "ex1_vi": "Trong một thói quen lành mạnh, để cải thiện kỹ năng nói, tôi đọc to các câu và tự nói về ngày của mình."
  },
  {
    "id": 130,
    "word": "sentences",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛntʌnsʌz/",
    "meaning": "câu",
    "ex1": "During a normal day, to improve my speaking, I read sentences aloud and talk to myself about my day.",
    "ex1_vi": "Trong một ngày bình thường, để cải thiện kỹ năng nói, tôi đọc to các câu và tự nói về ngày của mình."
  },
  {
    "id": 131,
    "word": "aloud",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌlˈaʊd/",
    "meaning": "thành tiếng",
    "ex1": "For good daily habits, to improve my speaking, I read sentences aloud and talk to myself about my day.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, để cải thiện kỹ năng nói, tôi đọc to các câu và tự nói về ngày của mình."
  },
  {
    "id": 132,
    "word": "talk",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈɔk/",
    "meaning": "nói chuyện",
    "ex1": "At home each day, to improve my speaking, I read sentences aloud and talk to myself about my day.",
    "ex1_vi": "Ở nhà mỗi ngày, để cải thiện kỹ năng nói, tôi đọc to các câu và tự nói về ngày của mình."
  },
  {
    "id": 133,
    "word": "myself",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/mˌaɪsˈɛlf/",
    "meaning": "bản thân tôi",
    "ex1": "In everyday life, to improve my speaking, I read sentences aloud and talk to myself about my day.",
    "ex1_vi": "Trong cuộc sống hằng ngày, để cải thiện kỹ năng nói, tôi đọc to các câu và tự nói về ngày của mình."
  },
  {
    "id": 134,
    "word": "practice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈæktʌs/",
    "meaning": "sự luyện tập",
    "ex1": "I sometimes practice with classmates.",
    "ex1_vi": "Đôi khi tôi luyện tập với bạn cùng lớp."
  },
  {
    "id": 135,
    "word": "classmates",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈæsmˌeɪts/",
    "meaning": "bạn cùng lớp",
    "ex1": "I sometimes practice with classmates.",
    "ex1_vi": "Đôi khi tôi luyện tập với bạn cùng lớp."
  },
  {
    "id": 136,
    "word": "ask",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈæsk/",
    "meaning": "hỏi",
    "ex1": "We ask easy questions, correct small mistakes, and encourage each other to continue.",
    "ex1_vi": "Chúng tôi hỏi những câu đơn giản, sửa các lỗi nhỏ và khuyến khích nhau tiếp tục."
  },
  {
    "id": 137,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "We ask easy questions, correct small mistakes, and encourage each other to continue.",
    "ex1_vi": "Chúng tôi hỏi những câu đơn giản, sửa các lỗi nhỏ và khuyến khích nhau tiếp tục."
  },
  {
    "id": 138,
    "word": "questions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kwˈɛstʃʌnz/",
    "meaning": "câu hỏi",
    "ex1": "In a healthy routine, we ask easy questions, correct small mistakes, and encourage each other to continue.",
    "ex1_vi": "Trong một thói quen lành mạnh, chúng tôi hỏi những câu đơn giản, sửa các lỗi nhỏ và khuyến khích nhau tiếp tục."
  },
  {
    "id": 139,
    "word": "correct",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kɝˈɛkt/",
    "meaning": "sửa; chỉnh",
    "ex1": "During a normal day, we ask easy questions, correct small mistakes, and encourage each other to continue.",
    "ex1_vi": "Trong một ngày bình thường, chúng tôi hỏi những câu đơn giản, sửa các lỗi nhỏ và khuyến khích nhau tiếp tục."
  },
  {
    "id": 140,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "For good daily habits, we ask easy questions, correct small mistakes, and encourage each other to continue.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, chúng tôi hỏi những câu đơn giản, sửa các lỗi nhỏ và khuyến khích nhau tiếp tục."
  },
  {
    "id": 141,
    "word": "mistakes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mɪstˈeɪks/",
    "meaning": "sai lầm",
    "ex1": "At home each day, we ask easy questions, correct small mistakes, and encourage each other to continue.",
    "ex1_vi": "Ở nhà mỗi ngày, chúng tôi hỏi những câu đơn giản, sửa các lỗi nhỏ và khuyến khích nhau tiếp tục."
  },
  {
    "id": 142,
    "word": "encourage",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɛnkˈɝɪdʒ/",
    "meaning": "khuyến khích",
    "ex1": "In everyday life, we ask easy questions, correct small mistakes, and encourage each other to continue.",
    "ex1_vi": "Trong cuộc sống hằng ngày, chúng tôi hỏi những câu đơn giản, sửa các lỗi nhỏ và khuyến khích nhau tiếp tục."
  },
  {
    "id": 143,
    "word": "other",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈʌðɝ/",
    "meaning": "người khác; nhau",
    "ex1": "For a balanced routine, we ask easy questions, correct small mistakes, and encourage each other to continue.",
    "ex1_vi": "Để có một lịch sinh hoạt cân bằng, chúng tôi hỏi những câu đơn giản, sửa các lỗi nhỏ và khuyến khích nhau tiếp tục."
  },
  {
    "id": 144,
    "word": "continue",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈɪnju/",
    "meaning": "tiếp tục",
    "ex1": "During regular practice, we ask easy questions, correct small mistakes, and encourage each other to continue.",
    "ex1_vi": "Trong quá trình luyện tập thường xuyên, chúng tôi hỏi những câu đơn giản, sửa các lỗi nhỏ và khuyến khích nhau tiếp tục."
  },
  {
    "id": 145,
    "word": "learning",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/lˈɝnɪŋ/",
    "meaning": "việc học",
    "ex1": "Learning a language takes time, so I try to be patient.",
    "ex1_vi": "Học một ngôn ngữ cần thời gian, vì vậy tôi cố gắng kiên nhẫn."
  },
  {
    "id": 146,
    "word": "language",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈæŋɡwʌdʒ/",
    "meaning": "ngôn ngữ",
    "ex1": "Learning a language takes time, so I try to be patient.",
    "ex1_vi": "Học một ngôn ngữ cần thời gian, vì vậy tôi cố gắng kiên nhẫn."
  },
  {
    "id": 147,
    "word": "patient",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈeɪʃʌnt/",
    "meaning": "kiên nhẫn",
    "ex1": "In a healthy routine, learning a language takes time, so I try to be patient.",
    "ex1_vi": "Trong một thói quen lành mạnh, học một ngôn ngữ cần thời gian, vì vậy tôi cố gắng kiên nhẫn."
  },
  {
    "id": 148,
    "word": "long",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɔŋ/",
    "meaning": "dài",
    "ex1": "A short practice every day is better than a long lesson once a month.",
    "ex1_vi": "Luyện tập ngắn mỗi ngày tốt hơn một bài học dài mỗi tháng một lần."
  },
  {
    "id": 149,
    "word": "lesson",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɛsʌn/",
    "meaning": "bài học",
    "ex1": "A short practice every day is better than a long lesson once a month.",
    "ex1_vi": "Luyện tập ngắn mỗi ngày tốt hơn một bài học dài mỗi tháng một lần."
  },
  {
    "id": 150,
    "word": "once",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈʌns/",
    "meaning": "một lần",
    "ex1": "In a healthy routine, a short practice every day is better than a long lesson once a month.",
    "ex1_vi": "Trong một thói quen lành mạnh, luyện tập ngắn mỗi ngày tốt hơn một bài học dài mỗi tháng một lần."
  },
  {
    "id": 151,
    "word": "month",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌnθ/",
    "meaning": "tháng",
    "ex1": "During a normal day, a short practice every day is better than a long lesson once a month.",
    "ex1_vi": "Trong một ngày bình thường, luyện tập ngắn mỗi ngày tốt hơn một bài học dài mỗi tháng một lần."
  },
  {
    "id": 152,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈusfʌl/",
    "meaning": "hữu ích",
    "ex1": "This useful habit makes me more confident and helps me communicate with people everywhere.",
    "ex1_vi": "Thói quen hữu ích này khiến tôi tự tin hơn và giúp tôi giao tiếp với mọi người ở khắp nơi."
  },
  {
    "id": 153,
    "word": "confident",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɑnfʌdʌnt/",
    "meaning": "tự tin",
    "ex1": "This useful habit makes me more confident and helps me communicate with people everywhere.",
    "ex1_vi": "Thói quen hữu ích này khiến tôi tự tin hơn và giúp tôi giao tiếp với mọi người ở khắp nơi."
  },
  {
    "id": 154,
    "word": "communicate",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌmjˈunʌkˌeɪt/",
    "meaning": "giao tiếp",
    "ex1": "In a healthy routine, this useful habit makes me more confident and helps me communicate with people everywhere.",
    "ex1_vi": "Trong một thói quen lành mạnh, thói quen hữu ích này khiến tôi tự tin hơn và giúp tôi giao tiếp với mọi người ở khắp nơi."
  },
  {
    "id": 155,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "During a normal day, this useful habit makes me more confident and helps me communicate with people everywhere.",
    "ex1_vi": "Trong một ngày bình thường, thói quen hữu ích này khiến tôi tự tin hơn và giúp tôi giao tiếp với mọi người ở khắp nơi."
  },
  {
    "id": 156,
    "word": "everywhere",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɛvriwˌɛr/",
    "meaning": "khắp mọi nơi",
    "ex1": "For good daily habits, this useful habit makes me more confident and helps me communicate with people everywhere.",
    "ex1_vi": "Đối với những thói quen tốt hằng ngày, thói quen hữu ích này khiến tôi tự tin hơn và giúp tôi giao tiếp với mọi người ở khắp nơi."
  },
  {
    "id": 157,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "I can see steady progress.",
    "ex1_vi": "Tôi có thể thấy sự tiến bộ đều đặn."
  },
  {
    "id": 158,
    "word": "see",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈi/",
    "meaning": "nhìn thấy",
    "ex1": "I can see steady progress.",
    "ex1_vi": "Tôi có thể thấy sự tiến bộ đều đặn."
  },
  {
    "id": 159,
    "word": "steady",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/stˈɛdi/",
    "meaning": "ổn định",
    "ex1": "In a healthy routine, I can see steady progress.",
    "ex1_vi": "Trong một thói quen lành mạnh, tôi có thể thấy sự tiến bộ đều đặn."
  },
  {
    "id": 160,
    "word": "progress",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑɡrˌɛs/",
    "meaning": "sự tiến bộ",
    "ex1": "During a normal day, I can see steady progress.",
    "ex1_vi": "Trong một ngày bình thường, tôi có thể thấy sự tiến bộ đều đặn."
  }
];

const newReadingVocabOrder = [
  "drinking",
  "enough",
  "water",
  "important",
  "habit",
  "daily",
  "life",
  "drink",
  "glass",
  "waking",
  "and",
  "carry",
  "bottle",
  "also",
  "meals",
  "exercise",
  "helps",
  "body",
  "work",
  "well",
  "keeps",
  "active",
  "weather",
  "hot",
  "more",
  "because",
  "lose",
  "sweat",
  "choose",
  "clean",
  "instead",
  "sweet",
  "drinks",
  "most",
  "time",
  "remember",
  "put",
  "desk",
  "fill",
  "again",
  "becomes",
  "empty",
  "regularly",
  "simple",
  "inexpensive",
  "good",
  "health",
  "every",
  "single",
  "day",
  "family",
  "follows",
  "too",
  "keeping",
  "room",
  "tidy",
  "like",
  "neat",
  "comfortable",
  "space",
  "morning",
  "make",
  "bed",
  "dirty",
  "clothes",
  "basket",
  "return",
  "books",
  "school",
  "things",
  "places",
  "weekends",
  "spend",
  "cleaning",
  "sweep",
  "floor",
  "wipe",
  "open",
  "window",
  "fresh",
  "air",
  "sometimes",
  "give",
  "away",
  "old",
  "items",
  "no",
  "longer",
  "need",
  "find",
  "quickly",
  "study",
  "better",
  "makes",
  "feel",
  "calm",
  "happy",
  "takes",
  "less",
  "do",
  "little",
  "each",
  "so",
  "try",
  "not",
  "lazy",
  "everyone",
  "enjoys",
  "home",
  "practicing",
  "english",
  "part",
  "routine",
  "learn",
  "five",
  "new",
  "words",
  "review",
  "evening",
  "listen",
  "short",
  "videos",
  "songs",
  "or",
  "conversations",
  "online",
  "improve",
  "speaking",
  "read",
  "sentences",
  "aloud",
  "talk",
  "myself",
  "practice",
  "classmates",
  "ask",
  "easy",
  "questions",
  "correct",
  "small",
  "mistakes",
  "encourage",
  "other",
  "continue",
  "learning",
  "language",
  "patient",
  "long",
  "lesson",
  "once",
  "month",
  "useful",
  "confident",
  "communicate",
  "people",
  "everywhere",
  "can",
  "see",
  "steady",
  "progress"
];
