const newEssayData = [
  {
    "text": "1. Banh Chung – Bánh chưng\nBanh chung is a traditional Vietnamese cake. It is square and is often prepared for Tet, the Vietnamese Lunar New Year. The green leaves outside make it look simple and beautiful.\n\nPeople make banh chung with sticky rice, green beans, and pork. These ingredients are placed inside dong leaves. Then the cake is tied carefully with strings.\n\nThe cake is boiled for many hours. Family members often sit together near the pot, talk, and wait. This activity creates warm memories during Tet.\n\nBanh chung has a soft texture and a rich taste. It represents the earth, family love, and respect for ancestors. Many Vietnamese people enjoy it with pickled vegetables.",
    "vi": "1. Bánh chưng\nBánh chưng là một loại bánh truyền thống của Việt Nam. Bánh có hình vuông và thường được chuẩn bị cho Tết, tức Tết Nguyên đán của Việt Nam. Những chiếc lá xanh bên ngoài làm bánh trông giản dị và đẹp mắt.\n\nMọi người làm bánh chưng bằng gạo nếp, đậu xanh và thịt lợn. Những nguyên liệu này được đặt bên trong lá dong. Sau đó bánh được buộc cẩn thận bằng dây.\n\nBánh được luộc trong nhiều giờ. Các thành viên trong gia đình thường ngồi cùng nhau gần nồi bánh, trò chuyện và chờ đợi. Hoạt động này tạo nên những kỷ niệm ấm áp trong dịp Tết.\n\nBánh chưng có kết cấu mềm và vị đậm đà. Bánh tượng trưng cho đất, tình yêu gia đình và sự kính trọng tổ tiên. Nhiều người Việt Nam thích ăn bánh cùng rau củ muối chua."
  },
  {
    "text": "2. Banh Tet – Bánh tét\nBanh tet is a traditional cake in southern and central Vietnam. It has a long, round shape and is often prepared for Tet. Its green leaf cover gives it a natural appearance.\n\nThe main ingredients are sticky rice, green beans, and pork. Some sweet versions contain bananas or black beans. The cake is wrapped tightly in banana leaves.\n\nPeople boil banh tet for hours until the rice becomes soft. After cooking, they cut it into round slices. The colorful layers look attractive.\n\nBanh tet is filling, tasty, and easy to share. Families often eat it with pickled vegetables. It is also a meaningful gift for relatives and friends during Tet.",
    "vi": "2. Bánh tét\nBánh tét là một loại bánh truyền thống ở miền Nam và miền Trung Việt Nam. Bánh có hình dài, tròn và thường được chuẩn bị cho Tết. Lớp lá xanh bên ngoài tạo cho bánh vẻ tự nhiên.\n\nNguyên liệu chính là gạo nếp, đậu xanh và thịt lợn. Một số phiên bản ngọt có chuối hoặc đậu đen. Bánh được gói chặt trong lá chuối.\n\nMọi người luộc bánh tét trong nhiều giờ cho đến khi gạo trở nên mềm. Sau khi nấu, họ cắt bánh thành những khoanh tròn. Các lớp màu sắc trông hấp dẫn.\n\nBánh tét no bụng, ngon và dễ chia sẻ. Các gia đình thường ăn bánh cùng rau củ muối chua. Đây cũng là một món quà ý nghĩa dành cho họ hàng và bạn bè trong dịp Tết."
  },
  {
    "text": "3. Banh Xeo – Bánh xèo\nBanh xeo is a famous Vietnamese pancake with a crispy yellow cover. Its name comes from the sound made when the batter touches a hot pan. It is popular in many regions.\n\nThe batter is usually made from rice flour, water, and turmeric. Cooks add shrimp, pork, bean sprouts, and green onions. The pancake is folded in half.\n\nPeople eat banh xeo with fresh vegetables and herbs. They wrap a small piece in lettuce or rice paper, then dip it in fish sauce.\n\nBanh xeo is crunchy, fresh, and full of flavor. It is often enjoyed with family or friends. Sharing this dish makes meals more cheerful and interesting together.",
    "vi": "3. Bánh xèo\nBánh xèo là một loại bánh kếp nổi tiếng của Việt Nam với lớp vỏ vàng giòn. Tên của bánh xuất phát từ âm thanh tạo ra khi bột chạm vào chảo nóng. Bánh phổ biến ở nhiều vùng.\n\nBột bánh thường được làm từ bột gạo, nước và nghệ. Người nấu thêm tôm, thịt lợn, giá đỗ và hành lá. Bánh được gấp làm đôi.\n\nMọi người ăn bánh xèo cùng rau tươi và rau thơm. Họ gói một miếng nhỏ trong rau xà lách hoặc bánh tráng, rồi chấm vào nước mắm.\n\nBánh xèo giòn, tươi và đậm hương vị. Bánh thường được thưởng thức cùng gia đình hoặc bạn bè. Cùng chia sẻ món ăn này làm bữa ăn vui vẻ và thú vị hơn."
  }
];
