const lessonVocabularyWords = [
  "banh",
  "chung",
  "traditional",
  "vietnamese",
  "cake",
  "square",
  "and",
  "often",
  "prepared",
  "tet",
  "lunar",
  "new",
  "year",
  "green",
  "leaves",
  "outside",
  "make",
  "look",
  "simple",
  "beautiful",
  "people",
  "sticky",
  "rice",
  "beans",
  "pork",
  "ingredients",
  "placed",
  "inside",
  "dong",
  "then",
  "tied",
  "carefully",
  "strings",
  "boiled",
  "hours",
  "family",
  "members",
  "sit",
  "together",
  "near",
  "pot",
  "talk",
  "wait",
  "activity",
  "creates",
  "warm",
  "memories",
  "has",
  "soft",
  "texture",
  "rich",
  "taste",
  "represents",
  "earth",
  "love",
  "respect",
  "ancestors",
  "enjoy",
  "pickled",
  "vegetables",
  "southern",
  "central",
  "vietnam",
  "long",
  "round",
  "shape",
  "leaf",
  "cover",
  "gives",
  "natural",
  "appearance",
  "main",
  "sweet",
  "versions",
  "contain",
  "bananas",
  "black",
  "wrapped",
  "tightly",
  "banana",
  "boil",
  "becomes",
  "cooking",
  "cut",
  "slices",
  "colorful",
  "layers",
  "attractive",
  "filling",
  "tasty",
  "easy",
  "share",
  "families",
  "eat",
  "also",
  "meaningful",
  "gift",
  "relatives",
  "friends",
  "xeo",
  "famous",
  "pancake",
  "crispy",
  "yellow",
  "name",
  "comes",
  "sound",
  "made",
  "when",
  "batter",
  "touches",
  "hot",
  "pan",
  "popular",
  "regions",
  "usually",
  "flour",
  "water",
  "turmeric",
  "cooks",
  "add",
  "shrimp",
  "bean",
  "sprouts",
  "onions",
  "folded",
  "half",
  "fresh",
  "herbs",
  "wrap",
  "small",
  "piece",
  "lettuce",
  "paper",
  "dip",
  "fish",
  "sauce",
  "crunchy",
  "full",
  "flavor",
  "enjoyed",
  "sharing",
  "dish",
  "makes",
  "meals",
  "more",
  "cheerful",
  "interesting"
];

const newVocabData = [
  {
    "id": 1,
    "word": "banh",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bæn/",
    "meaning": "bánh",
    "ex1": "Banh chung is a traditional Vietnamese cake.",
    "ex1_vi": "Bánh chưng là một loại bánh truyền thống của Việt Nam."
  },
  {
    "id": 2,
    "word": "chung",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃʊŋ/",
    "meaning": "chưng",
    "ex1": "Banh chung is a traditional Vietnamese cake.",
    "ex1_vi": "Bánh chưng là một loại bánh truyền thống của Việt Nam."
  },
  {
    "id": 3,
    "word": "traditional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trʌdˈɪʃʌnʌl/",
    "meaning": "truyền thống",
    "ex1": "Banh tet is a traditional cake in southern and central Vietnam.",
    "ex1_vi": "Bánh tét là một loại bánh truyền thống ở miền Nam và miền Trung Việt Nam."
  },
  {
    "id": 4,
    "word": "vietnamese",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/viˌɛtnɑmˈis/",
    "meaning": "Việt Nam; người Việt Nam",
    "ex1": "Many Vietnamese people enjoy it with pickled vegetables.",
    "ex1_vi": "Nhiều người Việt Nam thích ăn bánh cùng rau củ muối chua."
  },
  {
    "id": 5,
    "word": "cake",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈeɪk/",
    "meaning": "bánh",
    "ex1": "The cake is boiled for many hours.",
    "ex1_vi": "Bánh được luộc trong nhiều giờ."
  },
  {
    "id": 6,
    "word": "square",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/skwˈɛr/",
    "meaning": "hình vuông",
    "ex1": "It is square and is often prepared for Tet, the Vietnamese Lunar New Year.",
    "ex1_vi": "Bánh có hình vuông và thường được chuẩn bị cho Tết, tức Tết Nguyên đán của Việt Nam."
  },
  {
    "id": 7,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Banh tet is filling, tasty, and easy to share.",
    "ex1_vi": "Bánh tét no bụng, ngon và dễ chia sẻ."
  },
  {
    "id": 8,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "Families often eat it with pickled vegetables.",
    "ex1_vi": "Các gia đình thường ăn bánh cùng rau củ muối chua."
  },
  {
    "id": 9,
    "word": "prepared",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pripˈɛrd/",
    "meaning": "được chuẩn bị",
    "ex1": "It has a long, round shape and is often prepared for Tet.",
    "ex1_vi": "Bánh có hình dài, tròn và thường được chuẩn bị cho Tết."
  },
  {
    "id": 10,
    "word": "tet",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tɛt/",
    "meaning": "Tết",
    "ex1": "This activity creates warm memories during Tet.",
    "ex1_vi": "Hoạt động này tạo nên những kỷ niệm ấm áp trong dịp Tết."
  },
  {
    "id": 11,
    "word": "lunar",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈunɝ/",
    "meaning": "âm lịch",
    "ex1": "It is square and is often prepared for Tet, the Vietnamese Lunar New Year.",
    "ex1_vi": "Bánh có hình vuông và thường được chuẩn bị cho Tết, tức Tết Nguyên đán của Việt Nam."
  },
  {
    "id": 12,
    "word": "new",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈu/",
    "meaning": "mới",
    "ex1": "The finished cake looks new and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông mới và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 13,
    "word": "year",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈɪr/",
    "meaning": "năm",
    "ex1": "The year is important in this traditional Vietnamese cake.",
    "ex1_vi": "Năm rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 14,
    "word": "green",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈin/",
    "meaning": "xanh",
    "ex1": "Its green leaf cover gives it a natural appearance.",
    "ex1_vi": "Lớp lá xanh bên ngoài tạo cho bánh vẻ tự nhiên."
  },
  {
    "id": 15,
    "word": "leaves",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈivz/",
    "meaning": "lá",
    "ex1": "These ingredients are placed inside dong leaves.",
    "ex1_vi": "Những nguyên liệu này được đặt bên trong lá dong."
  },
  {
    "id": 16,
    "word": "outside",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaʊtsˈaɪd/",
    "meaning": "bên ngoài",
    "ex1": "The green leaves outside make it look simple and beautiful.",
    "ex1_vi": "Những chiếc lá xanh bên ngoài làm bánh trông giản dị và đẹp mắt."
  },
  {
    "id": 17,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm",
    "ex1": "The green leaves outside make it look simple and beautiful.",
    "ex1_vi": "Những chiếc lá xanh bên ngoài làm bánh trông giản dị và đẹp mắt."
  },
  {
    "id": 18,
    "word": "look",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊk/",
    "meaning": "trông",
    "ex1": "Cooks look the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu trông chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 19,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "The finished cake looks simple and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đơn giản và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 20,
    "word": "beautiful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bjˈutʌfʌl/",
    "meaning": "đẹp",
    "ex1": "The finished cake looks beautiful and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đẹp và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 21,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "Many Vietnamese people enjoy it with pickled vegetables.",
    "ex1_vi": "Nhiều người Việt Nam thích ăn bánh cùng rau củ muối chua."
  },
  {
    "id": 22,
    "word": "sticky",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/stˈɪki/",
    "meaning": "dẻo; nếp",
    "ex1": "The main ingredients are sticky rice, green beans, and pork.",
    "ex1_vi": "Nguyên liệu chính là gạo nếp, đậu xanh và thịt lợn."
  },
  {
    "id": 23,
    "word": "rice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪs/",
    "meaning": "gạo",
    "ex1": "The main ingredients are sticky rice, green beans, and pork.",
    "ex1_vi": "Nguyên liệu chính là gạo nếp, đậu xanh và thịt lợn."
  },
  {
    "id": 24,
    "word": "beans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈinz/",
    "meaning": "đậu",
    "ex1": "Some sweet versions contain bananas or black beans.",
    "ex1_vi": "Một số phiên bản ngọt có chuối hoặc đậu đen."
  },
  {
    "id": 25,
    "word": "pork",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɔrk/",
    "meaning": "thịt lợn",
    "ex1": "Cooks add shrimp, pork, bean sprouts, and green onions.",
    "ex1_vi": "Người nấu thêm tôm, thịt lợn, giá đỗ và hành lá."
  },
  {
    "id": 26,
    "word": "ingredients",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnɡrˈidiʌnts/",
    "meaning": "nguyên liệu",
    "ex1": "These ingredients are placed inside dong leaves.",
    "ex1_vi": "Những nguyên liệu này được đặt bên trong lá dong."
  },
  {
    "id": 27,
    "word": "placed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪst/",
    "meaning": "được đặt",
    "ex1": "The cake is placed carefully before family members enjoy it.",
    "ex1_vi": "Chiếc bánh được được đặt cẩn thận trước khi các thành viên gia đình thưởng thức."
  },
  {
    "id": 28,
    "word": "inside",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ˌɪnsˈaɪd/",
    "meaning": "bên trong",
    "ex1": "Cooks inside the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu bên trong chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 29,
    "word": "dong",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/dɔːŋ/",
    "meaning": "dong; lá dong",
    "ex1": "Cooks dong the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu dong; lá dong chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 30,
    "word": "then",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ðˈɛn/",
    "meaning": "sau đó",
    "ex1": "Then the cake is tied carefully with strings.",
    "ex1_vi": "Sau đó bánh được buộc cẩn thận bằng dây."
  },
  {
    "id": 31,
    "word": "tied",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈaɪd/",
    "meaning": "được buộc",
    "ex1": "Then the cake is tied carefully with strings.",
    "ex1_vi": "Sau đó bánh được buộc cẩn thận bằng dây."
  },
  {
    "id": 32,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "Cooks carefully prepare traditional cakes for family meals and celebrations.",
    "ex1_vi": "Người nấu cẩn thận chuẩn bị bánh truyền thống cho bữa ăn và lễ kỷ niệm gia đình."
  },
  {
    "id": 33,
    "word": "strings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/strˈɪŋz/",
    "meaning": "dây",
    "ex1": "The strings is important in this traditional Vietnamese cake.",
    "ex1_vi": "Dây rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 34,
    "word": "boiled",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɔɪld/",
    "meaning": "được luộc",
    "ex1": "The cake is boiled for many hours.",
    "ex1_vi": "Bánh được luộc trong nhiều giờ."
  },
  {
    "id": 35,
    "word": "hours",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaʊɝz/",
    "meaning": "giờ",
    "ex1": "People boil banh tet for hours until the rice becomes soft.",
    "ex1_vi": "Mọi người luộc bánh tét trong nhiều giờ cho đến khi gạo trở nên mềm."
  },
  {
    "id": 36,
    "word": "family",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "It is often enjoyed with family or friends.",
    "ex1_vi": "Bánh thường được thưởng thức cùng gia đình hoặc bạn bè."
  },
  {
    "id": 37,
    "word": "members",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛmbɝz/",
    "meaning": "thành viên",
    "ex1": "Family members often sit together near the pot, talk, and wait.",
    "ex1_vi": "Các thành viên trong gia đình thường ngồi cùng nhau gần nồi bánh, trò chuyện và chờ đợi."
  },
  {
    "id": 38,
    "word": "sit",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɪt/",
    "meaning": "ngồi",
    "ex1": "Family members often sit together near the pot, talk, and wait.",
    "ex1_vi": "Các thành viên trong gia đình thường ngồi cùng nhau gần nồi bánh, trò chuyện và chờ đợi."
  },
  {
    "id": 39,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌɡˈɛðɝ/",
    "meaning": "cùng nhau",
    "ex1": "Sharing this dish makes meals more cheerful and interesting together.",
    "ex1_vi": "Cùng chia sẻ món ăn này làm bữa ăn vui vẻ và thú vị hơn."
  },
  {
    "id": 40,
    "word": "near",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈɪr/",
    "meaning": "gần",
    "ex1": "The near is important in this traditional Vietnamese cake.",
    "ex1_vi": "Gần rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 41,
    "word": "pot",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑt/",
    "meaning": "nồi",
    "ex1": "The pot is important in this traditional Vietnamese cake.",
    "ex1_vi": "Nồi rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 42,
    "word": "talk",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈɔk/",
    "meaning": "trò chuyện",
    "ex1": "Cooks talk the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu trò chuyện chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 43,
    "word": "wait",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈeɪt/",
    "meaning": "chờ đợi",
    "ex1": "Cooks wait the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu chờ đợi chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 44,
    "word": "activity",
    "type": "noun",
    "cat": "n",
    "phonetic": "/æktˈɪvʌti/",
    "meaning": "hoạt động",
    "ex1": "This activity creates warm memories during Tet.",
    "ex1_vi": "Hoạt động này tạo nên những kỷ niệm ấm áp trong dịp Tết."
  },
  {
    "id": 45,
    "word": "creates",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kriˈeɪts/",
    "meaning": "tạo ra",
    "ex1": "The creates is important in this traditional Vietnamese cake.",
    "ex1_vi": "Tạo ra rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 46,
    "word": "warm",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɔrm/",
    "meaning": "ấm áp",
    "ex1": "Cooks warm the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu ấm áp chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 47,
    "word": "memories",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛmɝiz/",
    "meaning": "kỷ niệm",
    "ex1": "The memories is important in this traditional Vietnamese cake.",
    "ex1_vi": "Kỷ niệm rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 48,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "Banh chung has a soft texture and a rich taste.",
    "ex1_vi": "Bánh chưng có kết cấu mềm và vị đậm đà."
  },
  {
    "id": 49,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "Banh chung has a soft texture and a rich taste.",
    "ex1_vi": "Bánh chưng có kết cấu mềm và vị đậm đà."
  },
  {
    "id": 50,
    "word": "texture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛkstʃɝ/",
    "meaning": "kết cấu",
    "ex1": "The chewy texture makes this traditional cake easy to remember.",
    "ex1_vi": "Kết cấu dai khiến loại bánh truyền thống này dễ nhớ."
  },
  {
    "id": 51,
    "word": "rich",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɪtʃ/",
    "meaning": "đậm đà; béo",
    "ex1": "The finished cake looks rich and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đậm đà; béo và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 52,
    "word": "taste",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪst/",
    "meaning": "hương vị",
    "ex1": "Cooks taste the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu hương vị chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 53,
    "word": "represents",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˌɛprɪzˈɛnts/",
    "meaning": "tượng trưng",
    "ex1": "It represents the earth, family love, and respect for ancestors.",
    "ex1_vi": "Bánh tượng trưng cho đất, tình yêu gia đình và sự kính trọng tổ tiên."
  },
  {
    "id": 54,
    "word": "earth",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɝθ/",
    "meaning": "đất",
    "ex1": "It represents the earth, family love, and respect for ancestors.",
    "ex1_vi": "Bánh tượng trưng cho đất, tình yêu gia đình và sự kính trọng tổ tiên."
  },
  {
    "id": 55,
    "word": "love",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʌv/",
    "meaning": "tình yêu",
    "ex1": "Cooks love the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu tình yêu chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 56,
    "word": "respect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪspˈɛkt/",
    "meaning": "sự kính trọng",
    "ex1": "Cooks respect the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu sự kính trọng chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 57,
    "word": "ancestors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈænsˌɛstɝz/",
    "meaning": "tổ tiên",
    "ex1": "The ancestors is important in this traditional Vietnamese cake.",
    "ex1_vi": "Tổ tiên rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 58,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thưởng thức",
    "ex1": "Cooks enjoy the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu thưởng thức chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 59,
    "word": "pickled",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pˈɪkʌld/",
    "meaning": "muối chua",
    "ex1": "Families often eat it with pickled vegetables.",
    "ex1_vi": "Các gia đình thường ăn bánh cùng rau củ muối chua."
  },
  {
    "id": 60,
    "word": "vegetables",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɛdʒtʌbʌlz/",
    "meaning": "rau củ",
    "ex1": "People eat banh xeo with fresh vegetables and herbs.",
    "ex1_vi": "Mọi người ăn bánh xèo cùng rau tươi và rau thơm."
  },
  {
    "id": 61,
    "word": "southern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈʌðɝn/",
    "meaning": "miền Nam; thuộc miền Nam",
    "ex1": "Banh tet is a traditional cake in southern and central Vietnam.",
    "ex1_vi": "Bánh tét là một loại bánh truyền thống ở miền Nam và miền Trung Việt Nam."
  },
  {
    "id": 62,
    "word": "central",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɛntrʌl/",
    "meaning": "miền Trung; thuộc miền Trung",
    "ex1": "The finished cake looks central and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông miền Trung; thuộc miền Trung và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 63,
    "word": "vietnam",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/viˌɛtnˈɑm/",
    "meaning": "Việt Nam",
    "ex1": "Cooks vietnam the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu Việt Nam chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 64,
    "word": "long",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɔŋ/",
    "meaning": "dài",
    "ex1": "It has a long, round shape and is often prepared for Tet.",
    "ex1_vi": "Bánh có hình dài, tròn và thường được chuẩn bị cho Tết."
  },
  {
    "id": 65,
    "word": "round",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈaʊnd/",
    "meaning": "tròn",
    "ex1": "After cooking, they cut it into round slices.",
    "ex1_vi": "Sau khi nấu, họ cắt bánh thành những khoanh tròn."
  },
  {
    "id": 66,
    "word": "shape",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈeɪp/",
    "meaning": "hình dạng",
    "ex1": "The shape is important in this traditional Vietnamese cake.",
    "ex1_vi": "Hình dạng rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 67,
    "word": "leaf",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈif/",
    "meaning": "lá",
    "ex1": "Its green leaf cover gives it a natural appearance.",
    "ex1_vi": "Lớp lá xanh bên ngoài tạo cho bánh vẻ tự nhiên."
  },
  {
    "id": 68,
    "word": "cover",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌvɝ/",
    "meaning": "lớp vỏ; lớp phủ",
    "ex1": "Banh xeo is a famous Vietnamese pancake with a crispy yellow cover.",
    "ex1_vi": "Bánh xèo là một loại bánh kếp nổi tiếng của Việt Nam với lớp vỏ vàng giòn."
  },
  {
    "id": 69,
    "word": "gives",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvz/",
    "meaning": "mang lại",
    "ex1": "This cooking step gives a special result for the cake.",
    "ex1_vi": "Bước nấu này mang lại một kết quả đặc biệt cho chiếc bánh."
  },
  {
    "id": 70,
    "word": "natural",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈætʃɝʌl/",
    "meaning": "tự nhiên",
    "ex1": "The finished cake looks natural and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông tự nhiên và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 71,
    "word": "appearance",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌpˈɪrʌns/",
    "meaning": "vẻ ngoài",
    "ex1": "The appearance is important in this traditional Vietnamese cake.",
    "ex1_vi": "Vẻ ngoài rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 72,
    "word": "main",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈeɪn/",
    "meaning": "chính",
    "ex1": "The finished cake looks main and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông chính và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 73,
    "word": "sweet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/swˈit/",
    "meaning": "ngọt",
    "ex1": "Some sweet versions contain bananas or black beans.",
    "ex1_vi": "Một số phiên bản ngọt có chuối hoặc đậu đen."
  },
  {
    "id": 74,
    "word": "versions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɝʒʌnz/",
    "meaning": "phiên bản",
    "ex1": "The versions is important in this traditional Vietnamese cake.",
    "ex1_vi": "Phiên bản rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 75,
    "word": "contain",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈeɪn/",
    "meaning": "chứa",
    "ex1": "Cooks contain the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu chứa chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 76,
    "word": "bananas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bʌnˈænʌz/",
    "meaning": "chuối",
    "ex1": "The bananas is important in this traditional Vietnamese cake.",
    "ex1_vi": "Chuối rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 77,
    "word": "black",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/blˈæk/",
    "meaning": "đen",
    "ex1": "The finished cake looks black and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đen và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 78,
    "word": "wrapped",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈæpt/",
    "meaning": "được gói",
    "ex1": "The cake is wrapped tightly in banana leaves.",
    "ex1_vi": "Bánh được gói chặt trong lá chuối."
  },
  {
    "id": 79,
    "word": "tightly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tˈaɪtli/",
    "meaning": "chặt",
    "ex1": "The cake is wrapped tightly in banana leaves.",
    "ex1_vi": "Bánh được gói chặt trong lá chuối."
  },
  {
    "id": 80,
    "word": "banana",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bʌnˈænʌ/",
    "meaning": "chuối",
    "ex1": "Banana leaves are often used to wrap traditional cakes.",
    "ex1_vi": "Lá chuối thường được dùng để gói các loại bánh truyền thống."
  },
  {
    "id": 81,
    "word": "boil",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɔɪl/",
    "meaning": "luộc",
    "ex1": "People boil banh tet for hours until the rice becomes soft.",
    "ex1_vi": "Mọi người luộc bánh tét trong nhiều giờ cho đến khi gạo trở nên mềm."
  },
  {
    "id": 82,
    "word": "becomes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌmz/",
    "meaning": "trở nên",
    "ex1": "This cooking step becomes a special result for the cake.",
    "ex1_vi": "Bước nấu này trở nên một kết quả đặc biệt cho chiếc bánh."
  },
  {
    "id": 83,
    "word": "cooking",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʊkɪŋ/",
    "meaning": "nấu",
    "ex1": "After cooking, they cut it into round slices.",
    "ex1_vi": "Sau khi nấu, họ cắt bánh thành những khoanh tròn."
  },
  {
    "id": 84,
    "word": "cut",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌt/",
    "meaning": "cắt",
    "ex1": "Cooks cut the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu cắt chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 85,
    "word": "slices",
    "type": "noun",
    "cat": "n",
    "phonetic": "/slˈaɪsʌz/",
    "meaning": "lát; khoanh",
    "ex1": "The slices is important in this traditional Vietnamese cake.",
    "ex1_vi": "Lát; khoanh rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 86,
    "word": "colorful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌlɝfʌl/",
    "meaning": "nhiều màu sắc",
    "ex1": "The finished cake looks colorful and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông nhiều màu sắc và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 87,
    "word": "layers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈeɪɝz/",
    "meaning": "lớp",
    "ex1": "The layers is important in this traditional Vietnamese cake.",
    "ex1_vi": "Lớp rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 88,
    "word": "attractive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌtrˈæktɪv/",
    "meaning": "hấp dẫn",
    "ex1": "The finished cake looks attractive and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông hấp dẫn và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 89,
    "word": "filling",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɪlɪŋ/",
    "meaning": "nhân; no bụng",
    "ex1": "Banh tet is filling, tasty, and easy to share.",
    "ex1_vi": "Bánh tét no bụng, ngon và dễ chia sẻ."
  },
  {
    "id": 90,
    "word": "tasty",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈeɪsti/",
    "meaning": "ngon",
    "ex1": "The finished cake looks tasty and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông ngon và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 91,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "The finished cake looks easy and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông dễ và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 92,
    "word": "share",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈɛr/",
    "meaning": "chia sẻ",
    "ex1": "Cooks share the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu chia sẻ chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 93,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌliz/",
    "meaning": "các gia đình",
    "ex1": "The families is important in this traditional Vietnamese cake.",
    "ex1_vi": "Các gia đình rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 94,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "People eat banh xeo with fresh vegetables and herbs.",
    "ex1_vi": "Mọi người ăn bánh xèo cùng rau tươi và rau thơm."
  },
  {
    "id": 95,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "It is also a meaningful gift for relatives and friends during Tet.",
    "ex1_vi": "Đây cũng là một món quà ý nghĩa dành cho họ hàng và bạn bè trong dịp Tết."
  },
  {
    "id": 96,
    "word": "meaningful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈinɪŋfʌl/",
    "meaning": "ý nghĩa",
    "ex1": "It is also a meaningful gift for relatives and friends during Tet.",
    "ex1_vi": "Đây cũng là một món quà ý nghĩa dành cho họ hàng và bạn bè trong dịp Tết."
  },
  {
    "id": 97,
    "word": "gift",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɪft/",
    "meaning": "món quà",
    "ex1": "The gift is important in this traditional Vietnamese cake.",
    "ex1_vi": "Món quà rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 98,
    "word": "relatives",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɛlʌtɪvz/",
    "meaning": "họ hàng",
    "ex1": "The relatives is important in this traditional Vietnamese cake.",
    "ex1_vi": "Họ hàng rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 99,
    "word": "friends",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈɛndz/",
    "meaning": "bạn bè",
    "ex1": "It is often enjoyed with family or friends.",
    "ex1_vi": "Bánh thường được thưởng thức cùng gia đình hoặc bạn bè."
  },
  {
    "id": 100,
    "word": "xeo",
    "type": "noun",
    "cat": "n",
    "phonetic": "/seʊ/",
    "meaning": "xèo",
    "ex1": "Banh xeo is crunchy, fresh, and full of flavor.",
    "ex1_vi": "Bánh xèo giòn, tươi và đậm hương vị."
  },
  {
    "id": 101,
    "word": "famous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈeɪmʌs/",
    "meaning": "nổi tiếng",
    "ex1": "Banh xeo is a famous Vietnamese pancake with a crispy yellow cover.",
    "ex1_vi": "Bánh xèo là một loại bánh kếp nổi tiếng của Việt Nam với lớp vỏ vàng giòn."
  },
  {
    "id": 102,
    "word": "pancake",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈænkˌeɪk/",
    "meaning": "bánh kếp",
    "ex1": "The pancake is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bánh kếp rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 103,
    "word": "crispy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈɪspi/",
    "meaning": "giòn",
    "ex1": "Banh xeo has a crispy cover and fresh filling.",
    "ex1_vi": "Bánh xèo có lớp vỏ giòn và phần nhân tươi."
  },
  {
    "id": 104,
    "word": "yellow",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈɛloʊ/",
    "meaning": "vàng",
    "ex1": "The finished cake looks yellow and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông vàng và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 105,
    "word": "name",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈeɪm/",
    "meaning": "tên",
    "ex1": "Its name comes from the sound made when the batter touches a hot pan.",
    "ex1_vi": "Tên của bánh xuất phát từ âm thanh tạo ra khi bột chạm vào chảo nóng."
  },
  {
    "id": 106,
    "word": "comes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌmz/",
    "meaning": "đến; bắt nguồn",
    "ex1": "Its name comes from the sound made when the batter touches a hot pan.",
    "ex1_vi": "Tên của bánh xuất phát từ âm thanh tạo ra khi bột chạm vào chảo nóng."
  },
  {
    "id": 107,
    "word": "sound",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaʊnd/",
    "meaning": "âm thanh",
    "ex1": "The sound is important in this traditional Vietnamese cake.",
    "ex1_vi": "Âm thanh rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 108,
    "word": "made",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈeɪd/",
    "meaning": "được làm",
    "ex1": "The batter is usually made from rice flour, water, and turmeric.",
    "ex1_vi": "Bột bánh thường được làm từ bột gạo, nước và nghệ."
  },
  {
    "id": 109,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "Families cook together when they prepare traditional Vietnamese cakes.",
    "ex1_vi": "Các gia đình nấu cùng nhau khi họ chuẩn bị những loại bánh Việt Nam truyền thống."
  },
  {
    "id": 110,
    "word": "batter",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈætɝ/",
    "meaning": "bột bánh",
    "ex1": "The batter is usually made from rice flour, water, and turmeric.",
    "ex1_vi": "Bột bánh thường được làm từ bột gạo, nước và nghệ."
  },
  {
    "id": 111,
    "word": "touches",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈʌtʃʌz/",
    "meaning": "chạm",
    "ex1": "The touches is important in this traditional Vietnamese cake.",
    "ex1_vi": "Chạm rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 112,
    "word": "hot",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑt/",
    "meaning": "nóng",
    "ex1": "The finished cake looks hot and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông nóng và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 113,
    "word": "pan",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈæn/",
    "meaning": "chảo",
    "ex1": "The pan is important in this traditional Vietnamese cake.",
    "ex1_vi": "Chảo rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 114,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "The finished cake looks popular and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông phổ biến và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 115,
    "word": "regions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈidʒʌnz/",
    "meaning": "vùng",
    "ex1": "The regions is important in this traditional Vietnamese cake.",
    "ex1_vi": "Vùng rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 116,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "Cooks usually prepare traditional cakes for family meals and celebrations.",
    "ex1_vi": "Người nấu thường chuẩn bị bánh truyền thống cho bữa ăn và lễ kỷ niệm gia đình."
  },
  {
    "id": 117,
    "word": "flour",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈaʊɝ/",
    "meaning": "bột",
    "ex1": "Rice flour forms the base of many traditional cakes.",
    "ex1_vi": "Bột gạo tạo phần nền cho nhiều loại bánh truyền thống."
  },
  {
    "id": 118,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước",
    "ex1": "The water is important in this traditional Vietnamese cake.",
    "ex1_vi": "Nước rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 119,
    "word": "turmeric",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈtɜːrmərɪk/",
    "meaning": "nghệ",
    "ex1": "Turmeric gives banh xeo its familiar yellow color.",
    "ex1_vi": "Nghệ tạo cho bánh xèo màu vàng quen thuộc."
  },
  {
    "id": 120,
    "word": "cooks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʊks/",
    "meaning": "người nấu",
    "ex1": "Cooks add shrimp, pork, bean sprouts, and green onions.",
    "ex1_vi": "Người nấu thêm tôm, thịt lợn, giá đỗ và hành lá."
  },
  {
    "id": 121,
    "word": "add",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈæd/",
    "meaning": "thêm",
    "ex1": "Cooks add the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu thêm chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 122,
    "word": "shrimp",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃrˈɪmp/",
    "meaning": "tôm",
    "ex1": "Fresh shrimp adds rich flavor to several Vietnamese cakes.",
    "ex1_vi": "Tôm tươi làm tăng hương vị đậm đà cho nhiều loại bánh Việt Nam."
  },
  {
    "id": 123,
    "word": "bean",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈin/",
    "meaning": "đậu",
    "ex1": "The bean is important in this traditional Vietnamese cake.",
    "ex1_vi": "Đậu rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 124,
    "word": "sprouts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sprˈaʊts/",
    "meaning": "giá đỗ",
    "ex1": "The sprouts is important in this traditional Vietnamese cake.",
    "ex1_vi": "Giá đỗ rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 125,
    "word": "onions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈʌnjʌnz/",
    "meaning": "hành",
    "ex1": "The onions is important in this traditional Vietnamese cake.",
    "ex1_vi": "Hành rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 126,
    "word": "folded",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈoʊldʌd/",
    "meaning": "được gấp",
    "ex1": "The cake is folded carefully before family members enjoy it.",
    "ex1_vi": "Chiếc bánh được được gấp cẩn thận trước khi các thành viên gia đình thưởng thức."
  },
  {
    "id": 127,
    "word": "half",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈæf/",
    "meaning": "một nửa",
    "ex1": "The half is important in this traditional Vietnamese cake.",
    "ex1_vi": "Một nửa rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 128,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi",
    "ex1": "Banh xeo is crunchy, fresh, and full of flavor.",
    "ex1_vi": "Bánh xèo giòn, tươi và đậm hương vị."
  },
  {
    "id": 129,
    "word": "herbs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɝbz/",
    "meaning": "rau thơm",
    "ex1": "The herbs is important in this traditional Vietnamese cake.",
    "ex1_vi": "Rau thơm rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 130,
    "word": "wrap",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈæp/",
    "meaning": "gói",
    "ex1": "They wrap a small piece in lettuce or rice paper, then dip it in fish sauce.",
    "ex1_vi": "Họ gói một miếng nhỏ trong rau xà lách hoặc bánh tráng, rồi chấm vào nước mắm."
  },
  {
    "id": 131,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "They wrap a small piece in lettuce or rice paper, then dip it in fish sauce.",
    "ex1_vi": "Họ gói một miếng nhỏ trong rau xà lách hoặc bánh tráng, rồi chấm vào nước mắm."
  },
  {
    "id": 132,
    "word": "piece",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈis/",
    "meaning": "miếng",
    "ex1": "The piece is important in this traditional Vietnamese cake.",
    "ex1_vi": "Miếng rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 133,
    "word": "lettuce",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɛtʌs/",
    "meaning": "xà lách",
    "ex1": "The lettuce is important in this traditional Vietnamese cake.",
    "ex1_vi": "Xà lách rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 134,
    "word": "paper",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈeɪpɝ/",
    "meaning": "bánh tráng; giấy",
    "ex1": "The paper is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bánh tráng; giấy rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 135,
    "word": "dip",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈɪp/",
    "meaning": "chấm",
    "ex1": "Cooks dip the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu chấm chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 136,
    "word": "fish",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɪʃ/",
    "meaning": "cá",
    "ex1": "The fish is important in this traditional Vietnamese cake.",
    "ex1_vi": "Cá rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 137,
    "word": "sauce",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔs/",
    "meaning": "nước xốt; nước mắm",
    "ex1": "The sauce is important in this traditional Vietnamese cake.",
    "ex1_vi": "Nước xốt; nước mắm rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 138,
    "word": "crunchy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈʌntʃi/",
    "meaning": "giòn",
    "ex1": "The finished cake looks crunchy and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông giòn và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 139,
    "word": "full",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈʊl/",
    "meaning": "đầy",
    "ex1": "The finished cake looks full and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đầy và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 140,
    "word": "flavor",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝ/",
    "meaning": "hương vị",
    "ex1": "Fresh ingredients create a rich flavor in the finished cake.",
    "ex1_vi": "Nguyên liệu tươi tạo hương vị đậm đà cho chiếc bánh hoàn chỉnh."
  },
  {
    "id": 141,
    "word": "enjoyed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪd/",
    "meaning": "được thưởng thức",
    "ex1": "The cake is enjoyed carefully before family members enjoy it.",
    "ex1_vi": "Chiếc bánh được được thưởng thức cẩn thận trước khi các thành viên gia đình thưởng thức."
  },
  {
    "id": 142,
    "word": "sharing",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈɛrɪŋ/",
    "meaning": "việc chia sẻ",
    "ex1": "Sharing this dish makes meals more cheerful and interesting together.",
    "ex1_vi": "Cùng chia sẻ món ăn này làm bữa ăn vui vẻ và thú vị hơn."
  },
  {
    "id": 143,
    "word": "dish",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪʃ/",
    "meaning": "món ăn",
    "ex1": "The dish is important in this traditional Vietnamese cake.",
    "ex1_vi": "Món ăn rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 144,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm cho",
    "ex1": "This cooking step makes a special result for the cake.",
    "ex1_vi": "Bước nấu này làm cho một kết quả đặc biệt cho chiếc bánh."
  },
  {
    "id": 145,
    "word": "meals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈilz/",
    "meaning": "bữa ăn",
    "ex1": "The meals is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bữa ăn rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 146,
    "word": "more",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "hơn",
    "ex1": "Cooks more the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu hơn chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 147,
    "word": "cheerful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tʃˈɪrfʌl/",
    "meaning": "vui vẻ",
    "ex1": "The finished cake looks cheerful and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông vui vẻ và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 148,
    "word": "interesting",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɪntrʌstɪŋ/",
    "meaning": "thú vị",
    "ex1": "The finished cake looks interesting and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông thú vị và có vị dễ chịu khi được phục vụ."
  }
];

const newReadingVocabOrder = [
  "banh",
  "chung",
  "traditional",
  "vietnamese",
  "cake",
  "square",
  "and",
  "often",
  "prepared",
  "tet",
  "lunar",
  "new",
  "year",
  "green",
  "leaves",
  "outside",
  "make",
  "look",
  "simple",
  "beautiful",
  "people",
  "sticky",
  "rice",
  "beans",
  "pork",
  "ingredients",
  "placed",
  "inside",
  "dong",
  "then",
  "tied",
  "carefully",
  "strings",
  "boiled",
  "hours",
  "family",
  "members",
  "sit",
  "together",
  "near",
  "pot",
  "talk",
  "wait",
  "activity",
  "creates",
  "warm",
  "memories",
  "has",
  "soft",
  "texture",
  "rich",
  "taste",
  "represents",
  "earth",
  "love",
  "respect",
  "ancestors",
  "enjoy",
  "pickled",
  "vegetables",
  "southern",
  "central",
  "vietnam",
  "long",
  "round",
  "shape",
  "leaf",
  "cover",
  "gives",
  "natural",
  "appearance",
  "main",
  "sweet",
  "versions",
  "contain",
  "bananas",
  "black",
  "wrapped",
  "tightly",
  "banana",
  "boil",
  "becomes",
  "cooking",
  "cut",
  "slices",
  "colorful",
  "layers",
  "attractive",
  "filling",
  "tasty",
  "easy",
  "share",
  "families",
  "eat",
  "also",
  "meaningful",
  "gift",
  "relatives",
  "friends",
  "xeo",
  "famous",
  "pancake",
  "crispy",
  "yellow",
  "name",
  "comes",
  "sound",
  "made",
  "when",
  "batter",
  "touches",
  "hot",
  "pan",
  "popular",
  "regions",
  "usually",
  "flour",
  "water",
  "turmeric",
  "cooks",
  "add",
  "shrimp",
  "bean",
  "sprouts",
  "onions",
  "folded",
  "half",
  "fresh",
  "herbs",
  "wrap",
  "small",
  "piece",
  "lettuce",
  "paper",
  "dip",
  "fish",
  "sauce",
  "crunchy",
  "full",
  "flavor",
  "enjoyed",
  "sharing",
  "dish",
  "makes",
  "meals",
  "more",
  "cheerful",
  "interesting"
];
