const lessonVocabularyWords = [
  "banh",
  "cuon",
  "soft",
  "vietnamese",
  "dish",
  "made",
  "thin",
  "rice",
  "sheets",
  "commonly",
  "eaten",
  "breakfast",
  "but",
  "people",
  "also",
  "enjoy",
  "lunch",
  "dinner",
  "make",
  "cooks",
  "spread",
  "batter",
  "over",
  "hot",
  "cloth",
  "layer",
  "steamed",
  "short",
  "time",
  "becomes",
  "smooth",
  "and",
  "slightly",
  "clear",
  "filling",
  "often",
  "contains",
  "minced",
  "pork",
  "mushrooms",
  "onions",
  "rolls",
  "served",
  "fried",
  "fresh",
  "herbs",
  "sausage",
  "light",
  "fish",
  "sauce",
  "has",
  "gentle",
  "taste",
  "easy",
  "eat",
  "not",
  "heavy",
  "so",
  "suitable",
  "ages",
  "local",
  "shops",
  "prepare",
  "every",
  "morning",
  "beo",
  "small",
  "cake",
  "central",
  "vietnam",
  "tiny",
  "bowls",
  "plates",
  "white",
  "sticky",
  "flour",
  "water",
  "steaming",
  "add",
  "dried",
  "shrimp",
  "green",
  "onion",
  "oil",
  "crispy",
  "bread",
  "skin",
  "top",
  "usually",
  "sweet",
  "salty",
  "use",
  "spoon",
  "take",
  "toppings",
  "create",
  "interesting",
  "textures",
  "full",
  "flavor",
  "popular",
  "hue",
  "other",
  "provinces",
  "visitors",
  "snack",
  "while",
  "exploring",
  "markets",
  "traditional",
  "food",
  "streets",
  "bot",
  "loc",
  "chewy",
  "dumpling",
  "tapioca",
  "especially",
  "famous",
  "cooked",
  "dough",
  "looks",
  "attractive",
  "cakes",
  "wrapped",
  "banana",
  "leaves",
  "boiled",
  "without",
  "kinds",
  "delicious",
  "chili",
  "outside",
  "inside",
  "rich",
  "part",
  "family",
  "meal",
  "simple",
  "ingredients",
  "special",
  "remember",
  "cover",
  "orange"
];

const newVocabData = [
  {
    "id": 1,
    "word": "banh",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bæn/",
    "meaning": "bánh",
    "ex1": "Banh beo is light but full of flavor.",
    "ex1_vi": "Bánh bèo nhẹ nhưng đậm hương vị."
  },
  {
    "id": 2,
    "word": "cuon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kuːən/",
    "meaning": "cuốn",
    "ex1": "Banh cuon has a gentle taste and is easy to eat.",
    "ex1_vi": "Bánh cuốn có vị nhẹ nhàng và dễ ăn."
  },
  {
    "id": 3,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "It becomes smooth, soft, and slightly clear.",
    "ex1_vi": "Nó trở nên mịn, mềm và hơi trong."
  },
  {
    "id": 4,
    "word": "vietnamese",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/viˌɛtnɑmˈis/",
    "meaning": "Việt Nam; người Việt Nam",
    "ex1": "Banh cuon is a soft Vietnamese dish made from thin rice sheets.",
    "ex1_vi": "Bánh cuốn là một món ăn Việt Nam mềm được làm từ những lá bánh gạo mỏng."
  },
  {
    "id": 5,
    "word": "dish",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪʃ/",
    "meaning": "món ăn",
    "ex1": "Banh cuon is a soft Vietnamese dish made from thin rice sheets.",
    "ex1_vi": "Bánh cuốn là một món ăn Việt Nam mềm được làm từ những lá bánh gạo mỏng."
  },
  {
    "id": 6,
    "word": "made",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈeɪd/",
    "meaning": "được làm",
    "ex1": "The batter is made from rice flour and water.",
    "ex1_vi": "Bột bánh được làm từ bột gạo và nước."
  },
  {
    "id": 7,
    "word": "thin",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/θˈɪn/",
    "meaning": "mỏng",
    "ex1": "The thin layer is steamed for a short time.",
    "ex1_vi": "Lớp bột mỏng được hấp trong thời gian ngắn."
  },
  {
    "id": 8,
    "word": "rice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪs/",
    "meaning": "gạo",
    "ex1": "The batter is made from rice flour and water.",
    "ex1_vi": "Bột bánh được làm từ bột gạo và nước."
  },
  {
    "id": 9,
    "word": "sheets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈits/",
    "meaning": "lá bánh; tấm",
    "ex1": "To make the sheets, cooks spread rice batter over a hot cloth.",
    "ex1_vi": "Để làm lá bánh, người nấu tráng bột gạo trên một tấm vải nóng."
  },
  {
    "id": 10,
    "word": "commonly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɑmʌnli/",
    "meaning": "thường",
    "ex1": "It is commonly eaten for breakfast, but many people also enjoy it at lunch or dinner.",
    "ex1_vi": "Món này thường được ăn vào bữa sáng, nhưng nhiều người cũng thưởng thức vào bữa trưa hoặc bữa tối."
  },
  {
    "id": 11,
    "word": "eaten",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈitʌn/",
    "meaning": "được ăn",
    "ex1": "It is commonly eaten for breakfast, but many people also enjoy it at lunch or dinner.",
    "ex1_vi": "Món này thường được ăn vào bữa sáng, nhưng nhiều người cũng thưởng thức vào bữa trưa hoặc bữa tối."
  },
  {
    "id": 12,
    "word": "breakfast",
    "type": "noun",
    "cat": "n",
    "phonetic": "/brˈɛkfʌst/",
    "meaning": "bữa sáng",
    "ex1": "The breakfast is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bữa sáng rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 13,
    "word": "but",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bˈʌt/",
    "meaning": "nhưng",
    "ex1": "Banh beo is light but full of flavor.",
    "ex1_vi": "Bánh bèo nhẹ nhưng đậm hương vị."
  },
  {
    "id": 14,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "People usually eat banh beo with sweet and salty fish sauce.",
    "ex1_vi": "Mọi người thường ăn bánh bèo với nước mắm ngọt mặn."
  },
  {
    "id": 15,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "Cooks also prepare traditional cakes for family meals and celebrations.",
    "ex1_vi": "Người nấu cũng chuẩn bị bánh truyền thống cho bữa ăn và lễ kỷ niệm gia đình."
  },
  {
    "id": 16,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thưởng thức",
    "ex1": "Visitors often enjoy it as a snack while exploring markets and traditional food streets.",
    "ex1_vi": "Du khách thường thưởng thức bánh như một món ăn nhẹ khi khám phá chợ và những con phố ẩm thực truyền thống."
  },
  {
    "id": 17,
    "word": "lunch",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈʌntʃ/",
    "meaning": "bữa trưa",
    "ex1": "The lunch is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bữa trưa rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 18,
    "word": "dinner",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪnɝ/",
    "meaning": "bữa tối",
    "ex1": "The dinner is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bữa tối rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 19,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm",
    "ex1": "To make the sheets, cooks spread rice batter over a hot cloth.",
    "ex1_vi": "Để làm lá bánh, người nấu tráng bột gạo trên một tấm vải nóng."
  },
  {
    "id": 20,
    "word": "cooks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʊks/",
    "meaning": "người nấu",
    "ex1": "After steaming, cooks add dried shrimp, green onion oil, crispy bread, or pork skin on top.",
    "ex1_vi": "Sau khi hấp, người nấu thêm tôm khô, dầu hành xanh, bánh mì giòn hoặc da lợn lên trên."
  },
  {
    "id": 21,
    "word": "spread",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sprˈɛd/",
    "meaning": "tráng; trải",
    "ex1": "Cooks spread the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu tráng; trải chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 22,
    "word": "batter",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈætɝ/",
    "meaning": "bột bánh",
    "ex1": "Cooks spread the batter carefully before steaming the thin layer.",
    "ex1_vi": "Người nấu tráng bột cẩn thận trước khi hấp lớp bánh mỏng."
  },
  {
    "id": 23,
    "word": "over",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ˈoʊvɝ/",
    "meaning": "trên; qua",
    "ex1": "Cooks over the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu trên; qua chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 24,
    "word": "hot",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑt/",
    "meaning": "nóng",
    "ex1": "The finished cake looks hot and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông nóng và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 25,
    "word": "cloth",
    "type": "noun",
    "cat": "n",
    "phonetic": "/klˈɔθ/",
    "meaning": "vải",
    "ex1": "The cloth is important in this traditional Vietnamese cake.",
    "ex1_vi": "Vải rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 26,
    "word": "layer",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈeɪɝ/",
    "meaning": "lớp",
    "ex1": "The thin layer is steamed for a short time.",
    "ex1_vi": "Lớp bột mỏng được hấp trong thời gian ngắn."
  },
  {
    "id": 27,
    "word": "steamed",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/stˈimd/",
    "meaning": "được hấp",
    "ex1": "Banh beo is a small steamed rice cake from central Vietnam.",
    "ex1_vi": "Bánh bèo là một loại bánh gạo hấp nhỏ từ miền Trung Việt Nam."
  },
  {
    "id": 28,
    "word": "short",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɔrt/",
    "meaning": "ngắn",
    "ex1": "The finished cake looks short and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông ngắn và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 29,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "The time is important in this traditional Vietnamese cake.",
    "ex1_vi": "Thời gian rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 30,
    "word": "becomes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌmz/",
    "meaning": "trở nên",
    "ex1": "It becomes smooth, soft, and slightly clear.",
    "ex1_vi": "Nó trở nên mịn, mềm và hơi trong."
  },
  {
    "id": 31,
    "word": "smooth",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈuð/",
    "meaning": "mịn",
    "ex1": "The finished cake looks smooth and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông mịn và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 32,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "The filling usually contains shrimp and pork.",
    "ex1_vi": "Nhân thường có tôm và thịt lợn."
  },
  {
    "id": 33,
    "word": "slightly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/slˈaɪtli/",
    "meaning": "hơi",
    "ex1": "The cake is soft, white, and slightly sticky.",
    "ex1_vi": "Bánh mềm, trắng và hơi dính."
  },
  {
    "id": 34,
    "word": "clear",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈɪr/",
    "meaning": "trong",
    "ex1": "The cooked dough becomes clear and looks attractive.",
    "ex1_vi": "Phần bột đã nấu trở nên trong và trông hấp dẫn."
  },
  {
    "id": 35,
    "word": "filling",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɪlɪŋ/",
    "meaning": "nhân; no bụng",
    "ex1": "The filling usually contains shrimp and pork.",
    "ex1_vi": "Nhân thường có tôm và thịt lợn."
  },
  {
    "id": 36,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "The filling often contains minced pork, mushrooms, and onions.",
    "ex1_vi": "Nhân thường gồm thịt lợn băm, nấm và hành."
  },
  {
    "id": 37,
    "word": "contains",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌntˈeɪnz/",
    "meaning": "chứa",
    "ex1": "The filling often contains minced pork, mushrooms, and onions.",
    "ex1_vi": "Nhân thường gồm thịt lợn băm, nấm và hành."
  },
  {
    "id": 38,
    "word": "minced",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈɪnst/",
    "meaning": "băm nhỏ",
    "ex1": "The finished cake looks minced and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông băm nhỏ và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 39,
    "word": "pork",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɔrk/",
    "meaning": "thịt lợn",
    "ex1": "After steaming, cooks add dried shrimp, green onion oil, crispy bread, or pork skin on top.",
    "ex1_vi": "Sau khi hấp, người nấu thêm tôm khô, dầu hành xanh, bánh mì giòn hoặc da lợn lên trên."
  },
  {
    "id": 40,
    "word": "mushrooms",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌʃrumz/",
    "meaning": "nấm",
    "ex1": "The mushrooms is important in this traditional Vietnamese cake.",
    "ex1_vi": "Nấm rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 41,
    "word": "onions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈʌnjʌnz/",
    "meaning": "hành",
    "ex1": "People eat banh bot loc with fish sauce, chili, and fried onions.",
    "ex1_vi": "Mọi người ăn bánh bột lọc với nước mắm, ớt và hành phi."
  },
  {
    "id": 42,
    "word": "rolls",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈoʊlz/",
    "meaning": "cuốn bánh",
    "ex1": "The rolls are served with fried onions, fresh herbs, sausage, and light fish sauce.",
    "ex1_vi": "Các cuốn bánh được dùng cùng hành phi, rau thơm tươi, chả và nước mắm nhạt."
  },
  {
    "id": 43,
    "word": "served",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɝvd/",
    "meaning": "được phục vụ",
    "ex1": "It is served in tiny bowls or on small plates.",
    "ex1_vi": "Bánh được phục vụ trong những chiếc chén nhỏ hoặc trên đĩa nhỏ."
  },
  {
    "id": 44,
    "word": "fried",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈaɪd/",
    "meaning": "chiên; phi",
    "ex1": "People eat banh bot loc with fish sauce, chili, and fried onions.",
    "ex1_vi": "Mọi người ăn bánh bột lọc với nước mắm, ớt và hành phi."
  },
  {
    "id": 45,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi",
    "ex1": "Many local shops prepare it fresh every morning.",
    "ex1_vi": "Nhiều cửa hàng địa phương làm bánh tươi mỗi sáng."
  },
  {
    "id": 46,
    "word": "herbs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɝbz/",
    "meaning": "rau thơm",
    "ex1": "The rolls are served with fried onions, fresh herbs, sausage, and light fish sauce.",
    "ex1_vi": "Các cuốn bánh được dùng cùng hành phi, rau thơm tươi, chả và nước mắm nhạt."
  },
  {
    "id": 47,
    "word": "sausage",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔsʌdʒ/",
    "meaning": "chả; xúc xích",
    "ex1": "The sausage is important in this traditional Vietnamese cake.",
    "ex1_vi": "Chả; xúc xích rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 48,
    "word": "light",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈaɪt/",
    "meaning": "nhẹ",
    "ex1": "The finished cake looks light and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông nhẹ và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 49,
    "word": "fish",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɪʃ/",
    "meaning": "cá",
    "ex1": "People usually eat banh beo with sweet and salty fish sauce.",
    "ex1_vi": "Mọi người thường ăn bánh bèo với nước mắm ngọt mặn."
  },
  {
    "id": 50,
    "word": "sauce",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔs/",
    "meaning": "nước xốt; nước mắm",
    "ex1": "The sauce is important in this traditional Vietnamese cake.",
    "ex1_vi": "Nước xốt; nước mắm rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 51,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "Banh cuon has a gentle taste and is easy to eat.",
    "ex1_vi": "Bánh cuốn có vị nhẹ nhàng và dễ ăn."
  },
  {
    "id": 52,
    "word": "gentle",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈɛntʌl/",
    "meaning": "nhẹ nhàng",
    "ex1": "The finished cake looks gentle and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông nhẹ nhàng và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 53,
    "word": "taste",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪst/",
    "meaning": "hương vị",
    "ex1": "Its simple ingredients create a special taste.",
    "ex1_vi": "Những nguyên liệu đơn giản tạo nên hương vị đặc biệt."
  },
  {
    "id": 54,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "The finished cake looks easy and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông dễ và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 55,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "Cooks eat the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu ăn chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 56,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "It is not too heavy, so it is suitable for all ages.",
    "ex1_vi": "Món này không quá nặng bụng nên phù hợp với mọi lứa tuổi."
  },
  {
    "id": 57,
    "word": "heavy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛvi/",
    "meaning": "nặng; nặng bụng",
    "ex1": "It is not too heavy, so it is suitable for all ages.",
    "ex1_vi": "Món này không quá nặng bụng nên phù hợp với mọi lứa tuổi."
  },
  {
    "id": 58,
    "word": "so",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/sˈoʊ/",
    "meaning": "vì vậy",
    "ex1": "Families cook together so they prepare traditional Vietnamese cakes.",
    "ex1_vi": "Các gia đình nấu cùng nhau vì vậy họ chuẩn bị những loại bánh Việt Nam truyền thống."
  },
  {
    "id": 59,
    "word": "suitable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈutʌbʌl/",
    "meaning": "phù hợp",
    "ex1": "The finished cake looks suitable and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông phù hợp và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 60,
    "word": "ages",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈeɪdʒʌz/",
    "meaning": "lứa tuổi",
    "ex1": "The ages is important in this traditional Vietnamese cake.",
    "ex1_vi": "Lứa tuổi rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 61,
    "word": "local",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈoʊkʌl/",
    "meaning": "địa phương",
    "ex1": "Many local shops prepare it fresh every morning.",
    "ex1_vi": "Nhiều cửa hàng địa phương làm bánh tươi mỗi sáng."
  },
  {
    "id": 62,
    "word": "shops",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɑps/",
    "meaning": "cửa hàng",
    "ex1": "The shops is important in this traditional Vietnamese cake.",
    "ex1_vi": "Cửa hàng rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 63,
    "word": "prepare",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pripˈɛr/",
    "meaning": "chuẩn bị",
    "ex1": "Cooks prepare the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu chuẩn bị chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 64,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɝi/",
    "meaning": "mỗi",
    "ex1": "Cooks every the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu mỗi chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 65,
    "word": "morning",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈɔrnɪŋ/",
    "meaning": "buổi sáng",
    "ex1": "Families enjoy morning traditional cakes together during special events.",
    "ex1_vi": "Các gia đình thích buổi sáng bánh truyền thống cùng nhau trong các dịp đặc biệt."
  },
  {
    "id": 66,
    "word": "beo",
    "type": "noun",
    "cat": "n",
    "phonetic": "/beʊ/",
    "meaning": "bèo",
    "ex1": "Banh beo is a small steamed rice cake from central Vietnam.",
    "ex1_vi": "Bánh bèo là một loại bánh gạo hấp nhỏ từ miền Trung Việt Nam."
  },
  {
    "id": 67,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "They use a small spoon to take each cake.",
    "ex1_vi": "Họ dùng một chiếc thìa nhỏ để lấy từng chiếc bánh."
  },
  {
    "id": 68,
    "word": "cake",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈeɪk/",
    "meaning": "bánh",
    "ex1": "The cake is soft, white, and slightly sticky.",
    "ex1_vi": "Bánh mềm, trắng và hơi dính."
  },
  {
    "id": 69,
    "word": "central",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɛntrʌl/",
    "meaning": "miền Trung; thuộc miền Trung",
    "ex1": "It is popular in Hue and other central provinces.",
    "ex1_vi": "Bánh phổ biến ở Huế và các tỉnh miền Trung khác."
  },
  {
    "id": 70,
    "word": "vietnam",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/viˌɛtnˈɑm/",
    "meaning": "Việt Nam",
    "ex1": "It is especially famous in Hue and central Vietnam.",
    "ex1_vi": "Bánh đặc biệt nổi tiếng ở Huế và miền Trung Việt Nam."
  },
  {
    "id": 71,
    "word": "tiny",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈaɪni/",
    "meaning": "rất nhỏ",
    "ex1": "It is served in tiny bowls or on small plates.",
    "ex1_vi": "Bánh được phục vụ trong những chiếc chén nhỏ hoặc trên đĩa nhỏ."
  },
  {
    "id": 72,
    "word": "bowls",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈoʊlz/",
    "meaning": "chén; bát",
    "ex1": "The bowls is important in this traditional Vietnamese cake.",
    "ex1_vi": "Chén; bát rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 73,
    "word": "plates",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪts/",
    "meaning": "đĩa",
    "ex1": "The plates is important in this traditional Vietnamese cake.",
    "ex1_vi": "Đĩa rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 74,
    "word": "white",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈaɪt/",
    "meaning": "trắng",
    "ex1": "The finished cake looks white and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông trắng và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 75,
    "word": "sticky",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/stˈɪki/",
    "meaning": "dẻo; nếp",
    "ex1": "The finished cake looks sticky and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông dẻo; nếp và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 76,
    "word": "flour",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈaʊɝ/",
    "meaning": "bột",
    "ex1": "Banh bot loc is a chewy Vietnamese dumpling made from tapioca flour.",
    "ex1_vi": "Bánh bột lọc là một loại bánh dai của Việt Nam được làm từ bột năng."
  },
  {
    "id": 77,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước",
    "ex1": "The water is important in this traditional Vietnamese cake.",
    "ex1_vi": "Nước rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 78,
    "word": "steaming",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈimɪŋ/",
    "meaning": "việc hấp",
    "ex1": "Some cakes are wrapped in banana leaves before steaming, while others are boiled without leaves.",
    "ex1_vi": "Một số bánh được gói trong lá chuối trước khi hấp, trong khi những loại khác được luộc không có lá."
  },
  {
    "id": 79,
    "word": "add",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈæd/",
    "meaning": "thêm",
    "ex1": "Cooks add the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu thêm chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 80,
    "word": "dried",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/drˈaɪd/",
    "meaning": "khô",
    "ex1": "The finished cake looks dried and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông khô và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 81,
    "word": "shrimp",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃrˈɪmp/",
    "meaning": "tôm",
    "ex1": "Many visitors remember its clear cover and orange shrimp.",
    "ex1_vi": "Nhiều du khách nhớ lớp vỏ trong và con tôm màu cam của bánh."
  },
  {
    "id": 82,
    "word": "green",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈin/",
    "meaning": "xanh",
    "ex1": "The finished cake looks green and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông xanh và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 83,
    "word": "onion",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈʌnjʌn/",
    "meaning": "hành",
    "ex1": "The onion is important in this traditional Vietnamese cake.",
    "ex1_vi": "Hành rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 84,
    "word": "oil",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔɪl/",
    "meaning": "dầu",
    "ex1": "The oil is important in this traditional Vietnamese cake.",
    "ex1_vi": "Dầu rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 85,
    "word": "crispy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈɪspi/",
    "meaning": "giòn",
    "ex1": "Banh xeo has a crispy cover and fresh filling.",
    "ex1_vi": "Bánh xèo có lớp vỏ giòn và phần nhân tươi."
  },
  {
    "id": 86,
    "word": "bread",
    "type": "noun",
    "cat": "n",
    "phonetic": "/brˈɛd/",
    "meaning": "bánh mì",
    "ex1": "The bread is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bánh mì rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 87,
    "word": "skin",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪn/",
    "meaning": "da",
    "ex1": "The skin is important in this traditional Vietnamese cake.",
    "ex1_vi": "Da rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 88,
    "word": "top",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɑp/",
    "meaning": "trên cùng",
    "ex1": "The top is important in this traditional Vietnamese cake.",
    "ex1_vi": "Trên cùng rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 89,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "Cooks usually prepare traditional cakes for family meals and celebrations.",
    "ex1_vi": "Người nấu thường chuẩn bị bánh truyền thống cho bữa ăn và lễ kỷ niệm gia đình."
  },
  {
    "id": 90,
    "word": "sweet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/swˈit/",
    "meaning": "ngọt",
    "ex1": "The finished cake looks sweet and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông ngọt và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 91,
    "word": "salty",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɔlti/",
    "meaning": "mặn",
    "ex1": "The outside is soft and chewy, while the inside is salty and rich.",
    "ex1_vi": "Bên ngoài mềm và dai, trong khi phần bên trong mặn và đậm đà."
  },
  {
    "id": 92,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "dùng",
    "ex1": "They use a small spoon to take each cake.",
    "ex1_vi": "Họ dùng một chiếc thìa nhỏ để lấy từng chiếc bánh."
  },
  {
    "id": 93,
    "word": "spoon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈun/",
    "meaning": "thìa",
    "ex1": "The spoon is important in this traditional Vietnamese cake.",
    "ex1_vi": "Thìa rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 94,
    "word": "take",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈeɪk/",
    "meaning": "lấy",
    "ex1": "Cooks take the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu lấy chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 95,
    "word": "toppings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɑpɪŋz/",
    "meaning": "đồ phủ; topping",
    "ex1": "The toppings is important in this traditional Vietnamese cake.",
    "ex1_vi": "Đồ phủ; topping rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 96,
    "word": "create",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪt/",
    "meaning": "tạo ra",
    "ex1": "Its simple ingredients create a special taste.",
    "ex1_vi": "Những nguyên liệu đơn giản tạo nên hương vị đặc biệt."
  },
  {
    "id": 97,
    "word": "interesting",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɪntrʌstɪŋ/",
    "meaning": "thú vị",
    "ex1": "The finished cake looks interesting and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông thú vị và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 98,
    "word": "textures",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛkstʃɝz/",
    "meaning": "kết cấu",
    "ex1": "The textures is important in this traditional Vietnamese cake.",
    "ex1_vi": "Kết cấu rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 99,
    "word": "full",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈʊl/",
    "meaning": "đầy",
    "ex1": "The finished cake looks full and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đầy và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 100,
    "word": "flavor",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝ/",
    "meaning": "hương vị",
    "ex1": "Fresh ingredients create a rich flavor in the finished cake.",
    "ex1_vi": "Nguyên liệu tươi tạo hương vị đậm đà cho chiếc bánh hoàn chỉnh."
  },
  {
    "id": 101,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "It is popular in Hue and other central provinces.",
    "ex1_vi": "Bánh phổ biến ở Huế và các tỉnh miền Trung khác."
  },
  {
    "id": 102,
    "word": "hue",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hweɪ/",
    "meaning": "Huế",
    "ex1": "It is especially famous in Hue and central Vietnam.",
    "ex1_vi": "Bánh đặc biệt nổi tiếng ở Huế và miền Trung Việt Nam."
  },
  {
    "id": 103,
    "word": "other",
    "type": "determiner/adjective",
    "cat": "adj",
    "phonetic": "/ˈʌðɝ/",
    "meaning": "khác",
    "ex1": "Cooks other the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu khác chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 104,
    "word": "provinces",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑvʌnsʌz/",
    "meaning": "tỉnh",
    "ex1": "The provinces is important in this traditional Vietnamese cake.",
    "ex1_vi": "Tỉnh rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 105,
    "word": "visitors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪzɪtɝz/",
    "meaning": "du khách",
    "ex1": "Many visitors remember its clear cover and orange shrimp.",
    "ex1_vi": "Nhiều du khách nhớ lớp vỏ trong và con tôm màu cam của bánh."
  },
  {
    "id": 106,
    "word": "snack",
    "type": "noun",
    "cat": "n",
    "phonetic": "/snˈæk/",
    "meaning": "món ăn nhẹ",
    "ex1": "Visitors often enjoy it as a snack while exploring markets and traditional food streets.",
    "ex1_vi": "Du khách thường thưởng thức bánh như một món ăn nhẹ khi khám phá chợ và những con phố ẩm thực truyền thống."
  },
  {
    "id": 107,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "The outside is soft and chewy, while the inside is salty and rich.",
    "ex1_vi": "Bên ngoài mềm và dai, trong khi phần bên trong mặn và đậm đà."
  },
  {
    "id": 108,
    "word": "exploring",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɪksplˈɔrɪŋ/",
    "meaning": "khám phá",
    "ex1": "Families enjoy exploring traditional cakes together during special events.",
    "ex1_vi": "Các gia đình thích khám phá bánh truyền thống cùng nhau trong các dịp đặc biệt."
  },
  {
    "id": 109,
    "word": "markets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɑrkʌts/",
    "meaning": "chợ",
    "ex1": "The markets is important in this traditional Vietnamese cake.",
    "ex1_vi": "Chợ rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 110,
    "word": "traditional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trʌdˈɪʃʌnʌl/",
    "meaning": "truyền thống",
    "ex1": "Traditional cakes often connect food with Vietnamese family culture.",
    "ex1_vi": "Các loại bánh truyền thống thường kết nối ẩm thực với văn hóa gia đình Việt Nam."
  },
  {
    "id": 111,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thực phẩm",
    "ex1": "The food is important in this traditional Vietnamese cake.",
    "ex1_vi": "Thực phẩm rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 112,
    "word": "streets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/strˈits/",
    "meaning": "đường phố",
    "ex1": "The streets is important in this traditional Vietnamese cake.",
    "ex1_vi": "Đường phố rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 113,
    "word": "bot",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bɔːt/",
    "meaning": "bột",
    "ex1": "Banh bot loc is a chewy Vietnamese dumpling made from tapioca flour.",
    "ex1_vi": "Bánh bột lọc là một loại bánh dai của Việt Nam được làm từ bột năng."
  },
  {
    "id": 114,
    "word": "loc",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lɔːk/",
    "meaning": "lọc",
    "ex1": "The loc is important in this traditional Vietnamese cake.",
    "ex1_vi": "Lọc rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 115,
    "word": "chewy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tʃˈui/",
    "meaning": "dai",
    "ex1": "Tapioca flour gives banh bot loc a chewy texture.",
    "ex1_vi": "Bột năng tạo cho bánh bột lọc kết cấu dai."
  },
  {
    "id": 116,
    "word": "dumpling",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈʌmplɪŋ/",
    "meaning": "bánh bột; bánh dumpling",
    "ex1": "Families enjoy dumpling traditional cakes together during special events.",
    "ex1_vi": "Các gia đình thích bánh bột; bánh dumpling bánh truyền thống cùng nhau trong các dịp đặc biệt."
  },
  {
    "id": 117,
    "word": "tapioca",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌtæpiˈoʊkə/",
    "meaning": "bột năng; sắn",
    "ex1": "The tapioca is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bột năng; sắn rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 118,
    "word": "especially",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌspˈɛʃli/",
    "meaning": "đặc biệt",
    "ex1": "Cooks especially prepare traditional cakes for family meals and celebrations.",
    "ex1_vi": "Người nấu đặc biệt chuẩn bị bánh truyền thống cho bữa ăn và lễ kỷ niệm gia đình."
  },
  {
    "id": 119,
    "word": "famous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈeɪmʌs/",
    "meaning": "nổi tiếng",
    "ex1": "The finished cake looks famous and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông nổi tiếng và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 120,
    "word": "cooked",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʊkt/",
    "meaning": "đã nấu",
    "ex1": "The cooked dough becomes clear and looks attractive.",
    "ex1_vi": "Phần bột đã nấu trở nên trong và trông hấp dẫn."
  },
  {
    "id": 121,
    "word": "dough",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈoʊ/",
    "meaning": "bột nhào",
    "ex1": "The dough is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bột nhào rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 122,
    "word": "looks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈʊks/",
    "meaning": "trông",
    "ex1": "The looks is important in this traditional Vietnamese cake.",
    "ex1_vi": "Trông rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 123,
    "word": "attractive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌtrˈæktɪv/",
    "meaning": "hấp dẫn",
    "ex1": "The finished cake looks attractive and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông hấp dẫn và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 124,
    "word": "cakes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈeɪks/",
    "meaning": "các loại bánh",
    "ex1": "Some cakes are wrapped in banana leaves before steaming, while others are boiled without leaves.",
    "ex1_vi": "Một số bánh được gói trong lá chuối trước khi hấp, trong khi những loại khác được luộc không có lá."
  },
  {
    "id": 125,
    "word": "wrapped",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈæpt/",
    "meaning": "được gói",
    "ex1": "The cake is wrapped carefully in fresh banana leaves.",
    "ex1_vi": "Chiếc bánh được gói cẩn thận trong lá chuối tươi."
  },
  {
    "id": 126,
    "word": "banana",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bʌnˈænʌ/",
    "meaning": "chuối",
    "ex1": "Banana leaves are often used to wrap traditional cakes.",
    "ex1_vi": "Lá chuối thường được dùng để gói các loại bánh truyền thống."
  },
  {
    "id": 127,
    "word": "leaves",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈivz/",
    "meaning": "lá",
    "ex1": "The leaves is important in this traditional Vietnamese cake.",
    "ex1_vi": "Lá rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 128,
    "word": "boiled",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɔɪld/",
    "meaning": "được luộc",
    "ex1": "The cake is boiled carefully before family members enjoy it.",
    "ex1_vi": "Chiếc bánh được được luộc cẩn thận trước khi các thành viên gia đình thưởng thức."
  },
  {
    "id": 129,
    "word": "without",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wɪθˈaʊt/",
    "meaning": "không có",
    "ex1": "The without is important in this traditional Vietnamese cake.",
    "ex1_vi": "Không có rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 130,
    "word": "kinds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈaɪndz/",
    "meaning": "loại",
    "ex1": "The kinds is important in this traditional Vietnamese cake.",
    "ex1_vi": "Loại rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 131,
    "word": "delicious",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dɪlˈɪʃʌs/",
    "meaning": "ngon",
    "ex1": "The finished cake looks delicious and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông ngon và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 132,
    "word": "chili",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪli/",
    "meaning": "ớt",
    "ex1": "The chili is important in this traditional Vietnamese cake.",
    "ex1_vi": "Ớt rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 133,
    "word": "outside",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaʊtsˈaɪd/",
    "meaning": "bên ngoài",
    "ex1": "The outside is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bên ngoài rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 134,
    "word": "inside",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ˌɪnsˈaɪd/",
    "meaning": "bên trong",
    "ex1": "Cooks inside the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu bên trong chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 135,
    "word": "rich",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɪtʃ/",
    "meaning": "đậm đà; béo",
    "ex1": "The finished cake looks rich and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đậm đà; béo và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 136,
    "word": "part",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrt/",
    "meaning": "phần",
    "ex1": "This cake is often served as a snack or part of a family meal.",
    "ex1_vi": "Loại bánh này thường được phục vụ như món ăn nhẹ hoặc một phần của bữa ăn gia đình."
  },
  {
    "id": 137,
    "word": "family",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "This cake is often served as a snack or part of a family meal.",
    "ex1_vi": "Loại bánh này thường được phục vụ như món ăn nhẹ hoặc một phần của bữa ăn gia đình."
  },
  {
    "id": 138,
    "word": "meal",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈil/",
    "meaning": "bữa ăn",
    "ex1": "The meal is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bữa ăn rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 139,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "The finished cake looks simple and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đơn giản và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 140,
    "word": "ingredients",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌɪnɡrˈidiʌnts/",
    "meaning": "nguyên liệu",
    "ex1": "The ingredients is important in this traditional Vietnamese cake.",
    "ex1_vi": "Nguyên liệu rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 141,
    "word": "special",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/spˈɛʃʌl/",
    "meaning": "đặc biệt",
    "ex1": "The finished cake looks special and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đặc biệt và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 142,
    "word": "remember",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪmˈɛmbɝ/",
    "meaning": "nhớ",
    "ex1": "Cooks remember the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu nhớ chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 143,
    "word": "cover",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌvɝ/",
    "meaning": "lớp vỏ; lớp phủ",
    "ex1": "The cover is important in this traditional Vietnamese cake.",
    "ex1_vi": "Lớp vỏ; lớp phủ rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 144,
    "word": "orange",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɔrʌndʒ/",
    "meaning": "màu cam",
    "ex1": "The finished cake looks orange and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông màu cam và có vị dễ chịu khi được phục vụ."
  }
];

const newReadingVocabOrder = [
  "banh",
  "cuon",
  "soft",
  "vietnamese",
  "dish",
  "made",
  "thin",
  "rice",
  "sheets",
  "commonly",
  "eaten",
  "breakfast",
  "but",
  "people",
  "also",
  "enjoy",
  "lunch",
  "dinner",
  "make",
  "cooks",
  "spread",
  "batter",
  "over",
  "hot",
  "cloth",
  "layer",
  "steamed",
  "short",
  "time",
  "becomes",
  "smooth",
  "and",
  "slightly",
  "clear",
  "filling",
  "often",
  "contains",
  "minced",
  "pork",
  "mushrooms",
  "onions",
  "rolls",
  "served",
  "fried",
  "fresh",
  "herbs",
  "sausage",
  "light",
  "fish",
  "sauce",
  "has",
  "gentle",
  "taste",
  "easy",
  "eat",
  "not",
  "heavy",
  "so",
  "suitable",
  "ages",
  "local",
  "shops",
  "prepare",
  "every",
  "morning",
  "beo",
  "small",
  "cake",
  "central",
  "vietnam",
  "tiny",
  "bowls",
  "plates",
  "white",
  "sticky",
  "flour",
  "water",
  "steaming",
  "add",
  "dried",
  "shrimp",
  "green",
  "onion",
  "oil",
  "crispy",
  "bread",
  "skin",
  "top",
  "usually",
  "sweet",
  "salty",
  "use",
  "spoon",
  "take",
  "toppings",
  "create",
  "interesting",
  "textures",
  "full",
  "flavor",
  "popular",
  "hue",
  "other",
  "provinces",
  "visitors",
  "snack",
  "while",
  "exploring",
  "markets",
  "traditional",
  "food",
  "streets",
  "bot",
  "loc",
  "chewy",
  "dumpling",
  "tapioca",
  "especially",
  "famous",
  "cooked",
  "dough",
  "looks",
  "attractive",
  "cakes",
  "wrapped",
  "banana",
  "leaves",
  "boiled",
  "without",
  "kinds",
  "delicious",
  "chili",
  "outside",
  "inside",
  "rich",
  "part",
  "family",
  "meal",
  "simple",
  "ingredients",
  "special",
  "remember",
  "cover",
  "orange"
];
