const lessonVocabularyWords = [
  "banh",
  "khot",
  "small",
  "round",
  "pancake",
  "southern",
  "vietnam",
  "crispy",
  "outside",
  "and",
  "soft",
  "inside",
  "vung",
  "tau",
  "famous",
  "colorful",
  "tasty",
  "dish",
  "batter",
  "made",
  "rice",
  "flour",
  "coconut",
  "milk",
  "turmeric",
  "cooks",
  "pour",
  "hot",
  "molds",
  "shrimp",
  "usually",
  "placed",
  "top",
  "cake",
  "people",
  "eat",
  "lettuce",
  "herbs",
  "pickled",
  "vegetables",
  "wrap",
  "leaf",
  "dip",
  "sweet",
  "fish",
  "sauce",
  "has",
  "pleasant",
  "mix",
  "textures",
  "flavors",
  "best",
  "when",
  "served",
  "families",
  "tourists",
  "often",
  "share",
  "plate",
  "busy",
  "restaurants",
  "street",
  "food",
  "stalls",
  "traditional",
  "sticky",
  "found",
  "parts",
  "triangular",
  "wrapped",
  "banana",
  "leaves",
  "glutinous",
  "cakes",
  "may",
  "have",
  "green",
  "bean",
  "sugar",
  "filling",
  "savory",
  "versions",
  "contain",
  "pork",
  "beans",
  "steamed",
  "dough",
  "becomes",
  "chewy",
  "open",
  "can",
  "smell",
  "aroma",
  "prepared",
  "festivals",
  "family",
  "events",
  "ancestor",
  "ceremonies",
  "size",
  "makes",
  "easy",
  "carry",
  "shows",
  "simple",
  "beauty",
  "vietnamese",
  "culture",
  "bo",
  "airy",
  "texture",
  "holes",
  "look",
  "honeycomb",
  "popular",
  "markets",
  "gatherings",
  "yeast",
  "while",
  "baked",
  "pandan",
  "give",
  "color",
  "tastes",
  "mildly",
  "smells",
  "rich",
  "but",
  "not",
  "heavy",
  "warm",
  "tea",
  "enjoy",
  "children",
  "adults",
  "remember",
  "childhood",
  "remains",
  "familiar",
  "snack",
  "today",
  "da",
  "lon",
  "layer",
  "name",
  "means",
  "pig",
  "skin",
  "does",
  "describes",
  "tapioca",
  "different",
  "flavor",
  "steam",
  "thin",
  "time",
  "add",
  "next",
  "only",
  "first",
  "firm",
  "careful",
  "process",
  "creates",
  "beautiful",
  "lines",
  "fragrant",
  "enjoyable",
  "serve",
  "parties",
  "celebrations",
  "bright",
  "layers",
  "make",
  "attractive"
];

const newVocabData = [
  {
    "id": 1,
    "word": "banh",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bæn/",
    "meaning": "bánh",
    "ex1": "Banh bo tastes mildly sweet and smells pleasant.",
    "ex1_vi": "Bánh bò có vị ngọt nhẹ và mùi thơm dễ chịu."
  },
  {
    "id": 2,
    "word": "khot",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kɔːt/",
    "meaning": "khọt",
    "ex1": "Banh khot is a small round pancake from southern Vietnam.",
    "ex1_vi": "Bánh khọt là một loại bánh kếp tròn nhỏ từ miền Nam Việt Nam."
  },
  {
    "id": 3,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "Cooks pour it into small hot molds.",
    "ex1_vi": "Người nấu đổ bột vào những khuôn nhỏ nóng."
  },
  {
    "id": 4,
    "word": "round",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈaʊnd/",
    "meaning": "tròn",
    "ex1": "Banh khot is a small round pancake from southern Vietnam.",
    "ex1_vi": "Bánh khọt là một loại bánh kếp tròn nhỏ từ miền Nam Việt Nam."
  },
  {
    "id": 5,
    "word": "pancake",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈænkˌeɪk/",
    "meaning": "bánh kếp",
    "ex1": "The pancake is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bánh kếp rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 6,
    "word": "southern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈʌðɝn/",
    "meaning": "miền Nam; thuộc miền Nam",
    "ex1": "The finished cake looks southern and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông miền Nam; thuộc miền Nam và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 7,
    "word": "vietnam",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/viˌɛtnˈɑm/",
    "meaning": "Việt Nam",
    "ex1": "Banh da lon is a colorful steamed layer cake from Vietnam.",
    "ex1_vi": "Bánh da lợn là một loại bánh hấp nhiều lớp đầy màu sắc của Việt Nam."
  },
  {
    "id": 8,
    "word": "crispy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈɪspi/",
    "meaning": "giòn",
    "ex1": "It is crispy outside and soft inside.",
    "ex1_vi": "Bánh giòn bên ngoài và mềm bên trong."
  },
  {
    "id": 9,
    "word": "outside",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaʊtsˈaɪd/",
    "meaning": "bên ngoài",
    "ex1": "It is crispy outside and soft inside.",
    "ex1_vi": "Bánh giòn bên ngoài và mềm bên trong."
  },
  {
    "id": 10,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "It is popular at markets and family gatherings.",
    "ex1_vi": "Bánh phổ biến ở chợ và các buổi họp mặt gia đình."
  },
  {
    "id": 11,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "The cake is steamed until the dough becomes soft and chewy.",
    "ex1_vi": "Bánh được hấp cho đến khi bột trở nên mềm và dai."
  },
  {
    "id": 12,
    "word": "inside",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ˌɪnsˈaɪd/",
    "meaning": "bên trong",
    "ex1": "Small holes inside the cake look like a honeycomb.",
    "ex1_vi": "Những lỗ nhỏ bên trong bánh trông giống tổ ong."
  },
  {
    "id": 13,
    "word": "vung",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vʊŋ/",
    "meaning": "Vũng",
    "ex1": "Vung Tau is famous for this colorful and tasty dish.",
    "ex1_vi": "Vũng Tàu nổi tiếng với món ăn nhiều màu sắc và ngon miệng này."
  },
  {
    "id": 14,
    "word": "tau",
    "type": "noun",
    "cat": "n",
    "phonetic": "/taʊ/",
    "meaning": "Tàu",
    "ex1": "Vung Tau is famous for this colorful and tasty dish.",
    "ex1_vi": "Vũng Tàu nổi tiếng với món ăn nhiều màu sắc và ngon miệng này."
  },
  {
    "id": 15,
    "word": "famous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈeɪmʌs/",
    "meaning": "nổi tiếng",
    "ex1": "The finished cake looks famous and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông nổi tiếng và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 16,
    "word": "colorful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌlɝfʌl/",
    "meaning": "nhiều màu sắc",
    "ex1": "This cake is simple, colorful, and easy to enjoy.",
    "ex1_vi": "Loại bánh này đơn giản, nhiều màu sắc và dễ thưởng thức."
  },
  {
    "id": 17,
    "word": "tasty",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈeɪsti/",
    "meaning": "ngon",
    "ex1": "The finished cake looks tasty and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông ngon và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 18,
    "word": "dish",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪʃ/",
    "meaning": "món ăn",
    "ex1": "The dish is important in this traditional Vietnamese cake.",
    "ex1_vi": "Món ăn rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 19,
    "word": "batter",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈætɝ/",
    "meaning": "bột bánh",
    "ex1": "The batter is made from rice flour, coconut milk, and turmeric.",
    "ex1_vi": "Bột bánh được làm từ bột gạo, nước cốt dừa và nghệ."
  },
  {
    "id": 20,
    "word": "made",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈeɪd/",
    "meaning": "được làm",
    "ex1": "The outside is made from glutinous rice flour.",
    "ex1_vi": "Phần bên ngoài được làm từ bột gạo nếp."
  },
  {
    "id": 21,
    "word": "rice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪs/",
    "meaning": "gạo",
    "ex1": "The outside is made from glutinous rice flour.",
    "ex1_vi": "Phần bên ngoài được làm từ bột gạo nếp."
  },
  {
    "id": 22,
    "word": "flour",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈaʊɝ/",
    "meaning": "bột",
    "ex1": "The batter is made from rice flour, coconut milk, and turmeric.",
    "ex1_vi": "Bột bánh được làm từ bột gạo, nước cốt dừa và nghệ."
  },
  {
    "id": 23,
    "word": "coconut",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈkoʊkənʌt/",
    "meaning": "dừa",
    "ex1": "Sweet cakes may have green bean, coconut, or sugar filling.",
    "ex1_vi": "Bánh ngọt có thể có nhân đậu xanh, dừa hoặc đường."
  },
  {
    "id": 24,
    "word": "milk",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɪlk/",
    "meaning": "sữa; nước cốt",
    "ex1": "The coconut milk makes it rich but not too heavy.",
    "ex1_vi": "Nước cốt dừa làm bánh béo nhưng không quá nặng."
  },
  {
    "id": 25,
    "word": "turmeric",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈtɜːrmərɪk/",
    "meaning": "nghệ",
    "ex1": "Turmeric gives banh xeo its familiar yellow color.",
    "ex1_vi": "Nghệ tạo cho bánh xèo màu vàng quen thuộc."
  },
  {
    "id": 26,
    "word": "cooks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʊks/",
    "meaning": "người nấu",
    "ex1": "Cooks pour it into small hot molds.",
    "ex1_vi": "Người nấu đổ bột vào những khuôn nhỏ nóng."
  },
  {
    "id": 27,
    "word": "pour",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pˈɔr/",
    "meaning": "đổ",
    "ex1": "Cooks pour the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu đổ chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 28,
    "word": "hot",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑt/",
    "meaning": "nóng",
    "ex1": "The finished cake looks hot and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông nóng và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 29,
    "word": "molds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈoʊldz/",
    "meaning": "khuôn",
    "ex1": "The molds is important in this traditional Vietnamese cake.",
    "ex1_vi": "Khuôn rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 30,
    "word": "shrimp",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃrˈɪmp/",
    "meaning": "tôm",
    "ex1": "Savory versions often contain pork, shrimp, or beans.",
    "ex1_vi": "Các phiên bản mặn thường chứa thịt lợn, tôm hoặc đậu."
  },
  {
    "id": 31,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "A shrimp is usually placed on top of each cake.",
    "ex1_vi": "Một con tôm thường được đặt trên mỗi chiếc bánh."
  },
  {
    "id": 32,
    "word": "placed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪst/",
    "meaning": "được đặt",
    "ex1": "A shrimp is usually placed on top of each cake.",
    "ex1_vi": "Một con tôm thường được đặt trên mỗi chiếc bánh."
  },
  {
    "id": 33,
    "word": "top",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɑp/",
    "meaning": "trên cùng",
    "ex1": "The top is important in this traditional Vietnamese cake.",
    "ex1_vi": "Trên cùng rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 34,
    "word": "cake",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈeɪk/",
    "meaning": "bánh",
    "ex1": "Small holes inside the cake look like a honeycomb.",
    "ex1_vi": "Những lỗ nhỏ bên trong bánh trông giống tổ ong."
  },
  {
    "id": 35,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "People often eat it with warm tea.",
    "ex1_vi": "Mọi người thường ăn bánh với trà ấm."
  },
  {
    "id": 36,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "People often eat it with warm tea.",
    "ex1_vi": "Mọi người thường ăn bánh với trà ấm."
  },
  {
    "id": 37,
    "word": "lettuce",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɛtʌs/",
    "meaning": "xà lách",
    "ex1": "People eat banh khot with lettuce, herbs, and pickled vegetables.",
    "ex1_vi": "Mọi người ăn bánh khọt với xà lách, rau thơm và rau củ muối chua."
  },
  {
    "id": 38,
    "word": "herbs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɝbz/",
    "meaning": "rau thơm",
    "ex1": "People eat banh khot with lettuce, herbs, and pickled vegetables.",
    "ex1_vi": "Mọi người ăn bánh khọt với xà lách, rau thơm và rau củ muối chua."
  },
  {
    "id": 39,
    "word": "pickled",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pˈɪkʌld/",
    "meaning": "muối chua",
    "ex1": "Pickled vegetables balance the rich taste of traditional cakes.",
    "ex1_vi": "Rau củ muối chua cân bằng vị đậm đà của các loại bánh truyền thống."
  },
  {
    "id": 40,
    "word": "vegetables",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɛdʒtʌbʌlz/",
    "meaning": "rau củ",
    "ex1": "The vegetables is important in this traditional Vietnamese cake.",
    "ex1_vi": "Rau củ rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 41,
    "word": "wrap",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈæp/",
    "meaning": "gói",
    "ex1": "They wrap the cake in a leaf and dip it into sweet fish sauce.",
    "ex1_vi": "Họ gói bánh trong một chiếc lá và chấm vào nước mắm ngọt."
  },
  {
    "id": 42,
    "word": "leaf",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈif/",
    "meaning": "lá",
    "ex1": "When people open the leaf, they can smell a pleasant banana leaf aroma.",
    "ex1_vi": "Khi mọi người mở lá, họ có thể ngửi thấy mùi thơm dễ chịu của lá chuối."
  },
  {
    "id": 43,
    "word": "dip",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dˈɪp/",
    "meaning": "chấm",
    "ex1": "They wrap the cake in a leaf and dip it into sweet fish sauce.",
    "ex1_vi": "Họ gói bánh trong một chiếc lá và chấm vào nước mắm ngọt."
  },
  {
    "id": 44,
    "word": "sweet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/swˈit/",
    "meaning": "ngọt",
    "ex1": "Banh bo tastes mildly sweet and smells pleasant.",
    "ex1_vi": "Bánh bò có vị ngọt nhẹ và mùi thơm dễ chịu."
  },
  {
    "id": 45,
    "word": "fish",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɪʃ/",
    "meaning": "cá",
    "ex1": "The fish is important in this traditional Vietnamese cake.",
    "ex1_vi": "Cá rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 46,
    "word": "sauce",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔs/",
    "meaning": "nước xốt; nước mắm",
    "ex1": "The sauce is important in this traditional Vietnamese cake.",
    "ex1_vi": "Nước xốt; nước mắm rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 47,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "Each layer has a different color and flavor.",
    "ex1_vi": "Mỗi lớp có màu sắc và hương vị khác nhau."
  },
  {
    "id": 48,
    "word": "pleasant",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/plˈɛzʌnt/",
    "meaning": "dễ chịu",
    "ex1": "Banh khot has a pleasant mix of textures and flavors.",
    "ex1_vi": "Bánh khọt có sự kết hợp dễ chịu giữa nhiều kết cấu và hương vị."
  },
  {
    "id": 49,
    "word": "mix",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɪks/",
    "meaning": "sự kết hợp; trộn",
    "ex1": "Banh khot has a pleasant mix of textures and flavors.",
    "ex1_vi": "Bánh khọt có sự kết hợp dễ chịu giữa nhiều kết cấu và hương vị."
  },
  {
    "id": 50,
    "word": "textures",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛkstʃɝz/",
    "meaning": "kết cấu",
    "ex1": "The textures is important in this traditional Vietnamese cake.",
    "ex1_vi": "Kết cấu rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 51,
    "word": "flavors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝz/",
    "meaning": "hương vị",
    "ex1": "The flavors is important in this traditional Vietnamese cake.",
    "ex1_vi": "Hương vị rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 52,
    "word": "best",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɛst/",
    "meaning": "ngon nhất; tốt nhất",
    "ex1": "The finished cake looks best and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông ngon nhất; tốt nhất và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 53,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "When people open the leaf, they can smell a pleasant banana leaf aroma.",
    "ex1_vi": "Khi mọi người mở lá, họ có thể ngửi thấy mùi thơm dễ chịu của lá chuối."
  },
  {
    "id": 54,
    "word": "served",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɝvd/",
    "meaning": "được phục vụ",
    "ex1": "These cakes are served hot with sweet fish sauce.",
    "ex1_vi": "Những chiếc bánh này được phục vụ nóng cùng nước mắm ngọt."
  },
  {
    "id": 55,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌliz/",
    "meaning": "các gia đình",
    "ex1": "Families and tourists often share a plate at busy restaurants or small street food stalls.",
    "ex1_vi": "Các gia đình và du khách thường cùng chia sẻ một đĩa tại nhà hàng đông khách hoặc các quầy thức ăn đường phố nhỏ."
  },
  {
    "id": 56,
    "word": "tourists",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈʊrʌsts/",
    "meaning": "du khách",
    "ex1": "Families and tourists often share a plate at busy restaurants or small street food stalls.",
    "ex1_vi": "Các gia đình và du khách thường cùng chia sẻ một đĩa tại nhà hàng đông khách hoặc các quầy thức ăn đường phố nhỏ."
  },
  {
    "id": 57,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "Savory versions often contain pork, shrimp, or beans.",
    "ex1_vi": "Các phiên bản mặn thường chứa thịt lợn, tôm hoặc đậu."
  },
  {
    "id": 58,
    "word": "share",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈɛr/",
    "meaning": "chia sẻ",
    "ex1": "Its small size makes it easy to carry and share.",
    "ex1_vi": "Kích thước nhỏ khiến bánh dễ mang theo và chia sẻ."
  },
  {
    "id": 59,
    "word": "plate",
    "type": "noun",
    "cat": "n",
    "phonetic": "/plˈeɪt/",
    "meaning": "đĩa",
    "ex1": "The plate is important in this traditional Vietnamese cake.",
    "ex1_vi": "Đĩa rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 60,
    "word": "busy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bˈɪzi/",
    "meaning": "đông đúc; bận rộn",
    "ex1": "The finished cake looks busy and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đông đúc; bận rộn và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 61,
    "word": "restaurants",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɛstɝˌɑnts/",
    "meaning": "nhà hàng",
    "ex1": "The restaurants is important in this traditional Vietnamese cake.",
    "ex1_vi": "Nhà hàng rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 62,
    "word": "street",
    "type": "noun",
    "cat": "n",
    "phonetic": "/strˈit/",
    "meaning": "đường phố",
    "ex1": "The street is important in this traditional Vietnamese cake.",
    "ex1_vi": "Đường phố rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 63,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thực phẩm",
    "ex1": "It shows the simple beauty of Vietnamese traditional food and family culture.",
    "ex1_vi": "Bánh thể hiện vẻ đẹp giản dị của ẩm thực truyền thống Việt Nam và văn hóa gia đình."
  },
  {
    "id": 64,
    "word": "stalls",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈɔlz/",
    "meaning": "quầy hàng",
    "ex1": "The stalls is important in this traditional Vietnamese cake.",
    "ex1_vi": "Quầy hàng rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 65,
    "word": "traditional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trʌdˈɪʃʌnʌl/",
    "meaning": "truyền thống",
    "ex1": "It shows the simple beauty of Vietnamese traditional food and family culture.",
    "ex1_vi": "Bánh thể hiện vẻ đẹp giản dị của ẩm thực truyền thống Việt Nam và văn hóa gia đình."
  },
  {
    "id": 66,
    "word": "sticky",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/stˈɪki/",
    "meaning": "dẻo; nếp",
    "ex1": "Banh it is a traditional sticky rice cake found in many parts of Vietnam.",
    "ex1_vi": "Bánh ít là một loại bánh nếp truyền thống có ở nhiều nơi tại Việt Nam."
  },
  {
    "id": 67,
    "word": "found",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈaʊnd/",
    "meaning": "được tìm thấy; có ở",
    "ex1": "Banh it is a traditional sticky rice cake found in many parts of Vietnam.",
    "ex1_vi": "Bánh ít là một loại bánh nếp truyền thống có ở nhiều nơi tại Việt Nam."
  },
  {
    "id": 68,
    "word": "parts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrts/",
    "meaning": "vùng; phần",
    "ex1": "The parts is important in this traditional Vietnamese cake.",
    "ex1_vi": "Vùng; phần rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 69,
    "word": "triangular",
    "type": "noun",
    "cat": "n",
    "phonetic": "/traɪˈæŋɡjʌlɝ/",
    "meaning": "hình tam giác",
    "ex1": "It is small, round or triangular, and usually wrapped in banana leaves.",
    "ex1_vi": "Bánh nhỏ, tròn hoặc hình tam giác và thường được gói trong lá chuối."
  },
  {
    "id": 70,
    "word": "wrapped",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈæpt/",
    "meaning": "được gói",
    "ex1": "It is small, round or triangular, and usually wrapped in banana leaves.",
    "ex1_vi": "Bánh nhỏ, tròn hoặc hình tam giác và thường được gói trong lá chuối."
  },
  {
    "id": 71,
    "word": "banana",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bʌnˈænʌ/",
    "meaning": "chuối",
    "ex1": "Banana leaves are often used to wrap traditional cakes.",
    "ex1_vi": "Lá chuối thường được dùng để gói các loại bánh truyền thống."
  },
  {
    "id": 72,
    "word": "leaves",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈivz/",
    "meaning": "lá",
    "ex1": "Pandan leaves may give it a green color.",
    "ex1_vi": "Lá dứa có thể tạo cho bánh màu xanh."
  },
  {
    "id": 73,
    "word": "glutinous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɡluːtənəs/",
    "meaning": "nếp; dẻo",
    "ex1": "The finished cake looks glutinous and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông nếp; dẻo và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 74,
    "word": "cakes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈeɪks/",
    "meaning": "các loại bánh",
    "ex1": "Sweet cakes may have green bean, coconut, or sugar filling.",
    "ex1_vi": "Bánh ngọt có thể có nhân đậu xanh, dừa hoặc đường."
  },
  {
    "id": 75,
    "word": "may",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈeɪ/",
    "meaning": "có thể",
    "ex1": "Pandan leaves may give it a green color.",
    "ex1_vi": "Lá dứa có thể tạo cho bánh màu xanh."
  },
  {
    "id": 76,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có",
    "ex1": "Cooks have the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu có chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 77,
    "word": "green",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈin/",
    "meaning": "xanh",
    "ex1": "The finished cake looks green and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông xanh và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 78,
    "word": "bean",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈin/",
    "meaning": "đậu",
    "ex1": "The bean is important in this traditional Vietnamese cake.",
    "ex1_vi": "Đậu rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 79,
    "word": "sugar",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈʃʊɡər/",
    "meaning": "đường",
    "ex1": "The cake is made from rice flour, sugar, yeast, and coconut milk.",
    "ex1_vi": "Bánh được làm từ bột gạo, đường, men và nước cốt dừa."
  },
  {
    "id": 80,
    "word": "filling",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɪlɪŋ/",
    "meaning": "nhân; no bụng",
    "ex1": "The finished cake looks filling and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông nhân; no bụng và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 81,
    "word": "savory",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈeɪvɝi/",
    "meaning": "mặn; đậm vị",
    "ex1": "The finished cake looks savory and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông mặn; đậm vị và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 82,
    "word": "versions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɝʒʌnz/",
    "meaning": "phiên bản",
    "ex1": "Some versions are steamed, while others are baked.",
    "ex1_vi": "Một số phiên bản được hấp, trong khi những phiên bản khác được nướng."
  },
  {
    "id": 83,
    "word": "contain",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈeɪn/",
    "meaning": "chứa",
    "ex1": "Its name means pig skin cake, but it does not contain pig skin.",
    "ex1_vi": "Tên bánh có nghĩa là bánh da lợn, nhưng bánh không chứa da lợn."
  },
  {
    "id": 84,
    "word": "pork",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɔrk/",
    "meaning": "thịt lợn",
    "ex1": "Pork is a common savory filling in traditional cakes.",
    "ex1_vi": "Thịt lợn là loại nhân mặn phổ biến trong các loại bánh truyền thống."
  },
  {
    "id": 85,
    "word": "beans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈinz/",
    "meaning": "đậu",
    "ex1": "The beans is important in this traditional Vietnamese cake.",
    "ex1_vi": "Đậu rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 86,
    "word": "steamed",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/stˈimd/",
    "meaning": "được hấp",
    "ex1": "Some versions are steamed, while others are baked.",
    "ex1_vi": "Một số phiên bản được hấp, trong khi những phiên bản khác được nướng."
  },
  {
    "id": 87,
    "word": "dough",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈoʊ/",
    "meaning": "bột nhào",
    "ex1": "The cake is steamed until the dough becomes soft and chewy.",
    "ex1_vi": "Bánh được hấp cho đến khi bột trở nên mềm và dai."
  },
  {
    "id": 88,
    "word": "becomes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌmz/",
    "meaning": "trở nên",
    "ex1": "They add the next layer only after the first becomes firm.",
    "ex1_vi": "Họ chỉ thêm lớp tiếp theo sau khi lớp đầu tiên trở nên chắc."
  },
  {
    "id": 89,
    "word": "chewy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tʃˈui/",
    "meaning": "dai",
    "ex1": "Tapioca flour gives banh bot loc a chewy texture.",
    "ex1_vi": "Bột năng tạo cho bánh bột lọc kết cấu dai."
  },
  {
    "id": 90,
    "word": "open",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈoʊpʌn/",
    "meaning": "mở",
    "ex1": "Cooks open the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu mở chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 91,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Cooks can the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu có thể chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 92,
    "word": "smell",
    "type": "verb",
    "cat": "v",
    "phonetic": "/smˈɛl/",
    "meaning": "ngửi; mùi",
    "ex1": "Cooks smell the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu ngửi; mùi chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 93,
    "word": "aroma",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɝˈoʊmʌ/",
    "meaning": "hương thơm",
    "ex1": "The aroma is important in this traditional Vietnamese cake.",
    "ex1_vi": "Hương thơm rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 94,
    "word": "prepared",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pripˈɛrd/",
    "meaning": "được chuẩn bị",
    "ex1": "Banh it is often prepared for festivals, family events, and ancestor ceremonies.",
    "ex1_vi": "Bánh ít thường được chuẩn bị cho lễ hội, sự kiện gia đình và nghi lễ thờ cúng tổ tiên."
  },
  {
    "id": 95,
    "word": "festivals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɛstʌvʌlz/",
    "meaning": "lễ hội",
    "ex1": "Banh it is often prepared for festivals, family events, and ancestor ceremonies.",
    "ex1_vi": "Bánh ít thường được chuẩn bị cho lễ hội, sự kiện gia đình và nghi lễ thờ cúng tổ tiên."
  },
  {
    "id": 96,
    "word": "family",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "It is popular at markets and family gatherings.",
    "ex1_vi": "Bánh phổ biến ở chợ và các buổi họp mặt gia đình."
  },
  {
    "id": 97,
    "word": "events",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪvˈɛnts/",
    "meaning": "sự kiện",
    "ex1": "The events is important in this traditional Vietnamese cake.",
    "ex1_vi": "Sự kiện rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 98,
    "word": "ancestor",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈænsˌɛstɝ/",
    "meaning": "tổ tiên",
    "ex1": "The ancestor is important in this traditional Vietnamese cake.",
    "ex1_vi": "Tổ tiên rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 99,
    "word": "ceremonies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛrʌmˌoʊniz/",
    "meaning": "nghi lễ",
    "ex1": "The ceremonies is important in this traditional Vietnamese cake.",
    "ex1_vi": "Nghi lễ rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 100,
    "word": "size",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaɪz/",
    "meaning": "kích thước",
    "ex1": "Its small size makes it easy to carry and share.",
    "ex1_vi": "Kích thước nhỏ khiến bánh dễ mang theo và chia sẻ."
  },
  {
    "id": 101,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm cho",
    "ex1": "The coconut milk makes it rich but not too heavy.",
    "ex1_vi": "Nước cốt dừa làm bánh béo nhưng không quá nặng."
  },
  {
    "id": 102,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "This cake is simple, colorful, and easy to enjoy.",
    "ex1_vi": "Loại bánh này đơn giản, nhiều màu sắc và dễ thưởng thức."
  },
  {
    "id": 103,
    "word": "carry",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈæri/",
    "meaning": "mang theo",
    "ex1": "Cooks carry the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu mang theo chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 104,
    "word": "shows",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈoʊz/",
    "meaning": "thể hiện",
    "ex1": "This cooking step shows a special result for the cake.",
    "ex1_vi": "Bước nấu này thể hiện một kết quả đặc biệt cho chiếc bánh."
  },
  {
    "id": 105,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "The finished cake looks simple and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đơn giản và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 106,
    "word": "beauty",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bjˈuti/",
    "meaning": "vẻ đẹp",
    "ex1": "The beauty is important in this traditional Vietnamese cake.",
    "ex1_vi": "Vẻ đẹp rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 107,
    "word": "vietnamese",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/viˌɛtnɑmˈis/",
    "meaning": "Việt Nam; người Việt Nam",
    "ex1": "It remains a familiar Vietnamese snack today.",
    "ex1_vi": "Ngày nay bánh vẫn là một món ăn nhẹ Việt Nam quen thuộc."
  },
  {
    "id": 108,
    "word": "culture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌltʃɝ/",
    "meaning": "văn hóa",
    "ex1": "The culture is important in this traditional Vietnamese cake.",
    "ex1_vi": "Văn hóa rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 109,
    "word": "bo",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bɔː/",
    "meaning": "bò",
    "ex1": "Banh bo is a sweet Vietnamese cake with a soft and airy texture.",
    "ex1_vi": "Bánh bò là một loại bánh ngọt Việt Nam có kết cấu mềm và xốp."
  },
  {
    "id": 110,
    "word": "airy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɛri/",
    "meaning": "xốp",
    "ex1": "Banh bo is a sweet Vietnamese cake with a soft and airy texture.",
    "ex1_vi": "Bánh bò là một loại bánh ngọt Việt Nam có kết cấu mềm và xốp."
  },
  {
    "id": 111,
    "word": "texture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛkstʃɝ/",
    "meaning": "kết cấu",
    "ex1": "Children like its soft texture, while adults remember it from childhood.",
    "ex1_vi": "Trẻ em thích kết cấu mềm của bánh, trong khi người lớn nhớ đến nó từ thời thơ ấu."
  },
  {
    "id": 112,
    "word": "holes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊlz/",
    "meaning": "lỗ",
    "ex1": "The holes is important in this traditional Vietnamese cake.",
    "ex1_vi": "Lỗ rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 113,
    "word": "look",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊk/",
    "meaning": "trông",
    "ex1": "Cooks look the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu trông chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 114,
    "word": "honeycomb",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈhʌnikoʊm/",
    "meaning": "tổ ong",
    "ex1": "The honeycomb is important in this traditional Vietnamese cake.",
    "ex1_vi": "Tổ ong rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 115,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "The finished cake looks popular and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông phổ biến và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 116,
    "word": "markets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɑrkʌts/",
    "meaning": "chợ",
    "ex1": "People serve it at family parties, markets, and celebrations.",
    "ex1_vi": "Mọi người phục vụ bánh tại các bữa tiệc gia đình, chợ và lễ kỷ niệm."
  },
  {
    "id": 117,
    "word": "gatherings",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈæðɝɪŋz/",
    "meaning": "buổi họp mặt",
    "ex1": "The gatherings is important in this traditional Vietnamese cake.",
    "ex1_vi": "Buổi họp mặt rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 118,
    "word": "yeast",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈist/",
    "meaning": "men",
    "ex1": "The cake is made from rice flour, sugar, yeast, and coconut milk.",
    "ex1_vi": "Bánh được làm từ bột gạo, đường, men và nước cốt dừa."
  },
  {
    "id": 119,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "Children like its soft texture, while adults remember it from childhood.",
    "ex1_vi": "Trẻ em thích kết cấu mềm của bánh, trong khi người lớn nhớ đến nó từ thời thơ ấu."
  },
  {
    "id": 120,
    "word": "baked",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈeɪkt/",
    "meaning": "được nướng",
    "ex1": "The cake is baked carefully before family members enjoy it.",
    "ex1_vi": "Chiếc bánh được được nướng cẩn thận trước khi các thành viên gia đình thưởng thức."
  },
  {
    "id": 121,
    "word": "pandan",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈpændən/",
    "meaning": "lá dứa",
    "ex1": "Pandan leaves can give sweet cakes a green color.",
    "ex1_vi": "Lá dứa có thể tạo màu xanh cho các loại bánh ngọt."
  },
  {
    "id": 122,
    "word": "give",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪv/",
    "meaning": "cho; tạo",
    "ex1": "Cooks give the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu cho; tạo chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 123,
    "word": "color",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌlɝ/",
    "meaning": "màu sắc",
    "ex1": "Each layer has a different color and flavor.",
    "ex1_vi": "Mỗi lớp có màu sắc và hương vị khác nhau."
  },
  {
    "id": 124,
    "word": "tastes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪsts/",
    "meaning": "có vị",
    "ex1": "The tastes is important in this traditional Vietnamese cake.",
    "ex1_vi": "Có vị rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 125,
    "word": "mildly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/mˈaɪldli/",
    "meaning": "nhẹ",
    "ex1": "Cooks mildly prepare traditional cakes for family meals and celebrations.",
    "ex1_vi": "Người nấu nhẹ chuẩn bị bánh truyền thống cho bữa ăn và lễ kỷ niệm gia đình."
  },
  {
    "id": 126,
    "word": "smells",
    "type": "noun",
    "cat": "n",
    "phonetic": "/smˈɛlz/",
    "meaning": "có mùi",
    "ex1": "The smells is important in this traditional Vietnamese cake.",
    "ex1_vi": "Có mùi rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 127,
    "word": "rich",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɪtʃ/",
    "meaning": "đậm đà; béo",
    "ex1": "The finished cake looks rich and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đậm đà; béo và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 128,
    "word": "but",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bˈʌt/",
    "meaning": "nhưng",
    "ex1": "Its name means pig skin cake, but it does not contain pig skin.",
    "ex1_vi": "Tên bánh có nghĩa là bánh da lợn, nhưng bánh không chứa da lợn."
  },
  {
    "id": 129,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "Cooks not prepare traditional cakes for family meals and celebrations.",
    "ex1_vi": "Người nấu không chuẩn bị bánh truyền thống cho bữa ăn và lễ kỷ niệm gia đình."
  },
  {
    "id": 130,
    "word": "heavy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɛvi/",
    "meaning": "nặng; nặng bụng",
    "ex1": "The finished cake looks heavy and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông nặng; nặng bụng và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 131,
    "word": "warm",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɔrm/",
    "meaning": "ấm áp",
    "ex1": "Cooks warm the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu ấm áp chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 132,
    "word": "tea",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈi/",
    "meaning": "trà",
    "ex1": "Banh da lon is sweet, fragrant, and enjoyable with tea.",
    "ex1_vi": "Bánh da lợn ngọt, thơm và ngon khi dùng với trà."
  },
  {
    "id": 133,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thưởng thức",
    "ex1": "Cooks enjoy the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu thưởng thức chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 134,
    "word": "children",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪldrʌn/",
    "meaning": "trẻ em",
    "ex1": "Its bright colorful layers make it attractive to children and adults.",
    "ex1_vi": "Những lớp màu sắc tươi sáng làm bánh hấp dẫn đối với trẻ em và người lớn."
  },
  {
    "id": 135,
    "word": "adults",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌdˈʌlts/",
    "meaning": "người lớn",
    "ex1": "Its bright colorful layers make it attractive to children and adults.",
    "ex1_vi": "Những lớp màu sắc tươi sáng làm bánh hấp dẫn đối với trẻ em và người lớn."
  },
  {
    "id": 136,
    "word": "remember",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪmˈɛmbɝ/",
    "meaning": "nhớ",
    "ex1": "Cooks remember the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu nhớ chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 137,
    "word": "childhood",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈaɪldhˌʊd/",
    "meaning": "thời thơ ấu",
    "ex1": "The childhood is important in this traditional Vietnamese cake.",
    "ex1_vi": "Thời thơ ấu rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 138,
    "word": "remains",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rɪmˈeɪnz/",
    "meaning": "vẫn còn",
    "ex1": "It remains a familiar Vietnamese snack today.",
    "ex1_vi": "Ngày nay bánh vẫn là một món ăn nhẹ Việt Nam quen thuộc."
  },
  {
    "id": 139,
    "word": "familiar",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fʌmˈɪljɝ/",
    "meaning": "quen thuộc",
    "ex1": "The finished cake looks familiar and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông quen thuộc và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 140,
    "word": "snack",
    "type": "noun",
    "cat": "n",
    "phonetic": "/snˈæk/",
    "meaning": "món ăn nhẹ",
    "ex1": "The snack is important in this traditional Vietnamese cake.",
    "ex1_vi": "Món ăn nhẹ rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 141,
    "word": "today",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌdˈeɪ/",
    "meaning": "ngày nay",
    "ex1": "Cooks today prepare traditional cakes for family meals and celebrations.",
    "ex1_vi": "Người nấu ngày nay chuẩn bị bánh truyền thống cho bữa ăn và lễ kỷ niệm gia đình."
  },
  {
    "id": 142,
    "word": "da",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/dɑː/",
    "meaning": "da (trong tên bánh da lợn)",
    "ex1": "Banh da lon is sweet, fragrant, and enjoyable with tea.",
    "ex1_vi": "Bánh da lợn ngọt, thơm và ngon khi dùng với trà."
  },
  {
    "id": 143,
    "word": "lon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lɔːn/",
    "meaning": "lợn",
    "ex1": "Banh da lon is a colorful steamed layer cake from Vietnam.",
    "ex1_vi": "Bánh da lợn là một loại bánh hấp nhiều lớp đầy màu sắc của Việt Nam."
  },
  {
    "id": 144,
    "word": "layer",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈeɪɝ/",
    "meaning": "lớp",
    "ex1": "Cooks steam one thin layer at a time.",
    "ex1_vi": "Người nấu hấp từng lớp mỏng một."
  },
  {
    "id": 145,
    "word": "name",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈeɪm/",
    "meaning": "tên",
    "ex1": "The name is important in this traditional Vietnamese cake.",
    "ex1_vi": "Tên rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 146,
    "word": "means",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈinz/",
    "meaning": "có nghĩa",
    "ex1": "The means is important in this traditional Vietnamese cake.",
    "ex1_vi": "Có nghĩa rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 147,
    "word": "pig",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɪɡ/",
    "meaning": "lợn",
    "ex1": "The pig is important in this traditional Vietnamese cake.",
    "ex1_vi": "Lợn rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 148,
    "word": "skin",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪn/",
    "meaning": "da",
    "ex1": "The skin is important in this traditional Vietnamese cake.",
    "ex1_vi": "Da rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 149,
    "word": "does",
    "type": "auxiliary verb",
    "cat": "v",
    "phonetic": "/dˈʌz/",
    "meaning": "trợ động từ does",
    "ex1": "This cooking step does a special result for the cake.",
    "ex1_vi": "Bước nấu này trợ động từ does một kết quả đặc biệt cho chiếc bánh."
  },
  {
    "id": 150,
    "word": "describes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪskrˈaɪbz/",
    "meaning": "mô tả",
    "ex1": "The describes is important in this traditional Vietnamese cake.",
    "ex1_vi": "Mô tả rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 151,
    "word": "tapioca",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌtæpiˈoʊkə/",
    "meaning": "bột năng; sắn",
    "ex1": "The tapioca is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bột năng; sắn rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 152,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "The finished cake looks different and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông khác nhau và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 153,
    "word": "flavor",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝ/",
    "meaning": "hương vị",
    "ex1": "Fresh ingredients create a rich flavor in the finished cake.",
    "ex1_vi": "Nguyên liệu tươi tạo hương vị đậm đà cho chiếc bánh hoàn chỉnh."
  },
  {
    "id": 154,
    "word": "steam",
    "type": "verb",
    "cat": "v",
    "phonetic": "/stˈim/",
    "meaning": "hấp",
    "ex1": "Cooks steam one thin layer at a time.",
    "ex1_vi": "Người nấu hấp từng lớp mỏng một."
  },
  {
    "id": 155,
    "word": "thin",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/θˈɪn/",
    "meaning": "mỏng",
    "ex1": "The finished cake looks thin and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông mỏng và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 156,
    "word": "time",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaɪm/",
    "meaning": "thời gian",
    "ex1": "The time is important in this traditional Vietnamese cake.",
    "ex1_vi": "Thời gian rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 157,
    "word": "add",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈæd/",
    "meaning": "thêm",
    "ex1": "They add the next layer only after the first becomes firm.",
    "ex1_vi": "Họ chỉ thêm lớp tiếp theo sau khi lớp đầu tiên trở nên chắc."
  },
  {
    "id": 158,
    "word": "next",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/nˈɛkst/",
    "meaning": "tiếp theo",
    "ex1": "Cooks next the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu tiếp theo chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 159,
    "word": "only",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈoʊnli/",
    "meaning": "chỉ",
    "ex1": "Cooks only prepare traditional cakes for family meals and celebrations.",
    "ex1_vi": "Người nấu chỉ chuẩn bị bánh truyền thống cho bữa ăn và lễ kỷ niệm gia đình."
  },
  {
    "id": 160,
    "word": "first",
    "type": "number/adjective",
    "cat": "adj",
    "phonetic": "/fˈɝst/",
    "meaning": "đầu tiên",
    "ex1": "Cooks first the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu đầu tiên chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 161,
    "word": "firm",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɝm/",
    "meaning": "chắc",
    "ex1": "The finished cake looks firm and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông chắc và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 162,
    "word": "careful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɛrfʌl/",
    "meaning": "cẩn thận",
    "ex1": "The finished cake looks careful and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông cẩn thận và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 163,
    "word": "process",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑsˌɛs/",
    "meaning": "quy trình",
    "ex1": "The process is important in this traditional Vietnamese cake.",
    "ex1_vi": "Quy trình rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 164,
    "word": "creates",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kriˈeɪts/",
    "meaning": "tạo ra",
    "ex1": "The creates is important in this traditional Vietnamese cake.",
    "ex1_vi": "Tạo ra rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 165,
    "word": "beautiful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bjˈutʌfʌl/",
    "meaning": "đẹp",
    "ex1": "The finished cake looks beautiful and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông đẹp và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 166,
    "word": "lines",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈaɪnz/",
    "meaning": "đường; lớp",
    "ex1": "The lines is important in this traditional Vietnamese cake.",
    "ex1_vi": "Đường; lớp rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 167,
    "word": "fragrant",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈeɪɡrʌnt/",
    "meaning": "thơm",
    "ex1": "The finished cake looks fragrant and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông thơm và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 168,
    "word": "enjoyable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɛndʒˈɔɪʌbʌl/",
    "meaning": "thú vị; ngon",
    "ex1": "The finished cake looks enjoyable and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông thú vị; ngon và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 169,
    "word": "serve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈɝv/",
    "meaning": "phục vụ",
    "ex1": "People serve it at family parties, markets, and celebrations.",
    "ex1_vi": "Mọi người phục vụ bánh tại các bữa tiệc gia đình, chợ và lễ kỷ niệm."
  },
  {
    "id": 170,
    "word": "parties",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrtiz/",
    "meaning": "bữa tiệc",
    "ex1": "The parties is important in this traditional Vietnamese cake.",
    "ex1_vi": "Bữa tiệc rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 171,
    "word": "celebrations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˌɛlʌbrˈeɪʃʌnz/",
    "meaning": "lễ kỷ niệm",
    "ex1": "The celebrations is important in this traditional Vietnamese cake.",
    "ex1_vi": "Lễ kỷ niệm rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 172,
    "word": "bright",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/brˈaɪt/",
    "meaning": "tươi sáng",
    "ex1": "The finished cake looks bright and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông tươi sáng và có vị dễ chịu khi được phục vụ."
  },
  {
    "id": 173,
    "word": "layers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈeɪɝz/",
    "meaning": "lớp",
    "ex1": "The layers is important in this traditional Vietnamese cake.",
    "ex1_vi": "Lớp rất quan trọng trong loại bánh truyền thống Việt Nam này."
  },
  {
    "id": 174,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm",
    "ex1": "Cooks make the cake carefully before serving it to families.",
    "ex1_vi": "Người nấu làm chiếc bánh cẩn thận trước khi phục vụ cho gia đình."
  },
  {
    "id": 175,
    "word": "attractive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌtrˈæktɪv/",
    "meaning": "hấp dẫn",
    "ex1": "The finished cake looks attractive and tastes pleasant when served.",
    "ex1_vi": "Chiếc bánh hoàn chỉnh trông hấp dẫn và có vị dễ chịu khi được phục vụ."
  }
];

const newReadingVocabOrder = [
  "banh",
  "khot",
  "small",
  "round",
  "pancake",
  "southern",
  "vietnam",
  "crispy",
  "outside",
  "and",
  "soft",
  "inside",
  "vung",
  "tau",
  "famous",
  "colorful",
  "tasty",
  "dish",
  "batter",
  "made",
  "rice",
  "flour",
  "coconut",
  "milk",
  "turmeric",
  "cooks",
  "pour",
  "hot",
  "molds",
  "shrimp",
  "usually",
  "placed",
  "top",
  "cake",
  "people",
  "eat",
  "lettuce",
  "herbs",
  "pickled",
  "vegetables",
  "wrap",
  "leaf",
  "dip",
  "sweet",
  "fish",
  "sauce",
  "has",
  "pleasant",
  "mix",
  "textures",
  "flavors",
  "best",
  "when",
  "served",
  "families",
  "tourists",
  "often",
  "share",
  "plate",
  "busy",
  "restaurants",
  "street",
  "food",
  "stalls",
  "traditional",
  "sticky",
  "found",
  "parts",
  "triangular",
  "wrapped",
  "banana",
  "leaves",
  "glutinous",
  "cakes",
  "may",
  "have",
  "green",
  "bean",
  "sugar",
  "filling",
  "savory",
  "versions",
  "contain",
  "pork",
  "beans",
  "steamed",
  "dough",
  "becomes",
  "chewy",
  "open",
  "can",
  "smell",
  "aroma",
  "prepared",
  "festivals",
  "family",
  "events",
  "ancestor",
  "ceremonies",
  "size",
  "makes",
  "easy",
  "carry",
  "shows",
  "simple",
  "beauty",
  "vietnamese",
  "culture",
  "bo",
  "airy",
  "texture",
  "holes",
  "look",
  "honeycomb",
  "popular",
  "markets",
  "gatherings",
  "yeast",
  "while",
  "baked",
  "pandan",
  "give",
  "color",
  "tastes",
  "mildly",
  "smells",
  "rich",
  "but",
  "not",
  "heavy",
  "warm",
  "tea",
  "enjoy",
  "children",
  "adults",
  "remember",
  "childhood",
  "remains",
  "familiar",
  "snack",
  "today",
  "da",
  "lon",
  "layer",
  "name",
  "means",
  "pig",
  "skin",
  "does",
  "describes",
  "tapioca",
  "different",
  "flavor",
  "steam",
  "thin",
  "time",
  "add",
  "next",
  "only",
  "first",
  "firm",
  "careful",
  "process",
  "creates",
  "beautiful",
  "lines",
  "fragrant",
  "enjoyable",
  "serve",
  "parties",
  "celebrations",
  "bright",
  "layers",
  "make",
  "attractive"
];
