const lessonVocabularyWords = [
  "durian",
  "sầu",
  "riêng",
  "famous",
  "tropical",
  "fruit",
  "vietnam",
  "has",
  "large",
  "size",
  "hard",
  "shell",
  "and",
  "many",
  "sharp",
  "thorns",
  "inside",
  "yellow",
  "flesh",
  "soft",
  "creamy",
  "rich",
  "flavor",
  "very",
  "strong",
  "smell",
  "some",
  "people",
  "love",
  "while",
  "others",
  "find",
  "difficult",
  "enjoy",
  "vietnamese",
  "eat",
  "fresh",
  "or",
  "use",
  "make",
  "cakes",
  "sweet",
  "soups",
  "ice",
  "cream",
  "sticky",
  "rice",
  "smoothies",
  "often",
  "called",
  "king",
  "fruits",
  "grown",
  "mainly",
  "warm",
  "southern",
  "central",
  "highlands",
  "regions",
  "popular",
  "durians",
  "include",
  "ri6",
  "monthong",
  "harvest",
  "season",
  "lovers",
  "look",
  "forward",
  "enjoying",
  "rambutan",
  "chôm",
  "rambutans",
  "colorful",
  "small",
  "round",
  "red",
  "orange",
  "skin",
  "hairs",
  "unusual",
  "interesting",
  "after",
  "removing",
  "can",
  "see",
  "white",
  "juicy",
  "usually",
  "eaten",
  "but",
  "also",
  "used",
  "drinks",
  "canned",
  "desserts",
  "salads",
  "have",
  "slightly",
  "sour",
  "taste",
  "sold",
  "bunches",
  "local",
  "markets",
  "attractive",
  "appearance",
  "refreshing",
  "children",
  "adults",
  "visitors",
  "mangosteen",
  "măng",
  "cụt",
  "well-loved",
  "thick",
  "dark",
  "purple",
  "divided",
  "several",
  "sections",
  "gentle",
  "open",
  "carefully",
  "juice",
  "not",
  "normally",
  "sometimes",
  "queen",
  "because",
  "beautiful",
  "delicate",
  "short",
  "buy",
  "mangosteens",
  "families",
  "give",
  "gifts"
];

const newVocabData = [
  {
    "id": 1,
    "word": "durian",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈdʊriən/",
    "meaning": "sầu riêng",
    "ex1": "Durian is a famous tropical fruit in Vietnam.",
    "ex1_vi": "Sầu riêng là một loại trái cây nhiệt đới nổi tiếng ở Việt Nam."
  },
  {
    "id": 2,
    "word": "sầu",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sầu/",
    "meaning": "sầu (trong 'sầu riêng')",
    "ex1": "Vietnamese families often enjoy Sầu Riêng during everyday meals and snacks.",
    "ex1_vi": "Các gia đình Việt Nam thường thưởng thức Sầu Riêng trong các bữa ăn và món ăn nhẹ hằng ngày."
  },
  {
    "id": 3,
    "word": "riêng",
    "type": "noun",
    "cat": "n",
    "phonetic": "/riêng/",
    "meaning": "riêng (trong 'sầu riêng')",
    "ex1": "Local markets often sell fresh Sầu Riêng when this fruit is in season.",
    "ex1_vi": "Các chợ địa phương thường bán Sầu Riêng tươi khi loại quả này vào mùa."
  },
  {
    "id": 4,
    "word": "famous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈeɪmʌs/",
    "meaning": "nổi tiếng",
    "ex1": "Durian is a famous tropical fruit in Vietnam.",
    "ex1_vi": "Sầu riêng là một loại trái cây nhiệt đới nổi tiếng ở Việt Nam."
  },
  {
    "id": 5,
    "word": "tropical",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trˈɑpɪkʌl/",
    "meaning": "nhiệt đới",
    "ex1": "Rambutans are colorful tropical fruits grown mainly in southern Vietnam.",
    "ex1_vi": "Chôm chôm là loại trái cây nhiệt đới nhiều màu sắc được trồng chủ yếu ở miền Nam Việt Nam."
  },
  {
    "id": 6,
    "word": "fruit",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈut/",
    "meaning": "trái cây; quả",
    "ex1": "During the harvest season, many fruit lovers look forward to enjoying them.",
    "ex1_vi": "Trong mùa thu hoạch, nhiều người yêu trái cây mong chờ được thưởng thức chúng."
  },
  {
    "id": 7,
    "word": "vietnam",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/viˌɛtnˈɑm/",
    "meaning": "Việt Nam",
    "ex1": "Rambutans are colorful tropical fruits grown mainly in southern Vietnam.",
    "ex1_vi": "Chôm chôm là loại trái cây nhiệt đới nhiều màu sắc được trồng chủ yếu ở miền Nam Việt Nam."
  },
  {
    "id": 8,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "It has thick, dark purple skin and soft white flesh inside.",
    "ex1_vi": "Quả có vỏ dày màu tím sẫm và phần thịt trắng mềm bên trong."
  },
  {
    "id": 9,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒ/",
    "meaning": "lớn",
    "ex1": "It has a large size, a hard shell, and many sharp thorns.",
    "ex1_vi": "Quả có kích thước lớn, vỏ cứng và nhiều gai sắc."
  },
  {
    "id": 10,
    "word": "size",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaɪz/",
    "meaning": "kích thước",
    "ex1": "It has a large size, a hard shell, and many sharp thorns.",
    "ex1_vi": "Quả có kích thước lớn, vỏ cứng và nhiều gai sắc."
  },
  {
    "id": 11,
    "word": "hard",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑrd/",
    "meaning": "cứng",
    "ex1": "It has a large size, a hard shell, and many sharp thorns; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Quả có kích thước lớn, vỏ cứng và nhiều gai sắc; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 12,
    "word": "shell",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɛl/",
    "meaning": "vỏ cứng",
    "ex1": "It has a large size, a hard shell, and many sharp thorns; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Quả có kích thước lớn, vỏ cứng và nhiều gai sắc; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 13,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Inside, the yellow flesh is soft, creamy, and rich in flavor.",
    "ex1_vi": "Bên trong, phần thịt màu vàng mềm, béo mịn và đậm vị."
  },
  {
    "id": 14,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "During the harvest season, many fruit lovers look forward to enjoying them.",
    "ex1_vi": "Trong mùa thu hoạch, nhiều người yêu trái cây mong chờ được thưởng thức chúng."
  },
  {
    "id": 15,
    "word": "sharp",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɑrp/",
    "meaning": "sắc",
    "ex1": "It has a large size, a hard shell, and many sharp thorns; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Quả có kích thước lớn, vỏ cứng và nhiều gai sắc; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 16,
    "word": "thorns",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈɔrnz/",
    "meaning": "gai",
    "ex1": "It has a large size, a hard shell, and many sharp thorns; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Quả có kích thước lớn, vỏ cứng và nhiều gai sắc; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 17,
    "word": "inside",
    "type": "adverb/preposition",
    "cat": "adv",
    "phonetic": "/ˌɪnsˈaɪd/",
    "meaning": "bên trong",
    "ex1": "Inside, the yellow flesh is soft, creamy, and rich in flavor.",
    "ex1_vi": "Bên trong, phần thịt màu vàng mềm, béo mịn và đậm vị."
  },
  {
    "id": 18,
    "word": "yellow",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈɛloʊ/",
    "meaning": "màu vàng",
    "ex1": "They are small and round, with red, yellow, or orange skin.",
    "ex1_vi": "Quả nhỏ và tròn, có vỏ đỏ, vàng hoặc cam."
  },
  {
    "id": 19,
    "word": "flesh",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈɛʃ/",
    "meaning": "thịt quả",
    "ex1": "It has thick, dark purple skin and soft white flesh inside.",
    "ex1_vi": "Quả có vỏ dày màu tím sẫm và phần thịt trắng mềm bên trong."
  },
  {
    "id": 20,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "The soft hairs on the skin make the fruit look unusual and interesting.",
    "ex1_vi": "Những sợi lông mềm trên vỏ làm quả trông khác lạ và thú vị."
  },
  {
    "id": 21,
    "word": "creamy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈimi/",
    "meaning": "béo mịn",
    "ex1": "Inside, the yellow flesh is soft, creamy, and rich in flavor; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Bên trong, phần thịt màu vàng mềm, béo mịn và đậm vị; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 22,
    "word": "rich",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɪtʃ/",
    "meaning": "đậm đà",
    "ex1": "Inside, the yellow flesh is soft, creamy, and rich in flavor; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Bên trong, phần thịt màu vàng mềm, béo mịn và đậm vị; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 23,
    "word": "flavor",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝ/",
    "meaning": "hương vị",
    "ex1": "Their attractive appearance and refreshing flavor make them popular with children, adults, and visitors.",
    "ex1_vi": "Vẻ ngoài hấp dẫn và hương vị sảng khoái khiến chôm chôm được trẻ em, người lớn và du khách yêu thích."
  },
  {
    "id": 24,
    "word": "very",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/vˈɛri/",
    "meaning": "rất",
    "ex1": "Durian has a very strong smell.",
    "ex1_vi": "Sầu riêng có mùi rất mạnh."
  },
  {
    "id": 25,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋ/",
    "meaning": "mạnh",
    "ex1": "Durian has a very strong smell.",
    "ex1_vi": "Sầu riêng có mùi rất mạnh."
  },
  {
    "id": 26,
    "word": "smell",
    "type": "verb",
    "cat": "v",
    "phonetic": "/smˈɛl/",
    "meaning": "mùi",
    "ex1": "Durian has a very strong smell; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Sầu riêng có mùi rất mạnh; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 27,
    "word": "some",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌm/",
    "meaning": "một số",
    "ex1": "Some people love it, while others find it difficult to enjoy.",
    "ex1_vi": "Một số người yêu thích nó, trong khi những người khác thấy khó thưởng thức."
  },
  {
    "id": 28,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "Some people love it, while others find it difficult to enjoy.",
    "ex1_vi": "Một số người yêu thích nó, trong khi những người khác thấy khó thưởng thức."
  },
  {
    "id": 29,
    "word": "love",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʌv/",
    "meaning": "yêu thích",
    "ex1": "Some people love it, while others find it difficult to enjoy; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Một số người yêu thích nó, trong khi những người khác thấy khó thưởng thức; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 30,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "Some people love it, while others find it difficult to enjoy; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Một số người yêu thích nó, trong khi những người khác thấy khó thưởng thức; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 31,
    "word": "others",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈʌðɝz/",
    "meaning": "những người/quả khác",
    "ex1": "Some people love it, while others find it difficult to enjoy; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Một số người yêu thích nó, trong khi những người khác thấy khó thưởng thức; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 32,
    "word": "find",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪnd/",
    "meaning": "thấy; tìm",
    "ex1": "Some people love it, while others find it difficult to enjoy; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Một số người yêu thích nó, trong khi những người khác thấy khó thưởng thức; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 33,
    "word": "difficult",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfʌkʌlt/",
    "meaning": "khó",
    "ex1": "Some people love it, while others find it difficult to enjoy; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Một số người yêu thích nó, trong khi những người khác thấy khó thưởng thức; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 34,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thưởng thức",
    "ex1": "Some people love it, while others find it difficult to enjoy; this fruit remains a familiar part of local food culture.",
    "ex1_vi": "Một số người yêu thích nó, trong khi những người khác thấy khó thưởng thức; loại quả này vẫn là một phần quen thuộc của văn hóa ẩm thực địa phương."
  },
  {
    "id": 35,
    "word": "vietnamese",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/viˌɛtnɑmˈis/",
    "meaning": "thuộc Việt Nam; người Việt Nam",
    "ex1": "Popular Vietnamese durians include Ri6 and Monthong.",
    "ex1_vi": "Các giống sầu riêng Việt Nam phổ biến gồm Ri6 và Monthong."
  },
  {
    "id": 36,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "People usually open the fruit carefully and eat the white sections fresh.",
    "ex1_vi": "Mọi người thường mở quả cẩn thận và ăn các múi trắng tươi."
  },
  {
    "id": 37,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi",
    "ex1": "People usually open the fruit carefully and eat the white sections fresh.",
    "ex1_vi": "Mọi người thường mở quả cẩn thận và ăn các múi trắng tươi."
  },
  {
    "id": 38,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "They are small and round, with red, yellow, or orange skin.",
    "ex1_vi": "Quả nhỏ và tròn, có vỏ đỏ, vàng hoặc cam."
  },
  {
    "id": 39,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "Vietnamese people eat fresh durian or use it to make cakes, sweet soups, ice cream, sticky rice, and smoothies.",
    "ex1_vi": "Người Việt Nam ăn sầu riêng tươi hoặc dùng để làm bánh, chè ngọt, kem, xôi và sinh tố."
  },
  {
    "id": 40,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm",
    "ex1": "The soft hairs on the skin make the fruit look unusual and interesting.",
    "ex1_vi": "Những sợi lông mềm trên vỏ làm quả trông khác lạ và thú vị."
  },
  {
    "id": 41,
    "word": "cakes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈeɪks/",
    "meaning": "bánh",
    "ex1": "Vietnamese people eat fresh durian or use it to make cakes, sweet soups, ice cream, sticky rice, and smoothies.",
    "ex1_vi": "Người Việt Nam ăn sầu riêng tươi hoặc dùng để làm bánh, chè ngọt, kem, xôi và sinh tố."
  },
  {
    "id": 42,
    "word": "sweet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/swˈit/",
    "meaning": "ngọt",
    "ex1": "Rambutans have a sweet and slightly sour taste.",
    "ex1_vi": "Chôm chôm có vị ngọt và hơi chua."
  },
  {
    "id": 43,
    "word": "soups",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈups/",
    "meaning": "các món chè/súp",
    "ex1": "Vietnamese people eat fresh durian or use it to make cakes, sweet soups, ice cream, sticky rice, and smoothies; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Người Việt Nam ăn sầu riêng tươi hoặc dùng để làm bánh, chè ngọt, kem, xôi và sinh tố; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 44,
    "word": "ice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪs/",
    "meaning": "kem; đá",
    "ex1": "Vietnamese people eat fresh durian or use it to make cakes, sweet soups, ice cream, sticky rice, and smoothies; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Người Việt Nam ăn sầu riêng tươi hoặc dùng để làm bánh, chè ngọt, kem, xôi và sinh tố; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 45,
    "word": "cream",
    "type": "noun",
    "cat": "n",
    "phonetic": "/krˈim/",
    "meaning": "kem",
    "ex1": "Vietnamese people eat fresh durian or use it to make cakes, sweet soups, ice cream, sticky rice, and smoothies; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Người Việt Nam ăn sầu riêng tươi hoặc dùng để làm bánh, chè ngọt, kem, xôi và sinh tố; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 46,
    "word": "sticky",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/stˈɪki/",
    "meaning": "dẻo; nếp",
    "ex1": "Vietnamese people eat fresh durian or use it to make cakes, sweet soups, ice cream, sticky rice, and smoothies; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Người Việt Nam ăn sầu riêng tươi hoặc dùng để làm bánh, chè ngọt, kem, xôi và sinh tố; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 47,
    "word": "rice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈaɪs/",
    "meaning": "cơm; gạo",
    "ex1": "Vietnamese people eat fresh durian or use it to make cakes, sweet soups, ice cream, sticky rice, and smoothies; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Người Việt Nam ăn sầu riêng tươi hoặc dùng để làm bánh, chè ngọt, kem, xôi và sinh tố; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 48,
    "word": "smoothies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsmuːðiz/",
    "meaning": "sinh tố",
    "ex1": "Mangosteen can also be used in juice, smoothies, desserts, and fruit salads.",
    "ex1_vi": "Măng cụt cũng có thể được dùng trong nước ép, sinh tố, món tráng miệng và salad trái cây."
  },
  {
    "id": 49,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "Durian is often called the “king of fruits.”",
    "ex1_vi": "Sầu riêng thường được gọi là “vua của các loại trái cây”."
  },
  {
    "id": 50,
    "word": "called",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈɔld/",
    "meaning": "được gọi",
    "ex1": "Durian is often called the “king of fruits.”",
    "ex1_vi": "Sầu riêng thường được gọi là “vua của các loại trái cây”."
  },
  {
    "id": 51,
    "word": "king",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɪŋ/",
    "meaning": "vua",
    "ex1": "Durian is often called the “king of fruits”; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Sầu riêng thường được gọi là “vua của các loại trái cây”; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 52,
    "word": "fruits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈuts/",
    "meaning": "các loại trái cây",
    "ex1": "Mangosteen is sometimes called the “queen of fruits” because of its beautiful appearance and delicate flavor.",
    "ex1_vi": "Măng cụt đôi khi được gọi là “nữ hoàng của các loại trái cây” vì vẻ ngoài đẹp và hương vị tinh tế."
  },
  {
    "id": 53,
    "word": "grown",
    "type": "past participle",
    "cat": "v",
    "phonetic": "/ɡrˈoʊn/",
    "meaning": "được trồng",
    "ex1": "It is grown mainly in warm southern and Central Highlands regions.",
    "ex1_vi": "Nó được trồng chủ yếu ở các vùng ấm phía Nam và Tây Nguyên."
  },
  {
    "id": 54,
    "word": "mainly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/mˈeɪnli/",
    "meaning": "chủ yếu",
    "ex1": "It is grown mainly in warm southern and Central Highlands regions.",
    "ex1_vi": "Nó được trồng chủ yếu ở các vùng ấm phía Nam và Tây Nguyên."
  },
  {
    "id": 55,
    "word": "warm",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈɔrm/",
    "meaning": "ấm",
    "ex1": "It is grown mainly in warm southern and Central Highlands regions; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Nó được trồng chủ yếu ở các vùng ấm phía Nam và Tây Nguyên; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 56,
    "word": "southern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈʌðɝn/",
    "meaning": "phía Nam",
    "ex1": "It is mainly grown in southern Vietnam.",
    "ex1_vi": "Nó chủ yếu được trồng ở miền Nam Việt Nam."
  },
  {
    "id": 57,
    "word": "central",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɛntrʌl/",
    "meaning": "Trung; trung tâm",
    "ex1": "It is grown mainly in warm southern and Central Highlands regions; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Nó được trồng chủ yếu ở các vùng ấm phía Nam và Tây Nguyên; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 58,
    "word": "highlands",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈaɪlʌndz/",
    "meaning": "Tây Nguyên; vùng cao nguyên",
    "ex1": "It is grown mainly in warm southern and Central Highlands regions; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Nó được trồng chủ yếu ở các vùng ấm phía Nam và Tây Nguyên; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 59,
    "word": "regions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈidʒʌnz/",
    "meaning": "các vùng",
    "ex1": "It is grown mainly in warm southern and Central Highlands regions; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Nó được trồng chủ yếu ở các vùng ấm phía Nam và Tây Nguyên; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 60,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "Their attractive appearance and refreshing flavor make them popular with children, adults, and visitors.",
    "ex1_vi": "Vẻ ngoài hấp dẫn và hương vị sảng khoái khiến chôm chôm được trẻ em, người lớn và du khách yêu thích."
  },
  {
    "id": 61,
    "word": "durians",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈdʊriənz/",
    "meaning": "các quả/giống sầu riêng",
    "ex1": "Popular Vietnamese durians include Ri6 and Monthong.",
    "ex1_vi": "Các giống sầu riêng Việt Nam phổ biến gồm Ri6 và Monthong."
  },
  {
    "id": 62,
    "word": "include",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪnklˈud/",
    "meaning": "bao gồm",
    "ex1": "Popular Vietnamese durians include Ri6 and Monthong; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Các giống sầu riêng Việt Nam phổ biến gồm Ri6 và Monthong; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 63,
    "word": "ri6",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ri6/",
    "meaning": "Ri6",
    "ex1": "Popular Vietnamese durians include Ri6 and Monthong; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Các giống sầu riêng Việt Nam phổ biến gồm Ri6 và Monthong; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 64,
    "word": "monthong",
    "type": "noun",
    "cat": "n",
    "phonetic": "/monthong/",
    "meaning": "Monthong",
    "ex1": "Popular Vietnamese durians include Ri6 and Monthong; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Các giống sầu riêng Việt Nam phổ biến gồm Ri6 và Monthong; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 65,
    "word": "harvest",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɑrvʌst/",
    "meaning": "thu hoạch",
    "ex1": "During the harvest season, many fruit lovers look forward to enjoying them; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Trong mùa thu hoạch, nhiều người yêu trái cây mong chờ được thưởng thức chúng; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 66,
    "word": "season",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈizʌn/",
    "meaning": "mùa",
    "ex1": "They are often sold in large bunches at local markets during the fruit season.",
    "ex1_vi": "Chúng thường được bán thành chùm lớn tại các chợ địa phương trong mùa trái cây."
  },
  {
    "id": 67,
    "word": "lovers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈʌvɝz/",
    "meaning": "người yêu thích",
    "ex1": "During the harvest season, many fruit lovers look forward to enjoying them; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Trong mùa thu hoạch, nhiều người yêu trái cây mong chờ được thưởng thức chúng; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 68,
    "word": "look",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊk/",
    "meaning": "mong chờ; nhìn",
    "ex1": "During the harvest season, many fruit lovers look forward to enjoying them; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Trong mùa thu hoạch, nhiều người yêu trái cây mong chờ được thưởng thức chúng; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 69,
    "word": "forward",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/fˈɔrwɝd/",
    "meaning": "mong chờ",
    "ex1": "During the harvest season, many fruit lovers look forward to enjoying them; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Trong mùa thu hoạch, nhiều người yêu trái cây mong chờ được thưởng thức chúng; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 70,
    "word": "enjoying",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪɪŋ/",
    "meaning": "việc thưởng thức",
    "ex1": "During the harvest season, many fruit lovers look forward to enjoying them; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Trong mùa thu hoạch, nhiều người yêu trái cây mong chờ được thưởng thức chúng; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 71,
    "word": "rambutan",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ræmˈbuːtən/",
    "meaning": "chôm chôm",
    "ex1": "Vietnamese families often enjoy rambutan fresh during the local fruit season.",
    "ex1_vi": "Các gia đình Việt Nam thường thưởng thức rambutan tươi trong mùa trái cây địa phương."
  },
  {
    "id": 72,
    "word": "chôm",
    "type": "noun",
    "cat": "n",
    "phonetic": "/chôm/",
    "meaning": "chôm (trong 'chôm chôm')",
    "ex1": "Local markets often sell fresh Chôm Chôm when this fruit is in season.",
    "ex1_vi": "Các chợ địa phương thường bán Chôm Chôm tươi khi loại quả này vào mùa."
  },
  {
    "id": 73,
    "word": "rambutans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ræmˈbuːtənz/",
    "meaning": "chôm chôm",
    "ex1": "Rambutans have a sweet and slightly sour taste.",
    "ex1_vi": "Chôm chôm có vị ngọt và hơi chua."
  },
  {
    "id": 74,
    "word": "colorful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌlɝfʌl/",
    "meaning": "nhiều màu sắc",
    "ex1": "Rambutans are colorful tropical fruits grown mainly in southern Vietnam; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Chôm chôm là loại trái cây nhiệt đới nhiều màu sắc được trồng chủ yếu ở miền Nam Việt Nam; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 75,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "The flesh is divided into several small sections and has a sweet, gentle taste.",
    "ex1_vi": "Phần thịt được chia thành vài múi nhỏ và có vị ngọt dịu."
  },
  {
    "id": 76,
    "word": "round",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈaʊnd/",
    "meaning": "tròn",
    "ex1": "They are small and round, with red, yellow, or orange skin; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Quả nhỏ và tròn, có vỏ đỏ, vàng hoặc cam; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 77,
    "word": "red",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛd/",
    "meaning": "màu đỏ",
    "ex1": "They are small and round, with red, yellow, or orange skin; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Quả nhỏ và tròn, có vỏ đỏ, vàng hoặc cam; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 78,
    "word": "orange",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɔrʌndʒ/",
    "meaning": "màu cam",
    "ex1": "They are small and round, with red, yellow, or orange skin; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Quả nhỏ và tròn, có vỏ đỏ, vàng hoặc cam; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 79,
    "word": "skin",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪn/",
    "meaning": "vỏ",
    "ex1": "After removing the skin, people can see the white, juicy flesh inside.",
    "ex1_vi": "Sau khi bóc vỏ, mọi người có thể thấy phần thịt trắng, mọng nước bên trong."
  },
  {
    "id": 80,
    "word": "hairs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɛrz/",
    "meaning": "lông mềm",
    "ex1": "The soft hairs on the skin make the fruit look unusual and interesting; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Những sợi lông mềm trên vỏ làm quả trông khác lạ và thú vị; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 81,
    "word": "unusual",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌnjˈuʒˌuʌl/",
    "meaning": "khác lạ",
    "ex1": "The soft hairs on the skin make the fruit look unusual and interesting; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Những sợi lông mềm trên vỏ làm quả trông khác lạ và thú vị; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 82,
    "word": "interesting",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɪntrʌstɪŋ/",
    "meaning": "thú vị",
    "ex1": "The soft hairs on the skin make the fruit look unusual and interesting; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Những sợi lông mềm trên vỏ làm quả trông khác lạ và thú vị; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 83,
    "word": "after",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/ˈæftɝ/",
    "meaning": "sau",
    "ex1": "After removing the skin, people can see the white, juicy flesh inside.",
    "ex1_vi": "Sau khi bóc vỏ, mọi người có thể thấy phần thịt trắng, mọng nước bên trong."
  },
  {
    "id": 84,
    "word": "removing",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/rimˈuvɪŋ/",
    "meaning": "việc bóc/bỏ",
    "ex1": "After removing the skin, people can see the white, juicy flesh inside; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Sau khi bóc vỏ, mọi người có thể thấy phần thịt trắng, mọng nước bên trong; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 85,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Mangosteen can also be used in juice, smoothies, desserts, and fruit salads.",
    "ex1_vi": "Măng cụt cũng có thể được dùng trong nước ép, sinh tố, món tráng miệng và salad trái cây."
  },
  {
    "id": 86,
    "word": "see",
    "type": "verb",
    "cat": "v",
    "phonetic": "/sˈi/",
    "meaning": "nhìn thấy",
    "ex1": "After removing the skin, people can see the white, juicy flesh inside; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Sau khi bóc vỏ, mọi người có thể thấy phần thịt trắng, mọng nước bên trong; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 87,
    "word": "white",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈaɪt/",
    "meaning": "màu trắng",
    "ex1": "After removing the skin, people can see the white, juicy flesh inside; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Sau khi bóc vỏ, mọi người có thể thấy phần thịt trắng, mọng nước bên trong; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 88,
    "word": "juicy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈusi/",
    "meaning": "mọng nước",
    "ex1": "After removing the skin, people can see the white, juicy flesh inside; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Sau khi bóc vỏ, mọi người có thể thấy phần thịt trắng, mọng nước bên trong; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 89,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "Rambutans are usually eaten fresh, but they can also be used in sweet drinks, canned fruit, desserts, and fruit salads.",
    "ex1_vi": "Chôm chôm thường được ăn tươi, nhưng cũng có thể được dùng trong đồ uống ngọt, trái cây đóng hộp, món tráng miệng và salad trái cây."
  },
  {
    "id": 90,
    "word": "eaten",
    "type": "past participle",
    "cat": "v",
    "phonetic": "/ˈitʌn/",
    "meaning": "được ăn",
    "ex1": "Its thick skin is not normally eaten.",
    "ex1_vi": "Lớp vỏ dày của quả thường không được ăn."
  },
  {
    "id": 91,
    "word": "but",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bˈʌt/",
    "meaning": "nhưng",
    "ex1": "Rambutans are usually eaten fresh, but they can also be used in sweet drinks, canned fruit, desserts, and fruit salads.",
    "ex1_vi": "Chôm chôm thường được ăn tươi, nhưng cũng có thể được dùng trong đồ uống ngọt, trái cây đóng hộp, món tráng miệng và salad trái cây."
  },
  {
    "id": 92,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "Rambutans are usually eaten fresh, but they can also be used in sweet drinks, canned fruit, desserts, and fruit salads; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Chôm chôm thường được ăn tươi, nhưng cũng có thể được dùng trong đồ uống ngọt, trái cây đóng hộp, món tráng miệng và salad trái cây; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 93,
    "word": "used",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzd/",
    "meaning": "được sử dụng",
    "ex1": "Rambutans are usually eaten fresh, but they can also be used in sweet drinks, canned fruit, desserts, and fruit salads; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Chôm chôm thường được ăn tươi, nhưng cũng có thể được dùng trong đồ uống ngọt, trái cây đóng hộp, món tráng miệng và salad trái cây; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 94,
    "word": "drinks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɪŋks/",
    "meaning": "đồ uống",
    "ex1": "Rambutans are usually eaten fresh, but they can also be used in sweet drinks, canned fruit, desserts, and fruit salads; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Chôm chôm thường được ăn tươi, nhưng cũng có thể được dùng trong đồ uống ngọt, trái cây đóng hộp, món tráng miệng và salad trái cây; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 95,
    "word": "canned",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈænd/",
    "meaning": "đóng hộp",
    "ex1": "Rambutans are usually eaten fresh, but they can also be used in sweet drinks, canned fruit, desserts, and fruit salads; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Chôm chôm thường được ăn tươi, nhưng cũng có thể được dùng trong đồ uống ngọt, trái cây đóng hộp, món tráng miệng và salad trái cây; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 96,
    "word": "desserts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪzˈɝts/",
    "meaning": "món tráng miệng",
    "ex1": "Rambutans are usually eaten fresh, but they can also be used in sweet drinks, canned fruit, desserts, and fruit salads; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Chôm chôm thường được ăn tươi, nhưng cũng có thể được dùng trong đồ uống ngọt, trái cây đóng hộp, món tráng miệng và salad trái cây; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 97,
    "word": "salads",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈælʌdz/",
    "meaning": "salad trái cây",
    "ex1": "Rambutans are usually eaten fresh, but they can also be used in sweet drinks, canned fruit, desserts, and fruit salads; this fruit remains a familiar part of local food culture.",
    "ex1_vi": "Chôm chôm thường được ăn tươi, nhưng cũng có thể được dùng trong đồ uống ngọt, trái cây đóng hộp, món tráng miệng và salad trái cây; loại quả này vẫn là một phần quen thuộc của văn hóa ẩm thực địa phương."
  },
  {
    "id": 98,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có",
    "ex1": "Rambutans have a sweet and slightly sour taste; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Chôm chôm có vị ngọt và hơi chua; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 99,
    "word": "slightly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/slˈaɪtli/",
    "meaning": "hơi",
    "ex1": "Rambutans have a sweet and slightly sour taste; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Chôm chôm có vị ngọt và hơi chua; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 100,
    "word": "sour",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈaʊɝ/",
    "meaning": "chua",
    "ex1": "Rambutans have a sweet and slightly sour taste; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Chôm chôm có vị ngọt và hơi chua; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 101,
    "word": "taste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪst/",
    "meaning": "vị",
    "ex1": "The flesh is divided into several small sections and has a sweet, gentle taste.",
    "ex1_vi": "Phần thịt được chia thành vài múi nhỏ và có vị ngọt dịu."
  },
  {
    "id": 102,
    "word": "sold",
    "type": "past participle",
    "cat": "v",
    "phonetic": "/sˈoʊld/",
    "meaning": "được bán",
    "ex1": "They are often sold in large bunches at local markets during the fruit season.",
    "ex1_vi": "Chúng thường được bán thành chùm lớn tại các chợ địa phương trong mùa trái cây."
  },
  {
    "id": 103,
    "word": "bunches",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʌntʃʌz/",
    "meaning": "chùm",
    "ex1": "They are often sold in large bunches at local markets during the fruit season; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Chúng thường được bán thành chùm lớn tại các chợ địa phương trong mùa trái cây; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 104,
    "word": "local",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈoʊkʌl/",
    "meaning": "địa phương",
    "ex1": "They are often sold in large bunches at local markets during the fruit season; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Chúng thường được bán thành chùm lớn tại các chợ địa phương trong mùa trái cây; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 105,
    "word": "markets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɑrkʌts/",
    "meaning": "chợ",
    "ex1": "They are often sold in large bunches at local markets during the fruit season; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Chúng thường được bán thành chùm lớn tại các chợ địa phương trong mùa trái cây; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 106,
    "word": "attractive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌtrˈæktɪv/",
    "meaning": "hấp dẫn",
    "ex1": "Their attractive appearance and refreshing flavor make them popular with children, adults, and visitors; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Vẻ ngoài hấp dẫn và hương vị sảng khoái khiến chôm chôm được trẻ em, người lớn và du khách yêu thích; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 107,
    "word": "appearance",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌpˈɪrʌns/",
    "meaning": "vẻ ngoài",
    "ex1": "Mangosteen is sometimes called the “queen of fruits” because of its beautiful appearance and delicate flavor.",
    "ex1_vi": "Măng cụt đôi khi được gọi là “nữ hoàng của các loại trái cây” vì vẻ ngoài đẹp và hương vị tinh tế."
  },
  {
    "id": 108,
    "word": "refreshing",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪfrˈɛʃɪŋ/",
    "meaning": "sảng khoái",
    "ex1": "Their attractive appearance and refreshing flavor make them popular with children, adults, and visitors; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Vẻ ngoài hấp dẫn và hương vị sảng khoái khiến chôm chôm được trẻ em, người lớn và du khách yêu thích; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 109,
    "word": "children",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪldrʌn/",
    "meaning": "trẻ em",
    "ex1": "Their attractive appearance and refreshing flavor make them popular with children, adults, and visitors; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Vẻ ngoài hấp dẫn và hương vị sảng khoái khiến chôm chôm được trẻ em, người lớn và du khách yêu thích; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 110,
    "word": "adults",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌdˈʌlts/",
    "meaning": "người lớn",
    "ex1": "Their attractive appearance and refreshing flavor make them popular with children, adults, and visitors; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Vẻ ngoài hấp dẫn và hương vị sảng khoái khiến chôm chôm được trẻ em, người lớn và du khách yêu thích; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 111,
    "word": "visitors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪzɪtɝz/",
    "meaning": "du khách",
    "ex1": "Their attractive appearance and refreshing flavor make them popular with children, adults, and visitors; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Vẻ ngoài hấp dẫn và hương vị sảng khoái khiến chôm chôm được trẻ em, người lớn và du khách yêu thích; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 112,
    "word": "mangosteen",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈæŋɡoʊstˌin/",
    "meaning": "măng cụt",
    "ex1": "Mangosteen is a well-loved tropical fruit in Vietnam.",
    "ex1_vi": "Măng cụt là một loại trái cây nhiệt đới được yêu thích ở Việt Nam."
  },
  {
    "id": 113,
    "word": "măng",
    "type": "noun",
    "cat": "n",
    "phonetic": "/măng/",
    "meaning": "măng (trong 'măng cụt')",
    "ex1": "Vietnamese families often enjoy Măng Cụt during everyday meals and snacks.",
    "ex1_vi": "Các gia đình Việt Nam thường thưởng thức Măng Cụt trong các bữa ăn và món ăn nhẹ hằng ngày."
  },
  {
    "id": 114,
    "word": "cụt",
    "type": "noun",
    "cat": "n",
    "phonetic": "/cụt/",
    "meaning": "cụt (trong 'măng cụt')",
    "ex1": "Local markets often sell fresh Măng Cụt when this fruit is in season.",
    "ex1_vi": "Các chợ địa phương thường bán Măng Cụt tươi khi loại quả này vào mùa."
  },
  {
    "id": 115,
    "word": "well-loved",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌwel ˈlʌvd/",
    "meaning": "được yêu thích",
    "ex1": "Mangosteen is a well-loved tropical fruit in Vietnam.",
    "ex1_vi": "Măng cụt là một loại trái cây nhiệt đới được yêu thích ở Việt Nam."
  },
  {
    "id": 116,
    "word": "thick",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/θˈɪk/",
    "meaning": "dày",
    "ex1": "Its thick skin is not normally eaten.",
    "ex1_vi": "Lớp vỏ dày của quả thường không được ăn."
  },
  {
    "id": 117,
    "word": "dark",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɑrk/",
    "meaning": "sẫm",
    "ex1": "It has thick, dark purple skin and soft white flesh inside; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Quả có vỏ dày màu tím sẫm và phần thịt trắng mềm bên trong; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 118,
    "word": "purple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɝpʌl/",
    "meaning": "màu tím",
    "ex1": "It has thick, dark purple skin and soft white flesh inside; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Quả có vỏ dày màu tím sẫm và phần thịt trắng mềm bên trong; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 119,
    "word": "divided",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dɪvˈaɪdɪd/",
    "meaning": "được chia",
    "ex1": "The flesh is divided into several small sections and has a sweet, gentle taste; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Phần thịt được chia thành vài múi nhỏ và có vị ngọt dịu; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 120,
    "word": "several",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈɛvrʌl/",
    "meaning": "một số",
    "ex1": "The flesh is divided into several small sections and has a sweet, gentle taste; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Phần thịt được chia thành vài múi nhỏ và có vị ngọt dịu; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 121,
    "word": "sections",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛkʃʌnz/",
    "meaning": "múi; phần",
    "ex1": "The flesh is divided into several small sections and has a sweet, gentle taste; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Phần thịt được chia thành vài múi nhỏ và có vị ngọt dịu; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 122,
    "word": "gentle",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈɛntʌl/",
    "meaning": "dịu",
    "ex1": "The flesh is divided into several small sections and has a sweet, gentle taste; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Phần thịt được chia thành vài múi nhỏ và có vị ngọt dịu; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 123,
    "word": "open",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈoʊpʌn/",
    "meaning": "mở",
    "ex1": "People usually open the fruit carefully and eat the white sections fresh; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Mọi người thường mở quả cẩn thận và ăn các múi trắng tươi; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 124,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "People usually open the fruit carefully and eat the white sections fresh; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Mọi người thường mở quả cẩn thận và ăn các múi trắng tươi; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 125,
    "word": "juice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈus/",
    "meaning": "nước ép",
    "ex1": "Mangosteen can also be used in juice, smoothies, desserts, and fruit salads; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Măng cụt cũng có thể được dùng trong nước ép, sinh tố, món tráng miệng và salad trái cây; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 126,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "Its thick skin is not normally eaten; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Lớp vỏ dày của quả thường không được ăn; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 127,
    "word": "normally",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɔrmʌli/",
    "meaning": "thường",
    "ex1": "Its thick skin is not normally eaten; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Lớp vỏ dày của quả thường không được ăn; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 128,
    "word": "sometimes",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sʌmtˈaɪmz/",
    "meaning": "đôi khi",
    "ex1": "Mangosteen is sometimes called the “queen of fruits” because of its beautiful appearance and delicate flavor; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Măng cụt đôi khi được gọi là “nữ hoàng của các loại trái cây” vì vẻ ngoài đẹp và hương vị tinh tế; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 129,
    "word": "queen",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kwˈin/",
    "meaning": "nữ hoàng",
    "ex1": "Mangosteen is sometimes called the “queen of fruits” because of its beautiful appearance and delicate flavor; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Măng cụt đôi khi được gọi là “nữ hoàng của các loại trái cây” vì vẻ ngoài đẹp và hương vị tinh tế; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 130,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "Mangosteen is sometimes called the “queen of fruits” because of its beautiful appearance and delicate flavor; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Măng cụt đôi khi được gọi là “nữ hoàng của các loại trái cây” vì vẻ ngoài đẹp và hương vị tinh tế; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 131,
    "word": "beautiful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bjˈutʌfʌl/",
    "meaning": "đẹp",
    "ex1": "Mangosteen is sometimes called the “queen of fruits” because of its beautiful appearance and delicate flavor; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Măng cụt đôi khi được gọi là “nữ hoàng của các loại trái cây” vì vẻ ngoài đẹp và hương vị tinh tế; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 132,
    "word": "delicate",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɛlʌkʌt/",
    "meaning": "tinh tế",
    "ex1": "Mangosteen is sometimes called the “queen of fruits” because of its beautiful appearance and delicate flavor; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Măng cụt đôi khi được gọi là “nữ hoàng của các loại trái cây” vì vẻ ngoài đẹp và hương vị tinh tế; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 133,
    "word": "short",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɔrt/",
    "meaning": "ngắn",
    "ex1": "During its short season, many people buy mangosteens for their families or give them as gifts.",
    "ex1_vi": "Trong mùa ngắn, nhiều người mua măng cụt cho gia đình hoặc tặng làm quà."
  },
  {
    "id": 134,
    "word": "buy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈaɪ/",
    "meaning": "mua",
    "ex1": "During its short season, many people buy mangosteens for their families or give them as gifts.",
    "ex1_vi": "Trong mùa ngắn, nhiều người mua măng cụt cho gia đình hoặc tặng làm quà."
  },
  {
    "id": 135,
    "word": "mangosteens",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈæŋɡoʊstˌinz/",
    "meaning": "măng cụt",
    "ex1": "During its short season, many people buy mangosteens for their families or give them as gifts; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Trong mùa ngắn, nhiều người mua măng cụt cho gia đình hoặc tặng làm quà; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 136,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌliz/",
    "meaning": "các gia đình",
    "ex1": "During its short season, many people buy mangosteens for their families or give them as gifts; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Trong mùa ngắn, nhiều người mua măng cụt cho gia đình hoặc tặng làm quà; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 137,
    "word": "give",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪv/",
    "meaning": "tặng; cho",
    "ex1": "During its short season, many people buy mangosteens for their families or give them as gifts; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Trong mùa ngắn, nhiều người mua măng cụt cho gia đình hoặc tặng làm quà; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 138,
    "word": "gifts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɪfts/",
    "meaning": "quà",
    "ex1": "During its short season, many people buy mangosteens for their families or give them as gifts; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Trong mùa ngắn, nhiều người mua măng cụt cho gia đình hoặc tặng làm quà; những đặc điểm này khiến loại quả dễ nhận biết."
  }
];

const newReadingVocabOrder = [
  "durian",
  "sầu",
  "riêng",
  "famous",
  "tropical",
  "fruit",
  "vietnam",
  "has",
  "large",
  "size",
  "hard",
  "shell",
  "and",
  "many",
  "sharp",
  "thorns",
  "inside",
  "yellow",
  "flesh",
  "soft",
  "creamy",
  "rich",
  "flavor",
  "very",
  "strong",
  "smell",
  "some",
  "people",
  "love",
  "while",
  "others",
  "find",
  "difficult",
  "enjoy",
  "vietnamese",
  "eat",
  "fresh",
  "or",
  "use",
  "make",
  "cakes",
  "sweet",
  "soups",
  "ice",
  "cream",
  "sticky",
  "rice",
  "smoothies",
  "often",
  "called",
  "king",
  "fruits",
  "grown",
  "mainly",
  "warm",
  "southern",
  "central",
  "highlands",
  "regions",
  "popular",
  "durians",
  "include",
  "ri6",
  "monthong",
  "harvest",
  "season",
  "lovers",
  "look",
  "forward",
  "enjoying",
  "rambutan",
  "chôm",
  "rambutans",
  "colorful",
  "small",
  "round",
  "red",
  "orange",
  "skin",
  "hairs",
  "unusual",
  "interesting",
  "after",
  "removing",
  "can",
  "see",
  "white",
  "juicy",
  "usually",
  "eaten",
  "but",
  "also",
  "used",
  "drinks",
  "canned",
  "desserts",
  "salads",
  "have",
  "slightly",
  "sour",
  "taste",
  "sold",
  "bunches",
  "local",
  "markets",
  "attractive",
  "appearance",
  "refreshing",
  "children",
  "adults",
  "visitors",
  "mangosteen",
  "măng",
  "cụt",
  "well-loved",
  "thick",
  "dark",
  "purple",
  "divided",
  "several",
  "sections",
  "gentle",
  "open",
  "carefully",
  "juice",
  "not",
  "normally",
  "sometimes",
  "queen",
  "because",
  "beautiful",
  "delicate",
  "short",
  "buy",
  "mangosteens",
  "families",
  "give",
  "gifts"
];
