const lessonVocabularyWords = [
  "longan",
  "nhãn",
  "longans",
  "small",
  "round",
  "fruits",
  "grow",
  "bunches",
  "have",
  "thin",
  "brown",
  "skin",
  "and",
  "clear",
  "white",
  "flesh",
  "dark",
  "seed",
  "can",
  "seen",
  "so",
  "fruit",
  "name",
  "means",
  "dragon",
  "eye",
  "fresh",
  "sweet",
  "smell",
  "juicy",
  "taste",
  "people",
  "eat",
  "directly",
  "after",
  "removing",
  "also",
  "dried",
  "or",
  "used",
  "tea",
  "soup",
  "desserts",
  "traditional",
  "dishes",
  "grown",
  "several",
  "parts",
  "vietnam",
  "especially",
  "hung",
  "yen",
  "mekong",
  "delta",
  "famous",
  "sweetness",
  "thick",
  "popular",
  "summer",
  "family",
  "celebrations",
  "lychee",
  "vải",
  "thiều",
  "lychees",
  "rough",
  "red",
  "pink",
  "inside",
  "strong",
  "refreshing",
  "usually",
  "peel",
  "canned",
  "make",
  "juice",
  "jelly",
  "cakes",
  "cold",
  "drinks",
  "enjoyable",
  "hot",
  "days",
  "vietnamese",
  "areas",
  "such",
  "luc",
  "ngan",
  "thanh",
  "ha",
  "harvest",
  "season",
  "farmers",
  "collect",
  "large",
  "amounts",
  "enjoyed",
  "locally",
  "exported",
  "many",
  "other",
  "countries",
  "star",
  "apple",
  "vú",
  "sữa",
  "special",
  "tropical",
  "southern",
  "has",
  "smooth",
  "green",
  "purple",
  "when",
  "cut",
  "across",
  "middle",
  "sections",
  "form",
  "shape",
  "looks",
  "like",
  "soft",
  "milky",
  "often",
  "gently",
  "press",
  "before",
  "cutting",
  "open",
  "eating",
  "spoon",
  "smoothies",
  "chilled",
  "one",
  "variety",
  "lo",
  "ren",
  "tien",
  "giang",
  "pleasant",
  "creamy",
  "texture",
  "connected",
  "well-known",
  "story",
  "about",
  "mother",
  "love",
  "custard",
  "na",
  "mãng",
  "cầu",
  "ta",
  "found",
  "northern",
  "call",
  "while",
  "covered",
  "rounded",
  "ripe",
  "becomes",
  "fragrant",
  "hand",
  "seeds",
  "removed",
  "not",
  "eaten",
  "chi",
  "lang",
  "son",
  "province",
  "trees",
  "hills",
  "rocky",
  "land",
  "because",
  "natural"
];

const newVocabData = [
  {
    "id": 1,
    "word": "longan",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɑŋɡʌn/",
    "meaning": "nhãn",
    "ex1": "Hung Yen longan is famous for its sweetness and thick flesh.",
    "ex1_vi": "Nhãn Hưng Yên nổi tiếng vì độ ngọt và phần thịt dày."
  },
  {
    "id": 2,
    "word": "nhãn",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nhãn/",
    "meaning": "nhãn",
    "ex1": "Vietnamese families often enjoy Nhãn during everyday meals and snacks.",
    "ex1_vi": "Các gia đình Việt Nam thường thưởng thức Nhãn trong các bữa ăn và món ăn nhẹ hằng ngày."
  },
  {
    "id": 3,
    "word": "longans",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈlɑːŋɡənz/",
    "meaning": "nhãn",
    "ex1": "Longans are small, round fruits that grow in bunches.",
    "ex1_vi": "Nhãn là loại trái cây nhỏ, tròn mọc thành chùm."
  },
  {
    "id": 4,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "Lychees are small summer fruits with rough red or pink skin.",
    "ex1_vi": "Vải là loại trái cây mùa hè nhỏ có vỏ sần sùi màu đỏ hoặc hồng."
  },
  {
    "id": 5,
    "word": "round",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈaʊnd/",
    "meaning": "tròn",
    "ex1": "Longans are small, round fruits that grow in bunches.",
    "ex1_vi": "Nhãn là loại trái cây nhỏ, tròn mọc thành chùm."
  },
  {
    "id": 6,
    "word": "fruits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈuts/",
    "meaning": "các loại trái cây",
    "ex1": "Lychees are small summer fruits with rough red or pink skin.",
    "ex1_vi": "Vải là loại trái cây mùa hè nhỏ có vỏ sần sùi màu đỏ hoặc hồng."
  },
  {
    "id": 7,
    "word": "grow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡrˈoʊ/",
    "meaning": "mọc; trồng",
    "ex1": "Farmers often grow the trees on hills and rocky land.",
    "ex1_vi": "Nông dân thường trồng cây trên đồi và đất đá."
  },
  {
    "id": 8,
    "word": "bunches",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈʌntʃʌz/",
    "meaning": "chùm",
    "ex1": "Longans are small, round fruits that grow in bunches; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Nhãn là loại trái cây nhỏ, tròn mọc thành chùm; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 9,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có",
    "ex1": "Inside, they have white, juicy flesh and a dark brown seed.",
    "ex1_vi": "Bên trong, quả có thịt trắng mọng nước và một hạt nâu sẫm."
  },
  {
    "id": 10,
    "word": "thin",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/θˈɪn/",
    "meaning": "mỏng",
    "ex1": "They have thin brown skin and clear white flesh.",
    "ex1_vi": "Quả có vỏ nâu mỏng và thịt trắng trong."
  },
  {
    "id": 11,
    "word": "brown",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/brˈaʊn/",
    "meaning": "màu nâu",
    "ex1": "Inside, they have white, juicy flesh and a dark brown seed.",
    "ex1_vi": "Bên trong, quả có thịt trắng mọng nước và một hạt nâu sẫm."
  },
  {
    "id": 12,
    "word": "skin",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪn/",
    "meaning": "vỏ",
    "ex1": "They have thin brown skin and clear white flesh.",
    "ex1_vi": "Quả có vỏ nâu mỏng và thịt trắng trong."
  },
  {
    "id": 13,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Hung Yen longan is famous for its sweetness and thick flesh.",
    "ex1_vi": "Nhãn Hưng Yên nổi tiếng vì độ ngọt và phần thịt dày."
  },
  {
    "id": 14,
    "word": "clear",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈɪr/",
    "meaning": "trong",
    "ex1": "They have thin brown skin and clear white flesh; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Quả có vỏ nâu mỏng và thịt trắng trong; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 15,
    "word": "white",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈaɪt/",
    "meaning": "màu trắng",
    "ex1": "When ripe, the white flesh becomes soft, sweet, and fragrant.",
    "ex1_vi": "Khi chín, phần thịt trắng trở nên mềm, ngọt và thơm."
  },
  {
    "id": 16,
    "word": "flesh",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈɛʃ/",
    "meaning": "thịt quả",
    "ex1": "When ripe, the white flesh becomes soft, sweet, and fragrant.",
    "ex1_vi": "Khi chín, phần thịt trắng trở nên mềm, ngọt và thơm."
  },
  {
    "id": 17,
    "word": "dark",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɑrk/",
    "meaning": "sẫm",
    "ex1": "The dark seeds inside are removed and not eaten.",
    "ex1_vi": "Những hạt sẫm màu bên trong được bỏ ra và không ăn."
  },
  {
    "id": 18,
    "word": "seed",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈid/",
    "meaning": "hạt",
    "ex1": "A dark seed can be seen through the flesh, so the fruit’s name means “dragon’s eye.”",
    "ex1_vi": "Có thể nhìn thấy hạt sẫm màu qua phần thịt, vì vậy tên của quả có nghĩa là “mắt rồng”."
  },
  {
    "id": 19,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Star apple can also be used in smoothies and chilled desserts.",
    "ex1_vi": "Vú sữa cũng có thể được dùng trong sinh tố và món tráng miệng lạnh."
  },
  {
    "id": 20,
    "word": "seen",
    "type": "past participle",
    "cat": "v",
    "phonetic": "/sˈin/",
    "meaning": "được nhìn thấy",
    "ex1": "A dark seed can be seen through the flesh, so the fruit’s name means “dragon’s eye.”",
    "ex1_vi": "Có thể nhìn thấy hạt sẫm màu qua phần thịt, vì vậy tên của quả có nghĩa là “mắt rồng”."
  },
  {
    "id": 21,
    "word": "so",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/sˈoʊ/",
    "meaning": "vì vậy; nên",
    "ex1": "A dark seed can be seen through the flesh, so the fruit’s name means “dragon’s eye”; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Có thể nhìn thấy hạt sẫm màu qua phần thịt, vì vậy tên của quả có nghĩa là “mắt rồng”; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 22,
    "word": "fruit",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈut/",
    "meaning": "trái cây; quả",
    "ex1": "Star apple is a special tropical fruit grown in southern Vietnam.",
    "ex1_vi": "Vú sữa là một loại trái cây nhiệt đới đặc biệt được trồng ở miền Nam Việt Nam."
  },
  {
    "id": 23,
    "word": "name",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈeɪm/",
    "meaning": "tên",
    "ex1": "Its Vietnamese name, vú sữa, is connected with a well-known story about a mother’s love.",
    "ex1_vi": "Tên tiếng Việt “vú sữa” gắn với một câu chuyện nổi tiếng về tình yêu của người mẹ."
  },
  {
    "id": 24,
    "word": "means",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈinz/",
    "meaning": "có nghĩa",
    "ex1": "A dark seed can be seen through the flesh, so the fruit’s name means “dragon’s eye”; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Có thể nhìn thấy hạt sẫm màu qua phần thịt, vì vậy tên của quả có nghĩa là “mắt rồng”; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 25,
    "word": "dragon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈæɡʌn/",
    "meaning": "rồng",
    "ex1": "A dark seed can be seen through the flesh, so the fruit’s name means “dragon’s eye”; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Có thể nhìn thấy hạt sẫm màu qua phần thịt, vì vậy tên của quả có nghĩa là “mắt rồng”; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 26,
    "word": "eye",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪ/",
    "meaning": "mắt",
    "ex1": "A dark seed can be seen through the flesh, so the fruit’s name means “dragon’s eye”; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Có thể nhìn thấy hạt sẫm màu qua phần thịt, vì vậy tên của quả có nghĩa là “mắt rồng”; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 27,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi",
    "ex1": "People usually open the fruit by hand and eat the flesh fresh.",
    "ex1_vi": "Mọi người thường dùng tay mở quả và ăn phần thịt tươi."
  },
  {
    "id": 28,
    "word": "sweet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/swˈit/",
    "meaning": "ngọt",
    "ex1": "Lychees have a strong sweet smell and a refreshing taste.",
    "ex1_vi": "Vải có mùi ngọt mạnh và vị sảng khoái."
  },
  {
    "id": 29,
    "word": "smell",
    "type": "verb",
    "cat": "v",
    "phonetic": "/smˈɛl/",
    "meaning": "mùi",
    "ex1": "Lychees have a strong sweet smell and a refreshing taste.",
    "ex1_vi": "Vải có mùi ngọt mạnh và vị sảng khoái."
  },
  {
    "id": 30,
    "word": "juicy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈusi/",
    "meaning": "mọng nước",
    "ex1": "Fresh longans have a sweet smell and juicy taste.",
    "ex1_vi": "Nhãn tươi có mùi ngọt và vị mọng nước."
  },
  {
    "id": 31,
    "word": "taste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪst/",
    "meaning": "vị",
    "ex1": "Fresh longans have a sweet smell and juicy taste.",
    "ex1_vi": "Nhãn tươi có mùi ngọt và vị mọng nước."
  },
  {
    "id": 32,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "People usually open the fruit by hand and eat the flesh fresh.",
    "ex1_vi": "Mọi người thường dùng tay mở quả và ăn phần thịt tươi."
  },
  {
    "id": 33,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "People usually peel the skin and eat lychees fresh.",
    "ex1_vi": "Mọi người thường bóc vỏ và ăn vải tươi."
  },
  {
    "id": 34,
    "word": "directly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/dɝˈɛktli/",
    "meaning": "trực tiếp",
    "ex1": "People eat them directly after removing the skin.",
    "ex1_vi": "Mọi người ăn trực tiếp sau khi bóc vỏ."
  },
  {
    "id": 35,
    "word": "after",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/ˈæftɝ/",
    "meaning": "sau",
    "ex1": "People eat them directly after removing the skin.",
    "ex1_vi": "Mọi người ăn trực tiếp sau khi bóc vỏ."
  },
  {
    "id": 36,
    "word": "removing",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/rimˈuvɪŋ/",
    "meaning": "việc bóc/bỏ",
    "ex1": "People eat them directly after removing the skin; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Mọi người ăn trực tiếp sau khi bóc vỏ; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 37,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "Star apple can also be used in smoothies and chilled desserts.",
    "ex1_vi": "Vú sữa cũng có thể được dùng trong sinh tố và món tráng miệng lạnh."
  },
  {
    "id": 38,
    "word": "dried",
    "type": "verb",
    "cat": "v",
    "phonetic": "/drˈaɪd/",
    "meaning": "được sấy khô",
    "ex1": "Longans can also be dried or used in tea, sweet soup, desserts, and traditional dishes.",
    "ex1_vi": "Nhãn cũng có thể được sấy khô hoặc dùng trong trà, chè ngọt, món tráng miệng và các món truyền thống."
  },
  {
    "id": 39,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "It usually has smooth green or purple skin.",
    "ex1_vi": "Quả thường có vỏ xanh hoặc tím nhẵn."
  },
  {
    "id": 40,
    "word": "used",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzd/",
    "meaning": "được sử dụng",
    "ex1": "Longans can also be dried or used in tea, sweet soup, desserts, and traditional dishes.",
    "ex1_vi": "Nhãn cũng có thể được sấy khô hoặc dùng trong trà, chè ngọt, món tráng miệng và các món truyền thống."
  },
  {
    "id": 41,
    "word": "tea",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈi/",
    "meaning": "trà",
    "ex1": "The fruit can also be dried, canned, or used to make juice, tea, jelly, cakes, and desserts.",
    "ex1_vi": "Quả cũng có thể được sấy, đóng hộp hoặc dùng để làm nước ép, trà, thạch, bánh và món tráng miệng."
  },
  {
    "id": 42,
    "word": "soup",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈup/",
    "meaning": "súp",
    "ex1": "Longans can also be dried or used in tea, sweet soup, desserts, and traditional dishes; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Nhãn cũng có thể được sấy khô hoặc dùng trong trà, chè ngọt, món tráng miệng và các món truyền thống; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 43,
    "word": "desserts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪzˈɝts/",
    "meaning": "món tráng miệng",
    "ex1": "The fruit can also be dried, canned, or used to make juice, tea, jelly, cakes, and desserts.",
    "ex1_vi": "Quả cũng có thể được sấy, đóng hộp hoặc dùng để làm nước ép, trà, thạch, bánh và món tráng miệng."
  },
  {
    "id": 44,
    "word": "traditional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trʌdˈɪʃʌnʌl/",
    "meaning": "truyền thống",
    "ex1": "Longans can also be dried or used in tea, sweet soup, desserts, and traditional dishes; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Nhãn cũng có thể được sấy khô hoặc dùng trong trà, chè ngọt, món tráng miệng và các món truyền thống; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 45,
    "word": "dishes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪʃʌz/",
    "meaning": "món ăn",
    "ex1": "Longans can also be dried or used in tea, sweet soup, desserts, and traditional dishes; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Nhãn cũng có thể được sấy khô hoặc dùng trong trà, chè ngọt, món tráng miệng và các món truyền thống; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 46,
    "word": "grown",
    "type": "past participle",
    "cat": "v",
    "phonetic": "/ɡrˈoʊn/",
    "meaning": "được trồng",
    "ex1": "Star apple is a special tropical fruit grown in southern Vietnam.",
    "ex1_vi": "Vú sữa là một loại trái cây nhiệt đới đặc biệt được trồng ở miền Nam Việt Nam."
  },
  {
    "id": 47,
    "word": "several",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈɛvrʌl/",
    "meaning": "một số",
    "ex1": "Longans are grown in several parts of Vietnam, especially Hung Yen and the Mekong Delta.",
    "ex1_vi": "Nhãn được trồng ở nhiều vùng của Việt Nam, đặc biệt là Hưng Yên và Đồng bằng sông Cửu Long."
  },
  {
    "id": 48,
    "word": "parts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrts/",
    "meaning": "các vùng; phần",
    "ex1": "Custard apple is a sweet tropical fruit found in many parts of Vietnam.",
    "ex1_vi": "Na là một loại trái cây nhiệt đới ngọt được tìm thấy ở nhiều vùng của Việt Nam."
  },
  {
    "id": 49,
    "word": "vietnam",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/viˌɛtnˈɑm/",
    "meaning": "Việt Nam",
    "ex1": "Custard apple is a sweet tropical fruit found in many parts of Vietnam.",
    "ex1_vi": "Na là một loại trái cây nhiệt đới ngọt được tìm thấy ở nhiều vùng của Việt Nam."
  },
  {
    "id": 50,
    "word": "especially",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌspˈɛʃli/",
    "meaning": "đặc biệt",
    "ex1": "Cold lychee drinks are especially enjoyable on hot days.",
    "ex1_vi": "Đồ uống vải lạnh đặc biệt dễ chịu vào những ngày nóng."
  },
  {
    "id": 51,
    "word": "hung",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/hˈʌŋ/",
    "meaning": "Hưng",
    "ex1": "Longans are grown in several parts of Vietnam, especially Hung Yen and the Mekong Delta.",
    "ex1_vi": "Nhãn được trồng ở nhiều vùng của Việt Nam, đặc biệt là Hưng Yên và Đồng bằng sông Cửu Long."
  },
  {
    "id": 52,
    "word": "yen",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/jˈɛn/",
    "meaning": "Yên",
    "ex1": "Longans are grown in several parts of Vietnam, especially Hung Yen and the Mekong Delta; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Nhãn được trồng ở nhiều vùng của Việt Nam, đặc biệt là Hưng Yên và Đồng bằng sông Cửu Long; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 53,
    "word": "mekong",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/mˈeɪkɑŋ/",
    "meaning": "Mekong",
    "ex1": "Longans are grown in several parts of Vietnam, especially Hung Yen and the Mekong Delta; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Nhãn được trồng ở nhiều vùng của Việt Nam, đặc biệt là Hưng Yên và Đồng bằng sông Cửu Long; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 54,
    "word": "delta",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɛltʌ/",
    "meaning": "đồng bằng",
    "ex1": "Longans are grown in several parts of Vietnam, especially Hung Yen and the Mekong Delta; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Nhãn được trồng ở nhiều vùng của Việt Nam, đặc biệt là Hưng Yên và Đồng bằng sông Cửu Long; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 55,
    "word": "famous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈeɪmʌs/",
    "meaning": "nổi tiếng",
    "ex1": "One famous variety is Lo Ren star apple from Tien Giang.",
    "ex1_vi": "Một giống nổi tiếng là vú sữa Lò Rèn từ Tiền Giang."
  },
  {
    "id": 56,
    "word": "sweetness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/swˈitnʌs/",
    "meaning": "độ ngọt",
    "ex1": "The fruit is popular because of its natural sweetness and creamy texture.",
    "ex1_vi": "Loại quả này phổ biến vì vị ngọt tự nhiên và kết cấu béo mịn."
  },
  {
    "id": 57,
    "word": "thick",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/θˈɪk/",
    "meaning": "dày",
    "ex1": "Hung Yen longan is famous for its sweetness and thick flesh; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Nhãn Hưng Yên nổi tiếng vì độ ngọt và phần thịt dày; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 58,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "The fruit is popular because of its natural sweetness and creamy texture.",
    "ex1_vi": "Loại quả này phổ biến vì vị ngọt tự nhiên và kết cấu béo mịn."
  },
  {
    "id": 59,
    "word": "summer",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈʌmɝ/",
    "meaning": "mùa hè",
    "ex1": "The fruit is popular during summer and family celebrations.",
    "ex1_vi": "Loại quả này phổ biến vào mùa hè và các dịp sum họp gia đình."
  },
  {
    "id": 60,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "The fruit is popular during summer and family celebrations.",
    "ex1_vi": "Loại quả này phổ biến vào mùa hè và các dịp sum họp gia đình."
  },
  {
    "id": 61,
    "word": "celebrations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˌɛlʌbrˈeɪʃʌnz/",
    "meaning": "dịp lễ; sum họp",
    "ex1": "The fruit is popular during summer and family celebrations; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Loại quả này phổ biến vào mùa hè và các dịp sum họp gia đình; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 62,
    "word": "lychee",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈliːtʃiː/",
    "meaning": "vải",
    "ex1": "Cold lychee drinks are especially enjoyable on hot days.",
    "ex1_vi": "Đồ uống vải lạnh đặc biệt dễ chịu vào những ngày nóng."
  },
  {
    "id": 63,
    "word": "vải",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vải/",
    "meaning": "vải; vải thiều",
    "ex1": "Vietnamese families often enjoy Vải Thiều during everyday meals and snacks.",
    "ex1_vi": "Các gia đình Việt Nam thường thưởng thức Vải Thiều trong các bữa ăn và món ăn nhẹ hằng ngày."
  },
  {
    "id": 64,
    "word": "thiều",
    "type": "noun",
    "cat": "n",
    "phonetic": "/thiều/",
    "meaning": "thiều (trong 'vải thiều')",
    "ex1": "Local markets often sell fresh Vải Thiều when this fruit is in season.",
    "ex1_vi": "Các chợ địa phương thường bán Vải Thiều tươi khi loại quả này vào mùa."
  },
  {
    "id": 65,
    "word": "lychees",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈliːtʃiːz/",
    "meaning": "vải",
    "ex1": "Vietnamese lychees are enjoyed locally and exported to many other countries.",
    "ex1_vi": "Vải Việt Nam được thưởng thức trong nước và xuất khẩu sang nhiều quốc gia khác."
  },
  {
    "id": 66,
    "word": "rough",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈʌf/",
    "meaning": "sần sùi",
    "ex1": "Lychees are small summer fruits with rough red or pink skin; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Vải là loại trái cây mùa hè nhỏ có vỏ sần sùi màu đỏ hoặc hồng; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 67,
    "word": "red",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛd/",
    "meaning": "màu đỏ",
    "ex1": "Lychees are small summer fruits with rough red or pink skin; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Vải là loại trái cây mùa hè nhỏ có vỏ sần sùi màu đỏ hoặc hồng; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 68,
    "word": "pink",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɪŋk/",
    "meaning": "màu hồng",
    "ex1": "Lychees are small summer fruits with rough red or pink skin; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Vải là loại trái cây mùa hè nhỏ có vỏ sần sùi màu đỏ hoặc hồng; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 69,
    "word": "inside",
    "type": "adverb/preposition",
    "cat": "adv",
    "phonetic": "/ˌɪnsˈaɪd/",
    "meaning": "bên trong",
    "ex1": "The dark seeds inside are removed and not eaten.",
    "ex1_vi": "Những hạt sẫm màu bên trong được bỏ ra và không ăn."
  },
  {
    "id": 70,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋ/",
    "meaning": "mạnh",
    "ex1": "Lychees have a strong sweet smell and a refreshing taste; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Vải có mùi ngọt mạnh và vị sảng khoái; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 71,
    "word": "refreshing",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪfrˈɛʃɪŋ/",
    "meaning": "sảng khoái",
    "ex1": "Lychees have a strong sweet smell and a refreshing taste; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Vải có mùi ngọt mạnh và vị sảng khoái; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 72,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "People usually peel the skin and eat lychees fresh.",
    "ex1_vi": "Mọi người thường bóc vỏ và ăn vải tươi."
  },
  {
    "id": 73,
    "word": "peel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pˈil/",
    "meaning": "bóc vỏ",
    "ex1": "People usually peel the skin and eat lychees fresh; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Mọi người thường bóc vỏ và ăn vải tươi; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 74,
    "word": "canned",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈænd/",
    "meaning": "đóng hộp",
    "ex1": "The fruit can also be dried, canned, or used to make juice, tea, jelly, cakes, and desserts; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Quả cũng có thể được sấy, đóng hộp hoặc dùng để làm nước ép, trà, thạch, bánh và món tráng miệng; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 75,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm",
    "ex1": "The fruit can also be dried, canned, or used to make juice, tea, jelly, cakes, and desserts; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Quả cũng có thể được sấy, đóng hộp hoặc dùng để làm nước ép, trà, thạch, bánh và món tráng miệng; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 76,
    "word": "juice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈus/",
    "meaning": "nước ép",
    "ex1": "The fruit can also be dried, canned, or used to make juice, tea, jelly, cakes, and desserts; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Quả cũng có thể được sấy, đóng hộp hoặc dùng để làm nước ép, trà, thạch, bánh và món tráng miệng; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 77,
    "word": "jelly",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈɛli/",
    "meaning": "thạch",
    "ex1": "The fruit can also be dried, canned, or used to make juice, tea, jelly, cakes, and desserts; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Quả cũng có thể được sấy, đóng hộp hoặc dùng để làm nước ép, trà, thạch, bánh và món tráng miệng; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 78,
    "word": "cakes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈeɪks/",
    "meaning": "bánh",
    "ex1": "The fruit can also be dried, canned, or used to make juice, tea, jelly, cakes, and desserts; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Quả cũng có thể được sấy, đóng hộp hoặc dùng để làm nước ép, trà, thạch, bánh và món tráng miệng; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 79,
    "word": "cold",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈoʊld/",
    "meaning": "lạnh",
    "ex1": "Cold lychee drinks are especially enjoyable on hot days; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Đồ uống vải lạnh đặc biệt dễ chịu vào những ngày nóng; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 80,
    "word": "drinks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɪŋks/",
    "meaning": "đồ uống",
    "ex1": "Cold lychee drinks are especially enjoyable on hot days; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Đồ uống vải lạnh đặc biệt dễ chịu vào những ngày nóng; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 81,
    "word": "enjoyable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɛndʒˈɔɪʌbʌl/",
    "meaning": "dễ chịu; thú vị",
    "ex1": "Cold lychee drinks are especially enjoyable on hot days; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Đồ uống vải lạnh đặc biệt dễ chịu vào những ngày nóng; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 82,
    "word": "hot",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑt/",
    "meaning": "nóng",
    "ex1": "Cold lychee drinks are especially enjoyable on hot days; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Đồ uống vải lạnh đặc biệt dễ chịu vào những ngày nóng; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 83,
    "word": "days",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪz/",
    "meaning": "ngày",
    "ex1": "Cold lychee drinks are especially enjoyable on hot days; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Đồ uống vải lạnh đặc biệt dễ chịu vào những ngày nóng; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 84,
    "word": "vietnamese",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/viˌɛtnɑmˈis/",
    "meaning": "thuộc Việt Nam; người Việt Nam",
    "ex1": "Vietnamese lychees are enjoyed locally and exported to many other countries.",
    "ex1_vi": "Vải Việt Nam được thưởng thức trong nước và xuất khẩu sang nhiều quốc gia khác."
  },
  {
    "id": 85,
    "word": "areas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛriʌz/",
    "meaning": "khu vực",
    "ex1": "Vietnamese lychees are famous in areas such as Luc Ngan and Thanh Ha.",
    "ex1_vi": "Vải Việt Nam nổi tiếng ở những vùng như Lục Ngạn và Thanh Hà."
  },
  {
    "id": 86,
    "word": "such",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌtʃ/",
    "meaning": "như",
    "ex1": "Vietnamese lychees are famous in areas such as Luc Ngan and Thanh Ha.",
    "ex1_vi": "Vải Việt Nam nổi tiếng ở những vùng như Lục Ngạn và Thanh Hà."
  },
  {
    "id": 87,
    "word": "luc",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈuk/",
    "meaning": "Lục",
    "ex1": "Vietnamese lychees are famous in areas such as Luc Ngan and Thanh Ha; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Vải Việt Nam nổi tiếng ở những vùng như Lục Ngạn và Thanh Hà; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 88,
    "word": "ngan",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ngan/",
    "meaning": "Ngạn",
    "ex1": "Vietnamese lychees are famous in areas such as Luc Ngan and Thanh Ha; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Vải Việt Nam nổi tiếng ở những vùng như Lục Ngạn và Thanh Hà; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 89,
    "word": "thanh",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈæn/",
    "meaning": "Thanh",
    "ex1": "Vietnamese lychees are famous in areas such as Luc Ngan and Thanh Ha; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Vải Việt Nam nổi tiếng ở những vùng như Lục Ngạn và Thanh Hà; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 90,
    "word": "ha",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɑ/",
    "meaning": "Hà",
    "ex1": "Vietnamese lychees are famous in areas such as Luc Ngan and Thanh Ha; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Vải Việt Nam nổi tiếng ở những vùng như Lục Ngạn và Thanh Hà; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 91,
    "word": "harvest",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɑrvʌst/",
    "meaning": "thu hoạch",
    "ex1": "During the harvest season, farmers collect large amounts of fruit.",
    "ex1_vi": "Trong mùa thu hoạch, nông dân thu gom lượng lớn trái cây."
  },
  {
    "id": 92,
    "word": "season",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈizʌn/",
    "meaning": "mùa",
    "ex1": "During the harvest season, farmers collect large amounts of fruit.",
    "ex1_vi": "Trong mùa thu hoạch, nông dân thu gom lượng lớn trái cây."
  },
  {
    "id": 93,
    "word": "farmers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɑrmɝz/",
    "meaning": "nông dân",
    "ex1": "Farmers often grow the trees on hills and rocky land.",
    "ex1_vi": "Nông dân thường trồng cây trên đồi và đất đá."
  },
  {
    "id": 94,
    "word": "collect",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌlˈɛkt/",
    "meaning": "thu gom",
    "ex1": "During the harvest season, farmers collect large amounts of fruit; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Trong mùa thu hoạch, nông dân thu gom lượng lớn trái cây; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 95,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒ/",
    "meaning": "lớn",
    "ex1": "During the harvest season, farmers collect large amounts of fruit; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Trong mùa thu hoạch, nông dân thu gom lượng lớn trái cây; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 96,
    "word": "amounts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌmˈaʊnts/",
    "meaning": "lượng",
    "ex1": "During the harvest season, farmers collect large amounts of fruit; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Trong mùa thu hoạch, nông dân thu gom lượng lớn trái cây; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 97,
    "word": "enjoyed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪd/",
    "meaning": "được yêu thích",
    "ex1": "Vietnamese lychees are enjoyed locally and exported to many other countries; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Vải Việt Nam được thưởng thức trong nước và xuất khẩu sang nhiều quốc gia khác; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 98,
    "word": "locally",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/lˈoʊkʌli/",
    "meaning": "trong nước",
    "ex1": "Vietnamese lychees are enjoyed locally and exported to many other countries; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Vải Việt Nam được thưởng thức trong nước và xuất khẩu sang nhiều quốc gia khác; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 99,
    "word": "exported",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɪkspˈɔrtʌd/",
    "meaning": "được xuất khẩu",
    "ex1": "Vietnamese lychees are enjoyed locally and exported to many other countries; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Vải Việt Nam được thưởng thức trong nước và xuất khẩu sang nhiều quốc gia khác; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 100,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "In northern Vietnam, people often call it na, while many southern people call it mãng cầu ta.",
    "ex1_vi": "Ở miền Bắc Việt Nam, mọi người thường gọi là na, trong khi nhiều người miền Nam gọi là mãng cầu ta."
  },
  {
    "id": 101,
    "word": "other",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈʌðɝ/",
    "meaning": "khác",
    "ex1": "Vietnamese lychees are enjoyed locally and exported to many other countries; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Vải Việt Nam được thưởng thức trong nước và xuất khẩu sang nhiều quốc gia khác; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 102,
    "word": "countries",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌntriz/",
    "meaning": "quốc gia",
    "ex1": "Vietnamese lychees are enjoyed locally and exported to many other countries; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Vải Việt Nam được thưởng thức trong nước và xuất khẩu sang nhiều quốc gia khác; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 103,
    "word": "star",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈɑr/",
    "meaning": "ngôi sao; vú sữa trong cụm star apple",
    "ex1": "One famous variety is Lo Ren star apple from Tien Giang.",
    "ex1_vi": "Một giống nổi tiếng là vú sữa Lò Rèn từ Tiền Giang."
  },
  {
    "id": 104,
    "word": "apple",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈæpʌl/",
    "meaning": "táo; vú sữa trong cụm star apple",
    "ex1": "Chi Lang custard apple is a famous variety from Lang Son Province.",
    "ex1_vi": "Na Chi Lăng là một giống nổi tiếng từ tỉnh Lạng Sơn."
  },
  {
    "id": 105,
    "word": "vú",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vú/",
    "meaning": "vú",
    "ex1": "Its Vietnamese name, vú sữa, is connected with a well-known story about a mother’s love.",
    "ex1_vi": "Tên tiếng Việt “vú sữa” gắn với một câu chuyện nổi tiếng về tình yêu của người mẹ."
  },
  {
    "id": 106,
    "word": "sữa",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sữa/",
    "meaning": "sữa",
    "ex1": "Its Vietnamese name, vú sữa, is connected with a well-known story about a mother’s love; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Tên tiếng Việt “vú sữa” gắn với một câu chuyện nổi tiếng về tình yêu của người mẹ; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 107,
    "word": "special",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/spˈɛʃʌl/",
    "meaning": "đặc biệt",
    "ex1": "Star apple is a special tropical fruit grown in southern Vietnam; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Vú sữa là một loại trái cây nhiệt đới đặc biệt được trồng ở miền Nam Việt Nam; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 108,
    "word": "tropical",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trˈɑpɪkʌl/",
    "meaning": "nhiệt đới",
    "ex1": "Star apple is a special tropical fruit grown in southern Vietnam; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Vú sữa là một loại trái cây nhiệt đới đặc biệt được trồng ở miền Nam Việt Nam; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 109,
    "word": "southern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈʌðɝn/",
    "meaning": "phía Nam",
    "ex1": "In northern Vietnam, people often call it na, while many southern people call it mãng cầu ta.",
    "ex1_vi": "Ở miền Bắc Việt Nam, mọi người thường gọi là na, trong khi nhiều người miền Nam gọi là mãng cầu ta."
  },
  {
    "id": 110,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "The fruit has a pleasant smell and a creamy texture.",
    "ex1_vi": "Quả có mùi dễ chịu và kết cấu béo mịn."
  },
  {
    "id": 111,
    "word": "smooth",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈuð/",
    "meaning": "nhẵn",
    "ex1": "It usually has smooth green or purple skin.",
    "ex1_vi": "Quả thường có vỏ xanh hoặc tím nhẵn."
  },
  {
    "id": 112,
    "word": "green",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈin/",
    "meaning": "xanh",
    "ex1": "Its green skin is covered with small rounded sections.",
    "ex1_vi": "Lớp vỏ xanh được phủ bởi các múi nhỏ tròn."
  },
  {
    "id": 113,
    "word": "purple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɝpʌl/",
    "meaning": "màu tím",
    "ex1": "It usually has smooth green or purple skin; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Quả thường có vỏ xanh hoặc tím nhẵn; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 114,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "When the fruit is cut across the middle, its sections form a shape that looks like a star.",
    "ex1_vi": "Khi quả được cắt ngang ở giữa, các múi tạo thành hình giống như một ngôi sao."
  },
  {
    "id": 115,
    "word": "cut",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌt/",
    "meaning": "cắt",
    "ex1": "When the fruit is cut across the middle, its sections form a shape that looks like a star.",
    "ex1_vi": "Khi quả được cắt ngang ở giữa, các múi tạo thành hình giống như một ngôi sao."
  },
  {
    "id": 116,
    "word": "across",
    "type": "preposition/adverb",
    "cat": "adv",
    "phonetic": "/ʌkrˈɔs/",
    "meaning": "ngang qua",
    "ex1": "When the fruit is cut across the middle, its sections form a shape that looks like a star; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Khi quả được cắt ngang ở giữa, các múi tạo thành hình giống như một ngôi sao; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 117,
    "word": "middle",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈɪdʌl/",
    "meaning": "phần giữa",
    "ex1": "When the fruit is cut across the middle, its sections form a shape that looks like a star; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Khi quả được cắt ngang ở giữa, các múi tạo thành hình giống như một ngôi sao; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 118,
    "word": "sections",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛkʃʌnz/",
    "meaning": "múi; phần",
    "ex1": "Its green skin is covered with small rounded sections.",
    "ex1_vi": "Lớp vỏ xanh được phủ bởi các múi nhỏ tròn."
  },
  {
    "id": 119,
    "word": "form",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈɔrm/",
    "meaning": "tạo thành",
    "ex1": "When the fruit is cut across the middle, its sections form a shape that looks like a star; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Khi quả được cắt ngang ở giữa, các múi tạo thành hình giống như một ngôi sao; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 120,
    "word": "shape",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈeɪp/",
    "meaning": "hình dạng",
    "ex1": "When the fruit is cut across the middle, its sections form a shape that looks like a star; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Khi quả được cắt ngang ở giữa, các múi tạo thành hình giống như một ngôi sao; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 121,
    "word": "looks",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊks/",
    "meaning": "trông",
    "ex1": "When the fruit is cut across the middle, its sections form a shape that looks like a star; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Khi quả được cắt ngang ở giữa, các múi tạo thành hình giống như một ngôi sao; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 122,
    "word": "like",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈaɪk/",
    "meaning": "thích",
    "ex1": "When the fruit is cut across the middle, its sections form a shape that looks like a star; this fruit remains a familiar part of local food culture.",
    "ex1_vi": "Khi quả được cắt ngang ở giữa, các múi tạo thành hình giống như một ngôi sao; loại quả này vẫn là một phần quen thuộc của văn hóa ẩm thực địa phương."
  },
  {
    "id": 123,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "The flesh is soft, sweet, and milky.",
    "ex1_vi": "Phần thịt mềm, ngọt và có vị sữa."
  },
  {
    "id": 124,
    "word": "milky",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈɪlki/",
    "meaning": "có vị sữa",
    "ex1": "The flesh is soft, sweet, and milky.",
    "ex1_vi": "Phần thịt mềm, ngọt và có vị sữa."
  },
  {
    "id": 125,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "People often gently press the fruit before cutting it open and eating it with a spoon.",
    "ex1_vi": "Mọi người thường ấn nhẹ quả trước khi cắt mở và ăn bằng thìa."
  },
  {
    "id": 126,
    "word": "gently",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/dʒˈɛntli/",
    "meaning": "nhẹ nhàng",
    "ex1": "People often gently press the fruit before cutting it open and eating it with a spoon.",
    "ex1_vi": "Mọi người thường ấn nhẹ quả trước khi cắt mở và ăn bằng thìa."
  },
  {
    "id": 127,
    "word": "press",
    "type": "verb",
    "cat": "v",
    "phonetic": "/prˈɛs/",
    "meaning": "ấn",
    "ex1": "People often gently press the fruit before cutting it open and eating it with a spoon; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Mọi người thường ấn nhẹ quả trước khi cắt mở và ăn bằng thìa; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 128,
    "word": "before",
    "type": "preposition/conjunction",
    "cat": "adv",
    "phonetic": "/bɪfˈɔr/",
    "meaning": "trước",
    "ex1": "People often gently press the fruit before cutting it open and eating it with a spoon; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Mọi người thường ấn nhẹ quả trước khi cắt mở và ăn bằng thìa; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 129,
    "word": "cutting",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌtɪŋ/",
    "meaning": "việc cắt",
    "ex1": "People often gently press the fruit before cutting it open and eating it with a spoon; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Mọi người thường ấn nhẹ quả trước khi cắt mở và ăn bằng thìa; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 130,
    "word": "open",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈoʊpʌn/",
    "meaning": "mở",
    "ex1": "People often gently press the fruit before cutting it open and eating it with a spoon; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Mọi người thường ấn nhẹ quả trước khi cắt mở và ăn bằng thìa; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 131,
    "word": "eating",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈitɪŋ/",
    "meaning": "việc ăn",
    "ex1": "People often gently press the fruit before cutting it open and eating it with a spoon; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Mọi người thường ấn nhẹ quả trước khi cắt mở và ăn bằng thìa; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 132,
    "word": "spoon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈun/",
    "meaning": "thìa",
    "ex1": "People often gently press the fruit before cutting it open and eating it with a spoon; this fruit remains a familiar part of local food culture.",
    "ex1_vi": "Mọi người thường ấn nhẹ quả trước khi cắt mở và ăn bằng thìa; loại quả này vẫn là một phần quen thuộc của văn hóa ẩm thực địa phương."
  },
  {
    "id": 133,
    "word": "smoothies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsmuːðiz/",
    "meaning": "sinh tố",
    "ex1": "Star apple can also be used in smoothies and chilled desserts; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Vú sữa cũng có thể được dùng trong sinh tố và món tráng miệng lạnh; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 134,
    "word": "chilled",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tʃˈɪld/",
    "meaning": "được làm lạnh",
    "ex1": "Star apple can also be used in smoothies and chilled desserts; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Vú sữa cũng có thể được dùng trong sinh tố và món tráng miệng lạnh; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 135,
    "word": "one",
    "type": "number",
    "cat": "adj",
    "phonetic": "/wˈʌn/",
    "meaning": "một",
    "ex1": "One famous variety is Lo Ren star apple from Tien Giang; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Một giống nổi tiếng là vú sữa Lò Rèn từ Tiền Giang; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 136,
    "word": "variety",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vɝˈaɪʌti/",
    "meaning": "giống; loại",
    "ex1": "Chi Lang custard apple is a famous variety from Lang Son Province.",
    "ex1_vi": "Na Chi Lăng là một giống nổi tiếng từ tỉnh Lạng Sơn."
  },
  {
    "id": 137,
    "word": "lo",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈoʊ/",
    "meaning": "Lò",
    "ex1": "One famous variety is Lo Ren star apple from Tien Giang; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Một giống nổi tiếng là vú sữa Lò Rèn từ Tiền Giang; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 138,
    "word": "ren",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɛn/",
    "meaning": "Rèn",
    "ex1": "One famous variety is Lo Ren star apple from Tien Giang; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Một giống nổi tiếng là vú sữa Lò Rèn từ Tiền Giang; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 139,
    "word": "tien",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/tjˈɛn/",
    "meaning": "Tiền",
    "ex1": "One famous variety is Lo Ren star apple from Tien Giang; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Một giống nổi tiếng là vú sữa Lò Rèn từ Tiền Giang; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 140,
    "word": "giang",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/dʒiˈɑŋ/",
    "meaning": "Giang",
    "ex1": "One famous variety is Lo Ren star apple from Tien Giang; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Một giống nổi tiếng là vú sữa Lò Rèn từ Tiền Giang; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 141,
    "word": "pleasant",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/plˈɛzʌnt/",
    "meaning": "dễ chịu",
    "ex1": "The fruit has a pleasant smell and a creamy texture.",
    "ex1_vi": "Quả có mùi dễ chịu và kết cấu béo mịn."
  },
  {
    "id": 142,
    "word": "creamy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈimi/",
    "meaning": "béo mịn",
    "ex1": "The fruit has a pleasant smell and a creamy texture; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Quả có mùi dễ chịu và kết cấu béo mịn; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 143,
    "word": "texture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛkstʃɝ/",
    "meaning": "kết cấu",
    "ex1": "The fruit has a pleasant smell and a creamy texture; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Quả có mùi dễ chịu và kết cấu béo mịn; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 144,
    "word": "connected",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌnˈɛktɪd/",
    "meaning": "được gắn/kết nối",
    "ex1": "Its Vietnamese name, vú sữa, is connected with a well-known story about a mother’s love; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Tên tiếng Việt “vú sữa” gắn với một câu chuyện nổi tiếng về tình yêu của người mẹ; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 145,
    "word": "well-known",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈɛlnˈoʊn/",
    "meaning": "nổi tiếng",
    "ex1": "Its Vietnamese name, vú sữa, is connected with a well-known story about a mother’s love; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Tên tiếng Việt “vú sữa” gắn với một câu chuyện nổi tiếng về tình yêu của người mẹ; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 146,
    "word": "story",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈɔri/",
    "meaning": "câu chuyện",
    "ex1": "Its Vietnamese name, vú sữa, is connected with a well-known story about a mother’s love; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Tên tiếng Việt “vú sữa” gắn với một câu chuyện nổi tiếng về tình yêu của người mẹ; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 147,
    "word": "about",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ʌbˈaʊt/",
    "meaning": "về",
    "ex1": "Its Vietnamese name, vú sữa, is connected with a well-known story about a mother’s love; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Tên tiếng Việt “vú sữa” gắn với một câu chuyện nổi tiếng về tình yêu của người mẹ; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 148,
    "word": "mother",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈʌðɝ/",
    "meaning": "mẹ",
    "ex1": "Its Vietnamese name, vú sữa, is connected with a well-known story about a mother’s love; this fruit remains a familiar part of local food culture.",
    "ex1_vi": "Tên tiếng Việt “vú sữa” gắn với một câu chuyện nổi tiếng về tình yêu của người mẹ; loại quả này vẫn là một phần quen thuộc của văn hóa ẩm thực địa phương."
  },
  {
    "id": 149,
    "word": "love",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʌv/",
    "meaning": "yêu thích",
    "ex1": "Its Vietnamese name, vú sữa, is connected with a well-known story about a mother’s love; these features help distinguish this fruit from many others.",
    "ex1_vi": "Tên tiếng Việt “vú sữa” gắn với một câu chuyện nổi tiếng về tình yêu của người mẹ; những đặc điểm này giúp phân biệt loại quả này với nhiều loại khác."
  },
  {
    "id": 150,
    "word": "custard",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌstɝd/",
    "meaning": "mãng cầu; na trong cụm custard apple",
    "ex1": "Custard apple is a sweet tropical fruit found in many parts of Vietnam; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Na là một loại trái cây nhiệt đới ngọt được tìm thấy ở nhiều vùng của Việt Nam; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 151,
    "word": "na",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈɑ/",
    "meaning": "na",
    "ex1": "In northern Vietnam, people often call it na, while many southern people call it mãng cầu ta; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Ở miền Bắc Việt Nam, mọi người thường gọi là na, trong khi nhiều người miền Nam gọi là mãng cầu ta; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 152,
    "word": "mãng",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mãng/",
    "meaning": "mãng",
    "ex1": "In northern Vietnam, people often call it na, while many southern people call it mãng cầu ta; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Ở miền Bắc Việt Nam, mọi người thường gọi là na, trong khi nhiều người miền Nam gọi là mãng cầu ta; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 153,
    "word": "cầu",
    "type": "noun",
    "cat": "n",
    "phonetic": "/cầu/",
    "meaning": "cầu; trong mãng cầu",
    "ex1": "In northern Vietnam, people often call it na, while many southern people call it mãng cầu ta; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Ở miền Bắc Việt Nam, mọi người thường gọi là na, trong khi nhiều người miền Nam gọi là mãng cầu ta; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 154,
    "word": "ta",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɑ/",
    "meaning": "ta",
    "ex1": "In northern Vietnam, people often call it na, while many southern people call it mãng cầu ta; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Ở miền Bắc Việt Nam, mọi người thường gọi là na, trong khi nhiều người miền Nam gọi là mãng cầu ta; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 155,
    "word": "found",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaʊnd/",
    "meaning": "được tìm thấy",
    "ex1": "Custard apple is a sweet tropical fruit found in many parts of Vietnam; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Na là một loại trái cây nhiệt đới ngọt được tìm thấy ở nhiều vùng của Việt Nam; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 156,
    "word": "northern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈɔrðɝn/",
    "meaning": "phía Bắc",
    "ex1": "In northern Vietnam, people often call it na, while many southern people call it mãng cầu ta; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Ở miền Bắc Việt Nam, mọi người thường gọi là na, trong khi nhiều người miền Nam gọi là mãng cầu ta; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 157,
    "word": "call",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈɔl/",
    "meaning": "gọi",
    "ex1": "In northern Vietnam, people often call it na, while many southern people call it mãng cầu ta; this fruit remains a familiar part of local food culture.",
    "ex1_vi": "Ở miền Bắc Việt Nam, mọi người thường gọi là na, trong khi nhiều người miền Nam gọi là mãng cầu ta; loại quả này vẫn là một phần quen thuộc của văn hóa ẩm thực địa phương."
  },
  {
    "id": 158,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "In northern Vietnam, people often call it na, while many southern people call it mãng cầu ta; these features help distinguish this fruit from many others.",
    "ex1_vi": "Ở miền Bắc Việt Nam, mọi người thường gọi là na, trong khi nhiều người miền Nam gọi là mãng cầu ta; những đặc điểm này giúp phân biệt loại quả này với nhiều loại khác."
  },
  {
    "id": 159,
    "word": "covered",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌvɝd/",
    "meaning": "được phủ",
    "ex1": "Its green skin is covered with small rounded sections; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Lớp vỏ xanh được phủ bởi các múi nhỏ tròn; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 160,
    "word": "rounded",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈaʊndʌd/",
    "meaning": "tròn",
    "ex1": "Its green skin is covered with small rounded sections; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Lớp vỏ xanh được phủ bởi các múi nhỏ tròn; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 161,
    "word": "ripe",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈaɪp/",
    "meaning": "chín",
    "ex1": "When ripe, the white flesh becomes soft, sweet, and fragrant; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Khi chín, phần thịt trắng trở nên mềm, ngọt và thơm; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 162,
    "word": "becomes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈʌmz/",
    "meaning": "trở nên",
    "ex1": "When ripe, the white flesh becomes soft, sweet, and fragrant; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Khi chín, phần thịt trắng trở nên mềm, ngọt và thơm; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 163,
    "word": "fragrant",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈeɪɡrʌnt/",
    "meaning": "thơm",
    "ex1": "When ripe, the white flesh becomes soft, sweet, and fragrant; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Khi chín, phần thịt trắng trở nên mềm, ngọt và thơm; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 164,
    "word": "hand",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈænd/",
    "meaning": "tay",
    "ex1": "People usually open the fruit by hand and eat the flesh fresh; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Mọi người thường dùng tay mở quả và ăn phần thịt tươi; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 165,
    "word": "seeds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈidz/",
    "meaning": "hạt",
    "ex1": "The dark seeds inside are removed and not eaten; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Những hạt sẫm màu bên trong được bỏ ra và không ăn; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 166,
    "word": "removed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rimˈuvd/",
    "meaning": "được loại bỏ",
    "ex1": "The dark seeds inside are removed and not eaten; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Những hạt sẫm màu bên trong được bỏ ra và không ăn; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 167,
    "word": "not",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/nˈɑt/",
    "meaning": "không",
    "ex1": "The dark seeds inside are removed and not eaten; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Những hạt sẫm màu bên trong được bỏ ra và không ăn; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 168,
    "word": "eaten",
    "type": "past participle",
    "cat": "v",
    "phonetic": "/ˈitʌn/",
    "meaning": "được ăn",
    "ex1": "The dark seeds inside are removed and not eaten; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Những hạt sẫm màu bên trong được bỏ ra và không ăn; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 169,
    "word": "chi",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/kˈaɪ/",
    "meaning": "Chi",
    "ex1": "Chi Lang custard apple is a famous variety from Lang Son Province; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Na Chi Lăng là một giống nổi tiếng từ tỉnh Lạng Sơn; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 170,
    "word": "lang",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈæŋ/",
    "meaning": "Lăng",
    "ex1": "Chi Lang custard apple is a famous variety from Lang Son Province; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Na Chi Lăng là một giống nổi tiếng từ tỉnh Lạng Sơn; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 171,
    "word": "son",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈʌn/",
    "meaning": "Sơn",
    "ex1": "Chi Lang custard apple is a famous variety from Lang Son Province; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Na Chi Lăng là một giống nổi tiếng từ tỉnh Lạng Sơn; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 172,
    "word": "province",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑvʌns/",
    "meaning": "tỉnh",
    "ex1": "Chi Lang custard apple is a famous variety from Lang Son Province; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Na Chi Lăng là một giống nổi tiếng từ tỉnh Lạng Sơn; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 173,
    "word": "trees",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈiz/",
    "meaning": "cây",
    "ex1": "Farmers often grow the trees on hills and rocky land; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Nông dân thường trồng cây trên đồi và đất đá; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 174,
    "word": "hills",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɪlz/",
    "meaning": "đồi",
    "ex1": "Farmers often grow the trees on hills and rocky land; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Nông dân thường trồng cây trên đồi và đất đá; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 175,
    "word": "rocky",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɑki/",
    "meaning": "nhiều đá",
    "ex1": "Farmers often grow the trees on hills and rocky land; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Nông dân thường trồng cây trên đồi và đất đá; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 176,
    "word": "land",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈænd/",
    "meaning": "đất",
    "ex1": "Farmers often grow the trees on hills and rocky land; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Nông dân thường trồng cây trên đồi và đất đá; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 177,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "The fruit is popular because of its natural sweetness and creamy texture; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Loại quả này phổ biến vì vị ngọt tự nhiên và kết cấu béo mịn; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 178,
    "word": "natural",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈætʃɝʌl/",
    "meaning": "tự nhiên",
    "ex1": "The fruit is popular because of its natural sweetness and creamy texture; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Loại quả này phổ biến vì vị ngọt tự nhiên và kết cấu béo mịn; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  }
];

const newReadingVocabOrder = [
  "longan",
  "nhãn",
  "longans",
  "small",
  "round",
  "fruits",
  "grow",
  "bunches",
  "have",
  "thin",
  "brown",
  "skin",
  "and",
  "clear",
  "white",
  "flesh",
  "dark",
  "seed",
  "can",
  "seen",
  "so",
  "fruit",
  "name",
  "means",
  "dragon",
  "eye",
  "fresh",
  "sweet",
  "smell",
  "juicy",
  "taste",
  "people",
  "eat",
  "directly",
  "after",
  "removing",
  "also",
  "dried",
  "or",
  "used",
  "tea",
  "soup",
  "desserts",
  "traditional",
  "dishes",
  "grown",
  "several",
  "parts",
  "vietnam",
  "especially",
  "hung",
  "yen",
  "mekong",
  "delta",
  "famous",
  "sweetness",
  "thick",
  "popular",
  "summer",
  "family",
  "celebrations",
  "lychee",
  "vải",
  "thiều",
  "lychees",
  "rough",
  "red",
  "pink",
  "inside",
  "strong",
  "refreshing",
  "usually",
  "peel",
  "canned",
  "make",
  "juice",
  "jelly",
  "cakes",
  "cold",
  "drinks",
  "enjoyable",
  "hot",
  "days",
  "vietnamese",
  "areas",
  "such",
  "luc",
  "ngan",
  "thanh",
  "ha",
  "harvest",
  "season",
  "farmers",
  "collect",
  "large",
  "amounts",
  "enjoyed",
  "locally",
  "exported",
  "many",
  "other",
  "countries",
  "star",
  "apple",
  "vú",
  "sữa",
  "special",
  "tropical",
  "southern",
  "has",
  "smooth",
  "green",
  "purple",
  "when",
  "cut",
  "across",
  "middle",
  "sections",
  "form",
  "shape",
  "looks",
  "like",
  "soft",
  "milky",
  "often",
  "gently",
  "press",
  "before",
  "cutting",
  "open",
  "eating",
  "spoon",
  "smoothies",
  "chilled",
  "one",
  "variety",
  "lo",
  "ren",
  "tien",
  "giang",
  "pleasant",
  "creamy",
  "texture",
  "connected",
  "well-known",
  "story",
  "about",
  "mother",
  "love",
  "custard",
  "na",
  "mãng",
  "cầu",
  "ta",
  "found",
  "northern",
  "call",
  "while",
  "covered",
  "rounded",
  "ripe",
  "becomes",
  "fragrant",
  "hand",
  "seeds",
  "removed",
  "not",
  "eaten",
  "chi",
  "lang",
  "son",
  "province",
  "trees",
  "hills",
  "rocky",
  "land",
  "because",
  "natural"
];
