const newEssayData = [
  {
    "text": "Chapter 1. Banana – Chuối\nBananas are one of the most common fruits in Vietnam. They grow well in warm and wet weather. Bananas have yellow or green skin, and the fruit inside is soft, sweet, and easy to eat.\n\nVietnamese people enjoy bananas in many ways. They eat fresh bananas, make banana cakes, cook sweet banana soup, or dry bananas as snacks. Green bananas can also be used in salads and traditional dishes.\n\nBananas contain useful nutrients and provide energy for daily activities. They are affordable and available throughout the year. Because they are delicious, convenient, and easy to carry, bananas are popular with both children and adults.",
    "vi": "Chương 1. Chuối\nChuối là một trong những loại trái cây phổ biến nhất ở Việt Nam. Chuối phát triển tốt trong thời tiết ấm và ẩm ướt. Chuối có vỏ màu vàng hoặc xanh, và phần quả bên trong mềm, ngọt và dễ ăn.\n\nNgười Việt Nam thưởng thức chuối theo nhiều cách. Họ ăn chuối tươi, làm bánh chuối, nấu chè chuối ngọt hoặc sấy chuối làm món ăn vặt. Chuối xanh cũng có thể được dùng trong các món gỏi và món ăn truyền thống.\n\nChuối chứa các chất dinh dưỡng hữu ích và cung cấp năng lượng cho các hoạt động hằng ngày. Chuối có giá phải chăng và có quanh năm. Vì ngon, tiện lợi và dễ mang theo, chuối được cả trẻ em và người lớn ưa thích."
  },
  {
    "text": "Chapter 2. Mango – Xoài\nMangoes are popular tropical fruits in Vietnam. They are grown in many southern provinces, where the weather is warm and sunny. A ripe mango usually has yellow skin, soft flesh, and a sweet smell.\n\nPeople can eat ripe mangoes as a dessert or use them to make juice, smoothies, ice cream, and sweet dishes. Green mangoes are often eaten with salt, chili, or fish sauce. They are also used in fresh salads.\n\nMangoes have a rich flavor and contain several important nutrients. Many Vietnamese families enjoy mangoes during the hot season. Their bright color, pleasant smell, and delicious taste make them a favorite fruit.",
    "vi": "Chương 2. Xoài\nXoài là loại trái cây nhiệt đới phổ biến ở Việt Nam. Xoài được trồng ở nhiều tỉnh phía Nam, nơi thời tiết ấm và nhiều nắng. Một quả xoài chín thường có vỏ vàng, thịt mềm và mùi thơm ngọt.\n\nMọi người có thể ăn xoài chín như món tráng miệng hoặc dùng để làm nước ép, sinh tố, kem và các món ngọt. Xoài xanh thường được ăn với muối, ớt hoặc nước mắm. Xoài cũng được dùng trong các món gỏi tươi.\n\nXoài có hương vị đậm đà và chứa một số chất dinh dưỡng quan trọng. Nhiều gia đình Việt Nam thích ăn xoài vào mùa nóng. Màu sắc tươi sáng, mùi thơm dễ chịu và vị ngon khiến xoài trở thành loại trái cây được yêu thích."
  },
  {
    "text": "Chapter 3. Orange – Cam\nOranges are familiar fruits in Vietnam. They are round and usually have green, yellow, or orange skin. Inside, the fruit is divided into small sections filled with sweet or slightly sour juice.\n\nPeople often eat fresh oranges or squeeze them to make orange juice. A glass of orange juice is refreshing, especially on a hot day. Oranges can also be used in cakes, desserts, and fruit salads.\n\nOranges are well known for containing vitamin C. They are commonly sold in markets, supermarkets, and fruit shops. Their fresh smell and juicy taste make them popular with people of all ages.",
    "vi": "Chương 3. Cam\nCam là loại trái cây quen thuộc ở Việt Nam. Cam có hình tròn và thường có vỏ xanh, vàng hoặc cam. Bên trong, quả được chia thành các múi nhỏ chứa nước ngọt hoặc hơi chua.\n\nMọi người thường ăn cam tươi hoặc vắt để làm nước cam. Một ly nước cam rất sảng khoái, đặc biệt vào ngày nóng. Cam cũng có thể được dùng trong bánh, món tráng miệng và salad trái cây.\n\nCam nổi tiếng vì chứa vitamin C. Cam thường được bán ở chợ, siêu thị và cửa hàng trái cây. Mùi thơm tươi và vị mọng nước khiến cam được mọi lứa tuổi yêu thích."
  }
];
