const lessonVocabularyWords = [
  "watermelon",
  "dưa",
  "hấu",
  "watermelons",
  "large",
  "fruits",
  "green",
  "skin",
  "and",
  "juicy",
  "red",
  "or",
  "yellow",
  "flesh",
  "grown",
  "many",
  "parts",
  "vietnam",
  "especially",
  "popular",
  "hot",
  "weather",
  "because",
  "contain",
  "lot",
  "water",
  "vietnamese",
  "people",
  "usually",
  "cut",
  "slices",
  "eat",
  "fresh",
  "fruit",
  "can",
  "also",
  "used",
  "make",
  "juice",
  "smoothies",
  "ice",
  "cream",
  "colorful",
  "salads",
  "seeds",
  "sometimes",
  "roasted",
  "eaten",
  "snacks",
  "have",
  "sweet",
  "refreshing",
  "taste",
  "often",
  "placed",
  "family",
  "tables",
  "lunar",
  "new",
  "year",
  "color",
  "connected",
  "happiness",
  "luck",
  "good",
  "wishes",
  "papaya",
  "đu",
  "đủ",
  "papayas",
  "tropical",
  "commonly",
  "gardens",
  "ripe",
  "has",
  "orange",
  "soft",
  "inside",
  "there",
  "small",
  "black",
  "use",
  "desserts",
  "soups",
  "other",
  "traditional",
  "dishes",
  "easy",
  "grow",
  "available",
  "seasons",
  "texture",
  "gentle",
  "sweetness",
  "when",
  "both",
  "useful",
  "cooking",
  "pineapple",
  "dứa",
  "thơm",
  "khóm",
  "pineapples",
  "rough",
  "sharp",
  "leaves",
  "different",
  "call",
  "slightly",
  "sour",
  "remove",
  "pieces",
  "jam",
  "cakes",
  "added",
  "stir-fried",
  "strong",
  "pleasant",
  "smell",
  "flavor",
  "widely",
  "sold",
  "reasonable",
  "prices",
  "drinks",
  "meals"
];

const newVocabData = [
  {
    "id": 1,
    "word": "watermelon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝmˌɛlʌn/",
    "meaning": "dưa hấu",
    "ex1": "Watermelon seeds are sometimes roasted and eaten as snacks.",
    "ex1_vi": "Hạt dưa hấu đôi khi được rang và ăn như món ăn vặt."
  },
  {
    "id": 2,
    "word": "dưa",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dưa/",
    "meaning": "dưa",
    "ex1": "Vietnamese families often enjoy Dưa hấu during everyday meals and snacks.",
    "ex1_vi": "Các gia đình Việt Nam thường thưởng thức Dưa hấu trong các bữa ăn và món ăn nhẹ hằng ngày."
  },
  {
    "id": 3,
    "word": "hấu",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hấu/",
    "meaning": "hấu (trong 'dưa hấu')",
    "ex1": "Local markets often sell fresh Dưa hấu when this fruit is in season.",
    "ex1_vi": "Các chợ địa phương thường bán Dưa hấu tươi khi loại quả này vào mùa."
  },
  {
    "id": 4,
    "word": "watermelons",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝmˌɛlʌnz/",
    "meaning": "dưa hấu",
    "ex1": "Vietnamese people usually cut watermelons into slices and eat them fresh.",
    "ex1_vi": "Người Việt Nam thường cắt dưa hấu thành lát và ăn tươi."
  },
  {
    "id": 5,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒ/",
    "meaning": "lớn",
    "ex1": "Watermelons are large fruits with green skin and juicy red or yellow flesh.",
    "ex1_vi": "Dưa hấu là loại trái cây lớn có vỏ xanh và thịt quả mọng nước màu đỏ hoặc vàng."
  },
  {
    "id": 6,
    "word": "fruits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈuts/",
    "meaning": "trái cây",
    "ex1": "Pineapples are tropical fruits with rough skin and sharp green leaves.",
    "ex1_vi": "Dứa là loại trái cây nhiệt đới có vỏ sần sùi và lá xanh sắc."
  },
  {
    "id": 7,
    "word": "green",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈin/",
    "meaning": "màu xanh",
    "ex1": "Pineapples are tropical fruits with rough skin and sharp green leaves.",
    "ex1_vi": "Dứa là loại trái cây nhiệt đới có vỏ sần sùi và lá xanh sắc."
  },
  {
    "id": 8,
    "word": "skin",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪn/",
    "meaning": "vỏ",
    "ex1": "People usually remove the skin and cut pineapples into small pieces.",
    "ex1_vi": "Mọi người thường gọt vỏ và cắt dứa thành miếng nhỏ."
  },
  {
    "id": 9,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Vietnamese people usually cut watermelons into slices and eat them fresh.",
    "ex1_vi": "Người Việt Nam thường cắt dưa hấu thành lát và ăn tươi."
  },
  {
    "id": 10,
    "word": "juicy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈusi/",
    "meaning": "mọng nước",
    "ex1": "Watermelons are large fruits with green skin and juicy red or yellow flesh.",
    "ex1_vi": "Dưa hấu là loại trái cây lớn có vỏ xanh và thịt quả mọng nước màu đỏ hoặc vàng."
  },
  {
    "id": 11,
    "word": "red",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛd/",
    "meaning": "màu đỏ",
    "ex1": "Their red color is also connected with happiness, luck, and good wishes.",
    "ex1_vi": "Màu đỏ của dưa hấu cũng gắn với hạnh phúc, may mắn và những lời chúc tốt đẹp."
  },
  {
    "id": 12,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "A ripe papaya has yellow or orange skin and soft orange flesh.",
    "ex1_vi": "Một quả đu đủ chín có vỏ vàng hoặc cam và thịt quả màu cam mềm."
  },
  {
    "id": 13,
    "word": "yellow",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈɛloʊ/",
    "meaning": "màu vàng",
    "ex1": "The yellow flesh inside has a sweet and slightly sour taste.",
    "ex1_vi": "Phần thịt vàng bên trong có vị ngọt và hơi chua."
  },
  {
    "id": 14,
    "word": "flesh",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈɛʃ/",
    "meaning": "thịt quả",
    "ex1": "The yellow flesh inside has a sweet and slightly sour taste.",
    "ex1_vi": "Phần thịt vàng bên trong có vị ngọt và hơi chua."
  },
  {
    "id": 15,
    "word": "grown",
    "type": "past participle",
    "cat": "v",
    "phonetic": "/ɡrˈoʊn/",
    "meaning": "được trồng",
    "ex1": "They are widely grown in Vietnam and sold at reasonable prices.",
    "ex1_vi": "Dứa được trồng rộng rãi ở Việt Nam và bán với giá hợp lý."
  },
  {
    "id": 16,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Papayas are easy to grow and are available in many seasons.",
    "ex1_vi": "Đu đủ dễ trồng và có trong nhiều mùa."
  },
  {
    "id": 17,
    "word": "parts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrts/",
    "meaning": "phần",
    "ex1": "In different parts of Vietnam, people call this fruit dứa, thơm, or khóm.",
    "ex1_vi": "Ở các vùng khác nhau của Việt Nam, người ta gọi loại quả này là dứa, thơm hoặc khóm."
  },
  {
    "id": 18,
    "word": "vietnam",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/viˌɛtnˈɑm/",
    "meaning": "Việt Nam",
    "ex1": "They are widely grown in Vietnam and sold at reasonable prices.",
    "ex1_vi": "Dứa được trồng rộng rãi ở Việt Nam và bán với giá hợp lý."
  },
  {
    "id": 19,
    "word": "especially",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌspˈɛʃli/",
    "meaning": "đặc biệt",
    "ex1": "Watermelons are especially popular during hot weather because they contain a lot of water.",
    "ex1_vi": "Dưa hấu đặc biệt phổ biến trong thời tiết nóng vì chứa nhiều nước."
  },
  {
    "id": 20,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "This colorful fruit is popular in both drinks and meals.",
    "ex1_vi": "Loại trái cây nhiều màu sắc này phổ biến trong cả đồ uống lẫn bữa ăn."
  },
  {
    "id": 21,
    "word": "hot",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑt/",
    "meaning": "nóng",
    "ex1": "Watermelons are especially popular during hot weather because they contain a lot of water.",
    "ex1_vi": "Dưa hấu đặc biệt phổ biến trong thời tiết nóng vì chứa nhiều nước."
  },
  {
    "id": 22,
    "word": "weather",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɛðɝ/",
    "meaning": "thời tiết",
    "ex1": "Watermelons are especially popular during hot weather because they contain a lot of water; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Dưa hấu đặc biệt phổ biến trong thời tiết nóng vì chứa nhiều nước; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 23,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "Because they can be used when both green and ripe, papayas are useful fruits in Vietnamese cooking.",
    "ex1_vi": "Vì có thể dùng khi còn xanh lẫn khi chín, đu đủ là loại trái cây hữu ích trong nấu ăn Việt Nam."
  },
  {
    "id": 24,
    "word": "contain",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈeɪn/",
    "meaning": "chứa",
    "ex1": "Watermelons are especially popular during hot weather because they contain a lot of water; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Dưa hấu đặc biệt phổ biến trong thời tiết nóng vì chứa nhiều nước; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 25,
    "word": "lot",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɑt/",
    "meaning": "nhiều",
    "ex1": "Watermelons are especially popular during hot weather because they contain a lot of water; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Dưa hấu đặc biệt phổ biến trong thời tiết nóng vì chứa nhiều nước; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 26,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước",
    "ex1": "Watermelons are especially popular during hot weather because they contain a lot of water; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Dưa hấu đặc biệt phổ biến trong thời tiết nóng vì chứa nhiều nước; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 27,
    "word": "vietnamese",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/viˌɛtnɑmˈis/",
    "meaning": "thuộc Việt Nam; người Việt Nam",
    "ex1": "Papayas are tropical fruits commonly grown in Vietnamese gardens.",
    "ex1_vi": "Đu đủ là loại trái cây nhiệt đới thường được trồng trong các khu vườn Việt Nam."
  },
  {
    "id": 28,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "People also use them to make smoothies, desserts, and fruit salads.",
    "ex1_vi": "Mọi người cũng dùng đu đủ để làm sinh tố, món tráng miệng và salad trái cây."
  },
  {
    "id": 29,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "People usually remove the skin and cut pineapples into small pieces.",
    "ex1_vi": "Mọi người thường gọt vỏ và cắt dứa thành miếng nhỏ."
  },
  {
    "id": 30,
    "word": "cut",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌt/",
    "meaning": "cắt",
    "ex1": "Vietnamese people usually cut watermelons into slices and eat them fresh; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Người Việt Nam thường cắt dưa hấu thành lát và ăn tươi; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 31,
    "word": "slices",
    "type": "noun",
    "cat": "n",
    "phonetic": "/slˈaɪsʌz/",
    "meaning": "lát",
    "ex1": "Vietnamese people usually cut watermelons into slices and eat them fresh; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Người Việt Nam thường cắt dưa hấu thành lát và ăn tươi; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 32,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "Vietnamese people usually cut watermelons into slices and eat them fresh; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Người Việt Nam thường cắt dưa hấu thành lát và ăn tươi; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 33,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi",
    "ex1": "Ripe papayas are sweet and can be eaten fresh.",
    "ex1_vi": "Đu đủ chín ngọt và có thể ăn tươi."
  },
  {
    "id": 34,
    "word": "fruit",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈut/",
    "meaning": "trái cây; quả",
    "ex1": "People also use them to make smoothies, desserts, and fruit salads.",
    "ex1_vi": "Mọi người cũng dùng đu đủ để làm sinh tố, món tráng miệng và salad trái cây."
  },
  {
    "id": 35,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Ripe papayas are sweet and can be eaten fresh.",
    "ex1_vi": "Đu đủ chín ngọt và có thể ăn tươi."
  },
  {
    "id": 36,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "Their red color is also connected with happiness, luck, and good wishes.",
    "ex1_vi": "Màu đỏ của dưa hấu cũng gắn với hạnh phúc, may mắn và những lời chúc tốt đẹp."
  },
  {
    "id": 37,
    "word": "used",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzd/",
    "meaning": "được sử dụng",
    "ex1": "Green papayas are often used in salads, soups, and other traditional Vietnamese dishes.",
    "ex1_vi": "Đu đủ xanh thường được dùng trong gỏi, súp và các món truyền thống khác của Việt Nam."
  },
  {
    "id": 38,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm",
    "ex1": "Pineapples can be eaten fresh or used to make juice, jam, cakes, and fruit salads.",
    "ex1_vi": "Dứa có thể ăn tươi hoặc dùng để làm nước ép, mứt, bánh và salad trái cây."
  },
  {
    "id": 39,
    "word": "juice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈus/",
    "meaning": "nước ép",
    "ex1": "Pineapples can be eaten fresh or used to make juice, jam, cakes, and fruit salads.",
    "ex1_vi": "Dứa có thể ăn tươi hoặc dùng để làm nước ép, mứt, bánh và salad trái cây."
  },
  {
    "id": 40,
    "word": "smoothies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsmuːðiz/",
    "meaning": "sinh tố",
    "ex1": "The fruit can also be used to make juice, smoothies, ice cream, and colorful fruit salads.",
    "ex1_vi": "Quả cũng có thể được dùng để làm nước ép, sinh tố, kem và salad trái cây nhiều màu sắc."
  },
  {
    "id": 41,
    "word": "ice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪs/",
    "meaning": "kem; đá",
    "ex1": "The fruit can also be used to make juice, smoothies, ice cream, and colorful fruit salads.",
    "ex1_vi": "Quả cũng có thể được dùng để làm nước ép, sinh tố, kem và salad trái cây nhiều màu sắc."
  },
  {
    "id": 42,
    "word": "cream",
    "type": "noun",
    "cat": "n",
    "phonetic": "/krˈim/",
    "meaning": "kem",
    "ex1": "The fruit can also be used to make juice, smoothies, ice cream, and colorful fruit salads; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Quả cũng có thể được dùng để làm nước ép, sinh tố, kem và salad trái cây nhiều màu sắc; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 43,
    "word": "colorful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌlɝfʌl/",
    "meaning": "nhiều màu sắc",
    "ex1": "This colorful fruit is popular in both drinks and meals.",
    "ex1_vi": "Loại trái cây nhiều màu sắc này phổ biến trong cả đồ uống lẫn bữa ăn."
  },
  {
    "id": 44,
    "word": "salads",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈælʌdz/",
    "meaning": "salad; món gỏi",
    "ex1": "Green papayas are often used in salads, soups, and other traditional Vietnamese dishes.",
    "ex1_vi": "Đu đủ xanh thường được dùng trong gỏi, súp và các món truyền thống khác của Việt Nam."
  },
  {
    "id": 45,
    "word": "seeds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈidz/",
    "meaning": "hạt",
    "ex1": "Watermelon seeds are sometimes roasted and eaten as snacks.",
    "ex1_vi": "Hạt dưa hấu đôi khi được rang và ăn như món ăn vặt."
  },
  {
    "id": 46,
    "word": "sometimes",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sʌmtˈaɪmz/",
    "meaning": "đôi khi",
    "ex1": "Watermelon seeds are sometimes roasted and eaten as snacks; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Hạt dưa hấu đôi khi được rang và ăn như món ăn vặt; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 47,
    "word": "roasted",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rˈoʊstʌd/",
    "meaning": "được rang",
    "ex1": "Watermelon seeds are sometimes roasted and eaten as snacks; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Hạt dưa hấu đôi khi được rang và ăn như món ăn vặt; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 48,
    "word": "eaten",
    "type": "past participle",
    "cat": "v",
    "phonetic": "/ˈitʌn/",
    "meaning": "được ăn",
    "ex1": "Watermelon seeds are sometimes roasted and eaten as snacks; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Hạt dưa hấu đôi khi được rang và ăn như món ăn vặt; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 49,
    "word": "snacks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/snˈæks/",
    "meaning": "đồ ăn vặt",
    "ex1": "Watermelon seeds are sometimes roasted and eaten as snacks; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Hạt dưa hấu đôi khi được rang và ăn như món ăn vặt; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 50,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có",
    "ex1": "Pineapples have a strong, pleasant smell and a refreshing flavor.",
    "ex1_vi": "Dứa có mùi thơm mạnh, dễ chịu và hương vị sảng khoái."
  },
  {
    "id": 51,
    "word": "sweet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/swˈit/",
    "meaning": "ngọt",
    "ex1": "Watermelons have a sweet and refreshing taste.",
    "ex1_vi": "Dưa hấu có vị ngọt và sảng khoái."
  },
  {
    "id": 52,
    "word": "refreshing",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪfrˈɛʃɪŋ/",
    "meaning": "sảng khoái",
    "ex1": "Pineapples have a strong, pleasant smell and a refreshing flavor.",
    "ex1_vi": "Dứa có mùi thơm mạnh, dễ chịu và hương vị sảng khoái."
  },
  {
    "id": 53,
    "word": "taste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪst/",
    "meaning": "vị",
    "ex1": "Watermelons have a sweet and refreshing taste.",
    "ex1_vi": "Dưa hấu có vị ngọt và sảng khoái."
  },
  {
    "id": 54,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "They are often placed on family tables during the Lunar New Year.",
    "ex1_vi": "Chúng thường được đặt trên bàn gia đình trong dịp Tết Nguyên đán."
  },
  {
    "id": 55,
    "word": "placed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/plˈeɪst/",
    "meaning": "được đặt",
    "ex1": "They are often placed on family tables during the Lunar New Year.",
    "ex1_vi": "Chúng thường được đặt trên bàn gia đình trong dịp Tết Nguyên đán."
  },
  {
    "id": 56,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "They are often placed on family tables during the Lunar New Year; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Chúng thường được đặt trên bàn gia đình trong dịp Tết Nguyên đán; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 57,
    "word": "tables",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪbʌlz/",
    "meaning": "bàn",
    "ex1": "They are often placed on family tables during the Lunar New Year; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Chúng thường được đặt trên bàn gia đình trong dịp Tết Nguyên đán; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 58,
    "word": "lunar",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈunɝ/",
    "meaning": "âm lịch",
    "ex1": "They are often placed on family tables during the Lunar New Year; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Chúng thường được đặt trên bàn gia đình trong dịp Tết Nguyên đán; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 59,
    "word": "new",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈu/",
    "meaning": "mới",
    "ex1": "They are often placed on family tables during the Lunar New Year; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Chúng thường được đặt trên bàn gia đình trong dịp Tết Nguyên đán; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 60,
    "word": "year",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈɪr/",
    "meaning": "năm",
    "ex1": "They are often placed on family tables during the Lunar New Year; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Chúng thường được đặt trên bàn gia đình trong dịp Tết Nguyên đán; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 61,
    "word": "color",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌlɝ/",
    "meaning": "màu sắc",
    "ex1": "Their red color is also connected with happiness, luck, and good wishes; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Màu đỏ của dưa hấu cũng gắn với hạnh phúc, may mắn và những lời chúc tốt đẹp; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 62,
    "word": "connected",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌnˈɛktɪd/",
    "meaning": "được kết nối; liên quan",
    "ex1": "Their red color is also connected with happiness, luck, and good wishes; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Màu đỏ của dưa hấu cũng gắn với hạnh phúc, may mắn và những lời chúc tốt đẹp; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 63,
    "word": "happiness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈæpinʌs/",
    "meaning": "hạnh phúc",
    "ex1": "Their red color is also connected with happiness, luck, and good wishes; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Màu đỏ của dưa hấu cũng gắn với hạnh phúc, may mắn và những lời chúc tốt đẹp; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 64,
    "word": "luck",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈʌk/",
    "meaning": "may mắn",
    "ex1": "Their red color is also connected with happiness, luck, and good wishes; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Màu đỏ của dưa hấu cũng gắn với hạnh phúc, may mắn và những lời chúc tốt đẹp; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 65,
    "word": "good",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡˈʊd/",
    "meaning": "tốt",
    "ex1": "Their red color is also connected with happiness, luck, and good wishes; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Màu đỏ của dưa hấu cũng gắn với hạnh phúc, may mắn và những lời chúc tốt đẹp; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 66,
    "word": "wishes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɪʃɪz/",
    "meaning": "lời chúc",
    "ex1": "Their red color is also connected with happiness, luck, and good wishes; this fruit remains a familiar part of local food culture.",
    "ex1_vi": "Màu đỏ của dưa hấu cũng gắn với hạnh phúc, may mắn và những lời chúc tốt đẹp; loại quả này vẫn là một phần quen thuộc của văn hóa ẩm thực địa phương."
  },
  {
    "id": 67,
    "word": "papaya",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pʌpˈaɪʌ/",
    "meaning": "đu đủ",
    "ex1": "A ripe papaya has yellow or orange skin and soft orange flesh.",
    "ex1_vi": "Một quả đu đủ chín có vỏ vàng hoặc cam và thịt quả màu cam mềm."
  },
  {
    "id": 68,
    "word": "đu",
    "type": "noun",
    "cat": "n",
    "phonetic": "/đu/",
    "meaning": "đu (trong 'đu đủ')",
    "ex1": "Vietnamese families often enjoy Đu đủ during everyday meals and snacks.",
    "ex1_vi": "Các gia đình Việt Nam thường thưởng thức Đu đủ trong các bữa ăn và món ăn nhẹ hằng ngày."
  },
  {
    "id": 69,
    "word": "đủ",
    "type": "noun",
    "cat": "n",
    "phonetic": "/đủ/",
    "meaning": "đủ (trong 'đu đủ')",
    "ex1": "Local markets often sell fresh Đu đủ when this fruit is in season.",
    "ex1_vi": "Các chợ địa phương thường bán Đu đủ tươi khi loại quả này vào mùa."
  },
  {
    "id": 70,
    "word": "papayas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pʌpˈaɪʌz/",
    "meaning": "đu đủ",
    "ex1": "Papayas are easy to grow and are available in many seasons.",
    "ex1_vi": "Đu đủ dễ trồng và có trong nhiều mùa."
  },
  {
    "id": 71,
    "word": "tropical",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trˈɑpɪkʌl/",
    "meaning": "nhiệt đới",
    "ex1": "Papayas are tropical fruits commonly grown in Vietnamese gardens.",
    "ex1_vi": "Đu đủ là loại trái cây nhiệt đới thường được trồng trong các khu vườn Việt Nam."
  },
  {
    "id": 72,
    "word": "commonly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɑmʌnli/",
    "meaning": "thường",
    "ex1": "Papayas are tropical fruits commonly grown in Vietnamese gardens; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Đu đủ là loại trái cây nhiệt đới thường được trồng trong các khu vườn Việt Nam; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 73,
    "word": "gardens",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɑrdʌnz/",
    "meaning": "khu vườn",
    "ex1": "Papayas are tropical fruits commonly grown in Vietnamese gardens; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Đu đủ là loại trái cây nhiệt đới thường được trồng trong các khu vườn Việt Nam; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 74,
    "word": "ripe",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈaɪp/",
    "meaning": "chín",
    "ex1": "Because they can be used when both green and ripe, papayas are useful fruits in Vietnamese cooking.",
    "ex1_vi": "Vì có thể dùng khi còn xanh lẫn khi chín, đu đủ là loại trái cây hữu ích trong nấu ăn Việt Nam."
  },
  {
    "id": 75,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "A ripe papaya has yellow or orange skin and soft orange flesh; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Một quả đu đủ chín có vỏ vàng hoặc cam và thịt quả màu cam mềm; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 76,
    "word": "orange",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɔrʌndʒ/",
    "meaning": "cam; màu cam",
    "ex1": "A ripe papaya has yellow or orange skin and soft orange flesh; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Một quả đu đủ chín có vỏ vàng hoặc cam và thịt quả màu cam mềm; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 77,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "They have a soft texture and a gentle sweetness.",
    "ex1_vi": "Quả có kết cấu mềm và vị ngọt dịu."
  },
  {
    "id": 78,
    "word": "inside",
    "type": "adverb/preposition",
    "cat": "adv",
    "phonetic": "/ˌɪnsˈaɪd/",
    "meaning": "bên trong",
    "ex1": "Inside the fruit, there are many small black seeds.",
    "ex1_vi": "Bên trong quả có nhiều hạt nhỏ màu đen."
  },
  {
    "id": 79,
    "word": "there",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ðˈɛr/",
    "meaning": "ở đó",
    "ex1": "Inside the fruit, there are many small black seeds.",
    "ex1_vi": "Bên trong quả có nhiều hạt nhỏ màu đen."
  },
  {
    "id": 80,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "Inside the fruit, there are many small black seeds; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Bên trong quả có nhiều hạt nhỏ màu đen; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 81,
    "word": "black",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/blˈæk/",
    "meaning": "màu đen",
    "ex1": "Inside the fruit, there are many small black seeds; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Bên trong quả có nhiều hạt nhỏ màu đen; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 82,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "People also use them to make smoothies, desserts, and fruit salads; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Mọi người cũng dùng đu đủ để làm sinh tố, món tráng miệng và salad trái cây; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 83,
    "word": "desserts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪzˈɝts/",
    "meaning": "các món tráng miệng",
    "ex1": "People also use them to make smoothies, desserts, and fruit salads; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Mọi người cũng dùng đu đủ để làm sinh tố, món tráng miệng và salad trái cây; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 84,
    "word": "soups",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈups/",
    "meaning": "các món súp",
    "ex1": "They are also added to soups and stir-fried dishes.",
    "ex1_vi": "Dứa cũng được thêm vào súp và các món xào."
  },
  {
    "id": 85,
    "word": "other",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈʌðɝ/",
    "meaning": "khác",
    "ex1": "Green papayas are often used in salads, soups, and other traditional Vietnamese dishes; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Đu đủ xanh thường được dùng trong gỏi, súp và các món truyền thống khác của Việt Nam; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 86,
    "word": "traditional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trʌdˈɪʃʌnʌl/",
    "meaning": "truyền thống",
    "ex1": "Green papayas are often used in salads, soups, and other traditional Vietnamese dishes; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Đu đủ xanh thường được dùng trong gỏi, súp và các món truyền thống khác của Việt Nam; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 87,
    "word": "dishes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪʃʌz/",
    "meaning": "món ăn",
    "ex1": "They are also added to soups and stir-fried dishes.",
    "ex1_vi": "Dứa cũng được thêm vào súp và các món xào."
  },
  {
    "id": 88,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "Papayas are easy to grow and are available in many seasons; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Đu đủ dễ trồng và có trong nhiều mùa; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 89,
    "word": "grow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡrˈoʊ/",
    "meaning": "phát triển; trồng",
    "ex1": "Papayas are easy to grow and are available in many seasons; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Đu đủ dễ trồng và có trong nhiều mùa; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 90,
    "word": "available",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌvˈeɪlʌbʌl/",
    "meaning": "có sẵn",
    "ex1": "Papayas are easy to grow and are available in many seasons; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Đu đủ dễ trồng và có trong nhiều mùa; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 91,
    "word": "seasons",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈizʌnz/",
    "meaning": "các mùa",
    "ex1": "Papayas are easy to grow and are available in many seasons; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Đu đủ dễ trồng và có trong nhiều mùa; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 92,
    "word": "texture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛkstʃɝ/",
    "meaning": "kết cấu",
    "ex1": "They have a soft texture and a gentle sweetness.",
    "ex1_vi": "Quả có kết cấu mềm và vị ngọt dịu."
  },
  {
    "id": 93,
    "word": "gentle",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈɛntʌl/",
    "meaning": "dịu",
    "ex1": "They have a soft texture and a gentle sweetness; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Quả có kết cấu mềm và vị ngọt dịu; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 94,
    "word": "sweetness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/swˈitnʌs/",
    "meaning": "vị ngọt",
    "ex1": "They have a soft texture and a gentle sweetness; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Quả có kết cấu mềm và vị ngọt dịu; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 95,
    "word": "when",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈɛn/",
    "meaning": "khi",
    "ex1": "Because they can be used when both green and ripe, papayas are useful fruits in Vietnamese cooking; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Vì có thể dùng khi còn xanh lẫn khi chín, đu đủ là loại trái cây hữu ích trong nấu ăn Việt Nam; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 96,
    "word": "both",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/bˈoʊθ/",
    "meaning": "cả hai",
    "ex1": "Because they can be used when both green and ripe, papayas are useful fruits in Vietnamese cooking; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Vì có thể dùng khi còn xanh lẫn khi chín, đu đủ là loại trái cây hữu ích trong nấu ăn Việt Nam; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 97,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈusfʌl/",
    "meaning": "hữu ích",
    "ex1": "Because they can be used when both green and ripe, papayas are useful fruits in Vietnamese cooking; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Vì có thể dùng khi còn xanh lẫn khi chín, đu đủ là loại trái cây hữu ích trong nấu ăn Việt Nam; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 98,
    "word": "cooking",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/kˈʊkɪŋ/",
    "meaning": "nấu ăn",
    "ex1": "Because they can be used when both green and ripe, papayas are useful fruits in Vietnamese cooking; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Vì có thể dùng khi còn xanh lẫn khi chín, đu đủ là loại trái cây hữu ích trong nấu ăn Việt Nam; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 99,
    "word": "pineapple",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈaɪnˌæpʌl/",
    "meaning": "dứa; thơm; khóm",
    "ex1": "Vietnamese families often enjoy pineapple fresh during the local fruit season.",
    "ex1_vi": "Các gia đình Việt Nam thường thưởng thức pineapple tươi trong mùa trái cây địa phương."
  },
  {
    "id": 100,
    "word": "dứa",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dứa/",
    "meaning": "dứa",
    "ex1": "In different parts of Vietnam, people call this fruit dứa, thơm, or khóm.",
    "ex1_vi": "Ở các vùng khác nhau của Việt Nam, người ta gọi loại quả này là dứa, thơm hoặc khóm."
  },
  {
    "id": 101,
    "word": "thơm",
    "type": "noun",
    "cat": "n",
    "phonetic": "/thơm/",
    "meaning": "thơm",
    "ex1": "In different parts of Vietnam, people call this fruit dứa, thơm, or khóm; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Ở các vùng khác nhau của Việt Nam, người ta gọi loại quả này là dứa, thơm hoặc khóm; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 102,
    "word": "khóm",
    "type": "noun",
    "cat": "n",
    "phonetic": "/khóm/",
    "meaning": "khóm",
    "ex1": "In different parts of Vietnam, people call this fruit dứa, thơm, or khóm; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Ở các vùng khác nhau của Việt Nam, người ta gọi loại quả này là dứa, thơm hoặc khóm; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 103,
    "word": "pineapples",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈaɪnˌæpʌlz/",
    "meaning": "dứa; thơm; khóm",
    "ex1": "Pineapples are tropical fruits with rough skin and sharp green leaves; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Dứa là loại trái cây nhiệt đới có vỏ sần sùi và lá xanh sắc; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 104,
    "word": "rough",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈʌf/",
    "meaning": "sần sùi",
    "ex1": "Pineapples are tropical fruits with rough skin and sharp green leaves; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Dứa là loại trái cây nhiệt đới có vỏ sần sùi và lá xanh sắc; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 105,
    "word": "sharp",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʃˈɑrp/",
    "meaning": "sắc",
    "ex1": "Pineapples are tropical fruits with rough skin and sharp green leaves; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Dứa là loại trái cây nhiệt đới có vỏ sần sùi và lá xanh sắc; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 106,
    "word": "leaves",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈivz/",
    "meaning": "lá",
    "ex1": "Pineapples are tropical fruits with rough skin and sharp green leaves; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Dứa là loại trái cây nhiệt đới có vỏ sần sùi và lá xanh sắc; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 107,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "In different parts of Vietnam, people call this fruit dứa, thơm, or khóm; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Ở các vùng khác nhau của Việt Nam, người ta gọi loại quả này là dứa, thơm hoặc khóm; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 108,
    "word": "call",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈɔl/",
    "meaning": "gọi",
    "ex1": "In different parts of Vietnam, people call this fruit dứa, thơm, or khóm; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Ở các vùng khác nhau của Việt Nam, người ta gọi loại quả này là dứa, thơm hoặc khóm; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 109,
    "word": "slightly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/slˈaɪtli/",
    "meaning": "hơi; một chút",
    "ex1": "The yellow flesh inside has a sweet and slightly sour taste; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Phần thịt vàng bên trong có vị ngọt và hơi chua; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 110,
    "word": "sour",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈaʊɝ/",
    "meaning": "chua",
    "ex1": "The yellow flesh inside has a sweet and slightly sour taste; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Phần thịt vàng bên trong có vị ngọt và hơi chua; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 111,
    "word": "remove",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rimˈuv/",
    "meaning": "loại bỏ; gọt",
    "ex1": "People usually remove the skin and cut pineapples into small pieces; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Mọi người thường gọt vỏ và cắt dứa thành miếng nhỏ; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 112,
    "word": "pieces",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈisʌz/",
    "meaning": "miếng",
    "ex1": "People usually remove the skin and cut pineapples into small pieces; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Mọi người thường gọt vỏ và cắt dứa thành miếng nhỏ; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 113,
    "word": "jam",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈæm/",
    "meaning": "mứt",
    "ex1": "Pineapples can be eaten fresh or used to make juice, jam, cakes, and fruit salads; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Dứa có thể ăn tươi hoặc dùng để làm nước ép, mứt, bánh và salad trái cây; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 114,
    "word": "cakes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈeɪks/",
    "meaning": "bánh",
    "ex1": "Pineapples can be eaten fresh or used to make juice, jam, cakes, and fruit salads; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Dứa có thể ăn tươi hoặc dùng để làm nước ép, mứt, bánh và salad trái cây; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 115,
    "word": "added",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈædʌd/",
    "meaning": "được thêm",
    "ex1": "They are also added to soups and stir-fried dishes; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Dứa cũng được thêm vào súp và các món xào; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 116,
    "word": "stir-fried",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈstɜːr fraɪd/",
    "meaning": "xào",
    "ex1": "They are also added to soups and stir-fried dishes; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Dứa cũng được thêm vào súp và các món xào; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 117,
    "word": "strong",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/strˈɔŋ/",
    "meaning": "mạnh",
    "ex1": "Pineapples have a strong, pleasant smell and a refreshing flavor; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Dứa có mùi thơm mạnh, dễ chịu và hương vị sảng khoái; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 118,
    "word": "pleasant",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/plˈɛzʌnt/",
    "meaning": "dễ chịu",
    "ex1": "Pineapples have a strong, pleasant smell and a refreshing flavor; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Dứa có mùi thơm mạnh, dễ chịu và hương vị sảng khoái; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 119,
    "word": "smell",
    "type": "verb",
    "cat": "v",
    "phonetic": "/smˈɛl/",
    "meaning": "mùi",
    "ex1": "Pineapples have a strong, pleasant smell and a refreshing flavor; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Dứa có mùi thơm mạnh, dễ chịu và hương vị sảng khoái; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 120,
    "word": "flavor",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈeɪvɝ/",
    "meaning": "hương vị",
    "ex1": "Pineapples have a strong, pleasant smell and a refreshing flavor; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Dứa có mùi thơm mạnh, dễ chịu và hương vị sảng khoái; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 121,
    "word": "widely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈaɪdli/",
    "meaning": "rộng rãi",
    "ex1": "They are widely grown in Vietnam and sold at reasonable prices; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Dứa được trồng rộng rãi ở Việt Nam và bán với giá hợp lý; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 122,
    "word": "sold",
    "type": "past participle",
    "cat": "v",
    "phonetic": "/sˈoʊld/",
    "meaning": "được bán",
    "ex1": "They are widely grown in Vietnam and sold at reasonable prices; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Dứa được trồng rộng rãi ở Việt Nam và bán với giá hợp lý; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 123,
    "word": "reasonable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈizʌnʌbʌl/",
    "meaning": "hợp lý",
    "ex1": "They are widely grown in Vietnam and sold at reasonable prices; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Dứa được trồng rộng rãi ở Việt Nam và bán với giá hợp lý; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 124,
    "word": "prices",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈaɪsʌz/",
    "meaning": "giá",
    "ex1": "They are widely grown in Vietnam and sold at reasonable prices; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Dứa được trồng rộng rãi ở Việt Nam và bán với giá hợp lý; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 125,
    "word": "drinks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɪŋks/",
    "meaning": "đồ uống",
    "ex1": "This colorful fruit is popular in both drinks and meals; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Loại trái cây nhiều màu sắc này phổ biến trong cả đồ uống lẫn bữa ăn; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 126,
    "word": "meals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈilz/",
    "meaning": "bữa ăn",
    "ex1": "This colorful fruit is popular in both drinks and meals; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Loại trái cây nhiều màu sắc này phổ biến trong cả đồ uống lẫn bữa ăn; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  }
];

const newReadingVocabOrder = [
  "watermelon",
  "dưa",
  "hấu",
  "watermelons",
  "large",
  "fruits",
  "green",
  "skin",
  "and",
  "juicy",
  "red",
  "or",
  "yellow",
  "flesh",
  "grown",
  "many",
  "parts",
  "vietnam",
  "especially",
  "popular",
  "hot",
  "weather",
  "because",
  "contain",
  "lot",
  "water",
  "vietnamese",
  "people",
  "usually",
  "cut",
  "slices",
  "eat",
  "fresh",
  "fruit",
  "can",
  "also",
  "used",
  "make",
  "juice",
  "smoothies",
  "ice",
  "cream",
  "colorful",
  "salads",
  "seeds",
  "sometimes",
  "roasted",
  "eaten",
  "snacks",
  "have",
  "sweet",
  "refreshing",
  "taste",
  "often",
  "placed",
  "family",
  "tables",
  "lunar",
  "new",
  "year",
  "color",
  "connected",
  "happiness",
  "luck",
  "good",
  "wishes",
  "papaya",
  "đu",
  "đủ",
  "papayas",
  "tropical",
  "commonly",
  "gardens",
  "ripe",
  "has",
  "orange",
  "soft",
  "inside",
  "there",
  "small",
  "black",
  "use",
  "desserts",
  "soups",
  "other",
  "traditional",
  "dishes",
  "easy",
  "grow",
  "available",
  "seasons",
  "texture",
  "gentle",
  "sweetness",
  "when",
  "both",
  "useful",
  "cooking",
  "pineapple",
  "dứa",
  "thơm",
  "khóm",
  "pineapples",
  "rough",
  "sharp",
  "leaves",
  "different",
  "call",
  "slightly",
  "sour",
  "remove",
  "pieces",
  "jam",
  "cakes",
  "added",
  "stir-fried",
  "strong",
  "pleasant",
  "smell",
  "flavor",
  "widely",
  "sold",
  "reasonable",
  "prices",
  "drinks",
  "meals"
];
