const lessonVocabularyWords = [
  "guava",
  "ổi",
  "guavas",
  "common",
  "fruits",
  "vietnamese",
  "homes",
  "and",
  "gardens",
  "usually",
  "have",
  "green",
  "skin",
  "white",
  "or",
  "pink",
  "flesh",
  "some",
  "soft",
  "sweet",
  "while",
  "others",
  "crisp",
  "slightly",
  "sour",
  "people",
  "often",
  "cut",
  "slices",
  "eat",
  "salt",
  "chili",
  "can",
  "also",
  "used",
  "make",
  "juice",
  "smoothies",
  "jam",
  "fruit",
  "salads",
  "young",
  "especially",
  "popular",
  "fresh",
  "snacks",
  "smell",
  "contain",
  "many",
  "useful",
  "nutrients",
  "easy",
  "find",
  "local",
  "markets",
  "throughout",
  "year",
  "because",
  "crunchy",
  "affordable",
  "delicious",
  "enjoyed",
  "students",
  "families",
  "coconut",
  "dừa",
  "coconuts",
  "important",
  "tropical",
  "vietnam",
  "southern",
  "areas",
  "such",
  "ben",
  "tre",
  "has",
  "hard",
  "shell",
  "clear",
  "water",
  "inside",
  "trees",
  "grow",
  "well",
  "warm",
  "coastal",
  "regions",
  "refreshing",
  "use",
  "milk",
  "candy",
  "cakes",
  "soups",
  "drinks",
  "traditional",
  "dishes",
  "oil",
  "cooking",
  "personal",
  "care",
  "products",
  "almost",
  "every",
  "part",
  "tree",
  "leaves",
  "shells",
  "wood",
  "different",
  "reason",
  "valuable",
  "communities",
  "pomelo",
  "bưởi",
  "pomelos",
  "large",
  "citrus",
  "grown",
  "thick",
  "yellow",
  "juicy",
  "may",
  "light",
  "depending",
  "variety",
  "remove",
  "separate",
  "sections",
  "eaten",
  "added",
  "desserts",
  "sometimes",
  "tea",
  "hair-care",
  "gentle",
  "taste",
  "famous",
  "varieties",
  "include",
  "green-skin",
  "dien",
  "given",
  "gifts",
  "festivals",
  "family",
  "celebrations",
  "dragon",
  "thanh",
  "long",
  "one",
  "best-known",
  "bright",
  "parts",
  "look",
  "like",
  "small",
  "red",
  "purple",
  "tiny",
  "black",
  "seeds",
  "mild",
  "half",
  "spoon",
  "juices",
  "ice",
  "cream",
  "colorful",
  "widely",
  "provinces",
  "binh",
  "thuan",
  "unusual",
  "appearance",
  "makes",
  "attractive",
  "international",
  "visitors",
  "exports"
];

const newVocabData = [
  {
    "id": 1,
    "word": "guava",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡwˈɑvʌ/",
    "meaning": "ổi",
    "ex1": "Vietnamese families often enjoy guava fresh during the local fruit season.",
    "ex1_vi": "Các gia đình Việt Nam thường thưởng thức guava tươi trong mùa trái cây địa phương."
  },
  {
    "id": 2,
    "word": "ổi",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ổi/",
    "meaning": "ổi",
    "ex1": "Local markets often sell fresh Ổi when this fruit is in season.",
    "ex1_vi": "Các chợ địa phương thường bán Ổi tươi khi loại quả này vào mùa."
  },
  {
    "id": 3,
    "word": "guavas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡwˈɑvʌz/",
    "meaning": "ổi",
    "ex1": "Guavas have a fresh smell and contain many useful nutrients.",
    "ex1_vi": "Ổi có mùi thơm tươi và chứa nhiều chất dinh dưỡng hữu ích."
  },
  {
    "id": 4,
    "word": "common",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈɑmʌn/",
    "meaning": "phổ biến",
    "ex1": "Guavas are common fruits in Vietnamese homes and gardens.",
    "ex1_vi": "Ổi là loại trái cây phổ biến trong nhà và vườn của người Việt Nam."
  },
  {
    "id": 5,
    "word": "fruits",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈuts/",
    "meaning": "trái cây",
    "ex1": "Pomelos are large citrus fruits grown in many areas of Vietnam.",
    "ex1_vi": "Bưởi là loại trái cây họ cam quýt lớn được trồng ở nhiều khu vực của Việt Nam."
  },
  {
    "id": 6,
    "word": "vietnamese",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/viˌɛtnɑmˈis/",
    "meaning": "thuộc Việt Nam; người Việt Nam",
    "ex1": "For this reason, coconuts are valuable to many Vietnamese communities.",
    "ex1_vi": "Vì lý do này, dừa có giá trị đối với nhiều cộng đồng Việt Nam."
  },
  {
    "id": 7,
    "word": "homes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊmz/",
    "meaning": "nhà",
    "ex1": "Guavas are common fruits in Vietnamese homes and gardens.",
    "ex1_vi": "Ổi là loại trái cây phổ biến trong nhà và vườn của người Việt Nam."
  },
  {
    "id": 8,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Coconut leaves, shells, and wood are used to make different products.",
    "ex1_vi": "Lá dừa, vỏ dừa và gỗ được dùng để làm nhiều sản phẩm khác nhau."
  },
  {
    "id": 9,
    "word": "gardens",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɑrdʌnz/",
    "meaning": "khu vườn",
    "ex1": "Guavas are common fruits in Vietnamese homes and gardens; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Ổi là loại trái cây phổ biến trong nhà và vườn của người Việt Nam; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 10,
    "word": "usually",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/jˈuʒʌwʌli/",
    "meaning": "thường",
    "ex1": "They usually have green skin and white or pink flesh.",
    "ex1_vi": "Ổi thường có vỏ xanh và thịt trắng hoặc hồng."
  },
  {
    "id": 11,
    "word": "have",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæv/",
    "meaning": "có",
    "ex1": "They have thick green or yellow skin and juicy flesh inside.",
    "ex1_vi": "Bưởi có vỏ dày màu xanh hoặc vàng và thịt quả mọng nước bên trong."
  },
  {
    "id": 12,
    "word": "green",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɡrˈin/",
    "meaning": "màu xanh",
    "ex1": "They have thick green or yellow skin and juicy flesh inside.",
    "ex1_vi": "Bưởi có vỏ dày màu xanh hoặc vàng và thịt quả mọng nước bên trong."
  },
  {
    "id": 13,
    "word": "skin",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪn/",
    "meaning": "vỏ",
    "ex1": "They usually have green skin and white or pink flesh.",
    "ex1_vi": "Ổi thường có vỏ xanh và thịt trắng hoặc hồng."
  },
  {
    "id": 14,
    "word": "white",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈaɪt/",
    "meaning": "màu trắng",
    "ex1": "A coconut has a hard shell, white flesh, and clear water inside.",
    "ex1_vi": "Một quả dừa có vỏ cứng, cơm dừa trắng và nước trong bên trong."
  },
  {
    "id": 15,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "Pomelos can be eaten fresh or added to salads and desserts.",
    "ex1_vi": "Bưởi có thể được ăn tươi hoặc thêm vào salad và món tráng miệng."
  },
  {
    "id": 16,
    "word": "pink",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɪŋk/",
    "meaning": "màu hồng",
    "ex1": "The flesh may be white, pink, or light yellow, depending on the variety.",
    "ex1_vi": "Thịt quả có thể màu trắng, hồng hoặc vàng nhạt, tùy vào giống."
  },
  {
    "id": 17,
    "word": "flesh",
    "type": "noun",
    "cat": "n",
    "phonetic": "/flˈɛʃ/",
    "meaning": "thịt quả",
    "ex1": "A coconut has a hard shell, white flesh, and clear water inside.",
    "ex1_vi": "Một quả dừa có vỏ cứng, cơm dừa trắng và nước trong bên trong."
  },
  {
    "id": 18,
    "word": "some",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌm/",
    "meaning": "một số",
    "ex1": "Some guavas are soft and sweet, while others are crisp and slightly sour.",
    "ex1_vi": "Một số quả ổi mềm và ngọt, trong khi những quả khác giòn và hơi chua."
  },
  {
    "id": 19,
    "word": "soft",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɑft/",
    "meaning": "mềm",
    "ex1": "Some guavas are soft and sweet, while others are crisp and slightly sour.",
    "ex1_vi": "Một số quả ổi mềm và ngọt, trong khi những quả khác giòn và hơi chua."
  },
  {
    "id": 20,
    "word": "sweet",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/swˈit/",
    "meaning": "ngọt",
    "ex1": "Pomelos have a gentle sweet and slightly sour taste.",
    "ex1_vi": "Bưởi có vị ngọt dịu và hơi chua."
  },
  {
    "id": 21,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "Some guavas are soft and sweet, while others are crisp and slightly sour; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Một số quả ổi mềm và ngọt, trong khi những quả khác giòn và hơi chua; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 22,
    "word": "others",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈʌðɝz/",
    "meaning": "những quả/người khác",
    "ex1": "Some guavas are soft and sweet, while others are crisp and slightly sour; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Một số quả ổi mềm và ngọt, trong khi những quả khác giòn và hơi chua; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 23,
    "word": "crisp",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈɪsp/",
    "meaning": "giòn",
    "ex1": "Some guavas are soft and sweet, while others are crisp and slightly sour; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Một số quả ổi mềm và ngọt, trong khi những quả khác giòn và hơi chua; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 24,
    "word": "slightly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/slˈaɪtli/",
    "meaning": "hơi; một chút",
    "ex1": "Pomelos have a gentle sweet and slightly sour taste.",
    "ex1_vi": "Bưởi có vị ngọt dịu và hơi chua."
  },
  {
    "id": 25,
    "word": "sour",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈaʊɝ/",
    "meaning": "chua",
    "ex1": "Some guavas are soft and sweet, while others are crisp and slightly sour; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Một số quả ổi mềm và ngọt, trong khi những quả khác giòn và hơi chua; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 26,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "People usually remove the thick skin and separate the fruit into sections.",
    "ex1_vi": "Mọi người thường bóc lớp vỏ dày và tách quả thành các múi."
  },
  {
    "id": 27,
    "word": "often",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔfʌn/",
    "meaning": "thường",
    "ex1": "They are often given as gifts during festivals and family celebrations.",
    "ex1_vi": "Bưởi thường được tặng làm quà trong các lễ hội và dịp sum họp gia đình."
  },
  {
    "id": 28,
    "word": "cut",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kˈʌt/",
    "meaning": "cắt",
    "ex1": "People usually cut it in half and eat the flesh with a spoon.",
    "ex1_vi": "Mọi người thường cắt đôi quả và ăn phần thịt bằng thìa."
  },
  {
    "id": 29,
    "word": "slices",
    "type": "noun",
    "cat": "n",
    "phonetic": "/slˈaɪsʌz/",
    "meaning": "lát",
    "ex1": "Vietnamese people often cut guavas into slices and eat them with salt and chili.",
    "ex1_vi": "Người Việt Nam thường cắt ổi thành lát và ăn với muối và ớt."
  },
  {
    "id": 30,
    "word": "eat",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈit/",
    "meaning": "ăn",
    "ex1": "People usually cut it in half and eat the flesh with a spoon.",
    "ex1_vi": "Mọi người thường cắt đôi quả và ăn phần thịt bằng thìa."
  },
  {
    "id": 31,
    "word": "salt",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔlt/",
    "meaning": "muối",
    "ex1": "Vietnamese people often cut guavas into slices and eat them with salt and chili.",
    "ex1_vi": "Người Việt Nam thường cắt ổi thành lát và ăn với muối và ớt."
  },
  {
    "id": 32,
    "word": "chili",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tʃˈɪli/",
    "meaning": "ớt",
    "ex1": "Vietnamese people often cut guavas into slices and eat them with salt and chili; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Người Việt Nam thường cắt ổi thành lát và ăn với muối và ớt; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 33,
    "word": "can",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/kˈæn/",
    "meaning": "có thể",
    "ex1": "Pomelos can be eaten fresh or added to salads and desserts.",
    "ex1_vi": "Bưởi có thể được ăn tươi hoặc thêm vào salad và món tráng miệng."
  },
  {
    "id": 34,
    "word": "also",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlsoʊ/",
    "meaning": "cũng",
    "ex1": "Guavas can also be used to make juice, smoothies, jam, and fruit salads.",
    "ex1_vi": "Ổi cũng có thể được dùng để làm nước ép, sinh tố, mứt và salad trái cây."
  },
  {
    "id": 35,
    "word": "used",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈuzd/",
    "meaning": "được sử dụng",
    "ex1": "Coconut leaves, shells, and wood are used to make different products.",
    "ex1_vi": "Lá dừa, vỏ dừa và gỗ được dùng để làm nhiều sản phẩm khác nhau."
  },
  {
    "id": 36,
    "word": "make",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪk/",
    "meaning": "làm",
    "ex1": "Guavas can also be used to make juice, smoothies, jam, and fruit salads.",
    "ex1_vi": "Ổi cũng có thể được dùng để làm nước ép, sinh tố, mứt và salad trái cây."
  },
  {
    "id": 37,
    "word": "juice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈus/",
    "meaning": "nước ép",
    "ex1": "Guavas can also be used to make juice, smoothies, jam, and fruit salads; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Ổi cũng có thể được dùng để làm nước ép, sinh tố, mứt và salad trái cây; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 38,
    "word": "smoothies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈsmuːðiz/",
    "meaning": "sinh tố",
    "ex1": "It can also be used in smoothies, juices, ice cream, cakes, and colorful fruit salads.",
    "ex1_vi": "Thanh long cũng có thể được dùng trong sinh tố, nước ép, kem, bánh và salad trái cây nhiều màu sắc."
  },
  {
    "id": 39,
    "word": "jam",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈæm/",
    "meaning": "mứt",
    "ex1": "Guavas can also be used to make juice, smoothies, jam, and fruit salads; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Ổi cũng có thể được dùng để làm nước ép, sinh tố, mứt và salad trái cây; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 40,
    "word": "fruit",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈut/",
    "meaning": "trái cây; quả",
    "ex1": "People usually remove the thick skin and separate the fruit into sections.",
    "ex1_vi": "Mọi người thường bóc lớp vỏ dày và tách quả thành các múi."
  },
  {
    "id": 41,
    "word": "salads",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈælʌdz/",
    "meaning": "salad; món gỏi",
    "ex1": "It can also be used in smoothies, juices, ice cream, cakes, and colorful fruit salads.",
    "ex1_vi": "Thanh long cũng có thể được dùng trong sinh tố, nước ép, kem, bánh và salad trái cây nhiều màu sắc."
  },
  {
    "id": 42,
    "word": "young",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈʌŋ/",
    "meaning": "non; trẻ",
    "ex1": "Young guavas are especially popular as fresh snacks.",
    "ex1_vi": "Ổi non đặc biệt phổ biến như món ăn vặt tươi."
  },
  {
    "id": 43,
    "word": "especially",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ʌspˈɛʃli/",
    "meaning": "đặc biệt",
    "ex1": "Young guavas are especially popular as fresh snacks.",
    "ex1_vi": "Ổi non đặc biệt phổ biến như món ăn vặt tươi."
  },
  {
    "id": 44,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "Young guavas are especially popular as fresh snacks; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Ổi non đặc biệt phổ biến như món ăn vặt tươi; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 45,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "tươi",
    "ex1": "Guavas have a fresh smell and contain many useful nutrients.",
    "ex1_vi": "Ổi có mùi thơm tươi và chứa nhiều chất dinh dưỡng hữu ích."
  },
  {
    "id": 46,
    "word": "snacks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/snˈæks/",
    "meaning": "đồ ăn vặt",
    "ex1": "Pomelo skin is sometimes used to make sweet snacks, tea, or traditional hair-care products.",
    "ex1_vi": "Vỏ bưởi đôi khi được dùng để làm món ngọt, trà hoặc các sản phẩm chăm sóc tóc truyền thống."
  },
  {
    "id": 47,
    "word": "smell",
    "type": "verb",
    "cat": "v",
    "phonetic": "/smˈɛl/",
    "meaning": "mùi",
    "ex1": "Guavas have a fresh smell and contain many useful nutrients; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Ổi có mùi thơm tươi và chứa nhiều chất dinh dưỡng hữu ích; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 48,
    "word": "contain",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈeɪn/",
    "meaning": "chứa",
    "ex1": "Guavas have a fresh smell and contain many useful nutrients; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Ổi có mùi thơm tươi và chứa nhiều chất dinh dưỡng hữu ích; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 49,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "Pomelos are large citrus fruits grown in many areas of Vietnam.",
    "ex1_vi": "Bưởi là loại trái cây họ cam quýt lớn được trồng ở nhiều khu vực của Việt Nam."
  },
  {
    "id": 50,
    "word": "useful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈusfʌl/",
    "meaning": "hữu ích",
    "ex1": "Almost every part of the coconut tree can be useful.",
    "ex1_vi": "Gần như mọi bộ phận của cây dừa đều có thể hữu ích."
  },
  {
    "id": 51,
    "word": "nutrients",
    "type": "noun",
    "cat": "n",
    "phonetic": "/nˈutriʌnts/",
    "meaning": "chất dinh dưỡng",
    "ex1": "Guavas have a fresh smell and contain many useful nutrients; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Ổi có mùi thơm tươi và chứa nhiều chất dinh dưỡng hữu ích; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 52,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "They are easy to find in local markets throughout the year.",
    "ex1_vi": "Ổi dễ tìm ở các chợ địa phương quanh năm."
  },
  {
    "id": 53,
    "word": "find",
    "type": "verb",
    "cat": "v",
    "phonetic": "/fˈaɪnd/",
    "meaning": "phát hiện; tìm thấy",
    "ex1": "They are easy to find in local markets throughout the year.",
    "ex1_vi": "Ổi dễ tìm ở các chợ địa phương quanh năm."
  },
  {
    "id": 54,
    "word": "local",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈoʊkʌl/",
    "meaning": "địa phương",
    "ex1": "Its unusual appearance makes it attractive to local people and international visitors.",
    "ex1_vi": "Vẻ ngoài khác lạ khiến thanh long hấp dẫn với người dân địa phương và du khách quốc tế."
  },
  {
    "id": 55,
    "word": "markets",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɑrkʌts/",
    "meaning": "chợ; thị trường",
    "ex1": "Vietnam also exports dragon fruit to many markets.",
    "ex1_vi": "Việt Nam cũng xuất khẩu thanh long đến nhiều thị trường."
  },
  {
    "id": 56,
    "word": "throughout",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/θruˈaʊt/",
    "meaning": "suốt; xuyên suốt",
    "ex1": "They are easy to find in local markets throughout the year; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Ổi dễ tìm ở các chợ địa phương quanh năm; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 57,
    "word": "year",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈɪr/",
    "meaning": "năm",
    "ex1": "They are easy to find in local markets throughout the year; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Ổi dễ tìm ở các chợ địa phương quanh năm; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 58,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "Because they are crunchy, affordable, and delicious, guavas are enjoyed by many students and families.",
    "ex1_vi": "Vì giòn, giá phải chăng và ngon, ổi được nhiều học sinh và gia đình yêu thích."
  },
  {
    "id": 59,
    "word": "crunchy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/krˈʌntʃi/",
    "meaning": "giòn",
    "ex1": "Because they are crunchy, affordable, and delicious, guavas are enjoyed by many students and families.",
    "ex1_vi": "Vì giòn, giá phải chăng và ngon, ổi được nhiều học sinh và gia đình yêu thích."
  },
  {
    "id": 60,
    "word": "affordable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌfˈɔrdʌbʌl/",
    "meaning": "giá phải chăng",
    "ex1": "Because they are crunchy, affordable, and delicious, guavas are enjoyed by many students and families; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Vì giòn, giá phải chăng và ngon, ổi được nhiều học sinh và gia đình yêu thích; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 61,
    "word": "delicious",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dɪlˈɪʃʌs/",
    "meaning": "ngon",
    "ex1": "Because they are crunchy, affordable, and delicious, guavas are enjoyed by many students and families; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Vì giòn, giá phải chăng và ngon, ổi được nhiều học sinh và gia đình yêu thích; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 62,
    "word": "enjoyed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪd/",
    "meaning": "được yêu thích",
    "ex1": "Because they are crunchy, affordable, and delicious, guavas are enjoyed by many students and families; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Vì giòn, giá phải chăng và ngon, ổi được nhiều học sinh và gia đình yêu thích; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 63,
    "word": "students",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈudʌnts/",
    "meaning": "học sinh",
    "ex1": "Because they are crunchy, affordable, and delicious, guavas are enjoyed by many students and families; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Vì giòn, giá phải chăng và ngon, ổi được nhiều học sinh và gia đình yêu thích; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 64,
    "word": "families",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌliz/",
    "meaning": "các gia đình",
    "ex1": "Because they are crunchy, affordable, and delicious, guavas are enjoyed by many students and families; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Vì giòn, giá phải chăng và ngon, ổi được nhiều học sinh và gia đình yêu thích; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 65,
    "word": "coconut",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈoʊkʌnˌʌt/",
    "meaning": "dừa",
    "ex1": "Coconut oil is used in cooking and personal care products.",
    "ex1_vi": "Dầu dừa được dùng trong nấu ăn và các sản phẩm chăm sóc cá nhân."
  },
  {
    "id": 66,
    "word": "dừa",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dừa/",
    "meaning": "dừa",
    "ex1": "Vietnamese families often enjoy Dừa during everyday meals and snacks.",
    "ex1_vi": "Các gia đình Việt Nam thường thưởng thức Dừa trong các bữa ăn và món ăn nhẹ hằng ngày."
  },
  {
    "id": 67,
    "word": "coconuts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈoʊkʌnˌʌts/",
    "meaning": "dừa",
    "ex1": "For this reason, coconuts are valuable to many Vietnamese communities.",
    "ex1_vi": "Vì lý do này, dừa có giá trị đối với nhiều cộng đồng Việt Nam."
  },
  {
    "id": 68,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔrtʌnt/",
    "meaning": "quan trọng",
    "ex1": "Coconuts are important tropical fruits in Vietnam, especially in southern areas such as Ben Tre.",
    "ex1_vi": "Dừa là loại trái cây nhiệt đới quan trọng ở Việt Nam, đặc biệt tại các khu vực phía Nam như Bến Tre."
  },
  {
    "id": 69,
    "word": "tropical",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trˈɑpɪkʌl/",
    "meaning": "nhiệt đới",
    "ex1": "Dragon fruit is one of Vietnam’s best-known tropical fruits.",
    "ex1_vi": "Thanh long là một trong những loại trái cây nhiệt đới nổi tiếng nhất của Việt Nam."
  },
  {
    "id": 70,
    "word": "vietnam",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/viˌɛtnˈɑm/",
    "meaning": "Việt Nam",
    "ex1": "Dragon fruit is one of Vietnam’s best-known tropical fruits.",
    "ex1_vi": "Thanh long là một trong những loại trái cây nhiệt đới nổi tiếng nhất của Việt Nam."
  },
  {
    "id": 71,
    "word": "southern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈʌðɝn/",
    "meaning": "phía Nam",
    "ex1": "Coconuts are important tropical fruits in Vietnam, especially in southern areas such as Ben Tre.",
    "ex1_vi": "Dừa là loại trái cây nhiệt đới quan trọng ở Việt Nam, đặc biệt tại các khu vực phía Nam như Bến Tre."
  },
  {
    "id": 72,
    "word": "areas",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛriʌz/",
    "meaning": "khu vực",
    "ex1": "Coconuts are important tropical fruits in Vietnam, especially in southern areas such as Ben Tre; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Dừa là loại trái cây nhiệt đới quan trọng ở Việt Nam, đặc biệt tại các khu vực phía Nam như Bến Tre; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 73,
    "word": "such",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈʌtʃ/",
    "meaning": "như",
    "ex1": "This fruit is widely grown in provinces such as Binh Thuan and Long An.",
    "ex1_vi": "Loại quả này được trồng rộng rãi ở các tỉnh như Bình Thuận và Long An."
  },
  {
    "id": 74,
    "word": "ben",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈɛn/",
    "meaning": "Bến",
    "ex1": "Coconuts are important tropical fruits in Vietnam, especially in southern areas such as Ben Tre; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Dừa là loại trái cây nhiệt đới quan trọng ở Việt Nam, đặc biệt tại các khu vực phía Nam như Bến Tre; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 75,
    "word": "tre",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈeɪ/",
    "meaning": "Tre",
    "ex1": "Coconuts are important tropical fruits in Vietnam, especially in southern areas such as Ben Tre; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Dừa là loại trái cây nhiệt đới quan trọng ở Việt Nam, đặc biệt tại các khu vực phía Nam như Bến Tre; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 76,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "It has bright pink or yellow skin with green parts that look like small leaves.",
    "ex1_vi": "Quả có vỏ hồng hoặc vàng sáng với các phần màu xanh trông giống những chiếc lá nhỏ."
  },
  {
    "id": 77,
    "word": "hard",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/hˈɑrd/",
    "meaning": "cứng",
    "ex1": "A coconut has a hard shell, white flesh, and clear water inside; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Một quả dừa có vỏ cứng, cơm dừa trắng và nước trong bên trong; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 78,
    "word": "shell",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɛl/",
    "meaning": "vỏ cứng",
    "ex1": "A coconut has a hard shell, white flesh, and clear water inside; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Một quả dừa có vỏ cứng, cơm dừa trắng và nước trong bên trong; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 79,
    "word": "clear",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈɪr/",
    "meaning": "trong",
    "ex1": "A coconut has a hard shell, white flesh, and clear water inside; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Một quả dừa có vỏ cứng, cơm dừa trắng và nước trong bên trong; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 80,
    "word": "water",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɔtɝ/",
    "meaning": "nước",
    "ex1": "Fresh coconut water is sweet and refreshing.",
    "ex1_vi": "Nước dừa tươi ngọt và sảng khoái."
  },
  {
    "id": 81,
    "word": "inside",
    "type": "adverb/preposition",
    "cat": "adv",
    "phonetic": "/ˌɪnsˈaɪd/",
    "meaning": "bên trong",
    "ex1": "The flesh inside can be white, red, or purple with tiny black seeds.",
    "ex1_vi": "Thịt quả bên trong có thể màu trắng, đỏ hoặc tím với những hạt đen nhỏ."
  },
  {
    "id": 82,
    "word": "trees",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈiz/",
    "meaning": "cây",
    "ex1": "Coconut trees usually grow well in warm coastal regions.",
    "ex1_vi": "Cây dừa thường phát triển tốt ở các vùng ven biển ấm áp."
  },
  {
    "id": 83,
    "word": "grow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡrˈoʊ/",
    "meaning": "phát triển; trồng",
    "ex1": "Coconut trees usually grow well in warm coastal regions.",
    "ex1_vi": "Cây dừa thường phát triển tốt ở các vùng ven biển ấm áp."
  },
  {
    "id": 84,
    "word": "well",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈɛl/",
    "meaning": "tốt",
    "ex1": "Coconut trees usually grow well in warm coastal regions; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Cây dừa thường phát triển tốt ở các vùng ven biển ấm áp; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 85,
    "word": "warm",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈɔrm/",
    "meaning": "ấm",
    "ex1": "Coconut trees usually grow well in warm coastal regions; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Cây dừa thường phát triển tốt ở các vùng ven biển ấm áp; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 86,
    "word": "coastal",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈoʊstʌl/",
    "meaning": "ven biển",
    "ex1": "Coconut trees usually grow well in warm coastal regions; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Cây dừa thường phát triển tốt ở các vùng ven biển ấm áp; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 87,
    "word": "regions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈidʒʌnz/",
    "meaning": "vùng",
    "ex1": "Coconut trees usually grow well in warm coastal regions; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Cây dừa thường phát triển tốt ở các vùng ven biển ấm áp; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 88,
    "word": "refreshing",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rɪfrˈɛʃɪŋ/",
    "meaning": "sảng khoái",
    "ex1": "Fresh coconut water is sweet and refreshing.",
    "ex1_vi": "Nước dừa tươi ngọt và sảng khoái."
  },
  {
    "id": 89,
    "word": "use",
    "type": "verb",
    "cat": "v",
    "phonetic": "/jˈus/",
    "meaning": "sử dụng",
    "ex1": "People also use coconut flesh and coconut milk to make candy, cakes, sweet soups, drinks, and traditional dishes.",
    "ex1_vi": "Mọi người cũng dùng cơm dừa và nước cốt dừa để làm kẹo, bánh, chè, đồ uống và món ăn truyền thống."
  },
  {
    "id": 90,
    "word": "milk",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɪlk/",
    "meaning": "nước cốt dừa; sữa",
    "ex1": "People also use coconut flesh and coconut milk to make candy, cakes, sweet soups, drinks, and traditional dishes.",
    "ex1_vi": "Mọi người cũng dùng cơm dừa và nước cốt dừa để làm kẹo, bánh, chè, đồ uống và món ăn truyền thống."
  },
  {
    "id": 91,
    "word": "candy",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈændi/",
    "meaning": "kẹo",
    "ex1": "People also use coconut flesh and coconut milk to make candy, cakes, sweet soups, drinks, and traditional dishes; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Mọi người cũng dùng cơm dừa và nước cốt dừa để làm kẹo, bánh, chè, đồ uống và món ăn truyền thống; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 92,
    "word": "cakes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈeɪks/",
    "meaning": "bánh",
    "ex1": "People also use coconut flesh and coconut milk to make candy, cakes, sweet soups, drinks, and traditional dishes; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Mọi người cũng dùng cơm dừa và nước cốt dừa để làm kẹo, bánh, chè, đồ uống và món ăn truyền thống; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 93,
    "word": "soups",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈups/",
    "meaning": "các món súp",
    "ex1": "People also use coconut flesh and coconut milk to make candy, cakes, sweet soups, drinks, and traditional dishes; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Mọi người cũng dùng cơm dừa và nước cốt dừa để làm kẹo, bánh, chè, đồ uống và món ăn truyền thống; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 94,
    "word": "drinks",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈɪŋks/",
    "meaning": "đồ uống",
    "ex1": "People also use coconut flesh and coconut milk to make candy, cakes, sweet soups, drinks, and traditional dishes; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Mọi người cũng dùng cơm dừa và nước cốt dừa để làm kẹo, bánh, chè, đồ uống và món ăn truyền thống; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 95,
    "word": "traditional",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/trʌdˈɪʃʌnʌl/",
    "meaning": "truyền thống",
    "ex1": "Pomelo skin is sometimes used to make sweet snacks, tea, or traditional hair-care products.",
    "ex1_vi": "Vỏ bưởi đôi khi được dùng để làm món ngọt, trà hoặc các sản phẩm chăm sóc tóc truyền thống."
  },
  {
    "id": 96,
    "word": "dishes",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪʃʌz/",
    "meaning": "món ăn",
    "ex1": "People also use coconut flesh and coconut milk to make candy, cakes, sweet soups, drinks, and traditional dishes; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Mọi người cũng dùng cơm dừa và nước cốt dừa để làm kẹo, bánh, chè, đồ uống và món ăn truyền thống; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 97,
    "word": "oil",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔɪl/",
    "meaning": "dầu",
    "ex1": "Coconut oil is used in cooking and personal care products.",
    "ex1_vi": "Dầu dừa được dùng trong nấu ăn và các sản phẩm chăm sóc cá nhân."
  },
  {
    "id": 98,
    "word": "cooking",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/kˈʊkɪŋ/",
    "meaning": "nấu ăn",
    "ex1": "Coconut oil is used in cooking and personal care products; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Dầu dừa được dùng trong nấu ăn và các sản phẩm chăm sóc cá nhân; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 99,
    "word": "personal",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɝsɪnʌl/",
    "meaning": "cá nhân",
    "ex1": "Coconut oil is used in cooking and personal care products; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Dầu dừa được dùng trong nấu ăn và các sản phẩm chăm sóc cá nhân; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 100,
    "word": "care",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɛr/",
    "meaning": "chăm sóc",
    "ex1": "Coconut oil is used in cooking and personal care products; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Dầu dừa được dùng trong nấu ăn và các sản phẩm chăm sóc cá nhân; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 101,
    "word": "products",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑdʌkts/",
    "meaning": "sản phẩm",
    "ex1": "Coconut oil is used in cooking and personal care products; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Dầu dừa được dùng trong nấu ăn và các sản phẩm chăm sóc cá nhân; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 102,
    "word": "almost",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔlmˌoʊst/",
    "meaning": "gần như",
    "ex1": "Almost every part of the coconut tree can be useful.",
    "ex1_vi": "Gần như mọi bộ phận của cây dừa đều có thể hữu ích."
  },
  {
    "id": 103,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɝi/",
    "meaning": "mỗi",
    "ex1": "Almost every part of the coconut tree can be useful; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Gần như mọi bộ phận của cây dừa đều có thể hữu ích; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 104,
    "word": "part",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrt/",
    "meaning": "phần",
    "ex1": "Almost every part of the coconut tree can be useful; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Gần như mọi bộ phận của cây dừa đều có thể hữu ích; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 105,
    "word": "tree",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trˈi/",
    "meaning": "cây",
    "ex1": "Almost every part of the coconut tree can be useful; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Gần như mọi bộ phận của cây dừa đều có thể hữu ích; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 106,
    "word": "leaves",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈivz/",
    "meaning": "lá",
    "ex1": "It has bright pink or yellow skin with green parts that look like small leaves.",
    "ex1_vi": "Quả có vỏ hồng hoặc vàng sáng với các phần màu xanh trông giống những chiếc lá nhỏ."
  },
  {
    "id": 107,
    "word": "shells",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʃˈɛlz/",
    "meaning": "vỏ",
    "ex1": "Coconut leaves, shells, and wood are used to make different products; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Lá dừa, vỏ dừa và gỗ được dùng để làm nhiều sản phẩm khác nhau; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 108,
    "word": "wood",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈʊd/",
    "meaning": "gỗ",
    "ex1": "Coconut leaves, shells, and wood are used to make different products; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Lá dừa, vỏ dừa và gỗ được dùng để làm nhiều sản phẩm khác nhau; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 109,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "Coconut leaves, shells, and wood are used to make different products; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Lá dừa, vỏ dừa và gỗ được dùng để làm nhiều sản phẩm khác nhau; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 110,
    "word": "reason",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈizʌn/",
    "meaning": "lý do",
    "ex1": "For this reason, coconuts are valuable to many Vietnamese communities; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Vì lý do này, dừa có giá trị đối với nhiều cộng đồng Việt Nam; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 111,
    "word": "valuable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/vˈæljʌbʌl/",
    "meaning": "có giá trị",
    "ex1": "For this reason, coconuts are valuable to many Vietnamese communities; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Vì lý do này, dừa có giá trị đối với nhiều cộng đồng Việt Nam; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 112,
    "word": "communities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kʌmjˈunʌtiz/",
    "meaning": "cộng đồng",
    "ex1": "For this reason, coconuts are valuable to many Vietnamese communities; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Vì lý do này, dừa có giá trị đối với nhiều cộng đồng Việt Nam; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 113,
    "word": "pomelo",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈpɑːməloʊ/",
    "meaning": "bưởi",
    "ex1": "Famous varieties include green-skin pomelo and Dien pomelo.",
    "ex1_vi": "Các giống nổi tiếng gồm bưởi da xanh và bưởi Diễn."
  },
  {
    "id": 114,
    "word": "bưởi",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bưởi/",
    "meaning": "bưởi",
    "ex1": "Vietnamese families often enjoy Bưởi during everyday meals and snacks.",
    "ex1_vi": "Các gia đình Việt Nam thường thưởng thức Bưởi trong các bữa ăn và món ăn nhẹ hằng ngày."
  },
  {
    "id": 115,
    "word": "pomelos",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈpɑːməloʊz/",
    "meaning": "bưởi",
    "ex1": "Pomelos are large citrus fruits grown in many areas of Vietnam; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Bưởi là loại trái cây họ cam quýt lớn được trồng ở nhiều khu vực của Việt Nam; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 116,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒ/",
    "meaning": "lớn",
    "ex1": "Pomelos are large citrus fruits grown in many areas of Vietnam; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Bưởi là loại trái cây họ cam quýt lớn được trồng ở nhiều khu vực của Việt Nam; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 117,
    "word": "citrus",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪtrʌs/",
    "meaning": "họ cam quýt",
    "ex1": "Pomelos are large citrus fruits grown in many areas of Vietnam; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Bưởi là loại trái cây họ cam quýt lớn được trồng ở nhiều khu vực của Việt Nam; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 118,
    "word": "grown",
    "type": "past participle",
    "cat": "v",
    "phonetic": "/ɡrˈoʊn/",
    "meaning": "được trồng",
    "ex1": "This fruit is widely grown in provinces such as Binh Thuan and Long An.",
    "ex1_vi": "Loại quả này được trồng rộng rãi ở các tỉnh như Bình Thuận và Long An."
  },
  {
    "id": 119,
    "word": "thick",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/θˈɪk/",
    "meaning": "dày",
    "ex1": "They have thick green or yellow skin and juicy flesh inside; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Bưởi có vỏ dày màu xanh hoặc vàng và thịt quả mọng nước bên trong; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 120,
    "word": "yellow",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/jˈɛloʊ/",
    "meaning": "màu vàng",
    "ex1": "The flesh may be white, pink, or light yellow, depending on the variety.",
    "ex1_vi": "Thịt quả có thể màu trắng, hồng hoặc vàng nhạt, tùy vào giống."
  },
  {
    "id": 121,
    "word": "juicy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈusi/",
    "meaning": "mọng nước",
    "ex1": "They have thick green or yellow skin and juicy flesh inside; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Bưởi có vỏ dày màu xanh hoặc vàng và thịt quả mọng nước bên trong; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 122,
    "word": "may",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/mˈeɪ/",
    "meaning": "có thể",
    "ex1": "The flesh may be white, pink, or light yellow, depending on the variety; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Thịt quả có thể màu trắng, hồng hoặc vàng nhạt, tùy vào giống; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 123,
    "word": "light",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈaɪt/",
    "meaning": "nhạt; sáng",
    "ex1": "The flesh may be white, pink, or light yellow, depending on the variety; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Thịt quả có thể màu trắng, hồng hoặc vàng nhạt, tùy vào giống; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 124,
    "word": "depending",
    "type": "verb",
    "cat": "v",
    "phonetic": "/dɪpˈɛndɪŋ/",
    "meaning": "tùy thuộc",
    "ex1": "The flesh may be white, pink, or light yellow, depending on the variety; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Thịt quả có thể màu trắng, hồng hoặc vàng nhạt, tùy vào giống; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 125,
    "word": "variety",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vɝˈaɪʌti/",
    "meaning": "giống; loại",
    "ex1": "The flesh may be white, pink, or light yellow, depending on the variety; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Thịt quả có thể màu trắng, hồng hoặc vàng nhạt, tùy vào giống; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 126,
    "word": "remove",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rimˈuv/",
    "meaning": "loại bỏ; gọt",
    "ex1": "People usually remove the thick skin and separate the fruit into sections; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Mọi người thường bóc lớp vỏ dày và tách quả thành các múi; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 127,
    "word": "separate",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɛpɝˌeɪt/",
    "meaning": "tách",
    "ex1": "People usually remove the thick skin and separate the fruit into sections; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Mọi người thường bóc lớp vỏ dày và tách quả thành các múi; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 128,
    "word": "sections",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɛkʃʌnz/",
    "meaning": "múi; phần",
    "ex1": "People usually remove the thick skin and separate the fruit into sections; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Mọi người thường bóc lớp vỏ dày và tách quả thành các múi; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 129,
    "word": "eaten",
    "type": "past participle",
    "cat": "v",
    "phonetic": "/ˈitʌn/",
    "meaning": "được ăn",
    "ex1": "Pomelos can be eaten fresh or added to salads and desserts; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Bưởi có thể được ăn tươi hoặc thêm vào salad và món tráng miệng; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 130,
    "word": "added",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈædʌd/",
    "meaning": "được thêm",
    "ex1": "Pomelos can be eaten fresh or added to salads and desserts; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Bưởi có thể được ăn tươi hoặc thêm vào salad và món tráng miệng; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 131,
    "word": "desserts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dɪzˈɝts/",
    "meaning": "các món tráng miệng",
    "ex1": "Pomelos can be eaten fresh or added to salads and desserts; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Bưởi có thể được ăn tươi hoặc thêm vào salad và món tráng miệng; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 132,
    "word": "sometimes",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/sʌmtˈaɪmz/",
    "meaning": "đôi khi",
    "ex1": "Pomelo skin is sometimes used to make sweet snacks, tea, or traditional hair-care products; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Vỏ bưởi đôi khi được dùng để làm món ngọt, trà hoặc các sản phẩm chăm sóc tóc truyền thống; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 133,
    "word": "tea",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈi/",
    "meaning": "trà",
    "ex1": "Pomelo skin is sometimes used to make sweet snacks, tea, or traditional hair-care products; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Vỏ bưởi đôi khi được dùng để làm món ngọt, trà hoặc các sản phẩm chăm sóc tóc truyền thống; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 134,
    "word": "hair-care",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈher ker/",
    "meaning": "chăm sóc tóc",
    "ex1": "Pomelo skin is sometimes used to make sweet snacks, tea, or traditional hair-care products; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Vỏ bưởi đôi khi được dùng để làm món ngọt, trà hoặc các sản phẩm chăm sóc tóc truyền thống; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 135,
    "word": "gentle",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dʒˈɛntʌl/",
    "meaning": "dịu",
    "ex1": "Pomelos have a gentle sweet and slightly sour taste; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Bưởi có vị ngọt dịu và hơi chua; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 136,
    "word": "taste",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈeɪst/",
    "meaning": "vị",
    "ex1": "Dragon fruit has a mild, refreshing taste.",
    "ex1_vi": "Thanh long có vị dịu và sảng khoái."
  },
  {
    "id": 137,
    "word": "famous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈeɪmʌs/",
    "meaning": "nổi tiếng",
    "ex1": "Famous varieties include green-skin pomelo and Dien pomelo.",
    "ex1_vi": "Các giống nổi tiếng gồm bưởi da xanh và bưởi Diễn."
  },
  {
    "id": 138,
    "word": "varieties",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vɝˈaɪʌtiz/",
    "meaning": "các giống",
    "ex1": "Famous varieties include green-skin pomelo and Dien pomelo; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Các giống nổi tiếng gồm bưởi da xanh và bưởi Diễn; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 139,
    "word": "include",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪnklˈud/",
    "meaning": "bao gồm",
    "ex1": "Famous varieties include green-skin pomelo and Dien pomelo; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Các giống nổi tiếng gồm bưởi da xanh và bưởi Diễn; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 140,
    "word": "green-skin",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɡriːn skɪn/",
    "meaning": "da xanh",
    "ex1": "Famous varieties include green-skin pomelo and Dien pomelo; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Các giống nổi tiếng gồm bưởi da xanh và bưởi Diễn; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 141,
    "word": "dien",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/diːɛn/",
    "meaning": "Diễn",
    "ex1": "Famous varieties include green-skin pomelo and Dien pomelo; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Các giống nổi tiếng gồm bưởi da xanh và bưởi Diễn; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 142,
    "word": "given",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡˈɪvʌn/",
    "meaning": "được tặng",
    "ex1": "They are often given as gifts during festivals and family celebrations.",
    "ex1_vi": "Bưởi thường được tặng làm quà trong các lễ hội và dịp sum họp gia đình."
  },
  {
    "id": 143,
    "word": "gifts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈɪfts/",
    "meaning": "quà",
    "ex1": "They are often given as gifts during festivals and family celebrations; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Bưởi thường được tặng làm quà trong các lễ hội và dịp sum họp gia đình; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 144,
    "word": "festivals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɛstʌvʌlz/",
    "meaning": "lễ hội",
    "ex1": "They are often given as gifts during festivals and family celebrations; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Bưởi thường được tặng làm quà trong các lễ hội và dịp sum họp gia đình; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 145,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "They are often given as gifts during festivals and family celebrations; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Bưởi thường được tặng làm quà trong các lễ hội và dịp sum họp gia đình; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 146,
    "word": "celebrations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˌɛlʌbrˈeɪʃʌnz/",
    "meaning": "dịp kỷ niệm; lễ mừng",
    "ex1": "They are often given as gifts during festivals and family celebrations; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Bưởi thường được tặng làm quà trong các lễ hội và dịp sum họp gia đình; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 147,
    "word": "dragon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/drˈæɡʌn/",
    "meaning": "rồng; thanh long trong cụm 'dragon fruit'",
    "ex1": "Vietnam also exports dragon fruit to many markets.",
    "ex1_vi": "Việt Nam cũng xuất khẩu thanh long đến nhiều thị trường."
  },
  {
    "id": 148,
    "word": "thanh",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈæn/",
    "meaning": "thanh (trong 'thanh long')",
    "ex1": "Vietnamese families often enjoy Thanh Long during everyday meals and snacks.",
    "ex1_vi": "Các gia đình Việt Nam thường thưởng thức Thanh Long trong các bữa ăn và món ăn nhẹ hằng ngày."
  },
  {
    "id": 149,
    "word": "long",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɔŋ/",
    "meaning": "Long",
    "ex1": "This fruit is widely grown in provinces such as Binh Thuan and Long An; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Loại quả này được trồng rộng rãi ở các tỉnh như Bình Thuận và Long An; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 150,
    "word": "one",
    "type": "number/pronoun",
    "cat": "adj",
    "phonetic": "/wˈʌn/",
    "meaning": "một",
    "ex1": "Dragon fruit is one of Vietnam’s best-known tropical fruits; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Thanh long là một trong những loại trái cây nhiệt đới nổi tiếng nhất của Việt Nam; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 151,
    "word": "best-known",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌbest ˈnoʊn/",
    "meaning": "nổi tiếng nhất",
    "ex1": "Dragon fruit is one of Vietnam’s best-known tropical fruits; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Thanh long là một trong những loại trái cây nhiệt đới nổi tiếng nhất của Việt Nam; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 152,
    "word": "bright",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/brˈaɪt/",
    "meaning": "tươi sáng",
    "ex1": "It has bright pink or yellow skin with green parts that look like small leaves; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Quả có vỏ hồng hoặc vàng sáng với các phần màu xanh trông giống những chiếc lá nhỏ; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 153,
    "word": "parts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrts/",
    "meaning": "phần",
    "ex1": "It has bright pink or yellow skin with green parts that look like small leaves; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Quả có vỏ hồng hoặc vàng sáng với các phần màu xanh trông giống những chiếc lá nhỏ; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 154,
    "word": "look",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈʊk/",
    "meaning": "trông",
    "ex1": "It has bright pink or yellow skin with green parts that look like small leaves; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Quả có vỏ hồng hoặc vàng sáng với các phần màu xanh trông giống những chiếc lá nhỏ; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 155,
    "word": "like",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈaɪk/",
    "meaning": "giống như",
    "ex1": "It has bright pink or yellow skin with green parts that look like small leaves; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Quả có vỏ hồng hoặc vàng sáng với các phần màu xanh trông giống những chiếc lá nhỏ; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 156,
    "word": "small",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/smˈɔl/",
    "meaning": "nhỏ",
    "ex1": "It has bright pink or yellow skin with green parts that look like small leaves; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Quả có vỏ hồng hoặc vàng sáng với các phần màu xanh trông giống những chiếc lá nhỏ; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 157,
    "word": "red",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/rˈɛd/",
    "meaning": "màu đỏ",
    "ex1": "The flesh inside can be white, red, or purple with tiny black seeds.",
    "ex1_vi": "Thịt quả bên trong có thể màu trắng, đỏ hoặc tím với những hạt đen nhỏ."
  },
  {
    "id": 158,
    "word": "purple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɝpʌl/",
    "meaning": "màu tím",
    "ex1": "The flesh inside can be white, red, or purple with tiny black seeds; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Thịt quả bên trong có thể màu trắng, đỏ hoặc tím với những hạt đen nhỏ; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 159,
    "word": "tiny",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/tˈaɪni/",
    "meaning": "rất nhỏ",
    "ex1": "The flesh inside can be white, red, or purple with tiny black seeds; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Thịt quả bên trong có thể màu trắng, đỏ hoặc tím với những hạt đen nhỏ; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 160,
    "word": "black",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/blˈæk/",
    "meaning": "màu đen",
    "ex1": "The flesh inside can be white, red, or purple with tiny black seeds; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Thịt quả bên trong có thể màu trắng, đỏ hoặc tím với những hạt đen nhỏ; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 161,
    "word": "seeds",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈidz/",
    "meaning": "hạt",
    "ex1": "The flesh inside can be white, red, or purple with tiny black seeds; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Thịt quả bên trong có thể màu trắng, đỏ hoặc tím với những hạt đen nhỏ; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 162,
    "word": "mild",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈaɪld/",
    "meaning": "dịu",
    "ex1": "Dragon fruit has a mild, refreshing taste.",
    "ex1_vi": "Thanh long có vị dịu và sảng khoái."
  },
  {
    "id": 163,
    "word": "half",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈæf/",
    "meaning": "một nửa",
    "ex1": "People usually cut it in half and eat the flesh with a spoon; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Mọi người thường cắt đôi quả và ăn phần thịt bằng thìa; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 164,
    "word": "spoon",
    "type": "noun",
    "cat": "n",
    "phonetic": "/spˈun/",
    "meaning": "thìa",
    "ex1": "People usually cut it in half and eat the flesh with a spoon; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Mọi người thường cắt đôi quả và ăn phần thịt bằng thìa; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 165,
    "word": "juices",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˈusʌz/",
    "meaning": "các loại nước ép",
    "ex1": "It can also be used in smoothies, juices, ice cream, cakes, and colorful fruit salads; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Thanh long cũng có thể được dùng trong sinh tố, nước ép, kem, bánh và salad trái cây nhiều màu sắc; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 166,
    "word": "ice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈaɪs/",
    "meaning": "kem; đá",
    "ex1": "It can also be used in smoothies, juices, ice cream, cakes, and colorful fruit salads; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Thanh long cũng có thể được dùng trong sinh tố, nước ép, kem, bánh và salad trái cây nhiều màu sắc; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 167,
    "word": "cream",
    "type": "noun",
    "cat": "n",
    "phonetic": "/krˈim/",
    "meaning": "kem",
    "ex1": "It can also be used in smoothies, juices, ice cream, cakes, and colorful fruit salads; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Thanh long cũng có thể được dùng trong sinh tố, nước ép, kem, bánh và salad trái cây nhiều màu sắc; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 168,
    "word": "colorful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌlɝfʌl/",
    "meaning": "nhiều màu sắc",
    "ex1": "It can also be used in smoothies, juices, ice cream, cakes, and colorful fruit salads; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Thanh long cũng có thể được dùng trong sinh tố, nước ép, kem, bánh và salad trái cây nhiều màu sắc; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 169,
    "word": "widely",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/wˈaɪdli/",
    "meaning": "rộng rãi",
    "ex1": "This fruit is widely grown in provinces such as Binh Thuan and Long An; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Loại quả này được trồng rộng rãi ở các tỉnh như Bình Thuận và Long An; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 170,
    "word": "provinces",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈɑvʌnsʌz/",
    "meaning": "các tỉnh",
    "ex1": "This fruit is widely grown in provinces such as Binh Thuan and Long An; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Loại quả này được trồng rộng rãi ở các tỉnh như Bình Thuận và Long An; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 171,
    "word": "binh",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/bɪŋ/",
    "meaning": "Bình",
    "ex1": "This fruit is widely grown in provinces such as Binh Thuan and Long An; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Loại quả này được trồng rộng rãi ở các tỉnh như Bình Thuận và Long An; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 172,
    "word": "thuan",
    "type": "proper noun",
    "cat": "n",
    "phonetic": "/twɑːn/",
    "meaning": "Thuận",
    "ex1": "This fruit is widely grown in provinces such as Binh Thuan and Long An; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Loại quả này được trồng rộng rãi ở các tỉnh như Bình Thuận và Long An; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 173,
    "word": "unusual",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌnjˈuʒˌuʌl/",
    "meaning": "khác lạ",
    "ex1": "Its unusual appearance makes it attractive to local people and international visitors.",
    "ex1_vi": "Vẻ ngoài khác lạ khiến thanh long hấp dẫn với người dân địa phương và du khách quốc tế."
  },
  {
    "id": 174,
    "word": "appearance",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ʌpˈɪrʌns/",
    "meaning": "vẻ ngoài",
    "ex1": "Its unusual appearance makes it attractive to local people and international visitors; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Vẻ ngoài khác lạ khiến thanh long hấp dẫn với người dân địa phương và du khách quốc tế; loại quả này quen thuộc với nhiều người ở Việt Nam."
  },
  {
    "id": 175,
    "word": "makes",
    "type": "verb",
    "cat": "v",
    "phonetic": "/mˈeɪks/",
    "meaning": "làm cho",
    "ex1": "Its unusual appearance makes it attractive to local people and international visitors; many families enjoy this fruit when it is in season.",
    "ex1_vi": "Vẻ ngoài khác lạ khiến thanh long hấp dẫn với người dân địa phương và du khách quốc tế; nhiều gia đình thưởng thức loại quả này khi vào mùa."
  },
  {
    "id": 176,
    "word": "attractive",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ʌtrˈæktɪv/",
    "meaning": "hấp dẫn",
    "ex1": "Its unusual appearance makes it attractive to local people and international visitors; this fruit is commonly found at local markets in season.",
    "ex1_vi": "Vẻ ngoài khác lạ khiến thanh long hấp dẫn với người dân địa phương và du khách quốc tế; loại quả này thường có ở các chợ địa phương khi vào mùa."
  },
  {
    "id": 177,
    "word": "international",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪntɝnˈæʃʌnʌl/",
    "meaning": "quốc tế",
    "ex1": "Its unusual appearance makes it attractive to local people and international visitors; these qualities make the fruit easy to recognize.",
    "ex1_vi": "Vẻ ngoài khác lạ khiến thanh long hấp dẫn với người dân địa phương và du khách quốc tế; những đặc điểm này khiến loại quả dễ nhận biết."
  },
  {
    "id": 178,
    "word": "visitors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪzɪtɝz/",
    "meaning": "du khách",
    "ex1": "Its unusual appearance makes it attractive to local people and international visitors; people often enjoy this fruit fresh or in simple dishes.",
    "ex1_vi": "Vẻ ngoài khác lạ khiến thanh long hấp dẫn với người dân địa phương và du khách quốc tế; mọi người thường thưởng thức loại quả này tươi hoặc trong các món đơn giản."
  },
  {
    "id": 179,
    "word": "exports",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛkspɔrts/",
    "meaning": "xuất khẩu",
    "ex1": "Vietnam also exports dragon fruit to many markets; this fruit is familiar to many people in Vietnam.",
    "ex1_vi": "Việt Nam cũng xuất khẩu thanh long đến nhiều thị trường; loại quả này quen thuộc với nhiều người ở Việt Nam."
  }
];

const newReadingVocabOrder = [
  "guava",
  "ổi",
  "guavas",
  "common",
  "fruits",
  "vietnamese",
  "homes",
  "and",
  "gardens",
  "usually",
  "have",
  "green",
  "skin",
  "white",
  "or",
  "pink",
  "flesh",
  "some",
  "soft",
  "sweet",
  "while",
  "others",
  "crisp",
  "slightly",
  "sour",
  "people",
  "often",
  "cut",
  "slices",
  "eat",
  "salt",
  "chili",
  "can",
  "also",
  "used",
  "make",
  "juice",
  "smoothies",
  "jam",
  "fruit",
  "salads",
  "young",
  "especially",
  "popular",
  "fresh",
  "snacks",
  "smell",
  "contain",
  "many",
  "useful",
  "nutrients",
  "easy",
  "find",
  "local",
  "markets",
  "throughout",
  "year",
  "because",
  "crunchy",
  "affordable",
  "delicious",
  "enjoyed",
  "students",
  "families",
  "coconut",
  "dừa",
  "coconuts",
  "important",
  "tropical",
  "vietnam",
  "southern",
  "areas",
  "such",
  "ben",
  "tre",
  "has",
  "hard",
  "shell",
  "clear",
  "water",
  "inside",
  "trees",
  "grow",
  "well",
  "warm",
  "coastal",
  "regions",
  "refreshing",
  "use",
  "milk",
  "candy",
  "cakes",
  "soups",
  "drinks",
  "traditional",
  "dishes",
  "oil",
  "cooking",
  "personal",
  "care",
  "products",
  "almost",
  "every",
  "part",
  "tree",
  "leaves",
  "shells",
  "wood",
  "different",
  "reason",
  "valuable",
  "communities",
  "pomelo",
  "bưởi",
  "pomelos",
  "large",
  "citrus",
  "grown",
  "thick",
  "yellow",
  "juicy",
  "may",
  "light",
  "depending",
  "variety",
  "remove",
  "separate",
  "sections",
  "eaten",
  "added",
  "desserts",
  "sometimes",
  "tea",
  "hair-care",
  "gentle",
  "taste",
  "famous",
  "varieties",
  "include",
  "green-skin",
  "dien",
  "given",
  "gifts",
  "festivals",
  "family",
  "celebrations",
  "dragon",
  "thanh",
  "long",
  "one",
  "best-known",
  "bright",
  "parts",
  "look",
  "like",
  "small",
  "red",
  "purple",
  "tiny",
  "black",
  "seeds",
  "mild",
  "half",
  "spoon",
  "juices",
  "ice",
  "cream",
  "colorful",
  "widely",
  "provinces",
  "binh",
  "thuan",
  "unusual",
  "appearance",
  "makes",
  "attractive",
  "international",
  "visitors",
  "exports"
];
