const newEssayData = [
  {
    "text": "Chapter 7. Guava – Ổi\nGuavas are common fruits in Vietnamese homes and gardens. They usually have green skin and white or pink flesh. Some guavas are soft and sweet, while others are crisp and slightly sour.\n\nVietnamese people often cut guavas into slices and eat them with salt and chili. Guavas can also be used to make juice, smoothies, jam, and fruit salads. Young guavas are especially popular as fresh snacks.\n\nGuavas have a fresh smell and contain many useful nutrients. They are easy to find in local markets throughout the year. Because they are crunchy, affordable, and delicious, guavas are enjoyed by many students and families.",
    "vi": "Chương 7. Ổi\nỔi là loại trái cây phổ biến trong nhà và vườn của người Việt Nam. Ổi thường có vỏ xanh và thịt trắng hoặc hồng. Một số quả ổi mềm và ngọt, trong khi những quả khác giòn và hơi chua.\n\nNgười Việt Nam thường cắt ổi thành lát và ăn với muối và ớt. Ổi cũng có thể được dùng để làm nước ép, sinh tố, mứt và salad trái cây. Ổi non đặc biệt phổ biến như món ăn vặt tươi.\n\nỔi có mùi thơm tươi và chứa nhiều chất dinh dưỡng hữu ích. Ổi dễ tìm ở các chợ địa phương quanh năm. Vì giòn, giá phải chăng và ngon, ổi được nhiều học sinh và gia đình yêu thích."
  },
  {
    "text": "Chapter 8. Coconut – Dừa\nCoconuts are important tropical fruits in Vietnam, especially in southern areas such as Ben Tre. A coconut has a hard shell, white flesh, and clear water inside. Coconut trees usually grow well in warm coastal regions.\n\nFresh coconut water is sweet and refreshing. People also use coconut flesh and coconut milk to make candy, cakes, sweet soups, drinks, and traditional dishes. Coconut oil is used in cooking and personal care products.\n\nAlmost every part of the coconut tree can be useful. Coconut leaves, shells, and wood are used to make different products. For this reason, coconuts are valuable to many Vietnamese communities.",
    "vi": "Chương 8. Dừa\nDừa là loại trái cây nhiệt đới quan trọng ở Việt Nam, đặc biệt tại các khu vực phía Nam như Bến Tre. Một quả dừa có vỏ cứng, cơm dừa trắng và nước trong bên trong. Cây dừa thường phát triển tốt ở các vùng ven biển ấm áp.\n\nNước dừa tươi ngọt và sảng khoái. Mọi người cũng dùng cơm dừa và nước cốt dừa để làm kẹo, bánh, chè, đồ uống và món ăn truyền thống. Dầu dừa được dùng trong nấu ăn và các sản phẩm chăm sóc cá nhân.\n\nGần như mọi bộ phận của cây dừa đều có thể hữu ích. Lá dừa, vỏ dừa và gỗ được dùng để làm nhiều sản phẩm khác nhau. Vì lý do này, dừa có giá trị đối với nhiều cộng đồng Việt Nam."
  },
  {
    "text": "Chapter 9. Pomelo – Bưởi\nPomelos are large citrus fruits grown in many areas of Vietnam. They have thick green or yellow skin and juicy flesh inside. The flesh may be white, pink, or light yellow, depending on the variety.\n\nPeople usually remove the thick skin and separate the fruit into sections. Pomelos can be eaten fresh or added to salads and desserts. Pomelo skin is sometimes used to make sweet snacks, tea, or traditional hair-care products.\n\nPomelos have a gentle sweet and slightly sour taste. Famous varieties include green-skin pomelo and Dien pomelo. They are often given as gifts during festivals and family celebrations.",
    "vi": "Chương 9. Bưởi\nBưởi là loại trái cây họ cam quýt lớn được trồng ở nhiều khu vực của Việt Nam. Bưởi có vỏ dày màu xanh hoặc vàng và thịt quả mọng nước bên trong. Thịt quả có thể màu trắng, hồng hoặc vàng nhạt, tùy vào giống.\n\nMọi người thường bóc lớp vỏ dày và tách quả thành các múi. Bưởi có thể được ăn tươi hoặc thêm vào salad và món tráng miệng. Vỏ bưởi đôi khi được dùng để làm món ngọt, trà hoặc các sản phẩm chăm sóc tóc truyền thống.\n\nBưởi có vị ngọt dịu và hơi chua. Các giống nổi tiếng gồm bưởi da xanh và bưởi Diễn. Bưởi thường được tặng làm quà trong các lễ hội và dịp sum họp gia đình."
  },
  {
    "text": "Chapter 10. Dragon Fruit – Thanh Long\nDragon fruit is one of Vietnam’s best-known tropical fruits. It has bright pink or yellow skin with green parts that look like small leaves. The flesh inside can be white, red, or purple with tiny black seeds.\n\nDragon fruit has a mild, refreshing taste. People usually cut it in half and eat the flesh with a spoon. It can also be used in smoothies, juices, ice cream, cakes, and colorful fruit salads.\n\nThis fruit is widely grown in provinces such as Binh Thuan and Long An. Its unusual appearance makes it attractive to local people and international visitors. Vietnam also exports dragon fruit to many markets.",
    "vi": "Chương 10. Thanh long\nThanh long là một trong những loại trái cây nhiệt đới nổi tiếng nhất của Việt Nam. Quả có vỏ hồng hoặc vàng sáng với các phần màu xanh trông giống những chiếc lá nhỏ. Thịt quả bên trong có thể màu trắng, đỏ hoặc tím với những hạt đen nhỏ.\n\nThanh long có vị dịu và sảng khoái. Mọi người thường cắt đôi quả và ăn phần thịt bằng thìa. Thanh long cũng có thể được dùng trong sinh tố, nước ép, kem, bánh và salad trái cây nhiều màu sắc.\n\nLoại quả này được trồng rộng rãi ở các tỉnh như Bình Thuận và Long An. Vẻ ngoài khác lạ khiến thanh long hấp dẫn với người dân địa phương và du khách quốc tế. Việt Nam cũng xuất khẩu thanh long đến nhiều thị trường."
  }
];
