const newEssayData = [
  {
    "text": "Chapter 11. Durian – Sầu Riêng\nDurian is a famous tropical fruit in Vietnam. It has a large size, a hard shell, and many sharp thorns. Inside, the yellow flesh is soft, creamy, and rich in flavor.\n\nDurian has a very strong smell. Some people love it, while others find it difficult to enjoy. Vietnamese people eat fresh durian or use it to make cakes, sweet soups, ice cream, sticky rice, and smoothies.\n\nDurian is often called the “king of fruits.” It is grown mainly in warm southern and Central Highlands regions. Popular Vietnamese durians include Ri6 and Monthong. During the harvest season, many fruit lovers look forward to enjoying them.",
    "vi": "Chương 11. Sầu Riêng\nSầu riêng là một loại trái cây nhiệt đới nổi tiếng ở Việt Nam. Quả có kích thước lớn, vỏ cứng và nhiều gai sắc. Bên trong, phần thịt màu vàng mềm, béo mịn và đậm vị.\n\nSầu riêng có mùi rất mạnh. Một số người yêu thích nó, trong khi những người khác thấy khó thưởng thức. Người Việt Nam ăn sầu riêng tươi hoặc dùng để làm bánh, chè ngọt, kem, xôi và sinh tố.\n\nSầu riêng thường được gọi là “vua của các loại trái cây”. Nó được trồng chủ yếu ở các vùng ấm phía Nam và Tây Nguyên. Các giống sầu riêng Việt Nam phổ biến gồm Ri6 và Monthong. Trong mùa thu hoạch, nhiều người yêu trái cây mong chờ được thưởng thức chúng."
  },
  {
    "text": "Chapter 12. Rambutan – Chôm Chôm\nRambutans are colorful tropical fruits grown mainly in southern Vietnam. They are small and round, with red, yellow, or orange skin. The soft hairs on the skin make the fruit look unusual and interesting.\n\nAfter removing the skin, people can see the white, juicy flesh inside. Rambutans are usually eaten fresh, but they can also be used in sweet drinks, canned fruit, desserts, and fruit salads.\n\nRambutans have a sweet and slightly sour taste. They are often sold in large bunches at local markets during the fruit season. Their attractive appearance and refreshing flavor make them popular with children, adults, and visitors.",
    "vi": "Chương 12. Chôm Chôm\nChôm chôm là loại trái cây nhiệt đới nhiều màu sắc được trồng chủ yếu ở miền Nam Việt Nam. Quả nhỏ và tròn, có vỏ đỏ, vàng hoặc cam. Những sợi lông mềm trên vỏ làm quả trông khác lạ và thú vị.\n\nSau khi bóc vỏ, mọi người có thể thấy phần thịt trắng, mọng nước bên trong. Chôm chôm thường được ăn tươi, nhưng cũng có thể được dùng trong đồ uống ngọt, trái cây đóng hộp, món tráng miệng và salad trái cây.\n\nChôm chôm có vị ngọt và hơi chua. Chúng thường được bán thành chùm lớn tại các chợ địa phương trong mùa trái cây. Vẻ ngoài hấp dẫn và hương vị sảng khoái khiến chôm chôm được trẻ em, người lớn và du khách yêu thích."
  },
  {
    "text": "Chapter 13. Mangosteen – Măng Cụt\nMangosteen is a well-loved tropical fruit in Vietnam. It has thick, dark purple skin and soft white flesh inside. The flesh is divided into several small sections and has a sweet, gentle taste.\n\nPeople usually open the fruit carefully and eat the white sections fresh. Mangosteen can also be used in juice, smoothies, desserts, and fruit salads. Its thick skin is not normally eaten.\n\nMangosteen is sometimes called the “queen of fruits” because of its beautiful appearance and delicate flavor. It is mainly grown in southern Vietnam. During its short season, many people buy mangosteens for their families or give them as gifts.",
    "vi": "Chương 13. Măng Cụt\nMăng cụt là một loại trái cây nhiệt đới được yêu thích ở Việt Nam. Quả có vỏ dày màu tím sẫm và phần thịt trắng mềm bên trong. Phần thịt được chia thành vài múi nhỏ và có vị ngọt dịu.\n\nMọi người thường mở quả cẩn thận và ăn các múi trắng tươi. Măng cụt cũng có thể được dùng trong nước ép, sinh tố, món tráng miệng và salad trái cây. Lớp vỏ dày của quả thường không được ăn.\n\nMăng cụt đôi khi được gọi là “nữ hoàng của các loại trái cây” vì vẻ ngoài đẹp và hương vị tinh tế. Nó chủ yếu được trồng ở miền Nam Việt Nam. Trong mùa ngắn, nhiều người mua măng cụt cho gia đình hoặc tặng làm quà."
  }
];
