const newEssayData = [
  {
    "text": "7. Learning Music\nLearning music is a useful activity for children and adults everywhere. Music lessons help students improve listening skills, memory, and concentration. Regular practice also teaches patience and responsibility during the learning process every week.\n\nMany schools include music classes in their weekly schedules. Students learn songs, read simple music notes, and play different instruments together. Last semester, many classes performed beautiful songs for parents during a school celebration. Everyone enjoyed the performances and applauded warmly after every song.\n\nMore people will choose music lessons in the future. Online classes will make learning easier for busy students everywhere. Music education supports creativity, confidence, teamwork, and lifelong enjoyment for people of all ages together.",
    "vi": "7. Học âm nhạc\nHọc âm nhạc là một hoạt động hữu ích cho trẻ em và người lớn ở khắp nơi. Các bài học âm nhạc giúp học sinh cải thiện kỹ năng nghe, trí nhớ và sự tập trung. Luyện tập thường xuyên cũng dạy sự kiên nhẫn và trách nhiệm trong quá trình học mỗi tuần.\n\nNhiều trường học đưa lớp âm nhạc vào thời khóa biểu hằng tuần. Học sinh học các bài hát, đọc nốt nhạc đơn giản và cùng chơi các nhạc cụ khác nhau. Học kỳ trước, nhiều lớp đã biểu diễn những bài hát hay cho phụ huynh trong một lễ kỷ niệm ở trường. Mọi người thưởng thức các phần biểu diễn và vỗ tay nồng nhiệt sau mỗi bài hát.\n\nNhiều người hơn sẽ chọn học âm nhạc trong tương lai. Các lớp trực tuyến sẽ làm việc học dễ dàng hơn cho học sinh bận rộn ở khắp nơi. Giáo dục âm nhạc hỗ trợ sự sáng tạo, tự tin, làm việc nhóm và niềm vui học tập suốt đời cho mọi lứa tuổi."
  },
  {
    "text": "8. Famous Singers\nFamous singers inspire many people through their music and performances. They spend many hours practicing songs before recording albums or performing on stage. Strong voices, confidence, and hard work help singers achieve success in the music industry.\n\nMany singers perform at concerts, television shows, and charity events every year. Last month, several artists joined a special concert to raise money for children. Their performances attracted large audiences and encouraged many people to support the meaningful program together.\n\nMore talented singers will appear in the future because music education is improving. They will share different styles with global audiences. Their songs will continue bringing happiness, hope, and inspiration to listeners around the world every day.",
    "vi": "8. Ca sĩ nổi tiếng\nNhững ca sĩ nổi tiếng truyền cảm hứng cho nhiều người qua âm nhạc và phần biểu diễn của họ. Họ dành nhiều giờ luyện tập bài hát trước khi thu album hoặc biểu diễn trên sân khấu. Giọng hát mạnh mẽ, sự tự tin và chăm chỉ giúp ca sĩ đạt thành công trong ngành âm nhạc.\n\nNhiều ca sĩ biểu diễn tại các buổi hòa nhạc, chương trình truyền hình và sự kiện từ thiện mỗi năm. Tháng trước, một số nghệ sĩ tham gia một buổi hòa nhạc đặc biệt để gây quỹ cho trẻ em. Các phần biểu diễn của họ thu hút lượng khán giả lớn và khuyến khích nhiều người hỗ trợ chương trình ý nghĩa.\n\nNhiều ca sĩ tài năng hơn sẽ xuất hiện trong tương lai vì giáo dục âm nhạc đang được cải thiện. Họ sẽ chia sẻ các phong cách khác nhau với khán giả toàn cầu. Những bài hát của họ sẽ tiếp tục mang lại hạnh phúc, hy vọng và cảm hứng cho người nghe trên thế giới mỗi ngày."
  },
  {
    "text": "9. Music and Culture\nMusic is an important part of culture in every country around the world. Traditional songs tell stories about history, family, and local customs. Different cultures use music during celebrations, festivals, weddings, and many important community events every year.\n\nMany schools teach traditional songs to younger generations. Students learn about local culture while singing and playing simple musical instruments together. Last year, a cultural festival introduced traditional music from several countries. Visitors enjoyed every performance and learned interesting cultural differences through music.\n\nTraditional music will remain valuable in the future. More people will protect old songs and teach them to children. Music keeps cultural traditions alive and connects communities across different generations with pride and respect.",
    "vi": "9. Âm nhạc và văn hóa\nÂm nhạc là một phần quan trọng của văn hóa ở mọi quốc gia trên thế giới. Những bài hát truyền thống kể các câu chuyện về lịch sử, gia đình và phong tục địa phương. Các nền văn hóa khác nhau sử dụng âm nhạc trong lễ kỷ niệm, lễ hội, đám cưới và nhiều sự kiện cộng đồng quan trọng mỗi năm.\n\nNhiều trường dạy các bài hát truyền thống cho thế hệ trẻ. Học sinh tìm hiểu văn hóa địa phương trong khi hát và cùng chơi các nhạc cụ đơn giản. Năm ngoái, một lễ hội văn hóa giới thiệu âm nhạc truyền thống từ một số quốc gia. Du khách thưởng thức mỗi phần biểu diễn và học được những khác biệt văn hóa thú vị qua âm nhạc.\n\nÂm nhạc truyền thống sẽ vẫn có giá trị trong tương lai. Nhiều người hơn sẽ bảo vệ những bài hát cũ và dạy chúng cho trẻ em. Âm nhạc giữ cho truyền thống văn hóa sống mãi và kết nối các cộng đồng qua nhiều thế hệ với niềm tự hào và sự tôn trọng."
  },
  {
    "text": "10. The Future of Music\nMusic is changing because technology is developing very quickly today. People can discover new songs, watch performances, and listen to albums through digital platforms. Modern technology makes music available for listeners almost everywhere at any convenient time.\n\nMany artists now record songs in modern studios with advanced equipment. Last year, several musicians used online concerts to reach international audiences. These performances became popular because people could enjoy music without traveling long distances from home together.\n\nMusic will continue changing in the future with new ideas and technology. More artists will create creative songs and connect with larger audiences worldwide. Music will always remain an important part of entertainment, education, and cultural exchange for everyone.",
    "vi": "10. Tương lai của âm nhạc\nÂm nhạc đang thay đổi vì công nghệ đang phát triển rất nhanh hiện nay. Mọi người có thể khám phá bài hát mới, xem các phần biểu diễn và nghe album qua các nền tảng kỹ thuật số. Công nghệ hiện đại làm cho âm nhạc sẵn có với người nghe gần như mọi nơi vào bất kỳ thời điểm thuận tiện nào.\n\nNhiều nghệ sĩ hiện thu âm bài hát trong các phòng thu hiện đại với thiết bị tiên tiến. Năm ngoái, một số nhạc sĩ sử dụng các buổi hòa nhạc trực tuyến để tiếp cận khán giả quốc tế. Những phần biểu diễn này trở nên phổ biến vì mọi người có thể thưởng thức âm nhạc mà không cần di chuyển những quãng đường dài từ nhà.\n\nÂm nhạc sẽ tiếp tục thay đổi trong tương lai với những ý tưởng và công nghệ mới. Nhiều nghệ sĩ hơn sẽ tạo ra những bài hát sáng tạo và kết nối với lượng khán giả lớn hơn trên toàn thế giới. Âm nhạc sẽ luôn là một phần quan trọng của giải trí, giáo dục và trao đổi văn hóa cho mọi người."
  }
];
