const lessonVocabularyWords = [
  "pop",
  "music",
  "one",
  "most",
  "popular",
  "styles",
  "today",
  "has",
  "simple",
  "lyrics",
  "interesting",
  "melodies",
  "and",
  "easy",
  "rhythms",
  "many",
  "people",
  "enjoy",
  "listening",
  "songs",
  "home",
  "travel",
  "or",
  "while",
  "exercising",
  "every",
  "day",
  "famous",
  "singers",
  "release",
  "new",
  "year",
  "last",
  "summer",
  "several",
  "became",
  "television",
  "online",
  "platforms",
  "learned",
  "quickly",
  "sang",
  "together",
  "parties",
  "school",
  "activities",
  "brought",
  "happiness",
  "listeners",
  "everywhere",
  "will",
  "continue",
  "grow",
  "future",
  "create",
  "fresh",
  "different",
  "audiences",
  "modern",
  "technology",
  "help",
  "artists",
  "share",
  "around",
  "world",
  "more",
  "easily",
  "classical",
  "long",
  "history",
  "peaceful",
  "sound",
  "because",
  "helps",
  "relax",
  "think",
  "clearly",
  "orchestras",
  "perform",
  "large",
  "concert",
  "halls",
  "musicians",
  "spend",
  "years",
  "learning",
  "difficult",
  "pieces",
  "practice",
  "improve",
  "skills",
  "beautiful",
  "concerts",
  "students",
  "attended",
  "performance",
  "teachers",
  "listened",
  "carefully",
  "about",
  "musical",
  "instruments",
  "event",
  "remain",
  "important",
  "generations",
  "schools",
  "introduce",
  "composers",
  "wonderful",
  "performances",
  "teaches",
  "patience",
  "discipline",
  "appreciation",
  "artistic",
  "traditions",
  "festivals",
  "exciting",
  "events",
  "ages",
  "bands",
  "stages",
  "celebrations",
  "visitors",
  "food",
  "games",
  "friendly",
  "family",
  "members",
  "friends",
  "cities",
  "organize",
  "welcome",
  "local",
  "international",
  "weekend",
  "festival",
  "attracted",
  "thousands",
  "nearby",
  "towns",
  "colorful",
  "everyone",
  "enjoyed",
  "lively",
  "atmosphere",
  "throughout",
  "evening",
  "held",
  "countries",
  "next",
  "larger",
  "culture",
  "build",
  "friendships",
  "unforgettable",
  "memories",
  "celebration"
];

const newVocabData = [
  {
    "id": 1,
    "word": "pop",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑp/",
    "meaning": "nhạc pop",
    "ex1": "Many famous singers release new pop songs every year.",
    "ex1_vi": "Nhiều ca sĩ nổi tiếng phát hành các bài hát pop mới mỗi năm."
  },
  {
    "id": 2,
    "word": "music",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mjˈuzɪk/",
    "meaning": "âm nhạc",
    "ex1": "Classical music will remain important for future generations.",
    "ex1_vi": "Nhạc cổ điển sẽ vẫn quan trọng với các thế hệ tương lai."
  },
  {
    "id": 3,
    "word": "one",
    "type": "number/pronoun",
    "cat": "adj",
    "phonetic": "/wˈʌn/",
    "meaning": "một",
    "ex1": "Pop music is one of the most popular music styles today.",
    "ex1_vi": "Nhạc pop là một trong những phong cách âm nhạc phổ biến nhất hiện nay."
  },
  {
    "id": 4,
    "word": "most",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈoʊst/",
    "meaning": "nhất",
    "ex1": "Pop music is one of the most popular music styles today.",
    "ex1_vi": "Nhạc pop là một trong những phong cách âm nhạc phổ biến nhất hiện nay."
  },
  {
    "id": 5,
    "word": "popular",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈɑpjʌlɝ/",
    "meaning": "phổ biến",
    "ex1": "Students discuss popular during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về phổ biến trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 6,
    "word": "styles",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈaɪlz/",
    "meaning": "phong cách",
    "ex1": "Students discuss styles during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về phong cách trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 7,
    "word": "today",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌdˈeɪ/",
    "meaning": "ngày nay",
    "ex1": "Students discuss today during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về ngày nay trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 8,
    "word": "has",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈæz/",
    "meaning": "có",
    "ex1": "It has simple lyrics, interesting melodies, and easy rhythms.",
    "ex1_vi": "Nó có lời đơn giản, giai điệu thú vị và nhịp điệu dễ nghe."
  },
  {
    "id": 9,
    "word": "simple",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/sˈɪmpʌl/",
    "meaning": "đơn giản",
    "ex1": "It has simple lyrics, interesting melodies, and easy rhythms.",
    "ex1_vi": "Nó có lời đơn giản, giai điệu thú vị và nhịp điệu dễ nghe."
  },
  {
    "id": 10,
    "word": "lyrics",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɪrɪks/",
    "meaning": "lời bài hát",
    "ex1": "Students discuss lyrics during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về lời bài hát trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 11,
    "word": "interesting",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈɪntrʌstɪŋ/",
    "meaning": "thú vị",
    "ex1": "Students discuss interesting during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về thú vị trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 12,
    "word": "melodies",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛlʌdiz/",
    "meaning": "giai điệu",
    "ex1": "Students discuss melodies during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về giai điệu trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 13,
    "word": "and",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ʌnd/",
    "meaning": "và",
    "ex1": "Students discuss and during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về và trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 14,
    "word": "easy",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈizi/",
    "meaning": "dễ",
    "ex1": "Students discuss easy during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về dễ trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 15,
    "word": "rhythms",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rˈɪðʌmz/",
    "meaning": "nhịp điệu",
    "ex1": "Students discuss rhythms during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về nhịp điệu trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 16,
    "word": "many",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/mˈɛni/",
    "meaning": "nhiều",
    "ex1": "These songs brought happiness to many listeners everywhere.",
    "ex1_vi": "Những bài hát này mang lại hạnh phúc cho nhiều người nghe khắp nơi."
  },
  {
    "id": 17,
    "word": "people",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈipʌl/",
    "meaning": "mọi người",
    "ex1": "Music festivals are exciting events for people of different ages.",
    "ex1_vi": "Lễ hội âm nhạc là những sự kiện hào hứng dành cho người ở nhiều độ tuổi khác nhau."
  },
  {
    "id": 18,
    "word": "enjoy",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪ/",
    "meaning": "thích; thưởng thức",
    "ex1": "Students can enjoy during regular music lessons at school.",
    "ex1_vi": "Học sinh có thể thích; thưởng thức trong các giờ học âm nhạc thường xuyên ở trường."
  },
  {
    "id": 19,
    "word": "listening",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/lˈɪsʌnɪŋ/",
    "meaning": "nghe",
    "ex1": "Students learn about listening during regular music lessons.",
    "ex1_vi": "Học sinh học về nghe trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 20,
    "word": "songs",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɔŋz/",
    "meaning": "bài hát",
    "ex1": "These songs brought happiness to many listeners everywhere.",
    "ex1_vi": "Những bài hát này mang lại hạnh phúc cho nhiều người nghe khắp nơi."
  },
  {
    "id": 21,
    "word": "home",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈoʊm/",
    "meaning": "nhà",
    "ex1": "Students learn about home during regular music lessons.",
    "ex1_vi": "Học sinh học về nhà trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 22,
    "word": "travel",
    "type": "verb",
    "cat": "v",
    "phonetic": "/trˈævʌl/",
    "meaning": "du lịch",
    "ex1": "Students can travel during regular music lessons at school.",
    "ex1_vi": "Học sinh có thể du lịch trong các giờ học âm nhạc thường xuyên ở trường."
  },
  {
    "id": 23,
    "word": "or",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/ˈɔr/",
    "meaning": "hoặc",
    "ex1": "People can sing or play instruments during music lessons.",
    "ex1_vi": "Mọi người có thể hát hoặc chơi nhạc cụ trong giờ học âm nhạc."
  },
  {
    "id": 24,
    "word": "while",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/wˈaɪl/",
    "meaning": "trong khi",
    "ex1": "Soft music helps people relax while fast music gives energy.",
    "ex1_vi": "Nhạc nhẹ giúp mọi người thư giãn trong khi nhạc nhanh mang lại năng lượng."
  },
  {
    "id": 25,
    "word": "exercising",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɛksɝsˌaɪzɪŋ/",
    "meaning": "tập thể dục",
    "ex1": "Students learn about exercising during regular music lessons.",
    "ex1_vi": "Học sinh học về tập thể dục trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 26,
    "word": "every",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/ˈɛvɝi/",
    "meaning": "mỗi",
    "ex1": "Many famous singers release new pop songs every year.",
    "ex1_vi": "Nhiều ca sĩ nổi tiếng phát hành các bài hát pop mới mỗi năm."
  },
  {
    "id": 27,
    "word": "day",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈeɪ/",
    "meaning": "ngày",
    "ex1": "They practice every day to improve their skills and perform beautiful concerts.",
    "ex1_vi": "Họ luyện tập mỗi ngày để cải thiện kỹ năng và biểu diễn những buổi hòa nhạc hay."
  },
  {
    "id": 28,
    "word": "famous",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈeɪmʌs/",
    "meaning": "nổi tiếng",
    "ex1": "Students discuss famous during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về nổi tiếng trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 29,
    "word": "singers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪŋɝz/",
    "meaning": "ca sĩ",
    "ex1": "Students discuss singers during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về ca sĩ trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 30,
    "word": "release",
    "type": "noun",
    "cat": "n",
    "phonetic": "/rilˈis/",
    "meaning": "phát hành",
    "ex1": "Students discuss release during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về phát hành trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 31,
    "word": "new",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈu/",
    "meaning": "mới",
    "ex1": "Students discuss new during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về mới trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 32,
    "word": "year",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈɪr/",
    "meaning": "năm",
    "ex1": "Students discuss year during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về năm trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 33,
    "word": "last",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈæst/",
    "meaning": "trước",
    "ex1": "Last summer, several popular songs became famous on television and online platforms.",
    "ex1_vi": "Mùa hè năm ngoái, một số bài hát phổ biến trở nên nổi tiếng trên truyền hình và các nền tảng trực tuyến."
  },
  {
    "id": 34,
    "word": "summer",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈʌmɝ/",
    "meaning": "mùa hè",
    "ex1": "Last summer, several popular songs became famous on television and online platforms.",
    "ex1_vi": "Mùa hè năm ngoái, một số bài hát phổ biến trở nên nổi tiếng trên truyền hình và các nền tảng trực tuyến."
  },
  {
    "id": 35,
    "word": "several",
    "type": "determiner",
    "cat": "adj",
    "phonetic": "/sˈɛvrʌl/",
    "meaning": "một số",
    "ex1": "Students discuss several during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về một số trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 36,
    "word": "became",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bɪkˈeɪm/",
    "meaning": "đã trở nên",
    "ex1": "Students discuss became during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về đã trở nên trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 37,
    "word": "television",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈɛlʌvˌɪʒʌn/",
    "meaning": "truyền hình",
    "ex1": "Students discuss television during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về truyền hình trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 38,
    "word": "online",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɔnlˌaɪn/",
    "meaning": "trực tuyến",
    "ex1": "Students discuss online during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về trực tuyến trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 39,
    "word": "platforms",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈplætfɔːrmz/",
    "meaning": "nền tảng",
    "ex1": "Students discuss platforms during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về nền tảng trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 40,
    "word": "learned",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɝnd/",
    "meaning": "đã học",
    "ex1": "They listened carefully and learned about different musical instruments during the event.",
    "ex1_vi": "Họ lắng nghe cẩn thận và tìm hiểu về các nhạc cụ khác nhau trong sự kiện."
  },
  {
    "id": 41,
    "word": "quickly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kwˈɪkli/",
    "meaning": "nhanh chóng",
    "ex1": "Students quickly practice music during their weekly lessons.",
    "ex1_vi": "Học sinh nhanh chóng luyện tập âm nhạc trong các giờ học hằng tuần."
  },
  {
    "id": 42,
    "word": "sang",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈæŋ/",
    "meaning": "đã hát",
    "ex1": "Students learn about sang during regular music lessons.",
    "ex1_vi": "Học sinh học về đã hát trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 43,
    "word": "together",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/tʌɡˈɛðɝ/",
    "meaning": "cùng nhau",
    "ex1": "Students together practice music during their weekly lessons.",
    "ex1_vi": "Học sinh cùng nhau luyện tập âm nhạc trong các giờ học hằng tuần."
  },
  {
    "id": 44,
    "word": "parties",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈɑrtiz/",
    "meaning": "bữa tiệc",
    "ex1": "Students learn about parties during regular music lessons.",
    "ex1_vi": "Học sinh học về bữa tiệc trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 45,
    "word": "school",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈul/",
    "meaning": "trường học",
    "ex1": "Students learn about school during regular music lessons.",
    "ex1_vi": "Học sinh học về trường học trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 46,
    "word": "activities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/æktˈɪvʌtiz/",
    "meaning": "hoạt động",
    "ex1": "Students learn about activities during regular music lessons.",
    "ex1_vi": "Học sinh học về hoạt động trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 47,
    "word": "brought",
    "type": "noun",
    "cat": "n",
    "phonetic": "/brˈɔt/",
    "meaning": "đã mang lại",
    "ex1": "Students discuss brought during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về đã mang lại trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 48,
    "word": "happiness",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈæpinʌs/",
    "meaning": "hạnh phúc",
    "ex1": "Students discuss happiness during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về hạnh phúc trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 49,
    "word": "listeners",
    "type": "noun",
    "cat": "n",
    "phonetic": "/lˈɪsʌnɝz/",
    "meaning": "người nghe",
    "ex1": "Students discuss listeners during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về người nghe trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 50,
    "word": "everywhere",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈɛvriwˌɛr/",
    "meaning": "khắp nơi",
    "ex1": "Students discuss everywhere during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về khắp nơi trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 51,
    "word": "will",
    "type": "modal verb",
    "cat": "v",
    "phonetic": "/wˈɪl/",
    "meaning": "sẽ",
    "ex1": "Classical music will remain important for future generations.",
    "ex1_vi": "Nhạc cổ điển sẽ vẫn quan trọng với các thế hệ tương lai."
  },
  {
    "id": 52,
    "word": "continue",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kʌntˈɪnju/",
    "meaning": "tiếp tục",
    "ex1": "Pop music will continue to grow in the future.",
    "ex1_vi": "Nhạc pop sẽ tiếp tục phát triển trong tương lai."
  },
  {
    "id": 53,
    "word": "grow",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ɡrˈoʊ/",
    "meaning": "phát triển",
    "ex1": "Pop music will continue to grow in the future.",
    "ex1_vi": "Nhạc pop sẽ tiếp tục phát triển trong tương lai."
  },
  {
    "id": 54,
    "word": "future",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fjˈutʃɝ/",
    "meaning": "tương lai",
    "ex1": "Students discuss future during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về tương lai trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 55,
    "word": "create",
    "type": "verb",
    "cat": "v",
    "phonetic": "/kriˈeɪt/",
    "meaning": "tạo ra",
    "ex1": "New singers will create fresh songs for different audiences.",
    "ex1_vi": "Những ca sĩ mới sẽ tạo ra các bài hát mới mẻ cho những nhóm khán giả khác nhau."
  },
  {
    "id": 56,
    "word": "fresh",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛʃ/",
    "meaning": "mới mẻ",
    "ex1": "New singers will create fresh songs for different audiences.",
    "ex1_vi": "Những ca sĩ mới sẽ tạo ra các bài hát mới mẻ cho những nhóm khán giả khác nhau."
  },
  {
    "id": 57,
    "word": "different",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfɝʌnt/",
    "meaning": "khác nhau",
    "ex1": "Students discuss different during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về khác nhau trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 58,
    "word": "audiences",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɑdiʌnsʌz/",
    "meaning": "khán giả",
    "ex1": "Students discuss audiences during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về khán giả trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 59,
    "word": "modern",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/mˈɑdɝn/",
    "meaning": "hiện đại",
    "ex1": "This music activity is modern for students and listeners.",
    "ex1_vi": "Hoạt động âm nhạc này hiện đại đối với học sinh và người nghe."
  },
  {
    "id": 60,
    "word": "technology",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tɛknˈɑlʌdʒi/",
    "meaning": "công nghệ",
    "ex1": "Students learn about technology during regular music lessons.",
    "ex1_vi": "Học sinh học về công nghệ trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 61,
    "word": "help",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlp/",
    "meaning": "giúp",
    "ex1": "Students can help during regular music lessons at school.",
    "ex1_vi": "Học sinh có thể giúp trong các giờ học âm nhạc thường xuyên ở trường."
  },
  {
    "id": 62,
    "word": "artists",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɑrtɪsts/",
    "meaning": "nghệ sĩ",
    "ex1": "They will introduce new artists and different music styles to larger audiences.",
    "ex1_vi": "Chúng sẽ giới thiệu nghệ sĩ mới và các phong cách âm nhạc khác nhau tới lượng khán giả lớn hơn."
  },
  {
    "id": 63,
    "word": "share",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʃˈɛr/",
    "meaning": "chia sẻ",
    "ex1": "Students can share during regular music lessons at school.",
    "ex1_vi": "Học sinh có thể chia sẻ trong các giờ học âm nhạc thường xuyên ở trường."
  },
  {
    "id": 64,
    "word": "around",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ɝˈaʊnd/",
    "meaning": "xung quanh",
    "ex1": "Classical music has a long and interesting history around the world.",
    "ex1_vi": "Nhạc cổ điển có lịch sử lâu dài và thú vị trên thế giới."
  },
  {
    "id": 65,
    "word": "world",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈɝld/",
    "meaning": "thế giới",
    "ex1": "Classical music has a long and interesting history around the world.",
    "ex1_vi": "Nhạc cổ điển có lịch sử lâu dài và thú vị trên thế giới."
  },
  {
    "id": 66,
    "word": "more",
    "type": "determiner/adverb",
    "cat": "adj",
    "phonetic": "/mˈɔr/",
    "meaning": "nhiều hơn",
    "ex1": "More schools will introduce students to famous composers and wonderful performances.",
    "ex1_vi": "Nhiều trường học hơn sẽ giới thiệu cho học sinh những nhà soạn nhạc nổi tiếng và các buổi biểu diễn tuyệt vời."
  },
  {
    "id": 67,
    "word": "easily",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/ˈizʌli/",
    "meaning": "dễ dàng",
    "ex1": "Students easily practice music during their weekly lessons.",
    "ex1_vi": "Học sinh dễ dàng luyện tập âm nhạc trong các giờ học hằng tuần."
  },
  {
    "id": 68,
    "word": "classical",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/klˈæsɪkʌl/",
    "meaning": "cổ điển",
    "ex1": "Many classical musicians spend years learning difficult pieces.",
    "ex1_vi": "Nhiều nhạc sĩ cổ điển dành nhiều năm học những tác phẩm khó."
  },
  {
    "id": 69,
    "word": "long",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɔŋ/",
    "meaning": "dài",
    "ex1": "Students discuss long during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về dài trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 70,
    "word": "history",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɪstɝi/",
    "meaning": "lịch sử",
    "ex1": "Students discuss history during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về lịch sử trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 71,
    "word": "peaceful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/pˈisfʌl/",
    "meaning": "yên bình",
    "ex1": "This music activity is peaceful for students and listeners.",
    "ex1_vi": "Hoạt động âm nhạc này yên bình đối với học sinh và người nghe."
  },
  {
    "id": 72,
    "word": "sound",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈaʊnd/",
    "meaning": "âm thanh",
    "ex1": "Students learn about sound during regular music lessons.",
    "ex1_vi": "Học sinh học về âm thanh trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 73,
    "word": "because",
    "type": "conjunction",
    "cat": "conj",
    "phonetic": "/bɪkˈɔz/",
    "meaning": "bởi vì",
    "ex1": "Students practice because regular work improves their musical skills.",
    "ex1_vi": "Học sinh luyện tập vì công việc đều đặn giúp cải thiện kỹ năng âm nhạc."
  },
  {
    "id": 74,
    "word": "helps",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛlps/",
    "meaning": "giúp",
    "ex1": "Students discuss helps during regular music lessons at school.",
    "ex1_vi": "Học sinh thảo luận về giúp trong các giờ học âm nhạc thường xuyên ở trường."
  },
  {
    "id": 75,
    "word": "relax",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪlˈæks/",
    "meaning": "thư giãn",
    "ex1": "Students can relax during regular music lessons at school.",
    "ex1_vi": "Học sinh có thể thư giãn trong các giờ học âm nhạc thường xuyên ở trường."
  },
  {
    "id": 76,
    "word": "think",
    "type": "verb",
    "cat": "v",
    "phonetic": "/θˈɪŋk/",
    "meaning": "suy nghĩ",
    "ex1": "Students can think during regular music lessons at school.",
    "ex1_vi": "Học sinh có thể suy nghĩ trong các giờ học âm nhạc thường xuyên ở trường."
  },
  {
    "id": 77,
    "word": "clearly",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/klˈɪrli/",
    "meaning": "rõ ràng",
    "ex1": "Students clearly practice music during their weekly lessons.",
    "ex1_vi": "Học sinh rõ ràng luyện tập âm nhạc trong các giờ học hằng tuần."
  },
  {
    "id": 78,
    "word": "orchestras",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɔːrkɪstrəz/",
    "meaning": "dàn nhạc",
    "ex1": "Famous orchestras perform classical music in large concert halls every year.",
    "ex1_vi": "Những dàn nhạc nổi tiếng biểu diễn nhạc cổ điển tại các phòng hòa nhạc lớn mỗi năm."
  },
  {
    "id": 79,
    "word": "perform",
    "type": "verb",
    "cat": "v",
    "phonetic": "/pɝfˈɔrm/",
    "meaning": "biểu diễn",
    "ex1": "Famous orchestras perform classical music in large concert halls every year.",
    "ex1_vi": "Những dàn nhạc nổi tiếng biểu diễn nhạc cổ điển tại các phòng hòa nhạc lớn mỗi năm."
  },
  {
    "id": 80,
    "word": "large",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒ/",
    "meaning": "lớn",
    "ex1": "Students discuss large during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về lớn trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 81,
    "word": "concert",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑnsɝt/",
    "meaning": "hòa nhạc",
    "ex1": "Students discuss concert during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về hòa nhạc trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 82,
    "word": "halls",
    "type": "noun",
    "cat": "n",
    "phonetic": "/hˈɔlz/",
    "meaning": "phòng; hội trường",
    "ex1": "Students discuss halls during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về phòng; hội trường trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 83,
    "word": "musicians",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mjuzˈɪʃʌnz/",
    "meaning": "nhạc sĩ",
    "ex1": "Many classical musicians spend years learning difficult pieces.",
    "ex1_vi": "Nhiều nhạc sĩ cổ điển dành nhiều năm học những tác phẩm khó."
  },
  {
    "id": 84,
    "word": "spend",
    "type": "verb",
    "cat": "v",
    "phonetic": "/spˈɛnd/",
    "meaning": "dành",
    "ex1": "Students discuss spend during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về dành trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 85,
    "word": "years",
    "type": "noun",
    "cat": "n",
    "phonetic": "/jˈɪrz/",
    "meaning": "năm",
    "ex1": "Students discuss years during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về năm trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 86,
    "word": "learning",
    "type": "gerund",
    "cat": "v",
    "phonetic": "/lˈɝnɪŋ/",
    "meaning": "việc học",
    "ex1": "Students discuss learning during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về việc học trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 87,
    "word": "difficult",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/dˈɪfʌkʌlt/",
    "meaning": "khó",
    "ex1": "Students discuss difficult during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về khó trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 88,
    "word": "pieces",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈisʌz/",
    "meaning": "tác phẩm",
    "ex1": "Students discuss pieces during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về tác phẩm trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 89,
    "word": "practice",
    "type": "noun",
    "cat": "n",
    "phonetic": "/prˈæktʌs/",
    "meaning": "luyện tập",
    "ex1": "They practice every day to improve their skills and perform beautiful concerts.",
    "ex1_vi": "Họ luyện tập mỗi ngày để cải thiện kỹ năng và biểu diễn những buổi hòa nhạc hay."
  },
  {
    "id": 90,
    "word": "improve",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪmprˈuv/",
    "meaning": "cải thiện",
    "ex1": "Students discuss improve during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về cải thiện trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 91,
    "word": "skills",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈɪlz/",
    "meaning": "kỹ năng",
    "ex1": "Students discuss skills during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về kỹ năng trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 92,
    "word": "beautiful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/bjˈutʌfʌl/",
    "meaning": "hay; đẹp",
    "ex1": "Students discuss beautiful during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về hay; đẹp trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 93,
    "word": "concerts",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈɑnsɝts/",
    "meaning": "buổi hòa nhạc",
    "ex1": "Students discuss concerts during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về buổi hòa nhạc trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 94,
    "word": "students",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈudʌnts/",
    "meaning": "học sinh",
    "ex1": "More schools will introduce students to famous composers and wonderful performances.",
    "ex1_vi": "Nhiều trường học hơn sẽ giới thiệu cho học sinh những nhà soạn nhạc nổi tiếng và các buổi biểu diễn tuyệt vời."
  },
  {
    "id": 95,
    "word": "attended",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌtˈɛndɪd/",
    "meaning": "đã tham dự",
    "ex1": "Last year, many students attended a classical music performance with their teachers.",
    "ex1_vi": "Năm ngoái, nhiều học sinh tham dự một buổi biểu diễn nhạc cổ điển cùng giáo viên."
  },
  {
    "id": 96,
    "word": "performance",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɝfˈɔrmʌns/",
    "meaning": "phần biểu diễn",
    "ex1": "Last year, many students attended a classical music performance with their teachers.",
    "ex1_vi": "Năm ngoái, nhiều học sinh tham dự một buổi biểu diễn nhạc cổ điển cùng giáo viên."
  },
  {
    "id": 97,
    "word": "teachers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈitʃɝz/",
    "meaning": "giáo viên",
    "ex1": "Students discuss teachers during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về giáo viên trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 98,
    "word": "listened",
    "type": "verb",
    "cat": "v",
    "phonetic": "/lˈɪsʌnd/",
    "meaning": "đã lắng nghe",
    "ex1": "They listened carefully and learned about different musical instruments during the event.",
    "ex1_vi": "Họ lắng nghe cẩn thận và tìm hiểu về các nhạc cụ khác nhau trong sự kiện."
  },
  {
    "id": 99,
    "word": "carefully",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/kˈɛrfʌli/",
    "meaning": "cẩn thận",
    "ex1": "Students discuss carefully during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về cẩn thận trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 100,
    "word": "about",
    "type": "preposition",
    "cat": "adv",
    "phonetic": "/ʌbˈaʊt/",
    "meaning": "về",
    "ex1": "Students discuss about during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về về trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 101,
    "word": "musical",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˈmjuːzɪkəl/",
    "meaning": "thuộc âm nhạc",
    "ex1": "Students discuss musical during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về thuộc âm nhạc trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 102,
    "word": "instruments",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈɪnstrəmənts/",
    "meaning": "nhạc cụ",
    "ex1": "Students discuss instruments during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về nhạc cụ trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 103,
    "word": "event",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪvˈɛnt/",
    "meaning": "sự kiện",
    "ex1": "Students discuss event during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về sự kiện trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 104,
    "word": "remain",
    "type": "verb",
    "cat": "v",
    "phonetic": "/rɪmˈeɪn/",
    "meaning": "vẫn giữ",
    "ex1": "Students discuss remain during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về vẫn giữ trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 105,
    "word": "important",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪmpˈɔrtʌnt/",
    "meaning": "quan trọng",
    "ex1": "Students discuss important during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về quan trọng trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 106,
    "word": "generations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dʒˌɛnɝˈeɪʃʌnz/",
    "meaning": "thế hệ",
    "ex1": "Students discuss generations during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về thế hệ trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 107,
    "word": "schools",
    "type": "noun",
    "cat": "n",
    "phonetic": "/skˈulz/",
    "meaning": "trường học",
    "ex1": "Students discuss schools during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về trường học trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 108,
    "word": "introduce",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɪntrʌdˈus/",
    "meaning": "giới thiệu",
    "ex1": "Students discuss introduce during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về giới thiệu trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 109,
    "word": "composers",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kəmˈpoʊzərz/",
    "meaning": "nhà soạn nhạc",
    "ex1": "Students discuss composers during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về nhà soạn nhạc trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 110,
    "word": "wonderful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/wˈʌndɝfʌl/",
    "meaning": "tuyệt vời",
    "ex1": "Students discuss wonderful during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về tuyệt vời trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 111,
    "word": "performances",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pɝfˈɔrmʌnsʌz/",
    "meaning": "các phần biểu diễn",
    "ex1": "Students discuss performances during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về các phần biểu diễn trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 112,
    "word": "teaches",
    "type": "verb",
    "cat": "v",
    "phonetic": "/tˈitʃʌz/",
    "meaning": "dạy",
    "ex1": "Students discuss teaches during regular music lessons at school.",
    "ex1_vi": "Học sinh thảo luận về dạy trong các giờ học âm nhạc thường xuyên ở trường."
  },
  {
    "id": 113,
    "word": "patience",
    "type": "noun",
    "cat": "n",
    "phonetic": "/pˈeɪʃʌns/",
    "meaning": "sự kiên nhẫn",
    "ex1": "Students learn about patience during regular music lessons.",
    "ex1_vi": "Học sinh học về sự kiên nhẫn trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 114,
    "word": "discipline",
    "type": "noun",
    "cat": "n",
    "phonetic": "/dˈɪsʌplʌn/",
    "meaning": "kỷ luật",
    "ex1": "Students learn about discipline during regular music lessons.",
    "ex1_vi": "Học sinh học về kỷ luật trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 115,
    "word": "appreciation",
    "type": "noun",
    "cat": "n",
    "phonetic": "/əˌpriːʃiˈeɪʃən/",
    "meaning": "sự trân trọng",
    "ex1": "Students learn about appreciation during regular music lessons.",
    "ex1_vi": "Học sinh học về sự trân trọng trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 116,
    "word": "artistic",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɑrtˈɪstɪk/",
    "meaning": "thuộc nghệ thuật",
    "ex1": "Students learn about artistic during regular music lessons.",
    "ex1_vi": "Học sinh học về thuộc nghệ thuật trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 117,
    "word": "traditions",
    "type": "noun",
    "cat": "n",
    "phonetic": "/trʌdˈɪʃʌnz/",
    "meaning": "truyền thống",
    "ex1": "Students learn about traditions during regular music lessons.",
    "ex1_vi": "Học sinh học về truyền thống trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 118,
    "word": "festivals",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈɛstʌvʌlz/",
    "meaning": "lễ hội",
    "ex1": "Music festivals are exciting events for people of different ages.",
    "ex1_vi": "Lễ hội âm nhạc là những sự kiện hào hứng dành cho người ở nhiều độ tuổi khác nhau."
  },
  {
    "id": 119,
    "word": "exciting",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ɪksˈaɪtɪŋ/",
    "meaning": "hào hứng",
    "ex1": "Students discuss exciting during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về hào hứng trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 120,
    "word": "events",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɪvˈɛnts/",
    "meaning": "sự kiện",
    "ex1": "Students discuss events during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về sự kiện trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 121,
    "word": "ages",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈeɪdʒʌz/",
    "meaning": "độ tuổi",
    "ex1": "Students discuss ages during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về độ tuổi trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 122,
    "word": "bands",
    "type": "noun",
    "cat": "n",
    "phonetic": "/bˈændz/",
    "meaning": "ban nhạc",
    "ex1": "Many singers and bands perform on large stages during these celebrations.",
    "ex1_vi": "Nhiều ca sĩ và ban nhạc biểu diễn trên các sân khấu lớn trong những dịp lễ này."
  },
  {
    "id": 123,
    "word": "stages",
    "type": "noun",
    "cat": "n",
    "phonetic": "/stˈeɪdʒʌz/",
    "meaning": "sân khấu",
    "ex1": "Many singers and bands perform on large stages during these celebrations.",
    "ex1_vi": "Nhiều ca sĩ và ban nhạc biểu diễn trên các sân khấu lớn trong những dịp lễ này."
  },
  {
    "id": 124,
    "word": "celebrations",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˌsɛləˈbreɪʃənz/",
    "meaning": "lễ kỷ niệm",
    "ex1": "Students discuss celebrations during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về lễ kỷ niệm trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 125,
    "word": "visitors",
    "type": "noun",
    "cat": "n",
    "phonetic": "/vˈɪzɪtɝz/",
    "meaning": "du khách",
    "ex1": "Last weekend, a famous festival attracted thousands of visitors from nearby towns.",
    "ex1_vi": "Cuối tuần trước, một lễ hội nổi tiếng thu hút hàng nghìn du khách từ các thị trấn lân cận."
  },
  {
    "id": 126,
    "word": "food",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈud/",
    "meaning": "thức ăn",
    "ex1": "Students learn about food during regular music lessons.",
    "ex1_vi": "Học sinh học về thức ăn trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 127,
    "word": "games",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ɡˈeɪmz/",
    "meaning": "trò chơi",
    "ex1": "Students learn about games during regular music lessons.",
    "ex1_vi": "Học sinh học về trò chơi trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 128,
    "word": "friendly",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/frˈɛndli/",
    "meaning": "thân thiện",
    "ex1": "This music activity is friendly for students and listeners.",
    "ex1_vi": "Hoạt động âm nhạc này thân thiện đối với học sinh và người nghe."
  },
  {
    "id": 129,
    "word": "family",
    "type": "noun",
    "cat": "n",
    "phonetic": "/fˈæmʌli/",
    "meaning": "gia đình",
    "ex1": "Students learn about family during regular music lessons.",
    "ex1_vi": "Học sinh học về gia đình trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 130,
    "word": "members",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛmbɝz/",
    "meaning": "thành viên",
    "ex1": "Students learn about members during regular music lessons.",
    "ex1_vi": "Học sinh học về thành viên trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 131,
    "word": "friends",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈɛndz/",
    "meaning": "bạn bè",
    "ex1": "Students learn about friends during regular music lessons.",
    "ex1_vi": "Học sinh học về bạn bè trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 132,
    "word": "cities",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˈɪtiz/",
    "meaning": "thành phố",
    "ex1": "Students learn about cities during regular music lessons.",
    "ex1_vi": "Học sinh học về thành phố trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 133,
    "word": "organize",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˈɔrɡʌnˌaɪz/",
    "meaning": "tổ chức",
    "ex1": "Students can organize during regular music lessons at school.",
    "ex1_vi": "Học sinh có thể tổ chức trong các giờ học âm nhạc thường xuyên ở trường."
  },
  {
    "id": 134,
    "word": "welcome",
    "type": "verb",
    "cat": "v",
    "phonetic": "/wˈɛlkʌm/",
    "meaning": "chào đón",
    "ex1": "Students can welcome during regular music lessons at school.",
    "ex1_vi": "Học sinh có thể chào đón trong các giờ học âm nhạc thường xuyên ở trường."
  },
  {
    "id": 135,
    "word": "local",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈoʊkʌl/",
    "meaning": "địa phương",
    "ex1": "This music activity is local for students and listeners.",
    "ex1_vi": "Hoạt động âm nhạc này địa phương đối với học sinh và người nghe."
  },
  {
    "id": 136,
    "word": "international",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌɪntɝnˈæʃʌnʌl/",
    "meaning": "quốc tế",
    "ex1": "This music activity is international for students and listeners.",
    "ex1_vi": "Hoạt động âm nhạc này quốc tế đối với học sinh và người nghe."
  },
  {
    "id": 137,
    "word": "weekend",
    "type": "noun",
    "cat": "n",
    "phonetic": "/wˈikˌɛnd/",
    "meaning": "cuối tuần",
    "ex1": "Last weekend, a famous festival attracted thousands of visitors from nearby towns.",
    "ex1_vi": "Cuối tuần trước, một lễ hội nổi tiếng thu hút hàng nghìn du khách từ các thị trấn lân cận."
  },
  {
    "id": 138,
    "word": "festival",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/fˈɛstʌvʌl/",
    "meaning": "lễ hội",
    "ex1": "Students discuss festival during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về lễ hội trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 139,
    "word": "attracted",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ʌtrˈæktɪd/",
    "meaning": "đã thu hút",
    "ex1": "Students discuss attracted during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về đã thu hút trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 140,
    "word": "thousands",
    "type": "noun",
    "cat": "n",
    "phonetic": "/θˈaʊzʌndz/",
    "meaning": "hàng nghìn",
    "ex1": "Students discuss thousands during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về hàng nghìn trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 141,
    "word": "nearby",
    "type": "adverb/adjective",
    "cat": "adv",
    "phonetic": "/nˈɪrbˈaɪ/",
    "meaning": "gần đó",
    "ex1": "Students discuss nearby during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về gần đó trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 142,
    "word": "towns",
    "type": "noun",
    "cat": "n",
    "phonetic": "/tˈaʊnz/",
    "meaning": "thị trấn",
    "ex1": "Students discuss towns during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về thị trấn trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 143,
    "word": "colorful",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/kˈʌlɝfʌl/",
    "meaning": "nhiều màu sắc",
    "ex1": "This music activity is colorful for students and listeners.",
    "ex1_vi": "Hoạt động âm nhạc này nhiều màu sắc đối với học sinh và người nghe."
  },
  {
    "id": 144,
    "word": "everyone",
    "type": "pronoun",
    "cat": "n",
    "phonetic": "/ˈɛvriwˌʌn/",
    "meaning": "mọi người",
    "ex1": "Students learn about everyone during regular music lessons.",
    "ex1_vi": "Học sinh học về mọi người trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 145,
    "word": "enjoyed",
    "type": "verb",
    "cat": "v",
    "phonetic": "/ˌɛndʒˈɔɪd/",
    "meaning": "đã thưởng thức",
    "ex1": "Students enjoyed during a successful school music event.",
    "ex1_vi": "Học sinh đã thưởng thức trong một sự kiện âm nhạc thành công ở trường."
  },
  {
    "id": 146,
    "word": "lively",
    "type": "adverb",
    "cat": "adv",
    "phonetic": "/lˈaɪvli/",
    "meaning": "sôi động",
    "ex1": "Students lively practice music during their weekly lessons.",
    "ex1_vi": "Học sinh sôi động luyện tập âm nhạc trong các giờ học hằng tuần."
  },
  {
    "id": 147,
    "word": "atmosphere",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈætmʌsfˌɪr/",
    "meaning": "bầu không khí",
    "ex1": "Students learn about atmosphere during regular music lessons.",
    "ex1_vi": "Học sinh học về bầu không khí trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 148,
    "word": "throughout",
    "type": "preposition/adverb",
    "cat": "adv",
    "phonetic": "/θruˈaʊt/",
    "meaning": "suốt",
    "ex1": "Students use throughout naturally when talking about music activities.",
    "ex1_vi": "Học sinh dùng “throughout” tự nhiên khi nói về các hoạt động âm nhạc."
  },
  {
    "id": 149,
    "word": "evening",
    "type": "noun",
    "cat": "n",
    "phonetic": "/ˈivnɪŋ/",
    "meaning": "buổi tối",
    "ex1": "Students learn about evening during regular music lessons.",
    "ex1_vi": "Học sinh học về buổi tối trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 150,
    "word": "held",
    "type": "verb",
    "cat": "v",
    "phonetic": "/hˈɛld/",
    "meaning": "được tổ chức",
    "ex1": "More music festivals will be held in different countries next year.",
    "ex1_vi": "Nhiều lễ hội âm nhạc hơn sẽ được tổ chức ở các quốc gia khác nhau vào năm tới."
  },
  {
    "id": 151,
    "word": "countries",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌntriz/",
    "meaning": "quốc gia",
    "ex1": "More music festivals will be held in different countries next year.",
    "ex1_vi": "Nhiều lễ hội âm nhạc hơn sẽ được tổ chức ở các quốc gia khác nhau vào năm tới."
  },
  {
    "id": 152,
    "word": "next",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/nˈɛkst/",
    "meaning": "tiếp theo",
    "ex1": "Students discuss next during useful music activities at school.",
    "ex1_vi": "Học sinh thảo luận về tiếp theo trong các hoạt động âm nhạc hữu ích ở trường."
  },
  {
    "id": 153,
    "word": "larger",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/lˈɑrdʒɝ/",
    "meaning": "lớn hơn",
    "ex1": "They will introduce new artists and different music styles to larger audiences.",
    "ex1_vi": "Chúng sẽ giới thiệu nghệ sĩ mới và các phong cách âm nhạc khác nhau tới lượng khán giả lớn hơn."
  },
  {
    "id": 154,
    "word": "culture",
    "type": "noun",
    "cat": "n",
    "phonetic": "/kˈʌltʃɝ/",
    "meaning": "văn hóa",
    "ex1": "Students learn about culture during regular music lessons.",
    "ex1_vi": "Học sinh học về văn hóa trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 155,
    "word": "build",
    "type": "verb",
    "cat": "v",
    "phonetic": "/bˈɪld/",
    "meaning": "xây dựng",
    "ex1": "Students can build during regular music lessons at school.",
    "ex1_vi": "Học sinh có thể xây dựng trong các giờ học âm nhạc thường xuyên ở trường."
  },
  {
    "id": 156,
    "word": "friendships",
    "type": "noun",
    "cat": "n",
    "phonetic": "/frˈɛndʃɪps/",
    "meaning": "tình bạn",
    "ex1": "Students learn about friendships during regular music lessons.",
    "ex1_vi": "Học sinh học về tình bạn trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 157,
    "word": "unforgettable",
    "type": "adjective",
    "cat": "adj",
    "phonetic": "/ˌʌnfərˈɡɛtəbəl/",
    "meaning": "khó quên",
    "ex1": "This music activity is unforgettable for students and listeners.",
    "ex1_vi": "Hoạt động âm nhạc này khó quên đối với học sinh và người nghe."
  },
  {
    "id": 158,
    "word": "memories",
    "type": "noun",
    "cat": "n",
    "phonetic": "/mˈɛmɝiz/",
    "meaning": "kỷ niệm",
    "ex1": "Students learn about memories during regular music lessons.",
    "ex1_vi": "Học sinh học về kỷ niệm trong các giờ học âm nhạc thường xuyên."
  },
  {
    "id": 159,
    "word": "celebration",
    "type": "noun",
    "cat": "n",
    "phonetic": "/sˌɛlʌbrˈeɪʃʌn/",
    "meaning": "lễ kỷ niệm",
    "ex1": "Students learn about celebration during regular music lessons.",
    "ex1_vi": "Học sinh học về lễ kỷ niệm trong các giờ học âm nhạc thường xuyên."
  }
];

const newReadingVocabOrder = [
  "pop",
  "music",
  "one",
  "most",
  "popular",
  "styles",
  "today",
  "has",
  "simple",
  "lyrics",
  "interesting",
  "melodies",
  "and",
  "easy",
  "rhythms",
  "many",
  "people",
  "enjoy",
  "listening",
  "songs",
  "home",
  "travel",
  "or",
  "while",
  "exercising",
  "every",
  "day",
  "famous",
  "singers",
  "release",
  "new",
  "year",
  "last",
  "summer",
  "several",
  "became",
  "television",
  "online",
  "platforms",
  "learned",
  "quickly",
  "sang",
  "together",
  "parties",
  "school",
  "activities",
  "brought",
  "happiness",
  "listeners",
  "everywhere",
  "will",
  "continue",
  "grow",
  "future",
  "create",
  "fresh",
  "different",
  "audiences",
  "modern",
  "technology",
  "help",
  "artists",
  "share",
  "around",
  "world",
  "more",
  "easily",
  "classical",
  "long",
  "history",
  "peaceful",
  "sound",
  "because",
  "helps",
  "relax",
  "think",
  "clearly",
  "orchestras",
  "perform",
  "large",
  "concert",
  "halls",
  "musicians",
  "spend",
  "years",
  "learning",
  "difficult",
  "pieces",
  "practice",
  "improve",
  "skills",
  "beautiful",
  "concerts",
  "students",
  "attended",
  "performance",
  "teachers",
  "listened",
  "carefully",
  "about",
  "musical",
  "instruments",
  "event",
  "remain",
  "important",
  "generations",
  "schools",
  "introduce",
  "composers",
  "wonderful",
  "performances",
  "teaches",
  "patience",
  "discipline",
  "appreciation",
  "artistic",
  "traditions",
  "festivals",
  "exciting",
  "events",
  "ages",
  "bands",
  "stages",
  "celebrations",
  "visitors",
  "food",
  "games",
  "friendly",
  "family",
  "members",
  "friends",
  "cities",
  "organize",
  "welcome",
  "local",
  "international",
  "weekend",
  "festival",
  "attracted",
  "thousands",
  "nearby",
  "towns",
  "colorful",
  "everyone",
  "enjoyed",
  "lively",
  "atmosphere",
  "throughout",
  "evening",
  "held",
  "countries",
  "next",
  "larger",
  "culture",
  "build",
  "friendships",
  "unforgettable",
  "memories",
  "celebration"
];
